### ISSUE TITLE
Use GNU Unifont at 16px

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1031]
Paul Hardy of GNU Unifont fame writes,

<blockquote>
<p>The open area inside the rectangle where Fontforge draws sample glyphs is exactly 16 pixels tall, the same height as Unifont glyphs.

<p>Is there any chance of tweaking Fontforge for the next release so that if Unifont is installed the Fotnforge sample glyphs are rendered as 16 pixels tall, and either 8 or 16 pixels wide?  The glyphs would look razor-sharp then so their quality would be greatly improved.  
</blockquote>

 DONE :)

<blockquote>
Most of the glyphs except some CJK have a margin of blank pixels on top and bottom, so most wouldn't touch the rectangle top and bottom boundaries.  You can scroll through the CJK ideographs in Fontforge to get a better idea of the blurring consequences.
<p>
Installing the TrueType version of Unifont, then using Fontforge to look at the PCF (or BDF) version gives the best indication, because with a bitmap font Fontforge will give an anti-aliased, pixel-by-pixel rendering.
<p>
Along those lines, would you like me to make an SBIT version of Unifont part of future TrueTupe packages for GNU/Linux, along with the non-SBIT version?  I'd have to name it something like "Unifont_SBIT".  Then Fontforge could use that font if it's installed; if not, it could use "Unifont" if that's installed, and if not then fall back to some system font.
<p>
With Unifont being 16 pixels tall, and the rectangular sample box having 16 rows for display, it does seem a match made in heaven. :-)
 
</blockquote>

**Comment by ytrezq** [comment]
test

**Comment by ytrezq** [comment]
I did the same with a monospaced version of ɢɴᴜ Unifont ᴄꜱᴜʀ and it changed nothing.

[bdf file uploaded as ᴘɴɢ](https://cloud.githubusercontent.com/assets/3824869/9186355/15c0f616-3fc4-11e5-976c-4067f8c2346d.png)

**Comment by yg8ijvjvjv** [comment]
I would like to use a competitor font instead, where do I change it? I have uninstalled Unifont and would like to have FontForge display in Kissinger rather than the default "use Tahoma and if not available spam .notdef" behavior that requires users to make a font fake if they uninstalled Tahoma.

**Comment by yg8ijvjvjv** [comment]
Why is it bite-sized I-bug? The label should be changed to 16-sized UI-bug

**Comment by yg8ijvjvjv** [comment]
If the labels are spam, remove the labels.

**Comment by yg8ijvjvjv** [comment]
Are you trying to cause a paradox with the labels?

**Comment by yg8ijvjvjv** [comment]
Please stop censoring and explain what do you mean by the tags and how to replace the font.
