### ISSUE TITLE
Anchor points & UFO files

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#1046]
Scenario = fontforge opens a UFO created by e.g. Glyphs or Robofont.
The UFO has 'anchor points' used in the positioning of diacritic marks.

When Fontforge exports either a single Glif back to the original UFO or generates a whole new UFO, the anchor points are converted to points that are useless as anchor points in other font software that use UFO's (e.g. Glyphs, robofont, prepolator, superpolator, etc)

I have made a gist of a fontforge generated glif and the original robofont created glif @https://gist.github.com/vernnobile/7952956

As far as i can see fontforge strips away the 'name' tag of anchor points.

So the original anchor is

```
 <contour>
      <point x="509" y="0" type="move" name="bot"/>
    </contour>
```

but fontforge re-writes it as this;

```
<contour>
      <point x="509" y="0" type="move" smooth="yes"/>
    </contour>
```

**Comment by Bala93** [comment]
Hi guys,
I am currently developing a font. I was using the mark-base attachment(GPOS). And when i view it in the software, the marks are placed above the base. But when i create a .ttf file and install it in the system.The marks are getting shifted. Can you people tell me where i am going wrong ?
