### ISSUE TITLE
About gb12345

### ISSUE THREAD

**Issue by zjzengdongyang** [fontforge/fontforge#1199]
I'm using the fontforge fontforge branch, I enabled GB12345 encoding (/ configure --enabled-gb12345), but in the make, he did not execute make in fontforge-fontforge/plugins, and later in execution make me into fontforge-fontforge/plugins and then return fontforge-fontforge in execution make it a success. And I can not overwrite the master file fontforge branch branch files, and then make?
Maybe I should run ./bootstrap?
Oh，My God? Why not have a installation instructions.
chinese：
我使用fontforge的fontforge分支，我启用GB12345编码（./configure --enabled-gb12345），但在make时，他没有在fontforge-fontforge/plugins里执行make，后来我进入fontforge-fontforge/plugins里执行make，再返回fontforge-fontforge里执行make才成功。还有我可以不可以把master分支的文件覆盖fontforge分支的文件，然后进行make？
或许我应该运行 ./bootstrap?
我的天啊？为什么没有一个安装说明。

**Comment by skef** [comment]
gb12345 was removed.
