### ISSUE TITLE
Perhaps reimplement or add dialogs using pygtk or pyqt

### ISSUE THREAD

**Issue by monkeyiq** [fontforge/fontforge#1201]
If the python scripting was made a requirement then some of the dialogs could be recreated using python as the driver. The recent integration of the pygtk main loop with the fontforge one allows both UI to run at once. So a possible step would be, for example, to replace the GetInfo dialog with something written in python. The UI for that would then use pygtk and could be themed using gtk2, the layout code would not be as complicated etc.

New dialogs for parts of the functionality offered by Element/Font Info could also be created. For example to slipstream common processes like creating ligature substitutions. Using python for the UI layout should maybe help to allow designers to do layout etc for these dialogs too?

I'll probably do some UI mockup for this soon...

**Comment by adrientetar** [comment]
> so that HTML5 is one of the toolkits on par with PyGTK and PyQT

It would be good to have a webkit preview window or something when designing fonts for the screen, [as Hoefler does](http://www.typography.com/cloud/the-fonts/index.php#ssm-design).

**Comment by davelab6** [comment]
This is already done, as part of collab mode

**Comment by skef** [comment]
This general issue is discussed in other contexts.
