### ISSUE TITLE
fontforge-cygwin_2014_01_04: ExpandStroke() crashes in presence of sharp (40° or such) angles, or nearby segments

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#1228]
Example SFD files are in https://gist.github.com/ilyaza/9108327

Run with
  fontforge -lang=ff -c "Open($1); SelectAll(); ExpandStroke(64,1,1,0,1); " unifont-mono-xa996.sfd
(likewise for the second file).  Gives a stack dump (non-debugging version here, so cannot decipher it.)

(Note that the second file, unifont-mono-xaa1c-aa1d.sfd, contains two glyphs.  Each one of them works OK separately from the other one.  Breaking a stroke into several ones at sharp angles works around the issue in the first file; in the second one, I
needed to break the stroke into straight segments to make the script finish normally.

[This is not a new regression; it also crashes with 2012 build of fontforge.]

Thanks,
Ilya

**Comment by skef** [comment]
As of this evening this is fixed in the `stroke` branch.
