### ISSUE TITLE
Excess verbosity in fontforge-cygwin_2014_01_04:

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#1231]
During
     Open($1);  Generate($2);
I see
     SPLFirstVisitorFoundSoughtXY() 96.100000 96.000000 147.000000
(repeated ≈28000 times, with different numbers).  The font has about 55000 glyphs and is about 180MB large, so I think I cannot make a GIST out of it.

The workflow is as follows:
  • Several files with open and closed strokes are run through ExpandStroke() + cleanup (no such messages here);
  • The results are MergeFonts()ed and Save()d (messages here);
  • The Save()d file is converted to TTF (messages here again).

**Comment by sergey-s-betke** [comment]
I tested with latest fontforge build for windows. Project - https://github.com/Metrolog/Font.GOST2.304-81. Result - the same. What does it mean?

**Comment by sergey-s-betke** [comment]
@adrientetar, may be comment line 2160 in `splinefont.c`?

    printf("SPLFirstVisitorFoundSoughtXY() %f %f %f\n", d->x, spline->from->me.x, spline->to->me.x );

**Comment by sergey-s-betke** [comment]
@adrientetar , on actual release result the same: https://ci.appveyor.com/project/sergey-s-betke/font-gost2-304-81
On appveyor build server for each build I get latest fontforge release from chocolatey repository...

**Comment by sergey-s-betke** [comment]
@adrientetar, please, review and merge pull request #2744. Thank You!
