### ISSUE TITLE
Eliminate shared libraries

### ISSUE THREAD

**Issue by mskala** [fontforge/fontforge#1253]
While we're talking about removing cruft and streamlining the build system...

FontForge currently consists of several separate pieces that are dynamically linked at run time:
- "libgunicode," which encapsulates knowledge of the Unicode character set (possibly accompanied by one of two third-party libraries which do the same thing)
- "libgutils," which is a collection of miscellaneous routines
- "libgioftp," which is a wrapper for sockets
- "libgdraw," which is a buggy nonstandard GUI widget set
- "libfontforge," which edits fonts
- "libfontforgeexe," which is a GUI for "libfontforge"
- a plugin interface mediated by "libltdl"
- "fontforge," which is a tiny executable wrapper that loads everything else

These appear to be in separate shared libraries just so that people can link to them separately from other code.  However, _nobody really does that_.  Nobody uses libgunicode except FontForge, because the two competing libraries (which FontForge itself also recommends and prefers) are better.  Nobody uses libgutils except FontForge because glib and various other third-party libraries do the same thing better.  Same with libgioftp and libgdraw.  Someone might well want to do font editing other than through the FontForge GUI, so there is a legitimate reason to link to libfontforge... but anyone who tries will be frustrated because libfontforge and libfontforgeexe have so many cross-dependencies, and libfontforge is so tied to libfontforgeexe's GUI-inspired data structures, that it's not really possible to use libfontforge other than as part of FontForge.  Nobody wants to embed the entire FontForge GUI in another program, which it what libfontforgeexe might be useful for, because it will stomp all over their existing, more standard, GUI libraries and they might as well just run FontForge and be done with it.  And in all the years that the plugin interface has existed, as far as I know there has been one plugin written.  People who want to add features to FontForge usually join us here and get the features added all the way into the mainline instead of as plugins.  So the shared libraries exist just to support people who are doing things that nobody actually wants to do!

On the other hand, the existing complicated shared library structure has a very high, and ongoing, cost.  Is it worth paying that to support a non-existent user base? Structuring FontForge as a collection of shared libraries makes builds slower; it adds extra dependencies on the tools needed to maintain the shared libraries; it makes things especially hard for new users trying to build from a version control checkout; it drastically increases the complexity of FontForge's Autotools configuration, increasing the chance the Autotools configuration will be broken at any given moment; and it makes compatibility with non-Linux systems (especially Windows, which today is a very large fraction of the user base) much harder.

My suggestion:  stop wasting developer resources on maintaining this mess, and just don't have shared libraries, plugins, or libtool, anymore.  The existing Makefile.am definitions for building *.la libraries can be switched to build non-installed *.a libraries easily; and once that's done, it becomes possible to stop using libtool.  Removing the plugin interface is a little more complicated, especially if one wants to keep the existing GB12345 plugin, but that's a one-time cost stacked up against the ongoing costs of maintaining the shared library configuration.

I've done this on a local copy of FontForge, and it works quite well.  I will share my code soon, but my modifications are part of a project that also includes other major changes; I won't be able to just produce a clean pull request that could apply directly to mainline FontForge.

**Comment by jtanx** [comment]
This is basically done.
