### ISSUE TITLE
Add 'View, Hide Unused Cells' to Font View

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#130]
Deron suggested:

Add a "Hide unused cell rows" to the Font View window's View menu. 

This is similar to 'Encoding, Compact' but only affects the view and not the internals of the font at all.

It will also not change the order of the displayed glyphs, or cause any columns to shift around; and it would only hide completely empty rows in the view, and where they are hidden, show a thicker cell border line, to indicate that one or more rows are hidden.

**Comment by Roy-Orbison** [comment]
Anyone doing this? Or is there some other way to jump to the next/previous defined glyph that I don't know? The scroll-fest is not fun.

**Comment by Roy-Orbison** [comment]
😛 Ctrl + Alt + ] (and [)

**Comment by ctrlcctrlv** [comment]
I don't see why you can't just use Encoding -> Compact _temporarily_, and change it back to your target encoding when done.

**Comment by epilys** [comment]
`Encoding -> Compact` is indeed the solution, but I think its name could be improved for discoverability. For example, I found out about it by searching for 'hide unused glyphs' and arriving here. Perhaps rename it to 'Compact (hide unused glyphs)'?

**Comment by rgpublic** [comment]
I would have never ever found this if it wasn't for this issue. I would have expected this under "View".

**Comment by anasofiapaixao** [comment]
> I would have never ever found this if it wasn't for this issue. I would have expected this under "View".

I can add that this is the number one google search result for 'fontforge hide empty glyphs' which autocompleted for me because it's apparently a common enough search, and it's also how I found this issue, as I couldn't find it under 'View'.
