### ISSUE TITLE
TrueType Instruction Debugger not loading

### ISSUE THREAD

**Issue by anthrotype** [fontforge/fontforge#1326]
I have compiled the latest daily snapshot (17-04-2014) from the git repo, and I have set the flag to enable the freetype debugger, by specifying the freetype2 source directory (version 2.5.3).
However, when I try to run 'Debug...', after I set the size of the rasterization and click 'OK', then nothing shows up... 
Is anybody else having the same issue?

**Comment by skef** [comment]
The build process has changed drastically since this was filed. I've recently been compiling with the debugger for testing purposes and its working.  

Closing this -- update or refile if you're still interested and still having the problem.
