### ISSUE TITLE
Settle on 1 unicode name library and make it a requirement

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1341]
It seems from https://github.com/fontforge/fontforge/issues/1322 that we get variant crash/no crash based on the availability of different unicode libraries. This is a poor situation to be in. 

Therefore I propose that as part of @frank-trampe 's upcoming stable release, we make @JoesCat 's unicode library a mandatory dependency, so we don't get into this situation again.

**Comment by skef** [comment]
This has been argued back and forth and the stance continues to be adjusted over time.
