### ISSUE TITLE
Installing fontforge for use in metapolator

### ISSUE THREAD

**Issue by javburg** [fontforge/fontforge#1366]
Hi,
I'm trying to install components to run metapolator, but I'm having trouble with installing fontforge.
I'm trying to install with the following command:

$ brew install fontforge --with-x --HEAD;

But, this is the response I get:

==> Cloning https://github.com/fontforge/fontforge.git
Updating /Library/Caches/Homebrew/fontforge--git
==> ./autogen.sh
Failed to execute: ./autogen.sh

So I went to the fontforge--git directory in Terminal and entered:

$ ./bootstrap (which ran without a problem) and,
$ ./configure

But now I get stuck on this:
...
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for PYTHON... no
configure: error: Package requirements (python-"2.7") were not met:

No package 'python-2.7' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PYTHON_CFLAGS
and PYTHON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

How can I solve this?

**Comment by groversachin** [comment]
install python27-devel. this solved the issue.
