### ISSUE TITLE
Run Valgrind on Travis

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#1380]
[Neovim](https://github.com/neovim/neovim) has this functionality set up through a Shell script.

neovim/neovim@6c96e42e2c18bd6ae685b5a41c69b03954aa0375
neovim/neovim@a80a68c92747144f0094368ae01c0cb23095433c

**Comment by skef** [comment]
We're already bombarded with code-correctness assessments we don't pay enough attention to.
