### ISSUE TITLE
Terrible slowdown when zooming close while "fill" is on.

### ISSUE THREAD

**Issue by Gwenouille** [fontforge/fontforge#1391]
Windows 7 64, build from the 31st of May, sourceforge.

Everything is in the title: While "fill" is on, zooming heavily to a close-up is sluggish to say the least. If you zoom a lot at once (with the mousewheel), you crash.
No problems when fill is off.

I shall make a video to illustrate my point during the next days if i find the time.

Can anyone confirm ?

**Comment by jtanx** [comment]
@Gwenouille, it turns out the fix to the crashing/slowdown was surprisingly simple. The next release of FontForge should fix both any slowdown and crashes experienced while zooming with fill turned on.
