### ISSUE TITLE
compile failed with --enable-gb12345

### ISSUE THREAD

**Issue by copyliu** [fontforge/fontforge#1394]
Making all in fontforge
make[2]: Entering directory '/cygdrive/d/src/fontforge/fontforge'
make[2]: **\* No rule to make target '../plugins/gb12345.la', needed by 'libfontforge.la'.  Stop.
make[2]: Leaving directory '/cygdrive/d/src/fontforge/fontforge'
Makefile:1462: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/d/src/fontforge'
Makefile:1298: recipe for target 'all' failed
make: **\* [all] Error 2

if run make in plugins directory, it returns
  CCLD     gb12345.la
.libs/gb12345.o: In function `gb12345_LTX_FontForgeInit':
/cygdrive/d/src/fontforge/plugins/gb12345.c:4406: undefined reference to`AddEncoding'
/cygdrive/d/src/fontforge/plugins/gb12345.c:4407: undefined reference to `ui_interface'
collect2: error: ld returned 1 exit status
Makefile:1182: recipe for target 'gb12345.la' failed
make: **\* [gb12345.la] Error 1

**Comment by doughdemon** [comment]
I get the second error when trying to compile with the libtool replacement slibtool (http://git.midipix.org/cgit.cgi/slibtool/).

I think that the problem is that `-Wl,--no-undefined` gets passed to libtool although the plugin depends on symbols in the main executable.

**Comment by tessus** [comment]
I have to say that the build process on macOS is somewhat broken.

- `./configure` ignores the `PKG_CONFIG_PATH` and unless you set CFLAGS and LD_FLAGS explicitly, it abends.
- no matter what `--enable-gb12345` leads to:

```
 make[2]: *** No rule to make target `../plugins/gb12345.la', needed by `libfontforge.la'.  Stop.
```

- include files are missing from several `.c` files, which results in compile errors `error: use of undeclared identifier`

Seriously, have you guys even compiled the code, before releasing it as a dist tarball? If so, how? It is clearly broken.

**Comment by frank-trampe** [comment]
@tessus, we build the code for each release, but only as far as documented in the [README](https://github.com/fontforge/fontforge/blob/master/osx/README). We develop on more traditional POSIX environments, and working in Macintosh land has become progressively more difficult due to changes in the operating system and in Homebrew (which we can no longer use). We're happy to review pull requests to improve the situation.

**Comment by tessus** [comment]
@frank-trampe I downloaded https://github.com/fontforge/fontforge/releases/download/20170731/FontForge-20170730-Mac.dmg but get the following message:

![screen shot 2018-04-20 at 19 00 31](https://user-images.githubusercontent.com/223439/39077071-32202726-44cd-11e8-8580-74d76b03df4a.png)

Anyways, after changing a few things in the code, I was able to compile fontforge with:

`PKG_CONFIG_PATH=/opt/local/lib/pkgconfig/ PYTHON=/opt/local/bin/python2.7 PYTHON_CFLAGS="-I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes" PYTHON_LIBS="-L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation" CFLAGS=-I/opt/local/include LD_FLAGS=-L/opt/local/lib ./configure --prefix=/opt/local --mandir=/opt/local/share/man --x-includes=/opt/local/include --x-libraries=/opt/local/lib --disable-silent-rules --disable-dependency-tracking`

However, the app in `/opt/local/share/fontforge/osx` does not start. No error, no crash. Nothing.

**Comment by tessus** [comment]
Also, when I try to run the command line tool:

```
$ ./fontforge -v
dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Users/kct/data/tmp/ff-install/opt/local/bin/./fontforge
  Reason: image not found
Abort trap: 6
```

**Comment by jtanx** [comment]
```
export LD_LIBRARY_PATH=/opt/local/lib
```

**Comment by tessus** [comment]
nope. the problem is that I did the configure with `--prefix=/opt/local`, but I installed it as `make DESTDIR=~/tmp/ff-install install`

**Comment by jtanx** [comment]
ok

**Comment by tessus** [comment]
this is very unusual. the rpath seems to be hardcoded

**Comment by jtanx** [comment]
Yeah because it's mac

**Comment by tessus** [comment]
still, it doesn't make sense.

1) you can set it relative to the binary
2) and export LD_LIBRARY_PATH=/Users/kct/data/tmp/ff-install/opt/local/lib/ should work too

**Comment by jtanx** [comment]
In my experience, 1. (under autotools at least) seemingly can't be done without surgery on the dlls with `otool` to change it to be relative, and I bet 2. doesn't work because of 1., since the specified rpath is absolute.

**Comment by tessus** [comment]
> Also this is hijacking the gb12345 issue.

You're right (but only my comments about the GUI and I will open another ticket for that), but I still receive the following error:

```
make[2]: *** No rule to make target `../plugins/gb12345.la', needed by `libfontforge.la'.  Stop.
```

And this is exactly on topic.

So how do I fix this?

**Comment by jtanx** [comment]
Considering the issue is still open I'd expect that that build option is evidently still broken. Just compile without the gb12345 option, it's a niche option that hasn't worked for years.

Patches welcome to fix.

**Comment by tessus** [comment]
Do you mean the option hasn't worked for years or the gb12345 code?

**Comment by jtanx** [comment]
Please read the comments above. The build system had been incorrectly set up, so the gb1345 option doesn't work. And yes this particular option has been broken for years, I'd say at least since 2012.

**Comment by tessus** [comment]
I've read the comments above but I think you misunderstood my last question.

I was asking, if fontforge wouldn't work correctly, if you were able to get it to compile and link with the gb12345 libs manually.
If the entire gb12345 subsystem is broken, there's no need to fix the configure option or try to get it to compile manually.

**Comment by jtanx** [comment]
Hmmm not too sure, you'll have to try and see I guess.

Granted, gb12345 was done as a plugin (and I think it's the only plugin) - that whole plugin system may very well be broken too.

**Comment by tessus** [comment]
Haha, ok, I see. You know, I wanted to get a feel for what patches are needed. Just for `configure`, or the glue code in fontforge that accesses gb12345 functions, the gb12345 code itself, or the whole shebang. ;-)
It looks like it's the entire gb12345 component plus the plugin framework that is broken. :-(

In this case I suggest to remove this part completely. If none of it is working, it makes no sense to keep broken and dead code.

**Comment by skef** [comment]
gb12345 was removed.
