### ISSUE TITLE
Check your compiler warnings please.

### ISSUE THREAD

**Issue by JoesCat** [fontforge/fontforge#1403]
Comparing TAG-point 20140101 to today's HEAD, there's a lot more warnings, maybe 4x as many, and the warnings describe some fairly serious faults in some cases, like passing ints to pointers, and a variety of mismatched parameters.

If you are developing code, please watch your warnings for the code you create because I believe a fair number of problems getting reported are due to these problems.

**Comment by skef** [comment]
This doesn't do any good down the list at 1403
