### ISSUE TITLE
fontforge-cygwin_2012_08_02: Message: Some fragments did not join in uniA9C3

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#1424]
I was not paying attention before, but today I noticed the message

```
Internal Error:
Some fragments did not join in uniA9C3
```

Googling, I see that it is mentioned in a couple of bug reports of dependent packages, but not in FontForge mailing lists themselves.

If needed, I may try to provide a minimized example.

**Comment by eosrei** [comment]
*Copy/paste from #2631. Please re-open.*

Steps to reproduce. The attached SVG (renamed to .txt to make github happy) and code below causes the error: `Internal Error: Some fragments did not join`

```py
import fontforge

font = fontforge.font()
glyph = font.createChar(0x000d, 'CR')
glyph.importOutlines('fragments_did_not_join.svg')
```
Download: [fragments_did_not_join.svg.txt](https://github.com/fontforge/fontforge/files/139521/fragments_did_not_join.svg.txt)

**Comment by skef** [comment]
As of my testing this evening this is fixed in the `stroke` branch.
