### ISSUE TITLE
removeOverlaps() geometry isn't working well

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#1474]
- [x] #402, 
- [x] #473, 
- [x] #488,
- [x] #496, 
- [ ] #1374, 
- [ ] #529, 
- [x] #729,
- [x] #1424 
- [x] #1505 
- [x] #1506 
- [x] #1507
- [ ] http://fontforge.10959.n7.nabble.com/fontforge-devel-Where-is-the-changeWeight-code-td14573.html

Anything else?

**Comment by adrientetar** [comment]
Python removeOverlap() does not work for me.

**Comment by frank-trampe** [comment]
@adrientetar, can you be more specific?

**Comment by adrientetar** [comment]
I tried to build [Crimson Roman.sfd](https://github.com/skosch/Crimson) with the script I put in #2090, and in the generated fonts I see points added at intersections but no actual removal, if you look e.g. at the paragraph mark.

**Comment by frank-trampe** [comment]
Does the overlap removal succeed if run via native scripting or via the graphical interface?

**Comment by adrientetar** [comment]
Actually it didn't, but I found why: each of the two components had different path directions. Okay this is solved unless working with different path directions is in the scope of the project.

**Comment by frank-trampe** [comment]
Excellent. We only have one open sub-bug for this issue, and I think that it is fixed (but without confirmation).

**Comment by skef** [comment]
This issue seems to have represented #1374 for 4.5 or so years. That issue isn't solved but at this point it can represent itself -- closing.
