### ISSUE TITLE
Windows 7 64 bit MinGW Error - Attempt to output XXX into a 16-bit field.

### ISSUE THREAD

**Issue by jatmew** [fontforge/fontforge#1479]
I am trying to use fontforge as library in another program I am using (pdf2htmlEx). I am getting a ton of 

```
Internal Error: Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful.
```

errors followed by 

```
Internal Error: File Offset wrong for ttf table (name-data), -1 expected 174
```

Googling this issue I haven't really found any answers other than maybe there is an issue with Windows 7 64 bit running fontforge. Has anyone been able to use fontforge on Windows 7 64 bit system or know of steps to resolve this issue?

**Comment by skef** [comment]
Closing.
