### ISSUE TITLE
Add Element->Style commands to Python methods

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#149]
http://fontforge.org/elementmenu.html#Embolden isn't available via Python, but it should be

**Comment by skef** [comment]
This is misleading. ChangeWeight, italicize, and SmallCaps are there. Even the oft-lamented Change Glyph is actually "there", although its called `genericGlyphChange` and you have to use the Selection interface. Only the stuff like Outline and Shadow is missing.

**Comment by ctrlcctrlv** [comment]
Heh, outline and shadow fonts. Those were the days.

**Comment by skef** [comment]
We're probably not going to expose shadow, outline, inline etc. via python. Closing
