### ISSUE TITLE
Add WOFF to the native file formats

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#1504]
Blocked on #926. The scope of this issue is (both items are probably related):

- File explorer association
- Displaying WOFF files by default on the Open dialog (right now you have to click on Show all files... to see them).

**Comment by fred-wang** [comment]
@adrientetar  Just checking the code, it seems that woff extension is already considered in the "OpenType" section:
https://github.com/fontforge/fontforge/blob/master/fontforgeexe/openfontdlg.c#L138

And indeed when I select "OpenType" in the open dialog, woff files are displayed.
