### ISSUE TITLE
Windows: file chooser is sloppy when changing drive

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#1586]
- [x] Under Windows in the file chooser, when typing a drive letter e.g. `C:` then clicking Enter, FontForge crashes.
- [ ] Related issue: when opening FontForge from my external drive, I can't go to the root of the drive by clicking on "Parent directory" &ndash; it says "Method not allowed Not a directory". This is problematic.

cc @jtanx

**Comment by davelab6** [comment]
@adrientetar how is the 2nd task for this issue now?

**Comment by adrientetar** [comment]
Done.
