### ISSUE TITLE
PPA: package zeromq and czmq (newly) to support FontForge

### ISSUE THREAD

**Issue by monkeyiq** [fontforge/fontforge#1594]
Package these to save time each Travis CI run, so it can compile fontforge itself quicker and thus find regressions or compile errors quicker:
- [ ] zeromq
- [ ] czmq
- [ ] freetype
- [ ] Update Travis CI script to use the PPA, https://github.com/fontforge/fontforge/blob/master/.travis.yml#L10

**Comment by davelab6** [comment]
@monkeyiq are you able to build a windows package using @jtanx 's build system with collab?

**Comment by skef** [comment]
collab was removed. Not sure about freetype, refile is there is an issue.
