### ISSUE TITLE
Don't flicker the UI when making the update to send to the server

### ISSUE THREAD

**Issue by monkeyiq** [fontforge/fontforge#1614]
The update that is sent to the server is created by "undoing" the local change and sending the redo to the server. This creates a brief moment where the FontForge that is sending the change reverts to a previous state and then moves back to the current state. Unfortunately that transition is rendered which isn't great for the user.

The render should be temporarily suspended when creating this undo packet to send to the server so that the UI doesn't jump around.

Examples of this flicker are dragging to set the width in the metrics view which is very noticable.

**Comment by skef** [comment]
collab was removed.
