### ISSUE TITLE
File open dialogue issues

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#1640]
- [x] Something's changed recently that's made the file chooser noticeably slower than it was before, especially for folders containing a lot of items. Possibly the new mime type code?
- [x] If you click around enough in the file chooser, then eventually it will crash (long-standing issue)
- [x] The file chooser dialogue is sloooow if there are multiple PDF files in the folder. It seems to be opening/reading them to say in a tooltip which fonts are in the PDF. Don't do that (read them.)
- [ ] Add support for horizontal scrolling, for directories with really long filenames

**Comment by adrientetar** [comment]
@jtanx: Would be cool if FontForge could remember last browsed folder for opening fonts as is the case on Linux, is this feasible?

**Comment by jtanx** [comment]
It may be possible I guess, but I'm a bit short on time right now...
