### ISSUE TITLE
Add Script to remove data not mapped natively in FontForge (Clean SFD)

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#1690]
This task is important for generating clean/normalized output.

The values to be cleared are likely to include
* glif_name (per SplineChar)
* ufo_path (per Layer)
* x_height (per SplineFont)
* cap_height (per SplineFont)
* python_persistent (per SplineChar and per SplineFont)
.

Hopefully, we can eventually add x_height and cap_height as native FontForge values.

**Comment by adrientetar** [comment]
@frank-trampe Is this was "Clear special data" is for?

**Comment by frank-trampe** [comment]
The Python binding? Yes.

**Comment by adrientetar** [comment]
So what's remaining here?

**Comment by frank-trampe** [comment]
It's only accessible in Python right now. I suppose that I need to add a menu option and a native scripting binding.

**Comment by adrientetar** [comment]
@frank-trampe #1951?

**Comment by frank-trampe** [comment]
Oh. I didn't know that we had done that already.

I suppose that it is okay to close this, then.

**Comment by davelab6** [comment]
> and a native scripting binding.
Is that done?

**Comment by adrientetar** [comment]
Yes
