### ISSUE TITLE
Guidelines vanish when fill is enabled

### ISSUE THREAD

**Issue by kelvin13** [fontforge/fontforge#1705]
I'm sorry I'm probably being so annoying but...
If the fill display overrenders stuff that shouldn't show up (open paths) then ig it's trying to balance things out by forgetting to render guidelines?

![screenshot 061](https://cloud.githubusercontent.com/assets/2556986/4102511/7d8d4a00-312f-11e4-90bf-7ac59aae122f.png)
![screenshot 062](https://cloud.githubusercontent.com/assets/2556986/4102512/7f023f4e-312f-11e4-9c0f-09a47bf43e1d.png)

Built from the latest source

**Comment by jtanx** [comment]
Ohhh I see this has been reported again at #2719. Anyway, once #2788 gets merged, this should be fixed. Continue in #2719.
