### ISSUE TITLE
The Python pickler is unstable.

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#1713]
Opening a typeface such as Fira Sans from U. F. O., saving to S . F. D., opening that S. F. D., and saving to another S. F. D. may change the sequence of items in each persistent data store.

**Comment by frank-trampe** [comment]
Okay. I've decided vaguely how I plan to solve this.

I plan to convert the dict into a tuple and to sort by key name and then to use that sorted tuple for generation of the X. M. L.. This incidentally preserves input ordering in lib dictionaries only if the input is sorted, a major improvement from random ordering, but it cannot preserve non-sorted orderings.

I had originally thought that we could store the input data in an ordered tuple, but this would require an abstraction layer in order to provide dictionary-like functionality.

This would be a good time to air relevant preferences and concerns.

**Comment by davelab6** [comment]
I think this should be paused until
https://github.com/unified-font-object/ufo-spec/blob/master/source/xmlnormalization.textile
is settled.

**Comment by skef** [comment]
This may not be a completely satisfying answer but as of Python 3.7 (so March 2018 or so) iterators over standard Python dictionaries return values in insertion order. So this is probably no longer an issue in most of our installations (after the switch to python 3-as-default) and should gradually disappear without intervention.

**Comment by ctrlcctrlv** [comment]
Cool, that answer works for me. Bug closed as fixed in Python.
