### ISSUE TITLE
Increment side bearings does not work as expected

### ISSUE THREAD

**Issue by Kelvinsong** [fontforge/fontforge#1742]
When you run Increment Side Bearings By, it doesn’t increment the side bearings, it just sets the width of the glyph to be whatever you typed into it.

**Comment by frank-trampe** [comment]
@davelab6, why did you unassign me?

**Comment by davelab6** [comment]
I figured this was less important than the mac stuff, but great it was a bitesized fix and is done :)

**Comment by davelab6** [comment]
@Kelvinsong please test :)

**Comment by Kelvinsong** [comment]
It works! Thanks sm!!
