### ISSUE TITLE
Fontforge always seems to open windows on my secondary display

### ISSUE THREAD

**Issue by rrthomas** [fontforge/fontforge#1770]
I have two monitors. I mostly work on the right-hand one, which is configured as my primary. However, Fontforge always opens new windows on the left-hand monitor.

Some parts of the system seem to regard the left-hand monitor as primary, so this is not a total surprise, but it is an inconvenience! No other app I use regularly (Firefox, Emacs, Chrome, gnome-terminal) does this.

This is using an up-to-date git build (as of 06-Oct-2014).

**Comment by skef** [comment]
Most of these two-monitor problems seem to be solved by the gdk implementation.
