### ISSUE TITLE
Use mxe.cc for making Windows builds with Travis?

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1776]
I wonder if http://mxe.cc can be used to make Windows builds with Travis. 

@jtanx is your build system compatible with http://mxe.cc?

**Comment by jtanx** [comment]
Unless we cache/prebuild the mxe toolchain, this is never going to happen, as it would just take way too long to compile all the dependencies required.

**Comment by davelab6** [comment]
Making a Decker image to precompile is possible I think

**Comment by jtanx** [comment]
So I had a closer look at the Docker approach, and there were a few pitfalls:
* Most likely have to pay for AWS hosting to host any custom Docker image
* MXE doesn't provide a target for python, so either compile python ourselves (hard) or skip python scripting support

It'd be much easier to just get appveyor running (#2382), which I did have going at one point.

**Comment by davelab6** [comment]
If AppVeyor does the same thing with easy python, that sounds like a winner! :)
