### ISSUE TITLE
Include binary packages for the latest release on the release page

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1797]
@frank-trampe has uploaded a new src tarball and RPMs to https://github.com/fontforge/fontforge/releases/

Everyone, please check these files and let us know here if there are any critical mistakes.
- [x] @monkeyiq please make a mac build :)
- [x] @jtanx please make a win build :)
- [x] @frank-trampe please make the `.deb` related files
- [x] @frank-trampe please put the deb files in a PPA
- [x] @frank-trampe please put a description of how to install on Ubuntu using the PPA on the release page
- [ ] @frank-trampe please put a description of how to install on Fedora using the repos.fedorapeople.org repo on the [GNU+Linux](http://fontforge.github.io/en-US/downloads/gnulinux/) page 
- [ ] and link to that on the release page

**Comment by skef** [comment]
This happened.
