### ISSUE TITLE
Copy SF release files to here

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#18]

**Comment by skef** [comment]
Send them to the computer history museum.

**Comment by ctrlcctrlv** [comment]
Why what's going on are you shutting down our SF? Where will the mailing list go? Is that just over now? Please explain a little more

**Comment by skef** [comment]
What, no, I'm just closing the issue. Someone seeking 2012-era releases can find them where they are -- they don't need to be copied to github.

**Comment by ctrlcctrlv** [comment]
Oh, OK, I'm sorry, I took your comment very literally as if SourceForge was in imminent danger of closing. No problem about all the issues you're closing, I agree.
