### ISSUE TITLE
2014-10-14 Win7 Crash/confusion in initial Open font dialog

### ISSUE THREAD

**Issue by tshinnic** [fontforge/fontforge#1803]
User can easily crash the latest Windows FF by using Windows file path delimiters.  Other combinations give wildly different results.  Please pardon the number of examples, but I was looking for a pattern without looking at the code:

Starting with initial "Open Font" dialog box, shows "C:\Users\Tom\Documents" as list of 4 items:
>        "Documents"
>        "Tom"
>        "Users"
>        "C:"

- Enter "C:\Toms\"  - crashes

- Enter "C:\Toms"   - crashes

- Enter "\Toms"     - "Couldn't open font" "The requested file, Toms, does not exist"

- Enter "\Toms\"    - "Couldn't open font" "The requested file, Toms, does not exist"

- Select "C:" from top list button
Enter "\Toms"     - bounces me back to original "Documents" location 

- Select "C:" from top list button
Enter "\Toms\"    - bounces me back to original "Documents" location 

- Enter "C:/Toms/"  - works to display C:\Toms\

- Enter "C:/Toms"   - "Couldn't open font" "Toms is not in a known format ..."

- Enter "//Toms/    - in dir list area " Not Found" "No such file or directory"

- Enter "//Toms     - "Couldn't open font" "The requested file, Toms, does not exist"

- Enter "C://"      - Shows "C://",  in dir list area " Not Implemented" "No support for browsing : C"

- Enter "C:/"       - works to display "C:\" root directory

- Select "C:" from top list button
Enter "//Toms/    - in dir list area " Not Implemented" "No support for browsing : C"

- Select "C:" from top list button
Enter "//Toms"    - bounces me back to original "Documents" location 

- Select "C:" from top list button
Enter "/Toms"     - bounces me back to original "Documents" location 

- Select "C:" from top list button
Enter "/Toms/"    - Shows "C://Toms/", in dir list area " Not Implemented" "No support for browsing : C"

- Select "C:" from top list button
Enter "Toms"      - works to display C:\Toms\

Started on command to see version:
```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:53 AWST 14-Oct-2014-ML-TtfDb-D.
 Based on source from git with hash:f6ffb25d7732adcc8d32dae75bd90bda90250304
no xdefs_filename!
TESTING: getPixmapDir:C:/Program Files (x86)/FontForgeBuilds/share/fontforge/pixmaps
TESTING: getShareDir:C:/Program Files (x86)/FontForgeBuilds/share/fontforge
TESTING: GResourceProgramDir:C:/Program Files (x86)/FontForgeBuilds/bin
trying default theme:C:/Program Files (x86)/FontForgeBuilds/share/fontforge/pixmaps/resources
fontforge 11:53 AWST 14-Oct-2014
libfontforge 20141014
```

BTW: tooltips popup with blank areas - no text

BTW:  #1743 was forgotten

**Comment by adrientetar** [comment]
I think we may be done here.

**Comment by davelab6** [comment]
@jtanx what do you think?

**Comment by jtanx** [comment]
Since folders can also be treated as 'files' (e.g. UFO / sfdir), and without implementing more complex strategies of checking each folder to see if it's a UFO/sfdir, it's about as best as it can be.

i.e. if a user enters a folder address without a trailing slash, it's treated as a potential UFO/sfdir. So the dialogue box closes and FF attempts to read it as such. When it fails because it's not a font, it reopens the file chooser in that location instead. This closing/opening of the file chooser is not ideal, but it works.

Another potential improvement could be to show all the drives available in the dropdown list, but you'd have to think about how this would work (since each drive is the 'root' directory but the dropdown list only allows for one 'root' directory as per Unix standards)

**Comment by adrientetar** [comment]
Could we just check the name of the folder for the appropriate extensions?

**Comment by jtanx** [comment]
I guess you could. It's been quite a while since I looked at the code, so I can't exactly remember, but from what I recall, the code path was quite different depending on if the entered path had a trailing slash or not.
