### ISSUE TITLE
Mac: Collaboration Server beacon doesnt work

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1815]
When I start a collab server, it doesn't show on the list of client sessions, and gives an error about UDP being firewalled:

![screen shot 2014-10-18 at 6 20 28 pm](https://cloud.githubusercontent.com/assets/261579/4689664/58c36a40-56c5-11e4-98b4-dd7a39e926bf.png)

But my firewall is off:

![screen shot 2014-10-18 at 6 03 23 pm](https://cloud.githubusercontent.com/assets/261579/4689627/fd66e4f8-56c2-11e4-9eaa-425449706eff.png)

**Comment by skef** [comment]
Collab was removed.
