### ISSUE TITLE
UFO: Handle off-spec UFOs better

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1828]
Given a privately available UFO, @graphicore said,

> This is a UFO between version 2 and version 3. It may be that the AFDKFO created the mess in the first place, but the handling of it by fontforge can be improved.
>
> 1. There was a "layerinfo.plist", but it only contained info for the `layer.glyphs.com.adobe.type.processedGlyphs` layer, not the standard glyphs layer. So fontforge ignored the glyphs layer and loaded only this `AFDKO ProcessedGlyphs` layer. Since `metainfo.plist` says that this is a ufo version 2, I think fontforge should have ignored the `layerinfo.plist` file.
>
> 2. The layer widget in fontforge's charview became unusable, only displaying garbage layer names.

**Comment by davelab6** [comment]
@graphicore is ufoJS and https://github.com/robofab-developers/robofab/tree/ufo3k the two libraries that support UFOv3? Any others?

**Comment by graphicore** [comment]
@davelab6 There's https://github.com/typesupply/defcon/tree/ufo3 but it depends on the  robofab ufo3k branch as well, AFAIK. Also, there is project in racket https://github.com/danielecapo/sfont

I don't know if there's more.

**Comment by adrientetar** [comment]
What remains here?

**Comment by frank-trampe** [comment]
I think that we need to make a new issue for U. F. O. 3 support and to close this one.
