### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by DomT4** [fontforge/fontforge#1837]
On OS X:

```
fontforge --version
dyld: Library not loaded: /usr/local/lib/libzmq.3.dylib
  Referenced from: /usr/local/lib/libczmq.1.dylib
  Reason: image not found
[1]    52205 trace trap  fontforge --version
```

The czmq we're using is version 2.2.0 which should be sufficient according to the build documentation, but Fontforge seems to be ignoring the pkg-config file and refusing to see this dependency is present and consequently when attempting to load Fontforge from the command-line we see the dylib failure displayed above.

Any ideas? For now, I may just turn the collab dependencies into optional dependencies for Homebrew and change that when we fix this little issue.

**Comment by dcboy** [comment]
just use ln

ln -s /usr/local/opt/zeromq/lib/libzmq.5.dylib /usr/local/lib/libczmq.3.dylib
