### ISSUE TITLE
Dogfood our homebrew build

### ISSUE THREAD

**Issue by rrthomas** [fontforge/fontforge#1844]
`before_install_osx.sh` says: "using homebrew formula fontforge.rb", but as far as I can tell, it's a lie: the formula is not used during the Travis build. (I noticed because I had to add a dependency separately to `before_install_osx.sh` that was already in `fontforge.rb`.

Surely we should be using the homebrew recipe in the Travis build?

**Comment by davelab6** [comment]
I've updated this and made a note in the release guide on the wiki to keep it updated going forwards
