### ISSUE TITLE
corrupted double-linked list on GSUB liga subtable of segoeui.ttf

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#185]
http://sourceforge.net/mailarchive/forum.php?thread_name=CAOxViunrO1fKaNzZo%3DvvGJTag40zKx%2Bh6FiyiqY41g%3DSTS_9Ew%40mail.gmail.com&forum_name=fontforge-devel

**Comment by skef** [comment]
Link at link is dead, opened a contemporaneous version of segoeui.ttf and it worked fine. Closing for lack of ability to further confirm problem.
