### ISSUE TITLE
FontView: Scrollwheel in a Unicode encoded font locks up FontForge, 100% CPU usage

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1853]
Probably related to https://github.com/fontforge/fontforge/issues/502

Scrolling performance on mac for https://googlefontdirectory.googlecode.com/hg/ofl/merriweather/src/Merriweather-Regular.otf in FontView is quite good with the scrollbar, but when using the mousewheel, it locks up. 

Video: http://youtu.be/mNhZ6wNIt-c

**Comment by jtanx** [comment]
I noticed this on OS X. It lags on all scrolling actions. Interestingly using the GDK/Quartz backend there's no lag.

**Comment by frank-trampe** [comment]
Is this because of a higher event count? Can we profile the execution time?

**Comment by jtanx** [comment]
No idea... Any suggestions on what to profile it with? I'm having trouble getting valgrind to work. I didn't actually recall it being so slow before - then I uninstalled XQuartz and reinstalled it via homebrew (while trying to debug something else) - that's when  I noticed the lag. I have the feeling that reinstalling XQuartz might help.

**Comment by frank-trampe** [comment]
I'd first just put it in gdb, break 10 times where it's lagging, and see where that tends to be.

If valgrind isn't working, I'd try Instruments from Xcode. I haven't used it in a long time, but I seem to recall that it worked reasonably well.

And the third possibility is just having the event loop print an x to standard error for every hundred events and seeing how fast those pile up when dragging versus using the wheel.

**Comment by jtanx** [comment]
![prof](https://cloud.githubusercontent.com/assets/5137410/18422413/5d933fd8-78cd-11e6-8525-9afce1e852e4.png)
[prof.zip](https://github.com/fontforge/fontforge/files/466392/prof.zip)

That's the profiling graph from Google pprof. Breaking with GDB suggests that the majority of time is spent waiting for XQuartz to complete drawing options - i.e. blocked on `select`, hence the vast majority of profiler time being in `libsystem`

**Comment by frank-trampe** [comment]
Was there a difference in event rates between dragging the scroll bar and using the wheel?

**Comment by jtanx** [comment]
Hah, I upgraded to XQuartz 2.7.10rc2 and the lag went away. In any case, it looks like it's more of an XQuartz issue over FontForge. I haven't looked into dragging the scrollbar yet.

**Comment by jtanx** [comment]
I can get it to reliably lag with XQuartz 2.7.9. However, scrolling by dragging the scrollbar doesn't cause a backup of events. It's possible that XQuartz is applying some sort of event compression to mouse events, but the same isn't happening with scroll events:

~~~~~
X11 all events, while dragging the scrollbar
ELAPSED: 3.02 s, EVCNT: 100, E/s: 33.07
ELAPSED: 3.05 s, EVCNT: 179, E/s: 58.63
ELAPSED: 3.07 s, EVCNT: 187, E/s: 60.92
ELAPSED: 3.12 s, EVCNT: 142, E/s: 45.57
ELAPSED: 3.06 s, EVCNT: 129, E/s: 42.22
~~~~~

**Comment by jtanx** [comment]
Okay, actually XQuartz 2.7.10rc2 doesn't eliminate lag, it just reduces it significantly. The lag is much more pronounced scrolling in the fontview.
