### ISSUE TITLE
file picker doesn't list drive letters other than c: in dropdown

### ISSUE THREAD

**Issue by v-python** [fontforge/fontforge#1883]
In the initial file picker, the top drop down includes c:, but not other drive letters found on my machine (D:, E:, F:, etc.).

It does work to type d:\ in the file name entry field, but it is rather disconcerting to not see the other drives listed where expected.

**Comment by pedjas** [comment]
I have opposite issue. Font Forge sees D: and My documents but no C: disk.

I see this issue is quite old and still unresolved.

**Comment by jtanx** [comment]
Yep. Unlikely to be resolved for as long as we use GDraw.

Just type C:\ into the field and press enter.

**Comment by ctrlcctrlv** [comment]
I believe my work in #4357 fixes this issue. You guys are invited to try it. You can use one of the AppVeyor artifacts to avoid needing to build yourself.
