### ISSUE TITLE
pasting doesn't work

### ISSUE THREAD

**Issue by v-python** [fontforge/fontforge#1884]
Having failed (see <https://github.com/fontforge/fontforge/issues/1729>) to be able to type into the file picker dialog, I decided to try pasting. Copying the path from Windows Explorer, I was unable to paste it, even though right clicking the file picker file name box offered a paste option. Ctrl-v didn't work either, and AutoHotKey macros are also not recognized.

Whatever technology is used by fontforge (the cygwin system, per the above bug) must not care much about interoperability with other standard windows programs and features. It's a pretty sad state of affairs for usability.

**Comment by jtanx** [comment]
This may have been the result of #2286. Please reopen if it's still an issue.
