### ISSUE TITLE
Windows: random glyph moved to background on opening

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#1918]
Sometimes when opening an SFD on Windows, a random glyph gets moved to the background layer. It’s a bit worrying if there’s a memory corruption somewhere, anyhow it’s unclear why I’ve only seen this on Windows so far.

cc @jtanx

**Comment by sergey-s-betke** [comment]
Workaround for python script:

    font = fontforge.open (sourcefile) 
    for glyph in font.glyphs(): 
    	glyph.foreground += glyph.background

**Comment by frank-trampe** [comment]
@adrientetar, can you reproduce this consistently?

**Comment by adrientetar** [comment]
I don't know. It seems rather random, not sure if it's always the same glyphs or not.

**Comment by frank-trampe** [comment]
If you wanted to maximize the odds of reproducing the problem, what would you do? And what are the odds that it would actually happen each time you do that?

Is this a display issue, or is there foreground data in the input file that ends up in the background in the output file?

**Comment by be5invis** [comment]
@frank-trampe an example sfd is [here](https://gist.github.com/be5invis/b1d764250a7b75fa32c6), the glyph uni1DC8's outline went to background.

**Comment by frank-trampe** [comment]
Is the linked file an input or a [corrupted] output?

**Comment by be5invis** [comment]
@frank-trampe input.

**Comment by be5invis** [comment]
@frank-trampe input.

**Comment by be5invis** [comment]
@frank-trampe input.

**Comment by be5invis** [comment]
and @frank-trampe , by removing all `Back` and `Fore` lines in the SFD, the layer-shifting problem is gone.

**Comment by frank-trampe** [comment]
@be5invis, are you able to reproduce this on Linux, are does it only happen on Windows as for Adrien?

**Comment by be5invis** [comment]
@frank-trampe not tested yet. I will try it later using the computer in my home.

**Comment by frank-trampe** [comment]
I can't reproduce on Linux, so this is probably a platform-specific memory corruption problem. @jtanx, can you reproduce the problem on Windows?

**Comment by jtanx** [comment]
I haven't been able to reproduce this bug with a quick test, but since it's a sporadic issue I'll continue to look into it. I really haven't had much time lately though so I don't know how far I'll get with this.

**Comment by jtanx** [comment]
I have been able to reproduce this using `descret-roman.sfd`. It looks like sometimes it writes out the components in different order (e.g. the 'Fore' is still there, but it's being written out after the spline data):

````diff
*** descret-roman.sfd	2015-05-05 15:37:15.322959200 +0800
--- out.sfd	2015-05-05 15:31:42.371875500 +0800
***************
*** 8081,8087 ****
  AnchorPoint: "Anchor-5" 320 694 basechar 0
  LayerCount: 2
  Back
- Fore
  SplineSet
  48 0 m 1,0,-1
   48 59 l 1,1,-1
--- 8081,8086 ----
***************
*** 8136,8141 ****
--- 8135,8141 ----
   400 -47 400 -47 447 0 c 1,68,-1
   48 0 l 1,0,-1
  EndSplineSet
+ Fore
  Substitution2: "'c2sc' Capitals to Small Capitals lookup 2 subtable" Eogonek.sc
  EndChar
````

**Comment by jtanx** [comment]
Does this happen only on saving and then reloading the saved file, or does it immediately happen when a file is opened?

**Comment by jtanx** [comment]
I've just run it through gdb and something's interesting is happening in SFDGetChar - after it matches the 'Back' token, whatever it does in there offsets the file pointer so that when the next token is read (should be 'Fore'), it returns 're' - hence losing the foreground flag.

**Comment by be5invis** [comment]
I do not sure. The sfd is corrupted afaik, but i do not know whether it is caused by the parser OR the saving procedure.

- 发送自我的Sony Xperia™智能手机

---- Jeremy Tan 编写 ----

Does this happen only on saving and then reloading the saved file, or does it immediately happen when a file is opened?

---

**Comment by jtanx** [comment]
I think I know why this happens on Windows, re `ungetc`:

> Some library implementations may support this function to be called multiple times, making the characters available in the reverse order in which they were put back. Although this behavior has no standard portability guarantees, and further calls may simply fail after any number of calls beyond the first.

In other words, calling ungetc more than once has technically undefined behaviour.

**Comment by jtanx** [comment]
This bug was most likely introduced by  a8d06348 in `PeekMatch`.

**Comment by HugoLisbona** [comment]
Hello.

Similar issue, when importing a PNG file:

PNG file is imported in BACK layer;
![002](https://user-images.githubusercontent.com/38476751/38915548-6b955552-42e4-11e8-9d4f-fff5636dac8a.JPG)


So there is nothing in FRONT layer;
![003](https://user-images.githubusercontent.com/38476751/38915558-74ebb5ec-42e4-11e8-926b-8a2f3890dd63.JPG)


Hence there is no image;
![001](https://user-images.githubusercontent.com/38476751/38915563-7a13b2fe-42e4-11e8-8677-c642f8c90ff6.JPG)


Any help?

Font Forge version is: 08:20 UTC 31-Jul-2017-ML-TtfDb-D
OS is: Windows 10 version 10.0.16299 Comp 16299
