### ISSUE TITLE
cannot compile with ASan

### ISSUE THREAD

**Issue by holomorph** [fontforge/fontforge#1930]
[Address sanitizer](https://code.google.com/p/address-sanitizer/wiki/AddressSanitizer) is a fast memory checker and a part of LLVM and gcc. Not sure how it compares to coverity, but so far I have used it to track down bugs in another [project](https://github.com/weechat/weechat/search?q=asan&type=Issues&utf8=%E2%9C%93).  Using it consists of compiling and linking with the flag `-fsanitize=address`.  This is usually as easy as adding the flag to `CFLAGS` and `LDFLAGS`.

When doing this for fontforge, I get linker errors:

```
  CCLD     libgunicode.la
charset/.libs/libgunicode_la-alphabet.o: In function `_GLOBAL__sub_D_00099_0_alphabet.c':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/charset/alphabet.c:52: undefined reference to `__asan_unregister_globals'
<snip>
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ArabicForms.c:263: undefined reference to `__asan_register_globals'
.libs/libgunicode_la-char.o: In function `strstart':
<snip>
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/char.c:90: undefined reference to `__asan_report_load2'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/char.c:85: undefined reference to `__asan_report_load1'
.libs/libgunicode_la-char.o: In function `_GLOBAL__sub_I_00099_0_char.c':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/char.c:98: undefined reference to `__asan_init_v3'
.libs/libgunicode_la-memory.o: In function `NoMoreMemMessage':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:34: undefined reference to `__asan_report_load8'
.libs/libgunicode_la-memory.o: In function `copyn':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:54: undefined reference to `__asan_report_load_n'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:54: undefined reference to `__asan_report_store_n'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:55: undefined reference to `__asan_report_store1'
.libs/libgunicode_la-memory.o: In function `_GLOBAL__sub_D_00099_0_memory.c':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:57: undefined reference to `__asan_unregister_globals'
.libs/libgunicode_la-memory.o: In function `_GLOBAL__sub_I_00099_1_memory.c':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:57: undefined reference to `__asan_init_v3'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/memory.c:57: undefined reference to `__asan_register_globals'
.libs/libgunicode_la-ucharmap.o: In function `encoding2u_strncpy':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:52: undefined reference to `__asan_report_load8'
<snip>
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:377: undefined reference to `__asan_report_store1'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:381: undefined reference to `__asan_report_load8'
.libs/libgunicode_la-ucharmap.o: In function `BytesNormal':
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:399: undefined reference to `__asan_option_detect_stack_use_after_return'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:399: undefined reference to `__asan_stack_malloc_3'
/tmp/makepkg/fontforge-git/src/fontforge/Unicode/ucharmap.c:407: undefined reference to `__asan_report_store_n'
<snip>
/tmp/makepkg/fontforge-git/src/fontforge/lib/vasnprintf.c:1775: undefined reference to `__asan_stack_free_5'
../lib/.libs/libgnu.a(vasnprintf.o): In function `_GLOBAL__sub_I_00099_0_vasnprintf.c':
/tmp/makepkg/fontforge-git/src/fontforge/lib/vasnprintf.c:5580: undefined reference to `__asan_init_v3'
collect2: error: ld returned 1 exit status
Makefile:1337: recipe for target 'libgunicode.la' failed
```

I'm not sure why this happens for `libgunicode`, and it's possible other libraries fail.  Only `libgnu`, `dlopen` and `libltdlc` are built before `libgunicode`.

**Comment by adrientetar** [comment]
@jtanx Does not seem to work for me.

**Comment by floyd-fuh** [comment]
Unsure if this is related, but I wanted to give a hint at least. I had a similar issue with ffmpeg not passing the CFLAGS (-fsanitize-address) to all invocations of the compiler. See https://www.mail-archive.com/ffmpeg-devel@ffmpeg.org/msg23628.html

Btw. I laughed pretty hard, it seems @hannob (see #2348) and me are helping fix address sanitiser issues with projects because we both want to fuzz with AFL :P

**Comment by hannob** [comment]
I can give an update here. This is most likely due to an issue in libtool.
libtool will filter all flags it doesn't know on library linking - with the intention of avoiding flags that may cause problems. However with asan this approach actually causes a problem in the first place because the linking step will miss the asan libs.
Here's the upstream report:
https://savannah.gnu.org/patch/?8775

Unfortunately no reply yet from a dev. You can patch libtool with the patch provided there, but this should really be fixed in upstream's libtool.

**Comment by Earnestly** [comment]
Or move off libtool completely.  

I have struggled packaging and building many software projects using libtool, I'm happy if all it does is needlessly relink everything if it works in the end and I have absolutely no certainty about the resulting linkage.

**Comment by skef** [comment]
Asan support is now documented in the CMake wiki page.
