### ISSUE TITLE
Fonts saved using master version cannot be opened in older versions

### ISSUE THREAD

**Issue by santhoshtr** [fontforge/fontforge#1934]
I am using fontforge built from git(specifically my build is from a7edc6db40aec54f95ab28c28fa25d2be83eec4c). The sfd files generated by this version of fontforge has lot of additions to the sfd created by fontforge shipped by distros-example: 2012 versions. When the new sfd is opened by 2012 fontforge, all glyphs are shown blank. 

To reproduce try opening an sfd saved by fontforge from git master in older versions. All glyphs will be blank. It is also noted that fontforge 201408xx version cannot open SFD generated from 201410xx versions.

This is a serious problems since the distros like Fedora build TTF from sfds using packaged fontforge versions and resulting ttf will not have any glyphs.

(Sample SFD generated using latest fontforge is available at https://github.com/smc/Chilanka )

**Comment by ctrlcctrlv** [comment]
Superseded by #3800.
