### ISSUE TITLE
Generated path of glyphs in SVG file is different in some cases

### ISSUE THREAD

**Issue by parioux** [fontforge/fontforge#1944]
Hello,

I am running OSX 10.9.5 as well as an ubuntu 12.04 VM.

I've recently updated my fontforge version and I'm trying to generate an svg file but the output seems different from the one I had before with the same file...

```
Open("PT_Sans-Web-Regular.ttf")
SelectAll()
VFlip(0)
Generate("output.svg")
```

If I build from source (20141014 and 20141119 / ubuntu 12.04) and run the above ff script here's what I have for unicode U+0178 :

```
<glyph glyph-name="Ydieresis" unicode="&#x178;" horiz-adv-x="558" 
d="M239 278l-231 422h97l164 -306l17 -61h1l18 63l157 304h89l-229 -421v-279h-83v278zM133 794q0 21 15 34t39 13q23 0 37.5 -13t14.5 -34q0 -20 -14.5 -33t-37.5 -13q-24 0 -39 13t-15 33zM325 794q0 21 14.5 34t37.5 13q24 0 39 -13t15 -34q0 -20 -15 -33t-39 -13
q-23 0 -37.5 13t-14.5 33z" />
```

Using the same script with the 20141014 (ppa) ubuntu 12.04, 20141024 OSX 10.9.5 and 20110222 (apt) ubuntu 12.04 builds here's what I get :

```
<glyph glyph-name="Ydieresis" unicode="&#x178;" horiz-adv-x="558" 
d="M239 -278l-231 -422h97l164 306l17 61h1l18 -63l157 -304h89l-229 421v279h-83v-278zM133 -794q0 -21 15 -34t39 -13q23 0 37.5 13t14.5 34q0 20 -14.5 33t-37.5 13q-24 0 -39 -13t-15 -33zM325 -794q0 -21 14.5 -34t37.5 -13q24 0 39 13t15 34q0 20 -15 33t-39 13
q-23 0 -37.5 -13t-14.5 -33z" />
```

Take a closer look at the numbers and their signs, they are all flipped in one case. 
Is the VFlip function not working in some cases ? (or SelectAll ?) 
Is there something wrong or missing from my build (from source) ?

Also: if I generate the svg without calling SelectAll and VFlip then the output seems to be the same as I had before updating (no differences/changes).

Thanks for your help.

**Comment by skef** [comment]
Lots of changes that may have affected this on Mac OS since it was filed, so closing. Update with a comment if it should be reopened.
