### ISSUE TITLE
PPA doesn't include hotkeys

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1958]
PPA doesn't include hotkeys file. 

Mailing list discussion:

http://fontforge.10959.n7.nabble.com/fontforge-users-No-keyboard-shortcuts-on-precompiled-Linux-build-of-Fontforge-tp14515p14558.html

**Comment by davelab6** [comment]
@pathumego is this working now?

**Comment by pathumego** [comment]
Yep. Was Fixed

**Comment by frank-trampe** [comment]
Oops. I forgot about this one.
