### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#1960]
![fontforgeicon](https://cloud.githubusercontent.com/assets/3859425/5233173/ef8bbdc2-776f-11e4-9559-0908336d46e6.png)

Just a quick sketch but you get the idea. I wanted to put it up here to get some feedback and suggestions. And to know if it's some I should move forward with.
The current icon looks a bit :older_man:

**Comment by andreaslarsen** [comment]
fwiw this is how the latest iteration looks (more garamond-like and clearer at small sizes). 
I think it would look more at home on windows than the old one - especially with how win 10 is going to look.

![icon_512x512](https://cloud.githubusercontent.com/assets/3859425/7552649/30f11a34-f6c1-11e4-8f09-5a64b3efb156.png)

**Comment by skef** [comment]
This happened at some point.
