### ISSUE TITLE
PPA does not include Tango theme or icon

### ISSUE THREAD

**Issue by n8willis** [fontforge/fontforge#1969]
The Ubuntu PPA packages of the 2014126 release do not appear to include the Tango-style 'resources' file, instead defaulting to a rather old-fashioned X/motif look with a pale green widget background.

Similarly, the packages & .desktop file included do not include/use the newer "ff"-ligature PNG icon, but fall back on the low-res and aliased "anvil" .XPM pixmap instead.

**Comment by n7s** [comment]
It seems the issue was simply to do with copying the missings files to /usr/share/fontforge/

**Comment by n7s** [comment]
https://github.com/fontforge/fontforge/pull/2061
