### ISSUE TITLE
Homebrew OS X install broken

### ISSUE THREAD

**Issue by elmimmo** [fontforge/fontforge#1971]
Installing Fontforge on Mac OS X via the Homebrew package manager results in a GUI app that does not run.

Homebrew is the recommended package manager to install Fonforge, according to http://fontforge.github.io/en-US/downloads/mac/). Homebrew installs FontForge at /usr/local/Cellar/fontforge/, but then it instructs the user to “run `brew linkapps` to symlink these to /Applications”. Doing so and then double clicking the resulting “FontForge” symlink at /Applications returns this error:

> Please move the FontForge.app to your system /Applications folder.

**Comment by raeesbhatti** [comment]
@DomT4, I installed it the way you suggested but it still opens inside the CLI and not in GUI.

**Comment by raeesbhatti** [comment]
I tried to install last two releases for Mac too like the guide suggested, both did not work. The app quits without saying anything when you star it.
