### ISSUE TITLE
UFO: wrong path direction in AFDKO-generated files

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#1995]
Using an UFO from FontForge and compiling with AFDKO through robofont or Glyphs generates an OTF with inverted path direction and hints. 
It's weird because it seems that Glyphs and robofont show correct direction when opening the UFO and the generated files have the wrong one. I tried with an UFO made with robofont afterwards and problem does not show.

cc @frank-trampe

**Comment by davelab6** [comment]
@adrientetar said

> we should probably stop abstracting the path directions 

I've just looked at this, and fontforge today exports a cubic curve and a quadratic curve to a GLIF in the order it appears on screen, so I don't think there is any abstraction of path directions for UFO.

> Robofont fixes path direction to respect Postscript convention before compiling through the AFDKO, 

So, lets add a UFO export python script and bundle it with the next release, "Export UFO for AFDKO", that runs
```py
font = fontforge.activeFont()
for glyph in font.glyphs():
    glyph.layers[1] = glyph.layers[1].reverseDirection()
```
However,

**Comment by typemytype** [comment]
RoboFont doenst not fix contour direction before export. If you have a remove overlap before an export it is different. The remove overlap will fix the contour direction and will set it correctly with the given curve description.

**Comment by adrientetar** [comment]
@davelab6 Maybe a checkbox in the export window similar to the one for choosing kerning kind would do it? I like that export checkboxes retain your settings.

**Comment by adrientetar** [comment]
@davelab6 But my point was that the order curves appear on screen is forced by the program unless you don't care about error reporting and don't use correct direction.

Speaking of which, when you select multiple glyphs or all of them you can do correct direction but not invert direction — that would be another way to go with this issue but I think it is most convenient with an export checkbox.

**Comment by davelab6** [comment]
@typemytype thanks for clarifying! :)

**Comment by davelab6** [comment]
@adrientetar I leave how to implement this up to you; to me, shipping a Python script is easier to maintian, and I think as much as possible, FontForge should be extended that way rather than with C, but, as ever, "who does the work decides how its done" :)

**Comment by schriftgestalt** [comment]
Reading all this I think there should be any automatic fixing of path direction (there is none in glyphs). Maybe show a small warning. Only if you convert outline from PS to TTF the path direction should be reversed (but again without checking).

**Comment by davelab6** [comment]
when I test ff ufo export, it didn't change any path directions for me

**Comment by adrientetar** [comment]
> it didn't change any path directions for me

It doesn't indeed.

**Comment by davelab6** [comment]
@adrientetar I think the title 'wrong path direction in AFDKO-generated files' but I think we established that this was specific to your workflow; so I've opened a new issue for the 2 ways to resolve this, https://github.com/fontforge/fontforge/issues/2090 , and thus I propose closing this issue

**Comment by adrientetar** [comment]
> I think we established that this was specific to your workflow

I think we really established that using a flipped direction convention is something only FontForge and Fontographer do.

**Comment by davelab6** [comment]
On 27 February 2015 at 10:55, Adrien Tétar <notifications@github.com> wrote:

> I think we really established that using a flipped direction convention is
> something only FontForge and Fontographer do
>
I agree :) Sorry if I sounded snobby!! :) Using the 'real' convention in a
UFO workflow already works fine though, right?

**Comment by adrientetar** [comment]
> Sorry if I sounded snobby!! :)

No worries, you didn't.

> Using the 'real' convention in a UFO workflow already works fine though, right?

It works fine modulo the problem reporter and the "Correct direction" functionality. I'd say it's all good but I come from a native file which is why it's unfortunate Anyways the internals aren't something we're going to alter at this point.
