### ISSUE TITLE
Having really poor performance on any operation while font file is open.

### ISSUE THREAD

**Issue by seanmakesgames** [fontforge/fontforge#2003]
Initially this wasn't happening, so I assume it was a change I made in editing the file that caused the issue. Now I'm not so sure.

I've linked the font file:
https://www.dropbox.com/s/296u7ywkl8gc9wv/WhiteRabbit.sfd?dl=0

and a crash log from when I close the app while the performance spikes:
https://www.dropbox.com/s/6aol3dqjf0oy4lt/fontforge_crash_on_close.txt?dl=0

ohp, and I guess the issue is not tied to the font file. Something else is going on, here's a crash from just clicking around in a brand new file:
https://www.dropbox.com/s/8t0wr4clgvb66pn/crash%20from%20clicking%20around%20while%20the%20issue%20happens.txt?dl=0

Here's a capture from activity monitor during perf spike:
https://www.dropbox.com/s/ib9sd9easbepfjg/Sample_of_FontForge.txt?dl=0

On a macbook pro retina (specs in crash), running in latest XQuartz

repro steps:
1. open font file
2. start clicking around

result: very unresponsive to clicks.

**Comment by jtanx** [comment]
Closing out old issues, reopen if this is still occurring on the latest version.
