### ISSUE TITLE
Import SVG: stroke-linecap attribute is incorrectly interpreted

### ISSUE THREAD

**Issue by skarrmann** [fontforge/fontforge#2007]
When importing an SVG file, the stroke-linecap attribute is incorrectly interpreted. Refer to the video for reproducing the issue and the SVG files for testing.
- OS: Ubuntu 14.04
- FontForge Version: 0:59 UTC 27-Nov-2014, from http://ppa.launchpad.net/fontforge/fontforge/ubuntu
- Reproducing the issue: http://youtu.be/uPsYgs7ThyA
- SVG files: https://drive.google.com/file/d/0B8jV0ft98YzoZGZDVHFLclRGaWM/view?usp=sharing

**Comment by Delagen** [comment]
any movement? I get multiple bound when import such svg

**Comment by skef** [comment]
This is a `strcmp` problem. I'll fix in a bit.
