### ISSUE TITLE
Question: Release Tarball Size

### ISSUE THREAD

**Issue by DomT4** [fontforge/fontforge#2020]
Apologies for the dumb question here.

I was wondering if someone could briefly explain why the Github tarball is 16MB and builds fine, and the release tarball is 252MB and (normally) builds fine.

What am I getting from the release tarball that I wouldn't get from the automatically generated Github tarball, or git cloning a tag? Aside ` gnulib ` already existing? Could I just use the considerably smaller ` git clone --tag ` or archive tarball and get the same end result?

I'm inevitably missing something stupid here, so apologies in advance, and absolutely no intention to cause offence. Mad love for what you guys are doing here, as much cooler people than me would say.

**Comment by davelab6** [comment]
@frank-trampe did you address @lemzwerg 's 3 points? The latest release on https://github.com/fontforge/fontforge/releases went to 117Mb from 252Mb so I guess so :)
