### ISSUE TITLE
Building with x11 hardcodes Breakpad

### ISSUE THREAD

**Issue by DomT4** [fontforge/fontforge#2022]
Building Fontforge *(either the git tag or the archive tarball; haven't tried the release tarball yet because of the errors I discussed in the other issue)* with ` x11 ` support enabled seems to generate a hardcoded link from ` bin/fontforge ` to ` @executable_path/../Frameworks/Breakpad.framework/Versions/A/Breakpad `, the latter of which obviously doesn't exist in the situation where the binary is separate from the app bundle, and consequently ` fontforge ` errors out on ` dylib not loaded ` and refuses to load.

You can see this link by executing an ` otool -L ` on ` bin/fontforge `.

I used ` install_name_tool ` locally to change the ` @executable_path/../Frameworks/Breakpad.framework/Versions/A/Breakpad ` link in ` bin/fontforge ` to the share directory where FontForge.app exists, which fixed the error.

I'm not explicitly requesting Breakpad to build, although I'd be happy for it to do so, but if I build ` --with-x ` I get it regardless and when run the ` dylib not loaded ` fatal run error pops up.

Sorry for the multitude of issues today :cry:.

**Comment by davelab6** [comment]
@monkeyiq yikes - this is pretty urgent, it means we can't install FontForge with a UI via Homebrew, and since your fuuko package builder is down, we are totally without a way to run HEAD on Mac :(

**Comment by DomT4** [comment]
> it means we can't install FontForge with a UI via Homebrew

The UI works, It just needs the ` install_name_tool ` fix prior to actually running. We handle it automatically post-install at the moment if you build ` --with-x11 `, so it works, It's just not ideal to carry the workaround for an extended period of time. HEAD should be back in Homebrew soon - We're having some issues with the test-bot this evening, but it should be merged within the next 48 hours tops.

**Comment by davelab6** [comment]
@DomT4 I wonder if this is fixed now - @monkeyiq did a lot of work on the breakpad integration in March

**Comment by DomT4** [comment]
I'll remove the old fix and rebuild to see.

**Comment by DomT4** [comment]
Yup. Fixed :+1:. Looks like the link from ` bin/fontforge ` to Breakpad has gone completely.

These are the only ` otool -L ` references to ` Breakpad ` in the entire tree:

```
Changing dylib ID of /usr/local/Cellar/fontforge/20150330/share/fontforge/osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Breakpad
  from @executable_path/../Frameworks/Breakpad.framework/Versions/A/Breakpad
    to /usr/local/share/fontforge/osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Breakpad
Changing dylib ID of /usr/local/Cellar/fontforge/20150330/share/fontforge/osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/breakpadUtilities.dylib
  from @executable_path/../Frameworks/Breakpad.framework/Resources/breakpadUtilities.dylib
    to /usr/local/share/fontforge/osx/FontForge.app/Contents/Frameworks/Breakpad.framework/Versions/A/Resources/breakpadUtilities.dylib
```

**Comment by davelab6** [comment]
Great! Please close when the brew script is updated in their master :)

**Comment by DomT4** [comment]
Just pushing the PR now :).

**Comment by davelab6** [comment]
:8ball:

**Comment by DomT4** [comment]
Open: https://github.com/Homebrew/homebrew/pull/38410

**Comment by DomT4** [comment]
Merged!
