### ISSUE TITLE
Last windows version of FontForge 31-12-2014 cant be run in Windows-XP

### ISSUE THREAD

**Issue by saeedserpooshan** [fontforge/fontforge#2027]
After installing last FontForge 31-12-2014 in windows-xp 32 bit, i get this error when i try to run it:
"fontforge.exe - Entry Point Not Found: The procedure entry point if_nametoindex could not be located in the dynamic link library IPHLPAPI.DLL. "

i search the web and find such dll, but then the app throws another error about entry point _ftol2 in msvcrt.dll

what's the problem?

**Comment by jtanx** [comment]
Oops, let me have a look...

**Comment by jtanx** [comment]
Hmm.. It looks like after an update to glib (libgio specifically), it now makes use of if_nametoindex which is only present on Vista or later. I'd have to push for msys2 to build it without reference to that function, (if that's at all possible)...

**Comment by adrientetar** [comment]
It's almost a year that Windows XP support is dropped so it is being gradually phased out from libraries. I think we should do the same because it is irresponsible to let people use a system that is a security hazard.

**Comment by jtanx** [comment]
Well... I still use XP now and then. I'd be rather sad if XP support was dropped.

**Comment by davelab6** [comment]
Can we use the older version of glib?

Xp is widely used in the developing world, where fontforge is most popular

**Comment by jtanx** [comment]
Since I don't build glib myself and I don't think the old package is still available for install, I can't downgrade easily... 

But I can just copy the glib dll from an older build which is known to work with XP and package it with the new FontForge. Hopefully that could work.

**Comment by jtanx** [comment]
Nevermind, the old glib package was cached, so I've downgraded to that. If it works with XP, I'll roll out a new release.

**Comment by jtanx** [comment]
@saeedserpooshan, I've updated the release; could you try installing the new version? It should be named `FontForgeSetup-31-12-2014-r2.exe`. If it works for you then feel free to close this issue. Thanks for reporting it!

**Comment by saeedserpooshan** [comment]
thanks for your attention. i will check it now and reply to you.
by the way, it may be usefull for to mention that the last version which i could successfully install in win XP was "FontForge Setup 18-10-2014 prerelease2"

**Comment by saeedserpooshan** [comment]
I checked your r2 version and it works in XP. thank you.
but another question: did you downgrade something in this version which may affect overall operation of fontforge? in other words, is this version as good as wion vista+ version?

**Comment by jtanx** [comment]
It should be no different; the downgrade was to a component (glib) and for a part that (at least I'm pretty sure) FontForge doesn't use.

**Comment by davelab6** [comment]
I believe glib is used by fontforge for about 2 years now

Brilliant work!
