### ISSUE TITLE
Highlight selected references in distinct color in outline window

### ISSUE THREAD

**Issue by n8willis** [fontforge/fontforge#2030]
When editing a glyph in the outline window, glyph references are currently drawn using the same color whether they are selected or unselected. Thus you can't tell when opening a glyph that a reference (e.g., a diacritic or base glyph) is selected, and you occasionally move them accidently using the keyboard or other tools.

That's most often a problem when a reference was selected the last time the glyph was opened, since FontForge remembers previous selections.

Simplest fix might be to use Selected Point Color to either draw the reference outline or the corresponding bounding box, but maybe a separate color resource would be better -- if using the Selected Point Color would make it hard to see when a point and a reference are both selected.

**Comment by adrientetar** [comment]
There is an outline when a reference is selected, isn't that enough?

**Comment by skef** [comment]
Selected references have a rectangular outline as described. There aren't any plans to do more than that for the time being.

**Comment by n8willis** [comment]
> Selected references have a rectangular outline as described. 

That, quite obviously, does not work for rectangles. See macrons, etc.

> There aren't any plans to do more than that for the time being.

That's what makes it a bug. If there was a plan in place to fix it, it wouldn't have needed an issue filed.

**Comment by skef** [comment]
When you get above 300 issues or so the ones you're not likely to fix start interfering with finding the ones you might fix. We're currently at 907. FontForge has a tiny fraction of people actually submitting PRs and we leave open hundreds of issues that are very unlikely to ever be fixed.

There is an attitude in the user community that the scope of potential FontForge development is infinite: all future *and* past font formats should be completely supported and any feature someone wants should be implemented.

I'm trying to be *very slightly* more reasonable.

**Comment by skef** [comment]
> That's what makes it a bug. If there was a plan in place to fix it, it wouldn't have needed an issue filed.

And a bug is a discrepancy between either the documented behavior of a program or implicit/common-sense expectations about that behavior (such as it not crashing). A non-optimal or ambiguous case is not a bug per se.
