### ISSUE TITLE
font interpolate error

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge#2032]
Interpolation between the first two (25%) results in the 3rd picture - I'm on the latest.HEAD mac version on Yosemite. 

I have cleaned them up and fixed them for errors prior to interpolating and the o doesn't show any errors in the error log. It is as if the direction arrows are ignored or something, works fine on most other glyphs.

It's the hairline and regular font from this project: https://github.com/gidole/sans/tree/master/Source

![1](https://cloud.githubusercontent.com/assets/3859425/5629790/7a42fc18-95b7-11e4-85c1-2dfb3281687b.png)
![2](https://cloud.githubusercontent.com/assets/3859425/5629792/7a68765a-95b7-11e4-9121-6bb2d54f6bd8.png)
![3](https://cloud.githubusercontent.com/assets/3859425/5629791/7a67ab08-95b7-11e4-8dc9-cd4c379e69aa.png)

**Comment by adrientetar** [comment]
It is not an issue in the interpolation engine. If you want to interpolate diagonal points properly their position relative to the nearby HV points must be constant.

![7a68765a-95b7-11e4-9121-6bb2d54f6bd8](https://cloud.githubusercontent.com/assets/1250894/7225436/ccf7a08e-e73e-11e4-9850-7bce583a7aeb.png)

&alpha;/&beta; must be constant throughout your masters.

**Comment by andreaslarsen** [comment]
cheers
