### ISSUE TITLE
Fontforge on OS X Yosemite very slow to react Version 24.11.2014

### ISSUE THREAD

**Issue by robertdbuckley** [fontforge/fontforge#2038]
After starting fontforge there are about 30 seconds where everything works fine...then it just seems to "stick"....after clicking in a Glyph windows or on an index menu there is a lag of about 20 seconds before the command is carried out. Can anyone offer a tip?

**Comment by davelab6** [comment]
Use a daily development snapshot,
http://fontforge.github.io/en-US/downloads/mac/

**Comment by robertdbuckley** [comment]
I tried this but have the same problem. Works ok for about 20 seconds, then gets this lag time problem.

**Comment by jtanx** [comment]
Reopen if still an issue
