### ISSUE TITLE
Keymapping problem

### ISSUE THREAD

**Issue by robertdbuckley** [fontforge/fontforge#2045]
Ctrl + Is not working on windows 7 (latest version)
Ctrl - is zoom out - shouldn´t Ctrl + be zoom in?
I would suggest assigning Preview to another key - maybe Ctrl Y - as this would be easy to initiate.

**Comment by robertdbuckley** [comment]
Ah..just realized that Ctrl with a numberpad + DOES in fact zoom in. What is the mapping for Preview then?

**Comment by jtanx** [comment]
Strange... I just tested (assuming you're trying to zoom in in the char/glyph editing window) and Ctrl +/Ctrl - (non numpad) works fine. 

Preview... I think it's the backtick character (`) - usually to the left of number 1 (top left on a standard US Eng. keyboard).
