### ISSUE TITLE
Allow moving a point without touching its handles

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2050]
i.e. moving an anchor point along the path of its handles.

This is *very* useful when creating high-quality outlines so that you can fine-tune the location of the extrema without disrupting the course of the handles.

**Comment by davelab6** [comment]
How do other editors do it? A chord key?

**Comment by adrientetar** [comment]
> How do other editors do it? A chord key?

Glyphs uses Option + drag on the Mac. http://vimeo.com/43552747

**Comment by davelab6** [comment]
I'm not sure if that's good for XQuartz; `Cmd + Shift + Drag` seems to be identical to `Shift + Drag` so that seems like a good candidate.
