### ISSUE TITLE
Antivirus issue

### ISSUE THREAD

**Issue by JonathanMagus** [fontforge/fontforge#2052]
Hi

The latest Norton Antivirus Update has an issue with the latest version of Fontforge on Windows (31_12_2014, specifically with run_fontforge.exe), although not with the two previous versions of the software. I had been running an installation of it without any issues for more than two weeks before Norton responded like this, so suspect it is actually a misreading of something by Norton caused by the recent definition updates. Norton Power Eraser does not find any fault with Fontforge at all, when cross-checked with it.

I have notified Norton that they need to re-evaluate this situation and thought it appropriate to advise Fontforge also, in case there has been a change between the versions that antivirus software might misinterpret for some reason; and in case it becomes a support or reputational issue.

I have not had any trouble with Fontforge since using the more recent and stable Fontforge Builds and am not convinced there is an actual problem here. So, this is not a report of an issue. It is advising that an antivirus thinks there is one.

Perhaps worth checking?

Regards

JonathanMagus

**Comment by jtanx** [comment]
Yeah, it's definitely a false positive, and [it's happened before](http://sourceforge.net/p/fontforgebuilds/discussion/general/thread/9b686c1c/). Symantec had already been notified before, and the code for `run_fontforge` hasn't been changed in months if not years.

**Comment by JonathanMagus** [comment]
Thanks. I thought that might be the case. I will feed this back to Norton (Symantec).

**Comment by JonathanMagus** [comment]
An update: Symantec have acknowledged that this is a false positive and are correcting it in the next Antivirus definitions, which should already be available.

**Comment by jtanx** [comment]
Thanks for following that through!

**Comment by adrientetar** [comment]
Guess we can close this then.
