### ISSUE TITLE
Display problem on Mac OS/X Yosemite

### ISSUE THREAD

**Issue by uswd** [fontforge/fontforge#2053]
Hi,
I've followed the instructions on fontforge.github.io and installed XQuartz, logged out and in, and installed Fontforge.
When running Fontforge some windows opened but I can see them only partially on the display, the upper part being shifted outside the monitor display. And because the menu bar is not there I cannot move them with the mouse. Also the top menu shows only the X11 menu but no fontforge. BTW I've two 27" monitors attached.
Any ideas?

Best regards,
Ulrich

**Comment by andreaslarsen** [comment]
Not sure if it helps but I use shiftit for window management as it also supports x11/xQuartz

https://github.com/fikovnik/ShiftIt/releases

**Comment by uswd** [comment]
Thanks for the link. With shiftit I can get control over the fontforge window placement.
But the problem is still there. Interestingly when I use "top left" the top part disappears, when I use "bottom" the window is about 20 % higher than the bottom. I assume that fonforge (or X11) is not able to detect the correct monitor size and dimensions.
Also despite that with shiftit I can arrange the windows correctly every time I launch fontforge it "forgets" the last used position and placement. Then I have to rearrange everything again. Very annoying.

**Comment by andreaslarsen** [comment]
Strange - is the monitor size correctly set in "File" -> "X Resource Editor" -> "GDraw" ?

**Comment by uswd** [comment]
Last time I opened FontForge everything was correct. I was irritated, I thought maybe a restart issue. But before writing a "everything is fine now" I startet X11 and FontForge again, and the problem is back again! Strange. In File -> X Resource Editor -> GDraw there is only one number for screen width ("46.6667") but nothing about height. And BTW some windows disappears when moving to the second display.

**Comment by andreaslarsen** [comment]
I think the width should be your diagonal size - e.g. 24 if you're on a 24" monitor.
Do other x11 programs (e.g. inkscape) display correctly so you're sure it's not a bug with x11/xquartz?

**Comment by nighthawk663** [comment]
I am also having this problem. I also have a multi-display setup running on Yosemite. ShiftIt works to reposition the window, but every time FontForge opens a new window, it opens above the menu bar and I have to use ShiftIt to reposition the window someplace where I can access the top bar.

**Comment by davelab6** [comment]
Did you try clearing your prefs file?
