### ISSUE TITLE
Various first-use issues encountered on Max OS X 

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2055]
### Quick things
- [x] ~~The default value of `Element, OS/2, Metrics, X Height` is 0 but should be 500.~~ Adrien didn't think this was wise, see below, so striking it out
- [x] ~~Turn off CharView, View, Show, Control Points (Always) by default~~ Adrien didn't think this was wise, see below, so striking it out
- [x] ~~Crash, https://github.com/fontforge/fontforge/issues/2056~~ spurious so punting
### Mac integration
- [ ] After installing FontForge on a Mac, the first time it is run, it runs `fc-cache` over all the `/LIbrary/Fonts` which takes about 3 minutes on a Macbook Air. This is excruciating, and I wonder if this is really necessary, because I believe the reason this is run is to be able to register the fonts used to render the UI, and I believe those fonts are all in the `FontForge.app` bundle. So, can this scan be only scanning the bundle, and take just a second or two max..?
- [x] Weirdly the first time the program is run, the dock icon goes away after the `fc-cache` process completes, and XQuartz starts and the FF window appears. Quitting FontForge and launching it from the Finder again solves this. I don't think anything can be done about that, so checking this mark, but, it sucks :) Here's an image:

![screen shot 2015-01-22 at 7 51 03 pm](https://cloud.githubusercontent.com/assets/261579/5868663/d815c904-a27a-11e4-806a-8510c8639943.png)
- [x] The second time the program is run, the dock icon bounces forever. This really sucks and I hope something can be done! really distracting :( Here it is bouncing after the program is fully loaded:

![screen shot 2015-01-22 at 7 51 19 pm](https://cloud.githubusercontent.com/assets/261579/5868667/dcb6abcc-a27a-11e4-8819-4b9424706981.png)
- [x] File, Open Font, now opens in `/` instead of `~` which is very confusing. Change it to open in `~` :)

![screen shot 2015-01-22 at 8 13 14 pm](https://cloud.githubusercontent.com/assets/261579/5868670/eec9a724-a27a-11e4-8e79-40157bd65eea.png)
### Metrics View weirdness
- [ ] In the metrics view left side bar, clicking the items should toggle them; currently clicking activates and shift clicking deactivates...
- [ ] In metrics view, after going View, Set Point Size, the hotkeys make no sense. Fortunately the fix will be to just redefine the hotkeys to something sensible.

![screen shot 2015-01-22 at 8 22 01 pm](https://cloud.githubusercontent.com/assets/261579/5868694/3cf3bdf4-a27b-11e4-9720-b027592217b8.png)

![screen shot 2015-01-22 at 8 22 02 pm](https://cloud.githubusercontent.com/assets/261579/5868697/452ffcee-a27b-11e4-94f4-9060fc6a911d.png)
### More View options
- [ ] View, Show, Horizontal Metrics Lines is on by default, but only shows the `Element, Font Info, General, Ascent` + `Descent` lines, and baseline, not the `Element, OS/2, Metrics, X Height`; this should become a submenu item, 
- [ ] with each line its own child item in the submenu, 
- [ ] including X Height, and 
- [ ] that X Height item should be on by default
- [ ] View, Show, Horizontal Metrics Lines, also toggles the advanceWidth line's visibility; that should become 2 new child items, `Origin Line` and 
- [ ] `Width Line`
### Fine points OS X integration
- [x] ~~when you double click a glyph slot in FontView, the CharView window opens, but pretty small. Can CharView windows open 'maximized'?~~ @frank-trampe suggested this would be unwelcome, so striking it out. Anyway, here is the window pretty small:

![screen shot 2015-01-22 at 7 54 26 pm](https://cloud.githubusercontent.com/assets/261579/5868673/f7fc341a-a27a-11e4-9a51-b3aef60af575.png)
- [ ] After clicking the window maximize button (on mac, a green ball button) on the window title bar to make it maximized, the viewport doesn't run 'fit', and the glyph drawing area remains rather small. When I run fit it becomes better sized. Can this triggering of `fit()` after maximizing be done automatically? Here is the fit view:

![screen shot 2015-01-22 at 7 57 16 pm 2](https://cloud.githubusercontent.com/assets/261579/5868680/0962d2d6-a27b-11e4-9396-63aafb8b6403.png)
### Better Fit

 The View, Fit method could be smarter.
- [ ] For a blank glyph, the viewport could be fitted to the emsize + advanceWidth. Eg,

![screen shot 2015-03-12 at 7 02 21 am](https://cloud.githubusercontent.com/assets/261579/6608846/be27b026-c885-11e4-84ed-d7cc3389066e.png)
- [ ] For a glyph that exceeds the emsize in height, its bbox should be used rather than the emsize - which is what I think happens right now
- [ ] The zoom should be closer. For example this `Nacute` is shown at this size, which is too small as there is LOADS of room above and below:

From

![screen shot 2015-03-12 at 7 02 46 am](https://cloud.githubusercontent.com/assets/261579/6608896/465bc0cc-c886-11e4-91ba-15bb2a3a2c9b.png)

To

![screen shot 2015-03-12 at 7 02 54 am](https://cloud.githubusercontent.com/assets/261579/6608902/571daae2-c886-11e4-8267-3989f63081c6.png)
- [ ] It should fit the origin to the left side of the window, so there is space to add a glyph to right in the multi glyph input box. 

From 

![screen shot 2015-03-12 at 7 02 54 am](https://cloud.githubusercontent.com/assets/261579/6608886/2a80870c-c886-11e4-9e34-11acfd30eb81.png)

To

![screen shot 2015-03-12 at 7 03 02 am](https://cloud.githubusercontent.com/assets/261579/6608872/051521f8-c886-11e4-8bbd-2241e747c8c0.png)
### Kerning interaction
- [ ] After adding a lookup and kern subtable, then clicking an empty kern cell in the metrics window, the dialog to add a subtable appears (right in image below)

![screen shot 2015-03-12 at 6 39 45 am](https://cloud.githubusercontent.com/assets/261579/6608545/cb2a3d8c-c882-11e4-82b3-8f0ca5f01cdb.png)

The lookup subtable drop down selection shows which subtable is currently in use, so there should not be a dialog window appearing here. Instead, the Kern by Classes window should open directly:

![screen shot 2015-03-12 at 6 48 43 am](https://cloud.githubusercontent.com/assets/261579/6608652/df94a248-c883-11e4-911c-de2a7d86df10.png)

When I draw an A, a V, open a metrics window, type in AV, and then set the kerning value, the Create Lookup window appears correctly, I create a horizontal kerning lookup, and then I create a First Char class with A and a Second Char class with Z and...
- [ ] ...there is no way to cycle through the items in the Left Side or Right Side classes; there is a drop down but this is excruciating to click and click and click when there should be a button to click, and a hotkey to press, to cycle.

![screen shot 2015-01-22 at 8 37 10 pm](https://cloud.githubusercontent.com/assets/261579/5868712/708cc570-a27b-11e4-9a31-a78f7a821a52.png)
- [ ] ....when I clicked the left class and then the right class, a pop up appears that I had to click saying "Everything Else" blah blah. This message also appeared in the Messages window. So remove that dialog, it was super annoying. 
- [ ] ....when I clicked the left class and then the right class, I got a crash. However, when I tried the same thing again, I could not reproduce... but in general this dialog needs more QA testing and crash fixing :)
- [x] I also saw that the crash protection appeared to work then, but my lookup was not recovered, but there no Undo in the `Kerning by Classes` window, so no actions to be autosaved, so I guess this is a major request; and its in another issue, thus checking this off here.
- [ ] The Metrics View subtable dropdown's `New Lookup Subtable...` action doesn't work, as subtables created on existing lookups don't appear in the Metrics, Kern by Classes, list, and attempting to 'Create a New Lookup' from this doesn't do anything. 

![screen shot 2015-03-12 at 6 51 08 am](https://cloud.githubusercontent.com/assets/261579/6608717/5d29a956-c884-11e4-91e3-b03f7586dc8e.png)
### Better drawing interaction
- [x] #2050 seems important to make FF really actually useful for drawing glyphs with. 
- [ ] When you turn on CharView, View, Show, Control Points (Always) then you can not marquee select offcurve control points, only oncurve points; it would be good to be able to marquee select offcurve points when `Ctrl` is pressed

**Comment by lemzwerg** [comment]
Uh, oh, having so much different bug reports in a single issue is hard to maintain...  Anyways, it's not my job to tell you this :-)

Regarding fc-cache: Instead of adding specialized code for scanning only a subset of the system's directory, I suggest that fc-cache is run at installation time, where users expect that it may take some time until everything is done.  Doing so should shorten the start-up of the first call of the FontForge app considerably.

**Comment by adrientetar** [comment]
> I also saw that the crash protection appeared to work then, but my lookup was not recovered, but there no Undo in the Kerning by Classes window, so no actions to be autosaved, so I guess this is a major request...

That is #1621, fwiw.

**Comment by davelab6** [comment]
> I suggest that fc-cache is run at installation time, where users expect that it may take some time until everything is done. Doing so should shorten the start-up of the first call of the FontForge app considerably.

The way installation in Mac OS X goes is you drag the app bundle from the DMG disk image to the Applications folder ;) Its possible that we could set up a PKG installer, but I think its better to run fc-cache sanely.

**Comment by davelab6** [comment]
@frank-trampe I updated the main issue to prioritize all the things

**Comment by lemzwerg** [comment]
Dave, I don't know how the installation process works on OS X – do you say that it is not possible to make the dragging operation trigger the start of a script?

**Comment by davelab6** [comment]
Yes

**Comment by adrientetar** [comment]
> - The default value of Element, OS/2, Metrics, X Height is 0 but should be 500.
> - Turn off CharView, View, Show, Control Points (Always) by default

I disagree with these changes esp. the first one.

**Comment by davelab6** [comment]
I believe other editors (robofont, glyphs) use 500 as a default x-height. 

Always showing control points often clutters the screen and is off-putting in the first few hours of beginners use, and since turning it on is just a few clicks away (and is stored as a pref) I don't see the harm in changing this :)

**Comment by adrientetar** [comment]
> Always showing control points often clutters the screen and is off-putting in the first few hours of beginners use, and since turning it on is just a few clicks away (and is stored as a pref) I don't see the harm in changing this :) 

Clutters the screen? We're talking about designing, not using the fonts. The defaults need to be optimized defaults, not something you have to change everytime you install the program.

The first time I started FontForge, I had no experience with Casteljau (Bézier) curves whatsoever. But CPs are actually what you look for and look at when designing. It happens quite rarely but if I want to preview what I've drawn in the CharView I'll just use the preview keystroke.

**Comment by davelab6** [comment]
Clutters the screen so that selecting the control points you want can be hard, because other nearby control points are selected instead. The size of the points was increased because their target click area was said to be too small, and the 2 things combined degrades the user experience for people on laptops with smaller screens. There's another workshop coming up this weekend, I'll ask the participants about it. (You don't have to change it each time up install, because its a user pref, and your prefs are in your home dir?)

And the x height? :)

**Comment by adrientetar** [comment]
I see. For me things work okay since SnapDistance was decreased, the size of the points are not problematic to me (and my particular computers I guess).

For the xheight I don't think it makes sense to define a default value. At least if it's not present in the font, programs or font editors who need it may calculate it from the height of the x glyph or at least they can assert that the value just wasn't set. I don't see the point of setting an arbitrary value if it's going to be wrong most of the time anyways, regardless of what other font editors may be doing.

**Comment by davelab6** [comment]
Still seems slow :(

**Comment by frank-trampe** [comment]
@davelab6, can you check that your copy of fcprogress.pl has the new fc-cache call?

**Comment by ctrlcctrlv** [comment]
I don't have a Mac so can't test some of these, while some of them I don't actually think are issues. (Auto-running fit on resize would definitely annoy me now that I'm used to how it works.)

Closed per [G2B](https://github.com/fontforge/fontforge/wiki/Community-guidelines#g2b-wish-lists).
