### ISSUE TITLE
Bouncing dock icon on Macintosh

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#2058]
@davelab6 noted in #2055 that the dock icon for FontForge can bounce indefinitely on the Macintosh now that we have removed the Carbon event loop (#2004).

This [article](http://www.alecjacobson.com/weblog/?p=3581) has instructions for fixing the problem.

I propose that, in startui.c, we add the event sender like this (perhaps with the support function copied in directly before fontforge_main()). I don't like to put dangling block starts and ends in conditional macros, which is why I have a duplicate if statement.

```
#if defined(__Mac)
    if ( listen_to_apple_events ) {
        install_apple_event_handlers();
        install_mac_timer();
        setup_cocoa_app();
        RunApplicationEventLoop();
    } else
        cocoa_says_stop_bouncing();
    if ( listen_to_apple_events )
#endif
    if ( doopen || !any )
        _FVMenuOpen(NULL);
    GDrawEventLoop(NULL);
    GDrawDestroyDisplays();
```

I would need to get a lot of Homebrew stuff working in order to test this. Can @DomT4 try this?

**Comment by davelab6** [comment]
Homebrew should be easy to get going. Install it as normal, edit fontforge.rb to point to your own git repo, and install HEAD as normal to install your own repo.

**Comment by DomT4** [comment]
Yeah, If it's just a case of replacing those lines you can either copy and paste the Fontforge formula into downloads, point it at your Git repo, and then do ` brew install -v ~/Downloads/fontforge.rb --HEAD ` or similar, or you can do a git diff locally and then stick it at the bottom of the Fontforge formula with:

```
__END__

diff --
a/blah
b/blah
```

Etc. And then somewhere before ` def install ` kicks in just write ` patch :DATA `.
