### ISSUE TITLE
Macintosh .app building problems

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#2059]
I was trying to make an .app bundle for Macintosh using the tools in the osx folder. The instructions point to a script called force_rebuild.sh and to another script called create-osx-app-bundle.sh. I tried running these and iteratively adjusting things in order to get them to work. force_rebuild.sh, instead of forcing a rebuild of the current source tree, seems to install FontForge from MacPorts, and create-osx-app-bundle.sh subsequently generates a dmg containing an app bundle with no executable.

I then tried the stuff in travis-scripts. After some iterative adjustments, I got all the way to the step `brew install fontforge --HEAD --with-x`, which failed looking for a directory `/Library/Caches/Homebrew/fontforge--git`.

I am hoping that somebody with knowledge of this subject (@monkeyiq, perhaps) could clarify how one would go about building an app bundle for the Macintosh (including preparing the build environment).

**Comment by larsenwork** [comment]
has this been clarified? I'd like to be able to build too :)
