### ISSUE TITLE
can't change keyboard layout in windows

### ISSUE THREAD

**Issue by sergey-s-betke** [fontforge/fontforge#2065]
I have read #1908 and #1729. And I can't change keyboard layout:

    start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error -xkbmodel pc105 -xkblayout en,ru -xkbvariant winkeys -xkboptions grp:ctrl_shift_toggle

I can input just latin and digits.

If I test next command line:

    start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error -xkblayout ru

I can't input any chars (and latin, and digits). 

Please, help me with correct command line for support `ru` layout.

**Comment by jtanx** [comment]
I've just had a quick check, and it loks like VcXsrv isn't handling the keymap change:

~~~~~
Warning: Locale not supported by X, falling back to 'C' locale.
(II) AIGLX: enabled GLX_SGI_make_current_read
(II) AIGLX: enabled GLX_MESA_copy_sub_buffer
(II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
(II) AIGLX: enabled GLX_SGIX_pbuffer
(II) AIGLX: enabled GLX_ARB_multisample and GLX_SGIS_multisample
(II) 60 pixel formats reported by wglGetPixelFormatAttribivARB
(II) AIGLX: Set GLX version to 1.4
(II) GLX: Initialized Win32 native WGL GL provider for screen 0
(EE) Error loading keymap C:\Users\\AppData\Local\Temp\server-0.xkm
(EE) XKB: Failed to load keymap. Loading default keymap instead.
winBlockHandler - pthread_mutex_unlock()
winClipboardThreadProc - DISPLAY=127.0.0.1:0.0
~~~~~

**Comment by sergey-s-betke** [comment]
For a workaround, may be, I must to copy some files to %temp%? Or not?

**Comment by jtanx** [comment]
Hmm... I don't know. I tried with a full install of VcXsrv and it didn't work either. I wouldn't know where to get that file either.

**Comment by sergey-s-betke** [comment]
may be previous versions of VcXsrv? 

Other question: how I can encode Unicode string for "manual" storing them in to .sfd file? As a workaround...

**Comment by jtanx** [comment]
You could use something like notepad++ I guess, just make sure that it saves to UTF-8 (Encoding menu; should be the default option).

Another method might be to write out your text, and then to copy-paste it into FontForge.

**Comment by sergey-s-betke** [comment]
Copy-paste doesn't work, I have tested this solution first.

Yes, I use notepad++. But non ANSI strings to `LangName` are encoded. How can I encode my Unicode string to +XXXX form for `LangName`?

    LangName: 1033 "" "" "Normal" "" "" "" "" "" "" "Sergei S. Betke"
    LangName: 1049 "" "ujcn" "+BB4EMQRLBEcEPQRLBDkA"

**Comment by jtanx** [comment]
It looks to be UTF-7 encoded. 

Using this page:
http://kanjidict.stc.cx/recode.php

I set input-encoding to UTF-8, output encoding to UTF-7, text to be recoded as `Обычный`, and check the `Assume HTML (default: handle as plain text)` option and press convert, I get `+BB4EMQRLBEcEPQRLBDkA`

**Comment by sergey-s-betke** [comment]
ok. This is a workaround. Thank You, @jtanx.

**Comment by jtanx** [comment]
@sergey-s-betke, please try [this test build](http://sourceforge.net/projects/fontforgebuilds/files/i686/Portable/FontForge-mingw-w64-i686-d17f76-r1.7z). To use, specify:

~~~~~
start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error -xkbmodel pc105 -xkblayout us,ru -xkbvariant winkeys -xkboptions grp:ctrl_shift_toggle
~~~~~

Ensure that there are no open instances of FontForge (we need to restart the X server). Press `Ctrl+Shift` to switch to Russian keyboard layout.

Note that in the "Open Font Dialog" you can still only type ASCII characters, but everywhere else you should be able to type with your own keyboard layout.

**Comment by shaise** [comment]
It is now working for me with the official build. 
It seems jtanx solution works, but change the "-xkbvariant ,winkeys" to -xkbvariant winkeys (no comma)
So, in summary,
Goto the installation folder, edit the "fontforge.bat" file, find the line starting with:
"start /B..." and append the following: 
`-xkbmodel pc105 -xkblayout us,ru -xkbvariant winkeys -xkboptions grp:ctrl_shift_toggle`
replace 'ru' with your appropriate language
Run FontForge as usual
Please note - use Ctrl+Shift to change language, not the Alt+Shift
