### ISSUE TITLE
python problem

### ISSUE THREAD

**Issue by winds18** [fontforge/fontforge#2066]
```bash
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for PYTHON... no
configure: error: Package requirements (python-"2.7") were not met:

No package 'python-2.7' found
```
ps:Macos 10.10 python 2.7.6

**Comment by davelab6** [comment]
How are you building? With homebrew?

**Comment by winds18** [comment]
i set the env variable ```PYTHON``` it is ok

**Comment by davelab6** [comment]
Problem fixed? :)

**Comment by winds18** [comment]
en, it is ok

**Comment by groversachin** [comment]
install python27-devel. this solved the issue.

**Comment by garyblocks** [comment]
@winds18 I am facing the same issue, how did you set the PYTHON variable?

**Comment by jtanx** [comment]
@garyblocks do you have the python development headers installed (e.g. `libpython2.7-dev` or `python27-devel`)? If you're sure you do and it's still not working, then there is a manual override:

```bash
export PYTHON_CFLAGS=/path/to/python2.7/includes
export PYTHON_LIBS=-lpython2.7
```

The exact flags vary depending on your system. 

```
pkg-config --cflags python-2.7
pkg-config --libs python-2.7
```

Should tell you what those values should be. Failing that,

```
python-config --cflags
python-config --libs
```

should also work.

**Comment by garyblocks** [comment]
@jtanx Thank you for your solution, I tried export both PYTHON_CFLAGS and PYTHON_LIBS, no luck with that, but since I am using ubuntu, the package names seems different. I solved it by install python-dev and libpango1.0-dev.

**Comment by MrBenGriffin** [comment]
For modern python, you can use 
```
python3-config 
python3-config
```
so then use 
```
export PYTHON_CFLAGS=`python3-config  --cflags` && export PYTHON_LIBS=`python3-config  --libs`
```
