### ISSUE TITLE
FontForge Save Issue to TTF

### ISSUE THREAD

**Issue by paulceg** [fontforge/fontforge#2069]
I am attempting to save a .sfd file to a .ttf file. I am currently using Windows Vista.
Every time I attempt to save the file FF states the save failed, with the following error message.
FF version 15:20 AWST 31-Dec-2014

Internal Error:
Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful. File Offset wrong for ttf table (name-data), -1 expected 174

I have the same program running on my office Windows XP and it works flawlessly. How do I get past this issue to save them on the Vista machine? I am not very tech savvy, simple a designer wanting to make fonts.

I apologize if the solution is already in the forum. I was unsuccessful in finding it.

**Comment by adrientetar** [comment]
cc @jtanx

**Comment by paulceg** [comment]
Here is the link to the .sfd file.
https://www.dropbox.com/s/09nid0wf82molvp/DaniRae1.sfd?dl=0

**Comment by jtanx** [comment]
I've just tried saving that file to TTF on Windows 8 (same FF version), and I get no errors. The TTF file is OK. Hmm...

**Comment by paulceg** [comment]
I have 32 bit Vista.
I also do not have issues using XP at work and creating the TTF file. It is only with Vista where the error occurs.

**Comment by harryspier** [comment]
I just started using FontForge and have the same problem and same error message on a Windows 7 64 bit machine. .  Does it only work under Windows XP ?

**Comment by jtanx** [comment]
No, it should work on all versions from XP and up. Just to clarify - what locale is your Windows set to - i.e. is it set to English, German, French or something else? When you save the file, are there any non-English characters in the path (anything other than A-Z, 0-9)?

**Comment by harryspier** [comment]
Thanks Jeremy,

My locale is English and there are no non-english characters in the path

**Comment by harryspier** [comment]
I've just downloaded the latest version for Windows and the save problem
went away.
