### ISSUE TITLE
References and paste into

### ISSUE THREAD

**Issue by Alatius** [fontforge/fontforge#2071]
Pasting a reference into a glyph will delete any preexisting references in the glyph. To reproduce:
Draw something in A and B.
Copy A as reference and paste in C.
Copy B as reference and paste _into_ C.
C should now consists of one reference to A and one reference to B, but unfortunately the A reference has disappeared.
This worked correctly in the 2014-01 release, but is broken in the 2014-10 stable release. The behaviour is still faulty in the latest GIT version.

**Comment by Alatius** [comment]
I figured it out, it is due to commit e6cabc302f0bc850afd4c8c42a8a41574d41da0d. The original code had a simple implemention of a single linked list which grew at the head, but that commit unnecessarily added complexity by growing the list at the tail and using a separate reference to the last item in the list. Unfortunately, that reference was never actually set to point at the last item of the preexisting list. Easiest and cleanest would be to simply revert that commit.
I tried to follow the instructions for contributing patches, but got access denied when I tried to push my fork. Being a total git noob, I don't know whether I made some silly mistake, or if I simply need to ask for write permission first.

**Comment by jtanx** [comment]
You have to first fork the repo (see top right corner of github). You can then push changes to your fork, and then you can submit a pull request to merge your changes. However, that commit must have been to achieve some goal, so I don't think it's a simple as just reverting it, since reverting it would also revert the 'fix' for whatever behaviour it was trying to fix.

**Comment by davelab6** [comment]
Looks like it was for https://github.com/fontforge/fontforge/issues/1268

**Comment by Alatius** [comment]
Ah, thanks @jtanx, I had confused forking in github and branching in git... Oops! I see now also the benefit of maintaining the order of the references, as per @monkeyiq's patch. I've fixed the initialization of the "last" pointer, and made a pull request, mainly because I'm curious to see how it works.

**Comment by davelab6** [comment]
@Alatius what platform are you using? :)

**Comment by Alatius** [comment]
I'm on Linux (currently Linux Mint 17.) Why? :-)
