### ISSUE TITLE
FontForge crashed in Windows XP after saving kerning pairs.

### ISSUE THREAD

**Issue by viterzbayraku** [fontforge/fontforge#2081]
I am using Fontforge for create cyrillic font and have some problem with metric window. I can not type cyrillic letters and can not save kerning rules. After creating subtables for kerning and push OK button FontForge is crashed.

**Comment by jtanx** [comment]
Is this still an issue - and if so, do you want to reopen this issue?

**Comment by viterzbayraku** [comment]
New version do not have bug with saving, but still correctly do not saving kerning rules. Savin process have a lot of new opening windows, fontforge asking a lot times about new names of subtables. And as result kerning rules do not saving. I putting cursor to kerning line in metric window for change number of kerning offset, but FontForge asking new name of filter. It is strange, and i don't khow, how it working.
