### ISSUE TITLE
Symbol not found: _PyBool_Type

### ISSUE THREAD

**Issue by lakenen** [fontforge/fontforge#2085]
I get the following when I run `fontforge` on the command line (installed from source @ master):

```
dyld: Symbol not found: _PyBool_Type
  Referenced from: /usr/local/lib/libfontforge.2.dylib
  Expected in: flat namespace
 in /usr/local/lib/libfontforge.2.dylib
Trace/BPT trap: 5
```

On OS X 10.9.5, configured with this command to work with homebrew:

```
PATH="/usr/local/Cellar/gettext/0.19.4/bin/:${PATH}" \
  CFLAGS="-I./libltdl" \
  LIBPNG_CFLAGS="-I/usr/local/lib" \
  LIBPNG_LIBS="-L/usr/local/lib" \
  ZLIB_CFLAGS="-I/usr/lib" \
  ZLIB_LIBS="-L/usr/lib" \
  PYTHON_CFLAGS="-I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7" \
  PYTHON_LIBS="-L/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config" \
  ./configure --with-pythonbinary=/usr/local/bin/python
```

**Comment by lakenen** [comment]
For what it's worth, the python bindings work. I just get that error when I run fontforge on the command line.

**Comment by davelab6** [comment]
@lakenen how did you build it? I tried on a clean install with homebrew and its ok... both with last release and head

**Comment by lakenen** [comment]
I built from source with the configure command above, then `make`

**Comment by davelab6** [comment]
no homebrew?

**Comment by lakenen** [comment]
It works fine from homebrew. The issue is with installing from source.

**Comment by davelab6** [comment]
I'm curious! Why would you do that? :) If it works in Homebrew, why not just use Homebrew?

**Comment by lakenen** [comment]
I'm developing against fontforge with the python bindings, and I occasionally run into bugs like this: https://github.com/fontforge/fontforge/issues/2086 :)

**Comment by davelab6** [comment]
Okay :) I don't understand the aversion to homebrew in this case though :)

**Comment by lakenen** [comment]
Reason being I can apply the patch locally even if it's not merged.

**Comment by davelab6** [comment]
apply patch to your fork of ff and update the recipe tobpoibt head to you
repo?

**Comment by frank-trampe** [comment]
It's possible to have Homebrew build something that isn't in the main Homebrew tree. I will follow up when I'm back at the office on Monday.

**Comment by lakenen** [comment]
FWIW, I'd prefer to be able to build from source without homebrew. Is there something wrong with the way I've configured the build?

**Comment by jtanx** [comment]
I use a variant of

```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig  ./configure --enable-gdk=gdk3
```

Which works for me.

Travis also builds using homebrew - https://github.com/fontforge/fontforge/blob/master/.travis.yml

Reopen if you're still having this issue.
