### ISSUE TITLE
Segmentation fault when opening font.

### ISSUE THREAD

**Issue by lakenen** [fontforge/fontforge#2086]
I am getting a segfault when opening a font with fontforge. The font file in question can be downloaded here: https://cloud.box.com/shared/static/v08w1ptjbry7nd962jgilay82pxwgxre.pfa

To reproduce this issue, I'm running the homebrew version of fontforge (though I believe this issue persists on master as well). This is the command I've used to reproduce:

```
FONTFORGE_LANGUAGE=ff fontforge -c 'Open($1)' 33.pfa
```

See the output here: https://gist.github.com/lakenen/0b0ff36997000ea82ee9

**Comment by lakenen** [comment]
I'm sure this font is super messed up in some way, but it shouldn't segfault, right? :)

**Comment by tshinnic** [comment]
Using older UI, before crashing (FF 2014-10-14) it pops up with "Font file has bad glyph count field. maxp says: 93 sizeof(loca)=>187" so, yes, I'd assume the file is a bit cockeyed, but, no, FF shouldn't crash.  Though it might be that it tried to run even though seeing the file was at best inconsistent.  Oh my, looking at your gist I see that same message and a heck of a lot more.  Wow, torture test!

**Comment by lakenen** [comment]
I'd love to get my hands dirty and debug this myself, but I have no clue where to begin!

**Comment by adrientetar** [comment]
You can fix the crash with this:

~~~
diff --git a/fontforge/parsettfatt.c b/fontforge/parsettfatt.c
index 44a2436..24b0de3 100644
--- a/fontforge/parsettfatt.c
+++ b/fontforge/parsettfatt.c
@@ -1819,7 +1819,7 @@ return;
 	/*  assuming this lookup is tagged with a feature... */
 	if ( fl!=NULL )
 	for ( i=0; glyphs[i]!=0xffff; ++i ) if ( glyphs[i]<info->glyph_cnt ) {
-	    if ( info->chars[glyphs[i]]->name!=NULL ) {
+	    if ( info->chars[glyphs[i]] != NULL && info->chars[glyphs[i]]->name!=NULL ) {
 		which = format==1 ? (uint16) (glyphs[i]+delta) : glyph2s[i];
 		if ( which<info->glyph_cnt && which>=0 && info->chars[which]!=NULL &&
 			info->chars[which]->name==NULL ) {
~~~

However as the message that came before the crash say it seems FontForge cannot read any of the glyphs properly as if there is an offset in the tables or sth (or a bug in the opening code if your file id valid). 
In fact I'd say if the font was in a readable state the struct element up here simply shouldn't be NULL.

**Comment by davelab6** [comment]
so you dont apply the patch? seems good to me to not crash (and thus apply
this to master)

**Comment by lakenen** [comment]
@adrientetar thanks for the patch. That worked for me. I'm using the python bindings, so I was wondering if there's any way I can catch segmentation faults in the future when doing (or other fontforge operations):

```
font = fontforge.open(pfafile)
```

**Comment by adrientetar** [comment]
You can catch segfaults with a debugger.

**Comment by lakenen** [comment]
No I mean, how do I stop it from crashing my python code in production?

**Comment by adrientetar** [comment]
[These](http://stackoverflow.com/questions/22250893/capture-segmentation-fault-message-for-a-crashed-subprocess-no-out-and-err-af) methods may work. I have never tried such a thing.

**Comment by lakenen** [comment]
@adrientetar is this patch going to be merged?
