### ISSUE TITLE
Open Font Library Register URL is 404

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge#2087]
404: http://www.openfontlibrary.org/media/register

Correct: http://openfontlibrary.org/en/up

I believe it is this file that needs update (line 2028): https://github.com/fontforge/fontforge/blob/b1cb16dfe1ff153e90ad823a506e21bb37f8afca/fontforgeexe/savefontdlg.c

**Comment by adrientetar** [comment]
I had removed this functionality because it's completely broken but my patch caused a crash of the save dialog and I didn't investigate further. If you want to remove it go ahead.

**Comment by adrientetar** [comment]
Now dropped. #2159

**Comment by andreaslarsen** [comment]
ah, somehow missed your reply 29 days ago, but great
