### ISSUE TITLE
how to add integral coordinates for svg files automatically

### ISSUE THREAD

**Issue by duckravel** [fontforge/fontforge#2088]
I have some svg files and try to make it in the ttf form. However, it seems that svg files which create by other program can not have integral coordinates automatically ( I had checked the preference setting, and set snaptoINT to on). I have to go through the non-integral coordinate check every time I tweak a glyph. It there any way to figure out the problem ?

**Comment by davelab6** [comment]
round to int, is the ff command you need

**Comment by larsenwork** [comment]
assuming it was answer enough
