### ISSUE TITLE
Mniature pop-up windows

### ISSUE THREAD

**Issue by kosalaya** [fontforge/fontforge#2096]
miniature pop-up windows on taskbar show the same image.
i expect to see a thumbnail of each opened window of FF like in other applications. 

when taken the curser over them.
on windows 7 latest stable fontforge 

![img_20150302_142914](https://cloud.githubusercontent.com/assets/8073976/6438356/40f85e6e-c0ee-11e4-946a-c1f0c5813cdd.jpg)

**Comment by jtanx** [comment]
The thumbnails are likely controlled by VcXsrv, which is what is used to display X11 programs on Windows. So the fix would need to come from VcXsrv.
