### ISSUE TITLE
turning off fit to em, but ignoring certain large glyphs

### ISSUE THREAD

**Issue by Kelvinsong** [fontforge/fontforge#2100]
if a font includes very large glyphs (giant radical symbols or parentheses for example), turning off fit-to em will make the glyphs too small

**Comment by adrientetar** [comment]
Then why would you turn it off?

**Comment by Kelvinsong** [comment]
Fit to em zooms in too much—Accents and stuff often fall outside the Em square

**Comment by khaledhosny** [comment]
See [this](https://bitbucket.org/sortsmill/sortsmill-tools/commits/4c9a3b897b8af0d7b560573e814bc770c0b9adde?at=master) and [this](https://bitbucket.org/sortsmill/sortsmill-tools/commits/da4c16662b819b0d2650529a86aa9102674a5ad4?at=master) Sorts Mill Tools commits which try to fix the same issue (albeit in a slightly different way).

**Comment by adrientetar** [comment]
Looking good, I will cp

**Comment by Kelvinsong** [comment]
thank you!
