### ISSUE TITLE
Collaboration menu not on Ubuntu PPA

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2106]
The Collaboration menu is missing on Ubuntu PPA on 14.04

`Tools> Start web server in collab mode` is active and when clicked gives an Unhandled exception error.

![screenshot from 2015-03-02 09 27 35](https://cloud.githubusercontent.com/assets/6846609/6479113/d7bc4eb4-c265-11e4-9697-944b4c732985.png)

**Comment by davelab6** [comment]
@frank-trampe says this is because `czmq` isn't packaged anywhere

**Comment by pathumego** [comment]
@frank-trampe would this fix the issue? Can a `czmq` ppa added to Fontforge ppa?   Could this  solve the problem ?  https://launchpad.net/ubuntu/+source/czmq

**Comment by zoghal** [comment]
As well as windows

**Comment by jtanx** [comment]
With no active development on the collab feature, there are currently no plans to bring collab to Windows.

**Comment by zoghal** [comment]
@jtanx do you know exist any document for api collab ?
I have an idea for collab on windows, just don't know how I handle events for any changes.

**Comment by jtanx** [comment]
No I'm not aware of any specific API for it. You're best off looking at the source code for it e.g. [collabclient.c](https://github.com/fontforge/fontforge/blob/master/fontforge/collabclient.c) and [collabclientui.c](https://github.com/fontforge/fontforge/blob/master/fontforgeexe/collabclientui.c).

As far as I know, it works by using ZeroMQ to communicate between instances of FontForge. In terms of the message structures used and anything like how messages are sent/interpreted, I don't know.

**Comment by davelab6** [comment]
It uses undo serialization

**Comment by skef** [comment]
Collab was removed.
