### ISSUE TITLE
Ubuntu PPA icon 

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2107]
App icon on the Ubuntu PPA is an old low resolution icon. Replacing with icon used on OSx release seems better. 

![screenshot from 2015-03-02 09 27 35](https://cloud.githubusercontent.com/assets/6846609/6479157/97e848a0-c266-11e4-9c34-0c49912a4e11.png)

**Comment by andreaslarsen** [comment]
I think I still have the raw file somewhere - if you need other sizes let me know

**Comment by frank-trampe** [comment]
Send that to me if you can; I would prefer to avoid the trouble of converting from an icns file.

**Comment by frank-trampe** [comment]
Never mind. I just found it elsewhere in the tree.

**Comment by davelab6** [comment]
@pathumego is this working for you?

**Comment by pathumego** [comment]
Yep Its updated to the Old browo letterpress FF icon. But not the new white Icon ships with Mac. I was expecting to see the White Icon :)

But the icon in the about menu seems to be the white one.

![screen shot 2015-05-07 at 11 43 28 am](https://cloud.githubusercontent.com/assets/6846609/7509594/43a159ae-f4b0-11e4-9ca6-ad737e857d4d.png)

**Comment by andreaslarsen** [comment]
Some people felt the new icon didn't fit in windows/linux style so I believe it's only used for mac :)
