### ISSUE TITLE
Scripting: DefaultRoundToGrid() not being set properly?

### ISSUE THREAD

**Issue by weiweihuanghuang** [fontforge/fontforge#2112]
I'm running a script `Open($1);DefaultRoundToGrid();Generate($1:r + "-New.ttf");Close();` to set the ROUND_XY_TO_GRID bit in the [glyf table](http://www.microsoft.com/typography/otspec160/glyf.htm) for composite glyphs. If I am understanding correctly what this scripting function is supposed to do then the results are not correct.

When I check the the ttx dump for the font generated by FF, it has set flags="0x0000" which when compiled is not producing the desired effect. Werner Lemberg informs me it should be flags="0x4", this produces the correct result.

**Comment by adrientetar** [comment]
I think you need to run `SelectAll()``before doing it.

**Comment by adrientetar** [comment]
Here is the documentation:

> DefaultRoundToGrid()
> Looks at all selected glyphs, if any reference is not positioned by point matching, then FontForge will set the truetype "ROUND-TO-GRID" flag for the reference.

http://fontforge.github.io/scripting-alpha.html

Please look at the documentation before opening an issue.

**Comment by weiweihuanghuang** [comment]
My apologies, I tested the flag setting and they produce the expected result. The new flag is:
`flags="0x1004"` 

but the autohinting result is correct.
