### ISSUE TITLE
SVG import will crash FF

### ISSUE THREAD

**Issue by philipz-59** [fontforge/fontforge#2122]
When in outline font mode "Element > Font Info > Layers > Outline Font",
importing svg with stroke width=1e-9 into glyph will crash FontForge.

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- 2015-03-07 12:59:10 Generated by QCAD SVG Exporter -->
<svg width="30mm" height="30mm" viewBox="11 -43 30 30" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">
    <g transform="scale(1,-1)">
        <!-- Line -->
        <path d="M11,13 L41,43 " style="stroke:#000000;stroke-width:1e-9;"/>
    </g>
</svg>
```

**Comment by adrientetar** [comment]
cc @tshinnic

**Comment by skef** [comment]
This fails an assertion in the debug compilation of the current `stroke` branch. I haven't yet verified whether it works in release mode.

**Comment by skef** [comment]
With #4126 merged this import triggers an assertion when compiled with debug and some errors and a "I'm sorry this file is too complex for me to understand (or is erroneous)" message. Editing the stroke width up there is a point where you get a tiny blob (around 1e-1) and around .5 you start getting a stroked line. 

We could put more checks and workarounds in, like pre-scaling the source to make good output more probable. But for now the error-in-release, assertion-in-debug combo seems appropriate to me. Closing.
