### ISSUE TITLE
OS/2 fsSelection (style map) support

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2131]
They are `sf->pfminfo.os2_family_name` and `sf->pfminfo.os2_style_name` in the program. These values are not accessible neither from the UI nor from scripting, they are only roundtripping in OpenType fonts and SFD files for now.

I need these values because they are used for the UFO styleMap (see [here](https://github.com/fontforge/fontforge/blob/c07b08eaa81d807352c455975cc74053bd82d790/fontforge/ufo.c#L1089)) which maps Bold and Italic buttons to select weights e.g on Windows.

**Comment by davelab6** [comment]
I thought FF uses another value to 'automatically' set these?

**Comment by adrientetar** [comment]
I see no code that does this, and styleMapFamilyName and styleMapStyleName are not output for my fonts.

**Comment by adrientetar** [comment]
@davelab6 @frank-trampe: re on 80483839af13f7da54b76a6859ffb58a44dcb444 and adobe-fonts/source-sans-pro#47.

For styleMapStyleName, the UFO spec says "Style map style. The possible values are *regular*, *italic*, *bold* and *bold italic*. These are case sensitive." Are we indeed pulling out these values in lowercase?

Secondly, there should a way to set these inside FontForge, and here's why: they control the style-linking on Windows as I said previously, except that sometimes you want want to associate these things a bit differently e.g. use weight 600 as Bold link instead of 700.

Robofont has four checkboxes for that:

![](http://doc.robofont.com/wp-content/uploads/2011/12/font-info-sheet.png)

**Comment by adrientetar** [comment]
That being said, all italic style should (usually) map to italic and weight 700 is often the default, so I think using that as a default until the user overrides the parameters is a good thing.

**Comment by khaledhosny** [comment]
Why is those fields are in the OS/2 table? The [spec](http://www.microsoft.com/typography/otspec/os2.htm) has nothing like that AFAICT.

**Comment by adrientetar** [comment]
@khaledhosny You are right: they aren't part of the spec. In fact, [looking at the code](https://github.com/fontforge/fontforge/blob/0e44998f1e525498f2f7c17d13aead10ae4b6185/fontforge/tottf.c#L2148), os2_family_name is copied from sf->family when importing an opentype font and if set is used in place of sf->family when exporting ot fonts. It was added in 80483839af13f7da54b76a6859ffb58a44dcb444 mostly for UFOs it seems but you're right that it's probably not the best way to go about it (esp. since it's just a copy of another attribute and cannot be modified &ndash; is that indeed its point?). @frank-trampe?

Also, are we setting fsSelection when exporting a TTF from FontForge? I don't think we are, but then again maybe I haven't found the code that does it. 
So it looks like we should get rid of os2_family_name and os2_style_name and add a style map parameter in the font info that is automatically calculated by default and can be overriden, then we can export OT fonts and UFO with this information.

**Comment by adrientetar** [comment]
Ah, [found it](https://github.com/fontforge/fontforge/blob/master/fontforge/tottf.c#L3356): it's called `os2->fsSel` and calculated from macStyle (accessible in the font info).

**Comment by adrientetar** [comment]
Okay, I'll have a look at this issue.

**Comment by adrientetar** [comment]
It looks like we have an expressivity problem: [macStyle](http://www.microsoft.com/typography/otspec/os2.htm#fss) which is what's set up in FontForge has no "Regular" field, unlike OS/2 fsSelection. fsSelection is supposed to be calculated from that... so I'd suggest we show fsSelection in the UI and calculate macStyle from it at export if it's not overriden (well, spec says these settings must not contradict eachother for that matter).
