### ISSUE TITLE
Enable space in hotkeys (so it can be used for hot preview)

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2143]
When holding `space` to pan around, it would be nice to activate the fill while held, similar to how it is currently activated with ``` ` ``` on a US keyboard, which is often much harder to access on european keyboards - holding down ``` ` + space ``` gives the effect of what I would like with only space - and this in addition to the regular fill preview. This is a simple way to get better International keyboard support.

However, `space` isn't possible to use in the hotkeys file.

**Comment by jtanx** [comment]
@davelab6, slightly off-topic but #2375 changes the behaviour slightly of the spacebar pan activation. In particular, it reverts it back to 2012-era behaviour of only panning when you click and drag vs. immediately dragging when the spacebar is activated.

I presumed this was because #6 never implemented the previous behaviour correctly, but is this actually intended behaviour?

**Comment by davelab6** [comment]
I think it's not very important; the way it works in 2012/now is like
Photoshop and how I changed out was to be like gimp is, which I prefer. But
if the preview mode is to be triggered with space bar as well as hand pan
tool, then reverting to the PS style is ok for me

**Comment by anthrotype** [comment]
:+1: for activating the fill while holding the space bar

**Comment by pathumego** [comment]
+1

**Comment by anthrotype** [comment]
I checked out @jtanx's patch #2393 and it works great!
I was also wondering, would it be possible to allow users to disable the default spacebar behaviour whereby the hand tool starts moving the canvas as soon as the spacebar key is pressed? I guess many other users who come from other font editors, or regularly switch between them, are more used to a  spacebar *plus* mouse-click hand tool...
Thanks anyway.

**Comment by davelab6** [comment]
> would it be possible to allow users to disable the default spacebar behaviour whereby the hand tool starts moving the canvas as soon as the spacebar key is pressed?

#2375 does change the behavior this way

**Comment by davelab6** [comment]
Just tested this in https://github.com/fontforge/fontforge/releases/download/20160403/FontForge-Mac-20160403.zip and its awesome!!!
