### ISSUE TITLE
Preferences Window too tall for Macbook Air users

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2149]
The Preferences Window is too tall for Macbook Air users, so users can't click the OK button or grab the handle on the bottom right to resize it.

**Comment by andreaslarsen** [comment]
Just measured it and we could shave off 130px.

**Comment by jtanx** [comment]
Related to #2401

**Comment by jtanx** [comment]
Related to #2675

**Comment by jtanx** [comment]
I think this is fixed by #2679? Reopen if not.
