### ISSUE TITLE
Mac launching incredibly slow

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2151]
I just downloaded http://fuuko.libferris.com/osx/packages/201503/14_2204/FontForge.app.dmg on a fresh machine and starting it for the first time is incredibly slow. First the icon bounces on the Dock for about a minute, and then the fc-cache CocoaDialog sits there scanning for another minute.

@frank-trampe please test this again

**Comment by davelab6** [comment]
Okay, the very first time, the long dock bounce may be because XQuartz is run for the first time

**Comment by davelab6** [comment]
I just downloaded the latest release and, even though XQuartz has been run before, it takes a while to run. But the 2nd run is very fast.

**Comment by ultrasquid** [comment]
That's the way this build line has started for a long time. I'm used to it,
but I'm sure that long dock bounce and mysterious pause can be off-putting
to a lot of users.

On Tue, Apr 14, 2015 at 8:46 AM, Dave Crossland <notifications@github.com>
wrote:

> I just downloaded the latest release and, even though XQuartz has been run
> before, it takes a while to run. But the 2nd run is very fast.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2151#issuecomment-92919951>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by andreaslarsen** [comment]
Hmm...I've reinstalled FF a couple of times (prettydmg...) and the "FontForge is scanning for fonts" has been fast most of the times but not always?

**Comment by apjanke** [comment]
Part of this may be app validation. The first time a Mac app is run, I think the OS "verifies" the entire bundle as part of the launch sequence, and at 300+ MB, that could take a while for FontForge. This happens during a long dock bounce before any UI pops up. (Happens to other programs too; remember how slow Xcode is on first launch for a new version?)

**Comment by larsenwork** [comment]
I've recently had problems with `scanning for fonts` running every time i start FF. 
What exactly does `scanning for fonts` do?
`fc-cache` also uses 100% cpu which means fans kick in until the process is done (haven't timed it but >20 sec <1 min)

**Comment by jtanx** [comment]
It's because it uses Fontconfig to load system-installed fonts for use to display the user interface (via Pango/Cairo). If you install new fonts to your system then I believe that it needs to rebuild the cache. This can be slow because it has to essentially scan every font installed in your system.

I know that you can play around with Fontconfig settings so that it avoids this; this was done for Windows back when Fontconfig was used, but with Cairo enabled, it now uses the native font API, avoiding this issue altogether.

**Comment by larsenwork** [comment]
@jtanx makes sense - I've been installing a few fonts recently. 
Would it makes sense to disable font scanning on mac to avoid this and just stick to whatever fonts we have in the FontForge app?

**Comment by jtanx** [comment]
I'm not sure how it's packaged on Mac - you would need to see if disabling font scanning would affect any other programs that rely on Fontconfig too.

If you go down this path, then you also run into problems with not being able to display some glyphs (e.g. likely the CJK glyphs in the main font view) if they don't exist in the small subset of fonts that you want to use.

**Comment by larsenwork** [comment]
@jtanx ok, seems like too big of an trade-off. 
Does anyone known which folders it is scanning? Could maybe be faster is limited to (if it isn't already)
![screen shot 2015-06-24 at 15 38 02](https://cloud.githubusercontent.com/assets/3859425/8331151/06dfb8e2-1a87-11e5-91b7-193106c59e9c.png)

**Comment by skef** [comment]
No longer taking the XQuartz approach on the mac.
