### ISSUE TITLE
sflayout.c unconditionally calls arrayfree while arrayfree is only if  _NO_FFSCRIPT not defined.

### ISSUE THREAD

**Issue by microcai** [fontforge/fontforge#2154]
arrayfree() is defined in scripting.c and guard protected by  _NO_FFSCRIPT macro

but sflayout.c unconditionally calls arrayfree without _NO_FFSCRIPT guard. thus result  link error when build without native-scripting support.

**Comment by adrientetar** [comment]
@microcai Feel free to send a PR for this.

**Comment by frank-trampe** [comment]
This is a sub-issue of #2023.
