### ISSUE TITLE
[Linux] fontforge do not respect desktop DPI settings

### ISSUE THREAD

**Issue by microcai** [fontforge/fontforge#2155]
use xrandr --dpi 192 or configure via your favourite DE GUI tools, to set DPI to 192 or what ever.

open fontforge.

font is still toooo small.

**Comment by davelab6** [comment]
FontForge uses its own X11 toolkit which has its own way of scaling. You can change the `ScreenWidthCentimeters` in your theme file - http://fontforge.github.io/xres.html - and maybe also `DefaultScreenDpiSystem` in `~/.config/fontforge/prefs`

**Comment by adrientetar** [comment]
@davelab6 Maybe this issue is about improving the automatic setting of DPI scaling, if at all present?

**Comment by niedzielski** [comment]
I agree. This is neither convenient for the user to calculate and set nor applicable to the actual rendering of the glyphs themselves. I'll share my own experience, not to complain, but to illustrate the initial difficulty presented to new designers as soon as they open the program.

For example, I recently purchased an XPS 15 9560. The [website](http://www.dell.com/en-us/shop/productdetails/xps-15-9560-laptop) lists the width and height of the chassis but fails to provide the width and height of the display area itself. One website claimed that the width and height in pixels of the display is 3840px x 2160px. Assuming square pixels and an exact diagonal of 15", I was able to calculate a width of ~13.07". Perhaps this measure could be fished out of a driver somewhere but it seems like a small pain no matter what way you go about it.

I know nothing about X resources. However, adding a ~/.Xdefaults with a single configuration of `Gdraw.ScreenWidthInches: 13.0736330569` and running `xrdb ~/.Xdefaults` took effect on program restart without any issue. Still, this seems like something the program could determine on its own with some success and I think there's precedence in other programs such as Chromium or Gnome Terminal.

Finally, I'm sorry to share that the results were ultimately disappointing. The _menu_ fonts scale (too large for some reason) but the glyphs themselves do not:

Before ~/.Xdefaults:
![screenshot from 2017-03-05 21-45-55](https://cloud.githubusercontent.com/assets/1071806/23597299/c4e4dbc4-01ee-11e7-8453-f2ae759822a2.png)

After ~/.Xdefaults:
![screenshot from 2017-03-05 21-44-08](https://cloud.githubusercontent.com/assets/1071806/23597293/bc8cf740-01ee-11e7-8aa0-e4e47bdbe186.png)

I know the tone of this report is negative but I'm thrilled to have access to this software and hope it keeps getting better! Thank you!

**Comment by davelab6** [comment]
Change the glyph cell size in the view menu

**Comment by niedzielski** [comment]
:+1: @davelab6, thanks! I multiplied Gdraw.ScreenWidthInches by 1.5 and changed the glyphs size to 48px and now the program is very readable :]

![screenshot from 2017-03-06 19-01-00](https://cloud.githubusercontent.com/assets/1071806/23638505/44a2e7c4-029f-11e7-8ece-a9da6015e370.png)

**Comment by ctrlcctrlv** [comment]
No longer valid with GDK version of FontForge, X11 is deprecated.
