### ISSUE TITLE
Failed to download ubuntu version fontforge-20150228

### ISSUE THREAD

**Issue by xsoh** [fontforge/fontforge#2170]
Trying to download fontforge using apt-get in **ppa:fontforge/fontforge** gets me this error:

> Errors were encountered while processing:
> /var/cache/apt/archives/fontforge-common_20150228-0ubuntu1~trusty_all.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by skef** [comment]
This is a distro-specific problem with an old release. Most distro questions are beyond the project's control but not all. In any case I'm closing this for now; can reopen if needed.
