### ISSUE TITLE
Hanging while try to copy/paste characters between fonts.

### ISSUE THREAD

**Issue by skywinder** [fontforge/fontforge#2177]
**Step to reproduce:**
- Open 2 different fonts in separate windows.
- Select several characters in first font.
- Right click -> copy
- Select the same range of characters in second font
- Right click -> paste

**Expected result**
- The characters should be pasted (or replaced) in second font

**Actual result**
The both windows are hanging and not response for any actions.

**System:**
OS X - 10.10.2 
XQuartz 2.7.7
FontForge - the latest available version (see #2178)

![screen shot 2015-04-02 at 10 11 56](https://cloud.githubusercontent.com/assets/3356474/6959378/06b98fb6-d921-11e4-8650-36c3346edf8d.png)

**Comment by skywinder** [comment]
@davelab6 , @monkeyiq, @adrientetar, @anoxic any updates?

**Comment by adrientetar** [comment]
@skywinder From me, no. This seems OSX specific, copy-paste works for me on other OSes.

**Comment by davelab6** [comment]
What does your XQuartz prefs look like?

![screen shot 2015-04-15 at 3 24 24 pm](https://cloud.githubusercontent.com/assets/261579/7167509/883dc540-e383-11e4-9a85-639958439764.png)

**Comment by skywinder** [comment]
@davelab6 Exactly the same for this tab

**Comment by skywinder** [comment]
**Update:**

This bug is not reproduced anymore. (probably some update or restart of computer helps).

But before close this issue would like to ask another problem that appear with the same action:

I can't copy character and got this message:
![screen shot 2015-04-16 at 15 42 38](https://cloud.githubusercontent.com/assets/3356474/7180993/7a73e2ba-e44f-11e4-8ba8-a24bbac64399.png)

What can cause this problem?

**Comment by davelab6** [comment]
Ah, if you install xquartz but don't log out and log in again it can not
work.

Glad it's fixed :)

Please read the open type specification on the ms website

**Comment by adrientetar** [comment]
> What can cause this problem?

I think the message is pretty clear, if you don't know what an anchor is then maybe you don't need to bother with this. It's likely that the destination font doesn't have anchors anyway.
