### ISSUE TITLE
`Help -> About...` menu not works.

### ISSUE THREAD

**Issue by skywinder** [fontforge/fontforge#2178]
Try to look the current version of installed FontForge, but button "About..." doesn't work (nothing happens).

**System:**
OS X - 10.10.2 
XQuartz 2.7.7

![untitled1__untitled1_sfd__iso8859-1_](https://cloud.githubusercontent.com/assets/3356474/6959466/fee9ee24-d921-11e4-90cb-117237aab593.jpg)

**Comment by larsenwork** [comment]
part of #2257

**Comment by monkeyiq** [comment]
This is very old now, but for me on osx 10.11.5 and XQuartz 2.7.9 the about menu works with FontForge version 21:52 AEST 14-Mar-2015. So maybe things broke sometime very soon after that build date. I just happened to have a version in that timeframe so thought I'd see if I could find a close data point with it.
