### ISSUE TITLE
cannot delete Xming.exe, libfreetype-6.dll and pthreadGC2.dll after uninstalling

### ISSUE THREAD

**Issue by JonasDralle** [fontforge/fontforge#2183]
This might be a duplicate of #909

I want uninstall FontForge and want to delte all files in the installation folder.
All instances of fontforge are closed and its already uninstalled via FontForge uninstaller

I cannot delete theese 3 Files (some program still uses it or something):

- FontForge\bin\Xming-6.9.0.31\libfreetype-6.dll
- FontForge\bin\Xming-6.9.0.31\pthreadGC2.dll
- FontForge\bin\Xming-6.9.0.31\Xming.exe

![imagefile](http://i.imgur.com/dskFkUb.png)

**Comment by JonasDralle** [comment]
ok sorry to bother you.
i resolved my problem by closing xming.exe

can we reopen #909?

**Comment by jtanx** [comment]
This must be a very old installation of FontForge. Xming is no longer used. In any case, Xming/Vcxsrv (what is used now) should close when FontForge closes.

**Comment by adrientetar** [comment]
> can we reopen #909?

Can you upgrade to the latest version?
