### ISSUE TITLE
program/interface language problem

### ISSUE THREAD

**Issue by zersen** [fontforge/fontforge#2190]
I'm new user and not even close to programmer. 
Installed FontForge from http://fontforge.github.io/en-US/downloads/windows/
I work on Win7 set to English version.

After installation done as the download page states: 
"Download 2015-03-30 Release Installer (.exe)
Right click, select Run as Administrative User
After installation, right click FontForge shortcut and select Run as Administrative User"

The program displays menu and all windows in Polish and there is no way I could find to change the language. 
It is difficult to get help from the Internet if I have all messages in Polish so it makes my work/learning process extremely difficult. I imagine a lot of people find it to be so.

How can I change the language to English? Please, pretty please?

I found some advice here  
http://portableapps.com/news/2013-01-02--fontforge-portable-2012-07-31-released 

"The app itself is trying to display in Russian but your PC doesn't support showing in Russian for some reason. The language you select as it installs is only used by the installer, not the app. I think (but am not sure) the app detects the OS language and attempts to use that. But it likely cannot display Unicode characters. Is your Windows set to be in Russian? If so, I think that it is. In theory, FontForge is supposed to respect the LANG environment variable, so you should be able to edit your FontForgePortable.ini file within the FontForgePortable\App\AppInfo\Launcher directory and add the line:

LANG=en_GB

right after the HOME=%PAL:DataDir%\Home line in the Environment section. Note that it could be en or en_EN instead of en_US. But, it did not seem to work for me. It might for you.
but I don't know what to do" 

I don't know where to find this files I should change and obviously the program doesn't respect OS language settings in my case.
Looking for help I found other people with similar problem (FontForge choose the language they don't use or don't know) but I didn't find any fix.

**Comment by larsenwork** [comment]
Did you fix the issue? Otherwise try this: http://fontforge.10959.n7.nabble.com/UI-language-td13836.html

**Comment by jtanx** [comment]
The should be to manually edit `fontforge.bat` (e.g. C:\Program Files (x86)\FontForgeBuilds\fontforge.bat) and uncomment (remove the two `::`) the line that says:

> LANGUAGE=en

I don't know why it's defaulting to Polish though; it shouldn't be.

**Comment by Darkmaster006** [comment]
If you have not still fixed the issue, there's a quick solution I've found: change the file "FontForge.mo" that is in C:\Program Files (x86)\FontForgeBuilds\share\locale\LANGUAGETHEPROGRAMISINHERE\LC_MESSAGES\ for the one that is in the 'en' or 'en_GB' folder. Then you'll get it in English.
