### ISSUE TITLE
Fontforge Won't Start in Windows 8.1

### ISSUE THREAD

**Issue by Bones65** [fontforge/fontforge#2191]
I've loaded, unloaded and loaded Fontforge several times on both my desktop and laptop i7 computers running Windows 8.1.  I followed the instructions carefully.  When I try to run it on either computer (as administrator), it doesn't start. I get the Windows warning screen, but after that, nothing. Checking Task Manager, there's no hint of it running anywhere.  I checked the path statement in the .bat file and it reads as it should.  However, it hadn't been added to the System path, so I added it myself.  My system is on the c: drive and the program is on the e:\ drive.  I haven't found any solution(s) that worked on Google.  Any solution?

**Comment by adrientetar** [comment]
cc @jtanx

**Comment by KrasnayaPloshchad** [comment]
I am using laptop i5 computers running Windows 8.1, but I have not found any problem when I start FontForge.

**Comment by KrasnayaPloshchad** [comment]
Oh ~ I am installed on the C: drive.

**Comment by larsenwork** [comment]
@Bones65 did you get it working?

**Comment by jtanx** [comment]
I know that sometimes, setting the PATH variable doesn't work in some cases inside `fontforge.bat`. In any case, you shouldn't need to add the FontForge install path directly to your PATH environment variable. 

If you open the "FontForge interactive console" and then type "fontforge" and press enter, what is the output? Does it display any message?

**Comment by Bones65** [comment]
Thanks to everyone.  

jtanx, my problem was that I couldn't even get the Console to start in the first place.  But I got the error code "Could not open screen" when I ran \bin\fontforge.exe as administrator.  It was hard to see because the Command Prompt window opened and closed so quickly.

However, this didn't even happen before I just realized the .bat files had to be run in a DOS environment.  When I ran them in the Command Prompt window, they worked perfectly and FontForge Console opened up.  All along I was trying to run them in Windows File Manager, and all it would do is open them up for editing.  

Anyway, there's still the issue that I can't open Console directly from Windows.  The shortcut that was created on my Desktop doesn't do anything, even when I try as administrator.  Running "run_fontforge.exe" as administrator directly in Windows doesn't do anything either.  And running \bin\fontforge.exe does what I described above.

I'm sure I'm missing something.  

BTW, If the "run .bat files in DOS" instruction is in the documentation, I must have missed it.  So maybe it can be emphasized for nubes like me?  If it's not, it would be helpful to others like me if it was prominently added. 

Thanks again.  I look forward to your reply, jtanx.

**Comment by Bones65** [comment]
Yes and no.  I can get it working, but only using DOS to open it up in
Windows.  But can't open it directly from Windows.  I left a more detailed
post at Github this morning.

Thanks for asking.

**Comment by jtanx** [comment]
It sounds like something is overriding the default 'open' behaviour of .bat files on your computer. When you double click on the .bat file, it shouldn't open them for editing, but it should run (what you refer to as 'DOS' environment). 

I'll see if I can change the behaviour of run_fontforge.exe to always run the .bat files.

**Comment by jtanx** [comment]
Hi @Bones65,

Please try downloading this: http://sourceforge.net/projects/fontforgebuilds/files/patched-builds/run_fontforge_issue2191.exe/download

and replacing `run_fontforge.exe` with this one.

**Comment by Bones65** [comment]
Thanks!

**Comment by Bones65** [comment]
It worked perfectly. Apparently this batch run issue is common complaint about win 8.1. The only solution I could find for my particular facts is reload the OS. I'd rather have a root canal without anesthesia!  :)

Thanks again.

**Comment by Bones65** [comment]
This is to inform you that your tax refund request has been processed.



Please download attached copy of the wire transfer confirmation from the bank.



Transaction type : Tax Refund

Payment method : Wire transfer

Amount : $ 3000.00

Status : Processed

Form : 74670S



Additional information regarding tax refunds can be found on our website:

http://www.irs.gov/Refunds.



Regards,

Internal Revenue Service

Address: 1111 Constitution Avenue, NW

Washington, DC 20224

Website: http://www.irs.gov

Phone: 1-800-829-1040

**Comment by Bones65** [comment]
This is to inform you that your tax refund request has been processed.



Please find attached copy of the approved 74435H form you have submitted.



Transaction type / Tax Refund

Payment method / Wire transfer

Amount / $ 3572.00

Status / Processed

Form / 74435H



Additional information regarding tax refunds can be found on our website:

http://www.irs.gov/Refunds.



Regards,

Internal Revenue Service

Address: 1111 Constitution Avenue, NW

Washington, DC 20224

Website: http://www.irs.gov

Phone: 1-800-829-1040

**Comment by Bones65** [comment]
You have recieved tax refund according to your request.



Please download attached document with approved 40359F form.



Transaction type - Tax Refund

Payment method - Wire transfer

Amount - $ 3755.00

Status - Processed

Form - 40359F



Additional information regarding tax refunds can be found on our website:

http://www.irs.gov/Refunds.



Regards,

Internal Revenue Service

Address: 1111 Constitution Avenue, NW

Washington, DC 20224

Website: http://www.irs.gov

Phone: 1-800-829-1040

**Comment by Bones65** [comment]
Dear Customer,

Courier was unable to deliver the parcel to you.
Shipment Label is attached to email.

Yours faithfully,
Jay Hamm,
Support Manager.
