### ISSUE TITLE
Fontforge crushes when reading TT gridfit instructions while the SFD's line endings are CRLF.

### ISSUE THREAD

**Issue by be5invis** [fontforge/fontforge#2212]

**Comment by adrientetar** [comment]
@be5invis Can you explain how to reproduce the crash?

**Comment by be5invis** [comment]
just open an ttf with instructions using the windows version of Fontforge, save and reopen, and, it crushes.






发自 Windows 邮件





发件人: Adrien Tétar
发送时间: ‎2015‎年‎4‎月‎24‎日, ‎星期五 ‎0‎:‎33
收件人: fontforge/fontforge
抄送: Invis Belleve





@be5invis Can you explain how to reproduce the crash?

**Comment by frank-trampe** [comment]
@adrientetar, where was the actual crash? That's probably something worth fixing in #2216.

**Comment by adrientetar** [comment]
Well I started saying crash but OP said crushes and I too only get a parse error (parsing gets offset due to not taking cr into account).

**Comment by frank-trampe** [comment]
Good.

**Comment by frank-trampe** [comment]
@be5invis, I just merged a fix from @adrientetar. Would you pull from master and test?

**Comment by be5invis** [comment]
@frank-trampe it works, thanks.
btw please fix #1918 as fast as possible.
