### ISSUE TITLE
only empty window "untitled1.sfd (iso8859-1)"

### ISSUE THREAD

**Issue by luhukasugithub** [fontforge/fontforge#2213]
I tried to install fontforge on mac 10.8.5 with xquartz... i put the .app in the applications-folder, run it, it is charging fonts and then a empty window appaers: untitled1 untitled1.sfd (iso8859-1) and nothing else happens...
any ideas what to do??
thanks, Lukas

**Comment by davelab6** [comment]
Well it sprays to have loaded. Use the file menu to open an existing font

**Comment by luhukasugithub** [comment]
file menu? when I open a font, the font-library is opening...
I don't have any fontforge surface...
![bildschirmfoto 2015-04-23 um 16 15 42](https://cloud.githubusercontent.com/assets/12085078/7299086/1323ac78-e9d4-11e4-9d74-8b8c1858d996.png)
seems to be that I am a bit stupid, sorry for that!

**Comment by davelab6** [comment]
Yikes! This is what I see

![screen shot 2015-04-23 at 12 03 54 pm](https://cloud.githubusercontent.com/assets/261579/7301470/d5fc839c-e9b0-11e4-92db-fb38f74d5501.png)

**Comment by luhukasugithub** [comment]
jep... a would like to have your view, too!!

**Comment by davelab6** [comment]
I'm sorry, I don't know why this is happening. I don't know how to
reproduce the problem in order to fix it

**Comment by andreaslarsen** [comment]
try downloading this and double click (runs FF in debug mode) https://github.com/fontforge/YosemiForge/raw/master/Mac/Shortcuts/FFDebug.command

**Comment by luhukasugithub** [comment]
I can't download anything with this link. there is only appearing a page that says: "/Applications/FontForge.app/Contents/MacOS/FontForge --debug"

**Comment by andreaslarsen** [comment]
right click and "Download linked file as..."

**Comment by luhukasugithub** [comment]
i'm sorry but its only text... there is no link. and no liked file.

**Comment by andreaslarsen** [comment]
:smile: no need to be sorry, it is a file though
![screen shot 2015-04-27 at 18 14 27](https://cloud.githubusercontent.com/assets/3859425/7352018/45fc51a8-ed09-11e4-93b8-ea68c7769075.png)

**Comment by luhukasugithub** [comment]
puh... i succeeded in downloading the file! but now... can't run the file because I don't have the access privileges. It says I should change them but for the only file that i have, the fontforge.app, I have total access privileges. same with the debug-file. 
so which file does it want to change?

**Comment by andreaslarsen** [comment]
it's just supposed to launch fontforge in debug mode.

It creates only one file
/Users/USERNAME/FontForge-Debug-Output.txt

**Comment by luhukasugithub** [comment]
![bildschirmfoto 2015-04-28 um 13 38 20](https://cloud.githubusercontent.com/assets/12085078/7368781/e8fbcdc8-edab-11e4-8977-945ad3675b04.png)
hmm ok. this is the window appearing after double-click the file. its german but i translated it the post before.

**Comment by andreaslarsen** [comment]
hmm, verstehe ich nicht...probieren mal das Terminal zu öffnen und geben Sie 

"/Applications/FontForge.app/Contents/MacOS/FontForge --debug" 

ohne die ""

**Comment by luhukasugithub** [comment]
result:
PKGBASE: /Applications/FontForge.app
You must installed the XCode Command Lines Tools to run FontForge
in debug mode. For 10.7 they are available in the App Store. For
10.6, install XCode from the App Store then install them by running
XCode and looking in Preferences.
do I really have to install this xcode-thing? it says: 
    Users must be a memeber of Apple's Developer program
    Highly technical for beginners

**Comment by andreaslarsen** [comment]
You won't be using it - the debug script will. 

Try typing "xcode-select --install" in the terminal and click install (not sure if it works on older versions)

**Comment by luhukasugithub** [comment]
it seems to be impossible to even download a x-code verison. when I try to get the newest version, it says that my system is too old. and older versions don't exist anymore... and without downloading something, the terminal code xcode-select --install doesn't work...

**Comment by andreaslarsen** [comment]
hmm...then I don't know how to debug. You can always install some virtualbox linux and run the app there.

**Comment by lixiangliu** [comment]
Hi, 

I’m having the same problem as well, and I was able to run the command you previously mentioned above. 

The result looks like this. 

PKGBASE: /Applications/FontForge.app
/usr/bin/lldb
have set up python stuff... PYTHONHOME: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7 
have set up python stuff... PYTHON:     /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.*/bin/python 
Script started, output file is /Users/chrislau/FontForge-Debug-Output.txt
No entry for terminal type "xterm-256color";
using dumb terminal settings.
(lldb) command source -s 1 '/Applications/FontForge.app/Contents/MacOS/debug-script'
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
(lldb)
