### ISSUE TITLE
Host XQuartz ourself

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge#2219]
The official XQuartz server is very slow (takes >2 min to download 68mb on 20 gbit fiber)

**Comment by andreaslarsen** [comment]
maybe even as part of the dmg so that user don't have to wait for a second download?

**Comment by andreaslarsen** [comment]
I added it here to test it, makes for a easier install process. 
https://github.com/andreaslarsen/fontforge-installer/releases/download/v0.1-beta/FontForge.Installer.dmg

**Comment by ultrasquid** [comment]
I don't think it would be a bad idea to host a mirror of the XQuartz
installer, but that's another thing to keep updated in addition to
FontForge. Bundling it with the FF.dmg might eventually lead to the
included version becoming outdated if we aren't vigilant about their
updates.

Could keeping track of XQuartz updates be automated, whatever way the FF
installer is configured?

On Tue, Apr 28, 2015 at 4:50 AM, Andreas Larsen <notifications@github.com>
wrote:

> I added it here to test it, makes for a easier install process.
>
> https://github.com/andreaslarsen/fontforge-installer/releases/download/v0.1-beta/FontForge.Installer.dmg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2219#issuecomment-97033616>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by andreaslarsen** [comment]
What we are currently doing is linking to xquartz2.7.7 on the webpage, so that needs updating every time as well.

The script does not install xquartz if x11 or xquartz is already installed. It could also easily be improved further to notify user that we recommend xquartz 2.7.7 if they have an earlier version.

They have an rss feed for all releases where I've filtered out rc's + beta's but feedburner or ifttt won't accept it: http://pipes.yahoo.com/pipes/pipe.info?_id=2969f83150b423cd7def58817d67e2fc

It also outputs to json if that could be used somehow.

Latest version of the dmg
https://github.com/andreaslarsen/fontforge-installer/releases/

**Comment by andreaslarsen** [comment]
Their RSS was crap but I've now subscribed to changes on their releases page so I'll know when XQuartz gets updated :) 
Closing this, we can continue in the pretty-dmg thread if needed.
