### ISSUE TITLE
Mac: Can we remove any stuff from FontForge.App to make it smaller

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2220]
Or does it really need to be 380+ mb big?

**Comment by andreaslarsen** [comment]
- [ ] Python: It's pre-installed on macs?
- [ ] Help/documentation: Link to website instead

**Comment by larsenwork** [comment]
Mac has python preinstalled since 10.2. Does Fontforge need 2.7 or what's the reason for us bundling it? @frank-trampe https://github.com/fontforge/fontforge/blob/master/osx/create-osx-app-bundle.sh#L168
