### ISSUE TITLE
Update the default pixmaps png's

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge#2221]
I tried making them cleaner and look more at home in modern os - thoughts? 

I can make a pr if "we" want'em - I just can't figure out where to put'em 

![spritesheet](https://cloud.githubusercontent.com/assets/3859425/7318762/9d31d906-ea8f-11e4-9ca2-21a7011948c5.png)

**Comment by andreaslarsen** [comment]
As you can see I also created a custom folder icon for sfdir's that would need to be implemented in the code for it to work

**Comment by davelab6** [comment]
Awesome! The PNG files are in the SRC tree somewhere

**Comment by andreaslarsen** [comment]
https://github.com/fontforge/fontforge/tree/master/fontforgeexe/pixmaps/tango
or
https://github.com/fontforge/fontforge/tree/master/fontforgeexe/pixmaps/2012

**Comment by davelab6** [comment]
> https://github.com/fontforge/fontforge/tree/master/fontforgeexe/pixmaps/tango

This is the 'default theme' shown to users

> https://github.com/fontforge/fontforge/tree/master/fontforgeexe/pixmaps/2012

This is the 'framework theme' that was developed by George Williams

**Comment by andreaslarsen** [comment]
updated the tango ones here: https://github.com/fontforge/fontforge/tree/graphics-update

I made them 20px - the actual icons aren't bigger but it adds some padding, can be changed in anyone feels strongly about that.
 
![screen shot 2015-04-24 at 21 43 40](https://cloud.githubusercontent.com/assets/3859425/7327126/052e7f06-eacb-11e4-96dc-379caee0e6b3.png)

**Comment by davelab6** [comment]
WOW this looks AWESOME

**Comment by andreaslarsen** [comment]
pr #2229 closes this
