### ISSUE TITLE
Generate fonts does not produce a workable typeface

### ISSUE THREAD

**Issue by satis5d** [fontforge/fontforge#2223]
I've created an extremely simple font of only 4 glyphs - all dollar signs of different types. They've been assigned to the !, #, $, and % areas of the font. There are no errors when validating, but for the life of me I can' seem to generate a font that works. I get nothing but "not a valid font file" regardless of whether I use open type, type 1 or truetype. I'm at a complete loss as to what to do. Each glyph was copied from another font and modified. Please help. Thank you.

**Comment by davelab6** [comment]
> Each glyph was copied from another font and modified. 

I hope they were libre fonts! :) 

If you post your SFD file (eg on gist.github.com) then someone could take a look.

**Comment by satis5d** [comment]
Yes, they were made from free fonts. Thanks. I will attempt to post the file. I'm new to this, but very impressed with the speed of a response.

**Comment by davelab6** [comment]
Welcome to the FontForge community :) You could also make a full git repo and post both the binary you made that doesn't work and the SFD :)

**Comment by satis5d** [comment]
I just created a public gist called American Dollar font with issues.

**Comment by davelab6** [comment]
Where? Dont see it at https://github.com/satis5d?tab=repositories

**Comment by satis5d** [comment]
I posted it in the public at gist.github.com. I'm working on a repository now.

**Comment by satis5d** [comment]
Dave,
I couldn't get the Github repository to work. Here are the files that I'm having the issues with. Thanks for your help.
-Cary

**Comment by davelab6** [comment]
Please email me, dave@lab6.com

**Comment by davelab6** [comment]
Okay, I found your gist, and I made a github repo with it and a TTF I generated without issue: https://github.com/davelab6/americandollar

**Comment by satis5d** [comment]
Thank you very much, Dave! You've saved me hours of frustration.The font works exactly as it should. I don't know why I wasn't able to generate it, but at least now it's working. How can I show my appreciation? Is there some positive karma I can give you?
-Cary

**Comment by davelab6** [comment]
On the gist you generated a pfb font, you should chose OpenType CFF from
the type menu on the file dialog
