### ISSUE TITLE
Travis build for GNU+Linux failing

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2231]
https://travis-ci.org/fontforge/fontforge/jobs/60362888#L5737

**Comment by jtanx** [comment]
Probably related to this:

> In light of reported errors, we are going to cancel the 2015-04 updates at 1300 UTC 2015-04-28. Details: https://twitter.com/traviscistatus/status/592902357144498176

**Comment by jtanx** [comment]
Ok, so I think the compile was erroring out due to that, but it's now also failing this test:
https://github.com/fontforge/fontforge/blob/master/tests/test1006.py

Related to PR #2224 (in fact you can see that in the PR the last commit failed to build).

**Comment by frank-trampe** [comment]
Yes. I was amused to see that two people in a row merged stuff that failed Travis.

**Comment by adrientetar** [comment]
One build succeded and the other failed, I think I had not realized that only the Linux builder runs tests. I went towards the end of the build log and seen that the installation was successful. Being  used to spurious failures, I didn't look any further.

**Comment by davelab6** [comment]
@frank-trampe this is fixed now, right?

**Comment by adrientetar** [comment]
Yes it is.
