### ISSUE TITLE
Weird selection behavior

### ISSUE THREAD

**Issue by EtienneOz** [fontforge/fontforge#2232]
Hi,
On Ubuntu 14.04, nothing is happening when I'm trying to select the whole points of letter with ctrl+a (or menu -> select -> select all). The only way I have is to use ctrl+a and click on the path. Even like that, when I'm doing anything else like moving shape, zooming or scrolling, it deselects everything. This is really annoying...  
It is weird because everything was working well one hour ago, maybe I accidentally did a weird shortcut but I searched everywhere and wasn't able to solve it.

Edit: It looks like it doesn't deselect everything but hide selection. Indeed, I'm still able to drag points or move them with arrows even if it is "unselected". Less annoying but still weird.

**Comment by davelab6** [comment]
Is caps lock on?

**Comment by EtienneOz** [comment]
No caps lock.

**Comment by EtienneOz** [comment]
Ok, it magically reappeared. No idea why.

**Comment by andreaslarsen** [comment]
Ok, reopen issue if problem reappears
