### ISSUE TITLE
Change the UI font to Clear Sans 10pt

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2235]
It has a lot better hinting than current default - at least on mac. It's a font made for UI so it reads better at small sizes too. And I've added the apple icon at correct sizes so they also look better.

I added it to the theme so you can try it: https://github.com/fontforge/YosemiForge

![screen shot 2015-04-28 at 22 10 50](https://cloud.githubusercontent.com/assets/3859425/7379211/7307752a-edf3-11e4-8194-d8ae5318ab91.png)
![screen shot 2015-04-28 at 22 11 53](https://cloud.githubusercontent.com/assets/3859425/7379227/a349c3fa-edf3-11e4-9831-fc2bb7c4512e.png)

**Comment by andreaslarsen** [comment]
Just reinstalled (testing pretty.dmg..) and this is the default look... :/

![screen shot 2015-05-07 at 19 27 57](https://cloud.githubusercontent.com/assets/3859425/7521575/32a90d74-f4ef-11e4-836c-2275bd3a58aa.png)

**Comment by davelab6** [comment]
Closing as part of https://github.com/fontforge/fontforge/issues/2676

**Comment by fitojb** [comment]
Wouldn’t it be much better that, instead of hardcoding another font, FontForge would just follow the platform’s typeface?

**Comment by davelab6** [comment]
FontForge doesn't follow any other UI pattern of the platform, and can not. Therefore I quite like that the UI is the same everywhere :)
