### ISSUE TITLE
Windows open off-screen on multi-monitor setup (Windows)

### ISSUE THREAD

**Issue by davidhbrown** [fontforge/fontforge#2256]
When opening a font, that window is moved to what FontForge believes is the upper-right corner of the screen. Apparently, it does this by looking at the total dimensions of all connected monitors, not the dimensions of any single monitor. Consequently, the window may be positioned in an area that is not actually visible. 

Example/to recreate: I run a three-monitor setup with a large QFHD monitor in the center and a smaller FHD monitor at the right, bottom aligned with the bottom of the center monitor. The font window is opened in the non-imaged space above the right-hand FHD monitor.

Workaround: while FontForge's windows do not respond to the usual Alt+Space, m shortcut to move windows, they do respond to Win+left arrow and Win+right arrow keyboard shortcuts will move them to visible areas.

OS: Windows 8.1 Pro x64
Version: 09:31 AWST 1-May-2015

**Comment by andreaslarsen** [comment]
Would it fix it if they were moved to the upper left corner?

**Comment by davidhbrown** [comment]
Thanks for your note. 

 

It would probably fix it for some people, but so long as you’re looking at the total dimensions of the multiple-monitor setup instead of the dimensions of a single monitor, there’s going to be some setup that misses any corner. Someone could even do something crazy like put big monitors on the two sides and a tiny monitor in the middle such that even the centermost pixel didn’t map to an actual monitor.

 

I haven’t looked into FontForge enough to know what windowing engine you’re using (it looked unfamiliar), whether you even have an API to know the locations of actual monitors. If not, it might have to be a “would be nice” issue.

 

Dave

 

--

David H. Brown

dave@davidhbrown.us

**Comment by andreaslarsen** [comment]
FontForge uses it own windowing engine so..... :)

**Comment by elgonzo** [comment]
You probably are already aware of that, but let me mention it just to be sure:

When talking about "upper-left corners" with regard to multi-monitor setups running MS Windows, keep in mind that the upper-left corner of a multi-monitor setup is not necessarily at the virtual-screen coordinates (0,0).

The primary monitor always contains the origin (0,0) of the virtual-screen space coordinate system, no matter where this primary monitor is located within the multi-monitor setup.

If a secondary monitor is left or above the primary screen then the coordinates of the upper-left corner of your multi-monitor setup will be negative.

If you know this already, then please apologize my superfluous comment. :)

**Comment by tronster** [comment]
Having the same issue... 3 monitors and when I open it up (fresh install) it flies off the top right.  On Windows 7.   I really would just prefer the window is centered or there was a way to set it to 0,0 on whatever the "primary" monitor is.  If attachments work; attached is an image of the desktop. 
![monitor setup](https://cloud.githubusercontent.com/assets/907833/16820867/39112c1e-4921-11e6-9c85-f8908318aedb.png)

**Comment by tronster** [comment]
Additional notes: Initial program opens fine, it's just the font file I select that flies above there.  Attached is a screen shot that fixes it opening: 
![image](https://cloud.githubusercontent.com/assets/907833/16820943/9f7df91e-4921-11e6-9fa2-8b4dba89bc3b.png)

**Comment by jtanx** [comment]
This is a known issue... It won't be fixed unless FontForge gets rid of its hard dependency on X11. I have a [branch](https://github.com/jtanx/fontforge/tree/cairo) that fixes this issue, but it's not ready yet - nor do I know if I'll complete it, due to other issues.

**Comment by Tamschi** [comment]
For anyone else with this problem (on Windows 10, pretty sure it's more straightforward on other versions):
If you _Shift + right click_ the window in the task bar, you can move it onto the screen with the _arrow keys_ and confirm with _left click_ or _Enter_.

**Comment by pwust** [comment]
I am not sure if this will help working on this off-screen dialog issue for Windows OS builts.
I have a Two-Monitor setup for Windows 8.1 x64 like in the screenshot attached:
![image](https://cloud.githubusercontent.com/assets/3417544/26347688/a0dbbc76-3faa-11e7-9f03-c6114359f369.png)
The main monitor for OS is # 1, whilest # 2 is in portait mode, both aligned at bottom. For FontForge (Version "20:55 AWST 4-Oct-2016-ML-TtfDb-D)", git hash 172e17e105afb8d934cadac0e738443f00ef6553), many windows are place off-screen in the red/white shaded area, either top-left (e.g. glyph edit window), or globally centered (e.g. file open dialog at progam start).

**Comment by Orillian** [comment]
I have a similar setup to @pwust except I have another horizontal monitor to the right of the vertical one as well. I end up with fontforge opening the glyphs in the same space as what @pwust is showing. The open dialog shows dead center on my center vertical monitor. For me swapping the sides would not help.

At this point I don't know what to do to get it visible.

**Comment by Orillian** [comment]
OK, so I finally found out how to kinda use FontForge on Windows 10 with multiple monitors.

If you load the application, then select the font you want to work with and it opens (apparently in the upper right corner) you can select the window in the taskbar by pressing SHIFT+RIGHT CLICK this brings up a menu with a move option.

Select Move and then use the arrow keys on the keyboard to bring the window into view.

The only problem with this is that I sometimes have issues getting some of the other windows to come onto the screen when FontForge has more then one open. 

I've been able to do a bit of work on my desktop machine doing this but the workflow is far from optimal.
