### ISSUE TITLE
Using foreground color for the > sign in menus

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2258]
I thought I'd found a great way to add border to dropdown menus - but this fucks up the > sign which for some reason is drawn using BorderBrightest, brighter, darker, darkest...

This could be easily fixed by drawing it with foreground color instead

![screen shot 2015-05-06 at 11 29 04](https://cloud.githubusercontent.com/assets/3859425/7490975/0ff38bb6-f3e5-11e4-80fe-e207ffab4469.png)

**Comment by skef** [comment]
This was ultimately addressed as mentioned at https://github.com/fontforge/fontforge/pull/2266#issuecomment-105292661
