### ISSUE TITLE
Windows 4-30-2015 release installer hangs

### ISSUE THREAD

**Issue by bseib** [fontforge/fontforge#2265]
I downloaded the 4-30-2015 release for windows (Win 7) and opened the .exe file. It never launches. In fact, it hangs explorer.

![image](https://cloud.githubusercontent.com/assets/1313561/7539188/4f10b29e-f573-11e4-8df3-7750134342fd.png)

**Comment by bseib** [comment]
Okay, so after about 4 minutes of nothing happening, I finally got the security dialog and proceeded to install. I don't know why the installer took so long up front....

![image](https://cloud.githubusercontent.com/assets/1313561/7539248/b30e2e8e-f573-11e4-8829-b6f1c6a95fd5.png)

**Comment by andreaslarsen** [comment]
Does it happen if you try to install again?

**Comment by bseib** [comment]
It doesn't do it any more. If I re-open the installer .exe now, it goes immediately to the "Open File - Security Warning" without any delay.

I can't repeat it. Close the issue if you wish.

**Comment by andreaslarsen** [comment]
Cheers, will do, seems like an glitch in the operating system 

Reopen if the issue reappears

**Comment by jtanx** [comment]
More than likely it's your virus scanner that's causing the issue.

**Comment by bseib** [comment]
Nope. I have no virus scanner.

I did wonder if MS makes a network call when opening an unknown installer exe.
