### ISSUE TITLE
Can't open or import existing fonts?

### ISSUE THREAD

**Issue by rodneyrhodes** [fontforge/fontforge#2267]
I'm running FontForge as (X11 v2.7.7) on Mac OS X 10.10.3 . . . installation worked just fine, but I can't see any fonts when using the Open or Import dialog box. Even using the "All fonts" filter with the "Show hidden files" option turned on shows nothing.

**Comment by andreaslarsen** [comment]
Can you post a screenshot?

**Comment by rodneyrhodes** [comment]
The folder I'm addressed to has an outline font and a screen font in it, but neither of them appear in the Open dialog box.
![screen shot 2015-05-08 at 4 49 47 pm](https://cloud.githubusercontent.com/assets/12159142/7546348/5d810c28-f5a2-11e4-8318-ce38ee3286e5.jpg)

**Comment by andreaslarsen** [comment]
Strange. Can you send the font so I can try to open it on my system?
(if font isn't free then send me an email andreaslarsen86@gmail.com - I'll promise to delete it afterwards)

**Comment by andreaslarsen** [comment]
@rodneyrhodes did you get it working?

**Comment by andreaslarsen** [comment]
The fonts in question could be opened - non-issue.
