### ISSUE TITLE
fontforge version

### ISSUE THREAD

**Issue by pgajdos** [fontforge/fontforge#2270]
Hello,

see https://bugzilla.suse.com/show_bug.cgi?id=930076

Is it possible that fontforge --version would return version of the release, like

$ fontforge --version
[...]
fontforge 20150430
libfontforge 20150430

**Comment by JoesCat** [comment]
At the end of file "fontforge/start.c" change the code to read like this:
void doversion(const char *source_version_str) {
    if ( source_version_str!=NULL ) {
	printf( "fontforge %s\n", source_version_str );
	printf( "fontforge %d\n", FONTFORGE_VERSIONDATE_RAW );
    }
    printf( "libfontforge %d\n",
	    FONTFORGE_VERSIONDATE_RAW );
exit(0);
}


if that resolves the problem, please send in a patch.

**Comment by skef** [comment]
This happened at some point.
