### ISSUE TITLE
Merging fonts crashes fontforge

### ISSUE THREAD

**Issue by ahyangyi** [fontforge/fontforge#2272]
Steps to reproduce:
1. Install fontforge from current master.
2. Open fontforge, open two fonts.
3. From one of the fonts, choose "merge fonts", choose the other font, click OK.
4. Crash.

Using the python binding to merge fonts also crashes.

**Comment by jtanx** [comment]
Commit: a692c526d95c8e6ba25e9b48c9acd102d40a1843

Segfault at [splineutil.c:6022](https://github.com/fontforge/fontforge/blob/a9c48a6314b93cdded1b2bfa1312c2bb150b240c/fontforge/splineutil.c#L6022)
