### ISSUE TITLE
crash when creating vertical kerning table

### ISSUE THREAD

**Issue by Gwenouille** [fontforge/fontforge#2275]
Hi everyone,

I use Fontforge on windows 7 64, build from the 1st of May this year.
I was working on a font and added a "vkern" lookup table and subtable. After saving, i couldn't reopen the file later, at all : double-clicking on the file would lead to FF starting and stopping immediately.
Opening FF and then choosing the file to open in the dedicated window lead to an instant crash…
I managed to save my file by opeing it in a text editor and removing the lines mentionning the corresponding lookup and description of the subtable.

So i created a testfile: new file > font info > lookups > GPOS > Add Lookup (Pair position) > Feature: Vertical Kerning > OK > Add subtable > OK > Classes > OK
Then I saved, quit and reopened the file: impossible, FF won't launch.

If you do these steps but stop and save BEFORE adding a subtable, then you can open the file.

Can someone have a go and confirm the behaviour ?
At he moment, i can't use vertical kerning…

**Comment by Gwenouille** [comment]
Am I the only one to have that problem ?

**Comment by jtanx** [comment]
I have been able to reproduce this issue, but I haven't looked into what is causing it.

**Comment by jtanx** [comment]
Okay, so this error happens on Linux too. The cause of the exit is at [sfd.c:8032](https://github.com/fontforge/fontforge/blob/77f7de28bcfbaeef2eb29ed507484112714678d1/fontforge/sfd.c#L8032) "Version mixup in Kerning Classes of sfd file."

The issue is that the offset to read the vertical kerning class version is wrong (should be 10 instead of 9 due to the extra 'V' out front)

**Comment by jtanx** [comment]
Thanks for reporting this @Gwenouille - you can find a test build [here](http://sourceforge.net/projects/fontforgebuilds/files/i686/Installer/FontForgeSetup-26-05-2015.exe). It should also be fixed by the next proper release.
