### ISSUE TITLE
glyph.build and font.build uses modifier letter accents, not combining accents

### ISSUE THREAD

**Issue by sergey-s-betke** [fontforge/fontforge#2278]
For example: `glyph.build` for `acircumflex` glyph doesn't use `circumflexcomb`, this method uses`circumflex`. Why? It is correct? Why not `circumflexcomb`?

**Comment by sergey-s-betke** [comment]
@adrientetar, can You help me?

**Comment by sergey-s-betke** [comment]
Excuse me, I make mistake. The anchors are not used (in `build` method) even for outline fonts! Why?

**Comment by sergey-s-betke** [comment]
P.S.> Anchors from .fea file, example - https://github.com/Metrolog/Font.GOST2.304-81/tree/0.5

**Comment by adrientetar** [comment]
I'm sorry but I don't really use scripting and am not familiar with the code that does this. cc @tshinnic if you have time to look at this

**Comment by sergey-s-betke** [comment]
Additional information after tests.

For example: `glyph.build` for `acircumflex` glyph doesn't used `circumflexcomb`, this method used `circumflex`. Why? It is correct? Why not `circumflexcomb`?

**Comment by skef** [comment]
At least one other issue is filed on this.
