### ISSUE TITLE
Mac .app package working on OS X 10.6

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#228]
The Mac .app package should work on OS X 10.6 for the upcoming release

**Comment by fwlab** [comment]
Apparently it does not work under OS X 10.10.5, on iMac retina 5k.
Launching via the icon does not work, and launching via terminal produces the following output:
$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
$ dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
serving at port 8000
