### ISSUE TITLE
build failure on NetBSD

### ISSUE THREAD

**Issue by ChristTrekker** [fontforge/fontforge#2283]
Relevant steps and file sections follow.

-bash-4.3$ AMTAR=`which gtar` ./bootstrap

-bash-4.3$ CPPFLAGS="-I/usr/pkg/include" LDFLAGS="-L/usr/pkg/lib" 
./configure

checking Build with JPEG support?... yes
checking png.h usability... yes
checking png.h presence... yes
checking for png.h... yes
checking for library containing png_init_io... no
checking Build with PNG support?... no
checking tiffio.h usability... yes
checking tiffio.h presence... yes
checking for tiffio.h... yes
checking for library containing TIFFRewriteField... no
checking for library containing TIFFClose... -ltiff
checking Build with TIFF support?... yes
checking for LIBCAIRO... yes
checking Build with Cairo support?...
configure: error: in `/home/tim/dev/fontforge-20150430':
configure: error: ERROR: Please install the Developer version of libpng
See`config.log' for more details

configure:20022: $? = 0
configure:20214: result: yes
configure:20220: checking Build with Cairo support?
configure:20225: error: in `/home/tim/dev/fontforge-20150430':
configure:20227: error: ERROR: Please install the Developer version of 
libpng
See`config.log' for more details

Values of ${i_do_have_libpng} and ${with_libpng} are "no" and "check" at 
that point. However,

-bash-4.3$ nm /usr/pkg/lib/libpng16.a  | grep _init_
0000000000000b0f T png_info_init_3
0000000000001180 T png_init_io
000000000000182a T png_init_read_transformations
                 U png_init_read_transformations
0000000000000057 t png_init_filter_heuristics
-bash-4.3$ nm /usr/pkg/lib/libpng16.so  | grep _init_
0000000000005d36 T png_info_init_3
000000000001d4ee t png_init_filter_heuristics
00000000000063a9 T png_init_io
0000000000012842 t png_init_read_transformations

So, I'd think the configuration should have found what it was looking for.

**Comment by JoesCat** [comment]
Hi @ChristTrekker,
AC_CHECK_LIB(library, function, [action-if-found], [action-if-not-found], [other-libraries])
is a bit more mature than:
AC_SEARCH_LIBS(function, search-libs, [action-if-found], [action-if-not-found], [other-libraries])

In file m4/fontforge_search_libs.m4
change the line containing:
   AC_SEARCH_LIBS([$1],[$2],
to:
   AC_CHECK_LIB([$2],[$1],

Please see if that resolves the path searching problem.

**Comment by JoesCat** [comment]
ping?

**Comment by ChristTrekker** [comment]
Sorry, been tied up on other projects for some time. Haven't had a chance to get back to look at this.

**Comment by JoesCat** [comment]
Can you check if you have a sufficiently recent png library?
Fontforge is checking to see if it finds a function named "png_init_io"
If it doesn't exist, it means you have an older library, or one where that particular function was excluded.
https://www.google.ca/search?q=png_init_io+netbsd

**Comment by ctrlcctrlv** [comment]
I receive the same error attempting to build on Windows with MSYS2:

```
checking Build with TIFF support?... no
checking for cairo >= 1.6... yes
checking Build with Cairo support?... configure: error: in `/home/Fred/Workspace/fontforge':
configure: error: ERROR: Please install the Developer version of libpng
See `config.log' for more details
```
`mingw64/mingw-w64-x86_64-libpng` is installed and `/mingw64/include/png.h` exists, however.

**Comment by JoesCat** [comment]
png_init_io() is required in:
gutils/gimagereadpng.c
gutils/gimagewritepng.c
To work with netBSD, we probably need another AC_CHECK or AC_SEARCH in:
m4/fontforge_arg_with.m4
Can you try AC_CHECK ?
 I believe NetBSD is more reliable with it, and if yes, we can double-layer the test.
See configure.ac surrounding the math library as an example.
