### ISSUE TITLE
Windows: Clicking on the text box clears the clipboard for external inputs

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2286]
If you copy from one program into FontForge, it will paste correctly as long as you don't explicitly click on the text box. As soon as you click on the text box, the clipboard is cleared for unknown reasons. This bug is also present in the 2012 version.

**Comment by jtanx** [comment]
I don't think there is an easy fix for this. The clipboard gets cleared by calling `_ggadget_redraw` [gtextfield.c:1762](https://github.com/fontforge/fontforge/blob/7ee902/gdraw/gtextfield.c#L1762), but I think this is thre result of calling `GTextFieldGrabPrimarySelection` [gtextfield.c:1742](https://github.com/fontforge/fontforge/blob/7ee902/gdraw/gtextfield.c#L1742) beforehand.

The workaround would essentially involve copying whatever's in the clipboard on every click event, which is not ideal (nor completely straightforward to do)...

**Comment by larsenwork** [comment]
Ok, so the the current "workaround" is to select the box first - switch to other app - copy - switch back - paste? 
I might write that in the system specific tips/tricks chapter on designwithfontforge.

**Comment by jtanx** [comment]
That's right.

**Comment by jtanx** [comment]
Okay, just to confirm, it is `GTextFieldGrabPrimarySelection` that causes the clipboard to be cleared. I commented out that function, reran and the clipboard works fine.

**Comment by pathumego** [comment]
CC @kosalaya This is what you suffered from :)

**Comment by jtanx** [comment]
I wonder if in some roundabout manner, this is related to #704

**Comment by larsenwork** [comment]
@jtanx I'll add the workaround to online documentation so if/when it's fixed please ping me so I can remove it from docs again.

**Comment by jtanx** [comment]
Hmm, I know what happens now:

1. `GTextFieldGrabPrimarySelection` sets the 'primary' clipboard that allows middle-click pasting from one text field to another (It's implementation means that you cannot middle-click paste from and then into itself). Note that its design is flawed, in that it will simply allow primary clipboard copying based on the fact it was the last selected text box. This is because the functions that get called on paste (e.g. `genutf8data`) only look at the current selection at the time that it is called, and not at the time when `GTextFieldGrabPrimarySelection` was called. 
2. As part of its call, it sets the selection owner to itself (it owns the selection), hence the call to `XSetSelectionOwner`. But on Windows, this clears the clipboard as it awaits input from FontForge - there's **only one clipboard**. 
3. Setting the primary clipboard is not supported by VcXsrv (for whatever reason; middle-click pasting is not really a feature on Windows. It works with XWin/Cygwin though.). So the clipboard is now empty.

-------

What I have done to fix this is to only set FontForge as the selection owner if it was a copy to the 'clipboard' clipboard (X11 has any number of clipboards), or the 'explicit' copy clipboard. While this prevents primary clipboard copying from FontForge to external applications (can be done currently in CygWin), I figure this is not a big deal since this is not usual behaviour on Windows anyway.

**Comment by davelab6** [comment]
reopening so @larsenwork can track updating the docs

**Comment by larsenwork** [comment]
No reason for this issue to stay open just for me. I'd rather we just create a checklist somewhere when doing releases.
