### ISSUE TITLE
Not able to install latest version of fontforge in CentOS

### ISSUE THREAD

**Issue by karthiklin** [fontforge/fontforge#2287]
The below error occured

bootstrap:   error: One of these is required:
bootstrap:                 libtoolize glibtoolize
bootstrap:   error: Prerequisite 'git' not found. Please install it, or
bootstrap:          'export GIT=/path/to/git'.
bootstrap:   error: 'autoconf' version == 2.63 is too old
bootstrap:          'autoconf' version >= 2.68 is required
bootstrap:   error: Program    Min_version Homepage  
bootstrap:          -----------------------------------------------------------
bootstrap:          git        1.5.5       http://git-scm.com  
bootstrap:          perl       5.5         http://perl.com  
bootstrap:          tar        -           http://www.gnu.org/s/tar  
bootstrap:          autoconf   2.68        http://www.gnu.org/s/autoconf  
bootstrap:          automake   -           http://www.gnu.org/s/automake  
bootstrap:          -----------------------------------------------------------

**Comment by adrientetar** [comment]
Have you installed the dependencies?

**Comment by karthiklin** [comment]
The below packages are installed before compile

yum -y install gcc

yum -y install gcc-c++

yum -y install cmake

yum -y install libtool

yum -y install libpng-devel

yum -y install libjpeg-devel

yum -y install fontconfig-devel

Any other dependencies needed

**Comment by adrientetar** [comment]
> bootstrap: error: One of these is required:
bootstrap: libtoolize glibtoolize

Install one of these?

> bootstrap: error: Prerequisite 'git' not found. Please install it, or
bootstrap: 'export GIT=/path/to/git'.

Install git?

> bootstrap: error: 'autoconf' version == 2.63 is too old
bootstrap: 'autoconf' version >= 2.68 is required

Update autoconf?


…no?

**Comment by karthiklin** [comment]
Hi autoconf updated but again face the below error

[root@~/fontforge-20150430]# ./bootstrap 
bootstrap:   error: One of these is required:
bootstrap:                 libtoolize glibtoolize
bootstrap: running: --quiet
./bootstrap: line 4287: --quiet: command not found
[root@~/fontforge-20150430]# autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
[root@1~/fontforge-20150430]#
