### ISSUE TITLE
Windows: Cannot open/save files with paths/folders containing non-standard characters

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2290]
On Windows, functions like fopen/opendir/stat all only accept filenames in the current active codepage, which excludes opening files with characters outside of that codepage (e.g. Chinese and Cyrillic characters for a Windows/English setup).

Some aspects (like directory scanning) can be easily solved by using GLib and passing UTF-8 encoded filenames on Windows. Other aspects are less easily solved, as most function calls involving files are spread out, and most assume `u2def` (Unicode to default character encoding) is sufficient when it is not (on Windows - 99.9% of the time the default charset is 8859-1).

---

To be fixed:
- [x] fopen/open (in Gnulib)
- [x] <strike>freopen</strike> (not used)
- [x] opendir/readdir
- [x] rmdir (Unused; removed GFileRmDir)
- [x] unlink
- [x] access
- [x] mkdir
- [ ] getenv
- [x] `u2def` -->`u2fsys` / `def2u` --> `fsys2u` as necessary
- [x] stat/lstat
- [x] rename
- [x] remove (present in gtkui; left unchanged; unused elsewhere)
- [x] chmod (unused)
- [x] chdir 
- [x] creat? (unused)
- [ ] fsys functions
  - [ ] GFileGetHomeDocumentsDir - trailing slash
- [ ] Font loading code
- [ ]  endswithi is broken
- [ ] Check all instances of tolower

Anything else from https://developer.gnome.org/glib/stable/glib-File-Utilities.html

**Comment by be5invis** [comment]
Same problem on Chinses Windows. You should use "wide" version of WINAPIs (which accepts UTF-16 encoded strings) and perform a "widen" transformation if the internal encoding of strings is UTF-8.

**Comment by jtanx** [comment]
Yes, that is what GLib does - on Windows, it expects paths to be UTF-8 encoded, and internally it will do the conversion to UTF-16/call the Unicode/wide character version of the functions.

**Comment by jtanx** [comment]
Hmm... I was contemplating switching to using `g_fopen` from GLib, but in testing, we can't do that because we dynamically link to GLib, so it has its own CRT, meaning the FILE* won't work in our code. 

A solution that would work is using gnulib for fopen/open, then patching gnulib's implementation to accept UTF-8 strings on input...
