### ISSUE TITLE
Empty otf

### ISSUE THREAD

**Issue by kamil-s** [fontforge/fontforge#2297]
I run FontForge 01.05.2015 on Windows Vista, and have a problem generating fonts. Some formats, such as .ttf or .dfont, result in an error message, while others, .otf in particular, generate an empty file. I've had the same problem with older builds of FontForge. I have the same problem with every font I've tried.

**Comment by jtanx** [comment]
What is the error message?

**Comment by kamil-s** [comment]
That's it! There was a non-ASCII character in the path. Oh, thank you so much!

The error message, when there was one, meant simply 'saving failed' ("Zapis nie powiódł się").

Should anyone else experience the same problem, here's what I found. I kept my font files in my home directory which is "C:\\Users\Kasia i Kamil\fonty-mod". When I open a file from this path, it doesn't seem to matter where I want to generate the font to, I always get an error or an empty file. When, however, I move the .sfd file somewhere else ("D:\\kamil\praca\fonty"), I can generate it no problem, both to the new location, and to that C:\\... path. I suspect it may be that my stupid Windows does sometimes translate the "Users" part of the path to "Użytkownicy" (the same in Polish). It doesn't seem to be doing this for FontForge, but the moving of the .sfd files helped, so... Perhaps I should also note that I could generate .svg fonts regardless of the location of the .sfd file.

**Comment by jtanx** [comment]
Glad you found a solution! This is a known issue, related to #2290.

**Comment by kamil-s** [comment]
I'm sorry but it turns out the problem is not solved after all. When I read your answer, I did what I described above, and it worked just fine. After a reset, however, the problem is back. FontForge generates the otf, but the file is empty, despite there being no non-ASCII characters in the path.

**Comment by jtanx** [comment]
Strange. Could you please try the latest build [from here](http://sourceforge.net/projects/fontforgebuilds/)?

**Comment by kamil-s** [comment]
I did a few tests with a few resets in between, and it seems that everything is fine now. I'm very sorry for the prolonged trouble, and thank you so much for your help!

By the way, with the previous build, the computer beeped every time I closed FontForge (not the speakers, the computer), which always frightened me a bit. It appears that this, too, is gone now much to my relief.
