### ISSUE TITLE
Question: is it possible to install version 2012-07-31 with Python extension using homebrew?

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#2301]
Due to some path regressions I would like to install version 2012-07-31 again. 
Is it possible to install using homebrew? Thanks

**Comment by larsenwork** [comment]
I don't now - if it doesn't have to be that specific version you can find some other old ones here: http://fuuko.libferris.com/osx/packages/

**Comment by JoesCat** [comment]
If you have time, can you post details about the regression?

**Comment by dimitre** [comment]
Hello @JoesCat the regression is nicely detailed here:
https://github.com/fontforge/fontforge/issues/2025

**Comment by dimitre** [comment]
@larsenwork @joescat thanks, but as I'm using Python module I think I should compile it. in fact I keep a copy of OS X 10.6.8 with Fontforge 2012 in there.

**Comment by dimitre** [comment]
@davelab6

**Comment by davelab6** [comment]
@dimitre if you checkout a 2012-07-31 commit and look at the history of the fontforge.rb file in the homebrew repo you should be able to get a brew recipe that will work

**Comment by davelab6** [comment]
However, I think its madness. You are better off converting your source file to UFO and porting the Noodler or Outliner extensions for Glyphs and RoboFont to TruFont.

**Comment by dimitre** [comment]
indeed madness @davelab6 
The ideal would be having Fontforge expanding strokes nicely again!

**Comment by davelab6** [comment]
@dimitre I think reaching that ideal is going to take a lot of time. If you are really keen to sink the time in, I and @frank-trampe and others can guide you on the process :)

**Comment by dimitre** [comment]
@davelab6  FF is finally usable again. closing here :)
