### ISSUE TITLE
Remove Browse Web from menu

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2307]
This was dropped #1533. But MacOS builds still have it. Remove it as discussed on #2257

**Comment by pathumego** [comment]
![screen shot 2015-06-01 at 6 08 12 pm](https://cloud.githubusercontent.com/assets/6846609/7912931/3c5163d2-0889-11e5-8db1-6c16b3761c64.png)

**Comment by larsenwork** [comment]
It's only indirectly related and probably should be an issue of it's own but the "upload to open font library" should also be removed.
![screen shot 2015-06-01 at 14 45 06](https://cloud.githubusercontent.com/assets/3859425/7913042/d41392f2-086c-11e5-8bf1-71008ca49df4.png)

**Comment by jtanx** [comment]
That's also gone due to #1533, and in fact they haven't been present in Windows/Linux builds since Mid-2014 last year.

As far as I can see, the only way this can still be here is if the OS X builds are not being compiled from master.

**Comment by pathumego** [comment]
CC @frank-trampe

**Comment by larsenwork** [comment]
@frank-trampe this could maybe also explain why your menu arrow fix didn't work for me on latest HEAD mac build?

> As far as I can see, the only way this can still be here is if the OS X builds are not being compiled from master.

**Comment by adrientetar** [comment]
To clear up #1533 was reverted then reapplied with a fix in #2159 three months ago.

**Comment by frank-trampe** [comment]
Can somebody check the about window and see what the git commit is on the Macintosh version?

**Comment by pathumego** [comment]
This is what I see on 26-05-2015
![screen shot 2015-06-06 at 12 37 43 pm](https://cloud.githubusercontent.com/assets/6846609/8018758/e343f692-0c48-11e5-95cc-0e663691bb08.png)

**Comment by jtanx** [comment]
That would explain it: 05a30d48 is from the 12th of March. #2159 was introduced on the 23rd of March. So the source at the time of the build is about 2 months out of date.

**Comment by adrientetar** [comment]
So the version field prints current time instead of last commit time? Thought it was otherwise.

**Comment by jtanx** [comment]
From my experience, I think it actually prints configure time.

**Comment by pathumego** [comment]
@jtanx is #2312 caused of this issue?

**Comment by jtanx** [comment]
I don't quite understand; this issue (#2307) and that issue (#2312) are both because the Mac build is built from outdated source code (12th of March).

Pull #2159 fixes both #2307 and #2312, but it was only introduced on the 23rd of March. So the fix is to make a new Mac build using the latest source code.

**Comment by pathumego** [comment]
@larsenwork Any idea if this is fixed in the latest? And the dmg for latest 2015-06 is not release yet, so we can fix this there.

**Comment by larsenwork** [comment]
@pathumego I still have building issues (I think I pinged you in that issue?) so no - haven't been able to test it yet :)

**Comment by pathumego** [comment]
Fixed
