### ISSUE TITLE
I'm having all sorts of issues - how do you best start from scratch on mac?

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2318]
I've already mentioned #2315 but I currently can't even open metrics view without crashing. 

I've tried removing everything brew, reinstalled latest FF release, reinstalled xQuartz but still no luck...

Any suggestions?

**Comment by larsenwork** [comment]
@davelab6 or @pathumego or someone else - any suggestions? My FontForge is currently only "half"working... :neckbeard:

**Comment by davelab6** [comment]
That can happen when you use an external monitor and make a very large window, then start FF without the external monitor and it can't draw its windows at the sizes stored in the prefs file. 

All local settings are in `~/.config/fontforge` so if you `rm` that dir you are 'clean'

**Comment by larsenwork** [comment]
fucking aye...thanks!
