### ISSUE TITLE
@FontForge #TipTuesday

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2331]
This is probably for @davelab6 but I had this idea to get more followers and use the twitter account more actively by posting a weekly tip (tips, ideas, different way to do things, etc.). 

So we use the twitter account to notify about updates but also share bits of knowledge/experience with followers to get more following/reach through twitter.

**Comment by larsenwork** [comment]
And maybe also a #FontFriday where we pick one font created using fontforge and tweet it out.

**Comment by davelab6** [comment]
This sounds great; perhaps draft a tips page in the DWFF site?
