### ISSUE TITLE
Is there a way to delete all lookups at once

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2332]
I'm currently removing it in font.props manually but I was wondering if there was a smarter way to remove all GSUBs at once? 

Or to have the feature file replacing instead of merging with existing data?

**Comment by NuttShell** [comment]
Try this script, it removed GSUB and GPOS

#!/usr/bin/fontforge
TTFfileName = $1;
#Font format - otf or ttf. In my case - otf
FontExt = "otf"
Open(TTFfileName,1);
lookups = GetLookups("GSUB"); numlookups = SizeOf(lookups); i = 0;
	while (i < numlookups)
		RemoveLookup(lookups[i]); i++;
	endloop
lookups = GetLookups("GPOS"); numlookups = SizeOf(lookups); i = 0;
	while (i < numlookups)
		RemoveLookup(lookups[i]); i++;
	endloop
Generate(TTFfileName.FontExt); Close(); Quit(0);

**Comment by larsenwork** [comment]
Thanks for the reply @NuttShell been busy so only looked at it today. 

I have practically 0 FF scripting experience but as far I can tell your script removes GSUB + GPOS from an already generated font file (otf or ttf)

What I have is an open font from source (sfdir) that I want to strip of any opentype feature information. Both in font.props and in the separate glyphs.

**Comment by larsenwork** [comment]
What I'm doing right now is using simple perl scripts to clear it like so
```
perl -i -nle 'print if !/^Substitution2\b/' ~/git/Monoid-Master/Source/*/*.glyph
perl -i -nle 'print if !/^Lookup\b/' ~/git/Monoid-Master/Source/*/font.props
```

**Comment by larsenwork** [comment]
Added a bit more to the script - works fine, so I'll close this. 

```
perl -i -nle 'print if !/^Substitution2\b/' ~/git/Monoid-Master/Source/*/*.glyph
perl -i -nle 'print if !/^Ligature2\b/' ~/git/Monoid-Master/Source/*/*.glyph
perl -i -nle 'print if !/^Lookup\b/' ~/git/Monoid-Master/Source/*/font.props
sed -i '' '/ChainSub2/,/EndFPST/d' ~/git/Monoid-Master/Source/*/font.props
```
