### ISSUE TITLE
Keyboard shortcuts stopped working in Ubuntu 15.04

### ISSUE THREAD

**Issue by santhoshtr** [fontforge/fontforge#2334]
After upgrading one my computer to Ubuntu 15.04, none of the keyboard shortcuts are working. I used the ubuntu PPA(which does not have a package for vivid, I used utopic). Since shortcuts were not working, I tried building from source(20141014 tag). Shortcuts did not work there too. I verified that the hotkey files are present in /usr/share/fontforge/hotkeys too. I also removed the ~/.config/fontforge directory too. Still same result. Control+C, Control+V... no shortcut works.

**Comment by santhoshtr** [comment]
I think I found the issue. The input method fcitx was intercepting all the shortcuts. When I killed it started working

**Comment by larsenwork** [comment]
:+1: for closing an issue after finding the solution
