### ISSUE TITLE
Menu Re Structure Progress

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2335]
This is to track the pending tasks..
- [x] Draft of the new unified menu : https://docs.google.com/document/d/18UVeLOq-s_qJ_5IFbR8qHjHVufwk72KaLuI05WJNAWA/edit
- [x] List all changes needed to be done to get the menu looking like that: https://docs.google.com/spreadsheets/d/1jGKa63CDv8SbNjnARMpOPZBsSLRtQT2jEmwk6z7e27o/edit#gid=942886417
- [x] Get @lpsandaruwan  to implement those changes 
- [ ] Draft Announcement: https://docs.google.com/document/d/1bpShivntSBa8qkfD0agJdSb3dbDOhCXnNAF31FRRHzw/edit?usp=sharing
- [x] Try the menu system out.
- [ ] Make adjustments (if needed)
- [ ] Announcement and Test releases. https://drive.google.com/folderview?id=0B98Fs5a7IfdRfjFwdFVKcUVQUjZSSDBwTXlSRXB1dmthLXRlbFBPVVJRT21JVGVaek9yV3c&usp=sharing
- [ ] Draft tooltips for items that could benefit from such. https://github.com/fontforge/fontforge/issues/2259
- [x] Draft all right-click menus. 
- [ ] Implement tooltips.
- [ ] Implement right click menus.
- [ ] Merge to the regular releases. 
- [ ] Full documentation of rearrangements
- [ ] Announcement on forums + mailing lists (libregraphics lists)
- [ ] Blog posts (Libre graphics world, typedrawers, ubuntu sites)
- [ ] Update Documentation
- [ ] Update Screenshots / Content on DWFF
- [ ] Update Website

**Comment by larsenwork** [comment]
It's not frank but @lpsandaruwan doing the changes right?

**Comment by pathumego** [comment]
Yep, Updated

**Comment by pathumego** [comment]
@larsenwork @frank-trampe @jtanx Please find the test builds for new-menu structure by @lpsandaruwan [here](https://www.gumtree.com/p/bicycles/excellent-bike-for-sale.-includes-u-lock./1136297900). Im using this build as my default and so far its been awesome. Other two designers at mooniak will also switch to these builds for testing. 

How would you guys like to move forward on this? @lpsandaruwan's work is [here](https://github.com/fontforge/fontforge/tree/new-menus). 

I propose to tweet the link to test-builds, and [announcement](https://docs.google.com/document/d/1bpShivntSBa8qkfD0agJdSb3dbDOhCXnNAF31FRRHzw/edit) , and see if we get any comments. Post a GitHub issue/pr and let people post what they think. Meanwhile if @frank-trampe can review the changes then we can maybe aim to merge this for 2015-12 Release.

**Comment by pathumego** [comment]
cc @davelab6 @adrientetar

**Comment by frank-trampe** [comment]
Hi there. I'm at a conference this week, and I'm buried. I'll take a look Thursday, I think.

**Comment by pathumego** [comment]
@frank-trampe Cool :)

**Comment by pathumego** [comment]
@frank-trampe Ping :)

**Comment by frank-trampe** [comment]
Ah. Sorry about that. I vaguely remembered agreeing to do this, but I didn't see it in the pull request queue. Where is the source code?

**Comment by jtanx** [comment]
Some brief testing:

- Open shortcut (Ctrl+O) does not work.
- Font info shortcut (Ctrl+shift+F) does not work.

In fact, a lot of the old shortcuts no longer work. I think as many of the old shortcuts should be brought over to the new menus as possible.

**Comment by jtanx** [comment]
Typo: `Path->Intepoltion` --> `Path->Interpolation`

**Comment by pathumego** [comment]
Cc @lpsandaruwan

**Comment by pathumego** [comment]
@frank-trampe  its here https://github.com/fontforge/fontforge/tree/new-menus

**Comment by jtanx** [comment]
Hmm I'm not sure why this is, but the Extensions menu is greyed out and I can't open it. This means I can't access the "Execute script" function. I think it's because I build without collab enabled.

**Comment by pathumego** [comment]
So @lpsandaruwan is busy with some other work, Ive been trying to get someone to finish the execution and fix the remaining issues, with no luck. If @jtanx or @frank-trampe or anybody have time to finish this off I will be greatful. :) For now @lpsandaruwan is not working on this.

**Comment by davelab6** [comment]
@pathumego what are the remaining issues? 

@frank-trampe were there any commits related to this that you'd like more detailed explanations of?

**Comment by davelab6** [comment]
> List all changes needed to be done to get the menu looking like that: https://docs.google.com/spreadsheets/d/1jGKa63CDv8SbNjnARMpOPZBsSLRtQT2jEmwk6z7e27o/edit#gid=942886417

@pathumego in the above sheet, there are many red cells, and some mint-green cells. What do those mean? Also while many are 'done', many are blank. 

Maybe it would be good to set color of the whole row to green when all actions possibly related to that row are completed, so its clear visually what is finished with, and what is yet to be completed.

**Comment by lpsandaruwan** [comment]
Hi,
I began to working on this again. Please just give me a breathing space. :-)

**Comment by davelab6** [comment]
Cool! @monkeyiq or @frank-trampe might be interested to review your code, please open a "living" PR to see what you have so they can comment :)

**Comment by pathumego** [comment]
@davelab6 https://github.com/fontforge/fontforge/pull/2724

**Comment by skef** [comment]
This is relevant to the menus project, but the discussion and draft announcement also deal with other projects either already done or probably left for later. I might edit the description field in a bit to reduce it to the questions at hand.

**Comment by skef** [comment]
Dead project.
