### ISSUE TITLE
Add progress bar for "change weight"

### ISSUE THREAD

**Issue by fedorl** [fontforge/fontforge#2337]
Change weight hangs on Japanese IPAexGothic.ttf (available free on internet). Always stuck on particular entry, UI is not responding (Windows 7)

**Comment by fedorl** [comment]
Well, seems it does not hang but works very slow without any indication of progress. 

Some kind of progress bar will be very helpful. 

The UI stays unresponsive until change finishes for all selected glyphs, the only indication of work are warnings in console or warnings window (if there are any). There is also useless empty window "You changed the point numbering".

**Comment by fedorl** [comment]
Though note, on conversion to italic there IS progress bar. Not very handy but does the work.

Probably another bug is that cancel have no effect during long duration weight change (didn't try in other functions).

Yet another during italic -  error/warning popups grab the Windows focus and disrupt user work.

I hope all this floating windows UI will change one day, to something more professionally looking and functioning... Top-notch internals and algorithms but UI of quick-and-dirty student project.

**Comment by jtanx** [comment]
> Top-notch internals and algorithms but UI of quick-and-dirty student project.

Love it :P

Changing UI is *somewhat difficult* given that FontForge rolls with a completely custom UI toolkit written to interact directly with X11.

**Comment by fedorl** [comment]
Sure, I know how difficult it is.. just a hope : ) 

But It is just difficult, not because of toolkit or X11. I doubt a toolkit prohibits making windows layout mode with progress bars inside main window bottom or docked warnings etc. without misaligned popups. 

Given it is open source project where I personally can make a contribution but have no time to, I personally have no complaints - fantastic work. But with polished and flexible UI it may acquire much larger professional designer audience and provide ways for monetization, which in turn would allow to make even better product.

**Comment by pathumego** [comment]
@fedorl there are some efforts happening to make the UI friendly and not so bad :) See https://github.com/fontforge/fontforge/milestones Menu restructuring is happening right now. Drop in your comments.

**Comment by larsenwork** [comment]
@fedorl common problem in open source projects - those who care about function and know how to code care little about UI and those who care about UI and ease of use don't know how to code...
as @pathumego says we are currently redesigning/rearranging menu and other UI elements but it's like putting a layer of makeup on an old lady although this lady has a few tricks up her sleeve to make it worth it. 
I not sure the market for a highly specialised product such as FF is that big.

**Comment by adrientetar** [comment]
Misunderstood the issue at first, soz.

Note that there is already progress bar for some operations e.g. hinting so I changed the title to be more specific.

**Comment by larsenwork** [comment]
@adrientetar :+1: I forgot about those other progress bars - FF is generally surprisingly quick.
