### ISSUE TITLE
Oddities and crashes when trying to edit times.ttf

### ISSUE THREAD

**Issue by lprecord** [fontforge/fontforge#2343]
I copy times.ttf to some location where I have editing rights.
I open FF and select the file for edit. It already opens with various warnings.
I try to edit one glyph, and right away I get the warning that I changed the point numbering and instructions have been lost. All I did was to sloghtly move one control point in spiro mode. I did *not* add or delete control points.
After editing I save the file.
I close FF and try to open the saved ".sfd" file.
It opens with numerous warnings in two separate windows.
As soon as I try to modify one further glyph the program immediately crashes.

For details see attached screen shots. Unfortunately git doesn't let me attach the psd file written at the first save action.

A similar issue was posted before but prematurely closed by the issuer:
https://github.com/fontforge/fontforge/issues/2226

![001_opening_times_font](https://cloud.githubusercontent.com/assets/12803251/8046346/6a0df400-0e3a-11e5-9038-f03a6dcb1b8a.PNG)
![002_warnings_when_opening_times_font](https://cloud.githubusercontent.com/assets/12803251/8046347/6a150cfe-0e3a-11e5-8704-a93aec144dd1.PNG)
![003_warning_when_editing_times_font](https://cloud.githubusercontent.com/assets/12803251/8046348/6a1a7da6-0e3a-11e5-8575-a23fcd383e45.PNG)
![004_saving_modified_times_font_01](https://cloud.githubusercontent.com/assets/12803251/8046349/6a213d30-0e3a-11e5-9f33-6994c817da6f.png)
![005_saving_modified_times_font_02](https://cloud.githubusercontent.com/assets/12803251/8046350/6a284e18-0e3a-11e5-9851-4ec485249d91.png)
![006_file_written_when_saving_modified_times_font](https://cloud.githubusercontent.com/assets/12803251/8046352/6a336aa0-0e3a-11e5-9abf-cfb1f9b62025.PNG)
![007_closing_modified_times_font](https://cloud.githubusercontent.com/assets/12803251/8046353/6a363596-0e3a-11e5-9005-2a0bc9238d73.png)
![008_message_when_reopening_modified_times_font](https://cloud.githubusercontent.com/assets/12803251/8046351/6a2ba874-0e3a-11e5-876b-56289e0e1c41.PNG)
![009_repeated_message_when_reopening_modified_times_font](https://cloud.githubusercontent.com/assets/12803251/8046354/6a3b8a46-0e3a-11e5-8c37-8d7bb6af10a7.PNG)
![010_warnings_when_reopening_times_font_with_option_recover_session](https://cloud.githubusercontent.com/assets/12803251/8046355/6a3fffea-0e3a-11e5-8f30-cc6c60d8d5f1.png)
![011_warnings_when_reopening_times_font_02](https://cloud.githubusercontent.com/assets/12803251/8046356/6a46346e-0e3a-11e5-8d78-ddcf14fe898e.PNG)
![012_warnings_when_reopening_times_font_03](https://cloud.githubusercontent.com/assets/12803251/8046357/6a4b9b70-0e3a-11e5-8d54-dcd62b77a445.PNG)
![013_trying_to_edit_new_glyph](https://cloud.githubusercontent.com/assets/12803251/8046358/6a522a80-0e3a-11e5-8c98-b417838bfa14.png)
![014_program_crashes_after_first_edit_action_to_new_glyph](https://cloud.githubusercontent.com/assets/12803251/8046359/6a595e90-0e3a-11e5-8242-534c5c5784d2.png)

**Comment by jtanx** [comment]
The 'Missing right bracket' warnings and subsequent crashing is more than likely related to #1918 and #2250. The latest test version does not crash regardless of LF or CRLF line endings (no released build yet though). If you convert your sfd from CRLF (Windows/DOS line ending) to LF (Unix line ending) your version of FontForge should also be able to read it properly. 

I don't know about the other issues though, e.g. loss of point numbering and the 'Invalid 2nd order spline' error.

**Comment by lprecord** [comment]
Unfortunately converting the sfd doesn't solve the problem. Even worse: now FF crashes immediately when loading the sfd. see attached pics. I also added the "about" window..

**Comment by lprecord** [comment]
![conversion_to_unix_lf_format](https://cloud.githubusercontent.com/assets/12803251/8048409/48234b62-0e51-11e5-98ec-abd99e33b32d.PNG)
![ff_about](https://cloud.githubusercontent.com/assets/12803251/8048410/482a56dc-0e51-11e5-8277-89f1a0ecdfe4.PNG)
![ff_crashes_after_unix conversion](https://cloud.githubusercontent.com/assets/12803251/8048411/48300460-0e51-11e5-91b2-3e88d13c5cef.PNG)

**Comment by lprecord** [comment]
Tried the same with the latest stable version from Apr.30 and the build from May 30.

**Comment by jtanx** [comment]
Oops I think I got my comment about the line endings the other way around. Anyhow, try the latest build [from here](http://sourceforge.net/projects/fontforgebuilds/).

**Comment by jtanx** [comment]
I uploaded the latest build anyway, so just note that the latest [from here](http://sourceforge.net/projects/fontforgebuilds/) is `FontForgeSetup-09-06-2015.exe`. It may take a while to show up from now since I've just uploaded it.

**Comment by lprecord** [comment]
That build seems to solve the problem with the crashes. The "invalid 2nd order spline" messages remain though.
