### ISSUE TITLE
Change weight should not be joining points when is overlap in shape

### ISSUE THREAD

**Issue by zoghal** [fontforge/fontforge#2346]
![bug](https://cloud.githubusercontent.com/assets/174688/8056254/6e930dc2-0ebb-11e5-9475-df9c6db5cf1f.gif)
hi
Change weight should not be joining points when is overlap in shape!?

**Comment by larsenwork** [comment]
you can remove overlap prior to making it bolder - "solves" the issue

**Comment by skef** [comment]
If you look at the contour carefully you'll notice that it is (ignoring the self-overlap) effectively counterclockwise. That's going to have a weird effect when used in isolation with Change Weight.

With the new Expand Stroke code and a clockwise(ish) contour things work more or less as expected, except for some leftover triangle contours when decreasing weight. Given the remove-overlap-in-advance workaround that seems acceptable. 

If we really cared about this for some reason we could add a Change Weight "no-remove-overlap" option.
