### ISSUE TITLE
OTF small caps lost on import?

### ISSUE THREAD

**Issue by akivaatwood** [fontforge/fontforge#2352]
If I open a OTF font with small caps and then generate a new font from that the original small caps are lost (or so it seems -- the new font's small caps seem to just be scaled down)

I assume I'm doing something wrong, either on the import OR on the font generation.

Any pointers on where to look?

**Comment by larsenwork** [comment]
Look for any error messages when opening the small caps. 

Look in:  
`Element -> Font info  -> lookups`
to see if the substitution is there

**Comment by akivaatwood** [comment]
Hi
The substitution is there -- And I can see it on the font display (view- display substitutions)

Can I EDIT the small cap? (Specifically I need to place a dot under the H in both regular and small caps)

thanks

**Comment by larsenwork** [comment]
Open the lookup subtable and see what character H is substituted with and then edit that.

**Comment by akivaatwood** [comment]
according to the subtable it's u0124.a -- but if I do view-goto u1024.a I get a blank character
If I do  view- display substitutions and select c2sc I see the small cap

**Comment by larsenwork** [comment]
public font: upload it
commercial font: send to andreas at larsenwork dot com and I'll have a look and delete afterwards

**Comment by akivaatwood** [comment]
Thanks -- problem solved. Very much appreciate the help
