### ISSUE TITLE
Bad glyph (3), its definition extends beyond the space allowed for it

### ISSUE THREAD

**Issue by Chlara** [fontforge/fontforge#2354]
Hi FontForge

I use FontForge to analyse one font extracted from one pdf, who cause some problems to print. Can you say my what the Warning “Bad glyph (3), its definition extends beyond the space allowed for it” means?

This Warning comes from fontforge/fontforge/parsettf.c    Line 2289: LogError(_("Bad glyph (%d), its definition extends beyond the space allowed for it\n"), gid );

I don’t really understand C and it’s the first time I analyse a font…

Thanks
Chlara

**Comment by larsenwork** [comment]
Always a good idea to provide a screenshot of the culprit and/or link to the file in question. Note you can reference code by adding e.g. #L2289 to the url:  https://github.com/fontforge/fontforge/blob/414578478f89c8ab6d62da96381b6b7cf5e1343a/fontforge/parsettf.c#L2289

**Comment by Chlara** [comment]
Thanks for the note with the reference code.
I have found an solution to attache the ttf by changing the extension to ttf.gif....
![calibri_47 0 obj ttf](https://cloud.githubusercontent.com/assets/1552939/8106310/58478b5c-1040-11e5-9134-114d876114a0.gif)

**Comment by jtanx** [comment]
The warning means that the supposed location of the glyph data points to some location outside of the table, which is invalid.

E.g. The `loca` table suggests that the location of a particular glyph is at an offset of 10 bytes into the `glyf` table, but the `glyf` table is only 5 bytes long.
