### ISSUE TITLE
Cannot Open 3+ Fonts from TTC

### ISSUE THREAD

**Issue by Vassile-D** [fontforge/fontforge#2355]
I tried to use FontForge to merge two TTCs within the same font family to a single TTC file for easy distribution. But FontForge would freeze, and then crash while opening a third font. No error message were given, nor did Windows report FontForge closed unexpectedly.

If you need an example, try to open three or more font files from TTCs (you can easily find them in Windows' Font folder, e.g. "MingLiu.ttc" ).

FontForge/Lib Version: 09:31 AWST 2015/05/01
Platform: Windows 8.1 Pro x64
Running from installation on disk D (non-system, non-admin execution).

**Comment by jtanx** [comment]
This may be related to #2309. Please try the latest build from [here](http://sf.net/p/fontforgebuilds) and tell me if it still crashes.

Also; how much RAM do you have?

**Comment by Vassile-D** [comment]
Build **x86-64 333856 r1** seems to be working. I still have one TTC cannot be opened at all but I think it's the only one. It probably has bad TTC structure implemented that's causing crashes.

I have 16 GB RAM on a desktop PC so handling couple fonts should be a problem.

**Comment by jtanx** [comment]
Please try it with the 32-bit version (should be 33386-r3), since I haven't updated the 64-bit version yet. If you could indicate what TTC that is (or possibly even upload it), that would be great - even with a bad TTC structure FontForge should not be crashing.

Thanks!

**Comment by Vassile-D** [comment]
32-bit build **i686 333856-r3 does NOT work**. None of the TTCs (and their combinations) can be read up to the third font. It would stuck at "Loading font... Reading glyphs..." and freeze for 2~3 seconds then quit, with no error message given.

However, as mentioned, 64-bit build **x86-64 333856-r1** has no problem.

Another TTC which might have bad structures and was causing crashes is now readable. I did a system restore before doing these new tests (because I messed up with Windows' Font folder) so it wasn't a FF issue.

**Comment by jtanx** [comment]
Interesting. I have a feeling it may be because it's reaching the [memory limit](http://stackoverflow.com/questions/639540/how-much-memory-can-a-32-bit-process-access-on-a-64-bit-operating-system) for 32-bit processes since typically TTCs contain a large number of glyphs. Could you monitor memory usage while it loads the TTCs?

**Comment by Vassile-D** [comment]
New build **i686 99DA6F R2** can open up to 5 fonts at once and will crash while loading the 6th one.

You're right. It is a memory limit issue. It *(fontforge.exe)* always crashes at around 1800 MB memory usage, just before reaching 32-bit 2GB memory limit.

I don't know how you manage to push the boundary further (from opening 3 fonts to 5 fonts at the same time) in latest builds, but my issue is resolved: **Nothing directly related to FontForge, gotta blame it on the hardware.**

**Comment by jtanx** [comment]
That is interesting indeed! You can of course try using the 64-bit builds from fontforgebuilds which will overcome the 2GB limit. Just note that there is extra memory overhead working with the same number of fonts for various reasons, and that the Windows 64-bit builds tend to be more experimental and/or less frequently updated.

**Comment by adrientetar** [comment]
You can bump to 3GB per program with certain boot config: https://msdn.microsoft.com/en-us/library/windows/desktop/bb613473(v=vs.85).aspx
