### ISSUE TITLE
Error when trying to build from source

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2356]
@lpsandaruwan and @frank-trampe might be able to help :)

I building from source following the guide in `osx/README` and in my first build went fine but trying to build again I get `Warning: Only cleaning in ~/.macports; insufficient privileges for standard locations` and can't get further. Any ideas? I'd like to be able build from src so I can test my PR's properly before submitting:) 

```
ambp:~ andreaslarsen$ portindex
Creating port index in /Users/andreaslarsen

Total number of ports parsed:   0 
Ports successfully parsed:  0 
Ports failed:           0 
Up-to-date ports skipped:   0

ambp:~ andreaslarsen$ cd /usr/local/src/github-fontforge/osx
ambp:osx andreaslarsen$ ./force-rebuild.sh
... updating local git repo from github ... 
Already up-to-date.
/usr/local/src/github-fontforge/osx
--->  Cleaning fontforge
--->  Cleaning fontforge
Warning: Only cleaning in ~/.macports; insufficient privileges for standard locations
... starting build ... 
--->  Computing dependencies for fontforge.
--->  Scanning binaries for linking errors
--->  No broken files found.
ambp:osx andreaslarsen$ cd /opt/local/var/macports/build/_usr_local_src_github-fontforge_fontforge_osx/
-bash: cd: /opt/local/var/macports/build/_usr_local_src_github-fontforge_fontforge_osx/: No such file or directory
```

**Comment by davelab6** [comment]
`sudo ./force-rebuild.sh` ?

**Comment by davelab6** [comment]
Ah, I think that error happens here:

https://github.com/fontforge/fontforge/blob/master/osx/force-rebuild.sh#L17

Try commenting out that line, because https://github.com/fontforge/fontforge/blob/master/osx/force-rebuild.sh#L16 is the same command _with_ sudo, so that should work

**Comment by frank-trampe** [comment]
@davelab6, I think that that line cleans the user-specific files for safety purposes.

**Comment by frank-trampe** [comment]
It seems to me that macports is missing the local FontForge directory. Is `file:///usr/local/src/github-fontforge` above the default sources in `/opt/local/etc/macports/sources.conf`?

**Comment by larsenwork** [comment]
![screen shot 2015-06-12 at 23 32 51](https://cloud.githubusercontent.com/assets/3859425/8140375/60451704-115b-11e5-9eab-0294a70bbfc1.png)

This is my conf

**Comment by larsenwork** [comment]
@davelab6 how can I comment out when it automatically syncs with online master?

**Comment by davelab6** [comment]
Change the portfile to point to your local copy via `file://` url

**Comment by larsenwork** [comment]
commenting out + portfile didn't work, sudo did

**Comment by larsenwork** [comment]
Next issue: 
```
ambp:osx andreaslarsen$ sudo ./force-rebuild.sh
... updating local git repo from github ... 
Already up-to-date.
/usr/local/src/github-fontforge/osx
--->  Cleaning fontforge
--->  Cleaning fontforge
... starting build ... 
--->  Computing dependencies for fontforge.
--->  Scanning binaries for linking errors
--->  No broken files found.
ambp:osx andreaslarsen$ cd /opt/local/var/macports/build/_usr_local_src_github-fontforge_fontforge_osx/
-bash: cd: /opt/local/var/macports/build/_usr_local_src_github-fontforge_fontforge_osx/: No such file or directory
```
What I have in my build folder is this:
![screen shot 2015-06-13 at 01 07 17](https://cloud.githubusercontent.com/assets/3859425/8141542/9313ec5c-1168-11e5-8c17-ac46ed0c3e26.png)

**Comment by larsenwork** [comment]
I am updating the documentation with every successful step btw

**Comment by larsenwork** [comment]
Now terminal will let me cd into the folder - don't know why it wouldn't before. Next bump on the road:

```
ambp:_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_fontforge andreaslarsen$ bash ./osx/create-osx-app-bundle.sh
bash: ./osx/create-osx-app-bundle.sh: No such file or directory
ambp:_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_fontforge andreaslarsen$ 
```

**Comment by larsenwork** [comment]
I have the file `create-osx-app-bundle.sh` three places on my system: 

```
/usr/local/src/github-fontforge/osx/
/Library/Caches/Homebrew/fontforge--git/osx/create-osx-app-bundle.sh 
/Users/andreaslarsen/Git/fontforge/osx/create-osx-app-bundle.sh 
```

**Comment by frank-trampe** [comment]
I think that that is the wrong folder. If you use the sources from macports.org, you will get stale code.

If the correct folder does not exist, there is a prior step that is not working.

Try running `portindex` and `sudo portindex`. Tell me what they say.

**Comment by larsenwork** [comment]
@frank-trampe where should I run the portindex ?

**Comment by larsenwork** [comment]
```
ambp:~ andreaslarsen$ cd /usr/local/src/github-fontforge/osx
ambp:osx andreaslarsen$ portindex
Creating port index in /usr/local/src/github-fontforge/osx

Total number of ports parsed:	0 
Ports successfully parsed:	0 
Ports failed:			0 
Up-to-date ports skipped:	0

ambp:osx andreaslarsen$ sudo portindex
Password:
Creating port index in /usr/local/src/github-fontforge/osx

Total number of ports parsed:	0 
Ports successfully parsed:	0 
Ports failed:			0 
Up-to-date ports skipped:	0

ambp:osx andreaslarsen$ 
```

**Comment by frank-trampe** [comment]
So what I think you need to do is to put the source folder for fontforge inside of the folder github-fontforge (the category folder) and then run portindex from inside github-fontforge.

**Comment by larsenwork** [comment]
so I'd have e.g. `/usr/local/src/github-fontforge/fontforge-src/` ?

**Comment by larsenwork** [comment]
@frank-trampe getting closer and closer thanks to you but now I bumped into this after the bootstrap is done (full output [gist](https://gist.github.com/larsenwork/620ba6f157937f3f040a):

```
bootstrap: Done.  Now you can run './configure'.
Error: org.macports.extract for port fontforge returned: xcode-select: error: invalid argument '.'
Usage: xcode-select [options]

Print or change the path to the active developer directory. This directory
controls which tools are used for the Xcode command line tools (for example, 
xcodebuild) as well as the BSD development commands (such as cc and make).

Options:
  -h, --help                  print this help message and exit
  -p, --print-path            print the path of the active developer directory
  -s <path>, --switch <path>  set the path for the active developer directory
  --install                   open a dialog for installation of the command line developer tools
  -v, --version               print the xcode-select version
  -r, --reset                 reset to the default command line tools path
Warning: targets not executed for fontforge: org.macports.activate org.macports.extract org.macports.patch org.macports.configure org.macports.build org.macports.destroot org.macports.install
Please see the log file for port fontforge for details:
    /opt/local/var/macports/logs/_usr_local_src_github-fontforge_fontforge_osx/fontforge/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port fontforge failed
```
i did `ambp:osx andreaslarsen$ xcode-select -p` which points to `/Applications/Xcode.app/Contents/Developer` which looks like this:
![screen shot 2015-06-13 at 11 52 53](https://cloud.githubusercontent.com/assets/3859425/8143881/c2ac65de-11c2-11e5-9772-1b8055548d8f.png)

**Comment by frank-trampe** [comment]
@andreaslarsen, did you install the Xcode command line tools?

**Comment by larsenwork** [comment]
@frank-trampe yep, e.g.
```
ambp:~ andreaslarsen$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
I tried `sudo xcode-select -switch /Library/Developer/CommandLineTools` but that just resulting in the terminal thinking I xCode wasn't installed at all when running `sudo ./force-rebuild.sh`

**Comment by larsenwork** [comment]
I've been really busy lately but I'd really like to get this working - can @davelab6 , @pathumego or some other mac user try to replicate what I've done and see if they are more lucky/skilled than me?

**Comment by larsenwork** [comment]
@davelab6 @frank-trampe any suggestions as to how we can solve this? I can maybe do screen sharing or something similar if frank or someone else has ideas they want to try "live".

**Comment by davelab6** [comment]
I'm going to get hold of a clean 10.10 machine today, I'll keep you posted

**Comment by larsenwork** [comment]
@davelab6 hehe...sounds like you get your other machines from shady places...

I can see  just updated xcode CLI so I'll try to see if that helped in any way

**Comment by glyphobet** [comment]
@larsenwork @davelab6 @frank-trampe I think the changes in #2409 should help get a working Mac OS X build.

**Comment by glyphobet** [comment]
One more point about building: my build may have failed initially until I installed IPython with MacPorts. Or it may have been failing due to some other issue. Created #2410 for clarification.

**Comment by larsenwork** [comment]
@glyphobet great work - I will hopefully have some time this weekend to look at it again :+1:

**Comment by davelab6** [comment]
Building git master on homebrew fails:
```
$ brew install fontforge --HEAD --with-giflib --with-extra-tools
==> Installing fontforge
==> Cloning https://github.com/fontforge/fontforge.git
Cloning into '/Library/Caches/Homebrew/fontforge--git'...
remote: Counting objects: 2608, done.
remote: Compressing objects: 100% (2369/2369), done.
remote: Total 2608 (delta 307), reused 1942 (delta 163), pack-reused 0
Receiving objects: 100% (2608/2608), 22.51 MiB | 3.78 MiB/s, done.
Resolving deltas: 100% (307/307), done.
Checking connectivity... done.
==> Checking out branch master
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/fontforge/HEAD --disable-silent-rules
./configure: line 18115: /usr/local/bin/python: No such file or directory
./configure: line 18116: cd: /../../pkgconfig: No such file or directory
found python pkg_config information: 
checking whether /usr/local/bin/python version is >= 2.7... no
configure: error: Python interpreter is too old
 
READ THIS: https://git.io/brew-troubleshooting
 
These open issues may also help:
fontforge 20150612 (https://github.com/Homebrew/homebrew/pull/40631)
$
```
Building last release is ok:
```
$ brew install fontforge --with-giflib --with-extra-tools
==> Downloading https://github.com/fontforge/fontforge/archive/20150430.tar.gz
==> Downloading from https://codeload.github.com/fontforge/fontforge/tar.gz/20150430
######################################################################## 100.0%
==> ./bootstrap
==> ./configure --prefix=/usr/local/Cellar/fontforge/20150430_3 --disable-silent-rules --with-pythonbinary=/System/Library/Frameworks/Python.framework/Versions/2.7/
==> make
==> make install
==> make
Warning: fontforge dependency gettext was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/fontforge/20150430_3: 1307 files, 35M, built in 3.2 minutes
$
```

**Comment by davelab6** [comment]
I initially posted this [as a gist](https://gist.github.com/davelab6/740f70a1d98248af1767#comment-1489689) assuming it might something I'd done, and @DomT4 could advise, but in fact its deeper, and now there's a comment on the gist from @tdsmith as follows

> Hi, @DomT4 pointed me here. The solution to the Python problems Fontforge is having with Homebrew is to stop linking the Python extension modules to libpython. Only the executables that embed the interpreter need to be linked to Python. Python extension modules should be built with `-undefined dynamic_lookup` instead, so that the libpython symbols are resolved at import time.
> 
> A rough solution to that is encapsulated here: https://github.com/tdsmith/homebrew/commit/607b4fe1f6f379d6e9d263cad6c4f2ae86da337d -- setting PYTHON_LIBS to `-undefined dynamic_lookup` and modifying only `libfontforgeexe_la_LDFLAGS` in `fontforgeexe/Makefile.am` to include `-lpython`.
> 
> More formally, the build system should probably represent the flags necessary to build a Python extension module separately from the flags necessary to embed the Python interpreter.

**Comment by larsenwork** [comment]
Sorry, I've been crazy busy lately - what's the status on this? Has @davelab6, @glyphobet or anyone else been more successful?

**Comment by frank-trampe** [comment]
@davelab6 wanted me to look at it, but I was hoping that @tdsmith would be able to submit a pull request. If this is not likely, I can jump back in next week.

**Comment by glyphobet** [comment]
@larsenwork I was able to successfully build on a Mac OS X 10.9 system with MacPorts installed, with the changes in #2409 merged.

The issues reported in comments by @davelab6 arise when trying to build on a Mac OS X system with Homebrew installed, but this bug appears to have started out as a question about building using the build scripts in `fontforge/osx/`, which are explicitly *only* for MacPorts systems. So while the Homebrew issues are probably real issues, they should most likely be in their own independent bug report.

**Comment by DomT4** [comment]
I'm fairly sure the problems highlighted exist if you build on any system with Homebrew present, not just if you build within Homebrew itself, AFAIK. FontForge makes special effort to detect and use Homebrew's Python.

**Comment by glyphobet** [comment]
@DomT4 I'm not denying that at all. However, as this issue started out as an issue about building under MacPorts, the Homebrew discussion probably belongs on its own issue.

**Comment by DomT4** [comment]
Oh sure, no problem with that. Just wanted to clarify that the error can/will repro outside of the Homebrew build system as well.
