### ISSUE TITLE
please add vivid builds to launchpad PPA

### ISSUE THREAD

**Issue by jeras** [fontforge/fontforge#2357]
It might make sense to also add willy, to see how it compiles in a newer environment.

I would also suggest creating a recipe for git daily builds, but Launchpad requires making a Bazaar copy of the git project, and Bazaar can be annoyingly dysfunctional.

**Comment by pathumego** [comment]
Launchpad support Git now right? http://blog.launchpad.net/general/git-code-hosting-beta

**Comment by jeras** [comment]
I have not noticed this blog post, it was not widely publicised. Since not mentioned, recipes are probably not supported on git yet, in any case they need git import, which as I understand does not work yet.

**Comment by pathumego** [comment]
@jeras Im not familiar at all with PPA and launchpad related stuff :)  But +1 to adding new builds

**Comment by frank-trampe** [comment]
@jeras, are you on one of those newer platforms? Does FontForge compile correctly for you?

**Comment by jeras** [comment]
I copied it on Launchpad to my PPA, but for Vivid. It compiled, and I was able to install and run it.
https://launchpad.net/~iztok.jeras/+archive/ubuntu/ppa
