### ISSUE TITLE
Kerning not Effective in Inkscape or Open Office

### ISSUE THREAD

**Issue by Imagefile** [fontforge/fontforge#2360]
Hello,
spent the last month creating a font for a comic strip I've been working on, have finally finished and am very happy with how my font looks in the Metrics window.  Once I generate it and use it in Inkscape (program I'm putting my comics together in) the kerning does not work.
I created this kerning using the Fontforge tutorial on this site.
I apologize as I am sure this topic has been posted before- I found many others had asked about it on various sites, some even seem to have had success.  Not for me though.  I cannot figure out how to access the "traditional kerning" they allude to.
Any help would be appreciated.  I'm looking forward to banging my head against the next roadblock in this project.

**Comment by larsenwork** [comment]
I assume it looks correct in other programs since you're not mentioning any other problems?
Difficult for us to say without having the font. You can send it to me privately on andreas at larsenwork dot com if you don't want to post it here.

**Comment by Imagefile** [comment]
Thanks for responding!  I don't mind sharing- planning on adding it to some common use font website eventually anyway... though I doubt anyone would want it!
Here's the Fontforge file: 
https://www.dropbox.com/s/vrtsp9s0mowga8v/Wizard_19.sfd?dl=0
and here's a TTF (which is how intend to use it):
https://www.dropbox.com/s/lykuvu8enqb67a3/Wizard.ttf?dl=0
Thanks again!

**Comment by larsenwork** [comment]
Just had a quick look and I'd probably start by validating the font if I were you - open paths and stuff is never good. 
You can ignore the error about missing extrema. 
Your kerning tables look correct - although I don't know why you've used three subtables? One for classes and one for pairs should be enough.

**Comment by Imagefile** [comment]
OK, thanks for the advice!
I'm working on validating and combining the sub-tables.
We'll see if that shakes something loose- I'll let you know!

**Comment by Imagefile** [comment]
OK!  Thanks to your advice the kerning is now working!  I'm sure I'll still make a lot of changes- but the principle seems to be sound!
Font: 
https://www.dropbox.com/s/lykuvu8enqb67a3/Wizard.ttf?dl=0
Font Forge File:
https://www.dropbox.com/s/10lk4yyxhcmqo0e/Wizard_21.sfd?dl=0

**Comment by larsenwork** [comment]
:+1:
