### ISSUE TITLE
Can't start fontforge (Crashes on startup)

### ISSUE THREAD

**Issue by RePixelated** [fontforge/fontforge#2364]
Fontforge does not startup on hungarian Windows 8.1. It crashes before anything could be displayed. The only thing happening is a windows popup about the application not responding.
I have tried running it using administrator rights, compatibility mode (Windows 7, Vista SP2, XP SP3) and even reinstalling but nothing worked.
I have installed the latest Fontforge from the installer available on the official website

The output of fontforge.bat is the following:

----------------------------------------------------------------------------------------------------------------------

Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 08:25 AWST 13-Jun-2015-ML-TtfDb-D.
 Based on source from git with hash: 5134fe27846202c45cc0e1392705320e3b99a6fe
no xdefs_filename!
TESTING: getPixmapDir:C:/Program Files (x86)/FontForgeBuilds/share/fontforge/pix
maps
TESTING: getShareDir:C:/Program Files (x86)/FontForgeBuilds/share/fontforge
TESTING: GResourceProgramDir:C:/Program Files (x86)/FontForgeBuilds/bin
trying default theme:C:/Program Files (x86)/FontForgeBuilds/share/fontforge/pixm
aps/resources

(fontforge.exe:2332): GLib-CRITICAL **: g_dir_open_with_errno: assertion 'wpath
!= NULL' failed

(fontforge.exe:2332): GLib-WARNING **: GError set over the top of a previous GEr
ror or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before
it's set.
The overwriting error message was: Error opening directory 'C:/Users/Zal??nt/Doc
uments/': No such file or directory

----------------------------------------------------------------------------------------------------------------------

Could the problem be that with my username has non-Unicode characters in it? What I really do not understand from this output is that it tries to access the folder 'C:\Users\Zalán' when my user is in 'C:\Users\ZalánBálint'. The folder it presumably tries to access does not even exist.

**Comment by jtanx** [comment]
Oops, I think I know why. I'll have a new build out in about an hour.

**Comment by RePixelated** [comment]
Thanks. That was fast. :)

**Comment by jtanx** [comment]
Keep it open for now, we don't know if what I did will fix it until you can test it :)

I'm still resolving a few issues, so it may be a little while more.

**Comment by RePixelated** [comment]
OK. No problem. :)

**Comment by jtanx** [comment]
@RePixelated, can you try installing [this](https://github.com/fontforge/fontforge/releases/download/20150612/FontForgeSetup-14-06-2015-beta.exe) version to see if it is any better?

**Comment by RePixelated** [comment]
Yes. The new build works. It opens up without problem.

**Comment by RePixelated** [comment]
Thanks for the great and quick troubleshooting. :)

**Comment by jtanx** [comment]
Nice! Thanks for testing!
