### ISSUE TITLE
FontForge crashes repeatedly on both my systems.

### ISSUE THREAD

**Issue by PJMiller** [fontforge/fontforge#2365]
I installed FontForge on first my desktop computer and then on my laptop.  It is unusabel, it stops working repeatedly (you konw the windows dialog box which pops up over your application saying FontForge.exe has stopped working, Windows is looking for a solution).

My systems are both Windows 7 64 bit.

If I cannot edit a glyph for more than a few seconds without a crash and if I cannot save the font without risking a crash then the program is useless to me.

**Comment by lpsandaruwan** [comment]
Did you tried adding DEP exceptions, try this.
1. Open the Control Panel. (Classic View)
2. Click on Advanced system settings.(in upper left green area)
3. Click on the Continue button in the UAC prompt.
4. Click on the Settings button under Performance section.
5. Click on the Data Execution Prevention tab.
6. Click on "Turn on DEP for all programs and services except those I select" and press "Add." You will now add your program(exe file), expansions and Stuff Packs to the DEP exception list. Copy-and-paste these "C:" locations in the spot where it says "File Name."

**Comment by jtanx** [comment]
No, don't do that. That's skirting the issue.

I'm uploading a new release soon, so please try installing that and see if it helps.

**Comment by jtanx** [comment]
@PJMiller can you try installing [this](https://github.com/fontforge/fontforge/releases/download/20150612/FontForgeSetup-14-06-2015-beta.exe) release to see if it is any better?

**Comment by NuttShell** [comment]
in any version Windows (does not matter in which - 7, 8, 8.1) add
[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"FullPath2FontForge.exe"="~ WIN7RTM"
FontForge will stop crashes

**Comment by jtanx** [comment]
@NuttShell, can you try the release mentioned above to see if that fixes the issue without your workaround?

**Comment by NuttShell** [comment]
FontForge version
Based on sources from 08:25 AWST 13-Jun-2015-ML-TtfDb-D.
Based on source from git with hash: 5134fe27846202c45cc0e1392705320e3b99a6fe
FontForge crash, issue exist

**Comment by NuttShell** [comment]
when add Registry key, all ok

**Comment by jtanx** [comment]
@NuttShell, as I said earlier, can you try [this build](https://github.com/fontforge/fontforge/releases/download/20150612/FontForgeSetup-14-06-2015-beta.exe)?

**Comment by NuttShell** [comment]
Yes, I try. Issue exist

**Comment by jtanx** [comment]
Hmm... What is your installation path, version of Windows (and region/language setting)? E.g. Windows 8.1, English UK

**Comment by NuttShell** [comment]
i tried on many Windows (real and virtual - 7, 8, 8.1, 10) with various path with only latin letters.
region - Russian Federation

**Comment by NuttShell** [comment]
this issue begins from 2012 year, and only one exit for me - reg.key.

**Comment by jtanx** [comment]
Right, so it was an issue, even before the recent (past few months) releases?

**Comment by NuttShell** [comment]
yes, I collected and trying all of fontforge releases from 2009 years - in all of this crash is present.
I work with cmd shell and convert fonts with ff script. Not all fonts, but some will begin crashes fontforge.

**Comment by NuttShell** [comment]
I noticed - if you do the conversion in a (for .. repeat on error) cycle, then the problem font can get a good result after converting 2 or 3 attempts

**Comment by jtanx** [comment]
@NuttShell, could you try running this [debug version](https://github.com/fontforge/fontforge/releases/download/20150612/FontForge-mingw-w64-i686-99da6f-debug.7z) of FontForge:

1. Run `fontforge-debug.bat` from a console (CMD.exe)
2. It automatically starts GDB - when it crashes, it will open a text file containing debugging information.

Can you upload this debugging information?

**Comment by PJMiller** [comment]
I have downloaded the new version and installed it.  I have used it for a while and it definately seems a lot more stable than the other one but I am still a bit nervous about it because when I installed the first version there was a 'honeymoon period' where it seemed stable then I started getting crashes and it seemed to become more unstable with time.

I am not a programmer, I don't want to run the debug version from a console, it would probably go horribly wrong.

I will try putting the suggested registry key in but I am a bit nervous about messing with the registry.  What does this key do?

**Comment by PJMiller** [comment]
I did not add the key.  There were not enough details in the post. Is this added as as a string value subordinate to the Layers key or is it the data value for the layers key?

**Comment by NuttShell** [comment]
PJMiller:
Compatibility Mode with Windows 7
On windows 7+
Right click c:\Program Files (x86)\FontForgeBuilds\bin\fontforge.exe
Click properties
Click compatibility tab
Check the box ‘Run this program in compatibility mode for‘
Select from drop down list the "Windows 7"
Hit apply. Hit Ok.

jtanx:
something wrong with commandline version
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\fontforge.debug
[New Thread 6280.0x76c]
warning: SHIMVIEW: ShimInfo(Complete)

warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libfontforgeexe-2.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libgdraw-5.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libgutils-2.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libgunicode-4.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libfontforge-2.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libcairo-2.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libpango-1.0-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libpangocairo-1.0-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libpangoxft-1.0-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libX11-6.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libXft-2.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libuninameslist-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libspiro-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libX11-xcb-1.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libxcb-render-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libxcb-1.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libpangoft2-1.0-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libpangowin32-1.0-0.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libXrender-1.debug
warning: section .gnu_debuglink not found in E:\000\tools\bin\ff\.debug\libXau-6.debug
warning: HEAP[ff.exe]: 
warning: Heap block at 0279E698 modified at 0279E6B0 past requested size of 10


Program received signal SIGTRAP, Trace/breakpoint trap.
0x77e87077 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#0  0x77e87077 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x77e41537 in ntdll!LdrSetAppCompatDllRedirectionCallback () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00530000 in ?? ()
#3  0x77e860e4 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x77e269ea in ntdll!RtlHashUnicodeString () from C:\Windows\SYSTEM32\ntdll.dll
#5  0x77de1eaa in ntdll!RtlFreeHeap () from C:\Windows\SYSTEM32\ntdll.dll
#6  0x776fb0f9 in msvcrt!free () from C:\Windows\SYSTEM32\msvcrt.dll
#7  0x00530000 in ?? ()
#8  0x6e963fb5 in arrayfree (a=0x27a1128) at scripting.c:129
#9  0x6e9644cb in calldatafree (c=0x28ece0) at scripting.c:222
#10 0x6e9833b2 in docall (c=0x28f5e0, name=0x28f0ff "ToString", val=0x28f500) at scripting.c:9313
#11 0x6e9835bc in handlename (c=0x28f5e0, val=0x28f500) at scripting.c:9367
#12 0x6e98495c in term (c=0x28f5e0, val=0x28f500) at scripting.c:9610
#13 0x6e985152 in mul (c=0x28f5e0, val=0x28f500) at scripting.c:9755
#14 0x6e985381 in add (c=0x28f5e0, val=0x28f500) at scripting.c:9800
#15 0x6e98570c in comp (c=0x28f5e0, val=0x28f500) at scripting.c:9875
#16 0x6e985997 in _and (c=0x28f5e0, val=0x28f500) at scripting.c:9918
#17 0x6e985b0a in _or (c=0x28f5e0, val=0x28f500) at scripting.c:9949
#18 0x6e985c97 in assign (c=0x28f5e0, val=0x28f500) at scripting.c:9981
#19 0x6e985ce6 in assign (c=0x28f5e0, val=0x28f568) at scripting.c:9985
#20 0x6e9861e5 in expr (c=0x28f5e0, val=0x28f568) at scripting.c:10059
#21 0x6e986bc1 in ff_statement (c=0x28f5e0) at scripting.c:10268
#22 0x6e9873f7 in ProcessNativeScript (argc=6, argv=0x53c2e0, script=0x0) at scripting.c:10416
#23 0x6e987932 in _CheckIsScript (argc=6, argv=0x53c2e0) at scripting.c:10508
#24 0x6e987a33 in CheckIsScript (argc=6, argv=0x53c2e0) at scripting.c:10545
#25 0x63797b42 in fontforge_main (argc=6, argv=0x53c2e0) at startui.c:1056
#26 0x00401630 in main (argc=6, argv=0x53c2e0) at main.c:39
$1 = "locals..."
No symbol table info available.
#1  0x77e41537 in ntdll!LdrSetAppCompatDllRedirectionCallback () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#2  0x00530000 in ?? ()
No symbol table info available.
#3  0x77e860e4 in ntdll!RtlpNtSetValueKey () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#4  0x77e269ea in ntdll!RtlHashUnicodeString () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#5  0x77de1eaa in ntdll!RtlFreeHeap () from C:\Windows\SYSTEM32\ntdll.dll
No symbol table info available.
#6  0x776fb0f9 in msvcrt!free () from C:\Windows\SYSTEM32\msvcrt.dll
No symbol table info available.
#7  0x00530000 in ?? ()
A debugging session is active.

	Inferior 1 [process 6280] will be killed.

Quit anyway? (y or n) [answered Y; input not from terminal]

**Comment by PJMiller** [comment]
I don't need compatability mode for Windows 7 because I have Windows 7.

Sorry ...I only used the new installation for a short time because I had other things to do but I will use it tomorrow (Monday) and let you know how I get on.  For the short time I did use it, it seemed more stable.

Thanks.

**Comment by jtanx** [comment]
@NuttShell it looks like you attached the backtrace but deleted it? The backtrace is what I need. The debugger will not prevent it from crashing but it can tell us where the crash is occurring. Can you try it without the compatibility mode fix?

**Comment by jtanx** [comment]
@NuttShell  if possible, can you also attach the script that you are using? Thanks.

**Comment by NuttShell** [comment]
**jtanx** send link to email

**Comment by jtanx** [comment]
@NuttShell, thanks I found the reason for that crash - specifically this: e6d0a5704455e63e9332ace44ae52f4bce8838bc.

This may also be the reason why sometimes your script crashed and sometimes it worked in the past.

However, I cannot reproduce your issue with regards to having to apply the Windows 7 compatibility mode. I will upload a new test build soon - could you try this in debug mode (with the registry fix disabled) and send me the crash report?

Thanks!

**Comment by jtanx** [comment]
@NuttShell, could you please try [this](https://github.com/fontforge/fontforge/releases/download/20150612/FontForge-mingw-w64-i686-99da6f-debug-r2.7z) debug build?

**Comment by NuttShell** [comment]
Test without StrSplit - work fine, thank you!
Waiting for new build

**Comment by NuttShell** [comment]
**jtanx ** with last build all ok. Work fine for me.

**Comment by jtanx** [comment]
Thanks for testing!
