### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by akivaatwood** [fontforge/fontforge#2378]
I have an existing font -- if I load it up and try to generate a font (just changing the name) I get:

INternal Error:
Attempt to output 65657 into a 16 bit field. it will be truncated and the file will not be useful

(the max value is around 93500 or so...)

Any workaround?

**Comment by larsenwork** [comment]
No error/warning messages when you load the font?

**Comment by akivaatwood** [comment]
Just a few glyph mapping warnings.

The font DOES have a HUGE number of diacritic mark mappings -- I know 
the author ran into VOLT limits when he was building the tables...

**Comment by jtanx** [comment]
What operating system are you using?

**Comment by akivaatwood** [comment]
Linux. The when the font was originally build (not by me) they ran up against VOLT limits due to the large number of diacritic mark positionings

**Comment by larsenwork** [comment]
Can you post the font in question?

**Comment by akivaatwood** [comment]
It's a commercial font -- sent privately...

**Comment by larsenwork** [comment]
Got it and I can generate without problems on Mac. The font has some other errors you might wan't to fix but they're not related to your original issue.

![screen shot 2015-06-17 at 11 13 13](https://cloud.githubusercontent.com/assets/3859425/8203408/fc7b6108-14e1-11e5-8ef9-2ee395efb924.png)

**Comment by larsenwork** [comment]
@frank-trampe is the linux wizard around here

**Comment by akivaatwood** [comment]
Thanks -- I'll install to my mac...


I knew about those errors -- that's exactly why I wanted to load the font up...

**Comment by akivaatwood** [comment]
Installed to mac -- get same errror when generating a OpenType (CFF)
TTF generates fine -- running tests now

**Comment by akivaatwood** [comment]
What settings did you use to generate the font?

**Comment by larsenwork** [comment]
![screen shot 2015-06-17 at 12 21 20](https://cloud.githubusercontent.com/assets/3859425/8204784/6a9f7b70-14eb-11e5-8e50-a0d678d803ef.png)

**Comment by akivaatwood** [comment]
thanks
