### ISSUE TITLE
Test suite requires missing fonts

### ISSUE THREAD

**Issue by mskala** [fontforge/fontforge#2379]
George's old-time test suite in /tests requires a lot of files that are not in the source tree.  There's a vague recommendation in the README file for people to download them, but it doesn't say _from where_.  I imagine that many of them are commercial (possibly "free with strings attached") fonts that we're not allowed to distribute.  Some (or acceptable substitutes) may be packaged with popular operating systems, in which case the build system might be able to find them even if we don't distribute them.

Ideally, we should have freely distributable fonts for all test cases.  If the missing files are, or can be substituted by, standard OS-supplied fonts, then the build system should find and use the existing copies that may be on a user's system already.  Failing that, we should at least say where users can obtain the fonts that the tests need and we aren't allowed to distribute.  If even that is not possible (because the identity of the missing files may be lost in the mists of time), then these tests should be removed from the suite.

**Comment by adrientetar** [comment]
Duplicate of #1835

**Comment by mskala** [comment]
In that case I'll close, but hope this can count as some kind of a vote for attention to the other instance.
