### ISSUE TITLE
Closing expand stroke dialog with esc -> crash

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2384]
I haven't figured out how to do a proper crash rapport on Mac but you might be able to reproduce. 

**Always**
Open Outline Window -> open expand stroke dialog -> press esc -> crash

**Sometimes**
Open Outline Window -> open expand stroke dialog -> press "cancel" button -> crash

**Comment by jtanx** [comment]
Duplicate(?) of #2029

**Comment by larsenwork** [comment]
@jtanx duplicate yes :oops: looks like you've already fixed? :smile:

**Comment by larsenwork** [comment]
closing as duplicate of #2029 - haven't tested it yet since we are having mac building difficulties :)
