### ISSUE TITLE
Generate: Don't include FFTM

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2389]
It is annoying to have to remove `FFTM` tables from `.ttf` fonts made by FontForge. 
- [ ] The Generate dialog should have an option to not create them
- [ ] native scripting `Generate()` should have this option
- [ ] pythong scripting `font.generate()` should have this option

**Comment by ctrlcctrlv** [comment]
...why?

http://pfaedit.org/non-standard.html#FFTM

It's just a timestamp, I'm not sure who it's hurting by leaving it there.

I'm firmly in the "more options are always better" camp (interfaces designed by committee are a list of checkboxes and I am quite okay with that) but I'm just curious why this annoys you.

**Comment by davelab6** [comment]
Unneccessary extra bytes should not exist in web fonts. Serving billions of copies of a font per day, it all adds up.

**Comment by ctrlcctrlv** [comment]
Gotcha :+1:

**Comment by dscorbett** [comment]
@ctrlcctrlv, this should be reopened.
