### ISSUE TITLE
Internal Error: Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful.

### ISSUE THREAD

**Issue by N3ur0b** [fontforge/fontforge#2391]
Hey there,

i'm using Fontforge via Pythonscript. To execute my Script, I'm using the ffpython.exe in ...\Program Files (x86)\FontForgeBuilds\bin. 
Here is my Scipt:

for file in glob.glob("*.svg"):
	glyph = font.createChar(i)
	glyph.importOutlines(file)
	ymin = glyph.boundingBox()[1]
	i+=1
font.generate(dst+"\\"+name+".ttf")

The Script runs to the Point where fontforge should generate a TTF-File and casts an Error:

Internal Error: Attempt to output 2147483647 into a 16-bit field. It will be truncated and the file may not be useful.

Interresting is that when Fontforge wasn't started as Administrator at all and it works fine. If i run the Script with ffpython.exe it only works as Admin, otherwise... Error

I need to use that without Administrator-Permissions. Is there a way around?

I am using the newest Windows Version:

FontForge Windows build (32-bit)
Sun, Jun 14, 2015  8:42:38 PM +0800
94d7f4e22d9c5a9f097f56558aaa370447542b7e [june-release]
Based on master: 99da6faa1ea3b4f80ecd333f596ea7dab205325e

My Windows Version: Win 8.1 Pro 64bit

**Comment by jtanx** [comment]
It's always useful if you provide your full script. As it is I'm guessing at what you're doing. I'm using:

~~~~
import glob,os
import fontforge

font = fontforge.font()
i=ord('a')
dst="done"
name="testfont"
try:
	os.mkdir(dst)
except OSError:
	pass

for file in glob.glob("*.svg"):
	glyph = font.createChar(i)
	glyph.importOutlines(file)
	ymin = glyph.boundingBox()[1]
	i+=1
font.generate(dst+"\\"+name+".ttf")
~~~~

I haven't run into any problems. Can you tell me what directory you're trying to save to? Does your non-administrator account have permission to save to that location? Do you have any non-ASCII(non-English) characters in the path? Can you upload the font that you're using?
