### ISSUE TITLE
Crash with symbol lookup error (uniNamesList_name)

### ISSUE THREAD

**Issue by joshuakraemer** [fontforge/fontforge#2394]
When I move the mouse pointer over a font window, Fontforge crashes immediately with the following error:

fontforge: symbol lookup error: /usr/lib/libgutils.so.2: undefined symbol: uniNamesList_name

Fontforge version: 20150430
Operating system: OpenSUSE 13.1

**Comment by jtanx** [comment]
It seems FontForge has been compiled with libuninameslist support but you don't have libuninameslist present. Is it possible for you to install it?

**Comment by joshuakraemer** [comment]
libuninameslist was already installed, version 20091231-4.1.2. I have upgraded it to version 20140731-10.1 and now it works. The problem seems to be packaging related (wrong version dependency).
