### ISSUE TITLE
How I can edit the PCF font and save it to PCF type

### ISSUE THREAD

**Issue by DemonCloud** [fontforge/fontforge#2397]
I try to edit  *.pcf font file , but it can't save with ttf or otf file.
also it cant be save to pcf file~ how do i do?

**Comment by ctrlcctrlv** [comment]
FontForge doesn't have PCF as an output format.

Save as BDF then use `bdftopcf` ftp://www.x.org/pub/xorg/X11R7.6/doc/man/man1/bdftopcf.1.xhtml . In my distribution it was packaged as [`xorg-bdftopcf`](https://www.archlinux.org/packages/extra/x86_64/xorg-bdftopcf/).

**Comment by DemonCloud** [comment]
@ctrlcctrlv 

Thank you for help
