### ISSUE TITLE
Change language on OSX?

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2398]
What the title says. If it’s not currently possible to do that, then it’s TODO.

**Comment by jtanx** [comment]
I don't use OSX so I don't know if this will work or not, but does setting e.g 

````
export LANG=fr
````

work before launching FontForge?

**Comment by jtanx** [comment]
Sorry that should be

````
export LANGUAGE=fr
````

**Comment by larsenwork** [comment]
Just out of curiosity where does one set that? :)

**Comment by adrientetar** [comment]
On the Terminal.

**Comment by aramis-erak** [comment]
This should be solvable by finding the  initialization settings file, (much like https://github.com/fontforge/fontforge/issues/2443 ), but I can't find that file's equivalent, and am having the same issue; starting from the terminal with the export LANG= every time is a hassle. I installed using MacPorts, and the interface is for some reason set to Japanese.

**Comment by alrin0000** [comment]
Change for Mac version language:
/Applications/FontForge.app/Contents/MacOS/FontForge

line 62:
export LANG=en_US.UTF-8

Change example (chinese):
export LANG=zh_TW.UTF-8

restar FontForge.

**Comment by TobiasWantzen** [comment]
In 2022 that’s still a problem. I solved it as following on MacOS 10.15:

1. Quit FontForge
2. Goto `/Applications/FontForge.app/Contents/Resources/opt/local/share/locale`
3. Find the folder with your active local, in my case: `.../de/`
4. zip that folder for backup, and delete the unzipped folder
5. Start FontForge

Now my FontForge appears in English (= fallback language).
