### ISSUE TITLE
Font with bad fill

### ISSUE THREAD

**Issue by Jerome67000** [fontforge/fontforge#2399]
Hi,

I am using the [Ionic icons repo](https://github.com/driftyco/ionicons) for building my own font icons. This repo using fontforge (in command-line) to build font files.

I have a little problem with the render on some icons :

![untitled](https://cloud.githubusercontent.com/assets/7358899/8427859/e4bf0bda-1f1a-11e5-83bc-0313b6c45abb.png)![z](https://cloud.githubusercontent.com/assets/7358899/8427853/dd58a7de-1f1a-11e5-8fa9-0fda1b0a9977.png)

note : the problem is on my linux google chrome preview and on my android app but it works on the mac google chrome preview.

I have opened my svg font in fontforge and is still the same, but the form is present :
![b](https://cloud.githubusercontent.com/assets/7358899/8427948/6695e674-1f1b-11e5-9d17-3fdfa37c6427.png)
![a](https://cloud.githubusercontent.com/assets/7358899/8427951/683a19b4-1f1b-11e5-848b-4715cd48ac0a.png)

I have checked in illustrator and no problem found.

What is wrong ? how to solve them ?

**Comment by ultrasquid** [comment]
The direction of the circle needs to be reversed.

On Tue, Jun 30, 2015 at 2:32 AM, Jérôme GULLY <notifications@github.com>
wrote:

> Hi,
>
> I am using the Ionic icons repo <https://github.com/driftyco/ionicons>
> for building my own font icons. This repo using fontforge (in command-line)
> to build font files.
>
> I have a little problem with the render on some icons :
>
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/7358899/8427859/e4bf0bda-1f1a-11e5-83bc-0313b6c45abb.png>[image:
> z]
> <https://cloud.githubusercontent.com/assets/7358899/8427853/dd58a7de-1f1a-11e5-8fa9-0fda1b0a9977.png>
>
> note : the problem is on my linux google chrome preview and on my android
> app but it works on the mac google chrome preview.
>
> I have opened my svg font in fontforge and is still the same, but the form
> is present :
> [image: b]
> <https://cloud.githubusercontent.com/assets/7358899/8427948/6695e674-1f1b-11e5-9d17-3fdfa37c6427.png>
> [image: a]
> <https://cloud.githubusercontent.com/assets/7358899/8427951/683a19b4-1f1b-11e5-848b-4715cd48ac0a.png>
>
> I have checked in illustrator and no problem found.
>
> What is wrong ? how to solve them ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2399>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by Jerome67000** [comment]
Thanks for your answer, now it work ! Maybe it's obvious for a graphic but not for me developper XD.
