### ISSUE TITLE
Obliques generation error

### ISSUE THREAD

**Issue by larsenwork** [fontforge/fontforge#2400]
The curves look al sorts of wrong. I haven't had this problem before. Any ideas what's causing this? 
Itallics works just fine.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3859425/8428706/ecd54464-1f20-11e5-81fd-829e54ef60fd.gif)
![screen shot 2015-06-30 at 12 10 20](https://cloud.githubusercontent.com/assets/3859425/8428716/0344f604-1f21-11e5-895f-463baf8b5443.png)

**Comment by ultrasquid** [comment]
You're using the Style>Oblique function. There could be a problem in there,
but a bigger problem is the curve points that have their control nodes
bending.

Can you get adequate results using the Transformations>Skew function?

On Tue, Jun 30, 2015 at 3:11 AM, Andreas Larsen <notifications@github.com>
wrote:

> The curves look al sorts of wrong. I haven't had this problem before. Any
> ideas what's causing this?
> Itallics works just fine.
>
> [image: ezgif com-video-to-gif]
> <https://cloud.githubusercontent.com/assets/3859425/8428706/ecd54464-1f20-11e5-81fd-829e54ef60fd.gif>
> [image: screen shot 2015-06-30 at 12 10 20]
> <https://cloud.githubusercontent.com/assets/3859425/8428716/0344f604-1f21-11e5-895f-463baf8b5443.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2400>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by larsenwork** [comment]
@ultrasquid style>oblique is what I've used before without problems. Didn't try skew but style>itallics worked just fine (setting scale to 100%).

I just did the old "turn off and on again" and seems to have fixed it.

Closing for now and reopening if the bug reappears.
