### ISSUE TITLE
Random files are generated, and become unresponsive

### ISSUE THREAD

**Issue by enathu** [fontforge/fontforge#2401]
When working on a font, FontForge keeps storing new files with the extension of *.sfd-[number] in the same directory - Here the [number] is a variable but serial numbers. After some point, FontForge becomes unresponsive. Usually I need to end task using Task Manager, and restart FontForge to work again.

I am using Windows 8.1, and 2015-06-12 FF Release. Here is the screenshot of how it looks with the files created by FF. ![fontforge](https://cloud.githubusercontent.com/assets/62147/8455333/bd368afc-1ffb-11e5-9b8c-8bb9323b79a5.PNG)

Is it anything to do with AutoSave? or any fix available to stop this file generation?

Thank you.

**Comment by jtanx** [comment]
Strange. Do you know if this happened with any of the older versions of FontForge?

**Comment by enathu** [comment]
In older versions, I experienced crashes repeatedly. But haven't seen any file generation like this. I only saw this file generation with 2015-06-12 FF version.

**Comment by davelab6** [comment]
The Revisions to Retain preference is here, set it to 0:

![screen shot 2015-07-01 at 9 52 08 am](https://cloud.githubusercontent.com/assets/261579/8456053/e0061220-1fd6-11e5-84dd-d3da6b4e2685.png)

**Comment by enathu** [comment]
Hi @davelab6 I have set it to 0 and tried with a new file, and it keeps generating the files. So, I went to the preferences and checked, but it showed 32. So, again I set RevisionsToRetain to 0 and the files started to generate. And the 0 now became 32 in the preferences. The cycle continues. Any idea, please?

**Comment by jtanx** [comment]
Do you have any non-English/non-ASCII characters in your install path?

**Comment by jtanx** [comment]
Also the preferences box is a bit strange - how are you saving the preferences? If you click on the 'X' button it will not save preferences - you have to press 'enter' to save

**Comment by davelab6** [comment]
When you change the setting in the UI, quit FF and check the prefs file, and see if it is `0` there

**Comment by enathu** [comment]
@jtanx No, I haven't got any non-English/non-ASCII characters in path.

Oh, that's strange. I really thought that 'Preferences' works like the Glyphs app, 'Font Info' dialog box, and I did save by clicking on the 'X'. So, now I used the Enter key to save it. So, it isn't saving any files in the there. Thank you for the enlightenment.

Do you think, does this file generation directly related to the unresponsiveness of FF? I'll keep you posted on this as I am going to work on FF, and see.

**Comment by davelab6** [comment]
Most FF dialogs with an OK button are Windows (90s) style and require you
to press OK to commit the changes made in the dialog; if you press X or
Cancel, the changes are discarded.

**Comment by enathu** [comment]
@davelab6 @jtanx Is there any particular reason, not to have an OK or Save button in the Preferences dialog, since the most of the FF dialogs have buttons to commit the changes? I am curious. :)

**Comment by davelab6** [comment]
There is one:

[image: Inline images 1]

**Comment by enathu** [comment]
@davelab6 the image you've attached, not uploaded, I reckon. Please upload it again.

**Comment by davelab6** [comment]
There is an OK Button :)

![screen shot 2015-07-01 at 3 19 56 pm](https://cloud.githubusercontent.com/assets/261579/8464429/13fb7a00-2010-11e5-9696-4b0d93246722.png)

**Comment by enathu** [comment]
But, in Windows, there is no OK button, it seems. This is what I got in the UI. Please check.
![ff-preferences-win](https://cloud.githubusercontent.com/assets/62147/8464707/18dc0aae-203c-11e5-8ccb-b3c76d58af19.PNG)

**Comment by davelab6** [comment]
Drag the window size bigger and see if it appears

**Comment by enathu** [comment]
I have dragged the window size to the entire height of the screen, and I don't see the buttons there. May be, I wonder that's why @jtanx was suggesting to use Enter key in his previous comment, https://github.com/fontforge/fontforge/issues/2401#issuecomment-117691179 Here is the screenshot of dragged window.

![ff-dragged](https://cloud.githubusercontent.com/assets/62147/8465380/b2324d3a-2041-11e5-8165-79810d2451f9.PNG)

**Comment by davelab6** [comment]
Weird!

**Comment by enathu** [comment]
**Update** - By setting `RevisionsToRetain` to `0`, I can report that the unresponsiveness/crashes are considerably low. Working with FF for last three days, I came across only five crashes, which is very low compared to the early situation. All of the crashes were sudden termination with 'not responding' dialog box, while working in Editing view.

**Comment by jtanx** [comment]
If any of these crashes are repeatable, it would be great if you could outline what you did to make it happen so that they can be fixed. Thanks!

**Comment by enathu** [comment]
@jtanx Sure, I'll make sure to specifically capture the point of the crash when it happen again. While, I have noticed the crashes often occur when I draw with the pen tool, and move anchor points -- the Editing view window freezes with 'not responding' Windows message box, and FF crashes, subsequently. But. the frequency is totally random, I reckon.

**Comment by ctrlcctrlv** [comment]
Hi, one thing. It's not weird at all the behavior he's experiencing with the preferences box. He has one of those 1366x768 monitors, so the boundry of his screen is actually smaller than the boundry of the window.

![preferences](https://cloud.githubusercontent.com/assets/838783/8572006/91a9998a-25bc-11e5-881d-3fb206a272d6.png)

The window is hard coded to be this size. It should probably not be so large, and a scrollbar should appear sooner.

**Comment by davelab6** [comment]
@enathu any luck in finding those crashes?

**Comment by enathu** [comment]
@davelab6 Frequency of crashes is very low after setting `RevisionsToRetain` to `0`. However, as I already mentioned (https://github.com/fontforge/fontforge/issues/2401#issuecomment-118929217) that I only had couple of crashes after this setting change, which are totally random, and only occurs with sudden 'not responding' message. I suspect that moving anchor points using arrow keys with `ctrl` causes a lag in the Editing View UI, and ultimately makes the FF unresponsive. But, it's not always happening. It's just random. I'll keep you posted on this.

**Comment by pathumego** [comment]
@enathu Any news?

**Comment by pathumego** [comment]
@enathu SHall I close this? Any updates?

**Comment by enathu** [comment]
@pathumego I am using the latest build (24.08.2015) -- I haven't seen any crashes so far. For the time being, I think, we can safely close this issue. Since, there is an open issue (https://github.com/fontforge/fontforge/issues/2149) on Preference Window size issue raised on this thread. So, I am closing this for the time being.

**Comment by pathumego** [comment]
@enathu Thanks!
