### ISSUE TITLE
Text overlap in website

### ISSUE THREAD

**Issue by someonewithpc** [fontforge/fontforge#2408]
When loading the website the text with links overlaps with the rest of the text. However, changing the zoom, even if getting back to the original fixes it.

If relevant, I'll add that I'm using Chrome version 43.0.2357.130 (64-bit)

**Comment by jtanx** [comment]
I think this should be posted on [fontforge/fontforge.github.io](https://github.com/fontforge/fontforge.github.io)
cc @larsenwork
