### ISSUE TITLE
OS X build process fails if IPython is not installed

### ISSUE THREAD

**Issue by glyphobet** [fontforge/fontforge#2410]
The `patch` command on line 27 of `osx/create-osx-app-bundle.sh` fails if the MacPorts port `py27-ipython` isn't installed. 

https://github.com/fontforge/fontforge/blob/b3901fa241936c83f9dd9753d51e8c4ba5b2b1c7/osx/create-osx-app-bundle.sh#L27-28

I don't know what IPython is used for in FontForge. If it's absolutely required, then `py27-ipython` should be added to the requirements (or perhaps build requirements) in `osx/Portfile`. If it's optional, the command should check first for the existence of the IPython package before attempting to patch it.

**Comment by ctrlcctrlv** [comment]
It's not required. FontForge has very few hard requirements, but this was seemingly lost on the Apple packager...you don't even need Xorg ("XQuartz" on Apple I think) if you're just going to be using the scripting functionality, etc.

Looking at the patch itself:

https://github.com/fontforge/fontforge/blob/b3901fa241936c83f9dd9753d51e8c4ba5b2b1c7/osx/ipython-embed-fix.patch

I doubt this is best practice. It edits files outside of the fontforge root which might be relied on by other packages and would definitely confuse most package managers that rely on you not changing tracked files...

**Comment by glyphobet** [comment]
The patch doesn't touch anything outside the `FontForge.app` directory. The `-d $TEMPDIR/FontForge.app` argument to patch and the `+++ Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/site-packages/IPython/config/application.py` make sure of that.

**Comment by ctrlcctrlv** [comment]
Apple app containers have their own version of every dependency in the package?

Learn something new every day, especially why they tend to be so large :) Thanks!
