### ISSUE TITLE
FontForge won’t start on OS X Yosemite

### ISSUE THREAD

**Issue by lixiangliu** [fontforge/fontforge#2411]
I have XQuartz 2.7.7 installed on OS X v10.10.4, and tried to run FontForge 2015-04-30 on my computer. As far as I can get is a blank FontForge window opened. 

I have already tried to use “fc-cache -f -r -v”, but seems it does not help the situation at all.  

![2015-07-07 21 10 52](https://cloud.githubusercontent.com/assets/10280733/8550812/7a93b486-2505-11e5-8599-7b9029b991dd.png)

**Comment by lixiangliu** [comment]
Just created a new user account and try to launch FontForge with that, still the same old blank window. So I guess this problem is system-wide, could it be some poisoned-cache hanging around and preventing the FontForge to load properly?

**Comment by jtanx** [comment]
I seem to recall that this has been seen before but I can't find the relevant issue... @davelab6?

**Comment by lixiangliu** [comment]
Hi @jtanx,

https://github.com/fontforge/fontforge/issues/2213

You mean this one? 

<img width="682" alt="2015-07-10 14 03 29" src="https://cloud.githubusercontent.com/assets/10280733/8613016/76163b96-270c-11e5-964a-ed523d747c38.png">

So I ran this ```/Applications/FontForge.app/Contents/MacOS/FontForge --debug``` command on the terminal, here’s the result.

**Comment by jtanx** [comment]
Yep that would be it. If you type 'r'  (or 'run') and press enter into that lldb console it should start FontForge.

**Comment by lixiangliu** [comment]
(lldb) r
Process 11040 launched: '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64)
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 18:12 AEST  1-May-2015-ML-D.
 Based on source from git with hash: 05a30d48c86096e5cb61232a209d84c03be93906
no xdefs_filename!
TESTING: getPixmapDir:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps
TESTING: getShareDir:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge
TESTING: GResourceProgramDir:/Applications/FontForge.app/Contents/Resources/opt/local/bin
trying default theme:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/resources
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
zsys_interface length: 0
num_interfaces: 1
DEBUG POINT A REACHED...
getting network setup...
   port: 5670 
   addr: 192.168.1.255 
binding beacon...1. local addr:192.168.1.255 
binding beacon... 0x108320e28
binding beacon... port:5670 
binding beacon...2. local addr:0.0.0.0 
15-07-10 15:44:37 client beacon address: 0.0.0.0

setup_cocoa_app()

InitBreakpad(top)

2015-07-10 15:44:37.995 fontforge[11040:1620832] 0
0x7fff744898e0
2015-07-10 15:44:37.995 fontforge[11040:1620832] FontForge
0x10225a5a0
2015-07-10 15:44:37.995 fontforge[11040:1620832] English
0x7fff7448d8e0
2015-07-10 15:44:37.995 fontforge[11040:1620832] 20150501
0x10225cc00
2015-07-10 15:44:37.995 fontforge[11040:1620832] NSApplication
0x7fff7448fec0
2015-07-10 15:44:37.996 fontforge[11040:1620832] MainMenu
0x10225cc60
2015-07-10 15:44:37.996 fontforge[11040:1620832] (
        {
        CFBundleTypeExtensions =         (
            sfd,
            SFD
        );
        CFBundleTypeIconFile = "fontforge_sfd.icns";
        CFBundleTypeMIMETypes =         (
            "vnd.font-fontforge-sfd"
        );
        CFBundleTypeName = "Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            asfd,
            ASFD
        );
        CFBundleTypeIconFile = "fontforge_sfd.icns";
        CFBundleTypeMIMETypes =         (
            "vnd.font-fontforge-sfd"
        );
        CFBundleTypeName = "Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd~",
            "SFD~"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd-01",
            "SFD-01"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd-02",
            "SFD-02"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd-03",
            "SFD-03"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd-04",
            "SFD-04"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    },
        {
        CFBundleTypeExtensions =         (
            "sfd-05",
            "SFD-05"
        );
        CFBundleTypeIconFile = "fontforge_backup.icns";
        CFBundleTypeName = "Backup of Spline Font Database";
        CFBundleTypeRole = Editor;
        LSIsAppleDefaultForType = 1;
    }
)
0x10225aef0
2015-07-10 15:44:37.996 fontforge[11040:1620832] APPL
0x10225cb20
2015-07-10 15:44:37.996 fontforge[11040:1620832] FontForge.icns
0x10225a610
2015-07-10 15:44:37.996 fontforge[11040:1620832] http://fontforge.default.fontforge.uk0.bigv.io:3000/breakpad
0x10225a7f0
2015-07-10 15:44:37.996 fontforge[11040:1620832] Version 20150501
0x10225c6e0
2015-07-10 15:44:37.997 fontforge[11040:1620832] 6.0
0x7fff7448fba0
2015-07-10 15:44:37.997 fontforge[11040:1620832] FontForge
0x10225a5a0
2015-07-10 15:44:37.997 fontforge[11040:1620832] net.sourceforge.fontforge
0x10225ca40
2015-07-10 15:44:37.997 fontforge[11040:1620832] {
    FontForgeBuildTime = "18:12 AEST  1-May-2015";
    FontForgeGitHash = 05a30d48c86096e5cb61232a209d84c03be93906;
}
0x10225abf0
2015-07-10 15:44:37.997 fontforge[11040:1620832] ????
0x10225cb90
2015-07-10 15:44:37.997 fontforge[11040:1620832] public.app-category.graphics-design
0x10225c890
2015-07-10 15:44:37.997 fontforge[11040:1620832] The FontForge Developers
0x10225a720
2015-07-10 15:44:37.997 fontforge[11040:1620832] FontForge
0x10225a5a0
2015-07-10 15:44:37.997 fontforge[11040:1620832] FontForge version 20150501 based on sources from 18:12 AEST  1-May-2015 git:05a30d48c86096e5cb61232a209d84c03be93906
0x10225c770
2015-07-10 15:44:37.997 fontforge[11040:1620832] 05a30d48c86096e5cb61232a209d84c03be93906 - 18:12 AEST  1-May-2015
0x10225a940
xxx creating breakpad with plist:0x10253b590

This is what I got.

**Comment by davelab6** [comment]
I just installed FontForge today on a fresh new 10.10 laptop, using cask, and when I ran it the first time it said to move it to /Applications and opened the Finder in the directory where it was located, and so I moved it and it took about a minute scanning for fonts, and then it ran fine, and it started up nearly instantly after that. 

cc @frank-trampe @larsenwork

**Comment by larsenwork** [comment]
@davelab6 looks like @lixiangliu already has FF in applications folder. FWIW I'm also running XQuartz 2.7.7, OS X v10.10.4, FontForge 2015-04-30 without any major problems. @jtanx if this issue is duplicate then please reference that when adding the duplicate label :)

**Comment by jtanx** [comment]
@larsenwork, that issue has already been referenced [here](https://github.com/fontforge/fontforge/issues/2411#issuecomment-120239154)

**Comment by larsenwork** [comment]
@jtanx cheers, closing this to keep information in one issue.
