### ISSUE TITLE
How about some actual history of Fontforge?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#2413]
http://fontforge.github.io/en-US/project/

I mostly use the old documentation in `doc/html`. Please if you're going to continue with this "Web 2.0" craze at least keep the old option available as the author's documentation is nearly always more valuable and detailed than any substitute.

Anyway, I can't help but notice the current site makes no reference at all to the huge contributions of George Williams, PfaEdit, or any of the old history of FontForge at `doc/html/ff-history.html`, a page I really enjoyed reading (and which I have read numerous times).

>What on Earth Possessed me...

>I have always been interested in calligraphy, especially the eccentricities of the swash and black letter capitals.

>My father was deeply concerned with Renaissance printing, being a textual bibliographer of Shakespeare. His major focus was in the errors printers were likely to make, nevertheless I grew up in an environment where the long-s and other archaic devices appeared. My father used to brag that a great aunt of his still used the long-s in her hand-written notes.`

I feel like the current maintainers are appropriating this project without paying due respect to its history or author who gave it and us 460,000 SLOC for free. I have no idea how they even came to be maintainers, I asked on the `fontforge-users` SF list and was ignored. I see that fontforge.org now points to the github site, but someone other than George Williams owns that domain, so I can't even tell if you are continuing with permission.

It's not all bad. The Design with FontForge book is quite good for example. I however would really appreciate if we could please explain:

* how the new maintainers got this position;
* the great history behind FontForge's authorship;
* some of the eccentricities of the program to new developers. (Its reliance on xlib, gdraw, et cetera).

Perhaps this was just an oversight. I really hope it was. I'm sure I'm not alone in having used (sometimes just to convert a font, sometimes for a more difficult job) this program for years on GNU/Linux and then suddenly find new owners and no clue as to what happened.

Edit: Oh, and there's a reason that Ambrosia, Rotunda and related faces appear so much in the documentation, [they're works of FontForge's author that he made with the software](http://luc.devroye.org/fonts-25095.html). Are they typographic masterpieces? Not really, but they were actually made with FontForge. FF DIN was not. Let's try to showcase the work of our community on the official site instead of pretend DIN was made in FontForge because it "looks good". Inconsolata by Raph Levien was also made in FontForge.

**Comment by mskala** [comment]
Blame George for walking away without a succession plan in place.  However, one of the great things about open source is that the question of who ends up holding the "trademarks" doesn't even matter very much.  There are at least two other current projects maintaining code bases derived from PfaEdit; the fact that this one happens to be the one still labelled "FontForge" is basically an historical accident and doesn't mean anybody did anything nefarious.

**Comment by ctrlcctrlv** [comment]
And the other one is?

Also, to not even mention someone on the "About" page of their font editor speaks volumes more about you (if you did it) than about them.

**Comment by mskala** [comment]
The other two are FontAnvil, which I maintain myself, at http://tsukurimashou.osdn.jp/fontanvil.php.en , and SortsMill, maintained by Khaled Hosny and Barry Schwartz, at https://bitbucket.org/sortsmill/ .  You shouldn't expect to be welcomed in either of those places, nor anywhere else, if you bring the same spoiled-child attitude you'e showing here.

**Comment by ctrlcctrlv** [comment]
Thanks for Sorts Mill, it seems more actively developed. I'll try it.

Regarding my attitude, perhaps consider checking your own. I do not understand why you became so hostile when I asked how this state of affairs came to be, with all new maintainers and no mention of the previous one, so I can only guess that you feel guilty over something you did and don't want to tell anyone what it is, "Owner". 

I'm still very interested in what happened.

**Comment by JoesCat** [comment]
Hi Fredrick,
The current maintainers are people who have an interest in maintaining and improving FontForge. They will change with time as new people with energy and fire in the belly come along and start adding improvements while others that have been active taper-off with other things coming-up in their lives.

If you have the energy and interest to improve FontForge, then please start adding tiny patches that could probably be included. This is a group effort, and the more eyes interested in improving it, the better - for example, do you think you can write something answering this issue? If yes, give it a try.

**Comment by ctrlcctrlv** [comment]
@JoesCat working on it :) http://pfaedit.org/ff-history-redux.html (not done yet)

I created this issue to try to figure out what happened but didn't come up with too many answers, so I'll have to probably fill in the blanks with detective work. 

I will continue to maintain this site and the old documentation (thankfully it's old so it requires little effort to maintain, just don't type `rm` ;) )

**Comment by JoesCat** [comment]
On July 8, 2015 08:57:24 PM Fredrick Brennan wrote:
> I created this issue to try to figure out what happened but didn't come
> up with too many answers, so I'll have to probably fill in the blanks
> with detective work.

Patience and detective work required, Many here, are volunteers, and not 
everyone is up to date, up to speed, or often have focus on other targets.

**Comment by DomT4** [comment]
It's discussed in quite a bit of detail in [Conversations](http://conversations.tools/150211_PRINT.pdf), Page ~29 and ~162 in particular, George's direction for the project and Dave's involvement and such. It's an interesting read through.

**Comment by ctrlcctrlv** [comment]
@DomT4 Thank you very much. I will give that a read and add what I find to http://pfaedit.org/ff-history-redux.html .

**Comment by pathumego** [comment]
@ctrlcctrlv Please feel free to contribute here. https://github.com/fontforge/fontforge.github.io/issues/89 we are all here  because we love FontForge(Call it whatever you like :)

**Comment by pathumego** [comment]
@ctrlcctrlv this seems to explain a bit of history after George : https://en.wikipedia.org/wiki/FontForge. I think this should be moved to FontForge website repo. @ctrlcctrlv Can You kindly repost there?

**Comment by ctrlcctrlv** [comment]
@pathumego 

@larsenwork wrote "Keep it short" so I'll have to trim it down :wink: 

I'll do my best

**Comment by larsenwork** [comment]
@ctrlcctrlv Good! People don't like long reads and it's easier to update shorter text. Try making it 10 lines tops and then just link to the wiki where people can read more.

**Comment by pathumego** [comment]
Ok Im closing this since its posted fontforge/fontforge.github.io#89
