### ISSUE TITLE
error in reading commands

### ISSUE THREAD

**Issue by kosalaya** [fontforge/fontforge#2417]
when I open fontforge while sinhala keyboard is on, fontforge seem to read all the commands in sinhala  even if I switch the keyboard after. can't even do a little copy-past without relaunching software. can someone fix this?

**Comment by jtanx** [comment]
@kosalaya, I'm presuming you're running Windows? If so, how are you switching keyboard layouts? Does pressing `Ctrl+shift` or `Alt+shift` do anything? 

If those don't do anything, if you can edit `fontforge.bat` (Usually in `C:\Program Files (x86)\FontForgeBuilds\`), does changing

     start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error

to 

    start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error -xkboptions grp:ctrl_shift_toggle

do anything when you press `Ctrl+Shift`?

Finally, if that does not work, can you try this instead?

    start /B "" "%FF%\bin\VcXsrv\vcxsrv.exe" :%FF_XPORT% -multiwindow -clipboard -silent-dup-error  -xkblayout lk,us -xkboptions grp:ctrl_shift_toggle

I think `lk` should correspond to a Sinhala keyboard, but I don't know for sure. 

In any case, unfortunately switching keyboard layouts in FontForge will be independent of your 'Windows' option for your current keyboard layout.

**Comment by kosalaya** [comment]
well, this occurred in OS X. sorry I didn't mention. anyway, this might not be entirely a bug in fontforge. even after I relaunched the software I experienced the same problem. So this might have something to do with the X11 plugin.

**Comment by jtanx** [comment]
Ah. There should probably be similar settings for XQuartz, I presume.

**Comment by jtanx** [comment]
reopen if still an issue on the latest version
