### ISSUE TITLE
not run application in windows 8

### ISSUE THREAD

**Issue by dnbolt** [fontforge/fontforge#2419]
installing good
run instaled application no effect
please contact to me for full information

**Comment by jtanx** [comment]
Need more information... What happens when you try to run it? Any error messages? Screenshots?

**Comment by dnbolt** [comment]
No error meseges,
No process in task manager,
No logs in widows.
I can send you the logs, but the operating system, there are no error
messages, and logs the application I could not find, or can have the
opportunity to run in debug mode is the application?
I also can you make a video on the screen of my computer and play back the
entire procedure beginning with the installation to start attempt.
I can only do this after noon London time, it will be convenient?

Need more information... What happens when you try to run it? Any error
messages? Screenshots?

—
Reply to this email directly or view it on GitHub
<https://github.com/fontforge/fontforge/issues/2419#issuecomment-120554890>.

**Comment by jtanx** [comment]
When it installed, it should have added an option called 'FontForge interactive console' - if you could click on this shortcut, a CMD window will appear. If you type `fontforge` and press enter, you should see some text - can you show me what the output of that is? e.g.
![ffconsole](https://cloud.githubusercontent.com/assets/5137410/8632083/d06dfc66-27be-11e5-8db1-ce0b5810212e.png)

**Comment by dnbolt** [comment]
Ok
11 Июл 2015 г. 6:20 пользователь "Jeremy Tan" <notifications@github.com>
написал:

**Comment by dnbolt** [comment]
That's console output.

C:\Program Files (x86)\FontForgeBuilds>fontforge
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <
http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read
LICENSE.
 Based on sources from 08:25 AWST 13-Jun-2015-ML-TtfDb-D.
 Based on source from git with hash:
5134fe27846202c45cc0e1392705320e3b99a6fe
no xdefs_filename!
TESTING: getPixmapDir:C:/Program Files
(x86)/FontForgeBuilds/share/fontforge/pix
maps
TESTING: getShareDir:C:/Program Files (x86)/FontForgeBuilds/share/fontforge
TESTING: GResourceProgramDir:C:/Program Files (x86)/FontForgeBuilds/bin
trying default theme:C:/Program Files
(x86)/FontForgeBuilds/share/fontforge/pixm
aps/resources
ImportError: No module named site
XIO:  fatal IO error 10093 (Unknown error) on X server "127.0.0.1:11.0"
      after 390 requests (390 known processed) with 0 events remaining.
C:\Program Files (x86)\FontForgeBuilds>


You can provide remote access, if required.

On Sat, Jul 11, 2015 at 6:23 AM, Сергей Шварц <dnbolt@gmail.com> wrote:

> Ok
> 11 Июл 2015 г. 6:20 пользователь "Jeremy Tan" <notifications@github.com>
> написал:
>
>> When it installed, it should have added an option called 'FontForge
>> interactive console' - if you could click on this shortcut, a CMD window
>> will appear. If you type fontforge and press enter, you should see some
>> text - can you show me what the output of that is? e.g.
>> [image: ffconsole]
>> <https://cloud.githubusercontent.com/assets/5137410/8632083/d06dfc66-27be-11e5-8db1-ce0b5810212e.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120566188>
>> .
>>
>


-- 
+79119312232

**Comment by jtanx** [comment]
Interesting. Do you have a separate version of Python installed?

**Comment by jtanx** [comment]
Also, can you type

~~~~~
echo %PYTHONHOME%
echo %PYTHONPATH%
~~~~

into that console?What happens when you run

    ffpython

You should get something like:

~~~~~
Configuring the system path to add FontForge...
Configuration complete. You can now call 'fontforge' from the console.
You may also use the bundled Python distribution by calling `ffpython`.
Extra Python modules that you require may be installed via `ffpython`.

C:\Program Files (x86)\FontForgeBuilds>ffpython
Python 2.7.10 (default, Jun 26 2015, 11:11:16)
[GCC 4.9.2] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
~~~~~

(You can type `quit()` and press enter to quit)

**Comment by dnbolt** [comment]
Python 2.7.1 (r271:86832, Dec 11 2012, 02:45:46) [MSC v.1600 64 bit
(AMD64)] on
win32


On Sat, Jul 11, 2015 at 9:31 AM, Jeremy Tan <notifications@github.com>
wrote:

> Interesting. Do you have a separate version of Python installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120586871>
> .
>



-- 
+79119312232

**Comment by dnbolt** [comment]
C:\Users\Sergey>echo %PYTHONHOME%
C:\Program Files (x86)\CollabNet SVN\Python25\

C:\Users\Sergey>echo %PYTHONPATH%
%PYTHONPATH%

On Sat, Jul 11, 2015 at 9:38 AM, Сергей Шварц <dnbolt@gmail.com> wrote:

> Python 2.7.1 (r271:86832, Dec 11 2012, 02:45:46) [MSC v.1600 64 bit
> (AMD64)] on
> win32
>
>
> On Sat, Jul 11, 2015 at 9:31 AM, Jeremy Tan <notifications@github.com>
> wrote:
>
>> Interesting. Do you have a separate version of Python installed?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120586871>
>> .
>>
>
>
>
> --
> +79119312232
>



-- 
+79119312232

**Comment by dnbolt** [comment]
C:\Program Files (x86)\FontForgeBuilds>ffpython
ImportError: No module named site

On Sat, Jul 11, 2015 at 9:42 AM, Сергей Шварц <dnbolt@gmail.com> wrote:

> C:\Users\Sergey>echo %PYTHONHOME%
> C:\Program Files (x86)\CollabNet SVN\Python25\
>
> C:\Users\Sergey>echo %PYTHONPATH%
> %PYTHONPATH%
>
> On Sat, Jul 11, 2015 at 9:38 AM, Сергей Шварц <dnbolt@gmail.com> wrote:
>
>> Python 2.7.1 (r271:86832, Dec 11 2012, 02:45:46) [MSC v.1600 64 bit
>> (AMD64)] on
>> win32
>>
>>
>> On Sat, Jul 11, 2015 at 9:31 AM, Jeremy Tan <notifications@github.com>
>> wrote:
>>
>>> Interesting. Do you have a separate version of Python installed?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120586871>
>>> .
>>>
>>
>>
>>
>> --
>> +79119312232
>>
>
>
>
> --
> +79119312232
>



-- 
+79119312232

**Comment by jtanx** [comment]
> C:\Program Files (x86)\CollabNet SVN\Python25\

Okay that would be why. In `fontforge.bat` and `fontforge-console.bat`, try adding the following line (you can add it near the top but after the `set FF=` line):

     set PYTHONPATH=%FF%lib\python2.7

**Comment by jtanx** [comment]
If you would like an example, please [see here](https://github.com/jtanx/fontforgebuilds/blob/1e77d0daa1a7fb2322f6b2db947e1347e82f7ef1/ReleasePackage/fontforge.bat)

**Comment by dnbolt** [comment]
YEEE!
very very good!
thanks you!


On Sat, Jul 11, 2015 at 9:48 AM, Jeremy Tan <notifications@github.com>
wrote:

> C:\Program Files (x86)\CollabNet SVN\Python25\
>
> Okay that would be why. In fontforge.bat and fontforge-console.bat, try
> adding the following line (you can add it near the top but after the set
> FF= line):
>
>  set PYTHONPATH=%FF%lib\python2.7
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120587997>
> .
>



-- 
+79119312232

**Comment by dnbolt** [comment]
Add bug associated with the application translated into Russian. not
critical.
When selected when installing the Russian language, the lost code and can
not be read cirilic folder names.
When selected when installing the English language is all right.

On Sat, Jul 11, 2015 at 10:16 AM, Сергей Шварц <dnbolt@gmail.com> wrote:

> YEEE!
> very very good!
> thanks you!
>
>
> On Sat, Jul 11, 2015 at 9:48 AM, Jeremy Tan <notifications@github.com>
> wrote:
>
>> C:\Program Files (x86)\CollabNet SVN\Python25\
>>
>> Okay that would be why. In fontforge.bat and fontforge-console.bat, try
>> adding the following line (you can add it near the top but after the set
>> FF= line):
>>
>>  set PYTHONPATH=%FF%lib\python2.7
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fontforge/fontforge/issues/2419#issuecomment-120587997>
>> .
>>
>
>
>
> --
> +79119312232
>



-- 
+79119312232

**Comment by jtanx** [comment]
Glad you got it to work! Yes unfortunately FontForge does not cope well when installed to a non-English path (#2290)
