### ISSUE TITLE
sudden crash

### ISSUE THREAD

**Issue by kosalaya** [fontforge/fontforge#2422]
huge problem. fontforge crashes suddenly without indicating any particular reason. it's hard to figure out what command(s) trigger this but it's been happening very frequently. I tried installing few different builds hoping to get this solved but it didn't seem to work.

**Comment by pathumego** [comment]
@frank-trampe Can you help out to figure out whats wrong? @kosalaya is on OSX 10.3.

**Comment by pathumego** [comment]
After reinstalling x11 the problem was solved. I think there were some messed up pref files.
