### ISSUE TITLE
Font Generation: When overwriting UFO, save fails

### ISSUE THREAD

**Issue by enathu** [fontforge/fontforge#2424]
When generating the font (File> Generate Fonts), UFO generation works fine. But, let's say I made some changes in the font and want to generate the latest UFO by overwriting the previously generated UFO in the same path. Obviously, FF says the file already exists and asks whether to replace it or not.

![ff-replace](https://cloud.githubusercontent.com/assets/62147/8661662/0bcca700-29b1-11e5-84a3-84b504875a33.PNG)

When selecting the Replace option. FF shows a dialog box with 'Save Failed'

![ff-ufo-save-fail](https://cloud.githubusercontent.com/assets/62147/8661668/13cbd052-29b1-11e5-80fb-97fcd7f0d87c.PNG)

I have tried with other font formats, but others are working fine as intended. Only the UFO generation has this issue. 

I am using latest FF on Win 8.1 & I also tried with Win7 and FF having the same issue.

Is there any fix for this? 

Thank you.

**Comment by jtanx** [comment]
The offending line is [here](https://github.com/fontforge/fontforge/blob/master/fontforge/ufo.c#L1945) - it's a non-portable way to remove the folder given that `rm` doesn't exist on Windows.

**Comment by enathu** [comment]
@jtanx Thank you. :)

**Comment by jtanx** [comment]
@enathu if you want to test it, try installing [this version](https://github.com/fontforge/fontforge/releases/download/20150612/FontForgeSetup-23-07-2015-prerelease.exe)

**Comment by enathu** [comment]
@jtanx I've just tested it, and it works as intended. Thank you. :)
