### ISSUE TITLE
Disable auto-centering ?

### ISSUE THREAD

**Issue by HalfMadDad** [fontforge/fontforge#2430]
Hi Everyone

This is my first post. I am trying an experiment. Unicode has little images as fonts such as a telephone. However they are too small for some requirements. I am trying to split drawings into multiple terminal cells and piece them back together in a terminal to create a larger picture then what would be possible with one terminal cell so each font would only be part of a larger picture.

If I move the top left corner of the sliced picture into fontforge it autocenters it. I would like parts of pictures to be completely aligned with corners and not centered. Is there a way to set this up ?

Thanks for reading-Patrick

**Comment by larsenwork** [comment]
Just make sure the size of the slices = your upm/em size

**Comment by HalfMadDad** [comment]
Thanks Larsen :)

**Comment by larsenwork** [comment]
:+1:
