### ISSUE TITLE
One-time font search runs every time

### ISSUE THREAD

**Issue by cpcallen** [fontforge/fontforge#2432]
When I start FontForge, it brings up a dialog box which says "This setup is only run once..." - and that is true, in a sense: it runs once for each time that I start FontForge.  Needless to say this makes FF startup quite slow.

This is on OS X 10.6.8, FF "Version: 18:12 AEST 1-May-2015".  I am running XQuartz 2.3.6 (xorg-server 1.4.2-apple56).

**Comment by jtanx** [comment]
Related issues: #2316, #2151, #2055

**Comment by ultrasquid** [comment]
I can confirm this. Coincidentally I have very similar system specs.

On Fri, Jul 17, 2015 at 8:25 PM, Jeremy Tan <notifications@github.com>
wrote:

> Related issues: #2316 <https://github.com/fontforge/fontforge/issues/2316>,
> #2151 <https://github.com/fontforge/fontforge/issues/2151>, #2055
> <https://github.com/fontforge/fontforge/issues/2055>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2432#issuecomment-122478989>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by jtanx** [comment]
Just me noting something - but if Pango has been compiled with CoreText support (requires Cairo compiled with Quartz backend support), it can skip FontConfig totally, hence not needing to run fc-cache.

**Comment by frank-trampe** [comment]
We use cairo from MacPorts for the .app bundle. Do that Cairo and that Pango build with such options by default?

**Comment by jtanx** [comment]
No, the quartz backend stuff is disabled in MacPorts iirc. If you bundle the one from Homebrew (building them with the `--with-x11` option), it should have both the Quartz and X11 backends, allowing Pango to use CoreText.

**Comment by jtanx** [comment]
Actually, now I'm not so sure. I see mention of quartz + cairo/pango and macports on the net. Anyway, I'm *fairly* certain that whatever FontForge bundles, it doesn't have Core Text support.
