### ISSUE TITLE
How do I remove the red X over my new encoding slot?

### ISSUE THREAD

**Issue by luxe** [fontforge/fontforge#2434]
There is a font called [ProFont](http://tobiasjung.name/profont/).  
It's a small monospaced programming font that I only use at a particular font size.  
This font does not include any unicode characters, and so when there is unicode,
it's often rendered larger, and fuzzier.  
![unicode-now](https://cloud.githubusercontent.com/assets/1312081/8767455/895b88e8-2e2b-11e5-86a6-81e4408a8620.png)
It might not look fuzzy in that screenshot, because I have anti-alising turned off on my operating system.  Nonetheless, you can see that the Unicode characters are certainly not part of the same font family as the basic characters being rendered. The unicode characters are wider, bolder, and they increase the line height of whatever line they are on.  I assume that some kind of fallback font is being chosen to allow them to still display.

Anyway,  there were a few particular unicode characters that I wanted to add to ProFont so that they could be rendered in the small monospaced fashion as the rest of the basic characters.  For example,
I would like to make the unicode version of this `❲` look the same as `[`.  
i.e. I want characters `U+2772` and `U+005b` to look the same visually.  
(Yes, `[`, not `(`.  Although, I suppose the details here aren't really relevant to my question.)  
`U+005b` is already in ProFont since it's the basic `[` character.    
All I need to do, is extend ProFont so that it supports `U+2772` or `❲` as well.  

**Steps I took:**
loaded in font:  
![load](https://cloud.githubusercontent.com/assets/1312081/8767538/26b0f98c-2e2e-11e5-9c0a-31cdae06d9df.png)

*I guess I'll add a space next to the ÿ
![see-available-space](https://cloud.githubusercontent.com/assets/1312081/8767539/2c179962-2e2e-11e5-9e05-4e77235ed259.png)

So I choose `New Encoding Slot`  
![new-encoding-slot](https://cloud.githubusercontent.com/assets/1312081/8767542/4d922b3e-2e2e-11e5-8549-4a49a2bad38f.png)

![choose-1](https://cloud.githubusercontent.com/assets/1312081/8767545/5af8f5d2-2e2e-11e5-872b-23bde8926978.png)

I copy and paste in the character I want it to look exactly like:  
![copy-paste](https://cloud.githubusercontent.com/assets/1312081/8767552/78c2c836-2e2e-11e5-9caf-68f6dc8b7670.png)

I choose the unicode value that the slot will represent:  
![set-value](https://cloud.githubusercontent.com/assets/1312081/8767555/8585b272-2e2e-11e5-9406-a0423fdeaa5c.png)

Now, the problem, as I see it, is that I can't get rid of that red X.  
![still-x](https://cloud.githubusercontent.com/assets/1312081/8767584/038118d8-2e2f-11e5-9dfc-d42be4011758.png)

I've been trying to change encodings around, and change properties under glyph info, and flip random toggles that I don't understand to get that 'X' to go away.  If I ignore the red X and generate the font to a BDF, it can still be installed, but once it gets installed, its all broken, and doesn’t look like ProFont at all.  
If I load in that original .pcf file, and export it straight to `.bnf` without adding that encoding slot, it all works fine after being installed.  

Am I attempting to add additional character support correctly?

**Comment by luxe** [comment]
I had to pick Unicode as an encoding.  Scroll all the way down to that chatacter.  Do the steps I did above, and set the width.  The X goes away after I set the width.

**Comment by JohnDDuncanIII** [comment]
the `bdftopcf` command can convert your generated bdf back into a compressed pcf btw
