### ISSUE TITLE
Can't generate fonts

### ISSUE THREAD

**Issue by tkphelps** [fontforge/fontforge#2436]
I am a brand new user, just feeling things out. If I load a TTF font, make no changes, and then go to file|Generate Fonts, make a new file name in a working directory, click Generate. I get a dialog box "Save Failed". There is a file (much too small) with the new name, but it is "corrupted", Also, there is a new icon in the system tray, a black x on a gold o, apparently associated with system.XWinrc, whatever that is, and FontForge is frozen until I use Task manager to end the process on that error. I have version AWST 13-Jun-2015. I hope I just need a little instruction, but I didn't find any clues in the operating manual.

**Comment by jtanx** [comment]
Does this happen with all fonts? If not, can you provide a sample that causes this issue to happen?

Also, can you please try with [this version](https://github.com/fontforge/fontforge/releases/download/20150612/FontForgeSetup-23-07-2015-prerelease.exe)? Thanks!

**Comment by tkphelps** [comment]
I tried with Arial MT Rounded and with Courier, both, I think were part of the original windows installation. The result was exactly the same. I will try your new file.

Tkphelps

**Comment by tkphelps** [comment]
Tried the new version. Same result. “Save Failed” after a few seconds of “Saving Font” and a progress bar. I used the file cour.ttf from the Windows\Font directory, and simply tried to generate a new font. For reference, this is a Windows 7 Ultimate with SP1 and all the current updates. Would it be useful to know details of the machine? I am still suspecting an operator error, because lots of editing functions work.

TKPhelps

**Comment by tkphelps** [comment]
Problem solved. I found the “Run As Administrator” instruction. Thanks for your attention.

Keith

**Comment by jtanx** [comment]
Ah, I see - you were trying to save directly to `C:\Windows\Fonts`, and that would require elevated permissions.

**Comment by tkphelps** [comment]
Not quite. I was trying to save to a temp folder in My Documents. It still required the additional permission. (C:\Users\Keith\My Documents)&(Save Failed)
