### ISSUE TITLE
Deleting curves empties clipboard

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2442]
On Windows, have not tested other platforms.

1. copy a part of a glyph
2. open up another glyph in the editor, delete a part of it
3. try to paste what was copied, doesn’t work.

@jtanx: have you hit this situation already?

**Comment by enathu** [comment]
@adrientetar For me, it works fine as intended. I have tested on both Win 7 and 8.1.

**Comment by adrientetar** [comment]
It works for me as well, it seems there are other requirements to reproduce what I have experienced a couple of times already. Let me update after I try more.

**Comment by jtanx** [comment]
Strange. I haven't come across this before.
