### ISSUE TITLE
Interface language

### ISSUE THREAD

**Issue by Goveshka** [fontforge/fontforge#2443]
How to change interface language?
During installation, i choose english, but language is set like system default.

**Comment by jtanx** [comment]
I presume you're using Windows - that language choice is for the installer. To manually set the language for FontForge, you have to edit `C:\Program Files (x86)\FontForgeBuilds\fontforge.bat` - you will need administrator privileges to do this.

Change the line that says:

      ::set LANGUAGE=en

To 

       set LANGUAGE=en

Then save the file. Try launching FontForge again - it should now be in English.

**Comment by Gwenouille** [comment]
Oh… Didn't know that.
I used to open the folders with the locale infos and delete all folders that are not english :-)

**Comment by cybernaut4** [comment]
Are there any plans to change this from UI?

**Comment by ctrlcctrlv** [comment]
Nope. It'd be difficult to do that in a cross platform way. Users can reinstall and use the installer UI.

**Comment by JapanYoshi** [comment]
I looked at fontforge.bat, and it has the line `::set LANGUAGE-en`. Yet the application keeps booting in Japanese (Windows' system language).

**Comment by AntonioNoack** [comment]
That really should be an option in the UI... just save the file in a user-local folder like ~/.config/fontforge

**Comment by ctrlcctrlv** [comment]
Feel free to PR one :) I know of no current plans but that'd probably be accepted if you can make it work on Windows/macOS/Linux

**Comment by attikov** [comment]
are you kidding?
is determining the current language easier with multiplatform as giving a hint under the settings how to do it?
do I have to google and read github comments to achieve it?
there was not even a remarked set LANGUAGE in the bat file
+ extend the installer at least

**Comment by ygoe** [comment]
> Nope. It'd be difficult to do that in a cross platform way. Users can reinstall and use the installer UI.

Just for clarification, the installer UI language selection has absolutely no effect on the application UI language. The installer even correctly says so.

And the app help couldn't help me when I was looking for "language". So the only way to allow users to use a proper language that isn't wrong (like there would be any "encryption" in a font, at least the German UI suggested that) and that's maybe a little more widespread when seeking for support later is to do a web search, follow a few links and find instructions to manually edit files in system directories. The worst user experience you can have.

But then again, the whole UI is the worst user experience that exists, so it probably doesn't matter. Use something like Qt or .NET or maybe Python and you get much better UIs cross-platform. This one can't even properly be navigated with standard hotkeys.

**Comment by HaleyHalcyon** [comment]
I’m not a UI/UX expert but I think changing the language should not require admin privileges and editing a config text file manually.
