### ISSUE TITLE
On Fedora F17/F18, autoreconf and libtoolize fail

### ISSUE THREAD

**Issue by moyogo** [fontforge/fontforge#245]
[fontforge] $ ./autogen.sh
Preparing the fontforge build system...please wait

Found GNU Autoconf version 2.69
Found GNU Automake version 1.12.2
Found GNU Libtool version 2.4.2

Automatically preparing build ... Warning: autoreconf failed
Attempting to run the preparation steps individually

Preparing build ... ERROR: libtoolize failed

**Comment by skef** [comment]
We work with major downstream distros as we need to. FontForge installation is a moving target.
