### ISSUE TITLE
Cant add arguments for Autotrace

### ISSUE THREAD

**Issue by somename456** [fontforge/fontforge#2450]
using autotrace-0.31.1-w32.zip

works fine without arguments, but adding -corner-surround=4 (which is default value) in argument input does not yield any results

**Comment by jtanx** [comment]
Are you sure autotrace is being used? In `fontforge.bat` (C:\Program Files (x86)\FontForgeBuilds), there is a line that sets AUTOTRACE to be potrace (bundled with the distribution).

I just tried manually running autotrace with (the deault arguments FontForge uses):

      autotrace --output-format=eps --input-format=BMP --output-file output.eps input.bmp

and autotrace crashes...

**Comment by somename456** [comment]
Oh! I guess it wasn't using autotrace but rather potrace, I had autotrace in the path though, so i thought it prefered autotrace.
