### ISSUE TITLE
Update Python documentation for undefined math constants

### ISSUE THREAD

**Issue by fred-wang** [fontforge/fontforge#2454]
(cc'ing @khaledhosny)

The documentation for the Python interface mentions at several places "The special value of -32768 (0x8000)": https://github.com/fontforge/fontforge/blob/master/doc/html/python.html

Actually, these special values correspond to TEX_UNDEF which is 0x7fff, so the doc should be updated
https://github.com/fontforge/fontforge/blob/176a172222df093902e25ad4792fa3e2afa69825/fontforge/splinefont.h#L1534

(it may also be good to expose a python constant "TEX_UNDEF")

**Comment by JoesCat** [comment]
safe to close issue?

**Comment by fred-wang** [comment]
I think so.
