### ISSUE TITLE
"FontForge_latest-HEAD.app.dmg" (for OS X) no longer available?

### ISSUE THREAD

**Issue by KurtPfeifle** [fontforge/fontforge#2455]
The following website contains installation instructions for FontForge on Mac OS X:

* http://fontforge.github.io/en-US/downloads/mac/

As part of this website, it gives a link to development versions also, saying "*New development versions are released every few days, and the latest is always available as:

* http://fuuko.libferris.com/osx/packages/FontForge_latest-HEAD.app.dmg "

However this link is leading to a "***403 Forbidden***" error.

Please update the link, or remove that section from the web page in case these *latest-HEAD* builds are no longer available....

**Comment by davelab6** [comment]
Looks like @monkeyiq removed that symlink from http://fuuko.libferris.com/osx/packages/ - I've emailed him about this, hopefully he can restart the service soon :)

**Comment by gbuendia** [comment]
Hi, I don't know if this goes here or I should open a new issue.

The dmg is still unavailable. All of these yield a 404 error:
http://fuuko.libferris.com/osx/packages/FontForge_latest-HEAD.app.dmg
http://fuuko.libferris.com/osx/packages
http://fuuko.libferris.com/osx

http://fuuko.libferris.com leads to a page that apparently has nothing to do with software.
