### ISSUE TITLE
Keyboard layout, vs ASCII

### ISSUE THREAD

**Issue by Musicstave** [fontforge/fontforge#2460]
Hi,
Is there keyboard layout option to view the glyphs? Im working on a graphic type font and the ASCII layout is of no use, actually it's a hinderance. I continually have to export the font and put it into a word doc template keyboard I've made.
Im using Fontforge on Mac.

Many thanks

**Comment by pathumego** [comment]
Hi Your question is not clear, but gathering from what you already wrote.. Are you asking if you can see the glyphs on a keyboard layout?

**Comment by Musicstave** [comment]
Hi Pathum
Presently when using FF the Glyphs appear in chronological order. 
Therefore the letters of the alphabet appear in abc order. 
I am creating a graphical font that is not following this order. Therefor I need to work with a keyboard ordering of the glyphs. 
Hope this makes sense?
Regards
Terry
