### ISSUE TITLE
Pulldown menus can become detached from main menu (Windows)

### ISSUE THREAD

**Issue by elgonzo** [fontforge/fontforge#2461]
When opening a pull-down menu (for example the "File" menu) and then dragging the program window will detach the pull-down menu and leave it floating on the screen:
![menu_detach](https://cloud.githubusercontent.com/assets/6129198/9428320/db157cd6-49a9-11e5-926e-1b69969acc60.jpg)
Expected behavior would be that the pull-down menu is automatically being closed if the program window is being dragged.

Related to this issue is the undesired behavior of FontForge of not closing an open pull-down menu when another application window is being activated (by mouse-click or Alt+TAB).

OS: MS Windows 7 Pro x64
FontForge version: FontForge-mingw-w64-i686-99da6f-r2

**Comment by jtanx** [comment]
This is most likely not specific to Windows. Until the GUI is ever rewritten to use a standard toolkit, this is unlikely to be fixed.
