### ISSUE TITLE
Menus shown behind taskbar (Windows)

### ISSUE THREAD

**Issue by elgonzo** [fontforge/fontforge#2462]
If the FontForge window is placed at an unfortunate screen location, menus will open behind the taskbar, thus making the bottom menu entry/entries inaccessible until the FontForge window is being moved and the menu reopened:
![taskbar](https://cloud.githubusercontent.com/assets/6129198/9428345/30dde97c-49ab-11e5-825d-5e8ecc1317f4.jpg)
The pull-down menus should either always being displayed on top of the taskbar, or alternatively the space occupied by the taskbar needs to be taken into account when deciding whether pull-down menus should open downwards or upwards.

Related to issue #2256:
When deciding whether pull-down menus should open upwards or downwards, FontForge bases this decision incorrectly on the dimension of the virtual-screen bounding-box. This can lead to situations where a pull-down menu is being drawn off-screen:
![menu_cut](https://cloud.githubusercontent.com/assets/6129198/9428376/9db2b19e-49ac-11e5-9faa-93c37aaebe30.jpg)
The situation as displayed in this screenshot can for example occur with the following multi-monitor setup when FontForge is placed close to the bottom of monitor 1:
![mm](https://cloud.githubusercontent.com/assets/6129198/9428377/9db66104-49ac-11e5-977d-f12098130977.jpg)

OS: MS Windows 7 Pro x64
FontForge version: FontForge-mingw-w64-i686-99da6f-r2

**Comment by jtanx** [comment]
Similar to #2461, unlikely to be fixed any time soon.
