### ISSUE TITLE
Font Generation Fails Completely

### ISSUE THREAD

**Issue by enathu** [fontforge/fontforge#2465]
I have updated the FontForge with [latest build release for Windows](https://github.com/fontforge/fontforge/releases/download/20150824/FontForge-2015-08-24-Windows.exe), and with this new release when I trying to generate font (all formats - ttf, otf and other) it shows the message box "Save Failed" -

![save-failed](https://cloud.githubusercontent.com/assets/62147/9505252/fcee32c8-4c5e-11e5-9da0-e5c58b30cf96.PNG)

Once I click 'OK' on the "Save Failed" message and cancel the Font Generation dialog box, it shows this error in a message box. 

![error-1](https://cloud.githubusercontent.com/assets/62147/9505289/3451eaa2-4c5f-11e5-9487-ee8363f9aafd.PNG)

I've also, tried with different and brand new source files to get generate the font, and got the same error with subtle number changes in the message box.

![error-2](https://cloud.githubusercontent.com/assets/62147/9505349/75eebf30-4c5f-11e5-90ff-bdc7246dd242.PNG)

I have inspected the destination folder, where I tried to generate the font, I've noticed that FontForge created a file with the font extension each time I was trying to generate a font, but all the files are in the size of 1KB - and when I try to open the file, it shows "The requested file fontfile.ttf is not a valid font file." as an error message. 

The latest build completely fails in generating font.

Any fix for this? I look forward to hearing from you. Thank you.

**Comment by jtanx** [comment]
I can reproduce this. Strangely, it seems that the call to `tmpfile` is failing with `Permission denied` at `tottf.c:1490`. 

I've just tried it with a standalone C file and I can reproduce this issue. I think it may be because I upgraded to mingw-w64/gcc 5.2.0. 

The current workaround is to run FontForge as administrator.

**Comment by jtanx** [comment]
It's strange - if I debug older builds of FontForge, the tmpfile call succeeds, yet from all that I can see, calls to tmpfile should fail for non-administrators, since it tries to create files in the root (C:\) directory...

**Comment by jtanx** [comment]
@enathu, I've updated the release (same filename), so please try re-downloading and installing. Thanks!

**Comment by enathu** [comment]
@jtanx I have installed the updated new release file, and now it works fine. Thank you very much.

**Comment by Bildcode** [comment]
@jtanx  I've had the same issue. thanks for taking care.

**Comment by jtanx** [comment]
@Bildcode can you confirm that you are using the latest version available? Could you provide a sample font file? Thanks

**Comment by Bildcode** [comment]
I meant, I've had the issue but it's fine now - using version "09:10 AWST 27-Aug-2015".
Not sure if this version is in the official stable release section though.
I've got it from "latest builds" here: https://sourceforge.net/projects/fontforgebuilds/files/latest/download

**Comment by jtanx** [comment]
Oh, okay that makes sense; thanks for clarifying. I thought you meant that you were still experiencing this issue.
