### ISSUE TITLE
August 2015 release fails to launch on Mac OSX 10.6.8

### ISSUE THREAD

**Issue by ultrasquid** [fontforge/fontforge#2470]
Attempting to launch via the recommended terminal command, FontForge fails to launch and reports the following error:

$ 'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
ImportError: No module named SimpleHTTPServer

**Comment by RebeccaRGB** [comment]
I am having this same problem. Is there any resolution?

**Comment by ultrasquid** [comment]
@monkeyiq's build from
http://fuuko.libferris.com/osx/packages/201509/17_0419/ works, but it is
unclear if the resources are fully up to date with what's in this repository

On Mon, Sep 28, 2015 at 10:19 PM, Rebecca G. Bettencourt <
notifications@github.com> wrote:

> I am having this same problem. Is there any resolution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2470#issuecomment-143947679>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by RebeccaRGB** [comment]
That worked for me, thank you!

**Comment by jtanx** [comment]
#2530
