### ISSUE TITLE
Would you know of a professional to kern the table of Minion Display Regular for me?

### ISSUE THREAD

**Issue by CatherineGroves** [fontforge/fontforge#2478]
I run a small not-for-profit interfaith periodical (available in hardcopy form only) devoted to goodwill dialog. I do all the layout of the periodical myself. But I'm a stickler on how type appears, because I believe strongly that the ease of read for the reader depends upon factors they will never actually notice: i.e., kerning, proper line-spacing, etc. If body copy is to be appealing, it needs to adhere to those factors that make reading easy and smooth.

So I manually kern and I spend inordinate hours doing so. I have used Minion Display Regular for the body copy for many years now and I know that font better than the back of my hand. I know that in the version I have (and who knows what kerning table lies beneath that), an e should be adjusted by +1 point, except where a space follows at which time it should be adjusted by -1 point; and if an e precedes an a it needs +2 points; or if it precedes a space followed by an o it needs to be adjusted -3 points. In other words, I know the font. 

Simply, I can no longer devote the time to manual kerning. The only solution I can think of is to have the kerning table for the version of Minion Regular Display I use adjusted to my needs. I downloaded and tried to acquaint myself with fontforge, but I believe it's simply over my head. While I would need to keep this within a budget, I am willing to pay someone who is really good and reputable.

**Comment by weiweihuanghuang** [comment]
Perhaps you can look at http://www.kahrel.plus.com/indesign/kern.html ?

**Comment by hpapazian** [comment]
Wow, you're picky. Like me.  :-)
I've carried out modifications to professional fonts over many years for numerous clients. As you probably realize, kerning is arduous work (at least to do a good job). What is your budget?

**Comment by davelab6** [comment]
> BTW I believe it's against Adobe's EULA to modify the fonts

Actually Adobe's standard EULA allows modificiation of fonts, but the modified copy counts as one of the number of copies you are allowed.

> 14.7.6 If the font software you wish to modify is identified as “licensed for modification” on Adobe's website at : http://www.adobe.com/type/browser/legal/additional_licenses.html, you may also modify the font software provided that such modified software is used only for your own customary internal business or personal use and may not be distributed or transferred for any purpose, except in accordance with Section 4.4. of this agreement. The fonts listed on the website as non-modifiable may be converted in accordance with Section 14.7.4 above but may not be otherwise modified in any way. 

That page linked in the quote lists Minion as allowing modification.

**Comment by davelab6** [comment]
@CatherineGroves feel free to email me dave@lab6.com if you'd like a competitive quote

**Comment by frankrolf** [comment]
FWIW, Minion Display is not intended for use at text sizes. 
The spacing of the font is optimized for Display use (i.e. quite large).
For more information, see the Adobe Type Primer here (page 8):
http://wwwimages.adobe.com/content/dam/Adobe/en/products/type/pdfs/adobe-type-primer.pdf

**Comment by adrientetar** [comment]
Some like money, others like typography.

**Comment by CatherineGroves** [comment]
Thank you, all of you, for your advice, caveats and info. I am exploring and assimilating all of your comments. I had begun to despair of anyone who actually knew what a kerning table is! To suddenly meet with people who do understand what I'm talking about is such a relief. And please do keep your comments coming, if you have anything to add. I am actively pursuing it all. Again, thank you.
