### ISSUE TITLE
App (v Fontforge-20150824) crashes on launch OSX 10.10.4

### ISSUE THREAD

**Issue by Binarytales** [fontforge/fontforge#2479]
Here is the crash report in the Console.app

```
Process:               fontforge [1938]
Path:                  /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
Identifier:            fontforge
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           fontforge [1938]
User ID:               501

Date/Time:             2015-09-03 14:48:29.977 +0100
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        DF1F364A-5E50-E7EC-85B6-55A8A7846DE3

Sleep/Wake UUID:       55C90BB0-42B5-4DB9-9DB8-AD013A4470E5

Time Awake Since Boot: 920000 seconds
Time Since Wake:       16000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found

Binary Images:
    0x7fff6d769000 -     0x7fff6d79f837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld
    0x7fff95f42000 -     0x7fff95f42fff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff98c7f000 -     0x7fff98c7ffff  com.apple.CoreServices (62 - 62) <C69DA8A7-B536-34BF-A93F-1C170E2C6D58> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

 ```

and there is another produced at the same time

```

Process:               fc-cache [1934]
Path:                  /Applications/FontForge.app/Contents/MacOS/fc/fc-cache
Identifier:            fc-cache
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        perl5.18 [1933]
Responsible:           sh [1922]
User ID:               501

Date/Time:             2015-09-03 14:48:29.920 +0100
OS Version:            Mac OS X 10.10.4 (14E46)
Report Version:        11
Anonymous UUID:        DF1F364A-5E50-E7EC-85B6-55A8A7846DE3

Sleep/Wake UUID:       55C90BB0-42B5-4DB9-9DB8-AD013A4470E5

Time Awake Since Boot: 920000 seconds
Time Since Wake:       16000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libfontconfig.1.dylib
  Referenced from: /Applications/FontForge.app/Contents/MacOS/fc/fc-cache
  Reason: image not found

Binary Images:
    0x7fff6aa9a000 -     0x7fff6aad0837  dyld (353.2.1) <72A99D0F-0B56-3938-ABC5-67A0F33757C4> /usr/lib/dyld

 ```

**Comment by daveoconnor** [comment]
I think I'm geting something related when I try to run fontforge from the terminal after getting no UI when running it by using the icon.

➜  MacOS  ./FontForge --debug
PKGBASE: /Applications/FontForge.app
/usr/bin/lldb
have set up python stuff... PYTHONHOME: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7
have set up python stuff... PYTHON:     /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.*/bin/python
Script started, output file is /Users/doc/FontForge-Debug-Output.txt
No entry for terminal type "xterm-256color";
using dumb terminal settings.
(lldb) command source -s 0 '/Applications/FontForge.app/Contents/MacOS/debug-script'
Executing commands in '/Applications/FontForge.app/Contents/MacOS/debug-script'.
(lldb) version
lldb-320.4.160
(lldb) script print sys.version
2.7.5 (default, Mar  9 2014, 22:15:05)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
(lldb) settings set frame-format "frame #${frame.index}: ${frame.pc}{ ${module.file.basename}`${function.name-with-args}{${function.pc-offset}}}{ at ${line.file.basename}:${line.number}}\n"
(lldb) target create /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
Current executable set to '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64).
(lldb) target select 0
Current targets:
* target #0: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge ( arch=x86_64-apple-macosx, platform=host )
(lldb) #run -SkipPythonInitFiles
(lldb) # please type the run command to start FontForge
(lldb) #
(lldb) # run
(lldb) #
(lldb) run
Process 21545 launched: '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64)
dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
Process 21545 stopped
* thread #1: tid = 0x52356, 0x00007fff5fc0109d dyld`dyld_fatal_error + 1, stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
    frame #0: 0x00007fff5fc0109d dyld`dyld_fatal_error + 1
dyld`dyld_fatal_error + 1:
-> 0x7fff5fc0109d:  nop

dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*):
   0x7fff5fc0109e:  pushq  %rbp
   0x7fff5fc0109f:  movq   %rsp, %rbp
   0x7fff5fc010a2:  pushq  %r15

**Comment by erikronstrom** [comment]
I'm having the same problem

**Comment by jtanx** [comment]
#2530
