### ISSUE TITLE
Can not copy glyphs between two fonts 

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2482]
Can not copy glyphs between two files in GNU Build. Is there a way to enable this?

**Comment by pathumego** [comment]
@frank-trampe do you know what is the problem here :(

**Comment by skef** [comment]
The usual "can't copy" problem is that the copy function only works reliably if you open both fonts from the same running fontforge. So, for example, opening one file however you like and then opening the second file with "File -> Open". When opened that way, copying between fonts generally works.
