### ISSUE TITLE
Specify rotation origin when Python scripting

### ISSUE THREAD

**Issue by AndydeCleyre** [fontforge/fontforge#2489]
Hi,

I'm using a FontForge Python script to create new glyphs at specific locations if they don't exist, in the form of rotated existing glyphs. When I do this via the UI, I can specify whether the origin for this rotation will be "Glyph Origin" or "Center of Selection," but I don't know how to make this choice when scripting, where it seems to default to "Glyph Origin."

How can I script glyph rotations with "Center of Selection" as the origin?

Here is what I'm currently doing:

``` python
#!/usr/bin/fontforge -script

import fontforge
from psMat import rotate
from math import radians

from plumbum.cli import Application, SwitchAttr
from plumbum import local


DEK = 'uni218A'
EL = 'uni218B'

class Dozenalizer(Application):

    out_dir = SwitchAttr(['out'], default='./dozenalized_fonts', help='Output directory for generated fonts')

    def main(self, *font_files):
        for font_file in font_files:
            font = fontforge.open(font_file)
            if DEK not in font or EL not in font:
                for source, dest in {'two': DEK, 'three': EL}.items():
                    if dest not in font:
                        font.selection.select(source); font.copy()
                        font.selection.select(dest); font.paste()
                        font.transform(rotate(radians(180)))
                font.generate(str(local.path(self.out_dir) / local.path(font_file).basename))


if __name__ == '__main__':
    Dozenalizer.run()
```

**Comment by skef** [comment]
Everything needed is available via the `transform` interface. What you need to keep in mind is:

1. Rotation is geometrically origin-relative (that is, it is around (0,0))
2. You can put whatever point of the glyph you would like at the origin using `translate`.
3. Matrix transformations are composable. 

Together that makes this one bit of script that will rotate an individual glyph `g`:
```
    bb = g.boundingBox()
    cx = (bb[2] + bb[0]) / 2
    cy = (bb[3] + bb[1]) / 2
    trcen = psMat.translate(-cx, -cy)
    rotcen = psMat.compose(trcen, psMat.compose(psMat.rotate(radians(180)), psMat.inverse(trcen)))
    g.transform(rotcen)
```

Because each glyph has its own origin, to do this to all currently selected glyphs you would need to iterate over the selection like this:

```
for g in ff.selection.byGlyphs:
    bb = g.boundingBox()
    cx = (bb[2] + bb[0]) / 2
    cy = (bb[3] + bb[1]) / 2
    trcen = psMat.translate(-cx, -cy)
    rotcen = psMat.compose(trcen, psMat.compose(psMat.rotate(radians(180)), psMat.inverse(trcen)))
    g.transform(rotcen)
```

**Comment by skef** [comment]
A custom "by center of glyph" option could be added to the python interfaces, but

1. There could be tricky interactions with transform matrices, and
2. The "transform matrix philosophy" is the longstanding general solution to all of these issues, and it would be better to write a good document (including the above) than to add epicycles onto it. 

(Past users have also gone looking for a reverse interface, not aware that reflection is equivalent to negative scaling.)

Anyway, I keep a latent eye on the issue feed and try to clarify these things when they come up, so I'm closing this one.

**Comment by SpragUeInSanity** [comment]
Playing with rotation of fonts for a round watch face and found this post about how to use FontForge to rotate and have rotation correction.  Awesome stuff.  I was struggling trying to get my rotated fonts aligned using scripting.    Thanks skef!
