### ISSUE TITLE
Importing a bold TTF font does not set OS2->Style Map properly

### ISSUE THREAD

**Issue by jeberger** [fontforge/fontforge#2498]
# Steps to reproduce

- Import a bold TTF font (tried it with Hack and DejaVu Sans)
- Go to Element->Font Info->OS/2 and check the value of Style Map

# Expected result

The style map should be "Automatic" or "Bold".

# Actual result

The style map is "None".

# Version information

- FontForge version 09:10 AWST 27-Aug-2015 on Windows 7
- FontForge version 10:43 UTC 25-Jun-2015 on Arch Linux

# Extra information

A similar problem occurs with Bold Italic fonts (their style map is set to "Italic" instead of "Bold Italic"). However Italic fonts are handled properly.

This causes issues when importing and re-exporting a font directly without modifications: the newly exported font is not always recognized as bold. In particular, Qt5 will consider that the font is not bold and will apply its fake bold algorithm, resulting in an excessively heavy font.

**Comment by jtanx** [comment]
I wonder if this is related to #2493.

**Comment by jtanx** [comment]
If you want to test the latest version on Windows, see [here](http://sourceforge.net/projects/fontforgebuilds/files/i686/Portable/FontForge-mingw-w64-i686-b31ff0-r3.7z/download) (portable build only).

**Comment by jeberger** [comment]
@jtanx I've tested the version you've linked and the style map is set to bold as it should.

**Comment by jtanx** [comment]
Thanks for testing!
