### ISSUE TITLE
bootstrap fails with libtoolize: unrecognized option `--quiet'

### ISSUE THREAD

**Issue by acli** [fontforge/fontforge#2503]
I’m not sure how the bootstrap script is checking version numbers right now, but it needs to check for a minimum version number that is later than 1.5.x.

bash-4.2$ ./bootstrap 
bootstrap: running: libtoolize --quiet
libtoolize: unrecognized option `--quiet'
Try `libtoolize --help' for more information.
bash-4.2$ libtoolize --version
libtoolize (GNU libtool) 1.5.26

Copyright (C) 2005 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by lpsandaruwan** [comment]
Installing libltdl-dev package fix this?

**Comment by lpsandaruwan** [comment]
Installing libltdl-dev package fix this?
