### ISSUE TITLE
Closing paths/contours in Python

### ISSUE THREAD

**Issue by shermp** [fontforge/fontforge#2504]
I'm creating a python script to add a small amount of weight to a font (among other tasks). The automated tool occasionally has an issue where it leaves open paths in a few glyphs. In the GUI, this is easy enough to solve by using the automatic fix in the validation menu.

However, I cannot seem to find a similar method to perform this fix in python? Is there such a method available that isn't documented, or that I simply couldn't find?

Or do I have to go into each layer, iterate over the contours, and close them that way? If I have to do that, would someone be able to provide a simple snippet to point me in the right direction?

Thank you

**Comment by shermp** [comment]
So I've got it working by iterating through the contours and closing them. The problem I had before with this was I was not assigning my modified layer object back to the activelayer in the glyph.

Still though, if anybody knows of an easier method of doing this, I would love to know!

**Comment by skef** [comment]
When you `validate()` the font via the python interface the state will indicate whether any glyphs have open contours (bit `0x2`). You can then go through the cached `validation_state` of the individual glyphs to look for the individual glyphs, and then the contours of that glyph.

That's probably as integrated with the validation system as the python interface is likely to be for the time being.
