### ISSUE TITLE
I follow the install guide but I still can't install Fontforge

### ISSUE THREAD

**Issue by mixj93** [fontforge/fontforge#2507]
I move fontforge.app to /Applications. but when I click "open" button nothing happened!

![fontforge](https://cloud.githubusercontent.com/assets/12998118/10166864/9b993a9a-66f8-11e5-9773-4eeee5449f9a.gif)

Thank you so much for helping me.

**Comment by mrelwood** [comment]
I have the same issue. Repairing permissions and rebooting didn't help.

**Comment by JRRN** [comment]
Same issue.

**Comment by mrelwood** [comment]
Hint from another thread worked for me! The version from April does work on OSX Yosemite.

**Comment by sfcgeorge** [comment]
Yep same problem but on OS X 10.11 El Capitan.

**Comment by Jolg42** [comment]
:+1:

**Comment by mixj93** [comment]
The version from April does work on OSX Yosemite and El Capitan

**Comment by jtanx** [comment]
#2530
