### ISSUE TITLE
on windows when saving changes lookup subtitle giving this error "warning: Invalid parameter passed to C runtime function."

### ISSUE THREAD

**Issue by zoghal** [fontforge/fontforge#2514]
hi
on windows when saving changes lookup subtitle giving this error "warning: Invalid parameter passed to C runtime function."

version :
```
 Based on sources from 09:10 AWST 27-Aug-2015-ML-TtfDb-D.
 Based on source from git with hash: 3d950d3cde977900e5138019a918ed671efb4449
```

demo:
https://www.dropbox.com/s/efctxireiuu3h6d/fontforge-bug.gif?dl=0

warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\fontforge.debug
[New Thread 6768.0x1134]
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libfontforgeexe-2.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libgdraw-5.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libgutils-2.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libgunicode-4.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libuninameslist-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libcairo-2.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libX11-xcb-1.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libX11-6.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libxcb-1.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libXau-6.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libxcb-render-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libpango-1.0-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libpangocairo-1.0-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libpangoft2-1.0-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libpangowin32-1.0-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libpangoxft-1.0-0.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libXft-2.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libXrender-1.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libfontforge-2.debug
warning: section .gnu_debuglink not found in F:\FontForgeBuilds\bin\.debug\libspiro-0.debug
warning: Python failed to load the default activation context

[New Thread 6768.0x1200]
[New Thread 6768.0x1a28]
[New Thread 6768.0x17bc]
warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.
.
.
.
.
.
.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

[Thread 6768.0x1a28 exited with code 0]
[Thread 6768.0x17bc exited with code 0]
[Inferior 1 (process 6768) exited normally]
F:\FontForgeBuilds\\ffdebugscript.txt:2: Error in sourced command file:
No stack.

````

**Comment by jtanx** [comment]
You're running it under GDB - that message is normal when running under GDB. It isn't crashing (no segfault, no stack trace) which is good.

**Comment by zoghal** [comment]
ok :), thanks
