### ISSUE TITLE
Virus found in fontforge?

### ISSUE THREAD

**Issue by meowoo** [fontforge/fontforge#2519]
My anti-virus software found    Malware.Gen  in fontforge. Is that an wrong warning?

**Comment by ultrasquid** [comment]
Your antivrus is probably issuing an unrecognized vendor error or something
of that nature, but it should be looked into. Where did your copy of
FontForge come from? Was it a release from this repository? Which platform
is it for?

On Mon, Oct 12, 2015 at 12:11 AM, meowoo <notifications@github.com> wrote:

> My anti-virus software found Malware.Gen in fontforge. Is that an wrong
> warning?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2519>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by meowoo** [comment]
Hi, I download the copy from  http://fontforge.github.io/en-US/downloads/.  Windows platform

**Comment by ultrasquid** [comment]
Do you get the same result with the version available here:
https://github.com/fontforge/fontforge/releases/tag/20150824 ?

On Mon, Oct 12, 2015 at 1:05 AM, meowoo <notifications@github.com> wrote:

> Hi, I download the copy from http://fontforge.github.io/en-US/downloads/.
> Windows platform
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2519#issuecomment-147323767>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by meowoo** [comment]
sure,I download again from the /releases and get the same result.

**Comment by jtanx** [comment]
It's a false positive detection. What antivirus are you using?

**Comment by fitojb** [comment]
Please report this issue to your antivirus vendor.

**Comment by cicku** [comment]
Please contact the antivirus provider and report this false positive.
