### ISSUE TITLE
Improve OS X Integration

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#252]
In https://github.com/fontforge/fontforge/issues/203#issuecomment-12450498 @monkeyiq said, "[I can] expand that to also attach a Delegate to the NSApplication so that FontForge can ask for attention and other mac like special behavior."

This issue should be updated with a more complete list of things to do. 
- [ ] Ask for attention when not in the foreground

**Comment by skef** [comment]
We have Mac OS suggestions sprinkled throughout the issue database. Closing this meta-issue.
