### ISSUE TITLE
Fontforge-generated TrueType font not valid and cannot be installed

### ISSUE THREAD

**Issue by OrgoinArsalang** [fontforge/fontforge#2525]
Hello, when I generated .ttf font designed with Fontforge and choosen to install it, in some moment I received system message that font is not valid and cannot be installed (screenshot in Russian). 
![default](https://cloud.githubusercontent.com/assets/15111039/10462666/8d9404fc-71e8-11e5-824f-a64da1d41194.png)

Curious peculiarity is: if I rename generated .ttf file to anything different from projectname, it becomes valid and installable

OS is 32 bit Windows 7, FontForge is 8/27/2015 version. 

Font files uploaded to "Yandex disk" cloud:
.sfd file: https://yadi.sk/d/wqKf9b9_jiJKV
"Invalid" .ttf file: https://yadi.sk/d/diDt5rGnjiJJN

Thanks in advance.

**Comment by OrgoinArsalang** [comment]
Also, generating .ttf with different name set in pop-up dialog produces the same impact than renaming

**Comment by JoesCat** [comment]
I downloaded the sfd file, then tried to generate ttf and fontforge displayed these errors:
Open Contour
Self Intersecting
Wrong direction
Missing points at Extrema
Non integral coordinates

You need to fix these first.

**Comment by skef** [comment]
Closed due to inactivity.
