### ISSUE TITLE
Native Scripts stopped working after update from 20120731.b-5 to 20151013

### ISSUE THREAD

**Issue by tobltobs** [fontforge/fontforge#2527]
I have recently updated my fontforge install from the debian package version (20120731.b-5) to20151013 from git.
Now my native fontforge script (pe) stopped working. Stopped working means that fontforge does not raise an error but the resulting font is unchanged.

An example for a script:
```
    Open($argv[$argc-1])
    SelectAll()
    Shadow(angle,outlinewidth,shadowwidth)
    Save()
    Quit(0)
```
I could port those pe scripts to python but I can not find an equivalent of the shadow function in the python api.

**Comment by JoesCat** [comment]
Would you mind trying the version from 20151001?
I added a rather large edit on Oct 2nd (which shouldn't change anything from your perspective) and this narrows down if it is something I changed accidentily?
https://github.com/fontforge/fontforge/tree/52a869492c7c91fff84a4a0a21e743078ad2712d

Do you have an example font I should try?
email me if it needs to remain private.
I'll try your script tonight.

**Comment by tobltobs** [comment]
It seems this problem has more to do with my setup than fontforge itself. The problem only occurs if I call the script via pythons subprocess.open. It works if I call it direct. I did test this before, but somehow got it wrong. Sorry for confusion.
Saving the font to a non .sdf eg. .ttf does also work.
