### ISSUE TITLE
fontforge does not start

### ISSUE THREAD

**Issue by meisterleise** [fontforge/fontforge#2534]
I've just installed the newest versions of fontforge (20150829) an Xquartz 2.7.7 under OS X 10.10.2. I've done every little detail like explained in the description. But if I start fontforge absolutly nothing hanppens.

**Comment by pixelkrieg** [comment]
Try the fontforge head. It worked for us: https://github.com/fontforge/fontforge/issues/2530#issuecomment-148997584

**Comment by meisterleise** [comment]
Thank you! Yes this one works! :)

**Comment by JoesCat** [comment]
Thanks @pixelkrieg !
