### ISSUE TITLE
I Need generate TTC font but...

### ISSUE THREAD

**Issue by marcussacana** [fontforge/fontforge#2537]
My FontForge crash, i need make a TTC of a Unicode TTF collections, it's very important, can add support? i only view paid tools...

**Comment by jtanx** [comment]
What OS are you using? Which version of FontForge? What is the crash (screenshot/text dump)? What are the steps to make it crash? Can you provide the TTF fonts you are using?

**Comment by marcussacana** [comment]
hmmm sorry, i'm using a previous version, i update, don't crash to remake the TTC, but view this...
i can't view the japanese font chars 
![[http://i.imgur.com/E33DlJG.png]http://i.imgur.com/E33DlJG.png]

**Comment by marcussacana** [comment]
my log show
![http://i.imgur.com/NnBCS6O.png](http://i.imgur.com/NnBCS6O.png)

**Comment by marcussacana** [comment]
my font:
http://www6.zippyshare.com/v/5hlZSOO0/file.html

**Comment by jtanx** [comment]
Can you please outline the steps you are taking to make the TTC?

**Comment by marcussacana** [comment]
after i update remake without problem, but here
im only open the ttc font, select Meiryo after open again and select the Meiryo UI
after open, the japaneses chars don't show '-', i change the encoding to try view, but he remove 90% of chars from char entries list '-'

**Comment by jtanx** [comment]
If you change encoding you will likely remove characters. 

I don't quite understand "*japaneses chars don't show '-'*" - are you saying the font is missing a character? What is the unicode value of this character? e.g. U+002D? Can you give a screenshot of this?

**Comment by marcussacana** [comment]
![http://i.imgur.com/W5sG6QD.png](http://i.imgur.com/W5sG6QD.png)
if i save without encode, the FontForge show a warning message

**Comment by marcussacana** [comment]
hi, hmmm now is in other font
[[http://i.imgur.com/E9duAcw.png](http://i.imgur.com/E9duAcw.png)](http://i.imgur.com/E9duAcw.png)

win log:

Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome do Aplicativo:	fontforge.exe
  Versão do Aplicativo:	0.0.0.0
  Carimbo de Data/Hora do Aplicativo:	503119a3
  Nome do Módulo de Falhas:	libfontforge-1.dll
  Versão do Módulo de Falhas:	0.0.0.0
  Carimbo de Data/Hora do Módulo de Falhas:	503119a5
  Código de Exceção:	c0000005
  Deslocamento de Exceção:	00253ef6
  Versão do sistema operacional:	6.1.7601.2.1.0.256.1
  Identificação da Localidade:	1046
  Informações Adicionais 1:	0a9e
  Informações Adicionais 2:	0a9e372d3b4ad19135b953a78882e789
  Informações Adicionais 3:	0a9e
  Informações Adicionais 4:	0a9e372d3b4ad19135b953a78882e789

Leia nossa declaração de privacidade online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0416

Se a declaração de privacidade online não estiver disponível, leia nossa declaração de privacidade offline:
  C:\Windows\system32\pt-BR\erofflps.txt

**Comment by marcussacana** [comment]
... i open this font: http://www10.zippyshare.com/v/TDsrlLqm/file.html
and select the ms gothic
after i copy this chars
original = new
ﾃ = ã
ﾉ = é
ﾇ = ç

after this i open the anothers fonts in this ttc... and generate the TTC font again... after this, crash...

**Comment by jtanx** [comment]
That last screenshot looks like an older version of FontForge. Does it crash in latest version?

**Comment by marcussacana** [comment]
He don't crash in the last version (i test the older and lastest)
but the fon't generate missing chars or corrupted, i don't know, but the windows don't read more the font and have a icon change after save...
![[http://i.prntscr.com/69f215d4fc4b45d9a04518c7159b112e.png](http://i.prntscr.com/69f215d4fc4b45d9a04518c7159b112e.png)](http://i.prntscr.com/69f215d4fc4b45d9a04518c7159b112e.png)

**Comment by marcussacana** [comment]
Allways show this icon the game (i editing for a game read allowing translation of this game) don't read the MSGothic more, and change for another random font...

**Comment by marcussacana** [comment]
a gif using the FontForge
![[http://i.imgur.com/8FZglDE.gifv](http://i.imgur.com/8FZglDE.gifv)](http://i.imgur.com/8FZglDE.gifv)

**Comment by jtanx** [comment]
Just a suggestion but maybe try save the fonts individually as TTFs then use something like [UniteTTC](http://yozvox.web.fc2.com/556E697465545443.html) (I recall someone else on the issue tracker using this) to combine them into a TTC again.

**Comment by marcussacana** [comment]
now i only a way to edit this japanese ttf ^^
man, only for this thanks, i searching a way to remake a ttc for months... thanks

**Comment by marcussacana** [comment]
Hi, this TTC generator works ^^ thanks man...
Man, you know a way to only copy and replace a letter in the same font?
I need copy this letters: á é í ó ú ã Ã Á É Í Ó Ú ê ô Ê Ô ç Ç è à ò ù
and overwrite the half width katakana table...
i only need this, but allways try edit the ttf of the msgothic he 8mb size expand to 12mb and change the font preview icon in the explorer, after i install the game don't read the msgothic and select another font...
I try manual edit the game, but it's hard..
the best option it's a way to edit msgothic with minimum changes possible
