### ISSUE TITLE
FontForge doesn't read EBDT format 1 correctly

### ISSUE THREAD

**Issue by roytam1** [fontforge/fontforge#2543]
Some old fonts that come with EBDT format 1 bitmaps, and FontForge doesn't correctly read them.

**Comment by jtanx** [comment]
Have you got any samples?

**Comment by roytam1** [comment]
7z archive uploaded.
http://s000.tinyupload.com/index.php?file_id=32064115514411929991

**Comment by roytam1** [comment]
7z archive uploaded.
http://s000.tinyupload.com/index.php?file_id=32064115514411929991

**Comment by frank-trampe** [comment]
@roytam1, it's unlikely that we'll get to this anytime soon. Do you have some other means by which to convert these typefaces, or is this a blocking issue for you?

**Comment by roytam1** [comment]
low priority to me, I just let you know this issue. ;)
But I don't have a way to convert EBDT format 1 to newer EBDT format or BDF by the way.

**Comment by jtanx** [comment]
@roytam1, I've submitted a PR that I think fixes the issue (#2865). Thanks for reporting!

**Comment by roytam1** [comment]
> If you use Windows, you can find a test build here: https://ci.appveyor.com/project/fontforge/fontforge/build/1.0.180/artifacts
Thanks. Bitmaps are working now.
But for this build, Does TrueType bytecode interpreter disabled? When I opening mingli-b225.ttf, the outline strokes are not in correct position.

**Comment by jtanx** [comment]
The build should be more or less equivalent to the normal builds, with the exception that loading files with non-ascii/current locale characters probably doesn't work.

I'm not entirely sure what the bytecode interpretor has to do with the positioning of the strokes - sorry I'm not very familiar with that part. But I don't think they're related? I thought the bytecode interpreter was only use for hinting debugging.

**Comment by lemzwerg** [comment]
There are 'tricky' fonts (this is how FreeType calls them) like the very old `mingli.ttf` from 1992 (*not* `mingliu.ttc`, BTW) that need the bytecode interpreter to correctly position and scale subglyphs.  AFAIK, FontForge has never supported this (and GWW was aware of that).

Note that even today Apple calls the bytecode interpreter on MacOS to handle tricky fonts: in the `head` table, `unitsPerEm` must be 1024 and the `lowestRecPPEM` field larger than 18 to trigger CoreText's bytecode interpreter; the hints are then processed at 1024ppem.
