### ISSUE TITLE
Some self-intersecting stroked SVG paths become broken on import

### ISSUE THREAD

**Issue by wareya** [fontforge/fontforge#2547]
Some self-intersecting SVG paths don't import properly. Depending on the particular shape of the stroke (and minor changes seem to make a difference) it can break apart in the general area where it self-intersects. It happens both with near-perpendicular and near-parallel selfoverlaps, and with some in between. It doesn't seem to matter whether the self-overlap is "clockwise" or "counter-clockwise".

This doesn't seem to be inherent to SplineSetStroke, because I cannot for the life of me manage to cause such behavior with the "Expand Stroke..." function in the GUI. Perhaps buggy parameters are being set somewhere.

(By the way, the generated outline's directions are all backwards. Using the "Expand Stroke..." function in the GUI gives the right direction. Maybe this is relevant?)

The following SVG data exhibits this bug:

```
<svg width="109" height="109" viewBox="0 0 109 109">
    <g style="fill:none;stroke:#000000;stroke-width:3;">
        <path d="M 20.328983,83.78678 C 150.51815,19.632996 -50.48081,26.082124 86.805084,86.093221"/>
    </g>
</svg>
```

It doesn't seem to matter whether I do it via python or via GUI's "import".

My copy of fontforge is "Based on sources from 23:20 UTC 28-Sep-2015-ML-D."

**Comment by skef** [comment]
As of my testing this evening this is fixed in the `stroke` branch.
