### ISSUE TITLE
Python scripting randomly crashes or produces gibberish on Mac OS 10.10.4

### ISSUE THREAD

**Issue by valexodamium** [fontforge/fontforge#2552]
I've been trying to run this script (using the Execute script... menu thing) with [this](https://www.dropbox.com/s/usc2pu0k8bdxtfb/ithk1broken.sfd?dl=0) font; it's supposed to add a modification to the first 26 characters and add them 52 characters ahead, to produce [this](https://www.dropbox.com/s/3ly580vtd7zjb2n/ithk1.sfd?dl=0) result. If I try to run it though, it crashes; if I modify the range so it runs on an individual character or a range of fewer than all 26 characters it will either work correctly, produce gibberish, or crash, apparently randomly.

```
import fontforge

j = 39;
while j < 39+26:
  g=fontforge.activeFont().createMappedChar(j);
  for c in g.layers[fontforge.activeLayer()]:
    i=0;
    while i< len(c):
      if (c[i%len(c)].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i%len(c)].x == 144 and c[(i+2)%len(c)].x<c[(i+1)%len(c)].x):
        c.insertPoint((c[i].x+72 ,c[i].y-72 ,True),i);
        c.insertPoint((c[i].x+172,c[i].y-28 ,True),i+2);
        c.insertPoint((c[i].x+172,c[i].y-173,True),i+3);
        c.insertPoint((c[i].x+71 ,c[i].y-73 ,True),i+4);
        c[i+2] = fontforge.point(c[i].x+72,c[i].y+72,True);
        i = len(c)
      elif (c[i%len(c)].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i%len(c)].x == 144 and c[(i+2)%len(c)].x>c[(i+1)%len(c)].x):
        c.insertPoint((c[i].x+72 ,c[i].y-72     ,True),i);
        c.insertPoint((c[i+2].x-172,c[i].y-28   ,True),i-1);
        c.insertPoint((c[i+3].x-172,c[i+1].y-173,True),i-1);
        c.insertPoint((c[i+4].x-71 ,c[i+2].y-73 ,True),i-1);
        c[i+3] = fontforge.point(c[i+3].x+72,c[i+3].y+72,True);
        i = len(c)
      elif (c[i].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i].x == 111 and c[(i+2)%len(c)].x<c[(i+1)%len(c)].x):
        c.insertPoint((c[i].x+90 ,c[i].y-45 ,True),i);
        c.insertPoint((c[i].x+190,c[i].y+15 ,True),i+2);
        c.insertPoint((c[i].x+190,c[i].y-96,True),i+3);
        c.insertPoint((c[i].x+89 ,c[i].y-46 ,True),i+4);
        c[i+2] = fontforge.point(c[i+1].x,c[i+1].y+111,True);
        i=len(c)
      elif (c[i].y == 650 and c[(i+1)%len(c)].y == 550 and c[(i+1)%len(c)].x-c[i].x == 100):
        c.insertPoint((c[i+1].x    ,c[i+1].y+144,True),i+1);
        c.insertPoint((c[i+1].x+100,c[i+1].y+44 ,True),i+2);
        c.insertPoint((c[i+1].x+100,c[i+1].y-101,True),i+3);
        c.insertPoint((c[i+1].x    ,c[i+1].y-1  ,True),i+4);
        i = len(c)
      i = i+1;
  newglyph = fontforge.activeFont().createMappedChar(j+26*2);
  newglyph.layers[1] += c;
  newglyph.left_side_bearing=25;
  newglyph.right_side_bearing=25;
  j = j+1;
```

Also, [here](https://www.dropbox.com/s/d0fe7ybavw5n43x/fontforge_2015-10-30-212610_Nidaba.crash?dl=0) is a crash report. Apparently it's a segmentation fault.

**Comment by JoesCat** [comment]
A lot of code in FontForge assumes things are good, but there is much code that falls down if there are problems. I'm currently going through some re-write of the native script part of the program, but I know the python part is also suffering in this area too.

Code run through the GUI is treated a little differently than code run at the command line, and I also run into a seg fault in 32-bit linux if I run your code through the GUI.

Can you go to a command line and rerun your code?
On the command line, there is a bit more code checks (not done at the GUI level).

At the command line, try your code again:
fontforge -lang=py -script modify.py ithk1broken.sfd

(where in my example, modify.py is your script).
If you do this, you will note your code promptly stops at line 5.
 g=fontforge.activeFont().createMappedChar(j);

This indicates that the script you wrote may need more work.
Please fix your script as best you can, then we'll try this issue again.

If you need help, please ask on the user mailing list (if you can), since there are more eyeballs watching the mailing list, and likely able to help you quicker.

**Comment by valexodamium** [comment]
Well, it's unsurprising that it would stop there, seeing as (according to the documentation) `activeFont()` only works if you execute the script from the menu...

the script will at least run on command line if you add `fontforge.open("ithk1broken.sfd");` at the beginning and `fontforge.activeFont().save("result.sfd");` at the end but has the same problems as described above, although now what I see is that it randomly either 
* crashes with the message `Command terminated`
* crashes complaining that `TypeError: In cubic splines there must be exactly 2 control points between on curve points` (note: the documentation states that this should probably be `exactly 0 or exactly 2` and neither the code nor the fonts themselves involve any control points at all so this souldn't be a problem)
* runs, but produces garbage
* works as intended

**Comment by JoesCat** [comment]
Looking at Native font, running it at the command line makes fontforge do an exit() when it hits ScriptError() which isn't done in GUI mode. I seem to consistently hit Seg fault when I get to character 43.
one newglyph 43
next 43 <Glyph plus in font Untitled1>
Segmentation fault

When I use Valgrind, it does the whole run.
 valgrind fontforge -lang=py -script modify2.py ithk1broken2.sfd

Using modified python file:
```c
import fontforge

fontforge.open("ithk1broken.sfd");

j = 39;
while j < 39+26:
  g=fontforge.activeFont().createMappedChar(j);
  print 'next', j, g;
  for c in g.layers[fontforge.activeLayer()]:
    i=0;
    print 'x';
    while i< len(c):
      if (c[i%len(c)].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i%len(c)].x == 144 and c[(i+2)%len(c)].x<c[(i+1)%len(c)].x):
        print '<#1';
        c.insertPoint((c[i].x+72 ,c[i].y-72 ,True),i);
        c.insertPoint((c[i].x+172,c[i].y-28 ,True),i+2);
        c.insertPoint((c[i].x+172,c[i].y-173,True),i+3);
        c.insertPoint((c[i].x+71 ,c[i].y-73 ,True),i+4);
        c[i+2] = fontforge.point(c[i].x+72,c[i].y+72,True);
        i = len(c)
        print '#1>';
      elif (c[i%len(c)].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i%len(c)].x == 144 and c[(i+2)%len(c)].x>c[(i+1)%len(c)].x):
        print '<#2';
        c.insertPoint((c[i].x+72 ,c[i].y-72     ,True),i);
        c.insertPoint((c[i+2].x-172,c[i].y-28   ,True),i-1);
        c.insertPoint((c[i+3].x-172,c[i+1].y-173,True),i-1);
        c.insertPoint((c[i+4].x-71 ,c[i+2].y-73 ,True),i-1);
        c[i+3] = fontforge.point(c[i+3].x+72,c[i+3].y+72,True);
        i = len(c)
        print '#2>';
      elif (c[i].y == 600 and c[(i+1)%len(c)].y == 600 and c[(i+1)%len(c)].x-c[i].x == 111 and c[(i+2)%len(c)].x<c[(i+1)%len(c)].x):
        print '<#3';
        c.insertPoint((c[i].x+90 ,c[i].y-45 ,True),i);
        c.insertPoint((c[i].x+190,c[i].y+15 ,True),i+2);
        c.insertPoint((c[i].x+190,c[i].y-96,True),i+3);
        c.insertPoint((c[i].x+89 ,c[i].y-46 ,True),i+4);
        c[i+2] = fontforge.point(c[i+1].x,c[i+1].y+111,True);
        i=len(c)
        print '#3>';
      elif (c[i].y == 650 and c[(i+1)%len(c)].y == 550 and c[(i+1)%len(c)].x-c[i].x == 100):
        print '<#4';
        c.insertPoint((c[i+1].x    ,c[i+1].y+144,True),i+1);
        c.insertPoint((c[i+1].x+100,c[i+1].y+44 ,True),i+2);
        c.insertPoint((c[i+1].x+100,c[i+1].y-101,True),i+3);
        c.insertPoint((c[i+1].x    ,c[i+1].y-1  ,True),i+4);
        i = len(c)
        print '#4>';
      print c, len(c), j, i;
      i = i+1;
  print 'doing newglyph';
  newglyph = fontforge.activeFont().createMappedChar(j+26*2);
  newglyph.layers[1] += c;
  newglyph.left_side_bearing=25;
  newglyph.right_side_bearing=25;
  j = j+1;
  print 'done newglyph', j;

fontforge.activeFont().save("result_issue2552.sfd");
```

Seems there is a pointer being used as a value or visa-versa.

**Comment by JoesCat** [comment]
Since I seemed to repeatedly crash at 43, I changed the code to:
```c
while j < 39+4:
```
and looking at the results, I noted that character 93 and 94 do not look as expected, char 93 is no longer a closed font.

**Comment by JoesCat** [comment]
....behaving okay again while running under valgrind....  this bug needs more thought...

**Comment by jtanx** [comment]
Perhaps if we get a plain English description of what the script is trying to do it might make it easier to see if there's any issue with the script itself...

**Comment by valexodamium** [comment]
As I said before, it's supposed to add a modification to the first 26 characters and add the resulting characters to the font 52 characters ahead, to produce the result I linked above as the "this" in the phrase "to produce this result".

it was part of a project to create a LaTeX typesetting package for ithkuil.

I'm not sure what I can add beyond that.

**Comment by JoesCat** [comment]
Hi @jtanx,
It might help to temporarily add in python.c (approx line 2460):
```c
return( NULL );
	    }
	}
    }
+printf("InsertPoint x=%f y=%f on=%d pos=%d <\n", x,y,on,pos);

    if ( pos<0 || pos>=self->pt_cnt-1 )
	pos = self->pt_cnt-1;
    if ( self->pt_cnt >= self->pt_max ) {
```
...and run a modified version of @valexodamium script (like the 2nd example above with lots of print statements). I suspect it may be a string variable not being initialized to '\0', but then again, could be something else.

**Comment by skef** [comment]
This doesn't crash anymore, and does update the lowercase characters when it runs. The fix was probably part of the early-mid 2019 python work.
