### ISSUE TITLE
curl: (56) SSLRead() return error -9806 Error: Failed to download resource "fontforge"

### ISSUE THREAD

**Issue by tonyorlando** [fontforge/fontforge#2554]
After search the internet, and trying my best I could not find a solution to completing the fontforge download on my terminal. Thank you in advance for your help.

Tony

Tonys-MBP:~ tonyorlando$ brew install fontforge --with-x
==> Installing dependencies for fontforge: libtool, gettext, libffi, glib
==> Installing fontforge dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.yosemite.bott
######################################################################## 100.0%
==> Pouring libtool-2.4.6.yosemite.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing fontforge dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.6.yosemite.bot
######################################################################## 100.0%
==> Pouring gettext-0.19.6.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.6: 1921 files, 22M
==> Installing fontforge dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.yosemite.bott
######################################################################## 100.0%
==> Pouring libffi-3.0.13.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 14 files, 412K
==> Installing fontforge dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.46.1.yosemite.bottle
######################################################################## 100.0%
==> Pouring glib-2.46.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.46.1: 416 files, 19M
==> Installing fontforge dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.18.yosemite.bott
######################################################################## 100.0%
==> Pouring libpng-1.6.18.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.18: 17 files, 1.2M
==> Installing fontforge dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.6_1.yosemite.bot
######################################################################## 100.0%
==> Pouring freetype-2.6_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.6_1: 60 files, 2.6M
==> Installing fontforge dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.yosemite.
######################################################################## 100.0%
==> Pouring fontconfig-2.11.1.yosemite.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1: 448 files, 3.6M
==> Installing fontforge dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.32.8.yosemite.bott
######################################################################## 100.0%
==> Pouring pixman-0.32.8.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pixman/0.32.8: 11 files, 1.2M
==> Installing fontforge dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.2_1.yosemite.bot
######################################################################## 100.0%
==> Pouring cairo-1.14.2_1.yosemite.bottle.3.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.2_1: 111 files, 6.1M
==> Installing fontforge dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.yosemite.bo
######################################################################## 100.0%
==> Pouring pkg-config-0.29.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29: 10 files, 648K
==> Installing fontforge dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.46.
######################################################################## 100.0%
==> Pouring gobject-introspection-1.46.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.46.0: 198 files, 10M
==> Installing fontforge dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-55.1.yosemite.bottle.
######################################################################## 100.0%
==> Pouring icu4c-55.1.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/55.1: 244 files, 66M
==> Installing fontforge dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.0.4.yosemite.bot
######################################################################## 100.0%
==> Pouring harfbuzz-1.0.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.0.4: 94 files, 3.6M
==> Installing fontforge dependency: pango
==> Downloading https://homebrew.bintray.com/bottles/pango-1.38.1.yosemite.bottl
######################################################################## 100.0%
==> Pouring pango-1.38.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.38.1: 117 files, 4.6M
==> Installing fontforge dependency: zeromq
==> Downloading https://homebrew.bintray.com/bottles/zeromq-4.1.3.yosemite.bottl
######################################################################## 100.0%
==> Pouring zeromq-4.1.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/zeromq/4.1.3: 63 files, 3.3M
==> Installing fontforge dependency: libsodium
==> Downloading https://homebrew.bintray.com/bottles/libsodium-1.0.5.yosemite.bo
######################################################################## 100.0%
==> Pouring libsodium-1.0.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libsodium/1.0.5: 63 files, 1.2M
==> Installing fontforge dependency: czmq
==> Downloading https://homebrew.bintray.com/bottles/czmq-3.0.2_1.yosemite.bottl
######################################################################## 100.0%
==> Pouring czmq-3.0.2_1.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/czmq/3.0.2_1: 53 files, 1.6M
==> Installing fontforge dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.yosemite.bottle.2.t
######################################################################## 100.0%
==> Pouring jpeg-8d.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 776K
==> Installing fontforge dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.6.yosemite.bott
######################################################################## 100.0%
==> Pouring libtiff-4.0.6.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.6: 259 files, 3.9M
==> Installing fontforge
==> Downloading https://homebrew.bintray.com/bottles/fontforge-20150824.yosemite
########################################################                  78.2%
curl: (56) SSLRead() return error -36
Error: Failed to download resource "fontforge"
Download failed: https://homebrew.bintray.com/bottles/fontforge-20150824.yosemite.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for fontforge: autoconf, automake
==> Installing fontforge dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.yosemite.bott
######################################################################## 100.0%
==> Pouring autoconf-2.69.yosemite.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
/usr/local/share/emacs/site-lisp/

Add the following to your init file to have packages installed by
Homebrew added to your load-path:
(let ((default-directory "/usr/local/share/emacs/site-lisp/"))
  (normal-top-level-add-subdirs-to-load-path))
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.1M
==> Installing fontforge dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.yosemite.bott
######################################################################## 100.0%
==> Pouring automake-1.15.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
==> Downloading https://github.com/fontforge/fontforge/archive/20150824.tar.gz
==> Downloading from https://codeload.github.com/fontforge/fontforge/tar.gz/2015
######################################################################## 100.0%
curl: (56) SSLRead() return error -9806
Error: Failed to download resource "fontforge"
Download failed: https://codeload.github.com/fontforge/fontforge/tar.gz/20150824
Tonys-MBP:~ tonyorlando$

**Comment by jtanx** [comment]
This sounds like a temporary error with the download. If you still have the issue, please re-open.
