### ISSUE TITLE
Installation Bug (Nov 3, 2015)

### ISSUE THREAD

**Issue by notsirk** [fontforge/fontforge#2555]
Installed FontForge today.

One bug occured when using the installation file from:
FontForge 2015-08-24 (in the dropdown 'Short Guide)

Running OS X 10.10.5, all the instructions were good until I had to run the application.

Downloaded application.
Placed in Application folder.
Double-clicked App, had to verify.
Then would shut down.

Replaced the app with another installation from 'Other Sources or Versions'

FontForge_latest-HEAD.app.zip (Daily Dev)

This worked.

**Comment by lordton** [comment]
Same here. Tried two machines.

**Comment by uxperts** [comment]
Same here as well, El Capitan 10.11.2 Beta (15C47a)

**Comment by jtanx** [comment]
#2569
