### ISSUE TITLE
Hi! Need help with kerning...

### ISSUE THREAD

**Issue by PoppyP** [fontforge/fontforge#2558]
Hi there!
I need to alter a font I own; I need to increase the kerning within the font, rather than in the software each time we use the typeface.
I have installed FontForge and have increased the Bearings of each letter, however I can't now save it. 
Help!!

**Comment by jtanx** [comment]
Have you tried `File->Generate Fonts`?

**Comment by PoppyP** [comment]
Hi @jtanx - I did that but when I try to upload the font to my server it says it's corrupted.
Thanks!

**Comment by jtanx** [comment]
Hi @PoppyP, without knowing what the font is or why the server is rejecting the font, it's very hard to know what is causing the issue. Are you able to provide a sample?

**Comment by skef** [comment]
Closed due to inactivity.
