### ISSUE TITLE
How to set up my own composite glyph combinations

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2562]
Can I set up my own composite glyphs? So I can use `Build>Composite Glyphs` with the glyphs I want to build? 

<img width="532" alt="screen shot 2015-11-06 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/6846609/10996408/83b80446-847c-11e5-8d88-be7527dac516.png">

**Comment by mskala** [comment]
No, you can't.

See issue #2570 for some description of the multiple data sources that go into the "Build Composite Glyphs" command.  It starts with character decompositions from Unicode but then those are overridden with extra hardcoded rules in at least three places (makeutype.c, SFGetAlternate in fvcomposite.c, and SCBuildComposite in fvcomposite.c).  Although I agree it would be nice if these mappings were controllable by the user at run-time, that is not the case right now and it doesn't look like an easy thing to implement.  Even changing the built-in decompositions at compile time would not be easy; you could try editing Unicode's database, re-running makeutype.c, and recompiling FontForge, but depending on what you want to do it may be quite difficult to predict how such changes would interact with the hardcoded overrides.

My suggestion would be that you write a script to do whatever customized glyph composition you want by cutting and pasting, without using the "build composite glyphs" command at all.

**Comment by ctrlcctrlv** [comment]
This is now possible, and will be in the next release. It's been in `master` since April :-)

![2019-07-23-131312_1306x945_scrot](https://user-images.githubusercontent.com/838783/61684284-80689200-ad4b-11e9-8a11-d1f9895b3ad5.png)
