### ISSUE TITLE
Alphanumeric ligatures

### ISSUE THREAD

**Issue by hirokiosame** [fontforge/fontforge#2563]
I'm using fontforge to create a font with ligatures, some using numbers in them. I can get ligatures with purely letters to work fine, however, when I use numbers, it throws an error.

This is the code I have so far:

```
import fontforge

font = fontforge.font()

font.encoding = 'UnicodeFull'
font.version = '1.0'
font.weight = 'Regular'
font.fontname = 'icon'
font.familyname = 'icon'
font.fullname = 'icon'
font.em = 1008
font.ascent = 864
font.descent = 144


# Set up ligatures
font.addLookup('liga', 'gsub_ligature', (), (('liga', (('latn', ('dflt')), )), ))
font.addLookupSubtable('liga', 'liga')


def createEmptyChar(font, char):
    glyph = font.createChar(ord(char)).glyphPen()
    glyph.moveTo((0, 0))
    glyph = None


# Empty all characters to remove gibberish...
for code in range(0, 256):
    createEmptyChar(font, chr(code))


# Name of ligature
name = str('commentsmultiple')

icon = font.createChar(-1, name)

icon.addPosSub("liga", tuple(name))

icon.importOutlines('fonts/icon/svg/e601_commentsmultiple128.svg')


font.generate('fonts/icon/icon.woff')
font.close()
```

However, when I change the string 'commentsmultiple' to 'commentsmultiple128', it throws an error:
```Lookup subtable contains unused glyph 1 making the whole subtable invalid```
where '1' is the first number in the string. This error is thrown when I invoke addPosSub()

How can I add numbers to ligatures?

**Comment by mastef** [comment]
@hirokiosame how did you fix this?
