### ISSUE TITLE
How can I put fontforge on my linux web hosting server and run scripts with it??

### ISSUE THREAD

**Issue by nycionx** [fontforge/fontforge#2565]
I need to place fontforge on my linux web hosting server and only run scripts using it (command-line tool no gui necessary!). How can i install it on my server? or which files am i supposed to copy to my server to make it run? I have had no success at all so far.. i have tried to copy the contents of fontforge-20120731b-12.el7.i686.rpm which basically has usr>bin,lib, and share folders, with the fontforge executable in bin. i tried running a script like:
<?php
exec("./usr/bin/fontforge -script print.sh test.ttf &> log.txt");
print.sh simply prints some jibberish text just to see if fontforge will work
but i get the following error:

./usr/bin/fontforge: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

so then i found this file on my linux machine under /usr/lib/x86_64-linux-gnu and made the same directory on my server and copied the file but i STILL get the same error message again! why??

what am i doing wrong and how can i successfully run fontforge off my server? i just need the command line tool version not gui and no python scripting needed.

am i supposed to somehow specially build fontforge on my system so that all the necessary files (libraries,etc) are contained under one folder like a standalone app and then transfer that folder to my server? that would be ideal i think but i dont know how to do this and im a newb to building also. Please help it is very important for me and is greatly appreciated! Thanks in advance!

**Comment by mskala** [comment]
FontAnvil is designed for this kind of application.  It's still a fairly complicated package and not trivial to compile, but it at least has fewer dependencies.  No GUI, no Python, and so no need to have the libraries associated with those things at compile or run time.  See http://tsukurimashou.osdn.jp/ .  The version 0.3 source tarball on that page should work pretty well.  The very latest version is available by checking it out here on github ( https://github.com/mskala/Tsukurimashou ) but compiling from a checked-out repository is a fair bit more complicated than using the tarball.

**Comment by mskala** [comment]
On your more immediate problem:  it's probably a bad idea to name your FontForge script *.sh.  That extension is normally only used for shell scripts.  It's probably a good idea to specify the option "-lang=ff" when running a native script; I'm not sure, but suspect, that it may default to trying to use Python if you don't.

The message about error loading libpython suggests that you have a FontForge binary which requires Python.  It's unlikely that copying one or two libraries will be enough to satisfy it; Python is a fairly complicated thing and you probably will have to install all of Python to get this FontForge binary to work.  If that's not something you can do on your Web host, you'll probably be stuck compiling your own FontForge binary, if compiling FontForge without Python still works.

**Comment by JoesCat** [comment]
Install FontForge on the server just like any other application.
Learn to setup and use ssh, Use ssh certificates and keys, and limit ssh login to known client addresses to limit crackers from rooting your server.
You should be able to run fontforge as a normal user on the server using an ssh commandline.
https://www.google.ca/search?q=ssh+command+in+linux
Doing a quick look, this looks sort of okay:
http://www.thegeekstuff.com/2008/05/5-basic-linux-ssh-client-commands/

I did not test this out but have done this a few years ago, so it should look something like this (assuming you have a user called jsmith on server):
localhost$scp localhostfile.sfd jsmith@remotehost.example.com:/home/jsmith/localhostfile.sfd
localhost$ ssh -l jsmith remotehost.example.com
fontforge -lang=pe -script modify.pe localhostfile.sfd
localhost$scp jsmith@remotehost.example.com:/home/jsmith/remotehostfile.sfd remotehostfile.sfd

I haven't tested Fontforge, but believe that you can run the FontForge GUI remotely if your client computer also runs X, or X11 (example: linux, BSDs, Apple). If this is correct, you can simply type "fontforge" on the ssh commandline.
https://www.google.ca/search?q=connecting+to+remote+linux+desktop+via+ssh+with+x11+forwarding

If you are using wifi, like a laptop, you should create a box on the server side in case you lose the connection. Ideally, do it for hardwire because they can go down too. This allows the box on the other side to continue running, and you can log back into the same box. It's been a couple years since I've done it, so I don't remember the commandline name for the box...maybe something like host or starts with an h (maybe).

If your client computer runs windows, I think you use putty, but no GUI available since you won't have X on the windows side.

**Comment by JoesCat** [comment]
I forgot to add 'exit' after running fontforge so that you exit the ssh shell

**Comment by nycionx** [comment]
ok how can i build fontforge to make it "portable"? so that all necessary files required to run it or contained under one directory? is this possible and if so how would i go about doing it? im using linux mint latest and downloaded the the source code fontforge_full-20120731-b.tar.bz2 unpacked it, opened terminal, typed: 
./configure
then make
but i get an error:
../.libs/libfontforge.so: undefined reference to `PyUnicodeUCS4_DecodeUTF8'
../.libs/libfontforge.so: undefined reference to `PyString_FromStringAndSize'
../.libs/libfontforge.so: undefined reference to `PySequence_Check'
../.libs/libfontforge.so: undefined reference to `PyString_AsEncodedObject'
../.libs/libfontforge.so: undefined reference to `Py_Initialize'
../.libs/libfontforge.so: undefined reference to `_Py_ZeroStruct'
../.libs/libfontforge.so: undefined reference to `PyArg_ParseTupleAndKeywords'
../.libs/libfontforge.so: undefined reference to `PyExc_NotImplementedError'
../.libs/libfontforge.so: undefined reference to `PyMapping_Check'
../.libs/libfontforge.so: undefined reference to `PyFloat_Type'
../.libs/libfontforge.so: undefined reference to `PyInt_AsLong'
../.libs/libfontforge.so: undefined reference to `Py_Main'
../.libs/libfontforge.so: undefined reference to `PyObject_CallMethod'
../.libs/libfontforge.so: undefined reference to `PyMem_Free'
../.libs/libfontforge.so: undefined reference to `Py_InitModule4_64'
../.libs/libfontforge.so: undefined reference to `PyObject_GetAttrString'
../.libs/libfontforge.so: undefined reference to `PyEval_CallObjectWithKeywords'
../.libs/libfontforge.so: undefined reference to `PyUnicodeUCS4_AsUTF8String'
../.libs/libfontforge.so: undefined reference to `PyObject_SelfIter'
../.libs/libfontforge.so: undefined reference to `PyErr_SetString'
../.libs/libfontforge.so: undefined reference to `PyMapping_GetItemString'
../.libs/libfontforge.so: undefined reference to `PyExc_ValueError'
../.libs/libfontforge.so: undefined reference to `PyExc_TypeError'
../.libs/libfontforge.so: undefined reference to `PyTuple_GetItem'
../.libs/libfontforge.so: undefined reference to `PyErr_Print'
../.libs/libfontforge.so: undefined reference to `PyMem_Realloc'
../.libs/libfontforge.so: undefined reference to `PySequence_GetItem'
../.libs/libfontforge.so: undefined reference to `PyObject_Free'
../.libs/libfontforge.so: undefined reference to `PyFloat_FromDouble'
../.libs/libfontforge.so: undefined reference to `PyString_Decode'
../.libs/libfontforge.so: undefined reference to `PyType_Ready'
../.libs/libfontforge.so: undefined reference to `PySequence_Size'
../.libs/libfontforge.so: undefined reference to `PyErr_Clear'
../.libs/libfontforge.so: undefined reference to `PyDict_Update'
../.libs/libfontforge.so: undefined reference to `PyExc_KeyError'
../.libs/libfontforge.so: undefined reference to `PyString_FromString'
../.libs/libfontforge.so: undefined reference to `PyExc_EnvironmentError'
../.libs/libfontforge.so: undefined reference to `PyRun_InteractiveLoopFlags'
../.libs/libfontforge.so: undefined reference to `PyTuple_New'
../.libs/libfontforge.so: undefined reference to `PyType_Type'
../.libs/libfontforge.so: undefined reference to `Py_BuildValue'
../.libs/libfontforge.so: undefined reference to `PyErr_Occurred'
../.libs/libfontforge.so: undefined reference to `PyString_AsString'
../.libs/libfontforge.so: undefined reference to `PyTuple_SetItem'
../.libs/libfontforge.so: undefined reference to `_Py_NoneStruct'
../.libs/libfontforge.so: undefined reference to `PyFloat_AsDouble'
../.libs/libfontforge.so: undefined reference to `PyArg_ParseTuple'
../.libs/libfontforge.so: undefined reference to `Py_SetProgramName'
../.libs/libfontforge.so: undefined reference to `_Py_TrueStruct'
../.libs/libfontforge.so: undefined reference to `PyDict_New'
../.libs/libfontforge.so: undefined reference to `PyBool_Type'
../.libs/libfontforge.so: undefined reference to `PyCallable_Check'
../.libs/libfontforge.so: undefined reference to `PyString_FromFormat'
../.libs/libfontforge.so: undefined reference to `_PyObject_New'
../.libs/libfontforge.so: undefined reference to `PyString_AsStringAndSize'
../.libs/libfontforge.so: undefined reference to `PyInt_FromLong'
../.libs/libfontforge.so: undefined reference to `PyModule_AddObject'
../.libs/libfontforge.so: undefined reference to `PyExc_ImportError'
../.libs/libfontforge.so: undefined reference to `PyExc_AttributeError'
../.libs/libfontforge.so: undefined reference to `PyImport_AppendInittab'
../.libs/libfontforge.so: undefined reference to `PyType_IsSubtype'
../.libs/libfontforge.so: undefined reference to `PyTuple_Size'
../.libs/libfontforge.so: undefined reference to `PyRun_SimpleFileExFlags'
../.libs/libfontforge.so: undefined reference to `PyErr_Format'
../.libs/libfontforge.so: undefined reference to `PyExc_NameError'
../.libs/libfontforge.so: undefined reference to `PyRun_SimpleStringFlags'
../.libs/libfontforge.so: undefined reference to `PyMapping_HasKeyString'
../.libs/libfontforge.so: undefined reference to `PyMem_Malloc'
collect2: error: ld returned 1 exit status
make[1]: *** [../libfontforge.la] Error 1
make[1]: Leaving directory `/home/nycionx/Downloads/fgfgh/fontforge-20120731-b/fontforge'
make: *** [fontforge] Error 2

so im having trouble to build fontforge even normally but i also need it to be portable. which arguments or wutever do i have to type to make this possible?

**Comment by jtanx** [comment]
You're using the wrong tarball. The latest version is [here](https://github.com/fontforge/fontforge/releases/download/20150824/fontforge-20150824.tar.gz) (found [here](https://github.com/fontforge/fontforge/releases)). Try that first and see how you go.

**Comment by nycionx** [comment]
ok i was able to successfully build it using this configure setup so that all libs are in the same folder:

./configure --prefix=/home1/nycionx/public_html/ff --exec-prefix=/home1/nycionx/public_html/ff --libdir=/home1/nycionx/public_html/ff --includedir=/home1/nycionx/public_html/ff --datarootdir=/home1/nycionx/public_html/ff

then i uploaded the ff folder to my server and tried to run a fontforge script same as before but get this error:

./ff/bin/fontforge: /lib/libc.so.6: version `GLIBC_2.15' not found (required by /home1/nycionx/public_html/ff/libfontforge.so.1)
./ff/bin/fontforge: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /home1/nycionx/public_html/ff/libgutils.so.1)
./ff/bin/fontforge: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /home1/nycionx/public_html/ff/libgunicode.so.3)

so wtf, i mean i got libs depending on libs depending on other libs and on an on we go, how far does it go jesus christ, cant i have ALLLL the necessary libs under ONE directory?? i do not have permission to create the folder /lib/ and place libc.so.6 in there since this is a shared web hosting server (HostGator) and i dont have root access of course.

so is it possible at all to get what i want? i hate these FIXED paths. i need RELATIVE paths. like in Windows this isnt a problem at all. if an exe requires some dll it will first look inside the folder its calling from which is logical. this linux sh*t is driving me crazy!
Please help!

**Comment by jtanx** [comment]
Mmm yeah one of the nice things about Windows is a stable API/ABI...

Sounds like your server is running an older version of glibc than what you compiled for. You need to replicate your server environment as much as possible if you're going to compile on another machine. But yes, FontForge is a relatively complex program and it has many dependencies. Personally, I somewhat doubt that you'll be able to get it running unless you can compile it on the server.

**Comment by nycionx** [comment]
i just tried it but failed, i knew it:

checking for gcc... no
checking for cc... no
configure: error: in `/home1/nycionx/public_html/fontforge-20150824':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details.
checking for cl.exe... no

so i cant do anything since its not my server but hostgators right?

what about this stuff i googled:

http://www.cyberciti.biz/faq/linux-setting-changing-library-path/
http://superuser.com/questions/192573/how-do-you-specify-the-location-of-libraries-to-a-binary-linux

something to do with my own conf like /etc/ld.so.conf.d/blabla.conf
where i add some path directories to libraries? would i add like the path /home1/nycionx/public_html/ff   for instance? would that work? or what about LD_LIBRARY_PATH? whats that? can i use it in the configure command when builiding fontforge? or what about the env vars that the configure provides like CFLAGS, LDFLAGS, LIBS,CPPFLAGS, etc. how would i use these and would they work for what i want to achieve?

im still unconvinced that this is impossible! there must be SOMEONE out there that was able to put fontforge onto a server and run it and not just me. i just dont want to have to build my own server from home, i know that would work but its just a hassle for me.

so what about these env vars and the .conf file?

**Comment by JoesCat** [comment]
For security reasons, changing library paths using ld is unlikely to work since it involves /etc and/or /usr, which you will have read access, but not write access.
In terms of substituting libraries, you can run a shell with EXPORT pointing to alternate libraries, something like this: http://www.joescat.com/java/#MAK
One thing that might be worth trying is to get yourself a relatively old knoppix CDrom, and then compile on that...for anything that appears missing, add it, and try building again. You can do some substitutes, as per hostgator: http://support.hostgator.com/articles/specialized-help/technical/linux-application-paths-what-is-the-path-to  (as per that page... note you will need to call to have permission to use some programs).
Last but not least, FontForge is a very complex program, and looking at some of the code, I suspect it may bork on you if you try running more than one instance at a time unless you run them as separate users... running under same user will possibly get an intermingling of data back-n-forth if you have 2 users at the same moment run FontForge (fairly sure for the GUI, but needs better look for GUI-free version)..

**Comment by mskala** [comment]
I think that running multiple copies of FontForge at once is unlikely to be a problem, whether under the same or separate user IDs.  I was doing that frequently in the Tsukurimashou build before I switched to FontAnvil.

**Comment by mskala** [comment]
I believe this option was removed in commit 87cc3a67eee8208e0e7 , as part of @rrthomas's effort to use Gnulib wherever possible (so as to have one big dependency instead of many little ones).  Gnulib will probably provide iconv if you don't already have it, so it should not be necessary to install iconv separately.  If you don't have iconv, I think that fact will be detected and it'll build correctly without your needing to specify any option.  However:  A. you _ought_ to have iconv already, it's a pretty basic library used by nearly anything with internationalization support; and B. it's not clear to me whether Gnulib's iconv-subsititute support really works.

All I can suggest on building current FontForge without iconv is, try it and see if works, and if it doesn't, then it is probably not possible to make it work.

FontAnvil has a --without-iconv option to configure, inherited from an older FontForge version.  I don't know if that works and it can really build without iconv.  All my test machines have iconv.

**Comment by mskala** [comment]
Further to that:  current FontAnvil seems to build fine with the --without-iconv option specified to configure (although on a machine where iconv actually does exist), and the binary passes the same number of tests in both configurations.

**Comment by nycionx** [comment]
ok new problem, i decided to use CentOS 6.4 for my server and im having a problem while trying to build fontforge on it since the OS comes with an older version of python (2.6). so i googled how to install python 2.7 and everything went well but when i ran ./configure again i got it saying it can find python but not PYTHON..??? wut?? here:

checking for a Python interpreter with version >= 2.7... python2.7
checking for python2.7... /usr/local/bin/python2.7
checking for python2.7 version... 2.7
checking for python2.7 platform... linux2
checking for python2.7 script directory... ${prefix}/lib/python2.7/site-packages
checking for python2.7 extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for PYTHON... no
configure: error: in `/home/nycionx/Downloads/fontforge-20150824':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables PYTHON_CFLAGS
and PYTHON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

wut am i doing wrong and how can i fix this? 

also it says previously:

checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.25... no

my version is 0.23 is that a problem? thats the latest for 6.4. only CentOS 7.1 has 0.27 but i heard 6.4 is more stable and want to stick with it.

so is the problem with python or pkg-config?

here is where i learned how to install python 2.7 btw:
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

**Comment by nycionx** [comment]
ok nvm i fixed it doing this:

curl http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz -o pkgconfig.tgz
tar -zxf pkgconfig.tgz && cd pkg-config-0.28
./configure --with-internal-glib
make install

but now i have a NEW problem (yay!)
it cant find zlib! even tho i installed all the packages:

checking for PYTHON... yes
checking for library containing cos... -lm
checking for library containing XOpenDisplay... -lX11
checking for library containing XOpenDevice... no
checking for library containing XkbQueryExtension... none required
checking for ZLIB... no
configure: error: Package requirements (zlib) were not met:

No package 'zlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ZLIB_CFLAGS
and ZLIB_LIBS to avoid the need to call pkg-config.

**Comment by nycionx** [comment]
nvm i fixed it all myself, but what a hassle man...i freakin hate linux

**Comment by JoesCat** [comment]
On November 19, 2015 01:28:34 PM nycionx wrote:
> but now i have a NEW problem (yay!)
> it cant find zlib! even tho i installed all the packages:

I'm guessing this wasn't the latest version of FontForge HEAD.
I added a patch Nov6 to check for zlib if pkgconfig failed to find zlib.

**Comment by nycionx** [comment]
where can i find this patch? i dont see the section here on github?

also, cant i build without python anymore? there used to be that option..again removed or something? why? also --without-x is missing, please let me know if there's a way, i dont need python nor X11. thx

**Comment by jtanx** [comment]
Clone the latest head from github to get the zlib patch. Since it's not a tarball, you'll have to run:

      ./bootstrap

before you can run `./configure`. Check `./configure --help` to see what the specific options are for disabling X11 and python scripting.

**Comment by nycionx** [comment]
yes i did ./configure --help but --without-python and --without-x is missing! it used to once be there like in fontforge_full-20120731-b.tar.bz2
can you please return this option? thx!

**Comment by jtanx** [comment]
If you looked carefully at the output, you would see:

~~~~~~
--disable-python-scripting
--disable-python-extension
--with-x
~~~~~

Wherever you see a `with-` option, the `without-` option is implied. So try running

      ./configure --disable-python-scripting --disable-python-extension --with-x
