### ISSUE TITLE
Some progress with installation failure: dylibs not found

### ISSUE THREAD

**Issue by DannyThomas** [fontforge/fontforge#2568]
Some progress with installation failure: dylibs not found

<pre>
OS/X:      10.9.5
XQuartz:   2.7.8
FontForge: version 20150829 based on sources from 16:56 PDT 29-Aug-2015
           git:2409f895596e967721586667e38a899f419932b1

Opened Fontforge-20150824.dmg and installed in /Applications

<pre>FontForge immediately exited, with this error from console entry
  Dyld Error Message:
    Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
    Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
    Reason: image not found
symlinked /Applications/FontForge.app/Contents/Resources/opt/local/lib/lib ->
          /opt/local/lib
That seemed to make progress, but FontForge immediately exited, with this error
  Dyld Error Message:
    Dyld Error Message:
    Library not loaded: /opt/local/lib/libgif.4.dylib
    Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
    Reason: image not found
Which I couldn't fix because there was no such file anywhere on the disk

NB I don't have an immediate for the program but I couldn't determine
from the web site whether it provides conversion
  ttf/otf/ -> woff/woff2
There is no instance of "woff2" from google search "woff2 site:fontforge.github.io"
I can't find it now but I think I saw:
  woff -> otf.ttf.sfnt
  </pre>

**Comment by jtanx** [comment]
See #2569
