### ISSUE TITLE
Jagged edges on glyphs when generating OTF!

### ISSUE THREAD

**Issue by nycionx** [fontforge/fontforge#2578]
I have a font that is originally OTF but if i introduce some TTF glyphs in it and save it as OTF and open the new file, the TTF glyphs have jagged edges in some places (nodes). What is going on here? Some bug definitely. I dont have this problem when using FontLab Studio 5. Looks like Fontforge has trouble to convert the quadratic Bézier curves (TTF) to cubic Bézier curves (OTF). Has no one ever seen this or complained about it? Can someone please fix this with a patch if possible? Thx!

**Comment by NuttShell** [comment]
**nycionx**
Like this?
https://github.com/fontforge/fontforge/issues/2377

**Comment by nycionx** [comment]
Yes! So this hasnt been solved yet or wut? :(

**Comment by NuttShell** [comment]
**nycionx**
in FF scripting solved for me, in FF GUI - dont know.

**Comment by nycionx** [comment]
ok i just need for scripting too, so wuts the solution? i havent tested it yet but should it work properly with the latest build (fontforge-20150824.tar.gz) or do i need some patch or..?

**Comment by NuttShell** [comment]
**nycionx**
like this (for me):
```
#!/usr/ff/bin/fontforge
TTFfileName = $1;
filePath = $2;
Open(TTFfileName,1);
OTFfontName = $fontname+".otf";
OTFFullfontName = filePath+OTFfontName;

SetFontOrder(3);
RoundToInt();
RoundToCluster();
Generate(OTFFullfontName);
Close();
Quit(0);
```

**Comment by nycionx** [comment]
ok ill try this and let u know if i got a problem. probly in a few days im so busy. thx for the info!

**Comment by nycionx** [comment]
ya this doesnt work for me. tried it in script mode, still getting those ugly edges at some nodes... :(
who can fix this? why is this happening and hasnt been fixed by now already?

**Comment by NuttShell** [comment]
**nycionx**
screen, please

**Comment by nycionx** [comment]
ur right actually, in fonforge it doesnt show the jagged edges but in fontlab studio it does...weird! why? i installed the font and checked in adobe illustrator and no edges! so i guess thats wut matters the most. but its still strange phenomenon

**Comment by skef** [comment]
This appears to be a tool interaction problem beyond FF's scope. Closing.
