### ISSUE TITLE
Show outline when fill is turned on

### ISSUE THREAD

**Issue by mskala** [fontforge/fontforge#2581]
When fill is turned on, the outline disappears.  This seems to be relatively newly introduced - I don't recall seeing it before now, though I haven't been tracking the mainline version carefully.  If someone did this on purpose, I urge them to reconsider.  "Fill" is most useful when it is exactly that - darkening the interior of the outlines while the outlines remain visible.  If I didn't want to see the outlines, I would choose "Preview" instead.

**Comment by jtanx** [comment]
Bisection: Offending commit: dc9db1fadd1e6fabe48481848950de3b0c4d13db
