### ISSUE TITLE
Fine-tuning a trace:

### ISSUE THREAD

**Issue by JonathanMagus** [fontforge/fontforge#2582]
When Potrace is used by Inkscape adjusting the options allows a tighter, more accurate trace. When called by FontForge using the ‘Autotrace’ function of the ‘Element’ tab, Potrace delivers a default outcome. This means it is sometimes more effective to trace in Inkscape and then save as SVG for Fontforge to subsequently import.
 
This works, however, as Potrace is being used in both instances is it possible to have similar fine-tune control over the trace when done directly in Fontforge?

**Comment by jtanx** [comment]
You can specify additional command line options to pass to potrace when it's used in FontForge. If you can find the command line options to refine the trace, then you can set these in the Preferences dialogue - `File->Preferences->Apps->AutoTraceArgs`.

FontForge will always append the arguments `-c --eps -r 72 --output="tmpfilename"` to the output.

**Comment by JonathanMagus** [comment]
Thanks. 

I had not understood that AutotraceArgs in Preferences was not specific to the use of AutoTrace and that it would also work for Potrace.

Reducing the alphamax value there does what I was seeking to achieve.
