### ISSUE TITLE
Rounding coordinates to integers may damage outline data

### ISSUE THREAD

**Issue by derwind** [fontforge/fontforge#2601]
Hi,

I tried to make a font using my hand-writing characters. At first I converted them into SVG by Peter Selinger's potrace and then imported them by fontforge and generated ufo (Unified Font Object) data. It was OK.
In the next, I rounded coordinates of glyphs because potrace outputs decimal coordinates, and generated ufo data. But I noticed that some glyphs had invalid outline data.
### My environment

OS: Ubuntu 14.04
Fontforge: built from source code: git hash 54eeda3ef9c1c48f880ccb401d3505b788c80ee0  (Fri Dec 25 12:31:18 2015 +0100)
### How to reproduce the problem

(1)convert bmp to SVG by potrace.
(2)select arbitrary box in glyphs list in fontforge and import the SVG data by "File"->"Import".
(3)Round corrdinates by "Element"->"Round"->"To Int" (not depend on whether from fontview or charview)
(4)Generate ufo by "File"->"Generate Fonts" (Unified Font Object).

Opening the ufo data by fontforge again, some glyphs' outlines may be corrupted.
Note that it's no problem if (3) is omitted.
### Example

``` XML
<point x="466.1" y="409.5" type="curve" smooth="yes"/>
<point x="449.7" y="409.3"/>
<point x="436.3" y="408.7"/>
<point x="435.8" y="408.2" type="curve" smooth="yes"/>
<point x="434.6" y="407"/>
<point x="433.7" y="396.1"/>
<point x="431.1" y="354.5" type="curve" smooth="yes"/>
```

is rounded into

``` XML
<point x="466" y="410" type="curve" smooth="yes"/>
<point x="450" y="410"/>
<point x="436" y="408" type="line" smooth="yes"/>
<point x="435" y="407"/>
<point x="434" y="396"/>
<point x="431" y="354" type="curve" smooth="yes"/>
```

A line segment with one handle is seen, but it's an invalid data.
### Further detail

I also debugged fontforge's source code using GDB and found a buglike procedure. It's updating conditions of sp->nonextcp and sp->noprevcp in SplinePointRound function in splinechar.c .
potrace sometimes generates very very short handles. So rounded handles may have 0 lengths. But in this case, noextcp and/or noprevcp are set to true in SplinePointRound. I suspect it is a cause of the problem.
### My patch for the problem

I don't know this patch is good or not, but the problem seems to be resolved in my environment by this modification.
Could you please examine it?

In short, modification is that setting nonextcp and/or noprevcp to true if the length of a handle is 0 both before AND after rounding it.

``` C
$ git diff
diff --git a/fontforge/splinechar.c b/fontforge/splinechar.c
index c242218..dd98bfd 100644
--- a/fontforge/splinechar.c
+++ b/fontforge/splinechar.c
@@ -707,6 +707,9 @@ return;

 void SplinePointRound(SplinePoint *sp,real factor) {
     BasePoint noff, poff;
+       BasePoint origme = sp->me;
+       BasePoint orignextcp = sp->nextcp;
+       BasePoint origprevcp = sp->prevcp;

     if ( sp->prev!=NULL && sp->next!=NULL && sp->next->order2 &&
            sp->ttfindex == 0xffff ) {
@@ -738,9 +741,9 @@ void SplinePointRound(SplinePoint *sp,real factor) {
        sp->next->to->prevcp = sp->nextcp;
     if ( sp->prev!=NULL && sp->prev->order2 )
        sp->prev->from->nextcp = sp->prevcp;
-    if ( sp->nextcp.x==sp->me.x && sp->nextcp.y==sp->me.y )
+    if ( sp->nextcp.x==sp->me.x && sp->nextcp.y==sp->me.y && orignextcp.x==origme.x && orignextcp.y==origme.y )
        sp->nonextcp = true;
-    if ( sp->prevcp.x==sp->me.x && sp->prevcp.y==sp->me.y )
+    if ( sp->prevcp.x==sp->me.x && sp->prevcp.y==sp->me.y && origprevcp.x==origme.x && origprevcp.y==origme.y )
        sp->noprevcp = true;
 }
```

Regards.

**Comment by skef** [comment]
The general case of this issue is a major and pervasive problem. FontForge will decide that one cubic spline control point doesn't exist while leaving the other one, and then use that decision in subsequent translations. 

Before we fix these we should decide on a convention, preferably one without redundant info like the current one.
