### ISSUE TITLE
No scripting API to merge .fea feature files

### ISSUE THREAD

**Issue by katef** [fontforge/fontforge#2603]
There's a `GenerateFeatureFile` to generate these, but no equivalent to merge them. I would like to be able to automate merging from `.fea` files from a script, so that I can automate that as part of my build system.

Looking at [scripting.c](https://github.com/fontforge/fontforge/blob/master/fontforge/scripting.c#L8250) I see there's `MergeFeature`, but that looks unrelated.

**Comment by mskala** [comment]
MergeFeature() loads the features from a feature file into the current font, attempting to merge them with any features already there.  Is that what you want?  Have you tried it?

The internal function implementing this feature is unfortunately named "MergeKern"; it wraps a call to LoadKerningDataFromMetricsFile(), and that function is located in a source file whose name claims it's about saving AFM files.  But MergeFeature() does nonetheless merge feature files, including all types of features, not only kerning features.  The names of internal functions should not be used as the first resort for determining what user-visible commands will do.

**Comment by katef** [comment]
Oh great! No, I hadn't tried it — I saw the source talked about AFM files and kerning, and I thought that it was something unrelated. Thanks.

**Comment by katef** [comment]
@mskala About naming, this `MergeFeature` function, does it really ''replace'' features rather than merge over them?

I have lots of kerning information set in my `.sfd` file, and a `.fea` file which performs substitutions for stylistic alts and whatnot, with no description of kerns. All the kerns seem to be set to 0, when I use `MergeFeature` to bring in the `.fea` file.

Must I export the kerns to `.fea` format too? I'd rather not, since there's a lot of them.

**Comment by mskala** [comment]
It does make an *attempt* to merge what is in the file with what is already in the font.  However, exactly what that means is not 100% clear, especially if the feature file mentions a table that already exists in the font.  I think it's safest to export the features you want to keep, blow away whatever's in the font, and then use MergeFeature to load them back.  That's what I do - and it's not great, but does seem to work.

**Comment by katef** [comment]
Is there a scriptable way to blow things away? :)

**Comment by mskala** [comment]
I think GetLookups, followed by looping over the returned array with RemoveLookup, will work.  But this will require some experimentation.  What I actually do in my own project is regenerate an entire font from scratch (starting with no features in the font) so I'm not using a specific command to remove existing features.

**Comment by katef** [comment]
Hm. But what do you generate your font from? What's your canonical source for glyph outlines?

I could imagine keeping featureless .sfd files as the source, and only mergining in .fea things on-the-fly when generating .otf. That might work out, perhaps.

**Comment by mskala** [comment]
The ultimate source for me is MetaPost files, which generate Postscript, which are then merged in FontAnvil (FontForge would work) and the features added to generate OpenType.  Code available from http://tsukurimashou.osdn.jp/ .  Using FontForge .fea files as the "source" form seems to be what many projects do if they want to edit the sources graphically.  I think keeping the features separately in .fea files and editing those is much easier, but some people seem to prefer using FontForge's GUI to edit features.

**Comment by katef** [comment]
I see! That makes a lot more sense. Thanks!

In my case I'm working on somebody else's font kept in .sfd format. It really bothers me that we seem to use non-parametric formats for so many fonts. What a lot of effort!

I think what I probably ought to do, is find a way to strip this stuff out of the .sfd files, and keep the kerning canonically in .fea format. Meanwhile I'm closing this ticket. Thanks again!
