### ISSUE TITLE
Mac short guide broken download link

### ISSUE THREAD

**Issue by allcaps** [fontforge/fontforge#2604]
The download link for Fontforge in the [short guide](https://fontforge.github.io/en-US/downloads/mac/) is broken. 

The current link points to:
https://github.com/fontforge/fontforge/releases/download/20150824/Fontforge-20150824.dmg 
It should point to: 
https://github.com/fontforge/fontforge/releases/download/20150430/FontForge-2015-04-30-Mac.app.dmg

**Comment by ultrasquid** [comment]
However, the package at
http://fuuko.libferris.com/osx/packages/201509/17_0419/ is one that
actually works. Some features of the Github build seem to be missing in the
Fuuko build, or I haven't compared them properly.

On Wed, Jan 6, 2016 at 3:23 PM, Coen van der Kamp <notifications@github.com>
wrote:

> The download link for Fontforge in the short guide
> <https://fontforge.github.io/en-US/downloads/mac/> is broken.
>
> The current link points to:
>
> https://github.com/fontforge/fontforge/releases/download/20150824/Fontforge-20150824.dmg
> It should point to:
>
> https://github.com/fontforge/fontforge/releases/download/20150430/FontForge-2015-04-30-Mac.app.dmg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2604>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by marnen** [comment]
Also, Homebrew is no longer a viable install option for the GUI (even through Cask, it installs a broken version of FontForge). We should update the guide. I'll make a pull request, but before I do, I want to get some clarity on what we should recommend.

**Comment by jtanx** [comment]
Hmm since I don't use OSX would anyone mind setting up a PR to fix the download link? The relevant file is here: https://github.com/fontforge/fontforge.github.io/blob/master/en-US/downloads/mac.md

Post PRs to the website here https://github.com/fontforge/fontforge.github.io/pulls

**Comment by marnen** [comment]
@jtanx Looks like this got corrected at some point, except for the mention of Homebrew.
