### ISSUE TITLE
mirror characters so that they appear as numerals

### ISSUE THREAD

**Issue by CNXTim** [fontforge/fontforge#2606]
Hi,

I have a deceptively simple requirement; that is to use the upper case characters "S" and "E" so that they appear to be the numerals "5" and "3" .

I need asssitance in selecting the most approproite sans serif font to enable this illusion to be best carried off in a word such as CONSENT becoming CON53NT

**Comment by mskala** [comment]
On Sun, 10 Jan 2016, CNXTim wrote:
> I have a deceptively simple requirement; that is to use the upper case
> characters "S" and "E" so that they appear to be the numerals "5" and "3"

Wouldn't 2 be a better mirror image of S, than 5?

**Comment by CNXTim** [comment]
the project is exactly as i stated it; "5" and "3"

**Comment by CNXTim** [comment]
Perhaps a simpler way to explain ; the "5" is to look like a slightly modified  "S" and "3" is to look like a mirror imaged "E" So i presume the sans serif font selected will be crucial to creating the first glance illusion of the full word such as CONSENT is confused by the accepted fact that people actually look at the shape of the word, and NOT the individual characters when reading.

**Comment by CNXTim** [comment]
So final will be CON53NT

**Comment by skef** [comment]
This question isn't FontForge-specific.
