### ISSUE TITLE
cloud you open font in the middle of the window?wrong with Dual monitors

### ISSUE THREAD

**Issue by ted423** [fontforge/fontforge#2614]
I use dual monitors with different display resolution。
the software will display like this
![2016-01-27 19_50_43-greenshot](https://cloud.githubusercontent.com/assets/7042766/12612653/4fc4b23a-c52f-11e5-8a69-4364e84f36cf.png)

**Comment by skef** [comment]
Most of our dual montor problems are solved with the now-preferred GTK backend.
