### ISSUE TITLE
compilation without libspiro fails

### ISSUE THREAD

**Issue by lemzwerg** [fontforge/fontforge#2617]
[d4b202bc6f5cc10642631fdc89ba566118466daa]

If libspiro isn't present, compilation currently fails with

```
  CCLD     libfontforge.la
.libs/libfontforge_la-spiro.o: In function `SSRegenerateFromSpiros':
fontforge/spiro.c:274: undefined reference to `_SpiroCP2SplineSet'
```

This is a regression.  About half a year ago it worked just fine without libspiro.

**Comment by JoesCat** [comment]
Hi @jtanx, do recall what functions you were trying to make more robust 7-9-2015.
Maybe worth replacing the functions that need it with SSRegenerateSpiros - but would like to know what was getting fixed so we don't put a regression on a regression.

**Comment by jtanx** [comment]
The relevant commit is 31935b6eddf6b73941267ce316865ed54c8629c7. I recall it was to do with a segfault/crash occurring if the Spiro failed to converge.

Anyway, #2645 should fix this.

**Comment by JoesCat** [comment]
Thanks @jtanx!
Can you close if working okay @lemzwerg?

**Comment by lemzwerg** [comment]
It works, so please merge #2645.

**Comment by jtanx** [comment]
Thanks for testing! Currently waiting on an issue with Travis before merging.
