### ISSUE TITLE
dmg not found

### ISSUE THREAD

**Issue by pnlawlor** [fontforge/fontforge#2618]
Looks like a great project

Unfortunately when trying to download the dmg for Mac, the .dmg file isn't found.

Best
Pat

**Comment by corv89** [comment]
Same issue here

**Comment by JohnDDuncanIII** [comment]
I believe the build you're looking for is [here](https://github.com/fontforge/fontforge/releases/download/20150824/Fontforge-2015-08-24-Terminal_only.dmg).

Other (working) builds are [here](http://fuuko.libferris.com/osx/packages/)

**Comment by jtanx** [comment]
I've set the website to point to 2015-04-30 (last known working gui version on osx)
