### ISSUE TITLE
Too many glyphs. How can I select only certain range of glyphs?

### ISSUE THREAD

**Issue by haxpor** [fontforge/fontforge#2621]
![screen shot 2016-02-06 at 7 33 52 pm](https://cloud.githubusercontent.com/assets/673757/12866679/2d43f9aa-cd09-11e5-9bc3-7f65580864de.png)

I try to make the font monospace by setting width to be the same for all glyph.
But whenever I try to generate the font, it shows as above.

How can I select only certain range of glyphs?

**Comment by haxpor** [comment]
I solved the problem now by select glyphs that I don't need and remove it.
I followed this wiki http://wiki.unity3d.com/index.php?title=Create_a_new_TrueType_font_using_a_subset_of_characters_from_an_existing_TrueType_font.

**Comment by milahu** [comment]
to select a small range of glyphs, you can use the mouse pointer, 
to draw a selection from first glyph to last glyph.

with shift + click you can add or remove single glyphs.

> I followed this wiki ....

>  How to extract a specific sub range of characters:
> 1. Open the font in FontForge 
> 2. Select the Unicode subrange you want by going to Edit->Select->Select by Script.

this is useful when you only need latin glyphs, for example ....
but i did not find a way to select a range by numbers

**Comment by SoraAzure** [comment]
File > Execute Script, then type in 
> fontforge.activeFont().selection.select(("ranges", None), 0x1234, 0xABCD)

and click OK.
