### ISSUE TITLE
Creating substitutions in TTF fonts on Mac OS X (init/medi/fina)

### ISSUE THREAD

**Issue by mikkelee** [fontforge/fontforge#2623]
Hi

I'm trying to create a font that automatically substitutes `s` with `ſ` (long s) under the right circumstances (`ſ` for initial and medial forms, `s` for terminal forms). However, I can't seem to get it to work.

I've tried creating a minimal example, a font with quickly drawn letters `o`, `s`, and `ſ`. It has lookup tables for simple substituion where the `s` should get replaced with `ſ` when it is initial or medial. But when I generate the fonts (I choose Apple in the generate fonts options dialog), the substitutions do not happen when I type a text (`sosos` should render as `ſoſos`) .

I've attached the .sfd and generated .ttf files: [Archive.zip](https://github.com/fontforge/fontforge/files/120745/Archive.zip)

Any idea what's going wrong?

**Comment by frank-trampe** [comment]
@davelab6, how is this supposed to work?

**Comment by davelab6** [comment]
@mikkelee I think that the init/medi/fina features can't be used for Latin. 

There was a discussion about this topic in http://typedrawers.com/discussion/1358/what-are-the-best-practices-for-the-hist-feature-long-s

**Comment by mikkelee** [comment]
Thanks for the link. I eventually got it working by using `calt` features instead of init/medi/fina. I should have mentioned that in this issue.

**Comment by mikkelee** [comment]
You may close this if you choose. As mentioned, it's not an issue for me.
