### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by arunji2020** [fontforge/fontforge#2625]
Hi Team,

I have extracted customized font from pdf using fontforge and I have installed that font. I can able to see the Tamil language text using that customized font. But if I used any standard Tamil font in that text, I could not able to see it properly full of ASCII codes. How that particular text which support customized font to support the standard fonts like Bamini, latha etc., Could you please help on this?

Thanks,
Ak Arunkumar

**Comment by frank-trampe** [comment]
What do you mean by "the Tamil language text", and where are you displaying that text using the typeface?

It's probably a warning sign if non-western text is encoded in ASCII, particularly in the age of Unicode. How did you get/encode the text?

**Comment by jtanx** [comment]
It might also clarify things if you specified what OS you were using
