### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by Shawali** [fontforge/fontforge#2627]
Hello!

I have created a font on Illustrator, imported all the characters in SVG into Font Forge, generated the font and installed it.

It works great but when I press the space bar, instead of getting an actual space, I get a vertical rectangle, as if the glyph was missing.

I've found the glyph box for space in FF but I don't know really what to do with it. If I move the guides inside it, once I reinstall the font, the glyphs are all wrong ie I get a comma or whatever when I press the A key, etc.

Am I missing something here? Thanks!!

Charlie

**Comment by ultrasquid** [comment]
You need to set the width of your space. You don't have to put any shape in
there but space is a glyph and if the slot is empty it will present your
default glyph if pressed. Select the space slot in the font view and use
Metrics> Set Width, and give it any number greater than zero (though it
should be about half to two thirds the average width of your lowercase
letters).

The second problem sounds like your encoding is being set wrong. Use
Encoding> Reencode> ISO 10646-1 (Unicode, BMP). Unless you need to support
a legacy or specialty system there is no reason to use something other than
Unicode. Also be sure that the Compact attribute is not ticked.

On Wed, Feb 17, 2016 at 5:25 AM, Shawali <notifications@github.com> wrote:

> Hello!
>
> I have created a font on Illustrator, imported all the characters in SVG
> into Font Forge, generated the font and installed it.
>
> It works great but when I press the space bar, instead of getting an
> actual space, I get a vertical rectangle, as if the glyph was missing.
>
> I've found the glyph box for space in FF but I don't know really what to
> do with it. If I move the guides inside it, once I reinstall the font, the
> glyphs are all wrong ie I get a comma or whatever when I press the A key,
> etc.
>
> Am I missing something here? Thanks!!
>
> Charlie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2627>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by Shawali** [comment]
Thanks for your answer!

It didn't work at first, changing the width of the space glyph screwed up evertyhing and the ISO 10646-1 (Unicode, BMP) was already selected. But the, it worked when I set the width coefficient. I'm not sure why and how, but it works =)

**Comment by davelab6** [comment]
@Shawali what is the width coefficient?

**Comment by uriasjaime515** [comment]
i understand the question and the answers but i cant understand how to find exactly where the actual glyph is locqated if anyone can help me out.
