### ISSUE TITLE
Add a .github folder with templates for issues and pull requests

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2628]
The https://github.com/dear-github/dear-github letter has a practical response in https://github.com/blog/2111-issue-and-pull-request-templates

We should add a .github folder with templates for
- [ ] issues and 
- [ ] pull requests

I think it is good to leave the CONTRIBUTING.md file in the root so it is more visible.

**Comment by souravsingh** [comment]
I would like to work on this issue.

**Comment by davelab6** [comment]
Awesome! Please do and send a PR :D

**Comment by divayprakash** [comment]
Working on it!

**Comment by divayprakash** [comment]
PR is #2650
