### ISSUE TITLE
Internal Error: Some fragments did not join

### ISSUE THREAD

**Issue by eosrei** [fontforge/fontforge#2631]
Steps to reproduce #1424. The attached SVG (renamed to .txt to make github happy) and code below causes the error: `Internal Error: Some fragments did not join`

I accidentally imported the wrong file and was quite confused as to how this error appear. Solution was to import the correct file.

```py
import fontforge

font = fontforge.font()
glyph = font.createChar(0x000d, 'CR')
glyph.importOutlines('fragments_did_not_join.svg')
```
[fragments_did_not_join.svg.txt](https://github.com/fontforge/fontforge/files/139521/fragments_did_not_join.svg.txt)

Edit: I posted this in case someone else encounters the same issue, not asking for it to be fixed.

**Comment by frank-trampe** [comment]
Was the input a valid svg file?

**Comment by eosrei** [comment]
@frank-trampe Yes, an example file is attached to the initial comment.

**Comment by jtanx** [comment]
@eosrei just for future reference, but you can comment on closed issues, such as on #1424 instead of creating a new issue. Thanks.

**Comment by eosrei** [comment]
@jtanx I know I can comment on closed issues. @davelab6 requested a new issue when a reproducible test case was available, this is that test case. https://github.com/fontforge/fontforge/issues/1424#issuecomment-49561951

**Comment by davelab6** [comment]
(I'll try to advise re-opening in future :)
