### ISSUE TITLE
Broken link ?

### ISSUE THREAD

**Issue by sebuls** [fontforge/fontforge#2633]
When I click Contributors at http://fontforge.github.io/en-US/ I got a message 404 Not found.
Where can I find contributors?

**Comment by isaacminogue** [comment]
Also, on the topic of broken links...

The download button in the shortguide, gives me a 404:
https://github.com/fontforge/fontforge/releases/download/20150824/Fontforge-20150824.dmg

Whereas the detailed guide is correct:
https://github.com/fontforge/fontforge/releases/download/20150430/FontForge-2015-04-30-Mac.app.dmg

**Comment by sebuls** [comment]
When I click detailed guide, a file is downloaded. But I can't read it. I do not use Mac. Is there another reference that linux users can read?

**Comment by AndrewBreyen** [comment]
Another broken link: The Mac " FontForge 2015-08-24" link in detailed guide and simple guide

**Comment by jtanx** [comment]
All OSX downloads should now be pointing to 2015-04-30. The contributors link should also now be fixed. 

For future reference, please post issues about the website to https://github.com/fontforge/fontforge.github.io/issues
