### ISSUE TITLE
wrong link in documentation

### ISSUE THREAD

**Issue by ousia** [fontforge/fontforge#2639]
https://fontforge.github.io/en-US/site/siteindex/ contains a link (https://fontforge.github.io/en-US/site/siteindex/PfaEdit-TeX.html#Italic) which has a 404 destination.

Well, the file https://fontforge.github.io/en-US/documentation/reference/PfaEdit-TeX/index.html doesn’t contain an `id="italic"` attribute.

Just in case it helps.

**Comment by jtanx** [comment]
The site index references all the old documentation. So this should be fixed now with fontforge/fontforge.github.io@eac6eb2933f5b5041dc1da6fe6f44df2746be34e

For future reference, please post website related issues to here: https://github.com/fontforge/fontforge.github.io/issues

Thanks
