### ISSUE TITLE
How to build Type3 on windows

### ISSUE THREAD

**Issue by frankSol** [fontforge/fontforge#2640]
I want to build type3 on Windows!! 

I read [this](http://fontforge.github.io/en-US/documentation/interface/multilayer/) forum and tried to build. but I failed it. 

I just added the below code in ffbuild.sh file

>  PYTHON=$PYINST \
        ./configure $HOST \
            --enable-shared \
            --disable-static \
            --datarootdir=/usr/share/share_ff \
            --without-libzmq \
            --with-freetype-source="$WORK/freetype-2.6" \
            --without-libreadline \
			--enable-type3 \
            || bail "FontForge configure"
        touch fontforge.configure-complete

However, It didn't work:(
Could you give me some tips building type3?

**Comment by jtanx** [comment]
It looks like that compile option doesn't exist any more (that documentation's quite old). Have you already tried using any of the current builds of FontForge? I can see the "Type3 Multi Layered Font" option in the Font Info window.
