### ISSUE TITLE
Mac Installer Flags missing or out dated XQuartz

### ISSUE THREAD

**Issue by telemorph58** [fontforge/fontforge#2644]
Cannot get the Mac OSX installer to work.  It doesn't install fontforge, claiming that the XQuartz utility is missing, or outdated.  A refresh install of XQuartz and a restart of the MacBook Pro doesn't remedy the issue.

**Comment by frank-trampe** [comment]
Where is this installer? We just distribute a .app bundle that you drop into /Applications. (Said bundle is currently broken for other reasons, but it doesn't have an installer.)
