### ISSUE TITLE
solved--help with modifying one glyph in an existing font

### ISSUE THREAD

**Issue by ghost** [fontforge/fontforge#2651]
I read through the directions for fontforge, but the one thing I can't seem to figure out is this:  I own a font that I like and want to use, but the question mark it came with is a nightmare.  It's a squiggle that no one can tell is a question mark.  All I want to do is modify it, and then save it within the original font file.  According to the license I have, this minor modification is deemed acceptable in the EULA.  But is there a way of doing this?  Thanks.

Lisa

**Comment by roma247** [comment]
Forgot to mention: it's an Open type font (Not a ttf) and I'm using Windows...

**Comment by roma247** [comment]
Sorry to bother everyone--it wasn't clear from what I had read that you could just open a font file, modify it, and export the modified font.  There's so much great information in the How-To file, but such simple details as that are missing!  So I just gave it a try and figured it out.  Thanks.
