### ISSUE TITLE
Chinese calligraphy glyphs not rendered correctly

### ISSUE THREAD

**Issue by THausherr** [fontforge/fontforge#2657]
The attached font is a subsetted chinese font. It is not rendered correctly with several java tools that do the rendering themselves, so I wanted to see whether there's anything noteworthy on fontforge. 

See the screenshot of U+53EF - it is also "bad". 
![fontforge](https://cloud.githubusercontent.com/assets/6665575/14114557/aab192ca-f5d7-11e5-8194-c4b649c05b0f.png)

The correct rendering of the glyph is a square and a "T", see screenshot from Adobe Reader:
![adobereader](https://cloud.githubusercontent.com/assets/6665575/14114562/ade698b4-f5d7-11e5-80aa-466b99a093a5.png)

I found one weird thing: points 94, 118 and 119 are on the left of the glyph. (negative X value) (not in the screenshot)

related issue:
https://issues.apache.org/jira/browse/PDFBOX-3293

[PDFBOX-3293-github.zip](https://github.com/fontforge/fontforge/files/193795/PDFBOX-3293-github.zip)

**Comment by HinTak** [comment]
Well-known problem with hinting of dynalab fonts.

**Comment by HinTak** [comment]
Your subsets font is kaiu.ttf made by dynalab for microsoft. This is in the FAQ - look for "kaiu.ttf" in the FAQ.

**Comment by THausherr** [comment]
Ah ok, thanks.
