### ISSUE TITLE
We need *.php font file output for things like PDF made by TCPDF

### ISSUE THREAD

**Issue by MyNamesIs** [fontforge/fontforge#2658]
We need *.php font file output for things like PDF made by TCPDF - I am using automated *.pe scripts to convert out to all formats and it would be nice for full congrency including the PHP font flat files used on utilities like TCPDF a popular PHP library for making PDFs

I am doing this at http://fonts.labs.coop

**Comment by frank-trampe** [comment]
As U. F. O. gains ground as an interchange format, we've been trying to avoid adding new file formats to FontForge. I would suggest using the pen feature in RoboFab to build a converter.
