### ISSUE TITLE
Failed to open file

### ISSUE THREAD

**Issue by pixeleet** [fontforge/fontforge#2661]
I'm running fontforge in a NodeJS application through a `child_process`. In a docker container.

``` 
[Error: Command failed: fontforge -script "/opt/app/node_modules/font-converter/forge.sh" "/opt/app/tmp/imgl16tg.ttf" "/opt/app/tmp/imgl16ti.woff"
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 17:38 UTC 31-Mar-2016-ML-D.
 Based on source from git with hash: 46589404fd1ff5119a4680f9729cd2518e097946
imgl16tg.ttf is not in a known format (or uses features of that format fontforge does not support, or is so badly corrupted as to be unreadable)
Open: Failed to open: /opt/app/tmp/imgl16tg.ttf
Called from...
 /opt/app/node_modules/font-converter/forge.sh: line 2
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'fontforge -script "/opt/app/node_modules/font-converter/forge.sh" "/opt/app/tmp/imgl16tg.ttf" "/opt/app/tmp/imgl16ti.woff"' }
```

Checking the contents of the said folder I see the file is available, however Fontforge seems to be not able to open it. 

```
docker exec $(docker ps -q -f name=asset-converter) ls -la /opt/app/tmp
total 60
drwxr-xr-x  2 root root    40 Mar 31 17:55 .
drwxr-xr-x 13 root root  4096 Mar 31 17:46 ..
-rw-r--r--  1 root root     0 Jan  1  1980 .gitkeep
-rw-r--r--  1 root root 55393 Mar 31 17:55 imgl16tg.ttf
```

Tried it with the latest and greatest version from Github and the generally available package through apt-get.

Any clues to whether this is a bug or a fault on my end?

Cheers,
David

**Comment by mskala** [comment]
Can you open the same file with FontForge running as a GUI program?

**Comment by pixeleet** [comment]
Yep. That works.

**Comment by pixeleet** [comment]
The font file used: [Chunkfive Ex.ttf.zip](https://github.com/fontforge/fontforge/files/198403/Chunkfive.Ex.ttf.zip)

**Comment by mskala** [comment]
It opens fine for me with the FontForge GUI, FontForge interactive scripting, and FontAnvil.  So I'm guessing the file itself is okay.  What's in the script you're trying to run, and what language is that script written in?  From the messages you posted it looks like the script is named "forge.sh", and that's an unusual file extension for a FontForge script (usually .pe for native or .py for Python).

**Comment by pixeleet** [comment]
[font-converter])https://github.com/janezgec/node-js-font-converter) wraps fontforge, and thus the strange invocation you see. It's NodeJS calling a shell script through a child process.

**Comment by mskala** [comment]
I should add - that font file produces a bunch of warnings about name table entries and so on, on opening.  But nothing that should cause the interpreter to stop.

**Comment by pixeleet** [comment]
I saw that too, still, I could open it so I'm wondering still why it couldn't.

**Comment by mskala** [comment]
That's a native script and I suspect that FontForge will at least sometimes default to Python.  Maybe it would help to insert the option "-lang=ff" in the FontForge command line before "-script", if that's possible given the way FontForge is being invoked.

**Comment by pixeleet** [comment]
I've forked `font-converter` and added the line in question. Let's see.

**Comment by pixeleet** [comment]
```
Unknown option: -l
usage: fontforge [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'fontforge -script -lang=ff "/opt/app/node_modules/font-converter/forge.sh" "/opt/app/tmp/imgpdqg6.ttf" "/opt/app/tmp/imgpdqga.woff"' }
```

**Comment by mskala** [comment]
I think the -lang=ff option must come *before* -script on the command line.  Placing it after means it's taken as the parameter for -script and apparently passed through to the Python interpreter.

**Comment by JoesCat** [comment]
You probably want to wrap the entire combined-line in single quotes, otherwise the spaces can be confused for multiple commands and arguments. See if something like this (yellow) makes sense:
http://cvs.savannah.gnu.org/viewvc/aspell/scripts/prezip?root=aspell&r1=1.4&r2=1.4.4.1

 plus, like @mskala mentions, best to clarify with the added -lang=ff in front of -script

**Comment by JoesCat** [comment]
sorry about that, seems I was reading your code (from jul2015), https://github.com/janezgec/node-js-font-converter/blob/master/index.js but that doesn't seem to match the example you have above with the single quotes in the right places.

**Comment by pixeleet** [comment]
@JoesCat I've forked the repo @ https://github.com/Bannerwise/node-js-font-converter

**Comment by pixeleet** [comment]
@mskala @JoesCat Thanks for pitching in. 
Turns out one of our frontend devs' managed to comment out a line in their code which in turn resulted in a malformed request to our servers. 

I'm closing the issue.

cheers,
David
