### ISSUE TITLE
i can't see glyphs in the font view any more

### ISSUE THREAD

**Issue by kelvin13** [fontforge/fontforge#2665]
um…the glyphs in the fontview suddenly got really really faint. I tried reinstalling fontforge & everything.
![selection_001](https://cloud.githubusercontent.com/assets/2556986/14228342/0a8c5562-f8e0-11e5-82fa-338f6b21d666.png)

I'm using the April 2 version from github, Ubuntu 15.10.

**Comment by jtanx** [comment]
Hmm I can reproduce this. I'll see if I can find what the issue is

**Comment by jtanx** [comment]
Currently bisecting... 35c9398317c0839f24e8924a6e27d1bcfcb15d2f was good, HEAD is bad. So recent issue.

**Comment by jtanx** [comment]
This commit introduced the issue: 92086911ed0be6f3c466643389d777646015b738

Will check later what the issue is. cc @serval2412

**Comment by kelvin13** [comment]
Thank you so much!! <3
