### ISSUE TITLE
Brew installed FontForge doesn't open with UI

### ISSUE THREAD

**Issue by weiweihuanghuang** [fontforge/fontforge#2668]
OS X 10.11.4

```
 Based on sources from 11:56 CEST  3-Apr-2016-D.
 Based on source from git with hash: 1cb7b2e2ee653d32a0b2ff8244c3cea8d55fc716
```

Installed with `brew install -v --debug fontforge --HEAD  --with-giflib --with-x11 --with-libspiro`

And no UI opens? I just get

```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:56 CEST  3-Apr-2016-D.
 Based on source from git with hash: 1cb7b2e2ee653d32a0b2ff8244c3cea8d55fc716
>>> 

```

**Comment by jtanx** [comment]
This is a known issue - IIRC X11 support was removed from the brew version of Cairo which means that the GUI cannot be built with homebrew. I believe you have to use MacPorts(?) to build a version with the GUI. But since I don't use Mac, I could be totally off. @frank-trampe might be able to clarify.

**Comment by weiweihuanghuang** [comment]
Thanks, I will use the packaged app version for UI, and the brew version for scripting.

**Comment by frank-trampe** [comment]
Something like that. I made a fuss somewhere on GitHub and got confirmation that the problem on Homebrew would not be fixed. The additional problem is that our Macintosh .app bundle stopped working sometime last year. I tried posting a new one yesterday, and I'd be thrilled to have somebody test [it] (https://github.com/fontforge/fontforge/releases/tag/20160403) and report back.

**Comment by bagong** [comment]
What would proper testing involve? I downloaded it and started it. It comes up for me (el-capitan and XQuartz 2.9.7 rc2). The first time I started it, it claimed that Untitled1.sfd was missing, from then on it came up fine.

I opened the font musica.ttf. Seemed to go well.

Two issues I noticed:

- in the default Window the glyphs display in a very light grey
- I was scrolling up and down with a trackpad-drag, and apparently overdid it. The program got into a state where scrolling never stopped until ff crashed.

Best
.r.

**Comment by frank-trampe** [comment]
Your first issue is #2665, which we just fixed. The second one is one that we seem to have unsuccessfully fixed many times. I'll take another look.

I'm thrilled that it started at all. Do you have MacPorts installed?

**Comment by frank-trampe** [comment]
@bagong, what typeface were you using when you got the scroll crash?

**Comment by jtanx** [comment]
You can now get the gui with homebrew only, but:

* You must install cairo with the option `--with-x11` (i.e. `brew install cairo --with-x11`)
* You must install pango with the option `--with-x11` (i.e. `brew install pango --with-x11`)
* The FF formula needs to be updated to allow this, but it should configure/compile fine without MacPorts if you do it manually.

**Comment by lemzwerg** [comment]
Is it possible to make homebrew's FontForge formula enforce the `--with-x11` switches to cairo and pango?  Maybe it makes sense to have two formulas, 'FontForge-terminal' and 'FontForge'...

**Comment by jtanx** [comment]
The homebrew team appear to be very reluctant to add back x11 support to anything. Homebrew would likely make building the GUI optional, because when you have `--with-x11`, you have to compile cairo and pango from scratch.

**Comment by DomT4** [comment]
It can be made an option in the formula fairly easily, which can enforce the `pango` and `cairo` correct installations.

https://github.com/fontforge/fontforge/pull/2782 is an interesting PR, we should be able to turn that GUI on by complete default whenever that becomes available, given the removal of the burdensome X11 requirement.
