### ISSUE TITLE
FontForge new release!

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#2669]
Hello, I have a question:
When is released new FontForge version?
The latest version was released on 08.24.2015.

**Comment by jtanx** [comment]
I think @frank-trampe  just tagged an April release, but I would like to see #2665 fixed before it gets rolled out.

**Comment by typedesigner** [comment]
Thank you @jtanx jtanx. The FontLab working on version VI (http://www.fontlab.com/font-editor/fontlab-vi/). It would be optimal if fontforge similar functions gets.

**Comment by frank-trampe** [comment]
@typedesigner, it's better to ask these questions on the mailing list. It's certainly an issue in the general sense that we haven't released a new version since August, but it's not an issue in the GitHub sense of the word.

**Comment by typedesigner** [comment]
@frank-trampe When will new FontForge version be released? Many bugs were fixed since August 2015.

**Comment by fitojb** [comment]
https://github.com/fontforge/fontforge/releases/tag/20160403

> frank-trampe released this 3 days ago

**Comment by typedesigner** [comment]
@fitojb @frank-trampe  I need new FontForge for Windows 
http://fontforge.github.io/en-US/downloads/windows/

**Comment by jtanx** [comment]
@typedesigner the new Windows build should be up now.
