### ISSUE TITLE
Need installation help

### ISSUE THREAD

**Issue by helix42** [fontforge/fontforge#2670]
Hi there,

I wish to install the latest version of FontForge. I'm using Ubuntu (GNOME) 15.10. I followed the general Ubuntu PPA install guide, meaning I ran these commands:

`sudo add-apt-repository ppa:fontforge/fontforge;
sudo apt-get update;
sudo apt-get install fontforge;`

For some reason, though, it installed a 4 year old build, made in 2012.
![screenshot from 2016-04-03 13-46-55](https://cloud.githubusercontent.com/assets/7419656/14232255/fcafc8e2-f9a3-11e5-972e-bbb904b14640.png)

I would like to update it to the latest build, but I'm afraid I'd ruin something if I experiment with things, so I thought asking is the safest thing to do.

I tried to install with the [RPM guide](http://fontforge.github.io/en-US/downloads/gnulinux/) as well, at first it did not detect rpm on my pc, then I installed it, and then it says the downloaded .spec file is not rpm package.

How can I update?
Thanks in advance!

**Comment by frank-trampe** [comment]
@helix42, our Launchpad repository is not currently hosting packages for Wily. I'll try to make that happen on the next release cycle, probably this week, but it might not work without a little tinkering on my part, in which case it might be a few weeks.

**Comment by davelab6** [comment]
@helix42 you suggest you should uninstall it with apt-get/apititude/etc and then install by hand from source

**Comment by frank-trampe** [comment]
@helix42, try updating and installing now.

**Comment by helix42** [comment]
@frank-trampe Yay! It's working now. Thank you for your time and help! :blush:
