### ISSUE TITLE
tarball name is inconsistent

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#2672]
I see that zipfile for Mac contains actual date in its name but same is not for tarball. It is fontforge-20150824.106.g1cb7b2e.tar.gz file. Can this name be fixed to include 20160403 in it?

Also what is significance of "g" in "g1cb7b2e" ? I see that githash is 1cb7b2e only.

This release is marked as pre-release, does that mean in next one or two weeks there will be another release?

**Comment by davelab6** [comment]
@frank-trampe may be able to answer

**Comment by frank-trampe** [comment]
@pnemade, that release was not final, and I plan to make a new release today incorporating some urgent fixes. I was just trying to let people test the Macintosh bundle to see whether we've succeeded in building one that works.

**Comment by frank-trampe** [comment]
And the names were fuzzy because the packages slightly preceded the tagging of the release. They were from the same commit, though. The Red Hat files are named automatically, building on the name of the most recent tag. I don't know about the leading g. I named the Macintosh bundle manually.

**Comment by davelab6** [comment]
Related to https://github.com/fontforge/fontforge/issues/2674
