### ISSUE TITLE
Reduce height of settings window

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2675]
@typedesigner says,

> The Settings window is larger than Windows screen. You can not click OK. This is a bug that should be fixed.

- [x] Screenshot: 

![screen shot 2016-04-05 at 08 01 29](https://cloud.githubusercontent.com/assets/261579/14281040/a5581e0c-fb04-11e5-84d9-29cccfed2a99.png)

- [x] The FontForge version and the operating system you're using: Any since 2014, after 58bc080
- [x] The behavior you expect to see, and the actual behavior: Expected, the Prefs window is 4:3 proportions. Actual: the Prefs window is 1:5 or so
- [x] Steps to reproduce the behavior: File, Preferences
- [x] \(optional) Possible solution: Split Editing section into 2 sections, Editing 1 / Editing 2
- [x] workaround: press 'Enter' to save preferences.

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem: netbook and Windows users typically can't see all the options and particularly can't see the OK button
- [x] If the feature changes current behavior, reasons why your solution is better: No change

**Comment by enathu** [comment]
Related to this https://github.com/fontforge/fontforge/issues/2401#issuecomment-117821983
