### ISSUE TITLE
Mac release 2016-04-04 fails to start with python error

### ISSUE THREAD

**Issue by pthariensflame** [fontforge/fontforge#2684]
FontForge version: `fontforge 18:35 PDT  2-Apr-2016`, `libfontforge 20160402`, `Based on sources from 18:35 PDT  2-Apr-2016-ML-D.`, `Based on source from git with hash: 94038cd93f463ae5020b722a518c65abc843a79a`

FontForge silently fails to start when I attempt to launch it from the `/Applications` folder.  (I haven't tried launching it from elsewhere.)   When I manually invoke `/Applications/FontForge.app/Contents/MacOS/FontForge` from Terminal, I get the following output:

```
PKGBASE: /Applications/FontForge.app
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 18:35 PDT  2-Apr-2016-ML-D.
 Based on source from git with hash: 94038cd93f463ae5020b722a518c65abc843a79a
no xdefs_filename!
TESTING: getPixmapDir:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps
TESTING: getShareDir:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge
TESTING: GResourceProgramDir:/Applications/FontForge.app/Contents/Resources/opt/local/bin
trying default theme:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/resources
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SimpleHTTPServer.py", line 15, in <module>
    import BaseHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/BaseHTTPServer.py", line 81, in <module>
    import mimetools
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so
```

---
- [x] Provide a general summary of the issue in the **Title** above.  
- [x] Before you open an issue, please check if a similar issue already exists or has been closed before.
### Important

Mark with [x] to select. Leave as [ ] to unselect.
### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] (optional) Possible solution/fix/workaround
### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] (optional) Possible solution/fix/workaround

**Comment by davelab6** [comment]
> FontForge silently fails to start when I attempt to launch it from the /Applications folder. (I haven't tried launching it from elsewhere.) 

That's the only place it can run from :)

> When I manually invoke /Applications/FontForge.app/Contents/MacOS/FontForge from Terminal, I get the following output:

That's helpful. It seems the bundled 'flat' python module, part of the bundled 'Even' app, is not working. 

Which version of XQuartz, OS X, and python are you running? How did you install python?

**Comment by pthariensflame** [comment]
`XQuartz 2.7.8 (xorg-server 1.16.4)`

`Python 2.7.11`, installed via Homebrew

![versions](https://cloud.githubusercontent.com/assets/1847577/14369535/babfc52e-fcda-11e5-910d-1d04ca12683b.png)

**Comment by pthariensflame** [comment]
I should also note that, when attempting to run FontForge from Terminal, I had to manually `^C` my way out of it after it spat out the above-noted information.

**Comment by pthariensflame** [comment]
This is still a problem with the latest official Mac release, although it no longer hangs after crashing.

**Comment by pirminis** [comment]
I get this error in fresh macOS Sierra. FF worked perfectly fine in El Capitan.
