### ISSUE TITLE
FontForge Recovery did not recover glyphs

### ISSUE THREAD

**Issue by mynimi** [fontforge/fontforge#2686]
Hello
I've been working on a font for a few weeks now. All over the last week I created lookups, the glyphs for the full lowercase alphabet and about 30 ligatures and alternatives.
So today fontforge randomly crashed, I did not think about it, because I had saved my font just minutes before and it had just been sitting open while I was working on other things.
I shut the computer down, and when I opened FontForge back up, it told me that it did have a recovery of the file. So I clicked on it (really don't know why I did this now...) When I opened it though, I nearly had a heart attack. All but 6 glyphs are left. Lookups still there but I have no idea where the glyphs are.
I luckily generated the font yesterday in the evening so I can recover it, but just imagining that almost 20h of work are just gone because I clicked the wrong button would drive me crazy.
I checked the autosave folder, it is empty, so I did not find any possibility to recover anything that I had saved previously.

I run Windows 10 and that's my fontforge Version.
![fontforgeversion](https://cloud.githubusercontent.com/assets/6451964/14388457/8503b29a-fdae-11e5-9439-1533b17312dd.PNG)

I will just recreate my kerning now, but I am really interested if there is something you could do, if you don't have a backup anywhere. Is it really all lost?

**Edi**t: I think there was something wrong with my install. It kept crashing as soon as I changed anything. So I did reinstall and it is now working. But if there is any hidden way you can recover missing glyphs in case this happens again I would love to know about it.

**Comment by jtanx** [comment]
Hi @mynimi, this sounds very similar to #2681 - I have just updated the release, so please re-install FontForge (https://github.com/fontforge/fontforge/releases/download/20160404/FontForge-2016-04-04-Windows-r2.exe) and see if that fixes the issue.

**Comment by mynimi** [comment]
it did fix the crashing issue :)

**Comment by Acr515** [comment]
Bumping this thread because my FontForge just spontaneously crashed and the recovery wiped pretty much all my glyphs, save for the numbers and some symbols. I have the latest version; I downloaded it a couple days ago. This was my first font with this program and I lost several hours of work. Any way that I can prevent this from happening again or find my glyphs?
