### ISSUE TITLE
EPS import line join missing tangent

### ISSUE THREAD

**Issue by joojala** [fontforge/fontforge#2687]
The EPS importer handles line joins wrong. If you import EPS file with lines that have a round line join and the angle between the lines is > ~90 degrees, something weird happens. Here is a demo simple and quite minimal demo file:

```
%!PS-Adobe-3.0 EPSF-3.0
%%BoundingBox: 0 -1320 1200 110
%%Title: Error Demo
%%Creator: Janne Ojala
%%CreationDate:  2016-04-10
%%EndComments

6 setlinewidth 
1 setlinecap
1 setlinejoin

8 8 scale 

newpath
15 0 moveto
15 100  lineto
50 40 lineto %watch me
stroke

%%EOF
```

![Problem](https://cloud.githubusercontent.com/assets/18376200/14409203/15891e8c-ff16-11e5-9702-e9e5e9a2e7cf.png)

**Image 1:** Results of different angles for join

If on the otherhand you change the last _lineto_ statement to  `50 100 lineto` or 90 degrees of turn. You end up with a problem that is not nearly so visible, but still wrong tangents are not of equal length. When you make the same statement `50 110 lineto` or shallower than 90 degrees then all seems to be atleast visually correct.

**Comment by skef** [comment]
This works fine with the new Expand stroke code.
