### ISSUE TITLE
Extreme CPU useage fontforge on Mac

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#2707]
<img width="746" alt="screen shot 2016-04-21 at 12 07 44 pm" src="https://cloud.githubusercontent.com/assets/6846609/14707119/b0555bae-07ba-11e6-923c-bf40cf5c97b8.png">

My Mac is heating up and running the fans at full speed with latest binary.

**Comment by frank-trampe** [comment]
Attach gdb, break, and see where it's stuck.
