### ISSUE TITLE
Hoping to help update the Toolbar code

### ISSUE THREAD

**Issue by monkeyiq** [fontforge/fontforge#2712]
I see a number of issues (https://github.com/fontforge/fontforge/pull/2396, https://github.com/fontforge/fontforge/pull/2245) relating to new toolbar code. I am a C/C++ coder and would love to help get these great looking icons into FontForge if possible. My skills are not with drawing, though luckily for me there are many really nice icons already created for the new toolbar and design discussions have already occurred :)

It seems the most recent code is waiting in PR 2396.  @larsenwork other than looking at the formatting issue mentioned so that images.c is disturbed less what other actions are needed on this PR for you to be comfortable merging it? I'm happy to give the code changes some fresh eyes to try to see if there might be some unexpected issues and do a build/test to look for unexpected outcomes.

I thought about adding to existing threads/prs/etc but thought I'd create this one issue as a rally point for getting the toolbar merged.

**Comment by davelab6** [comment]
cc @pathumego

**Comment by JoesCat** [comment]
Hi @monkeyiq - long-time no see.
You might want to also think a little bit about 'a' 'h' too:
https://github.com/fontforge/libspiro/commit/0edbec32787d324cf156239044df3c41b8f7e4b6
I haven't added code to libspiro yet to activate it since I wanted to take a second look at test12
https://github.com/fontforge/fontforge/commit/c46c736da64fce0539cabca5793aff661dbbdf07
https://github.com/fontforge/fontforge/commit/8c9ebf62f6eb3f641050ec1cd5f0fdc1db171f8c

**Comment by frank-trampe** [comment]
We need two things in order to make this work and to do so without breaking other themes.
* Support for adjustable toolbar icon size (via the theme).
* Support for conditional toolbar icons.

**Comment by monkeyiq** [comment]
@frank-trampe cool. I'll take a look at implementing those features. I've now looked over the https://github.com/fontforge/fontforge/pull/2396/ just in case I was duplicating code updates. Seems we have the icons and just need the code :)

**Comment by monkeyiq** [comment]
Support for conditional icons opens up a few possibilities. Adding a block of conditional possibilities at the end of the toolbar is probably the simplest from an implementation perspective. It avoids having to work out what happens when something is turned off that is mid toolbar. For example if the magnify is turned off, do other icons shuffle up to take that space or is a gap left. Mode flips like the spiro are probably less confusing to users, as the other icons do not move just some get swapped when in spiro mode.

I'll have a dig around for context on what sort of conditional possibilities are the most interesting. @dave do you happen to recall some use cases for conditional icons?

**Comment by frank-trampe** [comment]
No. That's not what I meant. We need the ability to show different sprites for a given button depending upon whether the tool is selected or not.

**Comment by davelab6** [comment]
No but I hope Frank can speak up :)

**Comment by monkeyiq** [comment]
@frank-trampe cool. Really glad I clarified :)

**Comment by frank-trampe** [comment]
I ought to have waited until you built something.

**Comment by davelab6** [comment]
Right, instead of the simple edge drawing change that is used at the moment
(and which has become very hard to notice as physical pixel sizes have
gotten smaller)

**Comment by davelab6** [comment]
On 3 May 2016 at 20:09, Frank Trampe <notifications@github.com> wrote:

> I ought to have waited until you built something.
>

Don't be mean Frank :)

**Comment by monkeyiq** [comment]
@frank-trampe but then we would likely have code that doesn't get used

**Comment by davelab6** [comment]
On 3 May 2016 at 20:10, monkeyiq <notifications@github.com> wrote:

> @frank-trampe <https://github.com/frank-trampe> but then we would likely
> have code that doesn't get used
>
We could use it for only showing the Spiro toolbar icons when Spiro is
available which would be cool, but it isn't worth spending valuable time on
:)

**Comment by monkeyiq** [comment]
ok so selected images are now available https://github.com/monkeyiq/fontforge-fork/tree/2016/toolbar
note that the bright red/green bg is for testing, makes it obvious it is happening. 

![ff-selected](https://cloud.githubusercontent.com/assets/387108/15032620/2654f986-12a6-11e6-93b5-928e9b6a7278.png)


I've also turned off button borders in the code. They can be done in the theme images now if desired. I've always thought that they just create eye clutter, but that's just my personal thought on them.

assuming that we want old theme compatibility then I have to update to generate some frame on the non selected image for those that don't have a -selected.png file. (which will be all of them on an old theme). It might be simpler to have a small bash (or python for cross platform) script to make the -selected images and tell folks they should run that script to update their theme. Easy to pop up a dialog with this info, and keeps the actual fontforge code less cluttered with migration code. Ideally having a version number file in the theme would allow the migration script to handle newer versions as they are added. There is no version number now, so we could call that 0 and start at a VERSION file with 1 in it.

next up though will be fun funky huge icons (maybe 2.5x the size) in the toolbar to track down the places in the code that relies on the size being fixed and update that code.

**Comment by davelab6** [comment]
Agree about the clutter - awesome work!!!

I don't think we need the funky huge ones though?

Andreas has arranged a CraftingType.com workshop in Copenhagen this weekend
coming up, but I think its a bit too late to get this ready for then...

**Comment by monkeyiq** [comment]
the funky big icons are only for my testing. if it handles 300% sized icons ok then it will handle going from 24px to 28px or to 32px ok too :) or 16px if that floats your boat. It just makes the bugs more obvious for me to see. I'll revert the funky big new icons to the current ones once I'm fairly happy that the size updates work. Bringing in the images from https://github.com/fontforge/fontforge/pull/2396/ would be the next logical step. Those have a size of 26px instead of the existing 24px.

**Comment by frank-trampe** [comment]
Is it really that difficult to fall back? If the internal image for the selected mode is NULL, we would just use the normal mode image, right?

I can't check right now, but I think that we can already disable button borders by changing the colors in the theme.

**Comment by monkeyiq** [comment]
I already use the normal image if there is no selected image, but the normal image has no highlight. And without the borders you can't see what is selected. I'd have to make the code make the selected image a copy of the normal image and add some clicked border to it. It's not so hard to do, it's a question of where migration code should be placed knowing that it might be around for a long time.

**Comment by frank-trampe** [comment]
I don't think that's necessary. The theme will either have dual-mode buttons and make the relief invisible by adjusting those colors, or it will lack them and leave the fake relief intact. Right, @larsenwork?

**Comment by monkeyiq** [comment]
I'll merge this one once travis is done sniffing at it. https://github.com/fontforge/fontforge/pull/2720

**Comment by monkeyiq** [comment]
New look:
![newtb](https://cloud.githubusercontent.com/assets/387108/15089000/306749a8-143e-11e6-8d5e-59784de231c8.png)

**Comment by pathumego** [comment]
@monkeyiq I missed this!! Thank you!

**Comment by davelab6** [comment]
@pathumego are you able to build your own mac binary yet?

**Comment by pathumego** [comment]
@davelab6 Nope :( dying to get it running, is it working for you?

**Comment by davelab6** [comment]
My Macbook died so when i get a new one I will run through the instructions
:)

**Comment by frank-trampe** [comment]
See #2720.
