### ISSUE TITLE
Confusing GUI

### ISSUE THREAD

**Issue by ShalokShalom** [fontforge/fontforge#2717]
KaOS - FontForge 20150824-2

http://funkyimg.com/i/2bkHX.png

On the left side is the view of KFontView, on the right side FontForge.

Its my aim, to edit these weather icons, to be precise, give them colours.

Do i miss to install something?

The GUI looks very confusing to me and not as shown in the homepage:
https://fontforge.github.io/en-US/

**Comment by JoesCat** [comment]
Please read http://designwithfontforge.com/en-US/index.html

**Comment by ctrlcctrlv** [comment]
To get a similar view to KFontView, hit Encoding->Compact. Most likely the icons are somewhere around 0xE000, PUA...unless those icons have been encoded outside of the BMP?
