### ISSUE TITLE
QT

### ISSUE THREAD

**Issue by ShalokShalom** [fontforge/fontforge#2718]
From the FAQ:

"I realize now that that there are essentially two free widget sets that are far better at unicode support than mine. .. QT is written in C++, and, as I explain below, I don’t like C++, so that’s out."

C++ Qt != C++

https://youtu.be/ON0A1dsQOV0?t=10m31s

**Comment by JoesCat** [comment]
Appears to be more of a generale statement and unclear what this has to do with fixing or improving fontforge. Closing issue. Can be re-opened if more information given.

**Comment by ShalokShalom** [comment]
This is the reason for that issue here: https://github.com/fontforge/fontforge/issues/2717
