### ISSUE TITLE
Guides hidden when Foreground layer is active and Fill turned on

### ISSUE THREAD

**Issue by craxal** [fontforge/fontforge#2719]
**OS:** Windows
**FontForge Version:** ?.?.?

**Steps to reproduce:**
1. Open a glyph.
2. Select the Guides layer.
3. Draw several guide lines.
4. Switch to the Foreground layer.
5. Turn on Fill so that the glyph outline is filled.

**Expected:**
Guides remain visible.

**Actual:**
Guides disappear.

**Workaround:**
If I turn off Fill, the guides become visible again.

**Comment by mskala** [comment]
Probably related to #2581.  I get the idea that someone hated "Fill" and changed it to break other things so that it would become deprecated.

**Comment by jtanx** [comment]
I just tested latest master on Debian 8.5/KDE. Guidelines work with fill activated. Running VcXsrv locally on Windows and then FF (still on Debian) through X forwarding also works. But running latest master directly on Windows doesn't. Hmm.

**Comment by jtanx** [comment]
Ah, derp. @mskala you were right - #2581 did cause this issue (although I have no idea why the outline colour should affect the guideline colour). I had compiled the patched version on Debian and forgot to patch the corresponding version on Windows. So this is also fixed by #2788.
