### ISSUE TITLE
Mac + XQuartz: Right Click via Ctrl Not Working?

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2722]
Per https://twitter.com/SNugue/status/730337719981838337 when 3 button mouse emulation is enabled, ctrl + left click does not trigger a right click menu on any window in FontForge, using the latest versions of Mac OS X, XQuartz, and the most recent release of FontForge. 

To reproduce the behaviour, run the above configuration and hold ctrl and left click in the glyph window canvas or font window glyph table, and you should see a right click menu appear. 

This does appear when using the right click of an actual USB mouse, or the "two finger tap" on an Apple laptop trackpad. 

This is a problem because some people don't have Apple laptops with "two finger tap" trackpads, or like Sandrine, use Wacom tablets.

**Comment by davelab6** [comment]
While http://goesping.org/archives/2008/07/20/x11-tablet-support-on-mac/ said in 2008,

>  tablet taps don’t register as mouse clicks

This happens with my 2014 vintage macbok pro with a ctrl + left click so I think that's not relevant...

**Comment by wdh** [comment]
+1 on late 2013 MacBook Pro
