### ISSUE TITLE
cmap encodingRecord generated with broken (platformID, platformSpecificID)

### ISSUE THREAD

**Issue by TudorVisan** [fontforge/fontforge#2728]
FontForge version 20120731 running on Linux Mint 17.3 Cinnamon 64-bit, kernel 3.13.0-37-generic.

When non-BMP characters are present in a font FontForge generates a cmap (0, 10) encodingRecord. As far as I can tell from the documentation this combination of (platformID, platformSpecificID) does not exist. I believe the correct encodingRecord should have been (0, 4).

I have attached a font (LinLibertine_R.otf) that has what I believe are the correct encodingRecords. If you load this font in FontForge and generate another OpenType font from it you will see that the generated font has different encodingRecords. I have attached such a font (LinLibertine_R_generated.otf) .

Both attached files are in the following archive: [LinLibertine_R.zip](https://github.com/fontforge/fontforge/files/279317/LinLibertine_R.zip)

**Comment by fitojb** [comment]
> FontForge version 20120731

Have you tried the [latest FontForge release](https://launchpad.net/~fontforge/+archive/ubuntu/fontforge), version number 20160404?

**Comment by TudorVisan** [comment]
> Have you tried the latest FontForge release, version number 20160404?

I have updated to FontForge version 20160405. The problem persists. I have reattached the files, as generated with the new version.

[LinLibertine_R.zip](https://github.com/fontforge/fontforge/files/281509/LinLibertine_R.zip)
