### ISSUE TITLE
Please add Zesty build to PPA

### ISSUE THREAD

**Issue by justinbondlink** [fontforge/fontforge#2729]
It would be nice to add a build for Ubuntu Xenial 16.04 to the launchpad PPA.

Thanks!

**Comment by n7s** [comment]
see #2300 #229 and the work of Debian developers on https://anonscm.debian.org/cgit/pkg-fonts/fontforge.git

**Comment by PanderMusubi** [comment]
Also reported at Ubuntu https://bugs.launchpad.net/ubuntu/+source/fontforge/+bug/1595231 which is shipping a release from 2012! If the release from April is not included in the PPA, people on Ubuntu are thrown back to the 2012 release. :(

**Comment by PanderMusubi** [comment]
and see https://github.com/fontforge/fontforge/issues/2674

**Comment by rejhgadellaa** [comment]
+1

**Comment by Moilleadoir** [comment]
Is anything happening about this?

**Comment by frank-trampe** [comment]
The new release is available for Xenial. Not for Yakkety, though, since we ran out of Launchpad space.

**Comment by rrthomas** [comment]
Thanks very much, that's excellent!

**Comment by frank-trampe** [comment]
@rrthomas, it took a few tries. Something happened with libtool and some of the scripts like argz.m4 vanished. So we now run bootstrap with the `--copy` option for all Debian package builds.

**Comment by PanderMusubi** [comment]
How can the space at Launchpad get enlarged?

**Comment by frank-trampe** [comment]
Tough negotiation, I suppose. Ubuntu is profitable, FontForge is a deprived volunteer project, and Ubuntu makes money (indirectly) on FontForge, so I feel that the extra hosting ought to be free. If Canonical cannot accommodate, we'll explore other options.

**Comment by PanderMusubi** [comment]
If you create an issue on Launchpad regarding this, ask the FF devs en users to upvote it.

**Comment by frank-trampe** [comment]
I'm asking for an internal contact before I start making a public fuss. But that might be a decent plan.

**Comment by PanderMusubi** [comment]
If you have that connection it is indeed much better. Good luck and keep us posted.

**Comment by jre-wine** [comment]
This shouldn't be a problem since it's for a project, and not some random person.
IIRC you just have to ask a question at https://answers.launchpad.net/launchpad/

**Comment by frank-trampe** [comment]
I've gotten the limit boosted significantly, and FontForge is now available for Yakkety.

**Comment by mikhailnov** [comment]
Can you please make a build for Zesty 17.04 ?

**Comment by PanderMusubi** [comment]
Please, also start on Artful 17.10 or at least lay the ground work for it. The 24th of August is already the freeze for Ubuntu, see https://wiki.ubuntu.com/ArtfulAardvark/ReleaseSchedule
