### ISSUE TITLE
Improvements on building insctructions

### ISSUE THREAD

**Issue by PanderMusubi** [fontforge/fontforge#2736]
The file https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md could have the following improvements:
1. is `mkdir -p ~/src/github.com/fontforge;` and `cd ~/src/github.com/fontforge;` really necessary?
2. libspiro can also be installed on Debian an d Ubuntu with `apt-get install libspiro-dev` as the version in Ubuntu is of 2015-Jul-02, see https://github.com/fontforge/libspiro/blob/master/ChangeLog
3. libuninameslist can also be installed on Debian an d Ubuntu  with `apt-get install libuninameslist-dev` as the version in Ubuntu is of 2015-Jul-01, see https://github.com/fontforge/libuninameslist/blob/master/ChangeLog
4. before running installing fontforge, deinstall versions installed by package manager with `dpkg -P fontforge fontforge-common fontforge-extras` etc.

**Comment by JoesCat** [comment]
Hi @PanderMusubi, not everyone is running Ubuntu, and not everyone is running the latest distro.
What you indicate is good for a recent Debian, Ubuntu, Mint.....distro, but we still need to have instructions for users who use an older distro, or for users who want to jump ahead and use the latest HEAD.

In another issue, I believe you will be happy to know that there are several Debian Maintainers looking at making the current FontForge work as apt-get, and therefore you will benefit too with Ubuntu, making the install also very simple (see issue #2732 ).

If you see how to improve the instructions, but also keep it usable for users that have older distros, or distros that work a bit differently, please put together what you want to see improved or changed.
To help, you may want to search issues for problems, and use key-words like centos, bsd, apple, windows, and some less common OSes too, eg: irix, I think.

**Comment by PanderMusubi** [comment]
Thanks for your feedback and update on the packaging for Xenial.

I have made 2. and 3. more specific, for those who would like that. Personally, I like to build as less as possible, but if I have to, I do not want to build the depending projects as well as other software might need a specific version. Still wondering about 1. Number 4. I almost forgot myself.

**Comment by skef** [comment]
The install instructions were reworked and simplified.
