### ISSUE TITLE
FontForge new release!

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#2743]
Hello @davelab6, @frank-trampe, 
I have a question:
When is new FontForge version released? I am waiting for new icon-design.
The latest version was released on  04.04.2016.

**Comment by frank-trampe** [comment]
@typedesigner, the new release is pending. I expect it to arrive in about two weeks.

**Comment by JoesCat** [comment]
I'd like to update unicode from 6.3 to 9.0 before then, but it affects quite several files including the one I've got pending. ...therefore waiting for possible edit/changes to makeutype is_Ligatures.c ...likewise some caution required for some the latest PRs that affect a lot of files.

**Comment by frank-trampe** [comment]
Oh. I forgot about that one. I'll get back to it soon. It is a big changeset.

**Comment by frank-trampe** [comment]
As for other big ones, the gdk thing is not getting merged before this release. We'll stop accepting new non-bugfix changes a week or so before the release, so things ought to be stable by the cut date. And there's no firm deadline this time, so we can be as careful as we need to be.

**Comment by jtanx** [comment]
Linking potentially relevant issues: #2705

**Comment by jtanx** [comment]
Ideally for the new release - change [this line](https://github.com/fontforge/fontforge/blob/master/configure.ac#L37) in configure.ac to the release date, commit, then tag release, then run make dist to generate the release tarball.

**Comment by JoesCat** [comment]
Both configure.ac and Makefile.am need changing.
We need to follow CurrentRevisionAge instead of MajorMinorMicro.
More info here: https://github.com/fontforge/libuninameslist/issues/7

**Comment by JoesCat** [comment]
@jtanx ...also adding this...just noticed this comment now:
http://henrich2.rssing.com/browser.php?indx=10328685&last=1&item=23
"And maybe it'd be better to use date for versioning, IMHO (not 3.4.18 but 
20160621)."

I noted this earlier where Kevin (Fedora) made a similar note as well, but 
Werner's recent issue with CRA vs MMM in libuninameslist appeared like an 
important spot to commit to going back to a simplified yearmmdd without the 
leading Major/Minor/yearmmdd. Libspiro will preferably use a similar CRA fix 
when it's time to tag a new libspiro version too.

**Comment by frank-trampe** [comment]
I'm closing the issue since the release is done, but we can continue the versioning discussion.
