### ISSUE TITLE
Build Composite - regression in grave / acute positioning after 2012 version

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#2746]
Build Composite - regression in grave / acute positioning after 2012 version
I'm using the 2012 version installed on OS X 10.6.8, and the latest HEAD version. 

2012 version:
![screen shot 2016-07-20 at 11 57 39 am](https://cloud.githubusercontent.com/assets/58289/16991331/88f8415e-4e71-11e6-9f0e-49b6a6e95083.png)

2016 version:
![screen shot 2016-07-20 at 11 57 53 am](https://cloud.githubusercontent.com/assets/58289/16991330/88f50354-4e71-11e6-8328-a45c686a52ad.png)

I can generate a test case in Python if somebody wants to investigate further.
Thank you.

**Comment by jtanx** [comment]
@dimitre, yes please, a test case would be helpful. Thanks!

**Comment by frank-trampe** [comment]
@dimitre, ping.

**Comment by dimitre** [comment]
@jtanx @frank-trampe finally I've got the time to investigate and it was my fault. 
I'm now closing, thank you!
