### ISSUE TITLE
fontforge crashes when using pdf2htmlEX,is resolved by using branch of fork of fontforge-- why?

### ISSUE THREAD

**Issue by rorybudnick** [fontforge/fontforge#2751]
**Summary:**
When I run pdf2htmlEX on this pdf with the current version of fontforge, it segfaults.  _I believe this has to do with fontforge because it does not segfault and successfully converts when I use this branch of this fork of fontforge: https://github.com/coolwanglu/fontforge/tree/pdf2htmlEX_  I'm using Fontforge version 20160404 on an Ubuntu OS.

**Output of pdf2htmlEX --debug 1 test.pdf**
Add new temporary file: /tmp/pdf2htmlEX-xZD5TS/f2c9.woff
Add new temporary file: /tmp/pdf2htmlEX-xZD5TS/bg1f0.png
Install font 2ca: (23938 0) Helvetica-Bold
Embed font: /usr/share/fonts/type1/gsfonts/n019004l.pfb 714
Add new temporary file: /tmp/pdf2htmlEX-xZD5TS/__raw_font_2ca.pfb
em size: 1000
Add new temporary file: /tmp/pdf2htmlEX-xZD5TS/f2ca.map
space width: 0.278
_Add new temporary file: /tmp/pdf2htmlEX-xZD5TS/f2ca.woff
Segmentation fault (core dumped)_

When I try to attach the last mentioned font file(f2ca.woff) to this post, I get the error that the file is empty.
When I try to open it in the fontforge GUI: 
<img width="323" alt="screen shot 2016-07-22 at 11 49 42 am" src="https://cloud.githubusercontent.com/assets/6192780/17067882/c3aa1330-5002-11e6-8a57-0f7488b025bd.png">

**Comment by QGB** [comment]
hi @rorybudnick   
i got “Internal Error: assembly tables at wrong place” too
how to solve that

**Comment by ctrlcctrlv** [comment]
This is not a valid bug. Of course you are supposed to use @&zwnj;coolwanglu's fork of FontForge with pdf2htmlEX, which, besides, is no longer maintained.
