### ISSUE TITLE
Can't make font with 75582 glyphs! >3

### ISSUE THREAD

**Issue by Feay** [fontforge/fontforge#2752]
I am trying to save a font with 75582 in TFF or OTF formats and it wont let me, with some barrier to SNFT being 65535. PLease lift this barrer, my meta font has  75582 however i want them! (i've massed together noto+dejavu+code2000+code2001+code2002+TITUS cyberbit)
I do see only one pull request relating to this but it was to ADD a barrier to limit sntf to 65535! 

Font Forge Version: both 25may2016cigwn 15jun2015mingw
steps to reproduce: make a font with more than 65535 glyphs

**Comment by khaledhosny** [comment]
The limitation is in the SFNT format itself, not FontForge. There is no way around this, I’m afraid.
