### ISSUE TITLE
FontForge Yosemite for Windows

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#2764]
Hello @davelab6, @frank-trampe, @jtanx  when is new FontForge version released? I am waiting for new icon-design.
https://github.com/fontforge/YosemiForge
The latest version was released on 04.04.2016. Thanks.

**Comment by jtanx** [comment]
If you want that theme, you can install it yourself - see the [installation instructions](https://github.com/fontforge/YosemiForge#winlinux) on that project's page.

**Comment by jtanx** [comment]
I've added a new test build [here](https://sourceforge.net/projects/fontforgebuilds/files/i686/). It uses the icons from YosemiForge.

**Comment by typedesigner** [comment]
Thank you @jtanx ! 
Do you know when is new FontForge version released and uses the icons from YosemiForge ?
http://fontforge.github.io/en-US/downloads/windows/

**Comment by jtanx** [comment]
@typedesigner as in an official release? I don't know.

**Comment by typedesigner** [comment]
When is released the latest FontForge version? Is there a deadline?
