### ISSUE TITLE
Git history metadata

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2766]
I noticed that strangely George Williams isn't listed in https://github.com/fontforge/fontforge/graphs/contributors

I guess there is something funny going on with git commit usernames...

**Comment by davelab6** [comment]
Eg https://github.com/fontforge/fontforge/graphs/contributors?from=2001-04-22&to=2007-01-19&type=c shows only 4 commits, which can not be true :)

**Comment by jtanx** [comment]
You have to be a github user (and have your email tied to that user account) for it to show up.

**Comment by jtanx** [comment]
Unless George decides to create a Github account, this is 'normal' behaviour.

**Comment by davelab6** [comment]
OK, I'll email GWW and suggest he create an account to get credit for his great work :)
