### ISSUE TITLE
Issues with getting the PP repo on Mint 18

### ISSUE THREAD

**Issue by mxwoz** [fontforge/fontforge#2770]
When I do an install on Mint 18 I get 

_sudo add-apt-repository ppa:fontforge/fontforge_
**Cannot add PPA: '"Error reading https://launchpad.net/api/1.0/~fontforge/+archive/fontforge: (7, 'Failed to connect to launchpad.net port 443: Connection timed out')"'.**

I can get other parts of launchpad so its not a connectivity issue

Is there something clueless I am doing wrong?

**Comment by jtanx** [comment]
Sounds just like an issue with launchpad. It works for me on Ubuntu 16.04. Reopen if you're still having the same issue.
