### ISSUE TITLE
Substitution Glyphs based on presence of "space" or 2nd glyph of pair (2nd Class)

### ISSUE THREAD

**Issue by DLPI-GA** [fontforge/fontforge#2776]
I am extremely new to coding and FontForge. Couple of things: I am creating a cursive font for a language group that uses latin script. I am trying to continue the work of people that have come before and pen tooled every letter as oppose to using a TypeFace within their publication. That being said, there are some difficult letter-combinations that I need to recreate. 

For example. An _æ_ that is followed by a _k_  looks different from an _s_ , _v_ , or _b_ which is further more different than an _æ_ that comes after any CAPITAL letter. So, I have about 5 different æ's and need to figure out the coding to do it. Is it possible to code a substitution that swaps out the æ based on what comes after as opposed to before?

Additionally, since it is a cursive font, first letters of words have no beginning ligatures, is it possible to have "space" in Class 1 so that it can make the appropriate substitution for Class 2 glyphs?

**Comment by DLPI-GA** [comment]
Ok, so I saw that there is a glyph called "space", so that is solved. However, what about that initial instance of first character typed if it doesn't happen to be capitalized?

**Comment by JoesCat** [comment]
Please read through https://github.com/fontforge/fontforge/issues/2733 and register with the mailing list.
There are many eyes watching the mailing list, therefore potentially better chance of getting a reply on how-to do something.
Most issues here have to do with very specific bugs/fixes for the program FontForge itself, and.not how to use it.

Hope this helps clear any confusion.
Marking this as non-related.
