### ISSUE TITLE
kerning...

### ISSUE THREAD

**Issue by lailaps** [fontforge/fontforge#2779]
When it comes to kerning it's pain in the ass.
No documentation about kerning, only old and not working youtube videos.

I don't get it why does this program not have some useful tutorials?
I have so much space between each letter... this program isn't really user friendly...

Maybe only the developer knows how to use it correctly...

**Comment by frank-trampe** [comment]
Hi, @lailaps.

The issue tracker is for actual, specific deficiencies in FontForge, or its documentation. General queries, complaints, and hate mail are best accommodated on the [mailing list](https://lists.sourceforge.net/lists/listinfo/fontforge-users).

If there is something specific missing from [fontforge.github.io](http://fontforge.github.io/) or [designwithfontforge.com](http://designwithfontforge.com/), then post an issue explaining what specific kerning-related task you were unable to accomplish with the provided instructions.

I'm going to close this issue for now, but feel free to reopen with specifics.
