### ISSUE TITLE
typing unknown unicode characters in Metrics window causes immediate crash

### ISSUE THREAD

**Issue by RolfNoyer** [fontforge/fontforge#2797]
FontForge does not change the keyboard layout when you move to it from another application (even if this option is checked in System Preferences on the Mac).

Open Metrics Window, then press any key that inserts a glyph in a Unicode range not yet implemented in the Mac (e.g. u10B8x-10BFF).

FontForge always crashes instantly, with no warning. Upon reopening, one is occasionally asked to recover the file, but often there is no recovery of the file.

Workaround:

(1) Save constantly; crashes may happen at any moment.

(2) Make sure that before typing any character (including shortcut keys) that your keyboard layout is set to a “normal” keyboard. Do not depend on an automatic change of keyboard layout when clicking into Font Forge.

Using FontForge 20160402 on Mac Laptop running OS 10.11.6

**Comment by jtanx** [comment]
I can't seem to get it to crash. Can you outline the specific steps to get it to crash? e.g. Start FF, switch to XX keyboard layout, switch back, enter some keys, crash?

**Comment by frank-trampe** [comment]
And, since we might not be able to reproduce it, a stack trace would also be good.
