### ISSUE TITLE
Help with moving a glyph from one font to another

### ISSUE THREAD

**Issue by froggerjohn** [fontforge/fontforge#2801]
I have an issue that's conceptually simple, but have no experience editing TTF fonts.

I'm trying to use the card suit symbols (\u2660, etc) in an Android application, but Samsung phones force their color to black, regardless of what color I try to draw them. The outline (white) symbols do respect the draw color, but don't look as good. The ultimate goal is to be able to draw solid suit symbols in other colors.

Initially, I thought I would move the solid card suit glyphs to the outline glyph locations to bypass Samsung's force-to-black override. But when I open the font we're using (OpenSans-bold.ttf), it doesn't appear to include those characters at all.

So the next approach, is to try and copy over suit symbols from another font, such as this one:
https://www.pagat.com/com/cardsttf.html

The good news, is that if I open that font, copy the characters, and paste them into OpenSans-bold, I get the solid suits in the draw color I want. But the symbols are about half the size of what they should be. (They draw normal size if I draw directly from the original card font). And I don't know where that size mismatch is coming from, or how to fix it.

A secondary issue, is that when I "Generate Fonts" for TrueType, the resulting file is about half the size of the original, and I don't know what information I'm losing. The characters seem to look ok, but I need to be able to add the new card glyphs without losing anything significant from the original. Is that feasible?

Any help appreciated, thanks.

[update]
I found the "Font info" dialog, where the em size didn't match between the two fonts. Scaling the card font before the copy/paste fixed the size issue.

So the only remaining question is the differences in the export. I forgot one other piece of info, which is that the export throws errors of "Missing points at extrema" for afii10058 and 10029, and uni04c5 and uni0508.

**Comment by JoesCat** [comment]
Hi @froggerjohn,
Can you please ask this question again in the user mailing list instead?
There will be far more eyeballs reading the mailing list, plus questions like this help other novices and experts get better too. Here is the mailing list: https://lists.sourceforge.net/lists/listinfo/fontforge-users

Now closing this issue as "not a FontForge bug"
If you are indicating FontForge bugs, please reopen this issue.
