### ISSUE TITLE
Glyph substitution table not shown by FontForge

### ISSUE THREAD

**Issue by dennisr35** [fontforge/fontforge#2803]
I opened the font "Noto Sans Devanagari". The two Devanagari characters च् and छे are sustituted to a single character च्छे. This is a ligature which should be somewhere in the Font, but I cannot find it in FontForge.

**Comment by JoesCat** [comment]
At the moment, Fontforge has info up to unicode tables 6.3 and needs to be upgraded to unicode 9.0 (planned to be done soon), but I suspect the question you ask is more of a user-type of question and not one described as a defect/bug with FontForge itself.

Can you please ask this question again on the user mailing list?
https://lists.sourceforge.net/lists/listinfo/fontforge-users
There will be many more eyeballs reading the mailing list, and therefore a better chance to have your question answered.

...but, if you are pointing-out a defect with the program, please re-open this issue.
...or, if you want to help-out improve the program, I believe your knowledge of Devanagari would certainly be appreciated (in helping us improve the program).

Closing this issue as not a FontForge defect, but more of a user question.
