### ISSUE TITLE
"vcxsrv.exe has stopped working" error when start fontforge (crash)

### ISSUE THREAD

**Issue by saeedserpooshan** [fontforge/fontforge#2810]
i was running FontForge in windows 8.1 for several month. once upon a time, when i start running it, an error message appeared which says: "vcxsrv.exe has stopped working" and then nothing happens.
i uninstall and reinstall fontforge (different version) but it happens again.
what should i do now?

this is the output of interactive console:

C:\Program Files\FontForgeBuilds>fontforge
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 15:20 AWST 31-Dec-2014-ML-TtfDb-D.
 Based on source from git with hash: 6bfa9ed50dbea615f54c31cef7550906a47d15b1
no xdefs_filename!
TESTING: getPixmapDir:C:/Program Files/FontForgeBuilds/share/fontforge/pixmaps
TESTING: getShareDir:C:/Program Files/FontForgeBuilds/share/fontforge
TESTING: GResourceProgramDir:C:/Program Files/FontForgeBuilds/bin
trying default theme:C:/Program Files/FontForgeBuilds/share/fontforge/pixmaps/resources

**Comment by jtanx** [comment]
It sounds like VcXsrv has stopped working for you (and not FontForge), for some unknown reason.

Can you please try downloading and running this: https://sourceforge.net/projects/fontforgebuilds/files/patched-builds/FontForge-mingw-w64-i686-370627-appveyor-vcxsrv-1.18.3.0.7z

It's this build: https://ci.appveyor.com/project/fontforge/fontforge/build/1.0.61/artifacts with VcXsrv updated to 1.18.3.0 (the latest available).

**Comment by saeedserpooshan** [comment]
thanks @jtanx for your reply,
i download, unzip and run "run_fontforge.exe" as you mentioned, now the error message is as following:

vcxsrv.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-heap-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by jtanx** [comment]
I did a search and it suggests to install this: https://support.microsoft.com/en-us/kb/2999226

**Comment by saeedserpooshan** [comment]
i install that kb2999226. again an error occured when run the fontforge:

[Window Title]
VcXsrv windows xserver

[Main Instruction]
VcXsrv windows xserver has stopped working

problem details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	vcxsrv.exe
  Application Version:	1.18.3.0
  Application Timestamp:	57719911
  Fault Module Name:	ig4dev32.dll
  Fault Module Version:	8.14.10.1930
  Fault Module Timestamp:	4aba6fdd
  Exception Code:	c0000005
  Exception Offset:	0000d09f
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	4754
  Additional Information 4:	47547fafc9a3073a5bbe8e69322a8db5

**Comment by jtanx** [comment]
Hmm. It sounds like there's something going on between VcXsrv and your graphics drivers. As I don't develop VcXsrv, there's not too much I can do. You can try upgrading your graphics drivers to see if that helps. 

Also, you can try installing the full version of VcXsrv from here: https://sourceforge.net/projects/vcxsrv/

If you can run that version of VcXsrv (from the shortcut it makes in the start menu) without it crashing, then maybe there's something wrong with what I'm packaging.

**Comment by saeedserpooshan** [comment]
Good hint about graphics card. i had test some drivers with different versions in my system (although i re-install the original version atlast, but it seems that there is some problem with it). 

Now, i uninstall the display adapter driver from Device Manager and run the FontForge, it works without error! i should try to find best compatible driver for my pc...

Thanks man!

**Comment by jtanx** [comment]
Glad you found a solution!
