### ISSUE TITLE
Hi, I am trying to install caffe on my CPU (NO gpu) and Ubuntu – 14.04 and Python 2.7.6. I am getting below error  /caffe$ make pycaffe CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp /usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC /usr/local/lib/libpython2.7.a: error adding symbols: Bad value collect2: error: ld returned 1 exit status make: *** [python/caffe/_caffe.so] Error 1  I just followed the steps at : http://sunshineatnoon.github.io/How-to-install-caffe/  Please help me on this. I am totally stuck on my work.

### ISSUE THREAD

**Issue by ShibaPrasad** [fontforge/fontforge#2818]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
Hello, this is the issue tracker for FontForge. Please report issues about caffe here: https://github.com/BVLC/caffe/issues
