### ISSUE TITLE
Link static binary extension for Python

### ISSUE THREAD

**Issue by orklann** [fontforge/fontforge#2828]
I built from source to get the python extension of fontforge on macOS 10.11,  everything was ok, except that I can not `import fontforge` after copy the python extension into my new Mac. the python interpreter told me fontforge can not load some *.dylib.

So I wonder if we can build fontforge to generate a static python extension, but not a dynamic extension? (That's to say, I want  a fontforge.so which have no dependancies), Can I?

**Comment by jtanx** [comment]
Yes it can be done, but you'll need to merge #2815 to get it to work. In particular, you'll need this commit: e9ae3780428441b996293feec8f308afcd6301f7. See also #2353.

**Comment by aaron-elkins** [comment]
@jtanx thanks.

I failed to build fontforge on Mac OS X 10.11 with `--disable-shared` to build a static python extension, so I changed to build it from source with Homebrew.

And I get the python extension in `/usr/local/Cellar/fontforge/HEAD-8d13d4b/lib/python2.7/site-packages` which name is `fontforge.so`. And I can `import fontforge` in python, but `it seems this python extension still is not a static extension, it still dependents other dylib`.

P.S: `I did not merge #2815 yet, cause I don't know how to merge this commit in Homebrew.`

What I need is a static python extension, which does not dependent on other dylib, and can put it on my new Mac OS X without install a lots of dylib, is this possible?

**Comment by jtanx** [comment]
With the current make setup, I don't think it's not possible to build a static python extension. But why don't you just build it or install it via homebrew on your new mac?

**Comment by aaron-elkins** [comment]
I move the python extension to my new Mac is just for testing, and if anything runs ok, I can put this python extension and my python script together, and send it out for others to use.

But I don't want to put so much dylib together, there are so much...

**Comment by aaron-elkins** [comment]
Finally, I can build a static python extension by hacking homebrew, I just pushed my own hacking materials to my new [repo](https://github.com/aaron-elkins/fontforge-brew-static-build). 

Anyone interested in can have a check out.
