### ISSUE TITLE
Old gnulib.m4 makes autoconf complain about too early gl_EARLY

### ISSUE THREAD

**Issue by gioele** [fontforge/fontforge#2847]
When `autoconf` is invoked inside `bootstrap`, it will complain in various places that certain AC macros have been called in the wrong order. Examples:

```
configure.ac:188: warning: AM_PROG_AR was called before gl_PROG_AR_RANLIB
m4/gnulib-common.m4:252: gl_PROG_AR_RANLIB is expanded from...
m4/gnulib-comp.m4:34: gl_EARLY is expanded from...
configure.ac:188: the top level
```

```
configure.ac:188: warning: LT_INIT was called before AM_PROG_AR
/usr/share/aclocal-1.11/ar-lib.m4:15: AM_PROG_AR is expanded from...
m4/gnulib-common.m4:252: gl_PROG_AR_RANLIB is expanded from...
m4/gnulib-comp.m4:34: gl_EARLY is expanded from...
configure.ac:188: the top level
```

This problem has been fixed upstream in 2015 in the commit titled [gnulib-common.m4: fix gl_PROG_AR_RANLIB/AM_PROG_AR clash](http://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=f8fe25fab60e3c687a12446984bb475342956bb8). See also the discussion at <http://lists.gnu.org/archive/html/bug-gnulib/2015-07/msg00001.html>.

Would it be possible to update the gnulib m4 modules to a recent version that contains a fix for this problem?

**Comment by jtanx** [comment]
Sure! No idea how to do it though :smile:

**Comment by jtanx** [comment]
I think the problem's just in configure.ac itself. We just need to move the gl_EARLY call to before AM_PROG_AR.
