### ISSUE TITLE
Error in new font when typing "space" in GIMP

### ISSUE THREAD

**Issue by laurelp448** [fontforge/fontforge#2849]
Thanks for helping me with my font issue.  This is my first FontForge project, and I'm still dealing with the learning curve.  I created an OpenType font, and it works perfectly in Microsoft Word and Inkscape.  However, when I try to use the font in GIMP the spaces are replaced with the Unicode symbol for "space".  

![image](https://cloud.githubusercontent.com/assets/22261050/18609850/07759a9a-7cda-11e6-93f6-ca742773351e.png)

I've tried setting the width for the character, and it doesn't seem to change the output.  Does anyone have any suggestions?  Are FontForge fonts not compatible with GIMP?

**Comment by moyogo** [comment]
Try creating the space character in the font. It looks like it's missing from the font.

**Comment by laurelp448** [comment]
Thanks for the reply!  I've specified a width and created a point for the space character, is there anything else I need to do?

**Comment by laurelp448** [comment]
Thanks for the help, I added a glyph for the space and it shows up fine.

**Comment by Dapuva76** [comment]
I'm having the exact same problem, but setting the width does nothing. The encoding seems to be fine. Everything works but the whitespace. But what's this about setting a point for whitespace? I'm not sure every google page I found just tells me to adjust the width.
