### ISSUE TITLE
Layers window is broken in certain cases

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2852]
### When reporting a bug/issue:
- [x] Screenshot

    ![layers](https://cloud.githubusercontent.com/assets/5137410/18616060/df8fab24-7de7-11e6-8608-53dee988d5cd.png)
- [x] Windows 10 64 bit (but applicable to all)

Open Source Sans Pro (UFO). Layers window is not sized correctly. Even if I undock the palette and manually resize, it does not resize the layout to match new window size.

**Comment by frank-trampe** [comment]
If I recall correctly, there is an entirely different code path for the layer palette when the typeface has multiple exportable layers. It probably has not gotten the same attention as the normal layer palette.

**Comment by frank-trampe** [comment]
@jtanx, you closed this via #2855, right?

**Comment by jtanx** [comment]
Yep.
