### ISSUE TITLE
Travis cleanup

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2859]
Wishlist

* Simplify the Travis build procedure
    * Currently the Linux build essentially runs twice - the first time to compile/install FontForge, and the second when it runs distcheck. Not sure if we can do something about that.
* Make it make automated builds
* Make it possible to run automated Coverity builds

**Comment by typedesigner** [comment]
@jtanx When will new FontForge version released?
http://fontforge.github.io/en-US/downloads/windows-dl/

**Comment by frank-trampe** [comment]
@typedesigner, we try to keep issue discussions on-topic since they don't have subthread support. I would invite you to join the FontForge mailing list and to ask such questions there.

Since you asked, though, the new release is likely to arrive in the next two weeks. I was hoping to get it done sooner, but we have a lot of new pull requests that I want to get merged.

**Comment by typedesigner** [comment]
@frank-trampe Thank you for your reply, but i don't know how can i use mailing list. Is there an introduction?

**Comment by frank-trampe** [comment]
See [here](https://lists.sourceforge.net/lists/listinfo/fontforge-users).

**Comment by typedesigner** [comment]
@frank-trampe Thank you for link!

**Comment by jtanx** [comment]
After some head scratching due to dylib hell, I've made a bundler script that sort of works.

It produces a working app bundle, except that collab, even and Breakpad probably don't work. On the plus side, it only relies on Homebrew.

https://gist.github.com/jtanx/1565c653a10c6d01bfe2a3c8d5a184a4

1. Compile FontForge to a prefix - e.g.
     
     ~~~~~
     PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig/ CFLAGS="-g" ./configure --prefix=`pwd`/work  && make -j4 && make install 
     ~~~~~
2. Run the bundler:

    ~~~~~
    ./ffosxbuild.sh work/
    ~~~~~

**Comment by jtanx** [comment]
Oh yeah, I also have to compile with `listen_to_apple_events=false` otherwise FontForge never quits after all its windows are closed. It also doesn't appear in the dock. I don't know what to make of that.

**Comment by frank-trampe** [comment]
@jtanx, indeed, the main problem in building the present .app bundle is redoing the libraries, for which I wrote a set of commands last time. I am automating this process soon, and we can reuse that code for this builder as well.

These are my notes from last time. (It's not actually a script to be run in one piece.)
```
# Use a custom configure.
./configure --prefix=/Applications/FontForge.app/Contents/Resources/opt/local/ --with-cairo --enable-pixmaps-tango --x-includes=/opt/local/include --x-libraries=/Applications/FontForge.app/Contents/Resources/opt/local/lib --with-pythonbinary=/usr/bin/python --enable-gtk2-use --disable-silent-rules;
make;
# Comment out the DYLD_LIBRARY_PATH export in the FontForge launcher.
# Copy non-installed libraries for FontForge from the build directory.
# Copy all other dylibs from /opt/local/lib.
(cd /opt/local/lib && cp -pRP libgif.4.dylib libgif.dylib libjpeg.9.dylib libjpeg.dylib libpng16.16.dylib libpng16.dylib libtiff.5.dylib libtiff.dylib libuninameslist.0.dylib libuninames.dylib libpangocairo-1.0.0.dylib libpangocairo-1.0.dylib libcairo-gobject.2.dylib libcairo-gobject.dylib libcairo-script-interpreter.2.dylib libcairo-script-interpreter.dylib libcairo.2.dylib libcairo.dylib libgobject-2.0.0.dylib libgobject-2.0.dylib libpango-1.0.0.dylib libpango-1.0.dylib libpangoft2-1.0.0.dylib libpangoft2-1.0.dylib libpangoxft-1.0.0.dylib libpangoxft-1.0.dylib libXft.2.dylib libXft.dylib libfreetype.6.dylib libfreetype.dylib libfontconfig.1.dylib libfontconfig.dylib libSM.6.dylib libSM.dylib libICE.6.dylib libICE.dylib libreadline.6.2.dylib libreadline.6.3.dylib libreadline.6.dylib libreadline.dylib libspiro.0.0.1.dylib libspiro.0.dylib libspiro.dylib libharfbuzz.0.dylib libharfbuzz.dylib libgio-2.0.0.dylib libgio-2.0.dylib libglib-2.0.0.dylib libglib-2.0.dylib libxml2.2.dylib libxml2.dylib libiconv.2.dylib libiconv.dylib libintl.8.dylib libintl.dylib libX11-xcb.1.dylib libX11-xcb.dylib libX11.6.dylib libX11.dylib libXau.6.dylib libXau.dylib libXdmcp.6.dylib libXdmcp.dylib libXext.6.dylib libXext.dylib libXfixes.dylib libXi.6.dylib libXi.dylib libXrender.1.dylib libXrender.dylib libXt.6.dylib libXt.dylib /Applications/FontForge.app/Contents/Resources/opt/local/lib/;
# Redirect all of them as follows.
for tfile in *; do if [ -f "$tfile" ] && [ ! -h "$tfile" ] && [ `file "$tfile" | awk '{ print $2 }'` = "Mach-O" ] ; then for lfile in `otool -L "$tfile" | grep '^\t/opt/local/' | awk '{print $1}'` ; do install_name_tool -change "$lfile" `echo "$lfile" | sed -e 's|^/opt/local/|/Applications/FontForge.app/Contents/Resources/opt/local/|g'` "$tfile" ; done ; for lfile in `otool -L "$tfile" | grep '^\t' | head -n 1 | grep '^\t/opt/local/' | awk '{print $1}'` ; do install_name_tool -id `echo "$lfile" | sed -e 's|^/opt/local/|/Applications/FontForge.app/Contents/Resources/opt/local/|g'` "$tfile" ; done ; fi ; done ;
# Copy /opt/local/Library/Frameworks/Python.framework to /Applications/FontForge.app/Contents/Resources/opt/local/Library/Frameworks/Python.framework and fix all Mach-O files in that framework and the one in /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7 by running the previous fix-up command in each directory and subdirectory.

```

**Comment by jtanx** [comment]
Yeah, IMO the way that dynamic libraries are handled on OSX is insane. That's not even taking into account its handling of debugging symbols which I think you have to do something to to make it work on any computer. Actually I'm not even sure if you can do that or not.

I've found that dylibbundler helps to bundle all the required dylibs for a given executable, which is nice, except for when it misses out on certain libraries. So you end up still having to call `install_name_tool` to fix up anything that it missed.

The nice thing about using `@loader_path` is that you can specify the dylibs relative to each other, so that the bundle doesn't have to be in /Applications.

**Comment by jtanx** [comment]
Well, I wasn't happy with dylibbundler. It didn't fix all the paths that I wanted it to and it couldn't handle fixing multiple files at once where the files were in different folders. Furthermore it was *slow*.

I timed it and I think it took around 8 seconds for dylibbundler to just figure out the dependencies on the single fontforge binary. Even more time to patch it. Then its patching routine was dumb in that it ran install_name_tool for every single dependency that it found on every single file it was patching, even if that file didn't depend on that particular dependency.

So I wrote my own vesion - [lddx](https://github.com/jtanx/lddx). It's written in Go, which meant I could make it parallelisable fairly easily. I'm fairly confident that the dependency calculation is correct, although the collector/patcher still needs work (it's not robust - don't try running it again on the same file or on files with non-absolute dependencies).

Anyway - previously with dylibbundler:
~~~~~
time ./ffoldbuild.sh  work/

real 0m26.506s
user 0m9.211s
sys  0m15.027s
~~~~~

And dylibbundler's only patching *one* file.

With lddx:
~~~~~~
time ./ffosxbuild.sh work/


real 0m8.933s
user 0m3.705s
sys  0m12.581s
~~~~~~

And this is patching fontforge, fontforge-internal-collab-server (in libexec) and *the whole Python lib folder* (**all** the .so's depending on the Python dll) all at once, with no need to manually patch things up later. 

Calculating the dependencies on the single fontforge binary takes ~0.5 seconds - a 1600% decrease! I'm pretty happy.

**Comment by typedesigner** [comment]
@jtanx When will new FontForge version released with dylibbundler?
http://fontforge.github.io/en-US/downloads/windows-dl/

**Comment by jtanx** [comment]
What? It's got nothing to do with Windows. It's for OS X. This issue isn't even about the releases. Please restrict any discussion on that to #2743.

**Comment by jtanx** [comment]
I've made some good progress - see here: https://github.com/jtanx/fontforge/blob/travis/.travis.yml

All the user-specific scripts are gone. I've also switched it to a container-based build on Linux. 

One thing I would like to do is to get rid of the file generation for the unit tests, as this creates a prerequisite for FontForge to exist before the unit tests can be run. This is problematic because to run `make distcheck`, we essentially have to compile FontForge twice.

**Comment by jtanx** [comment]
We now have automated travis builds. Eventually the idea will be that you just update the `coverity` branch to match head and it should auto-generate a new coverity build. The only problem with it right now is that it runs the build for both Linux and OSX when in reality it should only run on Linux. So it's a good idea if you push to the `coverity` branch, to cancel the OSX build.
