### ISSUE TITLE
why is fontforge running slow

### ISSUE THREAD

**Issue by Adfont** [fontforge/fontforge#2860]
- Provide a general summary of the issue in the **Title** above.  
- Before you open an issue, please check if a similar issue already exists or has been closed before.
### Important

Mark with [x] to select. Leave as [ ] to unselect.
### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] (optional) Possible solution/fix/workaround
### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] (optional) Possible solution/fix/workaround

**Comment by frank-trampe** [comment]
Hi, @Adfont.

If this is a serious inquiry rather than just trolling, I would suggest consulting the check-list in the issue template that you submitted and including a description of the problem. If this is just trolling/flaming, close the issue, [subscribe to the mailing list](https://lists.sourceforge.net/lists/listinfo/fontforge-users), and do your thing there.

**Comment by Adfont** [comment]
Hello Frank,

Thank you for your reply, I have looked on the checklist and can not find a solution. My problem is when I try working from a scanned image the pen tool runs really slow, I didnt start to think it were my system but other creative software's such as adobe CC run fine.



________________________________

**Comment by jtanx** [comment]
@adfont what operating system are you using? Did you autotrace the image? Just how large is the scanned image?

**Comment by frank-trampe** [comment]
Pinging @Adfont.
