### ISSUE TITLE
Feature Request: The Harmonizer

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#2883]
@jtanx @frank-trampe @davelab6 
"The Harmonizer helps design nice, visually consistent curves while it retains the shape as far as possible." 
https://remix-tools.com/fontlab/tutorials

That would be very good futures for FontForge, Windows.

**Comment by frank-trampe** [comment]
I can't figure out precisely what it is from the picture, but it might be equivalent to FontForge's Spiro mode.

**Comment by frank-trampe** [comment]
I'm closing the issue. Even if Spiro is not equivalent, we're unlikely to add a third drawing mode anytime soon.
