### ISSUE TITLE
Can't open .sfd files

### ISSUE THREAD

**Issue by raphaz** [fontforge/fontforge#2892]
FontForge doesn't let me open several .sdf files I created in the last couple days. 
I was able to open and close them before. 

I crashed a couple times when working in FontForge yesterday and today, usually when zooming in or moving points, on rather random occasions. 

When trying to open the files FontForge is asking to recover it. When I click "yes" or "yes to all" nothing happens. If I click "skip for now" an "Untitled1.sfd" glyph window opens (not the actual file); when I then open the respective file through the file/open dialog from here I go through the same recovery routine like mentioned above, to no avail.

Is there any way I can recover my work from the last couple days?!

Thank you in advance!
Rapha

**Comment by frank-trampe** [comment]
@raphaz, are you saying that the old release handled them correctly and the new release crashes? Or that the files got corrupted somehow and cause crashes?

What version of FontForge are you using, and on what platform?

**Comment by raphaz** [comment]
Sorry, I guess I wasn't specific enough.
I can't open .sdf files anymore, the same files I was able to open yesterday and a couple hours ago today. 
This happened after FontForge crashed a couple times.
I didn't change or update XQuartz or FontForge since I last opened the files.

macOS Sierra 10.12X; Quartz 2.7.9 (xorg-server 1.17.4); FontForge 20160402 

I just restarted the Mac and I still can't open any .sdf files at all.

When I open XQuartz I get a xterm window with bash-3.2$

![ffopendialogue](https://cloud.githubusercontent.com/assets/22640974/19120814/405e08c6-8af2-11e6-8b4b-0b2371d12923.jpg)
![ffopenoptions](https://cloud.githubusercontent.com/assets/22640974/19120812/404d5bf2-8af2-11e6-8667-c6fb9c50044a.jpg)
![xquartz_xterm](https://cloud.githubusercontent.com/assets/22640974/19120813/405a574e-8af2-11e6-8fa6-0ce408e0610c.png)

**Comment by frank-trampe** [comment]
Your autosave files might be in `~/.config/fontforge/autosave`. See what's in there.

Do you absolutely need to recover the files? If so, you'll probably need to provide a copy of your autosave directory. If not, just move or delete it, and you ought to be able to open your original files.

If you can get FontForge to crash consistently, we would also appreciate getting the specific steps necessary to make it do so.

**Comment by raphaz** [comment]
Strangely enough I managed to open a couple older files and one of today's files through the FF open dialog but I still can't open any of the files I worked on the last couple hours today.

It's crucial for me to open these, yes. I saved these before I crashed. 
There really wasn't any detectable pattern causing the crash other than working in the single glyph window moving points and curves zoomed in closely.

Let me check the autosave directory as suggested. But since I manually saved the respective files...

**Comment by raphaz** [comment]
Not sure if I understand the path ~/.config/fontforge/autosave

**Comment by frank-trampe** [comment]
`~` is an abbreviation (understood by the shell) for your home directory. It expands to something like `/Users/raphaz`. If you open a new terminal window, the shell ought to start in that directory, so just type `cd .config/fontforge/autosave` (or `cd ~/.config/fontforge/autosave`) and press enter, and, if that succeeds, type `ls` and press enter in order to see the contents.

If you saved whatever work you want to recover, it seems that the failing recovery process is just an obstacle, so you'll want to start with a new autosave directory. Close FontForge and your prior terminal and try running this in a new terminal instance.

`mv ~/.config/fontforge/autosave ~/.config/fontforge/autosave-20161005`

Then reopen FontForge.

**Comment by raphaz** [comment]
Sorry but I'm still not sure how to get to these autosave files. See screenshots (terminal to the left, top directory and autosave search to the right). 
Thank you for your help and patience!

**Comment by raphaz** [comment]
![autosave](https://cloud.githubusercontent.com/assets/22640974/19122486/abb6393a-8af8-11e6-89d9-6b77019f3999.jpg)

**Comment by frank-trampe** [comment]
The exploration in the Finder is not in the right place. By default, it will not even show directories that start with `.`.

In your still-open terminal, type `ls` and press enter to see what files are autosaved. You can then `cd ..` to move the next directory up and move the directory out of the way by running `mv autosave autosave-20161005`.

**Comment by raphaz** [comment]
Btw. FontForge is usually not visible as an open app when I cycle through apps, I usually only see XQyuartz as an open application, and the respective FontForge window. But FontForge never appears as an open application. Is that normal?
![ffopen](https://cloud.githubusercontent.com/assets/22640974/19122644/6f20438e-8af9-11e6-9f05-0cbde746b48c.jpg)

**Comment by raphaz** [comment]
Sorry but still not sure what I'm doing here and if I'm doing it right?
![terminal](https://cloud.githubusercontent.com/assets/22640974/19122854/65ecfd56-8afa-11e6-9252-86f93622002b.jpg)

**Comment by frank-trampe** [comment]
@raphaz, it isn't optimal but it is the way it works right now on the Macintosh. Apple removed support for the compatibility layer that we used for Cocoa integration before. We're working on a long-term solution to that an to the XQuartz dependency.

**Comment by frank-trampe** [comment]
@raphaz, you forgot a space after `cd`. It's `cd ..`. So run `cd ..` and then run the `mv` command.

**Comment by raphaz** [comment]
Ok, did that. Thanks for the handholding! I'm not a programmer...
![terminalagain](https://cloud.githubusercontent.com/assets/22640974/19122988/e7c68d56-8afa-11e6-9aa5-06d84fa560bc.jpg)

**Comment by raphaz** [comment]
Still can't open any of these files, nothing happens, as if they don't exist.
Looks like I lost a couple hours worth of work and have to deal with it. Very frustrating!
How likely is it for this to happen again? What can I do to prevent that (I'm saving on a regular basis).

**Comment by raphaz** [comment]
Maybe FontForge is not working for me... I can't afford wasting precious hours with repeating crashing issues.

**Comment by raphaz** [comment]
Thanks for your help though!

**Comment by frank-trampe** [comment]
@raphaz, if you're willing to provide the files, we'd be happy to take a look and to try to fix the problem.

**Comment by raphaz** [comment]
Thank you! I'd appreciate that! 
How do I send the files to you though? It won't let me attach .sdf files here.

**Comment by frank-trampe** [comment]
Maybe Dropbox or 4shared?

**Comment by raphaz** [comment]
https://www.dropbox.com/sh/kez78pvr5l57sek/AAClHlydDudLob-nFfYZrBVGa?dl=0

**Comment by frank-trampe** [comment]
There are not any characters, which is causing FontForge to fail to load an encoding and then to crash. This is a problem I would like to fix. But are there supposed to be characters?

**Comment by raphaz** [comment]
I noticed that when I open sdf files (the ones I can) it first opens an empty file with no characters at all (a new file I guess?). If I then go through the FF open dialog and open the same file via directory  it opens the actual file with all the characters. Maybe try that? Maybe a Mac thing too?

**Comment by frank-trampe** [comment]
Yes. Opening files from the finder is a bit shaky, so using the open dialog is the right way to do things. But the files that you uploaded are completely broken. It looks like FontForge crashed part of the way through writing the grid. If you can consistently make it crash somehow, let us know the steps so that we can fix the problem.

**Comment by raphaz** [comment]
Well, I can't open these files so I wouldn't be able to observe when they're crashing.
Should a crash occur with the current files I'll report.

**Comment by raphaz** [comment]
Should that happen again though I'm not sure if I can keep working with FF. 
Anyhow, for now back to square one. Min. a days worth of work lost, plus some time-consuming design tweaks. Maybe open-source is not the way to go for me.

Thanks for trying to fix and help!
Rapha

**Comment by pathumego** [comment]
@raphaz If you save regularly in case of a crash you can just skip the recovery and open the files. Until we figure out what's happening it would be the best thing to do. I use FF daily and because I'm used to save often I actually rarely use the recovery, in case of crash.

**Comment by frank-trampe** [comment]
@raphaz, FontForge may have an edge case that your workflow happens to touch, but I think that you will find that FontForge is more stable than most typeface editors.

**Comment by frank-trampe** [comment]
@pathumego, the problem here is that FontForge is crashing during the save process, so it replaces a valid file with an invalid one.

@raphaz, until we identify the source of the mid-save crash, I would suggest that you not save over the original file and instead use a version number that you increment each time.

**Comment by jtanx** [comment]
@raphaz have you tried upgrading to the latest release? I see you're using 20160402. @frank-trampe, are we sure this isn't already fixed by 3b18b01ad983e5b4fd6fef6de0cd6010e3bf165e?

**Comment by frank-trampe** [comment]
@jtanx, it crashed for me on the newest release at fontview.c:7322.

**Comment by jtanx** [comment]
sample file no longer exists.
