### ISSUE TITLE
Ruler tool measurements misaligned [linux]

### ISSUE THREAD

**Issue by n8willis** [fontforge/fontforge#2895]
![ff2016-10-ruler-number-glitch](https://cloud.githubusercontent.com/assets/2192132/19186239/3d5b2208-8c7d-11e6-9ea8-a7858fbc3573.png)

Started working with the new October '16 release on Ubuntu (Xenial / 16.04). When using the ruler/measure tool in a glyph window, the segment-measurement numbers are not aligned to the measurement line; they are offset by a significant number of pixels (this is what's depicted in the screenshot attached).

So far, this is reproducible for me on any glyphs that has actual contours (components are also triggering an offset, it seems, but that's less of an issue up front). The numbers are supposed to sit next to the line segments that the tool measures; as it is, you can sort of work out which number goes with which measurement -- unless they are tightly spaced, in which case the numbers crowd over each other and may not be readable.

**Comment by jtanx** [comment]
Hmm. Odd. The ruler code hasn't really been touched since the last release, except to re-enable the expose call for the popup window (the yellow box). The ruler also appears to work correctly on Windows.

**Comment by n8willis** [comment]
@jtanx I'm using the PPA version; it would seem that that is worth testing then.  Since I can't recommend doing local source builds to regular users, that's a bit lower priority of a testing condition IMO.

**Comment by jtanx** [comment]
Ah yes, I've just tried the PPA build and I can reproduce the issue. That is a strange one.

**Comment by jtanx** [comment]
Ugh, it's optimisation dependent. Compiling with `-O0`, the problem disappears. I'm guessing at `-O2` or whatever the default optimisation level is, the bug crops up.

**Comment by jtanx** [comment]
Yep, so this isn't actually a new bug or anything, it's just that for whatever reason, the compiler in 16.04 has made this bug apparent with the optimisation levels it's compiling with.

**Comment by frank-trampe** [comment]
@n8willis, we'll wait a week or two for Xenial and Yakkety bugs to drift in, but I'll try to do another minor release for Launchpad sometime soon.

**Comment by frank-trampe** [comment]
@n8willis, I just pushed new packages to Launchpad.
