### ISSUE TITLE
Cannot configure fontforge with --enable-type3 option

### ISSUE THREAD

**Issue by jrbastien** [fontforge/fontforge#2898]
Hi,
I'm working on the French translation of FontForge and want to enable Multi Layered Editing of Type3.  From the documentation here: http://fontforge.github.io/en-US/documentation/interface/multilayer/, it tells me to configure fontforge with the --enable-type3 option

I get this error when doing this on Ubuntu 16.04:

./configure --enable-type3
configure: WARNING: unrecognized options: --enable-type3

I'm using the master branch forked on Sept. 24.

Has type3 support been removed intentionally or Am I doing something wrong?
### Important

Mark with [x] to select. Leave as [ ] to unselect.
### When reporting a bug/issue:
- [ ] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [X ] Steps to reproduce the behavior 
- [ ] (optional) Possible solution/fix/workaround

**Comment by frank-trampe** [comment]
I think that such support is included by default. What happens if you just install from the FontForge Launchpad repository?

**Comment by jrbastien** [comment]
Installing the launchpad release (on a system where I haven't compiled it before) gives me a broken package error:

Les paquets suivants contiennent des dépendances non satisfaites :
 fontforge : Dépend: fontforge-common (= 20161005-0ubuntu1~xenial) mais il n'est pas installé

 But curiously it still can start.  However, this is the same error.  You can't double click on the layer to get the layer dialog nor you can select "Type3 Multi layered font" in Element-->Font Info-->Layer tab.

**Comment by jrbastien** [comment]
I have resolved the dependencies issues I had by purging the fontforge-extras that were previously installed.  So I have now a clean installation using the ppa from launchpad.

Unfortunately, still no type3 support.

**Comment by jrbastien** [comment]
Is there anything else I can do to help resolving this issue?  I was thinking of comparing old versions with the latest one to see where the --enable-type3 got lost.  But I'm not sure how I can do this with Github.

**Comment by frank-trampe** [comment]
@jrbastien, since you're able to build FontForge, you could use the git bisect feature between current master and whatever build worked for you. Once that narrows the field to a commit, we can look at it.

**Comment by jrbastien** [comment]
Searching for a good commit made me look to the first one on October 13th 2014.  Still no enable-type3 option in configure.  I'm afraid the last time it worked FontForge code was not hosted by Github. 

If that can help, I see reference to this option in:

fontforge/Packaging/debian/cp-src/rules
fontforge/Packaging/redhat/m4/rpm.spec
fontforge/debian-old/rules

**Comment by jtanx** [comment]
I don't know much about type 3 fonts, but on Windows, I can select `Type 3 Multi layered Font` from the Font info dialogue.

**Comment by jrbastien** [comment]
@jtanx , interesting.  Two questions:

1.  How was FF installed on Windows?
2.  What font are you using to test with?

**Comment by jrbastien** [comment]
@jtanx, never mind my question.  I did not see your first edit.  I have made further test and I discovered that I cannot edit TrueType font as type 3 fonts.  OpenType, CMap, Adobe Type1 can all be converted to multi-layered fonts.

What is weird is that the font I have opened (and created myself) is an sfd file, so theoretically it is not truetype until I save it as such.  Perhaps, this is another property I have selected that prevents editing it as Type3?

If I can figure it out, I will update the documentation.

**Comment by ahyangyi** [comment]
@jrbastien Would the difference between quadratic Béziers and cubic Béziers be the issue? Typical truetype font uses the former, while a typical opentype font or Adobe Type 1 font uses the latter.

**Comment by jrbastien** [comment]
@ahyangyi , you are right on the spot.  Selecting "All layers cubic" makes the multi-layer option available again.

Thanks for all your help ( @frank-trampe, @jtanx , @ahyangyi ).  I will certainly update the documentation here https://github.com/fontforge/designwithfontforge.com

![quad_cuves](https://cloud.githubusercontent.com/assets/627071/19856079/559664e8-9f4e-11e6-99f6-9ad52388537f.JPG)

![cubic_curves](https://cloud.githubusercontent.com/assets/627071/19856087/5b0d93ec-9f4e-11e6-84b9-5c7a7aa9d86d.JPG)

**Comment by jrbastien** [comment]
A question for you all (@frank-trampe, @jtanx , @ahyangyi).  I have looked at the project 

https://github.com/fontforge/designwithfontforge.com

And could not find the multi-layer documentation.  I rather found it in:

https://github.com/fontforge/fontforge/blob/master/doc/html/multilayer.html

If I make the changes to this file and submit a pull request, how will the web site documentation gets updated?

**Comment by frank-trampe** [comment]
@jrbastien, most of the challenge is just finding where in the site to put the information and then converting it to markdown.

The designwithfontforge site (which we do manage) is separate from [the main FontForge site](https://fontforge.github.io), and I'm not sure exactly where to put this. @davelab6?

**Comment by jrbastien** [comment]
@frank-trampe , sorry if I'm confusing you.  I thought originally that this page was coming from "Design with FontForge because it uses a similar layout.  But in reality, it is accessible from the FontForge main site:

https://fontforge.github.io/en-US/ --> https://fontforge.github.io/en-US/documentation/ --> http://fontforge.github.io/en-US/documentation/interface/ --> http://fontforge.github.io/en-US/documentation/interface/elementmenu/ --> http://fontforge.github.io/en-US/documentation/interface/fontinfo/ --> http://fontforge.github.io/en-US/documentation/interface/multilayer/

So my question remains:  if I update the doc in this project, will it update the web site?

**Comment by frank-trampe** [comment]
It's in [its own repository](https://github.com/fontforge/fontforge.github.io/).
