### ISSUE TITLE
Crashes when running --lang=ff script to export SVG files

### ISSUE THREAD

**Issue by robmadole** [fontforge/fontforge#2900]
FontForge version:
- PPA package for Ubuntu Xenial (20161005)
- Compiled from source on Ubuntu 16.04 (20161005)
- Compiled from source on Ubuntu 14.04 (20161005)

**The following [gist](https://gist.github.com/robmadole/ab4b3e982502cdb0b0070c1b8b266681) provides the script and OTF file.**

Behavior:

Running `fontforge -lang=ff -c 'Open($1); SelectWorthOutputting(); foreach Export("%n.svg"); endloop;' FontAwesome.otf` results in FontForge crashing. (Crash output found in Gist)

In version 20160404 this crash does not occur.

**Comment by jtanx** [comment]
I think this might be related to #2897.

**Comment by frank-trampe** [comment]
I can confirm that #2897 fixes the problem. We'll do a new minor release soon.

**Comment by robmadole** [comment]
Yep, this fixes the problem for me as well.
