### ISSUE TITLE
File descriptor leak in fontforge 2.0.20161004

### ISSUE THREAD

**Issue by davidhedley** [fontforge/fontforge#2903]
There is a file descriptor leak in fontforge 2.0.20161004. When converting a large number of fonts you will eventually run out of open file descriptors.

The problem is in"redohead" in tottf.c

If you redo the head, the previous file handle is not closed. You need to change 

```
static void redohead(struct alltabs *at) {
    at->headf = tmpfile();
```

to

```
static void redohead(struct alltabs *at) {
    if (at->headf) fclose(at->headf); // file descriptor leak
    at->headf = tmpfile();
```

**Comment by frank-trampe** [comment]
@davidhedley, is there any chance you could submit a pull request?

**Comment by davidhedley** [comment]
Done
