### ISSUE TITLE
TTF Font appears empty in FontForge

### ISSUE THREAD

**Issue by pysaumont** [fontforge/fontforge#2906]
Hi,

I am trying to open a TTF Font called JazzFont in order to modify some characters. Once open, all characters are empty. The font works fine however in many applications. Is there some restriction about which TTF can be opened, and what should I check to understand what is happening?

Thanks.

**Comment by jtanx** [comment]
* Do you have a link to this font?
* Version of FF?
* What OS?

There was an issue template there that would have greatly helped if you had filled it out. Thanks.

**Comment by pysaumont** [comment]
Sorry for not having used the template.

FontForge version : 20:55
OS : Windows and Linux
Expected behavior : I expect to see the individual characters
Actual behavior : No characters are displayed
Steps to reproduce the behavior : open the font file
Possible solution: none at this time

The font is a commercial one from Sigler Music Fonts, and I got it with Finale music notation software, so I don't think I can provide a link and share it publicly. The encoding is described here:

[JazzFont encoding](https://usermanuals.finalemusic.com/Finale2012Win/Content/Finale/Jazz_Font.htm)

I tried it with several word processors and it works fine, at least for some characters. I would like to change the aspect of some characters, but when opened with FontForge, the characters do no show.

I tried to use the font with PdfBox (Apache Java library), and I could not access characters, whatever code I tried. I opened it with iText (another Java Library) and found that I could use the characters, but some have high codes (> 3000). I had to print characters up to 8000 in order to find all of them.

As a substitute, I tried to use the LilyJazz OTF font. When opening this font, I can see the alphanumeric characters and usual symbols, but none of the special music symbols. The LilyJazz font is downloadable on the [Lilypond user list](http://lists.gnu.org/archive/html/lilypond-user/2013-03/msg00647.html) at the end of the message

Thanks.

![capturejazzfont](https://cloud.githubusercontent.com/assets/10126283/19348807/082c4ef4-9150-11e6-94ff-c3cc44728c97.PNG)

**Comment by jtanx** [comment]
Hmm that is a strange one. So even if you go `Encoding->Compact` no glyphs are displayed?

**Comment by jtanx** [comment]
Ah. I think I found a copy of it. The glyphs are in the MS Symbol area, so it's probably a symbol encoded font. One of those non-standard types.

**Comment by pysaumont** [comment]
Thank you very much, that works! By the way, there are many warnings displayed saying that glyphs are mapped to wrong values. But these messages are in French, which is my local language, and this makes difficult to share problems (such as waring messages) or to search similar probblmes on Internet. Is there a way to have the interface in English on a French version of Windows?

**Comment by jtanx** [comment]
I'm glad it (sort of) works! To force English, it involves a little bit of work:

1. You will need to open `C:\Program Files (x86)\FontForgeBuilds\fontforge.bat` (or equivalent), usually using Notepad as Administrator (Start menu -> search for Notepad -> Right Click -> Run as Administrator)
3. Search for the line that says `::set LANGUAGE=en` and remove the `::` at the front of the line.
4. Save the file.

**Comment by skef** [comment]
This appears to be resolved.
