### ISSUE TITLE
Missing dependency check on glib development header

### ISSUE THREAD

**Issue by copyninja** [fontforge/fontforge#2907]
Hi,

While checking reverse build depends of fontforge in Debian, it was noticed that there is no check for glib development header and hence glib development header dependency was not included. The bug in question is [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835165). File `ffglib.h` references `glib.h` and `glib-object.h` and I did not realize until the maintainer of package told its fontforge which is missing dependency.

So I think there should be atleast `AC_CHECK_HEADERS([glib.h  glib-object.h])` declared in configure.ac to make sure the dependency is not missed.

**Comment by jtanx** [comment]
It does check for GLIB here: https://github.com/fontforge/fontforge/blob/master/configure.ac#L363

Although I'm not completely sure that it's configured as a hard dependency (but it should be). It's also implicit through the Pango dependency.

**Comment by copyninja** [comment]
But does it check for development header? I don't think so because then my
build on clean chroot would have failed. Development header is necessary
for other package which uses fontforge development header

**Comment by jtanx** [comment]
Yes it does. PKG_CHECK_MODULES is a very standard way of checking for the dev headers.

**Comment by copyninja** [comment]
Ah okay now I got it since [libpango1.0-dev](https://anonscm.debian.org/cgit/pkg-fonts/fontforge.git/tree/debian/control#n34) is present `libglib2.0 gets pulled automatically as you mentioned. But libglib2.0-dev is not pulled in by `libpango1.0-dev` instead its pulled in by `libcairo2-dev` so check went fine and it compiled.  But I missed it in `libfontforge-dev` as I did not explicitly list it in Build-Depends (it is calculated at run time by d-devlibdeps tool).

But I think it should be configured as hard dependency in configure.ac just to make sure distribution people won't miss it!.

**Comment by jtanx** [comment]
Yeah it's just a simple fix of erroring out if PKG_CHECK_MODULES finds that it's not available.

**Comment by jtanx** [comment]
I take back what I said. The default behaviour is to error out if it's not found:

~~~~~
checking for GLIB... no
configure: error: Package requirements (glib-2.0 >= 2.6 gio-2.0) were not met:

No package 'glib-2.0' found
Package 'glib-2.0', required by 'gio-2.0', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLIB_CFLAGS
and GLIB_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
!!! Build failed at: FontForge configure
~~~~~

So configure works fine as far as I can see.

**Comment by jtanx** [comment]
Perhaps it's just the metadata on the Debian packaging that's wrong. glib is a hard dependency.

**Comment by copyninja** [comment]
@jtanx Thanks for confirming. How did you test it just removed libglib2.0 library or you removed the header package (libglib2.0-dev)?. If you tested just removing library can you also check by removing the header package only?.

Meanwhile I will add it as hard dependency in fontforge to get updated dev dependency on libfontforge-dev

**Comment by jtanx** [comment]
I just renamed `glib-2.0.pc` to something else so that pkgconfig couldn't find it.

**Comment by jtanx** [comment]
If you want to check where pkg-config is resolving things to, run in your chroot:

````sh
pkg-config --debug glib-2.0
`````

**Comment by copyninja** [comment]
@jtanx I just added libglib2.0-dev as `Build-Depends` and uploaded new version of package but `pdf2htmlex` still fails here is the [build log](https://angband.pl/tmp/ff12/failed/pdf2htmlex_amd64-2016-10-15T14:35:51Z.build) any idea why `ffglib.h` can't find `glib.h`

**Comment by jtanx** [comment]
You'll notice that configuration line doesn't have something along the lines of `-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include`.

~~~~~
/usr/bin/cc   -I/<<BUILDDIR>>/pdf2htmlex-0.14.6+ds/src -I/usr/include/poppler -I/usr/include/fontforge  -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/pdf2htmlex-0.14.6+ds=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wall   -o CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o   -c /<<BUILDDIR>>/pdf2htmlex-0.14.6+ds/src/util/ffw.c
~~~~~

I presume FontForge is being compiled without GUI support? If so, try the following fix:

Replace

````
__pkg_deps="${__pkg_deps} zlib"
````

With 
````
__pkg_deps="${__pkg_deps} zlib glib-2.0"
````

In this file: https://github.com/fontforge/fontforge/blob/master/m4/fontforge_create_pkg-config_files.m4

**Comment by copyninja** [comment]
We actually build 2 flavor of fontforge one normal one and another `--without-x` option. Do you think this might be causing the problem?.. Is the wrong pkg-config file is being installed?

**Comment by jtanx** [comment]
If you build `--without-x`, the current pkg-config `.pc` doesn't account for the `glib-2.0` dependency. So if you modify the `.pc` as above, it should fix the issue when you compile `--without-x`.

**Comment by copyninja** [comment]
Both are built separately, I need to check which version of pkg-config file gets installed. I remember libfontforge-dev is generated from fontforge version developed with X support, so that makes me wonder why glib-2.0 was missing here?. Anyway thanks for hints I will again take a closer look.

**Comment by copyninja** [comment]
@jtanx Actually I was not insalling pkgconfig files at all :-). I now install it from X based fontforge but there is still error with `pdf2htmlex` [build log](https://angband.pl/tmp/ff13/failed/pdf2htmlex_amd64.build) but I feel this is more related to pdf2htmlex rather than fontforge. What do you think?.

**Comment by copyninja** [comment]
The function in error message `error: 'library_version_configuration' undeclared (first use in this function)` seems to be defined in fontforge `fontforge/libstamp.c` I wonder why its not able to find it!. Any hints?.

**Comment by jtanx** [comment]
Sorry I don't have access to a proper computer right now, so I can't examine this in too much detail. It might not be including the correct header (libffstamp.h??) otherwise maybe FontForge has changed so that particular variable no longer exists. By the looks of it, it should though.

**Comment by copyninja** [comment]
@jtanx It looks like the structure in question which is used by `pdf2htmlex` is defined inside `fontforge/libstamp.c` which means it is not exposed outside!. Either its internal to `fontforge` or recently had been moved (accidentally or intentionally not sure) away to stop it being used outside. If its intentional then there should be a note on how to make sure software which is probably using this structure should do to keep them working like usual. 

Any ideas or suggestion on this issue?.

Cc: @frank-trampe @davelab6

**Comment by copyninja** [comment]
I should probably open a new issue on this instead of dragging this thread.

**Comment by copyninja** [comment]
Moved discussion to #2941 

Cc: @jtanx @frank-trampe @davelab6

**Comment by copyninja** [comment]
Closing the issue as it was not related to fontforge, instead it was packaging issue
