### ISSUE TITLE
gradio.c:362:21: warning: iteration 6u invokes undefined behavior [-Waggressive-loop-optimizations]

### ISSUE THREAD

**Issue by jmsalvat** [fontforge/fontforge#2911]
gentoo user.
installing media-gfx/fontforge-20160404
compile fine but trigger a warning
- Messages for package media-gfx/fontforge-20160404:
- Package:    media-gfx/fontforge-20160404
- Repository: gentoo
- Maintainer: floppym@gentoo.org fonts@gentoo.org
- USE:        X abi_x86_64 amd64 cairo elibc_glibc gif gtk jpeg kernel_linux png python python_single_target_python3_4 python_targets_python2_7 python_targets_python3_4 readline svg tiff unicode userland_GNU
- FEATURES:   preserve-libs sandbox userpriv usersandbox
- Removing unnecessary /usr/lib64/libgunicode.la (no static archive)
- Removing unnecessary /usr/lib64/libgioftp.la (no static archive)
- Removing unnecessary /usr/lib64/python3.4/site-packages/fontforge.la (module)
- Removing unnecessary /usr/lib64/python3.4/site-packages/psMat.la (module)
- Removing unnecessary /usr/lib64/libgutils.la (no static archive)
- Removing unnecessary /usr/lib64/libgdraw.la (no static archive)
- Removing unnecessary /usr/lib64/fontforge/plugins/gb12345.la (module)
- Removing unnecessary /usr/lib64/libfontforge.la (no static archive)
- Removing unnecessary /usr/lib64/libfontforgeexe.la (no static archive)
- Final size of build directory: 125292 KiB
- Final size of installed tree: 28340 KiB
- Updating desktop mime database ...
- Updating shared mime info database ...
- QA Notice: Package triggers severe warnings which indicate that it
-            may exhibit random runtime failures.
- gradio.c:362:21: warning: iteration 6u invokes undefined behavior [-Waggressive-loop-optimizations]
- Please do not file a Gentoo bug and instead report the above QA
- issues directly to the upstream developers of this software.
- Homepage: http://fontforge.github.io/

**Comment by jtanx** [comment]
Probably because that `pts` is only 6 long but the loop writes to the array 7 times. Weird bit of code that.

**Comment by frank-trampe** [comment]
I think that it's wrong in two places. The angle is 30 degrees at `i = 0` and 150 degrees at `i = 6`, which is horizontally symmetrical. So `pts` ought to have 7 spots.

But then the lashes are drawn from 50 degrees to 110 degrees, which is not symmetrical. So we ought to be drawing lashes in the `i>0 && i<6` range.

**Comment by skef** [comment]
I believe this was dealt with in #3931.
