### ISSUE TITLE
Glyphs exported as SVG have unexpected viewBox width

### ISSUE THREAD

**Issue by robmadole** [fontforge/fontforge#2912]
FontForge version: built from Git commit hash fe1d84b7d05178885a36ba0adce0559a82a493d5

Steps to reproduce:
1. Open FontAwesome.otf (in attached Zip file)
2. Select glyph `/resize_vertical`
3. Export to SVG
4. Open the SVG in a text editor

Expected:

The viewBox on the SVG will be `0 -144 432 1008`.

Actual value:

`0 -144 1008 1008`

This problem makes the SVG unusable in situations where a correct viewBox is required. One thing of note is that this apparently only occurs with glyphs that are narrower than the EM unit. (If you export `camera` the viewBox is correct.)

Here is the icon in FontForge:

![resize_vertical_ff](https://cloud.githubusercontent.com/assets/132895/19404014/726d56c4-9230-11e6-9593-cfef63fa525a.png)

Here is the icon opened in Illustrator:

<img width="720" alt="opened_in_illustrator" src="https://cloud.githubusercontent.com/assets/132895/19404034/9a4d0b76-9230-11e6-8008-25e23d93e714.png">

OTF file used to export SVGs:

[FontAwesome.otf.zip](https://github.com/fontforge/fontforge/files/530526/FontAwesome.otf.zip)

**Comment by robmadole** [comment]
I think this behavior is caused by [this line](https://github.com/fontforge/fontforge/blob/f868b218516c734b3f8573019d05548b437391f5/fontforge/svg.c#L1040).

**Comment by frank-trampe** [comment]
It looks wrong to me, but there must have been a reason for it. @davelab6, @mskala, @jtanx?

**Comment by davelab6** [comment]
No idea, sorry :(

**Comment by frank-trampe** [comment]
Okay. No objections.

@robmadole, would you submit a pull request with the line commented out and a note explaining why?

**Comment by robmadole** [comment]
@frank-trampe let me put up a PR of what I'm currently running

**Comment by skef** [comment]
Fixed by #2919
