### ISSUE TITLE
Incomplete translation of the French po

### ISSUE THREAD

**Issue by jrbastien** [fontforge/fontforge#2913]
About 3000 strings are still untranslated.

I'm creating this issue in order to submit a pull request.  I have completed the translation in my fork.

**Comment by JoesCat** [comment]
Issue not necessary.
When you create a pull request, you can title the subject line accordingly... for example, "Incomplete translation of French po - completed"
Less work for you, less work for us.

**Comment by jrbastien** [comment]
Got it.  Thank you.
