### ISSUE TITLE
How to edit contextual subtables by commands?

### ISSUE THREAD

**Issue by Pecita** [fontforge/fontforge#2923]
Dear developers,
If you please, I would like a little help: _how to edit contextual subtables by commands?_

I would like to automate the creation of a font whose characters are connected in various ways,
in particular by generating articulations of calt and aalt subtables that it would be excessively tedious to do manually.
I have everything available except populating the contextual subtables.

**Comment by frank-trampe** [comment]
@Pecita, are you asking about how to read/write contextual subtables in the scripting environment or how to generate the values?

**Comment by Pecita** [comment]
> read/write contextual subtables in the scripting environment.

For example, I imagine to generate (taking values from XML and XSLT logic) a such script:
`#!/usr/bin/fontforge`
`Open('Arghja.sfd')`
`# Real commands`
`AddLookup('aalt_10','gsub_alternate',0,[['aalt',[['latn',['dflt']]]]])`
`AddLookupSubtable('aalt_10','aalt_10_')`
`AddLookup('aalt_01','gsub_alternate',0,[['aalt',[['latn',['dflt']]]]])`
`AddLookupSubtable('aalt_01','aalt_01_')`
`AddLookup('calt_pass1','gsub_context',8,[['calt',[['latn',['dflt']]]]])`
`AddLookupSubtable('calt_pass1','calt_pass1_')`
`Select('a')`
`AddPosSub('aalt_01_','uniE481')`
`AddPosSub('aalt_10_','uniE482')`
`# Imagined commands`
`ChangeMotif('calt_pass1',[['1',[['a d h k l m n r t u dotlessi']]]])`
`AddRules('calt_pass1','[1 @<aalt_01> 1 @<aalt_10>]')`
_(etc.)_

To automatize this UI action :
![capture du 2016-10-25 02-41-52](https://cloud.githubusercontent.com/assets/7825396/19669408/6282d3e2-9a5f-11e6-997f-6ca107caefb8.png)

**Comment by Pecita** [comment]
Dear developers,
I am (_almost \*_ ) able to generate using FF scripting a font with accentuable and connectable letters in the Pecita style. Sources are two concise XML files and SVG images without thickness. With this tool it is possible for a user not knowing typography nor how to use FontForge to create a complex Latin or Cyrillic writing font.

_\* Well almost !_
For calt lookups tables I do not know what to do else that generate a file to do copy/paste. Still missed!
Do you have an idea to make my tool possible?

[genCalt.txt](https://github.com/fontforge/fontforge/files/711922/genCalt.txt)

**Comment by Pecita** [comment]
Just a small up. Is there a way to replace the tedious copy/paste in this tool: [aghja.net / gencalt step](http://aghja.net/paradigme.xhtml#gencalt) ?
I do not think it is possible with FontForge scripting but I am taker of any inventive solution.

**Comment by frank-trampe** [comment]
@Pecita, my French isn't bad, but that's a long document. Based on your previous comments, I think that the best thing is to expose a little more of the GSUB functionality in the scripting interface. @davelab6, could you help us plan/design that?

**Comment by Pecita** [comment]
Using a fea file may be a track?
I tried using an fea file  generated by FF but it fail on merging back at the calt table step:
>     sub @cc2_match_2' @cc2_match_1'  by   ;
gives
> No substitution specified on line 417 of Pecita-Latin.fea

Use for test [fea.zip](https://github.com/fontforge/fontforge/files/1417796/fea.zip)

**Comment by Pecita** [comment]
The issue 3219 is the best way to solve this problem.
