### ISSUE TITLE
Homebrew install: issue with configure.ac using git HEAD

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#2930]
System: OS X 10.11.6
Trying to install with homebrew with the following command:
```
brew install fontforge --HEAD --with-giflib --with-x11 --with-libspiro --enable-pyextension
```

and I'm having this error:
```
Error: inreplace failed
configure.ac:
  expected replacement of "test \"y$HOMEBREW_BREW_FILE\" != \"y\"" with "false"
```
It used to work using --HEAD version. I've just installed OK without it.
Thanks

**Comment by jtanx** [comment]
See homebrew/homebrew-core#5611. I haven't had the time yet to complete it though.

**Comment by JoesCat** [comment]
Take a look here: https://github.com/fontforge/libuninameslist/pull/8 and note the "{"
The BSDs sometimes are a little out of sync when it comes to autoreconf, automake, and MAC is based on BSD, so we may need to add a few extra in places that newer versions don't have problems with. There might be some spot(s) that needs brackets.
Some scripts require "{}" and some other types of scripts need "[]"
to hunt for possible files, I would suggest trying something like:
grep "HOMEBREW_BREW_FILE" -R *

**Comment by dimitre** [comment]
Just to keep up to date, I was able to install now with this formula version
https://github.com/Homebrew/homebrew-core/commit/d3e027e27e6233dd8e277a09ba524f300ff8264a

using the following command:
```
brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/d3e027e27e6233dd8e277a09ba524f300ff8264a/Formula/fontforge.rb --HEAD --with-giflib --with-x11 --with-libspiro --enable-pyextension
```

I can test on 10.12 too if needed.

**Comment by JoesCat** [comment]
@dimitre, please check 10.2 if you can.
(Lacking any MAC, I have no MAC testing ability).

You probably already know this, but, just in case....
...Just adding a bunch of FYI based on watching other distros,
I recall png has a dependency on zip compression, plus FontForge uses zip in more places, so it's basically a hard dependency. Even though it is pretty common, and we forget to include it, another distro had to include math lib as a dependency in libspiro, so we added that into configure.ac in FontForge too. Yet another distro indicated you had to announce libraries built (without reboot), so I've mentioned that in the README for libuninameslist, and will (eventually) update the readme for libspiro too. Some distros also fail to check /usr/local when searching for libraries (I don't know if that is also the case with MACs). If any ideas here help, great!

Thanks dimitre for getting homebrew working!

**Comment by dimitre** [comment]
@JoesCat it builds well on 10.12, only the command line utilities which is good for me. 
As the actual homebrew formula is not building I'll keep using this formula version when needed.

```bash
######################################################################## 100.0%
==> Reinstalling fontforge --with-giflib --with-libspiro
==> Cloning https://github.com/fontforge/fontforge.git
Updating /Users/dimitre/Library/Caches/Homebrew/fontforge--git
==> Checking out branch master
==> Cloning git://git.savannah.gnu.org/gnulib.git
Updating /Users/dimitre/Library/Caches/Homebrew/fontforge--gnulib--git
==> Checking out revision 29ea6d6fe2a699a32edbe29f44fe72e0c253fcee
==> ./bootstrap --gnulib-srcdir=/Users/dimitre/Library/Caches/Homebrew/fontforge
==> ./configure --prefix=/usr/local/Cellar/fontforge/HEAD-3e5531e_1 --disable-si
==> make
==> make install
==> Caveats
This formula only installs the command line utilities.

FontForge.app can be downloaded directly from the website:
  https://fontforge.github.io

Alternatively, install with Homebrew-Cask:
  brew cask install fontforge
==> Summary
🍺  /usr/local/Cellar/fontforge/HEAD-3e5531e_1: 1,246 files, 26.5M, built in 3 minutes 57 seconds
z:~ dimitre$  
```

**Comment by dimitre** [comment]
Now the formula doesn't have the HEAD option
```
brew install fontforge --HEAD
```

returns:
```
Error: No head is defined for fontforge
```

**Comment by JoesCat** [comment]
Hi Dimitre,
I think I recall something like this earlier and went to look at homebrew 
git. Seems --HEAD was removed in homebrew pull 16226, Jul30,2017, and it 
coincides with fontforge tag/release 20170731
