### ISSUE TITLE
A public symbol `library_version_configuration` is made private causing pdf2htmlex breakage

### ISSUE THREAD

**Issue by copyninja** [fontforge/fontforge#2941]
Hi,

This is issue which is created from existing discussion on #2907 . We found  `pdf2htmlex` which uses libfontforge on Debian that it is failing to build with newer version of fontforge we have in `experimental`. On deeper investigation we noticed that it is failing due to missing symbol `library_version_configuration`. This symbol is now defined inside `fontforge/libstamp.c` which means its no longer publicly visible. Was this intentional or accidental?.

If intentional what should be done by software which uses this symbol?. In our case `pdf2htmlex`.

The related [build log](https://angband.pl/tmp/ff13/failed/pdf2htmlex_amd64.build)

**Comment by copyninja** [comment]
Any suggestions any one?. 

Cc: @jtanx @frank-trampe

**Comment by jtanx** [comment]
It must have been this commit that did it: 03fc77a871c3e509a96f95180fcfe27aa67b9e08 (#1251)

Perhaps try replacing `library_version_configuration.library_source_versiondate` with `FONTFORGE_VERSIONDATE_RAW`?

**Comment by copyninja** [comment]
You mean to say the `pdf2htmlex` should replace use of `library_version_configuration` with `FONTFORGE_VERSIONDATE_RAW`?

**Comment by jtanx** [comment]
Yes.

**Comment by jtanx** [comment]
In other words, pdf2htmlex shouldn't rely on `library_version_configuration`, but it should use the values found in FontForge's generated `config.h`/`fontforge-config.h` header.

**Comment by copyninja** [comment]
@jtanx Thanks I will report bug against `pdf2htmlex`. Now that fontforge hit unstable (to make sure it will be part of Debian 9.0), pdf2htmlex needs fixing.

**Comment by copyninja** [comment]
There was a patch added in Debian to make sure pdf2htmlex works with older fontforge. Now they have dropped the patch and it works fine. So this is not basically problem with fontforge hence closing the issue.

Thanks for the help @jtanx
