### ISSUE TITLE
Where to find TrueType, OpenType and other formats spec

### ISSUE THREAD

**Issue by orklann** [fontforge/fontforge#2948]
I am willing to contribute to fontforge or to figure out how fontforge works, but the first question coming into my mind is where to find TrueType, OpenType or other types specification, how do you fontforge developers refer to those specs or docs? Is there any one place which contains those specs?

**Comment by jtanx** [comment]
There are a few places you can look for the spec; here's one that I use: https://www.microsoft.com/en-us/Typography/OpenTypeSpecification.aspx. Here too: https://www.microsoft.com/typography/otspec/otff.htm. Otherwise there's always Google

**Comment by aaron-elkins** [comment]
Thanks @jtanx, looks awesome.

**Comment by aaron-elkins** [comment]
BTW, @jtanx Do you have any suggestion on writing my own TrueType, OpenType writer (Exporter)?

This looks so complex to me.

**Comment by jtanx** [comment]
Maybe try otfcc https://github.com/caryll/otfcc  if you want C  or fonttools https://github.com/fonttools/fonttools for something in Python.

**Comment by aaron-elkins** [comment]
thanks again, @jtanx 
otfcc is what I need, i prefer C.
