### ISSUE TITLE
"Could not launch FontForge (exit code 255)."

### ISSUE THREAD

**Issue by krfkeith** [fontforge/fontforge#2954]
I'm on Windows 7 64-bit

FontForge used to work fine for me, then randomly I got this issue. So I uninstalled it, downloaded the latest release, and installed it using "Run As Administrator" and the problem is still there.

**Comment by frank-trampe** [comment]
@jtanx, is the exit code from FontForge itself, or from a launcher?

**Comment by jtanx** [comment]
Could you please include a screenshot?
