### ISSUE TITLE
make failed : on Centos 6.8 64bit

### ISSUE THREAD

**Issue by vungnhanh** [fontforge/fontforge#2965]
I use fontforge-20161005 (https://github.com/fontforge/fontforge/releases)
and use : 
PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig
CFLAGS="-I/usr" \
LIBS="-L/usr" \
PYTHON_CFLAGS="-I/usr/local/include/python2.7" \
PYTHON_LIBS="-L/usr/local/lib/python2.7/config" \
ZLIB_CFLAGS="-I/usr/local/include" \
ZLIB_LIBS="-L/usr/lib64/pkgconfig" \
GLIB_CFLAGS="-I/usr/include/glib-2.0" \
GLIB_LIBS="-L/usr/lib64/glib-2.0/" \
FREETYPE_CFLAGS="-I/usr" \
FREETYPE_LIBS="-L/usr" \
LIBXML_CFLAGS="-I/usr" \
LIBXML_LIBS="-L/usr" \
./configure \
--without-x \
--without-cairo \
--without-libtiff \
--without-libspiro \
--without-libuninameslist \
--without-libzmq \
--without-libreadline \
--without-libiconv-prefix
when I run make , I encounter the following error : 
.libs/libgutils_la-fsys.o: In function `GFileRemove':
fsys.c:(.text+0xd1a): undefined reference to `g_dir_open'
fsys.c:(.text+0xd48): undefined reference to `g_build_filename'
fsys.c:(.text+0xd89): undefined reference to `g_free'
fsys.c:(.text+0xd95): undefined reference to `g_dir_read_name'
fsys.c:(.text+0xdac): undefined reference to `g_dir_close'
.libs/libgutils_la-fsys.o: In function `getTempDir':
fsys.c:(.text+0x2198): undefined reference to `g_get_tmp_dir'
.libs/libgutils_la-g_giomime.o: In function `GIOGetMimeType':
g_giomime.c:(.text+0x13e): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x15c): undefined reference to `g_free'
g_giomime.c:(.text+0x17e): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x1a7): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x1be): undefined reference to `g_content_type_get_mime_type'
g_giomime.c:(.text+0x1ce): undefined reference to `g_free'
g_giomime.c:(.text+0x1f1): undefined reference to `g_free'
collect2: ld returned 1 exit status
make[2]: *** [libgutils.la] Error 1
make[2]: Leaving directory `/opt/setup/pdf2htmlEX/required/fontforge-20161005/gutils'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/setup/pdf2htmlEX/required/fontforge-20161005'
make: *** [all] Error 2

please help me resolve it ..

thanks

**Comment by jtanx** [comment]
What version of GLib do you have? Those are all linking issues to functions found in GLib. IIRC there were a few other issues compiling on Centos 6, so I'd suggest using Centos 7 if possible.

**Comment by vungnhanh** [comment]
my version Glib : 
glib2-2.28.8-5.el6.x86_64
glib2-devel-2.28.8-5.el6.x86_64

**Comment by jtanx** [comment]
Hmm. Try adding `-lglib-2.0 -lintl` to `GLIB_LIBS`

**Comment by JoesCat** [comment]
configure.ac sets the limit as glib2.6 or later (see approx line 363).
PKG_CHECK_MODULES([GLIB],[glib-2.0 >= 2.6 gio-2.0])
This lowest limit was set by Ben back in 2012, and it may indeed be the lowest limit, or it may be the lowest limit as per his system when buildin/testing his code.

You could try edit the line to:
PKG_CHECK_MODULES([GLIB],[glib-2.0 >= 2.2 gio-2.0])
and then rerun:
./bootstrap
./configure
make
and then see if it compiles okay or not.
If it works for you, then the lowest limit might be 2.28 (based on your setup), or it might still be 2.6 and your configuration might not need some 2.6 calls.

**Comment by vungnhanh** [comment]
I have followed your instructions, but  I still get the error when run make :
libs/libgutils_la-fsys.o: In function `getTempDir':
fsys.c:(.text+0x2090): undefined reference to `g_get_tmp_dir'
.libs/libgutils_la-g_giomime.o: In function `GIOGetMimeType':
g_giomime.c:(.text+0x13e): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x15c): undefined reference to `g_free'
g_giomime.c:(.text+0x17e): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x1a7): undefined reference to `g_content_type_guess'
g_giomime.c:(.text+0x1be): undefined reference to `g_content_type_get_mime_type'
g_giomime.c:(.text+0x1ce): undefined reference to `g_free'
g_giomime.c:(.text+0x1f1): undefined reference to `g_free'
collect2: ld returned 1 exit status
make[2]: *** [libgutils.la] Error 1

maybe I will consider plans to use CentOS 7

thank you very much
