### ISSUE TITLE
fatal error: 'ltdl.h' file not found

### ISSUE THREAD

**Issue by WendyAnjanette** [fontforge/fontforge#2968]
ff version: the lastest release
os: osx el capitan
I tried installing fontforge with this configuration
./configure \
--disable-programs \
--enable-native-scripting \
--without-x \
--without-cairo \
--without-giflib \
--without-libjpeg \
--without-libtiff \
--without-libpng \
--without-libspiro \
--without-libuninameslist \
--without-libunicodenames \
--without-iconv \
--without-libzmq \
--without-libreadline \
--disable-python-scripting \
--disable-python-extension;

but I got an error: 
In file included from plugins.c:29:
../inc/pluginloading.h:31:10: fatal error: 'ltdl.h' file not found

is that a bad configuration? is there anyway I could fix this error?

**Comment by frank-trampe** [comment]
Hi, Wendy.

That suggests that you haven't installed the libltdl developer package. Is
there something wrong with the .app bundle that we provide that requires
you to build from source?

**Comment by WendyAnjanette** [comment]
Hi Sir Frank, 

thanks for replying, I tried install libltdl dev using homebrew but it seems like there's no libltdl there, isn't libltdl included in libtool? I'm just testing something out.

**Comment by WendyAnjanette** [comment]
isn't there anyway I could fix this? or do I really need to use homebrew to be able to install fontforge?

**Comment by JoesCat** [comment]
Hi @WendyAnjanette,
I don't have a Mac, but understand it is based on BSD, and therefore may have some links in another location.
In configure.ac you will see a line that shows:
dnl AC_SEARCH_LIBS([dlopen], [dl dld])
please change it and add
AC_SEARCH_LIBS([dlopen], [dl dld libc])
AC_CHECK_LIB([dl],[dlopen])
AC_CHECK_HEADER([ltdl.h])
AC_CHECK_HEADERS([dlfcn.h])
AC_CHECK_LIB([dl],[dlopen])

run
./bootstrap
./configure
watch for messages refering to the lines mentioned above and see if they say found or yes.

**Comment by WendyAnjanette** [comment]
Hi JoesCat, will try that, thanks!

**Comment by WendyAnjanette** [comment]
got this error from ./bootstrap
glibtoolize:   error: 'libltdl/COPYING.LIB' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/Makefile.am' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/README' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/Makefile.in' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__alloc.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__argz_.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__dirent.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__glibc.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__private.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt__strl.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt_dlloader.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt_error.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/lt_system.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/libltdl/slist.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/dld_link.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/dlopen.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/dyld.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/load_add_on.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/loadlibrary.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/preopen.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/loaders/shl_load.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt__alloc.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt__argz.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt__dirent.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt__strl.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt_dlloader.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/lt_error.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/ltdl.c' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/ltdl.h' exists: use '--force' to overwrite
glibtoolize:   error: 'libltdl/slist.c' exists: use '--force' to overwrite


and when I run ./configure:
ltdl.h is not found but dlfcn.h is found.

**Comment by jtanx** [comment]
Try running `./bootstrap --force`

**Comment by WendyAnjanette** [comment]
Hi jtanx, 

tried ./bootstrap --force then ./configure then this is showed, they weren't cached the last time I ./configure
checking for ltdl.h... (cached) no
checking for dlfcn.h... (cached) yes

thanks

**Comment by JoesCat** [comment]
I wasn't expecting all that noise with bootstrap, but I guess it is what it is ;-P
A google search found this when searching for the ltdl.h problem.
http://jemalloc.net/mailman/jemalloc-discuss/2011-April/000010.html
A quick check of /usr/include/ on my machine also shows it exists too, so I'm curious why we don't use dlcn.h instead? ...I suspect there is good reason, but means more reading.

Hi @jtanx, Hi @frank-trampe, you probably have a better idea here if it's a possible solution ?

**Comment by WendyAnjanette** [comment]
also at the end of ./configure it says pangoxft not found.
