### ISSUE TITLE
Kerning question

### ISSUE THREAD

**Issue by madinafatt** [fontforge/fontforge#2971]
My name is Fattakhova Madina, I'am from Kazan.  I could'n find autors'mail in Internet to ask a question about Font Forge. Maybe You will help me, please?  I'm using FontForge programm to create my own script and I like this programm. I made about 40 distance on left and right side of each letters and symbols. Then I make some kernings between pairs of gliphs. I saved my new script but when I try to write some text in WPS Writer (all letters Latin) between some pairs of gliphs kerning is not in way I did in FontForge. Version of FontForge: 20:55 AWST 4-Oct-2016 (20:55 AWST 4-Oct-2016-ML-TtfDb-D) And I used Horizontal kern in programm for pairs of kerning. Can You help me in my problem or maybe you have mail's of people who could help me, please?

**Comment by madinafatt** [comment]
![screen](https://cloud.githubusercontent.com/assets/24494116/21074087/8dcd43fa-bf00-11e6-95bf-3ce515ef3fa9.jpg)

**Comment by frank-trampe** [comment]
Any chance you could provide the typeface in question?

**Comment by madinafatt** [comment]
Hello! I added screen in comment, Sorry I didn't find how to join screen to my question. Yesterday I check my script in other programms, like Illustrator, Photoshop and Notebook and everything was OK with script. But, should  I find problems with WPS Writer? I don't know will people use my script in WPS Writer...

**Comment by davelab6** [comment]
Discussion moved to #2981
