### ISSUE TITLE
Problems with FontForge

### ISSUE THREAD

**Issue by madinafatt** [fontforge/fontforge#2981]
![for txt text](https://cloud.githubusercontent.com/assets/24494116/21506138/e6dbc7f6-cc7e-11e6-8c6a-ed7bc132fd02.jpg)
![in libreoffice](https://cloud.githubusercontent.com/assets/24494116/21506140/e7035cbc-cc7e-11e6-8fd5-e985b1c9f6bb.jpg)
[Christmas.zip](https://github.com/fontforge/fontforge/files/674524/Christmas.zip)

Hello everybody! Help me please! I have made a new font in FontForge, but in WPS Writer or in LibreOffise not all kerning is working. Kerning works good in Notepad. What am I doing wrong?

**Comment by frank-trampe** [comment]
Hi, @madinafatt. Post the font file and screenshots so that we can try to isolate the problem.

**Comment by madinafatt** [comment]
Here they are. I hope you will help me to find my mistakes.

*С уважением Фаттахова Мадина,*


*Facebook - http://www.facebook.com/
<http://www.facebook.com/>madina.fattakhova*
*Одноклассники - http://ok.ru/madina.fattakhova
<http://ok.ru/madina.fattakhova>*
*ВКонтакте - https://vk.com/idfattakhovam <https://vk.com/idfattakhovam>*
*Skype - rivelffM*

2016-12-27 21:44 GMT+03:00 Frank Trampe <notifications@github.com>:

**Comment by frank-trampe** [comment]
@madinafatt, try attaching in GitHub rather than attaching to an e-mail. The e-mail attachments seem not to come through.

**Comment by madinafatt** [comment]
Ok.

**Comment by madinafatt** [comment]
Hello Frank Trampe! Did you find mistakes in my font? Or maybe I would add some more screenshots or other files?

**Comment by davelab6** [comment]
@madinafatt you did not attach anything... you need to make a zip with your font file, then visit https://github.com/fontforge/fontforge/issues/2981 and drag and drop that zip into the comment area at the bottom of the page.

**Comment by frank-trampe** [comment]
@davelab6, it's attached at the top.

**Comment by madinafatt** [comment]
[FontForge.zip](https://github.com/fontforge/fontforge/files/676167/FontForge.zip)
Like this?

**Comment by davelab6** [comment]
@frank-trampe aha! 

@madinafatt sorry i missed that christmas.zip - love your font :D

**Comment by madinafatt** [comment]
Thank you! I want to make more fonts, but I think I did mistake somewere in FontForge...

**Comment by davelab6** [comment]
Looks to me like something has got messed up with FontForge. 

Here you can see that the option for a 'kern' table is clearly marked:

<img width="700" alt="screen shot 2016-12-28 at 21 37 16" src="https://cloud.githubusercontent.com/assets/261579/21531226/9e38cc24-cd46-11e6-98d2-248219f8bec8.png">

And here we can see there is no 'kern' table in the font:

```
$ ttx -s ~/Downloads/FontForge/*ttf
Dumping "/Users/dcrossland/Downloads/FontForge/Christmas-test.ttf" to "/Users/dcrossland/Downloads/FontForge/Christmas-test.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
$
```

@frank-trampe can you reproduce this?

**Comment by davelab6** [comment]
Oh, I see there is also `Old Style 'kern'` in OpenType options, I'll check that now

**Comment by frank-trampe** [comment]
I remember this dummy DSIG thing coming up before on Windows. Let me hunt for the issue.

**Comment by frank-trampe** [comment]
Can't find it.

**Comment by madinafatt** [comment]
I have done all your steps from 1 till 4, but how to do zip file with ttf at the end (step 5)?

**Comment by frank-trampe** [comment]
@madinafatt, there's not need to zip it. Dave just did that to make it easier for you to download/compare. Does the ttf work now?

**Comment by madinafatt** [comment]
Let me check it...

**Comment by madinafatt** [comment]
Great!!! It's works in LibreOffice, but not works in Word...

**Comment by madinafatt** [comment]
And about DSIG I didn't understand, sorry...

**Comment by frank-trampe** [comment]
Don't worry about the fake DSIG thing. It's some odd technical quirk.

**Comment by frank-trampe** [comment]
So the kerning works in LibreOffice and in Notepad but not in Word? Have you tried restarting Word? It might be caching the old copy.

**Comment by madinafatt** [comment]
A minute please...

**Comment by madinafatt** [comment]
No. it's not working. I restarted it and changed font - didn't helped

**Comment by frank-trampe** [comment]
Well, post the new ttf, and I'll take another look (probably tomorrow, unfortunately).

**Comment by madinafatt** [comment]
It works if I turn on the "kerning for glyphs with size... and I'm writing here 60 in Fonts preferenses. But instead space there are big rectangles there...

**Comment by madinafatt** [comment]
[Christmas.zip](https://github.com/fontforge/fontforge/files/676292/Christmas.zip)

**Comment by madinafatt** [comment]
Ok, I'll wait. Thank you! )))

**Comment by davelab6** [comment]
The file in your latest zip is functionally identical to the file I uploaded. 

> It works if I turn on the "kerning for glyphs with size... and I'm writing here 60 in Fonts preferenses. But instead space there are big rectangles there...

I don't know what you mean. 

> And about DSIG I didn't understand, sorry...

You should always include a DSIG table. 

Your initial point was that it didn't work in WPS Writer or LibreOffice, and now it works in LibreOffice. Does it work in WPS Writer?

Does your original work in Word, and its now stopped working?

**Comment by madinafatt** [comment]
Hello Dave! All my answers on screenshots. Please, look at them. And I hope I did latest ttf file you asked.
[Github.zip](https://github.com/fontforge/fontforge/files/677135/Github.zip)

**Comment by davelab6** [comment]
I'm confused - please restate your question :)

**Comment by madinafatt** [comment]
Ok.) My question was: Why my font not working in Word? I'm talking about kerning between some pares of glyphs. After your help (first time) kerning began to work in WPS Writer and in LibreOffice, as I show you in my screenshots)) 
I think we will talk about that next year, so that Best wishes for a merry Christmas and a happy New Year!!!

**Comment by davelab6** [comment]
Does your original work in Word, and its now stopped working? Or it has never worked in word? 

http://www.kimberlygeswein.com/2012/03/01/tip-using-kerning-in-word/ says it must be enabled even if it exists in the font

**Comment by madinafatt** [comment]
No, before your help kerning is not worked in Word. Now it's working but all spases have become big rectangles. How to change that?

**Comment by madinafatt** [comment]
Or  I should create "space" in FontForge too?

**Comment by davelab6** [comment]
Yes! Exactly 😄

**Comment by madinafatt** [comment]
Are you kidding? Tell me please,  in what programm other people checking their fonts?

**Comment by madinafatt** [comment]
And how to create space in FontForge?

**Comment by davelab6** [comment]
In the font view, press space and the space character will be selected.
Then press crtl-k to open the metrics window and set the advance with so
some suitable value.

**Comment by madinafatt** [comment]
Thank you!!! It is working everywere!!!

**Comment by madinafatt** [comment]
Hello Frank! Hello Dave! I have a little problem with my font again.  My font isn't working in Photoshop CS5. Help me please)

**Comment by davelab6** [comment]
What isn't working?

**Comment by madinafatt** [comment]
Not working kerning again. I can't find decision anywere else...
