### ISSUE TITLE
Homebrew's fontforge doesn't work correctly

### ISSUE THREAD

**Issue by equal-l2** [fontforge/fontforge#2984]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

Homebrew's fontforge 20161012 (and ~~the former version~~ 20161004, 20161001) on macOS 10.12.2 have a problem.

When I generate ricty with homebrew's fontforge (using http://www.rs.tus.ac.jp/yyusa/ricty/ricty_generator-4.1.0.sh), some characters in bold font will be oddly big.
![410_2000](https://cloud.githubusercontent.com/assets/8597717/21586143/a80be2a4-d110-11e6-88eb-d6602d2b1065.png)

When I do with official binary (20161004), everything seems good.
![good](https://cloud.githubusercontent.com/assets/8597717/21586172/0d1e24c2-d111-11e6-8c7e-ef680ae69283.png)

Is there anything wrong with [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fontforge.rb), or with ricty_generator?

I'm one of the contributors in homebrew, so let me know anything wrong with the formula.
If anything bad with ricty_generator, I'll contact the author.

**Comment by jtanx** [comment]
WRT the formula, https://github.com/Homebrew/homebrew-core/pull/5611 should probably be picked up to rule out anything funny with that. Otherwise the [changes](https://github.com/fontforge/fontforge/compare/20161004...20161012) between the two version were fairly minimal - could you perhaps try performing a bisect to see where the issue lies?

**Comment by equal-l2** [comment]
Well, this problem is relevant for homebrew fontforge from 20161001 to 20161012, so this should be a formula problem.

I'll look in Homebrew/homebrew-core#5611.

**Comment by equal-l2** [comment]
@jtanx 
Porting changes from your PR fixed the problem.
I should have included the change in the former version bump.

Thank you!

**Comment by equal-l2** [comment]
Well, I made a mistake and I thought the problem had been fixed.
Actually, the changes ported from jtanx's PR has no effect for this problem.

**Comment by equal-l2** [comment]
The problematic part does the below.

```
Open("Inconsolata-Bold.ttf")
ScaleToEm(860, 140)
SelectWorthOutputting()
ClearInstrs()
UnlinkReference()
Save("Modified-Inconsolata-Bold.sfd")
```

This will work fine with official binary, but with homebrew this leads to huge characters.

**Comment by jtanx** [comment]
That's a strange one. I can reproduce the issue using the Homebrew build, but not with a straight-from-source build

**Comment by jtanx** [comment]
I've built 20161012 and I cannot reproduce the issue on Linux. This suggests to me that this bug is either compiler dependent or there is some sort of memory corruption going on.

The only thing valgrind reports is:

```
=15061== Conditional jump or move depends on uninitialised value(s)
==15061==    at 0x5EB151F: AnchorClassDecompose (tottfgpos.c:417)
==15061==    by 0x5EB4740: AnchorsAway (tottfgpos.c:2452)
==15061==    by 0x5EB4740: otf_dumpALookup (tottfgpos.c:2582)
==15061==    by 0x5EB6C2D: G___figureLookups (tottfgpos.c:2651)
==15061==    by 0x5EB6C2D: dumpg___info (tottfgpos.c:3040)
==15061==    by 0x5EB7E29: otf_dumpgpos (tottfgpos.c:3250)
==15061==    by 0x5EC9B09: initATTables (tottf.c:5273)
==15061==    by 0x5ECAEC7: initTables (tottf.c:5754)
==15061==    by 0x5ECB388: _WriteTTFFont (tottf.c:6105)
==15061==    by 0x5ECB846: WriteTTFFont (tottf.c:6138)
==15061==    by 0x5DB9015: _DoSave (savefont.c:823)
==15061==    by 0x5DBA6BB: GenerateScript (savefont.c:1232)
==15061==    by 0x5DD1740: bGenerate (scripting.c:1965)
==15061==    by 0x5DD4317: docall (scripting.c:9268)
==15061== 
```

**Comment by jtanx** [comment]
CID1081861 may be relevant.

**Comment by equal-l2** [comment]
@jtanx 
Would you explain more in detail?
Unfortunately, I'm not so good at fonts.

**Comment by jtanx** [comment]
@equal-l2 I believe there's a bug in FontForge that's not related to any recent source code change - the bug has only been made apparent likely because of the compile environment - e.g.clang being used instead of gcc. 

Coverity isn't helping me out; CID1081861 is a false positive. This might take a while to fix...

I will say that the bug appears to occur for chars that reference other chars. They will be scaled wrongly, while the referenced chars are scaled OK.

**Comment by equal-l2** [comment]
@jtanx 
Oh, I didn't know about CID in Coverity.
(I had mistook CID as Adobe's CID)

Thanks for giving me workaround.

**Comment by equal-l2** [comment]
This seems to have been fixed before I know.
