### ISSUE TITLE
Native scripting: DebugCrashFontForge won't run without a font loaded

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#2987]
Running

```
fontforge -lang=ff -c "DebugCrashFontForge()"
```

Will complain that:

```
DebugCrashFontForge: This command requires an active font
Called from...
 <command-string>: line 1
```

This shouldn't be the case (why would you need to load a font just to crash FF?)

That said, having a function just to cause a segfault is pretty neat 😉

**Comment by JoesCat** [comment]
in scripting.c
```c
static struct builtins {
    const char *name;
    void (*func)(Context *);
    unsigned int nofontok: 1;	/* 0=require active font */
    unsigned int argcnt: 4;	/* 0=defined in function */
    unsigned int argtype: 4;	/* 0=defined in function */
```

Change the 0 to a 1 on line:
```c
-    { "DebugCrashFontForge", bDebugCrashFontForge, 0,0,0 },
+    { "DebugCrashFontForge", bDebugCrashFontForge, 1,0,0 },
```
Following git blame, the reason for this function seems to be to test if you can run a crash debugger (in Windows, MAC, Linux, otherOS) in the first place. Can't be complete if you can't crash it on purpose ;-P

**Comment by JoesCat** [comment]
Fixed it, then added more (patch 2990).
Reading another article about COW, think it best to leave this off as default.
http://advisories.mageia.org/MGASA-2016-0347.html

If you think we should add a configure toggle, like --with-debugcrash then it could be done, but recommend default action is to leave it off.

**Comment by JoesCat** [comment]
Seems issue resolved.
