### ISSUE TITLE
Download page links to XQuartz 2.7.7, but current version is 2.7.11

### ISSUE THREAD

**Issue by neoneye** [fontforge/fontforge#2991]
The [download page](http://fontforge.github.io/en-US/downloads/mac-dl/)

Links directly to [XQuartz-2.7.7.dmg](http://xquartz.macosforge.org/downloads/SL/XQuartz-2.7.7.dmg)

The newest XQuartz is [version 2.7.11](https://www.xquartz.org/)

When I download XQuartz-2.7.7 and install it, then XQuartz immediately says that it's outdated and that version 2.7.11 is available. Updating the link to the newest version, may save some people some time.

**Comment by frank-trampe** [comment]
Thank you @neoneye. We will fix it.

**Comment by jtanx** [comment]
Closed by fontforge/fontforge.github.io#111
