### ISSUE TITLE
FF freezes

### ISSUE THREAD

**Issue by uswd** [fontforge/fontforge#3002]
Hi,

MacOS Sierra 10.12.2, FontForge 2016/10/3, XQuartz 2.7.11 (xorg-server 1.18.4)

After validating a font I opened the first glyph with a missing point at extrema. In the glyph window I used the find problem feature to find the point. Suddenly FF freezes. When trying to select a menu item or a point inside the glyph window or trying to close a window I got only "beeps". I have to close XQuartz and of course nothing is saved ...

Best regards,
Ulrich

**Comment by uswd** [comment]
Addendum.

I installed in a Windows VM the windows version. There the program behaved quiet stable (only one "freeze" which I couldn't reproduce).

**Comment by frank-trampe** [comment]
@uswd, are you still able to reproduce the problem? If so, could you provide the input file and steps?

**Comment by uswd** [comment]
I've now the latest FontForge and MacOS HighSierra and I can't reproduce the problem.

**Comment by JoesCat** [comment]
That's a positive sign that FontForge continues in the direction of stability.
We've often fixed things that don't even have an associated issue, and there's a lot of patches between 2016/10/3 and now. Sometimes a patch over here fixes something indirectly elsewhere.

@uswd, you are the most prepared to see if this re-occurs, and if it appears vanquished for good, we could call this issue resolved. I'd say, give it a month longer, and if nothing appears, can you close the issue?
