### ISSUE TITLE
Impossible to set author / copyright manually?

### ISSUE THREAD

**Issue by winniehell** [fontforge/fontforge#3004]
### When reporting a bug/issue:
- [ ] Screenshot (not relevant?)
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

### Description

When generating fonts, it looks like the author / copyright information is automatically generated from the current user:

```
$ users
winnie
$ head css/zocial.svg 
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<!--
2017-1-22: Created with FontForge (http://fontforge.org)
-->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
<metadata>
Created by FontForge 20161013 at Sun Jan 22 20:50:49 2017
 By winnie,,,
Copyright (c) 2017, winnie,,,
```

Judging from the [GetAuthor()] method, it is not possible to specify the author manually. I would expect an optional command line flag to specify the author(s) name. This is especially useful when multiple authors work on the same font. Currently, the copyright information is wrong in that case.

When not passing an author, the behavior could still be the same as it is now, so this would not be a breaking change.

```
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 01:51 UTC 13-Oct-2016-ML-D.
 Based on source from git with hash: fe1d84b7d05178885a36ba0adce0559a82a493d5
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 01:51 UTC 13-Oct-2016
libfontforge 20161013
```

[GetAuthor()]: https://github.com/fontforge/fontforge/blob/8cf8d2960b2384de5882436dffbe2cd6d7352575/gutils/gutils.c#L53

**Comment by ChristTrekker** [comment]
You can set it manually ... within the GUI. I wouldn't expect every GUI feature to also be accessible from CLI.

**Comment by zimbatm** [comment]
Over at https://github.com/smcllns/css-social-buttons/ it's a bit of an issue. Because each PR will contain the same line changed it's likely that it will result in merge conflicts. It also introduces confusion regarding the copyright of the generated file.

**Comment by ctrlcctrlv** [comment]
Superseded by #5032.

I am closing this issue as it is very old and incorrectly states the case. This only affects deprecated SVG 1.1 format fonts. The API/GUI can easily change author/copyright info for OpenType fonts, FontForge's main output.
