### ISSUE TITLE
xQuartz not opening (OSX 10.12.3)

### ISSUE THREAD

**Issue by BenCrab** [fontforge/fontforge#3015]
After downloading xQuartz for the first time, and attempting to the app, the icon bounces in the application bar, but it doesn't open. I tried reinstalling three times with the same result, once from xQuartz.org and twice from fontforge.github.io.

(OSX 10.12.3)

**Comment by JoesCat** [comment]
please investigate issue #2799.
Please see what is shown if you start from a console terminal.
