### ISSUE TITLE
Download interstitial breaks licence terms

### ISSUE THREAD

**Issue by scruss** [fontforge/fontforge#3022]
## Problem

Download pages — such as [FontForge on GNU+Linux and other UNIXes, Almost There](http://fontforge.github.io/en-US/downloads/gnulinux/ "FontForge on GNU+Linux and other UNIXes, Almost There") — require you to sign up to the FontForge announcement list. The [licence](https://github.com/fontforge/fontforge/blob/master/LICENSE "fontforge/LICENSE at master · fontforge/fontforge") makes no mention of this restriction.

## Why this is a problem

Disclosure of e-mail addresses creates privacy issues. It also creates legal issues: for example, how can I be sure that your use of my e-mail address meets [CASL](http://fightspam.gc.ca/ "CASL") requirements?

## Solution

At the very least, provide an opt-out or bypass as other projects (eg: [Processing](https://processing.org/download/ "Processing"), [Arduino](https://www.arduino.cc/download_handler.php?f=/arduino-1.8.1-linux64.tar.xz "Arduino")) do. Ideally, link directly to the download location instead.

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

**Comment by JoesCat** [comment]
Hi @scruss,
Can you re-open this issue in https://github.com/fontforge/fontforge.github.io/issues

There are over 800 open (program-related) issues here, and your (webpage) issue will get lost in the noise here. This issue is more directly related there, than here (and will get better attention to/from web authors involved with the .io pages).

It's basically a bit of sorting and organization if you can reopen it there (and close this one).
Thanks,
Joe

**Comment by frank-trampe** [comment]
Hi, Stewart.

The BSD license puts no restrictions on the publishing of binaries, and the GPL requires only that the source code be made available, which does indeed happen. The source code (and in fact the binaries in some cases) are still available via GitHub, and you're welcome to download and to build the code yourself if you do not wish to be involved in the project. Or, if you want to have your cake and eat it too, you could submit a fake e-mail address.

For what it's worth, we currently send about two messages per year via the announcement list, and we plan to get that up to roughly eight per year if we end up using Kickstarter to support faster development and more releases. If deleting eight e-mails per year is too much of a price to pay to use FontForge, you probably don't have the time to learn how to use it anyway. Designing a typeface is one of the most complicated, knowledge-intensive tasks known to man, and even I haven't had time to learn it all, in some cases implementing features that I don't understand.

Software is much more dangerous than an e-mail address. If you don't trust an organization to manage the latter, you certainly ought not to trust it to manage the former.

If you're just dabbling and don't need all the new features, you might have an easier time just installing the 2012 version via your distribution's standard package repository.

**Comment by frank-trampe** [comment]
Ah. One more thing. The subscription process requires following a link in a confirmation e-mail. So it's fairly easy to opt out at that point.
