### ISSUE TITLE
FontForge won't launch on MacBook 

### ISSUE THREAD

**Issue by eszaq1** [fontforge/fontforge#3032]
I have this problem when trying to launch FontForge... A pop-up window says _'Your security preferences allow installation of only apps from the App Store and identified developers. Google Chrome downloaded this file yesterday at 20:47 from fontforge.github.io.'
I'm no expert on code or Mac IOS so appreciate simplistic advice!
Thanks in advance, Mark.
<img width="415" alt="screen shot 2017-02-16 at 20 56 00" src="https://cloud.githubusercontent.com/assets/25832755/23047906/95ec96be-f4aa-11e6-9e73-35428254ab80.png">
- MacBook Pro running MacOS Sierra 10.12.3
- XQuartz version 2.7.11
- Running FontForge version 20161003 based on sources from 23:50 PDT  3-Oct-2016 git:072edb0235cd163d6c3391da9cc3754c3c66f47a

**Comment by frank-trampe** [comment]
Have you tried changing your security settings?

**Comment by eszaq1** [comment]
@frank-trampe Hi, sounds promising... can you advise on best step-by-step method.

**Comment by frank-trampe** [comment]
Go to System Preferences and then to the Security section. Allow software from outside developers.

**Comment by eszaq1** [comment]
Ok... can't see a toggle or check box for this in Security & Privacy though...

**Comment by frank-trampe** [comment]
I don't have access to a Sierra machine. Maybe try a Google search for allowing third-party software on Sierra.

**Comment by frank-trampe** [comment]
Oh. The option is hidden now. See [here](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/).

**Comment by eszaq1** [comment]
@frank-trampe Cheers, mate... software open.

**Comment by kusha-b-k** [comment]
In mac os Sierra when you get this dialog box , just goto  System Preferences ---> after that click on 
Security & Privacy --> after that You can see Open anyway button click that thats it FontForge will open..


Thanks

**Comment by SundialServices** [comment]
On _High_ Sierra the option is still there, just more hidden than ever.  *Control-*click on the icon, choose "Open," and you will be asked to make an exception.  Now you must make an exception for every application – the blanket option is gone from "Security & Privacy" preferences.  "Now you know."
