### ISSUE TITLE
Is there a way for me to create a deb for fontforge?

### ISSUE THREAD

**Issue by carmatdaw** [fontforge/fontforge#3038]
We use fontforge in our production environment to export svg fonts for use in our web application.  I've made a change, possibly a bug fix, to fontforge in order to meet requirements of our production environment.  In order to deploy it, I need to create a deb file.  It appears that there may be a way to generate a deb file already implemented, but I haven't been able to find the right combination of commands to make that happen.

So...is there already a way to create a deb once I have a build I want to deploy?  If so, what is the secret sauce to make that happen?

(And, yes, if this turns out to be a bug, I'll submit a pull request, I have a separate ticket inquiring about whether my particular requirement is actually the result of a bug.)

**Comment by bkmgit** [comment]
Ubuntu:
https://packages.ubuntu.com/search?keywords=fontforge
Debian:
https://packages.debian.org/bullseye/fontforge

**Comment by ctrlcctrlv** [comment]
https://github.com/fontforge/fontforge/blob/8ce3216d492d4a249ffec163c005d098df28e58c/Packaging/debian/setup-metadata.sh#L3-L9
