### ISSUE TITLE
Immediate crash on Mac 

### ISSUE THREAD

**Issue by d6p2b** [fontforge/fontforge#3039]
I've got a fresh installation of FontForge  [ FontForge-20161004-Mac (1) 12.46.33 PM ]  running under XQuartz 2.7.11 (xorg-server 1.18.4) that crashes immediately on launch with a divide by zero exception in GDrawInstanciateFont + 59 (gdrawtxt.c:52)

Any suggestions?

The full crash file is attached.
[fontforge_2017-03-01-161649_Nudibranch.crash.txt](https://github.com/fontforge/fontforge/files/815093/fontforge_2017-03-01-161649_Nudibranch.crash.txt)

**Comment by michaelappuhn** [comment]
I just did a fresh install via [Homebrew Cask](https://caskroom.github.io/) and found that to resolve my opening issues.
