### ISSUE TITLE
Trying to extract a font from macOS Sierra TTC produces garbage

### ISSUE THREAD

**Issue by nwwt** [fontforge/fontforge#3040]
I'm trying to extract Kyokasho.ttc, which comes with macOS Sierra (when Japanese support is active) and contains Yu Kyokasho N. Can't upload the file because of copyright, but I could send it via mail.

Anyway, the file ostensibly loads (using current git version) and you get to select one of the four contained fonts, but there's a few "No glyph with unicode …" messages and no kanji actually show in their main window entries.

"Generate fonts" and TrueType then complains about CID and generates – without error – a garbage ttf file that's ~50 kB in size, which loads back into FontForge with a myriad of…
> The glyph named uni#### is mapped to U + ####. But its name indicates it should be mapped to U + ####

… and ofc contains nothing.

"Generate fonts" and OpenType yields an…
> Internal Error: Attempt to output -2147483648 into a 16-bit field. It will be truncated and the file may not be useful

… which leaves you with a ~7 MB file (which can be opened & saved again without renewed error) and is rejected by Chromium with

> OTS parsing error: OS/2: first char index 65535 > last char index 0 in os2

Same issue is encountered with all other Japanese Sierra ttc files that I tried.

*edit:* BTW, BREAKTTC.EXE from 1997's Microsoft TrueType SDK still works fine on it. Gotta use dosbox, ofc.

**Comment by rathsky** [comment]
Note: The internal error still occurs when trying to eg. convert the TTF extracted with breakttc into an OTF.

**Comment by Finii** [comment]
Hmm, [fontTools](https://fonttools.readthedocs.io/en/latest/ttLib/index.html) do not fail, but also create a mostly empty(*) font file:

(*) Empty when looked at with `fontforge`.
The glyphs seem to be there, `CMAP` lists them, I dont know....

```python
#!/usr/bin/env python3

from fontTools import ttLib

tt = ttLib.TTFont(sys.argv[1], fontNumber=0, checkChecksums=1)
tt.save("testexport.otf")
```
```shell
$ ./de-ttc.py Kyokasho.ttc 
bad checksum for 'head' table
bad checksum for 'name' table
$ ll
total 29324
-rwxrwxr-x 1 fini fini      193 Jan 21 13:58 de-ttc.py
-rw-rw-r-- 1 fini fini 13355728 Jul 29  2016 Kyokasho.ttc
-rw-rw-r-- 1 fini fini  9443849 Jan 21 07:38 Kyokasho.zip
-rw-rw-r-- 1 fini fini  7218036 Jan 21 13:59 testexport.otf
```

But then, the `MAXP` header says it's version is 0.3 something, which I have never seen; note https://docs.microsoft.com/en-us/typography/opentype/spec/maxp

I have font version 11.0d4e4 (c 2016)

See also https://www.reddit.com/r/LearnJapanese/comments/92bffd/use_macos_yukyokasho_font_on_windows_guide/

> all other Japanese Sierra ttc files

Hmm :-/

Have no clue, just wanted to add my findings here.

**Comment by ctrlcctrlv** [comment]
You tried [§D6](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D6)?

**Comment by Finii** [comment]
@ctrlcctrlv :tada: 
I never worked with CID fonts and I had no clue (as I already said ;)

So in fact @nwwt's problem is no problem (except from ... well, `fontforge` could do this automagically maybe?)

```
fontforge Kyokasho.ttc
```

![image](https://user-images.githubusercontent.com/16012374/150577099-dcf3e12e-3909-4d24-b300-ebc752ceabc5.png)

![image](https://user-images.githubusercontent.com/16012374/150577192-c9a33c8c-df4e-4c7a-bda8-2dfc5f40355e.png)

![image](https://user-images.githubusercontent.com/16012374/150577438-abfc61d8-4daa-4b5e-828f-2d6cba3a78ea.png)

![image](https://user-images.githubusercontent.com/16012374/150577574-71cc68fa-e037-46aa-8076-fdf9e3d1e024.png)

Everything is there!

Afterwards normal `generate` and all is fine.

Thank you @ctrlcctrlv and hope this solves it for you @nwwt :-)

**Comment by Finii** [comment]
The missing glyphs are really missing, maybe already in the source font.

![image](https://user-images.githubusercontent.com/16012374/150578356-a8ee6352-0d42-4f76-b4b9-6b9a7f442d76.png)

I would deem this issue closed.
