### ISSUE TITLE
fontforge: PyFF_OpenFont(): fontforge killed by signal 6 

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#3042]
1) Use a simple fontforge script where it will open the sfd file e.g. say generate.ff

```
import fontforge
from sys import argv

argc = len( argv )

if argc > 1:
	for i in range( 1, argc ):
		f = fontforge.open( argv[i] )
		otfile = f.fontname + ".otf"
		print("Generating OpenType file ", otfile)
		f.close()
```

2) get any sfd file e.g. FreeSans.sfd from gnu-free-fonts upstream tarball or get it directly from here https://pnemade.fedorapeople.org/FreeSans.sfd

3) run following command
/usr/bin/fontfore -lang=py -script generate.ff FreeSans.sfd

This will cause core dump. I suspect issue somewhere in python3.6 version.  I am getting this core dump on Fedora 26 system where we have fontforge-20161012-5.fc26.x86_64, python3-3.6.0-20.fc26.x86_64, gcc-7.0.1-0.10.fc26.x86_64 packages installed.

Truncated backtrace:
```Thread no. 1 (7 frames)
 #6 PyFF_OpenFont at python.c:1013
 #7 _PyCFunction_FastCallDict at /usr/src/debug/Python-3.6.0/Objects/methodobject.c:234
 #8 _PyCFunction_FastCallKeywords at /usr/src/debug/Python-3.6.0/Objects/methodobject.c:295
 #9 call_function at /usr/src/debug/Python-3.6.0/Python/ceval.c:4788
 #10 _PyEval_EvalFrameDefault at /usr/src/debug/Python-3.6.0/Python/ceval.c:3275
 #11 _PyEval_EvalCodeWithName at /usr/src/debug/Python-3.6.0/Python/ceval.c:4119
 #12 PyEval_EvalCodeEx at /usr/src/debug/Python-3.6.0/Python/ceval.c:4140
```

More information can be obtained from https://bugzilla.redhat.com/show_bug.cgi?id=1429574

**Comment by pravins** [comment]
This has been affecting build failure for Lohit series as well.  
* https://koji.fedoraproject.org/koji/taskinfo?taskID=18248306  
* Build Log: https://kojipkgs.fedoraproject.org//work/tasks/8306/18248306/build.log

* Script: https://raw.githubusercontent.com/pravins/lohit/master/scripts/apply_featurefile.py

**Comment by frank-trampe** [comment]
I can't reproduce the crash on Ubuntu, but it seems to be happening on the free statement. Could you try attaching valgrind to see whether it complains about a double-free there? Do you get the problem if you compile from source locally?

The Python documentation says that we are responsible for freeing a string from PyArg_ParseTuple, but it's customary to use PyMemFree instead of free. That might be a problem, but I don't know why it wouldn't surface anywhere else in our Python code.

Do previous versions of FontForge work?

**Comment by pnemade** [comment]
I just found this issue can be similar of issue#2992. I need some time to test the fix and if found working will close this as duplicate. 

Thanks @frank-trampe for looking into this issue.

**Comment by frank-trampe** [comment]
@pnemade, I see that you pushed a patch to Fedora with the PyMem_Free change. Does that solve the problem?

**Comment by pnemade** [comment]
@frank-trampe I think so. I was testing gnu-free-fonts and its built fine but then I realized some other font package is still failing to build using fontforge python API. Hence, I changed many of the free() calls to PyMem_Free() and now those fonts are also building fine against fontforge. 
I have submitted #3046 which will fix reported problems here.

**Comment by gioele** [comment]
@pnemade: with #3046 merged this bug should be fixed, right? Could you please close it if this is the case?

**Comment by pnemade** [comment]
@gioele  Yes this bug is fixed now and all the Fedora fonts builds also succeeded now.
