### ISSUE TITLE
Cannot merge .fea file

### ISSUE THREAD

**Issue by skosch** [fontforge/fontforge#3048]
We are experiencing difficulties when trying to import OpenType features. The problem seems to be that glyph names in the .fea files don't match the named glyphs in the .sfd – although to my human eye they do! The issue in question is skosch/Crimson#42, opened by @katef.

Steps to reproduce: `git clone https://github.com/skosch/Crimson`, then try to merge e.g. `Source Files/ik/Crimson-Roman#00_ik.fea` into `Source Files/Crimson-Roman.sfd` (optionally, rename glyphs to AGL first).

FF version: 13-Oct-2016 (from Ubuntu PPA)

I would be grateful for any pointers – we would love to leave this AGL-based mess behind and convert everything to Unicode UFO folders, but without those feature files we'll lose all of our kerning information.

**Comment by skosch** [comment]
Took me a few hours, but I have now cleaned everything up by hand. I somehow doubt FF will implement this ever, so I'm closing this. It *would* be nice, however, if syntax errors and missing references in feature files produced more helpful errors than just line numbers.

**Comment by katef** [comment]
I wanted to add, that I'm glad you're attacking this area. Good luck!
