### ISSUE TITLE
FontForge shows very old splash screen

### ISSUE THREAD

**Issue by probonopd** [fontforge/fontforge#3055]
The latest version available in the PPA for Ubuntu trusty looks like this:

![screenshot from 2017-04-15 21-26-44](https://cloud.githubusercontent.com/assets/2480569/25066296/5c3b316e-2222-11e7-9e50-1bdb70660b0b.png)

Would look so much less 90s if it was using this look:

![fontforge](https://cloud.githubusercontent.com/assets/2480569/25069972/b857cbce-2290-11e7-8806-3a70da35ce1b.png)

**Comment by JoesCat** [comment]
Make FontForge look good, ...or make FontForge work good... ;-)
If you are pointing-out a problem - then there are 800+ functional issues that have priority :-(
but if you are providing a patch - it could be reviewed by several maintainers :-)

**Comment by probonopd** [comment]
Oh, and Gtk+ or Qt should be used... relating to look good _and_ work good... :-)

**Comment by JoesCat** [comment]
Sometimes, what initially appears to be a ten minute fix, leads into something more involved ;-)
You may want to post some pngs for feedback.
Personally, I like the retro look, but then again, we don't know what you suggest, maybe better.
Take your time. The code itself is interesting as well.

**Comment by ahyangyi** [comment]
Wait, I actually prefer the old splash screen...

By the way, what made you feel the splash screen as 90s?

**Comment by probonopd** [comment]
@ahyangyi while this is (also) a matter of personal preference, the application and the website have no resemblance of each other...

**Comment by jmckean83** [comment]
Regardless of whether you like or dislike the look of the current splash screen (personally, I think it's horrible), there are some real issues with the way it displays -- at least on Windows. The text is completely jumbled, and the graphic part contains outdated copyright information. Is it perhaps even technically a misrepresentation to include copyright attributions to George Williams at this point in its development? Of course functionality is the priority, but being mindful of superficial, aesthetic concerns now and then is perhaps not a bad idea--especially if we want to keep FontForge alive in part by appealing to new users. Despite the old adage, a lot of people DO judge books by their covers.
![2017-04-17](https://cloud.githubusercontent.com/assets/24866207/25104129/265c49a4-238d-11e7-91d6-d551b5868015.png)

**Comment by frank-trampe** [comment]
It's not solely a Windows issue. I think that the leading character of the git hash gets cropped on other platforms. I have a lot of other stuff on my to-do list, but I would like to see at least that fixed.

**Comment by khaledhosny** [comment]
Just kill the splash screen, it serves no purpose. There is a preference to disable it, turn it on by default and forget about it. That is ≈1½ minuets work.

**Comment by probonopd** [comment]
Don't forget the About screen, too.

**Comment by probonopd** [comment]
![ffsplash1](https://user-images.githubusercontent.com/2480569/49190330-cf4f5a80-f369-11e8-80a3-a968aa03ccaf.png)
![ffsplash2](https://user-images.githubusercontent.com/2480569/49190331-cf4f5a80-f369-11e8-8d07-bee8a84f5e94.png)
![ffsplash3](https://user-images.githubusercontent.com/2480569/49190333-cf4f5a80-f369-11e8-8b20-f9fcebe3e1d0.png)

**Comment by ctrlcctrlv** [comment]
I have no problem with changing the images, but I don't think the text should be changed. Even at this late date, almost the entire codebase was written by the original author. 

(I've always found the text to be heartwarming as well, it always makes me smile.)

**Comment by JoesCat** [comment]
> (I've always found the text to be heartwarming as well, it always makes me smile.)

...now that's someone that understands ;-)

...I guess to appease those that prefer bland, maybe adding a checkmark in one of the menus to turn-off the splashscreen .... otherwise, I'd prefer and vote for "it stays".

**Comment by FloraCanou** [comment]
(If opinions are welcome...)
Not everyone has that nostalgic mindset. The modern-looking images are more delightful, like a breeze and basically fit the trend in the digital industry, which is flatness, clarity and simplicity. Inspect our rivals and you'll learn. 
As for the text, maybe it can be preserved, but it really should be showed only to those who are interested, who'd like to know the story. Otherwise it's can be a distractor, a cliché that sometimes gets you upset.

**Comment by probonopd** [comment]
For the sake of clarity, I was merely suggesting to change the picture (consisting of the 3 images posted above which can be used as a drop-in replacement), I was _not_ suggesting to change the text.

**Comment by probonopd** [comment]
Why on earth is the splash screen image apparently hardcoded in source code

https://github.com/fontforge/fontforge/blob/432761693527da966d072e3ade6d942b863a005d/fontforgeexe/splashimage.c

How can this file be re-generated?

**Comment by probonopd** [comment]
What are these files for when they are apparently not used at all?

- contrib/admintools/ffsplashbase.png
- fontforgeexe/pixmaps/2012/ffsplash1.png
- fontforgeexe/pixmaps/2012/ffsplash2.png
- fontforgeexe/pixmaps/2012/ffsplash3.png
- fontforgeexe/pixmaps/tango/ffsplash1.png
- fontforgeexe/pixmaps/tango/ffsplash2.png
- fontforgeexe/pixmaps/tango/ffsplash3.png

**Comment by JoesCat** [comment]
> For the sake of clarity, I was merely suggesting to change the picture (consisting of the 3 images posted above which can be used as a drop-in replacement) to match the more modern look of the website, I was not suggesting to change the text.

Understandable.
We have a large audience, with different tastes, different preferences, different needs. We have had patches pushed in, and pulled out. For example, anyone remember 3d theme?

Themes is a pretty big change, noticed by everyone.
The splashscreen is, I think, an even more noticeable change, especially this particular splashscreen.
I think it would be an error to take it out, but there are others here that hold other opinions as well.

Here's a suggestion.
1st run, this splashscreen (original story), 2nd run, 2nd splashscreen.
...but why stop there?.... go for four, eight, (16 maybe too many) different splash screens, then return back to 1st again. Each screen have a different theme, reason/story for existing....
...and for those that see no reason in having splashscreens, turn it off.
What can those other splash screens have? Don't know...be creative...maybe something about fonts?

**Comment by ctrlcctrlv** [comment]
The text has deep sentimental meaning to me. That's strange to some, fine. But I grew up using this software. I'm 23 and had a lot of fun with it as a teenager and have created a few fonts now. I really don't understand why changing it is even on the table. I learned OpenType with FontForge. This is bikeshedding at its worst.

We definitely don't need tons of splash screens. Let's just change the image to match the current state of the software. But changing the text is a betrayal of the author's intent.

I'm sure someone can psychoanalyze why I feel so strongly about this... :stuck_out_tongue:

**Comment by probonopd** [comment]
I am only talking about the image.

**Comment by frank-trampe** [comment]
This isn't quite bike-shedding. Bike-shedding has three problems: a low expertise bar for participation, an unclear standard for a better outcome, and low importance. This issue meets the first two criteria, but not the third. This is, although it pains me to say it, a rather important matter. It's the first foot forward for FontForge and makes a big statement. Is FontForge fancy and shiny and modern or does it at least aspire to be with some success? Does it have a rich historical legacy? Does FontForge honor its creator? I'll share my own personal opinions on the matter, but current policy is to refrain from changes without a strong consensus, which I don't see here yet.

**Comment by frank-trampe** [comment]
FontForge is still ancient under the hood and has a lot of antiquated trim, and it is probably still 90% the work of George Williams. I think that the current splash screen is truer to its identity than anything that looks sleek or modern. I don't feel strongly this way myself, so any persuasion ought to be aimed at the other people opposing this change.

**Comment by JoesCat** [comment]
On December 4, 2018 10:25:22 AM probonopd wrote:
> Currently the look and feel is _inconsistent_, the icon and website
> (modern, sleek, professional) does not _match_ the splash picture (low
> quality but "historic looking").

Take a look in /usr/docs and you'll see it is not in sync with the website.

As Frank mentioned, you need to take a look under the hood, and you'll see 
the code is probably 90% George's ...and to be fair about it, the existing 
code also has helped in creating the next version code easier if you have 
some sort of a template to follow, compared to going from scratch.

A good doctor will tell you it's probably ten times harder to add something 
than it is to cut something out, and I'd say the same goes here. It's easy 
to cut some code out, or repaint over some rust and say "accomplished!" vs, 
unravelling patches on patches, figure out intended destination, and aim for 
that destination with improved code if needed.

When 90% of the code is upgraded, this topic can have more significance.
...but for now, it's simply putting fresh paint on rust.
Let's improve FontForge first.

**Comment by brigazvi** [comment]
@frank-trampe @JoesCat 
I do not agree with many of the things said here,
But, even if you can not technically replace the image, at least update the text to 2000-2019.
By ignoring such basic things, we make Fontforge look ridiculous.


(I very much love Fontforge and very much thank you for your investment in its development.)

**Comment by ctrlcctrlv** [comment]
Hello friends &mdash;

I've got a fix for this, which I will PR in the next few hours. Here's what I've done:

* made FontForge use the year it's being compiled at as the year in the dialog and terminal output
* changed the image to the one by @probonopd 
* edited the text slightly to reflect GW is no longer main develper.

![ff splash](https://user-images.githubusercontent.com/838783/60420198-b5d10280-9c19-11e9-87e0-266525e8b5f0.png)

**Comment by frank-trampe** [comment]
@ctrlcctrlv, you seemed to be the one here most opposed to the change. Have you changed your mind?

**Comment by frank-trampe** [comment]
Oh, I see. You did keep the text, essentially.

**Comment by probonopd** [comment]
It may not have been clear from my original post, but my intention was never to suggest a change of the text, just the picture. So that it looks like the website.
