### ISSUE TITLE
Write geometry to TTF file.

### ISSUE THREAD

**Issue by TGISer** [fontforge/fontforge#3060]
Hi,
I want to write a program to write geometry to the TTF file, but  I'm not familiar with fontforge, how can i use fontforge to finish my work.
Thank you for your help!!!

**Comment by JoesCat** [comment]
Many people have contributed here: [designwithfontforge on github](https://github.com/fontforge/designwithfontforge.com)
The book to read is here: http://designwithfontforge.com
Character set is here: http://www.unicode.org/charts/
Please join the "user" mailing list: https://lists.sourceforge.net/lists/listinfo/fontforge-users
