### ISSUE TITLE
fontforge-20161005 installation problems

### ISSUE THREAD

**Issue by ipsmile** [fontforge/fontforge#3061]
My apology for this loooong message. You may skip most of those system messages. 

Trying to install the most recent version of FontForge on Linux Mint 18.1 and the installation process was terminated with an error:

-----------------------
$ sudo add-apt-repository ppa:fontforge/fontforge
You are about to add the following PPA:
More info: https://launchpad.net/~fontforge/+archive/ubuntu/fontforge
Press Enter to continue or Ctrl+C to cancel

Executing: /tmp/tmp.MM07W0Ko4A/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv-keys
63E0C3B9
gpg: requesting key 63E0C3B9 from hkp server keyserver.ubuntu.com
gpg: key 63E0C3B9: "Launchpad PPA for Package Maintainer" not changed
gpg: Total number processed: 1
gpg: unchanged: 1

$ sudo apt-get update
..........................

$ sudo apt-get install fontforge
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
fontforge-common libfontforge1 libgdraw4 libspiro0 libuninameslist0
Suggested packages:
python-fontforge
The following NEW packages will be installed:
fontforge fontforge-common libfontforge1 libgdraw4 libspiro0
libuninameslist0
0 upgraded, 6 newly installed, 0 to remove and 54 not upgraded.
Need to get 0 B/5,189 kB of archives.
After this operation, 21.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package fontforge-common.
(Reading database ... 420713 files and directories currently installed.)
Preparing to unpack .../fontforge-common_20161012-0ubuntu1xenial_all.deb ...
Unpacking fontforge-common (20161012-0ubuntu1xenial) ...
dpkg: error processing archive /var/cache/apt/archives/fontforge-common_20161012-0ubuntu1xenial_all.deb (--unpack):
trying to overwrite '/usr/share/fontforge/Adobe-Japan1-6.cidmap', which is also in package fontforge-extras 0.3-4ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package libgdraw4.
Preparing to unpack .../libgdraw4_20161012-0ubuntu1xenial_amd64.deb ...
Unpacking libgdraw4 (20161012-0ubuntu1xenial) ...
Selecting previously unselected package libspiro0:amd64.
Preparing to unpack .../libspiro0_1%3a0.5.20150702-4_amd64.deb ...
Unpacking libspiro0:amd64 (1:0.5.20150702-4) ...
Selecting previously unselected package libuninameslist0.
Preparing to unpack .../libuninameslist0_0.5.20150701-1_amd64.deb ...
Unpacking libuninameslist0 (0.5.20150701-1) ...
Selecting previously unselected package libfontforge1.
Preparing to unpack .../libfontforge1_20161012-0ubuntu1xenial_amd64.deb ...
Unpacking libfontforge1 (20161012-0ubuntu1xenial) ...
Selecting previously unselected package fontforge.
Preparing to unpack .../fontforge_20161012-0ubuntu1xenial_amd64.deb ...
Unpacking fontforge (20161012-0ubuntu1xenial) ...
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for menu (2.1.47ubuntu1) ...
Errors were encountered while processing:
/var/cache/apt/archives/fontforge-common_20161012-0ubuntu1xenial_all.deb
**E: Sub-process /usr/bin/dpkg returned an error code (1)_**

-----------------------

Then, turned to the rpm package on the webpage:
http://fontforge.github.io/en-US/downloads/gnulinux-dl/
Found no rpm package to download.

Only the source code are available. So, this turn out to be a compile and rebuild exercises. :)
Downloaded the required and optional developing tool packages, and made through executing ./configure without errors.
The installation stopped at the "make" step and following is the received error messages:

-----------------------
$ make
make[1]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/collab'
make[1]: '.gitignore' is up to date.
make[1]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/collab'
make[1]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/pyhook'
make[1]: '.gitignore' is up to date.
make[1]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/pyhook'
make[1]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/mackeys'
make[1]: '.gitignore' is up to date.
make[1]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/mackeys'
make[1]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/osx'
make[1]: '.gitignore' is up to date.
make[1]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/osx'
make all-recursive
make[1]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005'
Making all in inc
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/inc'
make all-am
make[3]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/inc'
make[3]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/inc'
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/inc'
Making all in lib
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/lib'
GEN alloca.h
GEN arpa/inet.h
GEN fcntl.h
GEN limits.h
GEN locale.h
GEN stdint.h
GEN stdio.h
GEN stdlib.h
GEN string.h
GEN strings.h
GEN sys/socket.h
GEN sys/stat.h
GEN sys/time.h
GEN sys/types.h
GEN sys/uio.h
GEN time.h
GEN unistd.h
GEN wchar.h
make all-recursive
make[3]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/lib'
make[4]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/lib'
CC c-strtod.lo
CC dirname-lgpl.lo
CC basename-lgpl.lo
CC stripslash.lo
CC exitfail.lo
CC fd-hook.lo
CC getprogname.lo
CC progname.lo
CC sockets.lo
CC sys_socket.lo
CC tempname.lo
CC tmpdir.lo
CC unistd.lo
CC xmalloc.lo
CC xalloc-die.lo
CC xsize.lo
CC xvasprintf.lo
CC xasprintf.lo
CC asnprintf.lo
CC printf-args.lo
CC printf-parse.lo
CC vasnprintf.lo
CCLD libgnu.la
ar: u' modifier ignored sinceD' is the default (see U') make[4]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/lib' make[3]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/lib' make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/lib' Making all in libltdl make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/libltdl' make all-am make[3]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/libltdl' CC loaders/dlopen.lo CCLD dlopen.la ar:u' modifier ignored since D' is the default (seeU')
CC loaders/libltdlc_la-preopen.lo
CC libltdlc_la-lt__alloc.lo
CC libltdlc_la-lt_dlloader.lo
CC libltdlc_la-lt_error.lo
CC libltdlc_la-ltdl.lo
CC libltdlc_la-slist.lo
CCLD libltdlc.la
ar: u' modifier ignored sinceD' is the default (see `U')
make[3]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/libltdl'
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/libltdl'
Making all in Unicode
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/Unicode'
CC charset/libgunicode_la-alphabet.lo
CC charset/libgunicode_la-big5.lo
CC charset/libgunicode_la-big5hkscs.lo
CC charset/libgunicode_la-gb2312.lo
CC charset/libgunicode_la-iso_8859_10.lo
CC charset/libgunicode_la-iso_8859_11.lo
CC charset/libgunicode_la-iso_8859_13.lo
CC charset/libgunicode_la-iso_8859_14.lo
CC charset/libgunicode_la-iso_8859_15.lo
CC charset/libgunicode_la-iso_8859_16.lo
CC charset/libgunicode_la-iso_8859_1.lo
CC charset/libgunicode_la-iso_8859_2.lo
CC charset/libgunicode_la-iso_8859_3.lo
CC charset/libgunicode_la-iso_8859_4.lo
CC charset/libgunicode_la-iso_8859_5.lo
CC charset/libgunicode_la-iso_8859_6.lo
CC charset/libgunicode_la-iso_8859_7.lo
CC charset/libgunicode_la-iso_8859_8.lo
CC charset/libgunicode_la-iso_8859_9.lo
CC charset/libgunicode_la-jis201.lo
CC charset/libgunicode_la-jis.lo
CC charset/libgunicode_la-johab.lo
CC charset/libgunicode_la-koi8_r.lo
CC charset/libgunicode_la-ksc5601.lo
CC charset/libgunicode_la-mac.lo
CC charset/libgunicode_la-MacSymbol.lo
CC charset/libgunicode_la-win.lo
CC charset/libgunicode_la-ZapfDingbats.lo
CC libgunicode_la-ArabicForms.lo
CC libgunicode_la-char.lo
CC libgunicode_la-is_Ligature.lo
CC libgunicode_la-memory.lo
CC libgunicode_la-ucharmap.lo
CC libgunicode_la-unialt.lo
CC libgunicode_la-ustring.lo
CC libgunicode_la-utype.lo
CC libgunicode_la-gwwiconv.lo
CCLD libgunicode.la
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/Unicode'
Making all in gutils
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/gutils'
CC libgutils_la-divisors.lo
CC libgutils_la-dlist.lo
CC libgutils_la-fsys.lo
fsys.c: In function 'GFileGetAbsoluteName':
fsys.c:227:6: warning: ignoring return value of 'getcwd', declared with attribute warn_unused_result [-Wunused-result]
getcwd(dirname_,sizeof(dirname_));
^
fsys.c: In function 'u_GFileGetAbsoluteName':
fsys.c:524:6: warning: ignoring return value of 'getcwd', declared with attribute warn_unused_result [-Wunused-result]
getcwd(dirname_,sizeof(dirname_));
^
CC libgutils_la-g_giomime.lo
CC libgutils_la-gcol.lo
CC libgutils_la-gimage.lo
CC libgutils_la-gimageread.lo
CC libgutils_la-gimagereadbmp.lo
gimagereadbmp.c: In function 'readpixels':
gimagereadbmp.c:173:6: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(head->byte_pixels+i*ll,1,ll,file);
^
CC libgutils_la-gimagereadgif.lo
CC libgutils_la-gimagereadjpeg.lo
CC libgutils_la-gimagereadpng.lo
CC libgutils_la-gimagereadras.lo
CC libgutils_la-gimagereadrgb.lo
gimagereadrgb.c: In function 'GImageReadRgb':
gimagereadrgb.c:250:3: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(base->data + (header.height-1-i)*base->bytes_per_line,header.width,1,fp);
^
gimagereadrgb.c:304:7: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(a,header.width,1,fp);
^
gimagereadrgb.c:305:7: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(a,header.width,1,fp);
^
CC libgutils_la-gimagereadtiff.lo
CC libgutils_la-gimagereadxbm.lo
gimagereadxbm.c: In function 'GImageReadXbm':
gimagereadxbm.c:118:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(file,",");
^
CC libgutils_la-gimagereadxpm.lo
CC libgutils_la-gimagewritebmp.lo
CC libgutils_la-gimagewritegimage.lo
CC libgutils_la-gimagewritejpeg.lo
CC libgutils_la-gimagewritepng.lo
CC libgutils_la-gimagewritexbm.lo
CC libgutils_la-gimagewritexpm.lo
CC libgutils_la-gio.lo
CC libgutils_la-giofile.lo
CC libgutils_la-giohosts.lo
CC libgutils_la-giothread.lo
CC libgutils_la-giotrans.lo
CC libgutils_la-gnetwork.lo
CC libgutils_la-gutils.lo
CC libgutils_la-gwwintl.lo
CC libgutils_la-prefs.lo
CC libgutils_la-unicodelibinfo.lo
CCLD libgutils.la
CC libgioftp_la-gioftp.lo
CCLD libgioftp.la
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/gutils'
Making all in breakpad
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad'
Making all in server
make[3]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad/server'
make[4]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad/server'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad/server'
make[3]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad/server'
make[3]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad'
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/breakpad'
Making all in fontforge
make[2]: Entering directory '/home/aaabbb/FontForge/fontforge-20161005/fontforge'
CC libfontforge_la-activeinui.lo
CC libfontforge_la-asmfpst.lo
CC libfontforge_la-autohint.lo
CC libfontforge_la-autosave.lo
CC libfontforge_la-autotrace.lo
autotrace.c: In function '_SCAutoTrace':
autotrace.c:411:3: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
chdir(tempname);
^
autotrace.c: In function 'SFFromMF':
autotrace.c:784:2: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
chdir(tempdir);
^
CC libfontforge_la-autowidth.lo
CC libfontforge_la-autowidth2.lo
CC libfontforge_la-bezctx_ff.lo
CC libfontforge_la-bitmapchar.lo
CC libfontforge_la-bitmapcontrol.lo
CC libfontforge_la-bvedit.lo
CC libfontforge_la-collabclient.lo
CC libfontforge_la-clipnoui.lo
CC libfontforge_la-cvexport.lo
CC libfontforge_la-cvimages.lo
cvimages.c: In function 'SCImportPlateFile':
cvimages.c:204:5: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
fgets(buffer,sizeof(buffer),plate);
^
cvimages.c: In function 'SCImportFig':
cvimages.c:832:2: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
fgets(buffer,sizeof(buffer),fig);
^
cvimages.c: In function 'slurpcompoundguts':
cvimages.c:782:2: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig,"%d",&oc);
^
cvimages.c: In function 'slurpcompound':
cvimages.c:389:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig, "%*d %*d %*d %*d" );
^
cvimages.c: In function 'slurpelipse':
cvimages.c:477:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig, "%d %*d %*d %*d %*d %*d %*d %*d %*f %d %f %d %d %d %d %*d %*d %*d %*d",
^
cvimages.c: In function 'slurparc':
cvimages.c:423:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig, "%d %*d %*d %*d %*d %*d %*d %*d %*f %*d %d %d %d %f %f %d %d %*d %*d %d
^
cvimages.c: In function 'slurppolyline':
cvimages.c:520:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig, "%d %*d %*d %*d %*d %*d %*d %*d %*f %*d %*d %d %d %d %d",
^
cvimages.c: In function 'slurppoints':
cvimages.c:370:2: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig,"%d %d", &x, &y );
^
cvimages.c: In function 'slurpspline':
cvimages.c:742:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig, "%d %*d %*d %*d %*d %*d %*d %*d %*f %*d %d %d %d",
^
cvimages.c:756:2: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(fig,"%lf",&xs.s[i]);
^
CC libfontforge_la-cvundoes.lo
cvundoes.c: In function 'copybuffer2svg':
cvundoes.c:1437:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(ret,1,*len,svg);
^
cvundoes.c: In function 'copybuffer2eps':
cvundoes.c:1597:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(ret,1,*len,eps);
^
cvundoes.c: In function 'copybuffer2svgmult':
cvundoes.c:1504:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(ret,1,*len,svg);
^
CC libfontforge_la-dumpbdf.lo
CC libfontforge_la-dumppfa.lo
CC libfontforge_la-effects.lo
CC libfontforge_la-encoding.lo
CC libfontforge_la-featurefile.lo
CC libfontforge_la-flaglist.lo
CC libfontforge_la-fontviewbase.lo
CC libfontforge_la-freetype.lo
CC libfontforge_la-fvcomposite.lo
CC libfontforge_la-fvfonts.lo
CC libfontforge_la-fvimportbdf.lo
fvimportbdf.c: In function '_SFImportBDF':
fvimportbdf.c:2213:2: warning: ignoring return value of 'system', declared with attribute warn_unused_result [-Wunused-result]
system(buf);
^
fvimportbdf.c: In function 'pcf_properties':
fvimportbdf.c:1456:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(strs,1,strl,file);
^
fvimportbdf.c: In function 'slurp_header':
fvimportbdf.c:503:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d",&cnt);
^
fvimportbdf.c:510:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf, "%d", &cnt );
^
fvimportbdf.c:519:2: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
fgets(buffer,sizeof(buffer),bdf );
^
fvimportbdf.c: In function 'PcfReadBitmaps':
fvimportbdf.c:1663:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(bitmap,1,sizebitmaps,file);
^
fvimportbdf.c: In function 'PcfReadEncodingsNames':
fvimportbdf.c:1718:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(string,1,stringsize,file);
^
fvimportbdf.c: In function 'AddBDFChar':
fvimportbdf.c:281:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d",&enc);
^
fvimportbdf.c:289:7: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d",&enc);
^
fvimportbdf.c:295:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d %*d",&width);
^
fvimportbdf.c:297:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d %*d",&vwidth);
^
fvimportbdf.c:299:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d %d",&swidth);
^
fvimportbdf.c:301:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d %d",&swidth1);
^
fvimportbdf.c:303:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(bdf,"%d %d %d %d",&hsz, &vsz, &xmin, &ymin );
^
CC libfontforge_la-fvmetrics.lo
CC libfontforge_la-ftdelta.lo
CC libfontforge_la-glyphcomp.lo
CC libfontforge_la-groups.lo
CC libfontforge_la-http.lo
CC libfontforge_la-ikarus.lo
ikarus.c: In function 'SFReadIkarus':
ikarus.c:603:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(fnam,1,12,file); / 6 words of filename /
^
ikarus.c:604:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(fullname,1,80,file); / 40 words of fontname (human readable) /
^
CC libfontforge_la-langfreq.lo
CC libfontforge_la-lookups.lo
CC libfontforge_la-macbinary.lo
macbinary.c: In function 'IsResourceInBinary':
macbinary.c:2951:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(header,1,4,f);
^
macbinary.c: In function 'IsResourceInHex':
macbinary.c:3041:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(header,1,20,binary);
^
macbinary.c:3047:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(header,1,4,binary);
^
macbinary.c: In function 'SearchPostScriptResources':
macbinary.c:2024:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(buffer,1,rlen,f);
^
macbinary.c: In function 'BuildFondList':
macbinary.c:2297:6: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(name,1,ch1,f);
^
CC libfontforge_la-macenc.lo
CC libfontforge_la-mathconstants.lo
CC libfontforge_la-mm.lo
CC libfontforge_la-namelist.lo
CC libfontforge_la-nonlineartrans.lo
CC libfontforge_la-noprefs.lo
CC libfontforge_la-nouiutil.lo
CC libfontforge_la-nowakowskittfinstr.lo
CC libfontforge_la-ofl.lo
CC libfontforge_la-othersubrs.lo
CC libfontforge_la-palmfonts.lo
palmfonts.c: In function 'SFReadPalmPdb':
palmfonts.c:345:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(name,1,32,file);
^
CC libfontforge_la-parsepdf.lo
parsepdf.c: In function 'FindObjectsFromXREFObject':
parsepdf.c:990:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf( pdf, "%d %d", &pc->root, &bar );
^
parsepdf.c: In function 'pdf_skipobjectheader':
parsepdf.c:424:5: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf( pc->pdf, "%d %d obj" );
^
parsepdf.c: In function 'pdf_findobject':
parsepdf.c:523:3: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf( data, "%d %d", &o, &offset );
^
parsepdf.c: In function 'seektrailer':
parsepdf.c:144:6: warning: ignoring return value of 'fscanf', declared with attribute warn_unused_result [-Wunused-result]
fscanf(pdf,"%d %ld",&pc->root,&bar);
^
CC libfontforge_la-parsepfa.lo
CC libfontforge_la-parsettfatt.lo
parsettfatt.c: In function 'read_statetable':
parsettfatt.c:4057:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(st->classes,1,st->nglyphs,ttf);
^
parsettfatt.c:4139:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(st->state_table,1,st->nstatesst->nclasses,ttf);
^
parsettfatt.c:4145:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(st->transitions,1,st->nentriesst->entry_size,ttf);
^
CC libfontforge_la-parsettfbmf.lo
parsettfbmf.c: In function 'ttfreadbmfglyph':
parsettfbmf.c:197:3: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(bdfc->bitmap+ibdfc->bytes_per_line,1,bdfc->bytes_per_line,ttf);
^
parsettfbmf.c:236:3: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(bdfc->bitmap+ibdfc->bytes_per_line,1,bdfc->bytes_per_line,ttf);
^
CC libfontforge_la-parsettf.lo
parsettf.c: In function 'PickTTFFont':
parsettf.c:646:13: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
asprintf(&names[i], "<Unknown font name %d>", i+1);
^
parsettf.c: In function 'readtyp1glyphs':
parsettf.c:4033:2: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(buffer,1,sizeof(buffer),ttf);
^
parsettf.c: In function 'TtfCopyTableBlindly':
parsettf.c:5479:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
fread(tab->data,1,len,ttf);
^
CC libfontforge_la-parsettfvar.lo
CC libfontforge_la-plugins.lo
**In file included from plugins.c:29:0:
../inc/pluginloading.h:31:18: fatal error: ltdl.h: No such file or directory
compilation terminated.
Makefile:2043: recipe for target 'libfontforge_la-plugins.lo' failed
make[2]: *** [libfontforge_la-plugins.lo] Error 1
make[2]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005/fontforge'
Makefile:1584: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/aaabbb/FontForge/fontforge-20161005'
Makefile:1420: recipe for target 'all' failed
make: *** [all] Error 2**

------------------------------------------------

I copied /fontforge-20161005/libltdl/ltdl.h to directory /fontforge-20161005/inc/ and the reported error saying lt_system.h: No such file or directory. Copied /fontforge-20161005/libltdl/libltdl/lt_system.h to the /fontforge-20161005/inc/ directory, then received  lt_error.h:No such file or directory. I am sure I could move those files and directory over to get through.

The reported missing header files in the process are all located in the source package under the directory /fontforge-20161005/
/fontforge-20161005/inc/pluginloading.h
/fontforge-20161005/libltdl/ltdl.h
/fontforge-20161005/libltdl/libltdl/lt_system.h
/fontforge-20161005/libltdl/libltdl/lt_error.h
/fontforge-20161005/libltdl/libltdl/lt_dlloader.h

There seems to be inconsistencies among the header file references of the included files and the actual locations of these header files.

Appreciate any helps for the fixes and pointing to the right directions.

Ip

**Comment by frank-trampe** [comment]
Uninstall all FontForge packages that ship with your distribution before trying to install from the PPA. Sorry for the delay; this one slipped through the cracks. In the future, ask on the mailing list for a quicker response.

**Comment by afonts** [comment]
I ran in to similar problem building fontforge-2.0.20170731 ...
Here is the make error:
**In file included from plugins.c:29:0:
../inc/pluginloading.h:31:18: fatal error: ltdl.h: No such file or directory
 #include <ltdl.h>
                  ^
compilation terminated.**
make[2]: *** [libfontforge_la-plugins.lo] Error 1
make[2]: Leaving directory `/home/here/test001/fontforge-2.0.20170731/fontforge'
make[1]: *** [all-recursive] Error 1**
make[1]: Leaving directory `/home/here/test001/fontforge-2.0.20170731'
make: *** [all] Error 2**

I fixed the error by installing the "libtool-ltdl-devel" rpm. 
Now I can 'make' without errors.
