### ISSUE TITLE
URGENT: File become too big to open? 

### ISSUE THREAD

**Issue by CiaranSaward** [fontforge/fontforge#3062]
- [X ] Screenshots included
Fontforge Version 20:55 AWST (4th Oct 2016). Operating system 64-bit Windows 8.1, 8g RAM. 

When attempting to open a font I've been working on, that had until recently been performing okay (if fairly slowly), the loading window seems to get a third of the way through loading the glyphs then an error message pops up saying 'fontforge.exe has stopped working.' It is consistently reaching this point then stopping working.

The file in question, 'Greyletter.sfd', is 1.93 GB. When I open up a smaller file called 'test.sfd' which is 5.8 KB, fontforge opens it very comfortably, so I suspect it's an issue with the file size. I've attached screenshots of the task manager as fontforge attempts to open the Greyletter file, and the memory shoots up trying to deal with it. 
Opening 'test' file from within font-forge:
![1](https://cloud.githubusercontent.com/assets/28228929/25566883/abc20398-2dda-11e7-9c06-050f49c078eb.png)
Succesfully opened:
![2](https://cloud.githubusercontent.com/assets/28228929/25566887/abceb2dc-2dda-11e7-8560-039f77fa8453.png)
Memory use for vcxsrv.exe only at 18.7 MB:
![3](https://cloud.githubusercontent.com/assets/28228929/25566885/abc5b146-2dda-11e7-8d33-8aba1dea1996.png)
Processing performance when attempting to open 'Greyletter' project file from within fontforge: (Computer audibly humming/whirring)
![4](https://cloud.githubusercontent.com/assets/28228929/25566886/abca0282-2dda-11e7-955f-a68bdb3a63d2.png)
![5](https://cloud.githubusercontent.com/assets/28228929/25566882/abbf8f96-2dda-11e7-88a9-eff14a3bcbf0.png)
![6](https://cloud.githubusercontent.com/assets/28228929/25566888/abe9c702-2dda-11e7-8a3f-3fdeee16e196.png)
![7](https://cloud.githubusercontent.com/assets/28228929/25566889/abefc5f8-2dda-11e7-8934-b15890ed6f1c.png)
Stops working:
![8](https://cloud.githubusercontent.com/assets/28228929/25566884/abc39014-2dda-11e7-89fd-533ba0079de1.png)

The 'Greyletter' file only contains about 15 glyphs but in most of these glyphs there is also an reference image contained in the second layer. I suspect it is these images that might be increasing the file size? The image itself is about 5000 KB and there are copies of it on most glyphs. 

Is there is way to open an earlier autosaved version of the file? Perhaps this would get around the issue if it is based on the large file size.  

If I succesfully open the file I can delete the images to try and reduce the file size to a workable level but it seems currently too big for me to open to make these changes. 

Any advice and help would be really really appreciated as the file is a project for the final year of my uni degree: deadline on Friday! 

P.S 
Don't know if this information will mean anything useful but the VcXsrv. X Server Log looks like this:

Welcome to the VcXsrv X Server
Vendor: The VcXsrv Project
Release: 1.14.2.1

Contact: marha@users.sourceforge.net

DefineSelf - Ciaran-Laptop has 1 usable IPv4 interface...
 address 192.168.0.5
DefineSelf - Ciaran-Laptop has IPv6 addresses...
 fe80::89f:a883:1149:347f 2a02:c7d:9207:c400:1d08:eb66:3fd8:8c7a 2a02:c7d:9207:c400:89f:a883:1149:347f fe80::18dc:3bff:3f57:fffa 2001:0:4137:9e76:18dc:3bff:3f57:fffa fda6:cdb7:9403:0:1d08:eb66:3fd8:8c7a fda6:cdb7:9403:0:89f:a883:1149:347f
Initializing built-in extension Generic Event Extensio
Initializing built-in extension SHAPE
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension XFree86-Bigfont
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension GLX
LoadPreferences: C:\Program Files (x86)\FontForgeBuilds\/.XWinrc not found
LoadPreferences: Loading C:\Program Files (x86)\FontForgeBuilds\bin\VcXsrv\system.XWinrc
(II) AIGLX: enabled GLX_SGI_make_current_read
(II) AIGLX: enabled GLX_MESA_copy_sub_buffer
(II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
(II) AIGLX: enabled GLX_SGIX_pbuffer
(II) AIGLX: enabled GLX_ARB_multisample and GLX_SGIS_multisample
(II) 67 pixel formats reported by wglGetPixelFormatAttribivARB
(II) AIGLX: Set GLX version to 1.4
(II) GLX: Initialized Win32 native WGL GL provider for screen 0
[dix] Could not init font path element fonts/misc/, removing from list!
[dix] Could not init font path element fonts/TTF/, removing from list!
[dix] Could not init font path element fonts/OTF, removing from list!
[dix] Could not init font path element fonts/Type1/, removing from list!
[dix] Could not init font path element fonts/100dpi/, removing from list!
[dix] Could not init font path element fonts/75dpi/, removing from list!
[dix] Could not init font path element fonts/cyrillic/, removing from list!
[dix] Could not init font path element fonts/Speedo/, removing from list!
[dix] Could not init font path element fonts/terminus-font/, removing from list!
winBlockHandler - pthread_mutex_unlock()

**Comment by jtanx** [comment]
It might be hitting a memory limit - you could try a 64-bit build from here: http://fontforgebuilds.sourceforge.net/ - http://sourceforge.net/projects/fontforgebuilds/files/x86_64/Portable/FontForge-mingw-w64-x86_64-1abf23-r1.7z

But **please** note:
* I don't recommend using the 64-bit Windows build long term since it hasn't been tested all too much
* Please make a backup of your sfd before using this
* If this doesn't work, then you'll have to manually remove the image data (not sure about this)

**Comment by CiaranSaward** [comment]
Thanks a lot jtanx! I'll make a back up then try the 64bit build tomorrow to get into the file and change it. Does 'back up' in this case just mean making another copy of the file or do I need to do anything fancy? Also does your recommendation to try a 64 bit build mean that the default fontforge is 32-bit? And how would I go about switching back to a 32 bit set-up afterwards?

**Comment by jtanx** [comment]
Yep just make sure you have a copy of the sfd before making changes.

The default Windows install is 32 bit. The 64 bit version I linked to is just a 7-zip archive, so you just have to extract it to somewhere and run it directly. To switch back to the normal one, just delete your extracted folder and launch FontForge as you normally do.

**Comment by CiaranSaward** [comment]
Downloaded and ran the 64 bit version, succesfully loaded up a copy of the file, deleted the images and the file size is now down to around 600 MB, and I can open it again with the 32 bit version. 

Thanks so much for your quick response jtanx, you're my saviour!

**Comment by jtanx** [comment]
I'm glad it worked! Although 600MB is still a very large file so I wonder if there might still be some images remaining somewhere.

In any case, just remember to keep backups of your sfd regularly, so that you have something to fall back to easily.

**Comment by frank-trampe** [comment]
Since the user-specific problem is resolved and we aren't going to work on supporting gigabyte typefaces anytime soon, I'm going to close the issue.
