### ISSUE TITLE
Despairing: All Glyphs Spontaneously Shrunk?! (+ Copying between files?)

### ISSUE THREAD

**Issue by CiaranSaward** [fontforge/fontforge#3063]
[X ] Screenshots included
Fontforge Version 20:55 AWST (4th Oct 2016). Operating system 64-bit Windows 8.1, 8g RAM.

Hello again, I'm working to a really tight deadline and desperately need some more assistance .

Whilst working on this project, fontforge unexpectedly stopped working and had to close. When I opened the recovery file all the glyphs had shrunk to maybe about half their size. You can see this in the font window, and in the metrics window (screenshots below), where there is a large amount of space now between top of the canvas and the letters. 

I don't know what might have caused this, but ist here any way of uniformly scaling them all back up? 

As a side quesion but equally important - something strange happened where my capital A was suddenly replaced by lower case z - I'm trying to paste the capital A glyph from a backup copy of the project, but can't seem to paste from one project to another. Is there any way to get round this?

Again, all advice and help would be really really appreciated as the file is a project for the final year of my uni degree: deadline on Friday!

Copy 4 of the project, glyphs normal size
![b1](https://cloud.githubusercontent.com/assets/28228929/25664686/442df45e-3013-11e7-9fb0-d42310ac05a1.png)
![b2](https://cloud.githubusercontent.com/assets/28228929/25664685/442b43a8-3013-11e7-91ea-9388b3ebc468.png)

Copy 5 saved from project recovery after Fontforgestopped working and closed. Letters shrunk.
![b3](https://cloud.githubusercontent.com/assets/28228929/25664688/44353016-3013-11e7-8298-3f698c4cd5ab.png)
Size difference not due to zoom in/out - input at default view for both metric windows.
![b4](https://cloud.githubusercontent.com/assets/28228929/25664689/445dabea-3013-11e7-9670-4516fc3307e9.png)

**Comment by frank-trampe** [comment]
@CiaranSaward, are the numerical dimensions in the glyph edit window actually different, or are the glyphs just displaying smaller? And how much work did you complete between the last save point and the recovery?

**Comment by CiaranSaward** [comment]
Thanks for your reply. Upon inspection the numerical dimensions do actually seem to be the same, so I guess they must just be displaying smaller. How can I get them to display larger? 

Between those two versions I've displayed I only lost 1 letter, although technically  I lost 7 glyphs after the recovery - for some reason it recovered them once, then after I closed and open, the recovered file was missing numerals 1-7. Hey ho. Are those recovery files stored anywhere?

Also do you know whether it is possible to copy and paste glyphs between projects?

**Comment by frank-trampe** [comment]
@CiaranSaward, the problem may be in the file metadata. If you open an sfd file in a text editor, you will notice that it's sort of human readable. You might want to try splicing the glyph data (most of the content) from the new file) with the main header from the old file.

@jtanx, where is the FontForge user directory on Windows?

**Comment by CiaranSaward** [comment]
Thanks - how would I go about doing that splicing?

**Comment by CiaranSaward** [comment]
I've got the glyphs to display at a larger size by selecting 'Fit to bounding box' in the view menu of the main window.

**Comment by jtanx** [comment]
@frank-trampe it should be under `%APPDATA%\FontForge`, which on all recent (i.e. non XP) versions of Windows, means something like `C:\Users\user_name\AppData\Roaming\FontForge`
