### ISSUE TITLE
(In MS-Windows)Glyph Info Window, wont let me Insert (special character)Text from the numlock +alt xxxx or clipboard

### ISSUE THREAD

**Issue by dernyn** [fontforge/fontforge#3068]
(MS-Windows clipboard to FontForge problem)
I'm using MS-windows to modified an existing TTF font, which is missing the associated keyboard character in the "Unicode Char:" TextBox field, on the Glyph Info Window... If I try to copy and paste the character from native MS-windows into FontForge It claims the character already exist, which it does not. With the general error "Only a single Character allowed", It does'nt seem to matter what character I copy and paste, the error is the same, even though there is nothing linked or using that particular character.

(MS-Windows keyboard insertion of Special Characters problem)
So My work-around was to try to Insert the character via the native MS-windows feature using:  Num-Lock(activated key) then holding Alt key pressed and typing the 4 digit character number of the special character.

version 20:55 awst 4-Oct-2016
windows 8, and windows 10

Is there another way to Insert special character where VcXsrc wont ignore it ?

**Comment by jtanx** [comment]
What unicode character are you trying to use? I can paste unicode values ok.

**Comment by dernyn** [comment]
it's a special character, the euro sign, u+20ac within 0x80 in the C1 control area.

**Comment by dernyn** [comment]
the assigned u+20ac location is not defined, has no glyph and has no name or unicode value assign to it

**Comment by jtanx** [comment]
I think it needs to have a valid slot for you to be able to use that location. What encoding is your font in?

**Comment by dernyn** [comment]
there is no need for the slot if I'm just trying to insert a character that is valid via keyboard........
this is the encoding...cp437 and western latin 1 (1252)

**Comment by jtanx** [comment]
Hmm that's a strange one. Sometimes I can reproduce the issue, but other times it works.

**Comment by dernyn** [comment]
sorry, I'm using ISO-8859-1 Latin 1 and Windows Latin"ANSI" which is 1252
I've tried different encoding and it does not accept the copying and pasting of the special character

**Comment by jtanx** [comment]
Just a theory, but because you're trying to do this in the C1 control area, FF isn't displaying any visual representation of that character in the 'Unicode Char' window, so that input looks empty, when it's not. So when you paste the second character in, it will complain of having two characters there even though it appears that only one is there.

**Comment by jtanx** [comment]
Yeah if you ctrl+a the field and press backspace before pasting, it works.

**Comment by dernyn** [comment]
ahh..it works only when I press backspace before pasting...how come?
It tries to create the U+20ac slot...
but it wont let me assigned the character to the 0x80 slot, which is what i want

**Comment by jtanx** [comment]
I don't think that setting has the meaning you're after. You want the Euro symbol in 0x80? Just use Windows Latin "ANSI" encoding. Otherwise you're using a custom encoding.

**Comment by dernyn** [comment]
I got the email notification but your last update did not get posted on the comments...
I have switch to custom encoding and it still not letting me assign slot U+0080 with the euro sign character, with it trying to change it to U+20AC

**Comment by typedesigner** [comment]
One should correct this bug and publish new fontforge (Windows) version.
[http://fontforge.github.io/en-US/downloads/](url)

**Comment by jtanx** [comment]
Looks like it now displays a placeholder
