### ISSUE TITLE
Fontforge does not recongnize BMP Font Image as valid fromar

### ISSUE THREAD

**Issue by xchellx** [fontforge/fontforge#3069]
I have this font in bitmap format (BMP) ripped from an old game and I aiming to retrace the inage and fix it up to create ttf font out of it. However, when I open the bitmap it says "filename.bmp is bot in a known format.". I asked this before on google plus and was redirected here to ask. My font bitmap file: http://www.mediafire.com/view/7j61191vippistz/edit_test_bitmap.bmp

- [ x ] Screenshot - error dialog: http://imgur.com/a/IPDJS 
- [ x ] The FontForge version and the operating system you're using - HP Workstation Windows 7 x64 with fontforge version Tue, Oct 4, 2016.
- [ x ] The behavior you expect to see, and the actual behavior I expect it to open the font.
- [ x ] Steps to reproduce the behavior - take any image of a font in bmp bitmap format using the open window and get an error message.
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jrbastien** [comment]
I think you are confusing a font in bitmap format and actual bitmap files.  These are not the same.  The font bitmap file you provided is not a font file.

See https://en.wikipedia.org/wiki/Computer_font#Bitmap_fonts
