### ISSUE TITLE
Does fontforge have a means to create alternative styles for a glyph?

### ISSUE THREAD

**Issue by Puddingboy** [fontforge/fontforge#3071]
Like handwritten fonts can have different characters to match styles.
https://www.designcuts.com/tutorials/using-font-swashes/

Does fontforge have a means to create alternative styles for a glyph?

**Comment by frank-trampe** [comment]
This is easiest implemented by adding the alternates under appropriate names and then importing a feature file with the aalt feature (or whichever sort of substitution you want to mandate/offer). See [here](http://opentypecookbook.com/common-techniques.html).

Usage questions get better responses on the [mailing list](https://lists.sourceforge.net/lists/listinfo/fontforge-users). If you have further questions, I would suggest going there.
