### ISSUE TITLE
FontForge won't launch on Mac 10.12.5

### ISSUE THREAD

**Issue by MarieGeipel** [fontforge/fontforge#3081]
I've installed the FontForge and XQuartz on my Mac 10.12.5 although the app appears and disappeared with no error messages. I do not have any developper skills, so hopefully it's an easy fix if that's a fixable bug. 
![screen shot 2017-06-08 at 3 47 45 pm](https://user-images.githubusercontent.com/29288101/26948389-3f1764b0-4c64-11e7-89f1-321bf97b1d69.png)

**Comment by frank-trampe** [comment]
@MarieGeipel, sorry for the problems. I don't have a Macintosh running that version of the system software. I'll probably need to spin up a virtual machine in order to test. Do other X11 applications, like Inkscape, work for you in that environment?
