### ISSUE TITLE
Question: Fontforge DrawingTools

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3082]
@davelab6 @jtanx @frank-trampe 

[http://designwithfontforge.com/en-US/Using_the_Fontforge_Drawing_Tools.html](url)
If you want to place breaks in your letterforms, as with the lower-left part of the ‘g’ below – that’s typically where you will want to use a Coin (besides for drawing lines):

![bezier_sample_4](https://user-images.githubusercontent.com/18243844/26963989-de028128-4cef-11e7-8a14-f422bdf800c9.png)

Note: As you can see, when setting breaks with a Coin, the direction of each handle should be tangent to the curve where it arrives.

**My Question:** how does it work? Where in the FontForge menu can I make this visible?

**Comment by frank-trampe** [comment]
@typedesigner, I've read this several times, and I still don't understand what you're saying. Could you perhaps draw what you expect to happen and what is happening?

**Comment by typedesigner** [comment]
@frank-trampe This is a quote: http://designwithfontforge.com/en-US/Using_the_Fontforge_Drawing_Tools.html

**My Question:** how does it work? Where in the FontForge menu can I make this **"Coin"** visible?

**Comment by JoesCat** [comment]
Hi @typedesigner,
Had to look at "coin" to understand it, and it refers to LibSpiro.
First, if you do not have LibSpiro installed yet, you need to install it first.
After installing LibSpiro, you will need to make clean, and rebuild FontForge (this is where I like 20120731 linking and we need to reinsert the removed code to avoid this rebuild step altogether).
If/when you have LibSpiro available, you activate it through the LibSpiro menu.
The LibSpiro curve functions numbercrunch differently from the built-in FontForge curve drawing functions.
The reason for indicating this is I see the drawing handles you have on your example.

**Comment by typedesigner** [comment]
@JoesCat I use: http://fontforge.github.io/en-US/downloads/windows-dl/
LibSpiro is a part of FontForge or?
![bezier_sample_4](https://user-images.githubusercontent.com/18243844/27771181-ec7860d0-5f49-11e7-9a20-6739b95e5e08.png)
My question is how can I see these lines?

**Comment by davelab6** [comment]
The purple and green lines are hints. Autohinter the glyph and check the
view, show menu settings

**Comment by frank-trampe** [comment]
Wait, so, @typedesigner, is any of the query about the coin point type? Spiro adds features, but the basic point type (allowing non-aligned tangents) is on the standard FontForge palette (the square point on a corner of a path). Is that not showing for you? If so, you've probably accidentally activated Spiro (by clicking the spiral icon), and you can get back to the normal drawing tools by clicking the generic Bezier icon.

**Comment by typedesigner** [comment]
@davelab6 I know that green and purple lines are auto hints. This is very good funktion in FontForge.

![unbenannt](https://user-images.githubusercontent.com/18243844/27780370-d09a1ae6-5fc8-11e7-9221-35091a83c4ef.PNG)

@frank-trampe My question is why on the images are round round lines? These are not hints. I do not use Spirio.

**Comment by davelab6** [comment]
Those are from a background layer

**Comment by frank-trampe** [comment]
@typedesigner, are you working on a typeface that has a background layer with those curves? If so, and if the layer is not visible, you would need to make it visible by clicking the appropriate spot on the entry for that layer on the layer palette. If you do not have such a layer, you would need to draw one. It might help if you told us your end goal in this effort.

**Comment by typedesigner** [comment]
@frank-trampe Of course layers are active.

**Comment by frank-trampe** [comment]
Did that solve your problem?

**Comment by typedesigner** [comment]
@frank-trampe Thank you. I think, I understand now better.

**Comment by frank-trampe** [comment]
Good. I'm going to close this issue then.
