### ISSUE TITLE
'Check for problems' dialog usability issues

### ISSUE THREAD

**Issue by mairin** [fontforge/fontforge#309]
Hi, I had a lot of confusion when I tried clicking on the 'Check for problems' dialog - I would hit okay to check for problems, and nothing would happen. There's a few things going on that I think caused the confusion:

- The first time I opened the dialog, I checked off a bunch of stuff in the 'check for problems' dialog, ran it, and it worked fine. It worked fine several times after.

- I restarted fontforge the next day, and I think what happened is that it forgot everything I had checked off in the 'check for problems' dialog, so it 'stopped working' because it wasn't checking for anything and silently 'succeeded'

- If nothing is checked off, the 'check for problems' dialog disappears without feedback when you press OK - which is confusing because you'd expect it to say something, maybe 'Cancelling check for problems since you didn't choose anything to check' or something like that.

A couple of suggestions:

- [ ] Initially, the 'check for problems' dialog should have some sane defaults checked off, rather than be blank by default.
- [ ] When someone customizes what 'check for problems' checks for, fontforge should remember that setting after being closed and subsequently restarted.
- [ ] You shouldn't be able to run 'check for problems' without anything to check for. Maybe grey out the 'okay' button with a message directly under or below it, or a gtk-style / firefox-style info-bar at the top that says, 'You must select at least one problem to check for before running the check test.' or something like that.

**Comment by pathumego** [comment]
#364
