### ISSUE TITLE
Help with em setting in grunt-webfont

### ISSUE THREAD

**Issue by printercu** [fontforge/fontforge#3099]
Hi!

I'm using fontforge with https://github.com/sapegin/grunt-webfont to generate fonts from svg automatically. It has `fontHeight` and `descent` options which set `em` and `descent` for font [here](https://github.com/sapegin/grunt-webfont/blob/b66d6b8a736b41187218490914fbd78c856df4aa/tasks/engines/fontforge/generate.py#L16-L18). I've checked that this values are changing according to my settings, but it doesn't affect generated fonts: I get same results for descent 64, 128 and 256. I expect it to change font's baseline, and how it's aligned to other fonts with css `vertical-align: baseline`.

Does setting `em` and `descent` should result in different font's baseline as I expect? If so, can you please take a look at that script and give advice how it can be fixed?

I've found some issues (https://github.com/fontforge/fontforge/issues/2201 and similar), but I'm not familiar with font terminology and not sure if it's related.

Thank you in advance!

**Comment by frank-trampe** [comment]
@printercu, there are different ascent and descent values that may be used for display in different contexts. Try adjusting them as shown [here](http://designwithfontforge.com/en-US/Line_Spacing.html) and see which one affects display on your device. Or just set all of them. `em` is not a real value (just a sum of native ascent and descent) and is not implemented in the Python bindings.

**Comment by printercu** [comment]
Thank you!
