### ISSUE TITLE
Mac 10.13 Beta - No windows open when FontForge is launched, XQuartz is launched

### ISSUE THREAD

**Issue by zackdabrams** [fontforge/fontforge#3100]
So I was using fontforge last night on the same Mac 10.13 beta software but when I woke up this morning and tried to launch fontforge, no windows showed up. I've tried deleting and reinstalling fontforge and xquartz but still no windows show up. To clarify, when I launch fontforge, it bounces and disappears and launches xquartz, but after that no windows show up. It shouldn't be an issue with the Mac update because I just used the software last night.

Thanks for the help.

**Comment by jtanx** [comment]
what do you see in the terminal when you try to launch fontforge manually, e.g. 

`/Applications/FontForge.app/Contents/MacOS/FontForge`

**Comment by hopefuture** [comment]
I can not open FontForge yet，My Mac is macOS Hight Sierra 10.13.1

**Comment by jtanx** [comment]
So.... did you try https://github.com/fontforge/fontforge/issues/3100#issuecomment-309242364? Do you have XQuartz?

**Comment by hopefuture** [comment]
What is it XQuartz?
