### ISSUE TITLE
Importing SVG for wide character results in shrunken character!

### ISSUE THREAD

**Issue by Yoshimaster96** [fontforge/fontforge#3116]
I currently have a font with an em size of 64, and thus a height of 64. However, I need to import a character with a width of 80. Doing so results in the character being shrunken to fit within a width of 64 towards the top of the bounding box. How do I disable this "feature"?

**Comment by jrbastien** [comment]
I think I understand what you mean but usually EM sizes are more like 1000, 1024, or 2048 (see http://designwithfontforge.com/en-US/The_EM_Square.html).

You can always select all your fonts after import and apply an horizontal scaling factor of 1.25 (80/64).  Go to Element --> Transformations --> Transform... -->Scale... and set X to 125.

**Comment by Yoshimaster96** [comment]
How do I import characters wider than the em size?

**Comment by Anonrate** [comment]
@Yoshimaster96 Open FontInfo `Element > FontInfo` and in the General tab, make sure **Scale Outlines** is not checked.  Now when you import a character, it wont be scaled.   You may have to do this each time if you're going to use the import feature multiple times.

**Comment by Yoshimaster96** [comment]
@Anonrate Won't let me uncheck it.

**Comment by frank-trampe** [comment]
@Yoshimaster96, post the file that you are using. The checkbox works for me.

**Comment by skef** [comment]
Inactive needs-info issue. Closing, will reopen if needed.
