### ISSUE TITLE
Man page for zsock APIs like zsock_new()

### ISSUE THREAD

**Issue by nayabbashasayed** [fontforge/fontforge#3117]
Current 0MQ version is 4.2.1

I've been reading [zguide](http://zguide.zeromq.org/page:all)(Written for v3.2).

The latest [C examples](https://github.com/booksbyus/zguide/tree/master/examples/C) won't work with v4.2.1.

Since **zctx** and so many APIs are deprecated with 4.0, I've decided to use version greater then 4.0. But where do I find the man pages for v4.2.1 APIs? I could only found the page for classes like [zsock class](http://czmq.zeromq.org/czmq4-0:zsock).

**Comment by jtanx** [comment]
@nayabbashasayed I think you want to be posting on https://github.com/zeromq/czmq

**Comment by nayabbashasayed** [comment]
Thanks.. :)
