### ISSUE TITLE
Bad hyper-link on a web page

### ISSUE THREAD

**Issue by JaiSoone** [fontforge/fontforge#3122]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
The web page https://github.com/fontforge/fontforge/wiki/User-Documentation
the hyper-link "How To Update FontForge's Unicode Support" links to a non-existent page.
- [ ] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround
It should link to "https://github.com/fontforge/fontforge/wiki/How-To-Update-Unicode-Support"
as the similarly named hyperlink in the table of contents to the right does.

**Comment by jtanx** [comment]
Thanks, it should be ok now (although the instructions probably aren't). I think anyone can update it, so feel free to update the wiki as required.
