### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Dmole** [fontforge/fontforge#3126]
http://fuuko.libferris.com/osx/packages/FontForge_latest-HEAD.app.dmg
from
http://fontforge.github.io/en-US/downloads/mac-dl/
is 404

**Comment by frank-trampe** [comment]
Hmm. I didn't set that up, so I don't know what's wrong. @jtanx?

**Comment by jtanx** [comment]
That is (or was) from  @monkeyiq's build bot. @davelab6 might know more, but I think it's defunct.

**Comment by davelab6** [comment]
Yeah this is long gone. Links should be removed.

**Comment by davelab6** [comment]
Fixed in https://github.com/fontforge/fontforge.github.io/pull/118
