### ISSUE TITLE
Installer FontForge-2017-07-31-Windows-r2.exe fails to opens under Windows 10

### ISSUE THREAD

**Issue by datamystic** [fontforge/fontforge#3128]
- [X] FontForge-2017-07-31-Windows-r2.exe, Windows 10 v1607 build 14393:1480
- [X] Double-clicked installer, did not open (I have admin rights, my own laptop)
- [X] Go to https://fontforge.github.io/en-US/downloads/windows/, Enter email address, takes you to: https://fontforge.github.io/en-US/downloads/windows-dl
Click button to download 2016-10-04 Release installer.
https://fontforge.github.io/en-US/downloads/windows-dl downloads.
Right-click, choose run as Administrator.
Nothing happens

**Comment by jtanx** [comment]
Hmm strange, I can't reproduce this. I built and tested this on Windows 10, and everything works on my end. I've also tested in a fresh Windows 10 VM, and I can install it just fine.

Confirming the SHA256 hash of the binary:
`467AC88B2F2FCE32B8CEA5C757AEB7B98B02C0ECCB3F93502130DB2ED228D8A9`

Are you running 32 bit or 64 bit Windows 10? Any 3rd party antivirus? Checked event viewer? Tried re-downloading the installer?

If it still doesn't work, I guess you could use the portable version https://sourceforge.net/projects/fontforgebuilds/files/i686/Portable/FontForge-mingw-w64-i686-bbe2d0-x11-r2.7z/download (you'll need to extract it yourself using something like 7-zip).

**Comment by datamystic** [comment]
Thanks for your quick response!

 

SHA256 checks out. I am running Win10 x64. I tried disabling KAV, and still run as admin did not work. Nothing obvious in Event Viewer. I will try again after a restart.

 

C:\Aemail\Downloads>CertUtil -hashfile FontForge-2017-07-31-Windows-r2.exe Sha256

SHA256 hash of file FontForge-2017-07-31-Windows-r2.exe:

467ac88b2f2fce32b8cea5c757aeb7b98b02c0eccb3f93502130db2ed228d8a9

CertUtil: -hashfile command completed successfully.

 

 

Let me know if I can help further.

 

Regards,

Simon Carter,  <http://datamystic.com/> DataMystic.com  Skype: <skype:datamystic?call> datamystic   <tel:+61.3.9028.8594> +61.3.9028.8594 (GMT+10 hours)  

 <https://predictbgl.com/> PredictBGL: Bloody smart  diabetes management

TextPipe: PCMAG - "The ultimate text conversion and manipulation tool"

Detach Outlook Attachments and send huge files -  <http://www.detachpipe.com/> DetachPipe.com

Download the latest Windows, Mac and iPhone software -  <http://downloadpipe.com/> DownloadPipe.com

**Comment by jtanx** [comment]
Thanks for testing. The setup uses [InnoSetup](http://www.jrsoftware.org/ishelp/topic_setupcmdline.htm#LOG), so you could perhaps try turning on logging:

```bat
C:\Aemail\Downloads>FontForge-2017-07-31-Windows-r2.exe /LOG=log.txt
```

And see if the log file it makes (if any) contains anything useful

**Comment by datamystic** [comment]
Bizarre – it worked perfectly this morning. The only thing I can think of is that I closed down Delphi XE2 and Visual Studio 2015, so it might have been a memory isuse.,

 

 

Let me know if I can help further.

 

Regards,

Simon Carter,  <http://datamystic.com/> DataMystic.com  Skype: <skype:datamystic?call> datamystic   <tel:+61.3.9028.8594> +61.3.9028.8594 (GMT+10 hours)  

 <https://predictbgl.com/> PredictBGL: Bloody smart  diabetes management

TextPipe: PCMAG - "The ultimate text conversion and manipulation tool"

Detach Outlook Attachments and send huge files -  <http://www.detachpipe.com/> DetachPipe.com

Download the latest Windows, Mac and iPhone software -  <http://downloadpipe.com/> DownloadPipe.com

**Comment by jtanx** [comment]
Strange indeed. Please reopen if you encounter the problem again. Thanks!
