### ISSUE TITLE
Where do tofu glyphs for characters come from?

### ISSUE THREAD

**Issue by JuanPotato** [fontforge/fontforge#3132]
![image](https://user-images.githubusercontent.com/9531780/28996031-b83e4f96-79c5-11e7-8070-deefb981d602.png)

wider screenshot
![image](https://user-images.githubusercontent.com/9531780/28996148-fe334a4a-79c7-11e7-8394-3ef78dea20dd.png)

These blocks with the codepoints in them, is there some code that generates them if they don't exist in any preexisting fonts? I ask this because [I'm trying to make a font that is exactly this](https://graphicdesign.stackexchange.com/q/95687/100584), but my current attempts have come out very blurry when you compare them with the ones in font forge. My understanding is that these are not a font, but rather built in to font forge.

**Comment by khaledhosny** [comment]
The text is drawn with Pango, so these hex boxes means you don’t have a font in your system that supports these characters (at least as far as Pango is concerned).

**Comment by JuanPotato** [comment]
Alright thanks

**Comment by sahilchamp** [comment]
Default boxes are fine, but why do the unicode code block appears inside this box? Is this Pango specific or all renderer behaves like this. Shouldn't I expect empty box or glyph present at glyph id 0
