### ISSUE TITLE
How to change fill color?

### ISSUE THREAD

**Issue by chackerian** [fontforge/fontforge#3141]
I am confused as to how you change the color of lines in fontforge. For example, I want letters A to E to be red, F to I to be blue and so on. Is this in the Resource Editor possibly? I tried looking there but had no luck. How can I change the fill color from default black to other colors?

**Comment by jtanx** [comment]
The fill/preview colour is controlled in the resource editor:

![reeee](https://user-images.githubusercontent.com/5137410/29557034-2aad4354-876b-11e7-98a4-3499f296f26c.PNG)

But this is a global setting. As far as I'm aware, there is no per-glyph configuration. What's your use case for colouring them differently?

**Comment by LukasExemplar** [comment]
Why do you not have it in the font editor? When makinga glyph in the editor, it comes out as white to me.

**Comment by skef** [comment]
While it is unusual that FontForge has two different preferences dialogs, both are "in the editor". The displayed dialog is opened by choosing "X Resource Editor" from the File menu. 

When changing things like Fill color you don't typically have to restart the program but it is necessary to close and reopen the CharView window.

**Comment by dzintars** [comment]
@jtanx I just few hours ago came up with the task to to create OpenType-SVG icon font. So basically i need to make few hundreds of unicode chars as colorful glyphs composed of different color paths. For example as this image.
![image](https://user-images.githubusercontent.com/547420/80928387-a330d800-8dac-11ea-9ef6-663b37e7e5d1.png)
Not sure is the FontForge right tool for this.

**Comment by skef** [comment]
FontForge doesn't currently have much in the way of color support for contours (other than choosing a global fill color, which is strictly a UI setting that doesn't affect output). You would probably be better off using Inkscape or another such tool but you could also make the shapes in FontForge and post-process with a library like python's svgwrite if you prefer.

**Comment by skef** [comment]
You can change the font-wide fill color and you can label individual glyphs with a color in the GlyphInfo dialog (the color is displayed in the FontView). Beyond that there won't be per-glyph-fill colors until and unless FontForge supports color fonts (too niche as a UI feature).
