### ISSUE TITLE
Installing FontForge on macOS 10.12.16

### ISSUE THREAD

**Issue by Bigemul** [fontforge/fontforge#3142]
Hi everyone

I'm trying to install FontForge on my computer. I have XQuartz in "Utilities", I open FontForge, I put the "FontForge" file in "Applications" and the program doesn't seem to see this file so I cannot open FontForge.

Can someone please help me?

Thanks in advance

**Comment by ryandesign** [comment]
Here is the MacPorts project's ticket requesting the port be updated: 

* https://trac.macports.org/ticket/43844

**Comment by jtanx** [comment]
What happens if you launch XQuartz first? What is displayed if you launch FontForge from the terminal?
