### ISSUE TITLE
FontForge segfaults when instantiating a new font if compiled with the UI disabled

### ISSUE THREAD

**Issue by felixhagspiel** [fontforge/fontforge#3145]
Hello,

I got a new macbook and tried to run fontcustom, but I always get the error `error  `fontforge` compilation failed. Try again with --debug for more details.`. After some research it seems that it is still working with the version `20170104`. How can I downgrade to this version? If I do `brew search fontforge` I only see the latest version.

currently I got:
fontcustom 1.3.8
fontforge 20170806

Thanks!

**Comment by JakeBeresford** [comment]
Same issue here, I dont see this version of fontforge in the releases. Could you please point me towards the changes for this release so that I can patch fontcustom if necessary.

**Comment by jtanx** [comment]
This is a segfault (see also: https://github.com/FontCustom/fontcustom/issues/355). Probably homebrew or python related.

I can see this happen on OS X, but not on Windows. As for installing an older version, I have no idea. Perhaps raise a ticket on Homebrew or something.

I'll try to debug this... But just looking at the script, there are so many levels of wrong with it I don't know...

**Comment by jtanx** [comment]
Minimal test case:

`./configure --without-x --disable-python-{scripting,extension}`
`make -j4 && make install`

`fontforge -lang=ff -c "New()"`

**Comment by jtanx** [comment]
```
 CC       libfontforgeexe_la-startnoui.lo
startnoui.c: In function âfontforge_mainâ:
startnoui.c:110:22: warning: implicit declaration of function âFindOrMakeEncodingâ [-Wimplicit-function-declaration]
     default_encoding=FindOrMakeEncoding("ISO8859-1");
                      ^~~~~~~~~~~~~~~~~~
startnoui.c:110:21: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     default_encoding=FindOrMakeEncoding("ISO8859-1");
```

Well then...

**Comment by jtanx** [comment]
@felixhagspiel / @JakeBeresford a fix was merged into Homebrew so if you update your installed version of fontforge (20170731 pkgrel 2), I think it should work now. It should also work with the [official releases](https://github.com/fontforge/fontforge/releases) since they are compiled with ui support and wouldn't be affected likewise.

**Comment by felixhagspiel** [comment]
Works! Thank you so much 👍
