### ISSUE TITLE
collab: zeromq-4.1.5 doesn't build with gcc7

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#3149]
With gcc7, the pinned version of zeromq fails to build - see: https://travis-ci.org/fontforge/fontforge/jobs/273962625

So we can:
* Attempt to build against a later version of zeromq
* Patch that version of zeromq to work
* Disable that warning
* Go back to an older compiler
* Maybe fix collab code to work with a later version if we can't just bump the version of czmq
* Drop collab altogether (it's unmaintained and buggy, from what I see... is anyone actively using it?)

**Comment by frank-trampe** [comment]
I think it's sort of ridiculous for that gcc check even to exist, but to include such bad math in czmq is equally vexing. I'm on the same version of gcc as Travis. Let me try a newer version of zeromq this week.

**Comment by jtanx** [comment]
As per #3150, I think for now, we'll just disable that warning so that Travis builds can continue to work.

For what it's worth, taking a quick look at what's required to make it work with czmq 4, I think it's mostly around replacing zsocket/zbeacon calls with zsock/zactor calls. But I could be mistaken, the documentation on czmq wasn't that good.

**Comment by skef** [comment]
Collab was removed
