### ISSUE TITLE
After following steps thoroughly, it won't open: doesn't do anything

### ISSUE THREAD

**Issue by rgrundig** [fontforge/fontforge#3151]
Hi, everyone! I've been trying to get FontForge (version 20170730) running on my Macbook Pro Retina (OS 10.12.6), with no success.

I have followed all the steps needed in order to install it and ended up at the part where you drag it to the applications folder (image attached below). Even though I removed the security blocks from my system preferences, when I double click the App, it doesn't do anything. One of the times I tried, it said "Verifying "FontForge.app", but that was the farthest I went. Any thought on what it could be? I have no idea what to do to make it open/work.

Thank you!

![image](https://user-images.githubusercontent.com/3253235/30356793-647b8ba2-9811-11e7-9b01-6e182ccd3463.png)

**Comment by frank-trampe** [comment]
So you have X11 installed? Does X11 appear to start when you start FontForge? Try running `/Applications/FontForge.app/Contents/MacOS/FontForge` from the Terminal and see what it says.

**Comment by rgrundig** [comment]
Hi Frank. Thanks for replying. X11 is not starting when I start FontForge. You did give me an idea though, and it worked. I opened X11, and then tried opening FontForge and guess what: it worked!

Closing both applications and trying to open only FontForge still doesn't work. I have to have both applications running apparently. Is this normal?

**Comment by frank-trampe** [comment]
@rgrundig, I'm not a Macintosh user, and my test environment is still on Yosemite, so I'm not sure what's happening. In the past, it started automatically. With each new version of Mac OS, there seems to be a new caveat for our users.

**Comment by jtanx** [comment]
We should merge #2782 at some point, if only for mac users... I'll get around to updating it some time...

**Comment by rgrundig** [comment]
Ok. Thanks for all the prompt replies guys.
