### ISSUE TITLE
Wont read SVG on mac or windows

### ISSUE THREAD

**Issue by ynbd** [fontforge/fontforge#3154]
hello,

im sorry if there is already an issue with this title, i coudnt find anything.

Im pretty new to fontforge and so far it is amazing!! Very easy and over all works perfect for me. 
At the moment im trying to create a hand drawn font, i save svg in illustrator CS6 and than try to open them in fontforge. I always get the same window on both mac and windows. "...svg is not in a known format  or uses features of that format fontforge does not support or is so badly corrupted as to be unreadable).. At first i though that the svg is to be or to small, but that didnt make a difference. 

Could you please give me some ideas of why this is happening.

Thank you so much!!!

![screen shot 2017-09-22 at 10 35 55 am](https://user-images.githubusercontent.com/7895310/30749715-3b2948d4-9f82-11e7-8747-9ac796219d2f.png)

**Comment by ctrlcctrlv** [comment]
FontForge can only open SVG fonts. You have to use the "Import" feature to import any other type of SVG.

**Comment by ynbd** [comment]
HI.
It worked on mac YAY!!! Im going try on windows!! Since i work on both!

Thanks so much for your help :)

**Comment by Anonrate** [comment]
@ynbd  Can you close the issue then if your problem has been resolved?

**Comment by jtanx** [comment]
Please reopen if you encounter any issues.
