### ISSUE TITLE
Where can I change the ruler font size

### ISSUE THREAD

**Issue by Anonrate** [fontforge/fontforge#3161]
This isn't really an issue but, I've changed all the settings in the preferences that font related and I am not able to change the font size of the ruler and meassuretool.  I've got a very HiPPI monitor and I have to go right up  to the screen as look at the info as if I'm looking through a cheerio.

I have looked through the source code as well and have not been able to find it.

Any help as to how I can make the font bigger for those areas would be very helpful.

**Comment by ctrlcctrlv** [comment]
I've got good news and bad news.

First, the good news. I found where in the code this is, so I made a naive change:

```
diff --git a/fontforgeexe/charview.c b/fontforgeexe/charview.c
index e6f619e5b..085197369 100644
--- a/fontforgeexe/charview.c
+++ b/fontforgeexe/charview.c
@@ -5877,7 +5877,7 @@ static void CVExposeRulers(CharView *cv, GWindow pixmap ) {
     GDrawDrawLine(pixmap,cv->rulerh,cv->mbh+cv->charselectorh+cv->infoh+cv->rulerh-1,8096,cv->mbh+cv->charselectorh+cv->infoh+cv->rulerh-1,def_fg);
     GDrawDrawLine(pixmap,cv->rulerh-1,cv->mbh+cv->charselectorh+cv->infoh+cv->rulerh,cv->rulerh-1,8096,def_fg);
 
-    GDrawSetFont(pixmap,cv->small);
+    GDrawSetFont(pixmap,cv->normal);
     if ( xmax-xmin<1 && cv->width>100 ) {
        CVDrawNum(cv,pixmap,cv->rulerh,ybase+cv->sas,"%.3f",xmin,0);
        CVDrawNum(cv,pixmap,cv->rulerh+cv->width,ybase+cv->sas,"%.3f",xmax,2);
```

Now the bad news. That did make the font larger, but it also made it look even worse than before.

![charview](https://user-images.githubusercontent.com/838783/31054082-57d974ee-a69a-11e7-995f-996281758593.png)

The right way to do this is to make `CharView->small` DPI-aware like `CharView->normal`, and then change all the places where it is used to make sure that the elements around it scale with the font.

That's a huge amount of work, but at least you know where to start if you want to undertake it. :-)

The easy way out (on systems with Xorg) is to use [run_scaled](https://github.com/kaueraal/run_scaled) and run FontForge with a standard DPI.

**Comment by Anonrate** [comment]
run_scaled actually may help a lot, even though my monitor is 187ppi, I have the ppi set to 144 as it makes it much easier to develop fonts for.  Thank you very much.

I will close this as I have all the information I need.   :)
