### ISSUE TITLE
Patching "Monaco" with Fira Ligature characters

### ISSUE THREAD

**Issue by carlca** [fontforge/fontforge#3169]
This is not an issue about the usage of FontForge per se, rather it is a question about the potential usage of FontForge, so apologies in advance for that.

macOS 10.12.6
MS VSCode Insiders 1.17.0
iTerm2 v3.1.2

Hello, I'm still a newbie when it comes to advanced font issues, so please be gentle with me! I'm using VSCode for coding with my preferred font Monaco. I also have this font in its Powerline incarnation in use in iTerm2 where I have it display the fancier aspects of ZSH very nicely.

I have seen and like the Ligature features of the Fira Code font but I don't particularly like the standard character images. My ideal solution would be the "Monaco for Powerline" font with characters such as the >= and := patched with the Fira Code ligature characters.

My research has led me to discover that there is a tool called "Font Patcher" and this related tool "FontForge" which sound suspiciously like the answer to my wishes, but I still haven't discovered instructions suitable for a beginner such as I to make use of them.

Can anyone tell me if what I am asking is actually possible and how to do it?

Assuming there are no legal issues in the way I would naturally make the successful outcome of my ventures publically available. Thanks in advance.

**Comment by frank-trampe** [comment]
This is best posted on the [FontForge mailing list](https://sourceforge.net/projects/fontforge/lists/fontforge-users).

One thing that I would specify before reposting is what ligature-related information you wish to move from one typeface to another. Glyphs, the liga feature data, the kerning data, or some combination of those.
