### ISSUE TITLE
"libfontforge2", not "libfontforge1"

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge#3173]
Currently, latest `libfontforge1` should be named as `libfontforge2`, because inside it lib numbered as 2.x:

* https://launchpad.net/~fontforge/+archive/ubuntu/fontforge/+files/libfontforge1_20170731-0ubuntu1~xenial_amd64.deb
  * `./usr/lib/`
    * `libfontforge.so.2`
    * `libfontforge.so.2.0.0`
    * `libfontforgeexe.so.2`
    * `libfontforgeexe.so.2.0.0`
    * ...

In same way, latest `libfontforge1` depend on some `libfontforge1` (it's oxumoron?). **But lib version of dependency not described!** As I understand, it depend on 'true' `libfontforge1`, that include libs numbered as 1.x:

* http://mirrors.kernel.org/ubuntu/pool/universe/f/fontforge/libfontforge1_20120731.b-7.1_amd64.deb
  * `./usr/lib/`
    * `libfontforge.so.1`
    * `libfontforge.so.1.0.0`
    * ...

### System info
FontForge vrsion: 20170731
OS: xUbuntu 16.04 'Xenial' (amd64)

**Comment by jtanx** [comment]
You're comparing the **2012**0731 release to the **2017**0731 release. The soversion was bumped from 1 to 2 some time after the 2012 release; they're different.

**Comment by Symbian9** [comment]
> You're comparing the 20120731 release to the 20170731 release

No, I'm not just compare, I just tried manually install FontForge 20170731 on own PC and that's why found this 'lib version coincindent'.

This really look like bug of lib numbering. Also, in `libfontforge1_20170731*.deb` package dependency not clear:
* now it look like: `Dependency: libfontforge1 ...`
* should be something like: `Dependency: libfontforge1 (= 20120731)`

Also, it's so horrible that 'one release depend on another one release'.

**Comment by jtanx** [comment]
Ah, I see, you're talking about the actual .deb package name instead of the soversions on the dlls.

**Comment by Symbian9** [comment]
> instead of the soversions on the dlls

I'm talking about few issues:
* [ ] some packages related to FontForge has not clear dependency info
* [ ] current version of "libfontforge" should be renamed to `libfontforge2`
* [ ] Is it really need make dependency on some packages from 20120731 release for current 20170731 release (and later) for install FontForge in our time?

**Comment by gioele** [comment]
Thanks for the heads up @Symbian9. However, all the packaging for Debian and Ubuntu is done upstream by the Debian fonts task force. You should get in contact with them using the mailing list <pkg-fonts-devel@lists.alioth.debian.org> or just report a bug at <https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=fontforge>.

**Comment by jtanx** [comment]
Actually, the Ubuntu PPA is maintained by @frank-trampe, AFAIK.

**Comment by gioele** [comment]
@jtanx, oh, I did not know that. Indeed the Debian packaging already uses `libfontforge2` as the package name, together with a `Replaces: libfontforge1`.

https://anonscm.debian.org/git/pkg-fonts/fontforge.git/tree/debian/control#n136

@frank-trampe: isn't the PPA based on the Debian git repo?

**Comment by jtanx** [comment]
I changed it to libfontforge4, matching the soversion bump. Not released yet on the ppa though.
