### ISSUE TITLE
Windows Download Page doesn't work on Firefox 

### ISSUE THREAD

**Issue by zoltan-dulac** [fontforge/fontforge#3180]
I could not download any of the builds with Firefox 55.0.3 on Windows. I fill in the email address, and it just reloads the page.

**Comment by JoesCat** [comment]
Hi @zoltan-dulac,
I am also running Firefox 55.0.3 (on Fedora), and I went and looked at the page in question.
First time I've looked :-)
[FontForge on Windows, Almost There](http://fontforge.github.io/en-US/downloads/windows/)
Colour scheme is non-default, and maybe the message needs clarification, but trying it out, I entered an email in the box, clicked on "Subscribe/Confirm and Download"
This changed to a sentence that says "Thanks. Continue this way." where 'this way.' is underlined.
You will need to click on the 'this way.' to continue to the actual download page.

See if that works. If yes, good, sorry for the confusion.
If yes, can you also think of a recommendation on how to improve this particular webpage?
(It may also need to fit within certain limitations and parameters).

**Comment by ilyaza** [comment]
This page looks very intimidating for me too.  I would not try to click through anything like this.

Eventually, I downloaded directly from http://fontforge.github.io/en-US/downloads/windows-dl/ — found via Google.

How to rewrite
=========

 - First, remove this nagging.  It is wrong anyway: the page works fine even when one leaves the email address blank.

    So: start with a plain link to download page.

- You may keep the current chunk below the plain link to dowload the page (mutatis mutandis).

    Just say that you recommend using the second alternative.
