### ISSUE TITLE
Provide new release with security fixes included

### ISSUE THREAD

**Issue by paulmenzel** [fontforge/fontforge#3182]
Would you be so kind to release a new version, that includes [the security fixes][1].

That would help distributions still, using “released” source archives as the foundation of their packaging.

[1]: http://metadata.ftp-master.debian.org/changelogs/main/f/fontforge/fontforge_20170731~dfsg-1_changelog

**Comment by jtanx** [comment]
As far as I'm aware, all of those security fixes are already in the 20170731 release.

**Comment by paulmenzel** [comment]
Ok, thank you for clearing that up, and sorry for the noise.
