### ISSUE TITLE
"save failed" when trying to generate

### ISSUE THREAD

**Issue by ManuHierosolymitanum** [fontforge/fontforge#3189]
Hi, 
I'm new to FF. It might be that I'm missing something, but after going through the tutorials and help files still no solution. 
When trying to generate a font of either type, I keep getting the "save failed" error. I get warnings of all kind of errors, but it also happens when I try to re-generate a commercial, well-organized TTF file, with or without changes I made in it, by the original file name or by a new one. 
Build is of 31 July 2017. I'm running windows 10 on 64 bit machine. Any clue will be much appreciated.
ManuM

**Comment by jtanx** [comment]
If you could post some screenshots that would be great. Do you have write access to the location that you are saving to?

**Comment by ManuHierosolymitanum** [comment]
You've  just provided the solution. 
I tried to save in another location than the Windows fonts folder, and it worked. 
Thank you!

**Comment by jtanx** [comment]
Glad you found a solution :)
