### ISSUE TITLE
gradio.c:362:21: warning: iteration 6u invokes undefined behavior

### ISSUE THREAD

**Issue by jonasstein** [fontforge/fontforge#3191]
```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * gradio.c:362:21: warning: iteration 6u invokes undefined behavior [-Waggressive-loop-optimizations]
 * tilepath.c:1310:5: warning: implicit declaration of function ‘CVPreserveState’ [-Wimplicit-function-declaration]
 * tilepath.c:1326:5: warning: implicit declaration of function ‘SCPreserveLayer’ [-Wimplicit-function-declaration]
 * tilepath.c:1410:12: warning: implicit declaration of function ‘RefCharsCopy’ [-Wimplicit-function-declaration]
 * tilepath.c:1954:28: warning: implicit declaration of function ‘CVLayer’ [-Wimplicit-function-declaration]

```

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
see on top

- [x] The FontForge version and the operating system you're using
fontforge-2.0.20170731 (media-gfx/fontforge-20170731) on gentoo linux

- [x] The behavior you expect to see, and the actual behavior
no warnings

- [x] Steps to reproduce the behavior 
install/compile

- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
fixed, iirc
