### ISSUE TITLE
Feature Request: Points of Inflection

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3197]
@frank-trampe @davelab6 

Hello,
would be very useful to add "Points of Inflection" feature. Comparable to the function: add extreme points.
Can you please program this?

**Comment by Anonrate** [comment]
I do believe that this is already a feature.  Check `View>Show>Points of Inflection`  If you can't see anything, try changing the colors around a bit via `File>X Resource Editor...>Outline View>Points of Inflection Color`

**Comment by davelab6** [comment]
Yeah but he means too add control points at those locations currently only
indicated visually

**Comment by typedesigner** [comment]
What is needed is a feature that automatically adds these "Points of Inflection". Such as exterema points. That would save a lot of time. Adding "Points of Inflection" manually requires a lot of time.

**Comment by linusromer** [comment]
Maybe my plugin is useful for you. It can add inflection points automatically:
https://github.com/linusromer/harmonize-tunnify-inflection

**Comment by skef** [comment]
Duplicate of #147
