### ISSUE TITLE
Help me preserve FontForge history to commemorate the 17th anniversary of FontForge!

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3198]
Hello friends! I am the webmaster of pfaedit.org and am requesting your contributions. Pfaedit.org was the old domain of FontForge which lapsed registration and I re-registered it. I am not squatting the domain, I did it to honor FontForge and George Williams and the history of this great project. If he requested it back from me I would of course give it to him.

http://pfaedit.sourceforge.net/oldchangelog.html

> PfaEdit was initially made available (on the web) on 7 Nov 2000, and moved to sourceforge 21 Apr 2001. I started coding it in approximately Sept of 2000. 

The 17th anniversary of FontForge is upon us in 5 days. If you have any history you'd like me to add, please let me know. I'm working on archiving the old SourceForge FontForge mailing lists and making them available on pfaedit.org also.

I love this project, I love how it was inspired and made, I love the story behind it, the about screen brings a tear to my eye since it reminds me so much of my own life...that's why I'm so dedicated to archiving our collective history as the FontForge community.

If you have anything you'd like me to add to pfaedit.org let me know.

For everyone, happy 17th anniversary!!! 🎊 🎉

**Comment by frank-trampe** [comment]
Good work. The old site design brings back fond memories.

Sorry for not responding sooner, but I didn't have anything interesting to share anyway.

**Comment by ctrlcctrlv** [comment]
No problem at all. Thank you for your continued maintenance of the project :-)
