### ISSUE TITLE
Installing Fontforge (Tag:20170731 ) in AMI Amazon Linux 2016.09

### ISSUE THREAD

**Issue by sarathprasath-krishnaswamy** [fontforge/fontforge#3200]
### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using -- Fontforge (Tag: 20170731), AMI Version: 2016.09
- [x] The behavior you expect to see, and the actual behavior -

I tried with the steps mentioned in the https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#building-a-red-hat-source-package-rpm, as I thought it will align with yum package manager

I tried `./configure --without-x` but it throws error like below:

`[root@machine1 fontforge]# PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --without-x;`
`checking build system type... x86_64-pc-linux-gnu`
`checking host system type... x86_64-pc-linux-gnu`
`checking for a BSD-compatible install... /usr/bin/install -c`
`checking whether build environment is sane... yes`
`checking for a thread-safe mkdir -p... /bin/mkdir -p`
`checking for gawk... gawk`
`checking whether make sets $(MAKE)... yes`
`checking whether make supports nested variables... yes`
`checking how to create a pax tar archive... gnutar`
`checking whether to enable maintainer-specific portions of Makefiles... yes`
`checking for style of include used by make... GNU`
`checking for gcc... gcc`
`checking whether the C compiler works... yes`
`checking for C compiler default output file name... a.out`
`checking for suffix of executables...`
`checking whether we are cross compiling... no`
`checking for suffix of object files... o`
`checking whether we are using the GNU C compiler... yes`
`checking whether gcc accepts -g... yes`
`checking for gcc option to accept ISO C89... none needed`
`checking dependency style of gcc... gcc3`
`checking how to run the C preprocessor... gcc -E`
`checking for grep that handles long lines and -e... /bin/grep`
`checking for egrep... /bin/grep -E`
`checking for ANSI C header files... yes`
`checking for sys/types.h... yes`
`checking for sys/stat.h... yes`
`checking for stdlib.h... yes`
`checking for string.h... yes`
`checking for memory.h... yes`
`checking for strings.h... yes`
`checking for inttypes.h... yes`
`checking for stdint.h... yes`
`checking for unistd.h... yes`
`checking minix/config.h usability... no`
`checking minix/config.h presence... no`
`checking for minix/config.h... no`
`checking whether it is safe to define __EXTENSIONS__... yes`
`checking whether _XOPEN_SOURCE should be defined... no`
`checking for gawk... (cached) gawk`
`checking for gcc... (cached) gcc`
`checking whether we are using the GNU C compiler... (cached) yes`
`checking whether gcc accepts -g... (cached) yes`
`checking for gcc option to accept ISO C89... (cached) none needed`
`checking dependency style of gcc... (cached) gcc3`
`checking for gcc option to accept ISO C99... -std=gnu99`
`checking whether gcc -std=gnu99 and cc understand -c and -o together... yes`
`checking for Minix Amsterdam compiler... no`
`checking for ar... ar`
`checking the archiver (ar) interface... ar`
`checking for ar... (cached) ar`
`checking for ranlib... ranlib`
`checking for special C compiler options needed for large files... no`
`checking for _FILE_OFFSET_BITS value needed for large files... no`
`checking for gcc -std=gnu99 option to accept ISO C99... (cached) -std=gnu99`
`checking for gcc -std=gnu99 -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99`
`checking how to run the C preprocessor... gcc -E`
`checking for grep that handles long lines and -e... (cached) /bin/grep`
`checking whether ln -s works... yes`
`checking whether make sets $(MAKE)... (cached) yes`
`checking for a sed that does not truncate output... /bin/sed`
`checking for strip... /usr/bin/strip`
`checking for gcc... gcc`
`checking whether we are using the GNU Objective C compiler... no`
`checking whether gcc accepts -g... no`
`checking dependency style of gcc... gcc3`
`checking the archiver (ar) interface... (cached) ar`
`checking whether make supports nested variables... (cached) yes`
`checking how to print strings... printf`
`checking for a sed that does not truncate output... (cached) /bin/sed`
`checking for fgrep... /bin/grep -F`
`checking for ld used by gcc -std=gnu99 -std=gnu99... /usr/bin/ld`
`checking if the linker (/usr/bin/ld) is GNU ld... yes`
`checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B`
`checking the name lister (/usr/bin/nm -B) interface... BSD nm`
`checking the maximum length of command line arguments... 1572864`
`checking whether the shell understands some XSI constructs... yes`
`checking whether the shell understands "+="... yes`
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... `func_convert_file_noop`
`checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop`
`checking for /usr/bin/ld option to reload object files... -r`
`checking for objdump... objdump`
`checking how to recognize dependent libraries... pass_all`
`checking for dlltool... no`
`checking how to associate runtime and link libraries... printf %s\n`
`checking for archiver @FILE support... @`
`checking for strip... /usr/bin/strip`
`checking for ranlib... (cached) ranlib`
`checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 -std=gnu99 object... ok`
`checking for sysroot... no`
`checking for mt... no`
`checking if : is a manifest tool... no`
`checking for dlfcn.h... yes`
`checking for objdir... .libs`
`checking if gcc -std=gnu99 -std=gnu99 supports -fno-rtti -fno-exceptions... no`
`checking for gcc -std=gnu99 -std=gnu99 option to produce PIC... -fPIC -DPIC`
`checking if gcc -std=gnu99 -std=gnu99 PIC flag -fPIC -DPIC works... yes`
`checking if gcc -std=gnu99 -std=gnu99 static flag -static works... no`
`checking if gcc -std=gnu99 -std=gnu99 supports -c -o file.o... yes`
`checking if gcc -std=gnu99 -std=gnu99 supports -c -o file.o... (cached) yes`
checking whether the gcc -std=gnu99 -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared `libraries... yes`
`checking whether -lc should be explicitly linked in... no`
`checking dynamic linker characteristics... GNU/Linux ld.so`
`checking how to hardcode library paths into programs... immediate`
`checking for shl_load... no`
`checking for shl_load in -ldld... no`
`checking for dlopen... no`
`checking for dlopen in -ldl... yes`
`checking whether a program can dlopen itself... yes`
`checking whether a statically linked program can dlopen itself... yes`
`checking whether stripping libraries is possible... yes`
`checking if libtool supports shared libraries... yes`
`checking whether to build shared libraries... yes`
`checking whether to build static libraries... yes`
`checking which extension is used for runtime loadable modules... .so`
`checking which variable specifies run-time module search path... LD_LIBRARY_PATH`
`checking for the default library search path... /lib64 /usr/lib64 /lib /usr/lib /usr/lib64/dyninst/usr/lib64/mysql /usr/local/lib`
`checking for library containing dlopen... -ldl`
`checking for dlerror... yes`
`checking for shl_load... (cached) no`
`checking for shl_load in -ldld... (cached) no`
`checking for dld_link in -ldld... no`
`checking for _ prefix in compiled symbols... no`
`checking whether deplibs are loaded by dlopen... yes`
`checking for argz.h... yes`
`checking for error_t... yes`
`checking for argz_add... yes`
`checking for argz_append... yes`
`checking for argz_count... yes`
`checking for argz_create_sep... yes`
`checking for argz_insert... yes`
`checking for argz_next... yes`
`checking for argz_stringify... yes`
`checking if argz actually works... yes`
`checking whether libtool supports -dlopen/-dlpreopen... yes`
`checking for ltdl.h... yes`
`checking whether lt_dlinterface_register is declared... yes`
`checking for lt_dladvise_preload in -lltdl... yes`
`checking where to find libltdl headers...`
`checking where to find libltdl library... -lltdl`
`checking for unistd.h... (cached) yes`
`checking for dl.h... no`
`checking for sys/dl.h... no`
`checking for dld.h... no`
`checking for mach-o/dyld.h... no`
`checking for dirent.h... yes`
`checking for closedir... yes`
`checking for opendir... yes`
`checking for readdir... yes`
`checking for strlcat... no`
`checking for strlcpy... no`
`checking for lt_dladvise_init in -lltdl... yes`
`checking for X... disabled`
`checking for pkg-config... /usr/bin/pkg-config`
`checking pkg-config is at least version 0.25... yes`
`checking for msgfmt... /usr/bin/msgfmt`
`checking for xgettext... /usr/bin/xgettext`
`checking for indent... /usr/bin/indent`
`checking for wget... /usr/bin/wget`
`checking for unzip... /usr/bin/unzip`
`checking for update-mime-database... /usr/bin/update-mime-database`
`checking for update-desktop-database... :`
`checking for plutil... :`
`checking for a Python interpreter with version >= 2.7... python`
`checking for python... /usr/bin/python`
`checking for python version... 2.7`
`checking for python platform... linux2`
`checking for python script directory... ${prefix}/lib/python2.7/dist-packages`
`checking for python extension module directory... ${exec_prefix}/lib64/python2.7/dist-packages`
`checking for PYTHON... yes`
`checking for potrace... no`
`checking math.h usability... yes`
`checking math.h presence... yes`
`checking for math.h... yes`
`checking for library containing cos... -lm`
`checking for ZLIB... yes`
`checking for GLIB... yes`
`checking for FREETYPE... yes`
`checking for LIBXML... yes`
`checking for library containing DGifOpenFileName... -lgif`
`checking for library containing EGifGetGifVersion... no`
`checking gif_lib.h usability... yes`
`checking gif_lib.h presence... yes`
`checking for gif_lib.h... yes`
`checking for ExtensionBlock.Function in gif_lib.h... yes`
`checking Build with GIFLIB or LIBUNGIF support?... yes`
`checking jpeglib.h usability... yes`
`checking jpeglib.h presence... yes`
`checking for jpeglib.h... yes`
`checking for library containing jpeg_CreateDecompress... -ljpeg`
`checking Build with JPEG support?... yes`
`checking png.h usability... yes`
`checking png.h presence... yes`
`checking for png.h... yes`
`checking for library containing png_init_io... -lpng`
`checking Build with PNG support?... yes`
`checking tiffio.h usability... no`
`checking tiffio.h presence... no`
`checking for tiffio.h... no`
`checking Build with TIFF support?... no`
`checking for LIBCAIRO... yes`
`checking Build with Cairo support?... yes`
`checking spiroentrypoints.h usability... no`
`checking spiroentrypoints.h presence... no`
`checking for spiroentrypoints.h... no`
`checking Build with LibSpiro Curve Contour support?... no`
`checking uninameslist.h usability... no`
`checking uninameslist.h presence... no`
`checking for uninameslist.h... no`
`checking Build with LibUniNamesList Unicode support?... no`
`checking for LIBZMQ... no`
`configure: WARNING: LIBZMQ was not found. We will continue building without it.`
`checking for library containing rl_readline_version... no`
`checking for library containing rl_readline_version... no`
`checking Build with LibReadLine support?... no`
`checking for PANGOCAIRO... no`
`configure: error: Package requirements (pangocairo) were not met:`

`No package 'pangocairo' found`

`Consider adjusting the PKG_CONFIG_PATH environment variable if you`
`installed software in a non-standard prefix.`

`Alternatively, you may set the environment variables PANGOCAIRO_CFLAGS`
`and PANGOCAIRO_LIBS to avoid the need to call pkg-config.`
`See the pkg-config man page for more details.`

Im stuck at **configure** step itself

Please help

**Comment by jtanx** [comment]
Have you installed pango and cairo?

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : Thanks for response,
When I tried to install, I got the messages saying its already installed,

`yum install cairo`
`Package pango-1.28.1-10.11.amzn1.x86_64 already installed and latest version`

` yum install pango`
`Package cairo-1.12.14-6.8.amzn1.x86_64 already installed and latest version`

**Comment by jtanx** [comment]
Development packages? `pango-devel`, `cairo-devel`

And from https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#building-a-red-hat-source-package-rpm

```
rpm-devel rpm-build git perl autoconf automake tar libtool glibc-devel m4 gcc cpp python-devel libjpeg-turbo-devel libtiff-devel libpng-devel giflib-devel freetype-devel uuid-devel libtool-ltdl-devel bzip2-devel libxml2-devel libuninameslist-devel libspiro-devel pango-devel cairo-devel chrpath
```

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : Im able to cross the `configure` step but now I'm stuck at `rpmbuild` step

`/bin/sh ../libtool --mode=compile gcc -std=gnu99 -std=gnu99  -g -c -o \`
	`splinerefigure.lo "-I../inc" "-I../inc" "-I../lib" "-I../lib" `"-DSHAREDIR=\"/usr/local/share/fontforge\"" "-DDOCDIR=\"/usr/local/share/doc/fontforge\"" "-I../uthash/src" "-I../uthash/src" "-DFF_UTHASH_GLIF_NAMES=1" "-DPLUGINDIR=\"/usr/local/lib/fontforge/plugins\"" -Wl,--no-undefined   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -pthread -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libdrm   -I/usr/include/freetype2          -I/usr/include/libxml2   -I/usr/include/python2.7   -pthread  ./splinerefigure.c
`libtool: compile:  gcc -std=gnu99 -std=gnu99 -g -c -I../inc -I../inc -I../lib -I../lib `-DSHAREDIR=\"/usr/local/share/fontforge\" -DDOCDIR=\"/usr/local/share/doc/fontforge\" -I../uthash/src -I../uthash/src -DFF_UTHASH_GLIF_NAMES=1 -DPLUGINDIR=\"/usr/local/lib/fontforge/plugins\" -Wl,--no-undefined -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/python2.7 -pthread ./splinerefigure.c  -fPIC -DPIC -o .libs/splinerefigure.o
`libtool: compile:  gcc -std=gnu99 -std=gnu99 -g -c -I../inc -I../inc -I../lib -I../lib `-DSHAREDIR=\"/usr/local/share/fontforge\" -DDOCDIR=\"/usr/local/share/doc/fontforge\" -I../uthash/src -I../uthash/src -DFF_UTHASH_GLIF_NAMES=1 -DPLUGINDIR=\"/usr/local/lib/fontforge/plugins\" -Wl,--no-undefined -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/python2.7 -pthread ./splinerefigure.c -o splinerefigure.o >/dev/null 2>&1
`  CCLD     libfontforge.la`
`  GEN      .gitignore`
`make[4]: Leaving directory `/usr/src/rpm/BUILD/fontforge-20170731/fontforge/fontforge'`
`Making all in gdraw`
`make[4]: Entering directory `/usr/src/rpm/BUILD/fontforge-20170731/fontforge/gdraw'`
`  CC       libgdraw_la-choosericons.lo`
`  CC       libgdraw_la-ctlvalues.lo`
`  CC       libgdraw_la-drawboxborder.lo`
`  CC       libgdraw_la-gaskdlg.lo`
`  CC       libgdraw_la-gbuttons.lo`
`  CC       libgdraw_la-gcolor.lo`
`  CC       libgdraw_la-gchardlg.lo`
`  CC       libgdraw_la-gcontainer.lo`
`  CC       libgdraw_la-gdraw.lo`
`  CC       libgdraw_la-gdrawbuildchars.lo`
`  CC       libgdraw_la-gdrawerror.lo`
`  CC       libgdraw_la-gdrawtxt.lo`
`In file included from gdrawtxt.c:30:0:`
`fontP.h:176:5: error: unknown type name 'PangoFontDescription'`
`     PangoFontDescription *pango_fd;`
`     ^`
`fontP.h:178:5: error: unknown type name 'PangoFontDescription'`
`     PangoFontDescription *pangoc_fd;`
`     ^`
`In file included from gdrawtxt.c:31:0:`
`gxcdrawP.h:56:1: error: unknown type name 'PangoFontDescription'`
` extern PangoFontDescription *_GXPDraw_configfont(GWindow gw, GFont *font);`
` ^`
`make[4]: *** [libgdraw_la-gdrawtxt.lo] Error 1`
`make[4]: Leaving directory `/usr/src/rpm/BUILD/fontforge-20170731/fontforge/gdraw'`
`make[3]: *** [all-recursive] Error 1`
`make[3]: Leaving directory `/usr/src/rpm/BUILD/fontforge-20170731/fontforge'`
`make[2]: *** [all] Error 2``
`make[2]: Leaving directory `/usr/src/rpm/BUILD/fontforge-20170731/fontforge'`
`make[1]: *** [all-recursive] Error 1``
`make[1]: Leaving directory `/usr/src/rpm/BUILD/fontforge-20170731'`
`make: *** [all] Error 2``
`error: Bad exit status from /var/tmp/rpm-tmp.epljTC (%build)`
`RPM build errors:``
`    Bad exit status from /var/tmp/rpm-tmp.epljTC (%build)`

**Comment by jtanx** [comment]
What did you do to make `configure` work?

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : Sorry for the late reply, I just installed the dependencies you mentioned in the previous comment in this thread, and it worked for me

**Comment by jtanx** [comment]
Hmm, without access to that build environment, I'm not too sure.

What's the output from running

```
pkg-config --cflags pango
pkg-config --libs pango
pkg-config --cflags cairo
pkg-config --libs cairo
```

?

What's your use case for compiling FontForge on AMI? If you're only after scripting, then you could try `./configure --without-x`. However, if this is part of some web service, just beware of the security implications of running FontForge on untrusted user input; it wasn't exactly built with this in mind.

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx: we need fontforge for https://github.com/FontCustom/fontcustom gem to work and with fonctcustom, as we are generating font icons in AMI 

Also these are outputs for the commands you have mentioned:
```
pkg-config --cflags pango
-pthread -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include

pkg-config --libs pango
-pthread -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0

pkg-config --libs cairo
-lcairo

pkg-config --cflags cairo
-I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libdrm

```
Also note that when I checked using yum what is the available fontforge version in amazon repo by using the command `yum info fontforge`, this is the output:
```
Available Packages
Name        : fontforge
Arch        : i686
Version     : 20090622
Release     : 3.1.7.amzn1
Size        : 6.4 M
Repo        : amzn-main/2016.09
Summary     : Outline and bitmap font editor
URL         : http://fontforge.sourceforge.net/
License     : BSD
Description : FontForge (former PfaEdit) is a font editor for outline and bitmap
            : fonts. It supports a range of font formats, including PostScript
            : (ASCII and binary Type 1, some Type 3 and Type 0), TrueType, OpenType
            : (Type2) and CID-keyed fonts.

Name        : fontforge
Arch        : x86_64
Version     : 20090622
Release     : 3.1.7.amzn1
Size        : 6.5 M
Repo        : amzn-main/2016.09
Summary     : Outline and bitmap font editor
URL         : http://fontforge.sourceforge.net/
License     : BSD
Description : FontForge (former PfaEdit) is a font editor for outline and bitmap
            : fonts. It supports a range of font formats, including PostScript
            : (ASCII and binary Type 1, some Type 3 and Type 0), TrueType, OpenType
            : (Type2) and CID-keyed fonts.
```

So, anyway you guys can help in uploading the new fontforge version to amazon repo?

**Comment by jtanx** [comment]
I have no idea how that package is being made. Since you're using it for FontCustom, have you tried configuring with

`./configure --without-x` as suggested before?

If you really need that gui, can you see `PangoFontDescription` in `/usr/include/pango-1.0/pango/pango-font.h`? Someting along the lines of

```c
typedef struct _PangoFontDescription PangoFontDescription;
```

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : We dont need gui of font forge
I have attached what I have tried, I am able to do `./configure --without-x` but the problem comes in the `rpmbuild` step mentioned in the https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md#building-a-red-hat-source-package-rpm

I have attached the error log also to get the full picture
[error.log](https://github.com/fontforge/fontforge/files/1470671/error.log)

**Comment by jtanx** [comment]
@sarathprasath-krishnaswamy thanks for the log, I think I understand a bit better.

I'm not familiar with RPM packaging (@frank-trampe may know better), but from the looks of it, to disable the gui, you'll need to modify that  `fontforge-20170731.spec` - where it has the `./configure` step - there is where you need to add the `--without-x` option.

I'm just guessing here, but perhaps the reason why it's failing to compile as is, is because the dependencies (e.g. on pango) aren't specified correctly in that spec file too.

**Comment by sarathprasath-krishnaswamy** [comment]
Adding the output of the spec file
```
[root@application1 ~]# cat ~/rpmbuild/SPECS/fontforge-20170731.spec

Name: fontforge
Version: 20170731
Release: 1
License: GPLv3
Vendor: FontForge
URL: http://fontforge.github.io/
Packager: Package Maintainer <releases@fontforge.org>
Summary: Computer typeface editor
Source: fontforge-20170731.tar.gz
Requires: libgdraw4 = 20170731, libfontforge1 = 20170731, fontforge-common = 20170731

%define _unpackaged_files_terminate_build 0

%prep
%setup

%description
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%build
./bootstrap;
./configure --prefix=/usr --libdir=/usr/lib --mandir=/usr/share/man --with-regular-link --enable-devicetables --enable-type3 --enable-pyextension;
make;

%install
make install DESTDIR="$RPM_BUILD_ROOT";
find "$RPM_BUILD_ROOT"//usr/lib -name "*.la" -delete;
chrpath -d "$RPM_BUILD_ROOT"//usr/bin/fontforge;
chmod 0644 "$RPM_BUILD_ROOT"//usr/lib/lib*.so.*;
(cd "$RPM_BUILD_ROOT"//usr/lib; for i in python*; do if [ -e $i/site-packages ] ; then mv $i/site-packages $i/dist-packages; fi ; done)
mkdir -p "$RPM_BUILD_ROOT"/usr/share/pixmaps ;
cp -pRP desktop/icons/* "$RPM_BUILD_ROOT"//usr/share/icons/ ;
cp -pRP Packaging/debian/cp-src/fontforge.xpm "$RPM_BUILD_ROOT"//usr/share/pixmaps/ ;
cp -pRP desktop/fontforge.desktop "$RPM_BUILD_ROOT"//usr/share/applications/ ;

%pre

%post

%preun

%postun

%clean

%files
%defattr(-,root,root)
%attr(0755,root,root) /usr/bin/fontforge
%attr(0755,root,root) /usr/bin/fontimage
%attr(0755,root,root) /usr/bin/fontlint
%attr(0755,root,root) /usr/bin/sfddiff
%attr(0644,root,root) /usr/share/applications/fontforge.desktop
%attr(0644,root,root) /usr/share/man/man1/fontforge.1.gz
%attr(0644,root,root) /usr/share/man/man1/fontimage.1.gz
%attr(0644,root,root) /usr/share/man/man1/fontlint.1.gz
%attr(0644,root,root) /usr/share/man/man1/sfddiff.1.gz
%attr(0644,root,root) /usr/share/mime/packages/fontforge.xml

%package -n libfontforge1
Requires: libgcc1
Summary: FontForge libraries

%description -n libfontforge1
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre -n libfontforge1

%post -n libfontforge1

%preun -n libfontforge1

%postun -n libfontforge1

%files -n libfontforge1
%defattr(-,root,root)
/usr/lib/libgioftp.so
/usr/lib/libgunicode.so
/usr/lib/libfontforge.so
/usr/lib/libfontforgeexe.so
/usr/lib/libgutils.so
/usr/lib/libgioftp.so.*
/usr/lib/libgunicode.so.*
/usr/lib/libfontforge.so.*
/usr/lib/libfontforgeexe.so.*
/usr/lib/libgutils.so.*

%package -n fontforge-devel
Requires: libfontforge1 = 20170731, libgdraw4 = 20170731
Summary: FontForge development headers

%description -n fontforge-devel
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre -n fontforge-devel

%post -n fontforge-devel

%preun -n fontforge-devel

%postun -n fontforge-devel

%files -n fontforge-devel
%defattr(-,root,root)
%attr(0644,root,root) /usr/include/fontforge/*.h
%attr(0644,root,root) /usr/lib/pkgconfig/*.pc

%package -n libgdraw4
Requires: libgcc1
Summary: gdraw libraries

%description -n libgdraw4
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre -n libgdraw4

%post -n libgdraw4

%preun -n libgdraw4

%postun -n libgdraw4

%files -n libgdraw4
%defattr(-,root,root)
/usr/lib/libgdraw.so
/usr/lib/libgdraw.so.*

%package -n python-fontforge
Requires: libfontforge1 = 20170731
Summary: Python bindings

%description -n python-fontforge
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre -n python-fontforge

%post -n python-fontforge

%preun -n python-fontforge

%postun -n python-fontforge

%files -n python-fontforge
%defattr(-,root,root)
%attr(0644,root,root) /usr/lib*/python*/[a-z]*-packages/psMat.so
%attr(0644,root,root) /usr/lib*/python*/[a-z]*-packages/fontforge.so
%attr(0644,root,root) /usr/share/fontforge/python/excepthook.py

%package common
Summary: Platform-independent support files

%description common
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre common

%post common

%preun common

%postun common

%files common
%defattr(-,root,root)
%attr(0644,root,root) /usr/share/locale/*/LC_MESSAGES/FontForge.mo
%attr(0644,root,root) /usr/share/icons/*x*/apps/fontforge.png
%attr(0644,root,root) /usr/share/icons/src/icon-*x*-apps-fontforge.svg
%attr(0644,root,root) /usr/share/icons/scalable/apps/fontforge.svg
%attr(0644,root,root) /usr/share/pixmaps/fontforge.xpm

%package doc
Summary: Documentation

%description doc
FontForge provides a complete suite of tools for producing high-quality typefaces and supports a wide range of file formats including TrueType, OpenType, PostScript, and U. F. O..

%pre doc

%post doc

%preun doc

%postun doc

%files common
%defattr(-,root,root)
%attr(0644,root,root) /usr/share/doc/fontforge/*.*
%attr(0644,root,root) /usr/share/doc/fontforge/flags/*.*

[root@application1 ~]#
```

**Comment by jtanx** [comment]
So did you try modifying it as suggested?

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : Yes, thats what I have given the error.log where the `configure --without-x` step is also there

**Comment by sarathprasath-krishnaswamy** [comment]
@jtanx : I have made the change & tried, now I got new error
Attached the error log
[configure_without_x_error.log](https://github.com/fontforge/fontforge/files/1473503/configure_without_x_error.log)

**Comment by jtanx** [comment]
* Your source structure is really weird. It first builds `/usr/src/rpm/BUILD/fontforge-20170731/fontforge/fontforgeexe`, then it tries to build `/usr/src/rpm/BUILD/fontforge-20170731/fontforgeexe`. Why are there two copies of fontforgeexe? Are you sure you generated your source tarball from a clean source tree?
* You appear to be using the 20170731 sources. Since you're building `--without-x`, you'll need to manually patch this change in: https://github.com/fontforge/fontforge/commit/72572a68d306712c040ca741f0655b190326a509#diff-6eb6f4d97683cbba5350f363660043b5R30 to `startnoui.c`, otherwise even if you could get it to build, it won't run correctly.

**Comment by frank-trampe** [comment]
Any updates, @sarathprasath-krishnaswamy?
