### ISSUE TITLE
Fontforge crashes when creating OpenType Fonts

### ISSUE THREAD

**Issue by JLapage** [fontforge/fontforge#3206]
I'm trying to make a slightly weird font - it's an autoligaturing font for a sci fi language (Xi'an from Star Citizen). I had some success up to this point, but suddenly I can no longer export opentype fonts. I go through the usual steps, get no Validation Errors but the GUI drops and a Zero byte font is generated.

The problem started when I added 'simplify' commands to the script that is generating this font. That was done because one character was having self-intersection issues (I didn't design them, they are ripped from a PDF). However, rolling the script to remove this doesn't seem to help. I was also concerned that maybe my substitution tables were getting too big, so I tried splitting them - also no luck. 

I have also tried reinstalling fontforge (though it was the same version) and clearing the font cache with FontNuke. Reinstalling xQuartz similarly had no effect.

I have put a save of the offending file on pastebin: https://pastebin.com/6bH8Z94b

I am on MacOS Sierra 10.12.6 and using the version of fontforge linked in the 'simple' download guide for Mac: 19:05 UTC 30-Jul-2017-ML-D

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot (can't screenshot a missing GUI!)
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by JLapage** [comment]
Closed issue because despite an hour of trying everything it is suddenly working again...

**Comment by jtanx** [comment]
Thanks for reporting. It might be a problem, although hard to say. Valgrind output for some random version of FF that I have installed at the moment:

```
==2238== Conditional jump or move depends on uninitialised value(s)
==2238==    at 0x6D4EBB8: FigureStemActive (stemdb.c:3525)
==2238==    by 0x6D5AAA9: GlyphDataBuild (stemdb.c:5986)
==2238==    by 0x6A42592: _SplineCharAutoHint (autohint.c:2954)
==2238==    by 0x6A42726: __SplineCharAutoHint (autohint.c:2981)
==2238==    by 0x6A42859: SplineCharAutoHint (autohint.c:2994)
==2238==    by 0x6CE27C6: SplineFont2ChrsSubrs2 (splinesave.c:3241)
==2238==    by 0x6D9492B: dumptype2glyphs (tottf.c:2632)
==2238==    by 0x6DA297C: initTables (tottf.c:5734)
==2238==    by 0x6DA473B: _WriteTTFFont (tottf.c:6127)
==2238==    by 0x6DA485A: WriteTTFFont (tottf.c:6160)
==2238==    by 0x6BF405E: _DoSave (savefont.c:840)
==2238==    by 0x6BF5E93: GenerateScript (savefont.c:1249)
==2238== 
==2238== Conditional jump or move depends on uninitialised value(s)
==2238==    at 0x6D4EBC2: FigureStemActive (stemdb.c:3525)
==2238==    by 0x6D5AAA9: GlyphDataBuild (stemdb.c:5986)
==2238==    by 0x6A42592: _SplineCharAutoHint (autohint.c:2954)
==2238==    by 0x6A42726: __SplineCharAutoHint (autohint.c:2981)
==2238==    by 0x6A42859: SplineCharAutoHint (autohint.c:2994)
==2238==    by 0x6CE27C6: SplineFont2ChrsSubrs2 (splinesave.c:3241)
==2238==    by 0x6D9492B: dumptype2glyphs (tottf.c:2632)
==2238==    by 0x6DA297C: initTables (tottf.c:5734)
==2238==    by 0x6DA473B: _WriteTTFFont (tottf.c:6127)
==2238==    by 0x6DA485A: WriteTTFFont (tottf.c:6160)
==2238==    by 0x6BF405E: _DoSave (savefont.c:840)
==2238==    by 0x6BF5E93: GenerateScript (savefont.c:1249)
==2238== 
==2238== Conditional jump or move depends on uninitialised value(s)
==2238==    at 0x6D4E979: FigureStemActive (stemdb.c:3513)
==2238==    by 0x6D5AAA9: GlyphDataBuild (stemdb.c:5986)
==2238==    by 0x6A42592: _SplineCharAutoHint (autohint.c:2954)
==2238==    by 0x6A42726: __SplineCharAutoHint (autohint.c:2981)
==2238==    by 0x6A42859: SplineCharAutoHint (autohint.c:2994)
==2238==    by 0x6CE27C6: SplineFont2ChrsSubrs2 (splinesave.c:3241)
==2238==    by 0x6D9492B: dumptype2glyphs (tottf.c:2632)
==2238==    by 0x6DA297C: initTables (tottf.c:5734)
==2238==    by 0x6DA473B: _WriteTTFFont (tottf.c:6127)
==2238==    by 0x6DA485A: WriteTTFFont (tottf.c:6160)
==2238==    by 0x6BF405E: _DoSave (savefont.c:840)
==2238==    by 0x6BF5E93: GenerateScript (savefont.c:1249)
==2238== 
==2238== Conditional jump or move depends on uninitialised value(s)
==2238==    at 0x6D4E987: FigureStemActive (stemdb.c:3513)
==2238==    by 0x6D5AAA9: GlyphDataBuild (stemdb.c:5986)
==2238==    by 0x6A42592: _SplineCharAutoHint (autohint.c:2954)
==2238==    by 0x6A42726: __SplineCharAutoHint (autohint.c:2981)
==2238==    by 0x6A42859: SplineCharAutoHint (autohint.c:2994)
==2238==    by 0x6CE27C6: SplineFont2ChrsSubrs2 (splinesave.c:3241)
==2238==    by 0x6D9492B: dumptype2glyphs (tottf.c:2632)
==2238==    by 0x6DA297C: initTables (tottf.c:5734)
==2238==    by 0x6DA473B: _WriteTTFFont (tottf.c:6127)
==2238==    by 0x6DA485A: WriteTTFFont (tottf.c:6160)
==2238==    by 0x6BF405E: _DoSave (savefont.c:840)
==2238==    by 0x6BF5E93: GenerateScript (savefont.c:1249)
==2238== 
```

**Comment by JLapage** [comment]
I narrowed the problem down to the fact that it only crashes if I have just run a python script. I'm using a script to populate my font, so all I have to do is save as an sfd, restart fontforge, and then export. Kinda inconvenient but an easy workaround.
