### ISSUE TITLE
Bug in downloading font-forge

### ISSUE THREAD

**Issue by KshitijaaJaglan** [fontforge/fontforge#3207]
While downloading font forge here [https://fontforge.github.io/en-US/downloads/windows/](https://fontforge.github.io/en-US/downloads/windows/)
![image](https://user-images.githubusercontent.com/29124655/33202975-8163cf62-d124-11e7-8189-e8e6f675bce3.png)
and after submitting the email id, here as abc@xyz.qwe,
the download doesn't start, instead, the email id is added to the url.
![image](https://user-images.githubusercontent.com/29124655/33203099-f6ad54e6-d124-11e7-9a75-914bc4ee116b.png)

### Important
This problem doesn't occur for the first time the user enters the email id, but takes place everytime after that.

I am using windows 7 ultimate, and chrome

**Comment by frank-trampe** [comment]
The specific problem was that, although the button worked, the form submission was triggering a page reload. I just fixed it.
