### ISSUE TITLE
Windows-1251 character encoding

### ISSUE THREAD

**Issue by typedesigner** [fontforge/fontforge#3214]
@davelab6 @jtanx @frank-trampe  
**I would suggest including this encoding in FontForge:**

Windows-1251 is a popular 8-bit character encoding, designed to cover languages that use the Cyrillic script such as Russian, Bulgarian, Serbian Cyrillic and other languages. It is the most widely used for encoding the Bulgarian, Serbian and Macedonian languages.

[https://en.wikipedia.org/wiki/Windows-1251](url)

**Comment by jtanx** [comment]
If you want that then go `Encoding->Add encoding name` and enter CP1251 then reencode as that.

**Comment by typedesigner** [comment]
Thanks!
