### ISSUE TITLE
Missing script in FontForge-2017-07-31-Windows-r2: no way to run command-line interface

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#3221]
The supplied `fontforge-console.bat` script just starts a new console.  It should either be corrected so that
in presence of command-line arguments it passes them to `fontforge`, or another script (I call mine `fontforge-do.bat`, attached) should be provided.  (It is enough to remove `echo`s from `fontforge-console`, and add a line

    "%FF%\bin\fontforge.exe" -nosplash %*

at the end.)

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

**Comment by ilyaza** [comment]
Apparently, attaching did not work (or my Firefox is too old).  I just put the file here:

    @echo off
    @rem echo Configuring the system path to add FontForge...
    set FF=%~dp0
    set "PYTHONHOME=%FF%"
    set "PYTHONPATH=%FF%lib\python2.7"
    set "PATH=%FF%;%FF%\bin;%PATH%"
    set FF_PATH_ADDED=TRUE

    "%FF%\bin\fontforge.exe" -nosplash %*

**Comment by ilyaza** [comment]
[fontforge-do.bat.txt](https://github.com/fontforge/fontforge/files/1558082/fontforge-do.bat.txt)
Another attempt to attach…  (Needed to append `.txt` to file name.)

**Comment by jtanx** [comment]
That's not the point of fontforge-console.bat.

The batch file sets up a console with a modified PATH variable so that you can run `fontforge` (the cli) from it. Or you could just call fontforge.bat directly yourself.
