### ISSUE TITLE
Defective splines produced by FontForge-2017-07-31-Windows-r2

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#3223]
Running the following script

    fontforge-do -lang=ff -c "Open($1); SelectAll(); ExpandStroke(64.545,1,1,0,1); RemoveOverlap(); SetFontOrder(2); Simplify(128,2.05); Simplify(128,2.05); RoundToInt(); RoundToInt(); AddInstrs('prep', 1, 'PUSHW_1 511 SCANCTRL PUSHB_1 4 SCANTYPE'); Save($2);" input-wrong-render.sfd out.sfd

on the attached file produces a working `out.sfd` file.   Opening the resulting file in FontForge, doing Ctrl-A Ctrl-E
(“Find Problems” with all glyphs) and choosing “Open Paths” and “Intersecting Paths” on the pane “Paths” shows that **all** the generated glyphs are defective.

This is not completely new; the version `2014_01_04` would produce much more severe problems.

[input-wrong-render.sfd.txt](https://github.com/fontforge/fontforge/files/1558111/input-wrong-render.sfd.txt)

**Update:** I double-checked, and many of these runs do not produce any warnings.  (I will report glyphs with warnings, but with no-problem output in a separate issue report.)  In fact, this is a continuation of the issue #3222: I found all the glyphs among the first 4′096 of “Smoothed” Unifont which crash FontForge, produce wrong output, and warnings; I separate them into 3 bug reports.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by HugoLisbona** [comment]
Hello and thanks for posting this issue.

I'm having a very similar problem with FontForge:

Some of the SVG files exported from illustrator are missing parts of the splines when imported in FontForge. 
So I have half-letters o no letters at all in FontForge. 

I double-checked the defective FontForge splines's designs, and in Illustrator all of them are designed in the exact same way.

So I don't know why just some of them are missing out splines in FontForge. 

Please any help on this issue?

(I'm new in github, hence if I'm missing some important info to explain the issue please let me know)

Kind regards, 
Hugo. 

I use the last available FontForge version together with windows 10 64bits.

**Comment by skef** [comment]
With the new Expand Stroke code there are no errors reported.
