### ISSUE TITLE
How to use another letter as a diacritical mark? 

### ISSUE THREAD

**Issue by thebigfootsdad** [fontforge/fontforge#3226]
So I'm creating a con-Lang and I am working on a custom font. It doesn't have vowels, but rather has diacritical marks/accents to go on top of the letters (and a bar underneath for stress/duplication). I tried using anchors through [this method](https://github.com/fontforge/fontforge/wiki/How-To-Create-Anchors) from the wiki here, which works for what Unicode defines as diacritical marks (such as the circumflex accent at `uni302`) , but I would much rather have the `a`, `e`, `i`, `o`, and `u` keys represent the marks. 
When checking through `ctrl+k`, however the anchor doesn't work. I can't simply set the width to 0 and then place the accent/bar before it because each glyph has a different height. 

I'm pretty new at this, and I don't really know where else to go to find an answer?

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using : Version 20:55 AWST 4 Oct 2016 on Windows 10
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by moyogo** [comment]
Have a lookup to zero the advance width of your vowels. Then you can have cursive anchors or use positioning in the y-direction to place it in top on the previous letter.

**Comment by thebigfootsdad** [comment]
I'm going to try and see if I can use kerning classes to define the location for ones with similar parameters. I'll come back once I'm done

**Comment by thebigfootsdad** [comment]
Ok so the horizontal kerning works, but not the vertical... :(

**Comment by moyogo** [comment]
Which applications have you tested? Any browsers?

**Comment by thebigfootsdad** [comment]
But nwither work in a word processing program

**Comment by thebigfootsdad** [comment]
Here are the screenshots of what's going on: 

hkern: ![image](https://user-images.githubusercontent.com/17292078/34228735-c40ec286-e5e2-11e7-8a0b-64b5a1f9df3a.png)

vkern: ![image](https://user-images.githubusercontent.com/17292078/34228745-d6e94854-e5e2-11e7-90df-3b2007e4389b.png)

wpp (same happens in MS Word and Adobe InDesign): 
![image](https://user-images.githubusercontent.com/17292078/34228803-10024bcc-e5e3-11e7-98d0-0e0f709a99c9.png)

-- I don't know if this is relevant, but in the top-right corner where I can choose a subtable, I can only choose the horizontal one, and not the vertical one, whether previewing hkern or vkern: 
![image](https://user-images.githubusercontent.com/17292078/34228870-4fcd90b8-e5e3-11e7-8fc5-d32dfc4d5030.png)

**Comment by thebigfootsdad** [comment]
I'll try firefox (my browser) now

**Comment by thebigfootsdad** [comment]
The horizontal kerning works in my browser, but not the vertical.

**Comment by moyogo** [comment]
Ah, don't use the vkrn feature tag. Have the vertical offset (and the horizontal zeroing of the advance width) in the positioning lookup of your kern feature.

**Comment by thebigfootsdad** [comment]
I'm not really getting how to do that? could you maybe explain more? 
Should I add a new GPOS Lookup for positioning and use regular kern or simply modify the one I have? 
Is it a matter of a new subtable? What should I modify?

I'm really sorry for all the questions, I just really don't know how to go on

**Comment by moyogo** [comment]
@thebigfootsdad I’ve manage to try my idea in FontForge:
* Create a GPOS Single Position lookup, I’ll call it lookup1 here, no feature, no script/language, just a add the name.
* Add a subtable to lookup1 and for each letter that is a diacritical mark, add an entry when the ∆x = ∆x_adv = - advance width of the glyph, and ∆y is the height difference of the diacritical mark.
* Add a GPOS Contextual Position lookup, kern feature and latn{dflt} script/language
* Add a subtable to that kern feature where you define the context where you want the lookup1 to be applied.

**Comment by ctrlcctrlv** [comment]
Closed as stale, answered question.

**Comment by giancarloantonucci** [comment]
Like the OP, I also want to make custom diacritics outside of the range defined by Unicode. Specifically, I want some custom "/triangleabovecombining" to appear above "m", which right now accepts the normal "/ringabovecombining" via a simple mark-to-base lookup (for better positioning). Now, I've followed the steps outlined by @moyogo but I don't understand the last one:

> * Add a subtable to that kern feature where you define the context where you want the lookup1 to be applied.

Can anyone expand on that?
