### ISSUE TITLE
Python: How to catch warning "I'm sorry this file is too complex for me to ..."

### ISSUE THREAD

**Issue by ArmandoAssuncao** [fontforge/fontforge#3230]
Hi, how could i catch the warning `I'm sorry this file is too complex for me to understand (or is erroneous)` , when the fontforge not recognize the svg?

my python code:
```
# my_script.py
# -*- coding: utf-8 -*-
import fontforge

font = fontforge.font()
char = font.createChar(1000)
glyph = char.importOutlines('svg_not_recognized.svg') # this line that shows the message
font.generate(output.ttf) # generates a font empty
```
running script:
`fontforge -quiet -script my_script.py`

Have any way of catch this warning?
Something like:
```
try:
  glyph = char.importOutlines('svg_not_recognized.svg')
except: 
  # do something
```

python 2.7.12
GNU/Linux
fontforge 00:15 UTC 31-Jul-2017
libfontforge 20170731

thanks

**Comment by ctrlcctrlv** [comment]
This is ridiculously hacky, but you could check `char.changed` after the call to `char.importOutlines`. If this does not work, you could check if the char has any points by checking `char.anchorPoints`. `char.importOutlines` returns nothing of value as far as I know, so your assignment to `glyph` is pointless.

The FontForge Python API is not what anyone would call Pythonic. There are no exceptions, as far as I know, outside of methods bound to the `fontforge` module - class members such as `glyph` have none.

**Comment by ArmandoAssuncao** [comment]
@ctrlcctrlv yep, the assignment to `glyph` not make sense, is the same that var `char`.
I'm testing with the `char.changed` method, seems to be working well.

thanks
