### ISSUE TITLE
FontForge-2017-07-31-Windows-r2 in glyph view: impossible to see fine details of a stroke

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#3237]
The brown outline zooms together with control points; so no matter how deep one zooms, the points are hardly visible.

I think the generated outline should not zoom to more than 7pt on the screen…  See the screenshot of the attached `.sfd` file.

![clip-fontforge-tip](https://user-images.githubusercontent.com/4063329/34318239-0487a184-e778-11e7-9e96-feb4a941a8cd.png)
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

[unifont.massaged_1_222_M-n.sfd.txt](https://github.com/fontforge/fontforge/files/1583975/unifont.massaged_1_222_M-n.sfd.txt)

**Comment by skef** [comment]
Ah -- I knew I remembered that there was a filed issue on this. Fixed by #4003.
