### ISSUE TITLE
Mystery: colors in UI (FontForge-2017-07-31-Windows-r2)

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#3241]
Is there a way to discover what different colors in UI actually **mean**?

In the glyphs overview window, I can see `Blue` about characters with glyphs.  I can see `DarkBlue` for the processed part of font when a long-running operation is active.

In a glyph view window, I can see `Wide brown` for open curved strokes, `Narrow Brown` for open straight strokes, `Gray` for closed strokes.

Are there other highlights? — And how a user is expected to find out about them?

- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
>Is there a way to discover what different colors in UI actually mean?

Not to be rude, but reading the source code is one way.

Here's some old documentation that answers (some) of your questions.

http://pfaedit.org/fontview.html

**Comment by skef** [comment]
The place to do this is in the analogous tab of the X Resource (appearance) Editor, under File. Almost all of the colors have tool-tips, so first find the color and then hover your mouse over it.
