### ISSUE TITLE
[Question] Where can I learn more about the OpenType format or where can I ask questions about an implementation of the OpenType format?

### ISSUE THREAD

**Issue by TsundereBug** [fontforge/fontforge#3244]
I'm trying to write a Scala library allowing me to construct OpenType Emoji fonts, and at this point I'm really stuck because of font terminology. I know this really isn't a question about fontforge, but I figured I could get some questions answered here.

So where's the best place to ask about my implementation of the OpenType font?

**Comment by moyogo** [comment]
There's the OpenType mailing list: https://www.microsoft.com/typography/otspec/otlist.htm.

There are also forums like http://typedrawers.com/ or http://www.typophile.com/ but those are not that technical.

**Comment by TsundereBug** [comment]
Thank you! 😁
