### ISSUE TITLE
 Hello, is there a Chinese version of this software? Or how to set up in Chinese

### ISSUE THREAD

**Issue by juanyungong** [fontforge/fontforge#3252]
我今天下载了很多次，这个软件的不同版本。
I downloaded many times today, the different versions of the software.
安装了很多次，网络搜索到的方法无法使他成为中文操作
It has been installed many times, and the network search method does not make him a Chinese operation
所以想请问下，这款软件应该怎么设置中文呢？
So I want to ask, how should this software be set up in Chinese?
因为我看到百度的介绍是这款软件包含中文的，但是不知道怎么设置。
Because I see Baidu's introduction that this software contains Chinese, but I don't know how to set it.
打扰各位了
Disturb you

**Comment by jtanx** [comment]
On windows, edit `fontforge.bat`, and uncomment/set

```bat
set LANGUAGE=zh_CN
```
