### ISSUE TITLE
FontForge crashes instantly on launch following a force-quit

### ISSUE THREAD

**Issue by practik** [fontforge/fontforge#3261]
Running FF 20170730 on macOS 10.12.6 / XQuartz 2.7.11:

The last time I used FF was couple of weeks ago.  Some time after quitting, I noticed my fan revving really high, so I checked Activity Monitor, saw that the culprit was a still-running FF process (either `fontforge` or `FontForge`, not sure which, though I'm guessing `fontforge`), and forced that process to quit.

Today when I tried to use FF again, it repeatedly crashed instantly on launch. Checking the logs, I saw that the `fc-cache` process was crashing because it couldn't find `libfontconfig.1.dylib`. mw9's fix from https://github.com/fontforge/fontforge/issues/2701#issuecomment-261817423 solved that problem, but now the `fontforge` process is crashing instead:

<details>

    Process:               fontforge [2307]
    Path:                  /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
    Identifier:            fontforge
    Version:               0
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           fontforge [2307]
    User ID:               501
    
    Date/Time:             2018-03-07 23:32:24.036 -0700
    OS Version:            Mac OS X 10.12.6 (16G1212)
    Report Version:        12
    Anonymous UUID:        BE1A6E78-F7D8-F0A3-B3AC-C50F279FE8F9
    
    
    Time Awake Since Boot: 4700 seconds
    
    System Integrity Protection: enabled
    
    Crashed Thread:        0  Dispatch queue: com.apple.main-thread
    
    Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
    Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
    Exception Note:        EXC_CORPSE_NOTIFY
    
    Termination Signal:    Segmentation fault: 11
    Termination Reason:    Namespace SIGNAL, Code 0xb
    Terminating Process:   exc handler [0]
    
    VM Regions Near 0:
    --> 
        __TEXT                 0000000106f7f000-0000000106f8a000 [   44K] r-x/rwx SM=COW  /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
    
    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   com.apple.CoreFoundation      	0x00007fff8b239ad8 CFArrayGetCount + 24
    1   libpangocairo-1.0.0.dylib     	0x0000000107e9eb67 pango_core_text_family_list_faces + 377
    2   libpangocairo-1.0.0.dylib     	0x0000000107e9f648 pango_core_text_fontset_new + 129
    3   libpangocairo-1.0.0.dylib     	0x0000000107e9f227 pango_core_text_font_map_load_fontset + 124
    4   libpangocairo-1.0.0.dylib     	0x0000000107e9f0e2 pango_core_text_font_map_load_font + 59
    5   libpangocairo-1.0.0.dylib     	0x0000000107e9a8d5 _pango_cairo_font_private_get_hex_box_info + 989
    6   libpangocairo-1.0.0.dylib     	0x0000000107e9af16 _pango_cairo_font_private_get_glyph_extents + 395
    7   libpangocairo-1.0.0.dylib     	0x0000000107ea0479 _pango_core_text_shape + 1591
    8   libpangocairo-1.0.0.dylib     	0x0000000107e9de8a _pango_core_text_shape_engine_shape + 40
    9   libpango-1.0.0.dylib          	0x0000000107fdbe28 _pango_engine_shape_shape + 47
    10  libpango-1.0.0.dylib          	0x0000000107feb564 pango_shape_full + 194
    11  libpango-1.0.0.dylib          	0x0000000107fe54c7 shape_run + 863
    12  libpango-1.0.0.dylib          	0x0000000107fe4b7b process_item + 85
    13  libpango-1.0.0.dylib          	0x0000000107fdf50a pango_layout_check_lines + 1627
    14  libpango-1.0.0.dylib          	0x0000000107fe2c51 pango_layout_get_extents_internal + 46
    15  libpango-1.0.0.dylib          	0x0000000107fe2fff pango_layout_get_pixel_extents + 71
    16  libgdraw.5.dylib              	0x00000001072f4a83 _GXPDraw_DoText8 + 117 (gxcdraw.c:1007)
    17  libgdraw.5.dylib              	0x00000001072af0dc GDrawGetText8Bounds + 78 (gdrawtxt.c:130)
    18  libfontforgeexe.2.dylib       	0x00000001070449fc v_e_h + 3936 (fontview.c:6289)
    19  libgdraw.5.dylib              	0x00000001072abb70 _GWidget_Container_eh + 220 (gcontainer.c:281)
    20  libgdraw.5.dylib              	0x00000001072eddf9 GXDrawRequestExpose + 383 (gxdraw.c:2486)
    21  libfontforgeexe.2.dylib       	0x0000000107045a3c v_e_h + 8096 (fontview.c:6951)
    22  libgdraw.5.dylib              	0x00000001072ac09e _GWidget_Container_eh + 1546 (gcontainer.c:403)
    23  libgdraw.5.dylib              	0x00000001072f0f27 GXDrawCheckPendingTimers + 212 (gxdraw.c:2656)
    24  libgdraw.5.dylib              	0x00000001072ef2ff GXDrawWaitForEvent + 644 (gxdraw.c:2721)
    25  libgdraw.5.dylib              	0x00000001072ee0b7 GXDrawEventLoop + 43 (gxdraw.c:3403)
    26  libfontforgeexe.2.dylib       	0x00000001070d04b9 fontforge_main + 6679 (startui.c:1373)
    27  libdyld.dylib                 	0x00007fffa0e55235 start + 1
    
    Thread 1:
    0   libsystem_kernel.dylib        	0x00007fffa0f8444e __workq_kernreturn + 10
    1   libsystem_pthread.dylib       	0x00007fffa106e621 _pthread_wqthread + 1426
    2   libsystem_pthread.dylib       	0x00007fffa106e07d start_wqthread + 13
    
    Thread 2:
    0   libsystem_kernel.dylib        	0x00007fffa0f8444e __workq_kernreturn + 10
    1   libsystem_pthread.dylib       	0x00007fffa106e621 _pthread_wqthread + 1426
    2   libsystem_pthread.dylib       	0x00007fffa106e07d start_wqthread + 13
    
    Thread 3:
    0   libsystem_kernel.dylib        	0x00007fffa0f8444e __workq_kernreturn + 10
    1   libsystem_pthread.dylib       	0x00007fffa106e621 _pthread_wqthread + 1426
    2   libsystem_pthread.dylib       	0x00007fffa106e07d start_wqthread + 13
    
    Thread 4:
    0   libsystem_kernel.dylib        	0x00007fffa0f8444e __workq_kernreturn + 10
    1   libsystem_pthread.dylib       	0x00007fffa106e48e _pthread_wqthread + 1023
    2   libsystem_pthread.dylib       	0x00007fffa106e07d start_wqthread + 13
    
    Thread 0 crashed with X86 Thread State (64-bit):
      rax: 0x00007f8420800aa0  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
      rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x00007fff58c7e610  rsp: 0x00007fff58c7e600
       r8: 0x0000000000000020   r9: 0x00007f8420496cd0  r10: 0x00000000ffff8000  r11: 0x0000000000000001
      r12: 0x00007f8422800000  r13: 0x00007fffa9dab070  r14: 0x0000000107ea2b2c  r15: 0x0000000000000000
      rip: 0x00007fff8b239ad8  rfl: 0x0000000000010246  cr2: 0x0000000000000000
      
    Logical CPU:     2
    Error Code:      0x00000004
    Trap Number:     14

</details>
<br>
It's odd that this started happening now; FF was quite stable during the month or so that I used it before the force-quit incident. Various rounds of uninstalling and reinstalling FF and XQuartz, including dropping back to FF 20161003, haven't helped.

**Comment by jtanx** [comment]
Stale issue, please retry with latest version and reopen if still happening.
