### ISSUE TITLE
FontForge-2017-07-31-Windows-r2 takes 2 minutes to open glyph view window for this glyph

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#3262]
To reproduce, click on a character in the overview view of the attached file, do <kbd>Ctrl</kbd>-<kbd>Alt</kbd>-<kbd>]</kbd> (to go to the only glyph in this `.sfd` file), then press <kbd>Enter</kbd>.  

On a medium-powered laptop, most glyphs open instantaneously.  This one takes 2 min when it is the only glyph in a file.  In fact, when this glyph is a part of 440M `.sfd` file (with close to 64K glyphs), it takes so long that I could not wait until it finished drawing in the window.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

[out-unifont-all-x3826-2min.sfd.txt](https://github.com/fontforge/fontforge/files/1796266/out-unifont-all-x3826-2min.sfd.txt)

**Comment by skef** [comment]
Just tried this on Arch Linux and the glyph opened fine. This will need Windows-specific attention to figure out.

**Comment by jtanx** [comment]
Seems fine on the latest version.
