### ISSUE TITLE
Adding new glyphs

### ISSUE THREAD

**Issue by 88880** [fontforge/fontforge#3279]
Hello. I am sorry if this is incredibly obvious but I want to add new glyphs to my font, mainly Latin letters with diacritics, such as an S with a cedilla, or a K with breve. How do I do add new slots for these specific glyphs? I add empty slots with "encoding>add encoding slots" but they are not defined for a letter.

Sorry again if this is obvious

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by 88880** [comment]
Also, how can I set the undefined glyphs to a default font? For example I don't have a custom _ampersand_ and want to set it to a default _Arial_ ampersand, such that when I use the font and use that glyph, it doesn't bring up empty space

**Comment by tuffnatty** [comment]
@88880 You do Encoding>Add encoding slots. New slots appear in the end of the table. You draw your glyphs, right-click the slots, Element Info, and assign a Unicode value.

**Comment by skef** [comment]
This appears sufficiently resolved.
