### ISSUE TITLE
how to build the GUI app on macOS?

### ISSUE THREAD

**Issue by tessus** [fontforge/fontforge#3281]
When I build fontforge on macOS, the GUI app is built as well.

But when I try to start it, I get the message that I should move it to the `/Applications` folder.
Ok, no problem. After I moved it to the `/Applications` folder, starting the app does not work either.
There's no error message in the console.

I'm in the process of updating the MacPorts fontforge Portfile, thus I try to get the GUI working as well.
(The previous Portfile that built fontforge from 2012 had a working GUI.)

This is my build env:
macOS 10.13.4 17E199
Xcode 9.3 9E145

ff version: https://github.com/fontforge/fontforge/releases/download/20170731/fontforge-dist-20170731.tar.xz

I'd appreciate any help on how to actually compile a working version of the GUI application.

**Comment by jtanx** [comment]
Yeah from what I recall, the process is pretty finicky. 

@frank-trampe knows the proper process for the actual releases.

I did have an attempt at making it as part of the ci, which is here: https://github.com/fontforge/fontforge/blob/master/travis-scripts/ffosxbuild.sh and the mac code paths here: https://github.com/fontforge/fontforge/blob/master/.travis.yml

But note I never had access to a physical mac, I did it all on a VM, which got annoying fast.

If you're working off git, you might also want to try using the gdk backend instead, as it gets rid of the x11 dependency (`--enable-gdk=gdk3`).

**Comment by mojca** [comment]
I figured out that, strange enough, if I call `fontforge some-font.otf`, it started working. Maybe it's just an issue with the initial splash screen?

There's definitely an unrelated bug with the following hardcoded library name:
```
File "/opt/local/share/fontforge/python/gdraw/_gdraw.py" line 4, in <module>
 _libraries['libgdraw.so.5'] = CDLL('libgdraw.so.5')
File "/opt/local/Library/Frameworks/Python.frameworks/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
 self._handle = _dlopen(self._name, mode)
OSError: dlopen(libgdraw.so.5, 6): image not found
```
It should be `libgdraw.5.dylib` in our case (and actually only works with full path for me).

This `gdk3` sounds like a super good news,  we definitely need to try it out.

**Comment by jtanx** [comment]
Ah yes, I do recall noticing something like that myself, from what I vaguely recall, there was some special behaviour on mac in the startup procedure, to do with interacting with the dock or something, I can't quite remember.

Not too sure on that gdraw interaction, but looking at (the probably outdated/broken) script: https://github.com/fontforge/fontforge/blob/master/osx/create-osx-app-bundle.sh#L244

It was worked around in the bundle by symlinking libgdraw.so.5 to the dylib name... There's quite a few hacks/workarounds/changes made when making the bundle.

**Comment by tessus** [comment]
@frank-trampe any insights in how to build the GUI app on macOS?

Do I need the X libraries? Because the osx app is also built when I use the option `--without-x`.
Do you run additional scripts to fix the libraries after the build process?

> If you're working off git, you might also want to try using the gdk backend instead, as it gets rid of the x11 dependency (--enable-gdk=gdk3).

@jtanx We usually only create ports for releases. However, there are ways to create -devel ports that compile from git. It's not really encouraged, but let's see. 

Are you sure, you didn't mean gtk3?

On the other hand, when is the next fontforge release planned? Maybe creating an interim release (as a rc for gtk) is not such a bad idea.

**Comment by tessus** [comment]
Another question: I'm a bit fuzzy about the dependencies. Why do I need `pygtk` when I build an X app (release 20170731). I either require X dependencies or GTK dependencies. I should not need both, especially when only one of these interfaces works.

**Comment by jtanx** [comment]
> Do I need the X libraries? Because the osx app is also built when I use the option

If you want the GUI, and you're building off the latest release, then yes you do. The osx app as built as part of `make` is far from complete, it's just a base to work off - that's what the scripts I pointed out earlier take and munge to get something that (semi?) works.

> Are you sure, you didn't mean gtk3?

No, I mean GDK, I wrote that backend. GDK is a component of GTK, so just install GTK and you'll get GDK as part of it.

> Why do I need pygtk when I build an X app 

Unrelated to anything previously mentioned, I believe there is some way of adding GTK GUI elements from python scripting, although I'm a bit less clear on how this works, as I've never used it. To be honest, I don't think you necessarily need this, I've built all the windows releases without it.

**Comment by tessus** [comment]
> No, I mean GDK, I wrote that backend. GDK is a component of GTK, so just install GTK and you'll get GDK as part of it.

alright - time for a new fontforge release :-)

**Comment by tessus** [comment]
just to make sure. first I create the osx app with make install and then I run the script `ffosxbuild.sh`, right?
well, I'll give it a try.

**Comment by jtanx** [comment]
It's been a long time since I looked at that, and since I never really had a proper environment to test it in, it may not work. Going off the travis script, the invocation appears to be


``` sh
./ffosxbuild.sh prefix hash

# e.g.

./ffoxbuild.sh ~/my-prefix `git rev-parse HEAD`
```

As part of the CI build, the result of that script is here: https://dl.bintray.com/fontforge/fontforge/ (note that current master is building X11 GUI builds)

So maybe it's worth checking what works and what doesn't out of that.

**Comment by tessus** [comment]
I've been trying to run your script, but it fails pretty soon. I have no idea how this actually runs when invoked with travis.

`outdir=$(realpath $outdir)` fails because the directory does not exist
the same is true for all the `cp` commands (e.g. `cp -r $workdir/bin $outdir/Contents/Resources/opt/local/`).
The target dirs do not exist and there are no `mkdir -p` commands in the script.
How can this run without errors in travis? This makes no sense.

Anyway, I'll try to fix the script so that it runs and see what happens.

**Comment by tessus** [comment]
ok, now I'm stuck:

`rm FontForge && cp $BASE/_FontForge FontForge`

There's no _FontForge directory. It was neither copied or created, so where is this coming from?

Another problem is that the copy commands don't do what you might think they do:

`cp -r $workdir/lib/python2.7 $outdir/Contents/Resources/opt/local/lib/python2.7` creates a `python2.7` directory in `$outdir/Contents/Resources/opt/local/lib/python2.7`.

Even the first copy command has a problem:

`cp -r $workdir/share/fontforge/osx/FontForge.app $outdir` creates the  `FontForge.app` directory in the output directory, but the following cp commands reference the level below.
The command should be
`cp -r $workdir/share/fontforge/osx/FontForge.app/* $outdir`

Anyway, I have no idea how to fix the `cp: /Users/kct/data/tmp/_FontForge: No such file or directory` error.

Can someone please shed some light on this?

**Comment by jtanx** [comment]
_FontForge is [here](https://github.com/fontforge/fontforge/blob/master/travis-scripts/_FontForge).

> cp -r $workdir/share/fontforge/osx/FontForge.app $outdir

That's correct, $outdir shouldn't exist at that point, it's determined as `outdir=FontForge-$builddate-${hash:0:7}.app`.

> cp -r $workdir/lib/python2.7 $outdir/Contents/Resources/opt/local/lib/python2.7 creates a python2.7 directory in $outdir/Contents/Resources/opt/local/lib/python2.7.

Sounds correct to me, what are you expecting?

**Comment by jtanx** [comment]
Ok I took a second look at the script, and it does presume a few things about how fontforge has been built. Mostly just that it's been compiled with python support.

I made the following mods to ffosxbuild.sh:

```sh
#Replace
mkdir $outdir/Contents/Resources/opt/local/lib
# with
mkdir -p $outdir/Contents/Resources/opt/local/lib
```

Assuming you've cloned fontforge, and are in the repo folder:

```sh
./bootstrap
./configure --enable-gdk=gdk3 --prefix=/Users/you/prefix --enable-python-extension --enable-python-scripting
make install -j4
travis-scripts/ffosxbuild.sh /Users/you/prefix some-random-string
```

That should make e..g `FontForge-2018-05-03-some-random-string.app` and `FontForge-2018-05-03-some-random-string.app.dmg`

You should be able to run `FontForge-2018-05-03-some-random-string.app/Contents/MacOS/FontForge` directly to bring up the gui.

**Comment by tessus** [comment]
No, I did not clone the repo. I use https://github.com/fontforge/fontforge/releases/download/20170731/fontforge-dist-20170731.tar.xz

> That's correct, $outdir shouldn't exist at that point, it's determined as outdir=FontForge-$builddate-${hash:0:7}.app.

Yes, I understand that, but the following line in the script
`cp -r $workdir/share/fontforge/osx/FontForge.app $outdir`
creates a FontForge.app directory in FontForge-$builddate-${hash:0:7}.app and I'm pretty sure that's not what you want.

> Sounds correct to me, what are you expecting?

It created a python2.7 directory in the python2.7 directory. The result was `$outdir/Contents/Resources/opt/local/lib/python2.7/python2.7/. . .`. I definitely did not expect that.

> Mostly just that it's been compiled with python support.

My version is compiled with python support.

**Comment by jtanx** [comment]
> creates a FontForge.app directory in FontForge-$builddate-${hash:0:7}.app and I'm pretty sure that's not what you want.

Hmm, not on my vm (sierra? I think) or on travis. What it does is it copies the `FontForge.app` folder, renaming it in the process to e.g. `FontForge-2016-10-17-3ba9b1a.app`

> It created a python2.7 directory in the python2.7 directory. The result was $outdir/Contents/Resources/opt/local/lib/python2.7/python2.7/. . .. I definitely did not expect that.

Yeah that shouldn't happen. Can you try removing outdir if it exists, and run the script again?

**Comment by jtanx** [comment]
Taking a step back, are you able to just build and run fontforge? 

When I run it from the terminal, it creates a dock icon, which you have to click on to bring up a window. I think the app bundle does something (probably in that _FontForge script) to make the window show up immediately.

**Comment by tessus** [comment]
> Yeah that shouldn't happen. Can you try removing outdir if it exists, and run the script again?

This does not work, because the script ends with the following error then:

`realpath: /Users/kct/data/tmp/FontForge-2018-05-04-some-random-string.app: No such file or directory`

If the directory does not exist, realpath throws an error.

> are you able to just build and run fontforge?

Nope, I get this output:

```
[~/data/tmp/fontforge-install/share/fontforge/osx/FontForge.app/Contents/MacOS]$ ./FontForge
PKGBASE: /Users/kct/data/tmp/fontforge-install/share/fontforge/osx/FontForge.app
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.30.2/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.30.2/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.30.2/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.30.2/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
```

And this popup:

<img width="414" alt="screen shot 2018-05-04 at 14 07 15" src="https://user-images.githubusercontent.com/223439/39644962-bd327f8a-4fa4-11e8-932a-3091c5856284.png">

Then, after moving it to `/Applications`, I get the following:

```
[/Applications/FontForge.app/Contents/MacOS]$ ./FontForge
PKGBASE: /Applications/FontForge.app
./FontForge: line 107: [1: command not found
Can't exec "/Applications/FontForge.app/Contents/MacOS/fc/fc-cache": No such file or directory at /System/Library/Perl/5.18/darwin-thread-multi-2level/IO/File.pm line 187.
Use of uninitialized value $fcproc in <HANDLE> at /Applications/FontForge.app/Contents/MacOS//fcprogress.pl line 38.
readline() on unopened filehandle at /Applications/FontForge.app/Contents/MacOS//fcprogress.pl line 38.
Done!

Can't call method "close" on an undefined value at /Applications/FontForge.app/Contents/MacOS//fcprogress.pl line 49.
./FontForge: line 138: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge: No such file or directory
./FontForge: line 138: exec: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge: cannot execute: No such file or directory
```

**Comment by mojca** [comment]
How did you end up with `/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge`? This looks like some wrong synthesis of two independent paths, the second one coming from MacPorts, while it should not end up in the app anyway.

In my opinion `fc-cache` should not end up in the app bundle built by MacPorts anyway (it might make sense for the standalone app, but not for the one in MP).

Maybe I should look into that script as well, but I imagine that most of the tricks which might be needed for a standalone app do not apply for MacPorts. It should only serve as some initial starting point to help debugging what might potentially be missing.

**Comment by tessus** [comment]
@mojca for my current tests I am not using macports at all. Before being able to do this with a Portfile, we have to get it working first.

Here are my steps:

```
PKG_CONFIG_PATH=/opt/local/lib/pkgconfig/ PYTHON=/opt/local/bin/python2.7 PYTHON_CFLAGS="-I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -pipe -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes" PYTHON_LIBS="-L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation" CFLAGS=-I/opt/local/include LD_FLAGS=-L/opt/local/lib ./configure --prefix=/Users/kct/tmp/fontforge-install --disable-dependency-trackingcd --x-includes=/opt/local/include --x-libraries=/opt/local/lib

make
make install
```

I've also been trying to run the script, but I ran into several issues (as you can see in my other comments above).
However, the script and/or the travis process seems to fix the binaries' rpaths and other issues with the package. (e.g. the images at https://dl.bintray.com/fontforge/fontforge/ work on my machine)

I'm still trying to get the script working...

**Comment by jtanx** [comment]
> This does not work, because the script ends with the following error then:

What realpath are you using? I'm using the one from gnu coreutils, which accepts determining the filepath even if that path doesn't exist yet.

> Nope, I get this output:

You're trying to run the app bundle, that's not what I mean.

I mean, if say you had:

```
./configure --prefix=/my/prefix
make install
```

Can you just run

```
export LD_LIBRARY_PATH=/my/prefix/lib
/my/prefix/bin/fontforge
```

> And this popup:

If the script ran correctly, then it would have replaced that version of the script with [_FontForge](https://github.com/fontforge/fontforge/blob/master/travis-scripts/_FontForge#L26), which disables that check.

**Comment by tessus** [comment]
> What realpath are you using? I'm using the one from gnu coreutils, which accepts determining the filepath even if that path doesn't exist yet.

There's no realpath on Mac. I installed it via MacPorts:

```
$ port info realpath
realpath @1.0.1 (sysutils)
```

Maybe it's an old version.

> Can you just run
> `/my/prefix/bin/fontforge`

```
[~/tmp/fontforge-install]$ ./bin/fontforge
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 21:52 UTC  2-May-2018-ML-D.
 Based on source from git with hash:
no xdefs_filename!
TESTING: getPixmapDir:/Users/kct/data/tmp/fontforge-install/share/fontforge/pixmaps
TESTING: getShareDir:/Users/kct/data/tmp/fontforge-install/share/fontforge
TESTING: GResourceProgramDir:/Users/kct/data/tmp/fontforge-install/bin
trying default theme:/Users/kct/data/tmp/fontforge-install/share/fontforge/pixmaps/resources
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
```

Yep, I get an X message though that the font couldn't be found:

<img width="287" alt="screen shot 2018-05-04 at 22 45 58" src="https://user-images.githubusercontent.com/223439/39659004-08cf993a-4fed-11e8-821a-87c1f00d8ffe.png">

> If the script ran correctly, then it would have replaced that version of the script with _FontForge, which disables that check.

Right, I'm still trying to get it to run correctly ;-)

**Comment by skef** [comment]
The build process has changed drastically since this was filed so even if there is still a problem it will be a different problem. Closing this.

**Comment by tessus** [comment]
@skef could you please reference the current build instructions then?

**Comment by skef** [comment]
First off, mac builds of FontForge are tricky enough that we always recommend using one of the packages we build. This doesn't answer the question, of course, but it's important to acknowledge the difficulty. 

*In theory* a Mac OS X version can be built in more or less the normal way with CMake and ninja, when those and the other dependencies are installed via Homebrew or other means. See the main INSTALL.md file: https://github.com/fontforge/fontforge/blob/master/INSTALL.md

That this is largely possible is also evident in our Travis build file, which is used to build a Mac OS X version when the master branch is updated. That is here: https://github.com/fontforge/fontforge/blob/master/.travis.yml . Looking through the `TRAVIS_OS_NAME` == "osx" portions give a pretty good idea of the dependencies, potential environment variable settings, and build process (the latter under 'script:`)

**Comment by skef** [comment]
The problem with a "general" set of Mac OS instructions is that different users prefer different frameworks and many of them just have problems or the FontForge folks have no experience with them. For our builds we've had to carefully pick and choose the environment to build in.

**Comment by tessus** [comment]
A while back I updated the MacPorts package for fontforge. But even when following the same steps as in the Travis CI pipeline, I was not able to get it to work. Of course I had to change a few scripts since they were exclusively for Travis, but still no luck. So I removed the GUI part from the port completely.
I hoped that I could add it back, so that the fontforge GUI app would be available via MacPorts. Anyway, if it takes 5 PhDs, 2 dev and build machines and a good measure of luck to get the GUI app compiled, then something is seriously wrong with the build process.

**Comment by skef** [comment]
The build process isn't one of my areas of expertise, unfortunately, but I know the Mac stuff is hampered by the low level of GDK support on that platform. (Even so, GDK seems to have wound up being an improvement over X11.) 

All I can say is that if "a while back" was before the CMake switch I suggest trying again, as @jtanx has really improved things in that switch. If it wasn't I don't have any further advice. FontForge has a Unix-y/X11-y lineage and is still easier to build on Linux etc than for other systems. Our current approach to that problem is to build an app image that works for most users.

**Comment by jtanx** [comment]
I'd suggest using homebrew, not macports. I finally got a somewhat working Catalina VM, so I'll try to get some steps listed.

**Comment by tessus** [comment]
> I'd suggest using homebrew

I think you didn't get my point. I don't use brew, neither do a lot of other people who prefer MacPorts over homebrew.

**Comment by jtanx** [comment]
There's unfortunately only so much time in the day, and I don't even have a proper macos environment to test this on.

Last I tried, it was pretty simple to get it compiling with homebrew. So if you choose to use macports, then complain that

> Anyway, if it takes 5 PhDs, 2 dev and build machines and a good measure of luck to get the GUI app compiled, then something is seriously wrong with the build process.

Then that's your prerogative.

In any case, as mentioned, the build system has changed a lot since when this ticket was raised, so maybe it's worth a shot to try again. All I'd suggest is don't try to compile it with the x11 backend, use the gdk one instead.

**Comment by jtanx** [comment]
For reference, from a fresh Catalina install, the [build steps](https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge#quickstart) just worked, after dealing with the homebrew cruft.

```
brew install gtk+3 cmake ninja ccache pkg-config gettext libspiro libtiff libuninameslist jpeg libpng giflib coreutils
brew link --force gettext

# see Homebrew/brew#5068
mv /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15/libxml-2.0.pc /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15/libxml-2.0-old.pc

# more or less standard build instructions
git clone https://github.com/fontforge/fontforge
cd fontforge
mkdir build
cd build
cmake  -GNinja .. -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache  -DCMAKE_INSTALL_PREFIX=~/prefixv
ninja install
~/prefixv/bin/fontforge
```

**Comment by mojca** [comment]
Just to clarify: do these build steps also work out of the box also for the August 2019 release or just for the master branch?

**Comment by ctrlcctrlv** [comment]
Why not try it and find out? Not much point compiling if you're going to be compiling a release. We're close to another one of those anyway.

**Comment by mojca** [comment]
@tessus: I tried compiling the master branch and it worked flawlessly out of the box, light-years better experience than trying to get it to compile years ago with the `./configure` script. I have `gtk3 +x11` installed at the moment, but I'm highly confident it would probably work with `gtk3 +quartz` (which is what one would probably want). There are still minor things that need fixing, like creating an `.app` out of the box, fixing the path of where python stuff gets installed etc., but those can be handled.

@ctrlcctrlv: I didn't understand what you tried to say with "not much point compiling if you're going to be compiling a release". I would prefer to compile the release, yes, but for the package manager we do need to be able to compile it rather than taking binaries. For individual users it certainly makes more sense to download a binary release rather than fight with compiler, but it's different from the perspective of wanting  to package something.

My only question was whether the major improvements have only been added recently (after the release) or already before the August release. But if there's another release on the horizon, it probably makes more sense to simply wait for that to happen and update the package then. Meanwhile we can polish the package and upload it once the release gets out.

**Comment by mojca** [comment]
To answer my own question: there's no `CMakeLists.txt` in the released version, so no point trying to wake the dead horse :)

**Comment by mojca** [comment]
The only thing that doesn't quite work out of the box is the `macbundle` target. That is: I would like to build fontforge "our own way", avoid third-party app bundling scripts, and only use the provided resources to package everything inside the app, with dependencies remaining inside the global prefix (for example, libpng should not be copied to the app). Such app would of course not be standalone.

But I need to admit that I'm not sure about the best implementation for this, as one would then need to keep the ability to build the app both ways. And I'm pretty sure that some other software has dependencies  on fontforge, so we would need to keep some parts in the prefix rather than move everything to  the `.app`.

**Comment by skef** [comment]
It's likely clear from this thread that we've picked our Mac battles, but if you wind up designing a target that does what you need and isn't too baroque I expect we would accept the PR. Various distros have had bits and pieces of support scripts and such in our repo over time.

**Comment by kencu** [comment]
BTW -- I fixed the GUI build for the previous version on MacPorts last year. The GUI builds,  installs, and works perfectly on every system from 10.4 PPC to the current ones.

But Mojca's new cmake port version works nicely too -- just tried it on SnowLeopard.

**Comment by kencu** [comment]
For sentimental reasons if no other, I thought you might like to see your beautiful app running on a tried-and-true DualG5 PowerPC Mac running Tiger. 

(Of course, it runs on every other system as well since then.)

![64404068-90081580-d02f-11e9-8865-905ac6fbfd54](https://user-images.githubusercontent.com/21211439/75517028-8fcf4e00-59b2-11ea-8a5c-5690333aba66.png)
