### ISSUE TITLE
The window refuses to show within my monitor.

### ISSUE THREAD

**Issue by RonynCato** [fontforge/fontforge#3283]
Windows 10

2017-7-31-Windows-r2

The window is rendering outside of my actual monitor and refuses to allow me to move it into view.
I can see it if I use Task View, but no amount of using the Win + Arrow keys moves it into sight.

**Comment by frank-trampe** [comment]
No idea on this one. @jtanx?

**Comment by JoesCat** [comment]
Hi @RonynCato,
Four suggestions that may help, let us know which one worked.
1. If you are using a laptop with an external monitor. Plug-in the monitor you used, and relocate the window onto the laptop area.
2. If you have multiple monitors, example, one Ysize pixel larger than the other, or you use one vertically, put the larger one on the left (L type configuration, not J type configuration).
3. If your windowing system has a zoom-in, zoom-out sort of feature when you open/close windows, you could probably see where the windows zoom-opens, or zoom-closes - suggesting where the window is opening-up out of visual space.
4. Right-click the desktop, and in properties, rearrange the screenspace.

**Comment by jtanx** [comment]
Hmm, only ever seen somehting like that on multi monitor configurations, although it usually just shows up in the centre, when considering the screenspace of all monitors as a single monitor.

* What is your monitor configuration? One monitor or multi monitor?
* Have you ever launched fontforge successfully in the past?

**Comment by RonynCato** [comment]
Two Landscape monitors side by side on the left and a TV on the right.
Never used the program before.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jtanx** [comment]
Yeah, that might be throwing it off. Having said that, Win+arrowing works for me. Is it possible to test with one monitor only?

**Comment by RonynCato** [comment]
It worked.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by skef** [comment]
I believe the current Windows build is supposed to work around this problem. @jtanx can reopen if that's wrong.

**Comment by jtanx** [comment]
Yeah this shouldn't be an issue for gdk builds.
