### ISSUE TITLE
Crash when deleting glyphs

### ISSUE THREAD

**Issue by Dobrotescu** [fontforge/fontforge#3287]
I don't have the proper environment to debug this issue, but it seems repetitive enough for someone that can do it to figure out what's wrong. 

I am using FontForge version "08:20 UTC 31-Jul-2017", on Windows XP(2003) (I'm a dinosaur waiting for asteroids, I know ...). The crash occurs when trying to do subsetting on **DejaVuSans.ttf** (part of the [dejavu-lgc-fonts-ttf-2.37.zip](http://sourceforge.net/projects/dejavu/files/dejavu/2.37/dejavu-lgc-fonts-ttf-2.37.zip), from DejaVu's [Downloads](https://dejavu-fonts.github.io/Download.html) page).

### Crash scenario:
**1.** Open **DejaVuSans.ttf** in FontForge;
**2.** Select the "Latin-1 Supplement" glyphs (U+00A0-U+00FF);
**3.** [Encoding]->[Detach & Remove Glyphs...];
**... CRASH!**

### Workaround:
**1.** Open **DejaVuSans.ttf** in FontForge;
**2.** Select the "Latin-1 Supplement" glyphs (U+00A0-U+00FF);
**3.** Deselect '**¨**' ("dieresis", U+00A8);
**4.** [Encoding]->[Detach & Remove Glyphs...];
**5.** Select '**¨**' ("dieresis", U+00A8);
**6.** [Encoding]->[Detach & Remove Glyphs...];
**... OK**

This problem doesn't occur when doing the same operations on **DejaVuSans-Bold.ttf** (part of the same package), or other fonts I tried, so it surely is something weird with the font itself. However, I imagine that if someone can figure out what the problem is, it could be handled as an error, or even fixed.

**Comment by skef** [comment]
I reproduced this on Linux with recent code. Investigating.
