### ISSUE TITLE
Bionic Beaver support on Launchpad.net?

### ISSUE THREAD

**Issue by onassar** [fontforge/fontforge#3289]
Installed 18.04 LTS and it doesn't seem launchpad.net has a dist for 18.04
Any timeline on when that will get uploaded?

![](https://i.imgur.com/DxkSGmr.png)

**Comment by JoesCat** [comment]
Hi @onassar,
That decision is up to the maintainers for Ubuntu.

This is probably the flowchart you're looking for....
First look at the releases here:
https://github.com/fontforge/fontforge/releases

Compare the latest release (not beta pre-releases) with what you see in Debian here:
https://packages.qa.debian.org/f/fontforge.html

...Debian will usually usually test it for a while (goes from unstable to testing with time),
...Ubuntu will usually pick-up unstable and run with that (look in lower right corner).

...now for your question - you'll need to follow-up on launchpad - maybe here:
https://launchpad.net/ubuntu/+source/fontforge
...reading your screenshot above, that may possibly be an Ubuntu mirror that is not synchronized with Ubuntu - so you may need to find another mirror to download from.

Hope that helps redirect you, and let us know what you find.

**Comment by onassar** [comment]
Hmmm, this stuff feels a bit beyond my grasp of using a CLI to do font conversions 🤣
I'm happy to file a request somewhere, though.

**Comment by n7s** [comment]
@frank-trampe  any chance you can get a fresher fontforge into the bionic section of the fontforge PPA ? Thanks!

**Comment by n7s** [comment]
see https://github.com/fontforge/fontforge/issues/2729

**Comment by n7s** [comment]
@frank-trampe ping...

**Comment by thedonquixotic** [comment]
Hey I'm trying to install font forge on my WSL installation of Ubuntu 18 and I can not as the PPA says that there isn't a release available. Has there been any movement on this issue?

**Comment by jeffdyke** [comment]
Just another ping to this ticket.  Similar to #2729 , it would be great to have a build for build for bionic

**Comment by jeffdyke** [comment]
for anyone that arrives here, it seems to be available by default: see `apt-cache policy fontforge`
no response needed for ping :)

**Comment by jcklpe** [comment]
@jeffdyke  Sorry I'm new to using Linux and open source in general. What do you mean it's available by default? Does that mean that it it comes preloaded in Ubuntu 18.04?

**Comment by jeffdyke** [comment]
@jcklpe - the output of that command shows that its now in universe, so there is no reason to install a separate ppa.  

```
$> apt-cache policy fontforge
fontforge:
  Installed: (none)
  Candidate: 1:20170731~dfsg-1
  Version table:
     1:20170731~dfsg-1 500
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

sorry for the delay
