### ISSUE TITLE
scripting.c: Open all files in binary mode commit breaks scripting

### ISSUE THREAD

**Issue by nicketson** [fontforge/fontforge#3296]
Commit [https://github.com/fontforge/fontforge/commit/12f7ca9240affc892bc3e136df01f20a11de1733#diff-e4727a838f83c24828480a0f74bdd867](https://github.com/fontforge/fontforge/commit/12f7ca9240affc892bc3e136df01f20a11de1733#diff-e4727a838f83c24828480a0f74bdd867) submitted by @jtanx breaks scripting. On this [line](https://github.com/fontforge/fontforge/commit/12f7ca9240affc892bc3e136df01f20a11de1733#diff-e4727a838f83c24828480a0f74bdd867R10018) the string literal `"r"` used in strcmp has erroneously been changed to `"rb"`. This breaks scripts doing things like this `Generate($1:r + ".ttf")`

**Comment by jtanx** [comment]
Thanks for reporting! Should be fixed with https://github.com/fontforge/fontforge/pull/3298

**Comment by nicketson** [comment]
No problem!
