### ISSUE TITLE
FontForge can try to load unknown font using FreeType

### ISSUE THREAD

**Issue by andreygursky** [fontforge/fontforge#3305]
FontForge 20170731

Custom font formats can be implemented as drivers/modules in FreeType. If FontForge is unable to open a font:
https://github.com/fontforge/fontforge/blob/9d425976e21e725113a359a53aa1a86b25829bb1/fontforge/splinefont.c#L1219-L1221
it should try to open it through FreeType.

**Comment by khaledhosny** [comment]
FontForge needs to parse the font to be able to edit it, not just render it, so I fail to see how FreeType can be of any help here.

**Comment by andreygursky** [comment]
Is parsing not a prerequisite for rendering?

**Comment by khaledhosny** [comment]
Yes, but 1) not every part of the font is needed to render the glyphs at FreeType level, so it usually parses just as much as it needs, while FontForge needs to parse everything 2) FreeType does not usually expose everything it parses, so there is no way for FontForge to access this information.

**Comment by andreygursky** [comment]
At least it was possible to get a good result with following (for the mentioned in PR "unknown" font --> sfd converter):
```c
face = FT_New_Face(fontfilename)
// face->num_glyphs
// face->ftDescription.nFirstChar;
// face->ftDescription.nLastChar;
for each character:
    ind = FT_Get_Char_Index(i)
    FT_Load_Glyph(face, ind)
    get face->glyph->metrics
    outline = &face->glyph->outline
    for each outline->n_contours:
        // moveto
        switch(tag)
            get spline set points (lineto, conicto, cubicto)
```

**Comment by JoesCat** [comment]
Checking the freetype library, I see the current freetype maintainer has also contributed to fontforge for many years, and I think if he had seen advantage in doing so, he would have suggested this earlier or even provided patches.

Thanks for the suggestion, but as @khaledhosny points-out, for fontforge to be effective, it really does need to work with the font files directly.

**Comment by lemzwerg** [comment]
Indeed.  FreeType is *not* a font parsing engine!  In particular, some formats like Type1 are handled in a way that are not suitable for any font editor.
