### ISSUE TITLE
The download link for GNU/Linux does not show up on the website

### ISSUE THREAD

**Issue by belluzj** [fontforge/fontforge#3308]
The email subscription form at https://fontforge.github.io/en-US/downloads/gnulinux/ gives a warning message that looks like this: 

![image](https://user-images.githubusercontent.com/3616772/41500216-ee9633e0-718d-11e8-8a77-f743f79c707e.png)

If I click on "Cancel", I can download FontForge (which, ignoring the fact that it's questionable to force people to disclose their email address, is the opposite of the form's purpose?)

If I click on "Continue", nothing happens, I don't see the download link, and according to errors messages in the developer tools, I probably don't subscribe to the newsletter either:

![image](https://user-images.githubusercontent.com/3616772/41500178-7d3c55ee-718d-11e8-8604-db32befd5355.png)

I'm using Firefox 60 on Ubuntu 17.10. In Chromium 66, the download link appears but I don't think that I'm subscribing to any newsletter either:

![image](https://user-images.githubusercontent.com/3616772/41500284-e271879e-718e-11e8-914c-be4d4fc57fe3.png)

Expected behaviour:
* I can download FontForge
* without being forced to disclose my email
* I can actually subscribe to the mailing list if I choose to do so

Thanks for your work on FontForge :)

### When reporting a bug/issue:
- [X] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [X] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by timur-tabi** [comment]
I can't download anything using Firefox.  I'm sure if it's an actual bug in Firefox, they will try to fix it.  My gut tells me that it's more likely to be a bug in the web site.
