### ISSUE TITLE
Raleway font adding in a letter 'i' after an 'f' when exporting from Crystal to PDf

### ISSUE THREAD

**Issue by dawnyanne** [fontforge/fontforge#3317]
Hi
I am having a problem with the raleway font ttf regular when exporting from Crystal reports to pdf. The Bold etc is fine and also capital letters - is there a way in font forge that I can stop this happening? 
![image](https://user-images.githubusercontent.com/20944683/42626833-35fba2f8-85c3-11e8-8b18-b77db4be9fdd.png)
![image](https://user-images.githubusercontent.com/20944683/42626851-3e3892f0-85c3-11e8-822c-835583268878.png)
any help would be much appreciated 
Dawn

**Comment by ctrlcctrlv** [comment]
I think @dawnyanne means that any "f" is getting an "i" after it, not that "fi" combos are merging.

**Comment by JoesCat** [comment]
There are multiple complaints on this topic, and appears to point to Crystal Reports.
As @fitojb  indicates, there is nothing here to fix, or could be fixed, with respect to FontForge.

This may be a suggested starting point for you to follow-up on your problem:
https://www.google.com/search?q=crystal+reports+adds+extra+character&ie=utf-8&oe=utf-8
