### ISSUE TITLE
Inconsistent documentation and no download links for 18.04

### ISSUE THREAD

**Issue by thedonquixotic** [fontforge/fontforge#3320]
There is no release on Launchpad for 18.04. 

So I looked at installing it from a previous version. On the website, besides launchpad it says to check the release page for rpm in order to install it from root. That links to the GitHub page for this project but there is not a single RPM visible. 

Either the website needs to change to support better documentation or the releases need to be made available. 

### Important
Mark with [x] to select. 

I'm using WSL on Windows.

**Comment by thedonquixotic** [comment]
I have tried building fontforge from source. I admit that I'm very new to all this, and I'm a designer not a developer to boot (though I'm taking classes to better my dev skills) but I can't find a release for Font Forge for 18.04. What's up with that?

**Comment by JoesCat** [comment]
Check to see if this link helps... https://repology.org/metapackage/fontforge/versions

**Comment by JoesCat** [comment]
If you are going to build from source, file .travis.yml holds an internal list of packages to load ahead of time before running tests:
```bash
packages: [autoconf, automake, autotools-dev, bzip2, gcc-7, libtool,
      libjpeg-dev, libtiff4-dev, libpng12-dev, libfreetype6-dev, libgif-dev,
libx11-dev, libxml2-dev, libpango1.0-dev, libcairo2-dev, python3.6-dev, lcov]
```
load these packages (above) before trying to build fontforge.
We're reducing the list (above), but it is a gradual process based on available bandwidth between all of us.

If you, or others, wish to contribute, there are plenty of places to look, not all tasks are code dependant, for example language translation of the po files, help files (within fontforge, as well as a design with fontforge howto book)....etc.
Another good place to contribute is anyone asking for help in the user mail lists, or even these issue trackers (which were really meant more for developer bugs and not general help requests).

**Comment by thedonquixotic** [comment]
@JoesCat Sorry I have just figured it out. The problem was not with fontforge but with the way that python script I was using was attemting to invoke it. I already had fontforge installed which is why my attempts at installing it kept messing up.
