### ISSUE TITLE
centos7 and python3.6.5 , install fontforge error

### ISSUE THREAD

**Issue by fa2002** [fontforge/fontforge#3321]
centos7 and python3.6.5 , install fontforge error:

make[2]: Leaving directory `/soft/fontforge-master/po'
Making all in pycontrib
make[2]: Entering directory `/soft/fontforge-master/pycontrib'
Making all in gdraw
make[3]: Entering directory `/soft/fontforge-master/pycontrib/gdraw'
make[3]: Leaving directory `/soft/fontforge-master/pycontrib/gdraw'
Making all in simple
make[3]: Entering directory `/soft/fontforge-master/pycontrib/simple'
make[3]: Leaving directory `/soft/fontforge-master/pycontrib/simple'
Making all in collab
make[3]: Entering directory `/soft/fontforge-master/pycontrib/collab'
make[3]: Leaving directory `/soft/fontforge-master/pycontrib/collab'
Making all in graphicore
make[3]: Entering directory `/soft/fontforge-master/pycontrib/graphicore'
make[3]: Leaving directory `/soft/fontforge-master/pycontrib/graphicore'
make[3]: Entering directory `/soft/fontforge-master/pycontrib'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/soft/fontforge-master/pycontrib'
make[2]: Leaving directory `/soft/fontforge-master/pycontrib'
Making all in share
make[2]: Entering directory `/soft/fontforge-master/share'
make[2]: Leaving directory `/soft/fontforge-master/share'
Making all in tests
make[2]: Entering directory `/soft/fontforge-master/tests'
make[2]: Leaving directory `/soft/fontforge-master/tests'
fatal: No names found, cannot describe anything.
make[2]: Entering directory `/soft/fontforge-master'
make[2]: Leaving directory `/soft/fontforge-master'
make[1]: Leaving directory `/soft/fontforge-master'

What is "fatal: No names found, cannot describe anything."?

**Comment by JoesCat** [comment]
This is a copy-n-paste from testing file .travis.yml
```sh
packages: [autoconf, automake, autotools-dev, bzip2, gcc-7, libtool,
      libjpeg-dev, libtiff4-dev, libpng12-dev, libfreetype6-dev, libgif-dev,
      libx11-dev, libxml2-dev, libpango1.0-dev, libcairo2-dev, python3.6-dev, lcov]
```
You are likely missing files needed to build
Can you check to see your installation, or add any possibly missing packages listed in this list above?
Pay extra attention to see if it's a dev type package, as you will need the extra *.h files during the build process.
The simpler build to try first is the no X command line version. If that builds ok, then more attention can be put next towards the additional packages required for a GUI build.

**Comment by fa2002** [comment]
think you

**Comment by fa2002** [comment]
thank you.
