### ISSUE TITLE
Mark-To-Base combinations not showing right in Metrics window

### ISSUE THREAD

**Issue by BenTalagan** [fontforge/fontforge#3324]
Version: Latest Mac released version (FontForge 2017-07-31)

Hi all, when building a font from scratch with just : 
- A Mark-to-Base lookup with one mark class inside
- 2 glyphs (one base, one mark)  

the positioning of the mark does not show correctly in the metrics window while it's ok in the anchor combination review widget (cf screenshot). Is this the intended behavior ? I think I remember it was working correctly before (but not sure), it seemed to me that the metrics window would handle this with no problem :

![ffbug](https://user-images.githubusercontent.com/427791/43781481-3f0a91ac-9a5d-11e8-9f5c-882d30dd57f9.jpg)

As well, moving the whole block (mark glyph+its mark anchor) affects the metrics window while it should not because the anchor stays at the same place relative to the glyph.

**Comment by BenTalagan** [comment]
Additional note : I'm not 100% sure but after consideration it seems a duplicate of : https://github.com/fontforge/fontforge/issues/3035

**Comment by ctrlcctrlv** [comment]
Is the `mark` table enabled for `latn{dflt}`?

**Comment by BenTalagan** [comment]
Yes, it is. For both `latn{dflt}` and `DFLT{dflt}`. If I generate an opentype ttf from this sfd, the installed font will work as expected in LibreOffice.

**Comment by ctrlcctrlv** [comment]
Can you upload the font? The version you're using is more than a year old, so I can confirm the bug in the current development tree if it's still happening.

**Comment by BenTalagan** [comment]
Sure! I have recreated a simple one with that same behavior (had trashed the other one I had made for the screenshot).

[MarkToBaseBugInMetrics.sfd.zip](https://github.com/fontforge/fontforge/files/2280033/MarkToBaseBugInMetrics.sfd.zip)
