### ISSUE TITLE
WOFF2 conversion prints "Compressed <start size> to <end size>."

### ISSUE THREAD

**Issue by Yay295** [fontforge/fontforge#3325]
Using the latest code (compiled from source e688b8c4dc634dcc128709f84b98f2407294f3fb) and Ubuntu 18.04 (also up-to-date), converting a font to WOFF2 through a Python script ends up printing the size before and after conversion. This isn't a particularly big problem, but it shouldn't really be there since none of the other conversions print this info. That said, I'd guess this was a libwoff issue, but I couldn't find any place that this is being printed in either theirs or your code, so hopefully someone else knows what it is.

**Comment by Yay295** [comment]
It looks like it is being printed from libwoff (https://github.com/google/woff2/blob/master/src/woff2_enc.cc#L291), but it can be disabled by not defining FONT_COMPRESSION_BIN. I'm not really sure how using dev libraries works, but is it possible to change this from fontforge's code, or would you have to recompile woff2 from source to change that?

**Comment by khaledhosny** [comment]
You need to define `FONT_COMPRESSION_BIN` when building libwoff2, it can’t be set from within FontForge code.

**Comment by Yay295** [comment]
*not define

That's what I expected. That said, I looked into it a bit more, and it is possible to redirect stdout/stderr to somewhere else temporarily.

https://github.com/fontforge/fontforge/blob/master/fontforge/woff.c#L662
```c
// redirect stdout/stderr to /dev/null or NUL
int stdout_id = fileno(stdout);
int stderr_id = fileno(stderr);
int stdout_orig = dup(stdout_id);
int stderr_orig = dup(stderr_id);
#ifdef __unix__
freopen("/dev/null", "w", stdout);
freopen("/dev/null", "w", stderr);
#else
freopen("NUL", "w", stdout);
freopen("NUL", "w", stderr);
#endif

// call libwoff function
ret = woff2_convert_ttf_to_woff2(raw_input, raw_input_length, comp_buffer, &comp_size);

// put stdout/stderr back
fclose(stdout);
fclose(stderr);
dup2(stdout_orig, stdout_id);
dup2(stderr_orig, stderr_id);
stdout = fdopen(stdout_id, "w");
stderr = fdopen(stderr_id, "w");
```
This probably won't work on Windows as is, but it is possible. I did test that this works n Ubuntu.

**Comment by jtanx** [comment]
We wouldn't include this in FontForge, it should be fixed in the woff2 library instead.
