### ISSUE TITLE
out-of-memory crash

### ISSUE THREAD

**Issue by Yay295** [fontforge/fontforge#3326]
Using the latest code (compiled from source e688b8c4dc634dcc128709f84b98f2407294f3fb) and Ubuntu 18.04 (also up-to-date), I came across a font file that fails to be converted, killing my script without warning or even any console output. The conversion failing is obviously the fault of libwoff, not FontForge, but perhaps you could detect this in your code and fail a bit more gracefully?

test script
```python
import fontforge
font = fontforge.open('simkai.ttf')
print('before convert')
font.generate('simkai.woff2')
print('after convert')
font.close()
```

[simkai.zip](https://github.com/fontforge/fontforge/files/2282026/simkai.zip)

**Comment by jtanx** [comment]
Thanks for the report, I'll take a look, probably on the weekend.

**Comment by jtanx** [comment]
As in, it was OOM killed?

**Comment by jtanx** [comment]
I ran this locally (although on Windows). It seems to run fine for me, max memory usage was round 700MB.

**Comment by Yay295** [comment]
I guess I should mention that I was running this on a server with only 1GB of RAM, and I hadn't remembered to set up a page file yet.

`dmesg` output
```
[163892.549131] Out of memory: Kill process 14547 (fontforge) score 731 or sacrifice child
[163892.551694] Killed process 14547 (fontforge) total-vm:887924kB, anon-rss:735160kB, file-rss:976kB, shmem-rss:0kB
[163892.618441] oom_reaper: reaped process 14547 (fontforge), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

I've also confirmed that this doesn't specifically have to do with WOFF2; I was able to get this result just by `fontforge.open`ing multiple files without closing them. Creating a much-too-small swap file also did not help, so this wasn't caused by the utter lack of a swap file.

**Comment by jtanx** [comment]
Yeah, if it's getting OOM killed, that's not really a problem of FontForge, you just need more resources. You'd run into the same issue running not just FontForge, but any program that consumes enough memory that it runs into the OOM killer.
