### ISSUE TITLE
FontForge-2017-07-31-Windows-r2: crash when trying to load the 3rd TTF within this TTC file

### ISSUE THREAD

**Issue by seemebreakthis** [fontforge/fontforge#3329]
There are 3 ttf's within this .ttc file (attached and zipped).  My intention is to load all the member ttf's, change some attributes in each of them, then generate a new .ttc with these 3 ttf's inside.

But whenever I try load the third ttf (order doesn't matter), the app crashes while loading.  

This behavior can be repeated in another Windows machine.

[mingliu.zip](https://github.com/fontforge/fontforge/files/2304520/mingliu.zip)

**Comment by jtanx** [comment]
Can you screenshot the crash? Seems to load fine here.
