### ISSUE TITLE
Save failed

### ISSUE THREAD

**Issue by all4fuun** [fontforge/fontforge#3332]
Using the latest version of fontforge (downloaded today sept 5 2018) on Windows 10 latest version. I cannot save a fontforge file or a generate and save a ttf file.
Does fontforge support windows 10?
I have created a simple font with 1 character that passes validation and still can't save. I am trying to save in a dir I created and I am trying run as administrator.

**Comment by all4fuun** [comment]
I am sure this is a windows issue as Birdfont cant seem to save a ttf file either
![fontforge](https://user-images.githubusercontent.com/43020902/45166636-5dbda100-b1ac-11e8-939d-3eb805b62985.JPG)

**Comment by JoesCat** [comment]
Hi @all4fuun,
Can you specify which directory you are trying to save to?
Are you overwriting an existing file? or is it a new file?
Reading that you have two independently different programs fail suggests you are trying to save into a directory that needs higher permission settings, or maybe you are trying to save over files that are locked by other program(s).
Start with saving to your user document folder. If it works there, but not the other location, then it is a permission thing. If it does not work there either, then create a directory "C:\TEMP", no spaces, see if that works...if yes, this might be a naming problem concerning spaces.

Please avoid running programs in administrator mode, it negates the security and safety features of the operating system and could cause you operating system problems.

**Comment by jtanx** [comment]
I assume you're using the build from fontforge.github.io. I have seen something like this before, where it fails to save because FontForge tries to write temp files to C:\, which was disallowed in newer versions of Windows - **but** the build from fontforge.github.io should work, because the tmpfile implementation was changed by gnulib to use  (iirc) %TEMP% instead.

anyway, can you attach the font you're trying to use?

**Comment by all4fuun** [comment]
Thanks for responding. I am using the build from fontforge.github.io. 
Its not the font. I put fontforge on another computer and it works just fine. 
The computer that fails has "my documents" pointing to drive D:. Drive C: is a SSD so I put all OS and programs there while all the data is sent to D:\users\me\my documents.

If  fontforge is hard coded to write to C: or %TEMP% which is probably pointing to C: I can see how it will fail.
I suppose I could set the TEMP dir to D:  but since its working on another computer I will just keep going that way.

**Comment by all4fuun** [comment]
BTW:This morning I tried to use fontforge on C:, but it cant even see the C: drive, only  the D: drive. Anyway to set preferences to use C:?

**Comment by JoesCat** [comment]
Can you create a new directory D:\users\me\documents  (no spaces)?
more info: https://social.technet.microsoft.com/Forums/windows/en-US/b4ae178e-65c4-49c3-a00a-4f6a2b2a281e/my-documents-vs-documents-folder?forum=w7itprogeneral

Is the problem happening with fontforge, or are you running a script that uses fontforge (might be the script needs to be space aware). ...helps seperate problem to fontforge or something else.

Also right click to see and compare the permission settings for:
C: vs D:
C:\users vs D:\users
C:\users\me vs D:\users\me
C:\users\me\Documents or "C:\users\me\my documents" vs D:\users\me\documents

**Comment by all4fuun** [comment]
I appreciate everyones comments, I was able  have finished what I need to do.

I am not running any script in fontforge.
I will give a some of these suggestions a try.

**Comment by Jimbo4oz** [comment]
This is how I got it to work on my MAC. 
- manually run the executable inside the FontForge application - /Applications/FontForge.app/Contents/MacOS/FontForge (can drag the alias to the applications folder)
- Open the file you saved (cannot use 'open with' as it will not load the file contents)

**Comment by AGHiggins** [comment]
Thanks @Jimbo4oz. 
This works for Mac: Launch FontForge, Click File > Open > select font to open > Make your edits etc. The generated fonts will save successfully.
This does not work: Right-click font > Open with... > FontForge > Make your edits. The generated fonts get the "Save Failed" error.
