### ISSUE TITLE
MacOS build from current source: problems and workarounds

### ISSUE THREAD

**Issue by animaux** [fontforge/fontforge#3335]
When trying ti install Fontforge on MacOS (10.12.6) using the intructions provided [here](https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md) under `## On Mac OS X with Homebrew` I run into the following issues:

    brew install -v --debug --with-giflib --with-libspiro fontforge --HEAD

This results in an error:

    Error: No head is defined for fontforge

Which can be resolved by editing the hombrew file, as described [here](https://github.com/dtinth/YosemiteAndElCapitanSystemFontPatcher/issues/18#issuecomment-323050614). However the old .rb file apparently has some deprecated stuff in it.

So there is still another error coming up:

    Calling 'depends_on ... => :run' is disabled! There is no replacement.

This can be solved by removing ` => :run` after `depends_on "libtool"` on line 24 of the `fontforge.rb` file.

Running the install now still ends up in an error:

    Error: undefined method `undent' for #<String:0x0000000101619ea8>

Apparently a known issue with `brew`, see [here](https://github.com/Homebrew/brew/issues/4494), the fix is to remove `.undent` from `fontforge.rb` in line 80.

I don’t know which actions to take to create a permanent fix, hopefully this issue is helpful in the meantime.

**Comment by jtanx** [comment]
Please submit all homebrew formula changes to https://github.com/homebrew/homebrew-core, we don't maintain it.

**Comment by animaux** [comment]
OK, thanks will close this and focus on releases.
