### ISSUE TITLE
Can't import .svg files without Fontforge completly freezing.

### ISSUE THREAD

**Issue by j0sh01578** [fontforge/fontforge#3340]
I experience a problem, where i can't import any .svg file to Fontforge, and it's driving me crazy. 

I've been trying different sizes, different .svg file formats...

Here is the log:

Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension XFree86-Bigfont
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension GLX
LoadPreferences: C:\Users\****\*****\*******\*****\FontForge-mingw-w64-i686-bbe2d0-x11-r2\/.XWinrc not found
LoadPreferences: Loading C:\Users\****\*****\*******\*****\FontForge-mingw-w64-i686-bbe2d0-x11-r2\bin\VcXsrv\system.XWinrc
(II) AIGLX: enabled GLX_SGI_make_current_read
(II) AIGLX: enabled GLX_MESA_copy_sub_buffer
(II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
(II) AIGLX: enabled GLX_SGIX_pbuffer
(II) AIGLX: enabled GLX_ARB_multisample and GLX_SGIS_multisample
(II) 68 pixel formats reported by wglGetPixelFormatAttribivARB
(II) AIGLX: Set GLX version to 1.4
(II) GLX: Initialized Win32 native WGL GL provider for screen 0
[dix] Could not init font path element fonts/misc/, removing from list!
[dix] Could not init font path element fonts/TTF/, removing from list!
[dix] Could not init font path element fonts/OTF, removing from list!
[dix] Could not init font path element fonts/Type1/, removing from list!
[dix] Could not init font path element fonts/100dpi/, removing from list!
[dix] Could not init font path element fonts/75dpi/, removing from list!
[dix] Could not init font path element fonts/cyrillic/, removing from list!
[dix] Could not init font path element fonts/Speedo/, removing from list!
[dix] Could not init font path element fonts/terminus-font/, removing from list!
winBlockHandler - pthread_mutex_unlock()

Thanks in advance.

**Comment by ctrlcctrlv** [comment]
That log is probably not helpful at all. We're going to need a traceback from `gdb`. Fedora-specific instructions can be found [here](http://designwithfontforge.com/en-US/When_Things_Go_Wrong_With_Fontforge_Itself.html); you're going to have to adapt them to your OS. Doing this on Windows is going to be twice as hard as Mac or Linux.

**Comment by j0sh01578** [comment]
> That log is probably not helpful at all. We're going to need a traceback from `gdb`. Fedora-specific instructions can be found [here](http://designwithfontforge.com/en-US/When_Things_Go_Wrong_With_Fontforge_Itself.html); you're going to have to adapt them to your OS. Doing this on Windows is going to be twice as hard as Mac or Linux.

I did that, and it was easier then I thought. I ran the debugging and the gdb, Problem is, the game is just freezing when I export a file and the backtrace isnt even showing anything, like everything is fine.

![image](https://user-images.githubusercontent.com/43368738/45700259-4dbe9d80-bb6c-11e8-889c-6aa4898d221f.png)

Guess I have to wait for an update or look for something else :,(

**Comment by ilyaza** [comment]
(Of course it is easier on Windows: there is no dependencies hell…)

Anyway, about your “backtrace isnt even showing anything”: why not provide what it it actually **shows**?  You did not even give the `bt` command!

Stop the process, and issue `bt`.

**Comment by skef** [comment]
We've changed some of the SVG and stroking code and this issue was never updated with more information. There's really nothing here to go on. Closing -- will reopen if more info is added.
