### ISSUE TITLE
FontForge 2018-09-17-5d09182 won't launch on MacOS 10.13.6 – but Inkscape does

### ISSUE THREAD

**Issue by SundialServices** [fontforge/fontforge#3341]
FontForge halts immediately – it doesn't even appear in the taskbar (the taskbar "quivers" slightly).  

XQuartz 2.7.11 is installed and Inkscape _does_ start.

I see no crash logs or other signs of trouble using the _Console_ application.

I have already created a security-exception for this application.  (Which, in _High_ Sierra, is done strictly on a per-application basis with "Control+Click" then "Open.")

**Comment by SundialServices** [comment]
A similar thing just happened with 2018-09-16-4a42a64, and I noticed something else:  _at first,_ the FF icon appeared and bounced; then it vanished without launching the application.  And _now_ we have a crash-report in the log!  The crash-report is attached but the relevant portion seems to be this:

```
Dyld Error Message:
  Library not loaded: @loader_path/libwoff2common.1.0.2.dylib
  Referenced from: /Users/mike/Desktop/FontForge-2018-09-16-4a42a64.app/Contents/Resources/opt/local/lib/libwoff2enc.1.0.2.dylib
  Reason: image not found
```
[fontforge_2018-09-20-121717_Perseus.crash.txt](https://github.com/fontforge/fontforge/files/2402153/fontforge_2018-09-20-121717_Perseus.crash.txt)

**Comment by SundialServices** [comment]
2018-02-02 _did_ open apparently because it does not attempt to contain any `libwoff2` components.

Fortunately, this should be an exceptionally easy fix for someone.

**Comment by darkbrow** [comment]
install woff2 using homebrew.
