### ISSUE TITLE
SIGSEGV on trying to Merge CID Font (Noto Sans Japanese) into other font

### ISSUE THREAD

**Issue by rawler** [fontforge/fontforge#3347]
When merging Noto Sans Japanese into other font (Noto Sans Latin for example), I get a crash in fvfonts.c:1049 (in FVMergeRefigureMapSel). The issue seems to be that for a lot of characters, `o_sf->glyphs[i]` is NULL. 

I'm not really capable of fixing the error. Instead a working workaround seems to be to flatten the font before merging. Confirmed on current git master (9e9278c66ecc47290accb4e9e4aff82e8578ce1e) at the time, on both Linux and OSX. Also confirmed on version "19:05 UTC 30-Jul-2017" on OSX.

Reproduce, in i.e. Python:

    font = fontforge.open('NotoSans-Bold.ttf')
    font.mergeFonts('Noto-Sans-Japanese-Bold.ttf')

[fonts.zip](https://github.com/fontforge/fontforge/files/2477654/fonts.zip)

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
`fvfont.c:_MergeFont()` starts like this:

    static void _MergeFont(SplineFont *into,SplineFont *other,struct sfmergecontext *mc) {
        int i, cnt, doit, emptypos, index, k;
        SplineFont *o_sf, *bitmap_into;
        BDFFont *bdf;
        FontViewBase *fvs;
        int *mapping;
    
        emptypos = into->glyphcnt;
        mapping = malloc(other->glyphcnt*sizeof(int));
        memset(mapping,-1,other->glyphcnt*sizeof(int));
    
        bitmap_into = into->cidmaster!=NULL? into->cidmaster : into;
    
        for ( doit=0; doit<2; ++doit ) {
        cnt = 0;
        k = 0;
        do {
            o_sf = ( other->subfonts==NULL ) ? other : other->subfonts[k];
            for ( i=0; i<o_sf->glyphcnt; ++i ) if ( o_sf->glyphs[i]!=NULL ) {
                if ( doit && (index = mapping[i])!=-1 ) {
                    /* Bug here. Suppose someone has a reference to our empty */
                    /*  char */
                    SplineCharFree(into->glyphs[index]);
                    into->glyphs[index] = SplineCharCopy(o_sf->glyphs[i],into,mc);
                    into->glyphs[index]->orig_pos = index;
                    if ( into->bitmaps!=NULL && other->bitmaps!=NULL )
                        BitmapsCopy(bitmap_into,other,index,i);
                } else if ( !doit ) {
                    if ( !SCWorthOutputting(o_sf->glyphs[i] ))
                        /* Don't bother to copy it */;
                    else if ( !SFHasChar(into,o_sf->glyphs[i]->unicodeenc,o_sf->glyphs[i]->name)) {
                        /* Possible for a font to contain a glyph not worth outputting */
                        if ( (index = _SFFindExistingSlot(into,o_sf->glyphs[i]->unicodeenc,o_sf->glyphs[i]->name))==-1 )
                            index = emptypos+cnt++;
                        mapping[i] = index;
                    }
                }
            }
            if ( !doit ) {
                if ( emptypos+cnt >= into->glyphcnt && emptypos+cnt>0 ) {
                    into->glyphs = realloc(into->glyphs,(emptypos+cnt)*sizeof(SplineChar *));
                    memset(into->glyphs+emptypos,0,cnt*sizeof(SplineChar *));
                    for ( bdf = bitmap_into->bitmaps; bdf!=NULL; bdf=bdf->next )
                        if ( emptypos+cnt > bdf->glyphcnt ) {
                            bdf->glyphs = realloc(bdf->glyphs,(emptypos+cnt)*sizeof(BDFChar *));
                            memset(bdf->glyphs+emptypos,0,cnt*sizeof(BDFChar *));
                            bdf->glyphmax = bdf->glyphcnt = emptypos+cnt;
                        }
                    for ( fvs = into->fv; fvs!=NULL; fvs=fvs->nextsame )
                        FVBiggerGlyphCache(fvs,emptypos+cnt);
                    for ( fvs = into->fv; fvs!=NULL; fvs=fvs->nextsame )
                        if ( fvs->sf == into )
                            FVMergeRefigureMapSel(fvs,into,o_sf,mapping,emptypos,cnt);
                    into->glyphcnt = into->glyphmax = emptypos+cnt;
                }
            }
            ++k;
        } while ( k<other->subfontcnt );
        }

From that `memset` we should already be a little uncomfortable because although the argument is passed as an int `memset` is uchar-based, so that's not really going to work. However, that's not the problem in this case. 

The problem is that `other` is loaded from `Noto-Sans-Japanese-Bold.ttf` which has subfonts, and this code doesn't really work with subfonts. For one thing `mapping` is initialized using `other->glyphcnt` which for this font is zero. But more generally (on my reading) the subfont `k`-based loop treats `mapping` as a cross-subfont data structure in some cases (as below this quoted area where the function copies kerning info) and as a per-subfont data structure in others (as in the call to `FVMergeRefigureMapSel`, where the SIGSEGV of this bug appears. There is therefore a bunch of cleanup needed to get this subfont loop working, if that is desirable. 

On the other hand

1. @rawler reports that flattening the font first produces an acceptable result, and
2. Given that `NonoSans-Bold.ttf` is not a CID font here is similar advice in the code two levels up (in between is `__MergeFont()`, and to the side is `CIDMergeFont()`

```
    void MergeFont(FontViewBase *fv,SplineFont *other, int preserveCrossFontKerning) {
    
        if ( fv->sf==other ) {
        ff_post_error(_("Merging Problem"),_("Merging a font with itself achieves nothing"));
    return;
        }
        if ( fv->sf->cidmaster!=NULL && other->subfonts!=NULL &&
            (strcmp(fv->sf->cidmaster->cidregistry,other->cidregistry)!=0 ||
             strcmp(fv->sf->cidmaster->ordering,other->ordering)!=0 ||
             fv->sf->cidmaster->supplement<other->supplement ||
             fv->sf->cidmaster->subfontcnt<other->subfontcnt )) {
        ff_post_error(_("Merging Problem"),_("When merging two CID keyed fonts, they must have the same Registry and Ordering, and the font being merged into (the mergee) must have a supplement which is at least as recent as the other's. Furthermore the mergee must have at least as many subfonts as the merger."));
    return;
        }
        /* Ok. when merging CID fonts... */
        /*  If fv is normal and other is CID then just flatten other and merge everything into fv */
        /*  If fv is CID and other is normal then merge other into the currently active font */
        /*  If both are CID then merge each subfont separately */
        if ( fv->sf->cidmaster!=NULL && other->subfonts!=NULL )
        CIDMergeFont(fv->sf->cidmaster,other,preserveCrossFontKerning);
        else
        __MergeFont(fv->sf,other,preserveCrossFontKerning);
    }
```

So that, combined with getting rid of the subfont loop in `_MergeFont()`, might be the best solution.

**Comment by jtanx** [comment]
> From that memset we should already be a little uncomfortable because although the argument is passed as an int memset is uchar-based

Nah, it should work fine, memsetting to `-1` or `0` is fairly common practice.
