### ISSUE TITLE
Any timeline for upcoming stable release please?

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#3361]
Hi,

Its like 15 months now since last stable release. I would like to request upstream developers if they can think on releasing next stable release soon.
If releasing stable release takes some efforts then how about frequent say quarterly snapshot releases?
I can work on picking any upstream commit and use it in Fedora to build but I will prefer upstream released tarballs only for now.

**Comment by frank-trampe** [comment]
Hi, @pnemade. We're currently in the middle of some substantial changes to the UFO import/export functionality in cooperation with SIL. It has taken a lot longer than expected to find and to implement totally non-breaking fixes to all of the issues in question. There will be a release before the end of the month.

**Comment by animaux** [comment]
Great! After hopelessly trying to compile from source on OS X I am very much loking forward to this release `:D`

**Comment by brigazvi** [comment]
@frank-trampe 
wow! I was so waiting for it.

**Comment by wchristian** [comment]
Trying to modify a font over the weekend was an experience full of glitches, crashes, fontforge corrupting the saved font, and nothing to show for it. Would waiting for the update help with that?

**Comment by frank-trampe** [comment]
@wchristian, please file a GitHub issue for each discrete issue with the input file and the specific steps taken to reach the problem.

**Comment by animaux** [comment]
(Christmas is near …)

**Comment by pnemade** [comment]
Any updates here? Its now almost 15 months since the last stable release.

**Comment by animaux** [comment]
@frank-trampe any update on this? A new release would really lighten things up `;)`

**Comment by ctrlcctrlv** [comment]
Why can't you just tag a certain Git commit as a release for your purposes? E.g. you could consider https://github.com/fontforge/fontforge/commit/cec4a984abb41419bf92fc58e5de0170404f0303 as FontForge v 2019.1 if you wanted. As you wrote, you already know you can do this&mdash;I suggest you do it.

**Comment by animaux** [comment]
I have tried multiple times to do a macOS build, never successful. I’m hoping a release will include a binary again.

**Comment by ctrlcctrlv** [comment]
Seems like you should start an issue about your problems building rather than try to get someone else to make a build. It's an open source project, so maybe you could start providing Mac OS binaries, as others have  done for e.g. FFmpeg on Windows. Feel free to contribute :smile:

**Comment by animaux** [comment]
I’m by no means a programmer. I have given some feedback on the problems I have encountered in the build process in another issue, but to no avail. I’m happy to contribute when I can.

**Comment by ctrlcctrlv** [comment]
Sure, I feel your pain also about the irregular release schedule, in my place I build from git on Arch Linux, but I understand for most end users it's difficult to do that. Hopefully someone who can provide binaries will do so. :+1: 

The reason I suggested you contribute is that I know that most of the developers active in the last 12 months don't use a Mac and/or don't have access to one. Mac builds are not at all simple, there are many issues surrounding them that require specialized expertise, see e.g. #3463&mdash;even some kind of signing is required for most non-technical users to run Fontforge on Mac since they won't generally want to disable signing or know how to.

**Comment by ctrlcctrlv** [comment]
What I suggest is that the Mac users of Fontforge, such as you and @MaddTheSane , team up to tag commits, build Mac bundles against those commits, then make those publicly available somewhere. I'm sure such an effort would warrant a place within `README.md` at least now that fontforge.org is unfortunately down.

**Comment by animaux** [comment]
Thanks! I was made aware that there are actually current mac binaries, but advertised nowhere for unknown reasons. I am just starting to see there are some recent issues regarding FF on Mac, so I will try to see if I can get more info before further spamming this thread.

**Comment by animaux** [comment]
`\o/` https://github.com/fontforge/fontforge/releases/tag/20190317

**Comment by skef** [comment]
Oh yeah, I guess this can close now.

"Advertising" installation archives from incremental builds can result in too many people using them. For most users, in most cases, stability outweighs having the latest.
