### ISSUE TITLE
Modified Glyph Character not recognized in InDesign Insert Special Character feature!

### ISSUE THREAD

**Issue by lenafranck** [fontforge/fontforge#3363]
I'm new to font forge and have limited experience with coding, though I'm not sure if that applies here.
Background: my company wants to use a font but it was missing a few key glyphs. Since it had an OFL I figured I could modify the font by creating the glyphs and putting them into their corresponding slots in FontForge. Works great. The bullet point works like a charm in InDesign and all the other glyphs are showing up in the glyphs panel. 

The Problem: 
I need the InDesign feature type>insert special character>symbol> (copyright symbol in this case) to actually enter in a copyright symbol in the text box. Instead it enters a no glyph symbol. When I hover over the added Copyright glyph in the glyphs panel of InDesign it says "GID: 103; Name: NULL." I'm confused because the Unicode and the Name show up in FontForge under Glyph info (picture attached) but somehow the code doesn't translate to InDesign.   

I'm working with the latest FontForge and InDesign versions. Please, any help would be amazing!

![copyright glyph info](https://user-images.githubusercontent.com/14284887/48650205-e2057f00-e9ba-11e8-8214-d4d6e7d268ac.png)

**Comment by skef** [comment]
Closing this. Will reopen if there is more feedback from the submitter.
