### ISSUE TITLE
Fontforge SetFontNames() Don't Supported Chinese

### ISSUE THREAD

**Issue by fengqu** [fontforge/fontforge#3367]
Hello!
Fontforge SetFontNames() function Don't Supported Chinese

**Comment by JoesCat** [comment]
I think it is a limitation of postscript. Further info on postscript:
https://stackoverflow.com/questions/3795624/how-to-generate-chinese-characters-using-postscript

**Comment by fengqu** [comment]
> I think it is a limitation of postscript. Further info on postscript:
> https://stackoverflow.com/questions/3795624/how-to-generate-chinese-characters-using-postscript

Thank you very much！
