### ISSUE TITLE
FontForge-2018-11-22-d90c985.app.dmg - won't open MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by dube68** [fontforge/fontforge#3373]
FontForge-2018-11-22-d90c985.app.dmg - won't open MacOS High Sierra 10.13.6

Hello,
When I click on the App Icon from Applications, it doesn't seem to do anything at all.

I searched the issues here and found one suggested workaround; launching the App from the Terminal but when I did that, I got a pop-up that stated:

```
Last login: Tue Nov 27 08:17:20 on ttys000
users-iMac:~ user$ /Applications/FontForge-2018-11-22-d90c985.app/Contents/MacOS/FontForge ; exit;
PKGBASE: /Applications/FontForge-2018-11-22-d90c985.app
logout
Saving session...
...copying shared history...dyld: Library not loaded: @loader_path/libbrotlicommon.1.dylib
  Referenced from: /Applications/FontForge-2018-11-22-d90c985.app/Contents/Resources/opt/local/lib/libbrotlienc.1.dylib
  Reason: image not found

...saving history...truncating history files...
...completed.
Deleting expired sessions...5 completed.

[Process completed]
```

I hope that makes sense to someone.

Thanks in advance

**Comment by jtanx** [comment]
Looks like it's missing a dylib from the package since we enabled woff2 support in the builds. I'll try to look into it over the weekend

**Comment by dube68** [comment]
Greatly appreciated jtanx, I look forward to that

Thanks again
