### ISSUE TITLE
FontForge freezes in generating 'aalt'

### ISSUE THREAD

**Issue by samiel60** [fontforge/fontforge#3382]
FontForge 11.21 (September 24th 2017)
Debian Testing / LinuxMint 19.0

FontForge would create 'aalt' "automagically"; so in its documentation.
Case 1:
1. I create a New lookup (Elements -- Information -- Lookup) in GSUB.
2. I choose Type: Single Substitution, and after:
3. Feature -- New : aalt.
4.1 With the right button of the mouse in the drop down menu now I choose:
Add 'aalt' feature. And FF freezes.
Case 2:
1., 2., 3., 
4.2 but this time I create the relative subtable with Add subtable.
With the new subtable I try 4,1. And FF freezes. Is this one a FF problem, or is there anything wrong in my method? Thank you

**Comment by ctrlcctrlv** [comment]
Upload the SFD file so we can attempt reproduction of the bug.

**Comment by samiel60** [comment]
I find the same problem with all files I tried. In any case:
https://www.dropbox.com/s/90j1gy74sll1m1o/SamielPro.sfd?dl=0

**Comment by samiel60** [comment]
Is it enough to report the matter here, or is there another specific place for what looks like bugs?

**Comment by ctrlcctrlv** [comment]
This is enough. My having attached a debug backtrace should help it get solved, though you should know FontForge is free, has few developers, and has many bugs, of which yours is unfortunately a low priority. I would recommend you in the meantime import `.fea` files instead of using the automatic `aalt` generation.

**Comment by samiel60** [comment]
ok thank you for your contribution.
Only a question: for my font is an experiental one, I created aalt hand by hand.
So, where I can found .fea files?

**Comment by ctrlcctrlv** [comment]
This might help.

https://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#8.a

Feature (`.fea`) files are standardized across tools that work with fonts. It's easier in my experience to use them rather than use the GUI to add some OpenType features.
