### ISSUE TITLE
Kerning displayed properly in FontForge(metric view and the print window) but it's a bit off in the generated font

### ISSUE THREAD

**Issue by PaddiM8** [fontforge/fontforge#3384]
### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

In FontForge Metric View (expected):
![rsz_screenshot_from_2018-12-20_18-44-15](https://user-images.githubusercontent.com/19822996/50301550-f213f100-0487-11e9-9783-f1edec1e025f.png)

In the editors I've tried it in(Windows notepad, leafpad, HTML/CSS in firefox, etc.):
![rsz_screenshot_from_2018-12-20_18-45-05](https://user-images.githubusercontent.com/19822996/50301554-f3ddb480-0487-11e9-8c4a-ad7c859c620d.png)

I have tried on Arch Linux and Windows 10, same result. 
Well, when I opened the font on Arch, I got a dialog saying "This font contains both a 'kern' table and a 'GPOS' table. The 'kern' table will only be read if there is no 'kern' feature in 'GPOS'.

FontForge version: https://github.com/fontforge/fontforge/releases/tag/20170731

**Comment by ctrlcctrlv** [comment]
What type of kerning are you exporting? While exporting the OTF, there are many kern options. What happens if you check "Windows-compatible kern"?

**Comment by ctrlcctrlv** [comment]
Also, we're going to need your SFD file to help you fully.
