### ISSUE TITLE
Missing right line with one letters

### ISSUE THREAD

**Issue by Dinoteka** [fontforge/fontforge#3385]
**internal error couldn't finde line

I lost the line. Missing right line with one letters. How to fix it?**

[https://www.photobox.co.uk/my/photo/full?photo_id=501506692823](url)

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.
`https://www.photobox.co.uk/my/photo/full?photo_id=501506692823`

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by Dinoteka** [comment]
https://www.photobox.co.uk/my/photo/full?photo_id=501506692823

internal error couldn't finde line

I lost the line. Missing right line with one letters. How to fix it?

**Comment by ctrlcctrlv** [comment]
None of your links work. They just redirect to the homepage.
