### ISSUE TITLE
Question: How To [Element > Build] Custom Glyph

### ISSUE THREAD

**Issue by ElsaTheHobo** [fontforge/fontforge#3386]
I'm creating a font for my conlang, which uses mostly Latin codepoints. Almost half of all the consonants are built using a diacritic + its equivalent unvoiced letter (eg d looks like t̗ , z = s̗). It would be very convenient if I could just do Element > Build > Accented Glyph to automatically build these, however, the option is grayed (I think because the unicode point is along the lines of 'b' and not like, 'a with acute'? but idk).

I tried using references as a workaround, but the "voiced" diacritic ref is not automatically placed at the anchor it should be, and tbh I really don't want to manually fix the diacritic's location for the 12 consonants that use it, especially since I can't see the anchor points in the ref.

Anyone know a fix for either build > accented glyph or my workaround? It would be very much appreciated. Thank you!

(Bonus question: how do I re-sort my encoding, moving the glyphs?)

**Comment by ctrlcctrlv** [comment]
You are correct that the Build -> Accented Glyph mechanism is based off Unicode data.

I don't think there's any way to do what you want unless you change the data the automatic mechanism is based on and rebuild FontForge. (As far as I know it's built by scripts which use the Unicode composition/normalization form data)

I'm not sure what you mean by the bonus question, either.

**Comment by ElsaTheHobo** [comment]
Damn, that sucks about the Build mechanism. Luckily fixing the 12 consonant's refs is not hard (I'm just lazy lol)

Bonus q clarification: I mean like, I have my glyphs sorted and encoded like M T A B C D. I'm pretty sure that if I wanted to sort them in a more sensible way like Unicode order A B C D, I'd have to copy-paste the symbols around and then manually fix the encoding. I tried using the reencode feature but I'm not entirely sure how that works? It didn't seem to do what I wanted.

**Comment by ctrlcctrlv** [comment]
The re-encode feature is definitely not for your case. It's for when you open a font in a legacy encoding, let's say from the 90's or early 00's, and you want to re-encode it to something more modern such as UnicodeBmp. (Of course it can also do the converse, but I don't recommend it. :smile: ) It is once again based on Unicode data.

You don't need to copy and paste the symbols around. You can go to Element -> Glyph Info and change the Unicode char the glyph stands for. The order of glyphs in a font really doesn't matter, they can be in any order, all that matters is the character representation of each glyph. If you want, after you change all the glyph info, you can use the re-encode feature to put the glyphs in Unicode order. (See also Encoding -> Compact)

**Comment by skef** [comment]
@ctrlcctrlv does #3645 address this?

**Comment by ctrlcctrlv** [comment]
@skef Actually, yes! I didn't think about the implications for conlangers since I'm not one, but my recent work does fix this.

**Comment by ElsaTheHobo** [comment]
:D

**Comment by skef** [comment]
> I didn't think about the implications for conlangers

You did, actually; you just had them filed under "[wacky](https://github.com/fontforge/fontforge/pull/3645#issuecomment-482417732)"

**Comment by ctrlcctrlv** [comment]
Closed as resolved by #3645.
