### ISSUE TITLE
GSUB lookup don't work when I generate my font!

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3390]
I need single substitution in order to designing an cursive English script, every thing work when I test my font in the Metric windows, but when I generate my font, single substitution feature don't work in word processing or in web browser using CSS font-face.

In order to make this problem clear I designed a font that I attached to this issue. It has only four glyph and base on the init and the fina feature that I specified in GSUB it must substitute initial zero(0) and final one(1) glyph with a glyph that is consist of reference of same glyph addition to a line under that glyph. Unfortunately mentioned feature don't work in the generated font.
[Problem_Example.zip](https://github.com/fontforge/fontforge/files/2710953/Problem_Example.zip)
 

My environment is as follow:

- Fontforge Version: 11:21 UTC 24-Se-2017

- OS: Ubuntu 18.10, I also I had same problem in Ubuntu 16.04

- Word Processing Application: LibreOffice Writer

**Comment by frank-trampe** [comment]
@AlirezaAlipour, this isn't quite specific enough to be handled as an issue. We would need to know specific deficiencies in the generated TrueType file. Please post to [the FontForge user list](https://sourceforge.net/projects/fontforge/lists/fontforge-users) with your input (SFD) file and output (TTF) file and ask for help finding the specific reason that Word isn't rendering the way you expect.

**Comment by AlirezaAlipour** [comment]
Thank @frank-trampe very much for your assist :)

I wish you a happy new year :)

**Comment by AlirezaAlipour** [comment]
I'm waiting for a solution :)

**Comment by dscorbett** [comment]
This isn’t a problem with FontForge. 'init' and 'fina' are for scripts like Arabic: they don’t work for Latin. You’ll need to use a contextual substitution to determine whether a glyph is in initial or final position.

**Comment by AlirezaAlipour** [comment]
Thank David very much :)

Unfortunately I forgot to update and close this issue, I researched on the web and asking from a kind man by email then I figured out that I can use contextual substitution or contextual chaining substitution_ now I'm using contextual chaining substitution for my propose_ and as you described, 'init' and 'fina' features are don't applicable for Latin and these features are used for Arabic.


I'm thankful to every one that help me :)
