### ISSUE TITLE
Export of .fea file

### ISSUE THREAD

**Issue by samiel60** [fontforge/fontforge#3392]
FontForge 11.21 (September 24th 2017)
Debian Testing / LinuxMint 19.1

I was not able to discover if is it possible to export .fea files with the font feaures
(lookup etc). Is it or not? Thank you

**Comment by skef** [comment]
Yes, it is possible. In the GUI the steps to generate a feature file are described here: http://fontforge.github.io/en-US/documentation/reference/featurefile/#outputting-a-feature-file . From python ( http://fontforge.github.io/en-US/documentation/scripting/python/ ) there is a method `generateFeatureFile` available on the `Font` object.
