### ISSUE TITLE
Kerning in Metrics Window is Incorrectly Displayed

### ISSUE THREAD

**Issue by zachbogart** [fontforge/fontforge#3400]
I am getting an odd behavior with displaying kerning between characters in the metrics view. If I kern by the negative of the letter width, the characters are not overlapping.

For example, here is a lowercase m:
<img width="1270" alt="font_m" src="https://user-images.githubusercontent.com/31786233/50871610-fe95b600-1370-11e9-843d-d7e11c226a89.png">
I have the bearings set to zero on both sides so all of the spacing is from the kerning.
It is ~1100 in width, so I expect kerning a m/m pair with -1100 to overlap the two letters. But instead it overshoots:
<img width="1411" alt="overlap_m" src="https://user-images.githubusercontent.com/31786233/50871623-0a817800-1371-11e9-806b-d837c048bb34.png">
Interestingly, the overlap can be reproduced if the kerning is set to 5/6ths of the letter width (or about -916):
<img width="1410" alt="overlap_cheating_m" src="https://user-images.githubusercontent.com/31786233/50871632-10775900-1371-11e9-94a0-b522ceee58f7.png">

Also, this behavior only occurs in the metrics window. For example, it does not occur in the kerning pair closeup dialogue.

I'm wondering why this is happening. Thanks for your help.

Zach

**Comment by ctrlcctrlv** [comment]
What happens in the generated font? (Try also comparing it with Windows-compatible kern checked to unchecked.)

**Comment by zachbogart** [comment]
The generated font shows them touching, not overlapping. My main confusion is the metric view is showing different visual kerning results compared with the kerning class page or kerning pair closeup page. Not even with a weird font.

Here's an example of it just using blocks I know are 100 by 100. If I kern them by 100, there is clearly too much space between them. Any ideas of the culprit?
<img width="712" alt="screen shot 2019-01-09 at 9 08 22 pm" src="https://user-images.githubusercontent.com/31786233/50947348-c36bb380-1452-11e9-9271-803386078070.png">

**Comment by ctrlcctrlv** [comment]
Like I said, what happens in the generated font? I need to know that to help you. Please post SFDs also.

**Comment by zachbogart** [comment]
The generated font seems to follow the intended kerning where it can (the dollar sign example boxes are perfectly spaced). The overlapping m doesn't seem to work and instead is generated without kerning. 

See attached (I'm still trying to get the hang of FontForge, so I'm just trying to understand it with a toy example): 
[font_testing.sfd.zip](https://github.com/fontforge/fontforge/files/2745292/font_testing.sfd.zip)

Again, it is a visual problem in the metrics window. The kerning seems to render fine, but I can't test out the font in the metrics pane without getting misleading results...

**Comment by ctrlcctrlv** [comment]
The behavior you describe does not happen in my build of FontForge.
![mmm](https://user-images.githubusercontent.com/838783/51072844-bb09b780-16a2-11e9-8d17-02a21810ab4a.png)

**Comment by zachbogart** [comment]
Why is the width of the m above zero? In my example the four numbers are [1199, 50, 50, -1100].

**Comment by skef** [comment]
@zachbogart: I believe a recent code change has fixed this problem. If you can, pull the code in the current master and verify the fix. (I've looked at the sfd in your zip file and I think it works but am not certain of the expected result.)

**Comment by zachbogart** [comment]
Apologies, but I'm having trouble downloading the code from source. I'm trying to follow the [install instructions](https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md) and hitting some road blocks. I'm on a Mac 10.14 Mojave by the way.

When I try to run `./configure` within the fontforge repo, I end up with an error related to pango: "No package 'pangoxft' found". Seems like homebrew of [pango doesn't include x11 anymore](https://github.com/fontforge/fontforge/issues/3077) and I'm confused about how to proceed.

Is the new addition part of the official release on the website? Or will that occur later down the line?

**Comment by skef** [comment]
It took a while but I think I found the automated builds, which are probably a much easier option. Try using the dmg from the bottom of this list: https://dl.bintray.com/fontforge/fontforge/

**Comment by zachbogart** [comment]
Excellent reference! Tried out `FontForge-2019-02-15-836b005.app.dmg` and it solves it. Much appreciated.
