### ISSUE TITLE
missing glib2 dependency in yum install

### ISSUE THREAD

**Issue by lrcstars** [fontforge/fontforge#3414]
I use `yum search fontforge` and install ontforge.x86_64 0:20120731b-12.el7
return Complete
but wen use fontforge return a error:
fontforge: symbol lookup error: /usr/lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
Here's where I found the solution:
https://bugs.archlinux.org/task/57869
I just run `yum install glib2`
https://github.com/fontforge/fontforge/issues/582

**Comment by ctrlcctrlv** [comment]
This is not a FontForge problem. Report the missing dependency to whoever packages FontForge for your platform (presumably Fedora).
