### ISSUE TITLE
Kerning Problems // Only happen to uppercase charcters 

### ISSUE THREAD

**Issue by javapep** [fontforge/fontforge#3415]
Hi, folks. I've made a font that all characters just uppercase. So the lowercase glyphs I filled with uppercase glyphs. Then  I've made kerning with "kerning class" and when I tested in fontforge it worked. Then  I generate and installed it when I tested in Inkscape the kerning just worked to lowercase characters only. How do I fix it? Thank you in advance

This SFD file 
[UPPERCASE.sfd.zip](https://github.com/fontforge/fontforge/files/2764650/UPPERCASE.sfd.zip)

kerning working in FF
![ffkerning](https://user-images.githubusercontent.com/37425641/51165526-14f0c400-18d3-11e9-874b-414fdc109ae3.png)

tested in inkscape ----Kerning just working to lowercase only
![kern](https://user-images.githubusercontent.com/37425641/51165061-98a9b100-18d1-11e9-8efe-e472aa642d25.png)

**Comment by ctrlcctrlv** [comment]
We cannot help you without the SFD file.

**Comment by javapep** [comment]
> We cannot help you without the SFD file.

Thax bro for feedback, this the sfd file

[UPPERCASE.sfd.zip](https://github.com/fontforge/fontforge/files/2760051/UPPERCASE.sfd.zip)
Thank you in advance

**Comment by ctrlcctrlv** [comment]
Interesting. I was able to reproduce the problem with FontForge master. As you say, it shows up correctly in the metrics window in FontForge but fails to work in Inkscape and Writer.

I believe  the issue is related to this warning. (Ignore the stuff about GTK, unrelated.)

![warnings](https://user-images.githubusercontent.com/838783/51303598-d264ee00-1a70-11e9-857d-aab3acea736f.png)

I think you might need to drop the GPOS table, but am not sure how to do it inside FontForge. I'm also not sure how you got into this situation.

I used ttx to dump the generated OTF, then deleted the GPOS table in the output TTX XML, then recompiled to OTF and it works fine.

![inkscape](https://user-images.githubusercontent.com/838783/51304065-1efcf900-1a72-11e9-8fce-cc879e9e69ae.png)

Anyone know how to do this _inside_ FontForge?

**Comment by ctrlcctrlv** [comment]
No problem. I'm not sure how it happened, but that seems plausible. Either way, `kern` and `GPOS` cannot co-exist peacefully in a font, it has to be one or the other AFAICT.

**Comment by javapep** [comment]
Thank bro for everything, so invaluable to me👍. God bless u and have a nice day

**Comment by javapep** [comment]
> No problem. I'm not sure how it happened, but that seems plausible. Either way, `kern` and `GPOS` cannot co-exist peacefully in a font, it has to be one or the other AFAICT.

Hi bro.. can you give me link or other how to use ttx to generate otf

**Comment by ctrlcctrlv** [comment]
I just had this problem in one of my own fonts. Any idea @jtanx ?

**Comment by javapep** [comment]
@ctrlcctrlv how to install the fonttools at terminal or manual... I've tried itu but not succsess

**Comment by skef** [comment]
So when I load the .sfd, generate a .ttf, and then open that .ttf in fontforge, something strange happens: all the lower-case glyphs have their normal names, but the uppercase glyphs have names like "glyph1" or "glyph5". Also, the kerning doesn't work in the metrics window, which makes sense because the GPOS table goes off of glyph name. 

The glyphs have the expected names in the .sfd, so something about the export seems to have this result. No names appear to be stored in the file, so maybe this has something to do with the `post` table?

**Comment by skef** [comment]
When I run `ttx` on the `.ttf` file generated by FontForge I get this as the first entry:
```
  <GlyphOrder>
    <!-- The 'id' attribute is only for humans; it is ignored when parsed. -->
    <GlyphID id="0" name=".notdef"/>
    <GlyphID id="1" name="space"/>
    <GlyphID id="2" name="A"/>
    <GlyphID id="3" name="B"/>
    <GlyphID id="4" name="C"/>
    <GlyphID id="5" name="D"/>
    <GlyphID id="6" name="E"/>
    <GlyphID id="7" name="F"/>
    <GlyphID id="8" name="G"/>
    <GlyphID id="9" name="H"/>
    <GlyphID id="10" name="I"/>
    <GlyphID id="11" name="J"/>
    <GlyphID id="12" name="K"/>
    <GlyphID id="13" name="L"/>
    <GlyphID id="14" name="M"/>
    <GlyphID id="15" name="N"/>
    <GlyphID id="16" name="O"/>
    <GlyphID id="17" name="P"/>
    <GlyphID id="18" name="Q"/>
    <GlyphID id="19" name="R"/>
    <GlyphID id="20" name="S"/>
    <GlyphID id="21" name="T"/>
    <GlyphID id="22" name="U"/>
    <GlyphID id="23" name="V"/>
    <GlyphID id="24" name="W"/>
    <GlyphID id="25" name="X"/>
    <GlyphID id="26" name="Y"/>
    <GlyphID id="27" name="Z"/>
    <GlyphID id="28" name="a"/>
    <GlyphID id="29" name="b"/>
    <GlyphID id="30" name="c"/>
    <GlyphID id="31" name="d"/>
    <GlyphID id="32" name="e"/>
    <GlyphID id="33" name="f"/>
    <GlyphID id="34" name="g"/>
    <GlyphID id="35" name="h"/>
    <GlyphID id="36" name="i"/>
    <GlyphID id="37" name="j"/>
    <GlyphID id="38" name="k"/>
    <GlyphID id="39" name="l"/>
    <GlyphID id="40" name="m"/>
    <GlyphID id="41" name="n"/>
    <GlyphID id="42" name="o"/>
    <GlyphID id="43" name="p"/>
    <GlyphID id="44" name="q"/>
    <GlyphID id="45" name="r"/>
    <GlyphID id="46" name="s"/>
    <GlyphID id="47" name="t"/>
    <GlyphID id="48" name="u"/>
    <GlyphID id="49" name="v"/>
    <GlyphID id="50" name="w"/>
    <GlyphID id="51" name="x"/>
    <GlyphID id="52" name="y"/>
    <GlyphID id="53" name="z"/>
    <GlyphID id="54" name="A"/>
    <GlyphID id="55" name="B"/>
    <GlyphID id="56" name="C"/>
    <GlyphID id="57" name="D"/>
    <GlyphID id="58" name="E"/>
    <GlyphID id="59" name="F"/>
    <GlyphID id="60" name="G"/>
    <GlyphID id="61" name="H"/>
    <GlyphID id="62" name="I"/>
    <GlyphID id="63" name="J"/>
    <GlyphID id="64" name="K"/>
    <GlyphID id="65" name="L"/>
    <GlyphID id="66" name="M"/>
    <GlyphID id="67" name="N"/>
    <GlyphID id="68" name="O"/>
    <GlyphID id="69" name="P"/>
    <GlyphID id="70" name="Q"/>
    <GlyphID id="71" name="R"/>
    <GlyphID id="72" name="S"/>
    <GlyphID id="73" name="T"/>
    <GlyphID id="74" name="U"/>
    <GlyphID id="75" name="V"/>
    <GlyphID id="76" name="W"/>
    <GlyphID id="77" name="X"/>
    <GlyphID id="78" name="Y"/>
    <GlyphID id="79" name="Z"/>
  </GlyphOrder>
```
Note the double-listing of the capitals. This matches the `post` table I see from `ttfdump`. So the question (at least relating to this symptom) is why FontForge is adding the extra entries, probably somewhere on the `tottf()` path.

**Comment by skef** [comment]
Well, this would do it:
```
grep StartChar UPPERCASE.sfd
StartChar: A
StartChar: B
StartChar: C
StartChar: D
StartChar: E
StartChar: F
StartChar: G
StartChar: H
StartChar: I
StartChar: J
StartChar: K
StartChar: L
StartChar: M
StartChar: N
StartChar: O
StartChar: P
StartChar: Q
StartChar: R
StartChar: S
StartChar: T
StartChar: U
StartChar: V
StartChar: W
StartChar: X
StartChar: Y
StartChar: Z
StartChar: A
StartChar: space
StartChar: X
StartChar: Z
StartChar: E
StartChar: W
StartChar: H
StartChar: N
StartChar: T
StartChar: F
StartChar: B
StartChar: C
StartChar: D
StartChar: G
StartChar: I
StartChar: J
StartChar: K
StartChar: L
StartChar: M
StartChar: O
StartChar: P
StartChar: Q
StartChar: R
StartChar: S
StartChar: U
StartChar: V
StartChar: Y
StartChar: a
StartChar: b
StartChar: c
StartChar: d
StartChar: e
StartChar: f
StartChar: g
StartChar: h
StartChar: i
StartChar: j
StartChar: k
StartChar: l
StartChar: m
StartChar: n
StartChar: o
StartChar: p
StartChar: q
StartChar: r
StartChar: s
StartChar: t
StartChar: u
StartChar: v
StartChar: w
StartChar: x
StartChar: y
StartChar: z
```
It appears that the reason your capitals aren't kerning is that your sfd file has two entries for each capital letter, which basically means that it's corrupt. They aren't coded identically:
```
StartChar: A
Encoding: -1 65 0

...

StartChar: A
Encoding: 65 65 26
```
But characters need unique names. 

So, to help further with this bug the next priority is identifying whether FontForge itself somehow created this problem, or some external tool or script did. Which do you think is more likely @javapep ?

**Comment by javapep** [comment]
Thanks your very much @skef for your explanation is very invaluable for me. First I thought  the problem accourade because I copied lookup data and reference with other font ( I Made font Family). Second maybe this bug on my fontforge because some glyphs not have name with normaly "A,B etc" insted  "glyph 1/2 and have nodef". Once again thanks bro👍👍👍...btw  how to install fonttools or ttx dump ini terminal or manualy. I tried to install but failed .

**Comment by skef** [comment]
`fonttools` is a python library, so for that you should look into your OS distribution's preferred python package manager. But beyond that advice I'm afraid installation of other software is beyond the purview here.

**Comment by ctrlcctrlv** [comment]
@skef KJV1611 has no repeating chars yet the same problem.

**Comment by skef** [comment]
@ctrlcctrlv : I realize I should probably be able to derive this from context, but could you supply the usual info, maybe in a new issue so we stop bothering @javapep ? It's fine to point to the .sfd without appending, but I need more info on the tools, the specific characters, and so on.

**Comment by skef** [comment]
I believe this was wrapped up accurately and any remaining issues have been discussed elsewhere.
