### ISSUE TITLE
Scaling Characters

### ISSUE THREAD

**Issue by dzhmartin** [fontforge/fontforge#3421]
Hey Folks, I need to make the letters of my font bigger without changing the em size. 
Here's what I am trying to do: 
When I load fonts onto my Kindle, I am able to change the font size to any of the integers between 1    and 10 (Size 1, Size 2, Size 3, etc). The issue is my font in Size 4 is too small and is too big in Size 5. Unlike in a Microsoft Word doc, where I have greater control over the font size (I can change it to 12pt, 12.1pt, 12.111pt, etc.), I'm stuck with Sizes 4 and 5. 
Is there a way to scale up all the characters in fontforge so that when I pick Size 4, everything is a bit bigger?

**Comment by skef** [comment]
There are many subtle issues with scaling fonts, including the details of spacing and kerning. Depending on how relevant these are to your situation you might need the better control available in a python script. 

However, there is a quick option:

1. From the menu in the font window pick Edit -> Select -> Select all (or type Control-A)
2. Pick Element -> Transformations -> Transform (or type Control-backslash)
3. Leave "Glyph Origin" as the Origin but pick "Scale Uniformly..." in the next drop-down. Enter the desired scale factor (out of 100). 
4. Recommended: Leave the first two boxes unchecked but check the last four. 
5. Hit "OK" and wait for the transformation process to complete. 
6. Save the file and generate the fonts as needed.

**Comment by orderla88** [comment]
Thank you so much.
