### ISSUE TITLE
web browsers reject generated woff2 file

### ISSUE THREAD

**Issue by Yay295** [fontforge/fontforge#3422]
Using FontForge built from source and configured with `./configure --enable-python-extension --enable-woff2`.
```
$ fontforge --version
Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 18:37 UTC 21-Jan-2019-D.
 Based on source from git with hash: b79781794295a7f3fb60f42094ef31f4a7d36b60
fontforge 18:37 UTC 21-Jan-2019
libfontforge 20190121
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

Test Python Code
```python
import fontforge

file = 'BellGothicStd-Black.otf'
for fname in fontforge.fontsInFile(file):
    font = fontforge.open(file + '(' + fname + ')', 1)
    newfilename = font.cidfontname or font.fontname
    font.generate(newfilename + '.woff2')
```
```
$ ./test.py
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
 SubFamily string in the language English (US)
 Mac String: Black
Windows String: Regular
Warning: Mac and Windows entries in the 'name' table differ for the
 Fullname string in the language English (US)
 Mac String: Bell Gothic Std Black
Windows String: BellGothicStd-Black
```
Input file and generated output file.
[BellGothicStd-Black.otf.zip](https://github.com/fontforge/fontforge/files/2780464/BellGothicStd-Black.otf.zip)
[BellGothicStd-Black.woff2.zip](https://github.com/fontforge/fontforge/files/2780465/BellGothicStd-Black.woff2.zip)

When trying to load the woff2 file I get the following error messages,
in Chrome:
```
Failed to decode downloaded font: https://example.com/fonts/BellGothicStd-Black.woff2
OTS parsing error: OS/2: Failed to parse table
```
in Firefox:
```
downloadable font: OS/2: usFirstCharIndex 65535 > usLastCharIndex 0 (font-family: "Bell Gothic Std Black" style:normal weight:900 stretch:normal src index:0) source: https://example.com/fonts/BellGothicStd-Black.woff2  fonts.css:1329:12
downloadable font: OS/2: Failed to parse table (font-family: "Bell Gothic Std Black" style:normal weight:900 stretch:normal src index:0) source: https://example.com/fonts/BellGothicStd-Black.woff2  fonts.css:1329:12
downloadable font: rejected by sanitizer (font-family: "Bell Gothic Std Black" style:normal weight:900 stretch:normal src index:0) source: https://example.com/fonts/BellGothicStd-Black.woff2
```

A woff file (not woff2) generated using the same script loads fine.
[BellGothicStd-Black.woff.zip](https://github.com/fontforge/fontforge/files/2780476/BellGothicStd-Black.woff.zip)

**Comment by ctrlcctrlv** [comment]
Looks like FontForge is generating an invalid OS/2 table, however `woff2_info` and `woff2_decompress` understand it just fine:

```
[fred@pc conrod]$ woff2_info /tmp/BellGothicStd-Black.woff2 
Processing /tmp/BellGothicStd-Black.woff2 => /tmp/BellGothicStd-Black.woff2
WOFF2Header
signature           0x774f4632
flavor              0x00010000
length              12968
numTables           16
reserved            0
totalSfntSize       31160
totalCompressedSize 12868
majorVersion        1
minorVersion        0
metaOffset          0
metaLength          0
metaOrigLength      0
privOffset          0
privLength          0
TableDirectory starts at +48
Entry offset flags tag  origLength txLength
    0     48  0x19 BASE         52
    1     50  0x3f FFTM         28
    2     56  0x1a GDEF         72
    3     58  0x1b GPOS       3404
    4     61  0x1c GSUB        958
    5     64  0x06 OS/2         96
    6     66  0x00 cmap        642
    7     69  0x11 gasp          8
    8     71  0x0a glyf      21988    16583
    9     78  0x0b loca        512        0
   10     82  0x01 head         54
   11     84  0x02 hhea         36
   12     86  0x03 hmtx       1018
   13     89  0x04 maxp         32
   14     91  0x05 name       1353
```

Here's the OS/2 table in the TTF generated by `woff2_decompress`:

```
  <OS_2>
    <!-- The fields 'usFirstCharIndex' and 'usLastCharIndex'
         will be recalculated by the compiler -->
    <version value="2"/>
    <xAvgCharWidth value="447"/>
    <usWeightClass value="900"/>
    <usWidthClass value="5"/>
    <fsType value="00000000 00000100"/>
    <ySubscriptXSize value="650"/>
    <ySubscriptYSize value="600"/>
    <ySubscriptXOffset value="0"/>
    <ySubscriptYOffset value="75"/>
    <ySuperscriptXSize value="650"/>
    <ySuperscriptYSize value="600"/>
    <ySuperscriptXOffset value="0"/>
    <ySuperscriptYOffset value="350"/>
    <yStrikeoutSize value="50"/>
    <yStrikeoutPosition value="315"/>
    <sFamilyClass value="0"/>
    <panose>
      <bFamilyType value="2"/>
      <bSerifStyle value="11"/>
      <bWeight value="7"/>
      <bProportion value="6"/>
      <bContrast value="2"/>
      <bStrokeVariation value="2"/>
      <bArmStyle value="2"/>
      <bLetterForm value="4"/>
      <bMidline value="2"/>
      <bXHeight value="4"/>
    </panose>
    <ulUnicodeRange1 value="10000000 00000000 00000000 10101111"/>
    <ulUnicodeRange2 value="01000000 00000000 00100000 01001010"/>
    <ulUnicodeRange3 value="00000000 00000000 00000000 00000000"/>
    <ulUnicodeRange4 value="00000000 00000000 00000000 00000000"/>
    <achVendID value="ADBE"/>
    <fsSelection value="00000000 00000000"/>
    <usFirstCharIndex value="65535"/>
    <usLastCharIndex value="0"/>
    <sTypoAscender value="748"/>
    <sTypoDescender value="-252"/>
    <sTypoLineGap value="200"/>
    <usWinAscent value="942"/>
    <usWinDescent value="250"/>
    <ulCodePageRange1 value="00000000 00000000 00000000 00000001"/>
    <ulCodePageRange2 value="00000000 00000000 00000000 00000000"/>
    <sxHeight value="525"/>
    <sCapHeight value="723"/>
    <usDefaultChar value="0"/>
    <usBreakChar value="32"/>
    <usMaxContext value="4"/>
  </OS_2>
```

**Comment by ctrlcctrlv** [comment]
Attempting to remove the table and recompiling with ttx/woff2_compress results in `OTS parsing error: OS/2: missing required table`

However...I got it to work by doing the following, basically I just did a round trip:

```
#!/bin/bash
woff2_decompress BellGothicStd-Black.woff2
ttx BellGothicStd-Black.ttf
rm BellGothicStd-Black.ttf
ttx BellGothicStd-Black.ttx
woff2_compress BellGothicStd-Black.ttf 
```

```
Processing BellGothicStd-Black.ttf => BellGothicStd-Black.woff2
Compressed 24719 to 12816.
```

![hola](https://user-images.githubusercontent.com/838783/51678651-e338d500-2017-11e9-8e73-0f47c133ff16.png)

Why did this work? I don't know. Hopefully some investigator can use the knowledge I've gained to crack the case, I'm too tired to go further with it. I think FontForge is making some error that ttx is fixing "automagically".

**Comment by ctrlcctrlv** [comment]
Oh! Just noticed something very interesting in the Firefox output!: `usFirstCharIndex 65535 > usLastCharIndex 0`

This is the problem! `ttx` is fixing it, it changes

```
    <usFirstCharIndex value="65535"/>
    <usLastCharIndex value="0"/>
```

to

```
     <usFirstCharIndex value="32"/>
     <usLastCharIndex value="64258"/>
```

This should be an easy patch in FontForge :+1:

**Comment by skef** [comment]
The explanation for those values is fairly simple and I expect the fix will be also. But some expertise would be helpful. 

`tottf.c:setos2()` initializes the variables that wind up getting assigned to `os2->firstcharindex` and `os2->lastcharindex` with this line:
```
avg1 = avg2 = last = 0; first = 0xffff;
```
Those values are then never changed. 

The problem seems to stem from this function having various guards that make use of the `format` parameter and `ff_woff2` (and `ff_woff` for that matter) are absent. The function was last updated in 2015 (and in ways probably irrelevant to this issue) and most likely needs some further updating for WOFF2, although **not necessarily** for the following reason:

The guard `format>=ff_ttf && format<=ff_otfdfont` pops up in a number of places. Given that WOFF2 seems to amount to a TTF wrapper (or at least that we're using it that way), my guess is that output will start working correctly if `ff_woff2` makes this guard true. 

In any case, `enum fontformat` is subject to inequality comparisons not documented at the declaration. Newer formats should therefore be checked against those comparisons and the enum should be reordered if necessary. To help with that here is some grepping (with references to fv_pythonbase removed):
```
fontforge/splinechar.c:1871:    else if ( format<=ff_cff )
fontforge/splinechar.c:1873:    else if ( format<=ff_ttfdfont )
fontforge/splinechar.c:1875:    else if ( format<=ff_otfdfont )
fontforge/macbinary.c:1253:    uint32 rfork_base = format>=ff_ttfdfont?0:128;   /* space for mac binary header */
fontforge/tottf.c:2847:    if ( format>=ff_ttf && format<=ff_ttfdfont ) {
fontforge/tottf.c:3369:    if (( format>=ff_ttf && format<=ff_otfdfont) && (at->gi.flags&ttf_flag_symbol))
fontforge/tottf.c:3448:     if ( ( format>=ff_ttf && format<=ff_otfdfont && sc->ttf_glyph>2) ||
fontforge/tottf.c:3449:             ( format>=ff_ttf && format<=ff_otfdfont && sc->ttf_glyph>0) ) {
fontforge/tottf.c:4055:    if (( format>=ff_ttf && format<=ff_otfdfont) && (at->gi.flags&ttf_flag_symbol))
fontforge/tottf.c:4833:    if (( format>=ff_ttf && format<=ff_otfdfont) && (at->gi.flags&ttf_flag_symbol))
```

@jtanx: I believe you commited the WOFF2 support. Do you have initial thoughts on this?

**Comment by jtanx** [comment]
@skef, what you describe sounds valid to me, woff2 support amounts to internally producing a ttf then passing it off to the woff2 library, so it should do everything that you'd expect on the ttf path.

**Comment by skef** [comment]
In that case the fix for this bug would involve inspecting `fontformat`:
```
enum fontformat { ff_pfa, ff_pfb, ff_pfbmacbin, ff_multiple, ff_mma, ff_mmb,
        ff_ptype3, ff_ptype0, ff_cid, ff_cff, ff_cffcid,
        ff_type42, ff_type42cid,
        ff_ttf, ff_ttfsym, ff_ttfmacbin, ff_ttc, ff_ttfdfont, ff_otf, ff_otfdfont,
        ff_otfcid, ff_otfciddfont, ff_svg, ff_ufo, ff_ufo2, ff_ufo3, ff_woff, ff_woff2, ff_none };
```
To decide which of the later values should be repositioned between `ff_tff` and `ff_otfdfont`. `ff_svg` has been there a while and the `ufo`s don't seem relevant, so that leaves the `ff_woff` and `ff_woff2`. But `woff` support has been there longer. Does it not use the TTF path, or not use it for this? Could it have been broken? 

I'll prepare a push request with a repositioned `ff_woff2` (and a **comment**) so further investigation can have something to work with.

**Comment by skef** [comment]
Oh good grief what a nightmare; I forgot about all the other tables built to be indexed by that enum. 

OK, new plan: leave ff_woff2 where it is and define macros for these checks right after the enum so that the code is a little more complicated but still centralized.
