### ISSUE TITLE
How do I get 'Regular' to not be added to the font name?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [fontforge/fontforge#3427]
An extension I use loads its own font file for text symbols, but for whatever reason they started randomly failing recently, which seems like a speed issue since they load correctly most of the time. Figured I'd try to convert the woff to a ttf to install locally, and rename it to the font name they use, witch is 'Batch', but no matter what I do, when I install it, the font is always named 'Batch Regular'. 

First time using it, and I'm following the tutorials, but I guess I'm doing something wrong. Any guidance would be appreciated.

[ef_conv_zip_uRrmK2BeUwA5qzxOhEL6WgeF.zip](https://github.com/fontforge/fontforge/files/2798767/ef_conv_zip_uRrmK2BeUwA5qzxOhEL6WgeF.zip)

**Comment by skef** [comment]
This doesn't address your FontForge issue, but it looks like there is a .ttf of this font generated by the author here: https://github.com/AdamWhitcroft/batch/tree/master/Webfont

**Comment by narcolepticinsomniac** [comment]
Appreciate the heads-up. Unfortunately, Windows says it's invalid by default. Seems they used invalid characters in their names. If I edit the names, it'll install, just like the one in the zip I linked, but the stupid 'Regular' is added no matter what I've tried with either file.

The fonts randomly failing were for RES on Reddit, and they're using pseudo-elements, so I was able to specify 'Batch Regular' with a little user CSS, which fixed it:

```
[id*="RES" i]:not([text]):before,
[id*="RES" i]:not([text]):after,
[class*="RES" i]:not([text]):before,
[class*="RES" i]:not([text]):after {
    font-family: Batch Regular!important;
}
```

This really shouldn't be necessary though. I would think there has to be a way to name it 'Batch' instead of 'Batch Regular', and I just haven't been able to figure it out.

**Comment by ctrlcctrlv** [comment]
I really don't understand what you mean.

In the file you uploaded, the font is just named "Batch" on my system, weight Regular.

"Regular" seems to be coming from the OS/2 data, because the PS weight is "Book"

**Comment by narcolepticinsomniac** [comment]
Not sure how to phrase it any clearer. How do I get rid of 'Regular' being added to the font name when installed? I get that it's added because the weight is "Book". I tried deleting that from PS Names. I've tried deleting everything but the bare essentials from TTF Names, but whatever I do, Windows adds the weight when it installs. 

If I open it again after, 'Regular' will be a hard coded entry in red text. So my question is, how do I prevent that? All fonts have weights. Not all fonts have weights in their names, so there has to be some way around it. Some property to give it, or some entry to make. That's what I mean.

**Comment by ctrlcctrlv** [comment]
When I install it I see no "Regular" in the name.

**Comment by ctrlcctrlv** [comment]
When I install it I see no "Regular" in the name. . . but I'm not using Windows. I don't see anything hard-coded in TTF names in the file you uploaded.

I see that both in PS and TTF names the name of the font is either a period, or a period followed by U+007F. . . perhaps you should try setting these to "Batch", maybe Windows is generating a font name because these are unorthodox font names.

**Comment by narcolepticinsomniac** [comment]
My fault for not really providing much info on the zip. I just grabbed the woff which  the extension was loading and used some online converter to convert to ttf. It was meant to be an easier starting point, but you could just as easily start with the woff. If I install the ttf in the zip, I get:

![batch icons regular](https://user-images.githubusercontent.com/14100003/51798454-67d64f80-21e0-11e9-9402-99178fbbcaea.png)

If I load the zip ttf in FontForge and change the name, like so:

![ps names](https://user-images.githubusercontent.com/14100003/51798459-96ecc100-21e0-11e9-96de-8a8725cf9218.png)

(only started playing with these values after 'Regular' was still being added after name change)
![ttf names](https://user-images.githubusercontent.com/14100003/51798461-9d7b3880-21e0-11e9-9437-7d562da0642d.png)

I get:

![batch regular](https://user-images.githubusercontent.com/14100003/51798465-ae2bae80-21e0-11e9-9f11-10db82735853.png)


No matter what entries I try to alter or delete, 'Regular' gets tacked on when installing in Win 8.1. If you have a successfully installed version in `C:\Windows\Fonts` named 'Batch', please copy it from there and hook me up with that copy. I'd be interested to see if it actually installs as 'Batch' on my OS. Appreciate the feedback btw.

**Comment by ctrlcctrlv** [comment]
Can you please upload the generated TTF you're installing so I can look at it in `ttx`? I see many other fonts in that _also_ have "Regular" after them, I'm suspicious this is a Windows thing.

**Comment by ctrlcctrlv** [comment]
Actually, I think I've figured it out already. In Windows Explorer, _all fonts_ will have the name of their style after them unless you have multiple fonts installed with the same family name but different styles. So there's no way to remove "Regular" from that view unless you install a "Bold" version I suppose.

**Comment by narcolepticinsomniac** [comment]
Yet it does for some reason? Specifying 'Batch Regular' in the CSS works, whereas 'Batch' doesn't.

**Comment by ctrlcctrlv** [comment]
In programs does it show as "Batch" or "Batch Regular"?

> Can you please upload the generated TTF you're installing so I can look at it in ttx?

**Comment by narcolepticinsomniac** [comment]
Sorry, thought you changed your mind, and then I altered the original experimenting with installing a bold version. Here's the ttf after altering in FontForge. If you open it, you'll see 'Regular' specified, which was not present when I generated the file. I've tried deleting it entirely, or setting the value to other things, to no avail. I figured it was something simple I'm doing wrong because I've never used this program before, or even really screwed much with fonts in general.

[Batch.zip](https://github.com/fontforge/fontforge/files/2799870/Batch.zip)

**Comment by narcolepticinsomniac** [comment]
Oh, and it only seems to work if 'Batch Regular' is specified in the CSS, and that's what shows in the computed tab in devtools. Correct me if I'm wrong, because I wish I was. I really figured specifying 'Batch' would work since it's the specified font-family name in the file.

**Comment by ctrlcctrlv** [comment]
What happens if you delete "Styles (SubFamily)" in TTF names?

**Comment by ctrlcctrlv** [comment]
(By the way, this font appears fine in Linux. KFontView displays it as "Batch", `fc-list` understands it as "Batch", LibreOffice lists it as "Batch", I can use it in CSS as "Batch", and so on.)

**Comment by narcolepticinsomniac** [comment]
Try it. It was deleted when I generated that file. Seems automatically generate it. There's lots of things Linux handles in more sane ways than Windows, but I'm trying to get it named correctly in Windows. Do you have a Windows install to check?

**Comment by narcolepticinsomniac** [comment]
Nvm, obviously you do from a previous comment.

**Comment by narcolepticinsomniac** [comment]
Btw, I have to think it's possible, because at one point I got it to be named 'Batch Batch'. Unfortunately that still sucks and I couldn't even repro.

**Comment by narcolepticinsomniac** [comment]
Appreciate you taking the time. I don't see Win 10 as an "upgrade" though, so that's not happening. I'll take some font naming bug over forced updates and telemetry "Windows as a service" any day of the week. I'll hang on to 8.1 till it becomes unusable and hope that LInux gets better hardware acceleration browser support in the meantime.

**Comment by ctrlcctrlv** [comment]
Closed as stale answered question involving old Windows version.
