### ISSUE TITLE
Installing fontforge-extras from ppa archive crashes

### ISSUE THREAD

**Issue by michiel5342** [fontforge/fontforge#3430]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

I tried to upgrade fontforge from the very old Ubuntu package to the newest release. Apt-get reported a crash trying to overwrite "/usr/share/fontforge/Adobe-Japan2-0.cidmap", which was held by package "fontforge-common". I tried purging fontforge first, and reinstall cleanly, but the crash repeated itself on another Adobe-*.cidmap for the same reason: fontforge-common and fontforge-extras have a concurrency problem.

### When reporting a bug/issue:
- [x] Copy of Terminal Output
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

```
    michiel@odin:~/Source$ sudo apt-get install fontforge fontforge-common fontforge-extras
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    Suggested packages:
        fontforge-doc
    The following NEW packages will be installed:
        fontforge fontforge-common fontforge-extras
    0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
    Need to get 399 kB/2,162 kB of archives.
    After this operation, 8,664 kB of additional disk space will be used.
    Get:1 http://nl.archive.ubuntu.com/ubuntu xenial/universe amd64 fontforge-extras amd64      0.3-4ubuntu1 [399 kB]
    Fetched 399 kB in 0s (686 kB/s)           
    (Reading database ... 479594 files and directories currently installed.)
    Preparing to unpack .../fontforge-common_20170731-0ubuntu1~xenial_all.deb ...
    Unpacking fontforge-common (20170731-0ubuntu1~xenial) ...
    Selecting previously unselected package fontforge.
    Preparing to unpack .../fontforge_20170731-0ubuntu1~xenial_amd64.deb ...
    Unpacking fontforge (20170731-0ubuntu1~xenial) ...
    Selecting previously unselected package fontforge-extras.
    Preparing to unpack .../fontforge-extras_0.3-4ubuntu1_amd64.deb ...
    Unpacking fontforge-extras (0.3-4ubuntu1) ...
    dpkg: error processing archive /var/cache/apt/archives/fontforge-extras_0.3-4ubuntu1_amd64.deb     (--unpack):
        trying to overwrite '/usr/share/fontforge/Adobe-Japan2-0.cidmap', which is also in package fontforge-common 20170731-0ubuntu1~xenial
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    Processing triggers for shared-mime-info (1.5-2ubuntu0.2) ...
    Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
    Processing triggers for mime-support (3.59ubuntu1) ...
    Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
    Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
    Rebuilding /usr/share/applications/bamf-2.index...
    Processing triggers for man-db (2.7.5-1) ...
    Errors were encountered while processing:
        /var/cache/apt/archives/fontforge-extras_0.3-4ubuntu1_amd64.deb
    E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Version used:
```
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.5 LTS
    Release:	16.04
    Codename:	xenial
```
### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
This is the wrong place to report your bug. This is not a FontForge problem, it is a problem with the packaging used by a certain repository. Report it  to the Ubuntu packagers. This should be closed like #3414.
