### ISSUE TITLE
Simplify may distort more than it's supposed to

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3433]
When points "Can Be Interpolated", Simplify may distort the shape by turning on the "interpolate" setting, which moves points.

https://www.dropbox.com/s/qeru8h0j9l0e0qq/2019_01_29_13_34_06_1364x768.avi?dl=0

The video above shows the glyph being distorted by Simplify, then after setting the points to "Can't Be Interpolated" Simplify gave much less distortion.

**Comment by daT4v1s** [comment]
try using "simplify more" instead of simplify, 
(the command maybe bit of a misnomer, 
the "more" here does not necessarily mean simplify it further, but simplify with more options,
perhaps it should be called simplify more/advanced options)

then set the error limit to a lower em-value.
