### ISSUE TITLE
Sadly, one person is not impressed with FontForge.

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3434]
This is horrible. Luc(as) de Groot, the creator of [Consolas](https://github.com/PiotrGrochowski/Consolas/), said

`Of course Consolas was not made with FontForge! (which is dead and inconvenient) You might want to research font software first.`

That's AWFUL! Any way to impress that guy?!

**Comment by skef** [comment]
Dude, come on. There's just a few volunteers here helping to keep some software working and comprehensible. Please don't troll.

**Comment by frank-trampe** [comment]
Oh, @skef, you have to admit that's pretty funny!

@PiotrGrochowski, the world's population of type designers can be divided into two types of people: FontForge people and snobs. I find it amusing that we can classify Mr. de Groot solely by the tone of his writing. He could write that about something else entirely, and I could tell you that he's not a FontForge user.

There are actually a lot of "easy" cosmetic changes that we could make to win snobs to FontForge, and I'd love to save them the money they spend on commercial software, but most of the changes (the ones we haven't made) would befuddle or inconvenience our core users. Ordinarily, I'd suggest that the best response here is to make gently snide remarks about Consolas, but it would obviously be really ironic if @PiotrGrochowski were the one doing so.

If Luc is reading this, I'm sure he'll understand that the trolling here is totally proportionate and non-malicious.
