### ISSUE TITLE
Images in buttons are aligned incorrectly

### ISSUE THREAD

**Issue by MaddTheSane** [fontforge/fontforge#3439]
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [X] Screenshot
<img width="482" alt="screen shot 2019-02-01 at 4 57 01 pm" src="https://user-images.githubusercontent.com/719492/52156847-f5ce9200-2647-11e9-8c21-4d414eb9f7b8.png">

- [X] The FontForge version and the operating system you're using
c96d3eb78197aeb1447a8957b37b687398a1b529 - Mac OS X 10.14.3
- [X] The behavior you expect to see, and the actual behavior
Expected to have the images in the buttons centered correctly instead of off-center.
- [X] Steps to reproduce the behavior 
Build under Mac OS X with gdk enabled.
- [ ] \(optional) Possible solution/fix/workaround

### Additional Info
Running on a MacBook Pro with a Retina display.

**Comment by ctrlcctrlv** [comment]
This is a generic HiDPI problem, shown platform is Arch Linux.

![icons](https://user-images.githubusercontent.com/838783/52161446-e6ab1b00-26ff-11e9-9a22-32c92123d0ff.png)

**Comment by MaddTheSane** [comment]
So is it a problem with FontForge or a bug in GDK?

**Comment by ctrlcctrlv** [comment]
How do you know you're using GDK? I don't think you are, it looks like FontForge's native `gdraw` toolkit.

**Comment by MaddTheSane** [comment]
I passed `--enable-gdk=gdk3` as a configure option. And it's showing up as an app on the OS X dock.

I'll try rebuilding the GTK2 library to target Quartz, just in case.

**Comment by ctrlcctrlv** [comment]
OK, I think I understand. It uses G**D**K, but not G**T**K, meaning it draws the gdraw widgets onto a GDK surface instead of calling to X11 directly. Cool.

Under HiDPI I've never seen correctly centered icons. I've noticed this issue for years but never bothered to report it because it seemed trivial.

**Comment by jtanx** [comment]
Ok, this is definitely a regression, I can see the out of whack icons on Windows too
![image](https://user-images.githubusercontent.com/5137410/52339215-9b2aa100-2a60-11e9-9948-762a3328e685.png)

Just a hunch, but I'd say it's a fairly recent regression

**Comment by jtanx** [comment]
Bisected to d45ecfe875acd4bf731f111985ac37342802c79c
