### ISSUE TITLE
I can't use Contextual Chaining Substitution by classes using complex dialog

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3440]
I want to use Contextual Chaining Substitution using classes by complex dialog but fontforge crash when I click on "OK" button after defining classes and rules.

My Platforms' and Software's info:

OS: Ubuntu 18.10, I also have this problem on Windows Server 2012 R2

FontForge Version: 11:21 UTC 24-Sep-2017(11:21 UTC 24-Sep-2017-ML-D)

FontForge Lib Version: 11:21 UTC 24-Sep-2017

**Comment by ctrlcctrlv** [comment]
This bug is most likely legitimate, but in practice most OpenType fonts made with FontForge do not have their features defined using the GUI. It's much simpler and less error prone to merge feature files instead using the File menu item- an example feature file can be found [here](https://github.com/ctrlcctrlv/kjv1611/blob/master/features.fea).

**Comment by skef** [comment]
The fact that you have verified the bug on two platforms suggests that you can reproduce the problem. I know that this request asks more of someone just trying to help, and that it could be that entering anything into the dialog causes the problem, but if you could add to this issue a set of specific steps that cause the crash, either relative to an `.sfd` file you provide or one from the tests/fonts directory of this repository, it's much more likely to be looked at. I'm likely to take a look if I don't have to spend too much time researching the potential steps.

**Comment by skef** [comment]
@AlirezaAlipour Can you check this with the more recent Windows releases, and add specific instructions to reproduce if it still crashes?

**Comment by AlirezaAlipour** [comment]
> @AlirezaAlipour Can you check this with the more recent Windows releases, and add specific instructions to reproduce if it still crashes?

Sorry for my delay,

Now I compiled fontforge from source, but when I try to use Contextual Chaining Substitution using classes by complex dialog using follow step I experiencing crashing.



My steps:

I suppose I want to create lookup to substitute first digit of "00" pattern with "1" to getting "10", I know that it can be achieved by other methods but I use this example only for illustration.

1. First I go to Lookups through Element > Font Info > Lookups
2. Then I create a Single Substitution lookup with “aalt” feature, then I create a subtable for it in order to substitute “0” with “1”.
2. Then I add a lookup Contextual Chaining Substitution lookup and `calt` feature, then I create a subtable for it, then try to edit it with selecting By Class and Complex dialog type and then click on "next" button, and in the Match classes section I add new record with Class "test" and Glyph in class "zero(0)", and then I try to create a rule in the "Matching rules base on list of class" by clicking on "new", then I set created lookup in the the step 2 at position 0 in “An ordered list of lookups and positions” section then I add the class “test” in the List of Class names of Match and Backtrack, then I click on “next” and then when I click on “OK” it crash.

OS: Ubuntu 18.10, now I don't have the Windows to check the problem on it.

**Comment by jamesconstable** [comment]
I am able to consistently reproduce this issue on Mac OS as well. Even simple inputs in the complex contextual chaining substitution dialog result in a crash on clicking OK.

OS: Mac OS 11.4 (Big Sur)
FontForge version: 2020-11-07 20:56 UTC-ML-D-GDK3

**Comment by jtanx** [comment]
@AlirezaAlipour / @jamesconstable  can you try the fix from #4777?

Linux AppImage: https://github.com/fontforge/fontforge/suites/3224669734/artifacts/74700761
MacOS bundle: https://github.com/fontforge/fontforge/suites/3224669734/artifacts/74700760

**Comment by jamesconstable** [comment]
This solves the problem for me. Thanks for the lightning fix!

**Comment by jtanx** [comment]
Great, thanks for confirming!
