### ISSUE TITLE
goto glyph dialog : numpad does not work

### ISSUE THREAD

**Issue by daT4v1s** [fontforge/fontforge#3450]
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
build from 2019-01jan-15 linux
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 

![screenshot from 2019-02-07 04-45-19 2](https://user-images.githubusercontent.com/47403824/52403086-ec07bd00-2a93-11e9-9af2-c98b732272aa.png)
![screenshot from 2019-02-07 04-44-28](https://user-images.githubusercontent.com/47403824/52403141-080b5e80-2a94-11e9-977f-0c9d80faf83e.png)

typing numbers on keypad does not work unexpectedly, only on main keyboard, 

- [x] \(optional) Possible solution/fix/workaround (un-optimal)
pressing shift-key to output numbers, else they behave as arrow keys though num-lock on

**Comment by jtanx** [comment]
Try compiling with the gdk backend, fairly sure it works on that (or at lest it does on windows)

Although probably something to do with how key events are processed in https://github.com/fontforge/fontforge/blob/master/gdraw/gxdraw.c#L2898-L2960
