### ISSUE TITLE
Self intersect gray area

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3456]
When two paths (say, A and B) touch in a point (say, C) but not pass through each other, like this

        A
        A
    A A C B B
        B
        B

it's considered a self intersect. Is this invalid in .ttf files? What if I wanted to make a fake bitmap font (real bitmap fonts (.fon) do not support Unicode)? I did make a fake bitmap font and it works perfectly fine, but the "Self Intersecting" warnings make me worried. Like, I'm unsure whether to do characters like this

          1 A A 2
          A     A
          A     A
    3 B B 4 A A 3
    B     B
    B     B
    2 B B 1

or this

          4 A A 5
          A     A
          A     A
    2 A A X A A 6
    A     A
    A     A
    1 A A 8

Both count as "Self Intersecting"! "Remove Overlap" oscillates between those two (changes one to the other) but it's always "Self Intersecting".

**Comment by skef** [comment]
One common practice is to leave overlaps in the .sfd file (and perhaps even in generated OpenType font files) while removing it (either by script or manually) before generating a TrueType font and not saving the resulting .sfd. This is often necessary when outlines that overlap with references (that are useful to keep *as* references). Given that workflow, there's no obvious practical problem with just treating touching points as overlapping in TrueType (other than ignoring the warnings if you choose to validate beforehand).

**Comment by ctrlcctrlv** [comment]
First, bitmap fonts do support Unicode, depending on the file format. The most used format today, the X11 bitmap format BDF, certainly supports Unicode. The FON format is proprietary, deprecated and should not be used for new fonts as far as I know.

On to your question, self-intersects are completely valid, even true self-intersects, they're just bad practice.

**Comment by ctrlcctrlv** [comment]
For the widest possible audience to use your pixel font in 2019, I recommend including TTF splines and also having an embedded bitmap font (EBDT table). If this is not possible, BDF format.

**Comment by PiotrGrochowski** [comment]
> 
> 
> For the widest possible audience to use your pixel font in 2019, I recommend including TTF splines and also having an embedded bitmap font (EBDT table). If this is not possible, BDF format.

They wouldn't be able to access my PC anyway, so what's the point?

**Comment by PiotrGrochowski** [comment]
>The FON format is proprietary, deprecated and should not be used for new fonts as far as I know.

Please don't disrespect younger fonters who are not prepared for making vector fonts. .fon is the only bitmap font format supported by Microsoft Windows.

**Comment by ctrlcctrlv** [comment]
No it isn't, Windows supports embedded bitmaps in TTF just as well.

**Comment by PiotrGrochowski** [comment]
> 
> 
> No it isn't, Windows supports embedded bitmaps in TTF just as well.

A bitmap font is only a true bitmap font if it always snaps to an integer multiple of one of its own sizes.

**Comment by ctrlcctrlv** [comment]
That might be your definition, but is not the normal understanding of the term "bitmap font".

**Comment by PiotrGrochowski** [comment]
Microsoft is always right though, so bitmap fonts must snap to an integer multiple of one of its own sizes.

**Comment by ctrlcctrlv** [comment]
Let's be clear. There is a bitmap font _format_, and then there is a bitmap font _renderer_. The _format_ can be rendered in any way, snapping or not snapping, depending on the implementation. There is nothing special about any format that would force it to be rendered in integer multiples only. Some software might do that, but other software may just as well not.

**Comment by PiotrGrochowski** [comment]
That's a first world problem
