### ISSUE TITLE
python printSample waterfall is empty

### ISSUE THREAD

**Issue by fovea1959** [fontforge/fontforge#3457]
### When reporting a bug/issue:
- [x] Screenshot
![image](https://user-images.githubusercontent.com/5349196/52498135-e1d5e380-2ba5-11e9-99b4-2b069a5fbbf7.png)

- [x] The FontForge version and the operating system you're using
Ubuntu 18.04
```
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:21 UTC 24-Sep-2017-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 11:21 UTC 24-Sep-2017
libfontforge 20170924
```
- [x] The behavior you expect to see, and the actual behavior
The Python printSample() won't print waterfall, you just get a header line.
- [x] Steps to reproduce the behavior 
run this script, look at waterfall.pdf
```
import fontforge

amb = fontforge.open('FXMatrix105MonoComprExpDblULSubItalic.sfd')
fontforge.printSetup('pdf-file', 'z.pdf')
amb.printSample('fontdisplay', 24, 'abcdefABCDEF', 'fontdisplay.pdf')
amb.printSample('waterfall', (12, 16, 24, 36), 'abcdefABCDEF', 'waterfall.pdf')
amb.printSample('fontsample', 24, 'abcdefABCDEF', 'fontsample.pdf')
```

Input file and sample output are attached (output is shown above).

[waterfall.pdf](https://github.com/fontforge/fontforge/files/2846384/waterfall.pdf)

[FXMatrix105MonoComprExpDblULSubItalic.zip](https://github.com/fontforge/fontforge/files/2846386/FXMatrix105MonoComprExpDblULSubItalic.zip)

- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
The reason this is happening is you haven't selected the letters first. Try:
 
```python
import fontforge
amb = fontforge.open('FXMatrix105MonoComprExpDblULSubItalic.sfd')
fontforge.printSetup('pdf-file', 'z.pdf')
amb.selection.select(("unicode","ranges"),ord('A'),ord('Z'))
amb.printSample('waterfall', (12, 16, 24, 36), 'abcdefABCDEF', 'waterfall.pdf')
```

**Comment by fovea1959** [comment]
ah! that works, thank you for the clear and accurate answer.

I was looking a quick way to do "The quick brown fox jumps over the lazy dog. " style sheets; looks like I'll need to try something else.
