### ISSUE TITLE
Can only embolden in a square formation

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3460]
Can only embolden in a square formation (for example, 2 units horizontally and vertically). But, if you want to make aesthetic variations of the font like changing width, then the font would have an imbalanced weight. But, it's only possible to embolden in a square formation, but that would require rectangle formation (such as 6 units horizontally and 0 units vertically). But there's only one input, so it's only possible to embolden in a square formation. Fix this GUI issue.

**Comment by skef** [comment]
"Change glyph" provides a more flexible set of options.

**Comment by PiotrGrochowski** [comment]
I don't know how to use it without causing weird glitches. In "Embolden" I would use "CJK, Squish" and allow thickening or thinnening without causing glitches.

**Comment by skef** [comment]
What are one or two examples of "weird glitches"?

**Comment by PiotrGrochowski** [comment]
https://www.dropbox.com/s/9t6xpvzq9scx35b/2019_02_10_07_48_50_1364x768.avi?dl=0
It demonstrates Microsoft Paint thinnening horizontally perfectly fine, but "Change Glyph" causing glitches. "Embolden" has a glitchless configuration in form of "CJK, Squish" so why not "Change Glyph"?

**Comment by skef** [comment]
If wishes were horses ...

**Comment by frank-trampe** [comment]
@PiotrGrochowski, unfortunately, doing this right would be non-trivial, and there is such a backlog of high priority work that we would almost certainly never get to this. We would be happy to accept a pull request if you're willing to write a patch, though.

**Comment by skef** [comment]
He was banned as a spammer/troll a while back.

**Comment by frank-trampe** [comment]
Oh. I missed that. Where?

**Comment by skef** [comment]
I think the actual comment may have been deleted -- I'm not sure. @jtanx noted it in #3486

**Comment by yg8ijvjvjv** [comment]
Expand Stroke was the answer
