### ISSUE TITLE
Sometimes shows character descriptions when window not in focus

### ISSUE THREAD

**Issue by PiotrGrochowski** [fontforge/fontforge#3466]
This is in Microsoft Windows, don't know whether it occurs in Mac OS or Linux. Sometimes shows character descriptions when window not in focus

**Comment by ctrlcctrlv** [comment]
I've noticed this before in Windows, I assume it's a bug in VcXsrv. I've never seen it happen in Linux.

**Comment by jtanx** [comment]
Yep, this is known, it's a VcXsrv bug. Problem goes away when using gdk.

**Comment by PiotrGrochowski** [comment]
You must mean gdi, because gdi is the rendering engine of Microsoft Windows. The thing is, it must be difficult to port that vCxSrv thing to gdi.

**Comment by jtanx** [comment]
No, I know what [I'm talking about](https://en.wikipedia.org/wiki/GDK)

**Comment by PiotrGrochowski** [comment]
It would be better to port it to gdi. It's the rendering engine of Microsoft Windows. Look at how amazing applications like Notepad and Microsoft Paint (XP version) look as they use gdi. Gdi automatically adapts to the High Contrast™ theme set in Microsoft Windows. Non-antialiased text looks much better with gdi because it always uses 2D hinting when not in ClearType mode. Look how bad the generated bitmaps are with any setting in FontForge right now!

**Comment by ctrlcctrlv** [comment]
@PiotrGrochowski Is this a joke? I really can't tell. You are woefully uninformed about FontForge's internals. You're debating with the guy who is the entire reason you even have a somewhat working and updated FontForge build for Windows to complain about.

**Comment by PiotrGrochowski** [comment]
> 
> 
> @PiotrGrochowski Is this a joke? I really can't tell. You are woefully uninformed about FontForge's internals. You're debating with the guy who is the entire reason you even have a somewhat working and updated FontForge build for Windows to complain about.

You'll probably be banned
