### ISSUE TITLE
Cursive Attachment(curs) feature don't works precisely in the metric view

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3470]
I need cursive attachment for a cursive script that I'm designing. In order to achieving this feature for my font I have created a GPOS table with Cursive Position type and Cursive Attachment(curs) feature. Cursive Attachment(curs) feature after generation works correctly and each glyph attach to each other precisely, also in the metric view Cursive Attachment(curs) feature works, but don't work precisely.

**Comment by ctrlcctrlv** [comment]
Us having screenshots and SFD files are essential to helping you.

**Comment by AlirezaAlipour** [comment]
Thank you very much for your help

[Cursive_Feature_test.zip](https://github.com/fontforge/fontforge/files/2855605/Cursive_Feature_test.zip)

**Comment by ctrlcctrlv** [comment]
The `curs` feature isn't selected. Hold down Shift and choose `curs` from the pane on the left in the Metrics view to add it to the enabled OT features.

**Comment by AlirezaAlipour** [comment]
> The `curs` feature isn't selected. Hold down Shift and choose `curs` from the pane on the left in the Metrics view to add it to the enabled OT features.

Thank you very for your assistance

If you look at left sidebar, there is Required Feature(RQD) feature, I added "RQD" feature in addition to Cursive Attachment(curs) feature to my lookup table because "curs" feature is not selected by default and with using "RQD" feature, it make my lookup table be applied, I also can select it using the Contextual Chaining Position.

**Comment by ctrlcctrlv** [comment]
Could it be that FontForge only shows the `curs` feature in Metrics for Urdu? I see Urdu mentioned in the manual. Or is it never showed? Do you know of a font that for sure has `curs` working in applications? Try opening it in FontForge.

**Comment by AlirezaAlipour** [comment]
> Could it be that FontForge only shows the `curs` feature in Metrics for Urdu? I see Urdu mentioned in the manual. Or is it never showed? Do you know of a font that for sure has `curs` working in applications? Try opening it in FontForge.

It works, but not precisely.

**Comment by ctrlcctrlv** [comment]
I know this doesn't solve the specific possible issue in FontForge in general, but from my understanding, you don't even need `curs` for Western-style cursive; `kern` and `calt` are sufficient. What makes `curs` special is that it's similar to `mark`, you can move the y positions of letters as well as the x.

**Comment by ctrlcctrlv** [comment]
>It works, but not precisely.

I also do see this sir, very interesting. If I disable `RQD` I see the characters move, but I see the correct positions in the anchor view. 

I have _confirmed_ this bug, and furthermore I believe that not only `curs` is affected, but all anchors. I believe issues #3324 and #3035 have the same cause as yours.

**Comment by AlirezaAlipour** [comment]
> > It works, but not precisely.
> 
> I also do see this sir, very interesting. If I disable `RQD` I see the characters move, but I see the correct positions in the anchor view.
> 
> I have _confirmed_ this bug, and furthermore I believe that not only `curs` is affected, but all anchors. I believe issues #3324 and #3035 have the same cause as yours.

Thank you very much for your assistance, I wish you a nice day.

**Comment by skef** [comment]
I think I have a handle on this. 

`fontforgeexe/metricsview.c` generally keeps `pixelsize` and `ptsize` when the DPI is 72 (and maintains a corresponding ratio when it differs from 72). It also makes use of a corresponding scale factor of `iscale*mv->pixelsize/(double) (mv->sf->ascent+mv->sf->descent)` where `iscale` is 1 when the scale is set by window height. In the sample font this will be .6 when `pixelsize` is 300. `scale` is used to scale from "SFD measurements" to output measurements. 

Some of the most important measurements are combined in `MVRefreshMetric`:
```
    int x = 10; int y = 10;
    for ( int i=0; i<cnt; ++i ) {
        MVRefreshValues(mv,i);
        SplineChar * sc = mv->glyphs[i].sc;
        BDFChar * bdfc = mv->bdf!=NULL ? mv->bdf->glyphs[sc->orig_pos] : BDFPieceMealCheck(mv->show,sc->orig_pos);
        mv->perchar[i].dwidth = rint(iscale * bdfc->width);
        mv->perchar[i].dx = x;
        mv->perchar[i].xoff = rint(iscale * mv->glyphs[i].vr.xoff);
        mv->perchar[i].yoff = rint(iscale * mv->glyphs[i].vr.yoff);
        mv->perchar[i].kernafter = rint(iscale * mv->glyphs[i].vr.h_adv_off);
        x += mv->perchar[i].dwidth + mv->perchar[i].kernafter;
        mv->perchar[i].dheight = rint(sc->vwidth*scale);
        mv->perchar[i].dy = y;
        if ( mv->vertical ) {
            mv->perchar[i].kernafter = rint( iscale * mv->glyphs[i].vr.v_adv_off);
            y += mv->perchar[i].dheight + mv->perchar[i].kernafter;
        }
    }
```
This code mixes measures generated elsewhere (such as `mv->glyphs[i].vr` from the lookup tables) and measures from the character returned by `BDFPieceMealCheck()`. That function generates values based on those set at the BDF font level, where in this case the font is `mv->show`. 

`mv->show`, in turn, is regenerated in a number of places, with code similar to this:
```
    mv->show = SplineFontPieceMeal(mv->sf, mv->layer, mv->ptsize, mv->dpi,
                                   MVGetSplineFontPieceMealFlags( mv ), NULL);
```
Usually mv->ptsize is passed but at least once it is mv->pixelsize, which may be an error but will only matter for DPIs other than 72. 

In any case, the overall system only works if the metrics produced by `BDFPieceMealCheck()`, and therefore determined by `SplineFontPieceMeal()`, match those generated elsewhere in `metricsview.c`. 

Unfortunately that's not true as of 4a6155aeb2d8ce381f417844efac5afcf63e4bff. That commit winds up setting a slightly different internal `ptsize`, which breaks the measure calculations. I have confirmed that reversing that commit in my test code yields the correct result in the metrics window for the test font. 

@khaledhosny, you're in the best position to point towards a resolution. What would be the general impact of reversing the commit? How might we refactor to avoid the metrics problem while solving whatever problem that change addressed?

**Comment by khaledhosny** [comment]
Feel free to reverse the commit, it was an aesthetic fix for font view with some fonts, I don’t remember the exact details.

**Comment by skef** [comment]
OK, I'll try the result on the related problems and see how it goes.
