### ISSUE TITLE
Installing FontForge on new distributions of Ubuntu

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3474]
I want to install FontForge from source code and base on [INSTALL-git.md](https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md) for Ubuntu I need to install `giflib-dbg` , but this package doesn't exist in new distributions of Ubuntu, for example for my current distribution (i.e Cosmic). Is `giflib-dbg` required? If it is required, what should I do?

**Comment by jtanx** [comment]
No, it's not required. The dependencies installed in [.travis.yml](https://github.com/fontforge/fontforge/blob/master/.travis.yml) is a reasonable indicator for what to install.

**Comment by AlirezaAlipour** [comment]
> No, it's not required. The dependencies installed in [.travis.yml](https://github.com/fontforge/fontforge/blob/master/.travis.yml) is a reasonable indicator for what to install.

Thank you very much for your assistance.

**Comment by AlirezaAlipour** [comment]
Now my problem is, in the stage of `make` I have faced with an error that you can seen in attached screenshot.
![screenshot from 2019-02-14 14-41-34](https://user-images.githubusercontent.com/14098141/52783399-07139780-3067-11e9-9b08-0c0a985d8122.png)

**Comment by jtanx** [comment]
It must have built libgunicode earlier, what do the logs say about that. Or else try a clean build again (`git clean -dxf`)?  Sounds like some sortof bad state

**Comment by AlirezaAlipour** [comment]
> It must have built libgunicode earlier, what do the logs say about that. Or else try a clean build again (`git clean -dxf`)? Sounds like some sortof bad state

I had created a directory name "Installation Workplace" and because of space in the directory name I had faced with mentioned problem, after replacing space with underscore, the problem has been solved.

Thank you very much, have a nice day.
