### ISSUE TITLE
Attempting to add an anchor results in infinite "Anchor Class Name" windows

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3482]
### When reporting a bug/issue:
- [x] Screenshot
![bug](https://user-images.githubusercontent.com/838783/53088574-1ef68a00-3545-11e9-8e38-5c3b8e879839.jpg)

- [x] The FontForge version and the operating system you're using
Arch Linux x64, https://github.com/fontforge/fontforge/commit/6abdba08e52d9431fcc49936c4e1127ac542d225
- [x] The behavior you expect to see, and the actual behavior
I expect a mark class to be added after I enter the name of it and press OK / enter key on keyboard.
- [x] Steps to reproduce the behavior 
* Open [N~.sfd](https://github.com/fontforge/fontforge/files/2884400/N.zip) ; or make your own new font without a `mark` OT feature
* Open tilde character view
* Right click, add anchor
* Attempt to enter anchor name
* Bug occurs

- [x] \(optional) Possible solution/fix/workaround
Create a `mark` feature in GPOS and add some classes before trying to add an anchor. Very non-obvious for users that you need to do this, or that it will even work.

**Comment by khaledhosny** [comment]
The bug happens when one presses Enter, pressing the OK button will work fine. Similar thing happens with the Anchor Point Info dialog, pressing enter there will open a new dialog, attempting to close them will crash FontForge.

But, I think you need to create a mark or mkmk lookup first, add anchor classes, then add anchors to the glyphs. Adding anchors without lookups will not end up in the compiled font.

**Comment by skef** [comment]
This fixes the problem and is at least roughly right but it's hard to evaluate the scope of potential side effects. (At worst (I *think*) menu acceleration for popup menus could be missing in some contexts, as that's what `GMenuPopupCheckKey(event)` is responsible for.)

```
diff --git a/gdraw/gcontainer.c b/gdraw/gcontainer.c
index da1c88ba2..9f6f3d012 100644
--- a/gdraw/gcontainer.c
+++ b/gdraw/gcontainer.c
@@ -496,7 +496,8 @@ static int _GWidget_TopLevel_Key(GWindow top, GWindow ew, GEvent *event) {
     }
     /* Check for mnemonics and shortcuts */
     if ( event->type == et_char && !GKeysymIsModifier(event->u.chr.keysym) ) {
-       handled = GMenuPopupCheckKey(event);
+       if ( topd->popupowner != NULL )
+           handled = GMenuPopupCheckKey(event);
        if ( topd->ispalette ) {
            if ( !(handled = GMenuBarCheckKey(top,topd->owner->gmenubar,event)) )
                handled = GWidgetCheckMn((GContainerD *) topd->owner,event);
```

**Comment by skef** [comment]
It seems like what is now done by `GMenuPopupCheckKey()` calling `gmenu_key()` should actually be done by the call to `(topd->popupowner->funcs->handle_key)(topd->popupowner,event)` shortly after in `_GWidget_TopLevel_Key()`. But the latter is usually set to `TN_PassChar()` which calls `GFI_Char()` and therefore appears to handle only Help, Save, Quit, and Close. Maybe the author didn't remember that option when implementing 6480bae10c7c4f554ebac0c7dd6592c60b081a50?

**Comment by skef** [comment]
I fixed this crap; probably correctly (the second time).
