### ISSUE TITLE
GDK modality changes

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3498]
This is (probably?) not a bug report, but a question. I guess the dev list would be a better place for this officially, but "coverage" there seems spotty.

gxdraw implements the familiar sort of application-wide modal window. The "trick" is more or less i the `inputRedirect` stuff in `GXDrawSetVisible()` and the other functions that deal with `gdisp->input`. 

At present ggdkdraw implements a "lighter" version of modality by way of `_GGDKDraw_FilterByModal()`. This more or less checks for windows in the chain from that receiving the event up to the root, and throws away events if any of those have a modal dialog (which, being a separate window, isn't in the chain). 

This is "lighter" because you can use other windows at the same time. For example, in gxdraw if you have a modal "Add Lookup" dialog open on top of the Font Info -> Lookups window, you have to close it before doing anything else with the application. In ggdkdraw you can use the Font and CharViews at the same time -- only the Font Info window is blocked. 

Considered in isolation as a UI semantic, I'm not really "bothered" by this or that worried that users may find it confusing. (So this is different from the Point Info dialog concerns I raised in another recent issue.) But I am worried in a program-correctness sense. Dialogs are often modal for a reason, with the code relying on nothing else changing for its lifetime. 

So: do we *know* this *isn't* a problem, or did the implementation just "wind up" this way? 

I take it @jtanx is the expert on this subject.

**Comment by jtanx** [comment]
The implementation wound up that way; it is actually a 'bug' in the sense of not matching gxdraw. I actually noted that when looking at #3437.

I actually had a branch to try to 'fix' this (https://github.com/fontforge/fontforge/tree/gdk-transients/gdraw), but never got around to finishing it (I think it works...)

imo what gxdraw is doing on this is somewhat insane, it's making completely unrelated windows (in terms of hierarchy) modal. Otherwise, you'd be able to get away with just setting the modal hint and letting the WM do the rest. But that's the way it goes...

**Comment by skef** [comment]
I would probably say "conservative" rather than "somewhat insane". Just freezing the window hierarchy isn't always going to be a safe semantic; a modal window on a CharView won't block that on another CharView displaying the same character (which I believe FontForge let's you do). 

Modern widget libraries typically supply enough rope by way of [window groups](https://developer.gnome.org/gtk3/stable/GtkWindowGroup.html). 

I ran into this looking at some gtk extension possibilities. It's actually quite straightforward to support GTK windows (assuming no mixing in a single window) in the GDK-based code. Once you hook up the events (and avoid running your own main loop, which seems to be discouraged in GTK now anyway), it mostly just works. But inter-system modality is one of the "doesn't just work" features, so supporting that (a good thing) would require sorting out what should be modal in relation to what.
