### ISSUE TITLE
Python's merge point method in contour class causes app crash

### ISSUE THREAD

**Issue by tisimst** [fontforge/fontforge#3501]
The "merge" function in the contour class of the python library crashes regardless of the node position given.

Example to repeat the crash, trying to merge the top extreme on-curve node at (400, 800):

import fontforge
cntr = fontforge.contour()
cntr.moveTo(0, 0)
cntr.cubicTo(0, 400, 200, 800, 400, 800)
cntr.cubicTo(600, 800, 800, 400, 800, 0)
cntr.merge(3)

OS: Windows 8.1 and 10
FF version: 31-Jul-2017
git hash: 8b6e7f07a5511e4de9c8a710db6ca8e770de8f7e

**Comment by skef** [comment]
Are you in a position to compile and test with https://github.com/skef/fontforge branch bg3501 ? If you can, verifying that merge at the contour level and using the UI has the same result.

**Comment by tisimst** [comment]
I haven't compiled FF before on any platform, though I'm not afraid to try if it comes to that.

**Comment by skef** [comment]
Well, some admittedly simple testing suggests that the fix does allow the underlying merge code to do its thing. it will likely make the next release, whenever that winds up being.

**Comment by tisimst** [comment]
That's great news! I can be patient. I have a couple of plugins I'd like to use the merge function in, but I'll pretend it's working for now ;-) Thanks for addressing it so quickly!

**Comment by tisimst** [comment]
By the way, I was looking at the "how to compile from source" documentation and it didn't say anything about how to do this on Windows. Or maybe I just missed it...

**Comment by skef** [comment]
There's some ongoing discussion about that in #3499

**Comment by skef** [comment]
< 24 hour turn-around! If you don't count the *\*cough\** release latency.

**Comment by jtanx** [comment]
:P, just use https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts

**Comment by skef** [comment]
@tisimst: That's a good point! You can grab the binary built off this merge from that directory and give it a shot.

**Comment by tisimst** [comment]
@jtanx Ooooooh! I like that! I can confirm the command works just like in the UI now. Thank you so much!

**Comment by tisimst** [comment]
How cautious should I be in using this "unofficial" build for daily work?

**Comment by skef** [comment]
The general quality level is probably higher in the current master than in the 2017 release. As always the highest risk comes with relatively new, large features, which in this case is mostly the GDK layer. However, that code is also in routine use by a number of people and seems quite stable.

**Comment by tisimst** [comment]
I'm struggling to get the appveyor build to see my python files. It doesn't seem to be looking in the usual place, if it's looking anywhere. Can someone confirm where this dev build might find scripts to load at startup?

**Comment by skef** [comment]
Try `\Users\???\AppData\FontForge\python` and see if that works (filling in your Windows username)

**Comment by jtanx** [comment]
@tisimst the appveyor builds are portable builds, controlled by

```bat
set FF_PORTABLE=TRUE
```

in `FontForge.bat`.

In that case, it relies solely on everything in the bundle, so python scripts are loaded from `lib\python2.7\site-packages` relative to where your bundle is, instead of from `C:\Program Files (x86)\FontForgeBuilds\lib\python2.7\site-packages`

**Comment by skef** [comment]
I assumed by "load at startup" @tisimst was referring to "init scripts", and therefore the things loaded by `PyFF_ProcessInitFiles()` based on the output of `default_pyinit_dirs()`. (Just putting a script in site-packages won't give you a menu item, for example.) 

However, if `FF_PORTABLE` is true then my advice won't work either. `getFontForgeShareDir()` is going to (probably?) wind up calling `PrefsUI_getFontForgeShareDir()`. If `__MINGW32__` is in effect that will return `GResourceProgramDir` + `/share/fontforge`, to which `default_pyinit_dirs()` will first try to add `python2` and then `python`. 

Based on what you're saying, I believe the `getFontForgeUserDir()` path will wind up looking in `__install_dir__\share\fontforge\preferences\python2` and failing that `__install_dir__\share\fontforge\preferences\python`. So for menu items I would try the latter and see if that works.

**Comment by tisimst** [comment]
Interesting... I'll have to do some playing around because even if I put my library files in there, the script that loads my custom plugins when FF boots doesn't seem to be found, either when I use `run_fontforge.exe` or via the batch script `fontforge.bat`.

For my "normal" installation, I have placed my `fftools` library code, which includes all the menu registration calls, in:

`C:\Program Files (x86)\FontForgeBuilds\lib\python2.7\site-packages`

and another file (`loadfftools.py`)  to initiate the registrations during app startup in:

`C:\Users\_username\AppData\Roaming\FontForge\python\`

**Comment by skef** [comment]
Right -- try putting the the latter in 

`C:\Program Files (x86)\FontForgeBuilds\share\fontforge\preferences\python`

I know that doesn't make a lot of sense, but that's where gutils/fsys.c line 940 is pointing.

**Comment by tisimst** [comment]
Now we're talking! I got it working in portable mode by placing the launch file in

`[FF]\share\fontforge\preferences\python`

Thanks so much! That is going to be extremely helpful.

**Comment by tisimst** [comment]
I've run into an issue with the above appveyor-built version. I'm now getting occasional crashes in my scripts when I didn't before. The crash log points to the following:

- Fault Module Name: libintl-8.dll
- Fault Module Version: 0.19.8.0
- Exception Code: c0000005
- Exception Offset: 0000a2f3

Even when I copy the same-named file from the normally installed, but older, version of FF into the `bin` folder for this one, the crash still happens and it didn't use to. Should I open a new issue for this? 

Unfortunately the script is somewhat long, but it appears to be happening after I've done this line of code (and, yes, the script uses the following `askForString` and `log` commands several times before this occurs):

```python
ytranslate = 0
ytranslate = askForString('Amount to move the glyph up (if any)?', default=str(ytranslate))
log('here')
```
When my script gets to this snippet, "here" never reaches FF's warning dialog box before the app crashes.

As background, I created wrappers around the input dialog and the print-to-warning-box internal commands to simplify the interface for myself:

```python
def log(*args):
    msg = ('%s'*len(args))%(args)
    fontforge.logWarning(msg)

def askForString(question, title="Question", default="well?"):
    return fontforge.askString(title, question, default)
```

As I mentioned above, I use these two commands all the time, even several times in the same script, so I'm a bit at a loss, but grateful for any insights anyone might have. I can certainly revert to using the standard distribution of FF until this gets resolved. Thanks for your help!

**Comment by skef** [comment]
A little chatting about infrastructure is OK in closed bugs, but this is an entirely new issue, so open a new "issue".

**Comment by skef** [comment]
And when you do, if you can, attach a (probably zipped, to make github happy) version of your script that reliably causes the crash, and instructions on how to trigger it. It doesn't matter how long the script is for this purpose. 

First guess is that this is c-api reference-count related. Second guess would be something with GDK, just because that's the other area that's changed a lot.

**Comment by tisimst** [comment]
Sounds good. I'll see if I can minimize the script to only include code related to the issue and start a new one.

**Comment by tisimst** [comment]
As an aside, can someone explain how to use the debugging symbols? I'm not familiar with how they work.

**Comment by skef** [comment]
I'm not sure what you mean by "use". When you compile with debugging enabled and either run the program under a debugger (like gdb) or open a core file, the debugger is able to much more helpful about linking the program operations to lines in the source files. When the source is in the same location as it was when the program was compiled, this often "just works"; if it's different you might have to point the debugger at the source.

**Comment by tisimst** [comment]
Well, that's me not knowing what I'm talking about (he he). I thought the file from appveyor that had some files with "debugging symbols" was some kind of file set the main app could utilize for better debugging, but I'm obviously ignorant. Never mind the noise.

**Comment by tisimst** [comment]
I discovered what the issue was, causing libintl-8.dll to crash. I was accidentally doing something like this:

```python
bbox = glyph.foreground.boundingBox()
fontforge.logWarning('%s'%bbox)
```

I *thought* I was supplying a single value to the string formatter, but since `bbox` *is* a tuple of values, the formatter crashed since it expected only a single value. So, refactoring the code to this fixed it:

```python
fontforge.logWarning('%s'%(bbox,))
```

since this only supplies a single value to the string formatter. This has happened numerous times and is nearly impossible to debug. Debugging any python script running in FontForge is generally a nightmare since it either crashes without warning, or supplies no useful traceback at all. I wrote a debugging wrapper that helps most of the time, but even it doesn't catch everything somehow. Anyway, case closed. Thanks, again, for the new app. Everything seems to be working wonderfully. I especially like the recent change to use GDK instead of X for the GUI.

**Comment by skef** [comment]
> Debugging any python script running in FontForge is generally a nightmare since it either crashes without warning, or supplies no useful traceback at all.

Because the FontForge python implementation is almost all behind the C-API, the bugs tend to show up as crashes rather than exceptions. So debugging with `gdb` tends to get to the problem quicker than trying to use python-level tools.

**Comment by skef** [comment]
I've just tried this on a normalish Linux build with python 3 and I get a warning that not all the formatting arguments were used rather than crash. So I guess the Windows build is more sensitive to this particular kind of problem.
