### ISSUE TITLE
Python library Tkinter fails to load

### ISSUE THREAD

**Issue by tisimst** [fontforge/fontforge#3504]
OS: Windows 8.1 and 10
FF version: 31-Jul-2017
git hash: 8b6e7f07a5511e4de9c8a710db6ca8e770de8f7e

Problem:
I can see in the lib > python2.7 > lib-tk folder there are tkinter-related files, but when I try even just
```python
import Tkinter
```
I get this error (from Tkinter.py, line 39):
```python
ImportError: DLL load failed: The specified module could not be found.
```
I've brought this up on the user & dev emails before, but it sure would be awesome to be able to create more advanced GUI widgets than the simple ones exposed through the python API. At the moment, I have to open multiple dialog input windows and it would really help to be able to input multiple values in the same window. I bypass this for the moment by comma-separating the values. It works fine, but not ideal.

**Comment by skef** [comment]
I would be surprised if this worked even when the library loaded. For it to work Tkinter would somehow need to keep itself separate from FontForge's own graphics layer. And then there would still be many event complications. 

If you want to pursue a tkinter solution you would probably be much better off putting RPyC in between. That way your graphics could be in a separate "application" from Fontforge but still control it through the python interface. And that would presumably work using the "system" python with Tkinter and the msys2 python with FontForge. 

I'm actually screwing around with a solution to this problem, but with gtk rather than Tkinter. The gdk layer makes the combination fairly viable. But I don't know if and when anything will come of that.

**Comment by jtanx** [comment]
I can sort of see tk being useful if you're just writing your own mini-ui to automate some tasks. As for why it doesn't work, we're not bundling the tcl/tk dlls by default - it will load once tcl86.dll/tk86.dll are copied from /mingw32/bin into FontForge's bin folder.

**Comment by tisimst** [comment]
Gotcha. I'm not partial to tk, honestly. I'd rather use other toolkits, but it seemed to be the easiest to support, which I could be greatly mistaken. 

Then how about this alternative. On Linux, FF's python API is exposed to the system-level python application. I've tried to figure out how to do this on Windows without success. If I could do the same there, where I can 
```python
import fontforge
```
in the regular python app, then that would be even better because I could then take advantage of other system-level installed python packages such as numpy, scipy, etc. I would gladly take this over getting tk to work.

**Comment by skef** [comment]
@tisimst: I really think in this case the kludge is the way to go. Try getting RPyC installed on the FontForge size (it's pure python) and the system python side. Start a "classic mode" server on the python side (you could trigger the start with a menu item or just from the startup script. Then control it with a client on the system python.

**Comment by skef** [comment]
Or, alternatively, go through the process of getting a full msys2 python setup, with the libraries you want. That should enable "import fontforge" in that python, assuming the paths are set up properly. (I'm assuming this will work from things I've read on the mailing list -- I haven't personally tried it or done much with windows recently.)

**Comment by tisimst** [comment]
I'll have to try some things. In the meantime, I can manage with what's currently available. Thanks for the help!

**Comment by skef** [comment]
I take this issue as standing in for "support python graphics library X that isn't GTK". GTK is something that *could* be supported in conjunction with the GGDKDraw. Anything else almost certainly wouldn't be at all compatible with (non-X-based) GGDKDraw and getting it to work with X would involve kludges like the old GTK layer used for Contrib, which "fell apart" quickly. 

The issue isn't getting the library to load, it's how the main loop is supposed to work and get passed events. Anyone who wants to do use such a thing would likely be better served by a separate application that uses RPC to execute FontForge python commands -- hence my RPyC recommendation. The difficulties of RPC are only picky. 

I doubt that any integrated solution for another graphics library is sustainable.
