### ISSUE TITLE
Is any method to change size of a glyph base on context?

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3507]
I want to know that there is any method that I can use to change size of an glyph or group of glyphs? for example number before fraction slash is smaller and have different position.

**Comment by skef** [comment]
OpenType supports both pairwise and more complex contextual substitution. Most OpenType features (each of which has a four-letter name) are intended for specific purposes, but there are 30 "Stylistic sets" (ss01..ss30) that are free for custom purposes. 

The substitution interface gets "arbitrarily complicated", and parts are considered by many to be a dark art. FontForge's documentation is [here](https://fontforge.github.io/editexample6-5.html).

**Comment by AlirezaAlipour** [comment]
> OpenType supports both pairwise and more complex contextual substitution. Most OpenType features (each of which has a four-letter name) are intended for specific purposes, but there are 30 "Stylistic sets" (ss01..ss30) that are free for custom purposes.
> 
> The substitution interface gets "arbitrarily complicated", and parts are considered by many to be a dark art. FontForge's documentation is [here](https://fontforge.github.io/editexample6-5.html).

Thank you very much for your comment.

**Comment by ctrlcctrlv** [comment]
Minor niggle: There are actually only 20 stylistic sets.

**Comment by ctrlcctrlv** [comment]
> The substitution interface gets "arbitrarily complicated", and parts are considered by many to be a dark art.

This is definitely true. I always stress to new users: *do not bother trying to figure out FontForge's substitution GUI.* Many hours have been lost in the doing of such, and there is little to be gained by using it. 

Instead, create a feature file for your font and merge it right before generating OTF, but never save the SFD with the feature file merged so you can change the features. This is the process I use to build my font [KJV1611](https://github.com/ctrlcctrlv/kjv1611).

**Comment by skef** [comment]
Here is a handy-dandy script to allow a feature file to be authoritative for GSUB info. I prefer a model where the file is the master version but you can still test substitution in the metrics window and so forth. 
```
#!/usr/bin/env python

# load OpenType features 
# (c) 2018 Skef
#
# usage: load-features.py [-e | -f f.fea] -o out.sfd in.sfd

import argparse
import sys
import os
import re
import fontforge

parser = argparse.ArgumentParser(
        description="reload_features.py: Reinit contents of a FontForge OpenType feature from a feature file")
parser.add_argument('-f', '--ffile', metavar='(feature_file)')
parser.add_argument('-o', '--output', metavar='(output_file)', required=True)
parser.add_argument('-e', '--empty', action='store_true', help='Remove GSUB entries without replacing')
parser.add_argument('input_file')

args = parser.parse_args()

if not os.path.exists(args.input_file):
    sys.stderr.write("Error: Input file '" + args.input_file + "' not found")
    sys.exit(2)

if args.ffile and args.empty:
    sys.stderr.write("Error: arguments --empty and --ffile are not compatible")

if args.ffile and not os.path.exists(args.ffile):
    sys.stderr.write("Error: Feature file '" + args.ffile + "' not found")
    sys.exit(2)

def empty_gsub(ff):
    for gsublname in ff.gsub_lookups:
        ff.removeLookup(gsublname)

def merge_features(ff, feaname):
    ff.mergeFeature(feaname);

ff = fontforge.open(args.input_file)
empty_gsub(ff)
if args.ffile:
    merge_features(ff, args.ffile)
ff.save(args.output)
```

However, while FontForge's interface can make things more complicated, the underlying OpenType substitution system is also arbitrarily complicated at the limits. Some of the contextual stuff is difficult to develop any intuitions for.

**Comment by khaledhosny** [comment]
I find FontForge OpenType UI much more intuitive than feature files, but feature files are much faster to edit and allow greater flexibility in reusing bits and pieces.

**Comment by AlirezaAlipour** [comment]
> I find FontForge OpenType UI much more intuitive than feature files, but feature files are much faster to edit and allow greater flexibility in reusing bits and pieces.

Base on [this resource](https://docs.microsoft.com/en-us/typography/opentype/spec/otff) OpenType is either comprises TrueType or CCF outline font.

Now I'm facing with following confusion:

- When we use FontForge to editing GSUB or GPOS, Are GSUB or GPOS considered TrueType or OpenType Tables?

- Is it posible to generate OpenType with ''.ttf" extension? base on [this resource](https://docs.microsoft.com/en-us/typography/opentype/spec/otff) OpenType can have ''.ttf" extension.

**Comment by skef** [comment]
My (admittedly amateur) understanding: 

1. That comment about TrueType or CCF is limited to the data for the actual outlines -- the geometry of the individual glyphs. 
2. The TrueType spec includes a convention for adding tables identified by four-character strings. Some specific tables are also part of that spec and some are not. In effect, you can add a new table to a TrueType font and a TrueType implementation will likely ignore it.
3. While this is an oversimplification, OpenType is mostly defined as an extension to TrueType. Most of the OpenType spec that is over-and-above the TrueType spec consists of tables that follow the TrueType *convention* with names and contents that are not part of the TrueType *spec*. 

Because OpenType mostly extends TrueType, a typical TrueType implementation can use the TrueType parts and ignore the OpenType-specific parts. What a given implementation does with an OpenType font given a `.ttf` extension may differ -- some may realize it's an OpenType font and treat it that way while others may ignore GSUB and GPOS.

**Comment by khaledhosny** [comment]
For simplicity, OpenType is a superset of TrueType so any valid TrueType font is also an OpenType font (but not the other way around). OpenType fonts can either have quadratic outlines (`glyf`/`loca` tables) like TrueType fonts and this usually uses `.ttf` extension, or cubic outlines (`CFF` table) and this typical uses `.otf` extension but `.ttf` is also valid.

So to answer the questions:
1. `GSUB` and `GPOS` are OpenType tables.
2. OpenType fonts can have `.ttf` extension (but be warned that, if your font uses cubic splines then FontForge will convert them to quadratic splines, and this conversion is both lossy and can increase the font size or degrade some of your glyphs).

**Comment by AlirezaAlipour** [comment]
How we can enable joining

> For simplicity, OpenType is a superset of TrueType so any valid TrueType font is also an OpenType font (but not the other way around). OpenType fonts can either have quadratic outlines (`glyf`/`loca` tables) like TrueType fonts and this usually uses `.ttf` extension, or cubic outlines (`CFF` table) and this typical uses `.otf` extension but `.ttf` is also valid.
> 
> So to answer the questions:
> 
> 1. `GSUB` and `GPOS` are OpenType tables.
> 2. OpenType fonts can have `.ttf` extension (but be warned that, if your font uses cubic splines then FontForge will convert them to quadratic splines, and this conversion is both lossy and can increase the font size or degrade some of your glyphs).

As you know when we want to generate font in FontForge, in the first dropdwon, OpenType variations and TrueType varitions are seperated, but when we select "TrueType" the "OpenType" will be sellected in the Options section, so It is not TrueType__ the font that will be generated will not be only TrueType __, insted it is OpenType. Does not FontForge need changes to solving this confusion?

**Comment by skef** [comment]
When one software system is based on another, it often picks and chooses the aspect of the "base" system that it supports. With TrueType and OpenType and some careful planning, it's often possible to make a single file that works well as a TrueType font and also as an OpenType font. But it isn't always possible and isn't always desirable becomes of various compromises, like the spline format issue @khaledhosny mentions.

**Comment by khaledhosny** [comment]
The UI is confusing indeed, what FontForge usually mean by TrueType is OpenType with quadratic splines (the Options dialog in Export dialog actually controls whether to output OpenType tables or not).

**Comment by AlirezaAlipour** [comment]
So for this issue can I inference that there is not any way to change size of a set of glyphs__ increase or decrese by an constant number __ base on context?

**Comment by skef** [comment]
No, with OpenType this is possible. Typically one would include the glyphs-of-a-different size as unencoded (Unicode = -1), probably made using references to the original glyphs if it's only a scale change. Then one would include GSUB contextual substitutions to swap in the unencoded glyphs. The feature one would use would depend on the motivation for the swapping. This is the way the `sinf` feature typically works (for example).

**Comment by AlirezaAlipour** [comment]
For more informatino, [this](https://helpx.adobe.com/fonts/using/open-type-syntax.html#frac) is a greate resource for fraction and other features.


Thank y'all for your assistanc, I wish y'all a nice day.
