### ISSUE TITLE
How to implement final form feature in Latin?

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3508]
There is a feature name "fina" that we can use it to substitute glyphs with another glyphs when they are final form. Final form is critical for language like Arabic and Persian, for example my name in Persian(my first language) is as follow:
"علیرضا علیپور" 

The letter "ا" in final form__ the last glyph from left to right in "علیرضا" __have different shape in order to attach to "علیرض".

Now I'm working on a Latin type that I need to design quotation mark, as you know one form of quotation marks has different shape before and after letter, word or sentence, in other word each one is 180 degree counterclockwise of another one, so I need a feature like "fina", with Contextual Chaining Substitution I can't define a rule for situation as follow:

quotation mark + infinite list of glyphs + quotation mark

For finite situation I can define rule as follow:

quotation mark + finite list of glyphs+ quotation mark

So I decided to bring up the problem in this place for suggestions.

**Comment by skef** [comment]
Generally speaking I know that most tools that substitute directed quotes for undirected ones use the presence of whitespace (and potentially certain punctuation, like periods) on one side as the heuristic. 

It's much more common to have some sort of composition tool implement this feature than to do it directly in a font. However, [here](https://cirw.in/blog/smart-quotes) is a link to one person who did this with OpenType, and choose the dlig "discretionary ligature" as the feature.

**Comment by AlirezaAlipour** [comment]
> Generally speaking I know that most tools that substitute directed quotes for undirected ones use the presence of whitespace (and potentially certain punctuation, like periods) on one side as the heuristic.
> 
> It's much more common to have some sort of composition tool implement this feature than to do it directly in a font. However, [here](https://cirw.in/blog/smart-quotes) is a link to one person who did this with OpenType, and choose the dlig "discretionary ligature" as the feature.

Very useful information, Thank you very much.

**Comment by skef** [comment]
I suspect that's as resolved as this issue is likely to get, and thus I'm closing it.

**Comment by AlirezaAlipour** [comment]
How we can set Unicode Joining_Type property value?

**Comment by AlirezaAlipour** [comment]
Please open this issue agin.

**Comment by skef** [comment]
The documentation suggests that Joining_Type is specific to a list of scripts that doesn't include Latin, so that question isn't related to the subject of this issue.

**Comment by AlirezaAlipour** [comment]
I want to know, is it possible to define Joining_Type properties like Dual_Joining for Latin?

**Comment by skef** [comment]
Good lord, man, this is software! Leave the infinite to the theologians; we, on this mortal plain, need only grapple with the *unbounded*. 

That feature is specific to particular scripts: https://www.unicode.org/versions/Unicode11.0.0/ch09.pdf#page=18 Even if you were somehow able to define it, most rendering engines would probably ignore it for `latn`. 

In theory you could do something akin to `frac`, in which you make a copy of every relevant glyph, start a contextual substitution chain at the first quote instance with the alternates, and end the chain at the second occurrence (basically using the alternates to track the context). That seems like a more viable approach than forcing Joining_Type into a Latin-shaped box, which doesn't make it a good idea.

**Comment by AlirezaAlipour** [comment]
> Good lord, man, this is software! Leave the infinite to the theologians; we, on this mortal plain, need only grapple with the _unbounded_.
> 
> That feature is specific to particular scripts: https://www.unicode.org/versions/Unicode11.0.0/ch09.pdf#page=18 Even if you were somehow able to define it, most rendering engines would probably ignore it for `latn`.
> 
> In theory you could do something akin to `frac`, in which you make a copy of every relevant glyph, start a contextual substitution chain at the first quote instance with the alternates, and end the chain at the second occurrence (basically using the alternates to track the context). That seems like a more viable approach than forcing Joining_Type into a Latin-shaped box, which doesn't make it a good idea.

Some time we lose our time because of human tendency to infinite, now despite of having a solution I'm searching to an more perfect solution, Thank you to remember me of my bad attitiude. I have OCD and perfection is one of attitude.

Have a nice day.
