### ISSUE TITLE
Ubuntu 18.04 - cannot run via CLI

### ISSUE THREAD

**Issue by barkdoll** [fontforge/fontforge#3526]
#### Environment information:
- OS: Ubuntu Server 18.04.2 LTS
- FontForge version: 20179731~dfsg-1 (from the Ubuntu universe ppa)

#### The issue
I try to run `fontforge` via CLI and I get the following error:
```
$ fontforge --version
$ fontforge: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func
```

#### Expected behavior
```
Copyright (c) 2000-201X by George Williams. See AUTHORS for Contributors.
  License <type>: ...
  ...
  ...
```

#### Steps to reproduce

1. install fontforge on Ubuntu Server 18.04.2 LTS
1. run `fontforge --version`

#### Other things I confirmed
- I checked list of dependencies against packages I had installed, and I couldn't find anything that I was missing
- `libpangoft2-1.0-0` is indeed installed
- installing `fontforge-nox` instead, the non-X version, results in the same error

**Comment by skef** [comment]
I believe the missing symbol `hb_font_funcs_set_variation_glyph_func` is not being sought in libpangoft2, but a symbol libpangoft2 is seeking, probably from HarfBuzz. 

This is apparently an esoteric installation problem seen in a number of systems in 2018. See https://github.com/cjcliffe/CubicSDR/issues/611

**Comment by barkdoll** [comment]
@skef Thank you for pointing me to [Harfbuzz](https://github.com/harfbuzz/harfuzz). I was able to fix the symbol link by building [the latest Harfbuzz](https://www.freedesktop.org/software/harfbuzz/release/) build from source.

All I did was...
```bash
$ wget https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-2.3.1.tar.bz2
$ tar -xjvf ./harfbuzz-2.3.1.tar.bz2
$ cd ./harfbuzz-2.3.1
$ ./configure
$ make
$ make install
```
and working!

**Comment by skef** [comment]
No problem -- just some googling. Unfortunately there's very little to be done about these ecosystem things as a high-level project.
