### ISSUE TITLE
Metrics Window - glitch in 'type text' field when using cyrillic

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#354]
OSX 10.8.2. fforge 201302 -15_0415/ 

When metrics window is showing cyrillic characters, any Latin entered into the 'text input' box / field is garbled / or falling below baseline (see screenshot). Is this a bug? or maybe it's an issue with the font fontforge is using in it's UI. I have not seen this before. Will also check on gnu/linux.

![Screen Shot 2013-02-15 at 14 46 31](https://f.cloud.github.com/assets/1130355/162588/db0cbafe-77c1-11e2-8cab-ecf3720747fe.png)

**Comment by skef** [comment]
This doesn't reproduce for me at present, closing.
