### ISSUE TITLE
altuni is unreliable

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3551]
Setting the field `altuni` of a `fontforge.font` in Python does not take immediate effect. Resetting the encoding fixes it. I am using Fontforge 20190317 on macOS Mojave 10.14.3 with Python 2.7.15.

The following script creates one glyph and assigns it to two code points.
```python
import os

import fontforge

def draw(cp):
    glyph_name = 'zero'
    if glyph_name in font:
        glyph = font[glyph_name]
        new_altuni = ((cp, -1, 0),)
        if glyph.altuni is None:
            glyph.altuni = new_altuni
        else:
            glyph.altuni += new_altuni
        return glyph
    glyph = font.createChar(cp)
    glyph.right_side_bearing = 200

font = fontforge.font()
font.encoding = 'UnicodeFull'
draw(0x30)
draw(0x31)
#font.encoding = font.encoding
for glyph in font.glyphs():
    print glyph.glyphname, glyph.unicode, glyph.altuni
font.generate('out.otf')
```
And indeed, the output shows that FontForge does associate multiple code points with the glyph.
```
zero 48 ((49, -1, 0),)
```
However, only one of the code points gets the glyph.
```console
$ hb-shape out.otf 01
[zero=0+200|.notdef=1+200]
```
Only one of the font’s 'cmap' subtables is correct.
```console
$ ttx -o /dev/stdout -t cmap out.otf 2>/dev/null
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.26">

  <cmap>
    <tableVersion version="0"/>
    <cmap_format_4 platformID="0" platEncID="3" language="0">
      <map code="0x30" name="zero"/><!-- DIGIT ZERO -->
    </cmap_format_4>
    <cmap_format_0 platformID="1" platEncID="0" language="0">
      <map code="0x0" name="zero"/>
      <map code="0x30" name="zero"/>
      <map code="0x31" name="zero"/>
    </cmap_format_0>
    <cmap_format_4 platformID="3" platEncID="1" language="0">
      <map code="0x30" name="zero"/><!-- DIGIT ZERO -->
    </cmap_format_4>
  </cmap>

</ttFont>
```
Uncommenting the commented line of the script, to reset the encoding, works around the problem.
```console
$ hb-shape out.otf 01
[zero=0+200|zero=1+200]
```

**Comment by skef** [comment]
Offhand, is it your impression this is a regression or could things have been this way for a while?

**Comment by dscorbett** [comment]
It was like this in the previous version.

**Comment by skef** [comment]
It's possible we could "really" fix this, but offhand I'm concerned about performance, so I'm leaning towards a "doc fix". 

There is a currently undocumented function `font.reencode()` that does the expected with the current encoding. Please confirm that calling that function in place of the commented line also fixes the problem. 

If it does, I'll update the `altuni` documentation to note that some changes will not immediately take effect, and `reencode()` should be run after a group of `altuni` adjustments and before generating or saving.

**Comment by khaledhosny** [comment]
Note that resetting the encoding can cause other effects, like any empty glyphs in the middle (between other non-empty glyphs) disappearing, which might be undesired and certainly unexpected. What I used to do with these kinds of problems (and FontForge has a fair number of them, but sadly I don’t remember much) is to close the font and re-open it again, heavy handed but has less undesired effects. This does not happen when you do these things from GUI, so there is some code somewhere that would handled this.

**Comment by dscorbett** [comment]
`font.reencode(font.encoding)` works too, which makes sense as it runs almost the same C code as `font.encoding = font.encoding`. But if that workaround can break things, I don’t think this should just get a doc fix.

@khaledhosny, I interpreted your workaround as `font.save('temp.sfd'); font.close(); font = fontforge.open('temp.sfd'); os.remove('temp.sfd')`. That works too. Is that what you meant?

**Comment by khaledhosny** [comment]
> @khaledhosny, I interpreted your workaround as `font.save('temp.sfd'); font.close(); font = fontforge.open('temp.sfd'); os.remove('temp.sfd')`. That works too. Is that what you meant?

Yes, something like that.

**Comment by skef** [comment]
Is the UI any different in this respect? Does the right thing happen when immediately generating a font after adding an alternative encoding using the Glyph Info dialog? I'm willing to attempt to break out some code to handle the case, and less willing to try to write it from scratch.

**Comment by khaledhosny** [comment]
Yes, I just tried it again; create a new font, the a new glyph, then add alternative Unicode from glyph info and generate the font, all without saving anything or re-encoding, and the generated font has the expected mapping.

**Comment by skef** [comment]
In that case I'll note "for the record" here that what probably needs to be done is to pull whateer parts of `charinfo.c:_CI_OK()` and `charinfo.c:_CI_ApplyAll()` do what is needed and make it available to the `altuni` setter.
