### ISSUE TITLE
Up/down arrow keys are broken in Execute Script

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3552]
In the “Execute Script” dialog box, pressing the up or down arrow key moves the cursor to the first line of the buffer. The left and right arrow keys work fine. I am using Fontforge 20190317 on macOS Mojave 10.14.3.

**Comment by skef** [comment]
Interestingly, this reproduces on Linux with both GXDraw and GGDKDraw. For me the down arrow always goes to the beginning of the first line, while the up arrow goes to the same offset on the first line. This shouldn't be too hard to track down.
