### ISSUE TITLE
Where does the AppImage go?

### ISSUE THREAD

**Issue by SRGOM** [fontforge/fontforge#3558]
This question is for @probonopd - I tried downloading from https://transfer.sh/FontForge-git.b031e64-x86_64.AppImage but no luck. There doesn't seem to be a way to download from https://appimage.github.io/apps/ either.

**Comment by SRGOM** [comment]
@probonopd Can you help?

**Comment by skef** [comment]
We link to the "release" AppImages in the release note: https://github.com/fontforge/fontforge/releases

The "incremental" app images go here: https://dl.bintray.com/fontforge/fontforge/ . This is (not) noted in [CONTRIBUTING.md](https://github.com/fontforge/fontforge/blob/master/CONTRIBUTING.md)

**Comment by probonopd** [comment]
We also added a "Download" button and some more buttons on https://appimage.github.io/FontForge/ (based on the AppStream information inside the latest AppImage release).

**Comment by SRGOM** [comment]
It seems that somebody is working on the GUI! 

I had an old version from arch-repo but thanks to @probonopd and you guys, I can use this.

Sidenote and probably irrelevant here but I wonder what the relationship between the page you linked to and bintray appimage store is? My understanding was that AppImage is mostly your creation and bintray provided you free hostin

**Comment by probonopd** [comment]
The AppImage repo on Bintray holds some of my personal test AppImages. Now that FontForge has an official AppImage the one on Bintray is no longer of interest to anyone. Unfortunately the free version of Bintray doesn't let me delete old releases.
