### ISSUE TITLE
HiDPI question - how can I make the CharView's ruler, toolbox larger?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3570]
GDK has massively helped this project in re: HiDPI, but it seems like no matter what I set `ScreenWidthInches` or `GDK_SCALE` to, the ruler and toolbox remain a constant size.

How can I make them larger so I don't have to use a magnifier anymore to do my work? The massive size imbalance is easily seen in the image below.

![Screenshot_20190323_130416](https://user-images.githubusercontent.com/838783/54861852-330ff000-4d6c-11e9-8ce5-3cd348db0d20.png)

**Comment by jtanx** [comment]
Does something like this work?

```patch
diff --git a/fontforgeexe/charview.c b/fontforgeexe/charview.c
index 67dbedc23..1bcd940b3 100644
--- a/fontforgeexe/charview.c
+++ b/fontforgeexe/charview.c
@@ -12598,11 +12598,8 @@ static void _CharViewCreate(CharView *cv, SplineChar *sc, FontView *fv,int enc,i
 
     cv->showdebugchanges = CVShows.showdebugchanges;
 
-    cv->infoh = 13;
-#if defined(__MINGW32__)||defined(__CYGWIN__)
-    cv->infoh = 26;
-#endif
-    cv->rulerh = 16;
+    cv->infoh = GDrawPointsToPixels(NULL, 13);
+    cv->rulerh = GDrawPointsToPixels(NULL, 16);
 
     GDrawGetSize(cv->gw,&pos);
     memset(&gd,0,sizeof(gd));
@@ -12909,11 +12906,8 @@ CharView *CharViewCreateExtended(SplineChar *sc, FontView *fv,int enc, int show
     cv->enc = enc;
     cv->map_of_enc = fv->b.map;		/* I know this is done again in _CharViewCreate, but it needs to be done before creating the title */
 
-    cv->infoh = 13;
-#if defined(__MINGW32__)||defined(__CYGWIN__)
-    cv->infoh = 26;
-#endif
-    cv->rulerh = 16;
+    cv->infoh = GDrawPointsToPixels(NULL, 13);
+    cv->rulerh = GDrawPointsToPixels(NULL, 16);
 
 
     SCLigCaretCheck(sc,false);
```

**Comment by jtanx** [comment]
Fixing the palette is harder, the size is tied to the image size of the icons...

**Comment by ctrlcctrlv** [comment]
The patch does not help the ruler either, just makes it a bit taller but I still need a magnifier to read it.

![patched](https://user-images.githubusercontent.com/838783/54862174-a831f400-4d71-11e9-8994-e831f2864b22.png)

**Comment by ctrlcctrlv** [comment]
Another, no doubt related HiDPI issue, is the tiny size of the icons in the "Spiro Get Info" dialog.
![spiro get info](https://user-images.githubusercontent.com/838783/54862236-a7e62880-4d72-11e9-8b0e-df348fed54e2.png)

**Comment by skef** [comment]
First off try setting `CharView.Rulers.FontSize` larger. That won't change the tics, but it's a start. 

For the tics play around with `units` and `littleunits` on 5868. And replace the 4 on lines 5920 and 5924 with a constant up top.

If you get a combination working, the next step is to either:

1) Add a separate tunable that affects `rulerh`, `units` and `littleunits` and your 4 replacement.
2) Tune these (in a sophisticated way) off of `CharView.Rulers.FontSize`.

**Comment by ctrlcctrlv** [comment]
No offense, and thank you for your help, I will attempt to apply it, but I believe FontForge's defaults should be more sane, as the proliferation of HiDPI displays sees no signs of slowing.

**Comment by skef** [comment]
I'm proceeding on these assumptions:

1. The current code does not configure things well based on hidpi detection or manual overrides.
2. You're the main person currently trying to use the program this way.
3. The way to get to a point where things are configured correctly is to identify the individual values that need to be scaled and pick the variable to scale them off of.
4. Given 2, you're the person to chew away on that project.

**Comment by ctrlcctrlv** [comment]
I believe I represent a silent majority :-)

**Comment by jtanx** [comment]
Just a note, but playing with GDK_SCALE locally scales everything correctly; I don't see the same behaviour with some parts not being scaled. Just thinking out loud though, I wonder if scaling isn't being applied appropriately in the gdk layer when creating pixmaps

**Comment by skef** [comment]
... or try that

**Comment by skef** [comment]
He's on Arch, which is always within spitting distance of the bleeding edge. Definitely 3 unless he's specifically configured it back.

**Comment by ctrlcctrlv** [comment]
That's weird, could it be my use of KDE? I type `env` and I see multiple perhaps related entries : 

QT_SCREEN_SCALE_FACTORS=DVI-I-0=1;DVI-I-1=1;HDMI-0=1;DP-0=1;DP-1=1;DP-2=1;DP-3=1;DP-4=1;DP-5=1;
XCURSOR_SIZE=64
XDG_CURRENT_DESKTOP=KDE
QT_AUTO_SCREEN_SCALE_FACTOR=0

I tried running with

``env -i XAUTHORITY=$XAUTHORITY DISPLAY=:0 GDK_SCALE=10 `which fontforge` ``

But that didn't help, and it still looked the same (that is, 2x). Let me see if I can definitively rule this out. By the way...

```
[fred@pc ~]$ pacman -Qi gtk3
Name            : gtk3
Version         : 1:3.24.7+25+g17665f06e3-1
Description     : GObject-based multi-platform GUI toolkit
Architecture    : x86_64

```

**Comment by skef** [comment]
I (also on Arch, also with KDE plasma) can do this in a shell:

`GDK_SCALE=2 fontforge`

and it works.

**Comment by ctrlcctrlv** [comment]
Hooray! Got it working. I decided to peek at `config.log`, and saw `--with-x`. Looks like I was still inadvertantly using the deprecated Xorg backend after being asked to compile with it at https://github.com/fontforge/fontforge/issues/3510#issuecomment-471161346. This is `GDK_SCALE=4`

![gdk](https://user-images.githubusercontent.com/838783/54862611-47f28080-4d78-11e9-92d8-dabeb53f8d26.png)

May I stress to the audience that this is yet another reason to use the GDK backend everywhere by default as I've advocated at https://github.com/fontforge/fontforge/issues/3541#issuecomment-473618836

**Comment by ctrlcctrlv** [comment]
Oh, by the way @jtanx , your patch is stupendous as usual when GDK is actually in use. I say you should commit it!

**Comment by jtanx** [comment]
Well that was an easy fix :P

As for the patch, I'm not sure it makes too much sense, it scales the height, but it was fixed with the size of the icons in mind (at least for the info bar), which don't scale with respect to the height

**Comment by ctrlcctrlv** [comment]
>Well that was an easy fix :P

Yes, I apologize to you for wasting your time. I suggest perhaps putting either "GDK" or "Xorg" in the About screen so that this issue can be fixed more quickly, as as it stands only subtle differences exist between the two and it's not especially easy, especially on Linux, to know which is in use.
