### ISSUE TITLE
fontforge tries to initialize GDK when no UI will be displayed

### ISSUE THREAD

**Issue by floppym** [fontforge/fontforge#3582]
Downstream bug: https://bugs.gentoo.org/681650

On Gentoo Linux, we run `make check` as part of the package build process. The test suite involves calling the built fontforge binary with options to convert several font files without any user interaction.

In the past, running these tests did not require an active X display.

After upgrading to 20190317, we get the following output from the test suite.

```
../fontforgeexe/fontforge -lang=ff -c 'Open($1); Generate($2)' fonts/Ambrosia.sfd fonts/Ambrosia.pt3
No protocol specified

(fontforge:326): Gdk-WARNING **: 13:12:52.415: cannot open display: 
make[3]: *** [Makefile:1823: fonts/Ambrosia.pt3] Error 1
make[3]: Leaving directory '/var/tmp/portage/media-gfx/fontforge-20190317/work/fontforge-20190317/tests'
make[2]: *** [Makefile:1662: check-am] Error 2
make[2]: Leaving directory '/var/tmp/portage/media-gfx/fontforge-20190317/work/fontforge-20190317/tests'
make[1]: *** [Makefile:1916: check-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/media-gfx/fontforge-20190317/work/fontforge-20190317'
make: *** [Makefile:2205: check] Error 2
```
I believe this happens because fontforge always calls the `gdk_init()` function, regardles of whether the user interface will ever be displayed.

**Comment by jtanx** [comment]
Ah, that makes sense. It might be enough to replace `gdk_init` with `gdk_init_check`, as there are checks further down the line to determine if it can get a display or not.

Otherwise we'd need to check the result after `CheckIsScript` is called in `startui.c`, or otherwise move `gdk_init` further down.

**Comment by floppym** [comment]
> otherwise move gdk_init further down.

This seemed like the most obvious solution to me. I tested it and it seems to work ok for both scripts and GUI usage.
