### ISSUE TITLE
Document clarification. 

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3584]
I'm going to use this thread to clarify aspects of the docs as I'm working through them. Please advise as you can.

**Comment by skef** [comment]
From `overview.html`: 

>  Consider any point in the glyph. If we draw an imaginary line from that point out to infinity (in any direction) and count the number of times we cross a path, each time we cross a clockwise path we add one to our count, each time we cross a counter clockwise path we subtract one. If the result of our count is non-zero then we color the point dark, otherwise we leave it white. So to make the A above work we make the outer path be clockwise and the two inner ones be counter-clockwise (Things could be done the other way around, but the convention is that the outer path should be clockwise).

This is just wrong, right? If I start in the upper "hole" of an "8" and aim my line through the lower hole, and the holes are counter-clockwise while the outer contour is clockwise, I get -1 + -1 + -1 + 1, or -2, which is non-zero.

**Comment by frank-trampe** [comment]
I think your addendum is right. For what it's worth, though, the non-zero rule deals with cases way outside good type design form. I'd vote for linking to the non-zero rule and, inline, just saying that (1) a filled path must not cross itself or another filled path, (2) a clockwise path is positive, and (3) a counter-clockwise path is negative. @davelab6, what do you think?

**Comment by skef** [comment]
My instinct is to say in-line (in better words) that you make a filled area with a clockwise contour, take an area out with an inner counter-clockwise area, and refer harder cases to a more complicated explanation elsewhere -- maybe the glossary. 

Even limiting to non-intersecting paths you can't attend to the direction of the contour being crossed in isolation. Crossing a contour twice (as in my example) needs to get you back to the same count. That's what the definition in Design With Fontforge gets you: It's not the direction of the contour alone but the way the portion being crossed goes over the virtual line.

**Comment by frank-trampe** [comment]
I meant contours, not test paths. If no contours cross, the clockwise/counterclockwise contour rule works. The complicated explanation could go in the glossary, but I don't know that we need to maintain it at all in user documentation. The cases in which it is necessary are to be avoided in the first place.

**Comment by skef** [comment]
> I meant contours, not test paths. If no contours cross, the clockwise/counterclockwise contour rule works. 

If that's right, then my example using an "8" is wrong and it would help to understand how. 
![eightex](https://user-images.githubusercontent.com/6175836/54948520-0db0ec80-4efa-11e9-92b3-7b6ca966ec9b.jpg)

**Comment by frank-trampe** [comment]
I don't understand how the example pertains at all to a model without a test path. There is an outer contour that runs clockwise with two counter-clockwise contours inside. The outer contour is positive, and the inner contours are negative. Right?

**Comment by skef** [comment]
So the rule you're thinking of is topological rather than geometric: you calculate by considering how many closed contours enclose your point and whether they are clockwise or counter-clockwise. That works, but I take it the advantage of a test line rule is that it doesn't depend on abstractly/topologically representing the shape in one's head.

**Comment by frank-trampe** [comment]
When you state it like that, as a comprehensive set of imperatives for the renderer, it doesn't sound any simpler than the test line rule. But if you state the designer imperatives that apply within good type design, as I did before, I think that it is a lot easier to understand. You're the one doing the work here, so I'll defer to your judgment. Just sharing my perspective on the matter.

**Comment by JoesCat** [comment]
I was reading your original post in this thread - when you have more eyes looking at something, you catch things that might not be seen before :-)
I think you're idea of starting from inside the 8 wasn't thought about as a possible scenario, so it indeed falls-over as wrong. Many people tend to think raster scan, so the any point is a problem here.

Your scenario special case can work if we think about even vs odd, but it again breaks down if you start from within what we'd call the black fill area of the eight.

Instead of the phrase any point, we should probably think of slicing the glyph like you slice bread. You start from the outside, you cross through the glyph, and you exit again. I think this is probably the likely scenario for raster scan colouring/filling too.

**Comment by JoesCat** [comment]
> I get -1 + -1 + -1 + 1, or -2,

Can also think this way:
crossing#1direction_at_interesction=clockwise
black
crossing#2direction_at_interesction=counterclockwise
white
crossing#3direction_at_interesction=clockwise
black
crossing#4direction_at_interesction=counterclockwise
white

**Comment by skef** [comment]
The issues can be broken down into three categories:

1. What's actually right and wrong
2. What's right but easier or more difficult to understand.
3. What's right but easier or more difficult to apply in practice. 

The current description in `overview.html` is *wrong* -- it doesn't give you the right answer in some cases. That's because (I'm guessing) it's a hybrid of the actual nonzero rule and the way @frank-trampe is thinking about it. 

The Nonzero rule is *right*, even for this case, but may be too difficult to understand. If you pay attention to the direction of the contour line as it crosses the test line, and not just "the direction of the contour", you get the right answer (as you do your latest comment). But then you've got confusing terminology because you're overloading "clockwise" with two different meanings. 

@frank-trampe's rule is also *right* (as far as I can tell), but may be difficult to apply in practice in some cases. I'm not as confident this is a matter of good glyph design as much as it is of the typical shapes of latin characters. Some shapes may be harder to topologically abstract in the way that's required.

**Comment by JoesCat** [comment]
I had a math professor that wrote his own book, and he said that for every math formula you add in the book you drop the readership by half. His book buyers were practically limited to students -LOL.

You are right, if it's difficult to understand, it's easy to get it wrong.
keeping terminology simple(r) helps everyone avoid confusion.

**Comment by skef** [comment]
I went with this for now. I may add a better explanation somewhere if I get really ambitious. 

> A general rule for which areas will be inked, or “part of the shape”, and which will not, can be difficult to 
understand or apply. However, this guideline covers most cases: To *add* an “inked” or “filled-in” area to the glyph, put a *clockwise* contour around it. To *remove* ink or fill from an area inside a clockwise 
contour, put a *counter-clockwise* contour around it. Then repeat this pattern in any additional area to be filled in, whether no contour surrounds it or a counter-clockwise contour surrounds it.  There is never any reason to put a clockwise contour directly inside another clockwise contour, nor to put a counter-clockwise contour directly inside another counter-clockwise contour; they should always alternate. And the “outer” contour of any part of a glyph should always be clockwise.

3.4 bonus points for "never" ... "nor".

**Comment by JoesCat** [comment]
>   There is never any reason to put...
> ...nor...

Sounds like an absolute.
Might be worth sitting on this a couple days before hitting merge, in case 
someone brings up an exception.

**Comment by skef** [comment]
Oh there's no risk of a merge in the next couple days, believe me.

**Comment by ilyaza** [comment]
> >  Then repeat this pattern in any additional area to be filled in, 
> > whether no contour surrounds it or a counter-clockwise contour surrounds it.  

Change to:

> (it does not matter whether this area is “standalone” or is in a hole inside a filled area).

**Comment by skef** [comment]
Issue two: For outputting to OpenType clearly one's anchor points should be noted in GPOS tables. However, FontForge lets you create "untabled" points with its dialogs, which can be useful for some purposes (such as better results from its "build composite glyph" feature). As it happens it's also easier for documentation purposes to use the dialogs initially and get into the lookup table complications later.

So suppose you create a bunch of anchors with the dialog and later want to add them to GPOS tables. Is this possible/safe? And how do you do it? (I've been playing around and not having much luck. It seems like adding them via the lookup dialog tends to result in FontForge thinking there are multiple anchors with the same name.)

**Comment by skef** [comment]
No one is going to listen to my embedded questions I don't think.

**Comment by ctrlcctrlv** [comment]
We're sorry @skef, sometimes us mere mortals cannot keep up with your sheer ability with C and knowledge of FontForge internals. 👍

**Comment by skef** [comment]
"It's just software."
