### ISSUE TITLE
Windows - Batch conversion fonts OTF2TTF

### ISSUE THREAD

**Issue by Sue2019** [fontforge/fontforge#3588]
I have  lots of OpenType fonts that I want to convert to TrueType fonts under windows10 system. It might be easy in linux, but I just can work under windows system. 
I am not familar with programming, so can I use some easy way to  convert. 
Thanks.

Windows 7/10
ffversion: Jul 31, 2017

**Comment by ctrlcctrlv** [comment]
This is not a forum, it is a bug tracker. You are not reporting a bug. I respectfully request that you close this issue and post to either the mailing list or some other typography forum.

**Comment by skef** [comment]
The archive page for the fontforge-users list is here: https://sourceforge.net/p/fontforge/mailman/fontforge-users/ . It has information on how to sign up.
