### ISSUE TITLE
OSX 10.14.3 Broken interface, wrong font

### ISSUE THREAD

**Issue by lukasoppermann** [fontforge/fontforge#3592]
I downloaded the latest version 2019-03-17 from the website and I am running OSX 10.14.3. Sadly the tool is unusable because the text is in an incorrect font.

Please let me know if I can provide more helpful information.

<img width="350" alt="Screenshot 2019-03-26 at 22 29 00" src="https://user-images.githubusercontent.com/813754/55035022-2f53c600-5017-11e9-961b-184cfc189a55.png">
<img width="178" alt="Screenshot 2019-03-26 at 22 29 05" src="https://user-images.githubusercontent.com/813754/55035023-2f53c600-5017-11e9-8029-0f3bc3ff9c0b.png">

**Comment by skef** [comment]
"I've seen some vulgar fonts in my time, but this is ridiculous!" 

Could you temporarily install DejaVu Sans on your system and see if that changes things? https://dejavu-fonts.github.io/

**Comment by ctrlcctrlv** [comment]
Bizarre&hellip;looks like FontForge is using some so-called "expert" font usually bundled with expensive fonts sold by Monotype, Linotype, etc.

**Comment by skef** [comment]
When not configured otherwise FontForge chooses a font with a string like "dejavu sans,helvetica,caliban,sans,clearlyu,unifont". (Unless the mac path is different in a way I'm missing.) Given that other users have had success with the mac build some weird font is a good first guess.

**Comment by lukasoppermann** [comment]
Hey @skef, sadly installing `DejaVu Sans` did not change anything. 😢 do you have any other idea. I have helvetica installed but maybe the path is different?

Can I somehow customize it or provide more infos for you?

**Comment by skef** [comment]
Here's a quickie idea that might work/help:

1. Run `sudo fs_usage | grep fontforge > /tmp/ff_io_trace.txt`
2. Start up fontforge to the point the bad font is displayed. 
3. Stop the first command and attach the output here (deleting any lines you deem impolitic).

**Comment by jtanx** [comment]
I swear I've seem a similar bug report in the past, I could never repro it though

**Comment by jtanx** [comment]
@lukasoppermann  out of interest, what's your monitor setup like?

**Comment by ctrlcctrlv** [comment]
I've confirmed my theory. For some reason, `helvetica` is causing `HelveticaFractions` to be chosen. This is an ancient pre-Unicode version of the font, where the fraction components were just stuck in ASCII codepoints because that's how things were done in the early 90's when it was released.

![fracs](https://user-images.githubusercontent.com/838783/55068749-83b18100-50bd-11e9-9544-2b627f71f0b4.png)

I remembered this font and tracked down a copy. As you can see, the numbers match up exactly.

I recommend uninstalling it. It's deprecated and honestly pointless. If you can't uninstall it, you're going to need to figure out why it's taking precedence over other fonts.

**Comment by lukasoppermann** [comment]
Nice, disabling `helvetica` in `Font Book` solved this. Thanks 👍 

@jtanx I am only using my mac books internal monitor.

**Comment by skef** [comment]
Wow, it doesn't get more customized than that on the issue-analysis front. 

While we're "here", it would be useful to know why installing Dejavu Sans didn't fix the this problem, given that it's supposed to be higher up in the font choice list.

**Comment by jtanx** [comment]
Nice find @ctrlcctrlv!

$10 on a pango bug, we've already had to pin to a specific version just to even get it run without crashing on mac

**Comment by ctrlcctrlv** [comment]
You shouldn't need to disable Helvetica completely, just Helvetica Fractions. Before Unicode and OpenType became widespread, these so-called "expert" fonts were heavily promoted by Linotype, other ones contained rare ligatures that we'd now put in `dlig`, historical forms we'd stick in `hist` today et cetera. 

I have no idea why this historical artifact was installed on your PC, but I can't imagine why you'd need it today. Even Linotype has moved on from this and just uses `frac` like a normal person would after, let's say, 2005. :-)

**Comment by lukasoppermann** [comment]
Hmm, sadly fontforge always crashes now when I try to open any font file, but I guess this is another issue.

**Comment by ctrlcctrlv** [comment]
Yes, that would be another issue. Time to whip out `gdb` ! :+1:

**Comment by skef** [comment]
Just to reassure you a bit -- we do have some mac users, including users of recently downloaded versions. We should be able to sort out these problems and get you going.
