### ISSUE TITLE
Add python interface for default hotkeys 

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3601]
People who extend FontForge using python may want to add keyboard shortcuts for registered menu-items. The "shortcut_str" is broken as of the 2012 hotkeys implementation. 

The use of that string should be updated in the following way:

1. The docs should be updated to say that it should just contain a keystroke set -- no need for a prefix and pipe.
2. Any existing prefix and pipe should be stripped out of passed strings, for compatibility. 
3. It should add a hotkey string corresponding to "FontView.Menu.Tools." + the menu string, with the passed shortcut. 
4. And the tricky part: it should have the same precedence as a default hotkey entry, and therefore be overridden by a user's "custom" hotkeys. 

The tricky part probably isn't that tricky, although it will require some changes. Right now precedence is handled by loading order. However, there is a `isUserDefined` state already there to track whether to write the hotkeys out to the user's file. We can modify this part of `gdraw/hotkey.c:hotkeySetFull()`:
```
    if( !append ) {
        Hotkey* oldkey = hotkeyFindByStateAndKeysym( hotkeyGetWindowTypeString(hk),
                                                     hk->state, hk->keysym );
        if( oldkey ) {
            dlist_erase( &hotkeys, (struct dlistnode *)oldkey );
            free(oldkey);
        }
    }
```
to be something like:
```
    if( !append ) {
        Hotkey* oldkey = hotkeyFindByStateAndKeysym( hotkeyGetWindowTypeString(hk),
                                                     hk->state, hk->keysym );
        if( oldkey ) {
            if ( oldkey->isUserDefined && !hk->isUserDefined ) {
                free(hk);
                return 0;
            }
            dlist_erase( &hotkeys, (struct dlistnode *)oldkey );
            free(oldkey);
        }
    }
```

**Comment by skef** [comment]
I should probably try to fix this before the next maintenance release.

**Comment by skef** [comment]
Thinking about this more, I'm less sure what the fix should be, if anything. 

When an individual user writes a script for individual use, they can just add their own hotkey in the configuration file. It might be more convenient to do it directly in the python, but that doesn't matter much. 

When someone writes a script for wider use there is more benefit to providing a default hotkey. But *what* default hotkey? How are they "allocated" between different scripts? And what hotkeys are "available" anyway? (I guess for a start a lot of modifier+function combos.) 

It might be better alter the interface so that rather than specifying a specific key combination, it would have "short", "normal" and "none" (or just `None` like now). Then the program could assign an available, appropriate hotkey and put that assignment into the user's file. 

That's probably not too hard to implement, but it doesn't seem like a priority. So for now maybe we should just update the documentation to clarify that the shortcut string is currently ignored, indicate how a user can add their own, and note that the system may be improved in the future.

**Comment by ctrlcctrlv** [comment]
There's a lot of weirdness around hotkeys in general. The names of the hotkey functions are ambiguous and in some cases archaic. As noted in #3604, just one function can have multiple hotkey names, scattered around the relevant documentation (`xres.html`, `HotKeys.html`, configurations in the share directory such as `default` and `default-n`).

I would suggest that we fix bugs and add clarity to hotkeys for options in the default distribution before we discuss ambitions to allow hotkeys for non-default scripts...the current hotkey system barely works.

**Comment by skef** [comment]
From looking at the code I'm somewhat confident that as of 2012 the `hotkeys` files are the only relevant control, and the `xres` directives have no effect. And I haven't yet run into a "code bug", just documentation problems and the mismatching issue I updated your other issue with a moment ago.
