### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fontforge/fontforge#3602]
I would like to point out that identifiers like “[`_PFED_H`](https://github.com/fontforge/fontforge/blob/9d02732cd71dab9bcb04631c985067b267f3ab65/fontforge/PfEd.h#L28 "Update candidate")” and “[`_UIINTERFACE_H`](https://github.com/fontforge/fontforge/blob/9d02732cd71dab9bcb04631c985067b267f3ab65/fontforge/uiinterface.h#L27 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by JoesCat** [comment]
We will be happy to look at what you describe. Please send in a PR with a patch.

**Comment by ctrlcctrlv** [comment]
This issue should be closed, patch or no patch. Accept the patch, fine, but to call this pedantic complaint an "issue" stretches the word so much that one side of it ends up in an alternate dimension.

**Comment by JoesCat** [comment]
Closing issue. Created new spam label. Looking at the users profile, it appears to be spamming.
