### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fontforge/fontforge#3603]
Would you like to add more error handling for return values from functions like the following?
- [ftell](https://pubs.opengroup.org/onlinepubs/9699919799/functions/ftell.html "Return a file offset") ⇒ [dumpGPOSsimplepos](https://github.com/fontforge/fontforge/blob/68c72b1c9c44330429c5eb40db784bd3a5ee1732/fontforge/tottfgpos.c#L934)
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [OpenDocumentsAE](https://github.com/fontforge/fontforge/blob/3659e2da7ef837d46f00a6fb6ce310dc754a8af9/fontforgeexe/startui.c#L474)

**Comment by JoesCat** [comment]
We will be happy to look at what you describe. Please send in a PR with a patch.

**Comment by skef** [comment]
In a perfect world every call to `malloc` would be checked for NULL, but there are a lot more productive ways to invest development time than that.

**Comment by JoesCat** [comment]
I'm hoping for a patch, but I suspect we've been spammed.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by skef** [comment]
@elfring Are you aware there are forms of communication other than rhetorical questions? And that neither of these is one of them?

**Comment by elfring** [comment]
I suggest to take additional software development possibilities into account for corresponding solutions.
Which approaches would you like to clarify further?

**Comment by skef** [comment]
I'm good.

**Comment by elfring** [comment]
Do you find any software development approaches more promising than other ways?

**Comment by skef** [comment]
The vast majority of the work in this repository involves maintaining and fixing bugs in a large C source base with its own widget library. The rest is slowly inching it towards the use of more standard interfaces. There are over a thousand open issues. 

I would be interested in a well-functioning C language refactoring engine, but CScout is not really functional right now and we aren't the audience for Coccinelle. CodeCompass looked promising but it's in the fifth circle of Docker hell at the moment.

**Comment by elfring** [comment]
I find the following development tools helpful for source code refactoring.
* [Semantic patch language (Coccinelle software)](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")
* [AspectC++](https://aspectc.org/ "Aspect-oriented software development")

**Comment by ctrlcctrlv** [comment]
This discussion is completely pointless.

_Thank you_, @elfring, for your opinion on C development, and appropriate tools thereof. I move that instead of you evangelizing these tools, you use them to submit pull requests to the repository. Show us their utility instead of trying to convert us to them, and maybe if the results you suggest are excellent we will be converted.

**Comment by elfring** [comment]
The utility of the mentioned higher level development tools was demonstrated at several places for other software already.
Would you find any of these concrete examples convincing for another application here?

**Comment by ctrlcctrlv** [comment]
**Submit patches, not further comments.** If the tools are in so many ways superior I'm sure you'll have no problem improving FontForge with them.

That is, if you've truly come here to improve FontForge, and not just dog us for perceived slights in the project's naming conventions, and troll the issue tracker with inane comments about your favorite development tools.

Do not reply to me. Submit a patch instead.

**Comment by elfring** [comment]
I suggest to reconsider the situation if another tool can be integrated into your software development process at all.
Will corresponding (semantic) patch approaches evolve (besides other design options) and get the desired change acceptance?

**Comment by ctrlcctrlv** [comment]
Your suggested has been considered and rejected. If you're not going to submit a PR, please kindly do us a favor and close this issue out voluntarily.

**Comment by elfring** [comment]
It will take another while for the integration of additional development tools and the achievement of corresponding change acceptance, won't it?

**Comment by skef** [comment]
I'm getting a distinct GPT-2 vibe

**Comment by ctrlcctrlv** [comment]
I'm getting a distinct Piotr Grochowski vibe...

**Comment by skef** [comment]
Piotr was more proper troll than sea lion.

**Comment by JoesCat** [comment]
closing issue. Looking at the users profile, it appears to be spamming.

**Comment by elfring** [comment]
Do you find an unwanted categorisation easier to set for such a bug report than to agree on a better software solution for this issue?

**Comment by JoesCat** [comment]
github notified of spambot.
