### ISSUE TITLE
FontForge deletes hotkeys if no font opened; otherwise ignores them

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3604]
I have the following in `/home/fred/.config/fontforge/hotkeys`:
```XResources
fontforge.CharView.Hotkey.Tool.SpiroG2:1
fontforge.CharView.Hotkey.Tool.SpiroG4:2
fontforge.CharView.Hotkey.Tool.SpiroCorner:3
fontforge.CharView.Hotkey.Tool.SpiroLeft:4
fontforge.CharView.Hotkey.Tool.SpiroRight:5
```

If I run `fontforge -open` and immediately close it, it deletes the file!

Even if I do open a font, these hotkeys don't work. I've tried as well `fontforge.CharView.Menu.Point.Tools.G2` and `CharView.Menu.Point.Tools.G2`, mentioned in `fontforge/share/default-n`, and those don't work either.

**Comment by skef** [comment]
This is either a documentation issue or an issue with `cvtoollist` and `cvspirotoollist` in `fontforgexe/cvpalettes.c`. Consider these lines:
```
    { { (unichar_t *) N_("C_orner"), (GImage *) "pointscorner.png", COLOR_DEFAULT, COLOR_DEFAULT, NULL, NULL, 0, 1, 1, 0, 0, 0, 1, 1, 0, 'o' }, H_(
"Corner Tool|No Shortcut"), NULL, NULL, CVMenuTool, cvt_corner },
...
    { { (unichar_t *) N_("G_2"), (GImage *) "pointsG2curve.png", COLOR_DEFAULT, COLOR_DEFAULT, NULL, NULL, 0, 1, 1, 0, 0, 0, 1, 1, 0, 'o' }, H_("G2
 Tool|No Shortcut"), NULL, NULL, CVMenuTool, cvt_spirog2 },
```

The hotkey system pulls the string to compare against from the string localized with `H_()`. For whatever reason a bunch of these don't match the printed string, including these.

These lines in a custom hotkey file work:
```
CharView.Menu.Point.Tools.G4 Tool:Shift+F8
CharView.Menu.Point.Tools.Corner Tool:B
```
And these lines (among others) in the master hotkeys file don't have any effect:
```
CharView.Menu.Point.Tools.Curve:2
CharView.Menu.Point.Tools.Corner:3
CharView.Menu.Point.Tools.Tangent:4
CharView.Menu.Point.Tools.HVCurve:5

CharView.Menu.Point.Tools.Toggle Spiro:S
+CharView.Menu.Point.Tools.G2:1
+CharView.Menu.Point.Tools.G4:2
+CharView.Menu.Point.Tools.Corner:3
+CharView.Menu.Point.Tools.Left:4
+CharView.Menu.Point.Tools.Right:5
```
One would think the proper fix is to make the H_ strings match up, fiddling with any internationalization as necessary. That would enable the listed hotkeys, though, which should both be tested and verified as desirable.

**Comment by ctrlcctrlv** [comment]
There should be a way within the FontForge UI to receive the hotkey string for any UI element...I don't know how difficult this would be to implement, but that is what Blender does.

**Comment by skef** [comment]
That's a post gdraw conversation, I suspect.

**Comment by ctrlcctrlv** [comment]
By the way, for future Googlers, I commend @skef on his tireless commitment to the project, and his digging through source code files, the strings in `cvpalettes.c` do indeed work, and for other Spiro disciples I leave the following, as of March 2019, _working_, `hotkeys` file:

```
CharView.Menu.Point.Tools.Activate Spiro:0
CharView.Menu.Point.Tools.G2 Tool:1
CharView.Menu.Point.Tools.G4 Tool:2
CharView.Menu.Point.Tools.Corner Tool:3
CharView.Menu.Point.Tools.Left Tool:4
CharView.Menu.Point.Tools.Right Tool:5
```

**However,** let me be clear, the bug where if you see only FontForge's open dialog and then close it, your hotkeys will be deleted, remains, even with this working configuration.

**Comment by ctrlcctrlv** [comment]
@skef: This is a reply to https://github.com/fontforge/fontforge/issues/3604#issuecomment-478209603 &hellip;

That issue isn't the proper place to reply about this issue, but I encourage you @skef to run `fontforge -open`, immediately close the file picker, and see that your `hotkeys` file has vanished. I encourage you to try to duplicate my result. :)

**Comment by skef** [comment]
Here are all of the instances where N_ string (with underscores removed)  doesn't match the H_ string (with pipe suffix removed) and some junk mixed in:
```
Font|New       New
Merge Feature Info...       Merge Kern Info...
Color|Choose...       Color Choose
Color|Default       Default
Condense/Extend...       Condense...
Change X-Height...       Change XHeight...
Add Small Capitals...       Add Small Caps...
Inline...       Inline
Outline...       Outline
Shadow...       Shadow
Wireframe...       Wireframe
Color|Choose...       Color Choose
Color|Default       Default
Set Extremum Bound...       Set Extremum bound...
Fit to font bounding box       Fit to em
Suggest Deltas...       Suggest Deltas
Connect to Session (ip:port "Connect to Session (ip:port)...|No Shortcut       
Tools2       Tools 2
Font|New       New
Curve       Curve Tool
HVCurve       HVCurve Tool
Corner       Corner Tool
Tangent       Tangent Tool
Deactivate Spiro       Activate Spiro
Corner       Corner Tool
G4       G4 Tool
G2       G2 Tool
Left       Left Tool
Right       Right Tool
Font|New       New
points|Merge       Merge
points|Merge to Line       Merge to Line
Remove Undoes...       Remove Undoes
Left Constraint       Prev Constraint
Right Constraint       Next Constraint
Condense/Extend...       Condense...
Change X-Height...       Change XHeight...
Inline...       Inline
Outline...       Outline
Shadow...       Shadow
Wireframe...       Wireframe
Check Self-Intersection       Clockwise
Glyph Self-Intersects       Clockwise
Insert Text Outlines...       Insert Text Outlines
Suggest Deltas...       Suggest Deltas
PointNumbers|None       None
Show Grid Fit (Live Update "Show Grid Fit (Live Update)...|No Shortcut       
Anti Alias       Grid Fit Anti Alias
Off       Grid Fit Off
Control Points (Always "Control Points (Always)|No Shortcut       
(Define \"Almost\       (Define \"Almost\")
FamilyBlues       Family Blues
Horizontal Metric Lines       Hori_zontal Metric Lines
SubFonts|All       All
SubFonts|None       None
Tools2       Tools 2
Tools2       Tools 2
Font|New       New
Merge Feature Info...       Merge Kern Info...
Deselect All       Clear Selection
Show       Show Grid
Partial       Partial Grid
Hide when Moving       Hide Grid when Moving
Hide       Hide Grid
Advance Width only       Advance Width Only
```

**Comment by skef** [comment]
@ctrlcctrlv we should probably just fix these so they match what's printed in the menu. I realize that list isn't  that great a reference, but if you `grep -R 'H_("str'` where `str` is the second string above, they're pretty easy to find.

**Comment by ctrlcctrlv** [comment]
Thank you, so that's a documentation issue. And about the deletion?

**Comment by skef** [comment]
I think if we actually fix the strings to match it's not a documentation issue. The documentation more or less describes how to look at a menu line and add a key combo for it. If all the `H_` strings match the menu text then one can actually do that. 

I'll glance at the deletion issue. "No promises"

**Comment by ctrlcctrlv** [comment]
I believe I've determined the deletions only happen to hotkey definitions that don't work anyway, so it may be a feature and not a bug.

If we change the strings to match the documentation rather than change the documentation to match the strings, we'll break the file I just confirmed works&hellip;I have no problem with that as long as there is a clear system for defining hotkey names and all the documentation talks about that system and not broken hotkey names from times gone by.

**Comment by skef** [comment]
It seems like the two places the current system is documented is https://fontforge.github.io/HotKeys.html#hotkeyassign and the default hotkeys file itself. And with the possibility of a few discrepancies, isn't the default hotkeys file pretty close to matching the suggested changes already? It certainly has "...G2" instead of "...G2 Tool". It seems like whoever made that file more or less followed my suggestion: read out the text in the menu hierarchy.

**Comment by skef** [comment]
It seems like editing a hotkeys file while any copy of FontForge is running is a bad idea -- it will just get written over. It doesn't seem like there's an editing interface within FontForge itself, though, so I'm confused about the point of writing it out at all. Is it "speculative generality" does it serve some purpose now?

**Comment by skef** [comment]
Why not be a little provocative and comment out `hotkeysSave()` from `startui.c` in the same push request that fixes the strings? That way it can either stop or maybe someone will identify its current purpose.

**Comment by skef** [comment]
@ctrlcctrlv do you want to chew away on the string project or should I?

**Comment by ctrlcctrlv** [comment]
You should because I don't really understand some of what you are proposing and would like to see it in code.

**Comment by skef** [comment]
@ctrlcctrlv Note that that fix gives particularly convenient hotkeys for the point types already in the defaults file -- numbers 1 through 5.
