### ISSUE TITLE
Anchor classes hang around when you remove all features and become inaccessible to Python API

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3607]
Right now we're discussing SFD / FEA separation, the cause of which I am the primary champion, in #3594, #3596, and elsewhere. During that discussion, my friend @skef came up with a compromise, `featuremunge.py`. While playing around with that, I believe I've found a problem with FontForge, which has unfortunately corrupted my font files&hellip;the reason I supported separation in the first place.

So, the problem is that FontForge will let you remove all its lookups via e.g.:

```python
[font.removeLookup(l) for l in list(font.gpos_lookups)+list(font.gsub_lookups)]
```

But, remember, the `mark` feature counts as a feature as well, and you can define anchors within it, as:

```fea
markClass [gravecomb acutecomb tildecomb] <anchor 273 353> @mark_top;
feature mark {
    lookup mark1 {
        pos base [a n] <anchor 307 573> mark @mark_top;
    } mark1;
} mark;
```

Put simply, if you remove all the lookups, and save, thinking the anchors will also be gone, you are sorely mistaken, they remain, and are no longer removable.

```sfd
 StartChar: a
 Encoding: 97 97 7
 Width: 485
 VWidth: 0
 InSpiro: 1
 Flags: HMW
 AnchorPoint: "mark_top" 310 500 basechar 0
```

Elsewhere we see...
```sfd
 AnchorClass2: "mark_top"""
```

In a healthy file that would look like...

```sfd
 AnchorClass2: "mark_top" "'mark' Mark Positioning in Latin lookup 0-1"
```

Getting out of this situation via the Python API seems itself impossible. That's because you can't find out what the anchor class name is because it's no longer part of a lookup, which is legal in SFD format but illegal in OpenType AFAIW.

```python
# This, to my great disappointment, does not work.
def clearAnchors(font):
    classes = list()
    for e in list(font.gpos_lookups)+list(font.gsub_lookups):
        aclasses = list(font.getLookupSubtableAnchorClasses(e))
        for ac in aclasses: classes.append(ac)

    for _class in classes:
        font.removeAnchorClass(_class)
```

So, I of course seek comment from the other honored contributors to the project, but I would suggest we either:

1. Make it so that anchors are bound to their lookups, and deleting one deletes the other. (my _preferred_ option)
1. Make it so that Python can discover anchor classes not bound to a subtable.

**Comment by skef** [comment]
This analysis coincidentally has to do with my question [here](https://github.com/fontforge/fontforge/issues/3584#issuecomment-477917115), but it's missing a couple factors. 

The main one is that at present anchor points don't have to start out with lookups in the first place. You can just create a new one with the anchor point dialog and start using it. Even if it won't work properly with OpenType, FontForge will use one when constructing a composite glyph when it is present in both "parents". 

The other factor is that they are discoverable through the python interface after all; they're in `glyph.anchorPoints`, and this script will print them regardless of whether there is a lookup:

```
#!/usr/bin/env python

import fontforge

f = fontforge.open("Untitled1.sfd")
for g in f.glyphs():
    print(g.glyphname,g.anchorPoints)
```
And assigning to `anchorPoints` does indeed alter or remove them. 

The problem I ran into while working on the documentation was how to get an *existing* anchor point into a lookup. Whatever I did seemed to create a new one with the same name, but maybe I was confused or didn't have the magic formula. I'm still looking for that answer. 

I'm not certain but I suspect removing the ability to have "non-lookuped" anchor points is a non-starter, because at least one other format besides OpenType supports them.

**Comment by skef** [comment]
Oh, and @ctrlcctrlv: I believe the interface you want/need already exists:

> `removeLookup(lookup-name[,remove_acs])` Remove the lookup (and any subtables within it). `remove_acs` (0 or 1), specifies whether to remove associated anchor classes and points.

I just didn't add the second argument in my script. You can replace `font.removeLookup(dln)` with `font.removeLookup(dln,1)` to have it also remove the anchors.

**Comment by ctrlcctrlv** [comment]
Thanks, that combined with using the glyph to remove the anchors to fix my current broken state should work. I can't test it right now but I have no reason to think it won't so I'll close this for now and open a new issue if I find something else.

**Comment by skef** [comment]
OK, but I still would like to know if it's possible to put Humpty Dumpty back together again, and how. What is the reliable method for getting an already existing anchor into a lookup?

**Comment by skef** [comment]
@ctrlcctrlv: Have you had any luck with my problem, or could you take a look? Is it possible to add an anchor point first and get it into a GPOS class second? Is it just a matter of some subtle state match-up that I missed?

**Comment by ctrlcctrlv** [comment]
@skef I've thought about it but I'm pretty sure it's impossible. I think you're kind of looking at it wrong as well, no offense, it's not really so much about moving the anchor _points_ into the table, but more about moving the anchor _class_ into a subtable. Obviously you could just hand edit the SFD file and set `AnchorClass2` accordingly, but there's no way to do that in Python AFAICT.

**Comment by ctrlcctrlv** [comment]
In my situation, the FEA file is the source of truth, so losing the anchor points that aren't part of a subtable is really not a big deal for me.

**Comment by skef** [comment]
Never mind python for the moment -- I'm just wondering about the GUI. I add an anchor point using the dialog in the glyph window, which adds a name that will be in that dialog in other circumstances. Now I want to have it be in a GPOS anchor class. Can I do that in the Font Info dialog somehow?

**Comment by ctrlcctrlv** [comment]
Yes you can, I just did it. Let's say you right click in the CharView, press "Add Anchor". You provide a class name _p_. Later you create a GPOS `mark` lookup and subtable. If you provide _p_ FontForge moves those anchors into the subtable. Just worked for me, at least.

**Comment by skef** [comment]
Ok, so maybe I had the class wrong when I was doing it. (I wound up with multiple classes of the same name in the CharView dialog, but maybe one was mark-to-base and one was mark-to-mark or something.)

It's good that this works - it makes the documentation stream easier.

**Comment by ctrlcctrlv** [comment]
@skef Either `mkmk` or `mark` work for me, see video&hellip;

https://drive.google.com/file/d/1YmCn5zv24a_OeeB7EhKMU14Pdppkqrux/view?usp=sharing

Sorry for the offsite link, it seems like 20MB is too large for Github for some reason.

**Comment by skef** [comment]
Cool, thanks -- I've stashed that.
