### ISSUE TITLE
GDK modality freeze sequence

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3611]
This is with a recent build on Arch Linux with GDK:

1. Run `fontforge tests/fonts/ItalicHand.sfd` (I don't think the font matters but it's the one I was using.
2. Open Metrics -> Kern Pair Close-up, enter "a" and "b" as glyphs. 
3. Pick "New Lookup Subtable" from the lower menu, make it a "kern" and press OK, accepting the default lookup name.

At this point the "Could not call GGDKDrawSetTransientFor" warning prints, but more importantly all windows are "grabbed", leaving the program effectively frozen.

**Comment by jtanx** [comment]
I guess you could say this is similar to #3589, in that the last nontransient window gets unset because the window is going away.  Yuck, all this transient business is too messy. Really GDraw should have been explicit about what it wanted to be transient *to*. But there's too many places for me to bother changing...

Will need to think this through some more

**Comment by skef** [comment]
Was thinking about this a bit earlier:

1. Window "parentage" is most relevant to issues like: a) where should a window initially appear? (maybe near the parent) and b) What window should get focus when this one is closed? (probably the parent). The current code also relates (what amounts to) parentage and modality. So why is that, and what is the proper relation?
2. @jtanx's earlier GGDKDraw modality implementation used the ancestry hierarchy to leave windows outside of that hierarchy "ungrabbed". I argued against that convention not on the basis of any of these modality implementation questions, but because I was worried it was more generally "unsafe" overall -- that the code wasn't really designed with that model in mind, and doing stuff in other windows might (for example) invalidate pointers "trusted" in the implementation under the modal dialogs. I don't want to revisit that issue here except to briefly consider whether going back to that model might help the present problem. Short answer: I don't see how it would. It seems like these issues are cropping up because in some cases it's hard to track parentage in the code, and you sometimes get multiple modal windows that  intuitively have a ancestor-descendant relationship but the code makes it hard to track. So these issues seem orthogonal to that question.
3. **Given** that decision, however, the remaining relationship between modality and parentage seems modest. Mostly, when a window marked as modal is raised you can block events in the other windows and let the current one do its thing. But there's a catch: what about windows raised in the process of using that modal window?
4. It seems like those break down into two categories: "Windows" at the widget level that are just parts of the modal window, like the matrix widget, and "true" top-level windows. I take it the code can already differentiate between these cases, and GDraw isn't setting any transients and such for the first category of window. If that's right (is it?) then the only concern is new top-level windows. 
5. So the question boils down to: How do you differentiate between a window raised by a modal window and a "spurious" new window, perhaps raised by the action of some script or background process, or as a weird side-effect of interacting with the model window? That's the actual problem given the current modality model. 
6. First sub-question: How much does this really matter? Suppose you were to ignore parentage entirely and just do things in terms of time: i) When a modal window is raised, all windows raised before that are blocked. ii) This convention also applies to a modal window raised in the process of using a modal window; the earlier one and any other windows opened in the interim are blocked, the most recent modal window and windows opened more recently aren't. This doesn't handle "spurious windows", but are there actually any spurious windows? And if there are in rare cases, could those be treated as bugs to fix? 
7. Suppose it does matter after all. In that case maybe we could concentrate on a solution for tracking parentage properly just in these cases: windows raised by modal windows. That seems like a much more contained problem than trying to track it correctly in all cases: When a modal window is raised, any previous windows are grabbed, and the problem is reduced to the question: With respect to any new *non-modal* window, is this a proper child of our current modal window? If it is not then suppress events, otherwise don't. Note that this is probably not "free": you might have to alter the code around raising windows from modal contexts. But it could be a viable and contained way forward.

**Comment by skef** [comment]
Consider this implementation of 6 above:

* The data structure is a stack of lists of windows. 
* When a new *modal* window is raised: Push a new list onto the stack with the window as its entry.
* When a modal window is closed: Pop its stack. If any windows remain on its list (*ugh*), add them to the list now at the top of the stack, if any. 
* When a non-modal window is opened: add it to the current list, if any.
* When a non-modal window is closed: Remove it from whatever list it appears in, if any. 
* With respect to individual events in the loop: If it's for a window in the list at the current top of the stack, let it through. Otherwise drop it. 

I say "if any" because there's no reason to track windows opened when there are no modal windows opened. They can be considered part of an implicit "zero list".

**Comment by jtanx** [comment]
So I'll just jot down a couple of notes I had made mentally, which probably answers a couple of the questions.

To set the modal hint, GDK docs imply that [you must have made it transient prior](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-set-modal-hint). GTK is less strict in the [wording of it](https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-modal).

The reason this wasn't really a problem for the X11 backend is because the last transient window never really gets unset (there's less strict cleanup that goes on), so it will happily make something transient to it, even if that window is about to go away (or perhaps is already gone)

I'd preferably like to keep this transient logic simple, having to maintain a stack of lists sounds like a pain. I'd think that what you almost want is an MRU list of active windows, but again, that's a pain to manage.

For this case in particular, I was thinking of changing the cleanup logic, to allow tranients/modals on dying windows, since that's what the old backend would have done anyway. The other issue can be solved by allowing more events to count against what sets the last nontransient window.

**Comment by jtanx** [comment]
Alright, I've looked at this a bit more, there's at least a couple of problems with the current appproach:

```c
    if (gw->transient_owner != NULL && gw->isverytransient && !gw->transient_owner->is_dying) {
            gdisp->last_nontransient_window = gw->transient_owner;
        } else if (!gw->istransient && !gw->is_dying) {
            gdisp->last_nontransient_window = gw;
        }
```

That transient_owner is not guaranteed to not be transient itself, depending on how the window was constructed - for popup dropdown lists, the transient owner can be a transient. So at the least, `last_nontransient_window` is a misnomer.

We also actually allow child windows to be set as the `last_nontransient_window` - as you noted, this doesn't really make sense; I'm not sure what gdk does in this case.

Outside of just fixing these, I can think of a couple of things that would make this scenario of not being able to interact with anything much less likely (or eliminate it altogether).
