### ISSUE TITLE
No font created

### ISSUE THREAD

**Issue by ipickedthis** [fontforge/fontforge#3625]
Running windows 10. Trying to create a font from png files that I have fully cropped.

They import seemingly ok. I imported 3 (abc) to test. 
The X for letter A is gone and the box is now blank, however B and C still have the X.

However the issue I am having right now is when generating the font, I cannot see any font file in explorer. I also created a folder for it to save in, that folder doesn't show up either. So I go to do it again and in FF save window, i see both the folder and the font file.

I get no noticeable errors. 

microsoft wanted to reject the installer but I "installed anyway". firewall also sandboxed the installer. But it all seems to function without complaint.

very strange that it can see the folder and the font file but windows cant.

**Comment by ctrlcctrlv** [comment]
Sorry, this issue is incomprehensible. Please upload your SFD and tell us what kind of font you are trying to generate. A screencast may help as well.

**Comment by skef** [comment]
Closing this. Can reopen if the submitter comes back with more info.
