### ISSUE TITLE
IRC channel? Discord server? Gitter.im?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3640]
Hey,

As part of my attempts to replace #3617 with better code, I've hit tons of snags in FontForge's GUI code.

But that's not what this is about. I just wish us developers had a way to communicate and get help from each other that wasn't completely issue based. I'd feel a lot more confident asking questions if I didn't have to mention people by name to know they'd see it.

I therefore volunteer to make a chatroom, but I just want to know what you'd all prefer. I prefer IRC, but I also see the benefit of gitter.im in helping people ask FontForge questions.

I also think that the whole "users need to email the mailing list for questions about using FontForge" is really outdated, and this issue tracker is used like a forum far too often.

What do you guys think?

**Comment by frank-trampe** [comment]
This might be feasible and useful for active developers to confer with
active developers, but it is less likely to work for general support. In
particular, unless you have a way to get the people who currently help on
the mailing list to be present in the chatroom, those needing help will
still end up falling back to the mailing list most of the time.

**Comment by ctrlcctrlv** [comment]
@frank-trampe Sure, understood. If it was an IRC channel, I'd make sure to put the mailing list in the topic. I don't want to replace the ml, but I do recognize that young people are unlikely to know how to use one, and may decide to just give up rather than learn how. If we use gitter.im, I'd split us into two channels, one for users and one for devel.

I'd be willing to help answer questions, and I've developed a few fonts with FontForge, so have at least some relevant experience.

**Comment by ctrlcctrlv** [comment]
Closing due to lack of interest
