### ISSUE TITLE
Crash when doing Control+O to open file on macOS High Sierra

### ISSUE THREAD

**Issue by gingerbeardman** [fontforge/fontforge#3641]
# Steps
1. Run macOS 10.13.6
2. Open FontForge version 20190317
3. Press Control+O or choose it from the menu

# Actual
- Crash

# Expected 
- Show file selector

### When reporting a bug/issue:
- [ ] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [X] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

Crash dump:
https://gist.githubusercontent.com/gingerbeardman/bbeffec46a7ce4e12b2b0af65b05c3b4/raw/28427a658f29fdf56f2949aeba1abfafcea31611/gistfile1.txt

**Comment by jtanx** [comment]
This is likely a duplicate of #3609, would you be able to confirm if the latest build from https://dl.bintray.com/fontforge/fontforge fixes it for you?

**Comment by gingerbeardman** [comment]
@jtanx yes, that fixes it - thanks!

(might be an idea to sort that page so most recent builds are at the top, I inadvertently downloaded the top 2016 build until i realised)

**Comment by jtanx** [comment]
Thanks for confirming. I'll try to get out a new release with that fix in. As for that web page, the formatting is not under our direct control, unfortunately

**Comment by gingerbeardman** [comment]
If you can put files in that directory you should be able to put some index configuration in there also?

**Comment by jtanx** [comment]
Nope, it's literally just what [bintray](https://bintray.com/fontforge/fontforge/fontforge-travis) provides.  We could of course provide some sort of interface to it, but this works well enough.
