### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#3642]
I'm looking at cutting a new release, likely some time this week, probably the weekend. This is more of a 'recovery' style release for the previous release - most prominently for #3641 and related issues, which is pretty bad.

**Comment by ctrlcctrlv** [comment]
@jtanx Will #3645 be in the release? I understand if it's too late, but I'd like users to test it.

**Comment by jtanx** [comment]
No, the only reason I'm cutting this release is to fix some bugs picked up from the previous release, and I have some bigger changes planned after.

**Comment by ctrlcctrlv** [comment]
@jtanx OK, hoping you can review #3645 and that there's no big merge commit or anything :)

**Comment by skef** [comment]
I take it there's little chance of a fix or some harm reduction for #3611-area problems on that schedule?

**Comment by jtanx** [comment]
I'll try, I did have some code kicking around, but not still need to test it out a bit more

**Comment by jtanx** [comment]
For inclusion: #3605, #3648 (not withstanding any major issues with it)

**Comment by jtanx** [comment]
Alright, I'll cut this in the next couple of hours

**Comment by jtanx** [comment]
Released.

**Comment by skef** [comment]
Thank you for this -- the combination of the improvements in the earlier release and the fixes here make for a good overall package.
