### ISSUE TITLE
Outdated Unicode 12.1 beta

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3644]
FontForge 20190317 claims to support Unicode 12.1. In fact, it uses an old beta version of 12.1, since which the name and names list entry of U+32FF have changed.
```pycon
>>> import fontforge
>>> print(fontforge.version())
20190317
>>> print(fontforge.UnicodeNamesListVersion())
Nameslist-Version: 12.1
>>> print(fontforge.UnicodeNameFromLib(0x32FF))
SQUARE ERA NAME SAYUU
>>> print(fontforge.UnicodeAnnotationFromLib(0x32FF))
	• temporary placeholder for actual reign name TBD
	≅ <square> 5DE6 53F3
```

**Comment by JoesCat** [comment]
more info: http://www.unicode.org/Public/

**Comment by JoesCat** [comment]
previous 4 years seemed to be announced approximately June, and most also were x.0, like 8.0, 9.0, 10.0, 11.0
12.0 came earlier than the previous 4, I just happened to look at the site and saw the announcement for 12.0, but looking at the info there was already a 12.1.0 d1 available, so I used that instead, which now the nameslist.txt is d3 for April 8th. and also includes your fix.
Seems 12 came early, and wasn't as stable a release like the prior few years.
Seeing a d3, I guess there might be some more bumping up.
If the French list is updated, it will look like a good time to also update the namelist too, to whatever d version is available, but for now, it may be best to provide a stable release for the distros to use.
If you need the latest, latest, this is where the nameslist.txt came from, and there are probably a few users that may need it, but I think most user may be ok with almost latest available right now.
Thanks for checking & hope this answer looks ok.

**Comment by dscorbett** [comment]
Unicode 12.0 was released earlier than usual because the Unicode Consortium has decided to start releasing in March from now on. It doesn’t mean version 12.0 was unstable. They will release version 12.1 so soon after 12.0 because of the timing of the Japanese emperor’s abdication, i.e. it’s just a coincidence. [L2/18-220](https://www.unicode.org/L2/L2018/18220-u121planning.txt) has more details.

In general, I recommend not using beta versions of Unicode in FontForge releases.

**Comment by dscorbett** [comment]
Unicode 12.1 is out and this bug is no longer in the latest FontForge.
