### ISSUE TITLE
Add the ability to navigate to, and open TTF/OTF's from, external drives

### ISSUE THREAD

**Issue by cssobral2013** [fontforge/fontforge#3646]
If this issue is already open, feel free to close it.

**Comment by JoesCat** [comment]
Uncertain what you mean by external drive. Can you provide an example?

**Comment by cssobral2013** [comment]
By "external drive" I mean other than internal HDD/SSD.

Em Qui, 11 de abr de 2019 12:47, Joe <notifications@github.com> escreveu:

**Comment by skef** [comment]
To make a guess: Are you a Windows user, and are you having trouble accessing files on a volume of a different letter, as in Windows is installed on `c:` and you need to get at a file on `d:`?

**Comment by cssobral2013** [comment]
Specifically, I need ways to navigate to a USB thumb drive, this's because
I have several of them.

Em Qui, 11 de abr de 2019 15:11, skef <notifications@github.com> escreveu:

**Comment by skef** [comment]
@cssobral2013: You say "specifically" without confirming the previous suggestion. Can you please indicate whether or not my description applies, and ideally provide an example of a pathname (for example `/usr/local/lib/foo.sfd` or `r:\foo\bar.sfd`) that you can use to access the file through the OS but can't through FontForge?

**Comment by cssobral2013** [comment]
It is on H:\*. sfd.

Em Qui, 11 de abr de 2019 17:07, skef <notifications@github.com> escreveu:

**Comment by cssobral2013** [comment]
I'll reproduce the steps once my PC is available.

Em Qui, 11 de abr de 2019 17:13, Cristiano Sobral <cssobral2013@gmail.com>
escreveu:

**Comment by jtanx** [comment]
You can do this, but to do so you'll have to manually change drives by entering `H:/` like so:
![image](https://user-images.githubusercontent.com/5137410/55993807-5b4b9880-5cf3-11e9-9ba2-146d30a22489.png)


and pressing ok/hitting enter.

The browser only shows one drive at a time.

**Comment by cssobral2013** [comment]
@jtanx, thank ya for the help. This issue can be closed, then.

**Comment by frank-trampe** [comment]
@jtanx, I'm glad somebody here has Windows!

**Comment by ctrlcctrlv** [comment]
I noticed this too on Windows. And even on Linux it's not exactly user friendly to navigate to a mount point when for most users, udev is deciding that mount point and not them, FontForge being one of the few GUI programs that doesn't list udev/udisks mount points

**Comment by skef** [comment]
GTK offers both native and non-native file dialogs. The disadvantage of the former is that you can't add controls to them, and FontForge leans on added controls pretty heavily.

I made a prototype of a GDK/GTK that would make it pretty easy to swap in GTK file dialogs in the GDK version of the software. And obviously if @jtanx ports to GTK it would be even more straightforward. Using the native dialogs would require some thought about alternatives to those added controls. Anyway @jtanx knows where the bridge code is.
