### ISSUE TITLE
Suspicious strcmp in scstyles.c

### ISSUE THREAD

**Issue by rikardfalkeborn** [fontforge/fontforge#3647]
The following snippet of code looks suspicious:

https://github.com/fontforge/fontforge/blob/c8cb445e3414678cba91ac7707b603332966bdae/fontforge/scstyles.c#L4403-L4404

Is there a missing == 0 after the last `strcmp()`?

**Comment by frank-trampe** [comment]
Agreed. Setting smallcaps true whenever ".small" is not present makes no sense. Pull request incoming?

**Comment by rikardfalkeborn** [comment]
> Agreed. Setting smallcaps true whenever ".small" is not present makes no sense. Pull request incoming?

Sure thing. I'll try to look at it tonight.
