### ISSUE TITLE
Error when generating fonts witn MathKerning

### ISSUE THREAD

**Issue by YuanshengZhao** [fontforge/fontforge#3649]
### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

Ver: Build 2019-3-17; Windows 10.
To reproduce:
- Create a new file, draw anything in glyph `A` and `B`;
- Create a `Math Kerning` for `A`, and link `B` as a `vert. Variants` of`A`;
- Save file;
- Generate OTF.

And the `Math Kerning` and `Vert. Variants` info is missing in the OTF.
This seems to be the problem of the newest version, the old version does not have this issue.
The `sfd` file is attached here: [bug.zip](https://github.com/fontforge/fontforge/files/3074072/bug.zip)

Screen shots:
Create and Save
![image](https://user-images.githubusercontent.com/37881856/56049947-926a8a00-5d85-11e9-9f18-aca5597e9f00.png)
![image](https://user-images.githubusercontent.com/37881856/56049977-a0b8a600-5d85-11e9-94d5-bc1372b49a6b.png)
![image](https://user-images.githubusercontent.com/37881856/56049991-add59500-5d85-11e9-90ae-77daefe49a28.png)
![image](https://user-images.githubusercontent.com/37881856/56050071-deb5ca00-5d85-11e9-9bf6-1c1209ac7bd2.png)
Error (open the generated OTF):
![image](https://user-images.githubusercontent.com/37881856/56050170-1d4b8480-5d86-11e9-9c26-a9ae2ae14c20.png)
![image](https://user-images.githubusercontent.com/37881856/56050195-2b010a00-5d86-11e9-87dd-8236a64d7614.png)

**Comment by frank-trampe** [comment]
What is the last version that worked correctly?

**Comment by YuanshengZhao** [comment]
2017 release works correctly.

**Comment by skef** [comment]
I did some extra flag cleanup on a @ctrlcctrlv fix and might have fat-fingered something. I'll take a look at this.

**Comment by skef** [comment]
Damn those non-email-generating comment edits ...

Given the confirmation that there isn't a known earlier version, I think I know what the problem is. Let me ask: Does this happen if you create the file and generate without saving/loading? Or when you were trying this did you always save and restart in between?

**Comment by skef** [comment]
Never mind about that question; turns out not to matter.

**Comment by YuanshengZhao** [comment]
I found that in the SFD file saved, there is no `MATH: ???? : ?` info;
If I open the `Element -> Other Info -> MATH Info` dialog and `OK`, then save file, the `MATH: ???? : ?` info will be in the SDF header.
And there is no problem with the OTF generated.

**Comment by jtanx** [comment]
@YuanshengZhao  can you try https://ci.appveyor.com/api/buildjobs/mech5t608cu90kej/artifacts/fontforgebuilds%2FFontForge-mingw-w64-i686-33a1b1-gdk3-appveyor.7z to see if it's fixed?

**Comment by YuanshengZhao** [comment]
Looks good. Though this version will not save recent files, etc(?)

**Comment by jtanx** [comment]
Thanks, by that do you mean it can't save files at all, or it doesn't show any recent files that you worked on? 

If it's the first, that's a known issue (tmpfile failures) and for the second, that's probably because it's a portable build, so the location it stores preferences is different.

In any case, it should be fine for the actual release builds

**Comment by skef** [comment]
> I found that in the SFD file saved, there is no `MATH: ???? : ?` info;
> If I open the `Element -> Other Info -> MATH Info` dialog and `OK`, then save file, the `MATH: ???? : ?` info will be in the SDF header.
> And there is no problem with the OTF generated.

That's consistent with what I found in the source.
