### ISSUE TITLE
Weird glitches when trying to edit uni1f200 (🈀)

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3653]
Arch Linux, https://github.com/fontforge/fontforge/commit/1dd7f9cf651f30309af7a3fdcb96e1fdc24cc505

Does FontForge actually support editing glyphs outside the BMP?

Because the font view becomes glitched when attempting to access one.

![hoka](https://user-images.githubusercontent.com/838783/56074626-85cb4d80-5de8-11e9-9bc6-c9d3379a375f.png)

Reproduction steps:

1. New font
2. Goto
3. `uni1f200`
4. Glitched fontview. Can't scroll, but arrow keys work.
5. If I attempt to double click on the glyph purporting to be 🈀, the fontview remains glitched, but changes slightly. Now arrow keys don't work. Putting something in the 🈀 doesn't help.

![hoka2](https://user-images.githubusercontent.com/838783/56074660-1013b180-5de9-11e9-902d-0b78b06d71b5.png)

**Comment by jtanx** [comment]
Seems to work ok here:
![image](https://user-images.githubusercontent.com/5137410/56075165-5543dd80-5e01-11e9-8d69-8d64fb7ffbe3.png)

**Comment by ctrlcctrlv** [comment]
Really? Let's try to figure out what's different. You're testing on GDK3 I'm sure, so what else
 should I check?

**Comment by jtanx** [comment]
What's your libuninamelist version? I built off master, granted with my meson patches. I'll try again off a vanilla master branch

**Comment by ctrlcctrlv** [comment]
libuninamelist is @ 20190305

**Comment by jtanx** [comment]
weird, I don't get how the description is different then

**Comment by ctrlcctrlv** [comment]
@jtanx Looks like you're not building with it, even though you have it installed, because your screenshot shows the block name, not the glyph name.

**Comment by jtanx** [comment]
Ah yeah that's totally possible, I didn't add libuninameslist detection into the meson build procedure

**Comment by ctrlcctrlv** [comment]
I just tried a build without `libuninameslist`, and that made no difference, unfortunately.
![hoka3](https://user-images.githubusercontent.com/838783/56075306-db0c5c80-5df2-11e9-9bb8-0ae34d59d286.png)

**Comment by jtanx** [comment]
How are you running fontforge? Because it looks like some of the preferences aren't being loaded (otherwise the fontview background would be white)

**Comment by ctrlcctrlv** [comment]
```
[fred@pc fontforge2]$ cat run_fontforge.sh 
#!/bin/sh
libtool --mode=execute gdb -ex "run $1" fontforgeexe/fontforge
```

I use this script for all my development.

**Comment by ctrlcctrlv** [comment]
Installing unfortunately made no difference. :disappointed: 

![hoka4](https://user-images.githubusercontent.com/838783/56075365-1a877880-5df4-11e9-8d96-cc5f2a86aa0d.png)

**Comment by jtanx** [comment]
So a vanilla x11 build works just fine for me, testing again with gdk

**Comment by jtanx** [comment]
Yeah, I'm stumped, all of those modes work just fine for me.

**Comment by ctrlcctrlv** [comment]
@jtanx On a hunch, I tried something. I did **View &rarr; Label Glyph By &rarr; Unicode**, and that works fine. I therefore think this is likely to be a font rendering issue. If I do **View &rarr; Label Glyph By &rarr; Glyph Image**, then press e.g. **&uarr;**, it glitches again, and still retains the hex codes and not the images.

![hoka5](https://user-images.githubusercontent.com/838783/56075655-908dde80-5df8-11e9-94a6-6ed131b65a04.png)

**Comment by ctrlcctrlv** [comment]
@jtanx I figured it out!! :dancer: 

![yes!](https://user-images.githubusercontent.com/838783/56075794-e5caef80-5dfa-11e9-8648-b6fa9d057fe4.png)

My hunch was correct. I ran FontForge with `FC_DEBUG=4`, which showed me that for some reason `Noto Color Emoji` was being loaded as a fallback font.

Unfortunately, my "fix" is uninstalling the font, but now we know what's wrong so we can fix it - right? Any idea why this helped? Can you please try installing Noto Color Emoji?

**Comment by jtanx** [comment]
Nice find, although weirdly it still works for me (I installed `fonts-noto-color-emoji`, this is on ubuntu 18.04)

![image](https://user-images.githubusercontent.com/5137410/56075861-81189080-5e0c-11e9-8906-75d9eeb87a3c.png)

**Comment by ctrlcctrlv** [comment]
Maybe it's bundling an old version of that font? I am using Arch after all.

**Comment by jtanx** [comment]
It could also just be some pango bug

**Comment by ctrlcctrlv** [comment]
Another astute observation. 

```
cairo and cairo-git are in conflict. Remove cairo-git? [y/N] y```

(I was using `cairo-git` so I could provide better backtraces a long time ago for another issue.)

Not using my custom built `cairo` fixed it completely. Most likely it had bugs not yet worked out. Sorry for wasting your time, thanks as always for the help in debugging.

![hoka6](https://user-images.githubusercontent.com/838783/56075923-abfae880-5dfc-11e9-8505-2df9902f43da.png)

**Comment by jtanx** [comment]
no worries, glad we got to the bottom of that

**Comment by ctrlcctrlv** [comment]
@jtanx yeah and if this happens again after a cairo update I'll let you know. Hopefully they won't release with whatever is causing this in it.
