### ISSUE TITLE
Another issue with MathKern

### ISSUE THREAD

**Issue by YuanshengZhao** [fontforge/fontforge#3654]
Ver: Build 2019-3-17; Windows 10
- Create a new file (encoding: unicode) and create 4752 (approx value, or more) glyphs (the content of the glyphs does not matter), save SFD file;
![image](https://user-images.githubusercontent.com/37881856/56074858-3ee35500-5df4-11e9-956f-6766fc86785f.png)
- Create Math Kern: use a text editor (Ex. VS Code) to create Math Kern for each glyph (again the detial does not matter). Now each glyph looks like this:
![image](https://user-images.githubusercontent.com/37881856/56074837-0e9bb680-5df4-11e9-8afc-bf95a99d36b1.png)
- Open the SFD, and generate OTF, an error will occur.
![image](https://user-images.githubusercontent.com/37881856/56074898-b6b17f80-5df4-11e9-9649-07fdd4ce45ef.png)

This happens only when the number of glyphs exceeds some value. If there is less glyphs there is no error. So it seems to an overflow of some varaibles (?).

The demo sfd file: 
[Untitled1.zip](https://github.com/fontforge/fontforge/files/3075759/Untitled1.zip)

**Comment by skef** [comment]
Does it do this if you uncheck "Windows-compatible 'kern'"? As I recall the purpose of that flag is to limit the `kern` table to the number of entries (certain versions of) Windows can deal with. It's also possible to output more values to that table using "Old style 'kern'" (again if I'm remembering correctly).

**Comment by ctrlcctrlv** [comment]
I thought Math kern uses its own table (`MATH`), not the `kern` table @skef

**Comment by skef** [comment]
That may be true. But in that case the "Windows-compatible" flag might limit the number of entries in `MATH` as well.. I don't know enough about the relevant issues to have a more specific idea without inspecting the code, and it's worth a shot trying a few flag combinations first.

**Comment by YuanshengZhao** [comment]
The problem remains for all the 4 combination of check/uncheck `Windows-compatible Kern` and `Old style Kern`.

**Comment by skef** [comment]
Well, looking more closely at the spec, the offsets in the header from the start of the table to the start of each subtable are 16 bits. So the short answer is that there may be some weird alternate encoding available to overcome this size limitation (or there may not be), but FontForge doesn't appear to have any knowledge of it if there is one. I suggest investigating whether what you hope to do is actually possible given the specification, and if it is we could take another look.

**Comment by skef** [comment]
There is documentation about the OpenType MATH table [here](https://docs.microsoft.com/en-us/typography/opentype/spec/math)

**Comment by YuanshengZhao** [comment]
As far as I know, therre is no way to avoid it. (Usually there is no need for so many, I discovered this because I made a mistake in making font by adding ~1300 meaningless zero kerning)

Though, I cannot understand why 16 bit int (~65535) is not enough, as there is only ~5000 glyphs (please forgive my ignorance...).

**Comment by skef** [comment]
The 16 bits is an offset, basically a relative pointer to an address. So it would be plenty if each of your entries only had one byte per glyph, but that's probably not the case. Twelve bytes per glyph at 5000 is already 60000 bytes. To figure out exactly where the memory is going we'd have to do some analysis on the particular entries.

**Comment by YuanshengZhao** [comment]
I see, thanks. It is probably an reality that the number of Math Kern allowed is very limited.

**Comment by skef** [comment]
There may be some way around the limitation in theory, but there's nothing currently in the FontForge code to suggest what that would be. Sorry I can't help more; all I know about this is from a very brief glimpse at the specs.

**Comment by skef** [comment]
Closing this as it's not clear how we would work around the table size limits.
