### ISSUE TITLE
Remove X-based GTK interface

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3656]
In the spirit of #3512 and #3655, another thing that needs to go is the old python GTK interface for gxdraw. This officially Does Not Make Sense Now, even if it could be revived. With a GDK-based GDraw (or some successor) there's no sense in mixing python GTK with the X version of the software -- anyone trying to do something like that would not choose the X stack. 

Main targets:

1. The relevant portions of `fontforgeexe/pythonui.c`
2. The files in `pycontrib/gdraw`
3. `pycontrib/graphicore` (might as well remove this too -- virtually all parts of it are moribund one way or another)

Note that `pycontrib/gdraw/_gdraw.py` tries to import `libgdraw.so.5`, making it an obstacle to library reduction projects. The whole thing is the very archetype of a "fragile" interface. The chances of anyone currently making independent use of it are close to nil, because it's based on the old `pygtk` module rather than the current PyGObject interface.

**Comment by jtanx** [comment]
Nice, I support this. Happy for all of that to go.

**Comment by skef** [comment]
I think I can do this pretty easily. I looked at that code a bit when I was thinking about the GTK bridge (although it turned out be mostly irrelevant to that project). I never did figure out exactly how the main loop worked -- only pieces. 

I'll follow up after #3655.

**Comment by frank-trampe** [comment]
There is no doubt in my mind that the GTK functionality in question has had zero users in years. No need to ask on the mailing list. Less sure about the Python shell. Does it actually work? I've never touched it.

**Comment by skef** [comment]
I put some effort into getting graphicore working and it's too reliant on a) the titular functionality and b) a very old version of IPython no one would have on their system anyway. The IPython-related pieces are in flux and something might be doable after some time has passed. (The blocker is an updated version of https://gitlab.gnome.org/GNOME/accerciser/blob/master/plugins/ipython_view.py , which is (or was) lagging behind IPython itself.) 

Regardless, it would almost certainly need to either be reimplemented "natively" or based on GGDKDraw (or a successor). That's the better way to go for "contributed" stuff anyway, because it has a chance of working on more platforms.

**Comment by skef** [comment]
"For the record": The version of our check-in `ipython_view.py` is ancient. Accerciser's version has been updated to support IPython 5. I believe the current version is 7, and they removed compatibility with some key earlier interfaces in 6 or 7. I assume Accerciser hand'es this with a requirement and maybe a custom installation, but that would of course be tricky for FontForge at best.

**Comment by frank-trampe** [comment]
It sounds like nobody could possibly be using it (unless using an ancient version of FontForge and thus unaffected by our changes) then. I think it's fine to remove it entirely.
