### ISSUE TITLE
No window has focus after a window is closed

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3675]
Closing a FontForge window does not return focus to the parent window. I am using FontForge 20190413 on macOS Mojave 10.14.4. This is a regression from FontForge 20170731. To reproduce:
* Open FontForge.
* Click “File” then “Open”, or perform any other action that opens a window.
* Close the window.
* Press arrow keys to move around in the main font grid. Nothing happens.
* Click the main window such that it regains focus.
* Press arrow keys to move around in the main font grid. Now it works.

**Comment by ctrlcctrlv** [comment]
I just tried this in Arch Linux and it doesn't happen there, so this is a Mac-only issue, which helps narrow it down.

**Comment by tamcy** [comment]
Would like to add that this also happens on Windows. For instance, on Char View window -> Open Transform dialog -> Close the dialog -> Char view not focused.
