### ISSUE TITLE
Anchor Control scrollbar does not resize automatically

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3681]
In the Anchor Control window, after clicking on a glyph, thus changing which and how many glyphs are displayed, the scrollbar does not update. If the new display is wider than the old display, you can’t scroll all the way to the right. Resizing the window fixes the scrollbar. I am using FontForge 20190413 on macOS Mojave 10.14.4.

**Comment by ctrlcctrlv** [comment]
Do you mind making a screencast of the problem because I can't reproduce it, maybe because I'm not understanding it

**Comment by dscorbett** [comment]
[Here you go.](https://github.com/fontforge/fontforge/files/3135249/Screen.Recording.2019-05-01.at.12.45.42.PM.mp4.zip)
