### ISSUE TITLE
There are duplicate flatpaks on flathub

### ISSUE THREAD

**Issue by n8willis** [fontforge/fontforge#3686]
Trying to install the new release via the fancy-schmancy new flatpak tool, I discovered that flathub.org currently identifies two FortForge packages as separate "refs". One is a spring 2019 build, which uses the org.fontforge.FontForge identifier; the other is a bronze-age 2017 "ref" ID'ed as io.github.Fontforge.

Presumably this is related to #3368, wherein that identifier was changed, but it seems like (if so) some additional step needs to happen to remove the old "ref".

As is, if you try to install FontForge as a 'pak, the CLI tool tells you you have to choose one of the "ref"s ... but it doesn't give you any info to help you make that choice -- not even the release versions. All you see are the IDs (org.fontforge.FontForge and io.github.Fontforge), which is a pretty opaque thing to make a selection from.

It also would appear that only the older "ref" is exposed on the public Flathub application page, since that shows the 2017 release. Probably not ideal. I don't know if axing the old "ref" would clear that up or if it'd require additional work.

Caveat: I don't actually know what "ref"s are supposed to be, in flatpaklingo. It seems like an internal facility that is leaking out by mistake in corner cases like this, since the end-user tools don't help users resolve "ref"-related faults. But I don't know.

**Comment by n8willis** [comment]
![ffpaking](https://user-images.githubusercontent.com/2192132/57150722-f9002800-6dc6-11e9-92c5-d396b41ed1e9.png)

(illustrative attachment of preceding experience for the hard-of-imagination)

**Comment by ctrlcctrlv** [comment]
I don't think this is our problem. If you don't think that this `flatpak` program is intuitive, why not complain to them? All we did was change our `.desktop` definition. Not our fault some third party is archiving it, right?

**Comment by jtanx** [comment]
@muelli maybe?

**Comment by n8willis** [comment]
> I don't think this is our problem. 

If the change to the appdata file is triggering the harm downstream, and harming users is considered a problem, then cause & effect says it is. If the appdata file owner needs to push back on the Flatpak project because they've discovered a problem, so be it; that's no different from interacting with distros or other projects upstream & downstream. Yet it's not a burden for the end users to shoulder.

> If you don't think that this `flatpak` program is intuitive, why not complain to them?

Well, allow me to assure you that I file all sorts of issues, and even occasionally merge things to fix them; just because they don't appear here does not mean that such things do not happen.

**Comment by muelli** [comment]
io.github.Fontforge has been EoLed, cf. https://github.com/flathub/io.github.Fontforge/blob/master/flathub.json and https://github.com/flathub/io.github.Fontforge/issues/1

There is org.fontforge.FontForge now. Seems like a bug in flatpak to not show EoLed packages more (or rather: less) prominently.

**Comment by jtanx** [comment]
I see, thanks. Seems like a flatpak problem them
