### ISSUE TITLE
Need Cidmap files, link provided doesn't have them

### ISSUE THREAD

**Issue by Xyrexus** [fontforge/fontforge#3697]
Just got the program to get a few fonts from a pdf file, I can't generate them without errors presumably because I don't have the cidmap files.

The program gives me an outdated link that does not contain a download for the cidmap files.

**Comment by skef** [comment]
You're probably looking for https://fontforge.github.io/assets/old/cidmaps.tgz

**Comment by jtanx** [comment]
The link should be fixed now.

**Comment by Artoria2e5** [comment]
There are still a few references to the old sourceforge link, and they should be updated too. See https://github.com/fontforge/fontforge/search?q=%22fontforge.sourceforge.net%2Fcidmaps.tgz%22&unscoped_q=%22fontforge.sourceforge.net%2Fcidmaps.tgz%22.

**Comment by migueldvb** [comment]
> You're probably looking for https://fontforge.github.io/assets/old/cidmaps.tgz

Link to cidmaps files is broken.

**Comment by jtanx** [comment]
It's fixed again (on  the old path) - either https://fontforge.org/cidmaps.tgz or https://fontforge.org/downloads/cidmaps.tgz will work.

**Comment by AurusHuang** [comment]
The links does not work as of today. I can only download a plain text file disguised as tgz, which content is "assets/old/cidmaps.tgz".

**Comment by jtanx** [comment]
Sorry about that, this should be fixed now, there was one other symlink that needed fixing.
