### ISSUE TITLE
Underlined letters are no longer keyboard shortcuts

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3702]
The labels of various elements of the UI, e.g. the menu bar and buttons, include underlined letters. In older versions of FontForge, those letters indicated keyboard shortcuts. For example, ⌥F opened the “File” menu. In FontForge 20190413 on macOS Mojave 10.14.4, the underlines are still there but the keyboard shortcuts don’t activate the associated UI elements.

**Comment by frank-trampe** [comment]
@jtanx, this does not happen for me on Ubuntu, which makes me think that it's a Macintosh thing. Are you in a position to test?
