### ISSUE TITLE
`brew install fontforge` introduces missing pipenv environment and downgraded postgresql postgresql

### ISSUE THREAD

**Issue by cjm771** [fontforge/fontforge#3704]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

When installing on mac os x 10.14.4/5 mojave, our pipenv virtual environment seems to get corrupted forcing us to remove it. Also it downgrades  postgresql from 11 -> 10.8.  Assuming it s an issue with the brew package possibly?

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
10.14.4-5 mojave

- [x] The behavior you expect to see, and the actual behavior
fontforge, and existing virtualenv / postgres unchanged (likely brew issue)

- [x] Steps to reproduce the behavior 
`brew install fontforge`
- [x] \(optional) Possible solution/fix/workaround
 to work around had to reinstall pipenv and also reconfigure postgresql.

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
Please file this at homebrew/homebrew-core thanks.
