### ISSUE TITLE
Metrics window is not repainted when I type a new kerning value

### ISSUE THREAD

**Issue by janpe2** [fontforge/fontforge#3720]
When I type a new kerning value in the Metrics window (see the circled text field in my screen shot), the glyphs don't move. The kerning data is changed but the problem is only in the preview that is not repainted. If I type a new side-bearing value, there is no problem with repainting.

- [x] Screenshot
- [x] The FontForge version and the operating system you're using: FontForge-2019-04-13. Windows 7 and Windows 10.
- [x] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

![FontForge_Metrics_bug](https://user-images.githubusercontent.com/26090208/58910366-fffbbc80-871d-11e9-8e21-d20b62ef9b53.png)

**Comment by ctrlcctrlv** [comment]
I have this problem too. You can force a repaint for now by adding and removing e.g. a space to the end of the string being examined. 

This should be fixed, I think it's always been this way though

**Comment by ctrlcctrlv** [comment]
Hey @janpe2, thanks for the bug report. I actually have dealt with this bug for years, and in a form of Stockholm syndrome, just put up with the annoyance and no longer thought about it as a bug _per se_. Your helpful comment led me to figure out why this happens in the first place, and I believe I've fixed it. If you could try out my patch, #3721, I'd appreciate it!

**Comment by janpe2** [comment]
Thank you. Unfortunately I don't currently have tools to test your PR, so I must wait for the next release of FontForge.
