### ISSUE TITLE
How to assign hotkeys to Numpad?

### ISSUE THREAD

**Issue by TangoBat** [fontforge/fontforge#3724]
I'm trying to assign Zoom In/Out to Numpad-/Numpad+ respectively, but I haven't been able to find any information regarding the keywords for numpad assignment. In ..fontforge\hotkeys\default I've tried setting "CharView.Menu.View.Zoom out" to: "Numpad+", "Numpad++", "Number pad +" and other similar combinations but none of them are working.

**Comment by ctrlcctrlv** [comment]
@skef might know

**Comment by skef** [comment]
I'm not sure if this will work, but it's worth a shot. 

As the Hotkey parser tries to parse a shortcut, it checks each portion against a set of known strings (like "Tab"). If it doesn't find a known string it tries to read a UTF-8 character. It then uses that character as the so-called "keysym". 

There's currently no string corresponding to those numeric keypad keys. But they do have keysym numbers defined by the underlying support layer, which happen to be the same across all three "modes (GDK, X, display-less). Numpad + (or as it is generally known `_KP_Add`) is 0xFFAB, and Numpad - (`_KP_Subtract`) is 0xFFAD. So if you can trick FontForge into reading those values from your hotkey file, it might work out for you. 

Given that FontForge is trying to read a UTF-8 character and interpreting it numerically, you'll want to add [HALFWIDTH HANGUL LETTER RIEUL-MIEUM](https://www.fileformat.info/info/unicode/char/ffab/index.htm) for `_KP_Add` and [HALFWIDTH HANGUL LETTER RIEUL-SIOS](https://www.fileformat.info/info/unicode/char/ffad/index.htm) for `_KP_Subtract`. But most likely the character identities don't matter. You'll just want to edit the file in some editor that 1) knows it's encoded as UTF-8 and b) lets you add characters by unicode codepoint. Then just do 0xFFAB and 0xFFAD respectively.

**Comment by skef** [comment]
Hey, I tried it and it worked. Who would have thunk?

**Comment by ctrlcctrlv** [comment]
# ʕ •ᴥ•ʔ .｡o ( ﾫﾫﾫﾭﾭﾭ )
# ┬─┬ノ( º _ ºノ)

**Comment by skef** [comment]
Either you have better fonts configured in your preferred Arch web browser or that bear is thinking about six rectangles.

**Comment by ctrlcctrlv** [comment]
![2019-06-09-144102_1018x418_scrot](https://user-images.githubusercontent.com/838783/59155878-7dc81b00-8ac4-11e9-8c56-7836c5bcb2f1.png)

He's thinking about FFAB and FFAD, hehe.

**Comment by skef** [comment]
I can't argue with the self-evident fact that I would have thunk!

**Comment by TangoBat** [comment]
@skef That worked, thank you so much! I was able to add them using Notepad++ and Windows Character Map.

For others who have the same issue on Windows 10:

1. Open the hotkeys file (  %programfiles(x86)%\FontForgeBuilds\share\fontforge\hotkeys\default ) in Notepad++. In the "Encoding" menu at the top, it's set to "UTF-8"
2. In the `Start` menu, type in `Run` then hit `Enter` to launch 
3. In the "Run" app, type in `charmap` then hit `Enter` to launch (you should probably pin/make a shortcut for Character Map for later use)
3. In the Character Map app, click the `Advanced View` checkbox at the bottom
4. Make sure "Charater Set" is set to "Unicode". In the "Go to Unicode" box to the right, enter the code for the character you want (`FFAB` for `Numpad+`, `FFAD` for `Numpad-`)
5. The characters will show up in the "Characters to Copy" box. Simply copy the characters and paste them into the corresponding line in the hotkeys file, you'll see the same glyph that was shown in the Character Map window.
