### ISSUE TITLE
No GSUB information available for a font with GSUB

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3734]
The GSUB tab of “Font Information” for [NotoSerifTibetan-Regular.ttf](https://github.com/googlefonts/noto-fonts/blob/2a41389346abdb6b83f5e0c4efe598bcb8abbb42/phaseIII_only/unhinted/ttf/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf) is empty, but that font has a GSUB table. I am using FontForge 20190413 on macOS Mojave 10.14.5.

**Comment by ctrlcctrlv** [comment]
If you try to re export the font, does FontForge write a GSUB table, even if it doesn't show one in the UI?

**Comment by dscorbett** [comment]
It writes an empty GSUB table:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.39">

  <GSUB>
    <Version value="0x00010000"/>
    <ScriptList>
      <!-- ScriptCount=3 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=0 -->
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
      <ScriptRecord index="1">
        <ScriptTag value="latn"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=0 -->
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
      <ScriptRecord index="2">
        <ScriptTag value="tibt"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=0 -->
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
    <FeatureList>
      <!-- FeatureCount=0 -->
    </FeatureList>
    <LookupList>
      <!-- LookupCount=0 -->
    </LookupList>
  </GSUB>

</ttFont>
```

**Comment by skef** [comment]
The diagnosis for this is quite simple. When you open the font you get a warning "Too many lookups 1164". Dump the font with `ttx` and that number can be confirmed: 
```
$ grep "Lookup index" NotoSerifTibetan-Regular.ttx | tail -3
      <Lookup index="1161">
      <Lookup index="1162">
      <Lookup index="1163">
```
The error is coming from `readttflookups()` in `parsettfatt.c`:
```
    fseek(ttf,pos,SEEK_SET);
    info->lookup_cnt = cnt = getushort(ttf);
    info->cur_lookups = NULL;
    if ( cnt<=0 )
return( NULL );
    else if ( cnt>1000 ) {
        LogError( _("Too many lookups %d\n"), cnt );
        info->bad_ot = true;
return( NULL );
    }
```
The fix boils down to a few questions:

1. Is the sanity check worth it? It's basically meant to protect the application environment against corrupt files.
2. If the sanity check (and the other similar checks) is worth it, what should the limit be? 
3. Regardless of the answer for 1 are there any other points in the code depending on the limit value explicitly or implicitly?

**Comment by ctrlcctrlv** [comment]
The check isn't worth it, it should be removed. At the most there should be a warning if there are over _n_ lookups, but 1000 is way too slow. I checked a few projects and none of them seem to limit the number of lookups; HarfBuzz for example doesn't limit lookups, the only limit I could find was a recursion limit.

**Comment by skef** [comment]
Before I code anything up, is the evidence the same for the similar checks (like features)?

**Comment by ctrlcctrlv** [comment]
Yes
