### ISSUE TITLE
Remove overlap doesn't work

### ISSUE THREAD

**Issue by monikazxcvbnm** [fontforge/fontforge#3748]
I'm new to fontforge and maybe I'm doing something wrong, but removing the overlay doesn't work. I mark all the points, both the letter and the glyph, I click "remove ovelap" and nothing happens. There is no information about the error, but the letter and glyph are not connected.
I am using windows 10, and the fontforge version:
![Screenshot_4](https://user-images.githubusercontent.com/52152454/59999641-c7873880-9662-11e9-8754-f0f71e942a3d.png)

This is the letter before the "remove overlap" click:
![Screenshot_1](https://user-images.githubusercontent.com/52152454/59999670-d110a080-9662-11e9-8b2e-b960d3cd280d.png)

And this is how it looks after:
![Screenshot_2](https://user-images.githubusercontent.com/52152454/59999679-d8d04500-9662-11e9-9d9b-794af50df69d.png)

**Comment by frank-trampe** [comment]
Any chance we could get the file?

**Comment by monikazxcvbnm** [comment]
Yes, sure. I tried to make the "ą" letter here.
[Kirvy-RegularEdit.zip](https://github.com/fontforge/fontforge/files/3321031/Kirvy-RegularEdit.zip)

**Comment by frank-trampe** [comment]
@monikazxcvbnm, the overlap removal is working as expected here. Your accent is drawn counter-clockwise, which makes it a negative shape. The end result has the overlap cancelled out and the two paths otherwise intact in their original directions. You will probably want to reverse the direction of that path.

**Comment by frank-trampe** [comment]
You can reverse the path direction from the Element menu after selecting a point on the path. For more information about filling rules, see [here](https://fontforge.github.io/editexample2.html).
