### ISSUE TITLE
[Feature Request] Support OS/2 stylemap in native script

### ISSUE THREAD

**Issue by ggl329** [fontforge/fontforge#3750]
I want to access OS/2 stylemap to generate italic font with native script like `font.os2_stylemap` in python (#3174).

patch:
```
diff -ur fontforge-master/fontforge/scripting.c fontforge-patched/fontforge/scripting.c
--- fontforge-master/fontforge/scripting.c      2019-06-23 08:29:10.000000000 +0900
+++ fontforge-patched/fontforge/scripting.c     2019-06-28 22:39:52.402356000 +0900
@@ -3747,6 +3747,8 @@
        setint16(&sf->pfminfo.weight,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"Width")==0 ) {
        setint16(&sf->pfminfo.width,c);
+    } else if ( strmatch(c->a.vals[1].u.sval,"StyleMap")==0 ) {
+       setint16(&sf->pfminfo.stylemap,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"FSType")==0 ) {
        setint16(&sf->pfminfo.fstype,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"IBMFamily")==0 ) {
@@ -3864,6 +3866,8 @@
        os2getint(sf->pfminfo.weight,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"Width")==0 ) {
        os2getint(sf->pfminfo.width,c);
+    } else if ( strmatch(c->a.vals[1].u.sval,"StyleMap")==0 ) {
+       os2getint(sf->pfminfo.stylemap,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"FSType")==0 ) {
        os2getint(sf->pfminfo.fstype,c);
     } else if ( strmatch(c->a.vals[1].u.sval,"IBMFamily")==0 ) {
```

**Comment by ctrlcctrlv** [comment]
Your patch looks fine to me. Submit a PR with it.

**Comment by JoesCat** [comment]
@ggl329 - use this as a template.
https://github.com/JoesCat/fontforge/commit/5ea90d0c2b9d3ab2d89c00725bfb961dc8cef32c
scripting.c needs a dictionary lookup to find your code.
You'll need an index lookup for each command you've listed above. Look at approx line 8600 in scripting.c in the example above.
To be complete, it would be ideal to add scripting-alpha.html information for users to know the commands are available - also shown in example mentioned above.
If you have a less mysterious name than @ggl329 (in the git PR itself is fine), we can add it to the AUTHORS (...which can use some further updating sometime soon).

**Comment by ggl329** [comment]
@JoesCat Thank you for helping me.

My patch is to add the way to access OS/2 stylemap by SetOS2Value("StyleMap", integer) and GetOS2Value("StyleMap"). (Sorry, I missed to describe this in my original comment.) Because there already exist entries of SetOS2Value and GetOS2Value in the lookup table, it is not necessary to add new entries, is it?

**Comment by JoesCat** [comment]
I wasn't looking too much at the code, my error - consider it extra info for others :-)

Looking at the code (above), I would recommend adding some error checks and returning errors when found. One problem we seem to see often is 65535 and 65536, so testing for the range 0..65535 as okay, and other values as bad will help avoid having users add issues saying they can't squeeze a non-16bit unsigned value into those variables. ...basically, an ounce of prevention is worth more than a pound of cure (avoid garbage-in/garbage-out).
