### ISSUE TITLE
⟦User decompositions⟧ `.` in glyph name leads to build failure

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3751]
Imagine a glyph `_ra_kudlit.i` (-1). This glyph is supposed to be built from `_ra` (U+170D) and `_kudlit.i` (U+1712). Its user decomposition is `170D 1712`.

It fails to build with glyph name `_ra_kudlit.i` . (Case Ⓐ)
It builds fine with glyph name `_ra_kudliti`. (Case Ⓑ)

Why? For some reason...SCMakeBaseReference (fvcomposite.c:1691), called by SCBuildComposit (fvcomposite.c:2877), behaves differently for glyph names containing periods. In Ⓑ, it looks up `uni170D` via `SFGetChar`, returning a pointer to `_ra`. But in Ⓐ, it looks up a non-existent character&hellip;`uni170D.i`.

I'm not sure why this feature is supposed to be useful. Perhaps for building accented small caps&hellip;although I'm not really sure why this would help with that I think I should disable it if a user decomposition exists, but to know if that's right I have to know what it's for.

What do you guys think? If no responses for a week I'll submit a PR to disable it for user decompositions.

**Comment by skef** [comment]
In my view this is a sub-part of #3713.

**Comment by ctrlcctrlv** [comment]
Agreed&hellip;I'll PR a fix for this, either on its own or as part of the new matrix-based User decompositions.
