### ISSUE TITLE
FontForge bricked my font file! `mark` feature disappears when trying to generate font...

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3752]
I don't know how this happened but it happened at the worst possible time, right before bed when I wanted to publish something before going to sleep.

FontForge bricked my font file. 01566b54197fa5c232b2a808c173c424fd7aba44 under Arch Linux. I can still open and edit it, but the OTF's generated from it are corrupt. This font is quite old&hellip;I started it in 2016, before I had the good sense to separate feature files from outlines in SFD.

Please help...

# Files

Last good working OTF file: https://github.com/ctrlcctrlv/OpenBaybayin/blob/master/OpenBaybayin.otf 
Newest SFD file: 
[OpenBaybayin.zip](https://github.com/fontforge/fontforge/files/3342857/OpenBaybayin.zip)

Even the "Initial commit" SFD in ctrlcctrlv/OpenBaybayin no longer works...I have no idea WTF I did but my FontForge SFD is bricked.

# Tables in SFD (GSUB)

![2019-06-30-202030_1560x1092_scrot](https://user-images.githubusercontent.com/838783/60396460-86b48580-9b74-11e9-9aed-d2d111cebc2c.png)

# Tables in OTF (GSUB)

![2019-06-30-202041_1560x1092_scrot](https://user-images.githubusercontent.com/838783/60396459-86b48580-9b74-11e9-9105-b11fb77adf19.png)

# Tables in SFD (GPOS)

![2019-06-30-202108_1560x1092_scrot](https://user-images.githubusercontent.com/838783/60396474-a77cdb00-9b74-11e9-9566-bc63c607c94d.png)

# Tables in OTF (GPOS)

![2019-06-30-202113_1560x1092_scrot](https://user-images.githubusercontent.com/838783/60396476-b19ed980-9b74-11e9-92ce-a091a2e31e1c.png)

Metrics view is also all 🤬'd up:

# Metrics view (SFD)
![2019-06-30-202446_454x756_scrot](https://user-images.githubusercontent.com/838783/60396515-34279900-9b75-11e9-8100-9e4ca196f8b5.png)

# Metrics view (OTF)
![2019-06-30-202505_454x756_scrot](https://user-images.githubusercontent.com/838783/60396520-38ec4d00-9b75-11e9-96c5-b9b4f01587b6.png)

# Things I've tried&hellip;

One thing that's worked for me in the past in similar situation is to use UFO as a pass-through. That did not work in this case. :disappointed:

**Comment by frank-trampe** [comment]
I am able to open the attached SFD. @ctrlcctrlv, the fact that a previously working SFD doesn't work for you suggests that the problem is not with the file but with your FontForge installation or configuration. I would suggest moving your FontForge configuration files to a temporary directory out of the way and trying again.

![Screenshot from 2019-06-30 11-40-51](https://user-images.githubusercontent.com/2512464/60399568-f4888f00-9b2b-11e9-822e-fa0e68ca7a93.png)

**Comment by khaledhosny** [comment]
Looks like you are generating AAT tables, these are parsed as features with numbers like what you are showing here.

**Comment by frank-trampe** [comment]
Oh. I misread this and confused the OTF and SFD results. Sorry about that.
I'll look at this again this afternoon.

**Comment by frank-trampe** [comment]
This is going to require a bit more attention. It's on my schedule for tomorrow if nobody else gets to it.

**Comment by ctrlcctrlv** [comment]
@khaledhosny Thanks for that tip, I had no idea what I was looking at there (presumed memory corruption) so simply wrote &ldquo;wtf&rdquo;. :wink: Indeed, if I disable &ldquo;Apple&rdquo; in File&rarr;Generate Fonts&hellip;&rarr;Options&rarr;SFNT, I no longer receive those `<1,2>` or `<2,2>` pseudo-features. This font is OpenType only, I certainly didn't consciously add any AAT features. If I disable &ldquo;Apple&rdquo;, now I receive a font that only has `kern` (and indeed, in a format `ttx` can't understand!)&hellip;my `GSUB` features are all dropped, and my very important (for this script) `mark` feature is also gone. Ugh&hellip;

**Comment by ctrlcctrlv** [comment]
Voluntarily closing folks, thanks all for taking a look at it, those `<1,2>` or `<2,2>` pseudo-features made me believe the generated font was corrupt, I didn't know that's what AAT features look like in FontForge's interface&hellip;somehow my File→Generate Fonts…→Options→SFNT got messed up. All I had to do was untick “Apple” and (re-)tick “OpenType”.
