### ISSUE TITLE
What is FlattenedAccentBaseHeight & how to calculate it

### ISSUE THREAD

**Issue by kumaryatham** [fontforge/fontforge#3756]
Can you please provide how to calculate **FlattenedAccentBaseHeight** from given ttf file.

I tried with ttfunk but coudn't able to find out FlattenedAccentBaseHeight value. And one of the blog saying its same as **cap_height**.  But cap_height & FlattenedAccentBaseHeight from fontforge are not matching for most of the fonts.

Thanks in advance.

**Comment by ctrlcctrlv** [comment]
This is MS's `MATH` table related, right? Doesn't seem to have anything to do with TrueType, but rather OpenType.

**Comment by khaledhosny** [comment]
That is one of the `MATH` table [constants](https://docs.microsoft.com/en-us/typography/opentype/spec/math#mathconstants-table). You don't need to worry about it unless you are making a font for mathematical typesetting, and if you are doing then there is much more to be concerned with.
