### ISSUE TITLE
⟦Expand Stroke⟧ Rectangular (calligraphic) results in spline with strange looking rectangular cut-out

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3762]
# A bug in three acts

![2019-07-05-175620_1807x665_scrot](https://user-images.githubusercontent.com/838783/60714713-2fd0f680-9f4e-11e9-9d29-41dcabff0ac2.png)
![2019-07-05-175605_1814x693_scrot](https://user-images.githubusercontent.com/838783/60714714-30698d00-9f4e-11e9-95a1-6b3b5a0f37e1.png)
![2019-07-05-175555_1757x647_scrot](https://user-images.githubusercontent.com/838783/60714715-30698d00-9f4e-11e9-82c4-acd2938d551c.png)

# Test case *sans* background image

[S.zip](https://github.com/fontforge/fontforge/files/3362127/S.zip)

## Required settings

<img src="https://user-images.githubusercontent.com/838783/60709947-293d8180-9f44-11e9-8336-7b14c5d0ac41.png" width="200">

# Work arounds

Attempting a &laquo;Simplify&raquo; _does not work_.

Enabling Spiro, moving the first point 1px to the left then 1px back (to force the original Bezier to be lost), then disabling Spiro again and stroking the resulting B&eacute;zier which now has many more points _does work_, but is very hacky obviously.

![2019-07-05-180149_632x563_scrot](https://user-images.githubusercontent.com/838783/60715120-e59c4500-9f4e-11e9-8cc2-c53328f2b607.png)
![2019-07-05-180204_645x799_scrot](https://user-images.githubusercontent.com/838783/60715118-e503ae80-9f4e-11e9-8446-5eb3aaf4b508.png)

**Comment by skef** [comment]
To reproduce this use the parameters in the image except set the pen angle to 45.
