### ISSUE TITLE
AppVeyor builds broken as of a few days ago

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3764]
All recent builds, e.g. the one in #3763, are failing the same way:

```
--2019-07-06 04:45:00--  https://sourceforge.net/projects/freetype/files/freetype2/2.10.1/freetype-2.10.1.tar.bz2
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-06 04:45:00 ERROR 404: Not Found.
!!! Build failed at: FreeType2 archive retreival
Command exited with code 1
```

Probably just needs a different URL. Why not distribute a version of FreeType in our organization, e.g. make a repo `fontforge/freetype2` with the ZIP so we are in control of the URL and know it won't break?

**Comment by frank-trampe** [comment]
Maintaining a mirror might not end up being any less work. If we switch to `xz`, we ought to be okay for a long time. Or we could just stop updating FreeType.

**Comment by ctrlcctrlv** [comment]
If it's as easy as switching to `xz`, my vote is just to do that :-)

**Comment by ctrlcctrlv** [comment]
Looks like this just needs to be changed? 

https://github.com/jtanx/fontforgebuilds/blob/master/ffbuild.sh#L279

**Comment by jtanx** [comment]
It's fixed now.

Mirroring sources ourselves if of little benefit, especially for freetype where we have to match the version of that was used to compile the freetype dll. The script already tries to use multiple mirrors to minimise the chance of failure.
