### ISSUE TITLE
[Question] How to remove Emoji glyphs from a font

### ISSUE THREAD

**Issue by guoyunhe** [fontforge/fontforge#3765]
DejaVu fonts contain a lot emoji glyphs, like start, smile face. I want to delete these from the font files (TTF). Is here any command line way to do so? Thanks!

**Comment by ctrlcctrlv** [comment]
1. The issue tracker is not a forum. It is not appropriate to ask questions here; questions may be asked on the mailing list and (hopefully soon) IRC.
2. It is probably possible to do what you want through the Python interface and running FontForge in headless mode to get a "command line way to do so". You could also just open the font, select all the emoji, right click, &laquo;Clear&raquo;, &laquo;File&rarr;Generate Fonts&hellip;&raquo;.
