### ISSUE TITLE
Unicode confuses FontForge when saving SFD…

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3768]
# *L'erreur:* 

_Une boîte de dialogue d'avertissement apparaît._

```
You tried to save with the filename Ấ.sfd but it was saved as Ấ.sfd.sfd. 
Please choose File/Generate Fonts to save to other formats.
```

The SFD content doesn't matter. Ấ.sfd should be a valid file name; the rename to Ấ.sfd.sfd is not helpful and is a bug.

_&ldquo;Why would anyone want to name a file Ấ.sfd,&rdquo;_ you ask? Well, that was the most logical name for [helping someone on the mailing list.](https://sourceforge.net/p/fontforge/mailman/message/36711601/)

It seems like having non-ASCII anywhere in the file name causes the error&hellip;

# All of the following cause the unnecessary rename

* Ấ2.sfd
* 2Ấ2.sfd
* нет.sfd
* ¡No!.sfd

# References

This is possibly a regression, albeit a very old one. (2013) See #369 and  #1572 for the code that added this error message.

**Comment by ctrlcctrlv** [comment]
By the way, I'm not asking for someone to help me fix this.

I see the problem already in fontview.c:_FVMenuSaveAs. I'm working on a fix already. I just need an open issue to cite in my PR. :smile:

**Comment by skef** [comment]
I think this is still open because #3770 didn't port the "Closes" message over, so I'll close it in a day unless someone updates or closes it first.
