### ISSUE TITLE
⟦Feature request⟧ It should be possible to close and reorder CharView tabs

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3776]
I have no immediate plans of working on this, and I may never do so, but it should be possible.

**Comment by skef** [comment]
Closing is already possible with `File -> Close Tab`

And don't forget drag and drop, with dragging outside of a window opening a new one.

**Comment by ctrlcctrlv** [comment]
Is reorder possible? Even if it's possible, I think we should also add a button on the tabs themselves, that's the paradigm most programs use, it's much more logical for users
