### ISSUE TITLE
I should be able to copy and paste objects without the CharView tab zoom resetting

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3783]
Not sure if this is a feature or a bug, guess it depends on how you're using FontForge. I definitely experience it as a bug.

Let's say we're drawing an `m`&hellip;

![2019-07-12-191708_3840x2160_scrot](https://user-images.githubusercontent.com/838783/61124461-894e9d80-a4d9-11e9-959a-f968898a5926.png)

We copy and paste the second stroke, and the zoom resets.

![2019-07-12-191809_3840x2160_scrot](https://user-images.githubusercontent.com/838783/61124512-aa16f300-a4d9-11e9-8c17-4176182de313.png)

D'oh&hellip;

**Comment by khaledhosny** [comment]
That was the fix in sortsmill https://github.com/khaledhosny/sortsmill/commit/18fee9bd1f3538376f61d486f662840b1ef4d2a9, feel free to backport.
