### ISSUE TITLE
some ideas for better work experience

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#3784]
hi there.
as a font designer i spend a lot of time with fontforge(averagely 4-5 hours/day) so i have some ideas for make fontforge more efficient:
1. snap nodes to marks.
2. set start point by selecting a node and pressing a shortcut key(necessary for VF masters manual adaptation).
3. set some shortcut keys for make paths clock/counterclockwise.
4. vertical skew:
vertical skew is a necessary transform function, i do it with 3 sub-transform:

![vcxsrv_2019-07-13_13-11-45](https://user-images.githubusercontent.com/25493297/61169226-c82f3280-a56f-11e9-8c37-8d0c54dc3e68.png)

or even better if we can input a custom skew degree.
5. kerning tables input enhancement:
kerning pairs table is one of annoying part of fontforge because it's very hard to input characters and numbers individually(takes up a lot of time) so its be great if we can select some rows(by shift and click and/or by mouse dragging) and write a string/value and apply that for all.(most of the rows included repeated things usually)
6. make all table lists sortable.

thank you.

**Comment by ctrlcctrlv** [comment]
I don't understand some of your requests, but I'm pretty sure all or most of the keyboard shortcut requests can be done already.

**Comment by aminabedi68** [comment]
OK, so we can't handle number 3. which part you can't understand? i can explain detailed.

**Comment by ctrlcctrlv** [comment]
Please explain (1) and (2) in more detail, what do you mean by &laquo;node&raquo;?

As regards other requests:

As for (3), I would be surprised if this wasn't already possible. @skef is our keyboard shortcut expert, he may know how to do it.
As for (4), I **agree**.
As for (5), I **disagree**. Or, I certainly am not going to put the time into doing that, and don't think any other team members will. If you need to make big changes to a font's kerns, you should use feature files.
As for (6), I **agree**.

**Comment by aminabedi68** [comment]
node = point/vertex
for number 2 i mean start point of the path.
for number 5, i know it's hard to do, but many designers(specially amateurs) aren't family with feature file and/or python automation codes and kerning is a long boring process in many scripts. so it was a big improve if you work on that.

**Comment by ctrlcctrlv** [comment]
(in re: (5))

Here's how I see it:

Fonts are software, according to most courts and foundries. FontForge can write much of the code needed to make a piece of font software automatically, but at the end of the day, a font is still a piece of software. Inevitably, FontForge's automation of the tedium of writing OpenType feature code will break down on edge cases, requiring the user to write code to achieve complex font features. There is nothing wrong with this. Amateurs can learn, most OpenType code is extremely simple, especially as regards kerns. I won't be working on it, but this is an open source project so at your discretion you can find someone to code up what you want for you and PR it to us.

**Comment by ctrlcctrlv** [comment]
Also, thank you for your comments, but as this is not a forum, I'm going to close your issue. I encourage you to make separate issues for each of your feature requests so they can be dealt with more effectively, as this is a bug/feature request tracker, not a forum.

**Comment by skef** [comment]
"Make First" should already have the shortcut Ctrl-1. Clockwise and counter-clockwise don't, but you can customize hotkeys as you wish.

**Comment by aminabedi68** [comment]
thank you @skef ,i really need it :)
thank you @ctrlcctrlv ,i want to help but i'm a designer anyway.
