### ISSUE TITLE
Rendering of material design icons (SVG) broken

### ISSUE THREAD

**Issue by ripper17** [fontforge/fontforge#3790]
### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] Steps to reproduce the behavior 
- [x] The behavior you expect to see, and the actual behavior

I'm having trouble using the current FontForge release with the material design icons from https://materialdesignicons.com/ : 
In the attached screenshot, you can see that the rendering of the imported SVG differs greatly in the current version (at the bottom) when compared to FontForge from 2012 (on top). I don't know where the issue really is, if it's a badly designed SVG or if the import of the SVG is incorrect. Opening the SVG in Inkscape (0.92) gives the desired result and seems to be consistent with the import from FontForge from 2012.

![Fontforge_2012vs2017](https://user-images.githubusercontent.com/7793762/61208866-a1e8ce80-a6f8-11e9-9b3e-1adb955b7e7c.jpg)

**FontForge version and the operating system**
fontforge 11:21 UTC 24-Sep-2017
libfontforge 20170924
Ubuntu 18.04.2 LTS

The issue does not appear with:
fontforge 20120731
libfontforge 20120731-ML
Ubuntu 16.04.3 LTS

**Steps to reproduce**
1.) https://materialdesignicons.com/icon/account-multiple-outline (NOTE: The issue does not happen on all material design icons, but very many)
2.) Click on "Icon Package" and download ".SVG for Grunt Webfont" (or ".SVG optimized", which will give different, yet also broken rendering)
3.) Open Fontforge and create a new font
4.) Import the downloaded SVG for any character

**Actual behaviour**
See lower part of the screenshot: the "bodies" of the two "people" are filled but shouldn't be. 
Note: For other icons you'll sometimes get missing lines, circles being collapsed etc. 

**Desired behaviour**
A rendering very close to the FontForge 2012 version or Inkscape (the bodies should not be filled)

**Additional info**
Another SVG (used now because the SVG markup is way simpler) is "alert-octagon". It has a path with multiple sub-paths. The sub-paths aren't all closed in the SVG markup ("Z"), there's only one "Z" at the very end of the path:
`<path d="M13,13H11V7H13M12,17.3A1.3,1.3 0 0,1 10.7,16A1.3,1.3 0 0,1 12,14.7A1.3,1.3 0 0,1 13.3,16A1.3,1.3 0 0,1 12,17.3M15.73,3H8.27L3,8.27V15.73L8.27,21H15.73L21,15.73V8.27L15.73,3Z" />`

In that particular instance, if I manually close all subpaths (so the markup becomes:
`<path d="M13,13H11V7H13ZM12,17.3A1.3,1.3 0 0,1 10.7,16A1.3,1.3 0 0,1 12,14.7A1.3,1.3 0 0,1 13.3,16A1.3,1.3 0 0,1 12,17.3ZM15.73,3H8.27L3,8.27V15.73L8.27,21H15.73L21,15.73V8.27L15.73,3Z" />`
), I do get the desired result for that icon. However, this does not fix all issues, e.g. the "account-multiple-outline" SVG will look even weirder with that "fix" applied (the heads will now more look like "+" signs).

Is this an issue with FontForge or with the SVGs? Is there any setting I could try in FontForge to get "better" results?

**Comment by ctrlcctrlv** [comment]
I am closing this bug as invalid. 

* **The path is not closed**, FontForge is working correctly. Some rasterizers (Firefox's, Inkscape's) interpret the unclosed path as a closed path...that might even be the correct thing to do during rasterization of an SVG.
  * During editing Inkscape sees the path correctly as unclosed.
* **The direction of the path is wrong**, selecting it and using &laquo;Element&rarr;Reverse Direction&raquo; causes FontForge's rasterizer to correctly interpret the path as being a hole even though it's not closed.

The semantics of font glyphs are not the same as SVG. Font glyphs rely primarily on direction to interpret the correct rasterization (i.e., whether path is a hole). Font glyphs should _never_ contain open paths, in any circumstances, as what to do is implementation defined.

If 2012 FontForge auto-closed the paths, it was wrong to do that.

**Comment by ripper17** [comment]
Thanks for taking time to look into this, I was able to solve this issue by closing the paths. 

(I hope I'm not causing this issue to reopen by commenting....)
