### ISSUE TITLE
Better quadratic spline editing (for VFs)

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#3803]
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem

I would like to suggest making it convenient to draw quadratic layer splines with 2+ off-curve points; when drawing with 2 off-curve point, it is very hard to get a pleasing shape. But with 2, it is similar to drawing with cubic beziers. 

Why is this a problem? When preparing UFOs and a DesignSpace.xml file to produce an OpenType Variable Font, its better to draw quadratics directly, rather than draw cubics and have them auto-converted to quadratics, because the conversion may make the intermediate instances in the design space look bad.

**Comment by skef** [comment]
Unless I misunderstand this is (roughly) a request to allow quadratic and cubic splines on the same layer, although that won't fully address the stated problem. 

A quadratic spline has, if not by definition then at least inherently, one control point between off-curve points (which may be placed so as to create a line, in which case it can be treated as if it is absent). A cubic spline similarly has two control points (which again can be positioned so as to create a line, or one can be co-located with an on-curve point leaving something like one control point, but that configuration has some strange properties). 

Some font packages support mixing quadratic and cubic splines freely. If FontForge supported that your concern would be partly addressed, in that only the cubic splines would need to be down-converted to quadratic for formats that only supported quadratic. But it would be a lot of additional work to allow mixing and the benefits would be modest.

**Comment by davelab6** [comment]
No, not on the same layer.

While a quadratic spline has by definition one control point between
off-curve points, the TT implementation "interpolates" the missing oncurve
points between a series of off-curve points.

**Comment by ctrlcctrlv** [comment]
I'm not sure if this is on topic or not, but, how hard would it be to re-use the Adobe MM code to support OpenType 1.8 variable fonts? As mentioned in #3544, we'd also need to support a new CFF table format, but other than that?

**Comment by skef** [comment]
Quadratic point interpolation isn't for additional design flexibility -- it's a (quite underwhelming at this point) storage-saving measure. On curve-points are (or can be) "interpolated" when they fall exactly between two off-curve points, so they don't need to be stored. But they can only be interpolated under that circumstance. It doesn't much affect the ability to arrive at particular quadratic curves. 

I've only worked with the quadratic interface a tiny bit, but I believe that FontForge already keeps on-curve points of the "curve" type centered and therefore in their interpolated point unless one selected "do not interpolate". Other point types behave differently.

**Comment by davelab6** [comment]
>
> Quadratic point interpolation is for additional design flexibility in 2
way: It allows a UI more familiar to those drawing cubics, and it allows
"point stacking" to do interpolation like this:
https://mjlagattuta.github.io/Space-Mono-Experiment/HOI/spacemono-hoi.html

The MM Stuff can't be used as GX/OTvar is a completely different model. See
https://www.monotype.com/resources/articles/part-1-from-truetype-gx-to-variable-fonts/
for some history. I think Fontforge has a GX implementation, though. I
believe GWW did the freetype implementation too :)

**Comment by skef** [comment]
If you open a FontForge quadratic layer, draw some curve points in a contour, select a single on-curve point, and choose "Element -> Can Be Interpolated" in the menu, is that what you're looking for? If not is there a specific interface on one or another tool that could serve as a reference?

**Comment by davelab6** [comment]
That is true, but it is inconvenient :)

**Comment by skef** [comment]
So the request boils down to being able to draw interpolated points (in a quadratic layer) more easily. To make things not too complicated to implement, suppose you could shift-click or double-click or something like that on the curve point palette tool to toggle it between normal and interpolated mode, demonstrated by whether the point shown there is solid or hollow. And there was also a corresponding menu item that toggled the tool, with a hotkey. Would that be sufficiently convenient? Would it be confusing for existing users?

**Comment by skef** [comment]
OK, I thought a little bit more about this and that solution isn't good, because it violates the expectations of how the tool is supposed to work.

However, this conversation and some testing has made me realize this is likely how the "Pen" tool (illustrated by the pen nib in the palette) is intended to be used. I've always found it kind of awkward in cubic mode, but in quadratic mode it seems to do just what you want -- click where you want the next control point to be and an interpolated point is added in between.

@davelab6 Can you try that and see if it's what you were hoping for and if not describe the difference? (Obviously there's a docs issue here but it doesn't seem much different than the many other docs issues up and down the project.)

**Comment by skef** [comment]
Any update on this @davelab6?

**Comment by ctrlcctrlv** [comment]
I'm still thinking about this too. I haven't really gotten any straight answers. We need to support a new CFF2 table format, that's for sure. But does FontForge already have the proper interpolation code or not? Do we also need to add a new type of interpolation, and if so, what type?

I played around a bit with Inkscape's interpolator.

![2019-08-17-180606_2276x615_scrot](https://user-images.githubusercontent.com/838783/63209909-8fa7e900-c119-11e9-9d02-7d0b05460f34.png)

This is Cantarell Regular and Cantarell Heavy. This is the outlines in the OTF files, no tricks were done here and the output is great. So, we need to nail down what kind of interpolator is being used. Is it the same as the MM interpolator? Is it the interpolator in Inkscape demonstrated above? Something even fancier?

**Comment by ctrlcctrlv** [comment]
I talked about this a bit with the Inkscape developers. What we might end up wanting to do here is just use HarfBuzz and/or Pango as the interpolator, feeding it a font made on the fly. FontForge already does this with FreeType for some hinting stuff, so this is not a totally new paradigm.

Our chat is here:
https://gist.github.com/ctrlcctrlv/a9fe2743e726a6914f82a577dbb06d9b#file-inkscape-devel_20190818-log

Of course, we may still want to implement our own interpolator if we don't already have the necessary one. The HarfBuzz option seems easier and therefore more viable to me though :-) After all, we do need to write code capable of writing out these CFF2 fonts, so doing that on the fly isn't really a huge stretch is it?

**Comment by khaledhosny** [comment]
FontForge supports both TrueType GX and Type 1 Multiple Master fonts, and certainly supports interpolation. Neither Pango nor HarfBuzz has an interpolator.

**Comment by khaledhosny** [comment]
https://fontforge.github.io/mmmenu.html
https://fontforge.github.io/multiplemaster.html
https://fontforge.github.io/elementmenu.html#Interpolate

**Comment by ctrlcctrlv** [comment]
I know we have an interpolator, just not if ours is the right kind.

**Comment by ctrlcctrlv** [comment]
HarfBuzz supports variable fonts. If we created fonts on the fly for testing, we could just tell HarfBuzz to display splines for the interpolation value X. HarfBuzz doesn't expose its interpolator, but it exposes a way to receive interpolated splines from an OpenType 1.8 font, so it's usable AFAICT.

That is, if we don't have a robust interpolator already. There are many ways to do spline interpolation, we need to be sure that one of the interpolation methods in FontForge is the same one used in the OpenType 1.8 spec. Not all interpolators are created equal. @khaledhosny ?

**Comment by khaledhosny** [comment]
HarfBuzz ***does not*** have a glyph interpolator nor a way to get glyph outlines. It supports ***shaping*** variable fonts, not ***rendering*** them.

**Comment by ctrlcctrlv** [comment]
Right, sorry. FreeType then. https://www.phoronix.com/scan.php?page=news_item&px=FreeType-2.8-Released

**Comment by davelab6** [comment]
Why not use fonttools varlib?

**Comment by ctrlcctrlv** [comment]
Because that would require us to ship Python scripts with FontForge, it would require hacks to write the UI for the VF feature in C while using libpython to do the heavy lifting, etc.

FontForge should not rely on scripts for core features. If you want to make VF support via a Python script, that's a cool project, I suppose, but we have too many blockers to implement something this complicated in Python alone, including #3663, #3719, and others.

**Comment by skef** [comment]
@davelab6 Care to update on the non-tangent topic of this issue? Does the "pen" tool in quadratic mode do what you want, and if not how so?

**Comment by skef** [comment]
I'm not sure why the initial discussion on this issue stopped, but here is my understanding of how FontForge already has the requested feature, or something close enough to it:

1. Ensure you are in quadratic mode
2. Select the "pen" tool. 
3. Press down on a portion of the canvas with the left mouse button and drag out an initial curve point. This is (unusually) an isolated point with two off-curve points.  
4. Now click with the mouse in subsequent canvas locations: Each click marks a new off-curve point, with the previous on-curve point being interpolated. 

Unless this issue is updated in the next few days I think it is a appropriate to close it.
