### ISSUE TITLE
Request: Build infrastructure for temporary/test executables

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3815]
I'm currently chewing on some algorithmic work and have had a frustrating time finding a home for test/example code. I wound up adding a function to `python.c` and putting things there. 

It would be nice if there were a directory with a makefile and straightforward instructions for how to build a C test program against the fontforge "libraries" (be they dynamic or static) and run it "in place" (i.e. not have to install). That way one could easily add another library and further header files for testing purposes, or to aid intermediate development. Right now the infrastructure is very monolithic and I more or less thew up my hands. 

@jtanx how hard would it be to add this? Maybe with a very simple program as a test that is built by `make check`, to make sure it doesn't rot?

**Comment by jtanx** [comment]
Under [cmake](https://github.com/jtanx/fontforge/blob/cmake3/contrib/fonttools/CMakeLists.txt), this is pretty trivial, I've already done something similar for building the extra/maintainer executables that are all over the place.

It's literally

```
add_executable(myexe mysource.c)
target_link_libraries(myexe PRiVATE fontforge) # Plus any other deps you have
```

Under autotools, it's a little bit more work, but can be done.

**Comment by jtanx** [comment]
If it's just for local scratch space, you could probably do something like:

* Make a new folder, called `scratch`
* Link the scratch folder in the toplevel `Makefile.am` https://github.com/fontforge/fontforge/blob/master/Makefile.am#L92
* Copy this layout https://github.com/fontforge/fontforge/blob/master/contrib/fonttools/Makefile.am#L46-L55
* Run make in that folder
* execute `.libs/mytestexe`

**Comment by skef** [comment]
I'll give that a shot. 

While you're "here" -- I suspect I'm going to try fixing "real-related" problems like this one in `mem.h`:
```
// FIXME: move from splinefont.h to a separate header
#ifdef FONTFORGE_CONFIG_USE_DOUBLE
# define real           double
# define bigreal        double
#else
# define real           float
# define bigreal        double
#endif
```
By adding an `inc/precision.h` and moving the stuff there. Would that be OK with you? Is there somewhere else centralized where it belongs? 

(I'm hoping to be able to build with `real/bigreal/extended` as `__float128`. Some math is yielding four only digits of accuracy and I'm trying to figure out if it's inherent to the calculations or if there's a mistake somewhere.)

**Comment by skef** [comment]
Oh, another reason it would be useful to have such a build location as a stable part of the infrastructure is for posting test code here. It would be nice to be able to share a little program that demonstrates this or that problem and make it easy for other contributors to compile and run it.

**Comment by jtanx** [comment]
I'll follow up with you later this evening, but just briefly on that shareable code, we can probably just add it to the contrib folder

**Comment by JoesCat** [comment]
Build, then "make check"
fontforge/libuninameslist or fontforge/libspiro
A search of a few distros show that it's also used for verification too.
test programs remain in test directory but are not installed.
key phrase is noinst in Makefile.am

**Comment by skef** [comment]
I haven't looked at this in a while but I was under the impression that the test code didn't link against any of the libraries. Instead the harness ultimately goes through `libfontforgeexe/fontforge`, which is a script that constructs a local environment to get around the not-yet-installed problem (with LD_LIBRARY_PATH and such).

**Comment by JoesCat** [comment]
The test code will link against the test library.
If you look at libspiro, it's a small library, so it should hopefully be easy to decipher.
You will see test/unittest creates a self-contained binary, while test/call-test* link against the library.

To convince yourself,
autoconf -i; automake
./configure --enable-verbose_lib
make
then
test/call-test0
test/call-test1
you'll see verbose print statements, which you would not normally see with the usual library installed in /usr/shared/local/.....
if you are going to install, I suggest you rebuild...
./configure
make
su
make install
exit

again, if you...
./configure --enable-verbose_lib
make
you'll once again see verbose print statements
test/call-test15

etc...
make check will log
and
make distcheck
will create a dist, then test all the configure.ac options in the dist
You need to remove .git first to make a compact dist (this last statement is off topic but trails prior statement)

**Comment by jtanx** [comment]
@skef, if you still need this, and now that the cmake changes are merged in, I can help you set it up.

**Comment by skef** [comment]
I still think it would be a good idea. 

I wound up adding a function to a file to run some tests through an added python interface in this instance. It would be better to have that test code (or what triggers it, depending on subtle include file issues) be built into something in tests (and therefore not installed). So "C-langauge-level test infrastructure support" best describes my current needs.

**Comment by jtanx** [comment]
> So "C-langauge-level test infrastructure support" best describes my current needs.

As it would have it, I had to run all tests through a [test driver anyway](https://github.com/fontforge/fontforge/blob/master/tests/CMakeLists.txt#L12-L16)

So presuming you want to add a test that is its own binary, at its most basic form it would be something like

```cmake
add_executable(mytest mytest.c)
target_link_libraries(mytest PRIVATE fontforge) # Plus whatever other dependencies are required

...
add_custom_target(check
  COMMAND "${CMAKE_CTEST_COMMAND}" "--output-on-failure" "--force-new-ctest-process"
  DEPENDS
    test_dependencies
    fontforgeexe
    systestdriver
    mytest # Add it as a dependency here
  VERBATIM
  USES_TERMINAL
)
...

add_test(NAME test_mytest COMMAND mytest WORKING_DIRECTORY
      "${CMAKE_CURRENT_BINARY_DIR}"
)
```

Assuming you have built everything note also that you can invoke specific tests with

```
# Assuming you are in your build folder
ctest -R _some_regex_matching_test_name_
```

**Comment by skef** [comment]
OK, I now have a better idea of what this should be, how it would ideally work. 

I'm currently trying to track down what seems to be a problem with `ApproximateSplineFromPointsSlopes()` or perhaps with how I am calling it. I know of a particular set of points that triggers the problem. What I would like to be able to do is write a C file that will build into an independent executable linked against the normal fontforge libraries but that just calls my main (or whatever) and exits. Then I can (for example) write the necessary code to call `ApproximateSplineFromPointsSlopes()` with those points and attach it to an issue, so that other people can easily see the problem and trace through the code with GDB. 

Of course, I could also use this for my own debugging purposes. 

@jtanx how hard would this be? Could there be a directory (or a name that can be added as a directory) where each c file in it is compiled into a separate executable? Perhaps not even requiring any additions to CMake inputs?

**Comment by jtanx** [comment]
Yes, that's trivial to do. If you just want an adhoc binary that doesn't get run as part of the test suite, you can follow this pattern: https://github.com/fontforge/fontforge/blob/master/contrib/fonttools/CMakeLists.txt

Basically all you need is two lines:

```cmake
add_executable(my_exe_name my_source.c)
target_link_libraries(my_exe_name PRIVATE fontforge)
```

As to where to put it, we could either put it under the `contrib` folder (perhaps add another subdirectory), or even under the `test` folder (in a subdirectory too if you want), I'd be happy either way.

**Comment by jtanx** [comment]
> Perhaps not even requiring any additions to CMake inputs?

Can you clarify what you mean by that?

**Comment by skef** [comment]
I mean: Could there just be a directory location where you can do "mkdir foo" and add a c file to it and it will be "discovered", either by rerunning cmake or (ideally) ninja. (I take it that however hard the former would be the latter would be significantly harder, and probably not worth attempting.)

**Comment by jtanx** [comment]
You technically can, although it would involve doing file globbing, and you'd have to manually rerun cmake to detect it. For that reason, file globbing is frowned upon, and it also slows the cmake step.

**Comment by skef** [comment]
I've been playing around with this and it works well.

**Comment by skef** [comment]
I think this is resolved, or resolved enough.
