### ISSUE TITLE
Sort out the load-open-paths situation

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3818]
I could use some help with #827 and #1270 and #3302 and (closed without merging) #3303. 

Here's a hypothesis:

1. #827 added general support for preserving open paths and was intended to allow open paths that started and ended in the same place. It accomplished the latter by altering the position of the (at least the) last point in the contour to be unique, so that `SFDCloseCheck()` would notice the difference in point locations and not close the contour.
2. #1270 restored the position of the point, and in the process broke that aspect of the fix. 
3. #3302 is the proof that the code doesn't handle the same-start-end case.
4. #3303 was an attempt to address that problem in a different way that was never merged. 

I don't necessarily need to solve this problem (although that would be nice), but #1270 is an incomplete fix that's makes something else I'm working on unhappy so I need to work out what parts of #827 are really needed.

**Comment by skef** [comment]
Actually, maybe open paths were always supported and therefore #827 accomplishes little after #1720 (it does have the flags cleanup).

**Comment by frank-trampe** [comment]
@skef, #1720 seems to be unrelated. You mean #1270, right?

**Comment by skef** [comment]
@frank-trampe Yes, sorry.

**Comment by skef** [comment]
Edited.

**Comment by frank-trampe** [comment]
Why can't `SFDCloseCheck` just check that neither point has the no-close flag?

**Comment by skef** [comment]
@frank-trampe I'm not sure how counter-factual your question is. I think it can't "just" check because the no-close flag is part of the SFD file state, not that of SplinePoint or Spline. 

However, it does seem like one could track whether the last line loaded had the flag and use that to decide whether to call `SFDCloseCheck`. In fact it looks like that's what #3303 was doing, more or less.
(However, `have_current_val` in #3303 seems unnecessary given that `current_val` is initialized to 0.)

I think the problem you asked about in #3303 could be fixed as:

```
if ( cur!=NULL && !(have_cur_val==1 && ) ) {
    if ( (cur_val & SFD_PTFLAG_FORCE_OPEN_PATH) && SFDCloseCheck(cur,order2))
        --ttfindex;
```

Right? (Although maybe that short-circuit guard is a bit opaque.)

**Comment by skef** [comment]
I think I'll prepare a push request with that basic idea and we can discuss things in that context.

**Comment by skef** [comment]
(There should have been a `!` in that last guard ... )
