### ISSUE TITLE
Non-Latin alt glyph names in glyph window text unescaped with text typed after

### ISSUE THREAD

**Issue by hyvyys** [fontforge/fontforge#3820]
When the preview text in Glyph window contains a non-Latin glyph (Cyrillic, Greek, or even some African Latin) with a period in the name (typically `uni0430.alt` etc.), and other text is typed after that glyph, it is converted into a sequence of the default glyph followed by the literal period glyph and the whole rest typed out, i.e. `/uni0430.alt` -> `/uni0430/period/a/l/t`. This is prevented by typing out slashes to escape the added letters so that they don't mess up the existing alt glyph, but this only works until the next time the text input gets focused.

Video recording of the issue: https://recordit.co/Nnji5v2NMd
FontForge version: 13-April-2019
OS: Windows 10

This is a severe bug as it interferes with testing alt glyphs (smallcaps, etc.) which in itself isn't easy or comfortable in FontForge. It might also happen with Latin glyphs, but I couldn't reproduce it at all times unlike with Cyrillic.

Steps to reproduce:

  1. Use the attached .sfd file [test.zip](https://github.com/fontforge/fontforge/files/3426655/test.zip), or
    1a. Create a base glyph e.g. `uni0430` and an alt glyph with period in the name, e.g. `uni0430.alt`
  2. Open the glyph with the period for edition by double-clicking
  3. Type at least two characters at the end of the input, or
    3a. Type one character, switch focus back and forth by clicking the drawing board and the input again
  4. Expect the text to be malformed

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
**Confirmed**, I've had this problem before as well, so don't need to test it. Your narrowing down of what causes this is helpful though, I just assumed sometimes there were glitches and got used to working around them. I was sick today but if I feel better tomorrow I'll look into how to fix this

**Comment by ctrlcctrlv** [comment]
(By the way, if I fix this, can I have a free Aromatron license :P What a lovely typeface. I don't do graphic design for a living, I collect fonts as a hobby, so if I spent money on licenses I'd never see a profit from that.)

**Comment by hyvyys** [comment]
Thanks for the follow-up, and the compliment :3 Aromatron is free for personal use and can be grabbed at DaFont, but if you fix this, you can use it for whatever, I promise :D

**Comment by ctrlcctrlv** [comment]
Good news:

While debugging I further narrowed down when this happens. It only happens when the char has a `uni` prefix. So if you name your Cyrillic &lsaquo;а&rsaquo;, something like &laquo;cyr_a&raquo;, this won't happen. And if you name your Latin &lsaquo;a&rsaquo; &laquo;uni0061&raquo;, which while not oft-done, is a perfectly valid thing to do, it _will_ happen. So it has nothing to do with Latin vs. non-Latin but rather glyph names. FontForge does not name Cyrillic and Hebrew by default, but I have a personal name file I use...that's why I thought this was just a glitch, I never quite put it together that in the rare times it happened I had a `uni` prefix, since I try to avoid glyphs named thus in my fonts.

Now let's be clear, this is definitely still a bug, and it definitely still needs to be fixed, but this might give you some solace while I figure out an appropriate patch.

**Comment by skef** [comment]
I'll reiterate what I said in another issue, which is that an easy way to make this interface much more stable would be to have "before" and "after" fields for the content to appear before and after the character. I know there were objections to that based on convenience but:

1. This is not the right interface to use to switch between characters to edit and
2. The current parser is simply not up to what is being asked of it. 

An alternative that might make people more happy is to replace the string representing the character (which could be displayed elsewhere) with a non-ASCII symbol that "can't" (i.e. attempts are rejected by the code) be deleted. 

We can change this or that but I suspect it's going to be very hard to fix things like #3192 without some kind of overhaul.

**Comment by ctrlcctrlv** [comment]
I know my fix has problems, I even mentioned one in the PR, but it's the best we've got right now. 

I think I'd be quite happy with before and after fields of type SplineChar*, that makes sense to me. Why not implement it?

**Comment by skef** [comment]
At least one person who uses it said it would be less convenient.

Interfaces that "magically" insert or remove characters when typing need to be very carefully thought out. This one isn't, unfortunately, and therefore very difficult to fix.
