### ISSUE TITLE
C++ keywords should not be in source

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3823]
```
In file included from geom.cpp:18:0:
splinefont.h:660:18: error: expected identifier before ‘;’ token
struct fpc class;
           ^
splinefont.h:660:18: error: multiple types in one declaration
splinefont.h:1829:18: error: expected unqualified-id before ‘new’
unsigned int new: 1; /* A new and unsaved font */
             ^
splinefont.h:1855:20: error: expected unqualified-id before ‘private’
struct psdict private; / read in from type1 file or provided by user */
              ^
splinefont.h:1855:19: error: expected ‘;’ at end of member declaration
struct psdict private; / read in from type1 file or provided by user */
              ^
splinefont.h:1855:27: error: expected ‘:’ before ‘;’ token
struct psdict private; / read in from type1 file or provided by user */
^
splinefont.h:2352:68: error: expected ‘,’ or ‘...’ before ‘private’
extern int SFPrivateGuess(SplineFont *sf,int layer, struct psdict *private,
                                                                   ^
```

@repu1sion, who is helping me integrate Lib2Geom into FontForge, discovered this.

Sane C compilers, like GCC, will *not* allow you to link C++ code with C code that contains C++ keywords. Even if it might be _technically_ possible, if you need to use the variables named after keywords in C++ code, you won't be able to.

There are many reasons you'd want to link C++ code with FontForge's code beyond my Lib2Geom integration. Therefore, I instructed @repu1sion to make a commit which will change all instances of C++ keywords to underscored versions. So `private` will become `private_`.

I know this might be contentious, so am making this issue so we can discuss it; perhaps someone knows a better way to use FontForge types from C++.

**Comment by ctrlcctrlv** [comment]
(@repu1sion commented to me that we could also just add `#ifdef __cplusplus` everywhere this happens, but that seems way, way worse to me than just changing the variable/member names to C++-friendly ones.)

**Comment by jtanx** [comment]
Ideally all headers should have the __cplusplus guards. But yeah, avoiding C++ keywords is also nice. 

> Sane C compilers, like GCC, will not allow you to link C++ code with C code that contains C++ keywords. 

Technicality, but this doesn't sound right, do you mean it won't allow you to *include* headers that haven't been properly set up? I don't see how linking could/would be affected.

**Comment by ctrlcctrlv** [comment]
Which would you prefer? I tend to think that it's just much better to never use C++ keywords, even in C code. If we use the guards and change it to be `private_` in C++ and `private` in C I think that is just confusing for developers.

**Comment by jtanx** [comment]
Well you won't even be able to use the C functions from C++ without an extern "C" somewhere, so you kind of need those `__cplusplus` checks anyway.

I'm also fine with renaming everything to avoid C++ keywords.

**Comment by ctrlcctrlv** [comment]
Right, I get that. He'd be able to explain it better than me, I don't know much about C++ to be frank, which is why I needed help to get this going in the first place. I _think_ he only needs the types, but as FontForge's headers all refer to each other even if not necessary (as you well know), it's erroring in unrelated parts of the code to what we're doing. I'll wait for him to reply here if I'm totally off-base. :-)

**Comment by repu1sion** [comment]
if we want to use calls to libgeom from our code, its really could be easier with creating some cpp file like geom.cpp and moving all c++ related code to it the build it with g++, not the whole project but just this file. but this file needs to use C objects from fontforge which defined in splinefont.h
So I guess I will try to renaming first, and only if this won't help - then try to build the whole fontforge project with g++. Also - maybe already someone has any experience with building fontforge with C++ compiler/linker?

**Comment by jtanx** [comment]
No, you don't need to, and shouldn't compile the whole project with g++. See how 

Here's some approaches you can take. 

One is to have all c++ code in its own file, which it sounds like you're already doing.

You either then need to expose some C API from that C++ code, then write some other code (in C) to interface that with everything else in FontForge.

Or, you can try directly using the existing objects in your C++ code. Either way, you're going to need to extern "C" some declarations to get things working.

If you go with the second option, an easy-ish way without fixing all the headers is to do something like:

```c++
extern "C" {
#include "splinefont.h"
#include "..."
}
```

From your c++ file.

If you want an example of option 1, see how https://github.com/fontforge/fontforge/blob/master/fontforge/woff2.cc was done.

**Comment by khaledhosny** [comment]
Not using C++ keywords is a good policy in general. I’d even go further and say we should aim at making FontForge code buildable with C++ compiler even it doesn’t use any C++ features at the moment. One day we should explore moving the codebase over to C++ and have a nicer language than the crazy C we are stuck with.

**Comment by khaledhosny** [comment]
We probably should add to all headers:
```C
#ifdef __cplusplus
extern "C" {
#endif
...

#ifdef __cplusplus
}
#endif
```

Or even better use the [GLib macros for it](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Macros.html#G-BEGIN-DECLS:CAPS).

**Comment by khaledhosny** [comment]
(Even GCC is written in C++ these days. If C is too low level for a C compiler, it certainly too low level for a font editor).

**Comment by frank-trampe** [comment]
@ctrlcctrlv, @repu1sion, what is the scale of the problem? In particular, how many lines would a patch changing all of these names include? In the past, we needed to maximize patch compatibility with a number of FontForge forks, but that is not as essential as it once was, and we could plausibly do this. Renaming things to end in an underscore is sort of awkward, though, and it would be nice if the scope were small enough that we could manually pick names.

**Comment by skef** [comment]
> if we want to use calls to libgeom from our code, its really could be easier with creating some cpp file like geom.cpp and moving all c++ related code to it the build it with g++, not the whole project but just this file. but this file needs to use C objects from fontforge which defined in splinefont.h

It's probably fine, and maybe preferable, to go down the compatibility road. But have you also considered a "no man's land/DMZ" approach? If you put a C-language upper layer on whatever interfaces you need from `geom.cpp`, and write those without including any FontForge headers, you could then just call them from the C-side (as it were). If on the other hand it would be better to do almost all this development in C++, you could write a thin C-language wrapper layer for just the parts you need.

**Comment by repu1sion** [comment]
If I have a geom.cpp file with fontforge headers included like this:
```
extern "C"
{
#include <fontforge-config.h>
#include "splinefont.h"
}
```
And then I build this only file with g++ like below:

```
/mnt/ssd/wrk/fontwork/fontforge/fontforge$ g++ -std=c++11 -I /usr/local/include/2geom-1.0.0/ -I /usr/local/include/fontforge/ geom.cpp
In file included from geom.cpp:18:0:
splinefont.h:660:18: error: expected identifier before ‘;’ token
  struct fpc class;
                  ^
splinefont.h:660:18: error: multiple types in one declaration
splinefont.h:1829:18: error: expected unqualified-id before ‘new’
     unsigned int new: 1;   /* A new and unsaved font */
                  ^
splinefont.h:1855:20: error: expected unqualified-id before ‘private’
     struct psdict *private; /* read in from type1 file or provided by user */
                    ^
splinefont.h:1855:19: error: expected ‘;’ at end of member declaration
     struct psdict *private; /* read in from type1 file or provided by user */
                   ^
splinefont.h:1855:27: error: expected ‘:’ before ‘;’ token
     struct psdict *private; /* read in from type1 file or provided by user */
                           ^
splinefont.h:2352:68: error: expected ‘,’ or ‘...’ before ‘private’
 extern int SFPrivateGuess(SplineFont *sf,int layer, struct psdict *private,

```
so even extern "C" doesn't help when you use reserved C++ words like 'class' and 'new'.

**Comment by jtanx** [comment]
Well yeah, `extern "C"` only helps so that you can actually call C functions from C++ code.

**Comment by repu1sion** [comment]
so 'extern C' is mostly about function names, not going deep.
https://stackoverflow.com/questions/1041866/what-is-the-effect-of-extern-c-in-c

And if we want to use C struct objects from splinefont.h like SplineSet and Spline - we have to get rid of reserved C++ words like 'new' and 'class' etc. Or some other propositions?

**Comment by skef** [comment]
> Not using C++ keywords is a good policy in general. I’d even go further and say we should aim at making FontForge code buildable with C++ compiler even it doesn’t use any C++ features at the moment. 

I support this general view. I think attempting to rewrite FontForge using C++ formalisms would be a mistake (unless it was done very slowly over many releases), but having the option of polymorphism and data protection for fixes and new development would be a good thing. C++ is a toolbox -- you can use what you want and (perhaps more importantly) not use what you don't want. 

So maybe we should just go ahead and drive to syntactic compatibility now? That would more than address this issue. How much work would it be? The code base has stayed away from exotic post-C99 stuff for the most part.

**Comment by khaledhosny** [comment]
> having the option of polymorphism and data protection for fixes and new development would be a good thing

Exactly. I‘m not proposing a rewrite, but the possibility to use C++ with the existing code if it simplifies fixing a particular bug or adding a new feature.

**Comment by ctrlcctrlv** [comment]
Hi guys:

I have a patch for this, but it won't make it so we can build FontForge with a C++ compiler. Even with `-Wno-c++11-narrowing`, `-Wno-deprecated`, and `-Wno-writable-strings`, all of which are required, we still can't build with `clang++`&mdash;

```
fontforge/nowakowskittfinstr.c:4054:23: error: cannot initialize a variable of type 'StemData *const *' (aka 'stemdata *const *') with an lvalue of type 'const void *'
    StemData * const *s1 = _s1, * const *s2 = _s2;
```

Not to mention how many times we need to do things like this to avoid `error: assigning to 'struct ... *' from incompatible type 'void *'`&mdash;

```diff
@@ -2903,10 +2903,10 @@ return;         /* Can't randomly add things to a CID keyed font */
 return;
 
     genchange->g.cnt = genchange->m.cnt+2;
-    genchange->g.maps = malloc(genchange->g.cnt*sizeof(struct position_maps));
+    genchange->g.maps = (struct position_maps*)malloc(genchange->g.cnt*sizeof(struct position_maps));
 
     if ( genchange->feature_tag!=0 ) {
-       uint32 *scripts = malloc(cnt*sizeof(uint32));
+       uint32 *scripts = (uint32*)malloc(cnt*sizeof(uint32));
        int scnt = 0;
        for ( enc=0; enc<fv->map->enccount; ++enc ) {
            if ( (gid=fv->map->map[enc])!=-1 && fv->selected[enc] && (sc=sf->glyphs[gid])!=NULL ) {
@@ -3045,7 +3045,7 @@ return;
     }
 
     genchange->g.cnt = genchange->m.cnt+2;
-    genchange->g.maps = malloc(genchange->g.cnt*sizeof(struct position_maps));
+    genchange->g.maps = (struct position_maps*)malloc(genchange->g.cnt*sizeof(struct position_maps));
 
     if ( sc->layers[layer].splines!=NULL ) {
        SCPreserveLayer(sc,layer,true);
```

I'm beginning to think the juice just ain't worth the squeeze, so am closing this metabug, and will not be filing a PR to fix this, as so much more needs to change than just a few names. If someone's interested, they can reopen a general issue to track "building FontForge with a C++ compiler."
