### ISSUE TITLE
Fontlint not running on latest OSX builds

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#383]
On latest OSX builds Fontlint is failing to run because fontlint expects the fontforge binary to be at '/opt/local/bin/fontforge', when in fact it is in same directory as fontlint, aka './fontforge'

Issue can be fixed by changing line 1 of fontlint
from 
# !/opt/local/bin/fontforge -lang=ff

to
# !./fontforge -lang=ff

**Comment by jtanx** [comment]
The shebang is generated based on the prefix set, so this is probably fixed.
