### ISSUE TITLE
Cannot switch active glyph freely when 50 glyphs or more are typed

### ISSUE THREAD

**Issue by hyvyys** [fontforge/fontforge#3830]
### Video

https://recordit.co/V77AHqkQcl

### Versions

FF 13-April-2019, Windows 10

### Actual behavior

When there are 49 or less glyphs, switching active glyph by clicking it works fine. After typing the 50th glyph, you can only switch to a later glyph, you cannot switch back to a glyph that sits in a previous position (to the left of the active glyph), unless you select the last glyph first. Only when the last glyph is active selecting a glyph to the left is possible.

In addition, with this amount of glyphs not all of them are visible in the window which cannot be scrolled all the way to the left. After a glyph closer to the left is selected, the scrollable area expands, but since there's no way to select the now accesible glyphs even farther to the left, there is no way to select the first glyph other than removing glyphs from the preview text.

### Expected behavior

All glyphs should be selectable freely regardless of their number. Window should be freely scrollable and the scrollable area should span across all glyphs.

### Steps to reproduce

1. Type 50 glyph names or more in the preview input.
2. Switch to any glyph other than first and last.
3. Try to switch to any other glyph to the left of the selected one — fails.

### Workaround

Shorten the preview text to less than 50 glyphs.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

**Comment by hyvyys** [comment]
Maybe related: #3162

**Comment by ctrlcctrlv** [comment]
I researched this&mdash;and sorry, I don't feel that this is a valid bug. `int additionalCharsToShowLimit` in `charview.c` is 50; `additionalCharsToShow`, the member of struct `CharView` (`views.h`), is 51, comment &laquo;`additionalCharsToShowLimit` + 1 in size&raquo;.

I think 50 is a logical number to use. Maybe it should be configurable, but I'm dubious as to why you need more than 50. It should work to just change the numbers in the places I mentioned and recompile.

Why do you want more than 50 to begin with?

**Comment by hyvyys** [comment]
In paid apps like FontLab you can even type out whole paragraphs with
multiple lines. If you think the number of characters should be limited,
then so be it but the behaviour of the app should be cohesive and
transparent to the user. If max chars are 50, then it should not be
possible to type more. Currently it is possible which leads to buggy
behavior one way or another.
I don't care, I just report what I see is wrong. No need to act on it!
Sorry to bother you.

Thanks,
Adam

śr., 31 lip 2019, 13:05 użytkownik Fredrick Brennan <
notifications@github.com> napisał:

**Comment by skef** [comment]
Is there a specification of this interface written down anywhere (other than the implementation)? That is, a list of the specific operations it's intended to support?

**Comment by ctrlcctrlv** [comment]
This is now configurable as of #4115. Closing as resolved in latest version.
