### ISSUE TITLE
Please correct font line height in GUI

### ISSUE THREAD

**Issue by milotype** [fontforge/fontforge#3835]
FontForge version 20190413 based on sources from 26-Jul-2019 git:279e69163e4da2be6240d1b35fdbb6438e792344
MacOSX 10.11.6

Due to bad font's line height, accented characters get cut off and accents don't show in the GUI.
=> see attachment
In the attached file there is a text marked with red color. The text is supposed to show "Širina". The accent of "Scaron" doesn't show.

![Font line-height](https://user-images.githubusercontent.com/43657314/62090972-2138df00-b26f-11e9-9202-294242e26420.png)

**Comment by milotype** [comment]
... and one more picture, to see how cramped the text appears.

I know that some font changes can be done at:
`/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/resources`
but I don't know how to manipulate line-height.

It appears, that if an icon is present on the line, the icon's height takes precedence. In such cases the text is better.

So please, do make a general change for the line-height (or use font's bounding box), so accents show and so lines aren't so cramped.

![GUI line-height](https://user-images.githubusercontent.com/43657314/62154678-7fb19c00-b307-11e9-9328-0432e38223c9.png)

**Comment by ctrlcctrlv** [comment]
I thought about this a little. It's probably fixable, but I'm not sure that it's desirable for languages without accents (like English, the most commonly used language for using FontForge) as it will make the lines unnecessarily tall.

FontForge is a font editing program after all, so why not make a font where the accents remain below the Ascent line? Certainly that's possible to do, and would solve your problem without having to change things for everyone else. Just a thought :smile_cat:

**Comment by ctrlcctrlv** [comment]
I decided to try it, and I think my idea works well, with some caveats.

I opened Cantarell, increased both the Ascent and Descent by 200, and changed family name to `QCantarell`. I then made fontconfig prefer QCantarell whenever a Sans font is requested if possible, and to pick QCantarell if DejaVu Sans, Helvetica or Arial is requested via `~/.config/fontconfig/fonts.conf`.

![2019-07-31-194207_1282x739_scrot](https://user-images.githubusercontent.com/838783/62209138-55291700-b3cb-11e9-9470-84d8177175ff.png)

Now you see, text is small. No wonder, as this new font has a big ascent and descent. You'll have to increase the text size, I'm too tired to look through the X Resource Editor but it's certainly possible.

So, I think you should do this and not require all of us to change.

**Comment by ctrlcctrlv** [comment]
One more thing:

I'm astonished to find even using regular Cantarell there's no problem!

![2019-07-31-194853_1282x739_scrot](https://user-images.githubusercontent.com/838783/62209420-219abc80-b3cc-11e9-8233-afef4c613c86.png)

So now I'm certain you just need to choose a better font. Perhaps Cantarell can be made default on OS X @jtanx?

**Comment by skef** [comment]
This is arguably, if obliquely, related to #3610 .

**Comment by ctrlcctrlv** [comment]
Sorry for laugh emoji but yes, you are right, it is indeed in its own way _related_!

**Comment by skef** [comment]
I'm actually not just making a joke. This is one of a small number of cases in which FontForge has to decide on a reader-oriented line height based on the font metrics.

**Comment by ctrlcctrlv** [comment]
Well, certainly that version of Helvetica is not suitable. It's meant to be very tightly packed, and they put the accents way above the ascender line. I don't know what we could do about this, or if we should do anything.

**Comment by skef** [comment]
Do we have access to it? What are it's internal metrics?

**Comment by ctrlcctrlv** [comment]
I wish I knew. If you have a Mac, I'm sure it's there somewhere. I looked on my PC and I don't have access to it, no. Apple distributes it with their operating system so it shouldn't be _that_ hard to get a copy. Perhaps TeX Gyre Heros (TeX Helvetica) has the same metrics?

**Comment by ctrlcctrlv** [comment]
TeX Gyre Heros is a dead end; it does not have the same metrics&mdash;it works fine. You're going to have to look at Apple's proprietary Helvetica.

![2019-07-31-200815_1282x739_scrot](https://user-images.githubusercontent.com/838783/62210489-dfbf4580-b3ce-11e9-8bda-30cfe9a501d8.png)

**Comment by skef** [comment]
[Helvetica 12.0d1e3](https://support.apple.com/en-us/HT206872), apparently.

**Comment by skef** [comment]
I think we should leave this open until it's determined whether there's a reliable way of interpreting the metrics of these fonts that FontForge currently ignores. If this is the system Helvetica it's not as if it's an obscure font file.

**Comment by milotype** [comment]
I would still like to ask, to reconsider my proposal.
Attached you can see all highest-level menu items. They do not all use the same line-height (inconsequent use in UI). Those marked with a red arrow are simply too crowded, no matter accents or not. It's generally not just the accents, but the accelerator marks as well.

And I guess the icons don't determine the line-height => see 4th column Hint-menu.

If the whole program would (proportionally) use line-height as in those unmarked menu blocks, that would improve the readability. So for menu items, menu sub-items, tool-tips, etc.

IMO, the programm should be readable no matter what font is used, and should definitely work with the, as default defined, "sans" font. I don't think it's good to ask the user to change the font (especially asking a non-programmer to chage some code in a certain file).

![Line-height-menu](https://user-images.githubusercontent.com/43657314/62210247-f5674780-b39b-11e9-8266-a09a03fbb378.png)

**Comment by ctrlcctrlv** [comment]
OK yeah I see your screenshot @milotype . Thanks, that's helpful, and it doesn't happen to me on Linux, all lines are pretty much the same height across the menus/dialogs/views.

I don't know if I can ask you to share the font with us. It's an (a) old version (b) in an obsolete OS but it is proprietary...your call.

**Comment by ctrlcctrlv** [comment]
Actually, I confirmed it's just less obvious on Linux. Side-by-side the difference can be seen, I think it just comes down to icons increasing the line height.

![image](https://user-images.githubusercontent.com/838783/62211263-9b34a980-b3d0-11e9-8307-d352e217c279.png)

**Comment by skef** [comment]
@milotype That increased spacing is just an artifact of the images on the left of those menus. The ones "without" images have empty ones to space them out.

**Comment by skef** [comment]
I would be happy seeing a few screenshots of the font metrics for that file open in FontForge, for a start. That shouldn't be an IP violation.

**Comment by ctrlcctrlv** [comment]
@skef Why is the difference so different between platforms? I had to line them up to see it on Linux, but in his Mac screenshots it's obvious; the MM menu is like half the size but still has five elements.

**Comment by skef** [comment]
Element -> Font Info -> General being the most important .

**Comment by skef** [comment]
@ctrlcctrlv Eh -- the images are of a fixed size (relative to DPI in a complex way) and the font is scalable. If the image is the larger of the two then the lines that have one will be larger, otherwise they won't be.

**Comment by ctrlcctrlv** [comment]
I get it. Yes, I agree, @milotype , start with showing us the metrics of the font as reported by FontForge.

(btw, this is for @skef only; thanks for helping me close out that issue! That was really kind of you, I know it was a simple thing to just add a comment but I couldn't really use my PC properly due to where I was burned until like...yesterday. I'm glad to be back but I'm going to bed now. I have to finish QRD by tomorrow to release it on time with the FontForge release hehe.)

**Comment by milotype** [comment]
I don't exactly know what "sans" font gets used on my mac by FontForge. But it does look like some Helvetica (see screenshot, I changed the font-size in the "resources" file to make it obvious like this: `Font: 400 10pt sans` to `Font: 400 20pt sans`)

![20pt](https://user-images.githubusercontent.com/43657314/62211685-7bd15880-b39f-11e9-8295-86c18a7de142.png)

**Comment by milotype** [comment]
Please hold on ... I've just changed the definition of "sans" to "Noto sans" and everything looks much better!
I'll try some more fonts.

**Comment by jtanx** [comment]
sans maps to [Helvetica](https://github.com/GNOME/pango/blob/dd3fc1b1976890bde122c87813f03da6c26129b9/pango/pangocoretext-fontmap.c#L156-L157)

**Comment by milotype** [comment]
In general I see 2 issues:
1. No matter what the problem is with the font which FontForge gets from the system, the line-height should still be the same accross the UI => consistency of menu items, menu sub-items, tool-tips and for glyph-tags (see attachment).
![glyph-tags](https://user-images.githubusercontent.com/43657314/62217932-cbb61c80-b3ab-11e9-9043-81d9981be4e3.png)

2. Font metrics (obviously) play a roll. I changed to "Helvetica" and to "Times" (both dfont format an mac) and both have the same problem, cramped lines of text. Changed to "Optima" (ttc font) and it looks better (but it doesn't have croatian diacritics!). Changed to "Geneva" (dfont) looks better, but also not perfect.
No matter what font gets specified, for instance `Font: 400 10pt Avenir,sans` FontForge (on Mac) uses Helvetica (and the order of listing also doesn't matter). Only when removing "sans" from the shorthand, the font specified gets used.

**Comment by milotype** [comment]
@skef 
> Element -> Font Info -> General being the most important .

Could some other metric be used instead of those – maybe the glyph height of "Aring"?

**Comment by skef** [comment]
@milotype I doubt you'll convince FF developers to put in an arbitrary kludge for this case, although that could happen. I raised my question above because presumably other Mac applications use these fonts and it's unlikely they have this problem -- system fonts tend to be well-behaved on "their" system.

So the question is: what vertical metrics are Mac applications using with these fonts, or in general? If we know how the "official" mac app decision is being made it's reasonable for FontForge to mimic it (either on a per-font basis or when compiled on a Mac).

**Comment by milotype** [comment]
**Whooaw**, I just realized FontForge doesn't use the standard apple menu bar!!! 
Instead it uses its own (maybe a leftover of XQuartz/X11). 
See attachment: comparing menu bars of diverse menu bars. The last one is _Inskcape_ which still runs under XQuartz, but it still has all sub-menus with good and identical line-heights. Please don't ask me how they do it, i'm no programmer, just a translator with little programming knowledge.

**Comment by milotype** [comment]
sorry, here's the pict …
![Mac-Comparison](https://user-images.githubusercontent.com/43657314/62250907-7a7b4c80-b3ee-11e9-9dcf-ed8323a3fafb.png)

**Comment by skef** [comment]
Let's redirect this discussion over to #3844 .

**Comment by skef** [comment]
I suspect the problem here is that FontForge is doing this:

```
void GGDKDrawGetFontMetrics(GWindow gw, GFont *fi, int *as, int *ds, int *ld) {
    //Log(LOGDEBUG, " ");

    GGDKDisplay *gdisp = ((GGDKWindow) gw)->display;
    PangoFont *pfont;
    PangoFontMetrics *fm;
    PangoFontMap *pfm;

    _GGDKDraw_configfont(gw, fi);
    pfm = pango_context_get_font_map(gdisp->pangoc_context);
    pfont = pango_font_map_load_font(pfm, gdisp->pangoc_context, fi->pangoc_fd);
    fm = pango_font_get_metrics(pfont, NULL);
    *as = pango_font_metrics_get_ascent(fm) / PANGO_SCALE;
    *ds = pango_font_metrics_get_descent(fm) / PANGO_SCALE;
    *ld = 0;
    pango_font_metrics_unref(fm);
    if (pfont != NULL) {
        g_object_unref(pfont);
    }
}


    GDrawWindowFontMetrics(m->w,m->font,&m->as, &ds, &ld);
    m->fh = m->as + ds + 1;            /* I need some extra space, else mneumonic underlines look bad */

```

Rather than using the output of `pango_font_metrics_get_height()`

Since `ld` doesn't appear to be used it should be easy enough to repurpose that for the height and use it where needed.

**Comment by ctrlcctrlv** [comment]
OK, but be mindful of the MetricsView. Please don't change its appearance. I feel like the narrower rows were done on purpose there.

![image](https://user-images.githubusercontent.com/838783/113858706-08860980-9772-11eb-8899-52d805c93d6e.png)

**Comment by skef** [comment]
To me "narrow" indicates width rather than height so I'm not sure how that relates.

**Comment by ctrlcctrlv** [comment]
Doesn't have to be. A narrow road, narrow highway, narrow hallway. Those all run from left to right, like the row in the table.

**Comment by skef** [comment]
Those change with perspective but are ... still widths? The question is how using font lineheight instead of calculating it from the ascent and descent would affect things that run left to right in a UI (without rotating the text).

**Comment by ctrlcctrlv** [comment]
OK. I don't want the rows to be taller. No need to argue about meanings of words. :)

**Comment by skef** [comment]
Well I just looked at the pango code and played around with ours a bit and it doesn't seem like there should be a difference between ascent+descent and height coming out of Pango.

I suspect the solution for this (short of adding some knobs to increase inter-line distance in various GGadgets) is just to pick better/more troubleshot fonts. Something I'm working on should help somewhat with that.
