### ISSUE TITLE
It would be nice to have a Python API for writing feature files

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3845]
It would be nice to have a Python API for writing feature files.

I've just released v1 of Quaerite Regnum Dei, my font based on 16th century handwriting. This font has more than one version of each small letter, so that it looks less like a font and more like real handwriting.

![2019-08-01-132741_2431x598_scrot](https://user-images.githubusercontent.com/838783/62275252-231fbf80-b474-11e9-8cce-a81a38f3a796.png)

![2019-08-01-143333_1633x541_scrot](https://user-images.githubusercontent.com/838783/62275368-5e21f300-b474-11e9-8a0c-783895c66b60.png)

I acheived this with contextual alternates, some of which are very hacky. (See https://github.com/ctrlcctrlv/QuaeriteRegnumDei/blob/master/features.fea#L9 )

I generated my features by writing a script. But some of the code I wrote is, to put it mildly, horrible!

```python
print("feature salt { lookup salt1 {")
for k, l in D.items():
    if k+".alt" in l:
      print("sub {0} by {1};".format(k, k+".alt"))
print("} salt1; } salt;")
```

Eek! Certainly there must be a better way? Like

```python
ff = fontforge.FeatureFile("features.fea", "w+")
calt = ff.newFeature('calt')
calt_l = calt.newLookup('calt1')
calt.addSub(k, k+".alt")
ff.close() # Does the final write and closes the file.
```

Am I just being too picky? I won't write this for just me to use, but if others think this would be valuable I could work on it.

**Comment by skef** [comment]
How would this be functionally different from:

1. Opening the relevant font file
2. Calling `addLookup`
3. Calling `addLookupSubtable`
4. Calling `generateFeatureFile`, either with no extra lookup argument or the name of the added lookup

?

**Comment by ctrlcctrlv** [comment]
It wouldn't be, thanks.

**Comment by khaledhosny** [comment]
There is also `fontTools.feaLib`, you can use it to create feature files, but it is a bit low level.
