### ISSUE TITLE
FontForge should warn me if it has an unsaved script in memory

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3846]
Yes, I know, I'm dumb, but I accidentally closed FontForge which had a script I was working on in &laquo;File&rarr;Execute Script&hellip;&raquo;. Needless to say, that script is gone now, in computer heaven. :cloud: :cry: 

FontForge should warn me if I've forgotten to export my script.

**Comment by khaledhosny** [comment]
Such a warning should have a “don’t warn me again” check, as I often use this window to write quick code I have no interest in keeping around and getting a warning every time will get into the way.

**Comment by ctrlcctrlv** [comment]
Yeah, and that check would set a preference. I hear you. I also often write throwaway code there, but I won't be annoyed by a warning in those times.
