### ISSUE TITLE
RealNear() is weird near zero. 

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3848]
This is `splineutil2.c:RealNear()` with the float variant removed for clarity:
```
int RealNear(real a,real b) {
    real d;

    if ( a==0 )
        return( b>-1e-8 && b<1e-8 );
    if ( b==0 )
        return( a>-1e-8 && a<1e-8 );

    d = a/(1024*1024.);

    a-=b;
    if ( d<0 )
        return( a>d && a<-d );
    else
        return( a>-d && a<d );
}
```
Suppose `a` is 0.0 and `b` is 1e-10. Then this evaluates to true. And if `a` is 1.0 and `b` is 1+1e-10 this also evaluates to true, given that `a` will be assigned -1e-10, which is between 1/(1024\*1024) and -1(1024\*1024).

But suppose `a` is 3\*1e-13 and `b` is 2\*1e-13. Then `a` will be assigned 1e-13, which is definitely not between 3\*1e-13/(1024\*1024) and -3\*1e-13/(1024\*1024). 

Given how floating point values work you can make an argument for a different test around 0. However, I don't see how that would apply to this function given the up-front tests against 0. Why would 0 and 1e-9 be near to each other when 3\*1e-13 and 2\*1e-13 are not?

**Comment by ctrlcctrlv** [comment]
Yikes. I bet this is the cause of quite a few spline manipulation bugs.

**Comment by skef** [comment]
I should clarify that I added this as an issue rather than just filing a PR because the larger project should discuss what Near-related functions are needed and how they should be implemented. There is probably (?) a reason `RealNear` is not equivalent to `RealWithin` called with a particular value. Maybe there should be a function more sensitive around 0 but this one seems wrong.

**Comment by frank-trampe** [comment]
For what it's worth, my explorations with spline overlap have shown that there is not a one-size-fits-all metric for whether two values are close. When accuracy counts, we ought to be using RealWithin.

The outputs aside, the logic in this function seems unnecessarily convoluted to me. And, on the topic of the outputs, having a special case for zero seems destabilizing since two relationally identical pairs of points would give different results depending upon their absolute locations. And then there's the problem you point out.

The challenge here is that we do not have very good geometry tests, so we could easily miss a stack of regressions pushing an intended fix.

**Comment by skef** [comment]
> The challenge here is that we do not have very good geometry tests, so we could easily miss a stack of regressions pushing an intended fix.

I second this problem, but my attempt to use `RealNear()` in a new context had such bad results that I think some investigation is in order on this particular problem. @ctrlcctrlv is right that this could be the source of multiple spline manipulation bugs in the current code.

**Comment by ctrlcctrlv** [comment]
I can help create some tests, depending on what you want to test. I mostly use the calligraphic stroker and the overlap tools. I could help create tests for the circular stroker but since I'm working on replacing it I'd rather not

**Comment by frank-trampe** [comment]
That would be great. Then we can come up with a few iterations of this function that make sense and see which of them don't cause problems. We don't need fully automated validation (which would probably be a lot of work), just input files and scripts that yield results that we can check visually.

**Comment by frank-trampe** [comment]
Looking at this again, I note that the threshold scales with `a` but not with `b`, which, like the special-zero-case, creates a location-dependence undesirable for geometrical operations and also creates an asymmetry where `RealNear(a, b)` might give a different result from `RealNear(b, a)`.

**Comment by frank-trampe** [comment]
A quick review of the grep results for `RealNear` suggests that most use cases do not anticipate tolerance scaling based on the magnitude of the coordinates and do not anticipate the asymmetry. I think that a good starting point for discussion would be a function that uses a simple global threshold for use in all point comparisons. We might retain the old code in a new function for use in special cases that benefit from the quirks.

**Comment by skef** [comment]
> I think that a good starting point for discussion would be a function that uses a simple global threshold for use in all point comparisons.

Sounds right to me.

**Comment by JoesCat** [comment]
There are a couple places in the code that I thought of as bad too, something like:
val = int(real)
I would have expected
val = int(real+0.5)
for getting integer values

**Comment by jtanx** [comment]
We should probably just implement something similar to that in https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/.

Something I never really understood is how those WithinXRoundingErrors work, like is that meant to be in terms of ULPs?

**Comment by skef** [comment]
> Something I never really understood is how those WithinXRoundingErrors work, like is that meant to be in terms of ULPs?

I haven't looked at the code closely enough to be sure, but I think that's right.

**Comment by skef** [comment]
@frank-trampe I have a suggestion for this that I'll probably turn into a PR sometime tonight. In order to change this with a smaller amount of risk I suggest that we retain the current cut-offs for when one of the values *equals* zero (1e-8 for double and 1e-5 for float), but change the general cut-off to "within" the power of two closest to the values of (1/1024*1024) and (1/1024*64) respectively, so I guess 1e-6 and 1e-5. (The float values probably don't matter at this point anyway). 

That eliminates most of the distortion but retains the current cutoffs when zero is passed as a constant, which may matter.

**Comment by frank-trampe** [comment]
Fine with me. I don't have a better proposal, and this seems easy enough to test.

**Comment by JoesCat** [comment]
If you look at ``` d = a/(1024*1024.) ``` you'll see you have non-consistent results, for example, a=1 or a=2047.
To be more consistent, you can probably use a window several decimal places down, like maybe 1e-5 to allow for rounding errors, example:
```c
int RealNear(real a,real b) {
/* return true if a and b are within 1e-5 of each other, otherwise return false */
    real d = a - b;

    if ( d >=0 )
        return( (d < 1e-5) );
    else
        return( (d > -1e-5) );
}
```

**Comment by skef** [comment]
@JoesCat are you indirectly commenting on #4119? I'm not sure where your note fits into the picture.

**Comment by JoesCat** [comment]
I have watch turned-off - didn't see it.
