### ISSUE TITLE
FontForge Website Downloads Broken

### ISSUE THREAD

**Issue by reidbiztech** [fontforge/fontforge#3851]
Hi, this is still broken in Firefox. It is blocked by browser policy now - the error in the console:

> Load denied by X-Frame-Options: https://sourceforge.net/projects/fontforge/lists/fontforge-announce does not permit cross-origin framing.
Blocked loading mixed active content “http://mm.fontforge.org/ffml/presubscribe.php”

Could you just post direct links to the downloads (file checksums would be great too - maybe even a good old fashioned ftp & mirrors?).

I think the current situation on the website is doing serious damage to FontForge.

P.S.: anyone have a download link for the current version for windows?

_Originally posted by @reidbiztech in https://github.com/fontforge/fontforge/issues/3351#issuecomment-517694377_

**Comment by reidbiztech** [comment]
Oh, by examining the source of https://fontforge.github.io/en-US/downloads/windows/ I was able to determine that the windows download is here: [https://fontforge.github.io/en-US/downloads/windows-dl/](https://fontforge.github.io/en-US/downloads/windows-dl/)

**Comment by frank-trampe** [comment]
Yes, we are familiar with the website structure.

**Comment by reidbiztech** [comment]
OK, great, was just a heads up. Eager to try the latest version. Glad to see FontForge is still here! I have a client who may be able to use it, and if it goes well, we will donate if we can. I do think a broken subscription gateway could be a problem though. Is the site source in a repo I could make a pull request to with a fix? (might be easy for me to do - a little something to help a bit?)

**Comment by frank-trampe** [comment]
It's already fixed.

**Comment by reidbiztech** [comment]
Awesome! Let the fonts flow!

**Comment by frank-trampe** [comment]
And thanks for letting us know by the way. Developers seldom have cause to go through the download channels, so this sort of thing goes unfixed until somebody tells us about it.

We love donations, but we also like to make sure that people are on the mailing list. The 2012 release definitely lived too long, and we don't want that to happen again.

**Comment by frank-trampe** [comment]
To answer your question from before, the website code is [here](https://github.com/fontforge/fontforge.github.io/).

**Comment by reidbiztech** [comment]
Cool - if I see anything else wonky along the way I'll let you know. Thanks!
