### ISSUE TITLE
run appstream validation as part of the CI

### ISSUE THREAD

**Issue by muelli** [fontforge/fontforge#3860]
It would be great to prevent breakage on the appdata files, like it happened in https://github.com/fontforge/fontforge/pull/3812 (which then needed to be fixed up with https://github.com/fontforge/fontforge/pull/3858).

I know two tools to validate, appstream-util and appstreamcli. The former is used by the flathub build bot.

**Comment by ctrlcctrlv** [comment]
Good idea. Are those tools commonly packaged?

**Comment by muelli** [comment]
yeah, appstream-util has been available for ages: https://packages.debian.org/search?keywords=appstream-util

**Comment by ctrlcctrlv** [comment]
I'm a bit confused since you offered two options. 

* Which is better?
* Will you be opening the PR to incorporate one (or both?) into our CI, or are you asking one of us to?

**Comment by muelli** [comment]
> * Which is better?
> 
For alleviating my pain, appstream-util is better, because it is used by flathub. And I try to maintain fontforge over there, so that's was causing my pain. 

> * Will you be opening the PR to incorporate one (or both?) into our CI, or are you asking one of us to?

I don't intend to find out how to make the check on Travis work. I've never worked with Travis and so far I it's not on my roadmap to find out how it works.  I might end up doing that, but I wouldn't hold my breath. 

Calling the appstream-util binary is very simple. You give "validate" and the appdata file as arguments. And then it complains and exits with a non-zero code.

**Comment by jtanx** [comment]
I've added appstream validation as part of #3879, I built appstream-util into an AppImage and run strict validation on the appdata xml when building the AppImage; https://travis-ci.org/fontforge/fontforge/jobs/572278600#L10791
