### ISSUE TITLE
Android version (other than by using Userland app)

### ISSUE THREAD

**Issue by cssobral2013** [fontforge/fontforge#3864]
Because it's growing the number of Android smartphones (and of tablets, to some extent), it's not a bad Idea to implement an Android version of this app (other than by using Userland).

**Comment by cssobral2013** [comment]
This is because there's NOT ANY official font editor for Android (other than by Userland), so this can be a Pioneer project.

**Comment by frank-trampe** [comment]
That would require building a new touch-friendly small-screen user interface, something for which we do not have adequate engineering resources, and it is not clear to me why somebody would be designing typefaces on a mobile device anyway. Somebody who has the time and the vision for such an undertaking is welcome to build on libfontforge.

**Comment by cssobral2013** [comment]
@frank-trampe, I'll close this issue for now, and If and when someone is interested on this, feel Free to re-open It.

**Comment by cssobral2013** [comment]
Another idea, excluding Userland, would be to implement a Windows-ARM version and running it on Wine.

**Comment by cssobral2013** [comment]
Although Wine exists for Android, it isn't useful because it requires an x86/64 device, and almost all non-low-end smartphones/tablets are ARM64.
