### ISSUE TITLE
Font generated significantly smaller filesize?!

### ISSUE THREAD

**Issue by zambala** [fontforge/fontforge#3868]
Helo,
I'm an amateur with FontSourge...
I was trying to open a TTF file, copy 2 fonts and Generate Fonts...
but - the resulting TTF file is significantly smaller as original file; I didn't intend to make it smaller, I wonder if I could loose some font quality or something?!
The original file is 302 kb; after this it is 250 kb; why so ?!
also - I was opening to correct in FontForge from TTF file - I have also an original .sfd file from fonts original author, but - it is opening without empty squares - like all empty glyph squares would be deleted?! - and I could not find how to insert my new glyphs in that file;

**Comment by skef** [comment]
> I have also an original .sfg file from fonts original author, but - it is opening without empty squares - like all empty glyph squares would be deleted?

If this is referring to a FontForge SFD file, it probably has the compact encoding enabled. Try opening it in FontForge, going to the "Encoding" menu at the top and see if "Compact" has a checkmark next to it. Selecting that option should remove the check and display the "empty" glyphs (for whatever encoding is enabled). 

For the TTF question it's hard to answer these without data. If you want to explore this yourself I recommend installing [fonttools](https://pypi.org/project/fonttools/) and using its "ttx" command to make an XML version of each TTF file. Then you can look at them in a text editor to see what's different.

**Comment by MdAyquassar** [comment]
Starting with TeX Gyre Termes Math v 1.543, I open the file texgyretermes-math.otf of size 532404 b with fontforge, notice that "Compact" is not checked, press Ctrl+Shift+G to regenerate the fonts into file TeXGyreTermesMath-Regular.otf, leaving all the options at their defaults, and obtain a bunch of errors:

- Self intersecting

- Missing Points at Extrema

- Glyph containing overlapped hints (in the same hintmask)

The detailed information would be too long to review in detail; I don't understand it anyway. So, I ignore this list and press "Generate" to create the fonts and obtain a brand new TeXGyreTermesMath-Regular.otf of size 522156 b (later: 522148; I don't know why the contents changes between compilations, the file seems compressed anyway). Anyway, the file got smaller by around 10 kb wrt. the original. Why? I have not omited any useful information during regeneration, have I? Or are the new compression algorithms so much better or, perhaps, even lossy?

Crosspost: http://tex.stackexchange.com/questions/505134/why-does-regenerating-a-font-by-fontforge-makes-it-smaller

**Comment by frank-trampe** [comment]
`ttx` is definitely the right tool. Are the XML outputs so different that you can't visually parse the diff, or are there just a few tables of unknown significance that differ?

**Comment by MdAyquassar** [comment]
```
$ diff texgyretermes-math.xml TeXGyreTermesMath-Regular.xml | wc -l
50083
$
```

**Comment by jtanx** [comment]
There's no guarantees on a 1:1 byte exact generation for various reasons.

FontForge has its own internal representation which it translates to/from when reading and generating, and I guess some of it is nondterministic (e.g. apparently hinting subroutine ids going off the ttx dump).

If you can isolate a *functional* difference between the two then feel free to file another issue.
