### ISSUE TITLE
I copied Glyphs, but system doesn't see them

### ISSUE THREAD

**Issue by zambala** [fontforge/fontforge#3870]
Hello,
I copied my glyphs, and generated ttf file, but it seems system doesn't see my glyphs.....
I installed them, and went to Word to check; If I select some text - Word shows those fonts are not in MyFont.... I can only insert them by -> insert a symbol -> insert , then it inserts; but otherwise doesn't see.....

Also.... while copying - I had a "double anchor" warning; I don't know what they meant by "anchor"; I was copying capital and small font Ḻḻ with "copy after" - and both gave warnings of "double anchor" - yet, the Capital font copied fine Ḻ, but the small font copied like _l and I don't know how to correct it....with line under l...
upd.
I somehow put the line under _l right way with ‘Element > Build > Build Accented Glyph’ , not sure yet how....

But I am still worried - why system doesn't see them...
If I insert my new fonts - and select them - they instantly show default Times New Roman

**Comment by ctrlcctrlv** [comment]
Hello. We need an SFD, and in this case maybe some screenshots, to help. 

Without these things, based on your description of the problem, I can only guess it's encoding related. Perhaps all of the glyphs are -1. Windows uses fallback fonts when the requested font doesn't have a glyph at a certain encoding.

**Comment by zambala** [comment]
It seems it resolved after I restarted Word; sorry;
