### ISSUE TITLE
FontForge app crash libpython3.7m.dll

### ISSUE THREAD

**Issue by ShadyGaDa** [fontforge/fontforge#3878]
![Untitled](https://user-images.githubusercontent.com/5815779/63090870-86b9ea80-bf54-11e9-90ca-6ee0eae1cabb.jpg)
unexplained crash on windows 8.1 x64
I have 2.7 and 3.6 python installed
will try to install 3.7 see if that helps.
otherwise at a loss?

**Comment by jtanx** [comment]
Is it an immediate crash on startup?

**Comment by ShadyGaDa** [comment]
Yep

**Comment by ctrlcctrlv** [comment]
You say you have 3.6 installed but Windows is blaming 3.7; one of you is wrong.

**Comment by jtanx** [comment]
What other Python(s) you have installed should have no bearing on this as we bundle our own (mingw) Python with the install.

**Comment by ShadyGaDa** [comment]
You are right they have no bearing.
Installed separate on path plus 3.7 now.
As you say nothing to do with this.
The program just won't start is all.
I will try in Windows 10.

**Comment by ShadyGaDa** [comment]
Having now found fontforge.exe in bin all running well.
run_fontforge.exe misleading with error as above.

**Comment by ctrlcctrlv** [comment]
I'm glad you resolved your problem, but `run_fontforge.exe` works for me just fine on Windows 10; if you tell the installer to make a desktop icon that's what it will link to.
