### ISSUE TITLE
CMake switchover meta-issue

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3880]
1. Update Install-git.md for CMake
    1. Refer to `CMakeLists.txt`
    2. Document `-DCMAKE_INSTALL_PREFIX` and `-DCMAKE_INSTALL_MANDIR`
2. Copy hotkey file so that it works with `build/bin/fontforge`?

**Comment by skef** [comment]
Maybe this issue can stick around a bit while we work out what needs to go in. Some subset of the Wiki info would be good, although it's fine to refer off to `CMakeLists.txt` for some of it. 

I think the distro installers would appreciate a note about (at least) `-DCMAKE_INSTALL_PREFIX` and `-DCMAKE_INSTALL_MANDIR` (assuming I have those right).

**Comment by skef** [comment]
(Now I'm just writing random notes to @jtanx ... sorry.)

It would be convenient if the hotkey file could be copied under `build` to a place where `build/bin/fontforge` would pick it up, if that could be Humpy-Dumptied together.

**Comment by skef** [comment]
Edited this into a meta-issue

**Comment by jtanx** [comment]
Huh, I thought I did document CMAKE_INSTALL_PREFIX but I guess not, I've added that and the note on CMAKE_INSTALL_MANDIR (well really any installable dir from [GNUInstallDirs](https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_PREFIX.html)) to the wiki.

**Comment by ctrlcctrlv** [comment]
Why does it take so long to rebuild (200+ objects) just from a small change to `inc/gimage.h`?

**Comment by jtanx** [comment]
Probably because all 200 source files include gimage.h in some way. Are you saying it's rebuilding more than on the autotools build?

**Comment by ctrlcctrlv** [comment]
I thought it did, but I just tested both of them and the autotools build is actually slower; sorry for the noise.

**Comment by ctrlcctrlv** [comment]
Sorry, this might be yet more noise, but I made a small change to the wiki to add the `-DENABLE_DEBUG=1` switch in the &ldquo;recommended for developers&rdquo; section.

https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge/_compare/0d3669d849c56534684394d240317d4df8bdee35...1ba621c7a23b11c56b54afaab146eca0af8dd894

This makes `TRACE(...)` work, which is a very useful macro for debugging quite a few areas of the code. I needed it for the [work I did today](https://mobile.twitter.com/FontForge/status/1162627336400846848).

**Comment by skef** [comment]
The decision to use a custom `-DENABLE_DEBUG` define rather than CMake's usual `-DCMAKE_BUILD_TYPE=Debug` has some side effects. The most important I've found is that `-DENABLE_DEBUG` still compiles with `-DNDEBUG` which turns off asserts. It also compiles with `-O2` which may be for the best but which does increase the incremental compilation time a bit (with `gcc` at least). The work-around is to use both `-DENABLE_DEBUG` and `-DCMAKE_BUILD_TYPE=Debug`.

Is there are reason not to just go with `-DCMAKE_BUILD_TYPE=Debug`?

**Comment by skef** [comment]
(Another reason to not use -O2 is that when debugging a lot of stuff winds up being marked "compiled out".)

**Comment by jtanx** [comment]
I mentioned it on the wiki, but `ENABLE_DEBUG` isn't very useful apart from enabling the TRACE macro (via defining FONTFORGE_DEBUG, iirc), which itself I've been meaning to clean up/unify with the gdk logger I wrote (since TRACE is not really much better than printf).

The only reason I added ENABLE_DEBUG was because it was a flag on the old autotools build system. As found, for actual debugging purposes, `-DCMAKE_BUILDTYPE=Debug` is what should be used.

There's probably a way to tie that FONTFORGE_DEBUG define to the build type too, so that ENABLE_DEBUG flag should probably just be dropped.

**Comment by jtanx** [comment]
Well actually we should just get rid of FONTFORGE_DEBUG and just check for 

```c
#ifdef DEBUG
```

**Comment by skef** [comment]
Eliminating the separate flag and documenting `-DCMAKE_BUILD_TYPE=Debug` aggressively would be my preference.

**Comment by ctrlcctrlv** [comment]
It's no problem with me if `-DENABLE_DEBUG` is merged with `-DCMAKE_BUILD_TYPE=Debug`. I find the `TRACE` stuff very useful for debugging, e.g., `wordlistparser.c`. While working I frequently add `TRACE`s. So as long as they aren't merged, developers should build FontForge with both options as I've specified in the wiki. Once they are merged, feel free to remove `-DENABLE_DEBUG` from the wiki, but not before.

**Comment by jtanx** [comment]
I'm just going to combine all my changes into https://github.com/fontforge/fontforge/pull/3879

I'll look at updating the docs next. But basically I think I got Debian packaging more or less working again. I can't believe how convoluted that process was.

**Comment by mvz** [comment]
Hi all :wave: I've been trying out the CMake build, and I must say I find it impractical to have the build directory be the working directory in my shell. One option I found for avoiding this is using the following commands from fontforge's top level directory:

```bash
cmake -B build -GNinja # more options here
ninja -C build
```

This way, I can easily run, e.g., `git grep` from the same shell.

**Comment by skef** [comment]
This seems done excepting doc changes and may be done period. I wanted earlier emphasis on debug builds but others might not. mvz has made another doc suggestion. 

What do you think @jtanx?

**Comment by jtanx** [comment]
I think I'd still like to get rid of ENABLE_DEBUG. As for how cmake/ninja is invoked, that's more of a personal preference.

**Comment by madig** [comment]
> One option I found for avoiding this is using the following commands from fontforge's top level directory:

(I have changed the wiki page on this. I added the RELEASE_TYPE explicitly because you need to for Ninaj and Makefiles, otherwise you get an unoptimized/non-Release build)

**Comment by jtanx** [comment]
>I added the RELEASE_TYPE explicitly

That's not necessary, I've already made it so it choose RelWithDebInfo by default.

**Comment by jtanx** [comment]
cmake -B also doesn't work for cmake 3.5.

**Comment by madig** [comment]
Ah, ok, didn't catch that. Back to the previous wiki content then.

**Comment by skef** [comment]
I believe this is done now.
