### ISSUE TITLE
Font Styles in various languages

### ISSUE THREAD

**Issue by milotype** [fontforge/fontforge#3882]
Not a bug, but merely a question.

After my PR #3834 for the "Font Styles in various languages" on the website, I wonder why the croatian trasnlation isn't being diplayed at
http://fontforge.github.io/en-US/documentation/customizing/fontstyles/
instead it's displayed on the "old" site at
https://fontforge.github.io/fontstyles.html

According to @jtanx my first PR #132 at fontforge/fontforge.github.io was the wrong place for submitting it.

Or is the "new" site just not updated yet?

**Comment by jtanx** [comment]
Ah yes, that's confusing. Basically the website is semi-ported to the 'new' layout, but we still have the old layout around. If you want to update the old layout, then you need to do what you did, but if you want to update the new layout, then that's editing directly e.g. https://github.com/fontforge/fontforge.github.io/blob/master/en-US/documentation/customizing/fontstyles.md

**Comment by milotype** [comment]
Ok, I just did it at fontforge/fontforge.github.io with
Update fontstyles.md with croatian #141

**Comment by milotype** [comment]
Sorry, the link seems to point to something else.
It is the PR 141 at `fontforge/fontforge.github.io` not `fontforge/fontforge`

**Comment by jtanx** [comment]
For cross-repo links to work, you need to write it like fontforge/fontforge.github.io#141

**Comment by milotype** [comment]
Ahhh, thank you!
