### ISSUE TITLE
Getting Data of a Subtable of a Lookup by Python

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3884]
How can I get data of a subtable of a GSUB lookup with Contexual Chaining Substitution type using Python? In other word, Does any method exit to getting data of a subtable of a lookup using Python?

_Note: I can't find any method in [this page](https://fontforge.github.io/python.html)_.

**Comment by skef** [comment]
For *normal* subtables you can do this (which you may already know):

1. `font.gsub_lookups` is a tuple of all the names of gsub lookups in the font, `font.gpos_lookups` is analogous. 
2. `font.getLookupSubtables()` takes the name of a lookup and returns a list of all subtables of that lookup.
3. `glyph.getPosSub()` takes the name of a subtable and returns the positioning/substitution info from that subtable *for that glyph*. 

I don't believe there is a similar programmatic interface for contextual subtables, but I could be mistaken about that. However, the answer to the question "Does any method exist to getting data of a subtable of a lookup using Python?" is "Yes." You can run `font.generateFeatureFile()` supplying the name of the lookup in question as the second argument and then extract the info from that file. That's a bit of a project, but fonttools has a [feature file parser](https://github.com/fonttools/fonttools/tree/master/Lib/fontTools/feaLib)

**Comment by AlirezaAlipour** [comment]
Thank you very much @skef.
