### ISSUE TITLE
The 'bootstrap' File Doest not Exit in The Current Source!

### ISSUE THREAD

**Issue by AlirezaAlipour** [fontforge/fontforge#3885]
Why the 'bootstrap' file does not exitst in the current source(commit 4dc8313c0b1abf51428ec27bbfc69a9580722da3)?

**Comment by skef** [comment]
The build system has changed from autotools/gnulib to CMake. See https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge

**Comment by AlirezaAlipour** [comment]
Thank @skef very much for your help, I wish you best.
