### ISSUE TITLE
fontforge on mac ImportError: No module named fontforge

### ISSUE THREAD

**Issue by Wassimo2** [fontforge/fontforge#3887]
i'm working on php app  using command line 
but when i call  fontfroge it doesn't work
ImportError: No module named fontforge

also this solution not working 
https://github.com/fontforge/fontforge/issues/2597

**Comment by jtanx** [comment]
Try the latest bundle from http://dl.bintray.com/fontforge/fontforge/

The python modules weren't relocated properly before

**Comment by ctrlcctrlv** [comment]
FontForge doesn't support PHP, so I have no idea what you even mean.

**Comment by jtanx** [comment]
ping @wassimo2

**Comment by ctrlcctrlv** [comment]
Closing as we don't even have a PHP module and @Wassimo2 is unresponsive.

**Comment by Wassimo2** [comment]
i'm working on lunix centos 6 and the last update available  is 2009

**Comment by jtanx** [comment]
You said Mac in the issue title, but now you say Centos? Anyway, if you're using Centos 6, you'll probably have to compile it yourself, which will be made difficult as all the packages/dependencies are out of date.
