### ISSUE TITLE
Bad glyph widths after transforming glyphs

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3888]
Transforming a glyph in FontForge 20190801 on macOS 10.14.5 can overflow and produce an unintended glyph width. I think `transform` should use saturating operations.

I ran this script:
```py
#!/usr/bin/env python3

import fontforge
import psMat

font = fontforge.font()
glyph1 = font.createChar(0x20)
glyph1.width = 0
glyph1.transform(psMat.translate(-1, 0))
glyph2 = font.createChar(0x21)
glyph2.width = 2 ** 16 - 1
glyph2.transform(psMat.translate(1, 0))
font.generate('bug.otf')
```
The narrow first glyph is now wide, and the wide second glyph is now narrow.
```console
$ ttx -q -t hmtx -o /dev/stdout bug.otf
WARNING: Glyph 'space' has a huge advance width (65535); is it intentional or an (invalid) negative value?
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="OTTO" ttLibVersion="3.44">

  <hmtx>
    <mtx name=".notdef" width="500" lsb="0"/>
    <mtx name="exclam" width="0" lsb="0"/>
    <mtx name="space" width="65535" lsb="0"/>
  </hmtx>

</ttFont>

```

**Comment by skef** [comment]
On the narrow diagnosis: When compiled normally all of FontForge's transformation arithmetic uses doubles, and otherwise it uses floats. (Compilation without double-precision has apparently been broken for a while.). So there's no real prospect or point of converting those operations to saturation arithmetic. 

The problem here is probably this part of `splinechar.c:SCSynchonizeWidth()`:
```
void SCSynchronizeWidth(SplineChar *sc,real newwidth, real oldwidth, FontViewBas
e *flagfv) {
    BDFFont *bdf;
    struct splinecharlist *dlist;
    RefChar *r = HasUseMyMetrics(sc,ly_fore);
    int isprobablybase;

    sc->widthset = true;
    if( r!=NULL ) {
        if ( oldwidth==r->sc->width ) {
            sc->width = r->sc->width;
return;
        }
        newwidth = r->sc->width;
    }
    if ( newwidth==oldwidth )
return;
    sc->width = newwidth;
```
`sc->width` is an `int16` and `newwidth` is (normally) a double. So direct assignment with implicit conversion is not the most elegant solution. This is easy enough to fix; the question is whether larger magnitude values warrant a warning. 

The same argument applies to `vwidth`, which unfortunately doesn't seem to have its own centralized setting function.

**Comment by skef** [comment]
Note: One problem is at tottf.c 2469:
```
        if ( SCWorthOutputting(sc) ) {
            if ( i<=at->gi.lasthwidth )
                putshort(at->gi.hmtx,sc->width);
```
The hmtx value is a uint16 while `sc->width` is an int16, which sets up a clash. Assuming `sc->width` is that way for a reason (other font formats supporting negative widths?) this should probably be
`putshort(at->gi.hmtx, sc->width<0 ? 0 : sc->width);`.

The max wrap-around seems less important and maybe not worth dealing with.

**Comment by ctrlcctrlv** [comment]
Other formats do support negative widths but TTF does not, George is correct.

**Comment by skef** [comment]
Slightly more analysis, for the record:

FontForge currently supports int16-valued character widths. That could change but it would require some work. One thing that could buy us is support for another 32K of TTF/OTF character width, whatever that's worth. 

Note that if, after the line `glyph2.width = 2 ** 16 - 1` in the description's script you add `print(glyph2.width)` the script prints "-1". This isn't an ideal situation but it's a general and common one (both "in the world" and in the various FontForge Python interfaces). Basically an unsupported value is being changed to a supported value by naive C-style casting. We could clean these up eventually, and therefore we could add it to our 900+ pile of issues now.

However, it seems as though that line was added by submitter as part of an overall theory of the problem that was a good guess (better than my own) but not exactly on the mark. Therefore I think it's reasonable to fix the inaccurate value problem with a zero-cutoff for TTF width and leave it at that. That means that both `exclam` and `space` as produced by the script will have zero width after the change.
