### ISSUE TITLE
Scripting: added contours to guide layer, but the contours are not actually added

### ISSUE THREAD

**Issue by RebBlumstein** [fontforge/fontforge#3889]
### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

Running Windows 10
Using FontForge 2019-08-01 release
Behavior Expected: two horizontal lines will be added to the guide layer for the specified font
Actual Behavior: horizontal lines are not created, and running the script a second time produces the same output (indicating that the contours were never really added).

Script is as follows:
import fontforge
import sys
font = fontforge.open("C:\\Data\\Tools\\My Programs\\Publishing\\Fonts\\Amerikai.sfd", 1)
em = font.em
a = font.ascent
d = font.descent
guide = font.guide
print("guide: %s" % len(guide))
capheight = 0.9\*d
xheight = 0.7\*d
capline = fontforge.contour()
capline.moveTo(-em, capheight)
capline.lineTo(em, capheight)
guide += capline
xline = fontforge.contour()
xline.moveTo(-em, xheight)
xline.lineTo(em, xheight)
guide += xline
print("capline: %s" % len(capline))
print("xline: %s" % len(xline))
print("guide: %s" % len(guide))
font.save()
font.close()

Script Output (even if run multiple times):
guide: 0
capline: 2
xline: 2
guide: 2

![Script Output](https://user-images.githubusercontent.com/32102773/63482989-83b68100-c4a3-11e9-922f-2a4eecbbbbf7.PNG)
![Guide Layer unchanged](https://user-images.githubusercontent.com/32102773/63483323-b2812700-c4a4-11e9-9885-bd318017c4d6.PNG)

**Comment by ctrlcctrlv** [comment]
You're not adding the contours to the glyph, it seems. I'm not home right now so can't test but I'm 90% sure that's the problem.

**Comment by skef** [comment]
I'm not going to verify this ATM, but the problem here is most likely that `font.guide` is a layer, and FontForge's layer-related interfaces are confusing. Even though layer objects like `font.guide` and `glyph.foreground` look like in-place objects, "getting" them makes a copy and updating them requires a "set".

If you add `font.guide = guide` after `guide += xline` it will probably start working.

**Comment by RebBlumstein** [comment]
font.guide = guide

solved the problem
Thanks!
