### ISSUE TITLE
Fix the documentation for installation on Ubuntu

### ISSUE THREAD

**Issue by MdAyquassar** [fontforge/fontforge#3890]
INSTALL-git.md says, as for now:

> To download all dependencies on Ubuntu, run:
> 
> sudo apt-get install packaging-dev pkg-config python-dev libpango1.0-dev libglib2.0-dev libxml2-dev giflib-dbg libjpeg-dev libtiff-dev libspiro-dev build-essential automake flex bison;
> 

But giflib-dbg is not present in ubuntu disco:

```
$ sudo apt-get install packaging-dev pkg-config python-dev libpango1.0-dev libglib2.0-dev libxml2-dev giflib-dbg libjpeg-dev libtiff-dev libspiro-dev build-essential automake flex bison
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket giflib-dbg kann nicht gefunden werden.
$ sudo aptitude search giflib-dbg
$ lsb_release -r
Release:        19.04
$
```

Without a proper installation procedure, I cannot even check whether the math-kern-related crashes from the ppa version have already been fixed in the repository...

**Comment by frank-trampe** [comment]
Unless you're debugging gif support, I'm sure that you can simply skip `giflib-dbg`.

**Comment by MdAyquassar** [comment]
Thank you. The next issue appears when I try to do

> Now run the build and installation scripts, and ensure you can open shared object files:
> 
> cd fontforge;
> ./bootstrap;
> ./configure;
> make;
> sudo make install;
> sudo ldconfig;

```
user@host:~/soft/fontforge/libuninameslist$ ..
user@host:~/soft/fontforge$ cd fontforge/
user@host:~/soft/fontforge/fontforge$ ./bootstrap
bash: ./bootstrap: Datei oder Verzeichnis nicht gefunden
user@host:~/soft/fontforge/fontforge$ 
```

There is no bootstrap:

```
$ find ../.. -iname \*bootstrap\*
$
```

**Comment by frank-trampe** [comment]
Ah, I guess we need to fix that too. For now, just run `autoreconf -if`.

**Comment by MdAyquassar** [comment]
```
$ autoreconf -if
autoreconf: 'configure.ac' or 'configure.in' is required
```

**Comment by frank-trampe** [comment]
Oh. I forgot. We merged the cmake changes.
```
mkdir build && pushd build && cmake $FFCONFIG .. && popd && make -C build -j4
```

**Comment by MdAyquassar** [comment]
```
$ mkdir build && pushd build && cmake $FFCONFIG .. && popd && make -C build -j4
~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GDK3: Found unsuitable version "", but required is at least
  "3.10" (found )
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/packages/FindGDK3.cmake:37 (find_package_handle_standard_args)
  CMakeLists.txt:99 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/malkis/soft/fontforge/fontforge/CMakeFiles/CMakeOutput.log".
See also "/home/malkis/soft/fontforge/fontforge/CMakeFiles/CMakeError.log".

```

**Comment by MdAyquassar** [comment]
```
$ mkdir build && pushd build && cmake $FFCONFIG .. && popd && make -C build -j4
~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GDK3: Found unsuitable version "", but required is at least
  "3.10" (found )
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/packages/FindGDK3.cmake:37 (find_package_handle_standard_args)
  CMakeLists.txt:99 (find_package)


-- Configuring incomplete, errors occurred!

```

**Comment by frank-trampe** [comment]
I would suggest installing the package "libgtk-3-dev".

**Comment by MdAyquassar** [comment]
Done. And after that `mkdir build && pushd build && cmake $FFCONFIG .. && popd && make -C build -j4`?

**Comment by frank-trampe** [comment]
"python3.7-dev".

**Comment by MdAyquassar** [comment]
Done. But then:
```
user@host:~/soft/fontforge/fontforge$ mkdir build && pushd build && cmake $FFCONFIG .. && popd && make -C build -j4
-- Build files have been written to: /home/user/soft/fontforge/fontforge
~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird betreten
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
```
The directory `build` is indeed empty.

**Comment by frank-trampe** [comment]
There's something odd going on. The `popd` command ought to return the working directory to the main FontForge directory. Not sure why that's not happening. No need to reinstall the other libraries. Not much has changed.

**Comment by MdAyquassar** [comment]
Hm, here are the different steps:

```
$ rm -rf build/
user@host:~/soft/fontforge/fontforge$ mkdir build
user@host:~/soft/fontforge/fontforge$ pushd build
~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge ~/soft/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
user@host:~/soft/fontforge/fontforge/build$ cmake $FFCONFIG ..
-- Could NOT find Readline (missing: Readline_INCLUDE_DIRS) 
-- Could NOT find WOFF2 (missing: WOFF2_LIBRARIES WOFF2_INCLUDE_DIRS) (found version "")
-- Build options: 
--   CMAKE_BUILD_TYPE = RelWithDebInfo
--   BUILD_SHARED_LIBS = ON
--   ENABLE_GUI = ON
--   ENABLE_X11 = OFF
--   ENABLE_NATIVE_SCRIPTING = ON
--   ENABLE_PYTHON_SCRIPTING = ON
--   ENABLE_PYTHON_EXTENSION = ON
--   ENABLE_LIBSPIRO = ON
--   ENABLE_LIBUNINAMESLIST = ON
--   ENABLE_LIBGIF = AUTO => ON
--   ENABLE_LIBJPEG = AUTO => ON
--   ENABLE_LIBPNG = AUTO => ON
--   ENABLE_LIBREADLINE = AUTO => OFF
--   ENABLE_LIBTIFF = AUTO => ON
--   ENABLE_WOFF2 = AUTO => OFF
--   ENABLE_CODE_COVERAGE = OFF
--   ENABLE_DEBUG = OFF
--   ENABLE_DEBUG_RAW_POINTS = OFF
--   ENABLE_FONTFORGE_EXTRAS = OFF
--   ENABLE_MAINTAINER_TOOLS = OFF
--   ENABLE_TILE_PATH = OFF
--   ENABLE_WRITE_PFM = OFF
--   ENABLE_FREETYPE_DEBUGGER = 
--   REAL_TYPE = double
--   THEME = tango
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/soft/fontforge/fontforge
user@host:~/soft/fontforge/fontforge/build$ popd
~/soft/fontforge/fontforge ~/soft/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
user@host:~/soft/fontforge/fontforge$ make -C build -j4
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird betreten
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird verlassen
user@host:~/soft/fontforge/fontforge$ ls -a
.              AUTHORS  cmake           cmake_install.cmake    contrib          CPackConfig.cmake        CTestTestfile.cmake    .dir-locals.el  fontforgeexe  .github     inc             LICENSE   Packaging  pyhook     share    travis-scripts
..             bin      CMakeCache.txt  CMakeLists.txt         CONTRIBUTING.md  CPackExtraDist.cmake     DartConfiguration.tcl  doc             gdraw         .gitignore  INSTALL-git.md  Makefile  po         README     Testing  .travis.yml
.appveyor.yml  build    CMakeFiles      cmake_uninstall.cmake  COPYING.gplv3    CPackSourceConfig.cmake  desktop                fontforge       .git          gutils      lib             osx       pycontrib  README.md  tests    Unicode
user@host:~/soft/fontforge/fontforge$ 
```

**Comment by frank-trampe** [comment]
Just to confirm (since it is redacted) you're running `cmake $FFCONFIG ..` out of the build directory and the build directory is empty after that step? Is `$FFCONFIG` blank (as I would expect in this case)?

**Comment by MdAyquassar** [comment]
user@host:~/soft/fontforge/fontforge$ rm -rf build && mkdir build && pushd build && echo "\$FFCONFIG=$FFCONFIG" && echo "pwd=`pwd`" && cmake $FFCONFIG .. && popd && make -C build -j4
~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
$FFCONFIG=
pwd=/home/user/soft/fontforge/fontforge/build
-- Could NOT find WOFF2 (missing: WOFF2_INCLUDE_DIRS) (found version "1.0.2")
-- Build options: 
--   CMAKE_BUILD_TYPE = RelWithDebInfo
--   BUILD_SHARED_LIBS = ON
--   ENABLE_GUI = ON
--   ENABLE_X11 = OFF
--   ENABLE_NATIVE_SCRIPTING = ON
--   ENABLE_PYTHON_SCRIPTING = ON
--   ENABLE_PYTHON_EXTENSION = ON
--   ENABLE_LIBSPIRO = ON
--   ENABLE_LIBUNINAMESLIST = ON
--   ENABLE_LIBGIF = AUTO => ON
--   ENABLE_LIBJPEG = AUTO => ON
--   ENABLE_LIBPNG = AUTO => ON
--   ENABLE_LIBREADLINE = AUTO => ON
--   ENABLE_LIBTIFF = AUTO => ON
--   ENABLE_WOFF2 = AUTO => OFF
--   ENABLE_CODE_COVERAGE = OFF
--   ENABLE_DEBUG = OFF
--   ENABLE_DEBUG_RAW_POINTS = OFF
--   ENABLE_FONTFORGE_EXTRAS = OFF
--   ENABLE_MAINTAINER_TOOLS = OFF
--   ENABLE_TILE_PATH = OFF
--   ENABLE_WRITE_PFM = OFF
--   ENABLE_FREETYPE_DEBUGGER = 
--   REAL_TYPE = double
--   THEME = tango
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/soft/fontforge/fontforge
~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird betreten
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird verlassen
user@host:~/soft/fontforge/fontforge$

**Comment by frank-trampe** [comment]
Oh. Here's what's happening. Previous failures have messed up your pushd/popd stack, so the files that are supposed to go into the build directory are going into the FontForge directory instead. Run `dirs -c` in order to clear the stack.

If it works properly, you'll see the following in your output.
`-- Build files have been written to: /var/tmp/ff10/fontforge/build`

**Comment by MdAyquassar** [comment]
Not quite:
```
user@host:~/soft/fontforge/fontforge$ dir -c && rm -rf build && mkdir build && pushd build && echo "\$FFCONFIG=$FFCONFIG" && echo "pwd=`pwd`" && cmake $FFCONFIG .. && ls -a && popd && make -C build -j4
CMakeFiles  share    doc    contrib    pyhook        gdraw      gutils   inc       CPackSourceConfig.cmake  CPackExtraDist.cmake   DartConfiguration.tcl  CMakeCache.txt  lib                  CTestTestfile.cmake  travis-scripts  cmake      README     AUTHORS         CONTRIBUTING.md  INSTALL-git.md
po          desktop  tests  pycontrib  fontforgeexe  fontforge  Unicode  Makefile  CPackConfig.cmake        cmake_uninstall.cmake  build                  bin             cmake_install.cmake  Testing              osx             Packaging  README.md  CMakeLists.txt  COPYING.gplv3    LICENSE
~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
$FFCONFIG=
pwd=/home/user/soft/fontforge/fontforge/build
-- Could NOT find WOFF2 (missing: WOFF2_INCLUDE_DIRS) (found version "1.0.2")
-- Build options: 
--   CMAKE_BUILD_TYPE = RelWithDebInfo
--   BUILD_SHARED_LIBS = ON
--   ENABLE_GUI = ON
--   ENABLE_X11 = OFF
--   ENABLE_NATIVE_SCRIPTING = ON
--   ENABLE_PYTHON_SCRIPTING = ON
--   ENABLE_PYTHON_EXTENSION = ON
--   ENABLE_LIBSPIRO = ON
--   ENABLE_LIBUNINAMESLIST = ON
--   ENABLE_LIBGIF = AUTO => ON
--   ENABLE_LIBJPEG = AUTO => ON
--   ENABLE_LIBPNG = AUTO => ON
--   ENABLE_LIBREADLINE = AUTO => ON
--   ENABLE_LIBTIFF = AUTO => ON
--   ENABLE_WOFF2 = AUTO => OFF
--   ENABLE_CODE_COVERAGE = OFF
--   ENABLE_DEBUG = OFF
--   ENABLE_DEBUG_RAW_POINTS = OFF
--   ENABLE_FONTFORGE_EXTRAS = OFF
--   ENABLE_MAINTAINER_TOOLS = OFF
--   ENABLE_TILE_PATH = OFF
--   ENABLE_WRITE_PFM = OFF
--   ENABLE_FREETYPE_DEBUGGER = 
--   REAL_TYPE = double
--   THEME = tango
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/soft/fontforge/fontforge
.  ..
~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge ~/soft/fontforge/fontforge/build ~/soft/fontforge/fontforge
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird betreten
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
make: Verzeichnis „/home/user/soft/fontforge/fontforge/build“ wird verlassen
user@host:~/soft/fontforge/fontforge$ 
```

**Comment by frank-trampe** [comment]
`dirs -c`, not `dir -c`.

**Comment by MdAyquassar** [comment]
Already found my mistake, but the result is the same (updated above).

**Comment by frank-trampe** [comment]
I'm stumped.

@jtanx, take a look at this when you get a chance. Per the posted output, the working directory is the build directory, and yet cmake is putting its files in the fontforge directory.

**Comment by frank-trampe** [comment]
Oh, wait. I think I know what might be happening. Try a git clean to clear out the cmake files in the top directory.

**Comment by MdAyquassar** [comment]
Git refuses to do so:
```
$ git clean
fatal: clean.requireForce standardmäßig auf "true" gesetzt und weder -i, -n noch -f gegeben; "clean" verweigert
user@host:~/soft/fontforge/fontforge$ ..
user@host:~/soft/fontforge$ git clean
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
user@host:~/soft/fontforge$ 
```
After all the mess, I think it is better if you could simply rebuild the ubuntu package on your side and put it into the ppa.

**Comment by frank-trampe** [comment]
Force clean via `git clean -fdx` (assuming that you don't have any modifications that you want to save).

**Comment by MdAyquassar** [comment]
Worked great, thx! Compilation done and the executable even works:
```
$ ./build/bin/fontforge ../../Ryge/TeXRygeTermesMath-Regular.otf &
[4] 30414
user@host:~/soft/fontforge/fontforge$ Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 2019-08-22 18:02 UTC-ML-D-GDK3.
 Based on source from git with hash: 07f502f59995b0f64c10d21379096a2a47bd40f1
Failed to open resource file: /home/user/soft/fontforge/fontforge/build/share/fontforge/pixmaps/resources

[4]+  Fertig                  ./build/bin/fontforge ../../Ryge/TeXRygeTermesMath-Regular.otf
user@host:~/soft/fontforge/fontforge$ 
```
I'll test the executable next time. The installation issues are solved for me. (But you might wish to update the installation instructions anyway.)

Thx again!

**Comment by frank-trampe** [comment]
Okay. Sorry this was so difficult. We do have documentation in progress for the new build process and expect to publish it prior to the next release.

**Comment by MdAyquassar** [comment]
Thank you for making it easy to me! Do I need the resource files to change the math kerning of existing fonts or are the resources just a gimmick?

**Comment by jtanx** [comment]
Updated documentation is already on https://github.com/fontforge/fontforge/pull/3879 and https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge

You're not meant to run directly from build/bin/fontforge unless you're just debugging stuff, otherwise you should run `make install`.

**Comment by jtanx** [comment]
To expand, the complaint about missing resources files when you directly run from build/bin/fontforge is because the theme information isn't copied into the build folder. It still functions just fine, but it will apply the 'default' theme.

**Comment by MdAyquassar** [comment]
Thank you. Could you update the procedure described in INSTALL-git.md, too? Moreover, I would wish to install fontforge locally, specifying `--prefix=$HOME/usr/local` (or similar) at an appropriate place before doing `make install`. But, above, I don't think I ever had a chance to run `./configure`.

**Comment by jtanx** [comment]
As I mentioned, that's all documented on https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge

Please read it. You don't do `./configure` any more, that's all controlled by cmake. You'd need something like `cmake .. -DCMAKE_INSTALL_PREFIX=/blah`.

**Comment by MdAyquassar** [comment]
@jtnax I took a look at it. Should I then simply forget the old, non-cmake way of installation?

**Comment by jtanx** [comment]
Yes, forget that completely.
