### ISSUE TITLE
Build failure on Linux Mint 19.2

### ISSUE THREAD

**Issue by ashinpan** [fontforge/fontforge#3897]
I tried to build the latest trunk on linux mint 19.2.  Cmake was successful but ninja build failed with the following message:

--------------------------------------

/usr/bin/ld: /usr/local/lib/libpython3.7m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_PyRuntime' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
[183/312] Building C object gdraw/CMakeFiles/gdraw.dir/ggdkdraw.c.o
ninja: build stopped: subcommand failed.

**Comment by jtanx** [comment]
Looks like you're trying to statically link to python, which wasn't compiled with fPIC. What flags, if any did you pass to cmake?

**Comment by jtanx** [comment]
It also looks like you have `libpython3.7` in /usr/local, did you compile this yourself? If so, you either should be linking to python as a shared library, or you should enable fPIC when compiling it.

**Comment by ashinpan** [comment]
Yeah, I don't even remember when I installed python3.7 or how. I just
removed it, and the build process is OK now. Thanks a lot for noticing it.

cheers,
