### ISSUE TITLE
Using python script to change  'OS/2 -> Panose -> Proportion' to  Monospaced.

### ISSUE THREAD

**Issue by hongyi-zhao** [fontforge/fontforge#3904]
Hi,

I read the talk here:

https://stackoverflow.com/questions/10290912/how-do-i-get-gnu-unifont-or-free-mono-working-on-gvim-windows

Which told the following:

------------
    start fontforge and open the unifont.ttf font. On Debian this is installed at

    /usr/share/fonts/truetype/unifont/unifont.ttf

    go to Element -> Font Info...
        under PS Names change Fontname, Family Name and Name for Humans, for example into UnifontMono.
        under OS/2 -> Panose change Proportion to Monospaced.
    click Save. In the popup select Change.
    File -> Generate Fonts.... Select TrueType in the left requester, select No Bitmap Fonts, disable Validate Before Saving.
    Save
------------

I want to do the above thing with a python script, how to write the corresponding commands in python?

Regards

**Comment by ctrlcctrlv** [comment]
Hello

This is not a forum, it's an issue tracker. Please email the mailing list `fontforge-users@lists.sourceforge.net` for questions, and use this issue tracker if (a) you think something is missing from the Python interface or (b) you have some other reproducible bug.
