### ISSUE TITLE
OSX - Crashes immediately on startup

### ISSUE THREAD

**Issue by noahbromberg** [fontforge/fontforge#3940]
Issue: When attempting to open FontForge, it appears to open for a split second, and then immediately closes. No window or error message actually appears, only the icon shows up in the Dock.
FontForge Version: 2019-08-01
OS: macOS Sierra 10.12.6

**Comment by ctrlcctrlv** [comment]
What happens if you run it in the console
Is there any debugging output available to us from Apple's Crash Reporter

**Comment by noahbromberg** [comment]
No messages are logged in the console, and no crash dialog box opens. The application simply opens and closes.

**Comment by jtanx** [comment]
@noahbromberg what fixed it for you?
