### ISSUE TITLE
MSWindows runtime failure "GetFileInformationByHandle"

### ISSUE THREAD

**Issue by gwgill** [fontforge/fontforge#3957]
Installed FontForge-2019-08-01-Windows.exe successfully.

Running run_fontforge.exe results in the following error:
"The procedure entry point GetFileInformationByHandleEx" could not be located in the dynamic link library KERNEL32.dll"

A previously installed older version of FontForge (2015-02-28) ran OK.

**Comment by skef** [comment]
What version of Wndows are you using?

**Comment by jtanx** [comment]
Windows XP is no longer supported.
