### ISSUE TITLE
cmake error on Debian Stretch

### ISSUE THREAD

**Issue by aimnadze** [fontforge/fontforge#3960]
Hi, I'm trying to build FontForge on Debian Stretch. I'm following the "CMake guide for FontForge" wiki page. But the command `cmake -GNinja ..` leads to the following output:

```
CMake Error at CMakeLists.txt:268 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "fontforge".
```

I'm neither a cmake expert nor an expert of any kind of compiling. But I think the wiki doesn't cover the building process well. Can anybody elaborate on the steps to build? Any help will be appreciated. Thanks in advance!

**Comment by skef** [comment]
Could you run `cmake --version` and copy the output here?

**Comment by skef** [comment]
Actually, here's an attempt at a work around. Try removing `CMakeCache.txt` (or deleting and re-`mkdir`ing `build`) and doing:
```
cmake -GNinja -DASSIMP_LIB_INSTALL_DIR=lib ..
```

**Comment by jtanx** [comment]
Sounds like you're trying to build statically, in which case I can spot a probable issue. Is `cmake -GNinja ..` really all you passed into cmake?

**Comment by aimnadze** [comment]
@skef The output of `cmake --version` is:

```
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

@jtanx I run only `cmake -GNinja ..`. Before I run the command I clean up the build folder. But the result is the same. Below is the full output if it may help:

```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:268 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "fontforge".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/user/sites/fontforge/fontforge/fontforge/build/CMakeFiles/CMakeOutput.log".
```

**Comment by aimnadze** [comment]
`-DASSIMP_LIB_INSTALL_DIR=lib` doesn't seem to change the result.

**Comment by jtanx** [comment]
You're running cmake one level too deep in the folder structure. You're inside the fontforge folder within this repo, but you should be creating that build folder one level higher.

**Comment by jtanx** [comment]
i.e. you should have `/home/user/sites/fontforge/fontforge/build` and not `/home/user/sites/fontforge/fontforge/fontforge/build`

**Comment by aimnadze** [comment]
That was the issue. Multiple `fontforge` folders might have screwed my mind. Thanks @jtanx
