### ISSUE TITLE
UFO import not handling note key correctly

### ISSUE THREAD

**Issue by eduardomourar** [fontforge/fontforge#3964]
The import UFO functionality should have the same behavior as the export regarding the mapping of fields. So the SFD field `Comment` is mapped to the UFO note `key` in the `dict` tag during the export, but not during import.

### FontForge version
Version: 20190801
OS: MacOS 10.14.6

### Expected behavior

If I import of UFO v2 file such as this one [here](https://github.com/eduardomourar/fiati/blob/763db1d11aa6fc0738b150fe6cf373785f43d2fd/sources/fiati-regular/fiati-regular.ufo/glyphs/uniE_C_43.glif#L34), I would expect the SFD file result to contain a `Comment` with the note value.

```
Comment: "fingeringFluteLHThumbBFlatClosed"
```

### Actual Behavior
But instead the note gets translated into a `PickledDataWithLists` for the glyph shown [here](https://github.com/eduardomourar/fiati/blob/763db1d11aa6fc0738b150fe6cf373785f43d2fd/sources/fiati-regular/fiati-regular.sfd#L1445).

```
PickledDataWithLists: "(dp0
Vnote
p1
VfingeringFluteLHThumbBFlatClosed
p2
s."
```

### Workaround

Modify SFD file after import by replacing the string from PickledDataWithLists to Comment.

**Comment by ctrlcctrlv** [comment]
Why would you expect that? FontForge imports it as a dictionary, which is what it is. If we do it your way we can only support `dict`s with one key, and we would throw out the key's name.

**Comment by skef** [comment]
The OP's description doesn't endorse mapping *any* `dict` value to the `Comment`. I read it as asking to special-case the `note` key.  

And the concern is certainly legitimate -- FontForge can't quite "Save" as UFO, exactly, but until it can data should still round-trip as much as possible.

**Comment by eduardomourar** [comment]
@ctrlcctrlv , just like skef mentioned, I am asking only for the `note` key to be mapped to `Comment`. I do agree that you need to import `dict` as a dictionary. Then to keep it consistent, FontForge should import/export the `note` both to/from the `PickledDataWithLists` and to `Comment`, where the latter should have priority.
