### ISSUE TITLE
Undo/redo action does not autorepeat

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#3968]
hi
in new fontforge (after 2017) it's not possible to undo/redo more than once(i mean over and over by a delay) while holding shortcut keys on windows. this is a necessary feature specially when we work on a glyph for a long time.
thank you.

**Comment by jtanx** [comment]
Can you please list out some exact steps that exhibit this. Screenshots and/or a screen recording also helps.

**Comment by aminabedi68** [comment]
i thought it's clear enough, i try to explain in more detail.
for example when we proceed several steps like transformations, direction changing, adding/deleting points/segments on a glyph we can go back/forward through all undo(s)/redo(s) by shortcut keys(ctrl+z/y), so the problem is that undo(s)/redo(s) are continuously happened by a delay when we holding shortcut keys in x11 fontforges but in new versions it just happens once for each time and when we work for a while and need to back for example 24th undo, we have to push 24 time on ctrl+z

**Comment by frank-trampe** [comment]
Allowing expensive and possibly lagging operations to run on a continuous basis can be dangerous (as in queuing up hundreds of operations in the time it takes to execute one of them) unless handled as a single request at each inter-operation interval with the key depressed. Did this work well before?

**Comment by aminabedi68** [comment]
number of undo steps is the limitation and it works perfect before.(If i`m not mistaken this number is a variable integer value in fontforge settings)

**Comment by jtanx** [comment]
Ok, I see what's going on here, this was basically an inadvertent feature (or bug, depending on how you look at it). 

Under gxdraw, only key up events are marked as autorepeat, so you get a sequence of <keydown:autorepeat=false>, <keyup:autorepeat=true> events.

Under ggdkdraw, both the key down and key up events are marked as autorepeat. 

Hotkey actions only fire on the key down event. At the same time, there's explicit code to ignore auto repeats:

https://github.com/fontforge/fontforge/blob/5112b8f3181424fd7b2b02fbbf4ce30acc2b4a77/gdraw/hotkeys.c#L133-L134

So under gxdraw -> that does nothing,under ggdkdraw, that filters out autorepeats.

**Comment by yg8ijvjvjv** [comment]
"Allowing expensive and possibly lagging operations to run on a continuous basis can be dangerous (as in queuing up hundreds of operations in the time it takes to execute one of them) unless handled as a single request at each inter-operation interval with the key depressed. Did this work well before?"

Try using a frame approach instead of a queue approach, advance a frame every 1÷60 of a second (60fps FontForge), put any operation in a single frame and each frame take input and check if it changed over the previous frame (if so, count that as a press or release).
