### ISSUE TITLE
Crash when exploring glyphs

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#3970]
hello
Crash occurs on windows OS  when exploring glyphs with glyph editing windows and shortcut keys (   shift+[    and    Shift+]   )
thank you.

**Comment by jtanx** [comment]
I can't reproduce this, are you able to list out the sequence of steps you're taking/post screenshots/a screencap?

**Comment by aminabedi68** [comment]
it happened several times a few days ago and today when i testing to record, works fine, I'm not sure maybe there is some special conditions or depend on system configurations cause that so i close this issue until i see that again. thank you.
