### ISSUE TITLE
Crash when labeling glyphs whose names include “.vert”

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#3973]
FontForge 20190801 crashes on macOS 10.14.6 after following these steps:

1. Download [NotoKufiArabic-Regular.otf](https://github.com/googlefonts/noto-fonts/blob/e87ac4b84ac38f7cff7fd6d87918d45785c0e9ea/phaseIII_only/unhinted/otf/NotoKufiArabic/NotoKufiArabic-Regular.otf).
2. Open it in FontForge.
3. Go to glyph `twodots.vert_alt1.below`.

[Here is the crash report.](https://github.com/fontforge/fontforge/files/3721319/fontforge_2019-10-12-205208.txt)

**Comment by jtanx** [comment]
I'll say this is a pango bug. It's reaching [this block](https://gitlab.gnome.org/GNOME/pango/blob/master/pango/pangocoretext-fontmap.c#L1338) which says it 'should always work' but clearly doesn't...

**Comment by dscorbett** [comment]
A workaround is to go to View › Label Glyph By and select anything other than Glyph Image.

**Comment by dscorbett** [comment]
Another workaround is to replace `.vert` in all glyph names with `.vvrt`. The problem is therefore caused by:
https://github.com/fontforge/fontforge/blob/ac635b818e38ddb8e7e2e1057330a32b4e25476e/fontforgeexe/fontview.c#L5897-L5898

**Comment by ctrlcctrlv** [comment]
Interesting&mdash;I've also noted strange behavior with FontForge's &ldquo;flipping&rdquo; of glyphs that are marked `.vert`.

**Comment by dscorbett** [comment]
The code for the italic style checks whether `buf[0]!='?'` but the code for the vertical case doesn’t. Could that be the cause of the crash? The original code did check for `'?'`:
https://github.com/fontforge/fontforge/blob/433b8b7c82171663d3a0a3e0b39b8366b10ef2f5/pfaedit/fontview.c#L3098-L3099

**Comment by jtanx** [comment]
No, it's not the cause. As I said, it's in pango, or how we use pango:
https://github.com/fontforge/fontforge/blob/5112b8f3181424fd7b2b02fbbf4ce30acc2b4a77/gdraw/ggdkcdraw.c#L194

That screws up the core text font map, preventing it from matching any font, which then causes Pango to abort. afaik you're meant to set the gravity on the context instead, which seems to work. Perhaps an issue on our side, but on the same hand it's kind of bad that you can do that to cause pango to crash. On Windows, either method fails, but at least it doesn't abort, it just spews a bunch of pango warnings.

Having said all that, I don't really understand where/how this is used in practice. I did find this [test font](https://github.com/fontforge/fontforge/blob/master/tests/fonts/VKern.sfd) by GWW, and that's about it.

**Comment by khaledhosny** [comment]
The Pango bug might be fixed with https://gitlab.gnome.org/GNOME/pango/merge_requests/150

**Comment by dscorbett** [comment]
With FontForge 20200314 and Pango 1.46.1, this no longer crashes.
