### ISSUE TITLE
Move all characters down

### ISSUE THREAD

**Issue by pavelkux** [fontforge/fontforge#3976]
I am really sorry that I am writing this here, but I didnt find any other ways to ask. Once I get the answer I will delete this post entirely.

I was playing around for hours with FontForge and I couldn't make running one simple thing - I want to moveall the letters of my font a bit more down (on vertical axis). I was trying to change in in the glyph editor, by transformations, etc. but it didnt really help. It was always the same.

Is there any way (ideally simple) how to change it? I was also looking for a way to set the baseline but I also didnt find anything. 
Thank you!

**Comment by frank-trampe** [comment]
That ought to work. Send a screen-shot of the options that you used.

**Comment by frank-trampe** [comment]
Oh. There could be a lot of factors in play. Try running the before and after TrueType files through ttx (from fonttools), diffing the results, and identifying which non-shape values change.

**Comment by pavelkux** [comment]
Hello again,
I am not sure I understand now. What will I achieve if I compare the new ttf with the old one? None of these bring the result I need?
Don't you have any particular tips what should I try in the FontForge to achieve that?

**Comment by frank-trampe** [comment]
Indeed. ttx doesn't solve anything. The point is to figure out which values are changing that ought not to be changing.

**Comment by pavelkux** [comment]
I understand. As far as I understand the fonttools is a separate package and not part of fontforge, correct? I can see in menu item "Tools" but it is grayed out.
I tried to download the fonttools package, but I am not really familiar with Python:-/

**Comment by pavelkux** [comment]
I am just trying different things with the tool and for whatever reason, if I change the position in the glyph editor, it is correctly displayed once exported.
So the question is - is there a way how to shift all the letters at once like I did in the glyph editor?

**Comment by frank-trampe** [comment]
I think that that means "changed since last hinted," but I'm actually not sure. Here's a test that might be useful. Select a range of glyphs, transform those in bulk. Transform another glyph from inside the char view. Then select "Changed Glyphs" (from the "Select" submenu of the "Edit" menu) and see what gets selected.

**Comment by skef** [comment]
The fourth-through-sixth paragraphs of https://fontforge.github.io/fontview.html are the (aging) documentation on the bars. The dark blue indicates that the glyph has been changed (that it has at least one "undo" record).

**Comment by pavelkux** [comment]
@frank-trampe, I tried it and it selects all the glyphs I touched (whichever method I used), but the highlight is different (as per my previous description).
@skef thank you for the post. So basically we know that those glyphs have been changed (by transformation) but it "hasn't been changed since it was last hinted" (as per the description) because it doesnt show those lightblue edges.

The transformation does exactly what I need and it can do it in a batch. The problem is that it seems that it is not persistant or it also changes another value (like bottomline) so the outcome is the same.

**Comment by skef** [comment]
Could you:

1. Open the font in FontForge
2. Immediately "save" it (as an "sfd")
3. Select the relevant characters and perform the bulk transform as in your numbered comment
4. Save it again as a different sfd
5. Run "sfddiff" (which should be part of the fontforge distribution) on both files to see what, if any, differences it reports. 

I'm also curious to know what happens when you open the file saved in number 4 again and try to generate a ttf from it. The generated font should be the same but we don't know what's happening yet so why not check ...

**Comment by pavelkux** [comment]
I dont see sfddiff in the fontForge but I ran another file comparison tool. Since it is not a binary format, I can paste here the results.

**Comment by pavelkux** [comment]
this is the original std
`StartChar: e
Encoding: 101 101 72
Width: 430
GlyphClass: 2
Flags: W
TtInstrs:
NPUSHB
 65
 0
 4
 7
 3
 7
 4
 3
 109
 8
 2
 2
 0
 9
 1
 7
 4
 0
 7
 96
 0
 1
 1
 6
 88
 0
 6
 6
 101
 72
 0
 3
 3
 5
 88
 0
 5
 5
 102
 5
 73
 11
 11
 0
 0
 11
 42
 11
 40
 35
 33
 29
 27
 20
 19
 17
 15
 0
 10
 0
 10
 35
 33
 10
 9
 22
CALL
EndTTInstrs
LayerCount: 2
Fore
SplineSet
116 285 m 2,0,1
 116 285 116 285 279 285 c 0,2,3
 302 285 302 285 302 308 c 0,4,5
 302 338 302 338 281 370 c 128,-1,6
 260 402 260 402 220 402 c 0,7,8
 183 402 183 402 157 373 c 128,-1,9
 131 344 131 344 122 314.5 c 128,-1,10
 113 285 113 285 116 285 c 2,0,1
111 248 m 1,11,12
 111 244 111 244 111 241 c 0,13,14
 111 153 111 153 158 104.5 c 128,-1,15
 205 56 205 56 274 56 c 0,16,17
 310 56 310 56 339 73.5 c 128,-1,18
 368 91 368 91 384 109 c 0,19,20
 385 109 385 109 386.5 107.5 c 128,-1,21
 388 106 388 106 390 102.5 c 128,-1,22
 392 99 392 99 392 95 c 0,23,24
 392 87 392 87 386 77 c 0,25,26
 367 46 367 46 329.5 19 c 128,-1,27
 292 -8 292 -8 240 -8 c 0,28,29
 152 -8 152 -8 96 51.5 c 128,-1,30
 40 111 40 111 40 200 c 0,31,32
 40 296 40 296 103.5 367 c 128,-1,33
 167 438 167 438 237 438 c 0,34,35
 279 438 279 438 310.5 423 c 128,-1,36
 342 408 342 408 357.5 384.5 c 128,-1,37
 373 361 373 361 380 340.5 c 128,-1,38
 387 320 387 320 387 302 c 0,39,40
 387 256 387 256 363 255 c 0,41,42
 254 248 254 248 111 248 c 1,11,12
EndSplineSet
Substitution2: "'smcp' Lowercase to Small Capitals lookup 1 subtable" e.sc
EndChar`

**Comment by pavelkux** [comment]
This is the new file
StartChar: e
Encoding: 101 101 72
Width: 430
VWidth: 943
GlyphClass: 2
Flags: W
TtInstrs:
NPUSHB
 65
 0
 4
 7
 3
 7
 4
 3
 109
 8
 2
 2
 0
 9
 1
 7
 4
 0
 7
 96
 0
 1
 1
 6
 88
 0
 6
 6
 101
 72
 0
 3
 3
 5
 88
 0
 5
 5
 102
 5
 73
 11
 11
 0
 0
 11
 42
 11
 40
 35
 33
 29
 27
 20
 19
 17
 15
 0
 10
 0
 10
 35
 33
 10
 9
 22
CALL
EndTTInstrs
LayerCount: 2
Fore
SplineSet
116 204 m 2,0,1
 116 204 116 204 279 204 c 0,2,3
 302 204 302 204 302 227 c 0,4,5
 302 257 302 257 281 289 c 128,-1,6
 260 321 260 321 220 321 c 0,7,8
 183 321 183 321 157 292 c 128,-1,9
 131 263 131 263 122 233.5 c 128,-1,10
 113 204 113 204 116 204 c 2,0,1
111 167 m 1,11,12
 111 163 111 163 111 160 c 0,13,14
 111 72 111 72 158 23.5 c 128,-1,15
 205 -25 205 -25 274 -25 c 0,16,17
 310 -25 310 -25 339 -7.5 c 128,-1,18
 368 10 368 10 384 28 c 0,19,20
 385 28 385 28 386.5 26.5 c 128,-1,21
 388 25 388 25 390 21.5 c 128,-1,22
 392 18 392 18 392 14 c 0,23,24
 392 6 392 6 386 -4 c 0,25,26
 367 -35 367 -35 329.5 -62 c 128,-1,27
 292 -89 292 -89 240 -89 c 0,28,29
 152 -89 152 -89 96 -29.5 c 128,-1,30
 40 30 40 30 40 119 c 0,31,32
 40 215 40 215 103.5 286 c 128,-1,33
 167 357 167 357 237 357 c 0,34,35
 279 357 279 357 310.5 342 c 128,-1,36
 342 327 342 327 357.5 303.5 c 128,-1,37
 373 280 373 280 380 259.5 c 128,-1,38
 387 239 387 239 387 221 c 0,39,40
 387 175 387 175 363 174 c 0,41,42
 254 167 254 167 111 167 c 1,11,12
EndSplineSet
Substitution2: "'smcp' Lowercase to Small Capitals lookup 1 subtable" e.sc
EndChar

**Comment by pavelkux** [comment]
in short, vWidth was added (it was not initially there) and numbers in SplineSet were changed

**Comment by skef** [comment]
That's just one character. Did you do the bulk transform on only that one character?

**Comment by pavelkux** [comment]
> That's just one character. Did you do the bulk transform on only that one character?
Yes. I applied that element->transformation->transform on letter e.
Let me also paste the result of moving the glyph in glyph editor

**Comment by skef** [comment]
This doesn't *seem* right, but I wonder if the TTF hinting is "coercing" the outlines back up to their original positions. 

Try this first: Do what you've been doing to generate the TTF file, except right before select all the relevant characters in the font view and do Hints -> Clear Hints. Then generate and test to see if you still see the problem. (We can worry about hints later.)

**Comment by pavelkux** [comment]
@skef I transformed all the glyphs, cleared hints right after it and generated new font.
It is the same.

**Comment by skef** [comment]
When you open the ttf you generate in Fontforge, and compare an individual character with the same one that you transformed (you don't even need to save, just generate and open what you generated so you have both open at the same time), is the one in the generated file moved down or not?

**Comment by pavelkux** [comment]
It is moved down in Fontforge (in the font preview). It is not moved down in any applications where the font is used.

**Comment by skef** [comment]
When there are no hints, and one character has been moved but not others, there's little else to determine the vertical position of that character. So at this point we should shift from debugging the transform to verifying your test methods. 

To do that, do the transform you've been doing and then before generating go to Element -> Font Info and change the PS names and the TTF names to something consistent but different. Then generate a ttf with an appropriate new filename and test it *via* the new name.

**Comment by pavelkux** [comment]
I wanted to thank you both for your help. I decided to solve the problem other way because I didn't have more time to dig into this issue. 
I really appreciate that you wanted to help me, so once again, thank you!

I am not sure if it makes sense to close this issue or not, but probably yes?

**Comment by SynTexDZN** [comment]
I also got this problem and didn't found any Solution to solve this. The preview works well but the font isn't shown correctly on my webpages. When switching between the original font and my edit some special characters change to the wanted y-axis Bit the letters are staying the same. Is there any workaround?

**~ SynTex**

**Comment by skef** [comment]
Could you post a simplified example file for us to try out as we try to identify the problem?

**Comment by SynTexDZN** [comment]
I managed to fix it. I had to disable a checkbox when exporting the font that applies auto alignment. Also I had to change the ID of the font and everything worked fine for me. If anyone has still this problem I could be more presize how i solved it.

~ **SynTex**

**Comment by agun888** [comment]
> I managed to fix it. I had to disable a checkbox when exporting the font that applies auto alignment. Also I had to change the ID of the font and everything worked fine for me. If anyone has still this problem I could be more presize how i solved it.
> 
> ~ **SynTex**

Hi syntex. Yes I still have that allignment problem when using poppins regular in my samsung phone. 

Can you be more presize how to move down all characters? Or move down baseline

**Comment by agun888** [comment]
![Screenshot_20210714-150712_One UI Home](https://user-images.githubusercontent.com/87416366/125588498-c033b0bd-6988-4899-875a-d66de00af13e.jpg)

This is my problem with poppins regular on my samsung phone.

**Comment by yenmoc** [comment]
i think you tried setting y to be too small to see the change here i left y as -100 and the characters moved down
