### ISSUE TITLE
link to license broken in windows

### ISSUE THREAD

**Issue by peterennis** [fontforge/fontforge#3978]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

Windows 10
The link should work
Download the current Windows version

![2019-10-16 20_46_31-Window](https://user-images.githubusercontent.com/140737/67021231-337b2a00-f0b4-11e9-9ad9-a941dea4b9e2.png)

**Comment by frank-trampe** [comment]
This is a DNS issue. We are looking into it.
