### ISSUE TITLE
Window controls on macOS behave weirdly

### ISSUE THREAD

**Issue by khaledhosny** [fontforge/fontforge#3980]
On macOS, if a window overlaps another FontForge window, clicking on the window close button often will be caught by the lower window and click on whatever part it is under the button. I have to move the window away to be able to close it.

**Comment by khaledhosny** [comment]
https://a.uguu.se/UWcs0dYbA3Tq.mov

**Comment by jtanx** [comment]
Ah, interesting, it looks like this is a regression from e4d5cf717

**Comment by jtanx** [comment]
Actually I take that back, that's not it. Hmmmm

**Comment by jtanx** [comment]
I'm calling this one a GTK bug. You can repro the same thing with this:


```c
#include <gtk/gtk.h>

int main(int argc, char* argv[])
{
	gtk_init(&argc, &argv);

	GtkWidget* window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title(GTK_WINDOW(window), "MAIN");
	gtk_widget_show(window);

	GtkWidget* window2 = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title(GTK_WINDOW(window2), "SECOND");
	gtk_widget_show(window2);

	gtk_main();

	return 0;
}
```

**Comment by khaledhosny** [comment]
A GTK issue indeed, I can reproduce it in other GTK applications.
