### ISSUE TITLE
Difficulty typing negative numbers in kerning field

### ISSUE THREAD

**Issue by aimnadze** [fontforge/fontforge#3983]
Hi,

It is difficult to type a negative number in kerning field. Any invalid value is cleared after it is typed. Thus the leading minus sign is cleared immediately after typing.

Steps to reproduce:
* Open FontForge
* Open a font with a kerning lookup table
* Open Metrics Window
* Type two characters
* Try typing a negative number between the these two characters

Actual result:
* The negative number should be completely as you type

Expected result:
* When you first press the minus sign it is ignored
* The rest of the number is written

Possible workaround:
* Type the positive part of the number
* Move the cursor at the beginning of the number
* Type the minus sign

**Comment by ctrlcctrlv** [comment]
@aimnadze Would you mind trying out my patch (#4116) and giving me your thoughts on my general theory?

If/when it goes through, the docs will read:

```
 Underneath the display area are a set of text fields. You may type in new numbers for any of these fields to change the corresponding metrics of the glyph. If you wish to type a negative number, it is best to type the positive portion first, then an ASCII minus (`-`). So, to type, -300, type 300, then press -. 
```

**Comment by ctrlcctrlv** [comment]
Closing as no reply and I think my solution, recently merged, is sufficient.
