### ISSUE TITLE
Cygwin docs / wiki outdated?

### ISSUE THREAD

**Issue by hyvyys** [fontforge/fontforge#3994]
I'm trying to build ff on cygwin, so I followed [this wiki page](https://github.com/fontforge/fontforge/wiki/Building-with-Cygwin). I am having doubts about these commands:

```bash
./bootstrap   >do_bootstrap.01 2>&1
./configure --prefix="$HOME/local" >do_conf.01 2>&1
make          >do_make.01     2>&1
make install  >do_install.01  2>&1
```

There are no files named `bootstrap` or `configure` in the root of the repo, and no make rules are detected.

do_bootstrap.01:

```
-bash: ./bootstrap: No such file or directory
```

do_conf.01:

```
-bash: ./configure: No such file or directory
```

do_install.01:

```
make: *** Brak reguł do wykonania obiektu 'install'. Stop.
```

(No rules for execution 'install object'. Stop)

do_make.01:

```
make: *** Nie podano obiektów i nie znaleziono makefile. Stop.
```

(No objects were given and no makefile was found. Stop)

**Comment by frank-trampe** [comment]
Oh. It is probably quite outdated. I'm not sure when the last time we tested anything on Cygwin was. I would suggest trying the standard cmake steps for now.

**Comment by jtanx** [comment]
Yeah, just follow the standard cmake steps. Although ymmv, I don't compile on Cygwin, I use msys2 /mingw-w64 instead.

**Comment by skef** [comment]
I edited the top of the page to point to the CMake instructions.
