### ISSUE TITLE
select unicode characters

### ISSUE THREAD

**Issue by Wassimo2** [fontforge/fontforge#4000]
hi i want to select unicode character copy and paste them to another font file 
https://stackoverflow.com/questions/58638451/fontforge-select-unicode-characters

**Comment by skef** [comment]
Do you mean that you want to copy a glyph with a certain unicode mapping, or you want to copy all and only those glyphs that have any unicode mapping?

**Comment by Wassimo2** [comment]
i want to copy selected unicode or  all unicode .
any way to do that so ?

**Comment by skef** [comment]
Do you care about/need to worry about:

1. References?
2. Open-type tables?
3. Anchor points?

If it's just a matter of copying the basic glyph info that's pretty straightforward. If there are references you may have to worry about ordering. 

The basic way to copy a single character based on unicode mapping, with the example of number 74, is this:
```
fromf = fontforge.open('from-file.sfd')
tof = fontforge.font()

fromf.selection.select(('unicode','more'), 74)
fromf.copy()
tof.selection.select(('unicode','more'), 74)
tof.paste()
tof.save('to-file.sfd')
```

There's probably a more elegant way of copying every encoded glyph, but here's some code that iterates through all the defined glyphs to find those with a unicode encoding, and then copies and pastes them by that encoding:

```
import fontforge

fromf = fontforge.open('from-file')
tof = fontforge.font()
tof.encoding = fromf.encoding

unis = []

fromf.selection.all()
for g in fromf.selection.byGlyphs:
    if g.unicode != -1:
        unis.append(g.unicode)

fromf.selection.none()

fromf.selection.select(('unicode','more'), *unis)
fromf.copy()
tof.selection.select(('unicode','more'), *unis)
tof.paste()
tof.save('to-file.sfd')
```
Copying and pasting by bulk-selection has some advantages -- in my experience FontForge is usually pretty intelligent about preserving which characters have splines and which have references when copying all at once. 

You don't necessarily need to copy into a new file -- you can open an existing one instead as long as you know the encodings are compatible or are willing to "reencode" it.

**Comment by Wassimo2** [comment]
i tried the example above and when i get to open the font file it says no table name .

**Comment by Wassimo2** [comment]
i'm using TTF files

**Comment by Wassimo2** [comment]
i need to remove any glyphs are not unicodes except SPACE 
Arabic fonts for Example

**Comment by skef** [comment]
If you're saying that the line `fromf = fontforge.open('from-file.ttf')` (with your filename) fails with "no table name" then that's an unrelated problem that would need its own diagnosis.

**Comment by Wassimo2** [comment]
so whats the right way to call tables ?
i'm sorry but i don't have much knowledge !

i just found that code and i tried to run it with unicode chars and i get that issue

**Comment by skef** [comment]
Can you put a complete copy of your adapted script and the complete error message into a comment here?

**Comment by Wassimo2** [comment]
i used this code 

`import fontforge

fromf = fontforge.open('input.ttf')
tof = fontforge.font()
tof.encoding = fromf.encoding

unis = []

fromf.selection.all()
for g in fromf.selection.byGlyphs:
    if g.unicode != -1:
        unis.append(g.unicode)

fromf.selection.none()

fromf.selection.select(*unis)
fromf.copy()
tof.selection.select( *unis)
tof.paste()
tof.save('output.ttf')`

and the returned command line error is 
At least one anchor point was lost when pasting from one font to another because no matching anchor class could be found in the new font.

**Comment by skef** [comment]
Ah, ok, so it is working it's just that some information is getting lost. 

I'm afraid that going into a full tutorial on everything you might want to copy from one font to another would take much too long. 

However, you said:

> i need to remove any glyphs are not unicodes except SPACE. Arabic fonts for Example

If that's what you want to do, it's probably going to be much easier to copy the whole font file and then open and delete what you *don't* want. Is there a reason you aren't taking that approach?

**Comment by Wassimo2** [comment]
> Ah, ok, so it is working it's just that some information is getting lost.
everything is lost not some of them 

> If that's what you want to do, it's probably going to be much easier to copy the whole font file and then open and delete what you don't want. Is there a reason you aren't taking that approach?

yes thats right !

**Comment by skef** [comment]
OK, if your goal is to create an internally consistent font that only contains some of the glyphs of a reference font, that process is usually called "subsetting". It can be tricky and while FontForge is capable of doing that, it requires some tricky coding and it may not do what you expected anyway. 

My recommendation is to either use one of the many online font subsetting tools (which may be an easy solution for you, just search for "font subsetting tool") or if you want to stick with python try `pyftsubset` in the [fonttools](https://github.com/fonttools/fonttools) package.

**Comment by skef** [comment]
This issue changed topic and I suspect it is resolved, so closing.
