### ISSUE TITLE
Stroke Replacement: What (if anything) to do about visible cusps

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4007]
In conjunction with #3991 we should chat about visible cusps and decide if the current solution is acceptable. 

Cusps are geometric artifacts of offsetting that occur when the curvature of the line being "stroked" is higher than the curvature of the portion of the nib drawing the curve. They only appear on the offset "side" of increased curvature (the acute/obtuse rather than reflex side). Here is an example (taken with the new code but compiled to trace the cusps):
![cusps](https://user-images.githubusercontent.com/6175836/68116688-4e211180-feb0-11e9-85f0-b1a0a6dd40e4.png)

(Note that when considering a calligraphic or other polygonal nib you can think of a point as having infinite curvature, and therefore never creating a cusp, and a line as having zero curvature, and therefore always creating a "cusp".)

Cusps are not a *calligraphic* issue; they "happen", in a sense, but the edge is always in an inked area. Accordingly, this is also true of the new algorithm when using the "Nib" join and cap options. Cusps are traced (as shown above) and then removed by Remove Overlap. 

Cusps can, however, be an issue with other cap and join styles, most commonly Bevel and Butt. This is well illustrated by @Tavmjong [here](http://tavmjong.free.fr/blog/?p=1257) and I hope he won't mind me borrowing a few images. This is Chrome and Firefox, respectively drawing a tight curve with a large offset radius and a butt cap:

![](http://tavmjong.free.fr/blog/wp-content/uploads/STROKING/stroke_open_path_chrome.png)

![](http://tavmjong.free.fr/blog/wp-content/uploads/STROKING/stroke_open_path_firefox.png)

As noted in the linked page Firefox is sweeping a line while Chrome is drawing an offset curve, and that strange concave edge is a visible cusp. One thing this difference demonstrates is that there isn't one correct rendering in this case. A user can combine a tight curve and a butt cap and just those parameters don't completely specify what the output should look like. 

Before we get into the new code, this is what the current (master branch) implementation does with a similar curve (I assume the generally sausage-like appearance would go away with a better `resolution` value):

![cusp2](https://user-images.githubusercontent.com/6175836/68118371-b3770180-feb4-11e9-87f5-8b24d75b2486.png)

With that in mind, this is how the new code looks with `TRACE_CUSPS` set to false (as it usually is):

![cusp3](https://user-images.githubusercontent.com/6175836/68118798-baeada80-feb5-11e9-80b5-a8cb28c926ae.png)

And now with `TRACE_CUSPS` set to true:

![cusp4](https://user-images.githubusercontent.com/6175836/68118813-c76f3300-feb5-11e9-8626-57e8354639f3.png)

So this last is, as you can see, quite similar to Chrome's output. 

Assuming Chrome's output is acceptable -- if anyone doesn't think so we can also discuss that in this issue -- I suppose the question boils down to whether we should trace the cusps to duplicate that output. 

After thinking about this for a while, my personal inclination is: No, we shouldn't bother tracing the cusps. Given that the geometry corresponding to a visible cusp is, in effect, undefined, any input/nib combination that includes one is (arguably) a mistake. Chrome should do something "reasonable" with it because it presents its output to the end-user. FontForge, in contrast, produces intermediate output that will eventually go into a font format. A user who sees that edge should take it as a reason to make a different tracing decision or to post-process.

**Comment by frank-trampe** [comment]
As you say, it seems unlikely to matter since any of the outputs is undesirable, but the Firefox model seems the only one that makes sense relative to the expected behavior of inking along a line segment sweeping perpendicular to the base path. Is there another high-level metaphor that describes the other behaviors?

**Comment by skef** [comment]
The high-level metaphor of offsetting is that of a parallel line. However, this isn't very useful given that the metaphor itself has no application in the circumstances that result in cups.

**Comment by frank-trampe** [comment]
Ah. That is indeed the right metaphor for offsetting. From my time thinking about stroking, I seem to have pigeonholed the parallel line metaphor as an approximation with poor edge case performance. But, for offsetting, that is exactly what one expects, I suppose.

**Comment by skef** [comment]
That seems reasonable. Because the current implementation only supports a constant nib angle there's no similar issue with stroking when using the nib options. And although I've extended the other caps and joins to arbitrary nibs they don't have any "metaphorical support" -- they're just stylistic choices.

**Comment by skef** [comment]
I guess as long as we've gotten into metaphor and the distinction between stroking and offsetting, the general approach I take is to consider what part of a nib is drawing the line given the shape and direction of the stroked curve. And if you do that with a circular nib you still get the cusps. 

The way I've come to think about this is as analogous to the problem solved by the differential on an axle: As the curve gets tighter one side of a physical nib will tend to drag against the paper. And when it gets tighter than the curvature of the nib, the "drawing edge" does, in a sense, double-back in the shape of the cusp. In a (metaphorical?) sense it *has* to for the line to continue from that point without a discontinuity in the drawing angle (as with a join). 

It's similar to how drawn line transitions from one corner of a calligraphic nib to another at the angle between them. 

So the two ways of thinking about offset curves are more intertwined than I first expected.

**Comment by ilyaza** [comment]
> One thing this difference demonstrates is that there isn't one correct rendering in this case.

Cannot agree.  (No matter how I hate Adobe’s implementations,) the PDF spec is generally speaking very well designed.  The PDF way is <b>the correct one</b>.  (This does mean that I have any objection to the other claims/conclusions of the OP.)

**Comment by skef** [comment]
@ilyaza The SVG spec doesn't seem to stipulate one of the renderings and the approach it takes traces back to the PS spec in a pretty linear way. Other than some references to "parallel" lines I don't see what in PLRMv3 (focusing on section 8.2) requires a particular rendering.

**Comment by skef** [comment]
Oh, never mind, my mistake -- the relevant section was referenced in @Tavmjong's doc. 

This is all likely theoretical and counter-factual, but offhand I'm not even sure how I would implement line-sweeping if I had to. It's a lot easier to think about as a rasterization strategy than for converting to spline paths. I suppose one could always rasterize and then fit the points on the edges.

**Comment by ilyaza** [comment]
Just to make it absolutely clear: I was focusing on a particular sentence.  I do not think that the implementing “the correct behavior” is warranted in any way.

(In my computer-generated fonts, I was <b>planning</b> to eventually use butt linecaps [where appropriate] — but pre-processing the input to avoid the monstrosities above.)

**Comment by skef** [comment]
@ilyaza: Understood. 

Given the conversation so far, I'm going to declare a *preliminary* conclusion that it's OK for untraced cusps to appear in output in some cases  given that:

1. Overhauling the whole algorithm to produce a fundamentally different result (like that of line tracing) would be a major undertaking.
2. The easily available alternative is a traced cusp, which isn't obviously better. 
3. Setting aside what the specifications mandate, there is no clearly correct solution on *aesthetic* grounds, so these cases can be left to the user to handle with pre- or post-processing. 

I'll leave this open for now. If there is no further discussion I'll copy this result into #3991 if and when it gets closer to being integrated.
