### ISSUE TITLE
Crash when removing overlaps

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4019]
The `stroke` branch crashes when removing overlaps. As requested in #3991 I am reporting this as a new issue. To reproduce:
1. Merge 91287f9beec230c8df05cedff9c61e1bd2b93a35 into 9a0a6ba5220d8bcbc3b9958d5b729cc5c83f7cb7.
2. Build a non-debug release.
3. Download and extract [removeOverlap.zip](https://github.com/fontforge/fontforge/files/3844079/removeOverlap.zip).
4. Run script1.py.
5. Run script2.py.

script2.py crashes. script1.py produces problem_layer.P, which is also included in the zip.

**Comment by skef** [comment]
As long as one has the recently committed 4e1c40c053c5ee982781ac2efddce78c2cc52513, one can now also just build from the master branch and run `script2.py` alone to reproduce the crash.
