### ISSUE TITLE
Does anyone know why I have invisible radio buttons?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4034]
Arch Linux, 5c2dbec01dadefb7eef1537c65b40a64e8a8da31, though not only on this commit, I've had this problem always on this PC. Has nothing to do with `stroke` branch.

![2019-11-25-154209_1060x1019_scrot](https://user-images.githubusercontent.com/838783/69521471-061a7980-0f9a-11ea-8707-123b03e1b0ef.png)

See e.g. `Nib Type` in above screenshot. I built via `cmake` + `ninja`&mdash;`sudo ninja install`.

**Comment by skef** [comment]
Lingering alternate theme somewhere? First off what does `/usr/share/fontforge/pixmaps/radio_on.png` look like? And is there anything suspicious-looking in `~/.config/fontforge`?

**Comment by skef** [comment]
Oh, check `/usr/local/share/fontforge/pixmaps` too. Are you building with `-DCMAKE_INSTALL_PREFIX=/usr` to match the `--prefix=/usr` of arch linux's  PKGBUILD?

**Comment by ctrlcctrlv** [comment]
/usr/local/share/fontforge/pixmaps/radio_on.png
![radio_on](https://user-images.githubusercontent.com/838783/69522758-28fa5d00-0f9d-11ea-93f5-40e037468ea3.png)

/usr/share/fontforge/pixmaps/radio_on.png (doesn't exist, neither does /usr/share/fontforge)

I'm not building with any options that aren't in the CMake build guide. FontForge is at /usr/local/bin/fontforge

**Comment by skef** [comment]
OK, run fontforge this way: `strace -o /tmp/fftrace.txt fontforge`, then open a new font, draw a little bit, open the dialog, close and quit. Then grep for "radio_on" in `/tmp/fftrace.txt`.

**Comment by skef** [comment]
`strace` is in the `strace` package if you don't have it.

**Comment by ctrlcctrlv** [comment]
I've tried it a few different ways but don't get any "radio_on" in that file.

**Comment by skef** [comment]
Then something is preventing normal radio button processing. What happens when you search for `.png` (presumably with a backslash before the dot if you're grepping? 

For reference this is what I see on my system:
```
access("/home/skef/.FontForge/tango-ct.theme/radio_on.png", F_OK) = -1 ENOENT (No such file or directory)
access("/home/skef/.FontForge/tango-ct.theme/tango/radio_on.png", F_OK) = -1 ENOENT (No such file or directory)
access("/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps//radio_on.png", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/fontforge/pixmaps/radio_on.png", F_OK) = 0
openat(AT_FDCWD, "/usr/share/fontforge/pixmaps/radio_on.png", O_RDONLY) = 5
access("/home/skef/.FontForge/tango-ct.theme/radio_on_disabled.png", F_OK) = -1 ENOENT (No such file or directory)
access("/home/skef/.FontForge/tango-ct.theme/tango/radio_on_disabled.png", F_OK) = -1 ENOENT (No such file or directory)
access("/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps//radio_on_disabled.png", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/share/fontforge/pixmaps/radio_on_disabled.png", F_OK) = 0
openat(AT_FDCWD, "/usr/share/fontforge/pixmaps/radio_on_disabled.png", O_RDONLY) = 5
```
Those are the various places FontForge looks for the pixmap, with the `= 0`s being where it finds them. 

BTW I'm going out for a bit be back in an hour or two.

**Comment by ctrlcctrlv** [comment]
I see essentially the same thing you do, just `/home/fred` instead.

```strace
access("/home/fred/.FontForge/tango-ct.theme/palettehand.png", F_OK) = -1 ENOENT (No such file or directory)
access("/home/fred/.FontForge/tango-ct.theme/tango/palettehand.png", F_OK) = -1 ENOENT (No such file or directory)
access("/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps//palettehand.png", F_OK) = -1 ENOENT (No such file or directory)
access("/usr/local/share/fontforge/pixmaps/palettehand.png", F_OK) = 0
```

I don't know why none of them are radio button related though?

**Comment by skef** [comment]
Next question: Grep that same file for "resources". Mine shows this:

```
openat(AT_FDCWD, "/usr/share/fontforge/resources/fontforge.resource", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/fontforge/pixmaps/resources", O_RDONLY) = 3

```

**Comment by ctrlcctrlv** [comment]
Snip:

```
access("/usr/local/bin/fontforge", X_OK) = 0
openat(AT_FDCWD, "/usr/local/share/fontforge/resources/fontforge.resource", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/share/fontforge/hotkeys/default", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=28406, ...}) = 0
```

**Comment by skef** [comment]
Let's move this to the free node

**Comment by ctrlcctrlv** [comment]
The cause of this issue was an outdated `XPrefs` file clashing with newer FontForge.

I've used FontForge for too long, basically. Deleting it solved the problem; I'll reset what needs to be reset in the GUI.
