### ISSUE TITLE
can't move between subtable rows and colomns with shortcut keys

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4044]
in new fontforge versions (after 2017) it's not possible to move between subtable rows and colomns with arrow keys(up/down) or tab button.(all subtables like substitutions and kerning pair subtables, ...etc on windows OS)

**Comment by skef** [comment]
@jtanx I've narrowed this one down quite a bit but I'm not sure I can make further progress without either a lot of research or some advice. 

The keystrokes still work when compiling against X11 but don't when using GDK. The relevant difference is here in `gcontainer.c:_GWidget_TopLevel_Key`:
```
526         if ( !handled ) {
527             if ( ew->widget_data==NULL ) {
528                 if ( ew->eh!=NULL )
529                     handled = (ew->eh)(ew,event);
530             } else if ( ew->widget_data->e_h!=NULL )
531                 handled = (ew->widget_data->e_h)(ew,event);
532         }
```
 In both cases `ew->widget_data` and `ew->widget_data->e_h` are not NULL. However, with X11 `e_h` is `matrixeditsub_e_h()` but with GDK it is `pstkd_e_h()`. The former checks for the arrow keysyms.

**Comment by jtanx** [comment]
I thought I commented on this somewhere, but I can't find it.

Anyway I think the difference is in how event propagation works under GDK (which I'm assuming is inherently tied to what GTK expects):

> For key events, the top-level window’s default “key-press-event” and “key-release-event” signal handlers handle mnemonics and accelerators first. Other key presses are then passed to gtk_window_propagate_key_event() which propagates the event upwards 

https://developer.gnome.org/gtk3/unstable/chap-input-handling.html

**Comment by skef** [comment]
Some more: I think the window coming into `_GGDKDraw_DispatchEvent()` with the key event is the tippy-top dialog window, while on the X11 side `XFindContext()` in `dispatchEvent()` is returning the container corresponding to `gmatrixedit`. I've confirmed that two containers, one with `pstkd_e_h` as the sub-event-handler and one with `matrixeditsub_e_h` as the sub-event handler, are created in either case.

**Comment by jtanx** [comment]
Yeah that concurs with what I was thinking.

**Comment by skef** [comment]
The following makes the arrows work and doesn't *obviously* (with pretty trivial testing) break other stuff:
```
diff --git a/gdraw/gcontainer.c b/gdraw/gcontainer.c
index 8a56faa7a..bf53d0c3c 100644
--- a/gdraw/gcontainer.c
+++ b/gdraw/gcontainer.c
@@ -95,6 +95,13 @@ return( NULL );
 return( td->gfocus );
 }
 
+GWindow GWindowGetFocusWindowOfWindow(GWindow gw) {
+    GGadget *gg = GWindowGetFocusGadgetOfWindow(gw);
+    if ( gg!=NULL && gg->base!=NULL )
+       return gg->base;
+    return gw;
+}
+
 int GGadgetActiveGadgetEditCmd(GWindow gw,enum editor_commands cmd) {
     GGadget *g = GWindowGetFocusGadgetOfWindow(gw);
 
diff --git a/gdraw/ggdkdraw.c b/gdraw/ggdkdraw.c
index e17a6a091..e97d41291 100644
--- a/gdraw/ggdkdraw.c
+++ b/gdraw/ggdkdraw.c
@@ -901,6 +901,8 @@ static void _GGDKDraw_DispatchEvent(GdkEvent *event, gpointer data) {
             GdkEventKey *key = (GdkEventKey *)event;
             gevent.type = event->type == GDK_KEY_PRESS ? et_char : et_charup;
             gevent.u.chr.state = _GGDKDraw_GdkModifierToKsm(((GdkEventKey *)event)->state);
+           gevent.w = GWindowGetFocusWindowOfWindow(gevent.w);
+           gw = (GGDKWindow)gevent.w;
 
 #ifdef GDK_WINDOWING_QUARTZ
             // On Mac, the Alt/Option key is used for alternate input.
diff --git a/inc/gdraw.h b/inc/gdraw.h
index a111207e0..a83ec2255 100644
--- a/inc/gdraw.h
+++ b/inc/gdraw.h
@@ -470,6 +470,7 @@ extern void GDrawSkipMouseMoveEvents(GWindow w,GEvent *last);
 extern void GDrawEventLoop(GDisplay *disp);
 extern void GDrawPostEvent(GEvent *e);
 extern void GDrawPostDragEvent(GWindow gw,GEvent *e,enum event_type);
+extern GWindow GWindowGetFocusWindowOfWindow(GWindow gw);
 
 extern GTimer *GDrawRequestTimer(GWindow w,int32 time_from_now,int32 frequency,
        void *userdata);
```
Could it really be this simple? Where is this likely to fail (presumably because the focus doesn't match up)?

**Comment by jtanx** [comment]
Will take a closer look, bu on the surface of it, that looks wrong - particularly how ggdkdraw is now depending on something that gcontainer is doing.

**Comment by skef** [comment]
This can be discussed in the context of #4180 now. 

As for the dependency it seems hard to avoid if need to bring in focus at all, unless tracking that needs to be added to GGDKdraw. `gcontainer.c` appears to be where that state is stored.

**Comment by jtanx** [comment]
It still doesn't feel like the right place to solve this. Either ggdkdraw just needs to somehow forward the event to the right window, or the ggadget code needs to pass the event down the chain. 

Note how this only breaks some actions - gcontainer obviously has a way of forwarding key events down to the relevant gadget otherwise all key events would have been broken.

**Comment by skef** [comment]
But what constitutes the "chain" other than which gadget has the focus at the bottom? 

The vast majority of sub-top-level directed events have `x,y` coordinates and therefore aren't focus dependent. Keystrokes to top-level windows without sub-windows will work because there's no ambiguity. 

I'll admit I don't understand the entirety of the problem but it looks like what handlers hand off to what grep up organically in the context of X `Window` targets. The problem here is that the grain is different.

**Comment by skef** [comment]
I suppose one could try modifying `_GWidget_TopLevel_Key()` around the `gfocus` handling to walk down the chain that way. However, any change there would also affect the gxdraw path. And anyway all the `handled` logic would have to be checked carefully to ensure it could be chained and there would probably need to be some re-writing. For example, if a sub-window can contain a menu the present location of `GKeysymIsModifier()` in `_GWidget_TopLevel_Key()` would come too early.
