### ISSUE TITLE
OpenType "rand" feature

### ISSUE THREAD

**Issue by JapanYoshi** [fontforge/fontforge#4045]
V20190801, Windows 10

I want to make a distressed typewriter font with 3 subtly different glyphs for each letter, but I don't know how to add the `rand` OpenType feature. I thought it was one of the GSUB tables, but I can't find it.

**Comment by ctrlcctrlv** [comment]
You want to make [TT2020](https://twitter.com/HW_BEAT_THAT/status/1202910568304107520), except with fewer alternates? :-P

**Comment by ctrlcctrlv** [comment]
Let me be more serious. As regards `rand`, in my development of TT2020, I discovered via correspondence that it is supported in HarfBuzz, so has somewhat wide support. 

It should be possible to add to FontForge as it is, _in veritate_, `aalt`, which has already been well implemented (to my knowledge). Unlike `aalt` which gives users all alternates to select from and demands their input, `rand` is a kind of forced `aalt`: the computer will select an alternate from the list regardless of user intent.

**Comment by ctrlcctrlv** [comment]
By the way @JapanYoshi if you want to work together I'd love to have someone else make a TT2020 style! If you have a script that generates good-looking typewritter-esque glyphs I'll run it on TT2020's base font. There are 3 styles currently in the beta: B, D and E. Perhaps you can help me make _TT2020 Style JY_? Just a thought!

**Comment by JapanYoshi** [comment]
My (unfortunately manual) procedure is this:
* Type letter in existing typewriter font
* blur
* overlay random cloud-like noise
* add transparent solid color according to frequency
* threshold
* shift position a little bit

**Comment by ctrlcctrlv** [comment]
In what program? Can I see some output? Might you wish to take this to IRC? #fontforge on Freenode if so.

**Comment by JapanYoshi** [comment]
I used GIMP to filter the letters. I just had the lowercase letters as my intended character set for a very specific usage.
![typewriter_distressed](https://user-images.githubusercontent.com/8707990/70370404-436ff700-190a-11ea-903c-6d72dfe5712d.png)

**Comment by ctrlcctrlv** [comment]
Why do the characters start thin and end heavy? I use GIMP also for all my styles so far. Here is my script for Style B:

```python
# Generate style B, given PNG of a single glyph image.

import sys
import os
import subprocess

i_f = os.environ["GIMPIMAGE"]
seed = os.environ["SEED"] or 11
alt = os.environ["ALT"] or 1
if alt <= 1:
    outfile = "styleB/{}.png".format(i_f.replace("pngs/", "").replace(".png", ""))
else:
    outfile = "styleB/{}.{}.png".format(i_f.replace("pngs/", "").replace(".png", ""), alt)
print("Opening {} and writing to {}".format(i_f, outfile))

im = pdb.file_png_load(i_f, 0)
print("===SIZE IS: {}===".format(str(im.height)+"X"+str(im.width)))
pdb.gimp_image_scale(im,im.width/3,im.height/3)
print("===SIZE IS: {}===".format(str(im.height)+"X"+str(im.width)))
pdb.plug_in_gauss(im, im.active_drawable, 80, 80, 0)
cell_noise_file = "gegl:cell-noise/{}x{}x{}.png".format(im.height, im.width, seed)
if not os.path.isfile(cell_noise_file):
    command = "/usr/bin/python3.8 gen_cell_noise.py -h {} -w {} -o 'gegl:cell-noise' -s {}".format(im.height, im.width, seed)
    os.system(command)
la = pdb.gimp_file_load_layer(im, cell_noise_file)
new_mask = pdb.gimp_layer_create_mask(la, 5)
pdb.gimp_layer_add_mask(im.layers[0], new_mask)
pdb.gimp_drawable_invert(new_mask, False)
pdb.gimp_brightness_contrast(new_mask, 57, 94)
pdb.gimp_layer_remove_mask(im.layers[0], 0)
pdb.gimp_layer_flatten(im.layers[0])
pdb.gimp_brightness_contrast(im.active_drawable, -127, 127)
pdb.gimp_image_convert_indexed(im, 0, 3, 0, False, True, '')
pdb.gimp_image_convert_grayscale(im)
pdb.gimp_layer_add_alpha(im.layers[0])
pdb.gimp_image_select_color(im, 2, im.active_drawable, (1.0,1.0,1.0))
pdb.gimp_drawable_edit_clear(im.active_drawable)
pdb.script_fu_distress_selection(im, im.active_drawable, 127, 2, 2, 10, 1, 1)
pdb.gimp_selection_invert(im)
nl = pdb.gimp_layer_new(im, im.width, im.height, 3, "QQ", 100, 0)
pdb.gimp_image_insert_layer(im, nl, None, -1)
pdb.gimp_image_remove_layer(im, im.layers[0])
#Below is problem command
pdb.gimp_edit_bucket_fill(im.active_drawable, 0, 0, 100, 255, True, 1.0, 1.0)
pdb.file_png_save_defaults(im, im.active_drawable, outfile, 0)
pdb.gimp_quit(1)
```

To speed up the process, cell noise can be reused, and is generated separately (requires python-gegl):

```python
#!/usr/bin/env python3
# Minimal example of using the filter `cell-noise` with GEGL through python-gegl.

import argparse

import sys
sys.path.append("/usr/local/lib/python3.8/site-packages")

ap = argparse.ArgumentParser(description="Generate Cell Noise without opening GIMP (unneeded arguments hardcoded, see script).", add_help=False)
ap.add_argument('-h', '--height', type=int, required=True)
ap.add_argument('-w', '--width', type=int, required=True)
ap.add_argument('-o', '--outdir', type=str, required=True)
ap.add_argument('-s', '--seed', type=int, required=True)
ap.add_argument('-б', '--бесцельный', type=int)
args = ap.parse_args()

# These two lines makes sure version of gegl is correct
import gi
gi.require_version('Gegl', '0.4')

import gegl
import random

g = gegl.Graph("cell-noise", "crop", "png-save")
g[2].path = "{outdir}/{height}x{width}x{seed}.png".format(outdir=args.outdir, height=args.height, width=args.width, seed=args.seed)
g[1].height = args.height
g[1].width = args.width
#                           Seed bounds ( on my system anyway )
#g[0].seed = random.randint(-2147483648, 2147483648)
g[0].seed = args.seed
g[0].scale = 0.100
#These are all the defaults, but we set them in case the defaults change.
g[0].iterations = 1
g[0].shape = 2
g[0].rank = 1
g[0].palettize = False
g()
```

**Comment by JapanYoshi** [comment]
May have dragged the wrong way and never noticed. All the automatic stuff
is way over my head.

**Comment by khaledhosny** [comment]
`rand` is already possible in FontForge, the lookup needs to be alternate substitution lookup and you can enter the `rand` feature tag manually if it isn’t available from the features list in the UI.

**Comment by JapanYoshi** [comment]
How do you bypass the UI like that?

**Comment by khaledhosny** [comment]
You can type feature tag in the lookup dialog.

**Comment by khaledhosny** [comment]
Actually, if you select “Alternate Substitution” as lookup type, there is “rand Randomize” in the feature dropdown.

**Comment by khaledhosny** [comment]
Note, AFAIK, only applications using HarfBuzz and Affinity Publisher (and some other niche applications), support `rand` feature, so it might still not work in your application of choice (or if you're selling/distributing the font, you might get complaints that it does not work in so and so application).

https://github.com/alif-type/punk-otf uses `rand` feature, you can use it to test the support of this feature in various applications.

Alternatively, you can emulate the pseudo randomness with contextual substitution lookups.

**Comment by ctrlcctrlv** [comment]
Closed as answered, stale question.
