### ISSUE TITLE
Change Glyph glitches out

### ISSUE THREAD

**Issue by 289aincwaeubr** [fontforge/fontforge#4046]
Change Glyph results in major glitches when "Vertical" is set to "Control Vertical Counters (use for CJK)".

![image](https://user-images.githubusercontent.com/58630921/70376044-36043e00-1905-11ea-909f-1277036c94a9.png)
(this is with the default values otherwise, that is, 100%+0)

**Comment by ctrlcctrlv** [comment]
So what? You're not using it for its intended purpose.

**Comment by 289aincwaeubr** [comment]
So you're saying the intended purpose of the "Control Vertical Counters (use for CJK)" setting is to glitch out?

**Comment by skef** [comment]
The acronym "CJK" refers to [Chinese, Japanese, and Korean](https://en.wikipedia.org/wiki/List_of_CJK_fonts) characters. This option is intended to be used with such characters, and (I believe) attempts to maintain certain properties when the character has a counter (an enclosed area). 

@ctrlcctrlv is arguing that when a parameter intended for one kind of character is used with a different kind of character, no particular result is guaranteed.

**Comment by 289aincwaeubr** [comment]
I'm blocking both of you for closing this important issue.
