### ISSUE TITLE
Warning: Contour end did not close

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4052]
Arch Linux, 3890b4762567b84cd57b6d03fb382ad7fdb3ad50

cc: @skef 

I would rate this bug as **high severity** as there seems to be no obvious way to fix it.

# File

[b.sfd](https://github.com/fontforge/fontforge/files/3948549/b.zip)

# Settings

* Circular, 45-45-0
* Setting &laquo;Remove Overlap&raquo; to &laquo;None&raquo; does not fix the problem.

# Screenshot

![2019-12-11-130929_2560x2101_scrot](https://user-images.githubusercontent.com/838783/70593275-57bc3880-1c17-11ea-95a3-81df92fb1e5d.png)
![2019-12-11-130955_1066x343_scrot](https://user-images.githubusercontent.com/838783/70593284-6276cd80-1c17-11ea-8f7c-c4d6dcb5773a.png)

**Comment by skef** [comment]
Note: You can use a Round cap as a workaround on this one.

**Comment by ctrlcctrlv** [comment]
It's strange that that isn't the default for the circular nib when the major and minor axes are equal? Thank you though, that does work. So this isn't as serious as there's a workaround.

**Comment by skef** [comment]
The problem with changing the default cap and join styles based on particular parameters is the question of what to change them back to when the user switches around. (There's a similar issue with the angle: ideally it would be zero for truly circular parameters, but then if people set a custom value they would lose it when changing things.) 

I basically didn't want to think about it.

Anyway, this big falls under the generic heading of "oh crap the floating point margin I guessed at isn't quite big enough for this case for some reason." My tentative recommended fix is to increase the third parameter of SplineSetJoin by either 2 or 2.5. (And while it's being changed, I now think they should all be 2*FIXUP_MARGIN or 2.5*FIXUP_MARGIN so not INTERSPLINE_MARGIN.) 

Hell, why not 2.5? Probably setting it to 1 em (equivalent to 10*FIXUP_MARGIN) would be fine, although that would risk not catching other geometry problems.

Can you test with that and see if it works OK?

**Comment by skef** [comment]
Well, a nib size of 100 exceeds a 2.5 margin, so I guess I have to think about this more.

**Comment by skef** [comment]
Oh crap I think I know what this is ...
