### ISSUE TITLE
install ubuntu (python3) : No module named 'fontforge'

### ISSUE THREAD

**Issue by vanche** [fontforge/fontforge#4056]
when I import fontforge, it can't find the fontforge module.
is there any installation guide for python3?

**Comment by skef** [comment]
Are you installing the program yourself or using a distro-supplied package?

**Comment by vanche** [comment]
I tried installing from source.

**Comment by jtanx** [comment]
More info please; filling out the issue template would have helped. What have you tried so far? OS version? Python version installed? build logs?

**Comment by Krulvis** [comment]
Hijacking this thread:
I successfully compiled from scratch using the build commands found in the aur [PKBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fontforge-git) file.
I want to be able to use the binaries in python however and found [online](http://dmtr.org/ff.php) that I should do this: `configure --enable-pyextension` But I have absolutely no idea what this means or where to add it. 

Any help is appreciated.

**OS:** Arch 
**Kernel:** 5.3.13
**Python:** 3.8.0

**Comment by skef** [comment]
Cmake build guidance is here: https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge

However, the python modules are now supposed to build by default when python is enabled and the build process can "find" the needed python configuration.

**Comment by Krulvis** [comment]
Thanks for the quick response!
I've now ran this to build with cmake: `cmake -G"Ninja" -D"CMAKE_INSTALL_PREFIX:PATH=/usr" -D"CMAKE_INSTALL_LIBDIR:PATH=lib" -D"Python3_ROOT_DIR=../../venv" ..
`
but I can't find python modules anywhere. How do I enable python and make sure it can "find" the needed python configuration?

**Comment by skef** [comment]
There's not much I can do to help from this end; I don't have any information about what may be going wrong. I run an Arch system myself and when I build with CMake and similar arguments (well, no CMAKE_INSTALL_LIBDIR) the modules are installed. 

After you build what does the output of "ninja check" look like?

**Comment by Krulvis** [comment]
`100% tests passed, 0 tests failed out of 100`
```
The following tests did not run:
          1 - test001_ff (Skipped)
          2 - test002_ff (Skipped)
          4 - test004_ff (Skipped)
          6 - test006_ff (Skipped)
         10 - test010_ff (Skipped)
         22 - test112_ff (Skipped)
         23 - test113_ff (Skipped)
         26 - test116_ff (Skipped)
         27 - test117_ff (Skipped)
         32 - test123_ff (Skipped)
         34 - test125_ff (Skipped)
         57 - test1001a_py (Skipped)
         58 - test1001a_pyhook (Skipped)
         59 - test1001b_py (Skipped)
         60 - test1001b_pyhook (Skipped)
         63 - test1002_py (Skipped)
         64 - test1002_pyhook (Skipped)
```

Where do you find the modules as in, how do you know they are installed?

**Comment by jtanx** [comment]
I doubt it'd work when you're targeting a virtualenv. What's the cmake output, from running the cmake command?

**Comment by Krulvis** [comment]
> I doubt it'd work when you're targeting a virtualenv. What's the cmake output, from running the cmake command?

I see what you mean,
reran the build from another folder now targeting my python3.8 directly:
`cmake -G"Ninja" -D"CMAKE_INSTALL_PREFIX:PATH=/usr" -D"CMAKE_INSTALL_LIBDIR:PATH=lib" -D"PYTHON=/usr/bin/python3.8" ..`
However I still can't find fontforge as module anywhere in the python3.8...

Here are the CMake output files
[CMakeError.log](https://github.com/fontforge/fontforge/files/4024318/CMakeError.log)
[CMakeOutput.log](https://github.com/fontforge/fontforge/files/4024319/CMakeOutput.log)

**Comment by jtanx** [comment]
Can you try deleting and recreating your build folder, and just running

```
cmake -GNinja ..
```

I don't need the CMakeError/CmakeOutput.log files, just what it prints to the console.

**Comment by Krulvis** [comment]
This is the output from `cmake -GNinja`
https://pastebin.com/BfqLPtkn

**Comment by jtanx** [comment]
From the logs it looks like it worked fine. What do you mean by it not working? Have you actually tried running `ninja install` at some point?

**Comment by Krulvis** [comment]
I did ran just `ninja` without install. 
This is the output from `ninja install`
```
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/libfontforge.so.4
CMake Error at fontforge/cmake_install.cmake:47 (file):
  file INSTALL cannot copy file
  "/home/krulvis/Downloads/fontforge/build/lib/libfontforge.so.4" to
  "/usr/local/lib/libfontforge.so.4".
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)


FAILED: CMakeFiles/install.util 
cd /home/krulvis/Downloads/fontforge/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by jtanx** [comment]
I'd suggest you read up on the steps involved in building from source (it's more or less all the same, a configure step, a build step and an install step).

The specific question here is, are you ok with installing this build of fontforge into your system (or more precisely into /usr/local)? This should also make the fontforge python modules importable from system python. If so, you'll need to run `sudo ninja install`. 

Otherwise you'd need to change the install prefix to not run with elevated permissions.

**Comment by Krulvis** [comment]
Yea, ok I'm fine with installing it into my system using sudo, but I still can't find or use those modules...
They are not in /lib/python3.8/site-packages and neither can I import fontforge when I run a python script using that python3.8

**Comment by jtanx** [comment]
Can you see them under `/usr/local/lib/python3.8/site-packages`?

**Comment by skef** [comment]
As an arch user I would say that `cmake  -GNinja ..  -DCMAKE_INSTALL_PREFIX=/usr` is a more typical configuration. Arch maintainers almost always redirect install output to the hierarchy directly under `/usr`.

**Comment by Krulvis** [comment]
> As an arch user I would say that `cmake -GNinja .. -DCMAKE_INSTALL_PREFIX=/usr` is a more typical configuration. Arch maintainers almost always redirect install output to the hierarchy directly under `/usr`.

That's what I thought but I guess it doesn't really matter to me in this case.

> Can you see them under `/usr/local/lib/python3.8/site-packages`?

Yes! Thanks for the amazing help guys, I'm still confused as to why it gets placed there though. I ran without the INSTALL_PREFIX command so was expecting the python module in /lib/python3.8.

This can now be marked as solved as I am expecting the same result for vanche once he follows the steps explained in this thread.
