### ISSUE TITLE
SelectAll() and BuildAccented() has no effect in script

### ISSUE THREAD

**Issue by paulbernhard** [fontforge/fontforge#4061]
Hi,

i wrote a simple fontforge script to process .pfa font files. The script `prepress.pe` is supposed to…

```
Open($1)
Reencode("unicode")
ScaleToEm(1024)
SelectAll()
BuildAccented()
Save($1)
Close()
```

Running it using `$ fontforge -script prepress.pe fontfile.pfa` it reencodes the file, scales all characters to 1024 em, saves it to `fontfile.pfa` but **does not build the accented glyphs**, exiting the script without error message. Reproducing the same steps in the GUI version on my Mac works well and build the accented glyphs sucessfully. 

The script executes very fast and i have the suspicion that the selection step before buiding the accents is somehow omitted. Trying the same process with `Clear()` instead of `BuildAccented()` does not clear all glyphs as expected. But if i replace `SelectAll()` with `Select("A")`, the "A" glyph is sucessfully cleared.

Could it be that the script doesn't "wait" for the `SelectAll()` to be performed or what could be a possible issue here ?

Thanks !

Specifications :

- Mac OS X 10.13.6
- fontforge OS X install: version 20190801
- fontforge command line install (brew): 20190801

**Comment by ctrlcctrlv** [comment]
What if you rewrite the script in Python? Does this only affect the FontForge scripting language (which is not recommended for new scripts)?

**Comment by paulbernhard** [comment]
I am neither very familiar with python nor the fontforge scripting language. Could you help me "translating" this script to python ?

**Comment by skef** [comment]
A couple things:

1. By using `Save()` this way you wind up replacing what was a PostScript Type 1 font file with a FontForge SFD file. I hope that is what you intended
2. With that caveat, I just saved a font as a `.pfa` from FontForge and then ran your script on it and got the same result as I did with the UI commands. So without more information (e.g. a specific test file to work with) it will be difficult to debug this problem.

**Comment by paulbernhard** [comment]
Hello, i am currently rewriting my fontforge script as python script. In the [Fontforge Docs)(https://fontforge.org/docs/) i can not find any method to expand the stroke using python scripts. I would assume something like:

```python
import fontforge
font = fontforge.open(path)
glyphs = font.selection.all()
glyphs.expandStroke(width) # <= this method does not exist
font.generate(filename)
```

**Comment by skef** [comment]
The glyph level method is described here: https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.glyph.stroke . Font level is here: https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.stroke

**Comment by paulbernhard** [comment]
Thanks a lot for the fast response. The python fontforge script works like a charm and the (new?) [Fontforge Docs](https://fontforge.org/docs) are good aswell; it just takes a little bit of time to find the right methods compared to the "original" Fontforge scripting.

I tried running a script to build accents again and it works well:

```python
import fontforge

font = fontforge.open(file)
font.selection.all()
font.build()
font.generate(path)
```

Thanks for all you do, best,
Paul
