### ISSUE TITLE
Feature request - Enhance editing of point handles.

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#408]
Off point handles in fontforge are only editable and visible when a point is selected. Propose that handles can be visible and editable when points are not selected. E.g. Glyphs and Robofont show off point handles as visible and can be moved without point being slected. This is provides superior editing functionality over fontforge.

Propose that off point handles in fontforge should be editable without the point being first selected and that fontforge gains ability to toggle visibility of off handles curves.

**Comment by skef** [comment]
This is long done, right?

**Comment by skef** [comment]
Yes, it's done. The Toggle is under View -> Show
