### ISSUE TITLE
Mac OS Gatekeeper prevents launch without workaround

### ISSUE THREAD

**Issue by lethefrost** [fontforge/fontforge#4082]
After I updated the system version to Catalina, I found that I was no longer able to use FontForge. It seems that it doesn't ask for the authority to access folders and it shows below in each folder when I try to find font file to open. 
<img width="369" alt="Snip 2019-12-31, 01-00-50" src="https://user-images.githubusercontent.com/47198693/71611786-e1518d00-2b69-11ea-9861-e8634cc748aa.png">
<img width="369" alt="Snip 2019-12-31, 01-05-45" src="https://user-images.githubusercontent.com/47198693/71611787-e3b3e700-2b69-11ea-96c6-e9db6596a965.png">
<img width="369" alt="Snip 2019-12-31, 01-05-54" src="https://user-images.githubusercontent.com/47198693/71611789-e57daa80-2b69-11ea-8acb-6a2d3f5a4899.png">

Since FontForge doesn't request authority of accessing, I couldn't find it in system privacy&safety setting and authorize it... I don't know why but the `+`/`-` buttons under the authorized apps list are grey and not available to click, which might mean that I couldn't add fontforge to the list manually..

OS version is macOS Catalina 10.15.2, FontForge version is 20190801.
Thanks for your time!

**Comment by ctrlcctrlv** [comment]
At first brush this seems to be a duplicate of #2344, but it is not, it's just related.

Projects in a similar position to ours have this problem as well: [GIMP](https://gitlab.gnome.org/GNOME/gimp/issues/3710), [Inkscape](https://gitlab.com/inkscape/inkscape/issues/459). You should try the workarounds they list.

After perusing the threads myself the easiest workaround is to avoid "Downloads, Documents, and Desktop, [as they] have additional protections".

As far as a real fix goes, I don't know that one will be immediately forthcoming. Certainly a fix won't be coming from me, as I have no access to any version of OS X to know what will work and what will not.

**Comment by lethefrost** [comment]
> As far as a real fix goes, I don't know that one will be immediately forthcoming. Certainly a fix won't be coming from me, as I have no access to any version of OS X to know what will work and what will not.

I am puzzled by the mysterious behavior of OS, and can only partially understand your words. It's maybe because I am currently not a mac developer and don't know very well about mac. I'm just curious about and wondering why some other apps could call a window (floating box) from the system, that says something like "Do you want to authorize *** app to access *** folder?" and user could choose yes or no by clicking buttons at the window. After that, the app should be able to operate in these folders. It's like to request user's permission. I am just asking something that I really don't know and if there is any offense then I would be really sorry for that. Is there any technical issues that prevent developers from doing so? 
Anyway, I got the point - don't use the default folders that were created by the macOS. Thank you for your advices and time!

**Comment by ctrlcctrlv** [comment]
There are a few reasons, but the first one is really simple: FontForge is cross platform, primarily developed on Linux, with Windows being the other platform that gets the most developer attention.

This issue only affects Mac OS, and only the latest version of it. That means we need to (a) have a Mac OS PC (b) maybe have a developer license? (c) buy Xcode? (d) buy a signature? I really don't know what follows from (a) because I don't even have (a). 

There's no way for me, as a developer, to emulate what Apple is doing here on my system. Their Gatekeeper is not based on some open standard, it's not just a matter of me loading some Linux kernel module to enforce the same things Apple does; there's no standard API for this.

The fact that GIMP, Inkscape, Krita, and so on, were all hit by this should help you understand: we had no early access to Catalina, Apple did nothing to warn even those big projects, much less ours, and even now, with Catalina in the wild, I'm missing (a).

Hope that helps

**Comment by JoesCat** [comment]
This OS behaviour can probably be looked at as an incremental improvement in security.
For example, this article mentions [Nasty Mac malware](https://www.theregister.co.uk/2019/12/21/roundup_dec_20/), and MACs make up 1/12th of the PC population.
Windows requires signed "drivers" (or a conscientious approval by the end user to allow them), and also owns it's own anti-malware software, yet it also gets viruses and trojans too. So far, Microsoft isn't requiring signed software yet, but it probably is coming too.
Fortunately, Linux is mostly ignored, but it's not immune ["...received 6 threats"](https://forums.mageia.org/en/viewtopic.php?f=7&t=13202#p77431).
Reality is, viruses of the past were hoaxes, jokes and pranks, but today's viruses are "for profit" and have a lot of effort put into them.

**Comment by ctrlcctrlv** [comment]
Even if this makes Mac users more secure, everything I wrote remains true, especially in terms of our ability to respond. Apple's Gatekeeper is not free software, nor does it does not implement an open protocol&mdash;I have no ability to fix this, and no desire to go buy a Mac. Please feel free to submit a fix if you can.

**Comment by lethefrost** [comment]
> The fact that GIMP, Inkscape, Krita, and so on, were all hit by this should help you understand: we had no early access to Catalina, Apple did nothing to warn even those big projects, much less ours, and even now, with Catalina in the wild, I'm missing (a).
> 
> Hope that helps

Thanks for explaining. I understand you are developing in an unfriendly environment and all of your work are not easy. You guys are really nice! I hope I could help in the future if I learn about that.

**Comment by jtanx** [comment]
I'm not sure if it's because I have developer tools installed or something, but this does not happen for me. I've tried out the 20190801 release, and apart from the usual 'this file was downloaded from the internet' warning, I can access all those locations just fine.

![image](https://user-images.githubusercontent.com/5137410/73605587-31ea5900-45f4-11ea-8c91-d58633c8630f.png)

This is in macos catalina 10.15.2.

By the way, I had to right click open the app to get around that 'file downloaded from the internet' /gatekeeper warning.

Please reopoen this if it's still an issue. Although I hazard to guess this will become more of an issue down the line with app notarization eugh

**Comment by ctrlcctrlv** [comment]
I'm reopening this as many users are noticing it. #4227, #4240, question received also to @FontForge Twitter account.

We _at least_ need to add something about how to handle this to the documentation.

**Comment by jtanx** [comment]
Well at least I can finally repro this, I had system integrity protection turned off, which was why I wasn't seeing the issue.

**Comment by jtanx** [comment]
The fix appears to be to get rid of the init script, in which case it'll prompt you to grant access. Which ultimately means fixing FontForge's convoluted startup process...

**Comment by alanwei0** [comment]
Maybe I found a workaround to make FontForge work again:

1. Find out FontForge in your Application folder
2. Right click on the icon to trigger context menu, click Show Package Contents
3. Go into `Contents/Resources/opt/local/bin/fontforge` and double click to run it on command line.

**Comment by LalithArt** [comment]
Hi,
I have same issue. 
<img width="369" alt="71611786-e1518d00-2b69-11ea-9861-e8634cc748aa" src="https://user-images.githubusercontent.com/58065821/81468649-76dae880-91fe-11ea-8214-ea1de0e2a485.png">
 I'm using mac OS in my home & office both. In my  home mac OS version is (mac OS high Sierra. FontForge works with it well. But my office computer OS is CATALINA. FontForge doesn't work with it. (cant open file, cant save a file)  what is the issue..? That means, Doesn't FontForge  work with mac OS - CATALINA ? I have the latest version of FontForge (14-03-2020 update) in both computer... My problem is Fontforge doesn't support with Catalina.

**Comment by skef** [comment]
@LalithArt There's probably not going to be a fix for this anytime very soon so for now we recommend looking through the various suggested workarounds (including the links to the GIMP and Inkscape issues above) for one that might work for you.

**Comment by MaddTheSane** [comment]
I think part of the issue is that FontForge uses a custom open/save panel than the OS's, meaning it doesn't ask the OS to ask for permission.

**Comment by Lizarrd9** [comment]
GIMP was a dead-end, the saving problem is fixed now with the latest update. But, I did get it to work on my end, by saving to my Dropbox folder or my Google drive folder. If you create a new folder in your user folder, you can save it there as well.

**Comment by LalithArt** [comment]
<<<*If you create a new folder in your user folder, you can save it there
as well*.>>>
This is superb. I tried. It works nicely. Now I can work with Catalina
version.

Thank you very much.


*----------------------------------------------------*
*Lalith Rathnayake*
*Artist | Type Designer*
*Colombo, Sri Lanka*
*M} +9477 748 7107*
*FB} **www.fb.com/LalithRathnayakeArts
<http://www.facebook.com/LalithRathnayakeArts>*
*W} *
*www.behance.net/lalithrathnayake <http://www.behance.net/lalithrathnayake>*

**Comment by ancestral** [comment]
FYI, [it would appear that GIMP has had a fix since last September](https://www.gimp.org/news/2019/10/31/gimp-2-10-14-released/), [Krita is now notarized](https://krita.org/en/item/first-notarized-macos-build-of-krita/) and [Inkscape is notarized, too.](https://inkscape.org/release/inkscape-1.0/)

Also, just in case anyone is curious, giving Fontforge full disk access in System Preferences does not resolve this issue.

**Comment by ctrlcctrlv** [comment]
@ancestral You are welcome to pay for the key, notarize FontForge, and we can collaborate on getting your notarized binary uploaded in time for the next release.

Is that something you are interested in doing?

**Comment by skef** [comment]
@jtanx has a comment earlier indicating the problem stems from the init script aspect of the startup path. Signing may also work if the infrastructure is more forgiving of signed content but I was under the impression we were going to try the startup fix first.

**Comment by ctrlcctrlv** [comment]
Oh, @skef, thanks for that reminder. I remember reading that comment now. I figured as @ancestral mentioned notarizing it was required.

**Comment by ancestral** [comment]
I don’t know if notarization is required. It might be?

Earlier in the thread there was mention that three other big open source projects also had permissions issues. I was just mentioning all of them seem to have resolved it, and at least two of them indicated they had notarized their apps. Not sure if GIMP did also, or if they found a different fix.

**Comment by tibetty** [comment]
> Maybe I found a workaround to make FontForge work again:
> 
> 1. Find out FontForge in your Application folder
> 2. Right click on the icon to trigger context menu, click Show Package Contents
> 3. Go into `Contents/Resources/opt/local/bin/fontforge` and double click to run it on command line.

For me, it works by following your instruction!  Many thanks, dude!

**Comment by aleksiy805** [comment]
It's work for me https://github.com/fontforge/fontforge/issues/2474#issuecomment-139686912

**Comment by JeyBailey** [comment]
Can't anyone with an Apple Developer Account notarize an application?  Perhaps the member/contributor(s) that signed those projects would be willing to do so for FontForge?  I believe Apple would provide a free Dev account to the parent foundation or entity, if it's non-profit, to accomplish this.

https://developer.apple.com/support/membership-fee-waiver/
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by teenageninja** [comment]
System Preferences app > Security & Privacy > Privacy > Full Disk Access > "+" button (and enter admin pass) > select an FontForge app from the list. It works for me.

**Comment by ctrlcctrlv** [comment]
@JeyBailey Thanks for your comment. Currently, given the lack of movement on this issue, it seems no active contributor has either a Mac or the time to fill out Apple's bureaucratic forms. Also, I don't want to get another project in trouble, who probably went to not inconsiderable expense and time to fill out the forms, by sharing their keys, which I doubt is allowed by Apple. However, should anyone find the time, your information is helpful.

**Comment by valentinefreeman** [comment]
Donated to download this — would have loved a mention near the donate/download blurb that it's impossible to open on Mac at this time.... Can I get my donation back?

**Comment by ancestral** [comment]
I think what needs to happen is the project should court a Mac developer with some experience, and consider raising or redirecting funds for a developer account and get notarized.

Whether people like it or not, operating systems are introducing tighter security, and this means some things require extra steps, and sometimes extra money. These kinds of things is _exactly_ where donated funds should go — to make the apps available on more platforms.

**Comment by frank-trampe** [comment]
If you have donated and want your money back (which is totally understandable if you can't run it), please request a refund through PayPal, and we will get it processed.

I agree with @ancestral about the need to fix this and the need for a Mac developer, but it's unfortunately a super tight job market. Companies with money are struggling to find engineers, and we don't have much money (about $2,000 in donations per year, I think).

**Comment by ctrlcctrlv** [comment]
We could consider documenting the issue. I opened https://github.com/fontforge/fontforge.github.io/issues/165. Feel free to commen there.

@frank-trampe is right about how you can get your donation back I am sure, but he is more diplomatic than me when it comes to whether you _should_ get your donation back. No, you should not. This is a free software project, and a workaround exists for Mac users. This is not a product that you bought (it's not a product at all). Did you donate enough to cover the cost of a recent enough Mac and a few hours of time? No? Then why should your single donation change this? You should view it as a contribution to the overall fund, which, if it ever reaches high enough, will see this issue addressed.

Donating to free software is admirable, using your donation as a rhetorical device is not.

**Comment by JeyBailey** [comment]
The issue is that I think the developer account used to sign it needs to be
consistent, and owned/managed by the host or sponsor organization for the
app.  I could probably sign it, but that would stifle future development as
future builds will need to be signed along the way.  I believe you can get
the account for free to do it, it's just that the account should be
owned/managed by the primary host/manager of the app.  You do need a Mac to
do it, but there wouldn't be a Mac version if someone didn't already build
it on a Mac, so there must be someone there that has done that.  If the
host gets the account and wants to share that with me (change the pw
after?) I would be happy to go through the actual signing of the app for
the group for now.  Apple will only get more stringent in their security
practices, so this isn't something likely to go away.

**Comment by jtanx** [comment]
My earlier comment regarding the init script remains valid - the fact that the actual process is launched by the script means that gatekeeper will only prompt for access made by the script itself, and will deny + not prompt to allow access for the subprocess.

The workaround above executes the actual FF binary directly which is why it works. If the init could be modified to directly execute the binary then that's one less problem to worry about, but it still remains that the startup procedure is a complete mess.

> there wouldn't be a Mac version if someone didn't already build
it on a Mac, so there must be someone there that has done that

This hasn't been true for many years, all the recent builds were done by Travis/Github Actions CI builds, and what mac changes have been made of late have all been through limited access in VMs.

At this point it is leaps and bounds easier to support Windows and Linux than it is to support Mac, which you can't even do for free - it's no wonder that support for this platform is lacklustre.

**Comment by andrew-c-duncan** [comment]
> Maybe I found a workaround to make FontForge work again:
> 
> 1. Find out FontForge in your Application folder
> 2. Right click on the icon to trigger context menu, click Show Package Contents
> 3. Go into `Contents/Resources/opt/local/bin/fontforge` and double click to run it on command line.

The solution by "alanwei0" works but is a bit of a pain having to hunt down 5 folder levels to start fontforge. Also when you do initiate fontforge it starts a terminal session. A modification that results in a more convenient solution is to create an apple script with Script Editor like:
"
try
	do shell script "/Applications/FontForge.app/Contents/MacOS/FontForge"
end try
"
and place it in the applications folder with the FontForge app. In my case, I saved it as "FontForge_Start.app" (so that it sat next to the FontForge app in Applications) and saved it as an .app, not a .scpt. To start FontForge, just click on FontForge_Start, and FontForge starts normally, no Terminal Window and you have access to your folders.

We now await FontForge to make the fix and have their software work with Mac OS as nicely as the folks from Inkscape and Gimp have.

**Comment by ctrlcctrlv** [comment]
@jtanx Given #4897, you may want to make sure that Big Sur still works post-#4827. If so, it's another reason to move forwards on #4840. If not, it means the wider issue of notarization needs re-examination.

**Comment by jtanx** [comment]
I'm actually stuck on catalina right now, but I don't foresee it being any different, if anyone wants to try just pick the latest mac bundle from the latest build

**Comment by ancestral** [comment]
@jtanx Thanks so much for your revised Info.plist! That certainly did the trick for me on macOS Monterey 12.1 with a M1 MacBook Pro. 

Here’s step-by-step instructions for anyone else out there, until we get a new binary release.

1. Find the FontForge app and right-click on the app and choose “Show Package Contents”.
2. Open “Contents”.
3. Edit the file “Info.plist” and replace it with the contents in this file: https://raw.githubusercontent.com/jtanx/fontforge/f1492c9374796abe798b7c00ae8ed7f939c246bd/osx/FontForge.app/Contents/Info.plist.in
4. Save the file.
5. Now we need to update the cache for LaunchServices. Open Terminal and type the following command: `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`

You will now be able to browse files from anywhere on your computer. If you did not grant Full Disk Access, that’s fine — macOS will now correctly ask you to grant FontForge permission to browse folders like Desktop, Documents, and Downloads as it comes up.

**Comment by ctrlcctrlv** [comment]
I'm reopening this until there's a new release. We shouldn't be considering this closed even if it's closed in `master` due to how many users dealing with this—I think serious issues should remain open until they are fixed _in a release_.

**Comment by dimitre** [comment]
I've just downloaded the binary and in fact I can access folders outside of the Desktop / Downloads / Documents
the workaround of invoking directly /Applications/FontForge.app/Contents/MacOS/FontForge works too.

In macOs if you name a .sh file as a .command extension and execution attributes you can double click and run directly from finder
```sh
#!/bin/bash
/Applications/FontForge.app/Contents/MacOS/FontForge
```

**Comment by andrew-c-duncan** [comment]
@ancestral - This procedure works a treat. Also running Monterey 12.1, MacBook Pro 2017.

**Comment by jtanx** [comment]
Instead of all these hacks, can someone please just confirm that the latest CI build e.g. https://github.com/fontforge/fontforge/suites/5010343124/artifacts/147188135 works

**Comment by dimitre** [comment]
> Instead of all these hacks, can someone please just confirm that the latest CI build e.g. https://github.com/fontforge/fontforge/suites/5010343124/artifacts/147188135 works

confirmed, working great here. it actually asks permission when you try to access Desktop for the first time and includes it on system preferences
<img width="345" alt="Screen Shot 2022-02-01 at 06 46 16" src="https://user-images.githubusercontent.com/58289/151946138-5e239275-44c7-4d47-b94d-57b437a880bc.png">

**Comment by jtanx** [comment]
Awesome, thanks for confirming!

**Comment by dimitre** [comment]
@jtanx quick question: How to get the CI build links? 
it would be great to have intermediate versions or tags, once it is not so easy to build from source as it once was.

**Comment by ctrlcctrlv** [comment]
@dimitre Sorry, different repository, but the instructions are identical. GitHub's UI is terrible, I get this question routinely.

https://github.com/MFEK/glif/wiki/Getting-the-latest-artifact

**Comment by robohack** [comment]
On macOS Montery 12.1 if one _Control_-click's on the app icon, e.g. in the `/Applications` folder and then selects "Open" from the context menu, the warning popup will now allow the app to be opened with the appearance of a new "Open" button in the warning panel.

At least that works for me.

Search for _"Open a Mac app from an unidentified developer"_ in the system help (also note how the mentioned "Open anyway" Security&Privacy preference may or may not appear depending on your actions and timing).

**Comment by jtanx** [comment]
https://github.com/fontforge/fontforge/releases/tag/20220308

**Comment by ctrlcctrlv** [comment]
The MFEK Foundation, Inc. is paying @subject38 to code sign MFEKglif (at least) and hopefully write a script I can use to codesign all MFEK binaries.

Cf. [MFEK Foundation Grant №2, Series of 2022](https://mfek.org/foundation/)

I applied for a “D-U-N-S number” as part of this effort, which is one of the absurdities Apple requires. Probably the first of many.

As I wrote on Twitter, if we get a certificate from Apple, [FontForge can certainly borrow it](https://twitter.com/MFEKglif/status/1516213690000941059) and I wouldn't mind sending it to either Frank or Jeremy. Anything that makes using free software easier is within scope so I see no conflict.

Skef knows a whole lot about Apple stuff, he also helped me fix a few Mac bugs in MFEKglif, so I'd say it's _likely_ we will get a certificate finally.

**Comment by zwocrcy** [comment]
> @jtanx Thanks so much for your revised Info.plist! That certainly did the trick for me on macOS Monterey 12.1 with a M1 MacBook Pro.
> 
> Here’s step-by-step instructions for anyone else out there, until we get a new binary release.
> 
> 1. Find the FontForge app and right-click on the app and choose “Show Package Contents”.
> 2. Open “Contents”.
> 3. Edit the file “Info.plist” and replace it with the contents in this file: https://raw.githubusercontent.com/jtanx/fontforge/f1492c9374796abe798b7c00ae8ed7f939c246bd/osx/FontForge.app/Contents/Info.plist.in
> 4. Save the file.
> 5. Now we need to update the cache for LaunchServices. Open Terminal and type the following command: `/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user`
> 
> You will now be able to browse files from anywhere on your computer. If you did not grant Full Disk Access, that’s fine — macOS will now correctly ask you to grant FontForge permission to browse folders like Desktop, Documents, and Downloads as it comes up.

Does this also work for Monterey 12.3.1 with Intel?

**Comment by ancestral** [comment]
> @ancestral Does this also work for Monterey 12.3.1 with Intel?

Yes.

But a new release came out since January, so you could just download FontForge over again and you’ll be fine.

**Comment by ctrlcctrlv** [comment]
Reopening, at least for now. @jtanx, you know more about Mac. Is this error equal to this issue or not?

![image](https://user-images.githubusercontent.com/838783/189513789-22fa4cde-6d25-4371-a4b4-728564172e72.png)

**Comment by jtanx** [comment]
Not quite the same, that latest screenshot is more just because we aren't notifying/signing the bundle

**Comment by jtanx** [comment]
Original issue is fixed.

**Comment by Gatada** [comment]
This was new to me as well.

However, the security alert has a question mark, and by pressing it I was presented with the solution/workaround (MacOS 15.6.1):

1. In Settings go to Security & Privacy
2. Find the Security section where you will see the option to open the blocked software.

See screenshot below if this wasn't clear.

<img width="790" height="281" alt="Image" src="https://github.com/user-attachments/assets/a0c7f25a-7864-41da-996b-e68a5c390dba" />
