### ISSUE TITLE
Dialect & Indigenous fonts if there is a correct way?

### ISSUE THREAD

**Issue by tyoc213** [fontforge/fontforge#4083]
I have two cases (two different native languages): one of them works as a normal abc, but some of the sane sounds have different figures; the other one is a silabary and a mix of vocals and consonants (but different figure as in hiragana)

* I have watched some pngs that say there are 1 to 4 drawings for the same sound a.
* Watching another drawing it says that is something like hiragana/katakana with vowels, consonants and a table like that.

So my question is... I just start drawing them in the places of A, B, C for lower case and uppercase... or should I first choose the code point of the character? becuse as far as I know, there is no codes defined for those symbols because they are indigenous langs... so, how to approach this? (I gess for start it is ok to have only the drawings of each char??)

**Comment by ctrlcctrlv** [comment]
What language

**Comment by FloraCanou** [comment]
Check Unicode to find if your script is really not included. If so, use Private Use Area before they include it. Make a custom IME to input it.

**Comment by tyoc213** [comment]
The lenguages are aztec which seems to have **U+15C00 to U+15FFF (tentative)[1]** and purepecha which doesnt seem to have one even tentative.

@FloraCanou I will look in to this for purepecha, but if you have a short explanation of what do I need to click, it would be great :), thanks for the pointers.

**Comment by tyoc213** [comment]
I guess, it is something like this? https://github.com/fontforge/fontforge/issues/615#issuecomment-20498736 and this one https://github.com/fontforge/fontforge/issues/3318#issuecomment-405171931

I mean I need to reencode in `ISO-10646-1` full or BMP and use the ranges 

> Three private use areas are defined: one in the Basic Multilingual Plane (U+E000–U+F8FF), and one each in, and nearly covering, planes 15 and 16 (U+F0000–U+FFFFD, U+100000–U+10FFFD). 

Well, I only counted 2 from the wikipedia... or they are refering to this ranges: U+E000–U+F8FF, U+F0000–U+FFFFD, U+100000–U+10FFFD... so 3 in total?

Anyway, I didnt get what you mean by `Make custom IME to input it`??

**Comment by ctrlcctrlv** [comment]
Do they look something like Mayan hieroglyphs?

Anyway, what I would recommend for your case, after thinking about it a little, is making a new font, then hitting Encoding&rarr;Compact (which will clear everything). Then, press Encoding&rarr;Add Encoding Slots, enter how many you need, then draw your glyphs. Then, Element&rarr;Glyph Info for each glyph, and give it an encoding. If the Unicode Consortium has defined a tenative encoding outside of PUA space, use that; other wise, use PUA space.

This will mean you don't have to scroll a lot, past tons of stuff not relevant to you.

Never mind about the IME. That has nothing to do with FontForge.

**Comment by ctrlcctrlv** [comment]
(By the way, Add Encoding Slots can be used multiple times, if you don't know yet how many glyphs you need.)

**Comment by ctrlcctrlv** [comment]
By the way, you are going to want to give the glyphs _good, descriptive names_, not NameMe.0, et cetera, so that if you need to re-encode your font at a later date as Unicode shifts things, you can do so easily. This will also make your font's glyphs easy to type in Metrics View.

**Comment by tyoc213** [comment]
Thanks for all the info, now I know a little more and maybe latter I will post some links to what IME is.

**Comment by ctrlcctrlv** [comment]
Closing as answered, stale question.
