### ISSUE TITLE
Request: Skip line by line scrolling for long scrolls

### ISSUE THREAD

**Issue by daT4v1s** [fontforge/fontforge#4092]
### When reporting a bug/issue:
- [x] The FontForge 2019-08aug-01 wine on linux ubuntu LTS (compiling & appimage didint wor)
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 

open a large unicode font files (lots of glyphs)
when scrolling for long distance it can be slow, with large delay between 
scroll-input, drawing and display,
e.g. scroll then not move mouse , it keeps on moving,

apparently it might scroll also on a grid-line-by line manner,

for overly-long distances, could it be forced that the scroll interval be at least one vertical page height,
thus less frames to draw from scroll-position A to B

**Comment by ctrlcctrlv** [comment]
Running via Wine on Linux is not supported. This bug is invalid, as are any others you find on that installation and fail to verify on a supported installation.

**Comment by daT4v1s** [comment]
the slow scrolling also affects linux native build if it works, 
but since inaccurate scroll position is probably undesirable,
going back to line-by-line scrolling after rendering catches up to input 
or a pause in scrolling is detected

**Comment by ctrlcctrlv** [comment]
In that case this is most likely a duplicate of #4063.
