### ISSUE TITLE
Dies after change weight

### ISSUE THREAD

**Issue by arturrataj** [fontforge/fontforge#4095]
Load the attached font, select the letter, change weight: remove anything in "fuzz", embolden by 9.

[test.zip](https://github.com/fontforge/fontforge/files/4043010/test.zip)

Based on sources from 2019-12-24 15:30 UTC-ML-D-GDK3.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): Winding number did not return to 0 when y=554,842
Internal Error (overlap): Winding number did not return to 0 when y=554,889
Internal Error (overlap): Winding number did not return to 0 when y=554,842
Internal Error (overlap): Winding number did not return to 0 when y=554,889
Internal Error (overlap): Winding number did not return to 0 when y=554,842
Internal Error (overlap): The start of the monotonic does not match that of the containing spline.
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

**Comment by skef** [comment]
Checking this with Valgrind there are a lot of these:

```
==17028== Invalid write of size 8
==17028==    at 0x4BEB943: SplineRefigure2 (splineorder2.c:1296)
==17028==    by 0x4BEBD92: SplineRefigure (splineorder2.c:1347)
==17028==    by 0x4C01F08: SSRemoveTiny (splineoverlap.c:3608)
==17028==    by 0x4C02DF4: SplineSetRemoveOverlap (splineoverlap.c:3962)
==17028==    by 0x4B5DF99: BoldSSStroke (scstyles.c:102)
==17028==    by 0x4B74AFD: SCEmbolden (scstyles.c:4065)
==17028==    by 0x4B75DB9: FVEmbolden (scstyles.c:4325)
==17028==    by 0x3995E8: Embolden_OK (scstylesui.c:1876)
==17028==    by 0x3F694C: GButtonInvoked (gbuttons.c:257)
==17028==    by 0x3F78C3: gbutton_mouse (gbuttons.c:485)
==17028==    by 0x401F81: _GWidget_Container_eh (gcontainer.c:304)
==17028==    by 0x403E01: _GWidget_TopLevel_eh (gcontainer.c:747)
==17028==  Address 0xb634588 is 24 bytes inside a block of size 96 free'd
==17028==    at 0x48399AB: free (vg_replace_malloc.c:530)
==17028==    by 0x4C327B4: SplineFree (splineutil.c:161)
==17028==    by 0x4C32AB7: SplinePointsFree (splineutil.c:228)
==17028==    by 0x4C32B76: SplinePointListFree (splineutil.c:248)
==17028==    by 0x4C01766: SSRemoveTiny (splineoverlap.c:3502)
==17028==    by 0x4C02DF4: SplineSetRemoveOverlap (splineoverlap.c:3962)
==17028==    by 0x4B5DF99: BoldSSStroke (scstyles.c:102)
==17028==    by 0x4B74AFD: SCEmbolden (scstyles.c:4065)
==17028==    by 0x4B75DB9: FVEmbolden (scstyles.c:4325)
==17028==    by 0x3995E8: Embolden_OK (scstylesui.c:1876)
==17028==    by 0x3F694C: GButtonInvoked (gbuttons.c:257)
==17028==    by 0x3F78C3: gbutton_mouse (gbuttons.c:485)
==17028==  Block was alloc'd at
==17028==    at 0x483AB65: calloc (vg_replace_malloc.c:752)
==17028==    by 0x4BE87FE: AlreadyQuadraticCheck (splineorder2.c:718)
==17028==    by 0x4BE8F2A: ttfApprox (splineorder2.c:776)
==17028==    by 0x4BE97E9: SSttfApprox (splineorder2.c:890)
==17028==    by 0x4BE99CF: SplineSetsTTFApprox (splineorder2.c:919)
==17028==    by 0x4BEA6C9: SplineSetsConvertOrder (splineorder2.c:1044)
==17028==    by 0x4C318A2: SplineSet_Stroke (splinestroke.c:1915)
==17028==    by 0x4C31916: SplineSets_Stroke (splinestroke.c:1929)
==17028==    by 0x4C32038: SplineSetStroke (splinestroke.c:2026)
==17028==    by 0x4B5DF57: BoldSSStroke (scstyles.c:100)
==17028==    by 0x4B74AFD: SCEmbolden (scstyles.c:4065)
==17028==    by 0x4B75DB9: FVEmbolden (scstyles.c:4325)
```

So the Expand Stroke part of the algorithm is post-converting to Quadratic, and then (probably) Remove Overlap is using some memory that it freed. (The alternative being that the frees are from a different, earlier run.)
