### ISSUE TITLE
Font weight names in Python API?

### ISSUE THREAD

**Issue by jorins** [fontforge/fontforge#4096]
I'm working on a build system for a mostly programatically generated font. Included in this process is trying to compile a font file for each weight according to the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#Common_weight_name_mapping).

My code looks like something like this
```
[...]

weights = {
    100: 'Thin',
    200: 'Extra Light',
    300: 'Light',
    400: 'Regular',
    500: 'Medium',
    600: 'Demi Bold',
    700: 'Bold',
    800: 'Extra Bold',
    900: 'Black',
    950: 'Extra Black',
}

[...]

for weight in weights:
    font = fontforge.font()
    font.encoding = 'UnicodeFull'
    font.familyname = 'My Font'
    font.fullname = f'My Font {weights[weight]}'
    font.weight = weights[weight]

[...]
```

This seems to work to an extent. When trying to add the generated .ttf fonts through KDE's standard font manager `kfontview`, I am shown the following names on the variations

```
100: Thin
200: Extra Light
300: Extra Light
400: Regular
500: Medium
600: Demi Bold
700: Bold
800: Bold
900: Black
950: Black
```

This causes conflict between the ones that share variation names and they can thus not be installed simultaneously. In the [docs](https://fontforge.org/python.html), the `weight` member is just described as `PostScript font weight string`. Could anyone give me some pointers?

Thanks in advance :)

**Comment by ctrlcctrlv** [comment]
What about the PostScript name of the font? Are you setting that too? It's important to many systems that that be unique.

Could the OS/2 table and its weights have something to do with it?

I will say that this stuff is extremely platform dependent no matter what you do.

**Comment by jorins** [comment]
I tried adding `font.fontname = f'My Font {weights[weight]}'`, but that didn't change anything. The docs declare both `font.fontname` and `font.fullname` as `PostScript font name`, though `font.fontname` has the added note `Note that in a CID keyed font this will be the name of the current subfont. Use cidfontname for the name of the font as a whole.`

What did work was setting `font.os2_weight = weight`. This doesn't support `Extra Black` as suggested by MDN, but I can live with that. Thank you for your help!
