### ISSUE TITLE
Chebyshev polynomial support

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4106]
Sometime in the not-too-far-future there are some likely projects that will include computations that lack closed-form solutions and have other tricky aspects. This is a wide-open area in the general case, but I've been doing enough reading on some specifics -- including Bezier arc-length reparameterization and elliptical arc length (don't ask) -- to determine that Chebychev polynomial expansions are a good approach to many of these problems.

I therefore want to ask now about the best way of adding Chebychev support. There are various options:

1. Write a from-scratch implementation based on common references. 
2. Adapt an existing BSD/MIT/etc-licensed implementation 
3. Add a GPL-licensed C library as a dependency
4. Add a BSD/MIT/etc-licensed C++ library as a dependency, then implement what is needed in C++ with top-level C wrappers. 

The main GPL C library is [GSL](https://www.gnu.org/software/gsl/). I haven't run across a more permissively licensed C library, and if there is one it's probably obscure enough to be an annoying dependency. Boost has [some support](https://www.boost.org/doc/libs/1_66_0/libs/math/doc/html/math_toolkit/sf_poly/chebyshev.html), has a very permissive license, and is probably already available in all the relevant distros. 

There's not much to a [basic implementation](https://people.sc.fsu.edu/~jburkardt/c_src/chebyshev/chebyshev.c) (this one is LGPL). However, the cost of writing, testing, and maintaining even a small new subsystem isn't zero. 

What are people's thoughts?

**Comment by jtanx** [comment]
My preference would not be to pull in gsl if we can avoid it, as that definitely would force FF as a whole to be GPL licensed.

Boost is also a bit of a beast to pull in, so I'd prefer not bringing it in without a strong reason to do so. 

Are we sure that this absolutely must be done with Chebyshev polynomials / more details on why this specifically is needed?

**Comment by frank-trampe** [comment]
I echo that caution about the GPL entrapment and am similarly curious, if you're willing to share at this stage, what adventures you have in mind.

**Comment by skef** [comment]
Is there a reason we need to have the "is this worth it" discussion as opposed to just saying that option 1 makes the most sense if and when it comes down to it?

@ctrlcctrlv favors adding something [PowerStroke](https://wiki.inkscape.org/wiki/index.php/PowerStroke)-like (although it would not "live"). This kind of thing, and dashing and so forth, requires robust two-way length support (determining how long a spline is at t, and determining the t that corresponds to a given length). When one needs to do this sort of thing and there isn't a closed-form integral or derivative, a polynomial expansion is a natural choice, as it tends to have a more efficient computation/accuracy trade-off than, say, an iterative linear segment approximation. (The trade-off being how  far "down" the expansion one goes.) Custom iterative solutions also need to be rewritten for different uses, with rounding problems handled differently, while expansions can often be general (e.g. you can either use the expansion directly or root-find with a Newton solver for a derivative).

**Comment by ctrlcctrlv** [comment]
Dashed lines are also required to fully support the SVG standard. https://www.w3.org/TR/svg-strokes/#StrokeDashing

**Comment by skef** [comment]
(Actually, when it comes down to it it's most likely I would follow option 2, probably with Boost: Copy the relevant sources into a single file, adapt the code into vanilla C from C++, put a note to that effect at the top leaving a copy of the Boost license (which is certainly permissive enough for this purpose) and a note in the LICENSE.txt file about the code's origin.)

**Comment by skef** [comment]
@ctrlcctrlv When it comes down to it FontForge has SVG Import/Export mostly to support moving contours back and forth between tools. While in theory someone could specify a dashed object in Inkscape (or whatever) and expect it to come through to FontForge that way, it's not something we necessarily need to support. 

How and whether FontForge ever offers full SVG2-level SVG font support is a different and more difficult question.

**Comment by ctrlcctrlv** [comment]
The idea of converting Boost code to C99 sounds optimal to me, and is in keeping with the general policy of vendorization.

**Comment by skef** [comment]
I got my answer for this and now we can cross the bridge if and when we come to it.
