### ISSUE TITLE
Warning: Left contour did not close

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4109]
This bug is under the `skef:arcs` branch but doesn't use arc joins so I doubt that's the problem. Even if it is, @skef should know about it.

![2020-01-27-154310_3589x1750_scrot](https://user-images.githubusercontent.com/838783/73157428-e7f90300-411b-11ea-855b-790c432c2d69.png)

# File: [S2.sfd](https://github.com/fontforge/fontforge/files/4115968/S2.zip)

**Comment by skef** [comment]
Ugh. This is another of those floating point cut-off problems. (I have to admit I haven't done a whole lot of 200+ diameter testing.) I should probably add a "max-width" parameter to the `strokecontext` with the max of width and height for a custom nib, and then soften some of the cut-offs by that value/10. 

BTW these are easy enough to work around by manually closing the contour and then running Remove Overlap, etc. as desired.
