### ISSUE TITLE
Question/Feature Request: guideline colours?

### ISSUE THREAD

**Issue by spiralbit** [fontforge/fontforge#4112]
I can create a guideline by clicking and dragging from the rulers, but the lines are solid black.  If you load an existing Adobe font (for example) the guidelines appear as a dotted blue line, which is much more appealing as its different to the black spline lines.  Is it possible to draw dotted blue guidelines?

FF 20190801 on iMac running OSX 10.13.6 and XQuartz 2.7.11.

Thanks,
David.

**Comment by skef** [comment]
In FontForge guidelines are (among the) objects in the Guideline Layer, which is common to all the glyphs in the font. I don't think there is a way to pick the colors of guidelines individually but you can pick the color of the whole layer by going to "File -> X Resource Editor -> Outline View 2" and changing the value of  "Guide Layer color".

As far as dashing goes, I don't think that is currently an option.

**Comment by skef** [comment]
Oh, I only know a little about this but I believe the dashed lines are Blue Values, or blue-value-related. Those are set in "Element -> Font Info -> PS Private". See https://github.com/fontforge/fontforge/wiki/How-TT-Hinting-Works for a bit more info.

**Comment by ctrlcctrlv** [comment]
Yeah, for sure the dashed lines are hinting related, not guidelines. And shouldn't be used as guidelines, as it will confuse the rasterizer.

**Comment by ctrlcctrlv** [comment]
This is possibly related to #4078, by the way. While working on color fonts there's no reason I can't extend the support to the Guide layer, at least that I can think of.

**Comment by skef** [comment]
@ctrlcctrlv Don't COLR fonts have one color per layer? Seems like also supporting within-layer color differences would require a different datastructure.

**Comment by ctrlcctrlv** [comment]
You are indeed correct @skef. My understanding of this request is that he wanted to have a single blue guideline. Multiple guidelines of different colors are not within the scope of the COLR/CPAL work.

**Comment by spiralbit** [comment]
> File -> X Resource Editor -> Outline View 2" and changing the value of "Guide Layer color

Thanks for your reply @skef, but I tried that and it doesn't seem to work - existing and newly created guides are still black.

**Comment by skef** [comment]
When I fooled around with the control I had to close the CharView and open it again, but it did work afterward.

Note that X Resource File changes are not "remembered" unless you save and load them from somewhere. See "File -> Preferences -> Generic -> ResourceFile". 

If you wind up able to close all your CharViews, open a new one with a guidelayer, and it's still grey-ish even though when you open the X Resources dialog the Guide Layer color is changed the way you wanted it, I'll try to work with you more to figure out what's wrong.

**Comment by ctrlcctrlv** [comment]
Honestly, it might not be too much of a problem to use the BlueValues as a type of guideline, so long as you don't generate your font with hints. :man_shrugging:

**Comment by spiralbit** [comment]
> When I fooled around with the control I had to close the CharView and open it again, but it did work afterward.
> 
> Note that X Resource File changes are not "remembered" unless you save and load them from somewhere. See "File -> Preferences -> Generic -> ResourceFile".
> 
> If you wind up able to close all your CharViews, open a new one with a guidelayer, and it's still grey-ish even though when you open the X Resources dialog the Guide Layer color is changed the way you wanted it, I'll try to work with you more to figure out what's wrong.

Thanks @skef, reopening the glyph window showed they were blue.  I'll save the prefs into the resource file.
