### ISSUE TITLE
Python-based UI interface improvements

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4147]
It seems like the project may be on the cusp of making more regular use of python scripts and potential user contributions. So I think I'll look into extending the interactive aspects of the scripting interface a bit more, in some ways we've already discussed in past issues and in other ways that are new (and easier). Here is a list:

1. [ ] Do the discovery thing discussed in #3663 so that you can install a python package in the normal way and have it add menu items. (Skip enable/disable for now, add that if and when people ask for it.)
2. [ ] Modify `registerMenuItem` so that if the `menu-function` argument is the string "separator" the "menu-name' item is replaced with a menu separator. 
3. [ ] Modify `registerMenuItem` so that if the `menu-function` argument is the string "link" the "data" field is treated as a URL, which is opened when the item is selected from the menu. (For good measure add an interface to the `fontforge` object for opening a web page in other contexts.) 
4. [ ] If possible, re-enable the `shortcut-string` (now more or less ineffectual) as a "suggestion", so that if the specified hotkey is not already "taken" it is enabled on that item. (The tricky thing here is whether one can tell that a hotkey is taken. I don't remember.) Junk the current syntax in favor of the hotkey file syntax (if they are different). Don't require repeating the name in the shortcut string. 
5. [ ] Write a short style guide, either in the docs or on the wiki (seems like docs would be preferable -- not many people know about the wiki), for scripts-for-other-people. Basically: encourage a single top-level menu item for each contribution with multiple sub-items. Then at the bottom a separator and a link to an "about" page. Also some suggestions for hotkey suggestions. Include the basics of how to write one module that does different things in different contexts. 

Unless discovery is trickier than I expect this shouldn't add up to much work.

**Comment by skef** [comment]
@frank-trampe @jtanx @ctrlcctrlv @linusromer Are there other low-to-medium hanging fruit?

**Comment by skef** [comment]
Maybe the top-level of the "Tools" menu should have a different ordering. Right now it and it sub-menus are in "first-registered first" order. That makes sense if you expect the scripts to all be written by the end-user, or a combination of a small number of curated scripts (like the old `contrib`) and the user content. It makes less sense if there is discovery. 

Alphabetical could be clunky but could be fine given the style guide. However, users with more than one existing script may hate the change. Maybe it should be alphabetical for everything outside of the *user's* python directory (as opposed to the shared one) and then a separator and then everything in that directory in registration order.

**Comment by skef** [comment]
@davelab6 Do you have any thoughts on this?

**Comment by skef** [comment]
I filed #4148 to track the problem of and a potential solution for allowing user-contributed scripts to participate in a future configurable menu project.

Given that change my inclination is to punt on any short-term half measure. So: top-level Tools menu items continue to be added in "discovery order". If our efforts are very successful this could create a mess, but it will be a fixable mess and might precipitate a more general menu project (if that hasn't happened already). 

(To be clear, the "mess" is that a user might install a bunch of FontForge tools, possibly some for other reasons than menu extensions, but wind up with a bunch of menu items due to discovery" The user will neither be able to disable any of those items, nor will they be able to reorder them. The coarse ordering will be determined by our code, probably shared-contrib-dir stuff, followed by discovery, followed by a divider, followed by user-contrib-dir stuff. The fine ordering will be file-alphabetic for the contrib dirs and "whatever python does with discovery" for that stuff.)

**Comment by frank-trampe** [comment]
That status quo is okay, of course. But, so long as we do so carefully (non-spuriously), I think that it would be fine to try and to iterate other halfway solutions as seem appropriate.

**Comment by skef** [comment]
@frank-trampe I don't disagree, I just didn't come up with a good halfway solution that fits into the timeframe. Most solutions would require some kind of UI and gdraw makes new UI stuff very time-consuming.

An alphabetic solution doesn't really help for discovery because the user has no control. In the shared contrib dir we determine the order by picking filenames. In the user's they can influence the order by naming and renaming their files. For discovery you just exchange one arbitrary ordering for another.

**Comment by skef** [comment]
@jtanx If I'm remembering an earlier conversation right the primary reason we package our own python for the Windows version of FontForge, as opposed to using the Most Common Windows Python Implementation, was that using the latter would require compiling FontForge with Visual Studio. And the primary blocker of Visual Studio *was* autotools/`configure`.

Now that you've done all the CMake work, where does that possibility stand? If we're going to push "shared" python extensions (in contrast with stuff you write for yourself) as a basic feature it would be ideal if extensions with arbitrary dependencies work on all or almost all platforms. How much more work would it be to get to that point?

**Comment by jtanx** [comment]
It'd still be a fair long way off. To get it to truly compile with MSVC, you have to fix a fair amount of code that relies on gcc/mingw behaviour (iirc there are at least a couple of headers that are provided by mingw that do not exist in the msvc toolchain).

Not only that, but you have to compile all of Fontforge's dependencies with the same toolchain (of which, there are many).

You could perhaps get gcc to link to a difference C runtime  - i.e. it'd be nice if msys2/mingw-w64 linked against the ucrt, then everything would just work (touch wood). But as I understand ucrt support in mingw is pretty immature, and msys2 definitely doesn't use it. Again, going down this route, you need to compile *everything* yourself.

**Comment by ctrlcctrlv** [comment]
As I've said before, we should just pack `pip` and document that we do so and how to install dependencies using our packed `pip`.

**Comment by jtanx** [comment]
Unless you pack a whole msys2 distribution too with gcc, pip won't help you when you try to install an extension with C components (like numpy, pandas etc etc)

**Comment by ctrlcctrlv** [comment]
Really? What about wheels?

**Comment by jtanx** [comment]
Wheels are compiler specific. If you read the name of the wheel it'll have msvc in it.

**Comment by jtanx** [comment]
correction - the wheels on pypi are built against msvc and won't be usable by this version of python

**Comment by ctrlcctrlv** [comment]
Oh, drat. Sorry for the noise. Thanks @jtanx

**Comment by jtanx** [comment]
There is a third option - link against the official python libs and stick your head in the sand about the CRT differences and hope it works ;)

**Comment by ctrlcctrlv** [comment]
My head is already in the sand, and I am extremely accustomed to hoping things work, so that sounds like a good idea to me :-)

**Comment by skef** [comment]
Based on a little reading: If we:

1. Aren't doing and don't need any C++ stuff and 
2. (Somehow) ensure that everything external to our build that we need to link against is a shared library.

Isn't it likely to work? Static libraries pose the compiler compatibility problems you note, but that should all be sorted out for a dynamic library.

**Comment by jtanx** [comment]
Dynamic linking (which we currently do) or not, in the current situation if you tried to link to Python, FontForge would be using one C runtime (msvcrt.dll) while Python (let's just say Python 3) would be using another (MSVC version something, but basically to the ucrt). That's what can cause issues.

**Comment by skef** [comment]
So stuff like https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=vs-2019

**Comment by skef** [comment]
I guess we wait and hope that the recent mingw 7.0 UCRT stuff prompts more adoption by msys2.

**Comment by ctrlcctrlv** [comment]
Since you're active @skef, and the problem I'm having seems related:

How am I supposed to handle strings in my contrib script? We're not just going to leave them all untranslated, right? I do want them in the `po` files, right?

**Comment by skef** [comment]
No, not the `po` files -- python internationalization is covered in https://docs.python.org/3/library/i18n.html

**Comment by ctrlcctrlv** [comment]
How far are we with that in our project, though? We already support Crowdin and build `po` files...to me it seems natural to also have our existing Gettext stuff just work with `contrib` scripts too.

**Comment by skef** [comment]
No, that doesn't really make sense. The python API allows for arbitrary extensions, most of which won't be under our influence. Having our C code do localization on the strings passed into it only addresses a tiny part of the problem. Python has its own framework and that's what should be used for internationalization and localization.

**Comment by ctrlcctrlv** [comment]
Well what I'm trying to say is, it doesn't make sense for arbitrary extensions, but it does make sense for ones we distribute.

**Comment by skef** [comment]
I understand the scope, it still doesn't make sense. 

Here are a few reasons: We would have to build infrastructure to parse python to extract the source strings to be localized. Python string manipulation does not work the same way as C string manipulation, so any translator changing argument ordering would need to know which flavor of string they are changing. Strings or string fragments supplied by dependencies (from modules that may be internationalized themselves) wouldn't be extracted and therefore wouldn't be translated. 

I'm going to stop there.

**Comment by ctrlcctrlv** [comment]
So, should we make `po` files just for our Python scripts then? `contrib/po`? Then use the Python `gettext` module to work with those?

**Comment by skef** [comment]
There are some decisions about exactly what "contrib" is going to be that we haven't made yet. Setting those aside the basics are here and are similar to the C process: https://docs.python.org/3/library/gettext.html#internationalizing-your-programs-and-modules (See also https://www.mattlayman.com/blog/2015/i18n/ ) One marks the strings and extracts them with a python-specific extractor. 

The `po` files should be maintained on a per-contribution basis (whether it be one or multiple files). How the corresponding `.mo` files will be handled will depend on the eventual form of `contrib`. If it's just a directory then there will probably be a corresponding directory of contrib `.mo` files, and we'll have to figure out how we point the one toward the other. If `contrib` winds up being a module (which is less likely but still possible), or perhaps a dependency module (a module with no content that causes other modules to be installed) then the `.mo` files will go in the corresponding module and installed in a python-appropriate location.

**Comment by ctrlcctrlv** [comment]
Thanks @skef. Given the Windows issue, it just being a directory seems like what's most likely to happen, at least initially.

**Comment by skef** [comment]
As @jtanx notes in https://github.com/fontforge/fontforge/issues/4062#issuecomment-566444943 Python for the Windows version of FontForge comes with `pip`. We can install any module that doesn't have C/C++-only dependencies and any code with such dependencies won't work on Windows anyway.

**Comment by ctrlcctrlv** [comment]
Oh, OK. Well, I'm going to PR my #703 script today (God willing there are no more big problems with the APIs). So, for my sake, I hope we can figure out the shape of `contrib` sooner rather than later. Feel free to join IRC :)

**Comment by skef** [comment]
The python hotkey i18n situation is a bit of a mess. 

The strings passed into `registerMenuItem` can be unicode and the strings in a `GMenuItem` are also `unichar_t`. However, the hotkey infrastructure seems to assume:

1. Hotkeys will be specified by their untranslated strings (reasonable)
2. The untranslated strings will be ASCII or losslessly translatable to ASCII (less reasonable).
3. Therefore the hotkey files themselves can be ASCII

The problem comes when someone wants to add a hotkey for a Python API menu item that is already localized. Not sure what to do about this.

**Comment by jtanx** [comment]
Well to put it bluntly the 'new' hotkey system was a bit of a bodge job. Not that I'm going to be touching it though. 

I think the time and effort is better spent making the switch to another toolkit that provides hotkey and menus support out of the box (ie progressing the gtk work).

**Comment by skef** [comment]
@jtanx it has the benefit of being modest and the significant disadvantage that the choice of how to deal with a few corner cases precluded using hash tables, which is very frustrating.

I guess for now we can say "you can localize your menu items, or let users pick their own hotkeys, but not both. Sorry.".

**Comment by skef** [comment]
I really don't like this, because its counter-intuitive and hokey, but I think the best thing to do is maintain roughly the same convention as the pre-2012 "shortkey" system.

So, for example, consider this registration:
```
fontforge.registerMenuItem(mainFunc, enableFunc, ("some","data"), "Font", "My package name.My extension|Ctrl+Shift+R", "Mon nom de package", "Mon extension" )
```
Each shortcut string will consist of `[period-separated headings|][keytext]`. Either are optional but any list of headings must end in a "|". Periods cannot be escaped.  If the headings are absent the menu text can be used in the `hotkeys` file (as long as it is ASCII). The keytext specifies a hotkey "suggestion", which will be activated as long as 1) the user has not specified a different choice in `hotkeys` or 2) that combination is not already used for something else. 

(This is actually, sadly, a slight oversimplification of what I'm thinking of, but that's not important here.)

It's sad that I'm about to write a pathetic little "parser" for this but I guess that's where things are.

**Comment by jtanx** [comment]
Let's not corner ourselves into this, especially because this is a public facing function.

> I guess for now we can say "you can localize your menu items, or let users pick their own hotkeys, but not both. Sorry.".

This sounded reasonable, and leaves us room to remove that restriction if/when we improve hotkeys.

**Comment by skef** [comment]
@jtanx So your preference is to punt for the time being? I guess I'm OK with that. 

You seem more optimistic about radical medium-term change than I am, though. It's one thing to become GTK compatible and quite another to actually switch to using it. Won't all the random stuff like the FontView Search/Replace window take a long time to sort through?

**Comment by jtanx** [comment]
I'll admit, it's fairly likely that we'll be stuck with gdraw for many more years to come, especially as resource constrained as we are.

But at the same time, I reckon if you worked steadily towards it, it's not unfeasible. With regards to:

> Won't all the random stuff like the FontView Search/Replace window take a long time to sort through?

To be honest, all the bog standard dialogs would probably be the *first* thing ported because you can do them without custom widgets/custom ui code. The hard ones to get right are things like the fontview/charview/metricsview (i.e. all the main windows).

**Comment by skef** [comment]
I mentioned search/replace specifically because it's one of the non-standard ones -- it has two embedded charview-like subwindows and a menu.

**Comment by skef** [comment]
There's been more talk about the menu/hotkey problem over in #4148. Given a look at the GTK Action interface I'm converging on this proposal: 

1. Restore the basic `ID_String|Key_Combo` structure of the (currently ignored) shortcut string. 
2. As already discussed the `Key_Combo` will serve as a suggestion and be added as the shortcut if it isn't already used.
3. If the `ID_String` is present it serves as the token for adding custom hotkeys (e.g. "CharView.Menu.Tools.ID_String:"). 
4. If there is no `ID_String` the string formed by joining the menu names with periods will be used instead. 
5. Design docs will encourage the addition of an `ID_String` and offer advice on how to ensure it is unique. 
6. In future menu implementations the `ID_String` can serve as the Action ID string, with the same period-joined backup.
 
Given that the backup string is the same as the current hotkey specification string this all should be (largely) backward compatible. 

The main question this proposal raises is how/where to communicate the `ID_String` to the user so they can use it to change their own hotkeys. If menus can have tooltips that's probably the most straightforward answer.
