### ISSUE TITLE
Assure that all features are scriptable

### ISSUE THREAD

**Issue by ultrasquid** [fontforge/fontforge#415]
It's come to my attention that some features of Element>Change Glyph are not available to scripting, whether native or Python. This should be corrected. It should also be investigated whether any other feature of FontForge might not currently be scriptable, and those likewise be made accessible to scripting.

**Comment by skef** [comment]
We're unlikely to port every feature to the native scripting language at this point -- particularly the point-level interfaces. There are some features missing from Python but an audit seems unlikely to be useful, as there are many vague cases concerning what counts as a feature. Better to (try to) act on requests for API-level access as they are filed. 

This started out as a "change glyph is missing" issue. That was actually inaccurate WRT Python at the time -- it was there in the selection-interface as "genericGlyphChange" (although it was documented in the wrong section of the `font` object).  #4133 added a `glyph` method for convenience. 

Closing this metabug.
