### ISSUE TITLE
Address accuracy in stroked SVG (and PS?) imports

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4153]
The "1" numerals in the file referenced by #2421 don't import very well because they get "over-Simplified". That is due to the fact that the import process uses the default stroke accuracy value. 

There are two issues with that value. One is that a user might want it higher not considering transformations. The second is that SVGs have internal transformations and we don't correct for them. We should probably consider a preference value for the output accuracy in em-units and then track the scale up and down through the transformations to maintain output-relative accuracy.

**Comment by Bobbug** [comment]
I'm having issues with my importer being able to find any files? I get told i'm not authorized.

**Comment by skef** [comment]
@Bobbug we would need more information to even start to help: What version of the FontForge, what OS and version of OS, and preferably a screenshot of the error dialog and Open File dialog which may have more relevant info.
