### ISSUE TITLE
Curvatura.py should probably be a contrib script

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4157]
It's really cool, and if we're blessing my in production fix for #703, we may as well bless @linusromer's [Curvatura.py](https://github.com/linusromer/curvatura/blob/master/curvatura-doc.pdf) too.

CC: @davelab6, @eliheuer.

**Comment by skef** [comment]
The issue for this is #4062. Closing as duplicate.

**Comment by ctrlcctrlv** [comment]
I think this may have been too hastily closed. This issue isn't exactly a duplicate of #4062, but it could be said that #4062 is a blocker on this issue and should be figured out first, upon which time this is reopened. When deciding which scripts will be part of the default distribution, I don't think it's a problem to give each potential script its own issue.

**Comment by ctrlcctrlv** [comment]
Nevermind, I'm wrong. This is a duplicate of #3216, so it should remain closed for that reason.
