### ISSUE TITLE
Implementation to open "arbitrary" URLs

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4165]
Short version: I believe that `gio` is a hard dependency. Suppose we were to replace FontForge's stuff for opening URLs with `g_app_info_launch_default_for_uri()`. Would anybody object? 

Long Version:

As noted in #4147 It would be nice if python script contributors could open a web page with information about their contribution. This raises some issues.

The first issue is security. Going from only opening certain very specific URLs (having to do with the help system) to arbitrary URLs naturally raises some questions. However, this is probably, ultimately, a fake problem. If the access is via the python API the code that uses it is already python code executing as the user.

The python point raises the question: should there be an API at all or should contributors who want to just import `webbrowser` or whatever. That seems OK but not great, as URLs opened that way might use a different browser than URLs opened within FontForge. 

So let's say that we do want to add a method on the `fontforge` interface for opening URLs, and integrate that with `registerMenuItem` as outlined in #4147. That's simple enough but raises the issue of our currently hokey and outdated code for doing so in `uiutil.c` I find using gio's interface for that attractive but maybe others won't. 

Tagging @jtanx and @frank-trampe

**Comment by ctrlcctrlv** [comment]
I wasn't tagged but I think Python authors should just import `webbrowser`. When would that ever use a different browser than FontForge's internal system? Both rely on the default browser, don't they?

**Comment by skef** [comment]
@ctrlcctrlv Unless we replace the stuff at the start of `uiutils.c` there's only a chance we'll wind up with the default browser. And the `BROWSER` environment variable is not a standard thing. 

(I personally use `chromium`, which won't be found at all with the current code.)

**Comment by skef** [comment]
Incidentally if the question was just whether we should add an `openURL` method to the `fontforge` interface I would agree that was unnecessary. The question is whether we should add a feature to `registerMenuItem` so that script developers can easily add a link to their About or Help page without having to code an actual extra function for that. I think the latter is worth doing, and if we wind up doing it we might as well add the former at the same time.

**Comment by ctrlcctrlv** [comment]
Uhh but @skef `findbrowser` calls `xdg-open`, which, on Linux, is guaranteed to choose the same default browser other programs do.

**Comment by skef** [comment]
`xdg-open` is probably ubiquitous on Linux systems at this point but not all of our users are on Linux.

**Comment by jtanx** [comment]
I'm tending to agree with @ctrlcctrlv, `webbrowser` should be sufficient, and there shouldn't need to be any reason to expose something specific for this.

If it's different to what FF is opening then let's just fix FF and get rid of its nonstandard behaviour.

**Comment by skef** [comment]
Alright - we can recommend `webbrowser` in the documentation and cross the `uiutils.c` bridge when we come to it.
