### ISSUE TITLE
Frederick Brennan is a toxic individual, and should be banned!

### ISSUE THREAD

**Issue by KingAlfonso** [fontforge/fontforge#4166]
I represent the "Q" community who Brennan is OBSESSED with, constantly posting hate speech against us on Twitter when all we want is a better country for our children and communities.

Frederick Brennan is a well known internet troll and founder of 8chan. Since founding it he has been in perpetual warfare with its owners and has even gone to court in Philippines to delay them getting citizenship. He is a toxic personality and during his time 8chan was full of child porn. Now that he's gone there's not nearly as much of it. Is that a coincdence? I don't think so. NeonRevolt wrote an article exposing his degeneracy you might be interested in https://www.neonrevolt.com/2019/11/02/replatforming-8kun-and-the-tragedy-of-judasasschariots-hw_beat_that-bad-choices-qanon-greatawakening-neonrevolt/

You should not work w/ him and you should ban him. He clearly enjoys this little hobby and it would be a big blow to him to lose it. Might even make the little troller change his ways just to get it back! So I guess you all need to ask urselves what's more important, fonts or America? And besides if you ban him I will get the word out that you side with patriots and I'm sure that they will make way better fonts or code than Brennan ever did. And probably for free. There are thousands of us and one of him.

Do you guys know whose paying him b.t.w.?

**Comment by stonemirror** [comment]
Let me get this straight: you created a GitHub ID specifically to demand that someone be "banned" — from what, exactly? by whom? — on behalf of the "community" of people who believe their getting secret coded messages on a web site full of Nazis from a government agent about an "elite" gang of Satanist cannibal pedophile Democrats?

And you're trying to bribe the project with the prospect of "better fonts" if it "bans" him?

I'd ask whether you were insane, but it'd be rhetorical. Why don't you find a better hobby?

**Comment by KingAlfonso** [comment]
This individual is now trying to troll me on twitter. He is a doxer. If I revealed my true identity he would certainly dox me on his page. He might be related to John [Brennan], who knows if he would stop at doxing. The cabal is very dangerous and still has a lot of influence.

You don't know anything about "Q". Maybe you should do some research before you try to teach me.

**Comment by skef** [comment]
I was kind of stressed and angry about this until I started thinking about labels I could add to it and now I'm just amused. It definitely counts as a `metabug` so that goes on. 

I'll admit it: `someday-maybe` is pretty tempting! But not `bite-sized`; I'm not a monster.

**Comment by KingAlfonso** [comment]
Bite sized, ha ha. I agree, thats not appropriate because He's porked up too much to be considered bite sized.

Good to see Contributors are taking this important issue seriously! Dark to light!

**Comment by skef** [comment]
You have a very strange conception of seriousness.

**Comment by jtanx** [comment]
Take this issue elsewhere, we don't need this kind of drama. The contributions and discussions on FontForge by @ctrlcctrlv have remained strictly about FontForge and I have every faith it will remain that way.

**Comment by ctrlcctrlv** [comment]
Thanks @jtanx, I had been quietly trying to get someone to delete this issue. Since you're in the core group, I recommend you do that. However, neither @davelab6 nor @frank-trampe replied, both are busy or it's night in their timezone. I did not reply personally as I did not want to feed the troll.

**Comment by ctrlcctrlv** [comment]
And, I am very sorry that trolls of mine have found their way to this issue tracker. Clearly @KingAlfonso is deranged and his charges against me do not need a reply.
