### ISSUE TITLE
About permission

### ISSUE THREAD

**Issue by Ridwan-Natar** [fontforge/fontforge#4188]
Hi.Admin FontForge  I apologize in advance, I want to ask, can I sell my font design work, that I made using FontForge, for my commercial needs? example: like making font designs and so on using FontForge, then I sell it on online market websites like, microstock and so on, or selling font design works that I made using FontForge, in other places like offline,  Is this action permitted by FontForge?  I need a reply to that question, and for participation, I thank you.  

name: Ridwan 
Contact: Muhammadridwanpbs@gmail.com

**Comment by skef** [comment]
You absolutely can do so. The software itself has a mixture of licenses but none of these restrict how fonts you create using FontForge can be sold or otherwise distributed.

**Comment by Ridwan-Natar** [comment]
Thank you for your participation.
