### ISSUE TITLE
Advice/Confirmation on Import/Export options

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4198]
I'm in the process of adding some infrastructure to support import and export options. I'm opening this issue to summarize the preliminary design and, with luck, get some feedback. (I would wait for the PR but the release timing may call for earlier discussion.)

Note that this isn't about the specific options, just the infrastructure to support them. 

First, `fontforge/sd.h` will get these additions:

```
typedef struct importparams {
    int initialized;
    int shown_svg, shown_eps, shown_scale, show_always;

    /* omitted options */
} ImportParams;

typedef struct exportparams {
    int initialized;
    int shown_svg, show_always;

    /* omitted options */
} ExportParams;

extern void InitImportParams(ImportParams *ip);
extern ImportParams *ImportParamsState(void);
extern void InitExportParams(ExportParams *ep);
extern ExportParams *ExportParamsState(void);
```

The `Init` functions will set up the base-level defaults and the `State` functions will have `static` members that represent the in-dialog settings. 

`stroke_flags` in `uiinterface.h` will be replaced by
```
    void (*import_dlg)(ImportParams *ip);
    void (*export_dlg)(ExportParams *ep);
```
The non-UI versions of these will do nothing. The UI versions will display dialogs for setting the values.

The options dialogs will always be the same and have all the options for every import/export type. The chicken/egg problems are too annoying for format-specific dialogs and some options are multi-format anyway. 

Each dialog will be force-raised once for each new applicable filetype. (So, for example, if there is an SVG-specific setting and the dialog has not already been raised for that type, it will come up after hitting "OK" in the respective (Import or Export) file dialog.) The user can then choose whether to see the dialog on every import or not. The options dialog can also be raised with an "Options" button I'll add to the respective file dialogs. 

The native scripting interface will have a means of setting each option but will not interact with the `State` statics. Python will have a `system_options` keyword where string "set" uses the passed parameters to set the `State` values and string "use" takes the values from the `State`.

Finally, I'll add the `Param` pointer to all of the import functions and to the SVG output function (as there is only one SVG output option to start with). 

All of this is taking longer than I had hoped but with luck I'll have a draft tomorrow evening.

**Comment by skef** [comment]
@frank-trampe you might want to weigh in on this

**Comment by ctrlcctrlv** [comment]
Will this also expand to the Merge Feature Info dialog?

**Comment by skef** [comment]
No, this is just for glyph-level import export plus the equivalent parts of FVImportImages()

**Comment by skef** [comment]
I have now finished the vast majority of the plumbing, the new Options dialogs, and added buttons in the Import and Export file dialogs to open their respective Options dialogs. I've also finished the open-at-least-once-per-format logic. The Python and native APIs are mostly done. That's almost all of the plumbing. 

Still to go are odds and ends of plumbing and the actual option implementations. With luck all that will be done tomorrow around this time.

**Comment by frank-trampe** [comment]
Does this affect the "Generate" process in any way?

**Comment by skef** [comment]
For the time being I'm only adding one Export option for SVG and it isn't supposed to affect SVG font output, so no, not if I do the code right. 

The `open` (font) side should have roughly the same story. I want to fix the "eraser" problems (in a different, later PR) and some of that code is shared, but the Import options aren't supposed to affect `open`

**Comment by skef** [comment]
I'm close to done with the implementation -- just some fiddling with the export scripting interface left (it doesn't currently have flags). After that I'll have to deal with the docs and some automated tests. 

The starting options are:

```
typedef struct importparams {
    int correct_direction;      // PS
    int simplify;
    int clip;                   // SVG
    int erasers;                // PS
    int scale;                  // Misc
    bigreal accuracy_target;
    bigreal default_joinlimit;
} ImportParams;

typedef struct exportparams {
    int use_transform;          // SVG
} ExportParams;
```

`correct_direction` and `erasers` replace the existing PostScript flags. They are "hooked up" to the code but the implementation isn't fixed yet -- that can come in a later release if at all. 

`simplify`, `accuracy_target` and `default_joinlimit` influence the corresponding Expand Stroke parameters for SVG and PS imports. Note that as part of implementing the `accuracy_target` I now scale that value corresponding to the minimum entity transform dimension. This is so all stroked paths should have roughly the same final em-unit accuracy regardless of whether they are stroked small and then enlarged or stroked large and then shrunk.

`scale` is true by default and makes imported images and SVG files scale to the font dimensions. When set to false images are not scaled but placed with the top at the ascent line. SVGs are "flipped" to correct for the y-axis and also placed with the top at the ascent line. Maybe there's a better option worth implementing; we can talk about it. 

`clip` will eventually support SVG clip paths (and maybe PS clip paths?) However, nothing is implemented yet and it is disabled in the dialog. 

`use_transform` is false by default. When set to true it restores the behavior of flipping the y axis of exported SVGs with a `transform` element. Otherwise Glyph SVGs are exported with modified y values. (I'm using `SplineCharCopy` to implement this, which makes me a little nervous but seems to work fine. We can talk about that too.)

**Comment by frank-trampe** [comment]
I don't use this functionality very often, but this seems like a positive and non-disruptive move.
