### ISSUE TITLE
configure fail

### ISSUE THREAD

**Issue by langsz** [fontforge/fontforge#4201]
I try to install the fontforge and when I run ./configure, I get  the errors.
--------------------------------------------------------------
checking for GLIB... no
checking for GLIB... no
checking for GIO_UNIX... no
configure: error: in `/home/software/fontforge-20190801/build':
configure: error: ERROR: Please install GLIB-2.0 (with GIO-2.0 or GIO-UNIX-2.0) libraries with development include files
----------------------------------------
My linux is centos 6.1 and I already installed glib-2.

Do you know what this error ？

**Comment by jtanx** [comment]
Did you install the glib-devel package?

**Comment by langsz** [comment]
> glib-devel

yes. but it is the same result.

**Comment by jtanx** [comment]
What happens when you run

```
pkg-config --libs glib-2.0
```

**Comment by langsz** [comment]
> pkg-config --libs glib-2.0

-lglib-2.0

**Comment by jtanx** [comment]
Yeah odd. I would suggest trying latest master, but you're running a pretty ancient version of centos.

Do all these commands succeed?

```
pkg-config --cflags "glib-2.0 >= 2.6"
pkg-config --cflags gio-2.0
pkg-config --cflags gio-unix-2.0
```

**Comment by langsz** [comment]
> Yeah odd. I would suggest trying latest master, but you're running a pretty ancient version of centos.
> 
> Do all these commands succeed?
> 
> ```
> pkg-config --cflags "glib-2.0 >= 2.6"
> pkg-config --cflags gio-2.0
> pkg-config --cflags gio-unix-2.0
> ```
 pkg-config --cflags "glib-2.0 >= 2.6"
-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
[WebDocument build]# pkg-config --cflags gio-2.0
-pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
[WebDocument build]# pkg-config --cflags gio-unix-2.0
-pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include

**Comment by jtanx** [comment]
And just double checking, all you're running is 

```
./configure
```

?

Not really sure what else to try.

**Comment by langsz** [comment]
> Yeah odd. I would suggest trying latest master, but you're running a pretty ancient version of centos.
> 
> Do all these commands succeed?
> 
> ```
> pkg-config --cflags "glib-2.0 >= 2.6"
> pkg-config --cflags

> And just double checking, all you're running is
> 
> ```
> ./configure
> ```
> 
> ?
> 
> Not really sure what else to try.



> Yeah odd. I would suggest trying latest master, but you're running a pretty ancient version of centos.
> 
> Do all these commands succeed?
> 
> ```
> pkg-config --cflags "glib-2.0 >= 2.6"
> pkg-config --cflags gio-2.0
> pkg-config --cflags gio-unix-2.0
> ```

 pkg-config --cflags "glib-2.0 >= 2.6"
-I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
[WebDocument build]# pkg-config --cflags gio-2.0
-pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
[WebDocument build]# pkg-config --cflags gio-unix-2.0
-pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include

**Comment by langsz** [comment]
> And just double checking, all you're running is
> 
> ```
> ./configure
> ```
> 
> ?
> 
> Not really sure what else to try.

I try many times

**Comment by ctrlcctrlv** [comment]
> CentOS Linux currently has 2 major released branches that are active: CentOS-6, and CentOS-7. The CentOS Project provides updates or other changes ONLY for the latest version of each major branch. Thus, if the latest minor version of CentOS-6 is version 6.6 then the CentOS Project only provides updated software for this minor version in the 6 branch. If you are using an older minor version than the latest in a given branch, then you are missing security and bugfix updates.

6.1 is from 2011; issue is not worth developer time.
