### ISSUE TITLE
GUI version of fontforge fails when used within in a script (but didn't used to)

### ISSUE THREAD

**Issue by juliangilbey** [fontforge/fontforge#4203]
### When reporting a bug/issue:
- [ ] The FontForge version and the operating system you're using

Debian testing, version 1:20190801~dfsg-2

- [ ] The behavior you expect to see, and the actual behavior

I am the maintainer of [mftrace](https://github.com/hanwen/mftrace) for Debian.  mftrace uses fontforge to do part of its job, and begins by testing that fontforge is present and working by running "fontforge --version".  This ran without issue using older versions of the fontforge package (the most recent such Debian package was 1:20170731~dfsg-2; after that, they jumped to version 20190801), but not with the current version - it just exits with an error.  Tracking this back, when the GUI-enabled version of fontforge is run without a valid DISPLAY, even if just running "fontforge --version" or "fontforge --help", it bombs out.  The older version did not do this.

I am aware that there is a non-GUI version of fontforge, but the GUI-enabled version used to work for non-GUI tasks in a non-GUI environment, but it no longer does.  Furthermore, scripts are used to using plain "fontforge", without caring whether it is GUI-enabled or not (and there is no simple way to check for this), but this change in behaviour has broken at least mftrace, and quite possibly other scripts too.

I have not isolated the change that caused this change in behaviour, though; at a quick glance, the code does not look dramatically different between 20170731 and 20190801.

- [ ] Steps to reproduce the behavior 

Run "fontforge --version" or "fontforge --help" using the GUI-enabled fontforge in a terminal without a valid DISPLAY.

- [ ] Possible solution/fix/workaround

I'm not sure where this change in behaviour was introduced, but perhaps there could be a check in `fontforgeexe/startui.c` for whether there is a valid GUI, and to revert to the behaviour of `fontforgeexe/startnoui.c` if there is not instead of crashing.

**Comment by skef** [comment]
Suggesting @jtanx for this one

**Comment by jtanx** [comment]
At a guess, sounds like a dup of #4048.

**Comment by jtanx** [comment]
Oh, maybe not that one. I'd think it might be #3922, but it looks like Debian still builds with the X11 backend. Will check this in the evening.

**Comment by jtanx** [comment]
Ok I take that back, it looks like it [is built](https://packages.debian.org/search?keywords=libgdraw6) with the GDK backend, in which case, backporting the change in #3922 should fix it.

**Comment by juliangilbey** [comment]
Ah, super, thanks - I'll try it out and let you know.

**Comment by juliangilbey** [comment]
Yes, it works.  Many thanks - closing this issue now.
