### ISSUE TITLE
GenerateScript method crash when using CID fonts

### ISSUE THREAD

**Issue by Fiooodooor** [fontforge/fontforge#4206]
### Important
FontForge version 20190801 (ac635b8)
Operating system independent [macOS 10.15 and Windows 10 tested]
Input: Any CID based font file. (tested on Japanese, Korean, Chinese fonts)
Output: any Open Type based font format (inc. True Type)
Method: GenerateScript

- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] (optional) Possible workaround

### Issue with GenerateScript method from SaveFont.c
I expected that generatescript would convert and save given font based on detected output format. Giving for an input, an OTF CID font (or other CID format font) and for output any open type font format the method fails. The detection mechanism makes it wrong:
line 1112:     if ( sf->cidmaster!=NULL ) {
should be: 
line 1112:     if ( sf->cidmaster!=NULL || sf->subfontcnt > 0) {
but even correcting this, don't prevent the script from crashing.

### Worrkaround
Before calling the GenerateScript do:

```c
SplineFont* font = LoadSplineFont("c:/AnyCidFont.otf", 1);
//Doing something with font before saving
// Then flatten the cid and make a map copy of 
if (font->subfontcnt > 0) {
	struct EncMap *tmpMapCpy = EncMapCopy(font->map);
	SFFlatten(&font);	
	if (tmpMapCpy != NULL)
	{
		if (font->map == NULL) {
			font->map = tmpMapCpy;
		} else {
			free(tmpMapCpy);
		}
	}
}
int result = GenerateScript(font, destinationFile, NULL, 0, -1, NULL, NULL, font->map, NULL, 1);
```

**Comment by skef** [comment]
Based on your description I would expect that a "Native" script like:

```
Open('蒙纳简版黑.otf')
Generate('a.ttf')
```
would crash when the `Open`ed file is a CID font. I just tried this with the current master branch of FontForge and it didn't. However, none of the relevant code looks like its been changed recently.

Could you add a short script and a specific font that demonstrates the problem to this issue? It's probably easiest to put them in a zip archive and attach it (github is picky about the formats that can be attached).

**Comment by Fiooodooor** [comment]
No it is not an Unicode issue and sorry for being not precise. Here you have got the simple code and attached font - standard one from macOS.
 
download font: [fontsDir.zip](https://github.com/fontforge/fontforge/files/4292840/fontsDir.zip)
download code: [converterCode.zip](https://github.com/fontforge/fontforge/files/4292871/converterCode.zip)

What the script is intended to do: Take first font from the collection to which a path is supported. Load this font file to splineFont object and save the result to the otf file format.

What does the script do: Load the font collection file and  takes first font from inside it as intended. Then when goes to generateScript method, everything stops, the target file is created with size 0 and then the application crash. 

I am using the VisualStudio 2017 C++ for Windows builds. Fontforge build from latest girhub repository. So need to add path to fontforge dir for include and link (add) fontforge.dll.a library to your project. Dll need to be in the same dir etc. 
Change the paths so they correspond to fonts dir and if anything goes wrong with upload/download, the you can get the font from MacOS > 10.13v. as me. It crash also on macOS build of my plugin and librariese.

Code for reproduction, main.cpp:
```C++
// main.cpp
extern "C" { 
#include "convertCollection.h" }

#include <iostream>
int main() {
try {
	std::cout << "Font conversion starting... " << std::endl;
	std::cout << "Result is " << fontConvert() << std::endl;
}
catch (...) {
	std::cout << "Unknown error occured! Exiting!" << std::endl;
	return -1;
}
return 0;
}
```
convertCollection.h file:
```C
//convertCollection.h

#ifndef CONVERT_COLLECTION_H
#define CONVERT_COLLECTION_H

	int fontConvert();
	
#endif // CONVERT_COLLECTION_H
```
convertCollection.c file:
```C
// convertCollection.c

#include "convertCollection.h"
#include <fontforge/fontforge.h>

int fontConvert() {
	int returnVal = -1;
	char sourceFile[]	   = "d:\\fontsDir\\HiraginoSansGB.ttc";
	char destinationFile[] = "d:\\fontsDir\\converted\\HiraginoSansGB_1.otf";

	SplineFont* font = NULL;
	doinitFontForgeMain();
	font = (SplineFont*)LoadSplineFont(sourceFile, 1);

	if (font != NULL)
		returnVal = GenerateScript(font, destinationFile, NULL, 0, -1, NULL, NULL, font->map, NULL, 1);
	return returnVal;
}
```

**Comment by skef** [comment]
Oh, I guess I should (or could) have realized this from the initial description. 

The FontForge folks who attend to these issues support the application and the library *to the extent that it supports the application*. We can't feasibly provide general support for new application development. Unless this crash can be reproduced in FontForge itself I'm afraid you're on your own.

Anyone is, of course, free to use the FontForge library as they wish within the parameters of its license. However, at this point I strongly encourage you to consider using the python API rather than attempting to call the functions directly from C or C++. If there must be a C-level interface it would likely be both easier and more stable to invoke the python methods via the C-API.

Sorry we can't be of more help ...
