### ISSUE TITLE
Assembling accented character does not work for Greek lowercase letters with iota subscript

### ISSUE THREAD

**Issue by dbenjaminmiller** [fontforge/fontforge#4210]
Using the 20190801 on Linux.
To replicate, simply have a font with Greek characters. Try to create an accented character: it'll work, except for Greek lowercase letters with iota subscript.

**Comment by skef** [comment]
@dbenjaminmiller We need a bit more info before we can look at this, specifically some sort of "one iota" joke. Could you supply that?

**Comment by dbenjaminmiller** [comment]
My attempt at a joke: since it won't make a character with an iota subscript, FontForge is making us choose between ἰῶτα ἓν ἢ μία κεραία … I think that's kinda funny within your parameters.
But in any case: just make an ω and an Ω, and add an iota subscript character. You'll be able to to automatically build the accented character for ῼ, but not for ῳ.
Hope the joke and info are enough.

**Comment by skef** [comment]
That would probably be funny to me if I were more cultured. Still, it makes me think you didn't care *one iota* about the more specific request. 

I'll take a quick look at this.

**Comment by dbenjaminmiller** [comment]
Nevermind, sorry — it was an issue with my font. Adding the iota subscript in the Greek combining marks area makes it work — but it won't take the iota adscript as a backup. Not an actual issue with the program.

**Comment by skef** [comment]
Oh, yes, the use of spacing characters as a backup is a Latin convention (that, I believe, came over with earlier PostScript font implementations). 

In any case I confirmed on my end that the building process works for this one.
