### ISSUE TITLE
Replace the embedded PDF font with the edited one

### ISSUE THREAD

**Issue by deepseek** [fontforge/fontforge#4211]
Hi there,

I have loaded a pdf file in fontforge and edited it's embedded font, 
now how can I replace the embedded font in the pdf file with the edited one

**Comment by skef** [comment]
I don't think FontForge itself will be of much help with that step (could be wrong). 

This says that the process is tricky and suggests two possibilities: https://superuser.com/questions/166024/substitute-a-font-in-a-pdf-document

This has a third possibility: https://www.iceni.com/blog/replacing-embedded-fonts-in-pdf/

None of these are open source, I'm afraid.

**Comment by deepseek** [comment]
hmmmm....
there must be a solution other than the ones you suggested.
perhaps remove the embedded fonts then add the edited one
any ideas

**Comment by frank-trampe** [comment]
@deepseek, there may indeed be another solution, but you are unlikely to find it here given that we do not work much with the PDF format. Maybe try the xpdf, poppler, or pdftk mailing list.
