### ISSUE TITLE
clipboard gets wiped after copying text from a dialog box and closing it [bug]

### ISSUE THREAD

**Issue by daT4v1s** [fontforge/fontforge#4213]
- [ ] Screenshot
- [x] The FontForge 20190801 appimage linux
- [x] The behavior you expect to see, and the actual behavior
for the clipboard not to be cleared on dialog-close

- [x] Steps to reproduce the behavior 
1. right-click a glyph
2. go to glyph info, copy a field
3. paste somewhere else
4. close dialog
5. attempt paste again (fails)

this disrupts workflow somewhat,
also it affects other dialog-windows (e.g. save as, font-info-property)

pretty sure this bug affects older versions as well

**Comment by JoesCat** [comment]
Hi @daT4v1s,
I recall from past Linux use, this is an expected default behaviour for older versions of linux so I don't think there is anything to fix here (from the point of view of FontForge).

Older default Linux desktop behaviour is as you note in the steps above are:
- the original item is marked for copying, and then copies are based on the marked original (there is no "clipboard").
- Some apps and desktops might simulate a clipboard.

Users familiar with older versions of Linux may be more aware of the lack of a go-between clipboard. Appimage is based on an older Linux base to maintain a larger pool of compatibility, so this seems to correlate.

Here are more bits of info related to" older" versions of Linux repeating the lack of clipboard:
https://unix.stackexchange.com/questions/414303/does-non-x-linux-have-a-clipboard
https://unix.stackexchange.com/questions/420386/where-is-clipboard-location/420391

Hope this helps explain this behaviour.

CC: @probonopd - may have more accurate info.

**Comment by jtanx** [comment]
Yeah as mentioned this is not a bug, it's a function of how the clipboard mechanism works through X11. If you want to maintain the copied value use a clipboard manager like klipper or gpaste.
