### ISSUE TITLE
How to find all glyphs (e.g. 'ś', 'š', 'ş') referencing to glyph (e.g. 's'), using python3 with Fontforge? 

### ISSUE THREAD

**Issue by pytkr** [fontforge/fontforge#4222]
I tried with a function `glyph.find(contour[,error-bound,search_flags])` to find `s`-related glyphs in font `times.tff` (from windows system font folder), however, nothing worked at all.

**python code:**
```python
font_File_Path = r"E:\test\times.ttf"
font = fontforge.open(font_File_Path)
glyphs = font.selection.byGlyphs.select(115) # glyph 's'
for glyph in glyphs:
	cont = glyph.foreground
	print('cont = ' + str(cont)) # it does have contour data
	rst = font.find(cont, 1000, ("reverse", "flips", "rotate", "scale"))
	for gly in rst:
		print('gly.codepoint = ' +str(gly.codepoint) + ', char = ' + str(chr(int(gly.codepoint.replace('U+', '0x'), 16))))
	return
return
```
**the result** contains no expected chars: 

> gly.codepoint = U+0025, char = %
gly.codepoint = U+0026, char = &
gly.codepoint = U+0030, char = 0
gly.codepoint = U+0034, char = 4
gly.codepoint = U+0040, char = @
gly.codepoint = U+0041, char = A
gly.codepoint = U+0073, char = s
gly.codepoint = U+00C6, char = Æ
gly.codepoint = U+2206, char = ∆
gly.codepoint = U+2030, char = ‰
gly.codepoint = U+00D0, char = Ð
gly.codepoint = U+00BC, char = ¼
gly.codepoint = U+00BE, char = ¾
gly.codepoint = U+0110, char = Đ
gly.codepoint = U+25B2, char = ▲
gly.codepoint = U+25BA, char = ►
gly.codepoint = U+25BC, char = ▼
gly.codepoint = U+25C4, char = ◄
gly.codepoint = U+2663, char = ♣
gly.codepoint = U+0394, char = Δ
gly.codepoint = U+03B8, char = θ
gly.codepoint = U+0426, char = Ц
gly.codepoint = U+05D0, char = א
gly.codepoint = U+05D4, char = ה
gly.codepoint = U+05D9, char = י
gly.codepoint = U+05E6, char = צ
gly.codepoint = U+05F1, char = ױ
gly.codepoint = U+05F2, char = ײ
gly.codepoint = U+FB30, char = אּ
gly.codepoint = U+FB39, char = יּ
gly.codepoint = U+200E, char = ‎
gly.codepoint = U+200F, char = ‏
gly.codepoint = U+060C, char = ،
gly.codepoint = U+061B, char = ؛
gly.codepoint = U+0661, char = ١
gly.codepoint = U+FB91, char = ﮑ
gly.codepoint = U+FB95, char = ﮕ

so, how to find all `s`-related glyphs (e.g. 'ś', 'š', 'ş') based on glyph (e.g. 's'), using python3 with  Fontforge, thanks!

Another related question is, if I change `s` to `ś`, namely, change `select(115)` to `select(156)`, and rerun this code, however, the for loop doesn't run at all. 

Then, I find that `ś` is a `reference glyph`, and it doesn't contain any contour data, thus, when using `find` function, the result will be totally wrong, due to an `empty` contour, namely, `find` cannot even find `ś` itself.

**Comment by ctrlcctrlv** [comment]
Why not `unicodedata` to find all likely candidates then search those for `s`, or just iterate through all glyphs in font and do the same.

**Comment by pytkr** [comment]
> Why not `unicodedata` to find all likely candidates then search those for `s`, or just iterate through all glyphs in font and do the same.

Thanks for you replay! 

When I use ff gui, I find the function is very handy by single-clicking the `s` glyph and using menu `Element > Other Info > Show Dependant > References`, the result is a list of `s`-related glyphs, how great it is! And clicking any item in it will jump to that glyph, e.g. `ś`, although jumping action will cause the list window to disappear (maybe a bug?).

If I create a new glyph which also has reference to `s`, then, this function can help me, too, so I tried to use python api and hope the python api can have the same effect, because I don't know whether unicodedata can cope with user-defined glyphs.

**Comment by skef** [comment]
Try something more like this:

```#!/usr/bin/env python

import fontforge

font_File_Path = r"E:\test\times.ttf"
font = fontforge.open(font_File_Path)
refname = font['s'].glyphname
for gn in font:
    g = font[gn]
    for ref in g.layerrefs[1]:
        if ref[0] == refname:
            print("Glyph " + gn + " has a reference to " + refname)
            continue

```

**Comment by pytkr** [comment]
> Try something more like this:
> 
> ```
> 
> import fontforge
> 
> font_File_Path = r"E:\test\times.ttf"
> font = fontforge.open(font_File_Path)
> refname = font['s'].glyphname
> for gn in font:
>     g = font[gn]
>     for ref in g.layerrefs[1]:
>         if ref[0] == refname:
>             print("Glyph " + gn + " has a reference to " + refname)
>             continue
> ```
> 
> (That assumes you only want references in the foreground layer. If you have a multilayer font or care about the background you'll have to look in other entries in the `layerrefs` tuple.)

Great thanks!

The method is to "work around" the `find` function, and it does work like charm! And the running complexity cost is not high at all and acceptable, thanks again!

In my understanding, `find‘ function uses contour data to find similar shaped glyphs, thus, logically, `s` can `find` some glyphs, no matter whether coded-glyphs like `ś` or some user un-coded-glyphs.

**Comment by skef** [comment]
The python `find` method corresponds to "Edit -> Find/Replace ..." in the UI. It can be used to find similar contours but it doesn't always work that well. The code I posted is doing something fairly close to what Show Dependent -> References does internally.
