### ISSUE TITLE
Can’t stroke a zero length line segment in version 20200314

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4223]
The following script creates a font with one glyph, a dot, in version 20190801. In version 20200314, the font contains no glyphs. I am using macOS 10.14.6.

```python3
import fontforge

font = fontforge.font()
glyph = font.createChar(0x30)
pen = glyph.glyphPen()
pen.moveTo((0, 0))
pen.lineTo((0, 0))
glyph.stroke('circular', 70, 'round', 'round', ())
font.generate('dot.otf')
```

Version 20200314 prints this warning.
```
Warning: No stroke output for contour
Warning: Font contained no glyphs
Number out of range: 2.14748e+09 in type2 output (must be [-65536,65535])
```

**Comment by skef** [comment]
To start with I'm not sure why this worked before. I guess we can check.

The old code treated, and the new code treats, a single point contour as a special case, replacing it with a copy of the nib. It's easy to verify in the GUI or via python that that works.

As it happens the FontForge semantic for creating a single point is a lone "moveTo". And you can verify that works by commenting out `pen.lineTo((0, 0))` in your test script above. This is, obviously, the easiest work-around. 

The current code clearly doesn't treat an infinitely short line as equivalent to a single point for this purpose. That the old code did may have been an accident -- it wasn't documented anywhere that I'm aware of. 

@dscorbett Given the workaround do you still care about this? Do you have many scripts that would need updating? Do you suspect that infinitely short lines are a common semantic for some other reason?

**Comment by skef** [comment]
Ah, this was probably a side-effect of the call to `SSRemoveZeroLengthSplines(base)` in the old `SplineSet_Stroke()`. The new code handles that case with

```
        if ( SplineLength(s)==0 ) // Can ignore zero length splines
            continue;
```
in `OffsetSplineSet()`

So it does seem to me that the `moveTo()` / `lineTo()` effect in the old code was a coincidence rather than a feature.

**Comment by dscorbett** [comment]
I’m fine with this new behavior.

**Comment by skef** [comment]
Alright - I'm going to mark this maybe-done and give others a chance to weigh in. If there are no objections I'll close it and we can refer to it if others have questions about the behavior change.

**Comment by ctrlcctrlv** [comment]
No, I am in definite disagreement. Single points should be stroked. This will certainly break my fonts, TT2020 etc.

**Comment by ctrlcctrlv** [comment]
Wait, sorry, I'm an idiot, we're talking about a class of line segment AB such that points A and B have equal coordinates; there's no reason that that should work, single points should be used instead.

I'm also fine with the new behavior for this class of line segments

**Comment by skef** [comment]
Yeah, so to be clear for the record, a single point, or using the pen interface a single `moveTo()`, will (or should) be replaced by a copy of the nib in both the old and the new systems unless the cap style is "Butt". I don't know if this is well documented but I consider it an official feature.

**Comment by skef** [comment]
Seems like there are no strong objections -- closing.
