### ISSUE TITLE
MacOS Catalina security problems

### ISSUE THREAD

**Issue by benwiggy** [fontforge/fontforge#4227]
As a result of the 'increased' security in Catalina, FontForge cannot access the Documents, Desktop or Downloads folders, nor Network Shares. 

<img width="371" alt="Screenshot 5" src="https://user-images.githubusercontent.com/20556865/76896523-e29d7680-6889-11ea-872b-15f0cd3dde99.png">

I've added FontForge to the "Full Disk Access" panel of the Security pref pane, but it doesn't seem possible to add apps to the "Files and Folders" panel. (That looks like an Apple bug, which I've filed.)

Is there anything that can be done? (I'm surprised I couldn't find a mention of this before.)

**Comment by skef** [comment]
Please refer to the workarounds in the Inkscape and GIMP issues linked [here](https://github.com/fontforge/fontforge/issues/4082#issuecomment-569874742)
