### ISSUE TITLE
copy to clipboard not working

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4228]
it's not possible to copy any text and paste outside of fontforge on windows 10 (i think the issue exist in all release after 2017)

**Comment by jtanx** [comment]
90% sure this is a GTK regression. Probably https://gitlab.gnome.org/GNOME/gtk/-/commit/6452d34cd7d84ee8b1edb784a9a08310d1b720b2

**Comment by zslevi** [comment]
Shift+Insert doesn't paste but Ctrl+V does.

I'm using FontForge version 20200314 on Windows 7.
