### ISSUE TITLE
make DESTDIR install fails when setting the rpath

### ISSUE THREAD

**Issue by heirecka** [fontforge/fontforge#4229]
When trying to install fontforge 20200314 to a DESTDIR it fails with:

```
Install the project...
/usr/x86_64-pc-linux-gnu/bin/cmake -P cmake_install.cmake
-- Install configuration: "None"
-- Installing: /var/tmp/paludis/build/media-gfx-fontforge-20200314/image/usr/x86_64-pc-linux-gnu/lib/libfontforge.so.4
CMake Error at fontforge/cmake_install.cmake:50 (file):
  file RPATH_CHANGE could not write new RPATH:

    /usr/x86_64-pc-linux-gnu/lib:/usr/x86_64-pc-linux-gnu/lib

  to the file:

    /var/tmp/paludis/build/media-gfx-fontforge-20200314/image//usr/x86_64-pc-linux-gnu/lib/libfontforge.so.4

  The replacement path is too long for the RUNPATH entry.
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)
```

To be honest, I'm rather clueless about the cause, pretty sure I've never seen an error like that (nor do I see it for any other package).

FontForge version: 20200314
OS: Exherbo Linux, cmake 3.16.5, binutils 2.34

**Comment by skef** [comment]
What was the full `cmake` command you used at the start before compilation?

**Comment by heirecka** [comment]
`cmake -DCMAKE_COLOR_MAKEFILE:BOOL=TRUE -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=None -DCMAKE_C_FLAGS:STRING=-march=native -pipe -O2 -DCMAKE_CXX_FLAGS:STRING=-march=native -O2 -pipe -DCMAKE_AR:PATH=x86_64-pc-linux-gnu-ar -DCMAKE_RANLIB:PATH=x86_64-pc-linux-gnu-ranlib -DCMAKE_NM:PATH=x86_64-pc-linux-gnu-nm -DCMAKE_C_COMPILER:PATH=x86_64-pc-linux-gnu-cc -DCMAKE_CXX_COMPILER:PATH=x86_64-pc-linux-gnu-c++ -DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM:STRING=NEVER -DCMAKE_SYSTEM_PREFIX_PATH:PATH=/usr/x86_64-pc-linux-gnu -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_DATAROOTDIR:PATH=/usr/share/ -DENABLE_FREETYPE_DEBUGGER= -DENABLE_LIBGIF:BOOL=TRUE -DENABLE_LIBJPEG:BOOL=TRUE -DENABLE_LIBPNG:BOOL=TRUE -DENABLE_LIBREADLINE:BOOL=TRUE -DENABLE_LIBSPIRO:BOOL=FALSE -DENABLE_LIBUNINAMESLIST:BOOL=TRUE -DENABLE_NATIVE_SCRIPTING:BOOL=FALSE -DENABLE_SANITIZER=none -DCMAKE_INSTALL_RPATH=/usr/x86_64-pc-linux-gnu/lib -DENABLE_DOCS:BOOL=FALSE -DENABLE_GUI:BOOL=TRUE -DENABLE_PYTHON_EXTENSION:BOOL=TRUE -DENABLE_PYTHON_SCRIPTING:BOOL=TRUE -DENABLE_LIBTIFF:BOOL=FALSE -DENABLE_WOFF2:BOOL=FALSE -DENABLE_X11:BOOL=TRUE /var/tmp/paludis/build/media-gfx-fontforge-20200314/work/fontforge-20200314
`

**Comment by skef** [comment]
This is a lot of options, so I can't be sure that this will help. However, I use CMAKE_INSTALL_PREFIX in my own workflow and just set is "directly", which in your case would correspond to `-DCMAKE_INSTALL_PREFIX=/usr/x86_64-pc-linux-gnu` rather than `-DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu`. Can you give that a try?

**Comment by jtanx** [comment]
The problem is likely this: 

https://github.com/fontforge/fontforge/blob/67687b099f82022d7384c76d0e1509fcc5e938b9/cmake/BuildUtils.cmake#L103-L106

You are defining `CMAKE_INSTALL_RPATH` in your invocation, but the above code is already adding it. So it's being added twice. There's a couple of things I can think of to resolve this, but the easiest for now is to not specify the CMAKE_INSTALL_RPATH yourself.

**Comment by heirecka** [comment]
> -DCMAKE_INSTALL_PREFIX=/usr/x86_64-pc-linux-gnu rather than -DCMAKE_INSTALL_PREFIX:PATH=/usr/x86_64-pc-linux-gnu. Can you give that a try?

Doesn't make a difference.


> You are defining CMAKE_INSTALL_RPATH in your invocation, but the above code is already adding it. So it's being added twice. There's a couple of things I can think of to resolve this, but the easiest for now is to not specify the CMAKE_INSTALL_RPATH yourself.

Oops, sorry. I actually added that only after encountering the error the first time.

> You can also just comment out the invocation of that for now, given you're basically defining everything yourself.

That obviously works.

**Comment by jtanx** [comment]
@heirecka can you confirm if #4232 fixes it for you?

**Comment by heirecka** [comment]
Yes, that indeed fixes this issue for me. Thank you!
