### ISSUE TITLE
CMake: Fontforge headers and some libraries not getting installed

### ISSUE THREAD

**Issue by CyberBotX** [fontforge/fontforge#4233]
In trying to update the Fontforge port for FreeBSD to tag 20200314, the test build I did showed that the headers for Fontforge were not being installed to `<install_prefix>/include/fontforge` like they were with the previous autotools build system. As well as this, the test build is showing that the libraries of `libfontforgeexe.so`, `libgunicode.so` and `libgutils.so` are not getting installed. The former I believe is going to be a problem for other consumers of fontforge as a build dependency in the FreeBSD ports tree. The latter, I don't know if they are actually problems yet as I have not tried to run the software after building from that tag.

A full build log showing what was being done can be found here:
https://poudriere.cyberbotx.com:8766/data/local-default/2020-03-21_14h08m08s/logs/errors/fontforge-20200314.log
(I'm still working on updating the port so things are a bit of a mess right now.)

**Comment by skef** [comment]
@jtanx knows more about this but as I understand it the project does not document a stable ABI and no projects that we are aware of depend on FontForge's libraries. The fine-grained shared libraries of the previous build system were either artifacts of past layout decisions or "speculative". So when the code was reorganized much of the code in the libraries was just statically linked into the binary. `libfontforge.so` remains to support the python modules.

And, of course, if there aren't projects that compile against FontForge and no stable ABI then there is no obvious need for include files.

**Comment by jtanx** [comment]
gunicode and gutils are combined into libfontforge. libgdraw is combined into the fontforge binary itself.

The decision to not install headers was a conscious one - as mentioned we don't provide a stable API or ABI, and from what I saw at the time, the only product with a build time dependency was pdf2htmlex, which has been abandoned. We asked about this on the mailing list with no replies too.

Can you provide a list of products that you're saying do have build time dependencies?

**Comment by CyberBotX** [comment]
I don't maintain any of these FreeBSD ports, but these are the ones that list fontforge as a build-time dependency:

* japanese/font-ricty (https://rictyfonts.github.io/)
* print/lilypond (http://lilypond.org/)
* x11-fonts/oxygen-fonts (https://cgit.kde.org/oxygen-fonts.git)

Since I don't maintain them, I don't know what they need fontforge as a build dependency for. I also don't know if they are using the headers or the executable. From a glance, though, those two font ports seem to just rely on the executable. Lilypond might also rely only on the executable but I'm not really sure on that. Lilypond also might be looking for the pkg-config files that are no longer with fontforge because of the switch to CMake.

**Comment by skef** [comment]
I've run into Lilypond before at some point and I believe they use the python API, and if not that the native scripting language. Fontforge is mentioned here: http://lilypond.org/mftrace/

It's at least unlikely that any of these are compiling against the libraries. I think it will be fine.

**Comment by jtanx** [comment]
Yeah, I'd be fairly confident that none of those actually compile against FontForge, but merely use the executable in some form.
