### ISSUE TITLE
Goto shortcut doesn't work with AltGr

### ISSUE THREAD

**Issue by zslevi** [fontforge/fontforge#4235]
The default shortcut for Goto is Ctrl+Shift+>
The Hungarian keyboard layout uses the AltGr+Z to type the character ">".
Neither Shift+AltGr+Z nor Ctrl+Shift+AltGr+Z does trigger this shortcut.

I'm using FontForge version 20200314 on Windows 7.

P.S.:
Couldn't locate the hotkeys file either.

![ffHotkeysFileMissingWindows7](https://user-images.githubusercontent.com/62501513/77247414-51375700-6c31-11ea-9f4a-657e842e001b.png)

**Comment by KamilLanda** [comment]
There are some shortcuts with AltGR on Czech keyboard too, but it is not functional too. 
File with keyboard shorcuts (named `default`) is in the `Program Files (x86)` directory
`C:\Program Files (x86)\FontForgeBuilds\share\fontforge\hotkeys`

![dir](https://user-images.githubusercontent.com/61148366/77346811-1e778680-6d37-11ea-9fa6-d5c0345ecbaf.png)

**Comment by zslevi** [comment]
Thanks, found it, works now.
