### ISSUE TITLE
Version number can't be copypasted from About window

### ISSUE THREAD

**Issue by zslevi** [fontforge/fontforge#4236]
The About windows closes for any mouse click, so the version number can't be copypasted. It's a minor usability  issue, but would make reporting bugs simpler.

I'm using FontForge version 20200314 on Windows 7.

**Comment by zslevi** [comment]
I guess it can't be solved 
until https://github.com/fontforge/fontforge/issues/4228
is solved.

**Comment by skef** [comment]
I'm sorry, I'm closing this. There are 800+ open bugs; FontForge can't be everything to everyone.
