### ISSUE TITLE
Adding Unicode Name to New Glyph, Changes All Empty Glyphs in Fontview to Display ? | U+???, Name.Me

### ISSUE THREAD

**Issue by sakura22** [fontforge/fontforge#4239]
Not sure if I don't understand Fontforge or it's the program.  I'd be grateful for any advice on whether it's a bug, capability of Fontforge or of me. It's a cool little program.
Thank you in advance for any help.

- Windows 10 1909 buld 18363.752
- 32MB RAM, 2060 RTX
- Fontforge build 14 Mar 2020
![ZeroNames4](https://user-images.githubusercontent.com/18496238/77508447-72f54000-6eb6-11ea-90bf-95b9c0fbc00e.png)

**My Desired Outcome**
I would like to add extra 'encoding slots' and assign them a PUA Unicode and not have all the empty Unicode glyps in FontView zero out to display ? | U+??? name.me*.* or spontaneously crash.
![ZeroNames1](https://user-images.githubusercontent.com/18496238/77506778-68d14280-6eb2-11ea-91f5-19a226598b9d.png)

Is the solution, that I have to use Fontforge's Unicode in ISO-106461, 'View>Goto' U+E00x and insert my glyph, composite etc, rather than adding an encoding slot and changing the Unicode?

**My Scenario**
1. When I add a new encoding slot and enter any PUA Unicode within the 'Glyph Info' section, 
a) the entire Fontview display turns all the empty glyph cells from their assigned unicode to ? | U+??? name.me*.* or
b) Sometimes, fontforge crashes as soon as I click OK within the Glyph Info box, and the only thing I've done is open fontforge, load a pre-existing font, add 1 encoding slot, then in Glyph Info changed the name to 'tt' and change the unicode to 'U+E001'.

2. I've tried a number of established fonts and the behaviour replicates. 
Linux Libertine, Agreloy, Great Vibes
In the below picture Linux Libertine has an empty PUA U+E038 so I attempted to change the 'new encoding slot' to U-e038.
![ZeroNames3](https://user-images.githubusercontent.com/18496238/77511564-0fbadc00-6ebd-11ea-9f69-c0d7613f4b9d.png)

3. I've also tried in compact view, and changing the encoding selection to ISO-106461-Full, BMP, and Latin 1 and 2 and each time, every empty glyph cell is reset to  ? | U+??? name.me*.*
![ZeroNames2](https://user-images.githubusercontent.com/18496238/77507191-a4204100-6eb3-11ea-9abf-0e63b6aa0a6d.png)

Any guidance is appreciated.

**Comment by skef** [comment]
This *is* a weird symptom, but here is one work-around that should work: First add the character as you have been, *then* reencode to Unicode BMP. The other empty glyphs will get their names back and the glyph you've added will move to its unicode slot. It will then appear in "compact" mode *as long as* it has some content (a reference or contour).

**Comment by sakura22** [comment]
Thanks for your quick reply and providing me with a work around. I hope this problem will be fixed soon. 

I'll leave closing or flagging this issue as a bug up to you. I'll carry on until the next update.
Thanks again.

**Comment by ctrlcctrlv** [comment]
Closed as invalid. This isn't a bug. When you add encoding slots, you're creating a custom encoding. The re-encode is necessary, not a weird symptom of anything.
