### ISSUE TITLE
[Won't run] FontForge 2020-03-14 on Windows Vista 32-bit

### ISSUE THREAD

**Issue by SWWEFHoiiqwdjxqo** [fontforge/fontforge#4243]
FontForge will install successfully, however when it is run, instead of a user interface to select a file, it immediately gives the following error:

![image](https://user-images.githubusercontent.com/62834424/77846895-94597300-71b9-11ea-9bc1-2dbe51bd0959.png)

After pressing OK, FontForge would then proceed to crash:

![image](https://user-images.githubusercontent.com/62834424/77846926-ae935100-71b9-11ea-9628-da7465a47161.png)

Then, it finishes crashing:

![image](https://user-images.githubusercontent.com/62834424/77846936-c1a62100-71b9-11ea-84ab-4c3b788216f0.png)

This is unexpected, because https://fontforge.org/docs/faq.html#faq-minimum does not mention a restriction on the Microsoft Windows version.

**Comment by jtanx** [comment]
FontForge is built with msys2/mingw-w64, which has dropped Vista support. So the documentation should probably be updated, but I have no intention of rebuilding to support Vista (or XP for that matter). Please use an older build or consider updating your OS.

**Comment by SWWEFHoiiqwdjxqo** [comment]
What font editor is instead recommended for this system?

**Comment by SWWEFHoiiqwdjxqo** [comment]
What font editor is instead recommended for this system? What font editor is instead recommended for this system?

**Comment by ctrlcctrlv** [comment]
We make no recommendations beyond FontForge. An old release will probably work.
