### ISSUE TITLE
The default GDK backend is not stable on Wayland

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#4247]
The new fontforge-20200314 release is not having stable GDK backend on Wayland. I found some UI bugs.  I am using Fedora 32, fontforge-20200314 default build.

1) fontforge sometimes could not render glyphs when opened font. (This happened at least once to me)
2) If you open any font and try to click on any glyph then it will not show as it is selected glyph.
3) if you try to "Font Info" then the widow that comes contains metadata information about this font but you cannot modify it. Click on various items left side, right side not getting changed.
4) Same for "Glyph Info" as well. Unable to show/render information about selected glyph.
5) If you "compact" the font, un-compacting will have no effect.
![fontforge-gdk-backend-wayland-warnings](https://user-images.githubusercontent.com/671366/77906161-1e323a80-72a5-11ea-8fa0-42ac3ab5bdab.png)

and also see https://pnemade.fedorapeople.org/fontforge/fontforge-run-under-wayland.webm

**Comment by jtanx** [comment]
Is this running with xwayland?

**Comment by pnemade** [comment]
Yes it worked fine if I enable X11 backend.  But, then with X11 enabled, I get #3366 issue.

If I use GDK backend build it works under Xorg and XWayland but under wayland, as described above issues appear. If same GDK build is run under Xorg above reported issues do not appear.

**Comment by jtanx** [comment]
So just confirming, you're saying that without XWayland (so just wayland), that's when you see this issue, but with XWayland it's fine?

If so, then this is a dup of #3295. In fact, I don't even know how it runs at all, as we've tried to limit the supported backends to X11 only on Linux.

**Comment by pnemade** [comment]
I think I used wrong terminology. I built fontforge with default configuration. I ran fontforge as
GDK backend + Wayland + XWayland adapter
and found the UI issues as reported in this issue description.

If I build fontforge with -DENABLE_X11=ON, and run it as
X11 backend + Wayland + XWayland adapter
then it worked fine. I can see glyphs getting selected, Glyph info navigation worked.

**Comment by skef** [comment]
Many of these problems point to some kind of screen update issue (or, rather, the lack of an update). 

Just as a first try do any of them resolve if you iconify and reopen the window?

**Comment by pnemade** [comment]
first I do not know why GDK backend build comes with no border window and no close (cross) button on right top corner of fontforge UI. So, I am not sure how to iconify it and reopen.

I did switched to other open applications and come back to fontforge UI window but of no use. I still see UI issues.

**Comment by jtanx** [comment]
The lack of borders is a sign that server-side decorations aren't being applied. Confirming, with the old X11 backend you do see borders? Because if you did I'd expect the same for the GDK (using X11) backend.

I'd expect no decorations with GDK using wayland directly as that's definitely broken.

**Comment by skef** [comment]
Maybe Wayland is, well, way more different than X than I'm aware of, but wouldn't the lack of those decorations imply that there was no running window manager? I thought Wayland still had [window managers](https://www.modmy.com/window-managers-wayland).

**Comment by jtanx** [comment]
Under pure wayland, mutter doesn't provide server side decorations; it expects full CSD a la GTK.  You'll find more info on it if you google for 'wayland server side decorations'

**Comment by jtanx** [comment]
Well I tried to spin up a Fedora 32 VM, and dnf is core dumping on me, so can't do much.

**Comment by jtanx** [comment]
I managed to get this working in a Fedora 32 VM and I can reproduce. But this looks 100% like an upstream GTK/GDK bug, it's not respecting our call to `gdk_set_allowed_backends` here: https://github.com/fontforge/fontforge/blob/master/fontforgeexe/startui.c#L1186

And it's defaulting to the wayland backend.

If I run it like so:

```
GDK_BACKEND=x11 bin/fontforge
```

It works fine.

**Comment by jtanx** [comment]
Well it's either an upstream bug or the documentation's off, but it seems to work if you set `gdk_set_allowed_backends` before calling `gdk_init`

**Comment by pnemade** [comment]
First I need to understand in new release 20200314, fontforge can be run in either backend only right? or Compiling with default options can allow to run same fontforge binary as X11 backend?

e.g. I have done Fedora build with below cmake options
```
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON .. -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_X11=ON -DTHEME=2012
```
I am even confused whether 2012 theme is supposed to work with both X11 and GDK backend or not?

I tested in my F32 VM with above cmake compilation with this pull-request patch. I still see same crash. I think as I have already compiled with ENABLE_X11 option, I don't need to use 
```
GDK_BACKEND=x11 fontforge
```
I tried above command anyway but it still crash for me.

**Comment by jtanx** [comment]
Ok let's clarify some things.

FontForge has two backends, one which uses GDK, and one where it interfaces directly with Xlib/X11. Prior to there being two backends, FontForge had one - the Xlib backend. If `ENABLE_X11` is disabled, FontForge will use the GDK backend. If it is enabled, the Xlib backend is used.

GDK itself however, supports interfacing with multiple backends - Wayland directly (which doesn't work for FontForge), X11 (probably via xlib or xcb, I didn't check), Win32 (for windows) and Quartz (for MacOS).

Note the extra layer of indirection if GDK is used.

So what I suggest you do is *do not* pass `ENABLE_X11=on` (or since you have already enabled it, pass `ENABLE_X11=off`). This will make FontForge use the GDK backend, and with #4253, forces it to use GDK's X11 backend instead of the Wayland backend, which is broken.

Regarding:
> I tried above command anyway but it still crash for me. I test under Wayland session only as its where crash used to happen.

That's expected because the option you passed does nothing when using the old Xlib backend (since you had ENABLE_X11 on); it's only relevant when GDK is enabled.

**Comment by pnemade** [comment]
@jtanx I confirm your patch in #4253 fixed fontforge UI issues on Wayland. Thank you for your help.

**Comment by jtanx** [comment]
Thanks for confirming
