### ISSUE TITLE
Can't set a contour name in a Python script

### ISSUE THREAD

**Issue by dse** [fontforge/fontforge#4249]
The following minimal working example Python script:

```
#!/usr/bin/env fontforge
# -*- mode: python; coding: utf-8 -*-
import fontforge
contour = fontforge.contour()
contour.name = 'foo'
```

ends with failure:

```
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20200314
 Based on sources from 2020-03-14 03:46 UTC-ML-D-GDK3.
 Based on source from git with hash: 67687b099f82022d7384c76d0e1509fcc5e938b9
fontforge(38801,0x111f4ddc0) malloc: *** error for object 0x108744ec0: pointer being freed was not allocated
fontforge(38801,0x111f4ddc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ uname -a
Darwin rectangle2 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

**Possible solution** is the following patch:

```
diff --git a/fontforge/python.c b/fontforge/python.c
index 5344b0f6..7e2ac5ee 100644
--- a/fontforge/python.c
+++ b/fontforge/python.c
@@ -2583,13 +2583,15 @@ return( Py_BuildValue("s", self->name ));
 }
 
 static int PyFF_Contour_set_name(PyFF_Contour *self,PyObject *value, void *UNUSED(closure)) {
-
-    free(self->name);
-    if ( value==Py_None )
-       self->name = NULL;
-    else {
-       PYGETSTR(value, self->name, -1);
-       ENDPYGETSTR();
+    if (self->name != NULL) {
+        free(self->name);
+        self->name = NULL;
+    }
+    if ( value!=Py_None ) {
+        char *name;
+        PYGETSTR(value, name, -1);
+        self->name = copy(name);
+        ENDPYGETSTR();
     }
 return( 0 );
 }
```

It's a minor rewrite of `PyFF_Contour_set_name` to make it more like `PyFFPoint_set_name`.  But also the former was missing a call to `copy()` which seems crucial here.

I say "possible solution" because unfortunately I'm unable to actually do a build because `fontforge-config.h` is not being generated on my system.

---

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
Looks like this was fixed by #4333
