### ISSUE TITLE
FontForge CLI should allow user to suppress copyright info

### ISSUE THREAD

**Issue by Alhadis** [fontforge/fontforge#4254]
**Platform:** macOS 10.13.6 (High Sierra)
**Version:** `fontForge 20190801` (build date: 13:06 UTC 14-Nov-2019)

When running a FontForge script from the command-line, a copyright notice is indiscriminately printed to stderr irrespective of `-nosplash` or `-quiet`:

~~~ console
λ fontforge -nosplash -quiet -c 'print("Foo");'
Copyright (c) 2000-2019. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 13:06 UTC 14-Nov-2019-D.
Foo
~~~

One can silence this with `2>/dev/null`, but that naturally hides legitimate error messages needed for debugging. It'd be nice if `-nosplash` and/or `-quiet` could silence the copyright info [when run from CLI](https://github.com/fontforge/fontforge/blob/0186c4175696fd8bdbbef87a1c6ce615bcaa9f54/fontforgeexe/startnoui.c#L89-L93) the same way it does [when run graphically](https://github.com/fontforge/fontforge/blob/0186c4175696fd8bdbbef87a1c6ce615bcaa9f54/fontforgeexe/startui.c#L944-L951).

On a related note, I noticed `-quiet` is handled inconsistently depending on the `-lang` parameter:

~~~console
λ fontforge -nosplash -quiet -lang=py -c 'print("Foo")'
Foo
Exit status: 0

λ fontforge -nosplash -quiet -lang=ff -c 'Print("Foo");'
-quiet: No such file
Exit status: 1
~~~
(Copyright banners omitted for brevity)

**Comment by ctrlcctrlv** [comment]
The `lang`parameter must always come first. This is described in documentation.

**Comment by ctrlcctrlv** [comment]
This bug is valid by the way. It's caused by a mismatch between `startui.c` which respects `quiet`and `startnoui.c` which doesn't. 

Proper fix is to put this in a function and use the function in both files.

**Comment by Alhadis** [comment]
> The `lang` parameter must always come first. This is described in documentation.

It isn't mentioned anywhere in the man page...

> Proper fix is to put this in a function and use the function in both files.

Agreed. I'm happy to submit a pull-request, now that I'm confident it's an oversight and not by design.
