### ISSUE TITLE
FONTFORGE_EXTRAS and MAINTAINER_TOOLS installing nothing.

### ISSUE THREAD

**Issue by algent-al** [fontforge/fontforge#4259]
### Description
While packaging fontforge 20200314 for Solus, enabling Cmake build options:
- ENABLE_FONTFORGE_EXTRAS
- ENABLE_MAINTAINER_TOOLS

```
    %cmake_ninja \
        -DENABLE_FONTFORGE_EXTRAS=ON \
        -DENABLE_MAINTAINER_TOOLS=ON \
        -DENABLE_DOCS=ON
```

doesn't make any change/add of files in installation directory. It is same as not adding them at all.
Here is the complete [file list](https://hasteb.in/obagoyey.sql) of the package.

Looking at the build directory something there is builded.

Both options enabled:
![bin-dir](https://user-images.githubusercontent.com/46356616/78459233-e158b000-76b7-11ea-97d8-1566d2bec906.png)
![contrib-dir](https://user-images.githubusercontent.com/46356616/78459293-41e7ed00-76b8-11ea-9533-bc2e850810d7.png)

Whithout options:
![bin-dir-2](https://user-images.githubusercontent.com/46356616/78459317-7196f500-76b8-11ea-9342-a071b19d6907.png)
![contrib-dir-2](https://user-images.githubusercontent.com/46356616/78459331-8f645a00-76b8-11ea-8d3a-4af64b3585db.png)

Not sure what I am doing wrong. My expectations are that some new files should be added in installation directory.

**Comment by jtanx** [comment]
It's expected.

Maintainer tools means just that - to be used to do certain tasks within the repo, and which does not make sense for it to be installed.

Whether or not the tools from FONTFORGE_EXTRAS get installed is I guess debatable but the current behaviour is it doesn't. iirc they were not installed under the old system either.

**Comment by ctrlcctrlv** [comment]
Closed as invalid per explanation in last comment.

**Comment by jtojnar** [comment]
The extras were installed, at least since https://github.com/fontforge/fontforge/commit/b02a75360fc508d97edd03d2a7fb4bac3547ae64, which moved them from `noinst_PROGRAMS` to `bin_PROGRAMS`. Would you accept the [Debian patch](https://salsa.debian.org/fonts-team/fontforge/-/blob/76bffe6ccf8ab20a0c81476a80a87ad245e2fd1c/debian/patches/0001-add-extra-cmake-install-rules.patch) created by @anthonyfok?
