### ISSUE TITLE
One pixel shift when exporting OTB (from PCF)

### ISSUE THREAD

**Issue by HW42** [fontforge/fontforge#4262]
I'm trying to convert [this PCF font](https://github.com/fontforge/fontforge/files/4433010/6x13.pcf.gz) (standard X11 font used for example by xterm by default) to OTB to be able to use it with Pango >= 1.44.

Taking the letter `P` as example, it normally looks like this (scaled up and added grey border for better visbility):
![P-rendered-xterm-pcf](https://user-images.githubusercontent.com/22183367/78467723-c6b22580-770f-11ea-8603-0afb184bfb69.png)
After loading the PCF file in fontforge it looks good:
![P-fontforge-pcf](https://user-images.githubusercontent.com/22183367/78467709-b69a4600-770f-11ea-9972-1f4f490b96d0.png)
But if I generate an OTB with fontforge and load it again the pixels are shifted one up:
![P-fontforge-otb](https://user-images.githubusercontent.com/22183367/78467712-c023ae00-770f-11ea-9524-741a8672e6e1.png)
and they also get rendered like this by Pango:
![P-rendered-xfce4-terminal-otb](https://user-images.githubusercontent.com/22183367/78467719-c3b73500-770f-11ea-8008-6d3b4c659a1e.png)

First noticed this problem in version 20190801 as shipped in Debian unstable, but I checked and see the same behavior with the 20200314 AppImage.

**Comment by ctrlcctrlv** [comment]
> First noticed this problem in version 20190801 as shipped in Debian unstable, but I checked and see the same behavior with the 20200314 AppImage.

Has it ever worked in any version to your knowledge?

**Comment by HW42** [comment]
> Has it ever worked in any version to your knowledge?

I don't know. I only tired the two versions mentioned above.

**Comment by jtanx** [comment]
This fixes the off-by-one shift when rereading the otb in FontForge (the ascent/descent is [signed](https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#sbitlinemetrics)), but not sure where the difference is coming from with pango. So to confirm - those grey-outlined bitmaps are what you see pango rendering it as?

```diff
diff --git a/fontforge/parsettfbmf.c b/fontforge/parsettfbmf.c
index 3b1f6b441..6c937a69a 100644
--- a/fontforge/parsettfbmf.c
+++ b/fontforge/parsettfbmf.c
@@ -521,8 +521,8 @@ void TTFLoadBitmaps(FILE *ttf,struct ttfinfo *info,int onlyone) {
        sizes[j].numIndexSubTables = getlong(ttf);
        if ( /* colorRef = */ getlong(ttf)!=0 )
            good = false;
-       sizes[j].ascent = getc(ttf);
-       sizes[j].descent = getc(ttf);
+       sizes[j].ascent = (int8)getc(ttf);
+       sizes[j].descent = (int8)getc(ttf);
        for ( k=0; k<12-2; ++k ) getc(ttf);     /* Horizontal Line Metrics */
        for ( k=0; k<12; ++k ) getc(ttf);       /* Vertical   Line Metrics */
        sizes[j].firstglyph = getushort(ttf);

```

**Comment by HW42** [comment]
Thank for looking into this!

> So to confirm - those grey-outlined bitmaps are what you see pango rendering it as?

Yes, the [second screenshot](https://user-images.githubusercontent.com/22183367/78467719-c3b73500-770f-11ea-8008-6d3b4c659a1e.png) with the grey border is how this gets rendered in xfce4-terminal which uses pango AFAIK. The screenshot has been created by showing the letter "P" surrounded by "Full block" characters (U+2588). After taking the screenshot I colored the surrounding black boxed grey and scaled it up for better visibility. The screenshot only shows one pixel around the letter

**Comment by jtanx** [comment]
Testing under arch linux with pango 1.44.7+11+g73b46b04-1 vs 1.43.0-2 I see no difference, testing with

```
pango-view  --background=black --foreground=white --font="Misc Fixed"  --dpi=72 -q -o pcf.png  b.log
pango-view  --background=black --foreground=white --font="Fixed"  --dpi=72 -q -o otb.png  b.log
```

PCF:
![pcf_143](https://user-images.githubusercontent.com/5137410/80852281-b5a2f880-8c6a-11ea-90b8-6fccbd54f82b.png)

OTB with pango 1.43:
![otb_143](https://user-images.githubusercontent.com/5137410/80852294-bdfb3380-8c6a-11ea-9822-53edd4d80dfa.png)

OTB with pango 1.44:
![otb_144](https://user-images.githubusercontent.com/5137410/80852298-c3587e00-8c6a-11ea-873d-2ae81f0df1a4.png)
