### ISSUE TITLE
Underline Position decreases each time a ttf file is opened

### ISSUE THREAD

**Issue by SWWEFHoiiqwdjxqo** [fontforge/fontforge#4264]
Font Info...\General\Underline Position
Have a font with Underline Position
Save as ttf
Open the ttf file
The resulting font now has a lower Underline Position. The more iterations of this are done, the lower the Underline Position. This means that each time the font designer cleans up the source font by saving as ttf and deleting the sfd file (which is done in practice when updating so that junk data like what part of the glyph is selected and fractional coordinates are eliminated), the font designer has to know readjust the Underline Position or risk unintended underline change in some applications, and if it's low enough it will disappear due to being clipped below font height boundaries (at least in reasonable rendering engines that know that portions of two different lines don't belong in one scanline).

**Comment by frank-trampe** [comment]
What version of FontForge are you using? We fixed a bug like this in 2018 as explained [here](https://fontforge.org/en-US/bulletins/underline_position_2018_1/).

**Comment by SWWEFHoiiqwdjxqo** [comment]
Oh god, you're right. I upgraded to update FontForge's perception of what Unicode is, but I overlooked those bugs. Closed as resolved.
