### ISSUE TITLE
Make the autohinter able not to change widths

### ISSUE THREAD

**Issue by yuiijjjjjjjjjjj** [fontforge/fontforge#4276]
As the autohinter makes the font too contain width changing instructions, it breaks monospaced and pseudomonospaced fonts.

**Comment by frank-trampe** [comment]
What instruction is that?

**Comment by yuiijjjjjjjjjjj** [comment]
I don't know.

**Comment by frank-trampe** [comment]
It is probably just the effect of adapting the hint grid to the pixel grid, which is a natural consequence of hinting. Many renderers will constrain geometry if they detect the font as being monospaced, which requires that all glyphs, including `.notdef`, have the same widths.

**Comment by yuiijjjjjjjjjjj** [comment]
Yeah no, not all renderers do this. And TrueType hinting is low level instructions, so in some way the autohinting probably does literally change widths. There are no "natural consequence"s, it's all in the instructions themselves. Try it yourself: in Visual TrueType, widths only change if the right side point is directly affected.

**Comment by frank-trampe** [comment]
I am aware that TrueType uses low-level instructions. I am not aware of an explicit instruction that changes the width of the glyph, and, absent specifics from you, I am inclined to believe that there is no such thing. Absent such an instruction, the only remaining explanation is that the resizing is a consequence of reconciling the adjusted points and the pixel grid.

It can't hurt to double-check the TrueType specification, but I would suggest checking that all of your glyphs have exactly the same width. If you are aware of a particular TrueType flag that some renderers use for explicit rather than implicit detection of monospace rendering preference, I would be curious to see it, as it seems a useful thing to implement.

**Comment by yuiijjjjjjjjjjj** [comment]
I doubt TrueType renderers know to "resizing is a consequence of reconciling the adjusted points and the pixel grid.". They are given instructions, and the instructions determine whether the width is changed. Instruction to change width works just like an instruction to change a point.

**Comment by skef** [comment]
@yuiijjjjjjjjjjj Given that you're experiencing this problem can you provide an example of it?

**Comment by frank-trampe** [comment]
@yuiijjjjjjjjjjj, I still think that it's rather unreasonable to insist that the people who maintain the software and read the specification don't understand TrueType when you refuse to read the specification yourself. And I likewise think it unreasonable to make us run in circles when you're unwilling to try the rather simple solution to your stated problem used by other monospaced fonts built with FontForge.

**Comment by frank-trampe** [comment]
@yuiijjjjjjjjjjj, since there is no evidence of a problem with FontForge itself, I'm going to close this issue. If you decide to try the same-width approach and have further problems, post your file here and we can try to figure out what's going on.

**Comment by yuiijjjjjjjjjjj** [comment]
From my experience, if the environment is designed to handle arbitrary widths then it doesn't hardcode any behavior for monospaced fonts so the instructions can change widths.

In TrueType you HAVE to specifically add instructions to change points. To think widths just change by themselves is a fallacy.

Here is an unhinted glyph example in VisualTrueType
![image](https://user-images.githubusercontent.com/63473040/79204794-64f36900-7e3d-11ea-8e56-8d37ab933599.png)

When instructions are not added on width, the width can't possibly change.
![image](https://user-images.githubusercontent.com/63473040/79205016-b3a10300-7e3d-11ea-837f-9e44a2526bbe.png)

Width may only change with an instruction on a specific point affecting width.
![image](https://user-images.githubusercontent.com/63473040/79205081-c4517900-7e3d-11ea-9239-732c4143e599.png)

I've done testing and it must be evident that it's plane lee visible that the widths are changed up.

[autohint.zip](https://github.com/fontforge/fontforge/files/4474228/autohint.zip) contains an original and autohinted version of a testing font. In GDI rendering it's clearly evident how it changes widths.

**Comment by yuiijjjjjjjjjjj** [comment]
You lost the argument already. Your theory is not true.

File\Preferences\TT Instrs\CounterControl is the problematic setting. If it's enabled, the widths change. If it's disabled, the widths don't change. The description does talk about widths, but I think it should be more clearly visible to the user that this is an option that changes widths.

**Comment by frank-trampe** [comment]
@yuiijjjjjjjjjjj, I'm glad you figured it out, but it seems rather childish to me to gloat over it. You enabled a non-standard setting and refused to share details or examples until just now. This isn't "stump the band" or some such game. We're actually trying to help you, and your rudeness and uncooperativeness do not make our job any easier or make you look any smarter.

Given the information that you provided, the most similar problem I had seen with FontForge was [the one](https://bugs.launchpad.net/ubuntu/+source/ttf-freefont/+bug/1001033) I mentioned previously. And, given your refusal to try that solution, it didn't make a lot of sense to keep brainstorming other possibilities.

For future reference, the `isFixedPitch` flag is actually set in FontForge (in `dumppfa.c`) based on the widths being identical, not inferred in the renderer.

I have never seen the counter control setting used. If we are to update the description, it might be worth examining and commenting the relevant source code first, mostly in `nowakowskittfinstr.c`, preferably with minimal whitespace changes.

**Comment by frank-trampe** [comment]
[Here](https://github.com/aseprite/freetype2/blob/fbbcf50367403a6316a013b51690071198962920/src/winfonts/winfnt.c#L783)'s the Freetype hack I was thinking of, by the way. Another reason to double-check glyph widths.
