### ISSUE TITLE
Problematic anti-aliasing in FreeType

### ISSUE THREAD

**Issue by ghost** [fontforge/fontforge#4279]
![image](https://user-images.githubusercontent.com/63473040/79224318-2bc9f180-7e5b-11ea-9556-429545d03f33.png)

1. There is no horizontal hinting. Above FontForge is classic GDI shown which is how it should render.

![image](https://user-images.githubusercontent.com/63473040/79224600-ac88ed80-7e5b-11ea-8fe6-d9fcf86e83d5.png)

2. Incorrect gamma. This screws with the rendering, making it inaccurate, and prevents the user from properly testing the readability of the font in sizes that are anti-aliased.

**Comment by mdpkh** [comment]
I think if you want horizontal hinting, you need to use FreeType engine 35

https://www.freetype.org/freetype2/docs/subpixel-hinting.html

**Comment by yuiijjjjjjjjjjj** [comment]
> 
> 
> I think if you want horizontal hinting, you need to use FreeType engine 35
> 
> https://www.freetype.org/freetype2/docs/subpixel-hinting.html

Are you sure there is such a setting in FontForge?

**Comment by ctrlcctrlv** [comment]
Closed as irrelevant, user's account gone

**Comment by fundamentals-fontdevelopment** [comment]
Unclose this. This is confirmed to be an actual issue, as the preview looks completely different from actual anti-aliased text.
