### ISSUE TITLE
FontForge completely f***s over if bdf file is attempted to be exported twice

### ISSUE THREAD

**Issue by ghost** [fontforge/fontforge#4282]
* Save a bdf font
* Save a bdf font again

In Microsoft Windows, FontForge now gets completely f***ed and the save window  cannot be exited.

**Comment by frank-trampe** [comment]
@yuiijjjjjjjjjjj, this is not a men's locker room. I would suggest adjusting the wording of the text and the title as soon as possible.

**Comment by frank-trampe** [comment]
I've fixed it for you.

**Comment by ctrlcctrlv** [comment]
Superseded by #4328.
