### ISSUE TITLE
Kerning does not appear

### ISSUE THREAD

**Issue by NewOlder7** [fontforge/fontforge#4283]
Hey there,
I am struggling with **kerning** by class after generating. The kerns do **not appear**... I fully followed this [tutorial](http://designwithfontforge.com/en-US/The_Final_Output_Generating_Font_Files.html) and tried a lot of things, but nothing worked. I searched the internet also, but I couldn't find exactly my problem. I am using Windows 7 and the version of FontForge from 2.6. 2019.

Here are my actions
1 | Validating font | Without problems.
2 | Generating font
![generating font](https://user-images.githubusercontent.com/63813215/79494525-7302de80-8023-11ea-957c-db221b871ff4.png)
![Generate fonts controls](https://user-images.githubusercontent.com/63813215/79494537-77c79280-8023-11ea-902f-60a5d1ce3f36.png)

The font is TrueType so it's height is 1024. After generating I open the generated font with FontForge and no errors appear. All kerning classes are still where they were just converted into one class.
For Kerning I use only GPOS so it is not broken with GSUB
![Kerning classes before](https://user-images.githubusercontent.com/63813215/79494568-8615ae80-8023-11ea-8252-919064099b85.png)

And if I see the preview of the font are write with it in an application, the kerning classes are somehow ignored.
This is how the preview looks
![kern is](https://user-images.githubusercontent.com/63813215/79494585-8ca42600-8023-11ea-9e90-4cfbee225ff2.png)

And this is how the preview should look like with kerning.
![kern should be](https://user-images.githubusercontent.com/63813215/79494599-93cb3400-8023-11ea-8742-13fcb246d9f3.png)

I hope there is a solution and that we will find it.

**Comment by ctrlcctrlv** [comment]
Why is &laquo;OpenType&raquo; / &laquo;Old style `kern`&raquo; unticked? The &laquo;Windows-compatible `kern`&raquo; does nothing if the `kern` table isn't being generated at all.

**Comment by NewOlder7** [comment]
@ctrlcctrlv I have tried it, but it still doesn't work... Btw I thought that if I export the font as TrueType I don't have to tick OpenType.

**Comment by NewOlder7** [comment]
I tried to create to do the font again just with two letters as a TrueType and the kerning class worked perfectly...

**Comment by KamilLanda** [comment]
I know 3 ways how to do kerning for latin script - 1) Pair Position (kerning), 2) Contextual Chaining Position, 3) Contextual Position

I tested my fonts in LibreOffice and Opera and Firefox, but some aplications have some problems with some variants. 

You can explore some examples for inspiration. Font with Pair Position (kerning) https://github.com/ctrlcctrlv/QuaeriteRegnumDei

And example with Contextual Chaining Position (options: By Classes & Simple) and Contextual Position (By Coverage & Simple) -> there are kernings for AB, AC, DE, DF. 
[Cant.zip](https://github.com/fontforge/fontforge/files/4492214/Cant.zip)

My experience with Contextual and Contextual Chaining: sometimes is non-functional Contextual and for some variants in non-functional Chaining -> but I tried it mainly for arabic font, no for latin scripts. 

My options for generating are 
![font-options](https://user-images.githubusercontent.com/61148366/79557925-af761f00-80a3-11ea-9c09-e7672c725604.png)

**Comment by NewOlder7** [comment]
Well, I am using the first way (Pair positions) by classes. I always test my fonts in Inkscape. Once the kerning worked so I am sure it works there. I will try it again from the start and will see if it will work...

**Comment by NewOlder7** [comment]
Okay, I tried it again and it doesn't work. I am looking for advice on what not to do if I want to export TrueType font's kerning classes correctly.

For removing errors I use Element -> Overlap -> Remove Overlap; Element -> Add Extrema; PS Private -> BlueValues; Lookups -> GPOS -> Pair Position (with custom table names)

Please help. If you see any mistakes in it or want me to post some additional details, not problem.

**Comment by KamilLanda** [comment]
Can you upload your FEA file? Or make FEA with definitions only for few letters - if you don't want to share complete file. I can try to find the bug.

**Comment by NewOlder7** [comment]
Okay, Github doesn't support .sfd so the [link](https://www.dropbox.com/s/qt0r4i654ra451g/Preview.sfd?dl=0) (Dropbox).

**Comment by KamilLanda** [comment]
I moved Class Upper & Upper to the top position and it was functional. 
![top-position](https://user-images.githubusercontent.com/61148366/79610956-d4957c80-80f9-11ea-87d9-ebf11e0ac2fd.png)

Maybe solution could be more lookups with one subtable, than more subtables in one lookup. Or hard and obfuscated version with all definitions in one subtable in one lookup.

**Comment by ctrlcctrlv** [comment]
Thanks @KamilLanda, you are correct: each kerning lookup should go in its own subtable when character coverage overlaps. 

The technical reason was explained in https://github.com/fontforge/fontforge/issues/3435#issuecomment-460975472:

>Multiple subtables are supported, but multiple subtables where character coverage overlap will not do what you expect; since a character that is covered in one subtable will be skipped for all subsequent subtables. Either merge the subtables or split them into different lookups.
>
> There is no FontForge issue here, FontForge is compiling the GPOS lookups as you created them faithfully, but your lookups don’t do what you think they are doing. I doubt that you will find any implementation where your GPOS kerning works, but even if you do it is still not a FontForge issue.
>
> For better or worse, FontForge representation of OpenType lookup is very close to the metal with little abstraction, this can make it clumsy to use at times, but on the other hand you can create pretty much any lookup supported by the standard (which is not the case for some other higher level representations).

Closing as question has been answered.

**Comment by NewOlder7** [comment]
Wow, thanks a lot.
