### ISSUE TITLE
[Question] How I can test fonts without installing?

### ISSUE THREAD

**Issue by xmha97** [fontforge/fontforge#4302]
Hello
How I can test fonts without installing?

![Windows 10](https://user-images.githubusercontent.com/23485114/80420731-7c782a80-88f0-11ea-8aa2-61b1649c3653.png)

**Comment by ctrlcctrlv** [comment]
Metrics View or third-party scripts/command line tools. Please use the mailing list or IRC for questions, that's not the purpose of this website.

**Comment by GTMxCode** [comment]
Id actually love to know of a solution for this as well. I've got font manager tools just like everyone else but when youve got 56 fonts per family and each "family" has a slightly different set of build parameters youre trying to dial in, it gets really cumbersome really quickly.. 

Not sure if youre familiar, but One thing I know of is the AFDKO library of tools,: https://adobe-type-tools.github.io/afdko/AFDKO-Overview.html, which includes  a number of proofing font proofing tools that can compare and output fonts in various different ways.  Here is an example of one of the tools called waterfallplot: https://i.imgur.com/2VeOuro.png. 

Still though at the end of the dayits eventually gonna mean installing fonts
