### ISSUE TITLE
Expose reference selection in python API

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#4303]
The current python API can adjust glyph contours (by point) and also references (by transformation matrix). However, in order to build interactive scripts that register menu items it helps to have some sort of UI. For contours the UI is typically based on point selection, which is how a lot of FontForge built-ins work. References can also be selected in FontForge but their selection status is not exposed in the API. We should do that. 

My inclination would be to add a third boolean element to the reference tuple to indicate if it is selected. Of course, this is likely to break some existing scripts. We can make the assignment code tolerant to omitting the value to reduce that breakage somewhat.

**Comment by skef** [comment]
@frank-trampe Any thoughts on this? Could we maybe ask the mailing list about expanding the tuple while making the third element optional on assignment?

**Comment by ctrlcctrlv** [comment]
I have no problems with the change fwiw

**Comment by frank-trampe** [comment]
This sounds fine to me. We're starting to hit the readability limits of the tuple, but it's too late to go back now.
