### ISSUE TITLE
Element > Build menu is greyed out, cannot Build Accented Glyph

### ISSUE THREAD

**Issue by probonopd** [fontforge/fontforge#4304]
I am trying to use the Build Accented Glyph feature as was suggested in https://github.com/fontforge/fontforge/issues/283#issuecomment-621458394.

In [this font](https://github.com/probonopd/font-rotation/tree/master/source/SeN-CBL.ufo), we already have the lowercase ‘a’ (u+0061) and the standard 'acute' (u+00b4) character but not the ‘acutecomb’ glyph (u+0301).

Using `FontForge-2020-03-14-67687b0-x86_64.AppImage` on Ubuntu 18.04.4 LTS, going to the ‘a acute’ character slot (u+00e1) and using the ‘Element > Build > Build Accented Glyph’ function as per the instructions does not work because __the ‘Element > Build' menu is greyed out__.

http://designwithfontforge.com/en-US/Diacritics_and_Accents.html says:

> So, using the example of building the ‘a acute’ character (u+00e1) , we would need to have already created the lowercase ‘a’ (u+0061) and the ‘acutecomb’ glyph (u+0301). Then selecting the ‘a acute’ character slot and using the ‘Element > Build > Build Accented Glyph’ function, FontForge will place a reference to the lowercase ‘a’ glyph and a reference to the ‘acutecomb’ glyph into the ‘a acute’ character slot (see below).

> It should be noted here that if you are not using anchors and lookup tables to position diacritic marks, then, if the glyph of a particular diacritic mark is not present in your font, FontForge will instead use a similar spacing character in place. For example, if the combining mark 'acutecomb' (u+0301) is not present, then FontForge will use the standard 'acute' (u+00b4) character when it automatically builds any acute accented glyphs. If the 'acutecomb' is present, then FontForge will always use that, unless you specifically force FontForge to use spacing characters for building accented glyphs.

**Comment by probonopd** [comment]
Turns out the  ‘Element > Build' menu is greyed out if the characters that are needed to build the accented graph are not there in the font. 

To find out which characters must be there, go to Element -> Glyph Info... -> Components. It will show exactly which Unicode characters need to be there and also allows to use custom ones.

**Comment by skinkie** [comment]
I hope this could be added to the FAQ.

**Comment by ctrlcctrlv** [comment]
Good idea. Sorry I neglected to do so when I added the feature.
