### ISSUE TITLE
"Scale width" grayed out

### ISSUE THREAD

**Issue by d01010101** [fontforge/fontforge#4323]
The option to scale the glyph width is grayed out for uniform/nonuniform scale. I tried different ratios, different combinations of options and different fonts, it did not help though.

Build 2020-03-06

**Comment by ctrlcctrlv** [comment]
I'm not sure what you mean. Are you talking about &laquo;Element&rarr;Transformations&rarr;Transform&hellip;&raquo;?

**Comment by d01010101** [comment]
Yes. Element's width cannot be scaled likewise. It seems that the option is grayed out unless all elements in the font are selected. Possibly there is a reason for that.

**Comment by ctrlcctrlv** [comment]
It's not greyed out for me. I need exact steps.

**Comment by d01010101** [comment]
I tested it now in multiple cases, and it seems that it sometimes does not work on some glyphs in some fonts. Possibly ones with mixed outlines and references to outlines. I am not sure if there is a test which show this in a repeated manner. Feel free to close the issue.

**Comment by ctrlcctrlv** [comment]
Closed per request of author, due to lack of test case.
