### ISSUE TITLE
Exporting a font containing glyph with a cubic curve segment containing a single off-curve point results in broken output

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4327]
### When reporting a bug/issue:
- [x] Screenshot
Teardrop.sfd's `Q`:
![image](https://user-images.githubusercontent.com/838783/81373363-72ed8000-90b1-11ea-9e69-4890ac0250af.png)
When roundtripped:
![image](https://user-images.githubusercontent.com/838783/81373459-a92aff80-90b1-11ea-8257-9473a224350c.png)

    Teardrop.sfd's `R`:
![image](https://user-images.githubusercontent.com/838783/81373584-eabbaa80-90b1-11ea-95e6-39667db05268.png)
    When roundtripped:
![image](https://user-images.githubusercontent.com/838783/81373560-dc6d8e80-90b1-11ea-83c3-82a86f72b4fb.png)

    Teardrop.sfd's `S`:
![image](https://user-images.githubusercontent.com/838783/81373714-3cfccb80-90b2-11ea-9dcc-cde99701bcdb.png)
    When roundtripped:
![image](https://user-images.githubusercontent.com/838783/81373721-41c17f80-90b2-11ea-9749-03ba21c08963.png)

- [x] The FontForge version and the operating system you're using
https://github.com/fontforge/fontforge/commit/21d929bbc2883a36963ef8dcc3952c8d93c40d1f, Win32 (also tested same version on Xubuntu)
- [x] The behavior you expect to see, and the actual behavior
FontForge generates a bad UFO that neither it, nor `fontmake`, can understand. As @skef has pointed out in #4321:
    
    > 01:19:22 skef As I note in that bug it's just a FontForge design error that you can create a cubic spline with one control point on a segment.
    > 01:20:07 skef Any time there is one control point the other control point should be treated as present and co-located with its on-curve point
    

    Our `S.glif` gets written, though, as:
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <glyph name="S" format="2">
      <advance width="1000"/>
      <unicode hex="0053"/>
      <outline>
        <contour>
          <point x="123" y="524" type="line"/>
          <point x="609" y="716"/>
          <point x="823" y="524" type="curve"/>
          <point x="823" y="208" type="line"/>
          <point x="123" y="208" type="line"/>
        </contour>
      </outline>
    </glyph>
   ```
- [x] Steps to reproduce the behavior 
1. File [teardrop.sfd](https://github.com/fontforge/fontforge/files/4597149/teardrop.zip)
2. Export UFO
3. Reopen UFO, or use in `fontmake`
- [x] \(optional) Possible solution/fix/workaround
Always write two off-curve points for cubic splines. Co-locate one if missing.

Can you please fix this @frank-trampe ? I don't have time to patch it right now.

**Comment by skef** [comment]
This is a manifestation of #4125 . A central fix would be ideal but would take some work so it may make sense to patch the edges as a stop-gap and sanity check.
