### ISSUE TITLE
Generate BDF stops working after one run

### ISSUE THREAD

**Issue by gingerbeardman** [fontforge/fontforge#4328]
### When reporting a bug/issue:
- [ ] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [X] Steps to reproduce the behavior 
- [X] \(optional) Possible solution/fix/workaround

## The FontForge version and the operating system you're using
FF 2020-03-14

## Steps to reproduce the behavior 
1. Open TTF file
1. Element > Bitmap Strikes Available... > (enter pixel size of font)
1. File > Generate Fonts... > Generate > OK

(works)

### Now repeat this step:
1. File > Generate Fonts... > change pixel size of output > Generate > OK

(error noise, no files are produced)

## Possible solution/fix/workaround
1. close and relaunch FF
1. redo the generate

**Comment by gingerbeardman** [comment]
Thanks to all

**Comment by yg8ijvjvjv** [comment]
This was also a regression, because in the 2017-07-31 version there wasn't a problem with exporting multiple bitmap fonts.
