### ISSUE TITLE
Failing to build on 64-bit macOS (can't map file, errno=22 file '/Library/Frameworks/freetype.framework' for architecture x86_64)

### ISSUE THREAD

**Issue by gingerbeardman** [fontforge/fontforge#4330]
## When reporting a bug/issue:
- [X] Screenshot
- [X] The FontForge version and the operating system you're using
- [X] The behavior you expect to see, and the actual behavior
- [X] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### The FontForge version and the operating system you're using

20200314

### The behavior you expect to see, and the actual behavior

Should build, but errors:

> can't map file, errno=22 file '/Library/Frameworks/freetype.framework' for architecture x86_64

![Screen shot 2020-05-09 at 08 50 36](https://user-images.githubusercontent.com/49612/81467662-28aff000-91d2-11ea-96d6-41604698b175.png)

### Steps to reproduce the behavior 

Follow build instructions on 64-bit macOS. I'm on Mojave 10.14.6 (18G4032)

**Comment by gingerbeardman** [comment]
Have just downloaded latest build from http://dl.bintray.com/fontforge/fontforge/

Thanks to https://github.com/fontforge/fontforge/pull/4329#issuecomment-626124427

**Comment by jtanx** [comment]
Are you using any of homebrew, macports or fink? We/I typically build with homebrew which seems to work ok.

**Comment by gingerbeardman** [comment]
Yes, I'm using homebrew.

**Comment by jtanx** [comment]
Do you have the freetype homebrew package installed?

**Comment by gingerbeardman** [comment]
Yes, installed via home-brew (I also tried force uninstalling and then reinstalling it)

**Comment by gingerbeardman** [comment]
```
$ file /Library/Frameworks/freetype.framework/Versions/A/freetype
/Library/Frameworks/freetype.framework/Versions/A/freetype: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386]
/Library/Frameworks/freetype.framework/Versions/A/freetype (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
/Library/Frameworks/freetype.framework/Versions/A/freetype (for architecture i386):	Mach-O dynamically linked shared library i386
```
