### ISSUE TITLE
Crash when setting a glyph comment containing a surrogate

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4331]
The following script crashes FontForge 20200314. I am using macOS 10.14.6.
```python3
import fontforge
fontforge.font().createChar(0x30).comment = '\ud800'
```
[Here is a crash report.](https://github.com/fontforge/fontforge/files/4618043/fontforge_2020-05-12-153621.txt)

**Comment by ctrlcctrlv** [comment]
You also need to try post- 127900aa.

**Comment by dscorbett** [comment]
The same thing happens.

**Comment by ctrlcctrlv** [comment]
Thanks for checking that for me before I tried myself. I see the problem, the patch is simple, but while I'm here I'm going to improve some other cases as well.
