### ISSUE TITLE
The GPL is not an EULA

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4335]
This step in the Win32 installer is unnecessary and should be removed:

![image](https://user-images.githubusercontent.com/838783/82069297-f7c73380-9687-11ea-8ec5-3455f557d24c.png)

I might be able to fix this myself, I do need to figure out our Win32 story anyway as discussed in #4321.

(Request [via ](https://twitter.com/HW_BEAT_THAT/status/1261320417370759171)@foone on Twitter.)

**Comment by JoesCat** [comment]
I'm a little puzzled why you would want to remove this.
I've seen this in quite a few installers...
I thought I saw it in...
Libre Office, GIMP, InkScape, Scribus, just to name a few...

I'm pretty sure I just recently saw it while installing Git, NotePad++, and a couple other dev tools,
and...
...I've certainly seen it included in upgrades to some pretty expensive test equipment that contains both proprietary as well as open source software...for more than one company in the biz.

benefits:
You're telling the end user the "can" and "cannot",
https://www.tldrlegal.com/l/bsd3 and https://www.tldrlegal.com/l/gpl-3.0

... plus you are also "reminding the end user" that if something breaks, you're not expected to pay for it or to fix it. You've probably seen similar requirements in commercial software.

**Comment by skef** [comment]
> I'm a little puzzled why you would want to remove this.

One reason is that it increases the kind of confusion evident in #4188

**Comment by ctrlcctrlv** [comment]
Another reason is, as I wrote on the PR:

> [W]e're something of a holdout. I agree that this was once very fashionable, but most other projects have stopped doing it after user complaints such as the original one that brought about this change.

There's no reason to do this only on Win32.
