### ISSUE TITLE
Feature request: Remove points tool

### ISSUE THREAD

**Issue by probonopd** [fontforge/fontforge#4337]
> A description of the problem you're trying to solve, including _why_ you think this is a problem

According to the [Adobe Type 1 Font Format specification (“black book”)](https://www-cdf.fnal.gov/offline/PostScript/T1_SPEC.PDF), one should “use the fewest Bézier curve segments that accurately represent a shape.”

It would be nice to have a tool that would allow the user play "font mikado", that is to remove points from an outline while keeping the change to the resulting shape as unchanged as possible by adjusting the remaining control points:

![](https://user-images.githubusercontent.com/2480569/82126422-39490300-979c-11ea-8a38-7750d0aaf0d7.gif)

(Screen recording from [DTL LetterModeller](https://www.lettermodel.org/?page_id=13))

> If the feature changes current behavior, reasons why your solution is better

Currently deleting a point just removes the point and opens the outline, resulting in a damaged outline.

> Possible solution/fix/workaround

Use a convoluted workflow described at https://medium.com/@probonopd/font-mikado-making-a-libre-typeface-and-learning-a-lot-e5e200eead5b.

**Comment by skef** [comment]
@probonopd Try selecting the candidate points (or the whole contour) and playing around with Element -> Simplify -> Simplify and ... -> Simplify More

**Comment by skef** [comment]
Or if you're just interested in the individual point try selecting the point you want to remove and selecting Edit -> Merge (which is also available in the right-click menu).

**Comment by probonopd** [comment]
Hi @skef __Edit --> Merge__ is indeed exactly what I was looking for. Thanks a lot!

**Comment by probonopd** [comment]
There is some intermittent weirdness - see where I struggle on the right-hand side when I have to redo my change only to retry it at the end (when it succeeds)...

![mikado](https://user-images.githubusercontent.com/2480569/82152969-3dd0f280-9854-11ea-8882-198800e84fc6.gif)

**Comment by skef** [comment]
You can see at the "weirdness point" that the point you didn't want merged was still selected. So to the extent there is weirdness it's with the selections rather than the Merge method. Unfortunately I can't tell what happened just from the diagram.

**Comment by skef** [comment]
> (Is it just me that I didn't find it? Could it be added as a tool to the tool palette for better discoverability?)

I think in general the tools palette is for functions that need dragging. You're not knowing about it is more of a documentation issue. The "old" docs have been and continue to be structured and pointed to in a way such that almost no one looks at them and "Design With FontForge" is (as you've seen) limited in what it covers.

**Comment by probonopd** [comment]
Agree it's mostly about documentation.

By the way, with the same number of points LetterModeller and FontForge come to subtly different solutions. Without knowing the maths underneath both, it's hard to say which one is "correct"...

![](https://user-images.githubusercontent.com/2480569/82154027-bb97fc80-985a-11ea-9977-be205ad98cc2.png)

**Comment by skef** [comment]
@probonopd Copy the original into FontForge's background layer to compare the outlines with each.

**Comment by probonopd** [comment]
Good idea. Turns out that FontForge gives the result closer to the original. :+1:

**Comment by probonopd** [comment]
Thanks @skef. The comparison shows that FontForge is a bit closer to the original shape :+1:
