### ISSUE TITLE
Fontforge ui fonts not displaying properly

### ISSUE THREAD

**Issue by darkyellow** [fontforge/fontforge#4340]
Hi

I did a git clone on the font forge repository as I wanted to have a version built that has the bytecode interpretter enabled.

My OS is Ubuntu 20.04

As you can see below the open font dialog has square's with 4 numbers in (in the box where you type or select the filename), I beleive this represents the unicode of the character.

![Screenshot from 2020-05-19 08-51-28](https://user-images.githubusercontent.com/2061348/82299900-01190e80-99ae-11ea-9f9e-3e2675bede62.png)

Also another screenshot from the bytecode interpretter itself. You can see the dialog on the right with the square boxes in.

![Screenshot from 2020-05-19 08-54-48](https://user-images.githubusercontent.com/2061348/82300337-961c0780-99ae-11ea-88d2-4c2cf3c2fc3b.png)

Is there anything in the build I missed? Or do I need something switched on to display the unicode fonts correctly? Or is there a font missing on my system?

**Comment by jtanx** [comment]
Sound like either you're missing fonts or your fontconfig is broken. Also how are you running FontForge, directly out of the build/bin folder, or are you installing it first? Can you try installing it (choose a suitable CMAKE_INSTALL_PREFIX if you don't want it ending up in /usr/local)

**Comment by darkyellow** [comment]
I was using from build/bin, have built and installed now. I ran the binary the system area and it fixed the open font dialog (also made it look like the packaged version). And it also fixed some other dialogs where the text was weird.

But the bytecode interpretter screen still shows the squares, do you know what font the window uses? Or how to rebuild font config (as you mentioned thatmight be broken)?

**Comment by darkyellow** [comment]
The issue is also on this preferences screen

![Screenshot from 2020-05-20 05-38-15](https://user-images.githubusercontent.com/2061348/82405954-34ff3d00-9a5d-11ea-8f8c-46d2abaf0871.png)

Here is the font open dialog working post ninja install

![Screenshot from 2020-05-20 05-47-22](https://user-images.githubusercontent.com/2061348/82406019-74c62480-9a5d-11ea-8ad4-757c37c8a9df.png)

and the bytecode instruction screen not working

![Screenshot from 2020-05-20 05-48-25](https://user-images.githubusercontent.com/2061348/82406096-a4752c80-9a5d-11ea-9243-91b921b35e9c.png)

I have tried looking at the code to find the dialog box for the byte code interpretter but its not that obvious where to look.

**Comment by skef** [comment]
@darkyellow Can you try the following:

1. Open the Elements -> Font Info ... dialog, pick "Lookups" on the right, and see if you have the same problem in the lookups window as in the Preferences dialog.
2. If you do, try following the instructions [here](https://github.com/fontforge/fontforge/issues/4238#issuecomment-602326591) to see if that fixes the problem with Font Info/lookups. (This is a little tricky, as you'll have to create a resource file if you don't have one via File -> X-Resource Editor -> Save As and then edit that file to add the line changing the font.) 

If you have the same problem and it does work, that suggests that you've found a few other places were FontForge chooses a font via `SANS_UI_FAMILIES` directly and that's not working on your system (for whatever reason). If it doesn't we can do a bit more research.

**Comment by darkyellow** [comment]
The Lookups looks fine unfortunately.

![Screenshot from 2020-05-20 10-14-46](https://user-images.githubusercontent.com/2061348/82428769-e795c680-9a82-11ea-8d85-eab495e2ade3.png)

**Comment by skef** [comment]
Ah, OK, it's the monospace fonts that are the problem. Try fiddling with File -> X Resource Editor -> Text Field (on the left) -> Font (towards the bottom). If you can't read the entry cut and paste to some text editing context that doesn't have the problem. (That should change the save dialog name field at a minimum.)

**Comment by darkyellow** [comment]
Hi, I am not quite sure what I am supposed to be doing here. All the fields in X Resource Editor look fine and the save dialog is fine. 

What type of widget is the Preferences - Mac and Byte Code Interpreter window? 
Should I inherit all the font properties to GGadget?

**Comment by skef** [comment]
Is the text field in the Save Dialog fine? Weird that it would be OK but the Open Font dialog wouldn't be. 

I'm suggesting changing the font selection string to some other font on your system and then opening the dialog to see if the problem is resolved. It should work the same way with the "Open Font" problem you screenshot above. 

Broadly speaking the "Preferences - Mac" widget is a GList but that doesn't entirely explain its typical font.

**Comment by darkyellow** [comment]
I think you missed the bit above, the open font dialog wasn't working, but after being told to ninja install then run rather than running from the build area the open font dialog issue resolved itself.

The Preferences - Mac and byte code debug are the windows that are broken still.

**Comment by skef** [comment]
Oh, sorry. Let me try to nail down the path by which that font is selected.

**Comment by skef** [comment]
Alright, the search string being used for the Preferences -  Mac widget (and probably the other one) is `"courier,monospace,clearlyu,unifont,unifont upper"`. Therefore the first thing I would look for on your system is a bogus Courier somewhere.

**Comment by skef** [comment]
One possible shortcut is to install the `strace` package (if you don't have it already), Invoke FontForge from the command line with `strace -o /tmp/fftrace.txt fontforge` (and whatever arguments you want to pass after), making sure you bring up the problematic dialog. Then `grep -i courier /tmp/fftrace.txt` to see what it might be opening.

**Comment by darkyellow** [comment]
I tried that but there was no courier in the 

I get this for monospace

access("/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", R_OK) = 0
access("/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", R_OK) = 0
readlink("/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", 0x7ffef3aa2ba0, 4095) = -1 EINVAL (Invalid argument)
stat("/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", {st_mode=S_IFREG|0644, st_size=943, ...}) = 0
openat(AT_FDCWD, "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", O_RDONLY|O_CLOEXEC) = 6

and this for unifont

access("/etc/fonts/conf.d/69-unifont.conf", R_OK) = 0
access("/etc/fonts/conf.d/69-unifont.conf", R_OK) = 0
readlink("/etc/fonts/conf.d/69-unifont.conf", "../conf.avail/69-unifont.conf", 4095) = 29
stat("/etc/fonts/conf.avail/69-unifont.conf", {st_mode=S_IFREG|0644, st_size=847, ...}) = 0
openat(AT_FDCWD, "/etc/fonts/conf.avail/69-unifont.conf", O_RDONLY|O_CLOEXEC) = 6
access("/etc/fonts/conf.avail/69-unifont.conf", R_OK) = 0
access("/etc/fonts/conf.avail/69-unifont.conf", R_OK) = 0
readlink("/etc/fonts/conf.avail/69-unifont.conf", 0x7ffef3aa2ba0, 4095) = -1 EINVAL (Invalid argument)

courier and clearlyu had no results

**Comment by skef** [comment]
Sorry, my knowledge of contemporary Linux font resolution is spotty.

Somewhere in the trace FontForge is likely opening a file with "metric-aliases" in the path. If you look at that file it will have substitutions for various font names, probably including Courier. (On mine it mentions "Nimbus Mono" and "TeX Gyre Cursor" -- "Courier New" should be treated as a separate font.) Take a look and see if FontForge opened any of the alternates.

**Comment by darkyellow** [comment]
My knowledge of fonts is pretty spotty too :) I'm in it for debugging the reading of fonts rather than creating new fonts.

So I looked at everything you mentioned Nimbus Mono PS and TeX Gyre Cursor are the two that came up, I searched for these in the file but I saw nothing about trying to open actual font files. It was just looking at the font config data for those fonts. 

I did notice this in the font view application though (the same squares, but not for the exact fonts in courier) so I will look further in to this as this could be linked to the reason

![Screenshot from 2020-05-20 16-37-02](https://user-images.githubusercontent.com/2061348/82466375-3d389600-9ab8-11ea-9045-76fe27262247.png)

![Screenshot from 2020-05-20 16-37-18](https://user-images.githubusercontent.com/2061348/82466390-432e7700-9ab8-11ea-86a1-f0222b4b1b48.png)

**Comment by skef** [comment]
@darkyellow Make sure you search for "Nimbus" with a capital N, as the actual font file is capitalized.

**Comment by ctrlcctrlv** [comment]
User obviously has a misconfigured system. This has nothing to do with FontForge and is not a FontForge bug. You have bad fonts installed either with the same name as one Pango expects to be good, or your system is messed up in some finish way. 

This is not a forum for Linux tech support, so this issue has been closed.

**Comment by ctrlcctrlv** [comment]
Hello my friend @darkyellow. I don't think I was wrong to dismiss your report, since I was indeed right, this is not a FontForge issue, but an Ubuntu issue, and this is not an Ubuntu support site.

Unfortunately, it's an Ubuntu issue I came to share with you recently. However, I'm much more stubborn than you are about not reinstalling systems, it seems. (Or, rather, I seem to know more of how the system works, so I have a better chance at fixing it.)

Be that as it may, it's unlikely (m)any other programs will suffer from this, as they almost always prioritize `monospace` over `courier` in Fontconfig, and we don't. We might want to stop doing that, at least on GNU/Linux.

I'd like to advise you that I am virtually certain that this will happen to you again if you reinstall TeXLive! So perhaps you want to hear the fix. Perhaps you will also wish to hear about how the system works so you can later fix it yourself? :wink:

I saw the same as you, broken "hex" glyphs instead of my expected monospace glyphs.

I ran `fontforge` as `FC_DEBUG=5 fontforge`, and saw ...

```
Match Pattern has 26 elts (size 32)
        family: "courier"(s) "Nimbus Mono PS"(s) "Nimbus Mono"(s) "Nimbus Mono L"(s) "TeX Gyre Cursor"(s) "Nimbus Mono PS"(s) "DejaVu Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "DejaVu LGC Sans Mono"(w) "DejaVu Sans Mono"(w) "Bitstream Vera Sans Mono"(w) "Inconsolata"(w) "Andale Mono"(w) "Courier New"(w) "Cumberland AMT"(w) "Luxi Mono"(w) "Nimbus Mono L"(w) "Nimbus Mono PS"(w) "Nimbus Mono"(w) "Nimbus Mono PS"(w) "Nimbus Mono PS"(w) "Courier"(w) "Nimbus Mono PS"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgMono"(w) "Noto Sans Mono CJK JP"(w) "Noto Sans Mono CJK KR"(w) "Noto Sans Mono CJK SC"(w) "Noto Sans Mono CJK TC"(w) "Noto Sans Mono CJK HK"(w) "Khmer OS System"(w) "Miriam Mono"(w) "VL Gothic"(w) "IPAMonaGothic"(w) "IPAGothic"(w) "Sazanami Gothic"(w) "Kochi Gothic"(w) "AR PL KaitiM GB"(w) "MS Gothic"(w) "UmePlus Gothic"(w) "NSimSun"(w) "MingLiu"(w) "AR PL ShanHeiSun Uni"(w) "AR PL New Sung Mono"(w) "HanyiSong"(w) "AR PL SungtiL GB"(w) "AR PL Mingti2L Big5"(w) "ZYSong18030"(w) "NanumGothicCoding"(w) "NanumGothic"(w) "UnDotum"(w) "Baekmuk Dotum"(w) "Baekmuk Gulim"(w) "TlwgTypo"(w) "TlwgTypist"(w) "TlwgTypewriter"(w) "TlwgMono"(w) "Hasida"(w) "Mitra Mono"(w) "GF Zemen Unicode"(w) "Hapax Berbère"(w) "Lohit Bengali"(w) "Lohit Gujarati"(w) "Lohit Hindi"(w) "Lohit Marathi"(w) "Lohit Maithili"(w) "Lohit Kashmiri"(w) "Lohit Konkani"(w) "Lohit Nepali"(w) "Lohit Sindhi"(w) "Lohit Punjabi"(w) "Lohit Tamil"(w) "Meera"(w) "Lohit Malayalam"(w) "Lohit Kannada"(w) "Lohit Telugu"(w) "Lohit Oriya"(w) "LKLUG"(w) "FreeMono"(w) "monospace"(s) "Terafik"(w) "clearlyu"(s) "unifont"(s) "unifont upper"(s) "Courier New"(w) "Cousine"(w) "Liberation Mono"(w) "Cumberland"(w) "Cumberland AMT"(w) "Courier"(w) "monospace"(w) "monospace"(w) "monospace"(w) "monospace"(w) "monospace"(w) "monospace"(w) "monospace"(w) "Courier"(w) "FreeSans"(w) "Arial Unicode MS"(w) "Arial Unicode"(w) "Code2000"(w) "Code2001"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w) "sans-serif"(w)
[...]
Best score 0 0 0 0 0 0 0 0 0 0 21 0 0 0 0 0 0 0 0 0 0 0 0 0 2.14748e+12
Pattern has 21 elts (size 21)
        family: "Courier"(w)
[...]
        file: "/usr/share/fonts/type1/texlive-fonts-recommended/pcrr8a.pfb"(w)
```

Quoth the raven: "_yuck!_"

We can confirm Fontconfig is the problem by asking it for Courier:

```
osboxes@osboxes:~/Workspace/tex$ fc-match 'Courier'
pcrr8a.pfb: "Courier" "Regular"
```

Why are we prioritizing a type 1 font for "Courier"? Well, TeXLive installed it, and for some reason, Ubuntu is treating it as a system font, and not just a TeXLive font.

But...Ubuntu doesn't seem to be able to understand Type 1 system fonts. So we get a broken font in FontForge. Wonderful. 🙄

OK, so here's how to fix it.

Put this in `~/.config/fontconfig/fonts.conf`:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
<selectfont>
    <rejectfont>
        <pattern>
            <patelt name="fontformat" >
                <string>Type 1</string>
            </patelt>
        </pattern>
    </rejectfont>
</selectfont>
</fontconfig>
```

This will tell Fontconfig not to pass any Type 1 fonts to the system. This should be default. You may also place it in `/etc/fonts/conf.avail` and symlink it to `/etc/fonts/conf.d`, of course.

Why is it broken? I don't know. Are all Type 1 fonts broken, or is this too wide a restriction? I also don't know. You may of course look into Fontconfig configuration yourself if you wish to narrow the prohibition, I have no desire to do so. Will this break TeXLive? I also don't know, because I don't care to use Type 1 fonts in TeXLive, I only use `xelatex`.

Good luck to all :-)

**Comment by darkyellow** [comment]
Thanks, yes I suspected it might be my issue I was just trying to get help tracking down which font fontforge was trying to use. I'm glad you have gotten to the bottom of it as it will be useful to others even though its not a font forge issue.

**Comment by krummja** [comment]
@ctrlcctrlv, just wanted to throw a quick thanks your way! Super helpful walkthrough fixed the problem for me.

**Comment by JamesTheAwesomeDude** [comment]
I am experiencing this issue on Ubuntu 20.04.

The fix in a nutshell was going to:

* File
* X Resource Editor
* Text Field (10th sub-item under GGadget; most of the way down on the left)
* **Checking** the checkbox labeled "Font" (at the bottom)
* Click OK

After this, dialogues were readable.
