### ISSUE TITLE
Missing dependency when building from source

### ISSUE THREAD

**Issue by darkyellow** [fontforge/fontforge#4347]
Hi

I raised another issue which was closed due to it not being fontforge's issue. I reinstalled Ubuntu 20.04 from scratch to resolve the issue (and it did!) but from a totally clean system I ran the below to install the dependencies but this wasn't enough.

sudo apt-get install libjpeg-dev libtiff5-dev libpng-dev libfreetype6-dev libgif-dev libgtk-3-dev libxml2-dev libpango1.0-dev libcairo2-dev libspiro-dev libuninameslist-dev python3-dev ninja-build cmake build-essential;

The belwo command failed

cmake -DENABLE_FREETYPE_DEBUGGER=<path to freetype source>/freetype/ -GNinja ..

because cmake was missing a dependency, I had to run the below to resolve.

sudo apt install gettext

**Comment by jtanx** [comment]
PR welcome

**Comment by darkyellow** [comment]
Sorry for the delay, I have created https://github.com/fontforge/fontforge/pull/4358/commits which just adds the dependency I saw that was missing

**Comment by ctrlcctrlv** [comment]
Closed by merger of #4358.
