### ISSUE TITLE
Not starting OSX 10.11.6

### ISSUE THREAD

**Issue by schroef** [fontforge/fontforge#4349]
### Important
—

### When reporting a bug/issue:
- Nothing shows
- FontFOrge 20200314, OSX 10.11.6
- Clicking app icon should start app, Nothing shows (no errors nothing)
- Double click app icon

### When you open an issue for a change/improvement/feature request:
- Ive used older versions and also have this installed on a different mac. I believe the issue is that I don't have quartz installed in this machine. Yet I'm not 100% sure this is the issue. I don't see any dependencies nor did I find minimal requirements

**Comment by ctrlcctrlv** [comment]
What? I'm sorry, this issue makes no sense. Do older versions work for you or don't they?

In any event, I am closing this per https://github.com/fontforge/fontforge/pull/3808#issuecomment-515010742. Your version of OS X is EOL. Ten months ago, we only supported ≥10.12. There's no reason to think the latest release will work on 10.11. 

I'll open a documentation bug elsewhere.

**Comment by schroef** [comment]
Okay riddle man! ill go and find older version then. Perhaps make those requirements easier to find, I looked for it for quite a while and did NOT find anything. Its not that hard, just add a paragraph in your readme, done!

But it does raise an issue, because normally OSX apps give a warning if it cant run on your OS. The app ICON should be grayed out and also gives the user a warning.

**Comment by schroef** [comment]
Here screengrab, i saw this yesterday and it does NOT state anything about OS. Perhaps do some checking of your own before you state something like that 

![Screen Shot 2020-05-26 at 12 13 58](https://user-images.githubusercontent.com/6923008/82924556-7d7d9580-9f4a-11ea-9978-f13c4838b2ab.png)

**Comment by schroef** [comment]
But i was checking the wrong place, its on the release page. I take the older version.

**Comment by schroef** [comment]
Still would advise your devs to a check how OSX handle older OS's. Current method is not correct but perhaps that's because its some kind of shell. Because its still depended on Quarts I guess

**Comment by frank-trampe** [comment]
@schroef, have you tried with XQuartz?

**Comment by schroef** [comment]
Yeah, but perhaps that could also be a cause. I got 2.7 I believe that should run. 

I just tried the 2019 August release which doesn't state what OS is a Minsk requirement, that didn't start neither but this does show a prompt about not being  apple approved app. I'll check the April version of 2019

**Comment by skef** [comment]
@schroef Try the advice [here](https://github.com/fontforge/fontforge/issues/4082#issuecomment-612408666) for the 2019 August problem. 

In the old days you could also Command-click (or something similar) to bring up a menu that lets you override the lack of a security-signature. It's not obvious because the entry is just "run application" or something but it gives you a choice rather than just an error.

**Comment by schroef** [comment]
@skef  thanks for replying, yes I know that trick. It's like run as admin on windows or use sudo in terminal. That did work, the August version didn't run. Didn't check console.log yet, perhaps it has useful info. But it's old release so it's kinda wasted time.

Still need to check the April release

**Comment by ctrlcctrlv** [comment]
"riddle man"? Kindly fuck off @schroef.
