### ISSUE TITLE
cidmaps should be bundled

### ISSUE THREAD

**Issue by pnemade** [fontforge/fontforge#4350]
Fontforge repository have https://github.com/fontforge/fontforge/tree/master/contrib/cidmap where cidmap files are available. 
I got below questions about them.
1)  I am not sure why those cidmap files are not available to be installed using `-DENABLE_MAINTAINER_TOOLS=ON` cmake option.
2)  Can some of them be updated? 
https://github.com/adobe-type-tools/Adobe-CNS1 shows Adobe-CNS1-7.cidmap is available.
https://github.com/adobe-type-tools/Adobe-KR shows Adobe-KR1-9.cidmap is available.

**Comment by ctrlcctrlv** [comment]
I also don't know why we aren't bundling them. We need the help of our historians. Calling @frank-trampe , @davelab6 and @JoesCat . If none of them know, we ought to start bundling them. I suspect that at one point Adobe was claiming copyright to them.

**Comment by JoesCat** [comment]
> ...historians?

cidmaps were somehow orphaned some time in the past ([example bug](https://bugs.archlinux.org/task/36301)), and found later as [debian fontforge extras](https://packages.debian.org/buster/fontforge-extras), and included as option "--enable-fontforge-extras" in fontforge 20190801.
Finding the original sources that were used to create the original cidmaps have proved to be challenging, and of the very few ftp locations where the sources were found, wasn't an exact match, plus some of our travis checks shouldn't have been testing against them (so the site locations either moved, were blocked, or removed).

2. source versions later than the original maps changed license, however, in [approx 2015](https://github.com/adobe-type-tools/cmap-resources/commit/6745f297fdbe04b7515570c09b13385b49744228), the licenses were reverted back to BSD-3, and someone did request/recommend updating them (either asked as an issue or mailing list request I can't find (late 2015?)). I think holding the "old" cidmaps plus having updated sources would be a good direction to go (similar to character tables), but something as big a step as this needs the help/attention of developers/users that understand these cidmaps.

> bundling?

1. Someone with an up-to-date cmake can answer ```-DENABLE_MAINTAINER_TOOLS=ON``` cmake option. @jtanx ? @skef ?

**Comment by jtanx** [comment]
`DENABLE_MAINTAINER_TOOLS` is for exactly that - enabling building maintainer tools for use within the repo.

If we think they should always be installed then let's just update it to make it so.

**Comment by ctrlcctrlv** [comment]
I am of the opinion we ought to always distribute the CID maps if we can do so legally. Making users hunt them down is pointless.

**Comment by jtanx** [comment]
Seems fine according to my interpretation of 

> Permission is hereby granted, free of charge, to any person obtaining a copy of this documentation file, to create their own derivative works from the content of this document to use, copy, publish, distribute, sublicense, and/or sell the derivative works, and to permit others to do the same, provided that the derived work is not represented as being a copy or version of this document.

**Comment by pnemade** [comment]
Hi,
Can someone please look into this request? Can Cidmap files be possible to update?

**Comment by yg8ijvjvjv** [comment]
It's because the fonts are OpenType OTF, but FontForge is misinterpreting them as CID files.

**Comment by ctrlcctrlv** [comment]
@pnemade I submitted a PR to install cidmaps by default, removing the sourceforge site from the error message. I will update them as part of a PR to be made after that one.

**Comment by ctrlcctrlv** [comment]
For now I'm going to consider this issue primarily about the bundling, and #1831 about the out-of-date nature of the cidmaps.
