### ISSUE TITLE
Unlink 0xFE0F emoji style from text fonts

### ISSUE THREAD

**Issue by guoyunhe** [fontforge/fontforge#4351]
Text fonts like the famous Liberation Serif fotnts, contains the smile face. It should only link to the text version `263A FE0E`. But in FontForge, I see it is linked to emoji version, too. This cause some color emoji being override. Unicode defines `FE0E` should only be linked to text font and `FE0F`. One font should never be linked to both. I hope in FontForge, it is possible to choose which version you want to link.

![image](https://user-images.githubusercontent.com/5836790/82941267-c2cbb280-9f9e-11ea-9145-b8ef719b1696.png)

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
This issue is invalid. We (I) have plans to support COLR/CPAL, but as we don't right now, there's nothing to change.

COLR/CPAL fonts are allowed to have traditional outlines ("fallback glyphs"). The COLR table works by specifying a list of layers which represent a fallback glyph.
