### ISSUE TITLE
10.11.6 only runs 2017 version with Xquarts 2.711 open

### ISSUE THREAD

**Issue by schroef** [fontforge/fontforge#4352]
_Originally posted by @schroef in https://github.com/fontforge/fontforge/issues/4349#issuecomment-634296615_

Started this issue here but that was close. Wanted to report back that on 10.11.6 only the # 20170731 
It will only run if XQuartz 2.711 is already started and FontForge is start by ctrl/cmd + RMB > open. Other methods don't start the app and results in crash.

**Comment by ctrlcctrlv** [comment]
OK
