### ISSUE TITLE
Windows build broken w/Python 3.8: expects non-existent `libffi-6.dll`  (workaround)

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4356]
This is simply a heads up for @jtanx and anyone else who is interested. ([Mad respect](https://twitter.com/HW_BEAT_THAT/status/1266922313200496640/photo/1) to him.)

It took me an hour and a half, but I was able to build on Windows today. 🥳

![image](https://user-images.githubusercontent.com/838783/83343360-1d6e5280-a2ae-11ea-9aee-fc8777d3ffd6.png)

There is a quite serious issue upstream in Python, [&numero;40535](https://bugs.python.org/issue40535).

In order to remedy this, I had to:

```bash
cp /$MINGVER/bin/libffi-6.dll $RELEASE/bin/libffi-7.dll
```

Apparently `ctypes` will bring everything down if you don't do this. If you run it from Bash, it won't even tell you what the problem is:

```
C:/msys64/home/Fred/Workspace/fontforgebuilds/ReleasePackage/bin/fontforge.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

You have to run it through `cmd.exe`!

![image](https://user-images.githubusercontent.com/838783/83343414-ce74ed00-a2ae-11ea-922c-436d9ed098f4.png)

Somehow in 2020, Microsoft still hasn't solved DLL hell.

**Comment by jtanx** [comment]
Seems to work ok here, I only have libffi-7.dll present. Done a `pacman -Syuu` recently?
