### ISSUE TITLE
Can there be a more TrueTypey mode?

### ISSUE THREAD

**Issue by fundamentals-fontdevelopment** [fontforge/fontforge#4363]
I'm a TrueType type designer and FontForge will often do things in a way that defy TrueType.

• Why is the em-size split into Ascent and Descent? They are not stored in the TrueType files, yet they are shown even as guides. The em-size does not need to correspond to any particular width or height. (#4274 )
• Disable Set Extremum Bound. This interface is extremely confusing, with invalid values (including 0 and fractionals) being silently turned back to 20, with the only way to find out being to open the dialog again. However, in practice any missing extrema will eventually glitch some operations at some point, so every extrema should be detected and fixed.
• When the point order is changed, by default it removes instructions. Not only this cannot be undone, but by the time FontForge warns about that it's too late. It can also happen when moving points as FontForge interpolates or deinterpolates points. How does Visual TrueType instead move points? It treats each point separately, but interpolated points don't count at all. VTT also has a Swap operation: toggles a point between on-curve and control point, same point number. It makes so much more sense than FontForge's point-order-destroying operations.
• When rounding to integer, sometimes it would move off-curve points by more than a half. Some relativity thing going on? No, this should not happen, each point should be rounded by itself. The way it is now, rounding to integer can make there be missing extrema. But the real TrueTypey mode would literally store each point (interpolated point is not a point) as an integer, avoiding the whole problem.
• Extremely confusingly, FontForge would silently make up its own .notdef at font export time when it doesn't exist. This should be an error instead.

**Comment by ctrlcctrlv** [comment]
Closed per [G2A: Wish lists](https://github.com/fontforge/fontforge/wiki/Community-guidelines#g2a-wish-lists).

**Comment by frank-trampe** [comment]
@fundamentals-fontdevelopment, as you many know, FontForge started as an editor for PostScript fonts called pfaedit. This informs its data model, its interaction model, and user expectations of those. We cannot make significant changes, and adding a parallel user interface is simply not a project we can staff. You may find that using FontForge in conjunction with other software provides  a workable if not perfect end-to-end solution.

**Comment by ctrlcctrlv** [comment]
@frank-trampe I think a lot of what they asked for is reasonable, especially if only applied to quadratic layers. Sub issue 1, though, is unreasonable, and I agree we should not implement it. Sub issue 2, I don't even understand. Sounds like just a minor GDraw issue at first, then veers off into weird territory. Sub issue 3, it sounds like something "nice to have" but I question why someone adding manual TrueType instructions is overly concerned about losing point numbering when using a GUI editor. Sub issue 4, I don't know how "extremely confusing" that is. It could be at most a warning&hellip;which I think it already is.

Per [#G2A](https://github.com/fontforge/fontforge/wiki/Community-guidelines#g2a-wish-lists), @fundamentals-fontdevelopment is advised that if they still want to pursue these issues, they should new ones, keeping in mind my input above, and answering it in the original post of the new issue(s).

**Comment by fundamentals-fontdevelopment** [comment]
> Sub issue 1, though, is unreasonable, and I agree we should not implement it.
I don't understand. What do you mean by that?

**Comment by ctrlcctrlv** [comment]
Certainly not, and I did not so much as imply that. I just said that we should not make a certain change you requested.

Please open new issues for the issues you wish to follow up as I asked. Please don't reply anymore to this one.

**Comment by frank-trampe** [comment]
@ctrlcctrlv, I was more addressing the subject line rather than a specific sub-topic.

**Comment by ctrlcctrlv** [comment]
Ah, now your comment makes sense! Sorry about that.
