### ISSUE TITLE
Can't import svg, no files in import window, just directories

### ISSUE THREAD

**Issue by Yuladesign** [fontforge/fontforge#4365]
I have FontForge-2020-03-14-Windows on Windows 8. I am a graphic designer with no coding experience. So please go easy on me with your answers and provide very specific instructions. 

When I try to import an SVG file, I just can't. Not only that FontForge lets me choose nothing other than disk C, but also it only shows directories in the Import window (directories amidst files is checked). SVG files are in the directory I choose, they are just not displayed in the Import Window.
I have downloaded this version of FontForge from fontforge.org.

**Comment by jtanx** [comment]
Try changing the format to SVG 
![image](https://user-images.githubusercontent.com/5137410/83941793-a0a12280-a831-11ea-947b-92f2d1aec595.png)

**Comment by Yuladesign** [comment]
Jtanx, tried that, doesn't help

**Comment by jtanx** [comment]
Screenshots please, both in explorer (make sure you have show extensions on) and in fontforge

**Comment by Yuladesign** [comment]
![image](https://user-images.githubusercontent.com/66514645/83941932-e3de9f80-a7f7-11ea-84c2-e7139052e406.png)

**Comment by Yuladesign** [comment]
![image](https://user-images.githubusercontent.com/66514645/83941950-08d31280-a7f8-11ea-9b13-6ba85f828ca3.png)

**Comment by Yuladesign** [comment]
![image](https://user-images.githubusercontent.com/66514645/83941961-26a07780-a7f8-11ea-8f8d-687fafa3edac.png)

**Comment by jtanx** [comment]
Can you:

* Try another folder other than program files? Like C:\temp
* Type * in the window and press enter, then look for the svg
![image](https://user-images.githubusercontent.com/5137410/83942069-d8a96500-a833-11ea-8c55-2b30d1118ae8.png)

**Comment by Yuladesign** [comment]
UPD. I have tried to open my SVG files in Adobe Illustrator. "File not found" pops up. Maybe that's the issue. Same situation if I try to place my SVG files in the root or any other directories on disk C.  Then how do I access my disk D (files open perfectly both in Explorer and Adobe Illustrator)?

**Comment by jtanx** [comment]
Type `D:\` in the window and press enter

**Comment by Yuladesign** [comment]
C:\Temp worked perfectly. Typing D provides no result

![image](https://user-images.githubusercontent.com/66514645/83942197-17bac480-a7fa-11ea-9141-19516349eec6.png)

**Comment by jtanx** [comment]
Did you type D here 
![image](https://user-images.githubusercontent.com/5137410/83942325-cfb99300-a835-11ea-8c2b-ddec3dfb90ed.png)

**Comment by Yuladesign** [comment]
It worked, thank you

**Comment by jtanx** [comment]
Great. Original issue sounds like a permissions problem.
