### ISSUE TITLE
Error in make command in alpine

### ISSUE THREAD

**Issue by NishealJ** [fontforge/fontforge#4366]
* Provide a general summary of the issue in the **Title** above. 
Hi, I'm trying to install pdf2htmlEX in the alpine container using the below command 
```
RUN apk --update add alpine-sdk xz poppler-dev pango-dev m4 libtool perl autoconf automake coreutils python-dev zlib-dev freetype-dev glib-dev cmake && \
    cd / && \
    git clone https://github.com/BWITS/fontforge.git && \
    cd fontforge && \
    ./bootstrap --force && \
    ./configure --without-iconv && \
    make && \
    make install && \
    cd / && \
    git clone git://github.com/coolwanglu/pdf2htmlEX.git && \
    cd pdf2htmlEX && \
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig && \
    cmake . && make && sudo make install && \
    apk del alpine-sdk xz poppler-dev pango-dev m4 libtool perl autoconf automake coreutils python-dev zlib-dev freetype-dev glib-dev cmake && \
    apk add libpng python freetype glib libintl libxml2 libltdl cairo poppler pango && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/* && \
    rm -rf /fontforge /libspiro /libuninameslist /pdf2htmlEX
```
but fontforge breaks at make, make install with this error
```
CCLD     libfontforge.la
ar: `u' modifier ignored since `D' is the default (see `U')
  GEN      .gitignore
make[2]: Leaving directory '/fontforge/fontforge'
Making all in gdraw
make[2]: Entering directory '/fontforge/gdraw'
  CC       libgdraw_la-choosericons.lo
  CC       libgdraw_la-ctlvalues.lo
  CC       libgdraw_la-drawboxborder.lo
In file included from drawboxborder.c:27:
../lib/math.h:38:3: error: #error "Please include config.h first."
  #error "Please include config.h first."
   ^~~~~
../lib/math.h:40:1: error: unknown type name '_GL_INLINE_HEADER_BEGIN'
 _GL_INLINE_HEADER_BEGIN
 ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ../lib/stdio.h:43,
                 from ../inc/basics.h:31,
                 from ../inc/gimage.h:29,
                 from ../inc/gdraw.h:29,
                 from drawboxborder.c:28:
/usr/include/fortify/stdio.h:20:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__extension__'
 __extension__
 ^~~~~~~~~~~~~
make[2]: *** [Makefile:1971: libgdraw_la-drawboxborder.lo] Error 1
make[2]: Leaving directory '/fontforge/gdraw'
make[1]: *** [Makefile:1953: all-recursive] Error 1
make[1]: Leaving directory '/fontforge'
make: *** [Makefile:1790: all] Error 2 
```
* Before you open an issue, please check if a similar issue already exists or has been closed before.

<img width="586" alt="Screenshot 2020-06-06 at 5 00 07 PM" src="https://user-images.githubusercontent.com/41017303/83943144-3aa7a180-a817-11ea-8e78-8b85091cbc53.png">

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by NishealJ** [comment]
Hi @ctrlcctrlv @jtanx @yursha can you please take alook?

**Comment by jtanx** [comment]
Sorry, we don't provide support for debugging issues with forks, particularly off old versions of FontForge. Sounds like a gnulib issue though.
