### ISSUE TITLE
Install fontforge in alpine linux

### ISSUE THREAD

**Issue by NishealJ** [fontforge/fontforge#4368]
* Provide a general summary of the issue in the **Title** above.  

Hi, I'm completely new to fontforge I'm looking to install pdf2htmlEX in alpine Linux which needs fontforge for the build.
But after a lot of research, I'm still unable to find the installation process of fontforge for alpine Linux nor its in the package distribution.

* Before you open an issue, please check if a similar issue already exists or has been closed before.

I checked I didn't find a similar issue like this.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot  =  Not needed
- [x] The FontForge version and the operating system you're using = I want to use the latest version
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by NishealJ** [comment]
Hi @jtanx @ctrlcctrlv please take alook. Thanks!

**Comment by jtanx** [comment]
Mate, stop tagging us and stop filing new issues, it's not helping.

If you want to compile fontforge follow [the instructions](https://github.com/fontforge/fontforge/blob/master/INSTALL.md). 

If you want to get pdf2htmlex working you're on your own. The last I saw it was abandoned, plus it only worked off some old version of FontForge. You're unlikely to get it working without knowing what you're doing, i.e. have at least some basic knowledge of C/C++ programming, which going off your comments, I highly doubt. At the least, the latest version of FontForge does not install development headers, so it's on you to patch it in whatever ways necessary to get pd2htmlex building.
