### ISSUE TITLE
FF Closes when I import some svg draws 

### ISSUE THREAD

**Issue by Keinmy** [fontforge/fontforge#4373]
Hi! I use a Windows 10 (Version 1909, SO 18363.836) and a FF version (20200314 c94f19e71cdbea2272ed6508f2d38a5b060dca9e) Built (2020-03-14 03:45 UTC-ML-TtfDb-D-GDK3) downloader from https://fontforge.org/en-US/downloads/windows/ in May.

Ok, I am making a font (obviously). First I worked whit Linux mint like OS, and i no have a problem. But i has change the computer and now i have Windows 10 and happens that when i import some svg draws of types, the program close suddenly, and i dont know why (Only happen whit some desing). I use Inkskape program for desing. 

No error messages appear.

### When reporting a bug/issue:
- [ ] Screenshot
- [x ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
We need the SVG file you're importing. Please add it to a zip file and upload it to GitHub. Also, does the exact same SVG cause a crash on Windows as well?

**Comment by Keinmy** [comment]
> We need the SVG file you're importing. Please add it to a zip file and upload it to GitHub. Also, does the exact same SVG cause a crash on Linux as well?

Thanks for answer. No, with Linux i no had any problem to import the svg draws. 

This glyph "¬", for example, any time that i try to import it, FF close. It doesn't matter if the draw-glyph is alone in archive or with others, the FF close (I must erase it of archive if i want to use the others signs drawings -I draw many glyphs in one archive svg. About 5 or 6- that is to say, the glyph cause error, not the archive)

[Signo.zip](https://github.com/fontforge/fontforge/files/4752841/Signo.zip)

**Comment by ctrlcctrlv** [comment]
Hi @Keinmy - I think this might be due to #4248 or a related issue.

Can you please try to install our AppVeyor build? It contains the newest development version. https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts

If this version also does not work, please let me know, and I'll take a look tomorrow.

**Comment by Delagen** [comment]
Also problem with generate SVG font with Scripting at Windows 10 #4353

**Comment by Delagen** [comment]
Seems with latest artifact it works

**Comment by Keinmy** [comment]
@ctrlcctrlv and @Delagen Thanks all. But i am not a programmer, i not understand that i must download or write code. And my english is poor. I am sorry a lot.

I left evidence of this in writing and seems that is a error of programation of FF-Windows, and i am not programmer, so i cant solve it. 

I will left the work with FF by the moment and will download the next right version.

**Comment by ctrlcctrlv** [comment]
@Keinmy What's your native language? I speak Spanish, Esperanto, and Tagalog well, Japanese okay, and Mandarin poorly. Perhaps we share a language other than English.

1. Install 7-Zip
1. Download FFontForge-mingw-w64-i686-47838f-appveyor.7z
1. Extract to a new folder
1. Open the folder
1. Run `run_fontforge.exe`

**Comment by Keinmy** [comment]
@ctrlcctrlvI I was install it and I was import the "¬" sign, and works well. Thanks very much for all,
(And congratulations for speak esperanto ;) )

**Comment by ctrlcctrlv** [comment]
Closed as resolved in latest master.
