### ISSUE TITLE
I think our wiki should be only editable by organization members

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4375]
Especially now that I put the [Community guidelines ](https://github.com/fontforge/fontforge/wiki/Community-guidelines)there...

[Changing access permissions for wikis](https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis)

Not many have used our wiki to write documentation, and I think it creates a needless avenue for subtle abuse. If this change is made, I'll edit the homepage of the wiki to encourage people who want to contribute some a new documentation page to open a PR against `gh-pages` branch.

**Comment by frank-trampe** [comment]
Agreed and done.
