### ISSUE TITLE
contour.simplify: Only selected points?

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4384]
Is there a way to use `contour.simplify` in the Python API only on selected points?

**Comment by skef** [comment]
I don't believe so. Simplify operates on adjacent splines and FontForge doesn't have a robust way of selecting spline ranges at present. You can select one by selecting the points on either side but after that it gets fuzzy.

**Comment by ctrlcctrlv** [comment]
@skef Is it too hacky to delete all points but what I want to simplify, run a simplify, save the contour, restore all points, replace the selected points with whatever result I saved?

**Comment by skef** [comment]
It's *tricky*, but if you do it correctly I wouldn't call it *hacky*.

This may show an easier approach, though. Suppose `c` is the contour of interest. Then you can do something like:

```
tc = fontforge.contour()
sl = slice(3, 13)
tc[:] = c[sl]
tc.simplify()
c[sl] = tc[:]
```
So, basically, copy the slice out into a temp contour, simplify it, and replace the slice with those contents. That way the whole problem boils down to determining the slice parameters, which can still be tricky but is at least a now-isolated problem.

**Comment by skef** [comment]
(This is assuming Simplify works on open contours (and that it preserves the end-points) which seems right but I haven't verified it.)

**Comment by ctrlcctrlv** [comment]
Nice, simple enough. Closed as I don't know that this needs to be part of the API.
