### ISSUE TITLE
How to change the font's property?

### ISSUE THREAD

**Issue by yufeiluo** [fontforge/fontforge#4388]
Rename DejaVuSansMono.ttf  as myfont.ttf and  generate fonts.
It encounter error info:

[https://www.dropbox.com/s/0wa22ipou4tn7va/encoding%20too%20large.png?dl=0](url)

How to set the encoding then?

**Comment by skef** [comment]
You set the encoding by choosing the desired value from the Encoding -> Reencode menu.
