### ISSUE TITLE
Typo in fontforge.org/docs

### ISSUE THREAD

**Issue by salchint** [fontforge/fontforge#4390]
It's just a minor issue. I have found a typo on your website.

In section _What’s the difference between a character and a glyph?_ of your docs site viewed on June 21, 2020 (https://fontforge.org/docs/#what-s-the-difference-between-a-character-and-a-glyph) you are giving two examples of single-character vs. multi-glyph relationships. It seems you mixed up the glyphs of the renaissance "s" and the Arabic "seen".

![glyph](https://user-images.githubusercontent.com/2872277/85248935-8e1d1080-b40f-11ea-8239-6549e741d47a.png)

**Comment by bkmgit** [comment]
This seems to have been fixed.
