### ISSUE TITLE
about Expand Stroke function

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4392]
Hi
new Expand Stroke function works very well but I have a problem: I'm working on a monoline variable font with a lot of open paths and using Expand Stroke to generate thin and bold weights, it's very important to keep the number of the points equal in both weights (to make masters compatible), but in the bold weight(maybe after an initial saturation depending on the curve radius and expand stroke value), the function generates some extra points (which seems unnecessary).

![text2735](https://user-images.githubusercontent.com/25493297/85524271-453aa700-b61d-11ea-9a57-e88264d90691.png)

the settings:

![image](https://user-images.githubusercontent.com/25493297/85527481-27227600-b620-11ea-91fe-33810a8c88e4.png)

another problem is about the path orders in different expandation values(extra points have been merged):

![fontforge_GHEC8fHUVF](https://user-images.githubusercontent.com/25493297/85553441-319d3980-b639-11ea-86b4-1b9baf7feff1.png)
![fontforge_nW0Vv93F27](https://user-images.githubusercontent.com/25493297/85553455-33ff9380-b639-11ea-95b4-a8a99e510b14.png)

**Comment by skef** [comment]
The Expand Stroke algorithm isn't designed with this use in mind.

Could it be/should it be? Your use case generalizes a little bit but in my view not so much as to call for an entirely new algorithm. And there's a more basic question about how the algorithm would "know" what points are needed at one offset radius versus another. If the points are superfluous you can just merge them in post-processing. If they aren't, how would the algorithm "know" to add them at the smaller radii?

If you want to use the algorithm in this way you should post-process the offset outputs with a script. It's pretty clear how that script would work in the case of your first example: Go through the different versions starting from the first point on the contour and match the on-curve points up based on a) order and b) slope. In this way any "extra" points can be identified. Finally, find the splines with the "missing" points and split the spline at the t value corresponding to that slope.

FontForge's scripting API makes it pretty easy to do everything but the last step. There's currently no way to split a spline at a given slope. One could write the code to do that entirely in Python, of course, but it would be nice if the contour-level API made some of this stuff easier. 

However, I don't see enough value in enhancing Expand Stroke in this way to make it worth the effort.

**Comment by skef** [comment]
Wait, when you say "not unnecessary" do you mean "necessary" or "not necessary"? The double-negative implies the former. 

If you don't actually care about the path accuracy afforded by those extra points you can *try* slowly increasing the accuracy target with the stroke radius. Or *just post-process*: the contour API has a merge method.

**Comment by skef** [comment]
There's too much going on in the new pictures to make it clear what the issue is.

**Comment by aminabedi68** [comment]
> Wait, when you say "not unnecessary" do you mean "necessary" or "not necessary"? The double-negative implies the former.
> 
> If you don't actually care about the path accuracy afforded by those extra points you can _try_ slowly increasing the accuracy target with the stroke radius. Or _just post-process_: the contour API has a merge method.

sorry :) I corrected that.




> 
> 
> There's too much going on in the new pictures to make it clear what the issue is.

new pictures show the thin and bold weights(from a source path with Expand Stroke function), as you see the path orders(shown with SVG numbers) are different.

**Comment by skef** [comment]
Could you post the source path (in an SFD either renamed with a .txt extension or added to a zip archive) and the stroking radii for the path ordering problem?

**Comment by aminabedi68** [comment]
I can understand that there is not enough resion to

**Comment by aminabedi68** [comment]
sorry, I had a mistake and touching some wrong buttons here!

> 
> 
> Could you post the source path (in an SFD either renamed with a .txt extension or added to a zip archive) and the stroking radii for the path ordering problem?

yes, sure. with the same settings (second screenshot). major and minor axes: 4 and 50

[q.txt](https://github.com/fontforge/fontforge/files/4825063/q.txt)

**Comment by skef** [comment]
I did the following:

1. Expanded at 4 and 50 at the same additional parameters as in your dialog, to produce these contours: [q_new.txt](https://github.com/fontforge/fontforge/files/4825231/q_new.txt)
2. Wrote a little script to copy each individual contour from each expansion into a separate character, 4 version lowercase b to t and 50 version uppercase B to T: [qq.txt](https://github.com/fontforge/fontforge/files/4825246/qq.txt)

Going through the respective contours in separate windows it seems like they all match up.

**Comment by aminabedi68** [comment]
yes. you right. SVG numbers are confusing because the start points are different. but the path orders are the same. thank you @skef

**Comment by skef** [comment]
Note: I suspect if you were to test with "Remove Overlap: None" then the start points in the corresponding contours would also match. I've only looked at the Remove Overlap code casually (the current algorithm was coded by @frank-trampe and has been working very well overall -- we do occasionally find bugs) but I expect that when contours are split, which point becomes the first in the new contour depends a lot on the particulars of the point positions. So that's another case where post-processing is likely to be needed.

**Comment by aminabedi68** [comment]
> 
> 
> I suspect if you were to test with "Remove Overlap: None" then the start points in the corresponding contours would also match

i tried. not match.

**Comment by skef** [comment]
Can you isolate the contours (probably by selecting one point, doing Edit -> Select -> points on selected contours, and copy-pasting) to show the difference? 

This may only be for my curiosity -- there are things it would be hard to change in the algorithm, things it would be easy to change, and things that I would expect would already be true. This falls into the third category -- I'm not sure why just expanding the stroke would yield a different start point.

**Comment by aminabedi68** [comment]
this is a single counter with different accuracy targets (Remove Overlap: None)(10 to 100)

![1](https://user-images.githubusercontent.com/25493297/85574516-18ea4f00-b64c-11ea-9eea-f90d0381f97a.png)

**Comment by skef** [comment]
Interesting -- In most cases the first point is in what amounts to the middle of a cap. I could understand why that might happen with Add Extrema turned on (maybe) but I honestly have no idea why it would wind up there otherwise. 

In the cases where it isn't on the extrema point is it always on one other corresponding point or does it move around?

**Comment by aminabedi68** [comment]
Sorry for the delay.
no, it moves around:

![image937](https://user-images.githubusercontent.com/25493297/85603868-041ab500-b666-11ea-896f-eeac7469890a.png)
