### ISSUE TITLE
Hardy Hershey Text ISSUE!   Can't write using it: TAB ERROR - INCONSISTENT USE OF TABS

### ISSUE THREAD

**Issue by marticos14** [fontforge/fontforge#4393]
Hi all,

Here's the thing: 

I'm trying to make single path text for my laser engraver, but I never could.
I am using the Hardy Hershey Text extension but it always shows me the same results (see screenshots 1 and 2).

I am no programmer and I have never code anything...
How could I solve that?

Thank you all

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ x] Screenshot
- [x ] Using windows 10 - 64 bits and the latest version of [Inkscape.](url
![Recorte INKSCAPE 1](https://user-images.githubusercontent.com/67366242/85528206-e9b3ed80-b60b-11ea-9d9d-a491e2b196ef.png)
![Recorte INKSCAPE 2](https://user-images.githubusercontent.com/67366242/85528213-eae51a80-b60b-11ea-858b-f250ccf4a64f.png)

)
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by frank-trampe** [comment]
Hi, @marticos14. The FontForge team do not maintain Hardy Hershey. I would suggest filing an issue [here](https://github.com/VirToReal/Hardy-Hershey-Text) instead.
