### ISSUE TITLE
Windows Version 20200314 crashes when importing SVG files

### ISSUE THREAD

**Issue by tomchen** [fontforge/fontforge#4396]
FontForge Windows Version 20200314 crashes when importing SVG files, while Windows Version 20190801, Linux Versions 20200314 and 20190801 all work fine.

### The FontForge version and the operating system you're using

Windows Version 20200314

### Steps to reproduce the behavior 

* Download my glyph SVG file "48 0.svg": https://raw.githubusercontent.com/tomchen/font-template/master/example/SVG/48%200.svg
* Start a new font in FontForge
* Click a blank glyph
* File -> Import
* Import "48 0.svg"
* With default Import Parameters, click OK
* It crashes, showing "FontForge has stopped working"

**Comment by jtanx** [comment]
Sounds like #4248 / #4373, can you try the latest build from https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts

**Comment by tomchen** [comment]
> Sounds like #4248 / #4373, can you try the latest build from https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts

Yes that latest build works well. Thanks.

Sorry I didn't see those closed issues.

It's a pretty big/annoying and easily encountered problem I guess. I'm advising users who need SVG importing to use 20190801 for now. Hope the next stable version will be released soon with this fix. Thx.

**Comment by skef** [comment]
@tomchen there have been the usual hiccups but the changes in 20200314 yield a much more accurate result when importing many SVGs. If I were you I would point them towards the build you used if accuracy is an issue.
