### ISSUE TITLE
"Create a new lookup" without function

### ISSUE THREAD

**Issue by Connum** [fontforge/fontforge#4401]
**OS:** Windows 10
**Version:** most recent build from https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts
> FontForge Windows build (32-bit)
Wed, Jul  8, 2020 10:03:23 AM +0000
4820613b173775fe828106f90a0fdb15684fd3fe [HEAD]
Based on master: 81b62100974b530d6ad4be4d9cbdc033fe41af12

### How to reproduce
1. Start with a fresh new font
2. Right-click any glyph and select `"Glyph Info..."`
3. Select "Substitutions" in the left menu and click `<New Substitution Variant>`, then `"New Lookup Subtable..."`
4. Select Type `Single Substition`, click `<New>` in the `Feature` column and select any arbitrary feature
5. Click `OK` and accept the suggested name with `OK` as well
6. The newly created subtable appears in the `Subtable` column as it should, so far so good.
![grafik](https://user-images.githubusercontent.com/13076806/87159124-1f6dfd00-c2c1-11ea-81c5-57fa09ba7cf7.png)
Now Click `<New Substitution Variant>` again, then again `"New Lookup Subtable..."`
7. In the following dialogue, select `Create a new lookup`
![grafik](https://user-images.githubusercontent.com/13076806/87158669-63143700-c2c0-11ea-90c7-47f59d822403.png)

#### Expected result
The Lookup creation dialogue opens again, just like it did after step 4.

#### Actual result
Seemingly, nothing happens, no additional Lookup or subtable is created and added to the `Subtable` column.

8. Click `OK`

#### Expected result
The rest of the font is untouched.

#### Actual result
All the encoding slots, except the one for the letter we had opened the Glyph Info panel for, show as a red question mark.
![grafik](https://user-images.githubusercontent.com/13076806/87157737-fb112100-c2be-11ea-877d-823a50e0577e.png)
(Same as in issue #4400)

**Comment by Connum** [comment]
I just compiled fontforge from the master branch using WLS Ubuntu 18.04.4 LTS, where the issue also occurs. Strange, that no one else encountered this before me!

**Comment by Connum** [comment]
Is there anything I could do to assist bugfixing? I tried using gdb, but there's no backtrace, assumingly because the app doesn't crash completely.

**Comment by skef** [comment]
@Connum How pressing a problem this is depends in large part on whether it still happens when the font file in question is populated with (at least) a typical minimum of glyphs. It's much more common to start with at least some glyphs and then add some tables -- after all there's nothing to **calt** (for example) without glyphs. 

If the problem occurs under a wider set of circumstances it is more likely to get faster attention. If it only occurs in a blank font it's the sort of thing that should be fixed at some point but isn't especially important to fix quickly.

**Comment by Connum** [comment]
Thanks for your feedback! Starting with a new font was just to keep things as simple as possible and to express that it wasn't a bug with a specific font file. I tried it with different OTF and TTF fonts that I opened and the issue also occurs there.
