### ISSUE TITLE
Kern row not aligned with other values in Metrics Window

### ISSUE THREAD

**Issue by Connum** [fontforge/fontforge#4402]
**Version & OS:** built from master on WSL Ubuntu 18.04.4 LTS / FontForge-mingw-w64-i686-d367d0-appveyor on Windows 10

**Steps to reproduce:**
1. Create a new font or open an existing one
2. Click `Metrics` in the main menu at the top
3. Click `New Metrics Window`
4. Take a look at the table of values at the bottom of the window

![grafik](https://user-images.githubusercontent.com/13076806/87224772-3a577480-c388-11ea-8dd4-b981fe393e40.png)

**Expected result:**
All the cells of the row for `Kern:` are aligned with those of the other values (`Name:`, `Width:`, `LBearing`, `RBearing`)

**Actual result:**
The first cell is too wide, so all other cells in the row are pushed to the right, which makes it really hard to see which value belongs where

**Comment by Connum** [comment]
Ok, I think I had an error in reasoning, correct me if I'm wrong: This is absolutely intentional, because it's the kerning value between those two glyphs, am I right? I was just confused because the value only shifts the right letter by the value, so I'd expect it to be under the corresponding letter being shifted. Then meybe the first column that can't have a value, could just be greyed out?

**Comment by skef** [comment]
@Connum You're more or less correct -- kerning is distinct from spacing in that it's relative to multiple characters, most often pairs of characters. The columns are offset to make that clearer. 

The "first column" contains the row heading, so it's actually consistent with the others in not having a value (although it's positioned unusually). All the headings could be right justified to make things a bit clearer but the cost/benefit of that change given the other graphics issues is probably unwarranted.
