### ISSUE TITLE
FontForge crashes when importing SVG

### ISSUE THREAD

**Issue by nerdius** [fontforge/fontforge#4406]
### Reporting a bug/issue:

- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] (optional) Possible solution/fix/workaround

### Short description:

The program crashes when I'm trying to import several SVGs to a glyph.

### Screenshot (to comply with the guidelines, otherwise irrelevant):

![FontForge Character View](https://user-images.githubusercontent.com/2781117/87955878-5e6d3100-cabf-11ea-963c-998855c30369.png)

### Confirmed to crash on:

- Character `U+F064`
- [These SVG files](https://github.com/fontforge/fontforge/files/4947644/fontforge-test-import-svgs.zip)
- Manjaro Linux 20.0.3 (Lysia)
- FontForge 20200314

I think the most relevant factors are SVGs themselves, because the _share.svg_ file manages to crash program when imported to every glyph I tested. The character code might also be somewhat relevant because, at one time, _robot.svg_ crashed the program when imported at `U+F544`, but not when at `U+F553`; although, I was unable to reproduce it since then and now it crashes every time, regardless of the character.

### Technical details:

- **OS:** Manjaro Linux
  - **Version:** 20.0.3 (Lysia)
  - **Architecture:** x86-64
  - **Kernel:** Linux kernel 5.7.0
    - **Release:** 5.7.0-3-MANJARO
  - **Desktop environment:** KDE Plasma 5.18.5
- **FontForge:**
  - **Version:** 20200314
  - **Build:** 2020-03-18 19:16 UTC-ML-D-GDK3
  - **OS package:** _extra/fontforge 20200314-2_ (Manjaro)
    - **Package file:** [_fontforge-20200314-2-x86_64.pkg.tar.zst_](https://manjaro.moson.org/stable/extra/x86_64/fontforge-20200314-2-x86_64.pkg.tar.zst)
    - **SHA1 checksum:** `16e5aa2a93983ddadc793307f638217b55bb7b1d`

### Steps to reproduce:

1. Create a new font file.
2. In the Character View window, select the character with code `U+F064`.
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>.
4. In _Format_, select _SVG_.
5. In _Options_, choose the following parameters (and click _OK_):
   ![FontForge Import Parameters](https://user-images.githubusercontent.com/2781117/87957780-c755a880-cac1-11ea-9692-615150d7c6e8.png)
6. Select one of the files I provided.
7. Observe a crash.

**Note:** If unable to reproduce, try the second file.

**Note:** I was unable to reproduce the same behaviour on a Windows 10 PC with the official latest Windows build from the website; everything seems to work just fine. So it may be specific to just Linux, Manjaro, or even this specific build.

### GDB output:

```
% gdb fontforge
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fontforge...
(No debugging symbols found in fontforge)
(gdb) run
Starting program: /usr/bin/fontforge
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Copyright (c) 2000-2020. See AUTHORS for Contributors.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
Version: 20200314
Based on sources from 2020-03-18 19:16 UTC-ML-D-GDK3.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b3e92e in ?? () from /usr/lib/libfontforge.so.4
(gdb) cont
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by nerdius** [comment]
### Update:

Character codes seem to be irrelevant; the program crashes when importing those SVGs at any glyph, even in the Latin range.

**Comment by ctrlcctrlv** [comment]
This is a known issue in the latest releases. Please try our developer builds. In your case, AUR package is probably simplest.

**Comment by nerdius** [comment]
@ctrlcctrlv,

> This is a known issue in the latest releases.

Are you sure? I've searched for the issues related to importing SVGs and they seem to be issues with the Windows build, e.g., #4248, #4373, and 4396. In my case, the crash happens on Linux, but not on Windows.

> Please try our developer builds. In your case, AUR package is probably simplest.

Same result:

```
% gdb fontforge
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fontforge...
(No debugging symbols found in fontforge)
(gdb) run
Starting program: /usr/bin/fontforge
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Copyright (c) 2000-2020. See AUTHORS for Contributors.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
Version: 20200314
Based on sources from 2020-07-21 09:34 UTC-ML-D-GDK3.
Based on source from git with hash: 7222a09f72a5e584036d35a26de31e3c54183efc

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b4df16 in ?? () from /usr/lib/libfontforge.so.4
(gdb) cont
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
```

**Comment by skef** [comment]
I'm looking at this.

@nerdius For my reference (and consolation) are these two SVGs from some larger collection where most didn't have import problems, and if so how large a collection was it?

**Comment by nerdius** [comment]
@skef, yes, exactly. For now, there are [27 SVGs](https://github.com/fontforge/fontforge/files/4953183/fontforge-test-import-svgs-full.zip) in total, and most of them cause no issues.

**Comment by skef** [comment]
Huh, that's not many. I'm not sure why you wound up running into these two corner cases given that we have some users importing hundreds of SVGs into symbol-type fonts. (Maybe the .999996 stroke with? Maybe the arcs are weird for some reason?)

Anyway, fixes in #4407.

**Comment by nerdius** [comment]
I'm not using strokes in this collection at all.

If it helps, most of these graphics were 24×24 in the beginning, then I upscaled them to 1000×1000 using Inkscape, to match the metrics I had in the font. It is possible that Inkscape did some binary rounding that resulted in those floating-point values that caused the crash.

**Comment by skef** [comment]
Ah, I guess if there's no `stroke` color defined then `stroke-width` is ignored. 

Both of these problems traced to floating point calculations that were very close to existing cut-offs. It's more likely that the *lack* of rounding in the scaling amplified some normally inconsequential bottom-of-precision floating point data that then slightly threw off some values. The raw numbers sort of reflect that (e.g. "41.636364,41.699999", "124.90909,125.1").

**Comment by nerdius** [comment]
[This](https://www.youtube.com/watch?v=PZRI1IfStY0&t=190) is what I meant regarding rounding in binary. Most programming languages have precision issues with floating-point values because the actual arithmetic is done in binary and then converted into decimal.

Inkscape often has precision issues when transforming paths by toolbar (which is what I did).

**Comment by nerdius** [comment]
### Update:

I was wrong; the issue is not specific to the Linux build. _robot.svg_ file seems to crash Windows build as well. I can import _share.svg_ on Windows with no issues, though.
