### ISSUE TITLE
Is the scale on the vector diagram width

### ISSUE THREAD

**Issue by Kodeyx** [fontforge/fontforge#4410]
Is the scale on the vector diagram width? Why does the outside image remain the same when I exceed the maximum width?
![image](https://user-images.githubusercontent.com/21009772/88264774-f311a200-ccfe-11ea-872f-59f90472a662.png)

**Comment by skef** [comment]
Is your question, roughly speaking, why when you set the width to 128 the visible portion of the glyph can go past that line? 

Character widths in (the most common) fonts relate to the spacing between characters. Unless there is additional kerning data the zero point of the "next" character will be matched with the end of the current one, where "the end" is determined by the width. That's more or less all that the width mark indicates. Fonts allow over- and under-hanging portions of glyphs and in some cases (like italic fonts) it is routine. 

If you want a glyph to "cut off" at its edge you'll have to design it that way.
