### ISSUE TITLE
"Could not open CIDmap file" - Adobe-Japan1-3

### ISSUE THREAD

**Issue by JapanYoshi** [fontforge/fontforge#4411]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
20200314 on Windows 10 64bit
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
Opening and editing a Japanese font with Adobe-Japan1-3 CIDmap. I don't know what's wrong with it, but FontForge tells me that CIDmap files are missing. I download the CIDmap files from the indicated place, and let FontForge load it, but it gives me the "Could not open CIDmap file" error message.
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
Can you provide the font? And you are using our CIDmaps, yes, not some updated ones from Adobe?

**Comment by JapanYoshi** [comment]
[FOT-PopHappinessStd-EB.zip](https://github.com/fontforge/fontforge/files/4985889/FOT-PopHappinessStd-EB.zip)
I'm using the font FOT-PopHappinessSTD-EB from Fontworks. I've specifically gone to the address that FontForge gives me in order to download the CIDmaps.

**Comment by ctrlcctrlv** [comment]
@JapanYoshi For me it worked to use `Adobe-Japan1-7.cidmap`. For your future reference, the CID filename is laid out like this, per Adobe:

Registry-Ordering-Supplement

&laquo;Registry&raquo; is equivalent to "Publisher".
&laquo;Ordering&raquo; just means the type of CID map, what it covers. This one is for Japan, thus `Japan1`.
&laquo;Supplement&raquo;, a version number.

So, using a later &laquo;Supplement&raquo; will always work to open files produced to earlier &laquo;Supplement&raquo;'s.
