### ISSUE TITLE
Lookups don't work when I add too many characters

### ISSUE THREAD

**Issue by ekaunt** [fontforge/fontforge#4416]
```
> fontforge -v
Version: 20200314
Based on sources from 2020-03-18 19:16 UTC-ML-D-GDK3.
fontforge 20200314
build date: 2020-03-18 19:16 UTC
```

I created a font (using the python module) that has 3832 characters, and a total of 60,000 glyphs. All the glyphs are mapped to one of the 3832 characters as an alternate substitution (namely the 'rand' lookup).

```
    font = fontforge.font()
    font.addLookup("random", "gsub_alternate", None, (("rand",(("DFLT",("dflt")),)),))
    font.addLookupSubtable("random", "rand-sub")

    # i add all the characters and variations here

    font.selection.all()
    font.addExtrema()
    font.save("font.sfd")
    font.generate("font.otf")
```

The sfd file gets generated just fine, but after making the otf, I get the error 
```
Internal Error: Attempt to output 65542 into a 16-bit field. It will be truncated and the file may not be useful.
Internal Error: Lookup sub table, rand-sub in random, is too big. Will not be useable.
```

Why am I getting this error? I know that SFNT has a maximum of 65536, but 60,000 is more than 5k glyphs less than that constraint.  
After deleting a couple hundred glyphs it told me `Attempt to output 65568 into a 16-bit field.` meaning that the number went **up** even though I removed characters…     
It's not the code that's the problem because when I generate a font with under 10,000 glyphs it doesn't give me this error.   
When I try to export the otf from the generated sfd with 60,000 glyphs through the fontforge gui it also gives me the error.  

Why is it still giving me this error?

Even with the error, the font still works, but it doesn't replace any characters by its 'rand' substitutions, which was the whole point of this font. It only renders the base glyph; the lookups got disabled.  

<br>

The files that I'm talking about are bundled here:  
[fonts.zip](https://mega.nz/file/b4IQBChR#R_KHm1KG83F4MNqDScfPTmJvAgbpQheMxxl4wrgEv4A)  
 - font-60000.sfd/otf
    - the 60,000 glyphs large font that's causing problems
 - font-263.sfd/otf
    - a small sample font (with 263 glyphs) that works flawlessly that was generated from the same script as font-60000
 - font-test.svg
    - an InkScape svg that should render the alternate substitutions. It works for font-263, but not for font-60000

![image](https://user-images.githubusercontent.com/62402760/89219894-a18ad200-d59e-11ea-9991-c10e4ae9dc5c.png)

font-60000.otf should also be using alternate substitutions just like font-263.otf is.

**Comment by skef** [comment]
Offsets into an individual GSUB table are encoded as unsigned 16 bit integers. The result is that each is effectively limited to a length of 2^16 bytes. How many entries that size corresponds to depends on the format of the table. 

FontForge is noting here that the size of "rand-sub" exceeds that limit; there is nothing FontForge itself can do about that.

**Comment by dscorbett** [comment]
I ran into a similar problem in my font. My solution was to generate lookups using [fontTools](https://fonttools.readthedocs.io/en/latest/) instead of FontForge. fontTools automatically splits gigantic subtables into multiple smaller subtables.

**Comment by ctrlcctrlv** [comment]
Essentially you just need to tell FontForge to make several rand subtables instead of one.

**Comment by ekaunt** [comment]
Thanks ya'll, I split the lookup every 10,000 glyphs and it works now!
