### ISSUE TITLE
Crash when generating OTC

### ISSUE THREAD

**Issue by WolfGangsta** [fontforge/fontforge#4417]
I'm trying to use FontForge's font collection generation capability to make an OpenType Collection out of a set of OTF files, as mentioned in #3543, but FontForge always fails, leaving only an empty (0 bytes) file in the target directory with the name I wanted to give it (emmentaler.otc).

When I try to run the Python generateTtc function on the files with the "cff" and "merge" ttcflags set, execution stops almost immediately. This was tested on Windows 10 (with FF 20190801) via FontForge interactive console and on LilyDev 2, a fork of Debian (with FF 20170812), via regular bash. On LilyDev, the crash is reported as a segfault, while no error message appears on Windows.

When I use the "Generate TTC..." GUI dialog (again, with the "Merge tables across fonts" and "As CFF fonts" options checked), FF exits immediately, having hit, I presume, the same segfault. I tested the GUI on both Windows and LilyDev, same as above.

The issue is present even when only attempting to merge two of the eight fonts, so I'm attaching a couple of the fonts that fail the merge, along with a stripped-down version of the generation script that still demonstrates the crash: [emmentaler.zip](https://github.com/fontforge/fontforge/files/5018232/emmentaler.zip)

(N.B. The files are a WIP version of Emmentaler, the standard music font for GNU LilyPond, so there's no issue with them going public. Also, since it's a music font, most of the glyphs reside in the PUA after 0xE000.)

**Comment by skef** [comment]
I appreciate the effort put into isolating this. Unfortunately the script in the provided archive refers to `emmentaler-11.otf` and `emmentaler-13.otf` but only contains `emmentaler.otf`. If possible could you update the archive with the needed files?

**Comment by jtanx** [comment]
@WolfGangsta do you still have the files required to reproduce this issue?

**Comment by skef** [comment]
Closing for lack of information.

**Comment by ceztko** [comment]
The attached [FoxitSerifCFFSet.zip](https://github.com/user-attachments/files/17788065/FoxitSerifCFFSet.zip), taken from [pdf.js](https://github.com/mozilla/pdf.js/tree/master/external/standard_fonts) (but was first found in pdfium) crashes FontForge 20230101 when trying to create a collection "As CFF fonts". Please re-open.

**Comment by Yukinoroh** [comment]
I just debugged this. It took two days.
Incomplete "don't generate FFTM" implementation was the culprit.
Fixed in pull request #5509.
