### ISSUE TITLE
Crush when loading Microsoft.YaHei.Mono

### ISSUE THREAD

**Issue by ElonH** [fontforge/fontforge#4418]
Using fontforge AppImage to load Microsoft.YaHei.Mono

application crush
```
$ ./FontForge-2020-03-14-67687b0-x86_64.appimage
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20200314
 Based on sources from 2020-03-14 03:38 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: 67687b099f82022d7384c76d0e1509fcc5e938b9
[1]    106213 segmentation fault (core dumped)  ./FontForge-2020-03-14-67687b0-x86_64.appimage

```
Font Link:
https://github.com/microsoft/terminal/issues/84#issuecomment-366114783
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
Seems like the `post` table is longer than strictly necessary, padded with zeroes.
