### ISSUE TITLE
Scripting constants changed in 1536d58fb5969c73644337053c8af2ffe3e0ae82

### ISSUE THREAD

**Issue by mahkoh** [fontforge/fontforge#4419]
In commit 1536d58fb5969c73644337053c8af2ffe3e0ae82 the value of the constant causing `ttf_flag_nohints` was changed from `0x8` to `0x80000`. `0x8` now means `ps_flag_nohints`.

In the case of python scripting, `omit-instructions` continues to map to `0x8` (now `ps_flag_nohints`, previously `ttf_flag_nohints`).

This change in values broke the build of the DejaVu fonts which uses both the constants and the python names to strip the tt instructions. I believe that this is also in violation of the documentation:

>#### no-hints
>Do not include PS hints

>#### omit-instructions
>Do not include TrueType instructions

I've submitted a patch downstream to fix the build: https://bugs.archlinux.org/task/67500

But this patch is distro specific because some distros might ship fontforge versions from before 1536d58fb5969c73644337053c8af2ffe3e0ae82.

**Comment by ctrlcctrlv** [comment]
Thanks @mahkoh , but I don't quite understand why you say the patch is "distro specific", or indeed, what this even has to do with us.

Seems like we, perhaps inadvertently, broke the DejaVu build, which expected an earlier FontForge version. It is quite normal, _especially_ for fonts which require the old FontForge scripting interface, to specify an old version of FontForge which must be used. An example is GNU FreeFont, see [[1]](https://github.com/fontforge/fontforge/issues/4261#issuecomment-609147712).

But, the native scripting interface is deprecated, see [#D2](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D2). We need the ability to add constants...what should we have done differently here? And are you thinking we should apply a patch?

Just one of many reasons not to use the native scripting function is that constants are not accessible as they are through Python. The flag is `("no-hints",)` to `font.generate` in Python.

**Comment by mahkoh** [comment]
Before the linked commit, using `omit-instructions` from python or the flag 0x8 from old-style scripts caused truetype instructions to be stripped. Now it no longer does. Are you saying this was intentional?

**Comment by ctrlcctrlv** [comment]
Oh, I see what you mean. The problem is not us adding new flags as part of recent work to Generate dialog, this is older work (despite it being Skef's commit, it's part of my first PR to this repo, funny!).

You are saying that 1536d58 inadvertently flipped `omit-instructions` and `no-hints`. It made `fm_flag_nopshints` omit TTF instructions, and `fm_flag_nottfhints` now drops the PostScript hints. Oops.

Is that right? Yes, that would be a bug.

**Comment by ctrlcctrlv** [comment]
So, if we fix this...which I think we should if I'm right about the problem...what does that mean for you and your Arch Linux patch @mahkoh ? You're going to need a new release from us, right...? Or are you going to ask Arch's `fontforge` package maintainer to backport our patch?

**Comment by mahkoh** [comment]
>You are saying that 1536d58 inadvertently flipped omit-instructions and no-hints.

Yes

>It made fm_flag_nopshints omit TTF instructions

Not quite. fm_flag_nopshints does what the name says. However, fm_flag_nopshints has the wrong numerical value 8 instead of 0x80000 and the python engine maps omit-instructions to fm_flag_nopshints instead of fm_flag_nottfhints. So the bug is a bit spread out. 

---

Fundamentally this was an api break. But it happened in 2019-03 and at this point there might be fonts depending on the new behavior. For example if the DejaVu font is fixed in arch by applying my patch to the DejaVu  package, then the package will break again if you make a release with the old behavior restored.

**Comment by ctrlcctrlv** [comment]
OK so it seems like the most prudent thing to do is fix the Python mapping but leave the numbering alone.

**Comment by ctrlcctrlv** [comment]
(I would assume that most people providing "no-hints" to Python are, or should be, also providing "no-instructions", by the way.)

**Comment by skef** [comment]
Yeah, this looks like a straightforward inversion that slipped past both the author (me) and the review process.

Given that the docs haven't changed I wouldn't worry in-the-mean-time fixes to individual scripts. We would just be fixing a bug introduced earlier, and they can adjust back.

**Comment by frank-trampe** [comment]
It looks like I'd need to read some code to figure out exactly what's going on here. Was this a mistaken change or an incomplete one? Would somebody submit a pull request to implement the corresponding fix?

**Comment by frank-trampe** [comment]
@skef, is this an easy fix?

**Comment by skef** [comment]
Should be. I'll take a look.
