### ISSUE TITLE
Question: how can I set a shortcut key to toggle "Use My Metrics" option in "Reference info" menu

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4422]
Hi
I'm using the latest fontforge version on windows 10 and need to check a huge number of glyphs(which are combined of at least 2 components) and set the "Use My Metrics" option(for one of the components) in the Reference Info menu. I can't find it in the hotkey shortcuts file. so what is the solution?
(I need to work with GUI to see and check the components)
thank you.

![fontforge_2020-08-08_20-51-43](https://user-images.githubusercontent.com/25493297/89715156-2881e500-d9b9-11ea-9df1-e8d3cc055979.png)

**Comment by skef** [comment]
Only FontForge menus have hotkeys per se.

Keyboard acceleration in dialogs is supposed to work (as far as I'm aware) through the alt-accelerators indicated by the underlined letters, which are supposed to *select* the element in question. This seems to work, in the sense that if I open the window (on my Arch Linux box), type Alt-U, and then hit the space bar, the "Use My Metrics" box checks and then unchecks, so it was at least selected correctly.

Therefore:

1. @aminabedi68 : See if Alt-U followed by space has a better outcome on Windows, and report back. Even if it works, don't close this bug yet.
2. @jtanx : I guess we need to figure out what's going on with the keystroke handler for checkboxes, either on Linux or generally.

(Note that the acceleration is broken in a number of contexts, such as in dialogs that have their own menus (e.g. the Expand Stroke dialog), dialogs with duplicate entries, or elements where the "label" is separate from the associated UI element.).

**Comment by aminabedi68** [comment]
hi @skef 
yes, it works as you explained (it's not better and still can't help a lot obviously)

**Comment by skef** [comment]
Alright - I may take a look at the handler problem relatively soon if I get a chance. Not in the next couple hours or whatever, but maybe in the next day. If I do a fix and there's a quick review that could give you a build to work from within the next couple days.

**Comment by skef** [comment]
@aminabedi68 I suppose you can try https://ci.appveyor.com/api/buildjobs/ttqttnnjbvo5e9ob/artifacts/fontforgebuilds%2FFontForge-mingw-w64-i686-1594a3-appveyor.7z prior to review if you like.

**Comment by aminabedi68** [comment]
thank you @skef , It's better now. one click on the spacebar toggles the checkbox (I still think it would be nice to access all these options directly via keyboard)
