### ISSUE TITLE
Crashes when importing simple .SVG from illustrator, seems to only happen to circle shapes.

### ISSUE THREAD

**Issue by MrCharli3** [fontforge/fontforge#4425]
Import view:
![bild](https://user-images.githubusercontent.com/20385838/89884960-93eed100-dbca-11ea-967d-40c5aca165d6.png)

My shape:
![bild](https://user-images.githubusercontent.com/20385838/89885289-23947f80-dbcb-11ea-83e9-7556c5ceec01.png)

Version: 20200314
OS: Windows X

I export a simple .SVG from adobe illustrator, but when importing it in fontforge, fontforge crashes. I had success with a rectangle, but when I try a circle it crashes.

Repro: Create a Circle shape in adobe illustrator, save as .SVG, try to import into fontforge.

**Comment by KamilLanda** [comment]
Try the version 06-04-20 https://sourceforge.net/projects/fontforgebuilds/files/i686/Installer/

**Comment by atjn** [comment]
Thanks @KamilLanda - I had this exact issue. Downloading the 06-04-2020 version solved the issue.

**Comment by ctrlcctrlv** [comment]
Closed as duplicate. Sorry everyone, next release will fix it.
