### ISSUE TITLE
Wrong fontlint warning about Omega glyph

### ISSUE THREAD

**Issue by th-otto** [fontforge/fontforge#4426]
When assigning a glyph named Omega to U+3A9, fontlint warns:

```
The glyph named Omega is mapped to U+03A9.
  But its name indicates it should be mapped to U+2126.
```

But according to the unicode database, U+2126 is Ohm, not Omega.

**Comment by ctrlcctrlv** [comment]
This has nothing to do with Unicode. FontForge is pre-Unicode.

`Omega` is a name from the [Adobe Glyph List](https://en.wikipedia.org/wiki/Adobe_Glyph_List). The AGL's relationship to Unicode is extremely complicated; see [[1]](https://github.com/adobe-type-tools/agl-specification).

But we can quite simply look and see you're wrong:

https://github.com/adobe-type-tools/agl-aglfn/blob/4036a9ca80a62f64f9de4f7321a9a045ad0ecfd6/glyphlist.txt#L480

>     Omega;2126

Sorry&mdash;closing as invalid.
