### ISSUE TITLE
Merge 2 fonts

### ISSUE THREAD

**Issue by Golddouble** [fontforge/fontforge#4429]
I have two *.ttf fonts. Font 1 has filled some font boxes, that font 2 has empty.

I want to have a new font (Font 3), that contains all of font 1 and font 2.

How can I do this?

I have already tried, but:
-When I copy a box with a font from Font 1 to an empty box in font 2, then "copy/paste" does not work.
-When I copy a box with a font from Font 1 to a new created font (Font 3), then I can paste it in an empty box in font 3, but it's much bigger in font 3 now, as it was in font 1. So it seems it's not the same then.

**Comment by KamilLanda** [comment]
Open Font1 and from his menu (File/ Open) open Font2. Then copy/paste will be probably functional. 

In File/ Preferences/ New Font -> there is parameter NewEmSize for new font. Maybe Font1 has different metrics, look to the Element/ Font info/ General

**Comment by ctrlcctrlv** [comment]
Yup, what @KamilLanda said.

**Comment by Golddouble** [comment]
> Open Font1 and from his menu (File/ Open) open Font2. Then copy/paste will be probably functional.

Thank you I was able to copy/paste boxes from font 2 to font 1 this way.
But the characters from font 2 are much too small in the boxes of font 1 now.



> Maybe Font1 has different metrics, look to the Element/ Font info/ General

Here are the difference settings of this fonts:
![Fontforge](https://user-images.githubusercontent.com/13977359/90288924-23221000-de7b-11ea-93ac-950a325a4e81.png)


But I am confused: It looks like this is a setting for all characters in all boxes of a font. 
But when I copy boxes from the right to the left, shouldn't then have the boxes of the left font, where I will copy in the characters from the right font, not have different settings?

**Comment by ctrlcctrlv** [comment]
No. Fonts have a concept of an `em size`, units per em&mdash;UPM. A font cannot have some glyphs with certain metrics and others with different ones. UPM must be uniform throughout the whole font.

The left font is 2048 UPM, the right 512 UPM. When you copy from the left to the right, therefore, of course the glyphs will appear larger. You must equalize the UPM of both fonts to avoid that.
