### ISSUE TITLE
How can I copy-paste ligatures from one font to another?

### ISSUE THREAD

**Issue by rediffusion** [fontforge/fontforge#4430]
Hello! 🙂

FontForge-2020-03-14-Windows
«Windows 10 2004»

---

 I have the font "**Fira Code**". I want copy then paste ligatures to this font "**Droid Sans Mono**". Is it possible? 
Please give me the manual on the link to the video tutorial (maybe YouTube or something). I'll appreciate it!

Best regards❗ ✌️

**Comment by ctrlcctrlv** [comment]
This is not so simple. Furthermore, the bug tracker is not a forum, sorry.

You need to do three things:
* copy the actual glyphs for the ligatures
* resize the new glyphs if needed to fit the new font's UPM
* add the OpenType features to do the ligature substitution

Future questions should be directed at IRC or the mailing list, per [#G2](https://github.com/fontforge/fontforge/wiki/Community-guidelines#G2). Thanks 😄
