### ISSUE TITLE
«Metrics→Set LBearing» fails to set glyph width; but «Metrics→Set RBearing» does

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4433]
Hi
this is an old issue about R/LBearing adjustment with fontforge metrics settings(ctrl+R/L in GUI). (I use fontforge on windows)
any change on RBearing directly affects the glyph width(which is right) but if you change LBearing value, the width will not change, so RBearing changes on the opposite side and you have to adjust the RBearing again.

**Comment by ctrlcctrlv** [comment]
Gave issue more descriptive title; confirmed. Python not affected, so fix is simple, we just need to do it right; no worries about backwards compatibility introduced by changing our behavior.

Verify with:

```python3
import fontforge as ff

f = ff.fonts()[0]

g=f[981]

g.left_side_bearing=0
```
