### ISSUE TITLE
Reserving a font name is probably not a sane default when adding OFL license

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4434]
http://web.archive.org/web/20160822030019/https://lwn.net/Articles/552178/

I consider Reserved Font Names (RFNs) harmful; Google Fonts (@davelab6) does not allow them, nor should they.

Reserving a font name primarily serves to detract from the work I put into my fonts, as fork authors feel forced to rename them, rather than acknowledge my work.

Furthermore, many RFNs are in practice legally null and void; for example, if I tried to declare an RFN on my KJV1611 font, that would be preposterous. Second, let's say a user opens a font under another FOSS license compatible with the SIL OFL, and decides to relicense their font as SIL OFL; to declare an RFN means that they are telling original author they can't use their own font name! (Obviously legally null and void.)

So, I think the GUI button "Add OFL" should not add an RFN by default. Perhaps a dialog should pop up asking, which explains a little bit about benefits and drawbacks of RFNs.

Comments?

Edit: Of course, we should not change people's saved fonts. Only if they click "Add OFL" should it change. By adding a dialog, we can inform old users that the effect of the button has changed.

**Comment by greytomorrow** [comment]
An interesting topic. My 2¢...

> as fork authors feel forced to rename them, rather than acknowledge my work.

> to declare an RFN means that they are telling original author they can't use their own font name!

I don't think the spirit of the SIL OFL is to *fork outright* as opposed to fold changes back into an existing font. With or without an RFN, if someone does makes modifications *for public release* to the original font, after contacting and consideration by the font creator/copyright owner, changes would be added to the original with a FONTLOG addition crediting the amendments. Obviously, if the original creator rejects the proposed changes, the OFL clearly allows *forking* with a new name -- the entire history of the typeface industry has been built on this, right or wrong, better or worse.

That said, you're not wrong in thinking that FontForge's RFN addition when adding the SIL license shouldn't be automatic, convenient as it may be.  Ultimately, it isn't up to FontForge to make that decision for the user.

I see four options here:
- Remove the `Add OFL` button entirely -- it would be up to the user to add their own license, which isn't necessarily a bad thing
- Add the explanation of the benefits/drawbacks of an RFN (or link to one) -- your original suggestion
- Remove the "five offending words" from the `Add OFL` option -- coming in a close second for the easiest option
- Leave things as they are -- no babies are being killed, no one is forced to hit that button, and not every FF user is designing OFL fonts

Personally, this issue doesn't leave me neither hot nor cold as it doesn't change functionality nor do I see this as a developer high-priority issue (a method for reshuffling non-unicode glyphs, for example, or fixing the many papercuts on the macOS version would be higher on my list).

**Comment by ctrlcctrlv** [comment]
Hi @emiguy3657 , unfortunately as far as your idea of priorities goes, it is not likely that we are going to be able to improve the situation on OSX anytime soon. I'm aware that many problems exist but I don't have a Mac and I don't know that it's appropriate even if I did for me to buy an Apple development key for $100 or however much it is to sign our releases. As I understand it, this is the main problem. Apple has some system called GateKeeper that requires us to fork over money for a signature. 

It might make more sense given how lightweight FontForge is, to use it within a virtual machine

**Comment by greytomorrow** [comment]
Ehmm...I think there's a little confusion here on your part. :smile:

First off, I think you're addressing the wrong person. @emiguy3657 posted something (totally) off-topic to the issue at hand.

Secondly, you misunderstand my final statement. I repeat that *I* consider the issue at hand (default RFN setting) low-priority. I didn't intend that the issues I stated are **high-priority**, but IMHO just higher than the philosophical argument at hand. I certainly didn't want to get into a "$99 Apple development key/Gatekeeper" discussion. FontForge on macOS works well enough. I think it's great that (for a good while now) X11 is no longer needed. I think it's great that (for the most part) the shortcuts have been mapped to the Command key. There's just a few issues -- "papercuts", so to speak. Ultimately, it's all up to *you* and the other programmers to decide bug/feature priorities. It's *your* baby.

Certainly, installing a (minimum) 8GB virtual machine *plus* the virtual machine software (you pick) just to run FontForge is a bit...excessive? It certainly isn't *lightweight."

But this is all off-topic to the issue at hand.

> Comments?

Well...*I* commented. I expressed my views on the OFL and RFNs. So far, no one else has responded to the "RFN or not" issue, leading me to believe that, so far, no one else sees this as high priority either. I'm **not** implying *ergo, it's a bad idea.* Just saying.

**Comment by davelab6** [comment]
RFNs have a valid use case: authors like SIL who don't want to deal with a support burden of 3rd party modifications, or those who see the opposite of Fred and actively want any forks to not be associated with them. 

But I believe this is a minority of OFL users. 

I think if the add OFL button has a good tooltip explaining the RFN option is available, and a link to the official FAQ which does advocate for RFNs, that's sufficient - and better than today
