### ISSUE TITLE
[documentation] Even Ubuntu should use AppImage since PPA often out of date

### ISSUE THREAD

**Issue by mnh48** [fontforge/fontforge#4439]
I created the original SFD file on my server (arch: amd64) which I connect from my device using VNC and SSH at that time, and the files are also available to public at: https://github.com/beringin-mnh48/mnh48-beringin

As I could not pay my server as I don't have enough money anymore after using it for food instead, I'm trying to open the same file on my only device available instead (arch: i686, but most software compiled for it seemed to be using i386) to continue editing as I want to add a few more glyphs and change some of the font feature, but:
1. it spouts out warning "Bad SFD Version number 3.2" when I'm inside the directory
2. it gives the error "not in a known format (or uses features of that format fontforge does not support, or is so badly corrupted as to be unreadable)" when I try to open the file.

### Screenshot
![image](https://user-images.githubusercontent.com/12217018/91975046-59073580-ed51-11ea-95a2-5f1b222f0ce3.png)
![image](https://user-images.githubusercontent.com/12217018/91975105-75a36d80-ed51-11ea-9369-50e70bdb4d6b.png)

### FontForge version
```
$ fontforge --version
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:21 UTC 24-Sep-2017-ML-D.
 Based on source from git with hash: 
no xdefs_filename!
TESTING: getPixmapDir:/usr/share/fontforge/pixmaps
TESTING: getShareDir:/usr/share/fontforge
TESTING: GResourceProgramDir:/usr/bin
trying default theme:/usr/share/fontforge/pixmaps/resources
fontforge 11:21 UTC 24-Sep-2017
libfontforge 20170924
```

It is the latest version from the PPA that is available for me, no more updates are available.
(Unrelevant parts are omitted with [...])
```
$ sudo apt update
[...]
Hit:6 http://ppa.launchpad.net/fontforge/fontforge/ubuntu bionic InRelease     
[...]
Fetched 252 kB in 11s (23.0 kB/s)                                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

### Operating system
```
OS: Ubuntu 18.04.5 LTS i686
Host: Pine Trail - M CRB Revision A 
CPU: Intel Atom N450 (2) @ 1.667GHz 
GPU: Intel Pineview M x86/MMX/SSE2 
Memory: 673MiB / 987MiB 
```

### Steps to reproduce
Using the operating system Ubuntu 18.04 LTS i686 (labelled as i386 on their side), install FontForge as instructed on the [download page](https://fontforge.org/en-US/downloads/gnulinux-dl/), section Ubuntu:
```
sudo add-apt-repository ppa:fontforge/fontforge;
sudo apt-get update;
sudo apt-get install fontforge;
```
Launch FontForge, then try to open any of the .sfd files from here:
https://github.com/beringin-mnh48/mnh48-beringin

### Behavior
Expected: It opens the file so that I can continue editing
Actual: It could not open the file

### Additional note
I also tried to move the file elsewhere to rule out problem with "space in path",
it is still the same so the space character is not the culprit here.

### Checklist
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
Probably a version mismatch. Not sure if the PPA is updated. Try using the Appimage.

**Comment by ctrlcctrlv** [comment]
Yeah for sure. You're using some ancient 2014 version of FontForge. You need to use something from at least the last two years. I can't remember exactly when we bumped the SFD version but I think it was in 2019.

**Comment by mnh48** [comment]
Like what I've written in the issue, I'm using the latest version from the PPA, as it is what is instructed on FontForge's own website.

If the instructions are wrong and Appimage is what I should be using instead from the beginning then it's a bug for the website and they need to change the instruction.

If the PPA is indeed the recommended way but it gets outdated then they should update it, PPA doesn't need to follow mainstream Ubuntu releases and can release newer versions regardless the OS version.

I'm an end user here, not a developer, but I'll try to use Appimage as suggested and see if it works.

**Comment by ctrlcctrlv** [comment]
Well you are using a very old version of Ubuntu so I don't know that you can blame even the maintainer of the PPA. It is unsupported to use a file from a new version on an old one of course.

**Comment by ctrlcctrlv** [comment]
I doubt our PPA maintainer is still compiling for i686 and don't think they're going to start, sorry. Time for a new computer, I reckon. I get not everyone can afford one, times are tough right now, but this isn't a priority.

**Comment by ctrlcctrlv** [comment]
One final thought: it probably makes a lot more sense to compile FontForge yourself than tou use a layer of indirection like Wine. It is not that hard to compile and does not have many dependencies

**Comment by mnh48** [comment]
sorry for the late reply
> One final thought: it probably makes a lot more sense to compile FontForge yourself than tou use a layer of indirection like Wine. It is not that hard to compile and does not have many dependencies

compiling from the source is usually known to be something that only advanced users would do
running FontForge via Wine do work, but since you wrote that it would be more sense to just compile myself

I tried to compile it, and after encountering some error and fixing them, I succeeded installing it, even though there were some warnings and notes being sprinkled around in the process
<details>
  <summary>first error detail</summary>
  
the first error was encountered on the `cmake -GNinja ..` step where it gives out these error:
```CMake
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Python3 (missing: Python3_LIBRARY Python3_INCLUDE_DIR
  Development) (found suitable version "3.8.0", minimum required is "3.3")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/backports/3.15.7/FindPython/Support.cmake:1660 (find_package_handle_standard_args)
  cmake/backports/3.15.7/FindPython3.cmake:215 (include)
  cmake/PackageUtils.cmake:41 (find_package)
  CMakeLists.txt:137 (find_package_auto)
```

I already had `python3-dev` installed but that didn't help, finally solved by installing `python3.8-dev` instead, I should have checked the exact python version installed before troubleshooting further
</details>

<details>
  <summary>second error detail</summary>
  
the second error was encountered on the `ninja install` step where it gives out these error:
```ninja
[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/libfontforge.so.4
CMake Error at fontforge/cmake_install.cmake:52 (file):
  file INSTALL cannot copy file
  "/home/yaya/Downloads/fontforge/build/lib/libfontforge.so.4" to
  "/usr/local/lib/libfontforge.so.4".
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)


FAILED: CMakeFiles/install.util 
cd /home/yaya/Downloads/fontforge/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

since I see that it is installing to `/usr` space I figured out that it might need root permission
so instead of the instruction `ninja install`, I change it to `sudo ninja install`, and it worked
</details>

<details>
  <summary>some of the warnings and notes shown</summary>

```CMake
../fontforge/savefont.c:669:16: note: directive argument in the range [0, 2147483647]
  sprintf( buf, "%d", subfont );
                ^~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../inc/basics.h:37,
                 from ../fontforge/splinefont.h:31,
                 from ../fontforge/savefont.h:33,
                 from ../fontforge/savefont.c:30:
/usr/include/i386-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 2 and 11 bytes into a destination of size 8
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and
```CMake
[127/309] Building C object fontforge/CMakeFiles/fontforge.dir/scripting.c.o
../fontforge/scripting.c: In function ‘_CheckIsScript’:
../fontforge/scripting.c:11021:6: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
      fgets(buffer,sizeof(buffer),temp);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
among others
</details>

---
I'm now running this version:
```
$ fontforge -v
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20200314
 Based on sources from 2020-09-13 21:14 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: c3468cbd0320c152c0cbf762b9e2b63642d9c65f
fontforge 20200314
build date: 2020-09-13 21:14 UTC
```

and I can now open the files correctly
sorry for any troubles caused

**Comment by ctrlcctrlv** [comment]
Good news. No trouble at all. FontForge is simpler to compile from source than other software. It might work on Wine, I don't know, but a native binary will always work better. :-)
