### ISSUE TITLE
First row of characters show 'error character'

### ISSUE THREAD

**Issue by Darkmaster006** [fontforge/fontforge#4443]
I am using Windows 10, the latest update (2004). 64-bit. Fontforge is the latest version (20200314). Here's an screenshot 
![dsafsd](https://user-images.githubusercontent.com/21136515/92497999-72d0ce80-f1d0-11ea-81a5-57fd7134cb4c.png)
The first row, as you can see, doesn't show me any of the characters that are supposed to be shown there. How can I fix this? Hope someone knows, thank you!

**Comment by ctrlcctrlv** [comment]
Hello. Those aren't error characters, it's supposed to be like that. FontForge shows you the entire encoding you've requested. You've requested the Unicode Basic Multilingual Plane, so are being shown the [C0 and C1 control codes](https://en.wikipedia.org/wiki/C0_and_C1_control_codes).
