### ISSUE TITLE
MAC OSX / STOPS INSTANTLY WHEN STARTING APP / CRASH

### ISSUE THREAD

**Issue by Skriptic** [fontforge/fontforge#4449]
HELP RUNNING OSX EL CAPITAN Each Time I start fontforge it just closes itself I tried with EVERY version of fontforge it still was crashing hope someone would be able to help me out I really wanted to try out fontforge. pls help :(

**Comment by jtanx** [comment]
Upgrade your os. You can try versions  20190413 or less but if it doesn't work there's not much that can be done.

**Comment by greytomorrow** [comment]
Is there somewhere that specifies the minimum requirements for using FontForge on various OSes? I haven't been able this information. For example I'm running macOS 10.13.6. Which is the latest version of FontForge that will run with this version?
