### ISSUE TITLE
FAQ or FeatureReq: How to change the font size of the measure tool?

### ISSUE THREAD

**Issue by noisnemid** [fontforge/fontforge#4454]
### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

![fontforge-snapshot-measure-tool-font-too-small](https://user-images.githubusercontent.com/16525011/94465034-dce9fb80-01f1-11eb-870d-9eb81dad6c7e.png)

As the screenshot shows, the font size of this UI is too small to read easily on screen.

As my screen is a common-modeled one with normal PPI (96), that too small font size of the measure tool UI is very hard to read.

It will be very nice if there is a way to set that a bigger font size.

-------------------------------------------------
Thanks for the creation to the world!

**Comment by skef** [comment]
The comment on this is a bit misleading. `GResourceFindFont()` uses the second parameter as a default, but will ignore it if the first argument validly specifies a font. So if `CharView.Measure.Font` by giving an appropriate value in the X Resources you can choose the font.

The "gap" is that `CharView.Measure.Font` isn't represented in the X Resources window so you have to add it by hand.
