### ISSUE TITLE
italic angle ignored by the fontforge in side bearing adjusment

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4461]
Hi
in earlier fontforge versions (before GTK) side bearing adjustment was always applied with considering the italic angle but now it's not working. here is an example:

![rect1349](https://user-images.githubusercontent.com/25493297/95244640-18527e80-081f-11eb-8b51-90383836aaad.png)

**Comment by frank-trampe** [comment]
What is the version or release date of the one that works correctly?

**Comment by frank-trampe** [comment]
And are you sure that it is the same input file? Even in old code, I see no reference to the italic angle, which makes me think that this might instead be about a flattened transformation matrix rather than side bearing handling.

**Comment by frank-trampe** [comment]
The relevant function seems to be DoChar in fvmetrics.c, in case you want to look at the commit history yourself. It is called from the dialog box by the various "Doit" functions in the same file.

**Comment by aminabedi68** [comment]
yes, it's weird! sorry, I was pretty sure(i saw it somewhere) so I didn't check it before opening the issue.
