### ISSUE TITLE
issue about right-click button on windows OS

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4462]
Hi
in the latest fontforge version on windows(and maybe in other versions), right-click button(on the keyboard) working continuously(stacking right-click menu bars as long as keep pushing on the right-click keyboard key).

**Comment by jtanx** [comment]
Can you screenshot or explain this a bit more clearly?

**Comment by aminabedi68** [comment]
I pushed on the right-click button key for 2 seconds and the menu bars repeated over 20 times.

![bitmap](https://user-images.githubusercontent.com/25493297/95305913-7de05280-0893-11eb-9424-a3b2dff6f671.png)

**Comment by jtanx** [comment]
hmm, I can't reproduce the issue. When you say latest version, you mean the one off fontforge.org? And by `right-click button key` you mean the right click button on your mouse?

**Comment by aminabedi68** [comment]
i have this version: ```FontForge-mingw-w64-i686-1594a3-appveyor```(i guess)
and no, i mean right-click keyboard key, it's near the left ctrl key so it happens many times and really annoying.

**Comment by jtanx** [comment]
Right, I see, the menu key.

**Comment by jtanx** [comment]
@aminabedi68 can you try out the build from https://ci.appveyor.com/project/fontforge/fontforge/builds/35613900/artifacts?

**Comment by aminabedi68** [comment]
yes! it's working nice :)
