### ISSUE TITLE
Question/Feature Request: moving a glyph without affecting on component copies

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4464]
there is a problem i have faced many times; many glyphs like circumflex in Latin, dots in Arabic, and so on... usually used as components in other glyphs, sometimes we need to move them, which makes all components moved correspondingly, so is there a solution to prevent components from moving? (i know the component's coordinates should change in the opposite way but can't find them all and apply the change manually, I thought maybe the other people have the same problem)

**Comment by KamilLanda** [comment]
For move the reference only in some glyphs you can use scripting. Select glyphs in which you want to move reference (component) and menu File/ Execute script, check radiobox FF and put there command PositionReference(x,y,"nameOfComponentToMove"). 

For example you have component named "dot" and arabic letters "feh" and "noon" with this component. So select glyphs "noon" and "feh" and run FF script: PositionReference(0,300,"dot") and component "dot" above "feh" and "noon" will move 300pt higher.

**Comment by aminabedi68** [comment]
thank you @KamilLanda , it's not useful for me, I need a function to adjust (Δx,Δy) insteed (x,y).

**Comment by skef** [comment]
The delta version of the command is [`MoveReference()`](https://fontforge.org/docs/scripting/scripting-alpha.html#MoveReference)

**Comment by aminabedi68** [comment]
thank you @skef , almost done. can i select all glyphs with a special component using script?

**Comment by skef** [comment]
I know more about the python scripting interface than I do about the native one. But do you need to? It seems as though `MoveReference()` searches for references that match the name, so if you just use `SelectWorthOutputting()` first the relevant glyphs will be found.

**Comment by aminabedi68** [comment]
yes, you're right, thank you so much 💐
