### ISSUE TITLE
Font forge crashed once on import, now it crashes every time

### ISSUE THREAD

**Issue by MrCharli3** [fontforge/fontforge#4466]
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
**2020-03-14, OS: Windows 10**
- [x] The behavior you expect to see, and the actual behavior
**Expect SVG from Illustrator to be imported as a glyph, instead crashes, even with SVGs that have worked fine before.**
- [x] Steps to reproduce the behavior 
**It started when I tried to import an SVG from illustrator that was using outlines, and had not been properly merged into one shape.**
- [ ] \(optional) Possible solution/fix/workaround

**I have re-installed font forge 3 times, restarted my PC, and tried in a new font forge project to import a SVG that has worked without any issues before, still just get an empty crash every time I Import.**

**Comment by skef** [comment]
The combination of reported issues is strange (as I think you agree).

Given that you reported an SVG crash (#4425) in August is it possible that you:

1. Before those problems were using the 2020-03-14 release version of the software.
2. On our advice, installed a more recent development build to work around your reported SVG problem.
3. Eventually ran into an SVG that still crashed that version.
4. Now forgetting about the development version, tried to reinstall the production and are now experiencing all the old problems?

Your earlier bug was closed but we aren't sure what advice you followed.

In general our advice for the SVG problems is to try a recent development build, e.g. https://ci.appveyor.com/project/fontforge/fontforge/build/artifacts . That has fixed everything so far except for #4452 .

**Comment by MrCharli3** [comment]
@skef thank you, while a bit embarrasing to admit this seems to be the issue. I also ran into an issue with AVG blocking the .exe file.

**Comment by skef** [comment]
If the particular SVG that started these latest troubles off still crashes on import with the development build please post it here and reopen. I or someone else will try to clean up any remaining crashes eventually.

**Comment by MrCharli3** [comment]
@skef sorry I merged the path so I no longer have it. But basically any shape from illustrator that uses outline seems to crash the program. Works when you convert outline to shape.

**Comment by skef** [comment]
@MrCharli3 That's fine.

Since you're working with SVGs frequently don't hesitate to file issues you run into with development build versions of the program. (Obviously the last release causes problems for certain kinds of SVGs so it's not very useful to test against at this point.)

**Comment by ctrlcctrlv** [comment]
It would definitely help us for you to provide a path that crashes FontForge even if every path from a certain proprietary program does, because we don't necessarily have access to that program. I don't have access to Illustrator for example.
