### ISSUE TITLE
python: fontname is changed on font open, without any option to not do it, and without any way to see the original

### ISSUE THREAD

**Issue by bjg2** [fontforge/fontforge#4468]
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
20200314
windows 10
- [x] The behavior you expect to see, and the actual behavior
When opening font through python fonforge removes some chars from fontname (like spaces) and I cannot find original fontname anywhere later. And I actually need it in my script.
- [x] Steps to reproduce the behavior 
Open a font with a space in its postscript name
- [ ] \(optional) Possible solution/fix/workaround

If this is 'by design' I hope that at least somewhere original fontname can be found, as I only see the one with problematic chars removed...

**Comment by skef** [comment]
I think what you're encountering is the difference between the "FontName" and the "FullName". The latter is intended for human-readable contexts and tends to have spaces and so forth. The former is for things like filenames. See https://fontforge.org/docs/ui/dialogs/fontinfo.html

You mention you're accessing the name from a script. If it's python see https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.fullname . If it is the native scripting language I'm not sure -- there is an interface for setting the name but not an obvious one for reading it (but that's just based on a brief look at the documentation).

**Comment by bjg2** [comment]
Sorry, I haven't described the problem well enough. I work with few thousand fonts and sometimes it happens that fontname has what fontforge considers invalid chars (like %/<>(){} etc but I think that each time for me it was space). I didn't do anything to make it that way - that's just the data that exists in the existing font file. It even shows when opening through GUI. Example:

![image](https://user-images.githubusercontent.com/6639273/96566532-f7ca0000-12c5-11eb-8ccc-30838a1d6c12.png)

Problem is, when opening the font with the postscript name that fontforge finds invalid, fontforge automatically removes chars it finds invalid. After opening the same font mentioned above fontname is `HartingPlain` instead of `Harting Plain`. Not to complicate by explaining my usecase any further, but I do need the exact post script name as it was written in the font file, regardless of whether it is valid or invalid. Can I get that info through python scripting?

Thanks!

**Comment by skef** [comment]
Ah, no, I doubt there's a current workaround for this problem. FontForge typically either tries to repair what it takes to be invalid data or gives up on opening a file; it doesn't tend to leave it in place.

**Comment by bjg2** [comment]
Not even some side-way to somehow from python call some code that reads name table without testing / repairing it? :/

Thanks anyway!

**Comment by skef** [comment]
FontForge isn't that kind of tool -- it provides font information by converting a font you open into its native format. That has advantages for some things but disadvantages in cases like this.

**Comment by bjg2** [comment]
Sorry for bother, but you seem to be informed and maybe you can help me.

I need to do these two things programatically:
* To be able to read the font postscript name without changing it
* To be able to change its postscript name without changing anything else and save it as a new font

Maybe fontforge is not the best option for these needs, can you recommend any other solution for this usecase? The rest of my codebase is in golang, if that has anything to do with the eventual recommendation...

**Comment by skef** [comment]
To do this by hand I would use [`ttx`](https://fonttools.readthedocs.io/en/latest/ttx.html). That tool lets you go back and forth between a TrueType or OpenType font and an XML representation of the font. Unfortunately I just played around a bit with trying to parse, change, and stringify `ttx` output and it seems as though ttx is sensitive to xml whitespace. If that could be made to work, though, you could do something like:

```
#!/usr/bin/env python

import subprocess
import xml.etree.ElementTree as ET

fname = "Harting_plain.ttf"

cp = subprocess.run("ttx -o - " + fname, shell=True, capture_output=True)

root = ET.fromstring(cp.stdout)
ps_elems = root.findall("*/namerecord[@nameID='6']")

for pe in ps_elems:
        # manipulate pe.text;

# feed ET.tostring(root) back into ttx
```

What you're looking to process is [`namerecord`s with `nameID` == 6](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids).

**Comment by bjg2** [comment]
That is EXACTLY what I need. Thank you very much sir, you are a gentleman and a scholar.

**Comment by skef** [comment]
FontForge happens to be a poor tool for this particular job -- closing.
