### ISSUE TITLE
FontForgeBuilds: pip.exe

### ISSUE THREAD

**Issue by dummy-index** [fontforge/fontforge#4469]
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

Installing FontForge-2020-03-14-Windows.exe, pip.exe is installed into FontForgeBuilds/bin/.
I suggest that ffpython is named such because the ffpython and the everyday use python can be simultaneously exist on search path. If so, pip.exe should also be renamed as such.
`mv pip.exe ffpip.exe`
`mv pip-script.py ffpip-script.py`

And in fact, this pip.exe doesn't work.
`failed to create process (C:\msys64\mingw32\bin\python.exe "C:\FontForgeBuilds\bin\pip-script.py").`
(I installed into C:\FontForgeBuilds)
This inexisting path is described in pip-script.py.
`#!C:/msys64/mingw32/bin/python.exe`
I modify it to
`#!C:/FontForgeBuilds/bin/ffpython.exe`
or
`#!./ffpython.exe`
then it become works.
But former (depends on the install directory) needs some effort, later is perhaps only for Windows (maybe this is a functionality of pip.exe)...

Or delete pip.exe and announce that to always use `ffpython -m pip <command>`?

**Comment by jtanx** [comment]
Thanks, I've gone with the latter (use ffpython -m pip)
