### ISSUE TITLE
Feature Request: please add a scripting procedure for importing of exported FEA files

### ISSUE THREAD

**Issue by Another-1** [fontforge/fontforge#4470]
Hello!

Can you please "extend" MergeFeature procedure for it to be able to import FEA files containing just bit of features (for example just a "calt"). It works OK in GUI via "Merge Feature Info". But in a script it fails with an error MergeFeature: "Failed to find kern info in file". I hoped that feature is actually imported even with an error message, but generated font has no features, so it's not true. In case of a lot of fonts to process, this change will save a lot of time.

So:
Expected behaviour: feature is merged (with or without an error message) and present in a generated file. 
Actual behaviour: error message "Failed to find kern info in file", no feature is merged.

Environment: Windows 10, latest FF.

Steps to reproduce:
Prepare the feature file:

```
languagesystem DFLT dflt;

# GSUB 

lookup calt {
  lookupflag 0;
    sub [\zero ] [\colon ]' [\zero ]  by [\semicolon ];
} calt;

feature calt {

 script DFLT;
     language dflt ;
      lookup calt;
} calt;
```
 
Take any font without features and in console mode open it and do a MergeFeature(<feature_file>)

Get an error, generate a font, open it in GUI and check that no features are added.

Still in GUI merge the same file via "Merge feature info" menu item. It merges OK and feature appears in a font info window (names can change though). Open a metrics window, enter "0:0" string to confirm that a colon is replaced with a semicolon.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by Marr11317** [comment]
why not first export the feature info, then append your file to it and import again?

**Comment by Another-1** [comment]
Maybe it's a way (will try). It's confusing that "handmade" file is merged ok via gui but fails when merged from a script. Should there be the same behavior in both ways, it would be more transparent.

**Comment by Another-1** [comment]
Seems like there was some error on my side, probably a typo. Can't reproduce an issue on another system anymore. Thanks for attention and sorry for disturbance!
