### ISSUE TITLE
Failed and error when to installing on Mac Os 

### ISSUE THREAD

**Issue by javapep** [fontforge/fontforge#4475]
Hi, Everyone.

This morning I've got a messange from my client, That my font can't installing on Mac, and they say the issu is " I get a big red "X" (meaning, do not install the font) next to the following item: 'kern' table structure and contents". How to solve it. I use font forge old version not the lastes version. BTW this my font https://creativemarket.com/JavaPep/4847385-Garlic-elegant-font. Thank you in advance.

**Comment by ctrlcctrlv** [comment]
Can I see a screenshot to better understand what you mean?

**Comment by javapep** [comment]
ctrlcctrlv I don't use Mac. This messange from my client. BTW my friend told me the issue maybe about "the kerning lookup table". because the popup warning says '"kern' table structure and contents". I made two kerning classes on looukp 0 and , it this the problem?
![kerning](https://user-images.githubusercontent.com/37425641/97934421-44bed380-1da8-11eb-8182-9d4573baf92e.png)

**Comment by ctrlcctrlv** [comment]
Probably unrelated. Try unchecking "Windows compatible Kern" at the time of generation.

**Comment by javapep** [comment]
Thanks the problem is solved...Its just upgrade to the newest fontforge
