### ISSUE TITLE
FreeType debugger no longer compiles with FreeType 2.10.3

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#4477]
Last working version is 2.10.2, seems like the internal.h header is gone.

**Comment by lemzwerg** [comment]
> Last working version is 2.10.2, seems like the internal.h header is
> gone.

Just replace the header macros with real filenames!


    Werner

**Comment by jtanx** [comment]
In this case it's not FontForge that's using the macros, it's the internal FreeType headers that FontForge pulls in that are. Can probably just add some version guards around the internal.h header, seems to compile fine without it on 2.10.3
