### ISSUE TITLE
Bundled Python 3.7.9 is out of date

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4487]
The AppImage associated with [release 20201107 in GitHub](https://github.com/fontforge/fontforge/releases/tag/20201107) uses Python 3.7.9. It would be convenient if the bundled Python were kept up to date. Compare the macOS disk image, which bundles Python 3.9.0.

**Comment by jtanx** [comment]
I'll look into this when I get around to #4476 but it'll be at the whim of whatever Python distribution is easily provided through CI.

**Comment by dscorbett** [comment]
It’s not a matter of whim. All you probably have to do is change .travis.yml to refer to Python 3.9 instead of Python 3.7. GitHub Actions provides a similar configurability with `actions/setup-python`.
