### ISSUE TITLE
CMake Error at fontforge/cmake_install.cmake:52 (file):file INSTALL cannot copy file

### ISSUE THREAD

**Issue by javapep** [fontforge/fontforge#4500]
Hi want to build fontforge 2020 in deepin os  all prosses is success except last step "ninja install" and the result is

[0/1] Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/lib/libfontforge.so.4
CMake Error at fontforge/cmake_install.cmake:52 (file):
  file INSTALL cannot copy file
  "/home/javapep/Downloads/fontforge-20201107/build/lib/libfontforge.so.4" to
  "/usr/local/lib/libfontforge.so.4".
Call Stack (most recent call first):
  cmake_install.cmake:45 (include)

FAILED: CMakeFiles/install.util 
cd /home/javapep/Downloads/fontforge-20201107/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.

How to fix it? Thanks

**Comment by ctrlcctrlv** [comment]
Are you running as root?

**Comment by javapep** [comment]
No ..muat be root to fix it

**Comment by ctrlcctrlv** [comment]
Yes. Or else choose a different installation prefix.

By the way, Deepin&mdash;never heard of that before. Looks very interesting. Has its own Qt-based DE. Do you think a non-Chinese user could figure it out? I don't speak Mandarin well but have used Arch Linux+KDE on and off (mostly on) for almost ten years at this point.

**Comment by javapep** [comment]
What do you means about a different installation? Via appimage?... IDK coz I can't speak Mandarin to...i just want to update fontforge 2020 deepin 15.11..in this version can use PPA fontforge...coz this version in unstable....

**Comment by ctrlcctrlv** [comment]
Forget about Deepin then.

Installation prefix refers to the path you're attempting to install to.

It would be best to just run the command as root, e.g.:

```
sudo ninja install
```

Otherwise you'd need to add `.desktop` files referring to the new path in the right places to get icons to appear, and I don't have time to walk you through that right now I'm afraid.

**Comment by ctrlcctrlv** [comment]
Also, yes, AppImage is a good choice too for your use case. Just download it, make it executable and click on it.

I'm closing your issue per [#G2](https://github.com/fontforge/fontforge/wiki/Community-guidelines#G2), FYI.

**Comment by javapep** [comment]
Hi thanks for your helping.. it's work ... i just edit to "sudo ninja install"  Thanks you in advance
