### ISSUE TITLE
Feature Request : add support for auto kerning

### ISSUE THREAD

**Issue by alfu145** [fontforge/fontforge#4517]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

For years, auto metrics has been used to fix metrics between two letters automatically; however, you still need to do kerning, which is a long process. I myself have spent many hours/days kerning, and because of this, it makes the process of making a font less productive. We should make an auto kerning option that would find kerning issues in different pairs of letters, and optically kern the pair; This sounds simple and easy; however, this might replace auto kerning all together. This is why we should change the way we do metrics and kerning.

**Comment by ctrlcctrlv** [comment]
FontForge already has an automatic kerner. It works okay in most cases.
