### ISSUE TITLE
MACOS Importing function for glyphs not working. HELP

### ISSUE THREAD

**Issue by endofdase** [fontforge/fontforge#4519]
Hello! I've been using font forge with xquartz successfully for the last year and a half. I sstopped using it a few months back, and not I'm trying to use it again. I usually import my glyphs using the import function like seen below. I usually go to my documents folder (which is where I store my glyph files in SVG individually). I usually import each one at a time. 

For some reason, I am no longer able to uses this function as instead of showing my whats inside my documents folder
it just says "Unauthorized. Operations not permitted" instead. Any help for fixing this?
<img width="533" alt="Screen Shot 2020-12-01 at 1 31 49 PM" src="https://user-images.githubusercontent.com/75338658/100799216-92dfea80-33d9-11eb-9b08-8676c8a7ea2c.png">

**Comment by jtanx** [comment]
See #4082. Try https://github.com/fontforge/fontforge/issues/2474#issuecomment-139686912?
