### ISSUE TITLE
Disk access on macOS Catalina

### ISSUE THREAD

**Issue by kalapi** [fontforge/fontforge#4520]
Getting this when I try to locate a file. 

![Screenshot 2020-12-03 at 7 22 35 PM](https://user-images.githubusercontent.com/15804460/101032380-e1d77c80-359f-11eb-8087-2e7d14527dab.png)

Giving `Full Disk Access` in `System Preferences>Security & Privacy>Privacy` isn't working. Any ideas?

Thanks in advance!

**Comment by jtanx** [comment]
See #4082.

**Comment by kalapi** [comment]
Sorry, should have looked harder to find a similar issue.
