### ISSUE TITLE
measure tool text not visible in popup (in both flatpak and fedora rpm)

### ISSUE THREAD

**Issue by fastrizwaan** [fontforge/fontforge#4523]
Fedora 33 workstation
Fontforge version: 20200314
https://flathub.org/apps/details/org.fontforge.FontForge

Please see this:
![fontforge](https://user-images.githubusercontent.com/1161682/101228135-5d304f80-36c0-11eb-8c1e-8393165f3abe.gif)

**Comment by fastrizwaan** [comment]
Issue caused by FixedMedium.ttf with no glyphs at ~/.local/share/fonts
removing the bad font fixed the issue.

**Comment by ctrlcctrlv** [comment]
Your screenshot also shows something similar to #4507
