### ISSUE TITLE
cannot make ligatures with non-alphabetic characters

### ISSUE THREAD

**Issue by johannes1971** [fontforge/fontforge#4526]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by johannes1971** [comment]
I'm trying to modify an existing TTF font with additional ligatures for programming. Specifically, I want to use ≠ (U+2260) instead of !=, ≤ (U+2264) instead of <=, and ≥ (U+2265) instead of >=. To do this I do the following:

1. Open the font.
2. Scroll to the ≠ character.
3. Select "glyph info"
4. Go to the ligatures tab.
5. Add "Ligature substitution lookup 3 subtable"
6. Type '!' in the source glyph names. It changes to "exclam(!)".
7. Attempt to type '=' in the source glyph names. There are several outcomes, none seem to work properly:
7.1. by immediately typing '=', it replaces most of "exclam(!)", leaving the text "e=". This is not accepted when I click "next".
7.2. by moving the cursor to the end of the existing text. '=' is not replaced by its full name, and again the final text ("exclam(!)=") is not accepted when I click "next".
7.3. by typing an extra space after the existing text. If I type '=' now, the original text is removed.
7.4. by typing "exclam(!)equals(=)". Clicking next seems to reset the dialog.
7.5. by typing "exclam(!) equals(=)". Clicking next seems to reset the dialog.

Am I just completely misunderstanding how this works? Or is it not possible to create a ligature for "!="? 

Windows 10. Version 20201107. Also reproduced on Ubuntu 20.04.

**Comment by skef** [comment]
The "Prev" and "Next" buttons change what glyph the Glyph Info dialog shows information about; they're for convenience in certain data entry circumstances. This should be more evident if you look at the dialog title bar as you press them. 

In general in these dialogs one refers to glyphs by their "glyph name", as in "exclam" and "equals". This one will use parentheses for certain characters as a clarification. So as far as I can tell from limited testing you want to follow your 7.5 instructions but hit "OK" rather than "Next". Then you could (for example) open the Font Info dialog and go to Lookups -> GSUB, find your table and press the plus to get at the subtable, select it and press "Edit Data" on the right to verify the entry.

**Comment by skef** [comment]
Having said all this, programming tools are highly variable in their support for ligatures and OpenType substitutions more generally.

**Comment by johannes1971** [comment]
Ok, I've managed to create the ligatures. But when I export the font (as OTF) and install it, Visual Studio does not display the ligatures. Note that this does work correctly with the Fira Code font, which is also an OTF and displays the ligatures correctly in Visual Studio. I'm not a big fan of Fira Code though and am trying to modify my preferred font to also has the ligature substitution.
Feel free to close this one.

**Comment by skef** [comment]
Try opening both the font you generated (not the SFD) and the one that works in FontForge and looking at the ligature tables to see what might be different. It could be that you're using a different OpenType feature or any number of other things.

**Comment by skef** [comment]
Feel free to ask more questions about your situation in this thread and I'll help if I can, but since the main issue is resolved I'm going to close this as you suggest.
