### ISSUE TITLE
Consider enabling the forum (“GitHub Discussions”)

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4534]
GitHub provides a forum now, “GitHub Discussions”.

https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/

`fonttools` has enabled it: https://github.com/fonttools/fonttools/discussions/2123

**Comment by jtanx** [comment]
I've enabled it, although I don't really know how much more beneficial this will actually be over the mailing list/everything else we already had.

**Comment by ctrlcctrlv** [comment]
Thanks @jtanx , I really did mean “consider”, I wasn't necessarily asking for it, just noting that other projects are rolling it out.

**Comment by skef** [comment]
This happened!
