### ISSUE TITLE
Another UFO glyph can't be roundtripped, this time a quadratic one

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4539]
Arch Linux, fc1970174ba9e965bef9b676ee2afd679079a34e

I haven't yet solved #4327 on my own, and now have an example of a quadratic glyph that FontForge also can't generate a correct UFO of. :frowning: 

Non-FontForge programs also have problems with this UFO. For example `fontmake` can't convert it (crashes).

# SFD

![2020-12-17-210237_1506x1392_scrot](https://user-images.githubusercontent.com/838783/102565346-466bfe80-40ab-11eb-8022-2130cafdb3f8.png)

# Conversion

```python3
import fontforge

f = fontforge.open("Issue4327Part2.sfd")
f.generate("{}.ufo".format(f.fontname))
```

```
$ fontforge Issue4327-Part2.ufo
```

# UFO

![2020-12-17-211231_2560x1392_scrot](https://user-images.githubusercontent.com/838783/102566035-a44d1600-40ac-11eb-9a86-95f7f36b38f2.png)

# Files

[Issue4327Part2.zip](https://github.com/fontforge/fontforge/files/5713253/Issue4327Part2.zip)

**Comment by jenskutilek** [comment]
Is the leftmost oncurve point apparently is the start point, but this point is not exported by FontForge to the UFO (maybe because it can be an implicit oncurve point?). In the UFO, the startpoint is shifted to the next offcurve.

fontmake doesn't seem to have a problem, except it can't run the default remove overlap filter on quadratic curves. If you keep overlaps, a font is exported.

```
$ fontmake --keep-direction --keep-overlaps -u Issue4327-Part2.ufo -o ttf
INFO:fontmake.font_project:Building TTF for Issue4327-Part2
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters:Running DecomposeComponentsFilter on Issue4327-Part2
INFO:ufo2ft.filters:Running CubicToQuadraticFilter on Issue4327-Part2
INFO:ufo2ft.filters.cubicToQuadratic:New spline lengths: 
INFO:ufo2ft:Building OpenType tables
INFO:ufo2ft.postProcessor:Compiling TrueType hinting
INFO:fontmake.font_project:Saving master_ttf/Issue4327-Part2.ttf
```

Though in the resulting font, the start point is shifted again, to the left point of the top line segment. All this shifting around of start points may be really bad if the font is TrueType-hinted. How does FontForge's own hinting handle that it omits points in output?

**Comment by ctrlcctrlv** [comment]
> How does FontForge's own hinting handle that it omits points in output?

Probably badly. Dragons live in our TrueType instructions code. I try to look at it as little as possible for my own sanity.

**Comment by ctrlcctrlv** [comment]
This is the workaround I'm using right now:

I'm outputting to OTF and then using `ufo-extractor` library ([robotools/extractor](https://github.com/robotools/extractor)). It's unfortunate hackery but it works.

```python3
#!/usr/bin/env python3
# This script does the following:
# - from the base SFD, stroke all glyphs
# - output it as an OTF due to #4327, #4539
# - use extractor to turn the OTF into UFO
# - massage the UFO slightly

import fontforge
import shutil
import os, sys
import tempfile

import extractor, defcon

import plistlib

_, namedweight, strokewidth, os2weight = sys.argv
os2weight = int(os2weight)

tempufodir = tempfile.mkdtemp()
ufoname = tempufodir+os.sep+"FRBAmericanCursive.ufo"
otfname = tempufodir+os.sep+"FRBAmericanCursive.otf"
outname = "build/FRBAmericanCursive-{}.ufo".format(namedweight)

try:
    shutil.rmtree(outname)
except OSError: pass

shutil.copytree("FRBAmericanCursive-SOURCE.ufo", outname)

f = fontforge.open("FRBAmericanCursive.sfd")
f.selection.all()
# No magic here in terms of building the list. They looked wrong without it, manual verification.
removeOverlap = lambda gn: "none" if gn not in ["section", "ampersand", "dollar", "t.high", "t.low", "cyr_ER.rlow"] else "layer"
removeInternal = lambda gn: False if gn in ["uni030A"] else True
for g in f.glyphs():
    g.stroke("circular", int(strokewidth), "round", "round", simplify=False, removeoverlap=removeOverlap(g.glyphname), removeinternal=removeInternal(g.glyphname), accuracy=0.10)
f.correctDirection()
f.generate(otfname, flags=("opentype","no-hints","no-flex","omit-instructions"))

ufo = defcon.Font()
extractor.extractUFO(otfname, ufo)
ufo.save(ufoname)

try:
    shutil.rmtree(outname+"/glyphs")
except OSError: pass

shutil.copytree(ufoname+os.sep+"glyphs", outname+"/glyphs")
shutil.rmtree(tempufodir)

plistf = open(outname+"/fontinfo.plist", "rb")
plist = plistlib.load(plistf)
plist["postscriptWeightName"] = namedweight
plist["openTypeOS2WeightClass"] = os2weight
plist["styleName"] = namedweight
plist["styleMapStyleName"] = "bold italic" if os2weight >= 700 else "italic"
plist["postscriptFontName"] = plist["postscriptFontName"].replace("Regular", namedweight)
plistf.close()
plistf = open(outname+"/fontinfo.plist", "wb")
plistlib.dump(plist, plistf)
```
