### ISSUE TITLE
How do I resize the exported SVG？

### ISSUE THREAD

**Issue by adorablely** [fontforge/fontforge#4540]
'`Export ('./ SVG /'+count+'. SVG ',pixelsize=256)'` does not work, the exported SCV is `viewBox="0 0 1000 1000"` size. How to change the size?

**Comment by ctrlcctrlv** [comment]
The legacy scripting language seems to use `pixelsize` with the same meaning as the Python API. Meaning, it only works for raster formats. There is no way to do what you want from within FontForge currently.

**Comment by skef** [comment]
I don't believe the program does any scaling on export. Therefore if you want a given glyph to be a given size on export you can copy the font, scale the glyphs as desired, and export them the normal way. 

For bitmaps I believe `pixelsize` will "scale" the whole font a uniform amount. So the equivalent (I think) will be to just set the "em size" to 256 before exporting:

```
#!/usr/bin/env python

import fontforge
import psMat

targetEm = 256

f = fontforge.open('LibertinusSerif-Regular.sfd')
f.em = targetEm

g = f['a']
g.export('a.svg')
```
The viewbox on the test glyph I generated this way is -10 0 136 256, which sounds more or less like what you want.

**Comment by adorablely** [comment]
Thank you very much for your help. Now there is another question, how to turn SVG relative path to absolute path, does the Python script provide relevant Settings?

发自我的iPhone


------------------ Original ------------------

**Comment by skef** [comment]
@adorablely I'm not sure exactly what you're asking. If you want to know how to store the files in a particular directory, I think you can just add the initial path to the export, as in

```
Export ('/home/you/svg/'+count+'.SVG')
```
or better:
```
Export('/home/you/svg/%n.svg')
```
to save them by name (in the native scripting language)

If you're asking in what directory the files will wind up if you use a relative path, that depends on which operating system FontForge is compiled for and how it was run. If you run it as a script directly it will most often be the current directory. Still, it may just be easier to specify where you want them as described above. 
```

**Comment by adorablely** [comment]
In the SVG path, "m q l" is the relative path for the control command and "m Q L" is the absolute path for the control command. The SVG exported using G.xport ('a.svg') is relative path, which makes my next step difficult. I haven't found out how to solve this problem.

发自我的iPhone


------------------ Original ------------------

**Comment by skef** [comment]
Oh, I think I understand now.

I don't believe FontForge provides an option to force absolute SVG paths. It's not supposed to matter much. If you gave more information about what the "next step" is I might be able to give some advice. The conversion itself is quite easy if you're already parsing the path; if you aren't then the difficulty is in finding the path strings.
