### ISSUE TITLE
No module named fontforge on MacOS Catalina

### ISSUE THREAD

**Issue by SunHaozhe** [fontforge/fontforge#4542]
I noticed that this issue has been raised before #2597 . However, it seems to me that this issue is still not fixed, so I open a new issue. 

I am on MacOS Catalina version 10.15.7

I first installed FontForge via [https://fontforge.org/en-US/downloads/mac-dl/](https://fontforge.org/en-US/downloads/mac-dl/), but it seems to me that it is only a Desktop application without python binding. Then I installed `fontforge` via `brew` using the command `brew install fontforge`, the `brew` command succeeded in installing `fontforge` but it still gives the same error `No module named fontforge`

I would like to use fontforge like a normal Python module

```python
import fontforge
```

Then execute the python script using the standard python interpreter

```zsh
python main.py
```

instead of doing `fontforge main.py`

Is this possible? 

The [official documentation](https://fontforge.org/docs/scripting/python.html#python-extension) states that in addition to embedding Python, FontForge typically installs a Python module accessible to the system’s python executable.

**Comment by jtanx** [comment]
It is possible but I don't know why it doesn't work with the hombrew package - that is not supported by us. My guess is that you're executing the wrong python and/or the extension has not been installed properly by homebrew - in any case ask in https://github.com/Homebrew/homebrew-core.

**Comment by SunHaozhe** [comment]
If the homebrew package is not supported by you, what is the recommended way to install `fontforge` on MacOS in order to be able to use it like a normal Python module?

**Comment by jtanx** [comment]
mac support is limited because none of the active developers also actively use macos. Therefore support is limited to whatever the bundle supports. 

The bundle includes the version of Python it was built with, so you can execute that directly if you really want -  FontForge.app/Contents/MacOS/FFPython which calls FontForge.app/Contents/Frameworks/Python.framework/Versions/3.9/bin/python3.

**Comment by kingwoshi** [comment]
@SunHaozhe You need use Python3.9, and try again!
