### ISSUE TITLE
Cant export font after adding 600 calt substitutions

### ISSUE THREAD

**Issue by ekaunt** [fontforge/fontforge#4543]
I have already looked through the internet and I asked the mailing list, but no one was able to answer me.

My Issue is that when I export a font after applying a large amount of substitutions (in my case 655 substitutions), the export fails. The message I get for why it failed is:

```
Internal Error:
Attempt to output 65562 into a 16-bit field. It will be truncated and the file may not be useful.
```

It should export just fine because I only have 655 substitutions, not 65k substitutions, so idk whats causing the problem.

Maybe my features file wasn't written properly. But if that's the case, then how come FontForge doesn't give any errors when importing it?

How can I go about troubleshooting this issue? I opened up the sfd in a text editor and I can't find `65562` or `1001A` (hex) anywhere in the file. I'm probably going about this the wrong way, but I don't know what else to do. I can't think of a reason why there's a value larger than 16 bits in the 655 calt substitutions.

Here are the files I'm working with:
- The sfd without any substitutions added:
  - https://mega.nz/file/q5AWCbYT#PnvNnZWhXb7lAKJyjOJvtRH_ergV2su43c4uNMR5Gng
- The sfd with all the substitutions:
  - https://mega.nz/file/i5RknLiT#Ymb1BYz5VPCW8rwdvsmYZIMFQEfkjBwNl0OZkU-xX0s
- The substitutions.fea file:
  - https://mega.nz/file/z0ZWATgZ#ZYwCZBNJlXyR16uQaFlpGLJzS8IBfJH729kV7XCipRM
- The script I made to generate the features file:
  - https://mega.nz/file/f1R2SL5R#DCfQCNmVFOxCZK3vVinipq5ADlAODZ-J1QK_QIl2C8Q

### When reporting a bug/issue:
- [X] Screenshot
![image](https://user-images.githubusercontent.com/62402760/102719111-09c22200-42ba-11eb-8a2f-7e6e5dd39385.png)
![image](https://user-images.githubusercontent.com/62402760/102719115-0b8be580-42ba-11eb-970f-973eb7ba31e2.png)

- [X] The FontForge version and the operating system you're using
```
Version: 20200314
 Based on sources from 2020-08-30 10:04 UTC-ML-D-GDK3.
fontforge 20200314
build date: 2020-08-30 10:04 UTC
```
```
OS: Manjaro Linux x86_64
Kernel: 5.9.11-3-MANJARO
WM: bspwm
```
- [X] Steps to reproduce the behavior 
- [x] The behavior you expect to see, and the actual behavior
- I expect to be able to export the font, and then use it with all of my `calt` substitutions.
- But, I get the error in the pic above
- Open up hana-with-fea.sfd
- export the font
- see the error

**Comment by skef** [comment]
65562 is the maximum size of the table in bytes. If each of your table entries is large even 600 substitutions could exceed that size.

Could you split the substitutions up into multiple subtables without losing functionality? That's usually the first step in these cases.

**Comment by ekaunt** [comment]
![image](https://user-images.githubusercontent.com/62402760/102721035-164c7780-42c6-11eb-8fd4-1dcef6d0c5db.png)

This is what my substitutions look like. I have the tables split at every single substitution

**Comment by KamilLanda** [comment]
Sometimes I have the same problem but for many GPOS definitions. It is really vexatious problem, also unsolved in https://github.com/fontforge/fontforge/issues/3009. 

So after the message "Internal error: Attemt to output ..." I open the generated TTF file and FontForge show the warning in which subtable is some problem - like this:
[
![bad-subtable](https://user-images.githubusercontent.com/61148366/102773680-f1213d00-4389-11eb-8ce5-fbcd1929f29b.png)
](url)

Then I move the "sick subtable" up or down, for example from position 68 to the position 55 or to the position 75 - but sometimes it is not so easy to find new "correct" position, so I try positions gradually -> from 68 for example to the 55, 54, 53 etc or to the 72, 73, 74 etc. But my experience is: the quickest with the "biggest certainty" is to move the sick subtable to the bottom. 

And the curiosity: after adding some next definitions to the subtables, it is possible to return the sick subtable to the primal position and error will not show. So after some next work I try to move the sick subtable to the primal position and mostly it is ok.

**Comment by ekaunt** [comment]
@KamilLanda fontforge crashes when i try to open the exported ttf…

**Comment by KamilLanda** [comment]
Unluckily I don't know what to do with crash :-(
