### ISSUE TITLE
My curser does not align with where I click [update]

### ISSUE THREAD

**Issue by bzkton** [fontforge/fontforge#4544]
First time encountring this problem, whatever window I am on in fontforge wherever I click to select something some other place gets highlighted instead. Unable to click menu bar above unless I navigate with keyboard. Please help, thank you!

Edit: I have found that this issue is only caused when I use my wacom tablet (bamboo cte-450)while using fontforge. When I use another mouse or touchpad this problem does not occur. Do you guys know what might cause this?

**Comment by jtanx** [comment]
Is this on Windows? If so, can you try https://github.com/fontforge/fontforge/issues/4659#issuecomment-793600453

**Comment by jtanx** [comment]
Assuming the same as in that comment
