### ISSUE TITLE
Viewbox of glyphs exported as SVG are offset by -10 on the x axis

### ISSUE THREAD

**Issue by sunknudsen** [fontforge/fontforge#4546]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior

#### Screenshot

![Screen Shot 2020-12-26 at 6 34 12 AM](https://user-images.githubusercontent.com/2117655/103150721-821f5c00-476e-11eb-8df3-4da605c2eb40.png)

![Screen Shot 2020-12-26 at 6 34 35 AM](https://user-images.githubusercontent.com/2117655/103150724-851a4c80-476e-11eb-800f-03e6393dafa0.png)

#### The FontForge version and the operating system you're using

20th Anniversary Edition (thanks so much for FontForge 🎉)

macOS Catalina 10.15.7

#### The behavior you expect to see, and the actual behavior

See screenshots... and here is the exported SVG. I expect `viewBox="-10 0 490 1000"` to be `viewBox="0 0 480 1000"`.

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-10 0 490 1000">
   <path fill="currentColor"
d="M410 350h-120l-30 -290h180zM190 350h-120l-30 -290h180z" />
</svg>
```

**Comment by skef** [comment]
1. We don't move the glyphs on the em-unit grid
2. If we didn't add margin in at least some cases, glyphs that extend into negative-x space (which are not uncommon) would be cropped by the viewbox.
3.This change, which is now several years old, was previewed on the fontforge-users mailing list and there were no objections. 
4. Given point 1 if you don't like the new behavior you can use a tool to adjust the left viewbox point back to zero. 

Closing.

**Comment by ctrlcctrlv** [comment]
Agreed with @skef
