### ISSUE TITLE
Why Ext-B fonts spacing are different

### ISSUE THREAD

**Issue by semizemi** [fontforge/fontforge#4547]
Whenever to use Simsun-Ext-B, instead of Simsun, after inputting an Ext-B Glyph the spacing will be different.
I see nothing difference other than contained glyphs in FontForge.

- [x] ScreenShot:
![Fontest](https://user-images.githubusercontent.com/75206763/103162870-384b7a00-4831-11eb-8a4a-c8ad48494868.jpg)

And have tested in Hanamin, found that Fontlink didn't work for HanaminA, but the result is same.

- [ ] HanaminA FontLink Registry:
```
HanaMinA Regular
REG_MULTI_SZ
HANAMINB.TTF,HanaMinB Regular
```

- [x] HanaminB FontLink Registry:

```
HanaMinB Regular
REG_MULTI_SZ
HANAMINA.TTF,HanaMinA Regular
```

FontForge Version: 20201107
OS Version: Windows 10 20H2
Editor: NotePad

- [x] Question:
1.Why is registry of HanaminA not working as same as HanaminB.
2.How to make Simsun and Simsun-ExtB or HanaminA and HanaminB spacing the same.

**Comment by ctrlcctrlv** [comment]
I am sorry to say that I am really not understanding this question at all and unless you have a license from Microsoft you're not even supposed to be modifying the SimSun font. 

Be that as it may, I suppose you are trying to merge two fonts to get the benefit of the different characters each supports. 

If the two fonts have different metrics, well then the spacing will change. How are you doing this merger? Are you using the Merge Fonts command or are you just copying and pasting?

**Comment by semizemi** [comment]
> 
> 
> I am sorry to say that I am really not understanding this question at all and unless you have a license from Microsoft you're not even supposed to be modifying the SimSun font.
> 
> Be that as it may, I suppose you are trying to merge two fonts to get the benefit of the different characters each supports.
> 
> If the two fonts have different metrics, well then the spacing will change. How are you doing this merger? Are you using the Merge Fonts command or are you just copying and pasting?

It seems like you misunderstood my question. Said to make Simsun or Hanamin to spacing the same, is not equal to make Simsun and Simsun-ExtB spacing the same. That's why to use Hanamin as example.

Sure HanaminA and HanaminB has same metrics, download and check from official site:
https://fonts.jp/hanazono/

As said is not merge, is Fontlink, an old functionality from Windows.
The question is TTF only supports 65535 glyphs, so CJK was separated into parts.
PartA is HanaminA, PartB is HanaminB.

Under the Fontlink of B to A, in Notepad wrote 2 CJK glyphs if 1 or 2 from B, comparing wrote 2 CJK glyphs from A, their spacing will be different.

As you can see on the Screenshot, no matter of width of space glyph, with or without space, the spacing is just different.
Yet can also see the default Fontlink from Simsun to Simsun-ExtB is spacing properly, instead of Simsun-ExtB to Simsun.
So i've no reason to modify Simsun or Simsun-ExtB, it's a question or discussion to solve the problem of CJK-B to CJK-A.
And better if can also solve why Fontlink of 3rd party can not link from A to B.

Thus i found there are other factors has impact to spacing, other than metrics, this is really strange:
Basic Latin U+0020-U+007E
Cyrilic Extended-C U+1C80-U+1C8F

**Comment by ctrlcctrlv** [comment]
…FontLink? Never heard of it. What does it have to do with FontForge? Are you using FontForge?

**Comment by semizemi** [comment]
> 
> 
> …FontLink? Never heard of it. What does it have to do with FontForge? Are you using FontForge?

Yes, and Hanamin is also generated from Fontforge. what FontLink is font fallback, never heard is normal as along as you don't have great needes in CJK fonts.
What i am going to do is to use whatever the method to solve this problem.

**Comment by ctrlcctrlv** [comment]
So you're saying you're having an issue, fundamentally, with Windows, and FontForge isn't helping you debug the problem with Windows. 

It's not showing you whatever difference you think it should to explain the different spacing. 

I don't think that's really a FontForge problem unless you know what's different about the fonts and why (or if) FontForge isn't displaying that information.

**Comment by semizemi** [comment]
> 
> 
> So you're saying you're having an issue, fundamentally, with Windows, and FontForge isn't helping you debug the problem with Windows.
> 
> It's not showing you whatever difference you think it should to explain the different spacing.
> 
> I don't think that's really a FontForge problem unless you know what's different about the fonts and why (or if) FontForge isn't displaying that information.

As said it's not a fontforge problem, but a problem while using fontforge. 
This is solved now. i've confirmed as not a generation bug.

**Comment by ctrlcctrlv** [comment]
In future, the bug tracker is only for FontForge bugs. Thanks.
