### ISSUE TITLE
feature request: Apply "Change Weight" function to the selected contour

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4554]

**Comment by skef** [comment]
There are some cases where you can imagine this being useful, such as adjusting the weight of the base of an "i" but not the dot. In most cases, however, the result wouldn't be what the user expected. Change weight attends to the glyph layout and baseline and such. Attempting to adjust contours at varying positions relative to those will just screw up those heuristics. 

We already have "Internal Only" and "External Only" in the Expand Stroke dialog for roughly this kind of purpose (which is what sits underneath Change Weight anyway).

If you really need this for yourself just write a script to copy the contours to a temporary glyph, run Change Weight, and copy them back.
