### ISSUE TITLE
Crash in `SSBoundsWithin`

### ISSUE THREAD

**Issue by dscorbett** [fontforge/fontforge#4560]
In FontForge 20201107 on macOS 10.14.6, the following script crashes in `SSBoundsWithin`.
```python3
import fontforge


c = fontforge.contour()
c += fontforge.point(0, 1)
c += fontforge.point(0, 1)
c.xBoundsAtY(0, 2)
```
Though the contour `c` may seem contrived, this is based on a real example where stroking two contours then removing their overlap ended up generating such a contour.

[Here is a crash report.](https://github.com/fontforge/fontforge/files/5767940/Python_2021-01-04-222641.txt)

**Comment by yg8ijvjvjv** [comment]
Does fontforge.point generate an off curve or an on curve point?
