### ISSUE TITLE
Can all the features of the font work in Android/Iphone phones?

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4563]
Hello,

I wanted to know which of the font's features below can work in Android/Iphone phones:
1. Ligature
2. Alternative Substitution
3. Kernings ( both single or classes )
4. Marks
5. Aalt

If not, is there special installation program or keyboard program needed for in Andriod and IOS?
If there, please point to those programs.
Thanks

**Comment by yg8ijvjvjv** [comment]
The OpenType features in the renderer are a part of the renderer. FontForge does not develop the renderers used in phones.

**Comment by frank-trampe** [comment]
@waykyi, as @yg8ijvjvjv points out, FontForge does not provide the functionality in question. But I think that Android does support most of those and has for some time. You can test some of them in the browser [here](https://charakterziffer.github.io/extra/otfeat.html).

**Comment by waykyi** [comment]
ok, thanks
