### ISSUE TITLE
Update app icon for macOS Big Sur 

### ISSUE THREAD

**Issue by JaydenIrwin** [fontforge/fontforge#4574]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

![image](https://user-images.githubusercontent.com/13500479/104148283-a8b0da00-539f-11eb-80ba-af3091550c4e.png)

I would love for the Mac app to fit in Better with macOS big sur icons by switching the app icon from a circle to the macOS app shape (rounded rect).

**Comment by skef** [comment]
We'll consider PRs for this sort of thing; the value of keeping an issue open is low. Closing.

**Comment by JaydenIrwin** [comment]
> We'll consider PRs for this sort of thing; the value of keeping an issue open is low. Closing.

Could you give me some guidance to where I can change the icon?

**Comment by skef** [comment]
In our source or in the packaged app?

**Comment by JaydenIrwin** [comment]
In the source.

**Comment by skef** [comment]
I believe it's `osx/FontForge.app/Contents/Resources/FontForge.icns`.

**Comment by JaydenIrwin** [comment]
Created [PR](https://github.com/fontforge/fontforge/pull/4690)
