### ISSUE TITLE
The memory could not be written (La memoria no se pudo written)

### ISSUE THREAD

**Issue by bedriczwaleta** [fontforge/fontforge#4576]
this happened when I wanted to bitmap strikes available in 2048 (BSA) for Autotrace

why

**Comment by yg8ijvjvjv** [comment]
Because when the hinting is outdated then the renderer writes to the null pointer (0x0000000000000000). A possible cause of this is when going out of bounds of an array of pointers one of the values is zero. Because nothing owns the null pointer, any program attempting to write it crashes.

**Comment by yg8ijvjvjv** [comment]
bedriczwaleta decides to give up on Bitmap Strikes Available and make the font with CI.

https://ufile.io/34x8tur1 the font crashes when doing 2048ppem in BSA with FreeType rasterization.

**Comment by yg8ijvjvjv** [comment]
https://ufile.io/f6jqwu19

**Comment by skef** [comment]
If the problem happens consistently please update the issue with more specific information (that error could mean several things).

One possibility is that FontForge simply ran out of available memory making such large strikes.

**Comment by yg8ijvjvjv** [comment]
Usually, when there is a memory access violation the program crashes and does not display an error message. So this must be something different.

**Comment by skef** [comment]
We do check a few places more prone to large allocations (which often call `NoMoreMemMessage()`) but not often.

**Comment by yg8ijvjvjv** [comment]
How much per square pixel is the memory allocation for the embed bitmaps?
