### ISSUE TITLE
How to "Set" the regular font in a family

### ISSUE THREAD

**Issue by faranciscus** [fontforge/fontforge#4580]
Hi, i made a font with four different styles, regular, italic, outlined and with contour, everything is ok except then when using this font in any program, the problem is when I select the font as default it opens the outlined font instead the regular one, how can I change this? this is, how doyou set the "regular" font in the family?

Thanks

**Comment by skef** [comment]
This is more of a font design question than a FontForge question. You might try the fontforge-users mailing list: https://sourceforge.net/projects/fontforge/lists/fontforge-users
