### ISSUE TITLE
How to find a Glyphs from its Unicode Char or Value?

### ISSUE THREAD

**Issue by jamesta696** [fontforge/fontforge#4582]
Hi,
Just trying to clean up my WOFF2 files and delete unnecessary junk.
I'm trying to find out how to find all Unicode Char's or Values and select them,
once selected I can invert selection and delete all other glyphs I don't need.

**Is there an FF function I can use to find and select specific unicode chars?**

Your help is appreciated. 
Thanks

**Comment by HinTak** [comment]
You can probably build something yourself around `glyph.unicode` ( see https://fontforge.org/docs/scripting/python/fontforge.html#glyph ). Mostly you want to delete every glyph for which that returns -1, except `.notdef` and a few special ones?

I think you just want a cmap function (that's character to glyph mapping), but you can just as well build you own lookup with something like (pseudo python code):

char2glyph = {}
foreach glyph in glyphs:
     char2glyph[glyph.unicode] = glyph

# now char2glyph[] maps chars to glyph... You need to catch KeyErrors for non-mapped code

But really, mostly you just want to do `select([glyph.unicode != -1 in glyph])` then select the exceptions?

**Comment by skef** [comment]
There's probably a cleaner way to do this, but this is simple. Suppose "f" is a python reference to your font. Then you can select all the glyphs in the encoding with:

```
for g in f.glyphs('encoding'):
    f.selection.select(("more",), g.glyphname)
```
You can also build a hash of encoding values to glyphs with:
```
enc = { g.encoding: g for g in f.glyphs('encoding') }
```
