### ISSUE TITLE
Extrapolate with Fontforge

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4584]
hi
if you have some full compatible masters (I take 0 and 1 in normalized values scale for all coordinates, just for simplify things), depends on the axes, master numbers and their situation you can do Extrapolate to get the other masters automatically using FontForge's "Interpolate Fonts" function.
here is an example with 3 masters across 2 axes (Contrast, Weight):

![g1533](https://user-images.githubusercontent.com/25493297/105012998-0904e300-5a54-11eb-882c-cfa0fdcd83e6.png)

in the case above you see a font with 3 masters in (normalized) points: (0,0) , (1,0) and (0,1). there is no way to create master (1,1) by regular interpolation. but FontForge's "Interpolate Fonts" function could work out of its defined ranges (I mean above 100% and less than 0), so you can get the fourth master with 2 easy steps:
1. first you need to do an interpolate between (0,1) and (1,0) by 50%:

![g1516](https://user-images.githubusercontent.com/25493297/105013558-a06a3600-5a54-11eb-936a-69a840d47cde.png)

2. then you need to do it again with the result font (which is (0.5,0.5)) and (0,0) by -50%. (you should do that via the result font in GUI):

![g1517](https://user-images.githubusercontent.com/25493297/105013739-d0b1d480-5a54-11eb-9295-04c6ca82754a.png)

the result is a bit different with the expected one(witch is designed already):

![g1518](https://user-images.githubusercontent.com/25493297/105014146-4f0e7680-5a55-11eb-9401-bf8f06db4df5.png)

i don't know what is wrong but i guess there is a nonlinear parameter i forgot or maybe i made a mistake, so please take a look at this:
[Extrapolate with fontforge.zip](https://github.com/fontforge/fontforge/files/5834909/Extrapolate.with.fontforge.zip)

CC: @ctrlcctrlv @skef @khaledhosny @frank-trampe and everyone who are interested.

thank you.

**Comment by aminabedi68** [comment]
ok :|
there is no idea apparently, going to close the issue.
I think it was clear enough but if you have any questions, please let me know.

**Comment by skef** [comment]
It's difficult to know what to say about this without knowing more about `1,1(expected).sfd`. How was it produced such that you believe it should be identical to that specific upper right point?

**Comment by aminabedi68** [comment]
hi @skef
you can design the expected "A" from the other masters (consider the serif heights, thickness of crossbar, stems...):

![1](https://user-images.githubusercontent.com/25493297/105756728-3ecd2e80-5f62-11eb-8353-cdabc8b99295.png)

I was hoping somebody told me about the math behind the function. and one other reason I open the issue, to aware people about the possibility (for those who don't know obviously)

**Comment by skef** [comment]
I'm definitely not an expert in this stuff but I think I can offer a basic explanation.

The masters in a variable font, together with the axes dimensions that are assigned to them, define an interpolation space. The version of the font at a given intermediate point in that space will be calculated from the others.

At first glance it may seem that the dimensions you assign to a given master imply some sort of consistency, as with the sort of vector algebra you're doing to calculate a "missing" master. There's no such implication. You could put a thinner or thicker glyph or even a slanted glyph at (1,1).

You can get an idea of how this works in [this section](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#interpolation-example) of the MS OpenType documentation. Note how they point out that the R3 variation offsets are all zero (OpenType masters are encoded as difference vectors). I believe this would correspond to your FontForge-calculated case, where the 1,1 value would be calculated based on (0,0) (the default/"true" master) and the variation masters at (0,1) and (1,0).

Putting a "designed' master at (1,1) will result in non-zero difference vectors at that point, which will affect fonts calculated at other points in the space. 

Therefore (again, I'm making inferences based on a limited undestanding here) if you wanted the space in your variable font to be equivalent to using the FontForge-calculated (1,1) you would just assign the (0,0), (0,1) and (1,0) masters and leave the (1,1) point unassigned.

**Comment by aminabedi68** [comment]
> At first glance it may seem that the dimensions you assign to a given master imply some sort of consistency, as with the sort of vector algebra you're doing to calculate a "missing" master. There's no such implication. You could put a thinner or thicker glyph or even a slanted glyph at (1,1).

yes, i can put everything in (1,1) and it works, just need to be compatible with the other masters, but then i can't say this is (1,1).
remember that how can i predict (1,1) should be and it's very close to the result, and yes as far as i know this is all about vector algebra.

> You can get an idea of how this works in [this section](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#interpolation-example) of the MS OpenType documentation. Note how they point out that the R3 variation offsets are all zero (OpenType masters are encoded as difference vectors). I believe this would correspond to your FontForge-calculated case, where the 1,1 value would be calculated based on (0,0) (the default/"true" master) and the variation masters at (0,1) and (1,0).

please take a look at this:
https://youtu.be/l9xTa-qfR6o?t=36m52s from @twardoch

maybe I'm wrong but i think all these are working very nice except one(?) thing, maybe interpolate with -50% isn't the right input here(?)

**Comment by ctrlcctrlv** [comment]
I really don't understand what you mean. It's a simple linear interpolation, that's it. If the master doesn't exist, both masters are combined. A human designer might draw it differently…there's no way to get the computer to match what a human would do if it's not equal to two linear interpolations.

**Comment by skef** [comment]
After staring at this some more I think I've picked out an aspect of your question I can make sense of. The serifs in both (0,0) and (0,1) extend from y=0 to y=51. The serifs in (1,0) extend from y=0 to y=16. The serifs in (1,1) *expected* also extend from y=0 to y=16.

So analytically one can ask "If the serif height doesn't change on the (0,0) -> (0,1) axis, and is brought down to 16 on the (0,0) -> (1,0) axis, wouldn't one expect the glyph at point (1,1) to have 16 height serifs? And if so, shouldn't the calculation procedure in terms of cross-interpolation with the two fonts yield a result with 16 height serifs? So what am I wrong about, the procedure or the resulting height?"

This is something I can look at, if not necessarily soon. My guess is that it's the procedure.

**Comment by aminabedi68** [comment]
hi @ctrlcctrlv :)
thank you to join us.

respectfully let's clear what is the issue about,

the issue is about:
* you can do Extrapolate with Fontforge! it's tricky but the result may not accurate enough due to settings or method.
* i design some predictable example, it's like you draw 3 angle of a square and you know where the fourth angle should be.

the issue is not about:
* Fontforge has some problems in its interpolate fonts function.
* Fontforge should follow my design process because i know what is correct :)

**Comment by aminabedi68** [comment]
yes @skef 
this is exactly what i say, and i think it's a part of procedure as you say, please take a look. it would be nice if we have a live preview.

**Comment by skef** [comment]
If (0,0) is the "master master" we can think of the transformation from it to (0,1) in terms of one vector per point p<sub>i</sub> calculated as p<sub>i</sub>(0,1)-p<sub>i</sub>(0,0). Same with (1,0) and p<sub>i</sub>(1,0)-p<sub>i</sub>(0,0). p<sub>i</sub>(1,1) should then be p<sub>i</sub>(0,0) + p<sub>i</sub>(0,1)-p<sub>i</sub>(0,0) + p<sub>i</sub>(1,0)-p<sub>i</sub>(0,0), which (mathematically) simplifies to p<sub>i</sub>(0,1) + p<sub>i</sub>(1,0) - p<sub>i</sub>(0,0). Let's simplify the notation to 

> p<sub>0,1</sub> + p<sub>1,0</sub> - p<sub>0,0</sub>. 

Now

> p<sub>.5,.5</sub> = .5\*p<sub>0,1</sub> + .5\*p<sub>1,0</sub>

What we want to know is *x* for

> *x*\*p<sub>.5,.5</sub> + (1-*x*)\*p<sub>0,0</sub> = p<sub>0,1</sub> + p<sub>1,0</sub> - p<sub>0,0</sub>

So

> .5*x*\*p<sub>0,1</sub> + .5*x*\*p<sub>1,0</sub> + p<sub>0,0</sub> - *x*\*p<sub>0,0</sub> = p<sub>0,1</sub> + p<sub>1,0</sub> - p<sub>0,0</sub>

> .5*x*\*p<sub>0,1</sub> + .5*x*\*p<sub>1,0</sub> - *x*\*p<sub>0,0</sub> = p<sub>0,1</sub> + p<sub>1,0</sub> - 2\*p<sub>0,0</sub>

> .5*x*\*(p<sub>0,1</sub> + p<sub>1,0</sub> - 2\*p<sub>0,0</sub>) = p<sub>0,1</sub> + p<sub>1,0</sub> - 2\*p<sub>0,0</sub>

Leaving x=2 and 1-x=-1. 

Which means the extrapolation should be by  -100% instead of -50%, as in:

```
#!/usr/bin/env python

import fontforge

f = fontforge.open('0,1.sfd')
g = f.interpolateFonts(.5, '1,0.sfd')
h = g.interpolateFonts(-1, '0,0.sfd')
h.save('output.sfd')
```

Now, `output.sfd` calculated this way still doesn't match `1\,1\(expected\).sfd` but it's closer; the main difference is that it's bolder. The serifs in `output.sfd` all go from y=0 to y=16. Since I don't know how you produced the boldness aspect of `1\,1\(expected\).sfd` I can't comment. So, take a look and see what you think.

**Comment by aminabedi68** [comment]
thank you @skef . you solve the problem 👌
bolder part is my fault i guess, serif height completely match with (1,0).
