### ISSUE TITLE
Exporting Glyph with Preserved Coordinates

### ISSUE THREAD

**Issue by ertpoi** [fontforge/fontforge#4587]
I have a SVG-font, from which I need `path d` data from each single glyph to be used in an application. 
I need to have all important data of each glyph (like their vertically-flipped paths, their correct central points as defined in the glyph) to be applied and contained in the `path d` of the exported glyph. So in the following script I use `VFlip` command, which seems to flip all selected glyphs vertically in write the effect in the resulting `path d` of output glyph.svg. However the central point is saved in the glyph.svg file in an `viewBox()` attribute and a `<g transform="matrix(1 0 0 -1 tx ty)"` which contains the `<path>` element. I was wondering whether there is a command to apply the viewBox information to the resulting path `d` string, so that I could use this string as a stand-alone string in another application?  

I am using this script to `Export` glyphs (the important part is actually `VFlip();` and `Export("....svg");`). 

```
/*This Fontforge script converts glyphs from some source and flips them
about their vertical axis. It also retrieves the bounding
box array [minx,miny,maxx,maxy] of each glyph.*/

Open($1);
exportpath=$2;
bboxpath=$3
SelectWorthOutputting();
VFlip();

foreach

name=GlyphInfo("Name");

#shitty names
if (Strsub(name,0,5) != "pedal")
bb=GlyphInfo("BBox");
minx=ToString(bb[0]);
miny=ToString(bb[1]);
maxx=ToString(bb[2]);
maxy=ToString(bb[3]);
/*Invert top/y and bottom:*/
WriteStringToFile(StrJoin([name,minx,miny,maxx,maxy,ToString(GlyphInfo("Width")),ToString(GlyphInfo("VWidth")),"\\n"]," "), bboxpath, 1);
Export(exportpath+name+".svg");
#Print(name+" > "+GlyphInfo());

endif;

endloop;
```

PS. sorry for asking this here, but I found no other places to ask a question like this: the mailing list seems to be accessible for certain users, I already requested access but there is no feedback as of to now, and StackOverflow seems to be not the right place for asking advanced FF questions.

**Comment by skef** [comment]
Can you be a bit more explicit about your question or issue?

**Comment by skef** [comment]
A couple releases ago we changed the default glyph-to-svg export behavior to rewrite the values in the path and added a flag in case people wanted the old behavior. The flag is described [here](https://fontforge.org/docs/scripting/scripting-alpha.html#Export). What version of FontForge are you using?

**Comment by skef** [comment]
Because this is likely already addressed in a newer release I'll close this in a couple days unless the filer updates.
