### ISSUE TITLE
Really use Typo Metrics in native scripting

### ISSUE THREAD

**Issue by NuttShell** [fontforge/fontforge#4588]
Hi!
How to change (or set) "Use TypoMetrics" bit in native script?
Thank in advice.

**Comment by skef** [comment]
I'm afraid it doesn't look like there's currently a native scripting interface for that. There is one in python, though.

**Comment by NuttShell** [comment]
Ok, thank you @skef 
And how do this in python?

**Comment by skef** [comment]
A `fontforge.font` object has a number of OS/2 related properties including [os2_use_typo_metrics](https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.os2_use_typo_metrics) . So although I've never done it I believe you can change the bit like this:

```
import fontforge

f = fontforge.open('fontfilename.sfd')
f.os2_use_typo_metrics = True
f.save('fontfilename_out.sfd')

**Comment by NuttShell** [comment]
Thank you @skef !!!
