### ISSUE TITLE
Importing PFA file results in segfault

### ISSUE THREAD

**Issue by sigalor** [fontforge/fontforge#4592]
I am currently dealing with parsing PDF files that use fonts that have no `ToUnicode` map associated with them, so in a first step, I wanted to extract the respective font and analyze it using FontForge. For that, I first executed `pdftops input.pdf` and from the resulting PostScript file, I extracted the part between the lines `%%BeginResource` and `%%EndResource` into a new file.

With that process, I created [this](https://gist.github.com/sigalor/125d60346977def3f17a90a87204f275) PostScript font (PFA) file. Unfortunately, when trying to import it into FontForge, the application segfaults.

- FontForge version: 20201107
- operating system: Ubuntu 20.04

**Comment by skef** [comment]
I have a fix for the crash but I'm afraid the result is an "I don't understand this file" message and a bunch of empty glyph slots.

**Comment by skef** [comment]
This is the ttf encoded in the hexidecimal, though, which together with the readable part of the PFA should give a good idea what's going on. (See "The sfnts Array" [here](https://www-cdf.fnal.gov/offline/PostScript/5012.pdf). 

[blah.zip](https://github.com/fontforge/fontforge/files/5873231/blah.zip)
