### ISSUE TITLE
No False Positive

### ISSUE THREAD

**Issue by Pugfeidbrull** [fontforge/fontforge#4593]
January 27, 2021

There is no false positive. There are people / companies, who do not check their programs with VirusTotal before sharing / selling it.

Yet everyone should do it with all the malware that abounds on the Internet. It doesn't 100% guarantee that there is no malware, but it is the basics.

https://i.postimg.cc/MGz62kfQ/Font-Forge-2020-11-07-Windows-exe-VT-1-l-66.png

**Comment by jtanx** [comment]
I think it's pretty clear from that it's a false positive.
