### ISSUE TITLE
Bitmap magnification more than 5

### ISSUE THREAD

**Issue by khlorghaal** [fontforge/fontforge#4599]
https://github.com/fontforge/fontforge/blob/cd969b3cd9fd2a05b51ed4b8bd3ce903773500c3/fontforgeexe/fontview.c#L3358

is there a reason magnification is limited to 5? Can this check be removed? Severely inconvenient for making a lowres font on a highres display.

**Comment by skef** [comment]
Eliminating it seems like a potentially poor idea but the limit could probably be raised. 

I just tried it with 20 and it seemed fine. Would that be enough?

**Comment by khlorghaal** [comment]
that should be plenty, i was wanting around 8\* for editing a 7x7 font on a 2k display

**Comment by yg8ijvjvjv** [comment]
When the value is set extremely high, it will determine no glyph fits and fallback to 0×0 glyph view, like it already does with large bitmaps. The cap might be to prevent numerical overflow (5462 size at six magnification is overflow in 16-bit integer for instance).

**Comment by skef** [comment]
Not sure why 5462 at x6 would be more salient than, say, 10000 at x3.

**Comment by yg8ijvjvjv** [comment]
Because 5462*6==32772, more than 32767, so it will overflow in 16-bit integers. 30000 does not overflow. With the cap of 5 the limit is 6553.

**Comment by skef** [comment]
Yes, I should have doubled checked my example, but the point stands: 1) 5462 is an extremely large strike and nothing makes it salient compared with 7500 or 10000. And regardless, FontForge code tends to use at least 32 bit integers unless there is some special reason to, as with generating font files. Hell, it usually uses an `int` for 
booleans.

You're not adding anything here except speculation and you've already been asked to stop spamming other issues.

**Comment by khlorghaal** [comment]
most extreme case would be making a 4x4 font on a 4k display, and you want characters 1/8 screen height:  ~64x magnification

**Comment by ctrlcctrlv** [comment]
If increasing the maximum to 64 doesn't cause crashes I have no problem with it. 😊
