### ISSUE TITLE
Converting OTF-font in CentOS 8 fails with double free detected in tcache 2

### ISSUE THREAD

**Issue by Kwisso911** [fontforge/fontforge#4604]
For any OTF-font we want to convert to WOFF/TTF in Fontforge fails with the following error:
free(): double free detected in tcache 2 Aborted (core dumped)

Command to replicate the bug in CentOS 8:
fontforge -lang=ff -c 'Open($1); Generate($2)' 'font2.otf' 'font2.woff'

**Comment by skef** [comment]
What version of FontForge is installed?

**Comment by Kwisso911** [comment]
The one from this package, which should be the most actual, correct me if i am wrong:
https://centos.pkgs.org/8/centos-powertools-x86_64/fontforge-20170731-15.el8.x86_64.rpm.html

**Comment by skef** [comment]
That page suggests the version is from July 2017, so very much not a recent version.

Are you in a position to build a more recent version?

**Comment by Kwisso911** [comment]
I am sorry, i am not in the position to build a more recent one for CentOS 8.

**Comment by skef** [comment]
In that case you might try the appimage: https://github.com/fontforge/fontforge/releases https://appimage.github.io/FontForge/

**Comment by Kwisso911** [comment]
Thank you for the help, i'll try it out and come back with an update.

**Comment by Kwisso911** [comment]
We could not use the appimage in our setup but we managed to get fontforge-20200314-5.el8.x86_64.rpm running on CentOS 8.

**Comment by skef** [comment]
Did it resolve the original woff problem?

**Comment by Kwisso911** [comment]
Yeah it did, the confusing part was that the standard rpm-package for CentOS 8 had this problem in. Which is gone in the newer build.

**Comment by skef** [comment]
Good! I'll close this one then.
