### ISSUE TITLE
Creating a glyph that substitutes 2 glyphs

### ISSUE THREAD

**Issue by dpchihuahua** [fontforge/fontforge#4607]
Hi! I´m new to fontforge and programming in general, but I´ve managed to surpass all the obstacles and I´m almost done with my first font.
However there´s still one big problem that doesn´t let me finish it.
I´m working on an alphabet for a non-unicode language and I want it to work on any keyboard or config, so I don´t want to change the keyboard preferences, I want it to work as a font for english, spanish or any latin keyboard.
The main problem is there´re some special glyphs for SH, CH, LL and other latin compound glyphs, but here, they work as unique glyphs, phonemes and sounds. I want the users to write as they talk, so I don´t want to use complex unicode inputs in order to get these glyphs, I want them to write S, then an H, and instead of getting the S or H glyphs I want´em to get the new SH symbol, that´s it. I´ve been reading a lot and I know it has to do with the substitution lookups, but my program doesn´t let me click on next when I´m adding the subtables.
I´ll be very grateful if you can help me since it´s the last obstacle I´m facing!

I´m working on a Windows 10 i.7

**Comment by skef** [comment]
Does this help? https://www.fonttutorials.com/how-to-create-ligatures/#adding-a-ligature-substitution-lookup-table

**Comment by dpchihuahua** [comment]
> Does this help? https://www.fonttutorials.com/how-to-create-ligatures/#adding-a-ligature-substitution-lookup-table

Thanks skef... I read the tutorial and I think it´s what I want... However when I get to the part of Adding a Ligature Substitution Subtable I write the S_H on the left column as the tutorial explains, but I get a popup saying there´s no S_H glyph.
In the tutorial they use f_i which is the exact same thing, and I understand they´re combining the 2 glyphs with the underscore (_) but it doesn´t work on my case... Maybe I´m failing on an unspecified step before this tutorial or something like that, do you have some idea please?
I´m attaching a capture
![Capture](https://user-images.githubusercontent.com/78451843/106677646-1c9d6700-6587-11eb-89a2-9a2217d43e97.PNG)

**Comment by dpchihuahua** [comment]
> Does this help? https://www.fonttutorials.com/how-to-create-ligatures/#adding-a-ligature-substitution-lookup-table

I´ve repeated and checked well and it´s fine!!! Thanks a lot
