### ISSUE TITLE
print (fontforge.version()) (or other equivalent command) should reflect intermediate builds too

### ISSUE THREAD

**Issue by dimitre** [fontforge/fontforge#4609]
- [x] The FontForge version and the operating system you're using
macOS 10.14 - 20201107, but actually it is the latest HEAD, master branch
- [x] The behavior you expect to see, and the actual behavior
print (fontforge.version()) returns 20201107 which is the latest release
it would be great to have any indication of actual build in this variable, like last commit date, or maybe the commit hash, or even just "prerelease" appended to the version.

I think it is useful because there is no way of knowing which build python is running (AFAIK, please let me know if there is)
Thank you

**Comment by skef** [comment]
I believe this has the git commit string (which is also available in the "about" screen) as its second element:

```
import fontforge

print(fontforge.__version__)
```

**Comment by dimitre** [comment]
Outstanding, I'll update my copy of reference here http://dmtr.org/ff.php
Closing now
