### ISSUE TITLE
Generate Fonts All Options Grayed Out

### ISSUE THREAD

**Issue by booth-f** [fontforge/fontforge#4620]
Screenshot: [https://i.imgur.com/wooWnlN.png](https://i.imgur.com/wooWnlN.png)

I'm working on building a font and all the glyphs that I have seem to be added. I've even gone through and ran through the validator and it comes back all good but the moment I try to export the font I can't. Even getting it to select opentype required me hitting the down arrow just to get it selected. Once I hit generate it creates an empty font document and says "font contained no glyphs" even though clearly they are in there.

FontForge version 20200314 on Gentoo Linux. I've even tried bringing the saved FontForge project file over to Windows 10 running FontForge 20201107 and got the same issue happening there as well.

Expect to See: Able to select a format to export the font to.
Actual behavior: All font export options are unavailable or produce an empty font file when generated.

Steps to Reproduce: Take any glyph traced in Inkscape and exported as an SVG and map it to a character in FontForge. Attempting to export the font will result in all options being unavailable.

I've also verified that in Inkscape I am working on a 1000x1000 render of the glyph so the vector is in the size FontForge is expecting.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
First off all of those glyphs have gray x-es behind them, which is FontForge indicating they're not valid. Without seeing a CharView window it's hard to tell definitively why but my guess is that they're zero-width, so you need to either open all of them and adjust the width or do so programatically. 

I also don't recall ever seeing glyphs with descenders poke up like that in FontForge, so their vertical positions are probably wrong, and it looks like you've imported with scaling set to true so they've been scaled different amounts. My recommendation: Start by setting the ViewBox for each glyph in Inkscape to be the full height of the font (ascent+descent) and position each glyph in the viewBox where you want it to end up. Then import with scaling turned off (or leave it on if you want to change the height at that stage -- as long as all the viewboxes are the same height they'll all scale the same amount).   

You also probably need to add some parameters to the ["Font Info ..."](https://fontforge.org/docs/ui/dialogs/fontinfo.html) dialog under "Elements" before you can generate in any outline font format (or at least generate them sensibly).
