### ISSUE TITLE
Fontforge download problem

### ISSUE THREAD

**Issue by edrol97** [fontforge/fontforge#4621]
Can't download Fontforge, as Apple says it is "cannot be opened because the developer cannot be verified." How do I solve this? I'm downloading on Mac OS Big Sur 11.0.1 and am attempting to download FontForge version 20200314, in order to merge two handmade fonts. Thanks, Eliot

**Comment by ctrlcctrlv** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
