### ISSUE TITLE
Ligature problems on Microsoft word

### ISSUE THREAD

**Issue by dpchihuahua** [fontforge/fontforge#4625]
I have a problem with the ligatures on my exported and installed OTF on word while it works perfect on font forge.
I´m working with non latin characters, as you can see here:
[https://drive.google.com/file/d/1kMBpWg4T6kBfaS3jVoEI5_gcKsYR6t_R/view?usp=sharing](url)
The first big letter is an A and the second is a L. The first little one is an m and the second is an a.

My ligatures work properly on fontforge, and as you can see below, the little symbols get mixed with the bigger ones, It´s supposed to look like this:
[https://drive.google.com/file/d/19_DV80Jz3AngTkf_cdds0jJ3O2ChtP9-/view?usp=sharing](url)
So, you can read it as AmLo

However, when I do the input on word, the cursor goes to the left of the big letter, so, the second letter fuses with the first, as you can see here:
[https://drive.google.com/file/d/1jYYNjuun2vA_INVse1TAAwj0N1LHpG-G/view?usp=sharing](url)

You should note that I´ve worked with the GPOS lookups and I can get all the combinations and they work fine, even in Word. The problem comes because some characters didn´t blended well so I decided to make special ligatures for them... 
For example, I haven´t done yet the ligatures for Wa and Za, so, they´re working just as mark to mark position without ligature, and you can see the input WaZa works fine and the cursor is on the right, but the combination isn´t aesthetic yet:
[https://drive.google.com/file/d/1xseKhLLLHBdJlIzejOa1F-ZdodugA0-x/view?usp=sharing](url)

Here you can see the Am without the ligature:
[https://drive.google.com/file/d/1kvbCynPHxNs2Yc6NO4XexZMLva_2hA36/view?usp=sharing](url)

Please, if someone knows a solution I´d be vere greatful!

**Comment by aminabedi68** [comment]
try using `rlig` instead `liga`
(It would be nice if you could share the font(unless you can't due to copyright protection))

**Comment by dpchihuahua** [comment]
@aminabedi68 AMAZING!!! that was it!!! I don´t know how this program can be so difficult sometimes... Thank you so much. I cannot share it yet, but when all the copyright is done I´ll show you!!! :)
Do you have some advice for Illustrator??? I still got the problem there. I know you should activate it on the OpenType menu - ligatures, but the option keeps greyed out with my font so I cannot use it. However, the font works amazing on Indesign, even with the normal ligatures... I´d be very greatful if you have some trick for that!

**Comment by KamilLanda** [comment]
You can also try to add the Contextual (Chaining) Substitution. Make one empty glyph and then you will substitute first character to the ligature and the second character to empty glyph. Or first to the empty glyph and second to the ligature.

**Comment by skef** [comment]
This appears to be a feature design issue rather than a FontForge issue -- closing.
