### ISSUE TITLE
Including files in UFO features.fea files: Our implementation is wrong

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4629]
The [specification](https://unifiedfontobject.org/versions/ufo3/features.fea/) is clear:

> Any `include()` statements must be relative to the UFO path, not to the `features.fea` file itself.

Meaning, the path the UFO _is in_ is the relative path used in these files. When you have a UFO named `a.ufo` and it has a `features.fea` containing:

```fea
include(../mark.fea);
```

This means:

* include `a.ufo/../../mark.fea`

Not:

* include `a.ufo/../mark.fea`

That's the meaning used by `fontmake`. Our implementation is wrong and should change, but it's going to break everyone's UFO's.

What to do, what to do?

**Comment by skef** [comment]
> What to do, what to do?

Probably search the proper way and then the improper way when the proper one fails[ And when someone with a collision files a bug tell them where the spec says their file should be.
