### ISSUE TITLE
Generated OTF is much larger than TTF

### ISSUE THREAD

**Issue by rajeeshknambiar** [fontforge/fontforge#4632]
Fontforge version: 20200314
OS: Fedora 33 x86_64

# Issue
Size of OTF file generated is much larger than TTF file (not sure if this is to be expected). Difference in `ttx` dump seems to show large `CFF` table in OTF.

# Supplementary information
Attached archive containing SFD, generated OTF and TTF files.
[Rachana.tar.gz](https://github.com/fontforge/fontforge/files/5977104/Rachana.tar.gz)

Steps to reproduce: open the SFD using Fontforge, Menu → Generate Fonts → Choose `OpenType (CFF)` for OTF, `TrueType` for TTF.
(Actual build script and full sources are available at https://gitlab.com/rit-fonts/RIT-Rachana/. One can run `make otf` to generate the files in `build` directory)

Generated OTF file size is 1.9 MB, TTF file size is 476 KB.

Any suggestions?

**Comment by skef** [comment]
Basically all of the size difference is in the contour storage (CFF in OT, glyf in TT):

```[skef@didactic build]$ ttx -l RIT-Rachana-Regular.otf
Listing table info for "RIT-Rachana-Regular.otf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CFF   0x7580481D   1861025      3144
    DSIG  0x00000001         8   1892896
    FFTM  0x7BD90C20        28   1892904
    GDEF  0x145D1262       110   1864172
    GPOS  0x155AB8D5     18046   1874848
    GSUB  0x243CB69D     10564   1864284
    OS/2  0x96CEE485        96       336
    cmap  0x8899CBB6       704      2408
    head  0x0932B67C        54       236
    hhea  0x10880D8C        36       292
    hmtx  0x4CE376A6      4644   1892932
    maxp  0x04895000         6       328
    name  0x0B788385      1976       432
    post  0xFE0C0022        32      3112

[skef@didactic build]$ ttx -l RIT-Rachana-Regular.ttf
Listing table info for "RIT-Rachana-Regular.ttf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    DSIG  0x00000001         8    441892
    FFTM  0x7BD90C20        28    470624
    GDEF  0x145D1262       110    441900
    GPOS  0x155AB8D5     18046    452576
    GSUB  0x243CB69D     10564    442012
    OS/2  0x96CEE465        96       408
    cmap  0x899CCBB6       704      5148
    cvt   0x0831062E        18      5852
    gasp  0xFFFF0004         8    441884
    glyf  0x667B4F09    420464     10520
    head  0x0931B67D        54       284
    hhea  0x10870D8C        36       340
    hmtx  0x4CE376A5      4644       504
    loca  0x0C5FBCA8      4648      5872
    maxp  0x05AF0189        32       376
    name  0x0B788385      1976    430984
    post  0x75CD7DAF      8923    432960
```
Given that you've designed the glyphs with quadratic splines with a lot of interpolated points it's not surprising the glyf table is relatively modest. For CFF your contours are being automatically converted to cubic splines directly without any attempt at simplification. 
 
I did the same conversion to with your SFD and then selected all the glyphs and ran "Simplify" (Not necessarily a safe procedure in every case) and wound up with this after generating:

```
[skef@didactic sources]$ ttx -l RITRachana-Regular.otf 
Listing table info for "RITRachana-Regular.otf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CFF   0xAD3D9D31    821247      3084
    FFTM  0x7C540811        28    824432
    GDEF  0x151B132C        98    824332
    OS/2  0x96CEE47E        96       288
    cmap  0x8899CBB6       704      2348
    head  0x09ADB26D        54       188
    hhea  0x10880D8C        36       244
    hmtx  0x4CE376A7      4644    824460
    maxp  0x04895000         6       280
    name  0x87890749      1964       384
    post  0xFE0C0022        32      3052
```

So better, if still not as small as the glyf table.

**Comment by ctrlcctrlv** [comment]
You may also want to consider exploring `compreffor`. `compreffor` is non-destructive, unlike Simplify.

https://github.com/googlefonts/compreffor

If you use a `fontmake` workflow, `compreffor` is default. (Yes, it's possible to use a `fontmake` workflow with FontForge. That's the only way I've worked for a year. You use FontForge to make UFO's, (or sadly sometimes due to #4539 etc., OTF then UFO via `ufo-extractor`), then you use `fontmake` to actually build the `OTF`. Cuts out FontForge's labyrinthine C codebase for a much more understandable Python codebase for when generation goes wrong. So far it's worked wonders for me—YMMV.

**Comment by khaledhosny** [comment]
Or https://github.com/adobe-type-tools/cffsubr which is much much faster.

**Comment by khaledhosny** [comment]
For SFD to UFO, I use my https://github.com/alif-type/sfdLib, which is pure Python and does a better job IMO, but I only tested it with the few remaining SFD fonts I actively maintain.

**Comment by rajeeshknambiar** [comment]
Many thanks, all.

So I shall try:
1. Cubic splines/Bézier curves in SFD to see if it produces acceptable results.
2. Otherwise, migrate to UFO utilizing the tools mentioned here. I guess @khaledhosny’s `tirobuild` is another potential build tool?

**Comment by khaledhosny** [comment]
`cffsubr` works on compiled OTF fonts, so you can use it to post-process the OTFs generated by FontForge (FontForge’s own subroutinzer is know to be sub-optimal):
```
$ python -m cffsubr Rachana-OTF.otf -o Rachana-OTF-CFFSUBR.otf
$ ttx -l Rachana-OTF.otf Rachana-OTF-CFFSUBR.otf
Listing table info for "Rachana-OTF.otf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CFF   0xEBB0B08B   1944520      2872
    DSIG  0x00000001         8   1977700
    FFTM  0x7AF4F7D6        28   1947392
    GDEF  0x12671042        94   1947420
    GPOS  0x9D877E7B     14026   1947516
    GSUB  0x4C77A7D5     11334   1961544
    OS/2  0x96C2E485        96       336
    cmap  0xD79B4444       530      2308
    head  0x09AC6A30        54       236
    hhea  0x10880DB8        36       292
    hmtx  0x94E8906E      4820   1972880
    maxp  0x04B55000         6       328
    name  0xC7D9E32F      1875       432
    post  0xFE0C0022        32      2840

Listing table info for "Rachana-OTF-CFFSUBR.otf":
    tag     checksum    length    offset
    ----  ----------  --------  --------
    CFF   0xD3D15213   1100307      2872
    DSIG  0x00000001         8   1133488
    FFTM  0x7AF4F7D6        28   1103180
    GDEF  0x12671042        94   1103208
    GPOS  0x9D877E7B     14026   1103304
    GSUB  0x4C77A7D5     11334   1117332
    OS/2  0x96C2E485        96       336
    cmap  0xD79B4444       530      2308
    head  0x09ADF33A        54       236
    hhea  0x10880DB8        36       292
    hmtx  0x94E8906E      4820   1128668
    maxp  0x04B55000         6       328
    name  0xC7D9E32F      1875       432
    post  0xFE0C0022        32      2840
```
It cuts down the CFF table by ~40% without any other change.

`tirobuild` is very specific to Tiro workflows and might not be useful for others, but it uses the same underlying libraries that `fontmake` uses.

**Comment by rajeeshknambiar** [comment]
> `cffsubr` works on compiled OTF fonts, so you can use it to post-process the OTFs generated by FontForge (FontForge’s own subroutinzer is know to be sub-optimal):

Ok, I just tried that and it indeed cuts down the size of OTF file to 1.1 MB.

Yet, I was hoping that the file could be under an MB. In order to achieve that, is it correct to assume that glyphs should be cubic curves?

**Comment by skef** [comment]
If you're outputting OTF a normal file of that type will store cubic curves.

**Comment by rajeeshknambiar** [comment]
> If you're outputting OTF a normal file of that type will store cubic curves.

Ok. Then to reduce the OTF file size, the best procedure is to simplify the curves & points (manually, to preserve the fidelity of shapes)?

**Comment by skef** [comment]
That would be a whole lot of work. I would recommend starting with Simplify (from the element menu) and inspecting the results, tweaking if necessary. 

Also: OpenType doesn't have the "no overlap" restrictions that TrueType has (@khaledhosny can step in here if I'm wrong about this) so another way to save a lot of space s to make more use of references. Many of your glyphs are different combinations of the same shapes, sometimes not overlapping at all (s1n1u1) and sometimes overlapping (m1u1 vs m1u2). (All of your accented "A"s are also contours instead of references.)

**Comment by khaledhosny** [comment]
CFF does not have references (AKA composite glyphs), it has subroutines and they can be any part of the glyph and cffsubr does an excellent job so no need to manually do it (it well de-subtoutinize the table before working on it anyway).

Regardless of this, overlaps are still not recommended whether it is CFF or glyf table, but there is a per-glyph flag to unlink and remove overlaps before generating the font.

**Comment by skef** [comment]
Huh -- that surprises me given how many variable fonts seem to include/rely on overlapping sections.

**Comment by ctrlcctrlv** [comment]
Variable fonts are a different beast. They use CFF2 table, not CFF. You are correct that overlapping is mandatory in variable fonts.

**Comment by skef** [comment]
So presumably once variable font support is sufficiently wide developers will have the option of using CFF2 for fonts that aren't variable (or "only happen to have one point on one variability axis").

Still, given that overlap is a rendering issue rather than a storage issue (CFF can certainly *store* overlapping contours), and rendering occurs after the calculation of a "variant", I would expect that CFF overlap is now only a problem for older renderers. (So, basically, if you were OK with your font only being used in contexts with CFF2 support then a CFF font with overlap probably also works fine in those places.)

**Comment by skef** [comment]
Seems like this is more or less resolved.

**Comment by rajeeshknambiar** [comment]
Couple more updates on this topic:

1.  Using `cffsubr` reduced size, but the output font seems malformed. Fontforge fails to open the file, XeLaTeX couldn’t generate PDF files with it, but [crowbar](http://www.corvelsoftware.co.uk/crowbar/) shapes the text correctly. Fontforge gives the following messages when trying to open the file:
```
No (usable) bitmap strikes in this TTF font: <font path>
<Font> is not in a known format (or uses features of that format fontforge does not support,
or is so badly corrupted as to be unreadble
```
and in the warnings window:
```
Ignoring 'CFF2' PostScript font program (Compact Font Format 2)
```
Font is generated using python build script linked in the report, with following lines added:
```python
with TTFont(out_font, lazy=False) as font:
    cffsubr.subroutinize(font, cff_version=2, keep_glyph_names=True)
    save(out_font)
```

The generated OTF file is available here for reference: https://rajeeshknambiar.fedorapeople.org/RIT-Rachana-Regular-cffsubr.otf

Should a bug be reported against FontForge for this?

2. I was able to generate valid OTF file of size `628 KB` by adding the `round` option to `generate` method (`PostScript → Round` option in `Generate → Options` window, which rounds coordinates to integers).
```python
tmpfont.generate(out_font, flags=('opentype','round','dummy-dsig'))
```
I’ll probably resort to this solution for now.

**Comment by ctrlcctrlv** [comment]
You are telling cffsubr to generate a CFF2 font. These fonts are still not widely supported in open source tools, such as XeLaTeX (or for that matter FontForge). Remove `cff_version=2`.
