### ISSUE TITLE
bootstrap fails while cloning gnulib

### ISSUE THREAD

**Issue by vnaganathan-conga** [fontforge/fontforge#4636]
I am trying to install Pdf2HTMLEx on alpine (in a docker) using these [instructions](https://hub.docker.com/r/bwits/pdf2htmlex-alpine/dockerfile). fontforge is a dependency that needs to be installed first. Unfortunately it is failing due to an issue with bootstrap. To debug this, I reproduced the issue on my MAC. Here is the summary:

I cloned fontforge.git on my MAC & ran ./bootstrap --force & it fails.

git clone https://github.com/BWITS/fontforge.git
cd fontforge
./bootstrap --force

This fails with a FATAL error.  This is caused by the use of the **--depth option** in the git clone.

bootstrap: running: libtoolize --force --quiet
bootstrap: running: git clone --depth 365 'http://git.savannah.gnu.org/r/gnulib.git' 'gnulib'
Cloning into 'gnulib'...
**fatal: dumb http transport does not support shallow capabilities**
----

Is there any workaround for this problem? Any suggestions/comments?

**Comment by jtanx** [comment]
This is not supported any more, sorry. We moved off gnulib/bootstrap ages ago.
