### ISSUE TITLE
Source Code  for fontforge.pyd?

### ISSUE THREAD

**Issue by itungsten** [fontforge/fontforge#4641]
Hello. Recently, I attempt to do some changes to the fontforge python module for performance

But it's frustrating that the file extension of fontforge is "pyd", and I cann't find source code anywhere. 

so, could you please tell me how I can make some changes to the library. For example, can I give a buffer of svg to "glyph.importOutlines" instead of a filename?

Thanks.

**Comment by skef** [comment]
The source code is in this file in the master repository: https://github.com/fontforge/fontforge/blob/master/fontforge/python.c . FontForge's support is provided via the python C-API.
