### ISSUE TITLE
macOS m1: dyld: Library not loaded: @rpath/libfontforge.4.dylib

### ISSUE THREAD

**Issue by Fortidude** [fontforge/fontforge#4658]
Installing FontForge with brew:

```
➜  ~ brew install fontforge

Warning: Treating fontforge as a formula. For the cask, use homebrew/cask/fontforge
Error: fontforge: no bottle available!
You can try to install from source with:
  brew install --build-from-source fontforge
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

installing from source:

```
➜  ~ brew install --build-from-source fontforge

==> cmake .. -GNinja -DENABLE_GUI=OFF -DENABLE_FONTFORGE_EXTRAS=ON
==> ninja
==> ninja install
==> fontforge cask is installed, skipping link.
==> Caveats
This formula only installs the command line utilities.

FontForge.app can be downloaded directly from the website:
  https://fontforge.github.io

Alternatively, install with Homebrew Cask:
  brew install --cask fontforge
==> Summary

```

tried to run:

```
dyld: Library not loaded: @rpath/libfontforge.4.dylib
  Referenced from: /opt/homebrew/Cellar/fontforge/20201107/bin/./fontforge
  Reason: image not found
```

I can see the `libfontforge.4.dylib` under `./lib/libfontforge.4.dylib` 

What can I do with this?

**Comment by jtanx** [comment]
Sounds like a homebrew problem. 

* Does installing from a bottle work?
* If you really want to build from source can you try commenting out https://github.com/Homebrew/homebrew-core/blob/7ec2d116a180efd718f0db47e087cf0fe5aa2302/Formula/fontforge.rb#L45 and rebuilding

**Comment by Fortidude** [comment]
I'm not really installing it from sources, instead I'm using this command:
```
brew install --build-from-source fontforge
```
I'm not sure if I can edit the source code this way.

About installing from a bottle, I've removed the Fontforge and tried to reinstall:
```
brew install --build-bottle fontforge
```

with or without `brew postinall Fontforge` it still not working. 

Worth to say that the issue occurs on Apple M1 Mac. So.. maybe some issues with brew itself? hmmm

**Comment by jtanx** [comment]
`--build-from-source` implies you are building it from source, why can't you just do `brew install fontforge`?

**Comment by Fortidude** [comment]
My first post here:

```
$ brew install fontforge

Error: fontforge: no bottle available!
You can try to install from source with:
  brew install --build-from-source fontforge
```

**Comment by jtanx** [comment]
Ah right. Well *that* is definitely a homebrew problem, which we don't support, sorry. Try editing the formula as suggested, but otherwise I have no idea.

**Comment by Fortidude** [comment]
It's probably because of ARM / rosetta mode. I will try to install brew under rosetta.

**Comment by radex** [comment]
@jtanx Hi, any idea why passing `-DCMAKE_INSTALL_RPATH=<the_correct_path>` to `cmake` wouldn't do the right thing? I also tried `CMAKE_INSTALL_NAME_DIR`

I attempted to fix the Homebrew formula in https://github.com/Homebrew/homebrew-core/pull/73107#discussion_r593764012 , however I can't figure out how I can get cmake to produce a correct binary. I found a workaround (by fixing up the broken binary's @rpath after the fact), but Homebrew maintainers are somewhat unhappy about doing it this way ;)

**Comment by carlocab** [comment]
Hi there, Homebrew maintainer here. I can see how this looks like a Homebrew problem, but note that you will almost certainly face a similar issue if you try to install fontforge (without using Homebrew) into a non-standard location.

**Comment by jtanx** [comment]
So this has clearly worked in the past and our CI still works which makes me suspicious that it's not our problem.

1. Have you tried the edit I suggested in https://github.com/fontforge/fontforge/issues/4658#issuecomment-793066853? Copying the binaries out of the build folder instead of the installation folder is not very kosher, especially for macos wrt. the loader paths.
2. Can you inspect the paths with `otool -L` for (a) the binary in the build folder, (b) the binary in the installation folder
3. Can you compare to a manual build/install that's not under homebrew?

**Comment by carlocab** [comment]
I agree with you that moving binaries out of the build directory isn't great, but it wouldn't be needed if they were actually installed by `ninja install`, which we call just two lines before that:

https://github.com/Homebrew/homebrew-core/blob/62c4f142f1aae3508596eb319bdf1ec331a8c74c/Formula/fontforge.rb#L42

Are you suggesting that we shouldn't be installing the extras?

**Comment by jtanx** [comment]
> Are you suggesting that we shouldn't be installing the extras?

Possibly, yes, as per https://github.com/fontforge/fontforge/blob/52e84327b429f557c1b73f3c8bc214082dcde485/contrib/fonttools/CMakeLists.txt#L3 they aren't installed for a reason. In any case, the proper way to install them is to patch the CMakeLists.txt.

But first thing's first, can you try to see if that actually makes a difference?

**Comment by carlocab** [comment]
I don't have an M1 Mac to test this on, but hopefully, @Fortidude or @radex can test this.

**Comment by carlocab** [comment]
I tried a slightly more subtle fix in Homebrew CI, and it seems to work. 

Then again, the test isn't very useful: it just calls `fontforge -version` and tries to import the Python libraries. On the other hand, `fontforge -version` fails without the fix:

```
==> /opt/homebrew/Cellar/fontforge/20201107/bin/fontforge -version
dyld: Library not loaded: @rpath/libfontforge.4.dylib
  Referenced from: /opt/homebrew/Cellar/fontforge/20201107/bin/fontforge
  Reason: image not found
```

**Comment by jtanx** [comment]
Great, well I guess that means we're on the right path then.

It probably means though that all those extra binaries you copied in won't work for the same reason. If you truly want to install those extra binaries, you should do this instead:

```diff
diff --git a/contrib/fonttools/CMakeLists.txt b/contrib/fonttools/CMakeLists.txt
index 0d3f464bc..b9f210cde 100644
--- a/contrib/fonttools/CMakeLists.txt
+++ b/contrib/fonttools/CMakeLists.txt
@@ -18,3 +18,5 @@ target_link_libraries(dewoff PRIVATE ZLIB::ZLIB)
 target_link_libraries(pcl2ttf PRIVATE MathLib::MathLib)
 target_link_libraries(ttf2eps PRIVATE fontforge)
 target_link_libraries(woff PRIVATE ZLIB::ZLIB)
+
+install(TARGETS acorn2sfd dewoff findtable pcl2ttf pfadecrypt rmligamarks showttf stripttc ttf2eps woff RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
\ No newline at end of file
```

**Comment by carlocab** [comment]
That seems to work too; thanks.
