### ISSUE TITLE
What is Spline1D? (improve Data Types documentation)

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4676]
I'm trying to convert `.glif` files into FontForge's internal format.

`SplinePoint`'s have a field called `splines` which is two `Spline1D`'s. What are these, and how do I calculate them? [It's not well documented](https://fontforge.org/docs/techref/splinefont.html).

At least, this sentence makes no sense to me:

> The `Spline1D` structures give the equations for the x and y coordinates respectively (`splines[0]` is for x, `splines[1]` is for y).

**Comment by ctrlcctrlv** [comment]
I'm leaving this open as I think the documentation could be improved, but I figured out I should call `SplineMake` in libfontforge.so and only make the `SplinePoint`'s myself, not the `Spline` type.

**Comment by skef** [comment]
There was just a discussion of this over at https://github.com/fontforge/fontforge/discussions/4673 . The FontForge documentation is at https://fontforge.org/docs/techref/bezier.html .

**Comment by ctrlcctrlv** [comment]
Hey, thanks. That's useful.

This works for me:

```
fn make_spline(from: *mut fontforge::SplinePoint, to: *mut fontforge::SplinePoint) -> *mut fontforge::Spline {
    unsafe {
        let s = fontforge::SplineMake(from, to, 0);
        fontforge::SplineRefigure(s);
        s
    }
}
```

**Comment by skef** [comment]
It's been a while but I'm pretty sure `SplineMake()` calls `SplineRefigure()` already. You typically call the latter directly when the point locations have changed but the spline structure already exists.

**Comment by ctrlcctrlv** [comment]
That makes sense. If you're curious what I'm doing, I'm making it so MFEKstroke can do nib stroking if FontForge is on the system.

This is 30% done but here it is, if you have any time to give further comment:

https://gist.github.com/ctrlcctrlv/2b75fd25b6ac531eb2c01670f0541730

**Comment by skef** [comment]
I'm not currently a "rust person" but the effort here mostly makes me wonder why you're not doing the equivalent of an "exec" with some external python code. If the source splines and nib are already in glif format (or easy to put in that format) it's easy enough to write a little stroking sub in python that takes command-line arguments and leaves the output also in a glif file to be read back in.

I guess one reason not to do that is performance but it seems unlikely to matter much in most circumstances.

**Comment by ctrlcctrlv** [comment]
Few reasons:
* FontForge may be on the system but not Python (or a working Python interpreter).
* On Windows, this means I only need to distribute libfontforge.dll and not a Python distribution. I plan to distribute MFEK as a .zip file on Windows of MFEKglif.exe, MFEKstroke.exe, MFEKmetadata.exe, etc. Now I can drop libfontforge.dll into there and it'll work.
* The source splines and nib are in .glif format, but I'm aware of several FontForge .glif bugs, especially #4327, #4539, which make me not want to rely on FontForge to write my .glif, I have more faith in the MFEK/glifparser.rlib I wrote

**Comment by jtanx** [comment]
Just as long as you keep in mind there are no api/abi guarantees since technically libfontforge is purely internal implementation detail.

**Comment by ctrlcctrlv** [comment]
That's fine, the ABI is stable enough. The few functions I'm using I doubt will be seeing major ABI changes. FontForge development moves slowly enough I can easily react in time if something does change.

**Comment by ctrlcctrlv** [comment]
I was able to stroke with a nib in Rust! :)

![image](https://user-images.githubusercontent.com/838783/112395820-7ee82d80-8cd5-11eb-8933-a395e5cf5de4.png)

```rust
fn convert_glif() {
    let nibglif: glifparser::Glif<()> = glifparser::read_ufo_glif(&fs::read_to_string("nib2.glif").unwrap());
    eprintln!("Reading nib...");
    let (mut nibss_raw, mut _nibss_ffsps) = glif_to_ffsplineset(nibglif);
    eprintln!("Reading path...");
    let ssglif: glifparser::Glif<()> = glifparser::read_ufo_glif(&fs::read_to_string("Q_.glif").unwrap());
    let mut outglif = ssglif.clone();
    let (mut ss_raw, mut _ss_ffsps) = glif_to_ffsplineset(ssglif);
    let mut nibss_boxed = Box::new(nibss_raw);
    let mut ss_boxed = Box::new(ss_raw);
    let mut nibss = nibss_boxed.as_mut();
    let mut ss = ss_boxed.as_mut();
    let mut out_ss;
    unsafe {
        let shape = fontforge::NibIsValid(nibss);
        if shape != 0 {
            let shapetype = fontforge::NibShapeTypeMsg(shape);
            eprintln!("Shape: {}\nCannot stroke!", ffi::CStr::from_ptr(shapetype).to_str().unwrap());
            return
        }
        let si = fontforge::InitializeStrokeInfo(ptr::null_mut());
        (*si).stroke_type = fontforge::si_type_si_nib;
        (*si).nib = nibss;
        (*si).width = 10.;
        (*si).simplify = -1;
        (*si).rmov = fontforge::stroke_rmov_srmov_none;
        // Do the stroke:
        let newss = fontforge::SplineSetStroke(ss, si, 0);
        //println!("{:?}", *newss);
        out_ss = *newss;
    }
    let out = ffsplineset_to_outline(out_ss);
    outglif.outline = Some(out);
    // XML .glif format
    println!("{}", glifparser::write_ufo_glif(outglif));
}
```

Now I just have to make an actual command line API and it's all ready to go.

**Comment by skef** [comment]
This is documented in multiple places. If it is hard to find that's because of the overall difficulty of finding things in the documentation. (Although it is touched on in the document linked to above: "The Spline1D structures give the equations for the x and y coordinates respectively (splines[0] is for x, splines[1] is for y).".)

Closing this.
