### ISSUE TITLE
Getting svg glyph d attribute

### ISSUE THREAD

**Issue by ertpoi** [fontforge/fontforge#4700]
I am working with a svg font file. How can I access the single glyph's `d` attribute while iterating over the single glyphs in Python? I have something like the following

```python
import fontforge as ff


f=ff.open("/home/ertpoi/bravura/svg/Bravura.svg")

for x in f.selection.all():
    glyph = f[x]
    print glyph.isWorthOutputting()
    print glyph.export("/tmp/SMT-{0}.svg".format(glyph.glyphname))
```

Is it possible to not export the glyphs and still have access to their `<path >` d attribute?

**Comment by ctrlcctrlv** [comment]
Not with the FontForge Python API. You're going to want an XML parser instead, I think.

**Comment by skef** [comment]
@ertpoi You can do something like what you're asking with FontForge but it's probably not what you want.

I suspect you're assuming that when FontForge opens an SVG font it retains the **original** path information. It doesn't -- if there are arcs and such they will be translated into Bezier spline sequences, relative positioning will become absolute positioning, and so forth.

If you want the individual SVG files from the font this may work (I haven't tested it): https://gist.github.com/su-narthur/1233e540777036d49e79e15c75135850

If you don't care that the paths may be translated you can generate the path equivalent to FontForge's internal state (once it has imported the file) by doing this:

```
#!/usr/bin/env python

import fontforge as ff
from fontTools.pens.svgPathPen import SVGPathPen

f = ff.open("/tmp/l.sfd")

f.selection.all()

glyphset = {}

for g in f.selection.byGlyphs:
    print(g)
    svgpen = SVGPathPen({})
    g.draw(svgpen)
    path = svgpen.getCommands()
    print(path)
```

**Comment by ertpoi** [comment]
Great, thanks for your help!
