### ISSUE TITLE
Opening CID font

### ISSUE THREAD

**Issue by NightFurySL2001** [fontforge/fontforge#4713]
Versions: FontForge v.20200314, Windows 10 20H2

When opening [Yuji Syuku font (OTF)](https://github.com/Kinutafontfactory/Yuji/tree/master/fonts/OTF), the glyphs do not appear fully unless flattened.
![image](https://user-images.githubusercontent.com/33471049/115962306-3bd7df00-a54d-11eb-973b-d899bebce021.png)

Flattened
![image](https://user-images.githubusercontent.com/33471049/115962360-9113f080-a54d-11eb-9501-70847b65ed45.png)

**Comment by ctrlcctrlv** [comment]
The CID menu allows you to switch between subfonts. 

We recommend flattening anyway if you're going to manipulate the font.
