### ISSUE TITLE
Question about fontforge GUI icons

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4715]
Hi
I'm trying to create a theme for fontforge but i can't find any link gives access to vector sources(if exist and available), so I would be appreciate any information you may give.
furthermore i'm thinking it would be interesting if we can build these icons as the glyphs set of an opentype svg font, but It's a bit hard and i don't know if there is some advantages/capacities for using in GUI or not (?)

**Comment by skef** [comment]
1. I don't know if you've seen #4704 but if not you should take a look. That will go in eventually and it both changes and extends the non-icon aspects of themes.
2. Given that the original icon sources are SVG, the old SVG font spec is phased out, and the new OpenType SVG font spec may have spotty support, I'm not sure the project is ready to go that direction. Significant testing would be needed. The alternative is to extend the code to make use of pixmap icons generated at different resolutions.
3. I was in the middle of a project to locate or make individual SVG icon files  for all our icons when I switched to a different project. If you were willing to complete that project as a step towards either an OT SVG font or a pixmap-based solution that would be great. (The same work is needed no matter the eventual direction unless the icons are all to be replaced, which would be at least contentious to do "unilaterally".) 

Relating to 3:

The menu (tango) icons I've collected are in 
[tango.zip](https://github.com/fontforge/fontforge/files/6390872/tango.zip) . That archive includes some files made by the original designer after the current pixmaps were generated and some icons I found and/or adapted. 

The main missing *tango* icons are those in the Element -> Style menu, Expand Stroke, Redo, and a few others. (I don't think it's worth making new icons for Inline, Shadow, etc., as those could just be left blank.) The sources, in a somewhat strange state to modern eyes, are at https://github.com/kemie/fontforge-tango-icons . (Most of the icons that aren't custom were taken from the Inkscape Tango icons of the area, which are still in the repository here: https://gitlab.com/inkscape/inkscape/-/tree/master/share/icons/Tango/scalable/actions ). 

There are still a number of icons remaining from the pre-Tango era, only some of which I've made versions of. Some of these (e.g. rotateccw.png, rotatecw.png, rotate180.png) are equivalent to existing or new Tango icons that can be copied or adapted. (The "ptinfo" icons are similar except those should be adapted from palette sources, see below.) There are other icons that still need thought, a number of them relating to the TrueType instruction debugger. 

The current chooser icons also date to that era. I was going to "Tango-ify" those based on this template: 
[chooser_sample.svg.txt](https://github.com/fontforge/fontforge/files/6391039/chooser_sample.svg.txt)

The palette icons are newer than any of these and were designed by @larsenwork 5-6 years ago and added by #2396. We don't have *final* sources for these, as far as I am aware, but there is an earlier draft of the artwork at https://github.com/fontforge/YosemiForge/tree/master/Resources/Graphics . Those contents would need to be adapted to match the current colors and line-styles (less dashing) and split into separate SVG files. (I sent an email asking if there were more recent sources available but never heard back -- not surprising after all this time. Ideally there would be a few improvements on the current pixmap versions, such as being able to see the spiro marks when the palette button is depressed.) 

Hope this helps, and it would be great if you were willing and able to get all this together.

**Comment by aminabedi68** [comment]
thank you @skef
I read your answer and shared links, it seems a great effort has begun to improve the UI looks and customizability.

> If you were willing to complete that project as a step towards either an OT SVG font or a pixmap-based solution that would be great.

sure! asap. first of all, I'll create all missing SVG's and generate pixmap-based PNG's, then going to create my own theme. (for now, I put the OT-SVG version aside, I still think it is a better solution and has very advantages but also there are some limitations like lack of support for gradient colors(afaik), I need to read more and talk with some people.)

**Comment by aminabedi68** [comment]
hi @skef 
i finished converting(designing) the rest of missing icons (with inkscape 0.92.5 (latest version before 1.0)).
please check and reply.
[rest of missing icons in svg.zip](https://github.com/fontforge/fontforge/files/6568614/rest.of.missing.icons.in.svg.zip)
[fontforge whole icon pack.zip](https://github.com/fontforge/fontforge/files/6568597/fontforge.whole.icon.pack.zip)

**Comment by skef** [comment]
Looks good overall -- a big step forward.

The sources based on the pre-Cairo icons (e.g. the debugging icons) may be a bit overly faithful but we can always deal with that in the future.

**Comment by aminabedi68** [comment]
yes. this isn't a redesign, more like converting png to svg. i'm trying to design a new icon pack.(i'm going to close the issue, if you want, reopen)
