### ISSUE TITLE
Native Scripting function `SetGlyphColor` doesn't work in cmd with Type 3 font

### ISSUE THREAD

**Issue by pytkr** [fontforge/fontforge#4717]
**Desc**: 
I use **arial.ttf** as testing font 
1. Using FF GUI to convert this font to **Type 3 Multi Layered Font**, and save as **ArialMT.pt3**, for coloring glyph
2. **only** change the fill color of the layer of glyph `A` to non-black color **#00ff00**
3. Then, run cmd to save glyph `A` to a svg file, as following:
```bat
"C:\Program Files (x86)\FontForgeBuilds\bin\fontforge.exe" -lang=ff -c "Open(\"E:/fonts/ArialMT.pt3\"); Select(\"A\"); Export(\"svg\"); Close(); Quit(0);"
```
4. Open this svg file, and the color of `A` is **#00ff00**, it's OK.

However, when I run cmd to set the color of glyph `B` to non-black color by adding `SetGlyphColor(0x00ff00);` and export to a svg file, as following:
```bat
"C:\Program Files (x86)\FontForgeBuilds\bin\fontforge.exe" -lang=ff -c "Open(\"E:/fonts/ArialMT.pt3\"); Select(\"B\"); SetGlyphColor(0x00ff00); Export(\"svg\"); Close(); Quit(0);"
```
Open this svg file, and the color of `B` is not changed and is **still black**.

Hope for your help and hope for a python api of the same function to change color, thanks!

- **FontForge**: Version: 20201107
- **OS**: win 7 sp1

**Comment by ctrlcctrlv** [comment]
Type 3 fonts do not include SVG fonts. They are a certain kind of PostScript font. FontForge does not support modern color font formats at present, the tracking issue for that'd be #677. Nobody is working on it ATM AFAIK. I was working on it, but then shifted focus to MFEK project, which humorously enough, MFEKglif recently got colored layer support. But that project isn't quite done enough for you to be able to export them. I'll try to remember to update this issue when it is.
