### ISSUE TITLE
Saved feature file (.fea) disagrees with .sfd

### ISSUE THREAD

**Issue by bdenckla** [fontforge/fontforge#4724]
When saving out an Adobe feature file, FontForge is too aggressive in grouping together "anchor-equal" glyphs, i.e. glyphs with the same base-to-mark anchors. Or, another way of putting it: FontForge's criteria for the "anchor-equality" of two glyphs is too weak/lenient. A single equal anchor (as long as it is found before any unequal anchor) is taken to constitute "anchor equality" of the two glyphs.

- [x] The FontForge version and the operating system you're using
Version: 20200314
Based on sources from 2020-03-14 03:45 UTC-ML-TtfDb-D-GDK3.
Based on source from git with hash: c94f19e71cdbea2272ed6508f2d38a5b060dca9e
- [x] The behavior you expect to see, and the actual behavior
Excerpt of expected behavior (note `pedagesh` has value 640 and is not lumped in with `samekhdagesh` & `kofdagesh`, which share value 570):
```
lookup markUpperMarksPositioning {
    markClass [\pashta ] <anchor 309 0> @A29;
    pos base \pedagesh <anchor 640 0> mark @A29
    pos base [\samekhdagesh \kofdagesh ] <anchor 570 0> mark @A29
} markUpperMarksPositioning;
```
I derive this expectation from the following excerpt from the `.sfd`:
```
StartChar: pashta
AnchorPoint: "A29" 309 0 mark 0
EndChar

StartChar: pedagesh
AnchorPoint: "A29" 640 0 basechar 0
EndChar
```
And my expectation is further strengthened by the following excerpt from a `.fea` decompilation produced by running  `otf2fea` on the `.ttf` generated by FontForge (`otf2fea` written by @simoncozens):
```
markClass pashta <anchor 309 0> @Anchor48;
lookup MarkToBase41 {
    pos base pedagesh <anchor 640 0> mark @Anchor48;
} MarkToBase41;
```
Excerpt of actual behavior (note `pedagesh` is lumped in with `samekhdagesh` & `kofdagesh`, with all 3 sharing value 570):
```
lookup markUpperMarksPositioning {
    markClass [\pashta ] <anchor 309 0> @A29;
    pos base [\samekhdagesh \pedagesh \kofdagesh ] <anchor 570 0> mark @A29
} markUpperMarksPositioning;
```
- [x] Steps to reproduce the behavior
Choose "Save feature file" for the attached `.sfd`: [TaameyFrankCLM-Medium-0d114.zip](https://github.com/fontforge/fontforge/files/6446590/TaameyFrankCLM-Medium-0d114.zip)

**Comment by bdenckla** [comment]
I feel like a bug like this would probably reside in `SameBaseAP`, but I don't see anything suspicious [there](https://github.com/fontforge/fontforge/blob/e873b8f43e35bfc8d2053534c4e071a956115819/fontforge/featurefile.c#L1020). Here is `SameBaseAP`, reformatted since its indentation is a little confusing:
```C
static int SameBaseAP(SplineChar *sc1, SplineChar *sc2, struct lookup_subtable *sub)
{
	AnchorPoint *ap1, *ap2;

	for (ap1 = sc1->anchor; ap1 != NULL; ap1 = ap1->next)
	{
		if (ap1->anchor->subtable == sub &&
			(ap1->type == at_basechar || ap1->type == at_basemark))
		{
			for (ap2 = sc2->anchor; ap2 != NULL; ap2 = ap2->next)
			{
				if (ap1->anchor == ap2->anchor &&
					(ap2->type == at_basechar || ap2->type == at_basemark))
				{
					if (ap1->me.x != ap2->me.x || ap1->me.y != ap2->me.y ||
						ap1->has_ttf_pt != ap2->has_ttf_pt ||
						(ap1->has_ttf_pt && ap1->ttf_pt_index != ap2->ttf_pt_index))
						return (false);
					else
						break;
				}
			}
			return (ap2 != NULL);
		}
	}
	return (false);
}
```
There is one thing I find slightly confusing about `SameBaseAP`, though it does not seem suspicious: why isn't the body of the top `if` written as follows?
```C
for (ap2 = sc2->anchor; ap2 != NULL; ap2 = ap2->next)
{
	if (cond1) // abbreviated condition 1
	{
		if (cond2) // abbreviated condition 2
			return (false);
		else
			return (true); // formerly break
	}
}
return (false); // formerly return (ap2 != NULL);
```
which could be further simplified to
```C
for (ap2 = sc2->anchor; ap2 != NULL; ap2 = ap2->next)
{
	if (cond1) // abbreviated condition 1
	{
		return cond2; // abbreviated condition 2
	}
}
return (false); // formerly return (ap2 != NULL);
```
(I've abbreviated the two `if` conditions since they are not relevant to my point.)

I guess it is just a stylistic choice, but it makes me think I'm not understanding the code. For example it makes me think that maybe this isn't just a stylistic alternative, i.e. perhaps my proposal would behave differently, in which case I've misunderstood the code.

**Comment by bdenckla** [comment]
Are paid bounties for bug fixes no longer possible? I see a [FontForge FreedomSponsors.org URL](https://freedomsponsors.org/project/220/) listed [here](http://designwithfontforge.com/en-US/When_Things_Go_Wrong_With_Fontforge_Itself.html) but FreedomSponsors.org seems to no longer be a going concern.

**Comment by skef** [comment]
They didn't really catch on, at least on this project. The set of people willing to work with FontForge source in depth has been pretty limited and its a specialty area often requiring at least some specific knowledge. 

If this is something that falls into the gap between knowing specifically what needs to happen (preferably with some test files) and being able to do yourself a fix can probably be arranged one way or another.

**Comment by bdenckla** [comment]
Thanks @skef I will try to put together a pull request.

First hurdle is I think I followed the build instructions in INSTALL.md but on the compile of every file I'm getting:

> fatal error: fontforge-config.h: No such file or directory.

BTW I also checked the instructions in "[CMake guide for FontForge](https://github.com/fontforge/fontforge/wiki/CMake-guide-for-FontForge)" and they seem to agree with the instructions in INSTALL.md.

On running the following:

```
cd fontforge
mkdir build
cd build
cmake -GNinja ..
ninja
ninja install
```

I get the following output (excerpted)

> [... Lots of CMake stuff ... ]
> -- Generating done
> -- Build files have been written to: /home/bdenckla/fontforge/fontforge/build
> [1/95] Building C object CMakeFiles/fontforge.dir/autohint.o
> FAILED: CMakeFiles/fontforge.dir/autohint.o
> /usr/bin/cc  -I../  -MD -MT CMakeFiles/fontforge.dir/autohint.o -MF CMakeFiles/fontforge.dir/autohint.o.d -o CMakeFiles/fontforge.dir/autohint.o   -c ../autohint.c
> ../autohint.c:28:10: fatal error: fontforge-config.h: No such file or directory
>    28 | #include <fontforge-config.h>
>       |          ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> [2/95] Building C object CMakeFiles/fontforge.dir/activeinui.o
> FAILED: CMakeFiles/fontforge.dir/activeinui.o
> /usr/bin/cc  -I../  -MD -MT CMakeFiles/fontforge.dir/activeinui.o -MF CMakeFiles/fontforge.dir/activeinui.o.d -o CMakeFiles/fontforge.dir/activeinui.o   -c ../activeinui.c
> ../activeinui.c:28:10: fatal error: fontforge-config.h: No such file or directory
>    28 | #include <fontforge-config.h>
>       |          ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> [Many more /usr/bin/cc failures like those above]
> compilation terminated.
> ninja: build stopped: subcommand failed.
> ninja: error: unknown target 'install'

Is `fontforge-config.h` a header file generated by CMake, the way good old `configure` does in the GNU autotools build system?

**Comment by skef** [comment]
I think this may be the same thing we just saw someone else do in #4719. Note that the "cd fontforge" there is to get into the *repository copy*, not the `fontforge` subdirectory of the repository. So whereever you cloned the git repo to, cd into the top level of that directory and follow our CMake wiki guidelines.

**Comment by bdenckla** [comment]
Thanks @skef indeed I was at the wrong fontforge directory level!
