### ISSUE TITLE
bug report: fontforge_main (startui.c:1029) 

### ISSUE THREAD

**Issue by wanghualei2** [fontforge/fontforge#4725]
I found a crash when I run the command "fontforge -script test.pe crash A"
 you can  click [this ](https://raw.githubusercontent.com/wanghualei2/crash_collect/master/fontforge/crash)to get crash.

and the test.pe content as follow:

```
Open($1, 1)
Select($2)
Print( GlyphInfo('Width') )
```

My environment is : ubuntu 18.04 ,gcc7.5

root@9a007102b63c:/home/data/crash_collect/font_forge# ./fontforge/build/bin/fontforge -script test.pe  crash  A
Copyright (c) 2000-2021. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2021-05-07 11:15 UTC-ML-D-GDK3.
 Based on source from git with hash: a5dedb4010cd49a5fcfaeed5d188dd7942294005
The following table(s) in the font have been ignored by FontForge
Segmentation fault (core dumped)

I use the valgrind to get the detail as follow:
==2024376== Memcheck, a memory error detector
==2024376== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2024376== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2024376== Command: /home/data/crash_collect/font_forge/fontforge/build/bin/fontforge -script /home/data/crash_collect/font_forge/test.pe /home/data/crash_collect/font_forge/crashesid:000000,sig:11,src:000000,op:change-havoc,rep:64,diff_start:9,diff_len:491 A
==2024376== Parent PID: 2024347
==2024376== 
==2024376== 
==2024376== HEAP SUMMARY:
==2024376==     in use at exit: 526,652 bytes in 8,399 blocks
==2024376==   total heap usage: 8,845 allocs, 446 frees, 809,365 bytes allocated
==2024376== 
==2024376== 4 bytes in 1 blocks are still reachable in loss record 1 of 275
==2024376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6DBAEE2: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6DBB43B: g_private_get (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6D928BC: g_slice_alloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6D6367D: g_hash_table_new_full (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6D8573A: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x40108D2: call_init (dl-init.c:72)
==2024376==    by 0x40108D2: _dl_init (dl-init.c:119)
==2024376==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==2024376==    by 0x4: ???
==2024376==    by 0x1FFF0006AE: ???
==2024376==    by 0x1FFF0006F0: ???
==2024376==    by 0x1FFF0006F8: ???
==2024376== 
==2024376== 4 bytes in 1 blocks are still reachable in loss record 2 of 275
==2024376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6DBAEE2: ??? (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6DBB43B: g_private_get (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6D4F608: g_get_charset (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x2865BE: DefaultEncoding (prefs.c:796)
==2024376==    by 0x2865BE: PrefsUI_SetDefaults (prefs.c:831)
==2024376==    by 0x510881C: InitSimpleStuff (start.c:90)
==2024376==    by 0x2CA140: fontforge_main (startui.c:1029)
==2024376==    by 0x7061BF6: (below main) (libc-start.c:310)
==2024376== 
==2024376== 8 bytes in 1 blocks are still reachable in loss record 3 of 275
==2024376==    at 0x4C31A3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x4C33D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6D7AC8F: g_realloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6B02840: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B08A91: g_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B0D4D5: g_type_plugin_get_type (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE0265: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x40108D2: call_init (dl-init.c:72)
==2024376==    by 0x40108D2: _dl_init (dl-init.c:119)
==2024376==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==2024376==    by 0x4: ???
==2024376==    by 0x1FFF0006AE: ???
==2024376==    by 0x1FFF0006F0: ???
==2024376== 
==2024376== 8 bytes in 1 blocks are still reachable in loss record 4 of 275
==2024376==    at 0x4C31A3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x4C33D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6D7AC8F: g_realloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6B02840: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B08A91: g_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE20DD: g_boxed_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE22DD: g_value_array_get_type (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AF3ED7: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE028B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x40108D2: call_init (dl-init.c:72)
==2024376==    by 0x40108D2: _dl_init (dl-init.c:119)
==2024376==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==2024376==    by 0x4: ???
==2024376== 
==2024376== 8 bytes in 1 blocks are still reachable in loss record 5 of 275
==2024376==    at 0x4C31A3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x4C33D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6D7AC8F: g_realloc (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6B02840: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B08A91: g_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B11D38: g_pointer_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B11DDF: g_gtype_get_type (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AF40BE: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE028B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x40108D2: call_init (dl-init.c:72)
==2024376==    by 0x40108D2: _dl_init (dl-init.c:119)
==2024376==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==2024376==    by 0x4: ???
==2024376== 
==2024376== 8 bytes in 1 blocks are still reachable in loss record 6 of 275
==2024376==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2024376==    by 0x6D7AC30: g_malloc0 (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.5600.4)
==2024376==    by 0x6B03A09: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B08AC4: g_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B11D38: g_pointer_type_register_static (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6B11DDF: g_gtype_get_type (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AF40BE: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x6AE028B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.5600.4)
==2024376==    by 0x40108D2: call_init (dl-init.c:72)
==2024376==    by 0x40108D2: _dl_init (dl-init.c:119)
==2024376==    by 0x40010C9: ??? (in /lib/x86_64-linux-gnu/ld-2.27.so)
==2024376==    by 0x4: ???
==2024376==    by 0x1FFF0006AE: ???
==2024376== 
......

**Comment by wanghualei2** [comment]
Do you think this is not a bug, or is it unrepeatable?I hope to get your answer?

**Comment by ctrlcctrlv** [comment]
`crash` is clearly not a valid font file, just look at it with `xxd`.

```sass
00000000: 0001 0000 0009 0080 0000 ff10 3853 2fef  ............8S/.
00000010: 8f3f 8156 0000 0118 0000 0020 636d 6170  .?.V....... cmap
00000020: 00a7 fbc9 0000 0190 0000 406e 676c 7966  ..........@nglyf
00000030: b4bc cf71 0000 01ec 0000 0104 6865 6164  ...q........head
00000040: eef6 f34e 0000 009c 00f7 ff35 6868 6561  ...N.......5hhea
00000050: 066b 0109 7fff 00d4 0000 0024 686d 7478  .k.........$hmtx
00000060: 08f3 00e5 0018 6c6f 6361 00fa 0152 0000  ......loca...R..
00000070: 01dc 0000 0010 6d61 7870 0010 0042 0000  ......maxp...B..
00000080: 00f8 0000 0020 705b 7374 77f4 9115 0000  ..... p[stw.....
00000090: 02f0 0000 0038 0001 0000 0001 0000 9be6  .....8..........
000000a0: 6208 5f0f 3cf5 0001 03ff fff7 0000 b492  b._.<...........
000000b0: f400 0000 0000 d942 bb6b 0000 0000 020d  .......B.k......
000000c0: 02fd 0000 0009 0002 0000 00ee 00c8 025a  ...............Z
000000d0: 000f ffd5 020d 0001 0000 0023 0000 0000  ...........#....
000000e0: 0700 1800 0200 2800 0300 0100 0000 0000  ......(.........
000000f0: 0000 0000 0000 0000 0200 04ff 4102 5800  ............A.X.
00000100: 0700 0002 7c79 7c7c 7c8a 0258 00ff 8000  ....|y|||..X....
00000110: 017c 7c7c 7c8a 0258 004b 0226 030b 0063  .||||..X.K.&...c
00000120: ee5e 003f 0142 0000 020b 0500 1000 0047  .^.?.B.........G
00000130: 4f4f 4701 4000 00fb 0104 2dfe db00 0004  OOG.@.....-.....
00000140: 2d01 2500 0001 9ef1 0000 0002 1802 ca00  -.%.............
00000150: 0000 2000 0401 f400 3202 3c00 3801 2000  .. .....2.<.8. .
00000160: 0f01 0200 4e02 5a00 0f00 0001 0000 00f4  ....N.Z.........
00000170: ffff ff0c 0000 0000 003d 0066 0069 fb01  .........=.f.i..
00000180: ffff 0000 ffc4 ff9c ff9a 05f2 0001 0000  ................
00000190: 0000 0000 0000 0000 0000 f39e 000d 0020  ............... 
000001a0: 0032 0000 01c2 1220 6403 0000 3311 2111  .2..... d...3.!.
000001b0: 3201 9002 eefd 1200 0002 0038 00d9 0202  2..........8....
000001c0: 01e7 0003 0007 0000 1335 2115 f135 2115  .........5!..5!.
000001d0: 3801 cafe 3601 ca01 a047 47c7 4747 0001  8...6....GG.GG..
000001e0: 000f 0000 0183 02fd 0017 0000 011e 1123  ...............#
000001f0: 1123 3500 0200 0033 3216 1707 2626 2322  .#5....32...&&#"
00000200: 0615 1533 014c 8758 5e5e 5c52 2035 1317  ...3.L.X^^\R 5..
00000210: 102a 162c 2b87 01d4 f12c 01bc 291e 1f68  .*.,+....,..)..h
00000220: 5b0b 0745 050a 2443 2300 0002 004e 0000  [..E..$C#....N..
00000230: 00ad 02e1 000b 000f 0000 1332 1615 1406  ...........2....
00000240: 2322 9c00 0000 3668 6865 6106 6b01 0900  #"....6hhea.k...
00000250: 0000 d400 0000 2468 6d74 781c 1d1b c9fd  ......$hmtx.....
00000260: e802 1800 11ff fc0f 0000 020d 02fd 0026  ...............&
00000270: 0002 0000 0007 0003 0158 0000 0001 0000  .........X......
00000280: 0000 0000 0000 0006 0005 0100 0000 0000  ................
00000290: 0000 0700 0000 2000 4900 4c42 c000 0301  ...... .I.LB....
000002a0: 0207 662b 7370 6163 65                   ..f+space
```

Either this falls under [#D1](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D1) if it came from a fuzzer or it falls under "crashing is the correct thing to do because this file is obviously erroneous".
