### ISSUE TITLE
Open a font file with Fontforge

### ISSUE THREAD

**Issue by egfontforgeA** [fontforge/fontforge#4726]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
If you start FontForge without a command-line argument you should initially see a file "chooser" that lets you open an existing file or a blank, new font with its "New" button. Otherwise you should be able to open an existing font by choosing "File -> Open" from the menu. 

If you're seeing the chooser dialog but it has no fonts listed there are two potential problems:

1. FontForge has opened an initial directory that doesn't contain any fonts. In this case you need to "navigate" to the right directory. The button that looks like a house should switch to your user ("home") directory and the up-arrow should move up a directory. clicking on a directory/folder will move down into it.
2. It's possible the font you want to edit isn't supported by FontForge, or has a file extension that FontForge doesn't recognize. If that's the case start by confirming you've selected the right directory in the dialog and come back to update this issue and we can help you further.

**Comment by skef** [comment]
Do you need further help with this?

**Comment by egfontforgeA** [comment]
Thanks for responding, but my issue is still not resolved. 
   I tried things.
  For my project, I need everything to work on at least 2 systems, either Microsoft and Linux, (That would be good for Mac too, but I don't know this OS at all) because I will have to check compatibility with keyboards later (AZERTY QWERTY AZERTY PLUS and Bépo ...) both with Windows and with Linux and make it accessible to as many people as possible. 
  I work with W10 and Linux Mint in dual boot. 

  I opened Fontforge in the same way in Linux with, as for in W10, the empty command bar. 

  As I was not understanding why the Fontforge explorer did not show me any path allowing me to access the font Liberation Serif, I looked for and found the Linux Mint font manager, inside it I have searched for the Liberation family and found Liberation Serif (normal). Below we can display the file path of this font in detailed development. So I copied this address and pasted it into the Fontforge command bar and clicked OK. Finally, I had the glyphs window of the desired font which appeared, while with the New font button, we get this glyphs window, certainly, but empty. 

  I looked for a way to find the path in the same way on W10, using online Windows help because there is nothing in the local help to answer this question. The specified path is Start> Settings> Personalization> fonts. Once opened this file I found this font which I already knew was installed, and therefore that the problem did not come from there. The path shown is as follows: 
         C:\WINDOWS\FONTS\LIBERATIONSERIF-REGULAR.TTF
   But when I paste this address into the Fontforge command bar, my response is that this font does not exist. 
  So it is still impossible for me to display the glyphs window relating to Liberation Serif, which is important to me, as my job is to use this particular font a lot. I intend to try with other fonts to see if Fontforge opens them (Times new novel for example), but Liberation Serif is essential to me ... 

  Other: When you mention File> Open, I don't understand because no line or tile indicates that in my version (french Fichier> Ouvrir), it doesn't exist?

   Thank you for your attention, I hope to have the pleasure of reading you again

**Comment by egfontforgeA** [comment]
Right now I tried with that path : C:\WINDOWS\FONTS\TIMES.TTF
It works, the window of glyphes Times new roamn display

**Comment by egfontforgeA** [comment]
Trying and trying again I finally found a solution; with the good path that works with Times New roman but not with Liberation Serif, I have always (for this one) the same answer: This file doesn't exist, but in the bigger window with that comand appears the list of  all the fonts like in a writing software in the bar of the current font, so  I was able to scroll through the different fonts , find Liberation serif Regular select it and finally open the good glyph window ...
Thank you for your attention anyway, maybe (I think it's sure) I 'll have other questions in the future
bye

**Comment by ctrlcctrlv** [comment]
I was barely able to understand your messages, but glad you got it sorted.
