### ISSUE TITLE
Is it necessary to create a font to start in an empty glyph window?

### ISSUE THREAD

**Issue by egfontforgeA** [fontforge/fontforge#4735]
Good morning all,
   I created a font made directly in fontforge.
   My problem is that after generating this font for testing,
after installing it seems to be successful on Windows 10, there is no change in the texts I type with my text apps 
(Libre Office or Open Office).
   Yet in the font preview window, my new or transformed glyphs appear, but when I type my text, it's as if they don't exist, it's the original letters of Liberation Serif that are written ...
I saved my font as .ttf and .otf, that doesn't change anything.

   I would point out that having only a few glyphs to edit, I worked from the start from the glyph window in a copy of the Liberation Serif font, as most of the letters and other signs were not intended for change shape in this project.

   I then ask myself this question: Should I start my project in an empty glyphs window?
What makes me ask this question is that in my attempts to install my font, from the viewport, Windows always sends me back to the Liberation Serif font telling me that it already exists and asking if I want to replace it, although I gave different names to my files of transformed font generated…?

   Another side question: It seems that the copy pasted does not work from a glyph window (the one of Liberation serif) to another glyph window (the empty one of a new font), so how to import existing glyphs internally, au even within Fontforge so as not to have to redo all the glyphs?

   This last operation may seem easy for many of you, but it is very complicated for me, so thank you for your help
Goodbye

**Comment by iterumllc** [comment]
The fontforge-users mailing list would be a better place to ask general questions. https://sourceforge.net/projects/fontforge/lists/fontforge-users

Copy-paste generally works when both windows are part of the same running program. To do it don't start both instances from the icon, start one that way and the other from File -> Open or File -> new.
