### ISSUE TITLE
[feature request] generate a PDF report with all the glyphs in a font-file

### ISSUE THREAD

**Issue by eladkarako** [fontforge/fontforge#4740]
<img src="https://github.com/eugmes/fntsample/raw/master/screenshot.png" />

there are several "scripts" to analyse and generate such PDFs,  
https://github.com/eugmes/fntsample and https://github.com/googlefonts/fontreport 
(both are dependencies-heavy). 
Having an option to "export to PDF" or "generate a PDF report" feels natural for FontForge to have as a built-in feature.

(I am, however, perfectly fine with any alternative anyone might know of, FontForge-scripting alone or with just few of external 3rd-party-tools is preferred).

example PDFs: <a href="https://github.com/googlefonts/fontreport/blob/main/examples/malayalam.pdf">https://github.com/googlefonts/fontreport/blob/main/examples/malayalam.pdf</a>,  
<a href="https://github.com/bBoxType/FiraGO/raw/master/Technical%20Report%20PDF/Technical_Report_FiraGO.pdf">https://github.com/bBoxType/FiraGO/raw/master/Technical%20Report%20PDF/Technical_Report_FiraGO.pdf</a>
<br/>

<sub>

<details><summary>When you open an issue for a change/improvement/feature request:</summary>
<br/>

- [x] Screenshot
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround

</details>

</sub>

**Comment by jtanx** [comment]
Have you tried the Print option?

**Comment by eladkarako** [comment]
<details><summary>ver</summary>
<pre>
FontForge Windows build (64-bit)
Thu, Aug  1, 2019 10:03:15 AM +0000
09e9429f765698a57ce1f7751977533f0ed2ec67 [HEAD]
Based on master: ac635b818e38ddb8e7e2e1057330a32b4e25476e
</pre>
</details>

> Have you tried the Print option?

yes, the file-print main menu as a dialog two tabs, "display" (demo) and again "print" which I guess should have some sort of glyph-table. but the result is always empty (and very simplistic), regardless the font-file I'm loading.

![2021-05-24_233057](https://user-images.githubusercontent.com/415238/119404556-a2851f80-bce8-11eb-8713-7e1934080d3e.jpg)

![2021-05-24_232959](https://user-images.githubusercontent.com/415238/119404545-a153f280-bce8-11eb-8af4-70316e3eca9e.jpg)

neither seems to be too helpful..

**Comment by ctrlcctrlv** [comment]
Why is it starting at U+101C0? That's not a valid Unicode character, it should be empty.

**Comment by eladkarako** [comment]
> Why 

<h3><code>¯\_(ツ)_/¯</code></h3>
