### ISSUE TITLE
"Could not launch FontForge (exit code 255)."

### ISSUE THREAD

**Issue by ge3224** [fontforge/fontforge#4747]
Windows FontForge installation cannot launch.

* A similar issue was raised and closed ([#2954](https://github.com/fontforge/fontforge/issues/2954)), but it does not provide any information regarding a solution.

- [x] ran the installer `FontForge-2020-11-07-Windows.exe` as Administrative User
- [x] Microsoft Windows Build 19041.985
- [x] The FontForge program itself `C:\Program Files (x86)\FontForgeBuilds\run_fontforge.exe` is being run as Administrative User
- [x] ![image](https://user-images.githubusercontent.com/75739874/121244792-edfd0900-c864-11eb-82c1-ba4881a5ce3c.png)

**Comment by JoesCat** [comment]
Not all scripts are thoroughly debugged for spaces, quotes (and generally all the chars of the top row of the keyboard). Instead of installing Fontforge in:
"C:\Program Files (x86)\FontForgeBuilds"

see if this resolves it, try install FontForge in:
C:\PROGRA~1\FontForgeBuilds

**Comment by jtanx** [comment]
Yeah, it's not that.

Can you launch this:
![image](https://user-images.githubusercontent.com/5137410/121323666-5aeecc80-c953-11eb-92ce-5eaa5d6a1efc.png)


Then run 
![image](https://user-images.githubusercontent.com/5137410/121323720-693ce880-c953-11eb-82c3-a101a9a463bc.png)

And screenshot any errors, if any?

**Comment by ge3224** [comment]
When I attempt to launch, nothing appears to happen...
![image](https://user-images.githubusercontent.com/75739874/121361870-44b52200-c8fb-11eb-83ad-020b59fb253f.png)

When I try to run the BAT file, I get ...
![image](https://user-images.githubusercontent.com/75739874/121365509-52b87200-c8fe-11eb-8b2d-3ea9afa41d32.png)

**Comment by ctrlcctrlv** [comment]
`\Vim\vim82`? That's really strange. That shouldn't be happening. Why would we even distribute vim with FontForge? Do we even? :thinking:

**Comment by jtanx** [comment]
We don't. In `fontforge.bat`, can you change the first line to be `@echo on`?

**Comment by ge3224** [comment]
With @echo on, it ends with $Env:Path, which includes Vim.

```
C:\Program Files (x86)\FontForgeBuilds>set "FF=C:\Program Files (x86)\FontForgeBuilds\" 

C:\Program Files (x86)\FontForgeBuilds>set "HOME=C:\Program Files (x86)\FontForgeBuilds\" 

C:\Program Files (x86)\FontForgeBuilds>set "PYTHONHOME=C:\Program Files (x86)\FontForgeBuilds\" 

C:\Program Files (x86)\FontForgeBuilds>set AUTOTRACE=potrace 
C:\Program Files (x86)\FontForgeBuilds>set "PATH=C:\Program Files (x86)\FontForgeBuilds\;C:\Program Files (x86)\FontForgeBuilds\\bin; ... C:\Program Files (x86)\Vim\vim82; ... "

```

**Comment by ctrlcctrlv** [comment]
I think your `PATH` variable's syntax is bad. If I'm right, a bunch of scripts won't work, not only FontForge. Post the whole value of `PATH`.

**Comment by ge3224** [comment]
I fixed my `PATH` variables and everything is working now. Thanks. 

![image](https://user-images.githubusercontent.com/75739874/121456728-20455e00-c96c-11eb-836a-8f2738ce96da.png)
