### ISSUE TITLE
Tool Palette Missing, and Tool Menu not available

### ISSUE THREAD

**Issue by hwarwick** [fontforge/fontforge#4755]
My Tool palette has disappeared. The Tools Menu is greyed out and nonfunctioning. I have no idea how this happened, and I'm dead in the water with a huge pile of things to do and FontForge isn't working.

### When reporting a bug/issue:
- [x ] The FontForge version
  the most recent as of 14 JUNE 2021
 and the operating system you're using
 Windows 10
- [x ] The behavior you expect to see, 
That my tool palette be visible and available and that the Tools menu be available and not greyed out.

- and the actual behavior
The tool palette is nowhere to be found, I have no idea how to get it back, and the Tools Menu is greyed out and not available or working.

- [x ] Steps to reproduce the behavior 
No idea. I was working on a font when it just stopped working.

- [x ] \(optional) Possible solution/fix/workaround
None.

HELP!!!!!

![Capture](https://user-images.githubusercontent.com/86036504/122330710-aaa83780-cf01-11eb-9e7b-e8f1db704934.JPG)

**Comment by iterumllc** [comment]
First, the tools menu has little to do with the palettes. It lists "menu items" registered by whatever python scripts you have installed.

Given the symptoms the most likely issue is that (in a CharView window) View -> Show -> Palettes -> Tools has somehow gotten unchecked. You likely want everything ("Tools", "Layers", and "Docked Palettes") checked.

**Comment by hwarwick** [comment]
Hi!
Thanks for your fast reply! I really appreciate it. I looked there, and yes, all that is now checked. The only thing not visible is the Tools Menu. I realise that it requires python scripts to be installed, and IIRC, I had some installed. But suddenly they're not there anymore? Too weird. And how all that stuff got "unchecked" I have no idea. Sigh. But now I can get back to work.  
Cheers!
H
