### ISSUE TITLE
question about select functions in fontforge script

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4758]
Hi
I'm trying to select all spline glyphs from a selected range, sth like this:
`Select(0u0621,0uFECF).SelectGlyphsSplines()`
i couldn't do that...
also i don't know how to save a selection (without using colors) as a series of glyph names...

**Comment by skef** [comment]
There's no "boolean" interface to `SelectGlyphsSplines()`, it just resets the selection to every glyph with splines. 

I think what you want is equivalent to.

```
SelectGlyphsSplines()
SelectFewer(0u0001, 0u0620, 0uFED0, 0uFFFF)
```

But I haven't tested that. 

A [foreach](https://fontforge.org/docs/scripting/scripting.html#example-1) loop will iterate through the selected glyphs. Passing "Name" to [GlyphInfo](https://fontforge.org/docs/scripting/scripting-alpha.html#GlyphInfo) will retrieve the name as a string. Outputting strings is a matter of `Print` or `WriteStringToFile`.

**Comment by aminabedi68** [comment]
Thank you @skef 
it's working in GUI Unicode full view (to work in compact view, glyphs written in the SelectFewer should be in the compact view)
about the foreach loop, I need to try but i think i got it 👍
