### ISSUE TITLE
[AppImage] Core python package 'pkg_resources' not found

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge#4761]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
  ![pic.1](https://i.imgur.com/pg91CUO.png)
- [x] The FontForge version and the operating system you're using
  - Version: `FontForge-2021-07-01-d5593d0-x86_64.AppImage`
  - OS: `Debian 10.x buster`
- [x] The behavior you expect to see, and the actual behavior
  - There should be no missing files inside AppImage.
- [x] Steps to reproduce the behavior
  1. Download latest nightly AppImage build;
  2. Launch it;
  3. See "Warnings" on startup.
- [x] \(optional) Possible solution/fix/workaround
  - Bundle needed Python package  `pkg_resources` into AppImage builds.

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by davewood** [comment]
I experienced the same problem with debian bookworm just now.
