### ISSUE TITLE
question about a scripting example in fontforge

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4766]
hi
i tried to do that in many ways but i couldn't pass the copy paste:
```python
import os
import fontforge as ff

a = ff.open("Pinar-light.sfd")
for glyph in a.glyphs() :
 if glyph.color == 0x00ffff : #select all glyphs with cyan color
  glyph.clear()
  a[glyph.layers['Back']].copy() #copy all contours of background layer
  a[glyph.layers['Fore']].past() #paste copied contours in foreground layer
 glyph.right_side_bearing += 2048 #increase the horizontal width of the glyph
a.save()

```

Trackback:
```
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2020-11-07 21:17 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: f8bbd68cb29e31eba3215894ae4124a8ecdc2033
a.py:12: DeprecationWarning: an integer is required (got type float).
Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  glyph.right_side_bearing += 2048
Traceback (most recent call last):
  File "a.py", line 10, in <module>
    a[glyph.layers['Back']].copy() #copy contours of background layer
TypeError: Index must be an integer or a string
```
i think the error related to the content of the bracket in ```a[...].copy()``` and i can't resolve it.
also i've tried ```glyph.background``` and ```glyph.layer_0``` in many other ways but i got some other errors.

**Comment by skef** [comment]
Can you describe in a few sentences what the script is intended to do?

**Comment by aminabedi68** [comment]
This is an incompleted code witch is a part of build script of a variable font, so it's not reasonable yet.
I need to clear cyan color tagged glyphs, copy contours stored in the background layers of these glyphs and paste them to the foreground layer.

**Comment by skef** [comment]
The font selection `copy` and `paste` methods work at the glyph level, which is higher-level than what you want here.

I would start by replacing the three lines inside the `if` condition with:
```
    glyph.setLayer(glyph.layers['Back'], 'Fore')
```
There's no need to `clear` because setting the foreground layer to new contents gets rid of the old contents.

**Comment by aminabedi68** [comment]
yes, it works! :) thank you 👍
how you realized that? i couldn't find `setLayer` [here](https://fontforge.org/docs/scripting/scripting-alpha.html), also i checked [here](https://www.iro.umontreal.ca/~boyer/typophile/doc/scripting.html) and [here](http://dmtr.org/ff.php)

**Comment by skef** [comment]
This is the current definitive python scripting doc https://fontforge.org/docs/scripting/python/fontforge.html#glyph

**Comment by aminabedi68** [comment]
Hmmm... yes. going to dig in :) thank you @skef
