### ISSUE TITLE
Import another kern (GPOS) table

### ISSUE THREAD

**Issue by SENSIB0I** [fontforge/fontforge#4768]
Hello, 
I want to import another kern table at font properties but the button is disabled. Can't find any solution on internet.

I downloaded and installed FontForge yesterday.

![image](https://user-images.githubusercontent.com/51211360/124649369-ad5ed280-de98-11eb-8f53-c3d325065afe.png)

I saved to file the actual one, rewrited it in notepad and wants to import and then join them.

**Comment by aminabedi68** [comment]
if you want to "import" a kerning table, you should open another font from current fontforge menu: file >> open , then you can use "import" button to import another lookup from the secound font.

**Comment by SENSIB0I** [comment]
What about importing file that's not included in another font? 
I prepared file like this and wants to use these rules.

It's a file that I exported from current font and made some changes to the letters that it don't supported.

![image](https://user-images.githubusercontent.com/51211360/124788734-eefb8600-df49-11eb-89da-b9ca9ce4e57e.png)

**Comment by aminabedi68** [comment]
use file >> Merge Feature Info...

**Comment by SENSIB0I** [comment]
Thanks you, 
It was problematic for me because the translation doesn't make sense sometimes as I use my native language.
