### ISSUE TITLE
Cannot generate bitmap fonts

### ISSUE THREAD

**Issue by joshuakraemer** [fontforge/fontforge#4779]
When I try to generate a bitmap font, I get an error message about missing bitmaps. With BDF chosen as the output format, the error message is:

> Attempt to save a pixel size that has not been created (30@0)

With OTB, the error message is:

> The font database does not contain a bitmap of size 30 and depth 0

This is the same for existing and newly created bitmap fonts.

Fontforge versions tested: 20201107 and 21b5a6e65c5f3fb526615d02560640a10face615 on Void Linux

**Comment by jtanx** [comment]
Do you have a sample font for exact steps to reproduce? I can't repro this.

**Comment by ctrlcctrlv** [comment]
Clearly at least some bitmap fonts can be generated, otherwise [`bitmapfont2otb`](https://github.com/ctrlcctrlv/bitmapfont2otb) wouldn’t work at all.

**Comment by joshuakraemer** [comment]
Exact steps to reproduce:

- Download https://cgit.freedesktop.org/xorg/font/adobe-75dpi/plain/helvR12.bdf
- Open with Fontforge
- Click "File > Generate Fonts..."
- Chose "No Outline Font" and "BDF" as output formats
- Click "Generate"
- Click "OK" to accept 75 dpi
- Error message appears

![error](https://user-images.githubusercontent.com/10373011/126864406-b92b0186-0f75-4091-b9cd-fc7127467167.png)

However, the following command works as expected:
```
fontforge -c 'font = fontforge.open("helvR12.bdf"); font.generate("HelveticaMedium-*.bdf")'
```

**Comment by jtanx** [comment]
The screenshot was helpful, thanks - I can reproduce this if I set `LANGUAGE=de`
