### ISSUE TITLE
SplineCharDefaultNextCP and SplineCharDefaultPrevCP do not produce handles anymore

### ISSUE THREAD

**Issue by linusromer** [fontforge/fontforge#4787]
When drawing a spline with smooth points the current github version of FontForge produces a spline that is not smooth at all (upper part of the following picture). However, it used to produce something like the lower part of the following picture:
![fferror](https://user-images.githubusercontent.com/11213578/128070161-66de72bd-ce3f-43ce-be21-99aef54d282c.png)
This must have happened in the past month, because my version on https://github.com/linusromer/fontforge from 1. july still works as it used to be. 
This issue may be related to [https://github.com/fontforge/fontforge/pull/4685](https://github.com/fontforge/fontforge/pull/4685).

**Comment by skef** [comment]
I'm too busy to look at this in any detail for quite some time but my guess is that the line https://github.com/fontforge/fontforge/pull/4685/commits/0f8fc11df7eaec55c75360db19494814d87ea33a#diff-78ff08502d7ca584fcdd8bc21ccc10e63b1eca0ed4406e0a1c8510b9e53a8712L3243 and its pair in `*DefaultPrevCP` was more substantive than I had realized in how it matches to  the change on (new line) 3385. I recommend putting something to match old line 3243/new line 3228 that actually alters the control point, such as setting `base->nextcp` to `base->me` + `unit`. It shouldn't matter *what* you set the nextcp to as long as it differs from `base.me`.

**Comment by linusromer** [comment]
@skef I can confirm that your suggestion fixes the issue.

**Comment by skef** [comment]
After thinking about this briefly a bit more it's probably more self-documenting to just maintain a function-local boolean in place of nonextcp to represent the need for the subsequent change. My suggestion works OK but is likely to mystify future developers (although maybe not with an appropriate comment?).

**Comment by linusromer** [comment]
You mean a function-local boolean that would replace `( base->prevcp.x!=base->me.x || base->prevcp.y!=base->me.y )` ? This is probably preferable, indeed.

**Comment by skef** [comment]
Yes -- checking the equality of ->prev/nextcp and ->me prior to calling SplineMake/Fixup is the general solution to the old nonextcp/noprevcp problems but in this case nonextcp was really being used as what amounted to a function-local boolean anyway. So better to just track that state with a local.
