### ISSUE TITLE
can you import glyphs from a font into different glyph places into new font

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4790]
I have fonts that were written all glyphs in the English glyph places. Now our language is supported in Unicode and the glyphs are assigned into way down in the glyph places. Do you have utility or import function that can read from old fonts and place them into appropriate places in Unicode? Thus creating a new font with glyphs are placed into assigned places into Unicode. Please help point me to such program or app out there so that it can be done properly and quickly. Thanks

**Comment by ctrlcctrlv** [comment]
You could probably do that with a FontForge script, yes, but you'd need to write it.

First you need to come up with a mapping from the ASCII codepoints to the Unicode codepoints, that would look something like:

```python3
MAP = {
  "A": 0x2828,
  "B": 0x2829,
  # …etc…
}
```

Then you need to…

```python3
import fontforge
import sys
font = fontforge.open(sys.argv[1])
for glyph in font.glyphs():
  glyph.unicode = MAP[glyph.unicode]
font.generate(…)
```

Not difficult.
