### ISSUE TITLE
Glyph image did not show in Metric/outline Windows but shown in Character Map App

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4792]
I don't know what I did wrong or forgot to set the setting some where, but the glyph image is not showing completely in Metric or Outline Windows.
But it shows every characters with dotted circles in Character Map in Windows. See the photo.
![Image Missing](https://user-images.githubusercontent.com/73824794/130269394-4e0a7835-cb34-42c2-ba62-dd26c41f3f28.jpg)

**Comment by Ilhamkang** [comment]
The dotted circle character will appear in any combining mark characters, even the glyph does not have the dotted circle. 

I think this is normal as we can read from the [Unicode Standard](https://www.unicode.org/versions/Unicode6.2.0/ch17.pdf. ).
![image](https://user-images.githubusercontent.com/22653757/130476498-ae8baccd-ee11-4e4c-a261-ac20ab8c5181.png)

**Comment by ctrlcctrlv** [comment]
Indeed, totally normal and expected behavior.

**Comment by waykyi** [comment]
Thank everyone. This explained it very well. So, this is Mark feature or Combining feature? I know Mark & Ligature, but not sure I know anything about Combining. Is this similar to Ligature? Thanks
