### ISSUE TITLE
how to set ttf font bold version parameters correctly for grouping in Illustrator

### ISSUE THREAD

**Issue by meeotch** [fontforge/fontforge#4803]
- [X] The FontForge version and the operating system you're using - 20201107, Windows 10

- [X] The behavior you expect to see, and the actual behavior
I've got a TTF font (call it Myfont), and have created a bold version for it using FF's Change Weight function.  I'm now trying to generate the bold font TTF file such that the two styles show up correctly in Illustrator as a single font with two styles.

- [X] Steps to reproduce the behavior 

If I give the bold version a different Family Name in the PS Names tab, both will install in Windows, and both will show up in Illustrator, but as separate fonts.  

I compared the existing files for Calibri regular and bold in FF, and in the PS Names tab, I see that three fields differ:
- Fontname (Calibri & Calibri-Bold)
- Name for Humans (Calibri & Calibri Bold)
- Weight (Book & Bold)

In the TTF Names tab, I see three differences:
- Fullname (Calibri & Calibri Bold)
- Unique ID (Microsoft: Calibri & Microsoft: Calibri Bold)
- Styles SubFamily (Regular & Bold)

In the OS/2 tab, one difference:  Weight Class (400 Regular & 700 Bold)

I have adjusted all of the above parameters in my bold custom font so that the values are analogous, using the info from the original font from which I created the bold one.

When I drag & drop the two TTF files into the Windows/Fonts folder, they appear to correctly install, and show up as a group ("stack of paper" icon).

However, when I go into Illustrator, only the regular version shows up, and the Styles menu shows only Regular as a choice.  The bold version is nowhere to be found.

- [X] \(optional) Possible solution/fix/workaround

I can install as two separate fonts, as mentioned above, by giving them different Fontnames.  But that's not what I'm trying to achieve.

**Comment by meeotch** [comment]
UPDATE: after some more fiddling, I seem to have fixed it. The original font had all of its OS/2 "Panose" settings (except Family Kind) set to the default "Any".

Setting the bold font Panose Weight to "Bold" seems to have allowed Illustrator to correctly display it as a Style of the original font.

At this point, I'm not sure which of the settings in the original post are relevant, but it works.

**Comment by ctrlcctrlv** [comment]
Noted.
