### ISSUE TITLE
 Pip install fontforge, says Couldnot find a version

### ISSUE THREAD

**Issue by dingdingdeding** [fontforge/fontforge#4805]
Pip install fontforge, says Couldnot find a version

**Comment by jtanx** [comment]
We don't currently distribute fontforge via pip/pypi.

**Comment by dingdingdeding** [comment]
thanks for your reply, emm, how can i use fontforge dependency in my python?

**Comment by jtanx** [comment]
What is your OS?

**Comment by dingdingdeding** [comment]
windows and linux

**Comment by jtanx** [comment]
Windows -> use the python bundled with the installer, Linux, install the package provided by your

**Comment by dingdingdeding** [comment]
where can i down the file

**Comment by dingdingdeding** [comment]
thanks，let me try
