### ISSUE TITLE
MATH Info window gets unnecessarily tall

### ISSUE THREAD

**Issue by DavidFangWJ** [fontforge/fontforge#4806]
I am using FontForge 20190801 distributed with Ubuntu 20.04 LTS. When I try to edit the italic correction for newly added glyphs, the MATH info window gets so tall that even buttons like "OK" or "cancel" becomes invisible. Since there is no option for the default size of MATH info window either under `~/.config/fontforge/prefs` or in the .sfd file, I am now unable to complete my work for the font.
![2021-09-09 16-28-56屏幕截图](https://user-images.githubusercontent.com/34878339/132758070-603c9cf2-0584-4e56-ae53-6e024ec9a6c8.png)

**Comment by DavidFangWJ** [comment]
Update: Fontforge 20201107 from [fontforge.github.io](url) exhibit the same behavior.

**Comment by skef** [comment]
Obviously this is undesirable in general, but as a work-around is it possible to resize the dialog by dragging the top of the title bar down, and then to move the window up by dragging the middle of the title bar up? It looks like this is an initial-window-size bug and things might still work if you can make the window shorter.

**Comment by DavidFangWJ** [comment]
> Obviously this is undesirable in general, but as a work-around is it possible to resize the dialog by dragging the top of the title bar down, and then to move the window up by dragging the middle of the title bar up? It looks like this is an initial-window-size bug and things might still work if you can make the window shorter.

Unfortunately the menu the window is defined to be fixed-size for some reason, so the shrinking would make buttons "OK" and "Cancel" invisible.
![2021-09-09 17-47-19屏幕截图](https://user-images.githubusercontent.com/34878339/132767017-d42d385a-2acb-4929-903b-a0d0b0c53af2.png)

**Comment by skef** [comment]
Oh, right -- that makes sense given how the layout works for this dialog. 

Given that the math table scrolls and the bar is visibly scroll-able its not likely to be the cause of this widget sizing issue. Could you go through all of the tabs to see if there's one that looks more likely to be causing the problem? Basically something that's tall but you wouldn't necessarily expect to be tall? It could be any of the tabs.

**Comment by DavidFangWJ** [comment]
I believe it is related to the "Vertical variants" table. For consistency with an unknown font (used in reference glyph display), I put the vertical variants of brackets into the range U+10Fxxx, but it made each line of the Vertical Variants table several times than what it should be.
![2021-09-09 20-04-28屏幕截图](https://user-images.githubusercontent.com/34878339/132777969-256e7d6e-05bc-415d-8938-d82e945fec08.png)

**Comment by skef** [comment]
@DavidFangWJ that's possible but that list also scrolls, so it's still less likely to be the cause. Are there any other tabs that take up the whole window but don't have a scroll bar?

**Comment by DavidFangWJ** [comment]
> @DavidFangWJ that's possible but that list also scrolls, so it's still less likely to be the cause. Are there any other tabs that take up the whole window but don't have a scroll bar?

No.

**Comment by skef** [comment]
No idea then. We'd probably need the font (or a "reduced" example with the same symptom) to diagnose. If you're comfortable posting that here in a zip that would work, otherwise there is probably a confidential back-channel (I don't normally handle that sort of thing).

**Comment by DavidFangWJ** [comment]
[OriSerif-Math.zip](https://github.com/fontforge/fontforge/files/7140606/OriSerif-Math.zip)

**Comment by ctrlcctrlv** [comment]
I can't duplicate, which might tell us something.

![image](https://user-images.githubusercontent.com/838783/132786903-bd704205-9481-4a2b-9aa9-5a25f792986e.png)

My Vertical Variants tab looks like this:

![image](https://user-images.githubusercontent.com/838783/132787083-5e130612-6349-4ad4-bd02-8a3814f47743.png)

I don't have the font actually installed, though.

I believe your problem is because you have the font installed, and no other font is using U+10FF31, etc.

**Comment by skef** [comment]
> I believe it is related to the "Vertical variants" table. For consistency with an unknown font (used in reference glyph display), I put the vertical variants of brackets into the range U+10Fxxx, but it made each line of the Vertical Variants table several times than what it should be.

I now suspect @DavidFangWJ is right about this, and that there is some interaction between the window size calculation and the scrolling calculation such that the code wants to fit a certain number of lines, or is sizing based on a certain number of lines, and the fact that a given line is much larger is causing the problem. Note that I haven't looked at any code, however; this is just a guess.

**Comment by DavidFangWJ** [comment]
> I now suspect @DavidFangWJ is right about this, and that there is some interaction between the window size calculation and the scrolling calculation such that the code wants to fit a certain number of lines, or is sizing based on a certain number of lines, and the fact that a given line is much larger is causing the problem. Note that I haven't looked at any code, however; this is just a guess.

The problem is now solved through @skef 's guess, by changing the unicode values of all extended shape characters to -1.
