### ISSUE TITLE
I have pasted an image to the glyph and when i close the editing window the box doesnt have a X but its white

### ISSUE THREAD

**Issue by KingOfTNT10** [fontforge/fontforge#4807]
title ^

**Comment by ctrlcctrlv** [comment]
Not a bug?

**Comment by skef** [comment]
Support for images in FontForge (as opposed to bitmaps in the Bitmap viewer) are for tracing. The lack of an X indicates there is some data for the glyph. The lack of any content indicates there are no contours.
