### ISSUE TITLE
wasm binding

### ISSUE THREAD

**Issue by jimmywarting** [fontforge/fontforge#4812]
I would like to use fontforge with scripting in the browser.

I have not much knowledge of wasm or c
but is it possible for you to compile to some wasm version for us to use in the browser?

**Comment by jtanx** [comment]
not at this stage no.

**Comment by lancejpollard** [comment]
Mind explaining why not? I am in the same boat :)

**Comment by warting** [comment]
For everyone needing it in browser, add feature requests here: https://github.com/premex-ab/fontforge-wasm
