### ISSUE TITLE
genericGlyphChange vMap - always results in TypeError or Segmentation fault

### ISSUE THREAD

**Issue by aiongg** [fontforge/fontforge#4815]
- [x] The FontForge version and the operating system you're using

Version: 20201107
 Based on sources from 2021-09-23 03:40 UTC-D.
 Based on source from git with hash: 21ad4a18fb3d4becfe566d8215eba4483b0ddc4b

Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux

- [x] The behavior you expect to see, and the actual behavior

Calling `genericGlyphChange` with a `vMap` keyword argument always causes either a TypeError with the message: `TypeError: vMap should be a tuple (or some other sequence type).` or a segmentation fault.

- [x] Steps to reproduce the behavior 

Open any font and try to run the `genericGlyphChange` function using a `vMap` argument:

```
>>> import fontforge
>>> f = fontforge.open('/path/to/anyfont')
>>> f['a'].genericGlyphChange( stemScale=1, hCounterScale=1, vMap=((300, 50, 200)) )
Segmentation fault
```

Or running the above as a script:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    f['a'].genericGlyphChange( stemScale=1, hCounterScale=1, vMap=((300, 50, 200)) )
TypeError: vMap should be a tuple (or some other sequence type).
```

-[ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
Not relevant to the problem but remember that you'll need to do "((300, 50, 200),)" to make a singleton three-tuple.
