### ISSUE TITLE
Can not change FG color of non-selected characters in main view

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge#4819]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
  ![Screenshot_2021-09-25_15-46-21](https://user-images.githubusercontent.com/13188580/134773496-dc901325-5511-4147-8c45-59ae9b13ecc1.png)
- [x] **The FontForge version and the operating system you're using:**
  `FontForge-2021-09-19-7ac72df-x86_64.AppImage`
- [x] **The behavior you expect to see, and the actual behavior:**
  There should be an option to change FG color of non-selected characters in main view (i.e. `FontView`), which by default it is "black"/`#000000`.
- [ ] Steps to reproduce the behavior 
- [x] \(optional) **Possible solution/fix/workaround:**
  In *"X Resource Editor > View"* there is only *"Background"* color option, but there should be a "Foreground" color option too for show fill of non-selected character in main window (i.e. `FontView`).

> **NOTE:** This issue is about overall foreground, which is differ from single char view (as mentioned in https://github.com/fontforge/fontforge/issues/3141)

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
This should/will be fixed by #4704, if;when it winds up being merged.

**Comment by Symbian9** [comment]
> This should/will be fixed by #4704

OK, hope it would be merged now.

Closing this as duplicate of #4391
