### ISSUE TITLE
Malware / security alert

### ISSUE THREAD

**Issue by valentinefreeman** [fontforge/fontforge#4821]
Donated and downloaded for the first time today and my Mac will not open because it can't verify the app doesn't contain malware... help?

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
Duplicate of #4082. `FontForge.dmg` is not “notarized” or built with a paid Apple Developer account, thus this warning. That issue contains instructions for running it anyway.
