### ISSUE TITLE
How do I make CMD recognize my FON file?

### ISSUE THREAD

**Issue by ghost** [fontforge/fontforge#4822]
I've taken the font from [here](https://github.com/kmar/Sweet16Font) and because of the nature of ClearType rendering in Windows I had to convert the fonts to a bitmap format (FON) which makes perfect sense considering the font is 8x16 and is not to be of vector type.

The issue is the newly generated font does not appear inside the Command Prompts Properties/Font.

What steps are required to mark the fonts as "monospace" and to be usable inside Command Prompt?

There is a hack using the Registry Editor but its not reliable as the fonts change to vector-based if I open `nano` or `vim`.

**Comment by skef** [comment]
This question is more appropriate for the fontforge-users mailing list.
