### ISSUE TITLE
FontForge won't launch on MacOS Big Sur

### ISSUE THREAD

**Issue by CajunRover** [fontforge/fontforge#4824]
I am unable to launch FontForge on my iMac running MacOS Big Sur. I keep getting a message reading "Cannot open because the developer has not been verified." Allowing it in System Preferences merely results in no message at all and still no launch. Can anyone please help? Thank you, Matt Leger

**Comment by skef** [comment]
FontForge doesn't sign its Mac version because signing opens a big can of worms. It should still be possible to run the program however.

Try following the instructions further down the page at https://support.apple.com/en-us/HT202491 . If that doesn't work get back in touch.

**Comment by ctrlcctrlv** [comment]
Duplicate of #4082.

**Comment by CajunRover** [comment]
I have already tried following those instructions. FontForge still will not launch.
