### ISSUE TITLE
Can't find specific symbols like pi

### ISSUE THREAD

**Issue by PhoeNicZz** [fontforge/fontforge#4829]
### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
FontForge Version 20201107 + Windows
- [x] The behavior you expect to see, and the actual behavior
I was expecting a way to search for specific symbols but it's not there (or I can't find it)
- [x] Steps to reproduce the behavior 
Just try looking for one symbol specifically, there's so many that you'd sit there for ages..
- [x] \(optional) Possible solution/fix/workaround
Adding a context menu in which you can paste a symbol and then it'd take you to where it is in the roster.

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
From what I know you can't look for specific glyphs in the roster, and I think if you wanna fix specific symbols because they're broken in your font this would be helpful.
- [ ] If the feature changes current behavior, reasons why your solution is better
- [x] \(optional) Possible solution/fix/workaround
Adding a context menu in which you can paste a symbol and then it'd take you to where it is in the roster.

**Comment by ctrlcctrlv** [comment]
If the current encoding is an uncompacted Unicode encoding, you can use «View→Goto» (<kbd>Ctrl</kbd><kbd>&gt;</kbd>). It accepts Unicode values like `uni03c0` or AGL values like `pi`.
