### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by mkli13** [fontforge/fontforge#4830]
Hello my name is Marina.
I am a graphic designer and it is the first time that I got involved in fonts design.
I have downloaded the fontforge and I start learning.
I have windows 10.
When I open the software the the tools button is inactive.
Should I do something else?
Thanks in advance.
Marina

**Comment by skef** [comment]
The Tools menu contains entries added by scripts or (soon) plugins. If you have no custom scripts there won't be anything in the Tools menu, and it will be inactive. This is normal, you're not "missing" anything.
