### ISSUE TITLE
How can I get glyphs' names beyond 0x10000?

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#4831]
I tried with build in Save Name List and it did not include all glyphs names in the font. Any info is much appreciated. Thanks

**Comment by waykyi** [comment]
Yes, I put "\n" and got [error:](![new line](https://user-images.githubusercontent.com/73824794/137619559-2bea39cc-943a-4ebb-9c53-588f98838525.jpg))
myText = GCode + " = " + GName + "\n";
Without "\n", it write out ok, but no break or newline.
I only need to write a newline and I can't figure out. Thanks

**Comment by waykyi** [comment]
Here is the font --> https://drive.google.com/file/d/1FY2VD3P8rPREEZ25LC78MOuDQCXJec3F/view?usp=sharing

**Comment by waykyi** [comment]
> And even having more than one works. This bug is not confirmed, please share the broken font.
> 
> ```
> 0x10400 dsrt_longi
> 0x10401 dsrt_longe
> ```
> 
> See also [#D2](https://github.com/fontforge/fontforge/wiki/Community-guidelines#D2) regarding deprecated scripting language. You want Python function [`font.saveNamelist`](https://fontforge.org/docs/scripting/python/fontforge.html).

That is what I want exactly. But I don't know how to run Python in FF. Can you point me to the document about this. Thanks

**Comment by skef** [comment]
There is no equivalent method in the native scripting language. 

If you just want to run this in isolation you can do:

```
fontforge -lang=py -c "f = fontforge.open('Pyidaungsu.ttf'); f.saveNamelist('Pyidaungsu_list.txt')"
```

Otherwise you can write a script like:

```
f = fontforge.open('Pyidaungsu.ttf')
f.saveNamelist('Pyidaungsu_list.txt')
```

save it as "namelist.py", and run `fontforge -lang=py -script namelist.py`. That should get you started. The python documentation is at https://fontforge.org/docs/scripting/python.html .

**Comment by skef** [comment]
Oh, it looks like saveNameList only contains a subset of glyphs for whatever reason.

Try saving this in "namelist.py" and running it as `fontforge -lang=py -script namelist.py Pyidaungsu.ttf:`

```
import fontforge
import sys

f = fontforge.open(sys.argv[1])

for g in f.glyphs():
    if g.unicode == -1:
        print("[none] " + g.glyphname)
    else:
        print("0x%04X %s" % (g.unicode, g.glyphname))
```

**Comment by waykyi** [comment]
Sorry for late reply. Thank you very much for your complete answers. Thanks
