### ISSUE TITLE
how to generate a TTF use .png image

### ISSUE THREAD

**Issue by dagongji10** [fontforge/fontforge#4837]
I have 3755 images for all first-level chinese character, can I use fontforge(python module) to generate a TrueType font?
![image](https://user-images.githubusercontent.com/15357846/139048968-450c59f9-ca26-4c83-a99f-3315cd004376.png)
I can use OpenCV to extract contour of each image, and alse convert each image to SVG, but I have no idea about generate a font use them.

**Comment by skef** [comment]
It's definitely possible to import SVGs into FontForge and to generate a font. There are a lot of complicated questions relating to fonts and efficient generation (e.g. scripting to avoid having to import 3755 SVG files by hand), however, and this isn't a good place for them. You might try the fontforge-users mailing list: https://sourceforge.net/projects/fontforge/lists/fontforge-users
