### ISSUE TITLE
Generate a descriptive human-readable Change Log with every release

### ISSUE THREAD

**Issue by ultrasquid** [fontforge/fontforge#484]
This is something George when he released new binaries as seen on http://fontforge.org/changelog.html#change-log . As you can see, this has not been updated since last July. We know that there have been many changes since then but I don't know how to distill them down to a simple list like the change log from all the activity here on github. 

Of course, this raises the question of what constitutes a release in this context, given our seeming continuous development cycle. I propose the change log be amended no less frequently than monthly, regardless of what we consider a proper release.

**Comment by skef** [comment]
@frank-trampe lists the greatest hits, this would be a lot of work and interested parties can check the git commit log.
