### ISSUE TITLE
2021–2022 release

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4840]
We have gone a year without a release, so I suggest we make a release by year's end.

Edit: Issue pinned according to [#G2A](https://github.com/fontforge/fontforge/wiki/Community-guidelines#g2a-wish-lists).

**Comment by dimitre** [comment]
Hope it gets relesed soon. paths work well now and in the past, but not in the anniversary release. Unfortunately brew doesn't install from head anymore

**Comment by ctrlcctrlv** [comment]
@dimitre Yes agreed also #4704, #4671 (both by @skef) merit another release, besides many bugs since fixed.

**Comment by skef** [comment]
The big one is arguably #4642, which we keep forgetting about because its been so long since it was merged. i still hope to get #4682 merged soon. And #4789 by @linusromer would be a good addition.

**Comment by ctrlcctrlv** [comment]
Oh yes indeed @skef sorry you're right. I did totally forget about it. Sorry, don't plan to use it too too much, but I of course appreciate the work and will likely port at least https://github.com/ctrlcctrlv/bitmapfont2otb/ because I never plan to implement a BDF/PCF reader in MFEK, so FontForge is my long term solution to the bitmap font question. Maybe will port too https://github.com/ctrlcctrlv/QuickAnchors. You know, the work you did for `askMulti` made QuickAnchors actually viable to configure in GUI, which is cool.

**Comment by ctrlcctrlv** [comment]
Actually, this is probably an abomination but my tolerance for software abominations knows no bounds—is it supported in the new Python plugins support, calling external executables in PATH?

If so—I can add a hook for glyph opening and then call MFEKglif instead of opening a CharView. I could add a mode to MFEKglif called `remote-control`, where my Python code in FontForge would send it the metrics, and on exit read its stdout to get the glyph data.

Would this kind of plugin be ok with you?

**Comment by ctrlcctrlv** [comment]
I don't want to rehash old arguments with you about Tkinter so I'm saying here "forget it, I don't care about Tkinter anymore, but what about arbitrary forking of independent processes?"

**Comment by skef** [comment]
I have occasional opinions about how things I've written might or might not be *rewritten*, beyond what the relevant licence strictly allows. I think such opinions are fairly common, though (sorry to be cryptic).

The *use* of the plugin interface falls entirely outside of that. I don't think it's any of my business what plugins people choose to write (unless, of course, they happen to be rewriting my code somehow, which could fall into the other category). 

Would what you describe work? Obviously one problem is that, unless you plan to wrap up the program you want to start into a python package, you can't establish a programmatic dependency so your users will have to install the other program(s) themselves. Another is "I can add a hook for glyph opening" -- this is, in effect, a proposal to modularize FontForge itself which might or might not make it past review.

**Comment by ctrlcctrlv** [comment]
Modularizing FontForge is probably too radical a change, given recent trends in PR acceptance. Therefore, I would probably actually write a program that "attacks" FontForge by attaching a pseudo-debugger to it. But, it would use the breakpoints to monitor what user is doing and also read/write FontForge's memory without its knowledge… like how a lot of videogame "trainers" work.

So, I'd use this to stub the function `CharViewCreate` and then every time it's hit actually call my own code instead. And other functions. I'd also probably inject data into `ShowAboutScreen` so you would know if the injection succeeded.

Maybe I could call it `MFEKfontforge`, that'd be funny.

**Comment by ctrlcctrlv** [comment]
Note: When a new release is made, remember to close #4082. (_Cf._ https://github.com/fontforge/fontforge/issues/4082#issuecomment-1026467698)

**Comment by jtanx** [comment]
So given the outstanding PRs, I think it's pretty obvious that we're going to miss this date. I could still continue with the release though, it's plenty big as is and I don't think any of the remaining ones are critical. We can always cut another release say a month later. Thoughts?

**Comment by dimitre** [comment]
IMHO the release is more important than completing PRs. 
I've started using FF way back, in sourceforge days and grey interface and it was never so hard to make it work correctly as it is now.
A release will improve things greatly for the average user.

**Comment by iterumllc** [comment]
I would prefer not releasing the plugin interface without (most of?) the menu improvements to avoid having anyone interested in writing a plugin deal with differing menu options and versioning checks for years from now.

Why don't we give me next weekend to try to deal with the things I just updated and if I fail to do that a release can go out without it? If it get it pretty close we can discuss what else needs to be done.

**Comment by jtanx** [comment]
Yeah, I've pushed the milestone back by a week anyway, so happy to leave it till then to decide. Probably just don't want to continually keep pushing back though.

Having said that I am going to be pretty busy towards the end of this week but will try to facilitate the release as best I can.

**Comment by iterumllc** [comment]
Well, I'm talking about the 26th and 27th for me so if we do that I guess it would be first week in March as the target.

**Comment by ctrlcctrlv** [comment]
@jtanx I'm sorry I've been missing an action but I think you should include a few commits of mine in the release notes because they are at least under some definitions major

* #4434
* #4618
* #4629
* #4707

To be extremely clear, I'm not demanding you include all four of these, that's probably overkill, but to include none of them it seems "underkill", especially the ones that changed default behavior (UFO fix, RFN change) or added significant new functionality (sub by NULL).

Thanks...

**Comment by jtanx** [comment]
Feel free to edit the release notes

**Comment by ctrlcctrlv** [comment]
Thank you, sorry I did not participate in the release process this time, so am adding these notes late, I just think they will benefit people to know. I'm highlighting my changes because I don't see a way to show you what I changed in GitHub software.

![image18](https://user-images.githubusercontent.com/838783/158221127-a6a246d3-722d-46bd-9c73-97bbaa9900c4.png)
