### ISSUE TITLE
Where are CI/Actions artifacts? (AppImage, EXE, DMG)

### ISSUE THREAD

**Issue by Symbian9** [fontforge/fontforge#4857]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
At the bottom of eg https://github.com/fontforge/fontforge/actions/runs/1472683780

**Comment by Symbian9** [comment]
@jtanx, may you setup `nightly.link` GitHub app (https://github.com/apps/nightly-link) for FontForge's `master` branch & replace link to Actions builds with `nightl.link` on [*"FontForge  developer builds"* page on website](https://fontforge.org/en-US/downloads/dev/)?

nightly.link would allow users to get FontForge 'nightly' builds **without** login to GitHub (because **GitHub Actions assets are available only for logged users**)

For example, see:

- https://github.com/solvespace/solvespace/pull/1137
