### ISSUE TITLE
Simplify stroke makes horizontal lines into curves

### ISSUE THREAD

**Issue by NightFurySL2001** [fontforge/fontforge#4868]
I traced an bmp externally using `potrace` and imported the svg into FontForge. This is the svg:
![image](https://user-images.githubusercontent.com/33471049/147031822-4a8c4029-bc73-4a9b-a004-a06557401992.png)

However, if I run simplify glyph, the glyph will turn into this:
![image](https://user-images.githubusercontent.com/33471049/147031961-1cab88d7-ae3e-4258-8afd-899c9722808e.png)

This has massively bloated the file size and converted two straight line sections into one long curve. All options in the "Simplify more..." menu can avoid this issue.

sample svg: [cid09487.zip](https://github.com/fontforge/fontforge/files/7759860/cid09487.zip)

FontForge 20201107, Windows 10 21H1.

**Comment by ctrlcctrlv** [comment]
Ah yes. I too have experienced this, and it's why [bitmapfont2otb](https://github.com/ctrlcctrlv/bitmapfont2otb/) doesn't run FontForge's simplify anymore.

I've been waiting for there to be a good implementation of a path simplifier as a library…either in FontForge's C codebase or elsewhere…even tried commissioning one, but I don't really think @prajwalprabhu is getting anywhere (_Cf._ https://github.com/MFEK/math.rlib/pull/22)…despite long time working on it, asked me very basic question yesterday about points/handles…nothing against him, but problem might be beyond him, as it's beyond most programmers, including probably also me ;-)

In terms of fixing your specific bug, function is SplineSetSimplify, it's a very confusing mass of C code, but luckily what you want to fix is quite constrained (if we begin with corners, and all points we remove are colinear, then, don't make curves), so you may just be able to get somewhere with it.

**Comment by linusromer** [comment]
In `splinefit.c` George Williams wrote:

> I used to check for a spline very close to linear (and if so, make it linear). But in when stroking a path with an elliptical pen we transform the coordinate system and our normal definitions of "close to linear" don't apply.

**Comment by ctrlcctrlv** [comment]
Sigh. He should've added a check obviously, and definitely should not be transforming his coordinate system randomly and smashing functions together even if they're not in the same coordinate system.

But we all know this... The question is whether you can figure out where that comment got added and undo his error.
