### ISSUE TITLE
Mac .mpkg installer

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#487]
Make a mpkg installer that contains a pkg for FF and the XQuartz pkg, checks for X11 and if not found installed it, asks to change the X11 keyboard pref for you so command key works, then copys FontForge.app to /Applications

**Comment by andreaslarsen** [comment]
I chose to make a small installer app instead. The primary reason for this being a lot lest obtrusive when just updating FF where:

Double click the icon -> installs and unmounts automatically

**Comment by skef** [comment]
We removed the XQuartz dependency.
