### ISSUE TITLE
make outline font from a stroke font source via build script

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4871]
Hi
I'm working on a project contains some stroke layers, i need a build script to automate the building process(converting stroke to outline), but i have 2 big issues:
1- I couldn't find any function to convert Font Type from stroke to outline (i mean how to access this menu : Element > Font Info > Layers > Font Type from python API)
2- even if we suppose to pass the previous issue, i can't use `stroke` function:
```python
import os
from os import path
import sys
import fontforge as ff

font_name = sys.argv[1]
source_path = os.path.abspath(os.getcwd())
font_path = source_path + "\\" + font_name + ".sfd"
font = ff.open(font_path)
font.stroke("circular", 50, "round", "round", "cleanup")
font.removeOverlap()
for glyph in font.glyphs():
 glyph.round()
font.save(source_path + "\\" + font_name + ".ttf")
```
here is an example(a tiny stroke sfd source with the build script):
[example.zip](https://github.com/fontforge/fontforge/files/7781686/example.zip)

**Comment by skef** [comment]
The font-level `stroke()` method uses the [selection interface](https://fontforge.org/docs/scripting/python/fontforge.html#selection). You need to select the glyphs to operate on before calling it.

**Comment by skef** [comment]
I haven't verified this works but there's a boolean called `font.strokedfont` in the Python API that looks like it's editable.

**Comment by aminabedi68** [comment]
> The font-level `stroke()` method uses the [selection interface](https://fontforge.org/docs/scripting/python/fontforge.html#selection). You need to select the glyphs to operate on before calling it.

yes, i forgot that.



> I haven't verified this works but there's a boolean called `font.strokedfont` in the Python API that looks like it's editable.

it is! `font.strokedfont = 0`

it's completely solved, thank you @skef
