### ISSUE TITLE
make macbundle fails on ARM

### ISSUE THREAD

**Issue by MaddTheSane** [fontforge/fontforge#4872]
As recently as commit a9c96f5e03ad260db3b28f474fa5455304e3c32a, using `make macbundle` on an Apple Silicon Mac running 12.1 causes CMake to fail:

````
Could not process dependencies: invalid magic number in record at byte 0x0
````

The issue isn't present on Intel Macs with the same set-up.
At a guess, I'd say that it's an issue with lddx (or whatever libraries it depends on) not yet being updated for ARM64.

**Comment by ctrlcctrlv** [comment]
>As recently as commit a9c96f5

Does this mean it works before that commit?

**Comment by MaddTheSane** [comment]
No, just when I noticed it.

**Comment by jtanx** [comment]
Unfortunately I don't have any system to debug this on; my VM (when it was working) is Intel based.

**Comment by jtanx** [comment]
The simplest thing to try I guess is a rebuild of lddx with the latest version of Go

**Comment by ctrlcctrlv** [comment]
I'm not aware of how M1 was rolled out. Does this mean FontForge is totally unusable on these machines, or does it just mean that you need to use an x86_64 emulator until compilation is fixed for ARM?

**Comment by MaddTheSane** [comment]
The bundling function doesn't work, but compiling and running work just fine.

**Comment by ctrlcctrlv** [comment]
Oh, I see. Thanks for confirming. :)

Is there an x86_64 emulator that it would be possible to try to run the bundler under?

**Comment by MaddTheSane** [comment]
I don't think it's an issue with the bundler trying to run (`lddx` runs on Apple Silicon), but the ARM64-generated object files.

**Comment by jtanx** [comment]
Can you try with this branch, I rebuilt lddx using github actions:  https://github.com/fontforge/fontforge/pull/new/lddx

It's built with the latest version of go so it might have updated macho parsing

**Comment by MaddTheSane** [comment]
No change.

It might be on my end, though. Don't have the energy to debug it right now, though.
It'd be helpful if it said _which_ file had the issue.

**Comment by jtanx** [comment]
if you're willing to upload your build folder (or probably just the `bin`+`lib` folder) I could probably take a closer look

**Comment by jtanx** [comment]
Oh yeah, when testing that new version of lddx, you might need to have cleared out your local copy / run `ninja clean` first, otherwise it might have used the cached/old version

**Comment by ctrlcctrlv** [comment]
I don't know much about this stuff, but on another project we had a problem where a library wasn't a "Universal Binary". We had to cross compile like:

```bash
GOOS=darwin GOARCH=amd64 go build -o …
GOOS=darwin GOARCH=arm64 go build -o …
``

then use `lipo -create`. You might try that while compiling `lddx`.

**Comment by ctrlcctrlv** [comment]
Oh and in case it's helpful we got a `lipo` from here, it is not a standard part of GCC or Clang:

https://github.com/tpoechtrager/cctools-port/blob/master/cctools/misc/lipo.c

**Comment by skef** [comment]
I'll likely have access to an ARM mac soon, before the scheduled release, so maybe we can work this out with it before then.

FWIW I've been mostly silent on here because I've moved and will start a new job soon but I hope to do FontForge work for the next few days, starting with some code reviews and looking at what I said I would on #4789. I'll also probably try to fix #4884 but that's enough of a corner case that there's no sense in holding a release for it. I don't anticipate a big pre-release small bug fixing push on my part, partly because time is short and partly because there are fewer low-hanging fruit now.

**Comment by skef** [comment]
Oh, BTW I never wound up with access to one of these.

**Comment by MaddTheSane** [comment]
Whatever the issue was, it seems it was resolved…
