### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by mktcode** [fontforge/fontforge#4886]
I'm trying to adjust descender and ascender of an existing woff2 font but after exporting, the changes don't take effect.

First under Element -> Font Info -> General I adjust the values. When I try to export, I ignore the warning about em (mine is 1000 and it suggest 1024/power of 2) and I fix two validation errors in the "@" symbol, caused by the adjusted descender/ascender (I just move the glyph back into the center box).

So far so good. But the changes don't take effect in the web project I'm working on and when I re-open that edited font, it shows the values as before, even though the file itself is marked by git as changed.

Is there anything I'm missing?

Linux Mint 20.3
Fontforge: 20201107 (AppImage)

https://user-images.githubusercontent.com/6792578/149842306-d2d8e7a5-719f-45fe-8edd-e9161ac1d52f.mp4

(Not sure why it doesn't show this validation errors in this recording now... maybe because I unchecked this "Scale Outlines" checkbox when changing the values?)

**Comment by ctrlcctrlv** [comment]
Make sure OS/2 values match.

**Comment by mktcode** [comment]
Oh yes thank you. Figured that out in the meanwhile but forgot to close this issue.
