### ISSUE TITLE
Improvement for Internal Error: Add the list with the names of the truncated Lookups

### ISSUE THREAD

**Issue by KamilLanda** [fontforge/fontforge#4891]
I don't know if it is realizable request. This message box is jarring.
![internal-error](https://user-images.githubusercontent.com/61148366/150637643-dded1a21-1817-4bc5-9855-e80ccc594b89.png)

My experience is, it is possible to change the position of the fretful Lookup, then the bug will disappear. But sometimes it is very hard (or impossible) to find the truncated Lookup. 
What to add the names of the truncated Lookups (or truncated Subtables) to the message box? Or at least the name of the 1st truncated one.

**Comment by ctrlcctrlv** [comment]
You want a debugger. Hook `IError`. This is not a good general addition to FontForge, as masking the issue is not solving it.

**Comment by ctrlcctrlv** [comment]
By the way, some debuggers won't allow you to hook a macro. So you may wish to hook `GDrawError`, `_GDraw_InitError`. If really desperate hook `_GGDKDraw_CreateWindow`.
