### ISSUE TITLE
required by: fontforge-20201107-r2[so:libpython3.10.so.1.0]

### ISSUE THREAD

**Issue by alizaibmail** [fontforge/fontforge#4901]
This is what i am doing in my docker file 
`FROM node:14-alpine3.14`
`RUN apk add fontforge`

this is the error i get 

`#6 7.884 ERROR: unable to select packages:
#6 7.967   so:libpython3.10.so.1.0 (no such package):
#6 7.967     required by: fontforge-20201107-r2[so:libpython3.10.so.1.0]
------`

What could be wrong ?

![image](https://user-images.githubusercontent.com/98738114/151766292-2756f679-19c5-4738-bb0d-69899ce0464d.png)

**Comment by jtanx** [comment]
Ask the alpine maintainers

**Comment by alizaibmail** [comment]
So we can not use fontforge with alpine ?

**Comment by jtanx** [comment]
You probably can, but clearly wherever you are sourcing that package from is broken

**Comment by alizaibmail** [comment]
Perfect, thanks for your time.
