### ISSUE TITLE
Just installed

### ISSUE THREAD

**Issue by criscory** [fontforge/fontforge#4930]
The toolbar is greyed out and nonresponsive.

![FontForge](https://user-images.githubusercontent.com/101030675/157104889-51b99755-3793-4ba6-aced-d7edf06a1552.png)

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
The tools menu is for options registered by python extensions. If there are no extensions installed it will be disabled.

**Comment by criscory** [comment]
Thanks Are there supposed to be two windows once you launch FontForge?
Your help is greatly appriciated.

**Comment by skef** [comment]
How many windows appear depends in part on what you've done before, as there is some "memory" about that in some of the files. But typically when you open a font you get a FontView (as pictured above) and then you can double-click on a glyph to get a CharView for it. Those are the two main windows you work with (besides dialogs).

**Comment by criscory** [comment]
Thank you so much.
