### ISSUE TITLE
about Balance and Harmonize in new fontforge release

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4938]
i usually use Balance and Harmonize from tools. These functions are always applied to the selected segments, but now in new release inside fontforge they are applied to whole contours in a glyph, and this cause serious limitations in using them.

**Comment by linusromer** [comment]
@aminabedi68 Do you refer to the glyph view or the font view? On which OS does this happen? Have you made sure that Curvatura.py does not mess anymore with FontForge? (I have checked it on Windows and Linux from source and cannot confirm the behaviour you described for the glyph view.)

**Comment by aminabedi68** [comment]
Hi, it working fine now! i don't know what was the problem, either the special case or my mistake while doing the test. thank you.
