### ISSUE TITLE
question: how to set "External only" in `font.stroke`

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4942]
Hi
how can i set "External only" in `font.stroke`?
and for future questions, where is the source of python api?

**Comment by skef** [comment]
Source is in `fontforge/python.c`. 

If you only want the external paths you'd set the removeinternal keyword variable to True (see https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.glyph.stroke )

**Comment by aminabedi68** [comment]
Thank you so much 👍
