### ISSUE TITLE
WOFF file can not be open by FF

### ISSUE THREAD

**Issue by NNSTH** [fontforge/fontforge#4946]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot: 
![FF crash](https://user-images.githubusercontent.com/36368967/158054640-36f76b72-e555-4453-b2f1-b209a22bf07c.png)

- [x] The FontForge version and the operating system you're using: FF on Ubuntu 16.04
- [x] The behavior you expect to see, and the actual behavior: I want to open the .woff file by FF, actual behavior: it can not be opened
- [x] Steps to reproduce the behavior: take [this .woff file](https://github.com/fontforge/fontforge/files/8239323/f3.woff.zip) and try open it by FF 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
Can FontForge read the font produced by running a third party Woff decompression program, such as Google's?

**Comment by NNSTH** [comment]
I'll be happy to help checking it, but I really don't know how.. can you instruct me?

**Comment by ctrlcctrlv** [comment]
Sure, it's a bit of a developer debugging tool.

https://github.com/wget/sfnt2woff

Checkout repo, compile with make, run woff2sfnt on your font. See if it works or crashes.

**Comment by NNSTH** [comment]
I can not run the executable file created since I'm running on Ubuntu, instead, I used [this tool](http://manpages.ubuntu.com/manpages/xenial/man1/woff2sfnt.1.html), and got an error: 
"WOFF error: bad parameter to WOFF function"
How can we continue checking from here?

**Comment by ChiefMikeK** [comment]
FYi the link above for f3.woff.zip is an empty zero size zip how big is your orig not zipped file?   
- I would like to open it in a hex viewer to see if the header is valid.

**Comment by ChiefMikeK** [comment]
🤨 Looks like a partial ripped font found this 
- copyright: Microsoft 2018 All Rights Reserved
- Calibri Bold Version 6.21

**Comment by ctrlcctrlv** [comment]
If woff2sfnt cannot interpret the font it's invalid, sorry. That's the reference implementation. If you have some reason to believe it should work, it should be fixed there before here. Closing.

**Comment by NNSTH** [comment]
I found the root cause of the partial ripped font- this was generated by FF from another font, but got an error, which I added to an existing opened bug, see [my comment on FF bug 3009](https://github.com/fontforge/fontforge/issues/3009#issuecomment-1070560739)
Thanks for your help, hope to find a resolution to this issue!

**Comment by jtanx** [comment]
>  FF on Ubuntu 16.04

Are you using the AppImage or are you using what's provided from Ubuntu's repos?

**Comment by NNSTH** [comment]
I'm using what's provided from Ubuntu's repos.

**Comment by jtanx** [comment]
Yeah that's an ancient version, follow the directions on the website and use the appimage

**Comment by NNSTH** [comment]
Using [this link](http://designwithfontforge.com/en-US/Installing_Fontforge.html), I do not see any instruction of how to use the appimage?

**Comment by jtanx** [comment]
https://fontforge.org/en-US/

**Comment by NNSTH** [comment]
Still getting the same error using an appimage, any other idea?

**Comment by jtanx** [comment]
Nope, it works for me.

**Comment by ChiefMikeK** [comment]
You could also try  
- [fontforge/INSTALL from source](https://github.com/fontforge/fontforge/blob/master/INSTALL.md )  
- it is more steps and slower to build but in the long past i've had better success with a few programs than with ppa's, fedora-dnf, etc.
- :neckbeard:

**Comment by NNSTH** [comment]
The latest AppImage is working for me, anyway I have an issue when trying to use it within another program, [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX). Seems like the only way to fix it is to have a fix in Ubuntu's repo. 
Can you update the repo please? so when I run `sudo apt-get update` I'll get the latest FF code with all fixes?

**Comment by skef** [comment]
@NNSTH The FontForge project doesn't manage downstream repos. You'll need to take it up with Ubuntu.
