### ISSUE TITLE
fontmake crashes with new fontforge ufo output

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4951]
Hi
fontmake crashes during font build process with new fontforge, it seems that the only difference is related to new entry `<key>guidelines</key>` in `fontinfo.plist` file.

it's a fontforge issue or fontmake?

**Comment by ctrlcctrlv** [comment]
@aminabedi68 I know it is not ideal but you can work around it with [`MFEKmetadata`](https://github.com/MFEK/metadata).

I call : 

```
MFEKmetadata myfont.ufo arbitrary -d -k guidelines
```

Before running fontmake.

**Comment by aminabedi68** [comment]
thank you @ctrlcctrlv 
but I can't use it, because it expand the build dependency to solve a tiny problem, i can solve it with a simple python script... i think this will cause crash in many build processes in feature, so it should be fixed somehow from fontforge or fontmake. so what you think? we need to open an issue for fontmake or a fontforge regression for this?

**Comment by jtanx** [comment]
Got a sample?

**Comment by ctrlcctrlv** [comment]
`MFEKmetadata` is broadly useful for fontmake builds, and is a single Rust binary.

It has many more abilities than just deleting keys, but of course, YMMV. I use it to patch metadata all the time.

I don't have access to the UFO I know has this issue atm...I believe it's a fontmake issue but can't recall exactly, FF may be doing something unexpected.

**Comment by aminabedi68** [comment]
@ctrlcctrlv 
MFEK project is amazing, i love to try it but couldn't install on windows os.
@jtanx 
this is a simplified version of build files for an ofl project, you can test it with latest and previous version of fontforge:
 [test.zip](https://github.com/fontforge/fontforge/files/8357206/test.zip)

**Comment by aminabedi68** [comment]
i did a mistake, it's about lack of `<key>guidelines</key>` in `fontinfo.plist` file!

**Comment by aminabedi68** [comment]
for those who want a temporary solution: i wrote a python script to check the `fontinfo.plist` file for `<key>guidelines</key>` and add it if not exist, it's not perfect but working for me:
<details>
  <summary>python script</summary>
  
```python
import os
import sys
import linecache
 
PATH = sys.argv[1]
os.chdir(PATH)

with open('fontinfo.plist') as f:
    if '<key>guidelines</key>' in f.read():
     sys.exit()
    else:
     file_read = open('fontinfo.plist', "r")
     lines = file_read.readlines()
     BreakLine = 2
     text = 'postscriptBlueShift'
     for line in lines:
      BreakLine += 1
      if text in line:
       break
     file_read.close()
     # guidelines key:
     section_2 = "    <key>guidelines</key>\n"
     # Before:
     section_1 = ""
     l = 0
     while l < BreakLine:
      section_1 = section_1 + linecache.getline('fontinfo.plist', l)
      l += 1
     # after:
     section_3 = ""
     l = BreakLine
     while True:
      section_3 = section_3 + linecache.getline('fontinfo.plist', l)
      l += 1
      if (linecache.getline('fontinfo.plist', l) == ""):
       break
     # new fontinfo:
     data = section_1 + section_2 + section_3
     fontinfo = open("fontinfo.plist" , "w")
     fontinfo.write(data)
     fontinfo.close()
```
</details>

**Comment by devosb** [comment]
> i did a mistake, it's about lack of `<key>guidelines</key>` in `fontinfo.plist` file!

And that lack leaves an `<array/>` element with no key value. Probably the [same issue](https://github.com/silnrsi/pysilfont/issues/76) that I found in another tool. That issue also has test data.
