### ISSUE TITLE
Wrong behavior of: Metrics - Set Both Bearing

### ISSUE THREAD

**Issue by samiel60** [fontforge/fontforge#4955]
I'm using last official FF Appimage (FontForge-2022-03-08-582bd41-x86_64.AppImage) on Debian Testing.
I start from a glyph that has _n_ pt of bearing on both sides. So I resort to **Metrics - Set Both Bearing** by setting them to _n + x_, LSB is correctly set to _n + x_, but RSB il set to _n + 2x_. It is as if the increase is applied twice to the right.
The bug is not specific to the operating system, as the same problem occurs in the MAC version.
This problem does not appear, from my tests, if instead of increasing the measure I reduce it.

**Comment by ctrlcctrlv** [comment]
Confirmed.

**Comment by Finii** [comment]
This commit breaks it:

1033bc6082762f2e2dd989cfbd95b5f184651854

      Remove fvt_dontmovewidth mistakenly added in bbde2a58b3
      and then copied forward

**Comment by Finii** [comment]
Fix:

```diff
index 8f9fc4aac..486d34847 100644
--- a/fontforge/fvmetrics.c
+++ b/fontforge/fvmetrics.c
@@ -160,7 +160,7 @@ return;
            SCSynchronizeWidth(sc,width,sc->width,fv);
        }
        if ( transform[4]!=0 ) {
-           FVTrans(fv,sc,transform,NULL,fvt_alllayers);
+           FVTrans(fv,sc,transform,NULL,fvt_alllayers | fvt_dontmovewidth);
            bvts[0].x = transform[4];
            for ( bdf = fv->sf->bitmaps; bdf!=NULL; bdf=bdf->next ) if ( bdf->glyphs[sc->orig_pos]!=NULL )
                BCTrans(bdf,bdf->glyphs[sc->orig_pos],bvts,fv);
```

**Comment by samiel60** [comment]
Not yet fixed?

**Comment by samiel60** [comment]
I notice that the bug persists in the last masters. And consequently also in the latest "debianized" version on Testing. Is there any hope of a resolution in the short term?

**Comment by jtanx** [comment]
Looks like @Finii 's patch is correct, with no regression in #4433.
