### ISSUE TITLE
Using the corner point tool producing unneeded control handles with newly placed points not on an existing outline.

### ISSUE THREAD

**Issue by Bry10022** [fontforge/fontforge#4957]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [X] Screenshot: See video.
- [X] The FontForge version and the operating system you're using:

- FontForge: 22020308 \582bd41a9bf04326300fc02a677fe3610d6d3ccd [ignore the backslash, I had to put something at the front of the hex string so it does not get formatted as a link to a commit]
- Operating System: Windows 10 Pro Version 21H2 Build 19044.1586

- [X] The behavior you expect to see, and the actual behavior

- Expected: Just the points where the newly placed points are.
- Actual: Unnecessary control handles are present on the points that I just placed.

- [X] Steps to reproduce the behavior: See video.
- [ ] \(optional) Possible solution/fix/workaround

I searched the issues, but nothing similar (as of current release) found. The issue did not occur prior to current release.

The video itself placed here so it does not disrupt the flow of text:

https://user-images.githubusercontent.com/9865306/159189620-4b7fe385-876b-4b49-852f-7b5991b84773.mp4

**Comment by skef** [comment]
Probably a stray nonextcp/noprevcp issue. I'll take a look.
