### ISSUE TITLE
Bad behavior of "Element -- Syle -- Add Small Caps"

### ISSUE THREAD

**Issue by samiel60** [fontforge/fontforge#4964]
I use the Element - Syle - Add Small Caps function. For my test I adopt the default settings (which are not suitable for the font, but here this is irrelevant)
In the version currently present in Debian Testing (20201107) the glyphs produced are imperfect, but still graphically correct:
![Schermata del 2022-03-23 23-04-12](https://user-images.githubusercontent.com/6018621/159805594-26724de3-501d-46fb-9c33-18af6adb3466.png)
In the latest version (FontForge-2022-03-23-a8be73b-x86_64.AppImage which I installed in the same Debian testing as AppImage), the glyphs are totally upset:
![Schermata del 2022-03-23 23-05-08](https://user-images.githubusercontent.com/6018621/159805617-f84ef6e8-e80c-4265-b0ba-44a1cef7daf3.png)

**Comment by ctrlcctrlv** [comment]
My feeling is either a recent @linusromer or @skef change likely caused this.

**Comment by linusromer** [comment]
@ctrlcctrlv At the moment I have no concrete idea how a recent change by me could be the cause for this behavior. Do you have a more concrete idea? The fact that straight lines get totally messed up (curved ones are okay) may point in the direction that my new node conversion [https://github.com/fontforge/fontforge/pull/4789](https://github.com/fontforge/fontforge/pull/4789) could somehow be the reason for this or maybe [https://github.com/fontforge/fontforge/pull/4685](https://github.com/fontforge/fontforge/pull/4685).

**Comment by skef** [comment]
I'll try to take a look at this one and #4959 before *too* long. Might not happen before US tax day. Then maybe we can do a maintenance release shortly after to get some of these tuneups out there.

**Comment by jtanx** [comment]
Yeah agreed that we should do a maintenance release; I've already set up the milestone for it.

**Comment by skef** [comment]
Yeah this is definitely my doing based on the symptoms.
