### ISSUE TITLE
Label Glymp By Unicode Name

### ISSUE THREAD

**Issue by skinkie** [fontforge/fontforge#4970]
At this moment a Glymp can be shown by a VERY small icon (a tip how to increse that woud be appreciated), name or unicode. But what it can't do is the "unicode name" hence gbreve, "ogonek", etc. this would really help.

![image](https://user-images.githubusercontent.com/502394/160599201-f996ba99-ceb4-400b-a196-52f2e7c4284f.png)
![image](https://user-images.githubusercontent.com/502394/160599254-3e39e179-7941-4956-88f2-40c1070c1a60.png)

**Comment by skef** [comment]
Assuming you're using the most recent version, you can open File -> Appearance Editor and change the size of Font View -> Font. https://fontforge.org/docs/ui/misc/xres.html#fonts

**Comment by skef** [comment]
Some Unicode glyph names are short but many of them are untenable for display in the FontView, e.g. "PARENTHESIZED LATIN CAPITAL LETTER M"

**Comment by skef** [comment]
Oh, note that generally when using the Appearance Editor you need to open a new window to see changes take effect, which in the case of the FontView may mean restarting.

**Comment by skinkie** [comment]
> Assuming you're using the most recent version, you can open File -> Appearance Editor and change the size of Font View -> Font. https://fontforge.org/docs/ui/misc/xres.html#fonts

![image](https://user-images.githubusercontent.com/502394/160606335-c40c670e-588f-4a86-b128-36f61d7be99f.png)

![image](https://user-images.githubusercontent.com/502394/160606548-65e218cd-777b-415d-a879-0854d1863139.png)

That works after a restart, but the 'images' are still small.

> Some Unicode glyph names are short but many of them are untenable for display in the FontView, e.g. "PARENTHESIZED LATIN CAPITAL LETTER M"

This might well be, but the unicode number is even less useful. Note that some of the glymps do contain useful stuff.

![image](https://user-images.githubusercontent.com/502394/160606965-5e6da874-5cda-4e7c-bdfa-ec4d634abd2f.png)

**Comment by skef** [comment]
Oh, I was confused about your question. 

The glyph images are proportional to the bounding box of the Font, not "zoomed in" to the individual path. This is supposed to be helpful -- if you don't see the glyph where it appears relative to the other glyphs a number of glyphs would be ambiguous. You can of course make them all bigger by changing the scale in the View window but accents are still going to be shown in accent position. 

I think our default recommendation would be to install a version of Unifont ( https://unifoundry.com/unifont/ ) and choose "Glyph Image" as the label. Then the label should be the corresponding glyph in the UI font unless there isn't one, with Unifont as the backup.

**Comment by skinkie** [comment]
@skef what I would like to see is the icon presentation a big bigger. So I can actually identify the 'combinable' glymps (cedille, breven, etc.) At this moment it is literally guessing or going by hover.

**Comment by skef** [comment]
To clarify, there are no glyph "icons" per se, -- choosing "glyph image" means that what is shown in the label field is just that character taken from the label font at the specified size. (There is some cleverness for non-unicode-mapped glyphs such as stripping off suffixes from the glyph names and trying to map the result.)

**Comment by skinkie** [comment]
> Set FontView -> Font to something like "300% ^View.LabelFont", save that config, restart, and see how it looks for you.

The above syntax won't get saved.

**Comment by skef** [comment]
Sorry, this system is a little arcane. Try the following:

1. Open the appearance editor
2. Go to the Font View tab
3. Edit the Font field to read "300% ^View.LabelFont"
4. Press the "Save As..." button at the bottom of the dialog.
5. Pick a handy location in the "Save" dialog for your new, customized resources file.
6. Click the "Save" button.
7. Click the OK button in the Appearance Editor dialog to close it.
8. Restart FontForge

This will also change the "ResourcesFile" entry in the Preferences dialog to the file you chose. If you ever need to undo this and go back to the system resources, you make the change there.

**Comment by skinkie** [comment]
@skef this works! Thanks!

**Comment by skef** [comment]
We're probably not going to offer the Unicode name in this field due to the long string problem, so I'm closing this.
