### ISSUE TITLE
Issue aboue fontforge native scripting

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#4973]
Hello
i'm working on a typeface and in the last step of build process i add a modification level with fontforge native scripting method:
```
Open($1);
SelectNone();
SelectMore(0u640);
Move(1024,0);
MoveReference(-1024,0,0xe02a);
SelectNone();
SelectMore(0uFCF2, 0uFCF3, 0uFCF4, 0uFE71, 0uFE77, 0uFE79, 0uFE7B, 0uFE7D, 0uFE7F);
Move(1024,0);
MoveReference(-1024,0,0xe02a);
SelectNone();
SelectMore(0uFDF2);
rbearing = GlyphInfo("RBearing") + 4096
SetRBearing(rbearing)
MoveReference(2048,0,0xe0a2);
MoveReference(2048,0,0xe03a);
MoveReference(2048,0,0xe033);
MoveReference(4096,0,0xe05a);
MoveReference(4096,0,0xe022);
Save();
```

it's pretty simple, but fontforge translate wrong codepoints for first four codepoints in line 7!
fontforge log:
```
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20201107
 Based on sources from 2020-11-07 21:17 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: f8bbd68cb29e31eba3215894ae4124a8ecdc2033
MoveReference: Failed to find a matching reference in: uniFD3C
Called from...
 kashida_versions_modification.pe: line 9
```

test files:
[test.zip](https://github.com/fontforge/fontforge/files/8379132/test.zip)

this is so important to me, please take a look.
(i don't know if there is a parallel solution via python API, the main problem to me via python is how to move outlines and components of a glyph)

**Comment by KamilLanda** [comment]
There is difference between functions **SelectMore** and **SelectSingletons**.
You used **SelectMore** but it selects 15 glyphs. 
```
SelectNone();
SelectMore(0uFCF2, 0uFCF3, 0uFCF4, 0uFE71, 0uFE77, 0uFE79, 0uFE7B, 0uFE7D, 0uFE7F);
```
![15glyphs](https://user-images.githubusercontent.com/61148366/160869078-077d24a3-cad6-4729-a96d-38d92f313874.png)


But **SelectSingletons** selects only 9 defined glyphs 
```
SelectNone();
SelectSingletons(0uFCF2, 0uFCF3, 0uFCF4, 0uFE71, 0uFE77, 0uFE79, 0uFE7B, 0uFE7D, 0uFE7F);
```
![9glyphs](https://user-images.githubusercontent.com/61148366/160869109-211a10e4-df20-459b-b61e-58646364819c.png)


With **SelectSingletons** it was functional for me without any error message *(I ran the script via menu File/ Execute script)*.

**Comment by aminabedi68** [comment]
yes! stupid me 🤦‍♂️
thank you @KamilLanda  :)
