### ISSUE TITLE
Python font.transform(psMat.scale(FACTOR)) does not give the same result as Scale Uniformly in the GUI.

### ISSUE THREAD

**Issue by kwand** [fontforge/fontforge#4976]
### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [x] \(optional) Possible solution/fix/workaround

**Fontforge version (on Arch Linux 5.17.1)**

```
fontforge -v
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-03-29 01:43 UTC-ML-D-GDK3.
 Based on source from git with hash: 7fec181549677e62cfb16101972f479183082c29
fontforge 20220308
build date: 2022-03-29 01:43 UTC
```

As titled. I would like to be able to perform a Scale Uniformly on all glyphs in a font via Python scripting, but so far I have not been able to replicate the same functionality via font.transform() - which, as far as I'm aware, the only method that I can use to replicate it. In particular, I've noticed the MATH table does not get scaled in Python, but it is (correctly, IMO) when done via the GUI.

**Expected Behaviour**
`font.transform(psMat.scale(FACTOR)` does the same thing as a GUI `Scale Uniformly...` with all glyphs selected (and checkboxes checked. Since font.transform() can only take in one argument, I think it's appropriate it is applied to the categories specified in the checkboxes. Either this, or more options should be exposed via font.transform()).

Note that "by all checkboxes checked", I mean this:

<details>
   <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/16279847/160954203-5275ed9b-e909-453f-b4c1-95d28d45bb91.png)
</details>

**Actual Behaviour**
The two methods are not equivalent - in particular, the MATH table does not get scaled in Python.  I do not know what else has not been missed in Python, but I suspect there may be more than just the MATH table that was not scaled.

<details>
   <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/16279847/160955728-b51a5129-3c5d-4081-8616-9e5c2c721d33.png)
![image](https://user-images.githubusercontent.com/16279847/160955765-cab00cea-d545-4432-a891-9813454fec76.png)
</details>

**Concrete steps to reproduce**
1. Open a font with an OpenType MATH table in the GUI and in Python (i.e. a math font. You can download the `Garamond-Math.otf` that I was working with from here: https://ctan.org/tex-archive/fonts/garamond-math)
2. Scale the font in the GUI with all glyphs selected (`Ctrl+A`) and options as seen in the screenshot above. Scaling factor can be 110% for simplicity
3. Do the same thing in Python i.e.
```
f.selection.all() # f is the variable we loaded the font into
f.transform(psMat.scale(1.10))
```
4. Save both versions (GUI and Python) and open them both up in the GUI. Notice that in particular the MATH table has not been scaled in Python.

**Possible solution/fix/workaround**

Expose a font.scaleUniformly() function in Python or add more parameters to font.transform(), allowing me to choose all the same categories in the GUI for transformation.

**Comment by kwand** [comment]
@skef I am told that you would be the best person to consult regarding this issue?

**Comment by skef** [comment]
Some of the UI functions are synchronized with the Python API and some aren't. It's less important (to me, anyway, whatever that's worth) that things work in the same way than that things be possible to do by each means without *too* much work. 

All that said, it seems like this should be a pretty easy change. The font-level UI transform dialog ultimately calls FVTransFunc with a bunch of flags:

```
        (td->transfunc)(td->userdata,transform,origin,bvts,
                (alllayers?fvt_alllayers:0)|
                (dogrid?fvt_dogrid:0)|
                 (dowidth?0:fvt_dontmovewidth)|
                 (round_2_int?fvt_round_to_int:0)|
                 (dokp?fvt_scalepstpos:0)|
                 (dokerns?fvt_scalekernclasses:0)|
                 (isapply?fvt_justapply:0));
```

(FVTtransFunc is passed in.) The equivalent Python function calls FVTransFunc with fewer flags:

```
static PyObject *PyFFFont_Transform(PyFF_Font *self, PyObject *args) {
    FontViewBase *fv;
    int i;
    double m[6];
    real t[6];
    BVTFunc bvts[1];

    if ( CheckIfFontClosed(self) )
return (NULL);
    fv = self->fv;
    if ( !PyArg_ParseTuple(args,"(dddddd)",&m[0], &m[1], &m[2], &m[3], &m[4], &m[5] ) )
return( NULL );
    for ( i=0; i<6; ++i )
        t[i] = m[i];
    bvts[0].func = bvt_none;
    FVTransFunc(fv,t,0,bvts,true);
Py_RETURN( self );
}
```

(That "true" is basically setting `fvt_alllayers`:

```
enum fvtrans_flags { fvt_alllayers=1, fvt_round_to_int=2,
        fvt_dontsetwidth=4, fvt_dontmovewidth=8, fvt_scalekernclasses=0x10,
        fvt_scalepstpos=0x20, fvt_dogrid=0x40, fvt_partialreftrans=0x80,
        fvt_justapply=0x100, fvt_revert=0x200, fvt_nopreserve=0x400,
        fvt_noupdate=0x800 };
```
)

So the work here would be spending an hour or two adding some keyword arguments that default to `False` (except for alllayers), using those to set the flags similarly, and updating the documentation.
