### ISSUE TITLE
Can't open FontForge (MAC)

### ISSUE THREAD

**Issue by Mirthe777** [fontforge/fontforge#4986]
I'm not able to open FontForge. It's saying "FontForge cannot be opened because the developer cannot be verified. macOS cannot verify that this app does not contain malware. This item is located on the disk image 'FontForge-2022-03-08-74e2eca.app.dmg'. Safari downloaded this disk image at 01:53 today from objects.githubusercontent.com." 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/99672790/162547656-669be001-ee87-418f-94e8-3df7193f9998.png">

(The screenshot is in Dutch)

What can I do?

**Comment by Bry10022** [comment]
You could try whitelisting the program in settings. Don't know how to do on mac, don't have one…

**Comment by jtanx** [comment]
https://apple.stackexchange.com/questions/373738/how-can-i-install-a-non-notarized-application-that-is-not-in-the-app-store-and-n

**Comment by Mirthe777** [comment]
> You could try whitelisting the program in settings. Don't know how to do on mac, don't have one…

Thank you very much. I fixed it on my own. Next time try not to make an comment like that. It hurts people
