### ISSUE TITLE
Kerning not working

### ISSUE THREAD

**Issue by Trainer0072** [fontforge/fontforge#4987]
So, I make kerning pair (letter P with letter o after, or any other pair), I save it and in metrics window it works, but whwn i export it, it only works in inkscape and nowhere else. I've read that it has to do something that I can export only GPOS table or GPOS + KERN table, but many programs can read kerning only if there is only KERN table, but i have no idea how can i exclude GPOS table from being exported. If someone managed to do so, please tell me how to do it, or maybe if someone would be that kind I may send my font file, and someone would export it for me. 

Thanks for all answers, bye

**Comment by ctrlcctrlv** [comment]
Make sure the `kern` table has the right languages and scripts in its lookup metadata. There's no reason GPOS should be so poorly supported on modern OS.
