### ISSUE TITLE
Can't save at all

### ISSUE THREAD

**Issue by dedicatedfollower467** [fontforge/fontforge#4991]
I literally can't save anything. I can edit characters, but can't save an .sfd file, so any work I do is lost entirely. I'm running Windows 10 and using the 2022-03-28 release of fontforge, downloading from fontforge.org.

Every time I try to save anything, I get a window pop-up telling me "Save Failed." For a while, I was getting an error message that would tell me "You tried to save as filename but it saved as filename.sfd." I no longer see that error message, and I cannot find any version of the file anywhere in my directory.

**Comment by ctrlcctrlv** [comment]
Potentially related to #4989 ?

**Comment by Mercury13** [comment]
No. Under Windows save dialog works really badly.
We opened a TTF, trying to save, and see this dialog.
![image](https://user-images.githubusercontent.com/10164882/163872922-87f39da6-b90f-4a3c-a64c-eb8c0d31e845.png)

Then we open some directory, and dialog changes to this one.
![image](https://user-images.githubusercontent.com/10164882/163873048-2f43f3c1-22e1-47c4-a31f-6d1631913fb3.png)

When we press OK in this condition, we get
![image](https://user-images.githubusercontent.com/10164882/163873096-c7c6ff2a-177e-4c84-ae23-a1cd9d1fe3d5.png)

Probably this is our “Save failed”.

If in this condition we TYPE FILENAME BY HAND, WITH EXTENSION, everything’s OK.
![image](https://user-images.githubusercontent.com/10164882/163873352-b62361c4-b6c0-432d-b77c-41a8180969ae.png)

**Comment by Mercury13** [comment]
I think that this bug is critical and you need to re-release: newbies want to save as quickly as possible.

**Comment by Mercury13** [comment]
In previous 20th-anniversary version it used to give some default filename, as we often edit some existing TTFs, not create from scratch.

**Comment by ctrlcctrlv** [comment]
The only recent change I can think of that could be causing this is #4939. @jtanx may know more.
