### ISSUE TITLE
Glyph Image font is hard to read

### ISSUE THREAD

**Issue by eishiya** [fontforge/fontforge#4992]
I updated to 2022.03.08 from I think a 2020 version (both on Windows 10 x64), and I've noticed the font used for "Glyph Image" previews in the main window has been changed, and is much less legible, at least on my standard dpi screen.

The thinner strokes of glyphs are *very* thin and sometimes hard to see, and glyphs now protrude into the area occupied by the font's glyphs.
![image](https://user-images.githubusercontent.com/70545646/163718256-3758b7b2-5049-4473-aa10-332692d1d9d3.png)

I don't have screenshots of the old font for the examples above, but I do have a comparison of some CJK brackets:
Old, perfectly clear:
![image](https://user-images.githubusercontent.com/70545646/163718657-78d1135c-3704-4145-8343-b841a4e369a4.png)
New, thin and blurry:
![image](https://user-images.githubusercontent.com/70545646/163718632-fa049b63-f314-4989-9fbf-2c22d09733ac.png)
Notice how the old font sits better in its box too. The new one seems to have its baseline at the bottom of the box, so anything with a descender will protrude below it. You can even see this on characters as common as "g":
![image](https://user-images.githubusercontent.com/70545646/163718723-9b9c8df1-d6ce-4443-b732-35eeeb2988aa.png)![image](https://user-images.githubusercontent.com/70545646/163718712-6ebfddae-487e-48b2-a582-d7cc638dd9b1.png)

In addition, many CJK characters that were present in the old font are missing in the new one:
Old:
![image](https://user-images.githubusercontent.com/70545646/163718893-d8cf5c55-44f1-4ea3-a1a6-e0214d6e5c28.png)
New:
![image](https://user-images.githubusercontent.com/70545646/163718870-816ed9ce-7f99-4c79-ab0c-bae6c8b82727.png)
And the characters that are there are often very hard to read, too. The old font made much better use of the available space, whereas this font seems meant for display at large sizes.

Clarity and coverage are both important for the Glyph Image font, as good previews greatly speed up finding specific glyphs and making sure that the glyph you're editing is the one you think it is.

I'm guessing this font was added with high-dpi users in mind. Perhaps both fonts could be offered options in Preferences? The new font is visually more appealing, but as the preview, it just gets in the way and slows me down ):

It seems that this font is also used for some of the dialogs but not all of them, which leads to an inconsistent view, with some text being clear (old fonts) and some being blurry:
![image](https://user-images.githubusercontent.com/70545646/163719216-8ab64d76-0523-4bc8-81ec-11b8c8678d78.png)

**Comment by skef** [comment]
If you or someone else can verify these problems on a fresh install of Windows on a non-HiDPI screen we'd be more likely to be interested in looking into them. Beyond that we don't know how your system is set up in terms of fonts and font configuration (default OS UI font, anti-aliasing, sub-pixel rendering, and so forth).

The fonts are configurable in the Appearance Editor (see https://github.com/fontforge/fontforge/issues/4970#issuecomment-1082466966) and as of the last release all the fonts throughout the config are configured relative to those four fields on the initial tab in that dialog.

Making sure that Deja Vu Sans is installed (it isn't by default on Windows) and putting it at the front of the list is likely to have a good result.

**Comment by eishiya** [comment]
Unfortunately a fresh install of Windows is not practical for me, but I can provide my settings:
Default OS UI font: Default (presumably Segoe UI)
Sub-pixel rendering: ClearType disabled
I don't think Windows has anti-aliasing settings beyond ClearType, that's something I've always had to control in individual programs.
I haven't done any font- or display-related configuration on Windows beyond disabling ClearType and extending my desktop to a second screen, so my settings should be very close to a clean install.

I spent a stupid amount of time looking for appearance settings in Preferences and the View menus, and somehow completely missed the Appearance Editor even though it's right next to Preferences! Thank you, I feel very silly.
Installing the entire DejaVu Sans family and restarting FontForge produced no changes, even though it's set as the first choice for LabelFont. I tried changing the spelling to "DejaVu Sans" (no space) to match the name of the font as displayed elsewhere, this also had no effect. Interestingly, setting a larger size also has no effect, and restarting FontForge resets the size in the LabelFont field back to 12pt and the "Deja Vu Sans" spelling. I get the feeling that's not supposed to happen...

**Comment by skef** [comment]
Just to check -- have you verified that you've actually saved a modified "resources" file so that any changes you make are still present after you restart, as I describe in that comment I linked to? That's often what trips users up their first time making Appearances changes.

**Comment by eishiya** [comment]
That was a goof, whoops xP I have, however, done those steps now and the properties are saving across restarts. However, my changes to LabelFont still do not change anything. I've been changing the 12pt to 16pt in an attempt to get *some* visible change regardless of font, but with no luck.

It looks like I have to Save As the appearance settings to the resource file every time I make any change in the Appearance Editor to make sure the changes persist across loads, is this intentional?

**Comment by skef** [comment]
I don't know when that decision stems from so I can't speak to whether it is *intentional*, but I believe it's *true*. The Appearance Editor evolved out of an X-resource based system where hand-editing wasn't unusual, and the developers at the time were probably thinking the system should be like a text editor, where saving is usually a separate step.

I did a partial overhaul of this system for the last release and I have further plans (that I may never get to) for simplifying it further. 

What does the "Font" entry under the "Font View" tab currently contain?

**Comment by skef** [comment]
To clarify something that may not be clear: the label font is *only* used (by default) for the labels in the FontView. The difference between 12 and 16 pt may be subtle enough not to be obvious. I suggest trying something like "200% ^View.LabelFont" in "Font View" -> "Font" and seeing if that obviously changes things. Then we can work backward.

**Comment by eishiya** [comment]
The file thing makes sense, thanks for the explanation!
I expect LabelFont to only affect the labels in font view, so no confusion there :]

"Font" in "Font View" contain~~s~~ed `400 12pt system-ui,DejaVu Sans,Calibri`
I've set it to `200% ^View.LabelFont` and *that* made a difference. I've now set it to just `^View.LabelFont`, which also works (I guess the `^` is a dereference/variable marker?)

Unfortunately it looks like DejaVu sans completely lacks CJK characters (to be fair, its website says as much), so its coverage is even worse than whatever was used before (presumably the OS font). But at least now I know how to tweak the appearance (definitely a different process from anything I expected xP), so if I/we can track down the old font or a good alternative...

**Comment by skef** [comment]
That "Font" entry looks like something from the previous resource files, maybe the result of an earlier edit.

The "^" notation indicates that any values you don't specify, or specify relatively  (as with a percentage) should be taken from the entry after the caret. This was added in the most recent release, and allows the four entries on that first tab to affect other entries, so that you can (for example) just change the font size in View.DefaultFont and have everything else scale accordingly. 

For coverage we recommend installing Unifont: https://unifoundry.com/unifont/ . I haven't tried the new OpenType version but either it or the TrueType version should work. It's definitely "pixel-y" but it has complete Unicode BMP coverage. Then if you want something for CJK in between put it before "unifont" in the list.

**Comment by eishiya** [comment]
Unifont seems to have all the CJK glyphs I need, and it looks nice and clear. Thank you so much for walking me through this. Definitely would not have been able to figure all this out myself, especially with all the FontForge restarting required xP

It would be nice if pressing OK in the Appearance Editor immediately applied the changes (it flashes the screen like it's going to, but does nothing). But, that's a different issue, so I will close this one. Thanks again!
