### ISSUE TITLE
Problem with Cyrillic selection in python module

### ISSUE THREAD

**Issue by chudotony** [fontforge/fontforge#5000]
I have a problem selecting Cyrillic glyphs via FontForge python module, though font contains them. For example, using `font.__contains__('zhe')` give `False` output, when `font.__contains__('e')` gives `True`

I tried to use unicode, Cyrillic letters and many other ways. Once output error was something like "symbol out of range", which supposes unicode script range, I guess. So, what am I doing wrong? How you extract glyphs from non-latin scripts?

PS: I'm using Ubuntu 20.04, python 3.8.10, fontforge 20190801

**Comment by chudotony** [comment]
Wow, now it works with this name! Many thanks, you helped me so much!

**Comment by ctrlcctrlv** [comment]
Sorry, this user emailed me personally so I'm more invested in what went wrong here and am reopening this therefore. The solution really confuses me.

Why would that have made a difference?

**Comment by ctrlcctrlv** [comment]
Hm—I meant to send @chudotony a reply but I didn't get around to it it seems but it's good since my answer was wrong, I misunderstood what was meant (I thought they were _assuming_ LATIN CYRILLIC SMALL LETTER ZHE would be named `zhe` despite that not being the case in the Adobe GLFN).

**Comment by skef** [comment]
I asked my question as a starting point to debugging, and because users frequently assume glyphs will be named one thing when they're actually named something else. I took the user's positive response as an indication that that's what happened. I'm not sure what else there is to do at this point.

**Comment by ctrlcctrlv** [comment]
Oh I get it. @chudotony put in the field "zhe" after noticing it wasn't there. Then, of course, the selection works. Thanks, I can be a bit slow.
