### ISSUE TITLE
How can you create Frac feature under Contextual Chaining Sustitutions

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5009]
1. I add new lookup in FF
2. Select Contextual Chaining Substitutions
3. Under that lookup I could not find any feature for Fractions
4. But, Windows system fonts like calabria has Frac feature is placed under Contextual Chaining lookup
5. So, how can you create thru FF UI or you have to write .fea file to import???
6. Since Frac feature needs to write Contextual Chaining Substitute code, should frac feature also be under CCS lookup as an option. Thanks

**Comment by skef** [comment]
You can just click on "New" on the pull-down menu (instead of the down arrow) and then type "frac" into the text box.

**Comment by waykyi** [comment]
Thanks a lot skef. I was used to using pulldown arrow to find feature options and never thought entering it by text. Thanks
