### ISSUE TITLE
How to set fontfamily=fontname

### ISSUE THREAD

**Issue by Firestar-Reimu** [fontforge/fontforge#5020]
I want to set `fontfamily=fontname`, so that on Windows all the fonts will not combined to one fontfamily. for example, cmb10 cmm10 cmmi10 will all named computer modern.

```
#!/usr/bin/fontforge
i=1
while ( i<$argc )
  Open($argv[i])
  SetFontNames($fontname, $fontname)
  i = i+1
endloop
```

I use this but not work.

**Comment by skef** [comment]
The first argument to `SetFontNames()` is the name for the individual font, the second is the name of the family. If you *don't* want the font files to be combined into one family, omit the second argument. If you want the font files to be in the same family but have individual names, set the first argument to something unique to each font file and the second to a common family name.

https://fontforge.org/docs/scripting/scripting-alpha.html#SetFontNames

**Comment by Firestar-Reimu** [comment]
OK I mean that the fonts have $fontfamily, but I want to set it to be as the same as fontname

or as you say, set it to none
