### ISSUE TITLE
cannot change path

### ISSUE THREAD

**Issue by Firestar-Reimu** [fontforge/fontforge#5026]
I want to open the font in folder 1 and folder 2. I wrote `openOTF.py` to open them.

```
Desktop 
├── openOTF.py
├── 1
│   ├── CMBSY7.otf
│   ├── CMBSY8.otf
│   └── CMBSY9.otf
├── 2
│   ├── CMCSC8.otf
│   └── CMCSC9.otf
```

this is openOTF.py

```python
import fontforge as ff
import os

folders = ["1/", "2/"]

for folder in folders:
    os.chdir(folder)
    print(os.getcwd())
    files = os.listdir("./")
    for font in files:
        print(font)
        f = ff.open(font)
        print(f.path)
    os.chdir("../")
```

but this is the output of `python open-otf.py`, which cannot find `CMCSC8.otf` in folder `2`, in fact it want to search `/home/firestar/Desktop/1/CMCSC8.otf`:

```
/home/firestar/Desktop/1
CMBSY9.otf
/home/firestar/Desktop/1/CMBSY9.otf
CMBSY8.otf
/home/firestar/Desktop/1/CMBSY8.otf
CMBSY7.otf
/home/firestar/Desktop/1/CMBSY7.otf
/home/firestar/Desktop/2
CMCSC8.otf
The requested file, CMCSC8.otf, does not exist
Traceback (most recent call last):
  File "/home/firestar/Desktop/open-otf.py", line 12, in <module>
    f = ff.open(font)
OSError: Open failed
```

it seems that `os.chdir("../")` changed the path to folder `2` but fontforge did not change the path (still in folder `1`).

**Comment by Firestar-Reimu** [comment]
> There isn't really an actual Python library there to know or care much what your Python instance considers to be the cwd.
> 
> I would strongly advise you to always prepare a fully qualified path yourself in Python when dealing with these kind of thin wrapppers/bindings to pieces of software like this.

So is it a bug? or a undone feature?

I have found a solution of:

```
files = glob.glob('./*/*.pfb')

for font in files:
    f = ff.open(font)
```

**Comment by Omnikron13** [comment]
> So is it a bug? or a undone feature?

I dunno, undefined I suppose. 

I guess the API reference should probably make it clear that the behaviour is undefined when given relative paths. (Alternatively the way the bindings are written could be changed to allow for small shims that could do things like injecting the python cwd to make things feel more 'native', but I'm doubtful there is much dev interest in doing that.)

**Comment by skef** [comment]
If you want to continue to use python's CWD you can also just call `os.path.abspath()` on your relative path before passing it into the fontforge module.

FontForge isn't written in Python and its Python module consists of the same C code compiled somewhat differently. It would probably be possible to synchronize environment variables between the two systems (which will be the same at `exec` time but can diverge after) but it would be tricky and isn't likely to happen.

**Comment by ctrlcctrlv** [comment]
Closing as wontfix per Skef's post.

**Comment by Omnikron13** [comment]
Would it be worth being a little more explicit about what `fontforge.open()` is expecting, or how it will treat what it is passed, in the documentation for it?
What it does is what I would personally have assumed it would do, but it seems the assumptions of somebody coming from Python may not be the same.
