### ISSUE TITLE
c++ use the libfontforge.so or fonrforge.so

### ISSUE THREAD

**Issue by HanWu1** [fontforge/fontforge#5027]
I have make install the fonrforge on UNIX，get the libfontforge.so and fontforge.so，
 but i donot   know what should i do to use the two file of ".so" in my c++ progaram;
where is the  API of  libfontforge.so?
where is the  API of  fontforge.so?

thanks,hope you kan give one hand: 

i just  want to achieve one c++ test tool that  convert some svgs to one ttf
like the python :
font = fontforge.font()
font.encoding = "UnicodeFull"
                for  unicode , svg_file  in   xxfiel:
		glyph =font.createChar(unicode,"font")
		glyph.importOutlines(svg_file)
font.generate("1.ttf")

thanks very much

**Comment by ctrlcctrlv** [comment]
`libfontforge.so` has an unstable API and isn't meant to be linked by non-FontForge consumers. I do it from Rust in [MFEKstroke](https://github.com/MFEK/stroke), but my use—and yours—is officially unsupported.
