### ISSUE TITLE
Build failure "ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by ACB-prgm** [fontforge/fontforge#5037]
I saw #4394 , but this did not seem to be relevant to me.

- [ ] The FontForge version and the operating system you're using
• FontForge March 2022 Release
• macOS Catalina 10.15.7

- [ ] The behavior you expect to see, and the actual behavior
expected to build without errors

- [ ] Steps to reproduce the behavior 
1. downloaded .zip source from [here](https://github.com/fontforge/fontforge/releases/tag/20220308)
2. unzipped and dropped to desktop
3. 
```
cd fontforge
mkdir build
cd build
cmake -GNinja ..
ninja
```
Error occurs with ninja build

This is the full error:
```
[145/280] Building C object fontforge/CMakeFiles/fontforge.dir/tottfgpos.c.o 
ninja: build stopped: subcommand failed.
```

[here](https://github.com/fontforge/fontforge/files/8841052/x.txt) is the terminal output from running `cmake -GNinja ..`

**Comment by ctrlcctrlv** [comment]
`ninja -d explain`?
