### ISSUE TITLE
fontforge-cygwin_2012_08_02: splines may become invisible

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#504]
The spline

```
SplineSet
1000 800 m 0
 0 348 -410 836 1000 0 c 0
EndSplineSet
```

is not shown.  When one select the lower point (1000,0) and moves its control point up or down sufficiently far, the curve appears again…

Example: https://gist.github.com/ilyaza/5316953

**Comment by skef** [comment]
The spline now appears with a vanilla GTK compilation (and likely appears with an X11/Cairo compilation). There may be compile flags that would reproduce the problem but these would be uncommon.
