### ISSUE TITLE
What does “自身相交” stand for? Is it a right/proper translation?

### ISSUE THREAD

**Issue by cheny0y0** [fontforge/fontforge#5042]

**Comment by ChiefMikeK** [comment]
[google](https://translate.google.com/?sl=auto&tl=en&text=%E8%87%AA%E8%BA%AB%E7%9B%B8%E4%BA%A4&op=translate ) = Self -intersect

**Comment by ChiefMikeK** [comment]
[Design With FontForge: Making Sure Your Font Works, Validation](http://designwithfontforge.com/en-US/Making_Sure_Your_Font_Works_Validation.html )  
> Fonts can have technical errors that prevent them from working or displaying correctly. For example, curves that intersect themselves will not render correctly because they do not have a “inside” and “outside”.

**Comment by ctrlcctrlv** [comment]
Translation issues should be discussed at Crowdin ( https://crowdin.com/project/fontforge ) per #3814.
