### ISSUE TITLE
SVG export of horizontal advance unreliable

### ISSUE THREAD

**Issue by rettinghaus** [fontforge/fontforge#5048]
When generating an SVG font some glyphs are missing the `horiz-adv-x` attribute, although a glyph width is set. 

At first I thought it is just missing for glyphs that follow the standard horizontal advance value defined on the font element. But I discovered that this seems to happen quite randomly. 

Also I find it difficult to set a specific `horiz-adv-x` value for the `font` element and then set it to "0" explicitly for non-width glyphs. I think it would be better to do it the other way round, i.e. assign every `glyph` element a `horiz-adv-x` attribute that has a non-zero value.

**Comment by Dimon-II** [comment]
I figured out the cause of the problem - this attribute is not written if the glyph size is the same as the default glyph size for the entire font. In SVG this is the top level tag font attribute horiz-adv-x="464"
