### ISSUE TITLE
Problems with default font on MAC version 12.4 

### ISSUE THREAD

**Issue by fitsarella** [fontforge/fontforge#5050]
Hello,

I recently downloaded the Font Forge Version 202203-08 version and I am experiencing troubles with the font display. 
After trying to read up on the issue here, I tried downloading the Deja vu sans and also the Unicode font but it didn't really solve the problem. Installing the unicode font showed a couple of glyphs but unfortunately the Font in Appearance Editor or in Save as etc. doesn't work.

see screenshots: 
![Bildschirmfoto 2022-06-17 um 11 58 49](https://user-images.githubusercontent.com/107681912/174277897-5c9b2f07-5418-4fd5-b283-03f54486b843.png)
![Bildschirmfoto 2022-06-17 um 11 59 17](https://user-images.githubusercontent.com/107681912/174277909-492feaac-023d-42f8-990b-d24887b2a81c.png)

As I have hardly any knowledge or skills of coding, I don't know how to solve this issue. 
would be really greatful if someone could help me out and give me a solution on how to solve this issue? 
would need a tutorial for coding dummies :D 

thank you so much! have a great day
cheers Felicitas

**Comment by skef** [comment]
The second screenshot is pretty normal -- a lot of those very-low-ASCII characters are control characters and they usually don't have associated glyphs.

Assuming you haven't done anything strange with your FontForge configuration before, the first screenshot implies that GDK (or something below it) can't find a reasonable monospace font corresponding to the string "monospace". I'm not sure what advice to give you on that as that mapping is supposed to "just work". However, it's possible that installing unifont on your system would be a work-around. Unifont is available at https://unifoundry.com/unifont/index.html and you probably want the normal TTF version.
