### ISSUE TITLE
Can't run FF Script in Windows 11 or Apple system

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5052]
I have a script below:

  # Import SVG files into MZ Unicode Part I
#Import SVG files into MZ Unicode Part I
FilePath = ( "C://My Documents/Font Development/Class/MZ/SVG/" ); 
SVG = "MZ-0"; # This need to Change!!!
i = 1;
j = 0;
.....   # Import function starts and loop thru all svg files

I got error dialogbox below:
![Unterminated line](https://user-images.githubusercontent.com/73824794/174491506-331c8015-9c10-42aa-b5a1-d6dad0afa3bd.png)

I am not sure there is any error in line1 which is only comment statement. So, what did I do wrong in here??? My friend tried in his Apple and he said it did not run. But other two friends were able to run in Windows 11/10 without problem. So, what could be the problem??? Can FF script run in Apple?

**Comment by skef** [comment]
Maybe a DOS vs Unix line termination thing?

**Comment by waykyi** [comment]
Thank you very much for your offer to help. I am attaching zip files of script, error image and svg files here. Thanks
[SVG.zip](https://github.com/fontforge/fontforge/files/8945934/SVG.zip)

**Comment by jtanx** [comment]
yea that's not from FF
