### ISSUE TITLE
feature request: File → Reload

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#5054]
Hi
in many cases we need to do some hack on source file with a text editor software, when return to the GUI we have to close the font and reopen it again, i suggest register an entry to File menu like "Reload" (with a confirm box on changed fonts) to reload it from memory.

**Comment by khaledhosny** [comment]
_File -> Revert File_ does this

**Comment by aminabedi68** [comment]
thank you @khaledhosny , i confirm that 👍
(i thought before, _File -> Revert,_ brings back the file to fontforge's own cache)
