### ISSUE TITLE
Installing FontForge 2022-03-08 on macOS

### ISSUE THREAD

**Issue by JoGilb** [fontforge/fontforge#5064]
Hi,

Trying to install FontForge 2022-03-08 on macOS 11.6.7
Download OK of a 63.7 MB DMG file.
Opening the DMG causes an error: "The following disk images could not be opened"

<img width="679" alt="Screenshot 2022-07-15 at 10 10 19" src="https://user-images.githubusercontent.com/101991717/179182567-65a5aa85-c750-4d77-921d-50ad3869b7e4.png">

Any idea please?

**Comment by JoGilb** [comment]
@dimitre Thanks, but I am not keen to install brew. 

I successfully installed the March 2020 version without any issue. The one available here: https://github.com/fontforge/fontforge/releases

So, there's definitely an issue with the March 2022 dmg file provided, either from the Fontforge website or from GitHub.

**Comment by jtanx** [comment]
Works for me on Monterey

**Comment by ctrlcctrlv** [comment]
@jtanx Hi. Are you OK with this issue being renamed to "FontForge application is not signed on macOS and a workaround is required", per #5102 and recent closure of #4082?

Just trying to keep these issues straight as it's a very common user problem.

**Comment by jtanx** [comment]
I don't think this one should be renamed, the original issue in this one seems more related to the dmg (which I cannot repro) rather than due to any signing issue.

**Comment by ctrlcctrlv** [comment]
How about reopening/renaming #5102?

**Comment by jtanx** [comment]
Sounds fine

**Comment by ctrlcctrlv** [comment]
Went with #5112 instead. Closing this as irreproducable and stale as it refers to v20220308. If the issue affects release v20230101, please open a new issue. Please include the SHA256 sum of the `.dmg` file in the new issue. If sums don't match your download is corrupt.
