### ISSUE TITLE
failing to build ocr-a font sources

### ISSUE THREAD

**Issue by alexmyczko** [fontforge/fontforge#5070]
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using: 20220308~dfsg-1 on debian sid
- [x] The behavior you expect to see, and the actual behavior: builds the font source, but doesn't
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

It appears newer fontforge software does more checks, and fails when input is not perfectly valid.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1015092

**Comment by jtanx** [comment]
I think this might be fixed on master, so maybe try the next release (should be out in a day or so)

**Comment by alexmyczko** [comment]
@jtanx Thank you, I confirm it fixes the problem.
