### ISSUE TITLE
Do we have latest 64bit build?

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5071]
Do we have latest 64bit build of Fontforge???
I installed March 2022 build and it shown up in Windows Task Manager as 32bit application. Do you have 64bit???

Seem like I can't import svg file get error message below: 

![image](https://user-images.githubusercontent.com/73824794/180593214-908f3a5f-7919-48c3-877e-4d7e435d328d.png)

![Star-01](https://user-images.githubusercontent.com/73824794/180610520-a43ad252-9b2f-451f-be2b-5e47971f7cf2.svg)

**Comment by ctrlcctrlv** [comment]
This won't solve your problem, but this line does look weird to me:

https://github.com/fontforge/fontforgebuilds/blob/b83e4d73389dfc6993ff9c502379ec4e1edaa1ad/ffbuild.sh#L169

Maybe we're not actually building a 64-bit binary?

**Comment by waykyi** [comment]
Thanks for the info.
