### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by MtYCNN** [fontforge/fontforge#5077]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
You need to give us a bit more to work with. Where did the build fail? What was the error?

**Comment by MtYCNN** [comment]
>The details of the error that occurred while typing ninja during installation are as follows. My system is Ubuntu 16.04, in a virtual environment, for Python 3.8.5.

ib/libfontforge.so.4: undefined reference to `TIFFOpen@LIBTIFF_4.0'
lib/libfontforge.so.4: undefined reference to `TIFFReadRGBAImage@LIBTIFF_4.0'
/root/picasso/yc7/anaconda3/lib/libfontconfig.so.1: undefined reference to `FT_Done_MM_Var'
lib/libfontforge.so.4: undefined reference to `TIFFGetField@LIBTIFF_4.0'
lib/libfontforge.so.4: undefined reference to `TIFFClose@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by jtanx** [comment]
needs more info e.g. the full output from running cmake, reopen if you add more info.
