### ISSUE TITLE
There should be: backup when saving a file; a file-opening window when closing the only font file window left

### ISSUE THREAD

**Issue by Scratchbin** [fontforge/fontforge#5085]
I was using version 2020-11-08. I accidentally triggered to save a big SFD file modded that I do not want to overwrite the original file. I terminated the programme then broke the file that a part of glyphs are gone.

- [ ] 1: Backup when saving a file, also make it able to cancel saving the file.

Enhance: When saving, create a file for temporary *backup* and replace the original file when done writing the *backup*. Make it able to cancel saving. Normally remove the *backup(s)* when quitting the entire programme that the *backup(s)* have been done for 14 days.

Reason: This solves the problem that corrupts file(s) by stopping the programme and the problem that accidentally saves file(s) "when there is/are no backup(s) and the file is huge wasting time to save".

- [ ] 2:

There should be a file opening window after closing the only window left for a font file.

Reason: This is good for situations that lack of memory left for the programme keeping from unwanted closes to the programme, especially when the PC has bad performance.

**Comment by jtanx** [comment]
There's already autosave and configuration that controls how many revisions to retain/how frequently to autosave. That problem is also mitigated if you have better revision control. 2. doesn't sound like a good enough reason to me.
