### ISSUE TITLE
FontForge does not save the glyph names and Unicode points of "unused" encoding slots in a custom encoding

### ISSUE THREAD

**Issue by Kiwilis** [fontforge/fontforge#5088]
When trying to save a font which uses a custom encoding as a .sfd file, FontForge only saves the glyph names and Unicode points of glyphs that are "used" (i.e. not removed when selecting «Remove Unused Slots» from the encoding menu) instead of saving them for all glyphs.

How to reproduce:
1. Create a new font.
2. Change encoding to custom.
3. Remove unused slots.
4. Create 2 new encoding slots.
5. Add a glyph name and Unicode point for both of them.
6. Draw something in one and leave the other one blank.
7. Save the font as a .sfd file.
8. Open the font again. The drawn character will have been save correctly, while the blank one is missing it's glyph name and Unicode point.

This issue was observed in FontForge version 20220308 on Ubuntu 22.04.

**Comment by ctrlcctrlv** [comment]
Not a bug, that's how it is meant to work.

If you want to be sure that your names hold over even for unfinished glyphs, you should define your encoding in a more robust way.

An example font is FRB Cistercian:

* https://github.com/ctrlcctrlv/FRBCistercian/blob/a350317aa96f041a0cf775544f583fa24d30963e/cistercian.enc
  * encoding file
* https://github.com/ctrlcctrlv/FRBCistercian/blob/a350317aa96f041a0cf775544f583fa24d30963e/cistercian.nam
  * nameslist file

Loading them Python example (also doable from UI in Encoding menu):
https://github.com/ctrlcctrlv/FRBCistercian/blob/a350317aa96f041a0cf775544f583fa24d30963e/make_font.py#L12-L13
