### ISSUE TITLE
Crash when using Validate

### ISSUE THREAD

**Issue by Alatius** [fontforge/fontforge#5090]
### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

Using the latest source code, running on Linux Mint 19.3.

As of commit f5d78b2 by @jtanx, I find that I cannot use the Validate command. FontForge crashes with the message
```fontforge: ../gdraw/ggdkcdraw.c:52: _GGDKDraw_CheckAutoPaint: Assertion `false && "No window should be drawing outside of expose calls"' failed.```

To reproduce:
1. Create a new font.
2. Open a glyph and draw some random spline, e.g. with the pen tool. Note: I think it is relevant that the points are placed at non-integer coordinates.
3. From the main window, run Element > Validation > Validate...
4. A dialog box will appear, asking about how to handle the non-integer coordinates.
5. Whatever button you click, FontForge will crash.

**Comment by jtanx** [comment]
This is similar to #5119, going to track this there.
