### ISSUE TITLE
Bad encoding information in 'cmap' table. Windows will reject fonts with an OS/2 version number of 0

### ISSUE THREAD

**Issue by Vimos** [fontforge/fontforge#5098]
For some self-crafted handwritten fonts, I came across this warning when loading them via fontforge.

The problem can be solved if I use `File->Generate Fonts...`.

(Just in case others may meet the same problem.)

If there are explanations over the issue, or simple command lines to detect such warnings, please drop me a hint.

**Comment by ctrlcctrlv** [comment]
Issue seems explained by the message?

Go to Element→Font Info and raise version above 0?
