### ISSUE TITLE
Can't open sfdirs anymore; they are treated as regular folders

### ISSUE THREAD

**Issue by CG-Tespy** [fontforge/fontforge#5100]
Version: 08-03-2022
OS: Windows 10

The issue is described aptly in the title. As things are now, I can't even open projects.

**Comment by skef** [comment]
@CG-Tespy this seems to have been fixed since the last release. Try the current development version, perhaps by downloading and unpacking MINGW32 from https://github.com/fontforge/fontforge/actions/runs/3115421135

**Comment by CG-Tespy** [comment]
It's fine, I installed the 1-08-2019 version and the issue wasn't there. That version fulfills my needs just fine, but if I need newer features in the future, I'll consider trying a dev version like you suggested
