### ISSUE TITLE
Yen sign instead of backslash

### ISSUE THREAD

**Issue by Ayron64632723837** [fontforge/fontforge#5103]
Just a problem with the font in the glyph header, it's not tied to a cell or file
FontForge version: 20220308
OS: Windows 10

![image](https://user-images.githubusercontent.com/96698378/189601875-1414d073-8913-4504-8ec0-45ca04c18f22.png)

**Comment by jtanx** [comment]
https://superuser.com/questions/1167662/why-is-windows-10-displaying-as-%C2%A5-on-the-command-line
