### ISSUE TITLE
Can't open saved sfd file.

### ISSUE THREAD

**Issue by hilmiyafia** [fontforge/fontforge#5115]
I have created a simple font using inkscape. Then open it in fontforge and save it. But when I want to reopen the file, the glyphs are gone. Here's what it's look like in fontforge. I also attached the sfd file:

[Simple.zip](https://github.com/fontforge/fontforge/files/9716169/Simple.zip)

![Missing](https://user-images.githubusercontent.com/56539775/194077496-f662f016-d41e-444c-9722-79e23831fa29.png)

**Comment by ctrlcctrlv** [comment]
That's a corrupt .sfd all right. Somehow it's got `StartChar:`'s with no glyph names following.

Fixed it for you, but there are only two glyphs in the font besides the .notdef, sorry. If you have no other backup all else is lost.
![image](https://user-images.githubusercontent.com/838783/194691109-ea1095c9-fe19-4c63-a31b-b871329b3f71.png)
[Simple.zip](https://github.com/fontforge/fontforge/files/9738492/Simple.zip)

Without knowing anything about your session that led to the corrupted save, fixing the bug that caused this corruption is probably not possible.
