### ISSUE TITLE
Font Generated wont remember the glyphs.

### ISSUE THREAD

**Issue by pakosaan** [fontforge/fontforge#5116]
It wont apply the custom glyphs made in the custom slots. why?
It sont render in the word libre-word or any editor

**Comment by Bry10022** [comment]
Did you, by any chance, create any GSUB lookups in the font file? You need to create lookups if you want glyph substitutions?
To remember which glyph it is, I usually give it a name, like `one.pnum.onum`, or `zero.zero`, or even `Aacute.alt`.
