### ISSUE TITLE
(Solved) Newer versions of FontForge crash when opening TTF/OTF files.

### ISSUE THREAD

**Issue by Mintsoda15** [fontforge/fontforge#5118]
![화면 캡처 2022-10-07 101700](https://user-images.githubusercontent.com/42484758/194446369-aa9c4f69-b81a-4443-ab60-4ed64bb760a6.png)
![화면 캡처 2022-10-07 101800](https://user-images.githubusercontent.com/42484758/194446381-1db498e3-50b6-4e31-b822-692376c17c82.png)
This is the March 8, 2022 version.(Windows 10)
FontForge crashes when opening TTF or OTF files with this version.

**Comment by skef** [comment]
Neither the current master branch nor the source compiled from the 20220308 tag crashes when opening FreeSerif.ttf downloaded from https://github.com/byrongibson/fonts/tree/master/backup/truetype.original/freefont . Please both check that file against your installation of FontForge and attach the file that is causing you problems here (you may need to put it in a zip archive).

**Comment by Mintsoda15** [comment]
Maybe the program on my PC has been modified. Uninstalling and reinstalling solved the problem.

**Comment by skef** [comment]
It happens!
