### ISSUE TITLE
GGDKDraw assertion failure when using ruler

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#5119]
@jtanx when I use the ruler tool in the current master (Arch Linux, debug build) I get an assertion failure just when the tool snaps to the second point: `fontforge: /home/skef/src/ff3/gdraw/ggdkcdraw.c:52: _GGDKDraw_CheckAutoPaint: Assertion 'false && "No window should be drawing outside of expose calls"' failed.`

I've only tried with a couple files (always cubic so far) but it seems to happen every time.

**Comment by skef** [comment]
This is also happening when I switch from the foreground to the background on the layer pallet. Seems like this may be a serious problem.

**Comment by jtanx** [comment]
Thanks, yeah this is related to #4949. Right now this won't matter when on GDK, but please continue to report all instances of these as we'll need to fix all of them eventually. I'll put up a PR to fix these ones.
