### ISSUE TITLE
Font shows incorrect name when installed on MacOS

### ISSUE THREAD

**Issue by ritualisticoffee** [fontforge/fontforge#5121]
After installing a font generated in FontForge, it shows up in Font Book (see below). The issue is the same whether I generate it as a OpenType or TrueType font.

<img width="880" alt="CleanShot 2022-10-07 at 16 29 46@2x" src="https://user-images.githubusercontent.com/36229763/194591595-6661d421-ac6b-4244-bf1c-2678d2965904.png">

If I click on show in finder it shows the font correctly titled. I'm not sure if this is an issue with Font Book, or something to do with some setting within FontForge but I've had no luck searching for solutions so I thought this a good place to post.

I've downloaded a few other fonts - both OpenType and TrueType - and both show up in Font Book under the correct name.

I am running MacOS Monterey 12.1 and FontForge Version 2020308.

* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by ctrlcctrlv** [comment]
Go to Element→Font Info, make sure both PostScript Names and TTF Names are set.

**Comment by ritualisticoffee** [comment]
Thank you!
