### ISSUE TITLE
Set Both Bearing dose not work as expected

### ISSUE THREAD

**Issue by aminabedi68** [fontforge/fontforge#5123]
hi
@ctrlcctrlv i think it's related to this fix #4693

https://user-images.githubusercontent.com/25493297/194712808-1e192fb4-872d-40c2-a48a-be856ae38ad1.mp4

**Comment by samiel60** [comment]
It's the same of "Wrong behavior of: Metrics - Set Both Bearing #4955"
which I opened on 18 March

**Comment by jtanx** [comment]
Going to close this to track in #4955.
