### ISSUE TITLE
修改win10的SimSun“宋体”,一些软件的界面发生变化(不正常),请问什么原因呢？？

### ISSUE THREAD

**Issue by wwzrh** [fontforge/fontforge#5145]
![修改win10的SimSun“宋体”,一些软件的界面发生变化(不正常),请问什么原因呢？？](https://user-images.githubusercontent.com/12047479/202647394-5390a7b8-01b0-4338-9d95-45ebeacba3ff.png)

**Comment by ctrlcctrlv** [comment]
I'm sorry, I can't speak Chinese. Please write the text on the image in English, or alternatively, at least put it in a text format so DeepL can take a crack at it.
很抱歉，我不会说中文。请把图片上的文字写成英文，或者至少把它写成文本格式，这样我就可以用 DeepL 来尝试翻译了。

**Comment by wwzrh** [comment]
Modify win10 SimSun "Song style", some software interface changes (abnormal), excuse me what reason?
----------------------------------
1、In win 10, simsun.ttc does not change the normal excel save interface (normal size).
2、Use FontForge \ FontCreator to add some characters to the "Song style" of SimSun in win10 system Simsun. ttc, such as ext-G area (U+30000) font, etc. The excel save interface is lengthened (abnormal). (Decomposed and merged with unitettc)
3、What's the reason?
@ctrlcctrlv

**Comment by ctrlcctrlv** [comment]
Thanks for explaining~ !
Unfortunately, I don't have an exact answer
There could be any number of reasons, the question is too broad
FontForge can't really properly edit complex already-compiled proprietary fonts such as those by Microsoft, Apple, and Google, without making some mistakes
We mostly use it to work on libre fonts; you should consider using other tools to merge fonts, and revert `Simsun.ttc` until then…
And, if you have more time, you could consider trying to isolate the problem and create a minimal test case so the bug can be solved. It's either misinterpreting the font on read-in to SFD format internally, or doing the write out as TTF Collection improperly.

---

謝謝你用英語解釋〜〜！
不幸的是　我沒有一個確切的答案
可能有很多原因　這個問題太廣泛了
FontForge不能正確地編輯複雜的已經編譯好的專有字體，如微軟，蘋果和谷歌的字體，而不會犯一些錯誤。
我們主要是用它來處理自由字體；你應該考慮使用其他工具來合併字體，並在這之前恢復 `Simsun.ttc` ……
而且，如果你有更多的時間，你可以考慮嘗試隔離這個問題，並創建一個最小的測試案例，這樣就可以解決這個錯誤了。它要么是在內部誤解了讀入時的字體為SFD格式，要么是在做寫出時的TTF集合時不正確
