### ISSUE TITLE
Repeated crashing when trying to open a font

### ISSUE THREAD

**Issue by Pigeon43** [fontforge/fontforge#5154]
## What happened
I changed a setting in the View menu (I cant remember which sorry) and then it would crash each time I tried opening a font. I reinstalled it, thinking it would solve the issue but it is still crashing despite being a fresh install.
* Only crashes when trying to open a font
* Happens with all font types (`.ttf`, `.otf`, `.woff2`)
* Happens with all fonts (including unedited ones from Google fonts, for example)

I had been running everything perfectly fine up until just now, so I can only assume it was the change I made in the View menu, but I tried deleting the application (and it's sibling directories/files) and then installing a fresh version, but it still breaks.

## Info
* Running on Windows 10

**Comment by skef** [comment]
I think we've heard about this happening before when a user turns of anti-aliasing. You probably need to edit or delete the configuration file, which is probably somewhere in your "AppData" folder, which is hidden by default. Try following these instructions to see the folder and then see if you can find the config file: https://www.lifewire.com/find-and-use-the-appdata-folder-in-windows-4771752

**Comment by Pigeon43** [comment]
YES. That sounds like it! I'll try what you suggested and report back.

Thank you! :)

**Comment by Pigeon43** [comment]
All good now! Thanks so much! :D
