### ISSUE TITLE
Save failed due to bug with naming

### ISSUE THREAD

**Issue by blobbiestfish** [fontforge/fontforge#5155]
This bug occurs every time I try to save. It's rather hard to concisely explain, so I'll just give a step-by-step of how it always happens on my end.

---

1. Open a new file, make any glyph. (I used the M character)
2. File > Save
3. Save failed dialogue box pops up

A message now pops up in the Warnings window saying this:
```
You tried to save with the filename font but it was saved as font.sdf.
Please choose File/Generate Fonts to save to other formats.
```
If I try to append `.sdf` to the end of the name while saving, it just says "Save failed" without any warning in the Warnings window.

---

I am using Windows 10 with FontForge's version being version 20220308.

**Comment by klei1984** [comment]
I have the same or a similar issue with that release version on Windows. In my case saving does not work at all to mounted vhdx virtual drives.

I downloaded the latest github actions windows mingw64 successful build artifacts and that worked for me. It is not a release version, it might have other issues, but at least it can save your work.
