### ISSUE TITLE
FontForge Is Removing OpenType Features And Replacing Them With Weird Ones

### ISSUE THREAD

**Issue by Sayhone721** [fontforge/fontforge#5158]
- [X] Screenshot
Source Files:
![Screenshot (89)](https://user-images.githubusercontent.com/92538982/209686885-aa2d7d6a-91d2-4d34-8214-1628122ada1d.png)
Generated TTF:
![Screenshot (90)](https://user-images.githubusercontent.com/92538982/209686984-4b25a238-fb0f-47fa-8e5c-d7de971d290c.png)
- [X] The FontForge version and the operating system you're using
FontForge Version: 3/8/2022
- [X] The behavior you expect to see, and the actual behavior
I expect it to generate the OpenType features that the font has.
What it actually does is replace them with weird ones like Right To Left Alternates.
- [X] Steps to reproduce the behavior 
1. Open any file that you can open in FontForge.
2. Generate the file.

**Comment by ctrlcctrlv** [comment]
Those are [Apple Advanced Typography](https://en.wikipedia.org/wiki/Apple_Advanced_Typography) features, not "weird ones".

Make sure OpenType export is actually checked on export time.

**Comment by Sayhone721** [comment]
Thanks for helping me out. Now the .ttf is working.

**Comment by ctrlcctrlv** [comment]
No problem :o)
