### ISSUE TITLE
it's terrible experience when i try to edit Adobe Source Han Sans by fontforge .  everything seem be ok , but when i try to generate a ttf file ,the order was wrong

### ISSUE THREAD

**Issue by Plainct** [fontforge/fontforge#5161]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround
- [ ] 
![image](https://user-images.githubusercontent.com/120462767/210032265-0d453cb8-a570-482a-a50f-4925547f0f84.png)
for example the “，” become“ヌ”
and the “？" become "ミ”

**Comment by ctrlcctrlv** [comment]
You must flatten CID fonts for export to have a chance of working. See https://github.com/fontforge/fontforge/pull/3955#issuecomment-640979727 and [#D6](https://github.com/fontforge/fontforge/pull/3955#issuecomment-640979727).

**Comment by Plainct** [comment]
![image](https://user-images.githubusercontent.com/120462767/210037565-f2a6bbec-2c0c-4e7e-8071-aeb839f3f2e3.png)
i have flatten it , but the order of graph is not right

**Comment by Plainct** [comment]
when i flatten by cmap
![image](https://user-images.githubusercontent.com/120462767/210038020-60b7eb11-eda9-4e62-a941-0d47f26508e0.png)
![image](https://user-images.githubusercontent.com/120462767/210038055-9ccfb4d0-a4e5-4eea-953b-e69a4f0a8d24.png)
the order seem like OK.
but after generate new file , the order still wrong.(the same as the order when i press "compact")
![image](https://user-images.githubusercontent.com/120462767/210038183-0f1aa9dd-a4d1-4483-a532-8553d3dc99de.png)

**Comment by Plainct** [comment]
![image](https://user-images.githubusercontent.com/120462767/210038287-62e0b5a0-1c83-49fe-a84c-0bab241ef2ff.png)

**Comment by Plainct** [comment]
this is the normal version
![image](https://user-images.githubusercontent.com/120462767/210038367-35d44d61-0959-463c-bf6b-fed326568f20.png)

**Comment by ctrlcctrlv** [comment]
After you do the flatten by CMap, try to re-encode as Unicode (Encoding menu)

**Comment by ctrlcctrlv** [comment]
> this is the normal version ![image](https://user-images.githubusercontent.com/120462767/210038367-35d44d61-0959-463c-bf6b-fed326568f20.png)

我是一个外国人，不是一个白痴 (・∀・)
我可以清楚地看到，u不见了，ヌ出现在不应该出现的地方。没有必要发表明显的跟帖。每次你的回复，我都会收到电子邮件。

**Comment by Plainct** [comment]
> a

![image](https://user-images.githubusercontent.com/120462767/210039079-85459b35-1dff-41b0-bd45-7d690dd4f193.png)
i have tried it and also generate a ttf file ,but the order still wrong

**Comment by ctrlcctrlv** [comment]
Please email the file to copypaste@kittens.ph or upload it in a .zip file here.

**Comment by Plainct** [comment]
[issues5161.zip](https://github.com/fontforge/fontforge/files/10323275/issues5161.zip)
My fontforge version is 20220308

**Comment by Plainct** [comment]
[issues5161sfd.zip](https://github.com/fontforge/fontforge/files/10323283/issues5161sfd.zip)

**Comment by ctrlcctrlv** [comment]
I'm unable to reproduce your issue.

I think you didn't follow my instructions quite right, or perhaps I wasn't clear enough.

> You must flatten CID fonts for export to have a chance of working. See https://github.com/fontforge/fontforge/pull/3955#issuecomment-640979727 and [#D6](https://github.com/fontforge/fontforge/wiki/Community-guidelines#d6-cid-keyed-fonts).

But now I notice you did the other operation, `FlattenByCIDMap`. Don't do this.

Do instead:
* CID→Flatten.
* Encoding→Re-encode→ISO 10646-1 (Unicode, Full)

Then try again with:
* File→Generate Fonts.

![image](https://user-images.githubusercontent.com/838783/210075435-5ff50b8f-4adc-4cfd-bbb9-ad2c1d5375c8.png)

Here's the TTF FontForge gave me which has no obvious glyph mapping issue: 
[SourceHanSansCN-Medium.ttf.zip](https://github.com/fontforge/fontforge/files/10324924/SourceHanSansCN-Medium.ttf.zip)

It may, however, have other issues. If all you want to do is OTF→TTF, FontForge is not the best tool for the job. Consider `otf2ttf` command in AFDKO.

**Comment by ctrlcctrlv** [comment]
By the way, I am cognizant of how annoying this is. And I agree, FontForge should handle CID-mapped fonts better, even though they are, excluding the single case of variable CFF2 fonts with multiple masters, a legacy format.

I did some research into the code a few years ago and determined it'd be way more work than I'm willing to put in, but any interested developer is free to search the bug tracker for "CID" and try to fix either the bugs I found or new bugs.

顺便说一下，我知道这有多烦人。我同意，FontForge应该更好地处理CID映射的字体，尽管除了具有多个字体主站的可变CFF2字体的单一情况外，它们是一种遗留格式。

几年前，我对代码做了一些研究，发现它比我愿意投入的工作要多得多。但是，任何有兴趣的开发者都可以在缺陷追踪器中搜索 "CID"，并尝试修复我当年发现的缺陷，或者新的缺陷。

**Comment by Plainct** [comment]
i have tried it  ,but it seem not work for me. i also reinstall fontforge and it still not work.
![image](https://user-images.githubusercontent.com/120462767/210078347-3a4f3627-382c-40eb-a676-3790e7079e12.png)

**Comment by ctrlcctrlv** [comment]
Hmm. Maybe there have been CID fixes since 20220308.

**Comment by ctrlcctrlv** [comment]
Yes there have been a few. Please try one of the latest artifacts.

If you don't know how to download the latest artifacts, please see this page: https://github.com/MFEK/glif/wiki/Getting-the-latest-artifact.

It's for a different project, but the instructions are identical. Just use fontforge/fontforge as the base instead of MFEK/glif.

我看了`git日志`，是的，有几个CIDMap相关的补丁。请尝试一下夜间的开发者二进制文件（"Artifacts"）。

如果你不知道如何下载最新的二进制文件，请看这个页面：https://github.com/MFEK/glif/wiki/Getting-the-latest-artifact。

这些说明是针对一个不同的项目，但你需要做的事情是相同的。只是使用fontforge/fontforge作为Git仓库，而不是MFEK/glif。

**Comment by Plainct** [comment]
Thank you for your time to do this, it work, when i upgade to the latest artifacts.

**Comment by ctrlcctrlv** [comment]
I'm glad! And apparently we're making a new release shortly, so it'll be fixed for everyone. Thanks for the report and for bearing with me as I don't speak Chinese well. Happy Year of the Rabbit!
