### ISSUE TITLE
Crashes when adding new TTF Name for particular languages in Font Info

### ISSUE THREAD

**Issue by Albrecht-SVG** [fontforge/fontforge#5162]
- [ ] Screenshot
- [x] The FontForge version 20220308 / Windows 10
- [ ] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
       - Choose "Element -> Font Info..."
       - Select "TTF Names"
       - Click `<New>` and select "Czech"
       - The application crashes
       - This also happens with at least the following languages:
           Bulgarian, Estonian, Finnish, Flemish, German Liechtenstein, German Luxembourg, German Swiss
           Italian Swiss, Africaans, Croatian, Frisian, Latin, Maltese, Portuguese, Turkish, Welsh

- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by jtanx** [comment]
Seems like this is fixed on master, try one of the CI builds eg https://github.com/fontforge/fontforge/suites/10097995623/artifacts/492294363

**Comment by jtanx** [comment]
Actually seems like I can repro this on linux
