### ISSUE TITLE
Scripting Layers: impossible?

### ISSUE THREAD

**Issue by ilyaza** [fontforge/fontforge#517]
Apparently, using GUI I can do certain operations on different layers, and I can copy outlines from one layer to another.  Looking at documentation in https://github.com/fontforge/fontforge.github.com/blob/master/en-US/documentation/developers/sfdformat.md, I cannot find any way to do it from scripts.

What I want: I generate `.sfd` with strokes in `Fore` layer, and outlines in `OUTL` layer.  I want to load this into FF, and script: do ExpandStroke() on `Fore` in all glyphs, then do: copy outlines from `OUTL` to `Fore`, and discard `OUTL`.  Do I miss something?  Or is documentation/scripting support incomplete?

**Comment by sergey-s-betke** [comment]
Any information about this problem? Simple task: how I can copy strokes from `Back` layer to `Fore` layer for `ExpandStroke()`?

**Comment by sergey-s-betke** [comment]
We need `CopyLayerToLayer`, scripting version (`scripting.c`).

**Comment by ilyaza** [comment]
On Tue, Mar 03, 2015 at 11:48:55AM -0800, Sergey S. Betke wrote:
> We need `CopyLayerToLayer`, scripting version (`scripting.c`).

One may also need “Choose This Layer as Active layer for glyph editing
functions”.  This may be “faked” with CopyLayerToLayer, but would
require tons of extra layers:

  instead of 	Modify Layer1   one would do	Modify Layer1
  	  	  …    		    	  	Copy 1 —→ 11
		  …				Clear 1
		  …				Copy 2 —→ 1
  	  	Modify Layer2			Modify Layer1
		Copy 2 —→ 1			Copy 11 —→ 1

  [time goes vertically!]

with 11 an “extra” layer.  If one needs to merge many layers this way,
one would need many “extra” layers.

Ilya

**Comment by skef** [comment]
I'm answering this for python only, as I haven't used the native language much. 

Most of the spline-modifying scripting commands are layer-specific. The layer they operate on is determined by the setting of `glyph.activeLayer` 

There is also the fontforge `layer` object, which can be used to copy spline data between layers, as well as layerrefs and so forth. 

This seems like enough info given the question asked and age of this issue. If you still have other questions feel free to open a new one.
