### ISSUE TITLE
fontmake won't recognize generated UFO3 file

### ISSUE THREAD

**Issue by Panogen** [fontforge/fontforge#5187]
fontforge.version() : 20220308
Windows 11 ver. 21H2

I am trying to generate a font through `fontmake` and have so far been unsuccessful. I start by creating a font (or opening an existing one) and using Generate Fonts to create a UFO3 directory of the font. That all appears to work without error. However, when I try to compile the font using `fontmake`, it tells me that the *entire* fontinfo.plist file is wrong. See here:
![image](https://user-images.githubusercontent.com/73259774/215239787-94a2fbfe-1f96-4ac2-aa9d-5bb821a8bafc.png)
I can't tell whether this is an issue with FontForge or `fontmake`. I am not familiar with the UFO specification so I cannot determine whether or not fontinfo.plist is actually formatted correctly. I am posting here so that I don't bother the fontmake developers with a non-issue, as I'm sure if it's an issue with them it would have been brought up already, and I can't find any posts with the same problem as me.

I had this problem on both a font I've been working on and a new font, [Tokida Sans (exported UFO)](https://github.com/fontforge/fontforge/files/10525095/TokidaSansRegular.ufo3.zip). The only changes I made to Tokida were to add some glyphs, change some names and fill out the PS Private table.

I am guessing there's something wrong with the way FontForge exports UFOs.

**Comment by jtanx** [comment]
use 20230101

**Comment by Panogen** [comment]
It worked. Thanks guys!
