### ISSUE TITLE
ffpython says encoding out of range, trying to select a glyph I just created.

### ISSUE THREAD

**Issue by Panogen** [fontforge/fontforge#5189]
fontforge.version(): 20230101
Windows 11 ver. 21H2

Title is self-explanatory. It doesn't matter if the glyph is named or not. A workaround is possible using the glyph name instead of the unicode value. See screenshot:
![image](https://user-images.githubusercontent.com/73259774/215309314-87e69a0a-56a0-494a-90d3-07a600b38eec.png)
Have I perhaps misunderstood the documentation for `select()`?

**Comment by jtanx** [comment]
Python/Windows problem, it's Python is not making stdout unicode

**Comment by ctrlcctrlv** [comment]
Probably encoding of STDIN/STDOUT, which Windows does weird stuff to. Try running through a shell like MSYS2.

**Comment by Panogen** [comment]
I'm confused though. The inputs of both arguments were both `0xe000`, so if there's some encoding error shouldn't it affect both of them the same way, therefore canceling out the problem?

**Comment by dscorbett** [comment]
The problem is not specific to Windows. U+E000 is not in the font’s encoding. Switching to `UnicodeBmp` or `UnicodeFull` fixes it.
```pycon
>>> font.findEncodingSlot(0xe000)
-1
>>> font.encoding = "UnicodeBmp"
>>> font.findEncodingSlot(0xe000)
57344
>>> font.selection.select(0xe000)
<fontforge.selection object at 0x10e804990>
```

**Comment by Panogen** [comment]
But I added the encoding myself using createChar() before using select().

**Comment by Panogen** [comment]
I still think there's something wrong with the `select()` function. If you look at the screenshot, FontForge understood `font.createChar(0xe000)` perfectly fine. It's the `select()` function that's having problems. I just find it hard to believe this is a Windows bug.

**Comment by Panogen** [comment]
![image](https://user-images.githubusercontent.com/73259774/216517265-36464f14-ddef-48c3-b223-fbb5929ecc6f.png)
From this it looks like `select()` is interpreting the argument as an encoding index rather than a unicode value, even when I specify unicode as the argument type.
