### ISSUE TITLE
Cannot Import Fontforge using ffpython. "DLL load failed while importing fontforge: The specified procedure could not be found."

### ISSUE THREAD

**Issue by visusys** [fontforge/fontforge#5213]
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot

First screenshot is just to show my version of python:

![pwsh_koVeJyZifT](https://user-images.githubusercontent.com/33441569/224519935-ea86ee59-38be-47e6-a473-50b92c76b503.png)

`Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32`

Second screenshot is me calling `ffpython` and then calling `import fontforge` from an activated venv (called `FontTools`). The import fails with an error message of: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing fontforge: The specified procedure could not be found.
```

![pwsh_013lakyAyM](https://user-images.githubusercontent.com/33441569/224519806-5d02fd2f-1598-461a-8b3f-9d0886e98a98.png)

Third screenshot is me calling `ffpython` after opening `C:\Program Files (x86)\FontForgeBuilds\fontforge-console.bat` and then **magically "import fontforge" works as expected.**

![cmd_GVcUORPnwr](https://user-images.githubusercontent.com/33441569/224519999-1e995fc7-e7f9-4606-bbc6-b6dedf51de50.png)

- [x] The FontForge version and the operating system you're using

Fontforge Version:

```
Version: 20230101
 Based on sources from 2023-01-01 05:31 UTC-ML-TtfDb-D-GDK3.
 Based on source from git with hash: a1dad3e81da03d5d5f3c4c1c1b9b5ca5ebcfcecf
 ```
 OS: Windows 10 Pro x64

- [x] The behavior you expect to see, and the actual behavior

I expect `import fontforge` to succeed after calling ffpython. My scripts are failing because I can't import the fontforge module.

The actual behavior is that `import fontforge` only works in the terminal that is launched after opening `"C:\Program Files (x86)\FontForgeBuilds\fontforge-console.bat"`

- [x] Steps to reproduce the behavior 

1. Install the latest version of FontForge
2. Run `C:\Program Files (x86)\FontForgeBuilds\fontforge-console.bat`
3. Add `C:\Program Files (x86)\FontForgeBuilds\bin` to your PATH environment variable.
4. Open a fresh console, optionally with Admin privileges, and call `ffpython`
5. Once you enter the Python interpreter, type `import fontforge`
6. You should see an error: **ImportError: DLL load failed while importing fontforge: The specified procedure could not be found.**

- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

Just as an addendum, the reason I am trying to get this working is that I have several font related scripts that leverage the fontforge module. I am calling these scripts in PowerShell with: 

`& ffpython "D:\Dev\Python\FontTools\VSYS\ConvertTTFToSVG.py" $CurrentFile` 

$CurrentFile is just a variable containing the path to a font. 
`ConvertTTFToSVG.py` is choking on the `import fontforge` statement.

I had this all working a few months ago, but I re-installed my OS recently and I'm trying to get things working again.

I could REALLY use any help or guidance. Thanks so much.

**Comment by visusys** [comment]
Adding a dump of environment variables from `C:\Program Files (x86)\FontForgeBuilds\fontforge-console.bat`:

![cmd_c8lUw3Olqo](https://user-images.githubusercontent.com/33441569/224524594-8688e8b3-bcaf-43e9-84de-701ee74e2443.png)

Here's my system PATH environment variables:

![rundll32_3GPeM6p3Tm](https://user-images.githubusercontent.com/33441569/224524639-b9fcc5a9-cd6d-4326-87c5-d8ad6509b17b.png)

Not sure if this will help, but the more information the better, I guess.

**Comment by jtanx** [comment]
Use the provided bat file, your env vars are setup wrong otherwise.

**Comment by visusys** [comment]
I've already used the bat file. How is this a solution? I can't automate anything then. You're telling me I need to manually open the bat file and then manually execute my script every time I want to use it? 

I need to be able to call `ffpython` from other environments, like PowerShell, or any other scripting environment.

Is there a way to set the environment variables manually in a script?
