### ISSUE TITLE
Anchor Points Aren't Working When You Generate A Font

### ISSUE THREAD

**Issue by Sayhone721** [fontforge/fontforge#5219]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using. Windows 11. Fontforge 1/1/2023.
- [X] The behavior you expect to see, and the actual behavior
 I expect it to generate all the anchor point classes, and use the correct ones, but it didn't.
Expectation: ![Screenshot (5)](https://user-images.githubusercontent.com/92538982/226214577-559ab211-4fb6-4d79-ac65-7223abe9d69e.png)
Reality: ![Screenshot (7)](https://user-images.githubusercontent.com/92538982/226214611-16753f3e-9f7e-42fe-92f1-d2c6c4d4db5e.png)
- [X] Steps to reproduce the behavior. 1. Add anchor points to a font. 2. Add `mark` to the GPOS features. 3. Generate the font.

**Comment by ctrlcctrlv** [comment]
Not understanding. Please make a video and upload ZIP of font.

**Comment by Sayhone721** [comment]
Now it's working.
https://user-images.githubusercontent.com/92538982/227067224-e2bcc2ba-cd3c-4e45-a227-15a0ea64d353.mp4

**Comment by ctrlcctrlv** [comment]
Still want to see if broken in video. Please split the file into 25MB chunks.

**Comment by ctrlcctrlv** [comment]
On GNU/Linux command is:

```bash
split --numeric-suffixes INPUT.VIDEO
```

Then zip them all one by one.

**Comment by Sayhone721** [comment]
I don't have Linux, but I know what to do.

**Comment by Sayhone721** [comment]
I don't have Linux, but I know what to do.

**Comment by Soilad** [comment]
> Now it's working. I didn't upload the video because it was too big. ![Screenshot (9)](https://user-images.githubusercontent.com/92538982/227068411-2187e2c2-5152-4c68-9d6a-0a53d1e843a8.png)

are you not gonna tell how u fixed it??

**Comment by Bronnel721** [comment]
> are you not gonna tell how u fixed it??

I would, but I forgot how I did it correctly, and I can't even do it anymore.

I honestly don't care that much since many styles of my fonts are [interpolated](https://fonts.google.com/knowledge/glossary/interpolation) (and also my fonts have many styles too) and the anchor points are not interpolated when I interpolate between two fonts, and I don't wanna import them from another style and tediously fix the placement of the anchor points in the interpolated styles either.
