### ISSUE TITLE
Impossible to search in material icons

### ISSUE THREAD

**Issue by boubou158** [fontforge/fontforge#5225]
Hi,

I am trying to remove some icons I do not use in my project from the Material Icons font and regenerate it.
It is not working, i can't search anything on the file. Trying to search for a code point found on https://fonts.google.com/icons?icon.query=information for instance do not work. Neither trying to search "information" directly.

How can i do to remove the unused icons from this font?

Thank you

**Comment by adbac** [comment]
Hi,

How have you exactly searched for the codepoint? Writing "e88e" in the dialog doesn't work, you need to write "unie88e". It works for me.
If you want to have a clean view of all the icons, go to the **Encoding** menu and then click **Compact**, it makes it easier to select and clear the glyphs you don't need.

I hope this will help you

**Comment by boubou158** [comment]
Thanks a lot @adbac , this was exactly what I was looking for!
Do you mind telling me how once I remove the glyphs, how to "condense the font" as described in this article in Remove unused selectors from the font file part: https://www.shedloadofcode.com/blog/reduce-material-design-icons-font-to-7kb-and-automate-with-pyautogui

**Comment by adbac** [comment]
Are you referring to this quote ?
<img src = "https://user-images.githubusercontent.com/126618591/230459568-d7158255-7201-4589-93b6-ffe78b960673.png" height="100px">
If this is the case, I think the author of the article meant "Compact", as I explained it in the previous comment:
> If you want to have a clean view of all the icons, go to the **Encoding** menu and then click **Compact**, it makes it easier to select and clear the glyphs you don't need.

**Comment by boubou158** [comment]
Hi @adbac ,

Whatever i try (using the woff2 or the ttf), when I compact then select some specific unicodes, invert the selection, then detach and remove glyphs and generate fonts, i cant access the icons anymore. I have this warning in fontforge: 
Lookup subtable contains unused glyph X making the whole subtable invalid

Then the icons are not displayed anymore on a test index.html trying to display some material icons.

Do you have any suggestions?

Thank you
