### ISSUE TITLE
Download fail - Virus detected

### ISSUE THREAD

**Issue by davidxmartins** [fontforge/fontforge#5235]
I keep getting a download fail from https://fontforge.org/en-US/downloads/windows-dl/
McAfee blocks FontForge download due to virus being detected.
Why does this happen, and how safe is it to override the antivirus and download and install this app? 

![Screenshot](https://user-images.githubusercontent.com/13626863/236179284-cb635e80-5c88-4953-9709-d49900a8177d.jpg)

**Comment by azabraao** [comment]
having same issue now

**Comment by davidxmartins** [comment]
Can anyone tell me if this is safe to download or not? And why am I getting this warning?

**Comment by davidxmartins** [comment]
Not much going on here. I'm doing to look for an alternative.

**Comment by ctrlcctrlv** [comment]
Which antivirus is "the antivirus"?

There's nothing we can do about this as we don't maintain any antivirus software muchless yours so the fact "there's not much going on here" is just evidence no one knows why it's saying that. (And likely the antivirus is proprietary so very few people even can know, and those who can may not be able to say for various reasons.)

Like all free software, it is safe to the extent you trust the maintainers. Closing as inactionable.

**Comment by davidxmartins** [comment]
Wow, nice way to talk to potential users of this software. That alone is enough reason for me to try something else. Besides, if the antivirus is being triggered, that's probably because something doggy is going on with this software. Unbelievable.

**Comment by ctrlcctrlv** [comment]
# How To Uninstall McAfee Antivirus
[![](http://i3.ytimg.com/vi/bKgf5PaBzyg/hqdefault.jpg)](https://www.youtube.com/watch?v=bKgf5PaBzyg)

Remember this old meme? Thanks for making me remember it.

> Unbelievable.

Speaking of old memes—

![image](https://github.com/fontforge/fontforge/assets/838783/09a3ed7e-9bd3-4c43-be08-c9f858c73f07)

**Comment by davidxmartins** [comment]
I see. I'm dealing with 12-year-old. Great. Thanks FontForge for nothing. I'm done here. Great experience.

**Comment by Bronnel721** [comment]
>Besides, if the antivirus is being triggered, that's probably because something dodgy is going on with this software. Unbelievable.

You realize it can also be a false positive too, right? I mean, noting happened to me when I downloaded it.

**Comment by ctrlcctrlv** [comment]
Careful, he may come to the realization that making users feel free community-maintained software is “dodgy” is a powerful force keeping corporate-developed proprietary software going.

Antivirus security ~~theatre~~ software is itself proprietary, so has no reason to work with any free software project.
