### ISSUE TITLE
PS private values are lost after saving WOFF2

### ISSUE THREAD

**Issue by Gush1986** [fontforge/fontforge#5240]
Hello! I try to create WOFF2 font from OTF font, but the PostScript private dictionary is empty after saving.
If I use another utils, PostScript dictionary has original values.
Reproduce:
1) Open font 0000_1.otf from Fonts.zip
2) Check PS private (OTF.jpg from Fonts.zip) - there are values
3) Create WOFF2 font (0000_1_ffout.woff2 from Fonts.zip)
4) Open created font
5) Check PS private (WOFF2.jpg from Fonts.zip) - there are no values

Expected: same PS private values for WOFF2 as for OTF
Actual: empty PS private dictionary

I use FontFotge v20230101 on Windows 10Pro

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround
[Fonts.zip](https://github.com/fontforge/fontforge/files/11528720/Fonts.zip)

**Comment by iorsh** [comment]
FontForge unconditionally uses TTF format to generate WOFF2 files, so PS private values are lost in the process - TTF export doesn't contain them.

It looks like woff2::ConvertTTFToWOFF2() contrary to its name can convert both OTF and TTF files - see https://github.com/google/woff2/blob/master/src/woff2_compress.cc, which works perfectly well with both types (installed and tested on my machine).

In _WriteWOFF2Font() we should use TTF or OTF writer dependent on Bezier curve order.
