### ISSUE TITLE
Display glyphs

### ISSUE THREAD

**Issue by WyxXu** [fontforge/fontforge#5243]
* Provide a general summary of the issue in the **Title** above.  
* Before you open an issue, please check if a similar issue already exists or has been closed before.

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by WyxXu** [comment]
So we can copy / merge easily selected glyph to complete a font from another font?

**Comment by WyxXu** [comment]
Or there already are some ways to do these but I don't know?

**Comment by waykyi** [comment]
Open two font files side by side, then select the glyphs from the first font and COPY
Goto second font and select the spot you want to PASTE and paste it.

**Comment by WyxXu** [comment]
> Open two font files side by side, then select the glyphs from the first font and COPY Goto second font and select the spot you want to PASTE and paste it.

one by one even when copying CJK symbols?

**Comment by waykyi** [comment]
No, select any number of glyphs and paste them. If you want the same positions, then select empty spaces along with glyphs you want to move, then paste in the other font.

**Comment by ctrlcctrlv** [comment]
This doesn't seem to be a bug report.
