### ISSUE TITLE
Translations contain invalid directives, causing gettext >= 0.22 to complain

### ISSUE THREAD

**Issue by heirecka** [fontforge/fontforge#5251]
FontForge fails to build with gettext >= 0.22. According to gettext's maintainer %hs directives are invalid (https://lists.gnu.org/archive/html/bug-gettext/2023-06/msg00071.html). This causes the build to fail like this:

```
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/it.po:2305: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/it.po:5837: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/it.po:6237: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
[ 14%] Generating pt.mo/usr/bin/msgfmt: found 3 fatal errors

[ 14%] Generating ru.mo
cd /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po && /usr/bin/msgfmt --check -o /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po/pt.mo /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/pt.po
cd /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po && /usr/bin/msgfmt --check -o /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po/ru.mo /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/ru.po
make[2]: *** [po/CMakeFiles/pofiles.dir/build.make:120: po/it.mo] Error 1
make[2]: *** Deleting file 'po/it.mo'
make[2]: *** Waiting for unfinished jobs....
[ 15%] Generating tr_TR.mo
cd /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po && /usr/bin/msgfmt --check -o /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po/tr_TR.mo /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/tr_TR.po
[ 16%] Generating uk.mo
[ 16%] Generating vi.mo
[ 16%] Built target appstream
cd /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po && /usr/bin/msgfmt --check -o /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po/uk.mo /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/uk.po
cd /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po && /usr/bin/msgfmt --check -o /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build/po/vi.mo /var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/vi.po
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:294: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 3, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:305: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 4, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:7435: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:19927: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:19935: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:19970: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:19986: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:20459: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:21045: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:21443: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:21772: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:24553: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/fontforge-20230101/po/fr.po:24564: 'msgstr' is not a valid C format string, unlike 'msgid'. Reason: In the directive number 2, the argument size specifier is invalid.
/usr/bin/msgfmt: found 13 fatal errors
make[2]: *** [po/CMakeFiles/pofiles.dir/build.make:112: po/fr.mo] Error 1
make[2]: *** Deleting file 'po/fr.mo'
make[2]: Leaving directory '/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build'
make[1]: *** [CMakeFiles/Makefile2:593: po/CMakeFiles/pofiles.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build'
[ 16%] Built target gunicode
make[1]: Leaving directory '/var/tmp/paludis/build/media-gfx-fontforge-20230101/work/build'
make: *** [Makefile:156: all] Error 2
```

### When reporting a bug/issue:

- [x] FontForge version: 20230101, but I think it's the same for master
- [x] \(optional) Possible solution/fix/workaround: Mark the affected translations as fuzzy, like in this patch:

```
From db6cda639018a7a9b173ece90f7382b84b9381be Mon Sep 17 00:00:00 2001
From: Heiko Becker <heirecka@exherbo.org>
Date: Thu, 22 Jun 2023 22:44:32 +0200
Subject: [PATCH] Mark translations with invalid directives as fuzzy

Works around a build failure with gettext >= 0.22, which is more
strict than earlier versions.
---
 po/fr.po | 26 +++++++++++++-------------
 po/it.po |  6 +++---
 2 files changed, 16 insertions(+), 16 deletions(-)

diff --git a/po/fr.po b/po/fr.po
index 26e446b38..bd4554096 100644
--- a/po/fr.po
+++ b/po/fr.po
@@ -289,7 +289,7 @@ msgstr "chaîne %1$.30s pour %2$.30s"
 #. GT: $2 is the glyph's encoding
 #. GT: $3 is the font name
 #. GT: $4 is the changed flag ('*' for the changed items)
-#, c-format
+#, c-format, fuzzy
 msgid "%1$.80s at %2$d from %3$.90s%4$s"
 msgstr "%1$.80s à %2$d de %3$.90hs%4$s"
 
@@ -300,7 +300,7 @@ msgstr "%1$.80s à %2$d de %3$.90hs%4$s"
 #. GT: $2 is the glyph's encoding
 #. GT: $3 is the pixel size of the bitmap font
 #. GT: $4 is the font name
-#, c-format
+#, c-format, fuzzy
 msgid "%1$.80s at %2$d size %3$d from %4$.80s"
 msgstr "%1$.80s (%2$d) taille %3$d de %4$.80hs"
 
@@ -7427,7 +7427,7 @@ msgstr ""
 "La fonte %1$.40s dans le fichier %2$.40s a été modifiée.\n"
 "Voulez-vous l'enregistrer ?"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "Font %1$.40s in file %2$.40s has been changed.\n"
 "Reverting the file will lose those changes.\n"
@@ -19920,7 +19920,7 @@ msgstr ""
 "Le nom de la fonte commence avec une séquence d'ordre d'octet utf8.  Ceci "
 "n'est pas permis.  %s"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "The fonts %1$.30s and %2$.30s have a different number of glyphs or different "
 "encodings"
@@ -19928,7 +19928,7 @@ msgstr ""
 "Les fontes %1$.30s et %2$.30hs n'ont pas le même nombre de glyphes ou des "
 "codages différents"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "The fonts %1$.30s and %2$.30s use different types of splines (one quadratic, "
 "one cubic)"
@@ -19963,7 +19963,7 @@ msgstr ""
 "Le glyphe %1$.30s dans %2$.30s a à la fois des références et des contours. "
 "Ceci n'est pas supporté dans une fonte MM"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "The glyph %1$.30s in font %2$.30s has a different hint mask on its contours "
 "than in %3$.30s"
@@ -19979,7 +19979,7 @@ msgstr ""
 "Le glyphe %1$.30s de la fonte %2$.30s a un nombre de points (ou de points de "
 "contrôle) différent que dans %3$.30s"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "The glyph %1$.30s in font %2$.30s has a different number of references than "
 "in %3$.30s"
@@ -20454,7 +20454,7 @@ msgstr ""
 "individuellement. Cela peut être utile si vous vouliez\n"
 "conserver les versions quadratiques et cubiques d'une fonte."
 
-#, c-format
+#, c-format, fuzzy
 msgid "The outlines of glyph %2$.30s were not found in the font %1$.60s"
 msgstr ""
 "Le contours du glyphe %2$.30s n'ont pas été trouvés dans la police %1$.60hs"
@@ -21040,7 +21040,7 @@ msgstr ""
 msgid "There is already a subtable with that name, please pick another."
 msgstr "Il y a déjà une sous-table avec ce nom, changez de nom SVP"
 
-#, c-format
+#, c-format, fuzzy
 msgid "There is already an anchor point named %1$.40s in %2$.40s."
 msgstr "Il y a déjà une ancre appelée %1$.40s dans %2$.40hs."
 
@@ -21435,7 +21435,7 @@ msgstr ""
 "Cette fonte ne précise pas de 'unitsPerEm', alors nous assumons que c'est "
 "1000."
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "This font is based on the charset %1$.20s-%2$.20s-%3$d, but the best I've "
 "been able to find is %1$.20s-%2$.20s-%4$d.\n"
@@ -21764,7 +21764,7 @@ msgstr ""
 "Et sur в, г, д, е, ж, л, м, ц, щ, ъ, ђ\n"
 "Et sur toutes les lettres grecques minuscules. Et peut être tout le reste."
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "This kerning pair (%.20s and %.20s) is currently part of a kerning class "
 "with a 0 offset for this combination. Would you like to alter this kerning "
@@ -24544,7 +24544,7 @@ msgstr ""
 "Vous voulez effacer %.30s qui est référencé par un\n"
 "autre glyphe. Êtes-vous sûr(e) de vouloir poursuivre ?"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "You are attempting to paste a reference to %1$s into %2$s.\n"
 "But %1$s does not exist in this font, nor can I find the original character "
@@ -24556,7 +24556,7 @@ msgstr ""
 "glyphe auquel il se référait.\n"
 "Le glyphe ne sera pas copié."
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "You are attempting to paste a reference to %1$s into %2$s.\n"
 "But %1$s does not exist in this font.\n"
diff --git a/po/it.po b/po/it.po
index e13711485..142819db9 100644
--- a/po/it.po
+++ b/po/it.po
@@ -2297,7 +2297,7 @@ msgstr "Riferimento invertito"
 msgid "Flipping"
 msgstr "Ribaltamento"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "Font %1$.40s in file %2$.40s has been changed.\n"
 "Reverting the file will lose those changes.\n"
@@ -5830,7 +5830,7 @@ msgstr ""
 msgid "The font does not contain a glyph named %s."
 msgstr "Questo font non contiene un glifo chiamato %s."
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "The glyph %1$.30s has a different number of contours in font %2$.30s than in "
 "%3$.30s"
@@ -6229,7 +6229,7 @@ msgstr ""
 msgid "This font does not specify font-face\n"
 msgstr "Questo font non specifica il font-face\n"
 
-#, c-format
+#, c-format, fuzzy
 msgid ""
 "This font is based on the charset %1$.20s-%2$.20s-%3$d, but the best I've "
 "been able to find is %1$.20s-%2$.20s-%4$d.\n"
-- 
2.41.0
```

**Comment by juhp** [comment]
@pnemade

**Comment by cyrillic8** [comment]
Wouldn't it be easier to just fix the c-format strings ?

--- a/po/fr.po	2023-06-22 20:08:25.403528173 -0400
+++ b/po/fr.po	2023-06-22 20:23:04.890647958 -0400
@@ -291,7 +291,7 @@
 #. GT: $4 is the changed flag ('*' for the changed items)
 #, c-format
 msgid "%1$.80s at %2$d from %3$.90s%4$s"
-msgstr "%1$.80s à %2$d de %3$.90hs%4$s"
+msgstr "%1$.80s à %2$d de %3$.90s%4$s"
 
 #. GT: This is the title for a window showing a bitmap character
 #. GT: It will look something like:
@@ -302,7 +302,7 @@
 #. GT: $4 is the font name
 #, c-format
 msgid "%1$.80s at %2$d size %3$d from %4$.80s"
-msgstr "%1$.80s (%2$d) taille %3$d de %4$.80hs"
+msgstr "%1$.80s (%2$d) taille %3$d de %4$.80s"
 
 #, c-format
 msgid "%1$s from lookup subtable %2$.50s"
@@ -7433,7 +7433,7 @@
 "Reverting the file will lose those changes.\n"
 "Is that what you want?"
 msgstr ""
-"La fonte %1$.40s dans le fichier %2$.40hs a été modifiée.\n"
+"La fonte %1$.40s dans le fichier %2$.40s a été modifiée.\n"
 "Revenir vous fera perdre toutes les modifications.\n"
 "Voulez vous vraiment revenir ?"
 
@@ -19925,7 +19925,7 @@
 "The fonts %1$.30s and %2$.30s have a different number of glyphs or different "
 "encodings"
 msgstr ""
-"Les fontes %1$.30s et %2$.30hs n'ont pas le même nombre de glyphes ou des "
+"Les fontes %1$.30s et %2$.30s n'ont pas le même nombre de glyphes ou des "
 "codages différents"
 
 #, c-format
@@ -19933,7 +19933,7 @@
 "The fonts %1$.30s and %2$.30s use different types of splines (one quadratic, "
 "one cubic)"
 msgstr ""
-"Les fontes %1$.30s et %2$.30hs utilisent des courbes de Bézier d'ordres "
+"Les fontes %1$.30s et %2$.30s utilisent des courbes de Bézier d'ordres "
 "différents (quadratique et cubique)"
 
 msgid "The generated font won't work with ATM"
@@ -19968,8 +19968,8 @@
 "The glyph %1$.30s in font %2$.30s has a different hint mask on its contours "
 "than in %3$.30s"
 msgstr ""
-"Le glyphe %1$.30s dans la police %2$.30hs a un masque de hints différent que "
-"dans %3$.30hs"
+"Le glyphe %1$.30s dans la police %2$.30s a un masque de hints différent que "
+"dans %3$.30s"
 
 #, c-format
 msgid ""
@@ -19984,8 +19984,8 @@
 "The glyph %1$.30s in font %2$.30s has a different number of references than "
 "in %3$.30s"
 msgstr ""
-"Le glyphe %1$.30s de la fonte %2$.30hs a un nombre de références différent "
-"dans %3$.30hs"
+"Le glyphe %1$.30s de la fonte %2$.30s a un nombre de références différent "
+"dans %3$.30s"
 
 #, c-format
 msgid ""
@@ -20457,7 +20457,7 @@
 #, c-format
 msgid "The outlines of glyph %2$.30s were not found in the font %1$.60s"
 msgstr ""
-"Le contours du glyphe %2$.30s n'ont pas été trouvés dans la police %1$.60hs"
+"Le contours du glyphe %2$.30s n'ont pas été trouvés dans la police %1$.60s"
 
 msgid "The paths that make up this glyph intersect one another"
 msgstr "Les chemins qui composent ce glyphe se coupent les uns les autres"
@@ -21042,7 +21042,7 @@
 
 #, c-format
 msgid "There is already an anchor point named %1$.40s in %2$.40s."
-msgstr "Il y a déjà une ancre appelée %1$.40s dans %2$.40hs."
+msgstr "Il y a déjà une ancre appelée %1$.40s dans %2$.40s."
 
 msgid "There is another glyph in the font with this name"
 msgstr "Il y a un autre glyphe dans la fonte avec ce nom"
@@ -21441,8 +21441,8 @@
 "been able to find is %1$.20s-%2$.20s-%4$d.\n"
 "Shall I use that or let you search?"
 msgstr ""
-"Cette fonte est basée sur le jeu de caractères %1$.20s-%2$.20hs-%3$d, mais "
-"ce que j'ai trouvé de mieux c'est %1$.20hs-%2$.20hs-%4$d.\n"
+"Cette fonte est basée sur le jeu de caractères %1$.20s-%2$.20s-%3$d, mais "
+"ce que j'ai trouvé de mieux c'est %1$.20s-%2$.20s-%4$d.\n"
 "Devrais-je utiliser cette valeur ou préférez vous chercher ?"
 
 msgid ""
@@ -21770,7 +21770,7 @@
 "with a 0 offset for this combination. Would you like to alter this kerning "
 "class entry (or create a kerning pair for just these two glyphs)?"
 msgstr ""
-"Cette paire de crénage (%.20s et %.20hs) est dans une classe de crénage\n"
+"Cette paire de crénage (%.20s et %.20s) est dans une classe de crénage\n"
 "avec un déplacement de 0 pour cette combinaison. Voulez-vous modifier cette "
 "partie\n"
 "de la classe de crénage (ou créer une nouvelle paire rien que pour ces 2 "
@@ -24551,8 +24551,8 @@
 "referred to.\n"
 "It will not be copied."
 msgstr ""
-"Vous essayer de coller une référence vers %1$s dans %2$hs.\n"
-"Mais %1$hs n'existe pas dans cette fonte, et FontForge ne trouve pas le "
+"Vous essayer de coller une référence vers %1$s dans %2$s.\n"
+"Mais %1$s n'existe pas dans cette fonte, et FontForge ne trouve pas le "
 "glyphe auquel il se référait.\n"
 "Le glyphe ne sera pas copié."
 
@@ -24562,8 +24562,8 @@
 "But %1$s does not exist in this font.\n"
 "Would you like to copy the original splines (or delete the reference)?"
 msgstr ""
-"Vous essayer de coller une référence vers %1$s dans %2$hs.\n"
-"Mais %1$hs n'existe pas dans cette fonte.\n"
+"Vous essayer de coller une référence vers %1$s dans %2$s.\n"
+"Mais %1$s n'existe pas dans cette fonte.\n"
 "Voulez vous copier le contour d'origine (ou supprimer la référence)?"
 
 msgid ""


--- a/po/it.po	2023-06-22 20:29:56.762631009 -0400
+++ b/po/it.po	2023-06-22 20:33:37.782584863 -0400
@@ -2303,7 +2303,7 @@
 "Reverting the file will lose those changes.\n"
 "Is that what you want?"
 msgstr ""
-"Il font %1$.40s nel file %2$.40hs è stato modificato.\n"
+"Il font %1$.40s nel file %2$.40s è stato modificato.\n"
 "Ripristinando il file perderai tutte le modifiche.\n"
 "È quello che vuoi fare?"
 
@@ -5835,7 +5835,7 @@
 "The glyph %1$.30s has a different number of contours in font %2$.30s than in "
 "%3$.30s"
 msgstr ""
-"Il glifo %1$.30s ha un diverso numero di contorni nel font %2$.30hs rispetto "
+"Il glifo %1$.30s ha un diverso numero di contorni nel font %2$.30s rispetto "
 "a %3$.30s"
 
 #, c-format
@@ -6235,8 +6235,8 @@
 "been able to find is %1$.20s-%2$.20s-%4$d.\n"
 "Shall I use that or let you search?"
 msgstr ""
-"Questo font è basato sulla codifica di caratteri %1$.20s-%2$.20hs-%3$d, ma "
-"il migliore che io abbia trovato è %1$.20hs-%2$.20hs-%4$d.\n"
+"Questo font è basato sulla codifica di caratteri %1$.20s-%2$.20s-%3$d, ma "
+"il migliore che io abbia trovato è %1$.20s-%2$.20s-%4$d.\n"
 "Devo usare questo valore o preferisci cercare tu stesso?"
 
 msgid ""

**Comment by heirecka** [comment]
> Wouldn't it be easier to just fix the c-format strings ?

Of course, I just don't have a clue about translations and possible peculiarities of the languages involved.

**Comment by cyrillic8** [comment]
The language involved is C, and those parts should not be modified by the translation.

**Comment by ctrlcctrlv** [comment]
Isn't this a bug in `gettext`?

**Comment by cyrillic8** [comment]
It looks more like a translation software bug, because the parts that are in english should be translated, and the parts that are in C should remain untouched.

**Comment by ctrlcctrlv** [comment]
I see. I don't think we can add `fuzzy`. Maybe though we can get rid of `%hs` if it is indeed invalid—I've no reason to doubt Bruno's word on that, but it did work for ≈20 years.

**Comment by skef** [comment]
Fixed by po update.

**Comment by chenrui333** [comment]
@skef any chance cutting a new release for this? Thanks!

**Comment by skef** [comment]
So, I've never done a release. And while there are some aspects of it that are pretty standard, our windows build is a little weird. 

@jtanx stuck his head in a month or two ago, though. Any chance you might be able to cut a release or pass off the relevant info/credentials?

**Comment by jtanx** [comment]
Yeah I can help with a release, but tbh all the binaries should be coming from ci now.

I don't have time to do much atm but if you tag me on anything I'll probably respond

**Comment by skef** [comment]
> Yeah I can help with a release, but tbh all the binaries should be coming from ci now.

OK, that's good to know.

I only have occasional eyes over here, trying to keep things from getting stuck and approving PRs. If we can get the ci stuff all working again and you fill me in on where and now to put things to do a release I can work with @iorsh to make decisions about what PRs need to go in before. Or you can have ongoing involvement - whichever you want.

**Comment by skef** [comment]
Oh, I have the impression that the "resources" weren't quite synced up on the last Windows release, so I'll take a look at what the CI is currently building and it's off I'll file an issue.

**Comment by iorsh** [comment]
I also need to check https://github.com/fontforge/fontforge/issues/5336, will try to get a windows machine for that.
