### ISSUE TITLE
I can't open or delete the installer

### ISSUE THREAD

**Issue by SskyBreaker76** [fontforge/fontforge#5253]
I downloaded the FontForge installer from the website to my E:\ but it won't let me open it. When I try to run as administrator I get a dialogue stating "Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item", and when I try to delete the file I get "File Access Denied", so I click Continue (with admin privilege) and it just tells me I need permission from myself to make changes to the file.

I am currently using Windows 11 22H2

Edit: Copying the file to my C:\ and trying to run causes the installer to simply vanish

**Comment by ctrlcctrlv** [comment]
Ask on a Windows help forum as this is clearly an OS issue/not FontForge related beyond its installer being the file you downloaded which triggered the preexisting buggy behavior; the only comment I can offer is that Windows is known to have very poor handling of r/w locks on files, I am not sure if this still the case in Windows 11 … 2022…H? (Service Pack? :joy:) 2, but I remember in the past if any program had an open file handle to a file Windows would not let you delete it and only a reboot would sort the issue.
