### ISSUE TITLE
Paste referenced glyphs causing error - Windows

### ISSUE THREAD

**Issue by georgeraraujo** [fontforge/fontforge#5281]
- [x] The FontForge version and the operating system you're using

FontForge version: 20230101
OS: Windows 10 Pro

- [X] The behavior you expect to see, and the actual behavior

The behavior I expect to see: I expect the glyphs to be copied successfully, and the generated font to contain the glyphs.
The actual behavior: The copy runs into errors, and the generated font has a single, wrong, glyph.

- [X] Steps to reproduce the behavior 

I started FontForge and clicked "New", "Encoding" > "Reencode" > "ISO 10646-1 (Unicode, Full)". I then saved the file: "File" > "Save" > `MusicSymbolsForMyEbook.sfd`.

Then I clicked "File" > "Open" > `sfd/FreeSerif.sfd` from [GNU FreeFont](http://ftp.gnu.org/gnu/freefont/freefont-src-20120503.tar.gz). I click "View" > "Goto" > "Musical Symbols", selected all relevant glyphs (`01D100` to `01D1DD`), and clicked "Edit" > "Copy".

![image](https://github.com/fontforge/fontforge/assets/4930759/1973b748-683c-44d6-aeb9-1600390a290d)

I went back to my new `MusicSymbolsForMyEbook.sfd` file and clicked "View" > "Goto" > "Musical Symbols", then "Edit" > "Paste".

![image](https://github.com/fontforge/fontforge/assets/4930759/2e0f1dbe-9619-4938-99da-5c6cd2d5f339)

I got an error and clicked "Yes to All":

![image](https://github.com/fontforge/fontforge/assets/4930759/6e31b632-0425-4a14-b12f-14402325e9da)

I got another error and clicked "Ok" several times until all glyphs were pasted:

![image](https://github.com/fontforge/fontforge/assets/4930759/34f4d3d3-3411-4b95-b86d-2801a6b8e77b)

I clicked "File" > "Save" `MusicSymbolsForMyEbook.sfd` to save my file, then clicked "File" > "Generate fonts..." to generate a TTF font. The generated TTF font has a single glyph (screenshot from nexusfont):

![image](https://github.com/fontforge/fontforge/assets/4930759/286170af-8ee1-49f7-983e-8f44ebeb7d46)

I noticed #584 looks similar, but remains open.

I also found [an old thread](https://sourceforge.net/p/fontforge/mailman/fontforge-users/thread/CAHAQwh0AqyA%2B37Zwxh5Xnisjk9XHm5inWuK_uZEmnpo0U6yCvw%40mail.gmail.com/#msg35410885) at SourceForge, but couldn't figure out how to apply it to my case.

**Comment by ctrlcctrlv** [comment]
Sorry to ask, but can you please switch interface language to English before reporting bugs? I can't tell which strings those are in the source code easily.

**Comment by georgeraraujo** [comment]
> Sorry to ask, but can you please switch interface language to English before reporting bugs? I can't tell which strings those are in the source code easily.

I have updated the images to show the message boxes in English.

**Comment by iorsh** [comment]
I was unable to reproduce this issue on Linux (Ubuntu 22).
![image](https://github.com/fontforge/fontforge/assets/3698866/476dd9fb-a755-446e-9598-67ff9c903732)
Could it be that the font file is ok, but the Windows Charmap is puzzled by missing Latin characters? Did you try to install it and actually use in e.g. Word (by selecting characters manually)?

**Comment by iorsh** [comment]
The errors you mentioned are expected for partial copy, I don't think anything could be done about them (except for maybe suppressing a bunch of identical errors). Try to also copy the ASCII range (U+0000 - U+00FF) just to make Windows happy.

**Comment by georgeraraujo** [comment]
> The errors you mentioned are expected for partial copy, I don't think anything could be done about them (except for maybe suppressing a bunch of identical errors). Try to also copy the ASCII range (U+0000 - U+00FF) just to make Windows happy.

I understand. I ended up using fontTools's `pyftsubset`:

```
pyftsubset FreeSerif.ttf -–unicodes=U+1D100-1D1DD --passthrough-tables --output-file=MusicSymbolsForMyEbook.ttf
```

Thanks anyway.
