### ISSUE TITLE
Fontforge freezes when opening a SVG-Font file (contours, not OTF/SVG)

### ISSUE THREAD

**Issue by ideogram** [fontforge/fontforge#5308]
- [x] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### Screenshot:
![image](https://github.com/fontforge/fontforge/assets/4469494/c0f5ee87-bb53-40f3-8f99-08854eca8633)

### Versions
OS: Mac OS Sonoma 14.0. 
Fontforge 20230101

### Behavior - expected

When opening a svg font file (black-and-white, 'contours', not a OTF/SVG font file), I would expect FontForge to open the file like it does with OTF and TTF files.

### Behavior - actual

The UI freezes, shows the infamous Mac beach ball, and the system only becomes responsive by switching to another application and choosing Force Quit... from the Apple system meu.

### Steps to reproduce:

1. Open any SVG font in FontForge. ( For example, you _might_ go to https://glyphter.com/ , drag 1 symbol into their canvas and download the resulting  ZIP file. Extract it, and choose the Glyphter.svg This is no endorsement. But it is hard to find a source of SVG font files online)
2. That's it. On my computer, it will freeze FontForge now.

I inspected the file from Glyphter, and it is indeed a SVG font file. (With a `<font>`, `<font-face>` tag, and `<glyph>` tags).

( I do not use Glyphter, I only use it here to provide a SVG file that will cause the issue. Instead, I use SVG font files to generate and change fonts using Python. SVG is easily readable and changeable.)

This behavior only appeared after I upgraded my OS to Sonoma. But of course, that might be coincidence. 
___
Edit: When opening a font from my system in FontForge on Windows, the problem did not occor.

**Comment by ctrlcctrlv** [comment]
Given the edit, most likely this duplicates #5112.

**Comment by ideogram** [comment]
No, it is not a duplicate of #5112 (“Apple: Developer could not be verified…” ) because I was able to use the GUI for other tasks in FontForge. The problem with reading SVG-fonts presents itself both through the GUI and when using FontForge from the CLI.

Strangely, an update of Sonoma, 14.1.1 seems to fix it.

That makes the problem "not reproducible" and, indeed, a candidate for closing this issue.

Thanks for looking into it.

**Comment by Monkey-D-Luffy-joyboy** [comment]
Hi legends, 
![Screenshot 2024-09-25](https://github.com/user-attachments/assets/9e2dc610-128a-45a4-9690-67f3820d3e19)
**Versions:** Mac OS Sequoia 15.0
Fontforge 20230101
Behaviour - expected
When opening a .svg font file (black-and-white, 'contours', not an OTF/SVG font file), I would expect FontForge to open the file like it does with OTF and TTF files.
Behavior - actual
The UI freezes and shows the infamous Mac beach ball, and the system only becomes responsive by switching to another application and choosing Force Quit from the Apple system menu. Or sometimes, FF crashes when I try to load any .svg files.

Steps to reproduce:
Open any .svg font in FontForge. ( I was watching this video to learn font making and software https://www.youtube.com/watch?v=l6BD5I_hmqo )

Please have your advice.
