### ISSUE TITLE
Prevent point type changes when dragging splines

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#533]
If you have curve points and you wish to adjust the spline between them directly, their type changes from curve points (where the previous and next CPs have the same angle) to corner points. A point's type should only change when the user directly changes it, not indirectly when they are seeking to just adjust the spline a little. 

Here is a video: http://youtu.be/D4MBxn5vHHI

**Comment by skef** [comment]
The feature was implemented as described (I didn't even know FF did this), and the case for further configuration possibilities seems ambiguous at best. Closing.
