### ISSUE TITLE
UFO: Show and edit point names

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#537]
Needed - ability to name / label points with unique names.
UI suggestion 1 - select point, right-click drop down menu gives option of 'add label'.
UI suggestion 2 - visibility of labels can be toggled on / off (global). Default should be on.
Important - these labels need to be compatible with point labels that UFOs can have stored in xml tags (see Simon Egli for details / examples).
PS - Robofont can do all this!

**Comment by davelab6** [comment]
@adrientetar  @pathumego is this done to your satisfaction?

**Comment by adrientetar** [comment]
I have not used point naming so far in my work so I can’t really tell.

**Comment by pathumego** [comment]
I haven't used it regularly. But it works. And I think expected behaviour is implemented. Its compatible on UFO xml tags as well.

My suggestion would be to merge it into `Point Info `. In connection with #2257   :)
