### ISSUE TITLE
CI fails for MINGW - fails to download potrace

### ISSUE THREAD

**Issue by iorsh** [fontforge/fontforge#5378]
Looks like CI is [dead again](https://github.com/fontforge/fontforge/actions/runs/8032360306/job/21941680505?pr=5358) - the Windows build depends on potrace binaries, which are downloaded from https://potrace.sourceforge.net/download/1.16/potrace-1.16.win64.tar.gz, but now are missing. 

It looks like potrace is now a standard package in MinGW - see https://packages.msys2.org/package/mingw-w64-x86_64-potrace. Would it be feasible to just install it with `pacman` instead of the custom installation which is done now?

@jtanx, @skef

**Comment by skef** [comment]
@jtanx knows a lot more about the windows stuff than I do. I'll wait to see if he can offer some insight before looking into this.

**Comment by iorsh** [comment]
Apparently this was a transient failure, but the question is still valid.

**Comment by jtanx** [comment]
https://github.com/fontforge/fontforgebuilds/commit/b6f86ba79faf6950848da931b8d90150c8034ae6
