### ISSUE TITLE
[QUESTION]The side bearing number is not an integer, it changes automatically 

### ISSUE THREAD

**Issue by WaningJupiter** [fontforge/fontforge#5387]
I'm using the [FontForge 2023-01-01] in Mac. 
First, in the metrics window, the side-bearings are float number, the comma is automatically placed after the first number : if you want to tape `15`, the comma will automatically added after the number`1`, and I have to delete the comma to write `15` . 

Second, as you can see in the video, the side bearing number changed out of my control, like any change at left-side bearing will influence the right-side bearing, well they should be independent. 

Any ideas ? Thanks!

https://github.com/fontforge/fontforge/assets/14837045/9b10f71b-c0a6-451e-86d4-2ab2d8127ee9

**Comment by iorsh** [comment]
I think this behavior is correct, even if misleading. The glyph width (top number) must be integer, and it's the sum of left bearing, right bearing and the width of the bounding box.

At some point the width is 649, and the bounding box is probably 620.6, so the sum of the bearings is 28.4. Regardless of any other changes the fractional 0.4 part will always be there.
