### ISSUE TITLE
Can FF Internal scripting have access to system level Read/Write

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5420]
I am trying to access svg files saved in my Windows system. The thing I am trying to do is to see if any svg files exist in the given path, if it is, then using a loop, I want to import them into assigned glyph spots until all svg files are imported. I could not find that ability in FF internal scripting or am I overlooked? Thanks for any help and direction.

**Comment by ChiefMikeK** [comment]
It is best to use a shell(external) script or cmd line input to search for and pass the `.../path/to/*.svg` file(s) on to fontForge 
And as I DONT USE WINDOWS :neckbeard: it's better to search/ask on reddit, chatGPT or ?

**Comment by waykyi** [comment]
I use Windows 11 and I can solve it by hard-coded the path in the script and svg names in the array. Thanks

**Comment by waykyi** [comment]
Thanks
