### ISSUE TITLE
Which internal FF functions to create ligatures???

### ISSUE THREAD

**Issue by waykyi** [fontforge/fontforge#5428]
I was able to create a Ligature lookup table with lookup subtable "myLigature-1"
Then selected two glyphs to make a ligature using the BuildComposite function.
But that did get me nowhere!!!
Could anyone of FF developers point me to the right function to call here??? Thanks

Here is my code:
AddLookup("myLigature", "gsub_ligature", 0, [["liga",[["latn",["dflt"]]]]] )
AddLookupSubtable("myLigature", "myLigatures-1")
Select( 0x50 )
SelectMore( 0x8f )
BuildComposite()

**Comment by waykyi** [comment]
Found answer at github

**Comment by KamilLanda** [comment]
And can you add the link to solution?
