### ISSUE TITLE
More crowdin problems

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#5438]
https://github.com/fontforge/fontforge/actions/runs/9640850262/job/26585357775

> ERROR
> code: 2
> message: Version 1.0 of the Crowdin API has been deprecated and removed
> Error: Process completed with exit code 1.

**Comment by iorsh** [comment]
The crowdin error seems less cryptic now. @skef, could you please check whether the API token is v1 or v2? Maybe .crowdin.yml would need an update too.

**Comment by iorsh** [comment]
Looks like it was fixed by https://github.com/fontforge/fontforge/commit/705433c295326df4a16e5491df917d0b48427242
