### ISSUE TITLE
I want to use Explorer to view files

### ISSUE THREAD

**Issue by Bin-qx** [fontforge/fontforge#5449]
* The original viewer you guys are trying to make us use is very difficult to use, please change it.
This is the only disappointing thing about this free software
### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The FontForge version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [x] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by skef** [comment]
Closed as dup of #3987
