### ISSUE TITLE
Support for OpenType Font Variations

### ISSUE THREAD

**Issue by timkrief** [fontforge/fontforge#5452]
Hi I'm trying to edit a dynamic font to add some missing characters. I searched for information about OpenType Font Variations / Dynamic Fonts support in font forge and I did not found any discussion about it, but maybe I used the wrong keywords or I searched in the wrong places. I would like to know if Font Forge currently supports this kind of fonts, if yes is there any documentation about it? And if no, is it planned to support it in the future?

Thank you for your work and have a nice day.

**Comment by skef** [comment]
FontForge does not support Variable Fonts and is not likely to in the future. Some designers use FontForge as a tool to make source files for such fonts and builds them using external tools, but that doesn't address your use case of editing an existing variable font, which is a very complex problem.

**Comment by davelab6** [comment]
I would contact the font project maintainer and find out if they can accept
glyph drawing contributions to expand the glyph set and then take care of
integrating them into their sources and build system for you as a
collaboration.

**Comment by timkrief** [comment]
> I would contact the font project maintainer and find out if they can accept glyph drawing contributions to expand the glyph set and then take care of integrating them into their sources and build system for you as a collaboration.

Thank you, yes I also did that https://github.com/arrowtype/shantell-sans/issues/142
