### ISSUE TITLE
Import Dialog: Format is not Remembered

### ISSUE THREAD

**Issue by baskerville** [fontforge/fontforge#551]
If I have previously selected _SVG_ as format in the import dialog, then on the next import, although _SVG_ is still selected, I can't see any SVG files unless I reselect _SVG_ in the drop down format menu.

**Comment by eleriaqueen** [comment]
I want to report that this Issue is still present in 31 Jul 2017 version downloaded from official website.

**Comment by ctrlcctrlv** [comment]
If you're going to be importing many SVG, I recommend you guys use a Python script and not the GUI. :-)

**Comment by skef** [comment]
I've run into this a few times too. It's a general problem -- it also happens when trying to import glifs, for example. I'll take a look later today.

**Comment by skef** [comment]
Hmm -- I know I've experienced this many times myself, but just trying the most straightforward things I can't come up with a reproducible case. @eleriaqueen are you aware of a sequence of steps (possibly including particular sample files) that reliably demonstrates the problem?

**Comment by eleriaqueen** [comment]
File -> Import -> (Go to a folder with SVG files) -> select SVG as "format" -> Import
Then
File -> Import -> (SVG is still selected as "Format" but no files are shown I have to re-select SVG for files to appear)
