### ISSUE TITLE
Pipx install for Netexec and running nxc

### ISSUE THREAD

**Issue by yabbing** [fontforge/fontforge#5518]
I am having two different issues one when I try to run the netexec install with pipx it is saying that pip failed to build arc4 and bitstruct. (screenshot below)

My other issue is I guess I have the command installed with apt install netexec but I am getting this error that I will have a screenshot below and I do not know what is going on with it and  I am hoping someone can help me out get this tool installed.

![nxc issue](https://github.com/user-attachments/assets/512b1a3a-579a-46b5-b037-4d6765bd3eeb)
![pipx issue](https://github.com/user-attachments/assets/812170a9-9663-4a35-92d3-53a5c2f72875)

**Comment by iorsh** [comment]
Thank you for opening the issue, but are you sure it's related to FontForge?
