### ISSUE TITLE
recurring "file too complex" error

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#555]
![Screen Shot 2013-04-20 at 08 42 21](https://f.cloud.github.com/assets/1130355/405352/13d06c78-a9d1-11e2-97b0-2d674fb7d90e.png)

Keep getting this error window pop up, when i copy contours from one glyph slot to another. Especially likely to occur if i 'select all' in a glyph window, copy and then attempt to paste in another glyph window. The paste fails. Very annoying.
Anyone else experienced this? I am seeing it on many fonts, so i don't think the issue is my outlines :)
OSX 10.8.3 build based on source from git with hash:a60ef489895c0927c005270cee83b5274bf3fd6a

**Comment by skef** [comment]
Old bug without needed info. Will reopen if needed.

**Comment by skef** [comment]
(After a bit of google searching:) No offense meant.
