### ISSUE TITLE
Make Graphicore's iPython (and PyGTK) ship on Mac

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#773]
``` sh
brew update; 
brew uninstall fontforge; 
brew install python;
sudo easy_install pip;
sudo pip install IPython;  
brew install gettext libpng jpeg libtiff giflib cairo pango libspiro czmq fontconfig automake libtool pkg-config glib pango;
brew install fontforge --with-x --HEAD --debug;
fontforge
```

Then go to `File, Execute Script (Crtl+.)` and enter,

``` py
from IPython import embed
embed()
```

This should work, but instead I get an error about importing md5:

![screen shot 2013-10-19 at 02 17 58](https://f.cloud.github.com/assets/261579/1365378/548f51ba-385c-11e3-8bc7-a3fe54f728a7.png)

Once this works, then https://github.com/davelab6/graphicore-FontForge-Python-Scripts can work with pygtk included :)

**Comment by davelab6** [comment]
@monkeyiq sadly this is no longer in the bundle I downloaded from fuuko...

**Comment by skef** [comment]
Graphicore was removed due to aging code problems and (ironically) gdk compatibility issues.
