### ISSUE TITLE
Add 'Merge to Line' function

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#799]
_In discussion for #404 (not needed to read it for understanding this issue) this feature request came about._

If you have 3 corner points forming 2 line segments, and you merge the central point, the resulting line segment becomes a curve. Sometimes users want to merge to a straight line. 
- [x] Add a "Merge to Line" function, that works like Merge, but just makes a line between the 2 end points of the selection.
- [x] Add a Char View, Edit menu item, "Merge to Line" 
- [x] Add a hotkey for Char View, Edit menu item, "Merge to Line", Ctrl+Shft+M

**Comment by skef** [comment]
It's been "merge to line" a long time. If that should change it can be part of some systemic future revision.
