### ISSUE TITLE
define a codingstyle

### ISSUE THREAD

**Issue by lynxis** [fontforge/fontforge#830]
The project should define a codingstyle. It doesn't matter which one, but it must easy to understand and improve readability of the code. At the moment there are lot of different coding styles in the code.

To start a discussion about the needs of this project, I suggest the linux [kernel coding style](https://www.kernel.org/doc/Documentation/CodingStyle)

**Comment by skef** [comment]
An email on February 19 2021 had this conclusion:

> On 2/19/21 6:33 AM, Frank Trampe wrote:
> > That works for me.
> >
> > On Fri, Feb 19, 2021, 04:21 T J <jtanx@outlook.com> wrote:
> >
> > If we can agree on one, then sure. I mean all my added files follow the same code style (e.g. ggdkdraw.c), I even committed the astyle command I ran in one of the commit messages:
> >
> > `astyle --style=java --pad-oper --unpad-paren --pad-header --indent=spaces --add-brackets --align-pointer=name`
> >
> > It tends to follow the general style of FF code, except no mixed tabs/spaces and no undented returns.

So, basically, mostly keep doing what has been done except where it comes to indentation, which should be done with spaces and without the shallow return statements. 

I've tried to codify this in a brief code style wiki here: https://github.com/fontforge/fontforge/wiki/Code-Style . Feel free to modify, extend, or delete as needed. Closing this.
