### ISSUE TITLE
Linux, Critical Pango Failures (Editted)

### ISSUE THREAD

**Issue by Earnestly** [fontforge/fontforge#848]
When starting `fontforge` with `pango 1.36` I get recieve:

```
(process:5247): Pango-CRITICAL **: pango_layout_set_text: assertion 'length == 0 || text != NULL' failed
```

And my fonts within FontForge itself look like this: http://a.pomf.se/8Xn2.png
# Edit

My mistake.  I assumed this was using the X RESOURCE MANAGER such as `xrdb -load <foo>` and not its own resources file.  When adding my selected options there my font is loaded and everything works well.

---

If I then create an `Xresources` file and `xrdb -load` it with the following contents (as suggested in the FAQ):

```
Gdraw.ScreenWidthInches: 30
Gdraw.ScreenWidthCentimeters: 60
```

Which when large enough actually removes the Pango-CRITICALs.  I also can’t seem to set my preferred UI font—`Lato`—via `fontforge.FontView.FontFamily: Lato`

The UI is still too large and it seems very difficult to display nice UI fonts throughout without a lot of configuration.

**Comment by skef** [comment]
This was a long time and many FF/pango versions ago. Reopen if necessary.
