### ISSUE TITLE
Improve 'close collab server' dialog

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#857]
When going to Collaborate menu, 'close local server', you see this,

![screen shot 2013-10-19 at 02 37 12](https://f.cloud.github.com/assets/261579/1365407/fd73884e-385e-11e3-94de-d48fe64a1f29.png)

but there can be several local servers. So instead this should,
- [ ] list them (probably reusing code from the beacon dialog but only with $font)
- [ ] with checkboxes to close them, and 
- [ ] have the checkboxes ticked by default.

When quitting FontForge, you may or may not want to kill the fontforge-internal-collab-server processes running. 

Therefore, on quit(), 
- [ ] check if any local servers are running (probably reuse code that dis/enables the 'close collab server' menu item)
- [ ] list them (probably reusing code from the beacon dialog but only with $font)
- [ ] with checkboxes to close them, and 
- [ ] have the checkboxes ticked by default.

**Comment by skef** [comment]
collab was removed.
