### ISSUE TITLE
Make Real Time Collaboration & Web Fonts Preview Work Out Of The Box on Mac

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#878]
Back in March I demo'd a new and to me very exciting, unique, feature of FontForge that I've developed with the AMAZING Dr Ben Martin (@monkeyiq) who lives down in Australia: real time "Google Docs"-like collaboration in FontForge, including real time web font previewing.

Here is a 10 minute presentation I gave with Ben about it at the Libre Graphics Meeting in Madrid at that time:

http://www.youtube.com/watch?v=xvSWVuauFVI

The slides for that are here:

https://speakerdeck.com/davelab6/lgm-2013-fonts-of-doom

This was initially developed in this repo: https://github.com/davelab6/fontforge-collab-nodejs

The documentation for the feature sprint in Madrid is here: 

http://titanpad.com/fontforge-interactivos13

And here's two 1 minute videos showing the feature working with real users:

http://www.youtube.com/watch?v=rMR7H8IWlTI

http://www.youtube.com/watch?v=BqwTim6gMHA

In Madrid we did a sprint on the real time collaboration mode, and the live web fonts preview feature, which is yet to ship 'out of the box'. So this issue is to track shipping it to all FontForge users :) 

This is JUST STARTING to be available as standard in in the Mac bundle of FontForge. The first version with this working can be downloaded here:

http://fuuko.libferris.com/osx/packages/201311/03_0415/FontForge.app.zip

(If you haven't installed it before, the full instructions are at http://fontforge.github.io/en-US/downloads/mac/ :-)

Then you must install the latest FontForge using [Homebrew](http://brew.sh):

``` sh
$ brew -v install fontforge --HEAD --with-cairo --with-czmq --with-gif --with-x --with-libspiro --with-pango --enable-pyextension;
```

Then follow this screencast to get it going - and remember to use Firefox as the browser:

http://youtu.be/xZY08SnS9oo

Please add comments to this issues with your feature suggestions or if you couldn't get it running :)

**Comment by skef** [comment]
collab was removed.
