### ISSUE TITLE
Ensure all aspects of Font Info work in collab mode

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#888]
Here is a list of the parts of the font info dialog that are the most important to work over collab, ranked by me @davelab6 in order of priority to users:

Layers, Lookups, Mac features, and OS/2 are likely to be the most troublesome; most are simple lists of key/value pairs. I've marked those with a \* and it probably makes sense to just run through them first because they'll be fast to do, then get stuck into the 3 big ones.
- [ ] Layers
- [ ] PS Names
- [ ] General
- [ ] OS/2
- [ ] TTF Names *
- [ ] Lookups
- [ ] Styleset Names *
- [ ] PS Private *
- [ ] Grid Fitting *
- [ ] WOFF *
- [ ] Mac *
- [ ] Mac features
- [ ] Comment *
- [ ] FONTLOG *
- [ ] Mark Classes *
- [ ] Mark Sets *
- [ ] Size *
- [ ] PS UID *
- [ ] TeX *

@monkeyiq made an initial attempt at this, but the undo system is Char based, there is no real support for Font level undo: https://github.com/fontforge/fontforge/pull/885

**Comment by skef** [comment]
collab was removed.
