### ISSUE TITLE
Add AppData.xml 

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#892]
http://blogs.gnome.org/hughsie/2013/08/29/gnome-software-center-and-you/

**Comment by divayprakash** [comment]
@davelab6 I'd like to take this up.

**Comment by JoesCat** [comment]
Can you check if this applies?
https://github.com/fontforge/fontforge/tree/master/desktop

**Comment by davelab6** [comment]
@divayprakash awesome! please do!! :)

**Comment by divayprakash** [comment]
@JoesCat That definitely applies, however there are a few changes :
- `<application>.....</application>` tags are replaced by `<component type="desktop">.....</component>`
-  `<id type="desktop">` is now simply `<id>`
- `<license>` tag needs to be replaced by `<metadata_license>` and `<project_license>`
- We need to add `<name>` and `<summary>` tags
- Screenshot code needs to be changed to 
```
<screenshot>
    <image>IMAGE_REF</image>
    <caption>IMAGE_CAPTION</caption>
</screenshot>
```
- `<updatecontact>` is changed to `<update_contact>`

**Comment by divayprakash** [comment]
@JoesCat @davelab6 Should I make the changes to that same file or create another?

**Comment by davelab6** [comment]
Same file, with a pull request, I guess?

**Comment by JoesCat** [comment]
On June 14, 2016 03:47:35 PM Dave Crossland wrote:
> Same file, with a pull request, I guess?

Git seems to recognize if you move a file, so if you need to move it, do 
that first, then modify the file. (two git updates). I have not been keeping 
tabs on what's happening, but check the file history for the files in that 
directory. I think Redhat may also be affected, so try to cover all or as 
many distros as you can with your improvements.

You also may want to check out what Debian is doing too so that you can 
merge what they are doing into the improvements (see issue #2732, and 
please give credit where credit is due if you pull in their mods - if you 
have trouble with reassigning-credit, one of us can take care of that, as 
it's not really as easy as click-n-change (I think)).

Thanks,
Looking forward to your help/improvements.

**Comment by divayprakash** [comment]
@JoesCat I've done some more research on this, and the `appdata.xml` file specification is more-or-less common across distros. I'm incorporating the following specs -
- https://wiki.debian.org/AppStream/Guidelines
- https://wiki.gnome.org/Initiatives/GnomeGoals/AppDataGnomeSoftware
- https://fedoraproject.org/wiki/Packaging:AppData
- https://people.freedesktop.org/~hughsient/appdata/

It seems to me that they're all drawing from one common source here -
- https://www.freedesktop.org/software/appstream/docs/chap-DistroData.html - we need to look at all the sub-sections here
- https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html - mostly sub-section 1 suffices, though we could check sub-section 3 also

Please take a look and let me know what you think!

**Comment by divayprakash** [comment]
Also, I am a complete newb at this, so I'm not able to understand #2732 at all.

**Comment by JoesCat** [comment]
On June 15, 2016 03:54:15 AM Divay Prakash wrote:
> Also, I am a complete newb at this, so I'm not able to understand #2732
> at all.

No worries about being a newbie - everyone learns to walk before they run.

to answer the question, you can follow along (below).

There is currently a lot of momentum updating and upgrading Debian at the 
moment, and I thought there was something affecting the files you are looking 
at right now.

When I looked at the (Debian) changes made, I thought I saw something 
affecting the desktop directory (in the expanded list here - about 3 days 
ago now):
http://anonscm.debian.org/cgit/pkg-fonts/fontforge.git/log/
you'll see one line: "Drop fontforge.menu file in favor of .desktop file"

...but when I follow the link, the changes are actually more in terms of 
converting from the 2012 version in favour of the Desktop files you are 
looking at now, so, it's not really affecting your files.

Looking at the (Debian) directory at the moment, here:
http://anonscm.debian.org/cgit/pkg-fonts/fontforge.git/tree/desktop
seems to confirm no changes that affect you, so there is nothing to pull-in 
from downstream. In summary - Go for it.

I'll be interested in reading the references you indicate, but seems you 
already have this well figured-out - please go ahead. :-)

**Comment by copyninja** [comment]
I got a request to install appdata.xml on [Debian](https://bugs.debian.org/857589) but I do not know how to make the build system of fontforge to install this file. Normally having some dependency like having xdg-utils enables install of .desktop file. Is there similar dependency to get it installed? or I should manually copy out the file during packaging?. If this thread seems irrelevant I will move it to separate issue.

**Comment by JoesCat** [comment]
Hi Vasudev,
This is probably the right place to ask (this thread/subject).
I'm occuppied with other things until late May, but first thought is it 
needs to be agreable across the different operating systems.

Large scale projects like GIMP, VLC, can probably have some good ideas on 
how to tackle this question across multiple OSes.
File m4/fontforge_with.m4 may give you an idea of how to pass variables 
from configure into make

**Comment by ajay004** [comment]
i am good in c and c++ language where should i start contributing

**Comment by frank-trampe** [comment]
@ajay004, we have a lot of open bugs in the tracker. Look for crashes and see whether you can fix them.

**Comment by copyninja** [comment]
> This is probably the right place to ask (this thread/subject). I'm occuppied with other things until late May, but first thought is it needs to be agreable across the different operating systems.

Is there any updates?

>  Large scale projects like GIMP, VLC, can probably have some good ideas on how to tackle this question across multiple OSes. File m4/fontforge_with.m4 may give you an idea of how to pass variables from configure into make

There is no specific option to make fontforge build system to enable installing this file so I guess I need to manually copy out the file while packaging.

**Comment by muelli** [comment]
> but I do not know how to make the build system of fontforge to install this file

I'm having a similar problem.
My short analysis, without understanding most of the tooling involved, revealed that the `DIST_COMMON` key in `desktop/Makefile.in` includes the icons and the `.desktop` file, but not the appdata file.  Although a quick experiment with this change wasn't successful for me.  Maybe someone with more autotools knowledge can chime in.

**Comment by JoesCat** [comment]
@muelli - The file you want to focus on is desktop/Makefile.am
Makefile.am will be regenerated when you run autoreconf and automake, or ./bootstrap for fresh installs.
googling some of the other terms will give hints on github, stackoverflow and other resources on te web.

**Comment by muelli** [comment]
There is an appdata file now, no?
Although it seems a bit awkward. After installation, the resulting appdata file does not have a `name` tag (and a summary tag is missing, too. A "translation" tag would be nice, but is not mandatory). That's at least what appstream-glib validate complains about. That's currently a problem for the distribution via flatpak, because it needs to ship the patched appdata file.

**Comment by JoesCat** [comment]
Hi @muelli,
As this is the first time fontforge desktop files are published, it is expected to have a couple bumps and hiccups.

There is an appdata (older standard not to be used anymore), and also a metainfo (newer standard) mentioned in #3368. Metainfo has summary info. appdata, being the older standard, is probably better left closer to follow the older ver1 standards (example older computers plus also used by appimage).
