### ISSUE TITLE
Add Ctl-Alt modifier to toggle Pointer tool's 'Interpolate Control Points on Motion'

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#893]
If you double click the Pointer tool, you find a VERY important option, 'Interpolate Control Points on Motion' which is more widely known in the type design community as 'Nudge':

![x11001](https://f.cloud.github.com/assets/261579/1457898/f0bee1f4-434c-11e3-8271-e4e2bde7f7e4.png)

(I made short video explaining it for designers here, http://www.youtube.com/watch?v=q2mNOTo9lqQ)
- [ ] fix the way this works on curve points, so they dont turn into fake corner points with BCPs at different angles but still a curve point type, but keep the BCPs with the same angle always. Youtube: http://youtu.be/QKGOInbrDtU
- [ ] add a Cmd modifier to the Pointer tool to toggle this on/off when that key is pressed. So you can double click the pointer tool to set your default mode, on or off, and use the modifier to activate the opposite mode.

Here is the same feature in another popular editor:

![](http://www.glyphsapp.com/content/images/blog-screenshots/4-nudge.gif)

**Comment by madig** [comment]
Can I change the mapping? Ctrl+Alt triggers window manager stuff...

**Comment by davelab6** [comment]
There was an effort to make hotkeys remappable during operation, not sure
where that went
