### ISSUE TITLE
Windows: Close Xming when FontForge quits

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#909]
- [ ] Close Xming when FontForge quits

**Comment by eladkarako** [comment]
Was it ever attempted to be fixed?
`FontForge-mingw-w64-i686-bbe2d0-x11-r2 from 31/07/17` with `fontforge.bat -lang "ff" -c "Open(...); MergeFonts(...); Generate(...);` . 
This still opens `"...\FontForge\\bin\VcXsrv\vcxsrv.exe"  :11 -multiwindow -clipboard -silent-dup-error` and keeps it running way after script's end.

**Comment by jtanx** [comment]
As mentioned before, this has never been an issue for me. At the end of that batch script, you should see a call to:

```bat
"%FF%\bin\VcXsrv_util.exe" -close
```

This should close vcxsrv as long as no other instances of fontforge are running (well actually so long as nothing is connected to vcxsrv).

**Comment by eladkarako** [comment]
oh yes [I can see it now](https://github.com/fontforge/fontforgebuilds/blob/master/patches/VcXsrv_util.c#L52-L53), it works well.
Thanks!
