### ISSUE TITLE
Windows: Make Real Time Collaboration & Web Fonts Preview Work Out Of The Box

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#911]
Related to #878 is doing the same for windows. At the moment, starting a collab server instantly crashes: I run FF, Collab, Start Session, press OK, and it crashes, windows says that fontforge-collab-server.exe has had a problem and needs to close.

![ie11](https://f.cloud.github.com/assets/261579/1462496/b553da0c-44fa-11e3-8950-76d880f673ca.png)

I am then in the server session, and when I try to move a point, I can not do anything because when I do something it is instantly undone, and then FF asks if I want to try reconnecting. 

![ie11b](https://f.cloud.github.com/assets/261579/1462497/b692f5f6-44fa-11e3-82ef-940ab018204a.png)

After a crash I loaded the debug mode and I had the told Xming open, which leads me to #909, and it wouldnt run, but when I closed Xming and retried, it similarly wouldn't run, leading me to #910

**Comment by skef** [comment]
collab was removed.
