### ISSUE TITLE
Cycle through prev/next glyphs inside multi-glyphs charview

### ISSUE THREAD

**Issue by vernnobile** [fontforge/fontforge#917]
When in a glyph edit window, and viewing a string of text, e.g. `noaon`, the user should be able to click select a glyph in that string, making it editable, e.g. the `a`, and then, with the `ctl-alt-]` and `ctl-alt-[` cycle through the font's character set replacing the `a` with the previous/next glyph in the font. 

E.g today using the `ctl-]` on the `a` in `/no[a]on` would open a new tab in this glyph window showing `b`. When this issue is closed, using the `ctl-alt-]` on the `a` in `/no[a]on` would change the string in the glyph window to `/no[b]on` and pressing it again changes it to `/no[c]on` then `/no[d]on` and so on.

**Comment by skef** [comment]
No evidence of outstanding issue: Can reopen if needed.
