### ISSUE TITLE
WOFF generated by FF have wrong 'head' checksum

### ISSUE THREAD

**Issue by coolwanglu** [fontforge/fontforge#926]
Open <https://dl.dropboxusercontent.com/u/475186/ff_bug/demo.html> with different browsers:

OS: Win 8.1

`IE 11`
![capture1](https://f.cloud.github.com/assets/734614/1491333/4d25e9de-47ac-11e3-9bc9-355bf3cbe245.PNG)

`Firefox 25`
![capture2](https://f.cloud.github.com/assets/734614/1491348/84590206-47ac-11e3-9eb9-f25c227ee4a1.PNG)

`Chrome 30`
![capture3](https://f.cloud.github.com/assets/734614/1491359/a40c029c-47ac-11e3-9efc-94607572cc6c.PNG)

[f7.woff](https://dl.dropboxusercontent.com/u/475186/ff_bug/f7.woff) and [f9.woff](https://dl.dropboxusercontent.com/u/475186/ff_bug/f9.woff) are respectively used in the two lines, which are generated from [f7.pfa](https://dl.dropboxusercontent.com/u/475186/ff_bug/f7.pfa) and [f9.pfa](https://dl.dropboxusercontent.com/u/475186/ff_bug/f9.pfa) with FontForge respectively. Note that both fonts contain only a subset of characters.

It can be observed that `f7.woff` is accepted by all three browsers, while `f9.woff` works only on IE. Firefox shows the following message regarding `f9.woff`

![capture4](https://f.cloud.github.com/assets/734614/1491381/06073ea8-47ad-11e3-9196-77b83a7ba6ce.PNG)

I heard that Chrome is using the same validator as Firefox, but I'm not sure.

I wonder if it is a bug of Fontforge, or bugs of the validator used in Firefox and chrome, or maybe something wrong in `f9.pfa` ?

**Comment by jimmywarting** [comment]
+1

**Comment by fred-wang** [comment]
Comparing the table directory of the ttf output generated by FontForge and the one constructed by calcHeadChecksum in validator.py, the only difference seems to be the offset of tables:

    fontforge sfnt output

    tag | checkSum | offset |length    
    CFF , 1370159785, 2116, 3754, 
    FFTM, 1992083500, 5904, 28, 
    GDEF, 2555936, 5872, 30, 
    OS/2, 1502503344, 288, 96, 
    cmap, 909254778, 1256, 826, 
    head, 95901027, 188, 54, 
    hhea, 88605330, 244, 36, 
    hmtx, 851312128, 5932, 104, 
    maxp, 1724416, 280, 6, 
    name, 2855594605, 384, 870, 
    post, 4285969253, 2084, 32, 
    
    validator.py calcHeadChecksum output
    
    tag | checkSum | offset |length    
    ('CFF ', 1370159785, 188, 3754)
    ('FFTM', 1992083500, 3944, 28)
    ('GDEF', 2555936, 3972, 30)
    ('OS/2', 1502503344, 4004, 96)
    ('cmap', 909254778, 4100, 826)
    ('head', 95901027, 4928, 54)
    ('hhea', 88605330, 4984, 36)
    ('hmtx', 851312128, 5020, 104)
    ('maxp', 1724416, 5124, 6)
    ('name', 2855594605, 5132, 870)
    ('post', 4285969253, 6004, 32)

I have a checkSumAdjustment branch that fixes this issue by modifying the offsets (so that the tables will be in the same order as the directory entries) and then recalculate the checkSumAdjustment. However, the WOFF spec does not seem to put any restriction on the actual table order (only on the directory entries), so I'm not sure it is the correct way to fix that.

**Comment by adrientetar** [comment]
It has to be better than what's being done currently for sure.

**Comment by fred-wang** [comment]
Trying again, the data I gave for f9.pfa in "fontforge sfnt output" are wrong, I'm not sure how I got them. The offsets are actually in the correct order, but there is at least "extra" data between the directory entry and the first table. Given that we'll need to fix the offset anyway, I guess it is safe to reorder the tables to match the order in the table directory. I'll prepare a pull request with some tests...

**Comment by fred-wang** [comment]
@adrientetar I've opened https://github.com/fontforge/fontforge/pull/2520

**Comment by fred-wang** [comment]
I've opened a new pull request #2524. Instead of recalculating the checkSumAdjustment based on the new order of tables in the WOFF file, I've just modified the code to preserve the table order. That's actually what sfnt2woff does.

**Comment by fred-wang** [comment]
I believe this issue can be closed now that #2524 is merged.
